### ISSUE TITLE
What is the meaning of the option 'chimSegmentReadGapMax'

### ISSUE THREAD

**Issue by ZijieJin** [alexdobin/STAR#1007]
In the manual, it defines the maximum gap in the read sequence between chimeric segments. What is the 'gap' stand for? Could you show me an example? Thanks

**Comment by alexdobin** [comment]
Hi Zijie,

the two chimeric segments may not cover the entire length of the read sequence. The maximum number of reads bases allowed in between the segments is defined by ```--chimSegmentReadGapMax```

Cheers
Alex

**Comment by ZijieJin** [comment]
> Hi Zijie,
> 
> the two chimeric segments may not cover the entire length of the read sequence. The maximum number of reads bases allowed in between the segments is defined by `--chimSegmentReadGapMax`
> 
> Cheers
> Alex

So, Is the cigar information in the sam file like 30M1000N70M an example of gap?

**Comment by alexdobin** [comment]
Hi Zijie,

the N in the CIGAR is the gap in the genome for normal - non-chimeric alignment. The "chimeric gap" we were talking about is the gap in the read sequence between two chimeric segments. In a normal alignment, it would correspond to an insertion.

Cheers
Alex

**Comment by ZijieJin** [comment]
> Hi Zijie,
> 
> the N in the CIGAR is the gap in the genome for normal - non-chimeric alignment. The "chimeric gap" we were talking about is the gap in the read sequence between two chimeric segments. In a normal alignment, it would correspond to an insertion.
> 
> Cheers
> Alex

I see, thanks!
