### ISSUE TITLE
FATAL PARAMETER ERROR:

### ISSUE THREAD

**Issue by sekhwal** [alexdobin/STAR#1014]
I am making Index file with the following command, however, I am getting the following error. I have a large size of RAM in my computer. MemAvailable:   126221336 kB

./STAR --runMode genomeGenerate --genomeDir /DataAnalysis/test-star/ --genomeFastaFiles /DataAnalysis/test-star/Homo_sapiens.GRCh38.dna.toplevel.fa --sjdbGTFfile /DataAnalysis//test-star/Homo_sapiens.GRCh38.100.gtf

EXITING because of FATAL PARAMETER ERROR: limitGenomeGenerateRAM=31000000000is too small for your genome
SOLUTION: please specify --limitGenomeGenerateRAM not less than 168632691637 and make that much RAM available 

Aug 27 10:46:57 ...... FATAL ERROR, exiting

**Comment by alexdobin** [comment]
Hi @sekhwal 

toplevel fasta file contains alternative loci and patches, which bloat the genome sequence and are typically not needed for RNA-seq analyses. Please use the "primary_assembly" file, e.g.:
[ftp://ftp.ensembl.org/pub/release-101/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz]

Cheers
Alex

**Comment by sekhwal** [comment]
Thank you for letting me know..
