### ISSUE TITLE
Ratio of fragments spanning SJ > 100%

### ISSUE THREAD

**Issue by jmartin77777** [alexdobin/STAR#1023]
I recently mapped 12 samples worth of Illumina RNAseq data against a reference and STAR is reporting > 100% ratios of 'fragSpanningSJ/mappedFrag' for 11 of the 12.   The values range from 110% - 125%.   These were mapped against a nematode reference for which I'd expect the intron size to be somewhat larger than the fragment size, which star is reporting at ~270bp.    These are 150mer paired end reads for each fragment, so I was wondering if STAR may be counting a single fragment as mapping to the same SJ > 1 time because each end is mapping over it.  Is that possible?     I am not entirely comfortable with that explanation though because I've used STAR to map many other RNAseq samples vs this worm and others are I never noticed this ration being so much above 100% before.   I have seen 101% or 102% in rare cases, but in this case I'm seeing a median value of 123%

Does anyone have any ideas what may be happening here?   Every other metric I've checked looks fine.

**Comment by alexdobin** [comment]
Hi @jmartin77777 

I am not sure what you mean by fragSpanningSJ/mappedFrag - how is this calculated?
If you are looking at the Log.final.out file, then indeed every splice crossed will be counted independently for each mate, so the splices overlapped by 2 mates will be double-counted.

If you want to avoid double counting, you can sum the read counts from the SJ.out.tab file. However, if a read (both mates) overlaps two or more junctions, it will get counted twice, so you may still get more spliced counts than reads. Also, SJ.out.tab is filtered against poorly supported junctions.

Cheers
Alex

**Comment by jmartin77777** [comment]
I can check the SJ.out.tab file, but the thing that is confusing me is that I have mapped other samples prep'd using the same library kit & methodology (ie. same fragment size & so on), against this same reference, and I have never seen that ratio being 120%.   So I was wondering if there was some obscure problem that could occur that I could QC for.   I probably need to check the production notes and see if anything odd happened during the library prep.   Thanks for the reply & information

**Comment by jmartin77777** [comment]
I can check the SJ.out.tab file, but the thing that is confusing me is that I have mapped other samples prep'd using the same library kit & methodology (ie. same fragment size & so on), against this same reference, and I have never seen that ratio being 120%.   So I was wondering if there was some obscure problem that could occur that I could QC for.   I probably need to check the production notes and see if anything odd happened during the library prep.   Thanks for the reply & information

**Comment by jmartin77777** [comment]
I can check the SJ.out.tab file, but the thing that is confusing me is that I have mapped other samples prep'd using the same library kit & methodology (ie. same fragment size & so on), against this same reference, and I have never seen that ratio being 120%.   So I was wondering if there was some obscure problem that could occur that I could QC for.   I probably need to check the production notes and see if anything odd happened during the library prep.   Thanks for the reply & information

**Comment by jmartin77777** [comment]
I can check the SJ.out.tab file, but the thing that is confusing me is that I have mapped other samples prep'd using the same library kit & methodology (ie. same fragment size & so on), against this same reference, and I have never seen that ratio being 120%.   So I was wondering if there was some obscure problem that could occur that I could QC for.   I probably need to check the production notes and see if anything odd happened during the library prep.   Thanks for the reply & information
