### ISSUE TITLE
STAR Database compatibility

### ISSUE THREAD

**Issue by max1c** [alexdobin/STAR#1026]
Hi,

I have recently ran into an issue with the indexes for the latest STAR version. It appears as if STAR is now using a different index format. My indexes have been built a long time ago so I am wondering if there is a compatibility list by version anywhere available? Also, are there any simple test cases to test this?

Thank you,

Maxim

**Comment by alexdobin** [comment]
Hi Maxim,

to find out which genome your version of STAR is compatible with, you can run
```STAR --help | grep versionGenome```
This gives the earliest version compatibility, e.g. for the 2.7.5c, the genomes generated by STAR 2.7.4a and later versions are good.

Cheers
Alex

**Comment by max1c** [comment]
Thank you for this valuable information. Appreciate all your hard work on STAR!
