### ISSUE TITLE
STAR Genome Index KILLED 

### ISSUE THREAD

**Issue by darrenboey** [alexdobin/STAR#1029]
Hi,

I am new to bioinformatics and STAR, and have been trying to create my human genome index but it always gets killed after the "generating Suffix Array index" step. My server has 32gb of ram and while running STAR I have killed all other screens to ensure as little things are running in the background as possible. 

The code I am using is:
STAR --runThreadN 4 --runMode genomeGenerate --genomeDir /data/GenomeDirect --genomeFastaFiles /data/GenomeDirect/GCF_000001405.39_GRCh38.p13_genomic.fa --sjdbGTFfile /data/GenomeDirect/GCF_000001405.39_GRCh38.p13_genomic.gtf --sjdbOverhang 100

Is there something that I am doing wrong? Or is it just a case of insufficient ram?

Thank you.

![free -m](https://user-images.githubusercontent.com/9208480/93594520-940f9700-f9e8-11ea-9456-5e50e4cf33a7.png)

**Comment by darrenboey** [comment]
Hi,

This is the log out file that I got after the error.


[Log.out.txt](https://github.com/alexdobin/STAR/files/5246623/Log.out.txt)

**Comment by alexdobin** [comment]
Hi @darrenboey 

I think you are very close to 32GB RAM limit.
These parameters might help:
--genomeChrBinNbits 16 --genomeSAindexNbases 12 --limitSjdbInsertNsj 300000

If these parameters do not help, you would need to use --genomeSAsparseD 2.

Cheers
Alex

**Comment by fjps** [comment]
Dear @alexdobin,

Hope this finds you well. with regard to this issue, I am having a similar one. Can you please give an advice?

I am trying to generate genome indexes for zea mays, working on a cluster with a limit of 32 gb per node and up to 32 threads.  I use the recommendations that you provide to @darrenboey , but it is still taking like forever (more than 12 h). Hoping to hear from you.

bests,
Francisco

[star_index.txt](https://github.com/alexdobin/STAR/files/6130853/star_index.txt)


Please find attached my Log.out file and the shell script that I am using.
[Log_out.txt](https://github.com/alexdobin/STAR/files/6130775/Log_out.txt)

**Comment by alexdobin** [comment]
Hi Francisco,

32GB should be sufficient to generate the genome.
There is nothing suspicious in the Log.out file.
I would try to request more threads: ```--runThreadN 8``` or even 16.

Cheers
Alex

**Comment by fjps** [comment]
Hi @alexdobin, 

Many thanks for the support, really helped. In addition to your suggestions I used: --limitGenomeGenerateRAM               28000000000, and everything works fine. Again many thanks for support.

best,
Francisco
