### ISSUE TITLE
terminate called after throwing an instance of 'std::bad_alloc'

### ISSUE THREAD

**Issue by TakashiKoyama** [alexdobin/STAR#103]
Hi,

I have problem with genomeGenerate. I am using STAR_2.5.0c_modified.
I started genomeGenerate as below.
```
$ STAR --runMode genomeGenerate --genomeDir ./ --genomeFastaFiles platanus_k35_gapClosed.substituted.fixfasta.fasta --runThreadN 20 --limitGenomeGenerateRAM 64000000000
```
and got error.
```
Jan 18 23:17:24 ..... Started STAR run
Jan 18 23:17:24 ... Starting to generate Genome files
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```
I attach my Log.out.
[Log.out.gz](https://github.com/alexdobin/STAR/files/94519/Log.out.gz)

Thank you for your kind helps!

Takashi

**Comment by TakashiKoyama** [comment]
Hi,

I tried genomeGenerate with human reference genome (hg38.fa) and STAR seems to work fine.
Hence, my reference genome file should be the cause.

The genomeGenerate has any limitations?
For your information, my genome is De Novo assembled and highly fragmented. It contains 366405 headers and the length of each scaffold vary from 100 to 1154345 bp.

I would appreciate any suggestions. Thank you.

Takashi

**Comment by alexdobin** [comment]
Hi Takashi,

If you are using a genome with a large > 5,000 number of references (chrosomes/scaffolds), you may need to reduce the --{genomeChrBinNbits to reduce RAM consumption. The following scaling is recommended: --genomeChrBinNbits} = min(18, log2(GenomeLength/NumberOfReferences)). For example, for 3~gigaBase genome with 100,000 chromosomes/scaffolds, this is equal to 15.

Cheers
Alex

**Comment by TakashiKoyama** [comment]
Hi Alex,

It works! Thank you!

Takashi

**Comment by PersistentlyHungry** [comment]
A bit of a noob question, but how does one check the number of references in the genome file?

**Comment by alexdobin** [comment]
Hi Chen,

for a fasta file:
$ grep "^>" Genome.fasta | wc -l

Cheers
Alex

**Comment by rspreafico-vir** [comment]
Not sure if possible, but I wonder whether certain STAR parameters could be auto-tweaked. If there is a defined rule for tweaking a parameter such as `--genomeChrBinNbits` above, why not implementing that rule as default, rather than a fixed parameter? Same goes for other parameters such as `-sjdbOverhang` which could be tweaked automatically by STAR upon reading in a few thousand reads.

**Comment by alexdobin** [comment]
Hi Roberto,

I am reluctant to implement this scaling as a default option for a couple of reasons:
1. Such scaling may introduce small changes in the mapping results, so either the users will have to change parameters for the new runs or re-run old runs.
2. In some cases, the simple scaling is just the guide, and the best parameters for the data and use cases have to be selected manually.

For now, I am planning to add warning when these parameters are not scaled properly.
At some point next year, I plan a major overhaul of STAR algorithm, and at that point I will also change the default behavior and include some of the auto-scaling.

Cheers
Alex

**Comment by rspreafico-vir** [comment]
Hi Alex,

gotcha! And thanks for taking the time to address this question. Your strategy makes total sense. 

One residual question I might have then, given the concern is mainly towards ensuring reproducible results across STAR versions, is whether such sensible defaults could be implemented only when a dedicated flag is passed, e.g. `--sensibleDefaults`. This would ensure that, without that tag, alignments with newer STAR versions still provide the same output as earlier STAR version. If the tag is provided though, any unset parameter could get such sensible defaults. In the case that both the sensible defaults flag is passed, as well as one of the affected parameters, then this latter would take priority over the sensible defaults. Such sensible defaults could include anything from `--genomeChrBinNbits`/`-sjdbOverhang` to configuring STAR with ENCODE defaults for a bunch of parameters. And in case a single `--sensibleDefaults` flag wouldn't work, then a flag that allows to pick from different default sets could help, e.g. `--defaultSet ENCODE`, `--defaultSet basic`, etc.

Thanks for considering, and if it doesn't work, I will be happy to wait next year for the major overhaul that you anticipated. :-)

Cheers
Roberto

**Comment by aguilar-gomez** [comment]
I cannot generate my reference. My fasta file is huge and the genome is very fragmented. I am running:
STAR --runMode genomeGenerate --genomeDir STARindex --genomeFastaFiles ./reference.fa --runThreadN 10 --genomeChrBinNbits 18
5569926969/7182879=775
--genomeChrBinNbits} = min(18, log2(GenomeLength/NumberOfReferences))
my reference is 5.6 Gb in 718K scaffolds
I get the same error people mention:
Dec 16 23:22:12 ..... started STAR run
Dec 16 23:22:12 ... starting to generate Genome files
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

**Comment by alexdobin** [comment]
Hi @aguilar-gomez

please try to run it with 
``
--genomeChrBinNbits 10 
``
(which is ~log2(775) ).
This number of scaffolds is too large and may slowdown mapping significantly.

Cheers
Alex

**Comment by jianguozhouzunyimedicaluniversity** [comment]
````
STAR --runMode genomeGenerate --genomeDir ~/reference/index/STAR/STAR_index/ --genomeFastaFiles ~/reference/genome/hg38/Homo_sapiens.GRCh38.dna.toplevel.fa --sjdbGTFfile ~/reference/genome/hg38/Homo_sapiens.GRCh38.99.chr_patch_hapl_scaff.gtf --sjdbOverhang 149
````

Apr 28 18:40:57 ..... started STAR run
Apr 28 18:40:57 ... starting to generate Genome files
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted

**Comment by atalgarni53860** [comment]
> Hi Takashi,
> 
> If you are using a genome with a large > 5,000 number of references (chrosomes/scaffolds), you may need to reduce the --{genomeChrBinNbits to reduce RAM consumption. The following scaling is recommended: --genomeChrBinNbits} = min(18, log2(GenomeLength/NumberOfReferences)). For example, for 3~gigaBase genome with 100,000 chromosomes/scaffolds, this is equal to

I had the same issue. thanks alot

**Comment by parichitran** [comment]
Hi,

I have problem with genomeGenerate. I am using STAR_2.7.10a.
I started genomeGenerate as below.
$ STAR --runThreadN 10 --runMode genomeGenerate /index  --genomeFastaFiles  /Homo_sapiens.GRCh38.dna.toplevel.fa --sjdbGTFfile /Homo_sapiens.GRCh38.gtf --genomeSAsparseD 3  --genomeSAindexNbases 12  --limitGenomeGenerateRAM 168632691637 --genomeChrBinNbits 6

and i got the following error
... starting to generate Genome files
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

Ram:64gb

Thanks in advance

**Comment by alexdobin** [comment]
Hi @Parichitran 

I think the issue is that you are using the "toplevel" FASTA, which contains alternative haplotypes and patches, and thus blows up the genome size. 
If you are using ENSEMBL, than the right FASTA is "primary_assembly":
http://ftp.ensembl.org/pub/current_fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
Or you can use "PRI"mary FASTA and GTF from GENCODE:
https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_39/GRCh38.primary_assembly.genome.fa.gz
https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_39/gencode.v39.primary_assembly.annotation.gtf.gz

Cheers
Alex

**Comment by WanpengWang-Elias** [comment]
> 

Hi,
I have the same problem when i use STAR to generate a mouse index. I am sure that i use the "primary_assembly" fasta and GTF which are PRI downloaded from GENCODE. And the code are as follows

$ STAR --runThreadN 10 --runMode genomeGenerate --genomeDir Starindex --genomeFastaFiles /share/home/bioinfo/training/wangwanpeng/RNAseq_11/00ref/GRCm39.primary_assembly.genome.fa --sjdbGTFfile /share/home/bioinfo/training/wangwanpeng/RNAseq_11/00ref/gencode.vM31.primary_assembly.annotation.gtf --limitGenomeGenerateRAM 104454248032 --genomeChrBinNbits 14 --genomeSAsparseD 3 --sjdbOverhang 149

and the error appears as follows:

ov 08 15:28:39 ... starting to sort Suffix Array. This may take a long time...
Nov 08 15:28:53 ... sorting Suffix Array chunks and saving them to disk...
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

I also checked the number of reference in fasta file:

$ grep "^>" *fa | wc -l
61

Thanks
sincerely

**Comment by WanpengWang-Elias** [comment]
Thanks for reply @alexdobin 
I used shell as follows to call memory:
srun --nodes=1 --ntasks-per-node=4 --mem 100 --time=10:00:00 --pty bash -I 

and the total RAM of the server is about 192G.
