### ISSUE TITLE
Release 2.7.6a

### ISSUE THREAD

**Issue by alexdobin** [alexdobin/STAR#1033]
Dear STAR users,

[2.7.6a](https://github.com/alexdobin/STAR/releases/tag/2.7.6a) is officially released.
Its major new feature is the BAM output for chimeric multimappers, implemented by @suhrig - see #802 for more details.
Thanks a lot, Sebastian, for an excellent contribution!

Please post any issues/questions specific to this release in this thread.

Cheers
Alex

**Comment by shwetagodbole** [comment]
Hi , 
I am trying to install STAR on my university cluster. However towards the end of compilation I get these warnings: 
Parameters_openReadsFiles.cpp: In member function ‘void Parameters::openReadsFiles()’:
Parameters_openReadsFiles.cpp:25:20: warning: variable ‘imate’ might be clobbered by ‘longjmp’ or ‘vfork’ [-Wclobbered]
          for (uint imate=0;imate<readFilesNames.size();imate++) {//open readIn files
They had also appeared earlier and even after setting the path I would get the error STAR command not found. I am not sure if it has been complied or not. 
Any help will be much appreciated. 

Thanks in advance.

**Comment by paulmenzel** [comment]
@shwetagodbole, how is that related to this release? Are these warnings new? Also, please use Markdown to mark up code blocks, so it’s better readable.

**Comment by shwetagodbole** [comment]
@paulmenzel Sorry about not including the markdown. 
And yes, I was trying to install the new release and I get that line at the end of make STAR. 
`Parameters_openReadsFiles.cpp: In member function ‘void Parameters::openReadsFiles()’:
Parameters_openReadsFiles.cpp:25:20: warning: variable ‘imate’ might be clobbered by ‘longjmp’ or ‘vfork’ [-Wclobbered]
          for (uint imate=0;imate<readFilesNames.size();imate++) {//open readIn files`
Then I also tried it with other releases and it still gave me the same error towards the end of compilation.

**Comment by alexdobin** [comment]
Hi @shwetagodbole 

this is normal - it's a compilation warning, but the resulting executable should be all right.
This is the only compilation warning I could not fix, unfortunately.

Cheers
Alex

**Comment by shwetagodbole** [comment]
@alexdobin Thank you for your response. alright :)
