### ISSUE TITLE
Reads only mapping when a partial genome is given

### ISSUE THREAD

**Issue by kbattenb** [alexdobin/STAR#1039]
Dear STAR developers,

I have a situation that I cannot figure out and was hoping that any of you could give me some advice.

I have a scRNAseq data that I am working on cleaning up.
So far, I have adapter/quality trimmed the R2 file (15-151bp).
To further clean this dataset, I am working on removing rRNA and tRNA from this R2 file.

I first made a subset of this R2 file highly enriched with rRNA as a test and ran the following script.
```
STAR --runMode genomeGenerate --genomeDir TEST --genomeFastaFiles GENOME.fas --sjdbGTFfile Non-Coding.gtf --sjdbOverhang 150 --limitGenomeGenerateRAM 50000000000 --outFileNamePrefix TEST
STAR --runMode alignReads --readFilesCommand zcat --outBAMcompression 9 --quantMode TranscriptomeSAM --outFilterMultimapNmax 100 --genomeDir TEST --readFilesIn R2.fq.gz --outFileNamePrefix TEST
```
My understanding was that any read that was present in the Transcriptome.bam is potentially rRNA and I would remove this.

This however is resulting in ca. 90% unmapped (too short).
What is perplexing me is that when I change the genome and annotation file to only consist of a single chromosome the mapping rate (uniquely and multi-mapped combined) becomes nearly 90%.

Could you give me advice on what the cause of this might be and how I should change the parameters to avoid such low mapping rate while referencing the entire genome?

Thank you.

Kai Battenberg

**Comment by alexdobin** [comment]
Hi Kai,

do you have only rRNA and tRNA sequences in GENOME.fas?
I am also not sure what do you mean by "file to only consist of a single chromosome".

In general, I recommend against mapping to a subset of a genome. If you feel that rRNA sequences are not represented well in the genome assembly, you can simply add them to the assembly as separate "chromosomes". 

Cheers
Alex

**Comment by kbattenb** [comment]
Hi Alex,

Sorry for the confusion.

GENOME.fas file originally contained the whole genome i.e. the nuclear (Chr0, Chr1...), plastidic (ChrC), mitochondrial (ChrM).
Likewise, the Non-Coding.gtf contained all predicted rRNA and tRNA for all these sequences. This resulted in very low mapping rate.

So, for the second round I used only one chromosome (Chr6) and its corresponding annotation.
This gave me ca. 90% mapping rate.

I do know that this chromosome has a sequence that at least 95% of the reads map to.
I checked this by running BLASTN with the read as the query and the chromosome as the subject, and the aligned segment of the chromosome does have an annotation on the .gtf file.

This is why I am wondering why I am getting a low mapping rate when I use the entire genome as a reference while getting a high mapping rate using only a single chromosome.

Does this clarify?
Thank you for the help.

Kai Battenberg

**Comment by alexdobin** [comment]
Hi Kai:

thanks, I understand the issue now. Could you please post the Log.final.out files for both the full genome and Chr6 runs?

Cheers
Alex

**Comment by kbattenb** [comment]
Hi Alex,

Yes here they are!
Any suggestion would be greatly appreciated.

Full Genome:
                                 Started job on |	Sep 16 17:30:03
                             Started mapping on |	Sep 16 17:30:08
                                    Finished on |	Sep 16 17:45:31
       Mapping speed, Million of reads per hour |	506.90

                          Number of input reads |	129962857
                      Average input read length |	122
                                    UNIQUE READS:
                   Uniquely mapped reads number |	14061
                        Uniquely mapped reads % |	0.01%
                          Average mapped length |	137.57
                       Number of splices: Total |	166
            Number of splices: Annotated (sjdb) |	34
                       Number of splices: GT/AG |	53
                       Number of splices: GC/AG |	1
                       Number of splices: AT/AC |	1
               Number of splices: Non-canonical |	111
                      Mismatch rate per base, % |	5.36%
                         Deletion rate per base |	0.50%
                        Deletion average length |	1.04
                        Insertion rate per base |	0.01%
                       Insertion average length |	1.00
                             MULTI-MAPPING READS:
        Number of reads mapped to multiple loci |	13201
             % of reads mapped to multiple loci |	0.01%
        Number of reads mapped to too many loci |	5931833
             % of reads mapped to too many loci |	4.56%
                                  UNMAPPED READS:
  Number of reads unmapped: too many mismatches |	0
       % of reads unmapped: too many mismatches |	0.00%
            Number of reads unmapped: too short |	85974666
                 % of reads unmapped: too short |	66.15%
                Number of reads unmapped: other |	38029096
                     % of reads unmapped: other |	29.26%
                                  CHIMERIC READS:
                       Number of chimeric reads |	0
                            % of chimeric reads |	0.00%

Chr6:
                                 Started job on |	Sep 28 08:15:31
                             Started mapping on |	Sep 28 08:15:32
                                    Finished on |	Sep 28 08:56:53
       Mapping speed, Million of reads per hour |	188.58

                          Number of input reads |	129962857
                      Average input read length |	122
                                    UNIQUE READS:
                   Uniquely mapped reads number |	5519232
                        Uniquely mapped reads % |	4.25%
                          Average mapped length |	140.41
                       Number of splices: Total |	372807
            Number of splices: Annotated (sjdb) |	0
                       Number of splices: GT/AG |	352371
                       Number of splices: GC/AG |	3717
                       Number of splices: AT/AC |	28
               Number of splices: Non-canonical |	16691
                      Mismatch rate per base, % |	3.65%
                         Deletion rate per base |	0.01%
                        Deletion average length |	1.25
                        Insertion rate per base |	0.00%
                       Insertion average length |	1.54
                             MULTI-MAPPING READS:
        Number of reads mapped to multiple loci |	124181275
             % of reads mapped to multiple loci |	95.55%
        Number of reads mapped to too many loci |	227
             % of reads mapped to too many loci |	0.00%
                                  UNMAPPED READS:
  Number of reads unmapped: too many mismatches |	0
       % of reads unmapped: too many mismatches |	0.00%
            Number of reads unmapped: too short |	261607
                 % of reads unmapped: too short |	0.20%
                Number of reads unmapped: other |	516
                     % of reads unmapped: other |	0.00%
                                  CHIMERIC READS:
                       Number of chimeric reads |	0
                            % of chimeric reads |	0.00%

**Comment by alexdobin** [comment]
Hi Kai,

thanks!
It seems that most of the reads map to a large number of loci when you map only to one chromosome.
When you map to the full genome, the number of potential mapping loci increases, which prevents any mapping.
You would need to tweak a bunch of parameters, for starters:

1. Prohibit splicing for now:
--alignIntronMax 1 --alignMatesGapMax 1
2. Increase --winAnchorMultimapNmax to 100, 200, 500

Please post the Log.final.out for these cases, and we will see if further tweaking is needed.

Cheers
Alex

**Comment by kbattenb** [comment]
Hi Alex,

It worked!!
Here are the outputs.
In addition to 100, 200, 500, I also ran 50 on --winAnchorMultimapNmax since that is the default.

--winAnchorMultimapNmax 50
```
                                 Started job on |	Sep 30 08:41:01
                             Started mapping on |	Sep 30 08:41:06
                                    Finished on |	Sep 30 09:05:16
       Mapping speed, Million of reads per hour |	322.67

                          Number of input reads |	129962857
                      Average input read length |	122
                                    UNIQUE READS:
                   Uniquely mapped reads number |	1578958
                        Uniquely mapped reads % |	1.21%
                          Average mapped length |	126.02
                       Number of splices: Total |	0
            Number of splices: Annotated (sjdb) |	0
                       Number of splices: GT/AG |	0
                       Number of splices: GC/AG |	0
                       Number of splices: AT/AC |	0
               Number of splices: Non-canonical |	0
                      Mismatch rate per base, % |	5.10%
                         Deletion rate per base |	0.06%
                        Deletion average length |	1.00
                        Insertion rate per base |	0.03%
                       Insertion average length |	1.05
                             MULTI-MAPPING READS:
        Number of reads mapped to multiple loci |	4125403
             % of reads mapped to multiple loci |	3.17%
        Number of reads mapped to too many loci |	9
             % of reads mapped to too many loci |	0.00%
                                  UNMAPPED READS:
  Number of reads unmapped: too many mismatches |	0
       % of reads unmapped: too many mismatches |	0.00%
            Number of reads unmapped: too short |	86246372
                 % of reads unmapped: too short |	66.36%
                Number of reads unmapped: other |	38012115
                     % of reads unmapped: other |	29.25%
                                  CHIMERIC READS:
                       Number of chimeric reads |	0
                            % of chimeric reads |	0.00%
```

**Comment by alexdobin** [comment]
Hi Kai:

this is great! It looks like your reads (or rather the anchor seeds) map to between 50 and 100 loci in the full genome.
You can now try to bring back the splicing if you are interested in it.

Cheers
Alex

**Comment by kbattenb** [comment]
Hi Alex,

It seems that way indeed.
I will try bringing splicing back although none of the rRNA annotation has any splicing.
It is always easier to explain what I did with fewer parameter settings adjusted away from the default.

Thank you so much!

Kai Battenberg
