### ISSUE TITLE
transcriptome alignment redundant output and no duplicates can be identified by picard

### ISSUE THREAD

**Issue by isuxyang** [alexdobin/STAR#104]
Hi, 

I encountered two strange problems with STAR alignment output of transcriptome data that I do not understand and hope you can give some insight, thanks !

PROBLEM1.  as illustrated in the alignment output example below, the same read pair (SN7001233:326:HGYCWBCXX:2:2110:11744:53901) is aligned to 3 different transcripts, however, the output seems to be redundant.  for example the alignment to reference ENST00000403880.1 was output twice with only difference is HI:i: field, where one is 1, the other is 4... from my understanding, this read pair should only be multimapped 3 times, whereas it is accounted for 6 times, hence 12 lines of output

SN7001233:326:HGYCWBCXX:2:2110:11744:53901	355	ENST00000403880.1 1438	0	72M	=	1598	235	CTTCGTCATCAACAACACACAGCGGGTCTTGAAAGGGGACTATAAAACACCAGCCAATCTGTAAGTATATTT	AGA.<GGG.GG<<GGA<<A.<GA.AGGG.....<.<.A<<GGAGGGAG.<G.<.AG.G.G...<..<.A.<.	NH:i:6	HI:i:1	RG:Z:id

SN7001233:326:HGYCWBCXX:2:2110:11744:53901	403	ENST00000403880.1 1598	0	75M	=	1438	-235	AAAATCCATTTAAGTGGAAATCGGACGTCTATTCCAAGCATATTGCTTGCTATTAATCGCCAAAACAGGACTGCT	..<.<..GGAG..<<.<..<.AAG<<.<<.<....<.<....<<<GG<..<<..GA<A.AGAGGGG.A.GG<.<.	NH:i:6	HI:i:1	RG:Z:id

SN7001233:326:HGYCWBCXX:2:2110:11744:53901	355	ENST00000398110.2 1322	0	72M	=	1482	235	CTTCGTCATCAACAACACACAGCGGGTCTTGAAAGGGGACTATAAAACACCAGCCAATCTGTAAGTATATTT	AGA.<GGG.GG<<GGA<<A.<GA.AGGG.....<.<.A<<GGAGGGAG.<G.<.AG.G.G...<..<.A.<.	NH:i:6	HI:i:2	RG:Z:id

SN7001233:326:HGYCWBCXX:2:2110:11744:53901	403	ENST00000398110.2 1482	0	75M	=	1322	-235	AAAATCCATTTAAGTGGAAATCGGACGTCTATTCCAAGCATATTGCTTGCTATTAATCGCCAAAACAGGACTGCT	..<.<..GGAG..<<.<..<.AAG<<.<<.<....<.<....<<<GG<..<<..GA<A.AGAGGGG.A.GG<.<.	NH:i:6	HI:i:2	RG:Z:id

SN7001233:326:HGYCWBCXX:2:2110:11744:53901	355	ENST00000338754.4 1288	0	72M	=	1448	235	CTTCGTCATCAACAACACACAGCGGGTCTTGAAAGGGGACTATAAAACACCAGCCAATCTGTAAGTATATTT	AGA.<GGG.GG<<GGA<<A.<GA.AGGG.....<.<.A<<GGAGGGAG.<G.<.AG.G.G...<..<.A.<.	NH:i:6	HI:i:3	RG:Z:id

SN7001233:326:HGYCWBCXX:2:2110:11744:53901	403	ENST00000338754.4 1448	0	75M	=	1288	-235	AAAATCCATTTAAGTGGAAATCGGACGTCTATTCCAAGCATATTGCTTGCTATTAATCGCCAAAACAGGACTGCT	..<.<..GGAG..<<.<..<.AAG<<.<<.<....<.<....<<<GG<..<<..GA<A.AGAGGGG.A.GG<.<.	NH:i:6	HI:i:3	RG:Z:id

SN7001233:326:HGYCWBCXX:2:2110:11744:53901	355	ENST00000403880.1 1438	0	72M	=	1598	235	CTTCGTCATCAACAACACACAGCGGGTCTTGAAAGGGGACTATAAAACACCAGCCAATCTGTAAGTATATTT	AGA.<GGG.GG<<GGA<<A.<GA.AGGG.....<.<.A<<GGAGGGAG.<G.<.AG.G.G...<..<.A.<.	NH:i:6	HI:i:4	RG:Z:id

SN7001233:326:HGYCWBCXX:2:2110:11744:53901	403	ENST00000403880.1 1598	0	75M	=	1438	-235	AAAATCCATTTAAGTGGAAATCGGACGTCTATTCCAAGCATATTGCTTGCTATTAATCGCCAAAACAGGACTGCT	..<.<..GGAG..<<.<..<.AAG<<.<<.<....<.<....<<<GG<..<<..GA<A.AGAGGGG.A.GG<.<.	NH:i:6	HI:i:4	RG:Z:id

SN7001233:326:HGYCWBCXX:2:2110:11744:53901	355	ENST00000398110.2 1322	0	72M	=	1482	235	CTTCGTCATCAACAACACACAGCGGGTCTTGAAAGGGGACTATAAAACACCAGCCAATCTGTAAGTATATTT	AGA.<GGG.GG<<GGA<<A.<GA.AGGG.....<.<.A<<GGAGGGAG.<G.<.AG.G.G...<..<.A.<.	NH:i:6	HI:i:5	RG:Z:id

SN7001233:326:HGYCWBCXX:2:2110:11744:53901	403	ENST00000398110.2 1482	0	75M	=	1322	-235	AAAATCCATTTAAGTGGAAATCGGACGTCTATTCCAAGCATATTGCTTGCTATTAATCGCCAAAACAGGACTGCT	..<.<..GGAG..<<.<..<.AAG<<.<<.<....<.<....<<<GG<..<<..GA<A.AGAGGGG.A.GG<.<.	NH:i:6	HI:i:5	RG:Z:id

SN7001233:326:HGYCWBCXX:2:2110:11744:53901	355	ENST00000338754.4 1288	0	72M	=	1448	235	CTTCGTCATCAACAACACACAGCGGGTCTTGAAAGGGGACTATAAAACACCAGCCAATCTGTAAGTATATTT	AGA.<GGG.GG<<GGA<<A.<GA.AGGG.....<.<.A<<GGAGGGAG.<G.<.AG.G.G...<..<.A.<.	NH:i:6	HI:i:6	RG:Z:id

SN7001233:326:HGYCWBCXX:2:2110:11744:53901	403	ENST00000338754.4 1448	0	75M	=	1288	-235	AAAATCCATTTAAGTGGAAATCGGACGTCTATTCCAAGCATATTGCTTGCTATTAATCGCCAAAACAGGACTGCT	..<.<..GGAG..<<.<..<.AAG<<.<<.<....<.<....<<<GG<..<<..GA<A.AGAGGGG.A.GG<.<.	NH:i:6	HI:i:6	RG:Z:id

PROBLEM 2: for all the samples I've tested using picard duplicate function, the transcript.bam file output has no report of duplication which is rather odd as I know some libraries do have high duplication rate. Have anyone encountered this previously? I do not know if it is due to some flag setting in bam file.

**Comment by alexdobin** [comment]
Hi @isuxyang 
I could not reproduce problem 1 when I mapped you sequence to the h38/Gencode 24 genome (please see below).
What genome/annotations/STAR version are you using?

As to problem 2, do you know whether Picard considers duplication of multi-mappers?
Most of the alignments to transcriptome are multi-mappers.

Cheers
Alex



1       355     ENST00000403880.5       1438    1       72M     =       1598    235     CTTCGTCATCAACAACACACAGCGGGTCTTGAAAGGGGACTATAAAACACCAGCCAATCTGTAAGTATATTT        *       NH:i:3  HI:i:1
1       403     ENST00000403880.5       1598    1       75M     =       1438    -235    AAAATCCATTTAAGTGGAAATCGGACGTCTATTCCAAGCATATTGCTTGCTATTAATCGCCAAAACAGGACTGCT     *       NH:i:3  HI:i:1
1       99      ENST00000398110.6       1322    1       72M     =       1482    235     CTTCGTCATCAACAACACACAGCGGGTCTTGAAAGGGGACTATAAAACACCAGCCAATCTGTAAGTATATTT        *       NH:i:3  HI:i:2
1       147     ENST00000398110.6       1482    1       75M     =       1322    -235    AAAATCCATTTAAGTGGAAATCGGACGTCTATTCCAAGCATATTGCTTGCTATTAATCGCCAAAACAGGACTGCT     *       NH:i:3  HI:i:2
1       355     ENST00000338754.8       1288    1       72M     =       1448    235     CTTCGTCATCAACAACACACAGCGGGTCTTGAAAGGGGACTATAAAACACCAGCCAATCTGTAAGTATATTT        *       NH:i:3  HI:i:3
1       403     ENST00000338754.8       1448    1       75M     =       1288    -235    AAAATCCATTTAAGTGGAAATCGGACGTCTATTCCAAGCATATTGCTTGCTATTAATCGCCAAAACAGGACTGCT     *       NH:i:3  HI:i:3

**Comment by isuxyang** [comment]
Hi Alex, 

thanks a lot for your response. From your response, I assume that's not the intended behavior of STAR. 
Also, I realized/guess picard doesn't even consider multi-mapped reads to begin with, hence the behavior, so, in this case, I know STAR might do duprm , do you know if that will work on multi-mapped reads, if so, I'll give it a try (if you could kindly recommend how to use that command).

More detailed answers to your question 1 below. And see if you may see what I may have done incorrectly with star command.

Thanks,
Xiao


Here's the exact command I used and the version of star is STAR_2.5.0a_alpha, and the grep results shown below: 

STAR --genomeDir /illumina/scratch/panacea/resource/References/Homo_sapiens/GENCODE/GRCh37_p12/Index/STAR/GENCODE_74bp/ --readFilesIn /illumina/scratch/CMS/Dan/debug/r1.fq.gz /illumina/scratch/CMS/Dan/debug/r2.fq.gz --outFileNamePrefix /illumina/scratch/CMS/Dan/debug/result/TEST/TEST_star_ --outSAMtype BAM SortedByCoordinate --sjdbOverhang 74 --outSAMunmapped Within --outFilterType BySJout --outSAMattributes NH HI AS NM MD  --outFilterMultimapNmax 20  --outFilterMismatchNmax 999  --outFilterMismatchNoverLmax 0.04  --alignIntronMin 20  --alignIntronMax 1000000  --alignMatesGapMax 1000000  --alignSJoverhangMin 8  --alignSJDBoverhangMin 1  --sjdbScore 1  --runThreadN 16  --genomeLoad NoSharedMemory  --quantMode TranscriptomeSAM  --outSAMheaderHD @HD VN:1.4 --outSAMattrRGline ID:id LB:library PL:platform PU:machine SM:sample --readFilesCommand zcat


samtools view result/TEST/TEST_star_Aligned.toTranscriptome.out.bam | grep SN7001233:326:HGYCWBCXX:2:2110:11744:53901 

SN7001233:326:HGYCWBCXX:2:2110:11744:53901	355	ENST00000403880.1	1438	0	72M	=	1598	235	CTTCGTCATCAACAACACACAGCGGGTCTTGAAAGGGGACTATAAAACACCAGCCAATCTGTAAGTATATTT	AGA.<GGG.GG<<GGA<<A.<GA.AGGG.....<.<.A<<GGAGGGAG.<G.<.AG.G.G...<..<.A.<.	NH:i:6	HI:i:1	RG:Z:id
SN7001233:326:HGYCWBCXX:2:2110:11744:53901	403	ENST00000403880.1	1598	0	75M	=	1438	-235	AAAATCCATTTAAGTGGAAATCGGACGTCTATTCCAAGCATATTGCTTGCTATTAATCGCCAAAACAGGACTGCT	..<.<..GGAG..<<.<..<.AAG<<.<<.<....<.<....<<<GG<..<<..GA<A.AGAGGGG.A.GG<.<.	NH:i:6	HI:i:1	RG:Z:id
SN7001233:326:HGYCWBCXX:2:2110:11744:53901	355	ENST00000398110.2	1322	0	72M	=	1482	235	CTTCGTCATCAACAACACACAGCGGGTCTTGAAAGGGGACTATAAAACACCAGCCAATCTGTAAGTATATTT	AGA.<GGG.GG<<GGA<<A.<GA.AGGG.....<.<.A<<GGAGGGAG.<G.<.AG.G.G...<..<.A.<.	NH:i:6	HI:i:2	RG:Z:id
SN7001233:326:HGYCWBCXX:2:2110:11744:53901	403	ENST00000398110.2	1482	0	75M	=	1322	-235	AAAATCCATTTAAGTGGAAATCGGACGTCTATTCCAAGCATATTGCTTGCTATTAATCGCCAAAACAGGACTGCT	..<.<..GGAG..<<.<..<.AAG<<.<<.<....<.<....<<<GG<..<<..GA<A.AGAGGGG.A.GG<.<.	NH:i:6	HI:i:2	RG:Z:id
SN7001233:326:HGYCWBCXX:2:2110:11744:53901	355	ENST00000338754.4	1288	0	72M	=	1448	235	CTTCGTCATCAACAACACACAGCGGGTCTTGAAAGGGGACTATAAAACACCAGCCAATCTGTAAGTATATTT	AGA.<GGG.GG<<GGA<<A.<GA.AGGG.....<.<.A<<GGAGGGAG.<G.<.AG.G.G...<..<.A.<.	NH:i:6	HI:i:3	RG:Z:id
SN7001233:326:HGYCWBCXX:2:2110:11744:53901	403	ENST00000338754.4	1448	0	75M	=	1288	-235	AAAATCCATTTAAGTGGAAATCGGACGTCTATTCCAAGCATATTGCTTGCTATTAATCGCCAAAACAGGACTGCT	..<.<..GGAG..<<.<..<.AAG<<.<<.<....<.<....<<<GG<..<<..GA<A.AGAGGGG.A.GG<.<.	NH:i:6	HI:i:3	RG:Z:id
SN7001233:326:HGYCWBCXX:2:2110:11744:53901	355	ENST00000403880.1	1438	0	72M	=	1598	235	CTTCGTCATCAACAACACACAGCGGGTCTTGAAAGGGGACTATAAAACACCAGCCAATCTGTAAGTATATTT	AGA.<GGG.GG<<GGA<<A.<GA.AGGG.....<.<.A<<GGAGGGAG.<G.<.AG.G.G...<..<.A.<.	NH:i:6	HI:i:4	RG:Z:id
SN7001233:326:HGYCWBCXX:2:2110:11744:53901	403	ENST00000403880.1	1598	0	75M	=	1438	-235	AAAATCCATTTAAGTGGAAATCGGACGTCTATTCCAAGCATATTGCTTGCTATTAATCGCCAAAACAGGACTGCT	..<.<..GGAG..<<.<..<.AAG<<.<<.<....<.<....<<<GG<..<<..GA<A.AGAGGGG.A.GG<.<.	NH:i:6	HI:i:4	RG:Z:id
SN7001233:326:HGYCWBCXX:2:2110:11744:53901	355	ENST00000398110.2	1322	0	72M	=	1482	235	CTTCGTCATCAACAACACACAGCGGGTCTTGAAAGGGGACTATAAAACACCAGCCAATCTGTAAGTATATTT	AGA.<GGG.GG<<GGA<<A.<GA.AGGG.....<.<.A<<GGAGGGAG.<G.<.AG.G.G...<..<.A.<.	NH:i:6	HI:i:5	RG:Z:id
SN7001233:326:HGYCWBCXX:2:2110:11744:53901	403	ENST00000398110.2	1482	0	75M	=	1322	-235	AAAATCCATTTAAGTGGAAATCGGACGTCTATTCCAAGCATATTGCTTGCTATTAATCGCCAAAACAGGACTGCT	..<.<..GGAG..<<.<..<.AAG<<.<<.<....<.<....<<<GG<..<<..GA<A.AGAGGGG.A.GG<.<.	NH:i:6	HI:i:5	RG:Z:id
SN7001233:326:HGYCWBCXX:2:2110:11744:53901	355	ENST00000338754.4	1288	0	72M	=	1448	235	CTTCGTCATCAACAACACACAGCGGGTCTTGAAAGGGGACTATAAAACACCAGCCAATCTGTAAGTATATTT	AGA.<GGG.GG<<GGA<<A.<GA.AGGG.....<.<.A<<GGAGGGAG.<G.<.AG.G.G...<..<.A.<.	NH:i:6	HI:i:6	RG:Z:id
SN7001233:326:HGYCWBCXX:2:2110:11744:53901	403	ENST00000338754.4	1448	0	75M	=	1288	-235	AAAATCCATTTAAGTGGAAATCGGACGTCTATTCCAAGCATATTGCTTGCTATTAATCGCCAAAACAGGACTGCT	..<.<..GGAG..<<.<..<.AAG<<.<<.<....<.<....<<<GG<..<<..GA<A.AGAGGGG.A.GG<.<.	NH:i:6	HI:i:6	RG:Z:id

**Comment by alexdobin** [comment]
Hi Xiao,

STAR_2.5.0a_alpha is not a stable version, could you please try the latest tagged release, 2.5.1a?
I tried 2.5.0b with hg19/Gencode19 annotations, and could not reproduce the problem.

Cheers
Alex

**Comment by isuxyang** [comment]
Hi Alex, 

I've tried 2.5.1a, rebuilding reference index, and rerun STAR alignment using only one read pair, the result remains the same, no luck there (see exact cmd below). The input genome fasta file (ALL) and gtf file (first row in the table) are downloaded from the link http://www.gencodegenes.org/releases/19.html

Thanks for all your help. 
Xiao

1. index stage 

STAR --genomeDir ./ --runMode genomeGenerate --genomeFastaFiles ../../../Sequence/GRCh37.p13.genome.fa --runThreadN 15 --sjdbOverhang 74 --sjdbGTFfile ../../../Annotation/gencode.v19.annotation.gtf
Jan 21 17:29:41 ..... Started STAR run
Jan 21 17:29:41 ... Starting to generate Genome files
Jan 21 17:30:40 ... starting to sort  Suffix Array. This may take a long time...
Jan 21 17:30:59 ... sorting Suffix Array chunks and saving them to disk...
Jan 21 17:54:13 ... loading chunks from disk, packing SA...
Jan 21 17:56:46 ... Finished generating suffix array
Jan 21 17:56:46 ... Generating Suffix Array index
Jan 21 18:00:40 ... Completed Suffix Array index
Jan 21 18:00:40 ..... Processing annotations GTF
Jan 21 18:00:58 ..... Inserting junctions into the genome indices
Jan 21 18:03:53 ... writing Genome to disk ...
Jan 21 18:04:08 ... writing Suffix Array to disk ...
Jan 21 18:05:24 ... writing SAindex to disk
Jan 21 18:05:30 ..... Finished successfully

2. the input files

r1.1.fq.gz

@SN7001233:326:HGYCWBCXX:2:2110:11744:53901 1:N:0:3
CTTCGTCATCAACAACACACAGCGGGTCTTGAAAGGGGACTATAAAACACCAGCCAATCTGTAAGTATATTT
+
AGA.<GGG.GG<<GGA<<A.<GA.AGGG.....<.<.A<<GGAGGGAG.<G.<.AG.G.G...<..<.A.<.

r2.1.fq.gz 

@SN7001233:326:HGYCWBCXX:2:2110:11744:53901 2:N:0:3
AGCAGTCCTGTTTTGGCGATTAATAGCAAGCAATATGCTTGGAATAGACGTCCGATTTCCACTTAAATGGATTTT
+
.<.<GG.A.GGGGAGA.A<AG..<<..<GG<<<....<.<....<.<<.<<GAA.<..<.<<..GAGG..<.<..

3. alignment stage 

STAR --genomeDir /illumina/scratch/panacea/resource/References/Homo_sapiens/GENCODE/GRCh37_p13/Index/STAR/GENCODE_74bp/ --readFilesIn /illumina/scratch/CMS/Dan/debug/r1.1.fq.gz /illumina/scratch/CMS/Dan/debug/r2.1.fq.gz --outFileNamePrefix /illumina/scratch/CMS/Dan/debug/result/TEST/TEST_star_ --outSAMtype BAM SortedByCoordinate --sjdbOverhang 74 --outSAMunmapped Within --outFilterType BySJout --outSAMattributes NH HI AS NM MD  --outFilterMultimapNmax 20  --outFilterMismatchNmax 999  --outFilterMismatchNoverLmax 0.04  --alignIntronMin 20  --alignIntronMax 1000000  --alignMatesGapMax 1000000  --alignSJoverhangMin 8  --alignSJDBoverhangMin 1  --sjdbScore 1  --runThreadN 16  --genomeLoad NoSharedMemory  --quantMode TranscriptomeSAM  --outSAMheaderHD @HD VN:1.4 --outSAMattrRGline ID:id LB:library PL:platform PU:machine SM:sample --readFilesCommand zcat
Jan 22 10:06:16 ..... Started STAR run
Jan 22 10:06:17 ..... Loading genome
Jan 22 10:09:09 ..... Started mapping
Jan 22 10:09:16 ..... Started sorting BAM
Jan 22 10:09:16 ..... Finished successfully

4. resulting bam file 

samtools view result/TEST/TEST_star_Aligned.toTranscriptome.out.bam
SN7001233:326:HGYCWBCXX:2:2110:11744:53901	355	ENST00000403880.1	1438	0	72M	=	1598	235	CTTCGTCATCAACAACACACAGCGGGTCTTGAAAGGGGACTATAAAACACCAGCCAATCTGTAAGTATATTT	AGA.<GGG.GG<<GGA<<A.<GA.AGGG.....<.<.A<<GGAGGGAG.<G.<.AG.G.G...<..<.A.<.	NH:i:6	HI:i:1	RG:Z:id
SN7001233:326:HGYCWBCXX:2:2110:11744:53901	403	ENST00000403880.1	1598	0	75M	=	1438	-235	AAAATCCATTTAAGTGGAAATCGGACGTCTATTCCAAGCATATTGCTTGCTATTAATCGCCAAAACAGGACTGCT	..<.<..GGAG..<<.<..<.AAG<<.<<.<....<.<....<<<GG<..<<..GA<A.AGAGGGG.A.GG<.<.	NH:i:6	HI:i:1	RG:Z:id
SN7001233:326:HGYCWBCXX:2:2110:11744:53901	355	ENST00000398110.2	1322	0	72M	=	1482	235	CTTCGTCATCAACAACACACAGCGGGTCTTGAAAGGGGACTATAAAACACCAGCCAATCTGTAAGTATATTT	AGA.<GGG.GG<<GGA<<A.<GA.AGGG.....<.<.A<<GGAGGGAG.<G.<.AG.G.G...<..<.A.<.	NH:i:6	HI:i:2	RG:Z:id
SN7001233:326:HGYCWBCXX:2:2110:11744:53901	403	ENST00000398110.2	1482	0	75M	=	1322	-235	AAAATCCATTTAAGTGGAAATCGGACGTCTATTCCAAGCATATTGCTTGCTATTAATCGCCAAAACAGGACTGCT	..<.<..GGAG..<<.<..<.AAG<<.<<.<....<.<....<<<GG<..<<..GA<A.AGAGGGG.A.GG<.<.	NH:i:6	HI:i:2	RG:Z:id
SN7001233:326:HGYCWBCXX:2:2110:11744:53901	355	ENST00000338754.4	1288	0	72M	=	1448	235	CTTCGTCATCAACAACACACAGCGGGTCTTGAAAGGGGACTATAAAACACCAGCCAATCTGTAAGTATATTT	AGA.<GGG.GG<<GGA<<A.<GA.AGGG.....<.<.A<<GGAGGGAG.<G.<.AG.G.G...<..<.A.<.	NH:i:6	HI:i:3	RG:Z:id
SN7001233:326:HGYCWBCXX:2:2110:11744:53901	403	ENST00000338754.4	1448	0	75M	=	1288	-235	AAAATCCATTTAAGTGGAAATCGGACGTCTATTCCAAGCATATTGCTTGCTATTAATCGCCAAAACAGGACTGCT	..<.<..GGAG..<<.<..<.AAG<<.<<.<....<.<....<<<GG<..<<..GA<A.AGAGGGG.A.GG<.<.	NH:i:6	HI:i:3	RG:Z:id
SN7001233:326:HGYCWBCXX:2:2110:11744:53901	99	ENST00000403880.1	1438	0	72M	=	1598	235	CTTCGTCATCAACAACACACAGCGGGTCTTGAAAGGGGACTATAAAACACCAGCCAATCTGTAAGTATATTT	AGA.<GGG.GG<<GGA<<A.<GA.AGGG.....<.<.A<<GGAGGGAG.<G.<.AG.G.G...<..<.A.<.	NH:i:6	HI:i:4	RG:Z:id
SN7001233:326:HGYCWBCXX:2:2110:11744:53901	147	ENST00000403880.1	1598	0	75M	=	1438	-235	AAAATCCATTTAAGTGGAAATCGGACGTCTATTCCAAGCATATTGCTTGCTATTAATCGCCAAAACAGGACTGCT	..<.<..GGAG..<<.<..<.AAG<<.<<.<....<.<....<<<GG<..<<..GA<A.AGAGGGG.A.GG<.<.	NH:i:6	HI:i:4	RG:Z:id
SN7001233:326:HGYCWBCXX:2:2110:11744:53901	355	ENST00000398110.2	1322	0	72M	=	1482	235	CTTCGTCATCAACAACACACAGCGGGTCTTGAAAGGGGACTATAAAACACCAGCCAATCTGTAAGTATATTT	AGA.<GGG.GG<<GGA<<A.<GA.AGGG.....<.<.A<<GGAGGGAG.<G.<.AG.G.G...<..<.A.<.	NH:i:6	HI:i:5	RG:Z:id
SN7001233:326:HGYCWBCXX:2:2110:11744:53901	403	ENST00000398110.2	1482	0	75M	=	1322	-235	AAAATCCATTTAAGTGGAAATCGGACGTCTATTCCAAGCATATTGCTTGCTATTAATCGCCAAAACAGGACTGCT	..<.<..GGAG..<<.<..<.AAG<<.<<.<....<.<....<<<GG<..<<..GA<A.AGAGGGG.A.GG<.<.	NH:i:6	HI:i:5	RG:Z:id
SN7001233:326:HGYCWBCXX:2:2110:11744:53901	355	ENST00000338754.4	1288	0	72M	=	1448	235	CTTCGTCATCAACAACACACAGCGGGTCTTGAAAGGGGACTATAAAACACCAGCCAATCTGTAAGTATATTT	AGA.<GGG.GG<<GGA<<A.<GA.AGGG.....<.<.A<<GGAGGGAG.<G.<.AG.G.G...<..<.A.<.	NH:i:6	HI:i:6	RG:Z:id
SN7001233:326:HGYCWBCXX:2:2110:11744:53901	403	ENST00000338754.4	1448	0	75M	=	1288	-235	AAAATCCATTTAAGTGGAAATCGGACGTCTATTCCAAGCATATTGCTTGCTATTAATCGCCAAAACAGGACTGCT	..<.<..GGAG..<<.<..<.AAG<<.<<.<....<.<....<<<GG<..<<..GA<A.AGAGGGG.A.GG<.<.	NH:i:6	HI:i:6	RG:Z:id

**Comment by alexdobin** [comment]
Hi Xiao,

this is truly weird. It seems like this transcript is "duplicated" for some reason in the annotations. Could you please send me the Log.out files from both the genome generation and mapping runs.
I am running your exact commands and will compare two outputs.

Cheers
Alex

**Comment by isuxyang** [comment]
Hi Alex, 

I thought the same previously but did not find duplication in the gtf file... I attached both log files for your reference. 

thanks,
Xiao

[Log.out.genomeGen.txt](https://github.com/alexdobin/STAR/files/101400/Log.out.genomeGen.txt)

[test_star_Log.out.alignment.txt](https://github.com/alexdobin/STAR/files/101404/test_star_Log.out.alignment.txt)

**Comment by alexdobin** [comment]
Hi Xiao,

thanks a lot for the detailed description of the problem - I was finally able to reproduce it.
The problem was caused by --outFilterMismatchNoverLmax 0.04 parameter - it allowed some strange genomic alignments with soft-clipping that mapped back to exactly the same transcript.
I will fix this problem, in the meantime please use the following parameter instead:
 --outFilterMismatchNoverReadLmax 0.04.
It has the same meaning, but normalizes the number of mismatches to the whole read length, not just the number of matched bases. This is the parameter we are currently using in ENCODE.

Cheers
Alex

**Comment by isuxyang** [comment]
Thanks Alex for your timely looking into the issue. Greatly appreciate !

**Comment by isuxyang** [comment]
Hi Alex, 

One more follow up, I'm trying to understand the relationship of alignment output to genome and the .transcriptome.bam file.  I wonder if you could explain how is the .transcriptome.bam file is generated. Is it by directly converting the genome alignment using gtf file to the transcripts coordinates? So if this is the case, then 
1. do you have separate script to do so ? 
2. as a read aligned to one transcript of a gene, then it is highly likely it will align to the other transcript of the same gene, will this be output twice ? 

thanks,
Xiao

**Comment by alexdobin** [comment]
Hi Xiao,

STAR indeed directly converts genomic alignment coordinates into coordinates on transcripts.
1. This feature is coded directly inside STAR, there is no separate script. In the future I am planning to make this conversion work with external BAMs.
2. If a read conforms to many transcripts, all of the alignments will be output. Many reads that map uniquely in the genomic space become multimappers in the transcriptomic space.

Cheers
Alex

**Comment by frankyan** [comment]
@alexdobin Sorry for reopening the closed issue. Has this problem been solved in 2.5.2b? I encountered a similar problem. Read is reported as multiple mapping, but the multimappers are totally the same. However, I didn't use that parameter `--outFilterMismatchNoverLmax`.  Following is the parameters I used. 
```
STAR 
--genomeDir smallpartial_DNA
--readFilesIn $inputFolder/R1_rmdup.fa.gz 
--readFilesCommand zcat 
--outSAMtype BAM SortedByCoordinate 
--outSAMstrandField intronMotif 
--outReadsUnmapped Fastx 
--outSAMattributes All 
--outFileNamePrefix targetMapping
--quantMode GeneCounts 
--alignEndsType Extend5pOfRead1 
--seedSearchStartLmax 25 
--runThreadN 30 
--outFilterScoreMin 21 
--outFilterScoreMinOverLread 0.13 
--outFilterMatchNmin 21 
--outFilterMatchNminOverLread 0.13
--alignIntronMaxdefault 1
```
After several attempts, I found that removing `--alignIntronMaxdefault 1` solved the problem. So what do you think about the reason? I need to prohibit unannotated junctions, so what else parameter can be used?

**Comment by alexdobin** [comment]
Hi @frankyan 

this looks like a different problem. Could you please send me an example of multi-alignments that look exactly the same?

--alignIntronMax will prohibit unannotated junctions.

Cheers
Alex

**Comment by frankyan** [comment]
Hi Alex,

Thank you for your reply. As the `--alignIntronMax` caused such duplicated multiple mapping, so we cannot use it to prohibit unannotated junctions. 

Here is an example. We are trying to map sequencing reads to human rDNA sequence [NCBI U13369](https://www.ncbi.nlm.nih.gov/nuccore/U13369). We don't have GTF file. So we built the genome index using the following command line.  
```
STAR   --runMode genomeGenerate   --runThreadN 4   --genomeDir ./human_rDNA_unit   --genomeFastaFiles ./U13369_1____Human_ribosomal_DNA_complete_repeating_unit.fa      --genomeSAindexNbases 7
```
Here is an example sequencing read for mapping.
```
@K00180:220:HCLWLBBXX:6:1101:21298:1086 1:N:0:NCTTGA
AAGCATGCCAGAGTCTCGTTCGTTATCGGAATTAACCAGACAAATCGCTCCACCAACTAAGAACGGCCATGCACCACCACCCACGGAATCGAGAAAGAGC
+
AAFFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFJJJJFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ
```
The mapping result is below. You can find 3 duplicated multiple mapping.
```
@HD     VN:1.4
@SQ     SN:U13369.1     LN:42999
@PG     ID:STAR PN:STAR VN:STAR_2.5.1b  CL:STAR   --runThreadN 10   --genomeDir ../human_rDNA_unit   --readFilesIn ./Without_N.fastq      --outFileNamePrefix ./Without_N/Without_N   --outFilterScoreMin 21   --outFilterScoreMinOverLread 0.13   --outFilterMatchNmin 21   --outFilterMatchNminOverLread 0.13   --seedSearchStartLmax 25   --alignIntronMax 1   --alignEndsType Extend5pOfRead1
@CO     user command line: STAR --genomeDir ../human_rDNA_unit --readFilesIn ./Without_N.fastq --runThreadN 10 --outFileNamePrefix ./Without_N/Without_N --alignEndsType Extend5pOfRead1 --seedSearchStartLmax 25 --outFilterScoreMin 21 --outFilterScoreMinOverLread 0.13 --outFilterMatchNmin 21 --outFilterMatchNminOverLread 0.13 --alignIntronMax 1
K00180:220:HCLWLBBXX:6:1101:21298:1086  16      U13369.1        4958    1       100M    *       0       0       GCTCTTTCTCGATTCCGTGGGTGGTGGTGCATGGCCGTTCTTAGTTGGTGGAGCGATTTGTCTGGTTAATTCCGATAACGAACGAGACTCTGGCATGCTT    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJFJJJJFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFFAA    NH:i:3  HI:i:1  AS:i:96 nM:i:1
K00180:220:HCLWLBBXX:6:1101:21298:1086  272     U13369.1        4958    1       100M    *       0       0       GCTCTTTCTCGATTCCGTGGGTGGTGGTGCATGGCCGTTCTTAGTTGGTGGAGCGATTTGTCTGGTTAATTCCGATAACGAACGAGACTCTGGCATGCTT    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJFJJJJFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFFAA    NH:i:3  HI:i:2  AS:i:96 nM:i:1
K00180:220:HCLWLBBXX:6:1101:21298:1086  272     U13369.1        4958    1       100M    *       0       0       GCTCTTTCTCGATTCCGTGGGTGGTGGTGCATGGCCGTTCTTAGTTGGTGGAGCGATTTGTCTGGTTAATTCCGATAACGAACGAGACTCTGGCATGCTT    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJFJJJJFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFFAA    NH:i:3  HI:i:3  AS:i:96 nM:i:1
````
If we removed the argument `--alignIntronMax`, the duplicated mappings disappeared.

**Comment by alexdobin** [comment]
Hi @frankyan 

I think this bug was fixed in one of the latest patches, please try to run the STAR from GitHub master.
I still see the problem in 2.5.3a, but it disappears in the master version.

Cheers
Alex
