### ISSUE TITLE
SA file not loading?

### ISSUE THREAD

**Issue by medeeapopescu** [alexdobin/STAR#1049]
Hi,

I'm trying to use STAR to align dropSeq reads to the human genome. The genomeGenerate step was successful, and the mapping step initiated (as per the Log.final.out file) but the Log.progress.out is not updating after 2 hours of running. I went back to the Log.out file and found the following line: 

SA file size: 24955615537 bytes; state: good=1 eof=0 fail=0 bad=0
Loading SA ... done! state: good=0 eof=0 fail=1 bad=1; loaded 0 bytes

What is the SA file and why would it be unsuccessful in loading? The same error popped up in all 4 of the samples I'm trying to align.

Thanks,

Medeea

**Comment by alexdobin** [comment]
Hi Medeea,

how much RAM do you have? Please post the entire Log.out file.

Cheers
Alex

**Comment by medeeapopescu** [comment]
Sure, it's attached. I'm running on a cluster, with 96 GB available per node (I checked one of the STAR_align jobs after I killed the job and it was using 6.50GB/96GB, so I don't think it's a memory problem). 


[Log.txt](https://github.com/alexdobin/STAR/files/5309228/Log.txt)

**Comment by alexdobin** [comment]
Thanks!
Nothing else is suspicious in the Log, and 96GB should be more than enough.
It looks like it's not loading the SA file - maybe it was truncated? 
Please check its size in the STAR_INDEX/SA_100/ genome directory, it should be 
exactly 24955615537 bytes. 

Also, I would recommend switching to one of the latest releases (e.g. 2.7.6a).

Cheers
Alex

**Comment by medeeapopescu** [comment]
Hm okay, I went into STAR_INDEX/SA_100, and there is actually an SA directory (not file), and the directory looks like it contains just a copy of everything in the SA_100 folder (chrLength.txt, Genome, exonInfo.tab, etc). What is the SA file? Does it get generated during the genomeGenerate step?

**Comment by alexdobin** [comment]
SA is indeed a file that's generated in the --genomeGenerate file inside the directory provided in the --genomeDir.
Please remove all the files and directories from SA_100, and re-generate the genome again.

**Comment by medeeapopescu** [comment]
That did it! Mapping finished successfully for everything. I dunno how SA became a directory, but thanks for your help!
