### ISSUE TITLE
 FATAL ERROR in reads input: quality string length is not equal to sequence length

### ISSUE THREAD

**Issue by lovelymaoqin** [alexdobin/STAR#1055]
Hi Alex,

After I trimming the adapter, I did the alignment with the following parameters. And it gave me error as below.
![image](https://user-images.githubusercontent.com/62307133/95386852-e7755680-08bd-11eb-90fd-9e35b40c712c.png)

And I checked it by $grep -B4 -A8 "^@K00269:290:HHC23BBXY:4:1115:16488:30063" new-C110ES.fastq
but, it looks like there are 4 lines read and also the quality value has the same length as the sequence length. Not sure why, would you give me some suggestions?

![image](https://user-images.githubusercontent.com/62307133/95387044-33c09680-08be-11eb-9271-9e4acf0235c7.png)

**Comment by lovelymaoqin** [comment]
Forgot to post the alignment parameters. Just some background for my case: 50 bp single read miRNA

STAR --runThreadN 20 --genomeDir /proj/linnlab/ying/RNAseq/startest --readFilesIn new-C110ES.fastq --outFilterMismatchNoverLmax 0.05 --outFilterMatch
Nmin 16 --outFilterScoreMinOverLread 0  --outFilterMatchNminOverLread 0 --alignIntronMax 1 --outSAMtype BAM SortedByCoordinate --outFileNamePrefix /proj/linnlab/ying/RNAseq/startest/C110ES
~                                                                                                                                                                                                           
~                                                                                                                                                                                                           
~

**Comment by alexdobin** [comment]
Hi @lovelymaoqin 

the reads look fine indeed. Couple of things to try:
1. Save the grepped reads into a file and try to map just them. Does it still cause the error?
2. Try to map untrimmed reads.

Cheers
Alex

**Comment by isii-95** [comment]
hi @alexdobin ! I get the same error as @lovelymaoqin:
![image](https://user-images.githubusercontent.com/79819471/121057682-845dfb80-c78d-11eb-8f18-322acbacb38c.png)

I grep both ID's to see if the have a problem with the length and they are fine:
![image](https://user-images.githubusercontent.com/79819471/121059857-f33c5400-c78f-11eb-9b8c-1ee4a87b17ac.png)

I also search the reevers for these files to check:
![image](https://user-images.githubusercontent.com/79819471/121060460-a86f0c00-c790-11eb-84e9-e9f14b9ea4a0.png)

becauseI don't have access to the untrimmed fastq's I save every grep in a different file and mapp them (the first ID with its reverse and then mapped the second ID with its reverse) and I had no  fatal error, so I don't know why I couldn't mapp them with the full fastq..

I used this data: https://www.ebi.ac.uk/ena/browser/view/ERX3326021

I tried also mapping the full fastq ( the one that have both information, asuming it as forward and reverse) and had no problem mapping it, but I'm not sure if STAR can take it as paired end  reads or if it take it as single reads if it's just one file

**Comment by alexdobin** [comment]
Hi Isil,

please check the formatting of the ~10 reads before the error occurs. There may be a problem there that screws the reads downstream. Are the ENA reads trimmed? If not, I would recommend mapping them to see if you still see the problem. Also, if you are not using the latest STAR release, please switch to it.

Cheers
Alex

**Comment by isii-95** [comment]
Hi @alexdobin, I download the las version of STAR, checked the firsts reads and they look fine, also, I use the file with both forward and reverse reads together and mapped them as a single read file and have no error, but as the reads are paired end, I need both files and it just don't work. I also try mapping forward alone and revers alone unsuccessfully getting an error for each file, so I don't know if it's some problem with STAR or with the actual files.
I'm trying to contact the authors of the paper to see if they have some answers too.

**Comment by alexdobin** [comment]
Hi Isil,

I would try to map untrimmed reads first. Trimming might have messed up the file formatting, but it's not easy to see since this may happen somewhere in the middle of the file.

Cheers
Alex

**Comment by pabisk** [comment]
I find it odd that so many different tools mess up the fastq formatting, and so easily. Is this a STAR issue or should I contact the people responsible for bbmap as well?

In my case unmapped reads are output by STAR and then are cleaned with bbduk.sh entropy=0.5 entropywindow=50 entropyk=5. For this I use bbmap v38.18 from bioconda (also tried a newer version) and STAR v2.7.9a (also tried an older version) but all give the same error.

![image](https://user-images.githubusercontent.com/70287343/127177718-74bfb8ae-440d-43ed-a6b0-772870991e25.png)

**Comment by apredeus** [comment]
I'm actually observing it right now transiently - re-running literally the same set of files, with the same program and script etc, seems to fix the problem. This might have something to do with concatenating multiple files and `echo` command somehow interfering with read streams. The error message I see in most of those seems to have "FILE" word breaking into the sequence, which is also similar to "FILE" listings in the logs:

> EXITING because of FATAL ERROR in reads input: quality string length is not equal to sequence length
> @SRR14212943.3479824
> TGTACAGCAAAGFILE 3
> NTCATTTCAAGATGGCGTCATGTGTGCG
> SOLUTION: fix your fastq file

**Comment by alexdobin** [comment]
Hi Alex,

one explanation is that there are several jobs running in the same directory, this could mess the streams.
Before restarting a job, I recommend removing all files from the run directory, just to be safe.

Cheers
Alex

**Comment by MyhFe** [comment]
@alexdobin Hi Alex,
I tried everything you suggested in this thread and still I get this error:
`EXITING because of FATAL ERROR in reads input: quality string length is not equal to sequence length
@SRR9434783.1
TGGGAAATGACCCTCCTAA..........`

when inspecting my fastq.gz file I get this:
![Untitled](https://user-images.githubusercontent.com/49835922/148530328-909bf2f7-7243-447a-a02a-6ded86c4e0d1.png)

The lengths are the same! is there a problem with the files I downloaded from NCBI or is it STAR? Thanks a lot.
-Lior

**Comment by alexdobin** [comment]
Hi Lior,

these are long reads, so they would require STARlong.
However, STAR is presently not very suitable for long reads with high error rates, I would recommend minmap2 instead.

Cheers
Alex

**Comment by diwasri** [comment]
Hi Alex,

I am having the same problem. I did UMI extract (using UMItools) on my files and then trimmed 6nt using cutadapt. I dont see (atleast with a quick glance) any discrepancies in the string lengths. However, when I do STAR mapping, I get the error "EXITING because of FATAL ERROR in reads input: quality string length is not equal to sequence length".

I tried making small files of 1000, 10000 and 100,000 reads from the raw, UMI extracted and trimmed files and then mapping them. The raw files seem to work fine during mapping, however the UMI extracted and the trimmed files are getting processed. What could be the reason?

Thank you

**Comment by alexdobin** [comment]
Hi @diwasri 

this is caused by a discrepancy in the quality and sequence in the trimmed files.
Does it complain about a specific read?
You can also try to reduce ```-readMapNumber``` until it stops failing - this will tell you which read is at fault.

Cheers
Alex

**Comment by diwasri** [comment]
I redid the trimming using the "-m 1" option to make sure I removed empty reads and that seemed to fix the problem.

Thank you
Meenu

**Comment by elengss** [comment]
Hi there, I am getting the same error with my FASTQ file. I wonder if anyone could see why this is the case? Here are the first 4 lines. Thanks very much. It is not obvious as this messes up the formatting, but the second and fourth lines are the same length. 

@m64176e_220527_114538/59/ccs
TTTTTTTTTTTTTTTTTTTTTTTTTTTTTGTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTAATTTCATATTATATTCTCAATGCTTTCAAAGCCCAACAGTGATTTTAAAAAGAAATTAAACAACATGCTTTCATTGAATTTTTAAAAATCTATACAATTCAAGCTAATGAAATATTTTATTGTACATAATAAAAGTGGTGTTTTTTCTAAAAAAAAAAACAATAAAATAAAATAAAAAAAAAAATTTCCAGGCCCAGACGTCTGTGGGAGTACGTGAGGAAAGGATTCCACTCAAGTATAATCAGCAATACTCTATTGAATGAAACCATAACTCCACTTCACTCCCTATGGTAAATACTAACATTCACCACAGGCTTGAAATTCCTGTAGCATCAGTAGAACTATTTTTGAAAATATTACAAACATGCTTATGATGCATAGGAGGATGAAAAAATTTAGACTGTAACCGCACACCATATGTAATCCCAGCTTTTCTAATTTACAACCAGTTAAGAATTACAATATCCAAAGAAAGTATTTTAAGATATATATGCTCACTGGTAAGTGATTTTCTACTCAAATAAATAGGAAAATTTGCATTTTAATGTCACATTGAATTTCAGTACTTTTCAATCCAAGAAAAAAAAAATAAACCGAGACATGGTCATGAGTTCAGGATTATATATATTACAATTTGCCTTGTTATAATACATTTGTGGCTTTATGATAAAAATAACTCAGGGACATATGGAATTCAAGCTGATTTGCGTAACTGTCACAAGAAAAAAAGCATTAAATGCATTTCTGAAATAAGTATTTTCATTAATTTCAGAATCTCAAAACAGCATTAGACCTTGCCTTGTTTAAAAAAAATTTAGTTCAACACTAAGCTAGCTAAATAACCTTCTTGAAAGGTTTAAACACAATTGATATAGAAAATGCTTTCCCTCTAATCTCAACTTTACATAAATGGAACAGGTGAGGAAGAAAAGGTAGACAATTTCTTTAGCAGCATATATGGCTAAATCCATCAACCACCTTAAACTAGAATGTCCATTATTGACCCCATTAAAAAGAACTGGGGAAATATCAAAAATTACTGATTTCATAAACCAAAAGACATCAATTTTAGGGTTACAGTTAGTAAAATATTTTGAGACACTTCAAAAACTTTTAACCATAAACTAGAAGAATCATCTCTTCATTGTAAGAAAGAAAGGCCTAACAGAAAGACATTTAAACTAAACTGATTTTCAATCCTCTTAGAACAAACAAAATGAAAAATAATGGTTGATTAGCTAAGCTTTGTGCTCTAATCAAACTAATTAATTACAGTGATTTTAAATGGCAACAGCCCATCTGACTGGGCAGCTTGACAGTTCAGAATACTTTTGCAATGATTTTTTAACGCAAAGACACTAAAATGATCCAGTCATGCAATGTTCATCTTATGCATTCTGCATCTCTTTGCCAATCTTGTAGCTAAGGATCTTGTTCCAATCAATCTTAGTGCGTGTAACTGGCAACTGTCGACGTAAGGCTTTGAAAGTAGTGTCCGACATTGTCTGATAATTCTCACTGATGGCAGTCTGGTATTCATTTTCTGCAGCTTCTACAATCTTTATAAATTCTTTTGCTGTTTGCACTTCATTAGACACTGTTAGGGAATCTTGTATATCTTTATGACTCACTAACTGAACATTACCATCTTCATAATAATGAACCTGAATTTTCAAGATGCCAACCACTTGAGTGGTTGAAGGAGTGATTGTAAACTTCCATTCTGACCTCCAACGACCATTCCAAAATTTTTTGCTTGGAACTGATGGCTTTCTATGCATGCAATAATGGTTTGCTGTCCATCTATTTTTTGCCATACACAGTGCAGACTCCATTCGGGTAATGTTCTTTTACGTAAGCTCTCAGAGCAGTTTCTACTGAAGTTCTCCATGATTCAACTGCATTTTCTACTTCACAGGGTCTTGGATCAGTTGCCTCCTTCCTTAAGTGATCAAATTTAAAACAGATTCTGTTCTTTGGATCCAAAAACTTTCCATTTCCCAAGTCGCCATGTTCTGTTATCAATACCTGATCTTCATAACCTTCAATTTTTACTGGAGTAAACTGGTCCAAGTTATACTGTGCAAATGCATGGGCTGCTCCTTCCCTGAGAAGATTGTCATTATTAAGCAGTAACCGAACATCATTAAAAACCTCATTAAATTCTCCAGGAGGGGCATGAATGATGAATTTTGCTGCTATACGCACCTTCTCTTCATCAGACAACTGCTCCTCCAGATCCGCCATCTTCCTTCTGGCGACAAACCGCGGCGGCGGCGGCGGCAGCGGCCACCTGACTTCCCCGTTTCCGTGCGGTCCTCAGCGCCGCGCGCCCCCGCTAAGGGAGGGCCC
+
'wwwwwwwvnd]_dkspf^\_gn`^friYY&`cefea^dlpqqmfa^_djpqqpfZWanqqqqqqqqqqqqm[Y\_[zH|nMoqhOsjlKJpRT^Nvib<6ToRW~~eK~{SxaobkfqB}|fH~~~{cP~wRhLgc^Q~]WafcI|xRjc~f^i7~~~v%hqq_lerqrteb{MnMYsceqInafX~uefL~~~p[zetsb`l2L\6s[mcoF__c&krs_U^c3Wvt`[\gw~paRVKCfmolHvnnX%aPaooooomRMv~6noU~>fu`eo[_tcoep:~uZT_\ab^RqT~X~xB~aI~6ojdrf?icsrq\gVfoeUQwms`lbqm7efc}iMT~vObcV^~brJ|cdc~aW^r;}XQ`\MgiLzog`ciAk_oBqgjD~keoRuFb~fInpMtO~oekV`IWiYTThne?VFkk:~~~~a%dmhYqV|scL~~bojSdO~JfYdmf`>L^S~rS~rog:~~|`fQrrXcUU[ZR?b?pd,NecQo\kmnesd~lJ~~ncb8jxycqNkA{vseU~S~jd[~c~c6YZ~hDA^R[cOvY~}cX~}blXC{}rb~cqhVeehenfcrMkcoV~sIjepfnA~~~c_jfrfI~qpI}Y]pCyEh^kJVkGSgE~~}6aLfrfqeoc~fB^R|~^VYPR^Py~~f[pqU~QnO'ANQThmftkdT~{X~d_cnQjnV~pfol\rdBrRjU~o=oU\LM^XgY~rbZpD}}aV~c~]<xfpaiiYX;9ik`qTm':^spofmpA~~~Z\\~cqRj=~~rfjgZcP{O|\sfc}FdhE]J~~`d2^]zbmetfqZR}J7z~~yJM\SjShL~}kffeCywWYcK~mhR~blWGPT|`MFUNmM~sVJ[E[qcrc@~~rbjcfE^~qcsT~X~fA~P\eAtZ<`ks}~}fCnndcJoQKcKl^bZ~TF_=`cfLmihKH2{b~O?ifK~uR~FX?,7RQqe`wQwUUek\W[Q~~ynfc7rR<~~qJeKqhekfd~bD}xq]SeD}ooV~WyelT~qfoT~c|JI~~wThsrcte[mU~~`Jv~mcfoeforrrqiC~cpLiaUFZ/Xfc~NsdS~Hp3]c`feO_h[ZsNlVZ~o^{LXA~~lSRe>~~~lcFpaW&bewRctqqlc-||{POmXdofoX~~Rjo,tXGoE}}tcrW.?dVxH~~~oK~pO~keod[yqcrIx~jYS3{~dY[WnfpbHza'wwxc>InRU>t@TmqL~ddUUdH\,[sq]SbcccP}foc~e_BnX=qT]E|_I|@wqd~encS~}ctekI~mL~{b`;~}]iM`4qqrf\rrP~o`]~ncLs`Z~~eM~~fL?'Smvdp_{fNwN~bqSzqec_Z~ccW~{QkfMbP]ZkL^5cZRYYgF~IV:~seocqfF,krjB{XN<~eY~eoc-yPXjcoftenIp~goce^}Vteo`U~fkJP_Ykb,vvdffc~oep?mr~~tb}Yda9vYaNBI`CF~~{kffdV~o`pfooffc~oeb~fkjbb~qoffoNwLlf]T\YoH?o_e=hKaXcZt^ZhaP_TVBi^Te;c[DMD{@UibPDQeOyo:cdgRM6PRu_KEvSV|doetLLmQcrZ]O~cZ~~fAdP`raEW^jFZ8sc^^~etcofWY\zc~crfqeVa9I:yf`brdh=~`kU~]H/opqeiffoccJ}e[meZrTdV~~pnI~tOxcD~~wdelfV~~ffqc]eRh_~peseqdiG_~b;xP7pYK\rMVjqqlcP~|edf5(dd^alZ~blf`vKYM~bW~ooeR~fcV2SlWlOVO|O}of6P@og|aIx`kT[T}PpO~Yb_~RYae3h]~f\n5n\^jfq[ydeMke`c~BiNKxcEf`ApYQzO~V0pRkGIg?_'dpL+fXhiubcOJ5hNscofloMoaSt~cqfUaI\USBAz[IN`P^/op\b`etO~opJbU1evxxv`MlQCV]lb```_focmNjGs[ZzdDt]WTooeZ~];v[_[a`ZTsccqepfocrefmbG{iHj[ao+``aW~crV~oofXMnaHmcmffjD~~~elscc~fp[nK~~scZ~P}bhfob[t[J~OM{@s.vCYDabefpqPB~jDxkK~~|eocrc~Jkf=yeW~~J~rrTu5yzy</CxwV~nX~~Kq~ZtctdgK~foeb~coed~rrN^|qsFgW`D5NOiba^OcQ~[id_uI~~}mrcjD~r`dAxd]8M~sO|c~^IxQgrclDLPf>e{VeMejEmo[aW\c;pQ_6Tj_WfTXkTeRhWd^MKqN?kBcV^cTdUa9oW5`T`c]TMj-hhhZ1ecM'2jGnU@i\bPm`5fR(lmYSI:IL^UOK;>2G?aa[F=76LVWVB?PNO1ZKcMVMLcNSTFTMXO@UMUOJJCdVDdUMWI5ZO*Q=SMLc7X<Y6PDeOOXK/\P;VNM(TODeO/BN8_O8_OUMODeDdVCdUOXM@S8ZBINDbbDcM@MO@I<CcVOUM2N&JLN2HM1@Xb_OMO-I6^`K=cc5aa

**Comment by maximus3219** [comment]
Hi Alex @alexdobin ,

I also got the same error in a case recently. Previously, I have processed the fastq files with the same script and pipeline with no problems. Just that this single case got the fatal error message.

![STAR Alignment failure screencap](https://user-images.githubusercontent.com/77224119/190838716-d8126e62-0127-4c22-af1f-d7b773f46a97.png)

Thank you.

Maximus

**Comment by alexdobin** [comment]
Hi Maximus,

Judging by the error message from gzip, it looks like your fastq.gz file was corrupted.

**Comment by x811zou** [comment]
> I redid the trimming using the "-m 1" option to make sure I removed empty reads and that seemed to fix the problem.
> 
> Thank you Meenu

when trimming tool did you use?

**Comment by rvermamsm** [comment]
Hi Alex @alexdobin,

I also got the same error as @maximus3219 got.
Could you please tell me how to fix these corrupted fastq files?

**Comment by tomaskai** [comment]
Hi Alex @alexdobin,
I also got the same error 
`
EXITING because of FATAL ERROR in reads input: quality string length is not equal to sequence length
@A00289:784:H25CWDSX5:2:1638:18096:35524
+
54:4806:10880 75389 N 0
SOLUTION: fix your fastq file
`
![image](https://user-images.githubusercontent.com/30766607/236426624-e883f212-8595-437f-ba93-87e7dd5812a2.png)

I have checked the trimed fastq file, the quality length and the sequence length are equal.
![image](https://user-images.githubusercontent.com/30766607/236426688-818dd58f-c432-447b-9aba-3f66bb1da5cb.png)

**Comment by tomaskai** [comment]
I checked raw data, Read1 and Read2 both have the read, but the read of Read2 is gone after trimmed. 

I'm confused about why this is happening and how to do to solve the problem. 

![image](https://github.com/alexdobin/STAR/assets/30766607/f2ef7887-b1da-4be2-a91c-dd0199d6f461)
![image](https://github.com/alexdobin/STAR/assets/30766607/db9627df-7e47-4b17-ad7e-085092216da6)

Thank you!
Tomaskai

**Comment by alexdobin** [comment]
Hi Tomaskai,

The trimming software has to be run with options that discard both of the reads if one of the reads gets completely trimmed.

**Comment by Adarsh931** [comment]
I just wanted to add that I also was getting the same error and it seems after trimming when I was zipping it using gzip, some problem came and it stopped zipping. I rezipped and the problem went away.

**Comment by z5310969** [comment]
Hi Alex @alexdobin ,
I am trying to run STAR on CAVATICA using some mcf7 fastq.gz files from the ENA browser https://www.ebi.ac.uk/ena/browser/view/SRR22102317 
with this command 
`mkdir STAR && tar -xvf /sbgenomics/Projects/3d8ae4e1-b857-4347-88a2-25aa330d2f1e/Assets/gencode.v41.annotation.rsem-1.3.3.star-index-archive.tar -C STAR && STAR --outFileNamePrefix SRR22102317.hs38. --readFilesIn /sbgenomics/Projects/3d8ae4e1-b857-4347-88a2-25aa330d2f1e/MCF7/SRR22102317_1.fastq.gz /sbgenomics/Projects/3d8ae4e1-b857-4347-88a2-25aa330d2f1e/MCF7/SRR22102317_2.fastq.gz --genomeDir STAR --outFilterMultimapNmax 100 --outSAMattributes All --outSAMtype BAM Unsorted --readFilesCommand zcat --runMode alignReads --runThreadN 10 --sjdbOverhang 100 --winAnchorMultimapNmax 200`

and receive this error:

<img width="1952" height="257" alt="Image" src="https://github.com/user-attachments/assets/6a76b89e-95c3-4a9a-aa5d-8a9e746d1752" />

The files were obtained by importing the download links from ENA to CAVATICA.

I'm a bit lost on how to solve this problem given this message.

Regards,
Austin
