### ISSUE TITLE
Very low mapped reads %

### ISSUE THREAD

**Issue by rjg2186** [alexdobin/STAR#1057]
I have 30 samples of paired-end reads and after trimming the reads at 3' end for quality < 30, the read lengths vary between 120-145 in these 30 samples.

I tried to build the genome index with default parameters and aligned reads with below commands. The alignment rate is ~33% and ~65% reads unmapped too short.

Since the read lengths vary between the samples, for --sjdbOverhang, I did not give any specific value. Based on documentation it indicates the default is 99 for typical 2x100bp PE reads. 

I am not sure how to specify in my case since the read lengths vary for samples. Even between R1 and R2, they vary due to trimming. Building genome index for each sample would be tedious. 

Can you please suggest on how to handle this scenario.

Thanks

```
/STAR-2.7.5b/bin/Linux_x86_64/STAR --runThreadN 10 --runMode genomeGenerate --genomeDir /work_dir/STAR_index --genomeFastaFiles genome.fasta

/STAR-2.7.5b/bin/Linux_x86_64/STAR --runMode alignReads --runThreadN 10 --genomeDir /work_dir/STAR_index --sjdbGTFfile annotation.gtf --quantMode GeneCounts --readFilesCommand gunzip -c --readFilesIn sample_1_R1.fastq.gz sample_1_R2.fastq.gz
```

The Log out is shown below

```
                          Number of input reads |	46562047
                      Average input read length |	239
                                    UNIQUE READS:
                   Uniquely mapped reads number |	15361565
                        Uniquely mapped reads % |	32.99%
                          Average mapped length |	225.95
                       Number of splices: Total |	5960408
            Number of splices: Annotated (sjdb) |	4375851
                       Number of splices: GT/AG |	5719931
                       Number of splices: GC/AG |	66078
                       Number of splices: AT/AC |	2091
               Number of splices: Non-canonical |	172308
                      Mismatch rate per base, % |	1.29%
                         Deletion rate per base |	0.02%
                        Deletion average length |	2.17
                        Insertion rate per base |	0.01%
                       Insertion average length |	1.59
                             MULTI-MAPPING READS:
        Number of reads mapped to multiple loci |	703397
             % of reads mapped to multiple loci |	1.51%
        Number of reads mapped to too many loci |	26778
             % of reads mapped to too many loci |	0.06%
                                  UNMAPPED READS:
  Number of reads unmapped: too many mismatches |	0
       % of reads unmapped: too many mismatches |	0.00%
            Number of reads unmapped: too short |	30292275
                 % of reads unmapped: too short |	65.06%
                Number of reads unmapped: other |	178032
                     % of reads unmapped: other |	0.38%
                                  CHIMERIC READS:
                       Number of chimeric reads |	0
                            % of chimeric reads |	0.00%

```

**Comment by scseekers** [comment]
Even I have observed this lately for my samples as well. I am not sure that it's because I update to the newer STAR version or there was something fishy with my data.

**Comment by rjg2186** [comment]
@alexdobin 

Can you please let me know how the read alignment % (uniquely mapped reads %) is calculated. The genome that I have was denovo assembled and it has >10,000 scaffolds. The genome size is similar to human. Out of these, only around 1000 scaffolds has gene predictions.

When I use the complete genome for index and run STAR align, the uniquely mapped % is ~85% and when I use only the scaffolds with predicted genes (~1000 scaffolds), the uniquely mapped % drop to ~35% (as shown in previous post). 

But when I take a look in ReadsPerGene.out.tab file, for almost 90% genes, the gene counts are identical or very close from these two runs. But the % reads mapped is varying a lot.

Can you please let me know how the uniquely mapped reads % is calculated and --quantMode geneCounts is calculated. 

Thanks.

**Comment by scseekers** [comment]
Here @rjg2186 
>Log.final.out: summary mapping statistics after mapping job is complete, very useful for
quality control. The statistics are calculated for each read (single- or paired-end) and then
summed or averaged over all reads. Note that STAR counts a paired-end read as one read,
(unlike the samtools flagstat/idxstats, which count each mate separately). Most of the information is collected about the UNIQUE mappers (unlike samtools flagstat/idxstats which does not
separate unique or multi-mappers). Each splicing is counted in the numbers of splices, which
would correspond to summing the counts in SJ.out.tab. The mismatch/indel error rates are
calculated on a per base basis, i.e. as total number of mismatches/indels in all unique mappers
divided by the total number of mapped bases.

And the genecounts would estimate the readcounts like HTSeq-count in default mode(union) as described [here](https://htseq.readthedocs.io/en/release_0.11.1/count.html)

**Comment by alexdobin** [comment]
Hi @rjg2186 

my explanation would be like that: it seems like you have 50% of the reads mapping to scaffolds where there are no annotations. If you remove those scaffolds, you do not get those reads aligned, but all the reads that align to genes are still there, so genic counts do not change too much.

I guess I do not see the problem here, except that the annotations are incomplete. I think you have an opportunity here to discover new genes. :) 
It's best to align to the "whole" genome in order to avoid forcing reads to a few scaffolds, even if all of your "useful" reads are on a few scaffolds.

Cheers
Alex

**Comment by rjg2186** [comment]
Hi @alexdobin  and @scseekers 

Thanks a lot the info and suggestions.
