### ISSUE TITLE
Is there any way to estimate the memory usage of STAR?

### ISSUE THREAD

**Issue by altairwei** [alexdobin/STAR#1063]
I need to use STAR in a CWL workflow and this workflow will run on an HPC with torque batch system. If I know the size of the genome index and the size of the reads data, can I estimate how much memory STAR will use?

**Comment by alexdobin** [comment]
Hi Altair,

the total RAM should be close to the sum of this file sizes in the GenomeDir: Genome, SA and SAi
plus the Nthreads*--limitIObufferSize (=Nthreads*150e6 bytes by default).
I would add another ~1GB just to be safe.

Cheers
Alex

**Comment by altairwei** [comment]
The size of each file is as follows:

* Genome = 14G
* SA = 117G
* SAindex = 1.6G
* Nthreads = 6
* limitIObufferSize = 144M

RAM = 14G + 117G + 1.6G + 6×144M = 133.44G

This value is almost equal to the tip I was given when STAR failed to run before.

```
    EXITING: fatal error trying to allocate genome arrays, exception thrown: std::bad_alloc
    Possible cause 1: not enough RAM. Check if you have enough RAM 143904161277 bytes
    Possible cause 2: not enough virtual memory allowed with ulimit. SOLUTION: run ulimit -v 143904161277
```

That's great!

**Comment by alexdobin** [comment]
Hi Altair,

the calculation in the code is actually outdated, it does not add Nthreads*limitIObufferSize, rather it adds 2e9 bytes.
However, the results are pretty close. :)

Cheers
Alex
