### ISSUE TITLE
Makefile:112: Depend.list: No such file or directory

### ISSUE THREAD

**Issue by coraolpe** [alexdobin/STAR#1064]
Hi, 
I don't have much experience with compiling from source and I've tried reading on stack exchange etc for several hours now but everything I try doesn't work so I hope it's ok I post here. 
I have installed gcc using homebrew. 
Now within source I try to use:

make STARforMacStatic CXX=/usr/local/Cellar/gcc/10.2.0/

But I get:
Makefile:112: Depend.list: No such file or directory
/Library/Developer/CommandLineTools/usr/bin/make -C htslib lib-static
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o kfunc.o kfunc.c
error: unable to open output file 'kfunc.o': 'Permission denied'
1 error generated.
make[1]: *** [kfunc.o] Error 1
make: *** [htslib/libhts.a] Error 2

I would be super grateful for help.

Kind regards
Cora

**Comment by coraolpe** [comment]
Hi, after a few more hours of googling I found out what to do and I think I have managed to compile now so I'm closing this issue.

**Comment by alexdobin** [comment]
Hi @coraolpe 

if you do not mind sharing what you did to fix it, it may help other users.
I am not using Macs, so do not know much about them.

Cheers
Alex

**Comment by coraolpe** [comment]
Hi Alex,

so sorry, I am new to this and have completely gone against etiquette.
Here is what I had to do:
I had to be the owner of the directory that contains STAR such that I could write to stuff. so I used: (with olpe being me)

sudo chown -Rv olpe /path/to/directory 

once I did that I tried running the same make command and it worked!

best wishes
Cora

**Comment by alexdobin** [comment]
Hi Cora,

great, thanks for sharing it!
There is no strict etiquette, I did not mean to be pushy...
I am generally trying to encourage people to share their experiences.

Cheers
Alex
