### ISSUE TITLE
Proper usage to make tags that work with gatk

### ISSUE THREAD

**Issue by gevro** [alexdobin/STAR#1067]
What is the correct way to run STAR so that it generates tags such that the BAM files can work with gatk?
I've tried:
--outSAMattrRGline ID:sample_name SM:sample_name

However, gatk keeps throwing validation errors about the header of the BAM file made by STAR.

Since gatk is one of the most frequent downstream tools for calling variants, it would be helpful if STAR produced correctly formatted BAM files that gatk can use.

**Comment by rcosentino** [comment]
Hi, I am using STAR in combination with GATK. 
As default I am using:
--outSAMattrRGline ID:rg1 SM:sm1 LB=lib1 PL=illumina PU=unit1

not sure if all of them are required. But I think that ID SM and PL are the minimal requirement by GATK. 
Also remember to use:
--outSAMmapqUnique 60
to adjust the unique mapping quality to what GATK expects.
I hope it helps.
Best,
Raúl

**Comment by gevro** [comment]
Thank you!
