### ISSUE TITLE
STARsolo output bam UMI collapsed?

### ISSUE THREAD

**Issue by rcosentino** [alexdobin/STAR#1070]
Hi,
I am trying to use STARsolo output bam to call variants. My question is regarding the output bam. Are the reads containing the same UMI-barcode combination collapsed (i.e. there is only one read mapped for any of them)?
Cheers,

Raúl

**Comment by alexdobin** [comment]
Hi Raúl

no, the BAM file contains all reads, with UB tags displaying the (possibly error corrected) UMIs.

Cheers
Alex
