### ISSUE TITLE
STARsolo generates UMI Counts but returns Segmentation Fault

### ISSUE THREAD

**Issue by mvanmoerbeke** [alexdobin/STAR#1071]
Dear Alex

We are experiencing a segmentation fault when running STARsolo on a number of our samples. For these samples, it seems that the mapping and counting is performed as the matrix.mtx file is created although the .bam file has a file size of 0. Although STARsolo results in an error, a succesful mapping and counting occurs with STAR.

Could you maybe assist us in solving the segmentation fault?
I attach a sample for which we observed this error. Our samples consist of reads generated from 4 lanes with R1 consisting of a barcode and UMI and R2 representing the actual read. In addition, the log file and matrix.mtx file is also attached.

The used STARsolo command is:

`STAR --soloType Droplet --quantMode GeneCounts --genomeLoad LoadAndKeep --runThreadN 4 --outFilterMultimapNmax 1 --outSAMtype BAM SortedByCoordinate --soloCBstart 1 --soloCBlen 10 --soloUMIstart 11 --soloUMIlen 10 --soloBarcodeReadLength 0 --soloStrand Unstranded --soloFeatures Gene --genomeDir /app/sw/rnaseqpreproc/starReference/current/genomeIndex_HumanFullGenome_ERCC/ --limitBAMsortRAM 10000000000 --outReadsUnmapped Fastx --outSAMunmapped Within --outSAMattributes NH HI nM AS CR UR CB UB GX GN --soloCBwhitelist GAGACAAGGC.txt --outFileNamePrefix /STARsolo/GAGACAAGGC/ --readFilesIn GAGACAAGGC_lane1_R2_001.fastq,GAGACAAGGC_lane2_R2_001.fastq,GAGACAAGGC_lane3_R2_001.fastq,GAGACAAGGC_lane4_R2_001.fastq GAGACAAGGC_lane1_R1_001.fastq,GAGACAAGGC_lane2_R1_001.fastq,GAGACAAGGC_lane3_R1_001.fastq,GAGACAAGGC_lane4_R1_001.fastq
`

The used STAR command is

`STAR --quantMode GeneCounts --genomeLoad LoadAndKeep --runThreadN 4 --outFilterMultimapNmax 1 --outSAMtype BAM SortedByCoordinate Gene --genomeDir /app/sw/rnaseqpreproc/starReference/current/genomeIndex_HumanFullGenome_ERCC/ --limitBAMsortRAM 10000000000 --outReadsUnmapped Fastx --outSAMunmapped Within --outFileNamePrefix /STAR/GAGACAAGGC/ --readFilesIn GAGACAAGGC_lane1_R2_001.fastq,GAGACAAGGC_lane2_R2_001.fastq,GAGACAAGGC_lane3_R2_001.fastq,GAGACAAGGC_lane4_R2_001.fastq GAGACAAGGC_lane1_R1_001.fastq,GAGACAAGGC_lane2_R1_001.fastq,GAGACAAGGC_lane3_R1_001.fastq,GAGACAAGGC_lane4_R1_001.fastq
`

Thank you in advance!

[exampleData.zip](https://github.com/alexdobin/STAR/files/5464775/exampleData.zip)

All the best
Marijke

**Comment by alexdobin** [comment]
Hi Marijke,

this was a bug, thanks for reporting it!
Please try the recent patch from GitHub master:
https://github.com/alexdobin/STAR/archive/master.zip
Now it should run without problems on the dataset you sent me.

Cheers
Alex

**Comment by mvanmoerbeke** [comment]
Hi Alex

You're welcome!
Thank you very much for the fix! All our samples are now mapping successfully.

Thanks a lot!

All the best
Marijke

**Comment by alexdobin** [comment]
Hi Marijke,

great, thanks for testing it!

Cheers
Alex
