### ISSUE TITLE
Convert chimeric.out.junction to chimeric.out.sam after running STAR

### ISSUE THREAD

**Issue by alam-shahul** [alexdobin/STAR#1072]
Hello! Is there a script to convert chimeric.out.junction files to the chimeric.out.sam format? I need this for a downstream tool, but I did not run STAR with the `--chimOutType SeparateSAMold` flag the first time around on my dataset, and it will be painful to run it again.

**Comment by alexdobin** [comment]
Hi @alam-shahul 

no, unfortunately, this is not possible - Chimeric.out.junction does not contain all the necessary information to generate SAM.

Cheers
Alex

**Comment by apinharanda** [comment]
Hi Alex! What about the other way round? Have the sam but want the chimeric.out.junction. I ran --chimOutType SeparateSAMold but left the "Junctions" out..

Thank you in advance! 

Ana

**Comment by alexdobin** [comment]
Hi Ana,

this should be possible, but I do not have a script to do it. It's probably easiest to re-run mapping with the right chimeric output options.

Cheers
Alex

**Comment by apinharanda** [comment]
Hi Alex,

Thank you so much for the reply.
Will do.

Ana
