### ISSUE TITLE
Is there a maximum value for --outAnchorMultimapNmax  ? 

### ISSUE THREAD

**Issue by samiraghazali** [alexdobin/STAR#1073]
Dear Alex,

Interested in repetitive elements, I increased the parameter --outFilterMultimapNmax to 1000. And as recommended by you in TEtranscripts, I set the parameter --outAnchorMultimapNmax to 2000 (twice the value set for -outFilterMultimapNmax ). I thought it would allow STAR to search for all the possible seeds ( maximum 2000), if the entire read is mapped after this to more than 1000 locations, it is considered as unmapped and added to the category % of reads mapped to too many loci. However, using these parameters, 30% of my reads are unmapped for other reasons than too many mismatches or too short.

Keeping --outAnchorMultimapNmax by default, I obtained : 12% of reads mapped to multiple loci, 0% of reads mapped to too many loci and 5,42% of reads unmapped : other .

Would you please explain to me how does --outAnchorMultimapNmax affect the mapping ? Is there a maximum value for it same way as the minimum (50)?

Thank you in advance for your help

Samira

**Comment by alexdobin** [comment]
Hi Samira,

```--winAnchorMultimapNmax``` (not  --outAnchorMultimapNmax) determines the number of loci a seed (i.e. exactly matching part of the read can map to). If a read is supposed to map to N locations, then --winAnchorMultimapNmax has > N, 2*N is a good starting point.

If you make --outAnchorMultimapNmax too large, you might hit other limitations that prevent reads from being mapped - also it will slow down the mapping. This is why I recommend increasing it gradually and checking the results.
To prevent these limitations (if you really want to go far with the--outAnchorMultimapNmax), you can try to increase these parameters: 
```--alignWindowsPerReadNmax``` : from default 10000 
```--alignTranscriptsPerWindowNmax```: from default 100
```--seedPerWindowNmax```: from default 50
```--seedNoneLociPerWindow```: from default 10

You can also try --alignIntronMax 1 which will prohibit splicing. This may be needed for repeated elements mapping if they tend to appear within the standard splice window of ~600kb. If you are interested in spliced alignment, you will have to do a 2-step alignment: first, map with splicing allowed and small value of --outAnchorMultimapNmax, and then remap unmapped reads with large --outAnchorMultimapNmax and --alignIntronMax 1.

Cheers
Alex

**Comment by samiraghazali** [comment]
Dear Alex,

My problem is solved. Thank you for your help.

Best regards,

Samira

**Comment by samiraghazali** [comment]
Hi Alexandre,
I allow myself to send you this email because I need an opinion from
professional bioinformatician especially in alignment step given its
importance in the downstream analysis. Like recommended by you, I increased
progressively the parameter --seedPerWindowNmax till 1000 which gave me the
best results (according to me). I send you the statistics with the commands
I used  :
1. "--alignIntronMax 1 --outSAMprimaryFlag AllBestScore --
outFilterMultimapScoreRange 0 --outFilterMultimapNmax 500 --alignMatesGapMax
1000 --outReadsUnmapped Fastx --outMultimapperOrder Random" which gave me
[image: image.png]
2.  "--alignIntronMax 1 --outSAMprimaryFlag AllBestScore  --
outFilterMultimapScoreRange 0  --outFilterMultimapNmax 500 --
seedPerWindowNmax 1000 --winAnchorMultimapNmax 1000  --alignMatesGapMax
1000 --outReadsUnmapped Fastx  --outMultimapperOrder Random"
which gave me :
[image: image.png]
knowing that I am analysing ChIP-seq data, do you think that the parameters
I selected are good enough? Thank you in advance for your time and your
response.

Samira GHAZALI


Le mer. 11 nov. 2020 à 23:51, Alexander Dobin <notifications@github.com> a
écrit :

**Comment by alexdobin** [comment]
Hi Samira,

the image did not get attached, you would need to attach it from the GitHub website.
As you increase --seedPerWindowNmax parameter, do the % of unmapped saturate? If so, then your choice of parameters is good.

Cheers
Alex
