### ISSUE TITLE
STARlong on nanopore long reads RNAseq datasets?

### ISSUE THREAD

**Issue by JamalEH** [alexdobin/STAR#1076]
Dear Alex,

I have a nanopore long reads RNAseq dataset which I want to map against the human reference genome. Can I use STARlong utility for that? is the steps "index creation and alignment steps" are the same as using STAR for short RNA-seq reads?

Thank you so much in advance!

Best regards,
Jamal

**Comment by alexdobin** [comment]
Hi Jamal,

nanopore reads have high error rates, which STAR cannot deal with presently. At the moment, I would recommend minimap2.

Cheers
Alex

**Comment by JamalEH** [comment]
Dear Alex,

Thank you so much for your feedback!

Best regards,
Jamal.
