### ISSUE TITLE
EXITING because of FATAL ERROR in reads input: short read sequence line: 0

### ISSUE THREAD

**Issue by GGM652** [alexdobin/STAR#1077]
Hi, 
I realize that multiple issues regarding this error message have been opened and answered (and I read all of them) but I still can't figure out what's going on in my case. I am running Star from the terminal and when trying to run the following command 
`STAR --runMode alignReads --runThreadN 7 --outSAMstrandField intronMotif --outSAMtype BAM SortedByCoordinate --sjdbGTFfile ./hw1_annot.gtf --genomeDir ./STAR_index --readFilesIn hw1_reads.fasta --outFileNamePrefix ./bam/
`
I get this error:
`EXITING because of FATAL ERROR in reads input: short read sequence line: 0
Read Name=>read64025041/ENST00000418930
Read Sequence====
DEF_readNameLengthMax=50000
DEF_readSeqLengthMax=650`

Intersetingly, when I add the `--readFilesCommand gunzip -c` (which is something that worked in a different issue) it runs, but it doesn't do anything (see attached log). Note that the fasta-file is not zipped, which confuses me even more. 
I have tried setting `--genomeSAindexNbases 10` in the genome generation step - as suggested in another issue -  but that didn't help either.
I am pretty new to bioinformatics so I'm pretty lost here. Any help would be greatly appreciated. Thanks!
[Log.final.out.txt](https://github.com/alexdobin/STAR/files/5524187/Log.final.out.txt)

**Comment by alexdobin** [comment]
Hi @GGM652 

the --readFilesIn should be the files with the reads that you want to map, which is usually a FASTQ file, not FASTA. What are the reads that you are trying to map?

Cheers
Alex

**Comment by GGM652** [comment]
Hi @alexdobin,
turns out the file containing the reads was corrupted, which I couldnt understand for some time due to being a complete beginner. Apologies if I wasted your time and thanks a lot for getting back to me nonetheless.
Best.
