### ISSUE TITLE
STARsolo. Summary files not changing while changing "--soloUMIdedup" parameter

### ISSUE THREAD

**Issue by rcosentino** [alexdobin/STAR#1078]
Hi, 
I was trying out the effect of changing different barcode filtering and UMI filtering/deduplication parameters. To my surprise, for some cases, the summary file looked exactly the same.
For example using `--soloUMIdedup Exact` OR   `--soloUMIdedup 1MM_Directional` OR the default (which should be using `--soloUMIdedup 1MM_All`) lead to the exact same values in "summary.csv" and "Features.stats".

So I thought that changing these parameters was not having an effect, but then I checked the matrices and they are actually different and the direction of change makes sense to me.
UMIcounts:
default : 609951
Exact: 1258890
1MM_Directional: 655639

I tried playing around with other parameters like using `--soloCBmatchWLtype 1MM` or `--soloCBmatchWLtype Exact` or `--soloUMIfiltering MultiGeneUMI` and for these I saw, as expected, differences in summary files.

Could it be that for some reason the Summary file is still being made from the default settings in case of "--soloUMIdedup"?
Or am I missing something? Could you reproduce this? I am using STARv2.7.6

Best,

Raúl

**Comment by alexdobin** [comment]
Hi Raúl

thanks for pointing it out - you are correct, at the moment the stats in the Features.stats and summary.csv files are calculated for the ```--soloUMIdedup 1MM_All``` counting, even if the other counting type is used or the matrix output. I will fix this behavior in future releases.

Cheers
Alex

**Comment by francois-a** [comment]
Hi Alex,

It appears that this extends to the tags — I don't see a difference in 'CB' values between `--soloUMIdedup` set to `1MM_Directional` or `1MM_All`. Can you confirm that this is currently the case?

Best,
François

**Comment by alexdobin** [comment]
Hi François

you are talking about UB, not CB, right? CB (cell barcode) is not affected by UMI deduplication options.

For UB, indeed the output is taken from 1MM_All calculation - this will be fixed in the next release that I hope to push our this week.

Cheers
Alex

**Comment by francois-a** [comment]
Yes, sorry, I meant UB... thanks for the quick answer and the coming fix!

**Comment by alexdobin** [comment]
Hi Raúl and François

this issue was fixed in https://github.com/alexdobin/STAR/releases/tag/2.7.8a
The Summary.csv file now reflects the UMI deduplication and filtering options.

Also, new option ```--soloUMIdedup 1M_Directional_UMItools``` provides better agreement with UMItools "directional" deduplication scheme.

Cheers
Alex

**Comment by francois-a** [comment]
Hi Alex,

Many thanks for fixing this! Will test the new option shortly.

**Comment by rcosentino** [comment]
thank you, Alex!
