### ISSUE TITLE
Trimmomatic reads as input - >98% unmapped reads: too short

### ISSUE THREAD

**Issue by quimollo** [alexdobin/STAR#1080]
Hi Alex,
I'm analyzing single-cell RNAseq PE reads and trying to pipe pre-processed reads (Trimmomatic) to STAR but I get >98% of "reads unmapped: too short". 

I've checked the log file from STAR and the "Average input read length" is >140 bp. When checking the trimmed reads with FastQC their size is between 70 and 75 bp and the quality is above 30 in almost all read long. Both files (PE reads) for the same sample have the same number of lines.
On the other hand, when I run the same command on the raw reads and I get >80% of reads mapped.

Trimmomatic Command (inside a loop over samples, taking reads1 and reads2 files):
trimmomatic PE -threads $NUMCPUS $FASTQLOC/${reads1[$i]} $FASTQLOC/${reads1[$i]} $outR1paired $outR1unpaired $outR2paired $outR2unpaired ILLUMINACLIP:/path/to/NexteraPE-PE.fa:2:30:10:2:keepBothReads LEADING:20 TRAILING:20 MINLEN:36

STAR Indexing Command:
nohup STAR --runThreadN 10 --runMode genomeGenerate --genomeDir /output/path/to/STAR_IDX_75/ --genomeFastaFiles /path/to/GRCh38.primary_assembly.genome.fa --sjdbGTFfile /path/to/gencode.v35.annotation.gtf --sjdbOverhang 75 &> nohup_STARIDX75.out &

STAR Mapping Command (inside a loop over $outR1paired and $outR2paired files):
STAR --genomeDir $STAR_IDX --readFilesIn $file $file_r2 --readFilesCommand zcat --outFileNamePrefix $OUTDIR/$sample  --runThreadN $NUMCPUS --quantMode GeneCounts TranscriptomeSAM --sjdbGTFfile /data/kns601/GENOMES/GRCh38.p13_relase35/gencode.v35.annotation.gtf --outSAMtype BAM SortedByCoordinate --outSAMattributes Standard --outFilterMultimapNmax 1 --sjdbOverhang 75  --twopassMode Basic

As I've been reading in some of the issues here but I couldn't find the exact same problem. I guess it similar to some other issues where the error comes from the input file format, but I can't manage to solve it.

On the other hand, I've seen that it's possible to do read-preprocessing with STAR directly. Do you think I would get very different results when comparing to Trimmomatic?

Thanks! 
Quim

**Comment by alexdobin** [comment]
Hi Quim,

I do not use Trimmomatic so cannot comment if the parameters are correct.
Most likely the problem is that some of the reads are excluded in Read1 file but kept in the Read2 file. Please check that the order of trimmed reads in both files is the same - i.e. read ID lines (1,5,9...) coincide.

Cheers
Alex

**Comment by quimollo** [comment]
Hi Alex,

I've noticed that I had an error in the Trimmomatic code and I was using the two forward fastq files. ($FASTQLOC/${reads1[$i]} $FASTQLOC/${reads**1**[$i]} instead of $FASTQLOC/${reads1[$i]} $FASTQLOC/${reads**2**[$i]} ), so the identifiers where exactly the same and so were the sequences.

Once I changed that, I ran STAR with "--readFilesCommand **gunzip -c**" as "--readFilesCommand zcat" wasn't working for some reason.

Cheers,
Quim

I leave the commands for the record:

Trimmomatic:
$TRIM PE -threads 10 -phred33 $file $file_r2 ${OUTDIR}/${sample}_trim1P.fastq.gz ${OUTDIR}/${sample}_trim1U.fastq.gz ${OUTDIR}/${sample}_trim2P.fastq.gz ${OUTDIR}/${sample}_trim2U.fastq.gz ILLUMINACLIP:${TRIM_ADAPTERS}:2:30:10:2:keepBothReads LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 > "${OUTDIR}/${sample}_trimmomatic.log" 2>&1

Where:
$TRIM -> location of the Trimmomatic file
$file -> forward fastq raw read
$file_r2 -> reverse fastq raw read


STAR:
$STAR --genomeDir $STAR_IDX --readFilesIn $file $file_r2 --readFilesCommand gunzip -c --outFileNamePrefix ${OUTDIR}/${sample}_ --runThreadN 10 --quantMode GeneCounts TranscriptomeSAM --sjdbGTFfile $GTFFILE --outSAMtype BAM SortedByCoordinate --outSAMattributes Standard --outFilterMultimapNmax 1 --sjdbOverhang 75 --twopassMode Basic

Where:
$STAR -> location of STAR
$file -> forward trimmed paired read (${OUTDIR}/${sample}_trim1P.fastq.gz)
$file_r2 -> reverse trimmed paired read (${OUTDIR}/${sample}_trim2P.fastq.gz)
