### ISSUE TITLE
check that the path to genome files, specified in --genomeDir is correct and the files are present, and have user read permsissions

### ISSUE THREAD

**Issue by dandata123-tech** [alexdobin/STAR#1082]
Hi Alex,your work is really good!
I'am a green hand of STAR and when i use the STARsole i met some trouble
I use cellranger index as my genomeDir and it works well when i use cllranger
but i met error and the error is as [followed]

[log.out.docx](https://github.com/alexdobin/STAR/files/5542366/log.out.docx)
[log.out.docx](https://github.com/alexdobin/STAR/files/5542367/log.out.docx)

EXITING because of FATAL ERROR: could not open genome file /data3/cellranger/cellranger3.1/refdata-cellranger-GRCh38-3.0.0//genomeParameters.txt
SOLUTION: check that the path to genome files, specified in --genomeDir is correct and the files are present, and have user read permsissions

Nov 15 20:48:31 ...... FATAL ERROR, exiting

**Comment by dandata123-tech** [comment]
tha

**Comment by dandata123-tech** [comment]
thanks,I have solved the problem.
yours,Dan

**Comment by dandata123-tech** [comment]
sorry to interupt you again, and here is another problem,


[nuc2k.Log.out.docx](https://github.com/alexdobin/STAR/files/5542559/nuc2k.Log.out.docx)

EXITING because of FATAL ERROR: cannot insert sequence on the fly because of strand GstrandBit problem
SOLUTION: please contact STAR author at https://groups.google.com/forum/#!forum/rna-star

Nov 15 22:34:41 ...... FATAL ERROR, exiting

**Comment by alexdobin** [comment]
Hi @dandata123-tech 

please remove 
```
--sjdbGTFfile /data3/cellranger/cellranger4.0.0/refdata-gex-GRCh38-2020-A/genes/genes.gtf 
--genomeFastaFiles /data3/cellranger/cellranger4.0.0/refdata-gex-GRCh38-2020-A/fasta/genome.fa
```
from you command line - these are only used for genome generation step.

Cheers
Alex

**Comment by dandata123-tech** [comment]
thanks for replying me ,and i met another problem
[nuc2k.Log.out.docx](https://github.com/alexdobin/STAR/files/5559277/nuc2k.Log.out.docx)

**Comment by alexdobin** [comment]
Hi @dandata123-tech 

the files in ```--readFilesIn``` should be supplied in ```cDND_read Barcode_read``` order.
For 10X libraries, it means ```--readFilesIn Read2 Read1```

Cheers
Alex

**Comment by dandata123-tech** [comment]
thanks for replying, but the order i use is R2,R2,R2,R2,R1,R1,R1,R1,i wondering if the order is right?and when i use 10*,it seems the file is right

**Comment by dandata123-tech** [comment]
and if i get the bam file.could i use star with bam file directly?i want to get  --soloFeatures Gene GeneFull SJ this function,thaks a lot

**Comment by alexdobin** [comment]
Hi @dandata123-tech 

you have to have space(s) between R2 and R1 lists, i.e.
```--readFilesIn R2,R2,R2   R1,R1,R1```

Cheers
Alex

**Comment by dandata123-tech** [comment]
thanks for replying me ,i fix this problem,but 

> Nov 27 13:49:51 ..... started STAR run
Nov 27 13:49:51 ..... loading genome
Nov 27 13:52:45 ..... started mapping
Nov 27 13:52:45 ..... finished mapping
Nov 27 13:52:45 ..... started Solo counting
Nov 27 13:52:46 ..... finished Solo counting
Nov 27 13:52:46 ..... started sorting BAM
Nov 27 13:52:47 ..... finished successfully
but my file is empty and here is my logout

[nuc2k.Log.out.docx](https://github.com/alexdobin/STAR/files/5606187/nuc2k.Log.out.docx)
It is really kind of you
thanks

**Comment by alexdobin** [comment]
Hi @dandata123-tech 

there is this error message at the end of Log.out:
```EXITING: because of fatal INPUT ERROR: number of input files for mate2=5 is not equal to that for mate0=4
Make sure that the number of files in --readFilesIn is the same for both mates```
It should have appeared in the stdout as well - but it's always good to check Log.out for errors and warnings.

Cheers
Alex

**Comment by dandata123-tech** [comment]
thanks for replying me,but the number of file is same .May be i should check the original file
 
thanks,
Dan

**Comment by dandata123-tech** [comment]
i check the error 

> zcat/data1/sc_rna/190031U/190031U_56dhuGE/56dhuGE_S1_L001_R1_001.fastq.gz,/data1/sc_rna/190031U/190031U_56dhuGE/56dhuGE_S1_L002_R1_001.fastq.gz,/data1/sc_rna/190031U/190031U_56dhuGE,/56dhuGE_S1_L003_R1_001.fastq.gz,/data1/sc_rna/190031U/190031U_56dhuGE/56dhuGE_S1_L004_R1_001.fastq.gz: No such file or directory
gzip: /data1/sc_rna/190031U/190031U_56dhuGE/56dhuGE_S1_L001_R2_001.fastq.gz,/data1/sc_rna/190031U/190031U_56dhuGE/56dhuGE_S1_L002_R2_001.fastq.gz,/data1/sc_rna/190031U/190031U_56dhuGE/56dhuGE_S1_L003_R2_001.fastq.gz,/data1/sc_rna/190031U/190031U_56dhuGE/56dhuGE_S1_L004_R2_001.fastq.gz: No such file or directory


and i am sure the file ca work well because i use it run cellranger,and get the bam file 

here is my code

STAR --genomeDir /data2/starsole2 --soloType CB_UMI_Simple --soloCBwhitelist /data3/cellranger/cellranger3.1/cellranger-3.1.0/cellranger-cs/3.1.0/lib/python/cellranger/barcodes/737K-august-2016.txt --soloUMIlen 12 --readFilesIn <(zcat /data1/sc_rna/190031U/190031U_56dhuGE/56dhuGE_S1_L001_R2_001.fastq.gz,/data1/sc_rna/190031U/190031U_56dhuGE/56dhuGE_S1_L002_R2_001.fastq.gz,/data1/sc_rna/190031U/190031U_56dhuGE/56dhuGE_S1_L003_R2_001.fastq.gz,/data1/sc_rna/190031U/190031U_56dhuGE/56dhuGE_S1_L004_R2_001.fastq.gz) <(zcat/data1/sc_rna/190031U/190031U_56dhuGE/56dhuGE_S1_L001_R1_001.fastq.gz,/data1/sc_rna/190031U/190031U_56dhuGE/56dhuGE_S1_L002_R1_001.fastq.gz,/data1/sc_rna/190031U/190031U_56dhuGE,/56dhuGE_S1_L003_R1_001.fastq.gz,/data1/sc_rna/190031U/190031U_56dhuGE/56dhuGE_S1_L004_R1_001.fastq.gz) --soloFeatures Gene GeneFull SJ --outSAMattributes NH HI nM AS CR UR CB UB GX GN sS sQ sM --soloUMIfiltering MultiGeneUMI --soloCBmatchWLtype 1MM_multi_pseudocounts --outFileNamePrefix nuc2k. --outSAMtype BAM SortedByCoordinate
[nuc2k.Log.out.docx](https://github.com/alexdobin/STAR/files/5620757/nuc2k.Log.out.docx)

**Comment by alexdobin** [comment]
Hi @dandata123-tech 

If you are using process substitution <(), you need to have a space-separated list, not comma-separated:
```
--readFilesIn <(zcat /data1/sc_rna/190031U/190031U_56dhuGE/56dhuGE_S1_L001_R2_001.fastq.gz 
/data1/sc_rna/190031U/190031U_56dhuGE/56dhuGE_S1_L002_R2_001.fastq.gz /data1/sc_rna/190031U/190031U_56dhuGE/56dhuGE_S1_L003_R2_001.fastq.gz /data1/sc_rna/190031U/190031U_56dhuGE/56dhuGE_S1_L004_R2_001.fastq.gz)
<(zcat /data1/sc_rna/190031U/190031U_56dhuGE/56dhuGE_S1_L001_R1_001.fastq.gz /data1/sc_rna/190031U/190031U_56dhuGE/56dhuGE_S1_L002_R1_001.fastq.gz /data1/sc_rna/190031U/190031U_56dhuGE,/56dhuGE_S1_L003_R1_001.fastq.gz /data1/sc_rna/190031U/190031U_56dhuGE/56dhuGE_S1_L004_R1_001.fastq.gz) 
```
Cheers
Alex

**Comment by dandata123-tech** [comment]
It's really kind of you,no error any more.
I love STAR!

yours,
Dan

**Comment by dandata123-tech** [comment]
sorry to interrupt you again,
if i make space-seperate, it makes same mistake again
_EXITING because of FATAL ERROR in input read file: the total length of barcode sequence is 150 not equal to expected 28
Read ID=@A00262:475:H3C3CDSXY:3:1101:1108:1031 1 N 0   Sequence=ANTGAAGCATTGGGAGTCCTCATCAGACCCGCACTCGGAAGTCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
SOLUTION: make sure that the barcode read is the last file in --readFilesIn , and check that it has the correct formatting
          If UMI+CB length is not equal to the barcode read length, specify barcode read length with --soloBarcodeReadLength
_
 and here is my log.out file
[nuc2k.Log.out.docx](https://github.com/alexdobin/STAR/files/5640132/nuc2k.Log.out.docx)

**Comment by dandata123-tech** [comment]
and i tryed  other data too,
if  i use R2,R2,R2,R2 R1,R1,R1,R1 way ,error is 

**ReadAlignChunk_processChunks.cpp:201:processChunks** EXITING because of FATAL ERROR in input reads: unknown file format: the read ID should start with @ or > 


if i use <(zcat R2 R2 R2 R2) <(zcat R1 R1 R1 R1) way ,i met the problem 

**EXITING** because of FATAL ERROR in input read file: the total length of barcode sequence is 150 not equal to expected 28
Read ID=@A00869:148:HYV5YDSXX:1:1101:1570:1016 1 N 0   Sequence=AGCCAATCAGAGTGTGTTGAATGCTTTCTGAGATTCTGATCTGTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
SOLUTION: make sure that the barcode read is the last file in --readFilesIn , and check that it has the correct formatting
          If UMI+CB length is not equal to the barcode read length, specify barcode read length with --soloBarcodeReadLength

thanks,
yours
Dan

**Comment by dandata123-tech** [comment]
Hello Alex,
I follow your advise, and I check the format use bamtofastq  to transfer bam to standard R1,R2,and i get wrong again
here is my code **STAR --genomeDir /data2/starsole2 --soloType CB_UMI_Simple --soloCBwhitelist /data3/cellranger/cellranger3.1/cellranger-3.1.0/cellranger-cs/3.1.0/lib/python/cellranger/barcodes/737K-august-2016.txt --soloUMIlen 12 --readFilesIn /data3/bam/190031U_56dhuGE_0_1_H3C3CDSXY/bamtofastq_S1_L003_R2_001.fastq.gz,/data3/bam/190031U_56dhuGE_0_1_H3C3CDSXY/bamtofastq_S1_L003_R2_002.fastq.gz,/data3/bam/190031U_56dhuGE_0_1_H3C3CDSXY/bamtofastq_S1_L003_R2_003.fastq.gz,/data3/bam/190031U_56dhuGE_0_1_H3C3CDSXY/bamtofastq_S1_L003_R2_004.fastq.gz,/data3/bam/190031U_56dhuGE_0_1_H3C3CDSXY/bamtofastq_S1_L003_R2_005.fastq.gz,/data3/bam/190031U_56dhuGE_0_1_H3C3CDSXY/bamtofastq_S1_L003_R2_006.fastq.gz,/data3/bam/190031U_56dhuGE_0_1_H3C3CDSXY/bamtofastq_S1_L003_R2_007.fastq.gz,/data3/bam/190031U_56dhuGE_0_1_H3C3CDSXY/bamtofastq_S1_L003_R2_008.fastq.gz,/data3/bam/190031U_56dhuGE_0_1_H3C3CDSXY/bamtofastq_S1_L003_R2_009.fastq.gz,/data3/bam/190031U_56dhuGE_0_1_H3C3CDSXY/bamtofastq_S1_L003_R2_010.fastq.gz,/data3/bam/190031U_56dhuGE_0_1_H3C3CDSXY/bamtofastq_S1_L003_R2_011.fastq.gz /data3/bam/190031U_56dhuGE_0_1_H3C3CDSXY/bamtofastq_S1_L003_R1_001.fastq.gz,/data3/bam/190031U_56dhuGE_0_1_H3C3CDSXY/bamtofastq_S1_L003_R1_002.fastq.gz,/data3/bam/190031U_56dhuGE_0_1_H3C3CDSXY/bamtofastq_S1_L003_R1_003.fastq.gz,/data3/bam/190031U_56dhuGE_0_1_H3C3CDSXY/bamtofastq_S1_L003_R1_004.fastq.gz,/data3/bam/190031U_56dhuGE_0_1_H3C3CDSXY/bamtofastq_S1_L003_R1_005.fastq.gz,/data3/bam/190031U_56dhuGE_0_1_H3C3CDSXY/bamtofastq_S1_L003_R1_006.fastq.gz,/data3/bam/190031U_56dhuGE_0_1_H3C3CDSXY/bamtofastq_S1_L003_R1_007.fastq.gz,/data3/bam/190031U_56dhuGE_0_1_H3C3CDSXY/bamtofastq_S1_L003_R1_008.fastq.gz,/data3/bam/190031U_56dhuGE_0_1_H3C3CDSXY/bamtofastq_S1_L003_R1_009.fastq.gz,/data3/bam/190031U_56dhuGE_0_1_H3C3CDSXY/bamtofastq_S1_L003_R1_010.fastq.gz,/data3/bam/190031U_56dhuGE_0_1_H3C3CDSXY/bamtofastq_S1_L003_R1_011.fastq.gz --soloFeatures Gene GeneFull SJ --outSAMattributes NH HI nM AS CR UR CB UB GX GN sS sQ sM --soloUMIfiltering MultiGeneUMI --soloCBmatchWLtype 1MM_multi_pseudocounts --outFileNamePrefix nuc2k. --outSAMtype BAM SortedByCoordinate**

and here is my error

>  ReadAlignChunk_processChunks.cpp:201:processChunks EXITING because of FATAL ERROR in input reads: unknown file format: the read ID should start with @ or > 


[Uploading nuc2k.Log.out.docx…]()

**Comment by dandata123-tech** [comment]
Hi,Alex:
I use the data from 10*,and i get the same error again,here is my code 

> STAR --genomeDir /data2/starsole2 --soloType CB_UMI_Simple --soloCBwhitelist /data3/cellranger/cellranger3.1/cellranger-3.1.0/cellranger-cs/3.1.0/lib/python/cellranger/barcodes/737K-august-2016.txt --soloUMIlen 12 --readFilesIn /data3/bam/190031U_56dhuGE_0_1_H3C3CDSXY/pbmc_1k_v3_fastqs/pbmc_1k_v3_S1_L001_R2_001.fastq.gz,/data3/bam/190031U_56dhuGE_0_1_H3C3CDSXY/pbmc_1k_v3_fastqs/pbmc_1k_v3_S1_L002_R2_001.fastq.gz /data3/bam/190031U_56dhuGE_0_1_H3C3CDSXY/pbmc_1k_v3_fastqs/pbmc_1k_v3_S1_L001_R1_001.fastq.gz,/data3/bam/190031U_56dhuGE_0_1_H3C3CDSXY/pbmc_1k_v3_fastqs/pbmc_1k_v3_S1_L002_R1_001.fastq.gz --soloFeatures Gene GeneFull SJ --outSAMattributes NH HI nM AS CR UR CB UB GX GN sS sQ sM --soloUMIfiltering MultiGeneUMI --soloCBmatchWLtype 1MM_multi_pseudocounts --outFileNamePrefix nuc2k. --outSAMtype BAM SortedByCoordinate

and here is my error.

> ReadAlignChunk_processChunks.cpp:201:processChunks EXITING because of FATAL ERROR in input reads: unknown file format: the read ID should start with @ or > 

the error is the same as I showed to you in my data.

and i will put my log.out at the same time
[nuc2k.Log.out.docx](https://github.com/alexdobin/STAR/files/5657130/nuc2k.Log.out.docx)

**Comment by alexdobin** [comment]
Hi Dan,

before trying to map all reads together, please try mapping a pair of unzipped files:

```
gunzip -c /data3/bam/190031U_56dhuGE_0_1_H3C3CDSXY/pbmc_1k_v3_fastqs/pbmc_1k_v3_S1_L001_R2_001.fastq.gz > R2.fq
gunzip -c /data3/bam/190031U_56dhuGE_0_1_H3C3CDSXY/pbmc_1k_v3_fastqs/pbmc_1k_v3_S1_L001_R1_001.fastq.gz > R1.fq

STAR --genomeDir /data2/starsole2 --soloType CB_UMI_Simple --soloCBwhitelist /data3/cellranger/cellranger3.1/cellranger-3.1.0/cellranger-cs/3.1.0/lib/python/cellranger/barcodes/737K-august-2016.txt --soloUMIlen 12 --readFilesIn R2.fq R1.fq --soloFeatures Gene GeneFull SJ --outSAMattributes NH HI nM AS CR UR CB UB GX GN sS sQ sM --soloUMIfiltering MultiGeneUMI --soloCBmatchWLtype 1MM_multi_pseudocounts --outFileNamePrefix nuc2k. --outSAMtype BAM SortedByCoordinate
```

Cheers
Alex

**Comment by dandata123-tech** [comment]
Hi,Alex,
thanks a lot for replying me.I tried it and it works well if gunzip the fastq,gz. Ang I am trying to verify if this method works well when use with my data.

Yours,
Dan

**Comment by dandata123-tech** [comment]
Hi,Alex,
sorry to bother you again,when i work with unizip file,it works well and give me the final outcome.
I add 
 **--limitOutSJcollapsed** 2000000 --limitBAMsortRAM 64060816911
But my computer is 128G,and it supposed have enough memory for our data
then I get the outcome,and I met some trouble
first,I find the barcodes in my file is far less than the outcome from cellranger
second,I havn't found the spliced outcome that contain the isoform expression 
I wonder if is the add of the two function that lead to the wrong outcome

Yours,
Dan

**Comment by alexdobin** [comment]
Hi Dan,

have you mapped all the unzipped FASTQ files?
Please send me the outs/metrics_summary.csv and Solo.out/Gene/Summary.csv files.

Cheers
Alex

**Comment by dandata123-tech** [comment]
Hi,Alex,
Sorry for not replying in time,I rerun the data and the outcome is same,
here is the file you want

[Summary (copy).csv.txt](https://github.com/alexdobin/STAR/files/5722406/Summary.copy.csv.txt)
[nuc2k.Log.out.docx](https://github.com/alexdobin/STAR/files/5722417/nuc2k.Log.out.docx)
and i haven't found the file ' outs/metrics_summary.csv'

Yours,
Dan

**Comment by alexdobin** [comment]
Hi Dan,

it looks like these are 10X v3 libraries, so you need to use another barcode whitelist:
```3M-february-2018.txt```
This file is somewhere here:
```cellranger-3.1.0/cellranger-cs/3.1.0/lib/python/cellranger/barcodes/3M-february-2018.txt.gz```
Note that you need to unzip it for STARsolo.

Cheers
Alex

**Comment by dandata123-tech** [comment]
Hi,Alex,

Thanks a lot for replying me, I will try it soon.

Yours,
Dan

**Comment by alexdobin** [comment]
Hi Dan,

please unzip the file into a separate file
```
zcat 3M-february-2018.txt.gz > 3M-february-2018.txt
```
and supply the **unzipped** ```3M-february-2018.txt``` file to STARsolo.

Cheers
Alex

**Comment by dandata123-tech** [comment]
Hi,Alex:
happy new year!
i finally get the outcome from starsolo, the starsole barcodes number is 7009,and the cellranger is 7810,does it matter?
and the other question is  i haven't found the spliced outcome that contain the isoform expression,

Yours,
Dan

**Comment by alexdobin** [comment]
Hi Dan,

this difference is in the "filtered" cells - you can try the develop branch to get a better agreement with CellRanger:
https://github.com/alexdobin/STAR/issues/824#issuecomment-673607931

STARsolo does not presently calculate isoform expression. The splice junction counts are output in the Solo.out/SJ/ directory.

Cheers
Alex

**Comment by dandata123-tech** [comment]
Hi,Alex:
I can't see the feature in my file 
![Screenshot from 2021-01-10 15-01-22](https://user-images.githubusercontent.com/71436326/104116590-d290df00-5354-11eb-8b0d-c3ed440636b3.png)
and what is junction count mean? what it will show to use

Yours,Dan

**Comment by alexdobin** [comment]
Hi Dan,

for the features.tsv is a link to the SJ.out.tab which has coordinates of all detected junctions.
The matrix.mtx contains the counts of reads per junction per cell.

Cheers
Alex

**Comment by nolarifi** [comment]
> Hi Alex,your work is really good! I'am a green hand of STAR and when i use the STARsole i met some trouble I use cellranger index as my genomeDir and it works well when i use cllranger but i met error and the error is as [followed]
> 
> [log.out.docx](https://github.com/alexdobin/STAR/files/5542366/log.out.docx) [log.out.docx](https://github.com/alexdobin/STAR/files/5542367/log.out.docx)
> 
> EXITING because of FATAL ERROR: could not open genome file /data3/cellranger/cellranger3.1/refdata-cellranger-GRCh38-3.0.0//genomeParameters.txt SOLUTION: check that the path to genome files, specified in --genomeDir is correct and the files are present, and have user read permsissions
> 
> Nov 15 20:48:31 ...... FATAL ERROR, exiting

I have the same problem . How did u solve the problem plz

**Comment by alexdobin** [comment]
This is a problem with path or permission. Please check that genomeParameters.txt exists in the folder specified in ```--genomeDir``` and is readable.
