### ISSUE TITLE
RG tag are not added to BAM reads when using readFilesManifest

### ISSUE THREAD

**Issue by DimitriMeistermann** [alexdobin/STAR#1089]
Reads are properly aligned, however no read group tag is added. It is hence impossible to identify reads and execute tools such as *samtools split*.

STAR v2.7.6a

My command:

```bash
STAR --runThreadN 30 --genomeDir /path/to/GRCh38/STAR_INDEX --readFilesCommand zcat \
                --readFilesManifest /path/to/star_manifest.txt \
                --outFileNamePrefix  /path/to/STAR_ALIGN. --outSAMtype BAM Unsorted \
                 1>  /path/to/STAR_ALIGN.out 2>  /path/to/STAR_ALIGN.err
```
I run the command with these test files:

FASTQs:
* [D8_IVC2_E2_B1_66.fastq.gz](https://github.com/alexdobin/STAR/files/5609558/D8_IVC2_E2_B1_66.fastq.gz)
* [D8_IVC2_E2_B1_70.fastq.gz](https://github.com/alexdobin/STAR/files/5609559/D8_IVC2_E2_B1_70.fastq.gz)
* [D8_IVC2_E2_B1_81.fastq.gz](https://github.com/alexdobin/STAR/files/5609561/D8_IVC2_E2_B1_81.fastq.gz)
* [hv_D10_IVC5_E1_B1_29.fastq.gz](https://github.com/alexdobin/STAR/files/5609562/hv_D10_IVC5_E1_B1_29.fastq.gz)

manifest:
* [star_manifest.txt](https://github.com/alexdobin/STAR/files/5609560/star_manifest.txt)

**Comment by DimitriMeistermann** [comment]
I almost forgot to be polite :)

Cheers
Dimitri

**Comment by alexdobin** [comment]
Hi Dimitri,

for the read group taag output, you need to add ```RG``` to the ```--outSAMattributes``` list, e.g.
```--outSAMattributes NH HI AS nM RG```

Cheers
Alex

Cheers
Alex

**Comment by DimitriMeistermann** [comment]
Dear Alex,
It works perfectly, thank you for you support.

Best wishes

**Comment by AlexandraBomane** [comment]
Dear Alex,

Thank you for providing this helpful solution.
However, I observed that it is not possible to add "SM" in `--outSAMattributes` list,
Firstly, I would like to know why this attribute is not supported.
Secondly, when I add "RG" in `--outSAMattributes` list, the only attribute displayed in reads alignments is "ID", "SM" does not appear. Is there a reason for that?

Many thanks,
Alexandra
