### ISSUE TITLE
Segfault on read

### ISSUE THREAD

**Issue by roryk** [alexdobin/STAR#109]
Hi Alex,

I attached an example where STAR is segfaulting on a read. If you download the attached tar and run the run.sh script it should build a small index and do two mappings. One is a single read that works and the other is a single read from the same sample that causes STAR to segfault. I tried 2.5.0c and 2.5.1b and it has the same behavior.

[segfault-example.tar.gz](https://github.com/alexdobin/STAR/files/114961/segfault-example.tar.gz)

**Comment by alexdobin** [comment]
Hi Rory,

thanks for the nice test example!
Did it happen also when you mapped this read to full human genome, or just this small genome?
For a very small genome you would need to reduce --genomeSAindexNbases to log2(GenomeLength)/2 - 1, which is 6 for mitochondrion genome.
This is basically the k-mer that appears 4 time in the genome of this size (considering random sequences). Making this scaling automatic is on my TODO list for a long time.

Cheers
Alex
