### ISSUE TITLE
STARsolo for spliced and unspliced matrix from bam

### ISSUE THREAD

**Issue by crazyhottommy** [alexdobin/STAR#1090]
Hi Alex,

Is it possible to have the spliced and unpliced matrix from bam file generated from 10x cellranger for RNA velocity?
I do not want to realign the bam files.
btw, I see https://github.com/alexdobin/STAR/blob/master/docs/STARsolo.md#velocyto-splicedunsplicedambiguous-quantification

Thanks!
Tommy

**Comment by alexdobin** [comment]
Hi Tommy,

this is not possible at the moment, unfortunately - you would need to re-map the reads to get the velocity quantification.
I am about to release a new feature that will simplify the re-mapping: it will input the reads and barcodes directly from BAM files, without the need to convert them to fastqs.

Cheers
Alex

**Comment by crazyhottommy** [comment]
Thank you Alex. Look forward to that new version!

**Comment by alexdobin** [comment]
Hi Tommy,

the 2.7.8a version can read from BAM files - though it still does the full remapping.

Cheers
Alex

**Comment by crazyhottommy** [comment]
Thanks for the update, Alex!

**Comment by galaxyeee** [comment]
Hi, 
I have a question about this problem. Is it possible to input reads from SAM file that is output file after STAR mapping?
I did STARsolo mapping without  --soloFeatures Gene Velocyto.

**Comment by alexdobin** [comment]
Hi @galaxyeee 

no, STARsolo needs to be re-run with --soloFeatures Gene Velocyto

**Comment by galaxyeee** [comment]
Oh, Thank you for your help @alexdobin.

**Comment by jcdaneshmand** [comment]
> Hi Tommy,
> 
> the 2.7.8a version can read from BAM files - though it still does the full remapping.
> 
> Cheers Alex

Hi @alexdobin,

So is running something like this, impossible at this point? I have a cellranger bam, and I'm trying to get velocities by processing it with starsolo.  The whole process completes successfully, but there is no output other than the logs.

`    STAR \
      --runMode alignReads \
      --readFilesType SAM SE \
      --readFilesCommand "samtools view -F 0x100 -h" \
      --soloInputSAMattrBarcodeSeq CB UR \
      --readFilesIn "$BAM_FILE" \
      --genomeDir "$GENOME_DIR" \
      --runThreadN "$THREADS" \
      --soloFeatures Gene Velocyto \
      --outSAMtype None \
      --outFileNamePrefix "$OUT_DIR/" \
      --outTmpDir /tmp/starsolo
`

Thank you so much for your help.
