### ISSUE TITLE
Miss @rg tag in the header when use .bam as input for mapping with STAR 2.7.6a

### ISSUE THREAD

**Issue by ysu2015** [alexdobin/STAR#1092]
Hi,

I am using star 2.7.6a, and found that if the BAM file that is input to STAR has an @rg record in the header, but that is removed from the output. But the @rg is useful for my downstream analysis. Is there a way that I could have it  back?

Thank you so much in advance.
Y

**Comment by alexdobin** [comment]
Hi @ysu2015 

if you supply STAR with the SAM header, all tags from it (except chromosomes which are replaced) will be copied. If you are starting with BAM, you would need ``` samtools view -h ``` :
``` STAR ... --readFilesIn A.bam --readFilesCommand samtools view -h --readFilesType SAM SE ```

Cheers
Alex

**Comment by ysu2015** [comment]
Hi Alex,
Thank you so much for your response. I will give a try.
Bests,
Y
