### ISSUE TITLE
Need help with genome generate.

### ISSUE THREAD

**Issue by Kappy2** [alexdobin/STAR#1093]
Hi!
First, I have no idea what I am doing... 

I am trying to generate the genome index and I keep getting the same error. I know I am messing up somewhere with the files, but I don't know which files to use. I am using rnor 6.0 (rat). I tried FASTA and GTF files from ensembl and from NCBI... same error message. It seems like whatever is in the file is not in the same format needed to create the index. Any insight would be great!

STAR --runThreadN 6 --runMode genomeGenerate --genomeDir ~/analysis --genomeFastaFiles /gpfs/scratch/kipoon/FASTA/GCA_000001895.4_Rnor_6.0_cds_from_genomic.fna --sjdbGTFfile /gpfs/scratch/kipoon/FASTA/GCA_000001895.4_Rnor_6.0_genomic.gtf --sjdbOverhang 100
Dec 01 14:23:35 ..... started STAR run
!!!!! WARNING: Could not move Log.out file from ./Log.out into /gpfs/home/kipoon/analysis/Log.out. Will keep ./Log.out

Dec 01 14:23:35 ... starting to generate Genome files
Dec 01 14:23:35 ..... processing annotations GTF

Fatal INPUT FILE error, no valid exon lines in the GTF file: /gpfs/scratch/kipoon/FASTA/GCA_000001895.4_Rnor_6.0_genomic.gtf
Solution: check the formatting of the GTF file. One likely cause is the difference in chromosome naming between GTF and FASTA file.

Dec 01 14:23:35 ...... FATAL ERROR, exiting

**Comment by brianpenghe** [comment]
Same question. Anyone know how to solve it?

**Comment by alexdobin** [comment]
Hi @brianpenghe 

could you please open a new issue and describe it?

**Comment by brianpenghe** [comment]
Yes my description is here: https://github.com/alexdobin/STAR/issues/357#issuecomment-1107916053
