### ISSUE TITLE
Reads of varying length

### ISSUE THREAD

**Issue by Elena-Everatt** [alexdobin/STAR#1094]
Hello,

Some advice would be very useful: I have lots of samples of very different read lengths (as they come from different projects), and these lengths vary from 50 to 300. Would it be ok to use a single index for all of them, generated with the default value max(ReadLength)-1?

Best,
Elena

**Comment by alexdobin** [comment]
Hi Elena,

for reads ranging from 50 to 300, I would use the default value  ``` --sjdbOverhang 100 ```.

Cheers
Alex

**Comment by Elena-Everatt** [comment]
Thank you very much.
