### ISSUE TITLE
[Question] How to avoid output alignments bigger than the read length?

### ISSUE THREAD

**Issue by edsonmachado** [alexdobin/STAR#1096]
Hi Alex, 

I'm working on a genome annotation project for which I am mapping short RNA-Seq from single-end libraries of 50 bp reads. I'm a little confused about some STAR alignments results, in which the length of the resultant alignment segment is extremely bigger than the read length. 

Is it possible to avoid these big alignments? Could you please help me?

I'm sorry if I lose some basic aspect of the STAR workflow.

Here is an example of the output (in bold the big alignments that I don't want in the output):

CHR     Start    End      Name            Quality    Strand
Chr1    741      792      LB1.79505817    255        +
Chr1    741      792      LB1.144725391   255        +
Chr1    741      792      LB1.62809328    255        +
Chr1    741      792      LB1.13313206    255        +
Chr1    744      795      LB1.45334584    0          +
**Chr1    744      26374    LB1.45334584    0          +
Chr1    744      37493    LB1.45334584    0          +
Chr1    744      44408    LB1.45334584    0          +
Chr1    744      86964    LB1.45334584    0          +
Chr1    744      125629   LB1.45334584    0          +
Chr1    744      144314   LB1.45334584    0          +
Chr1    744      151916   LB1.45334584    0          +
Chr1    744      160402   LB1.45334584    0          +
Chr1    744      185792   LB1.45334584    0          +
Chr1    744      234666   LB1.45334584    0          +
Chr1    744      250085   LB1.45334584    0          +**
Chr1    744      795      LB1.41983505    255        +
Chr1    744      795      LB1.16707165    255        +
Chr1    750      801      LB1.82401630    255        +

And the STAR parameters that I'm using:

--outSAMtype BAM Unsorted
--outSJfilterReads Unique
--outFilterMultimapNmax 1000
--outFilterMismatchNmax 2
--outFilterScoreMinOverLread 0.9
--outFilterMatchNminOverLread 0.9

Best regards.

**Comment by alexdobin** [comment]
Hi Edson,

these alignments must be spliced - you can check that by looking at the CIGAR string in BAM, which contains N operation (genomic gap) for spliced alignments. While most small non-cding RNAs should not be spliced, you can still get some spliced reads in small-RN-seq libraries - e.g. short fragments of mRNAs. If you want to completely prohibit splicing, please use 
```--alignIntronMax 1```

Cheers
Alex

**Comment by edsonmachado** [comment]
Hi Alex,

Yes, I need to prohibit splicing in the alignment output. I'm sorry about didn't be too explicit with my question, but I'm just a computer scientist struggling with some particularities of the biological world =)

By using `--alignIntronMax 1` I got exactly the output that I want.

Many thanks!
