### ISSUE TITLE
STAR running error

### ISSUE THREAD

**Issue by tf1993614** [alexdobin/STAR#1098]
Hi,

When I ran STAR on my Uni's cluster, it presents one error as shown below. 

/hpcfs/users/a1763076/project_ovary/scripts/cromwell-executions/RNApipeline/02ba7863-325b-453f-9e30-38353547c9e3/call-align/execution/script: **line 23: 195665 Segmentation fault**     

Next, I also checked the Log.progression file and it shows information below.

 
![屏幕截图 2020-12-10 140248](https://user-images.githubusercontent.com/61369770/101718153-90c00f00-3af0-11eb-9b3e-ce55b9eef1c2.png)

It seems that mapping does well. If so, why system gives out above error message.

Could you give me a solution to fix this problem.

Thanks and I am looking forward to hearing from you .

**Comment by alexdobin** [comment]
Hi @tf1993614 

please send me the Log.out file of the failed run.

Cheers
Alex

**Comment by tf1993614** [comment]
[Log.out.txt](https://github.com/alexdobin/STAR/files/5699377/Log.out.txt)

Hi Alex,

Thanks for your response. I have attached the Log.out file.

I think mapping is pretty alright. But when the program intends to sort it, the segmentation fault comes out.

Another person also reported this problem in issue #942. She gave me one suggestion to just use one thread for mapping and sorting. I am trying that. Hopefully, it will work.

Cheers,
Feng

**Comment by alexdobin** [comment]
Hi Feng,

the attached file looks like the stdout of the run script. STAR should have generated Log.out file in the output directory - please send me that file. Using fewer sorting threads might indeed help, e.g. --outBAMsortingThreadN 3 .
Also, you can output unsorted BAM and then sort it with samtools, it may be more efficient.

Cheers
Alex

**Comment by tf1993614** [comment]
Hi Alexdobin,

Thank you for your response. 

I solved out this problem when I just used one thread for sorting. Maybe you could add more suggestive information in the STAR program when this error comes out, such as "please try use less thread for sorting" . It will be very helpful for a newbee in Bioinformatics like me.  To be honest, this small problem got me stuck here for almost 2 weeks. Fortunately, I finally settled it down. 

Christmas is coming soon and have a good holiday.

Thank you so much for your help again.

Feng

**Comment by alexdobin** [comment]
Hi Feng,

thanks for letting me know the problem got resolved. Such issues are user/system-dependent, and it's hard for me to anticipate which solutions will work. I will add some suggestions to the manual.

Cheers
Alex
