### ISSUE TITLE
ReadAlignChunk_processChunks.cpp:201:processChunks EXITING because of FATAL ERROR in input reads: unknown file format: the read ID should start with @ or > 

### ISSUE THREAD

**Issue by krabio** [alexdobin/STAR#1101]
Dear all, 
I am running STAR on 16 samples, and on one of them i get this error on pass 2 (it did not fail in genomegenerate step).
I have seen a similar error showed up before, but i am running a more recent version of STAR (STAR-2.7.5c) than the one mentioned (2.7.0), and i am using --readFilesCommand zcat. When i run the same file with  --readMapNumber 1 or even --readMapNumber 100000 it does not crash. I am assuming it is some kind of end of file error in my fastq file, but i fail to find it. 
Star has run fine for all other samples. 
Any help would be appreciated,

**Comment by alexdobin** [comment]
Hi @krabio 

this certainly indicates the problem with the FASTQ file(s), so you may want to check them.
There are tools out there that can do it. To check what 1,5,9th ... lines start with @, you can do something like:
```
zcat fastq.gz | awk 'NR%4==1 && $1!~/^@/ {print; print NR; exit}'
```
which should print the erroneous line and its line number.

Cheers
Alex

**Comment by AcharSri** [comment]
> Hi @krabio
> 
> this certainly indicates the problem with the FASTQ file(s), so you may want to check them.
> There are tools out there that can do it. To check what 1,5,9th ... lines start with @, you can do something like:
> 
> ```
> zcat fastq.gz | awk 'NR%4==1 && $1!~/^@/ {print; print NR; exit}'
> ```
> 
> which should print the erroneous line and its line number.
> 
> Cheers
> Alex

Hi Alex,
Even I am facing similar error. I was able to print the erroneous line and its line number. What is the next step that I need to do?

Kindly, help me out.
Sridevi

**Comment by alexdobin** [comment]
Hi Sridevi,

if your fastq file has the ID line (i.e. lines 1,5,9,...) that does not start with @, it means the file was not properly generate or got corrupted. The best thing is to go back to the source of this file.

Cheers
Alex

**Comment by AcharSri** [comment]
> Hi Sridevi,
> 
> if your fastq file has the ID line (i.e. lines 1,5,9,...) that does not start with @, it means the file was not properly generate or got corrupted. The best thing is to go back to the source of this file.
> 
> Cheers
> Alex

Thank you, Alex. 
Yes, you are right. My fastq.gz files were corrupted.
