### ISSUE TITLE
Memory Issues when run STAR with Chimeric options

### ISSUE THREAD

**Issue by seahearman** [alexdobin/STAR#1105]
Hi,
I am using a machine with 32GB memory. When I tested the star aligner with Chimeric options, the process can be easily crashed. Is there any way to make it use a little bit less memory? 
Here is my script (basically copy-paste from STAR-Fusion page):
STAR \
--genomeDir Human.B38.Gencode.V33 \
--runThreadN 4 \
--readFilesIn sample_1.fastq.gz sample_2.fastq.gz \
--outReadsUnmapped None \
--twopassMode Basic \
--readFilesCommand "gunzip -c" \
--outSAMstrandField intronMotif \
--outSAMunmapped Within \
--limitBAMsortRAM 24000000 \
--outSAMattrRGline ID:GRPundef PU:unit1 SM:sample_name PL:illumina LB:lib_unknown \
--outFileNamePrefix sample.Fusion. \
--chimSegmentMin 12 \
--chimJunctionOverhangMin 8 \
--chimOutJunctionFormat 1 \
--alignSJDBoverhangMin 10 \
--alignMatesGapMax 100000 \
--alignIntronMax 100000 \
--alignSJstitchMismatchNmax 5 -1 5 5 \
--chimMultimapScoreRange 3 \
--chimScoreJunctionNonGTAG -4 \
--chimMultimapNmax 20 \
--chimNonchimScoreDropMin 10 \
--peOverlapNbasesMin 12 \
--peOverlapMMp 0.1 \
--alignInsertionFlush Right \
--alignSplicedMateMapLminOverLmate 0 \
--alignSplicedMateMapLmin 30

I am testing using very a small RNAseq dataset. you can find them here:
[RNAseq](http://omicsoft.com/downloads/data/tutorial/RNASeq.zip)
I am a little worried that with normal RNAseq samples, whether it can never finish the jobs with 32GB memory.

**Comment by alexdobin** [comment]
Hi @seahearman 

please send me the Log.out file.

Cheers
Alex

**Comment by jhl667** [comment]
Similar issue for me, using STAR-Fusion controlled settings (v2.7.2b).  Ran about 100 samples, for 2 of them progress ends up getting stuck around 78.5% and then ultimately dumping.  I am currently giving them about 96GB RAM.

**Comment by jhl667** [comment]
@alexdobin If you have not yet received a Log.out file, I'm happy to send mine.

**Comment by alexdobin** [comment]
Hi @jhl667 

please try 2.7.6a or later version - a memory leak problem in the earlier may have been causing this issue.
If it still does not work, please send me the Log.out file.

For @seahearman example, I am getting ~33GB RAM usage with 2.7.7a, there might be a way to reduce it to below 32GB, but it will be tough to fit in 32GB RAM. The best option would be to generate the genome with --genomeSAsparseD 2 .

Cheers
Alex

**Comment by jhl667** [comment]
Thanks @alexdobin, I will do that.  Do you know whether STAR-Fusion will complain about this?  In their compatibility matrix, 2.7.2b is still listed as the required pairing with the latest STAR-Fusion.  Of course, I suppose I will find out after I do some testing whether this works, but I thought you might know off the top of your head.

**Comment by jhl667** [comment]
Upgrading to 2.7.8a does indeed allow for the STAR process to finish.  Thanks for your help!
