### ISSUE TITLE
EXITING because of FATAL PARAMETER ERROR: limitGenomeGenerateRAM=31000000000is too small for your genome

### ISSUE THREAD

**Issue by mfaleevs** [alexdobin/STAR#1109]
Hello! Sorry to post once more, as I know this has been asked before, but when I try and run my index my genome, it gives me this error. I tried to add the limitgenomegenerate command and yet it still wont do it, along with several other parameters suggested on the internet. I have the latest version of STAR installed as well so that cant be the issue either. The strange thing is is that when monitoring my RAM, it doesnt get all used up, which makes me think there is an issue somewhere in my commands? 
Any help would be appreciated and many thanks!

```
STAR --runThreadN 4 --runMode genomeGenerate --genomeDir genome_index --genomeFastaFiles /Users/mfaleeva/Desktop/Homo_sapiens.GRCh38.dna.toplevel.fa --sjdbGTFfile /Users/mfaleeva/Desktop/Homo_sapiens.GRCh38.102.gtf--limitGenomeGenerateRAM=168632691637
--genomeChrBinNbits=14--genomeSAsparseD=3/sjdbOverhang 99
```

**Comment by alexdobin** [comment]
Hi @mfaleevs 

there should not be any "=" symbols in the command line, only spaces to separate different options, i.e.:
```
STAR --runThreadN 4 --runMode genomeGenerate --genomeDir genome_index --genomeFastaFiles /Users/mfaleeva/Desktop/Homo_sapiens.GRCh38.dna.toplevel.fa --sjdbGTFfile /Users/mfaleeva/Desktop/Homo_sapiens.GRCh38.102.gtf --limitGenomeGenerateRAM 168632691637
--genomeChrBinNbits 14 --genomeSAsparseD 3 --sjdbOverhang 99
```
Also, I strongly recommend against using the .toplevel. FASTA file, which contains patches and alternative loci, which unnecessarily increase genome size. The correct file to use is .primary_assembly. , e.g.,
ftp://ftp.ensembl.org/pub/release-102/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz

Cheers
Alex

**Comment by mfaleevs** [comment]
Thank you so much! That fixed the problem :)
