### ISSUE TITLE
Problem with STAR 2.51 (std::bad_alloc)

### ISSUE THREAD

**Issue by xandinho2468** [alexdobin/STAR#111]
Hi

I have an Ubuntu machine (15.10) and i'm trying to get STAR to generate a genome index

It's always giving this error 
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

Does anyone has this problem?

**Comment by roryk** [comment]
std::bad_alloc is from not having enough memory on the machine to generate the index. You need about 30-40 GB to generate an index for the human genome, for example.

**Comment by haodongchen** [comment]
Hi, I had the same problem but fixed it by increasing mem to 32G. However, it has been running for more than 72h and is still running. How long will it take to generate an index for the human genome?

**Comment by xandinho2468** [comment]
Wait... but I have 128GB for a genome half the size of the human genome...  do I need to specify the max mem in the program options ?

**Comment by roryk** [comment]
Does your genome have a lot of contigs?

**Comment by roryk** [comment]
Setting the maximum memory should help.

@haodongchen if you pass STAR more threads to use, it will run more quickly. It does take a while if you run it with only one thread.

**Comment by alexdobin** [comment]
Hi @xandinho2468, @haodongchen
Rory's suggestions are good, but please be more specific: what parameters did you use, size of your genome/number of contigs etc. Posting your Log.out file is the best way to communicate all the details.

Cheers
Alex
