### ISSUE TITLE
Confused how to run 2-pass mapping in most recent STAR version

### ISSUE THREAD

**Issue by callumparr** [alexdobin/STAR#1110]
I want to extract junctions from some public short-read libraries I've downloaded. There are 3x 150bp PE TruSeq mRNA libraries. I wanted to do all sample 2-pass but actually wasn't sure when it is best to do manual all-sample or per sample 1st pass. Or when to do the automated mode using 2pass flag. So far I have done 2-pass manually but do I need to regenerate the genome index before doing 2nd mapping? So far I have done the folllowing: 

Generate genome from ensembl GRCm38 and GTF file version 99.

```
/home/callum/STAR-2.7.7a/bin/Linux_x86_64/STAR --runThreadN 8 --runMode genomeGenerate --genomeDir Genome_files/mm10 --genomeFastaFiles Genome_files/Mus_musculus.GRCm38.dna.primary_assembly.fa --sjdbGTFfile cDNA_DESeq2/ReferenceData/Mus_musculus.GRCm38.99.gtf --sjdbOverhang 149
```

I did first round of mapping of all samples together. 

```
STAR-2.7.7a/bin/Linux_x86_64/STAR --runThreadN 1 --genomeDir $HOME/Genome_files/mm10 --readFilesIn ERR2680378_1.fastq.gz,ERR3363655_1.fastq.gz,ERR3363656_1.fastq.gz ERR2680378_2.fastq.gz,ERR3363655_2.fastq.gz,ERR3363656_2.fastq.gz --readFilesCommand gunzip -c --outSAMattrRGline ID:ERR2680378 , ID:ERR3363655 , ID:ERR3363656 --outSAMtype BAM SortedByCoordinate --outFileNamePrefix MM_brain_cDNA_TruSeq_stranded
```

Then filter the SJout.tab file to remove MT junctions and junctions that are supported by a couple of unique reads and/or multimappers. Then repeat the mapping with the `--sjdbFileChrStartEnd `

```
/home/callum/STAR-2.7.7a/bin/Linux_x86_64/STAR --runThreadN 1 --genomeDir $HOME/Genome_files/mm10 --readFilesIn ERR2680378_1.fastq.gz,ERR3363655_1.fastq.gz,ERR3363656_1.fastq.gz ERR2680378_2.fastq.gz,ERR3363655_2.fastq.gz,ERR3363656_2.fastq.gz --readFilesCommand gunzip -c --outSAMattrRGline ID:ERR2680378 , ID:ERR3363655 , ID:ERR3363656 --outSAMtype BAM SortedByCoordinate --outFileNamePrefix MM_brain_cDNA_TruSeq_stranded.2ndPass --sjdbFileChrStartEnd MM_brain_TruSeq_final.filtered.SJout.tab
```

**Comment by alexdobin** [comment]
Hi @callumparr 

what you did is exactly the "manual" 2-pass run. 
The ```--sjdbFileChrStartEnd MM_brain_TruSeq_final.filtered.SJout.tab``` option re-generates genome on-the-fly inserting the junctions detected in the 1st pass.

Cheers
Alex

**Comment by callumparr** [comment]
OK thank you.
