### ISSUE TITLE
starsolo: reproducing the filtered count matrix using the BAM

### ISSUE THREAD

**Issue by Lioscro** [alexdobin/STAR#1116]
Hi! Thanks for responding to my previous question regarding read assignments for velocyto.

I've been investigating ways to parse the alignment BAM file output from starsolo. I used the following options when invoking `STAR`:
```
--soloFeatures Gene
--outSAMmultNmax 1
--outSAMtype BAM SortedByCoordinate
--outSAMattributes MD GX GN CR CY UR UY CB UB
--soloCBwhitelist [10x version 2 barcode whitelist]
--outFilterScoreMinOverLread 0.3
--outFilterMatchNminOverLread 0.3
```
from which I get a `sortedByCoord.out.bam` BAM file, along with a filtered count matrix in `Solo.out/Gene/filtered`. I have been trying to reproduce the filtered count matrix solely using the BAM, but I keep getting inconsistencies, and was wondering if you could help me figure this out! Here is my procedure so far:
1. For each mapped read in the BAM, extract the `GX`, `CB`, and `UB` tags. If any of these are missing, skip the read.
2. For every `CB`, `GX` pair, count the number of unique `UB`s.

Here is a plot from my test data of log1p counts, where the x axis is the counts from the filtered count matrix, and the y axis is my reconstruction.
![image](https://user-images.githubusercontent.com/1281521/104248841-47891500-5438-11eb-87da-c0c1f6195f79.png)

I am trying to reconstruct the count matrix because I need to work with individual reads (specifically, how many of each type of mutation are present in the reads) and be able to map those back to a cell and gene.

Thanks in advance!

**Comment by alexdobin** [comment]
Hi Joseph,

the BAM file is consistent with the ```Solo.out/Gene/raw/matrix.mtx``` in my tests.

You would need to omit ```--outSAMmultNmax 1```, since some multimappers can be assigned to gene - if only one alignment is consistent with a gene, or multiple alignments are consistent with the same gene. ```--outSAMmultNmax 1``` only outputs one alignment for multimappers, which may not be the one assigned to a gene (GX tag).

Otherwise, your procedure should work.

Cheers
Alex

**Comment by Lioscro** [comment]
Hi, @alexdobin, thanks for your answer.
From my understanding, `--outSAMmultNmax 1` only outputs the highest-scoring alignment. Does this mean the highest-scoring alignment for a read may not be assigned to a gene (GX tag), but one of its subsequent alignments may do so, and in this case, STAR counts the read to the gene for which the read has a smaller alignment score, but has an assigned gene?

**Comment by alexdobin** [comment]
Hi Joseph,

```--outSAMmultNmax 1``` output one alignment per read quasi-randomly selecting from the top-scoring alignments.
By default, top-scoring alignments include those with scores >= topScore-1.
Morover, most multimapping alignments have exactly the same scores = topScore, and ```--outSAMmultNmax 1``` does not take into account the presence of the GX tag.

Things should work fine if you omit this option when mapping. In most cases, only one of the multimapper's alignments will have the GX tag. In some cases, where multiple alignments map to the same gene, you can have several alignments with the same GX tag - however, they will all have the same UB, so they will collapse into one count for that gene.

If this does not solve the discrepancy, I can share my script to re-generate the count matrix from BAM.

Cheers
Alex

**Comment by Lioscro** [comment]
Hi, @alexdobin, that worked perfectly for my 10x data!
One more question: does this mean that if a read is a multimapper to two different genes, each alignment is considered an independent count (count + 1 for each of the two genes)? How is this dealt with for Smart-seq alignments, which do not have UMIs?

**Comment by alexdobin** [comment]
Hi Joseph,

great, thanks for confirming it!

A multimapper that map to two or more different genes is not counted in the matrix.mtx, and are not getting the GX tag, so it's still consistent. This rule applies to both Droplet and Smart-seq solo types.

For Smart-seq, even though they do not have UMIs, they can be deduplicated based on the alignment coordinates, with the ```--soloUMIdedup Exact``` option.

Cheers
Alex
