### ISSUE TITLE
Multi-mappings [Illumina paired-end]

### ISSUE THREAD

**Issue by brguez** [alexdobin/STAR#1119]
Hi STAR team, 

I am interested into read pairs where one mate uniquely aligns on the reference while the other has multi-mappings as correspond to a L1 sequence (there are 1000s on the reference). 

After running STAR with default parameters, it appears that those multi-mappings are not reported in the bam file. I wonder if you could tell me which parameters I should tweak to get those reads aligned. 

Thanks in advance

Best, 
Berni

**Comment by alexdobin** [comment]
Hi Berni,

STAR will only output concordant paired alignments, i.e. mates aligning on the same chromosome, within a certain distance (~600k by default, can be controlled by ```--alignMatesGapMax```) and on the opposite strands.
If you want to get discordant alignment, the best way is to map the mate1 and mate2 separately.
Detecting alignments to 1000 loci would require increasing ```----outFilterMultimapNmax``` and ```--winAnchorMultimapNmax```, though a large value for the latter would result in a slow mapping speed, and may also require tweaking other parameters. Other strategies may be preferable for such highly multimapping reads, i.e. mapping to a consensus sequence.

Cheers
Alex

**Comment by brguez** [comment]
Hi Alex, 

Thanks a lot for your extremely valuable input. It is clear now. 

Best, 
Berni
