### ISSUE TITLE
Library dependency issues

### ISSUE THREAD

**Issue by blikzen** [alexdobin/STAR#112]
Your installation instructions no longer work. I've tried on multiple fresh installs of ubuntu and debian.

./STAR: /usr/lib/x86_64-linux-gnu/libgomp.so.1: version `GOMP_4.0' not found (required by ./STAR)
./STAR: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./STAR)
./STAR: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ./STAR)
./STAR: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./STAR)

$ locate libstdc++.so.6
/usr/lib/x86_64-linux-gnu/libstdc++.so.6
/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19

**Comment by blikzen** [comment]
the static binary build still works, but the other don't. i thought it had something to do with the gcc so i installed the test version of gcc, and that seems to solve the first set of dependency issues, but now complains about GLIBCXX_3.4.21

./STAR: relocation error: ./STAR: symbol _ZTVNSt7__cxx1119basic_istringstreamIcSt11char_traitsIcESaIcEEE, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference

i tried linking to libstdc++.so.6.0.19, but no luck

**Comment by alexdobin** [comment]
Hi @blikzen,

I have compile this version with gcc 5.3.0, whcih might create compatibility issues if you have older glibc. If static version does not create substantial problems (like RAM overusage), it should be safe to use. Also, it's pretty simple to compile STAR from source - simply do `make` from the source/ directory.

Cheers
Alex
