### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by been9312** [alexdobin/STAR#1121]
An error occurred during the compilation according to the manual.

cd source
sudo apt install make
make STAR
make -C htslib lib-static
make[1]: Entering directory '/home/asb/STAR-2.7.7a/source/htslib'
cc -g -Wall -02 -l. -DSAMTOOLS=1 -c -o kfunc.o kfunc.c
make[1]: cc: Command not found
make[1]: *** [Makefile:99: kfun.o] Error 127
make[1]: Leaving directory 'home/asb/STAR-2.7.7a/source/htslib'
Makefile:111: Depend.list: No such file or directory
make: *** [Makefile:121: htslib/libhts.a] Error 2

**Comment by Gaodelike** [comment]
And how to issue this problem?

**Comment by been9312** [comment]
> And how to issue this problem?

I just did not install gcc
After install gcc with brew, the problem was solved.
