### ISSUE TITLE
Understanding MD tag produced by STAR

### ISSUE THREAD

**Issue by sagnikbanerjee15** [alexdobin/STAR#1122]
Hello,

Here is an example of an alignment produced by STAR (version 2.7.7a).

```
read_id1	0	1	23342300	255	10M1609N28M3D29M1I31M1S	*	0	0	TGAAAAAAAAAAAAAAAGTTTGGGTTTTTAAAAGAAGTCTTCTTTTTTTTGGGTTTATGGGCTGAAAAAAATTGTTGTGTTTTTTGTATTTTATTTTTTG	IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII	NH:i:1	HI:i:1	AS:i:79	nM:i:2	NM:i:6	MD:Z:38^ATC0T2T56	jM:B:c,2	jI:B:i,23342310,23343918	XS:A:-
```

I am having trouble understanding the MD flag. From what I understand, there are 38 matches to the reference followed by 3 deletions (of the reference), 1 mismatch, 2 matches, 1 mismatch, and finally 56 matches. When I add up the matches and mismatches, I am getting 98 (38+1+2+1+56). The length of the sequence is 99 (after removing the right soft clip). I think I am missing something but shouldn't the two lengths be the same?

Thank you.

**Comment by alexdobin** [comment]
Hi Sagnik,

there is also ```1I``` inserted base - i.e. extra base in the read, which makes the total 98+1=99.

Cheers
Alex

**Comment by sagnikbanerjee15** [comment]
Oh, I see. Thanks for pointing it out.
