### ISSUE TITLE
chimScore options

### ISSUE THREAD

**Issue by helloeoh001** [alexdobin/STAR#1123]
Hi Alex,

I am optrimizing the options of STAR to detect gene fusions with the data generated from cancer patients
For the options regarding chimeric alignment, 'chimScore' seems affect the senistivity to chimera.
Could you breifly explain how to calculrate 'chimScore' ?
Is that the alignmet score of chimeric segments?
Below is my understanding about the sensitivity to chimera by increasgin or decreasing the chimScore options.
Is that right?
![image](https://user-images.githubusercontent.com/16658129/105154120-8dd32800-5b4c-11eb-9b41-0a622b9c2cef.png)

**Comment by alexdobin** [comment]
Hi @helloeoh001 

chimScore is calculated as a sum of alignment scores from the two chimeric segments. The maximum score is the length of the reads (sum of mates' lengths for PE reads).

```--chimScoreMin``` is the required minimum chimScore. Increasing it reduces sensitivity but increases precision of output chimeras.

```--chimScoreDropMax``` is the maximum reduction in the chimScore with respect to the read length (i.e. max possible chimScore). Increasing it increases sensitivity but reduces precision.

```--chimNonchimScoreDropMin``` controls the maximum score of the best **non-chimeric** alignment. If the best **non-chimeric** alignment has the score < (readLength-chimNonchimScoreDropMin), only then the chimeric stitching is performed. Increasing it reduces sensitivity but increases precision.

Cheers
Alex

**Comment by helloeoh001** [comment]
Hi Alex,

Thank you so much for clarifying that!!!

Best wishes,

Ensel
