### ISSUE TITLE
Segmentation fault (core dumped) error in STAR 2pass 

### ISSUE THREAD

**Issue by zhaouu** [alexdobin/STAR#1124]
Hi Alex,

I've used STAR for RNAseq alignments. However, I'm getting segfault errors. 
```
Jan 20 21:41:07 ..... started STAR run
Jan 20 21:41:07 ..... loading genome
Jan 20 21:41:26 ..... loading variations VCF
Jan 20 21:42:31 ..... inserting junctions into the genome indices
Jan 20 21:48:23 ..... started mapping

gzip: stdout: Broken pipe

gzip: stdout: Broken pipe
Segmentation fault (core dumped)
```
[NM_STAR.Log.out.log](https://github.com/alexdobin/STAR/files/5842851/NM_STAR.Log.out.log)

But when I run sample file of fastq files, it can be run successfully.
```
zcat /public/home/xbxu/DATA_130/Data_Hybrid/Hybrid_RNA-seq_ZH_224sample/NM_RRB19418-V_1.clean.fq.gz|head -n 40000 > ~/temp/NM_1.fq
zcat /public/home/xbxu/DATA_130/Data_Hybrid/Hybrid_RNA-seq_ZH_224sample/NM_RRB19418-V_2.clean.fq.gz|head -n 40000 > ~/temp/NM_2.fq
(base) [hzhao@c03n07 ASE]$ /public/home/hzhao/anaconda3/bin/STAR --runThreadN 1 --genomeDir /public/home/hzhao/data/Hybrid_panicle/ASE/star_index --readFilesIn ~/temp/NM_1.fq.gz ~/temp/NM_2.fq.gz --readFilesCommand gunzip -c --outFileNamePrefix ~/temp/NM_STAR. --genomeTransformOutput SAM SJ --outSAMtype BAM Unsorted --sjdbFileChrStartEnd star_map/F1010_M14_pass1/SJ.out.filtered.tab star_map/F1010_M12_pass1/SJ.out.filtered.tab  --outSAMmapqUnique 60 --waspOutputMode SAMtag --varVCFfile /public/home/hzhao/data/Hybrid_panicle/genotypes/VCFs/STAR_WASP_snp.vcf --outSAMattrRGline ID:NM SM:NM PL:PL:ILLUMINA --limitSjdbInsertNsj 9000000
Jan 20 22:01:47 ..... started STAR run
Jan 20 22:01:47 ..... loading genome
Jan 20 22:01:53 ..... loading variations VCF
Jan 20 22:01:55 ..... inserting junctions into the genome indices
Jan 20 22:02:57 ..... started mapping
Jan 20 22:03:01 ..... finished mapping
Jan 20 22:03:01 ..... finished successfully

```
[NM_STAR.Log.smaple.log](https://github.com/alexdobin/STAR/files/5842925/NM_STAR.Log.smaple.log)

I am very confused about this, can you please give me some advice?
Thanks.

**Comment by zhaouu** [comment]
When I remove the --genomeTransformOutput SAM SJ parameter, the program works fine, maybe it's a bug in the program?

**Comment by alexdobin** [comment]
Hi @zhaouu 

correct, ```--genomeTransformOutput SAM SJ``` should not be used for normal RNA-seq mapping. It's only used with "consensus" genome mapping.

Cheers
Alex

**Comment by zhaouu** [comment]
> Hi @zhaouu
> 
> correct, `--genomeTransformOutput SAM SJ` should not be used for normal RNA-seq mapping. It's only used with "consensus" genome mapping.
> 
> Cheers
> Alex

Thank you very much for your reply. I did use "consensus" genome mapping. I generated the genome index using --genomeTransformVCF. But in mapping, some samples are not available because of the --genomeTransformOutput SAM SJ parameter, but others run fine.

`{STAR} --runThreadN {threads} --runMode genomeGenerate --genomeDir {output.index} --genomeTransformVCF {consensus_vcf} --genomeTransformType Haploid --genomeSAindexNbases {genomeSAindexNbases} --genomeFastaFiles {input.ref} --sjdbGTFfile {input.gtf} --sjdbOverhang 100`

**Comment by alexdobin** [comment]
Hi @zhaouu 

presently, the consensus genome mapping does not work with the ```--waspOutputMode``` and ```--varVCFfile``` options. So you either need to omit them for consensus genome mapping, or use standard genome with these options.

Cheers
Alex
