### ISSUE TITLE
Big difference in BAM sizes created in two ways: STAR-> BAM and STAR->SAM->(samtools)BAM

### ISSUE THREAD

**Issue by mkazanov** [alexdobin/STAR#1127]
Hi Alex,

I tried to create BAM file in two ways:

1. Using STAR with `--chimOutType WithinBAM` and `--outSAMtype BAM Unsorted`

2. Create SAM file using STAR with `--chimOutType SeparateSAMold` and then to create BAM file
using `samtools sort`.

I expected that two BAM files should be equal in size, but they sizes were 4-times different:
12G if BAM was created in STAR, and 3G if BAM created from SAM using samtools.
Could you suggest what is the reason?

Thanks

**Comment by alexdobin** [comment]
Hi Marat,

the 1st file is unsorted, and the 2nd one is sorted, and sorted BAM files are compressed much better - this probably explains the differences you see. 

Note, that there differences in how chimeric alignments are recorded with ```--genomeTransformOutput SAM SJ ``` and ```--genomeTransformOutput SAM SJ ```.

Cheers
Alex

**Comment by mkazanov** [comment]
Hi Alex,

I found that `--outBAMcompression` parameter was set to `0`.
This possible was the reason for big size of .bam file.
When I changed it to `--outBAMcompression 10` the size of the file decreased substantially even for  `--outSAMtype BAM Unsorted` option. And with  '--outSAMtype BAM SortedByCoordinate` it becomes smaller, almost as for `samtools sort`.

Thanks!

**Comment by alexdobin** [comment]
Hi Marat,

that makes sense, thanks for letting me know!

Cheers
Alex
