### ISSUE TITLE
Nested exons cause STAR to report improper transcript lenghts

### ISSUE THREAD

**Issue by uros-sipetic** [alexdobin/STAR#1128]
Hey, I ran into a really weird scenario :) 
Basically, I was using a non-model GTF (HPV type 16), and one of the genes looked like this:
![hpv_exon_problem](https://user-images.githubusercontent.com/16819349/105347420-2b7b3580-5be7-11eb-8d07-46fc7611b5bf.png)
Essentially, the first exon covers the whole gene, while the other two are located inside the first one. 
STAR finished building the index archive at first without errors, and I am able to align reads like this, but then further downstream errors come up (with RSEM specifically). 

Then by looking at STAR Genome Generate logs and STAR index files, it turns out that the reported length for this particular transcript was not correct, i.e. instead of being 7598-7125, it was further decreased by the total length of the overlapping exons, which essentially caused reads to fall of the ends of the transcript, since it's length was less than the actual length. 

Since this was a non-model GTF, I just deleted these exons and continued my analysis, but figured to report this if it's something that could be addressed in any way. 
I tried this with STAR versions 2.6.0c and 2.7.3a

**Comment by alexdobin** [comment]
Hi @uros-sipetic 

this is a mistake in the GTF - all 3 exons belong to the same transcript, but the exons that belong to the same transcript cannot overlap. If you look in the Log.out file from the genome generation, you should see WARNINGs about it.
You can fix it by choosing a different transcript_id for the first exon

Cheers
Alex

**Comment by uros-sipetic** [comment]
Yeah, thanks Alex! I understood it as a mistake in the GTF as well, and the WARNINGs in the Log.out from the Genome Generate step helped me debug this. Just figured to report it here, as I saw others having similar issues in RSEM, which happens because these exons-within-exons (which shouldn't happen as you said), so hopefully it will help someone

**Comment by alexdobin** [comment]
Thanks! I probably should completely drop transcripts with overlapping exons.

**Comment by uros-sipetic** [comment]
Hm.. so, what would you suggest in my case above?
I still want to find the expression of the gene in the example I gave (and coincidentally, since the first exon covers the whole gene and the transcript, I can use tools like RSEM which quantifies on transcript level and then summarizes to gene level). This will give me the same transcript and gene level expressions, but I'm fine with that. 
Removing this transcript will then... make RSEM not quantify this gene at all, correct?

**Comment by alexdobin** [comment]
Hi @uros-sipetic 

if you are willing to manually change the GTF, you could modify the transcript_id for the large exon so that it represents a different transcript, e.g. ```transcript_id "transcript_HpV16gp1_A"```. Then you will to re-generate the genome for STAR and RSEM, and re-run both.

Cheers
Alex
