### ISSUE TITLE
starsolo core dump after error

### ISSUE THREAD

**Issue by zhangguy** [alexdobin/STAR#1129]
Hi @alexdobin ,

I'm trying to run some single-cell data. My read 1 is trimmed to various length, and I encountered this error and core dump if I have read1 entries that are very short, although I did --soloBarcodeReadLength 0 
```
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr
```
I tried 2.7.7a and 2.7.5c, both are giving the same error, and I made fresh index. 
This is my running command:
```
index=GRCh38-gencode-v35/STAR2.7.7a_index/star
STAR \
    --soloType CB_UMI_Simple \
    --soloCBwhitelist 3M-february-2018.txt \
    --soloCBstart 1 \
    --soloCBlen 16 \
    --soloUMIstart 17 \
    --soloUMIlen 12 \
    --soloBarcodeReadLength 0 \
    --runThreadN 16 \
    --soloFeatures Gene SJ GeneFull \
    --genomeDir $index \
    --soloUMIfiltering MultiGeneUMI \
    --soloCellFilter None \
    --outFileNamePrefix test_ \
    --readFilesCommand zcat --outSAMtype BAM SortedByCoordinate \
    --readFilesIn $r2 $r1
```
Attached are a pair of fastq file, and this is the problematic reads ```@K00345:145:HFVFVBBXY:1:1119:20811:33615 1:N:0:TTCAGGTG```

I understand that I can pre-filter my fastq file, but wondering if it is possible to add some internal checking in STAR?

Thank you very much.

[r2.fastq.gz](https://github.com/alexdobin/STAR/files/5859460/r2.fastq.gz)
[r1.fastq.gz](https://github.com/alexdobin/STAR/files/5859461/r1.fastq.gz)

**Comment by alexdobin** [comment]
Hi @zhangguy 

I will add such a check, but I am not sure why would you want to trim the barcode read?

Cheers
Alex

**Comment by zhangguy** [comment]
> Hi @zhangguy
> 
> I will add such a check, but I am not sure why would you want to trim the barcode read?
> 
> Cheers
> Alex

Thanks very much Alex. Indeed it doesn't make sense to trim the barcode read, it is just sometimes we got data from CRO or collaborators that use standard RNAseq preprocessing pipelines.

**Comment by alexdobin** [comment]
Hi @zhangguy 

this issue was fixed in https://github.com/alexdobin/STAR/releases/tag/2.7.8a.

Cheers
Alex
