### ISSUE TITLE
Default value for readSeqLengthMax

### ISSUE THREAD

**Issue by druvus** [alexdobin/STAR#113]
Hi, 
I have some bacterial dataset that was generated using the MiSeq 600 cycles kit so I have compiled STAR using a higher readSeqLengthMax value. Would it be possible to increase the default value to 650 in next release to allow analysis of data from the complete set range of Illumina kits out of the box or would it effect the analysis in some way?

**Comment by alexdobin** [comment]
Hi Andreas,

made the change. This value does not affect the mapping results. Its main purpose is to point that for long reads the STARlong version is preferrable. How did the mapping go with 2x300 reads. For bacteria, it's probably OK, but it would be very slow for big genome and long reads.

Cheers
Alex

**Comment by druvus** [comment]
Thanks Alex, 
the dataset is quite small so it finish relatively fast. However I have not done any testing to check how much faster it would run if I cut the sequences in advance. I will try to squeeze in some comparisons later.

The MiSeq is mainly used for screening and testing so I think it will never be used for any large-scale RNA-seq studies. 

/Andreas
