### ISSUE TITLE
What cells are being used for summary statistics in <featureType>/Summary.csv ?

### ISSUE THREAD

**Issue by ColeWunderlich** [alexdobin/STAR#1132]
There are several cell-based metrics given in the `Summary.csv` file for each feature type (example below for `GeneFull`).  I was wondering what sort of cells these metrics are derived from:  all `CB` that passed the white list, or only `CB` that pass both the whitelist and the cell filtration step (ie 'true' cells).  

----
Example 
```
Reads in  Cells Mapped to Unique GeneFulls
Fraction of Reads in Cells
Mean Reads per Cell
Median Reads per Cell
UMIs in Cells
Mean UMI per Cell
Median UMI per Cell
Mean GeneFulls per Cell
Median GeneFulls per Cell
Total GeneFulls Detected
```

**Comment by alexdobin** [comment]
Hi Cole,

all these metrics are calculated with respect to the cells that passed filtering.

Cheers
Alex

**Comment by ColeWunderlich** [comment]
Hey Alex,

Sorry for the slow response. Just to make sure I understand, by filtering you mean elbow-plot filtering, not white list filtering, correct?

Cole

**Comment by alexdobin** [comment]
Hi Cole,

correct, filtering (a.k.a. cell calling) by total UMI counts per cell, recorded in Solo.out/GeneFull/filtered/ .

Cheers
Alex

**Comment by ColeWunderlich** [comment]
Awesome, thanks Alex!
