### ISSUE TITLE
supplementary linked to anchor instead of representative when insert size equals read length

### ISSUE THREAD

**Issue by suhrig** [alexdobin/STAR#1135]
Hi Alex,

With paired-end data, a chimeric fragment gives rise to three SAM records: the supplementary, the representative and the anchor. The supplementary is always linked to the representative by means of a `SA` tag and vice versa. In most cases, the representative can easily be identified as the read that overlaps with the fusion breakpoint. However, when the insert size is small, it happens that both the anchor and the representative overlap with the fusion breakpoint. In the extreme case (insert size == read length), the anchor and the representative overlap with the fusion breakpoint by the same number of bases, because one is simply the reverse complement of the other, such that both have the same alignment coordinates. I noticed that in this particular edge case, STAR does not consistently link the supplementary to the representative. Instead, about half the time (randomly?), the supplementary is linked to the anchor. Here is an example, where STAR gave me two different alignments for the same pair of reads between different runs:

Correct (supplementary linked to representative):

```
TESTREAD 2113    chr4    25676680        255     23M65H  chr6    117324351       0       AACCATTAGCAGAGAGGCTCAGG FFFFFFFFFFFFFFFFFFFFFFF NH:i:1  HI:i:1  AS:i:22 nM:i:0  NM:i:0  SA:Z:chr6,117324351,-,65M23S,255,0;
TESTREAD 163     chr6    117324351       255     65M23S  =       117324351       65      AACAACCAGAAATATTCCAACTATAATAGTAAGTATGAAACTTGTTTCTGGTATCCAAAAATCATCCTGAGCCTCTCTGCTAATGGTT AFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF6FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF NH:i:1  HI:i:1  AS:i:128        nM:i:0  NM:i:0
TESTREAD 83      chr6    117324351       255     65M23S  =       117324351       -65     AACAACCAGAAATATTCCAACTATAATAGTAAGTATGAAACTTGTTTCTGGTATCCAAAAATCATCCTGAGCCTCTCTGCTAATGGTT FFFFFFFFFFAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF NH:i:1  HI:i:1  AS:i:128        nM:i:0  NM:i:0  SA:Z:chr4,25676680,+,23M65H,255,0;
```

Incorrect (supplementary linked to anchor):

```
TESTREAD 2225    chr4    25676680        255     23M65H  chr6    117324351       0       AACCATTAGCAGAGAGGCTCAGG FFFFFFFFFFFFFFFFFFFFFFF NH:i:1  HI:i:1  AS:i:0  nM:i:0  NM:i:0  SA:Z:chr6,117324351,+,65M23S,255,0;
TESTREAD 163     chr6    117324351       255     65M23S  =       117324351       65      AACAACCAGAAATATTCCAACTATAATAGTAAGTATGAAACTTGTTTCTGGTATCCAAAAATCATCCTGAGCCTCTCTGCTAATGGTT AFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF6FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF NH:i:1  HI:i:1  AS:i:0  nM:i:0  NM:i:0  SA:Z:chr4,25676680,-,23M65H,255,0;
TESTREAD 83      chr6    117324351       255     65M23S  =       117324351       -65     AACAACCAGAAATATTCCAACTATAATAGTAAGTATGAAACTTGTTTCTGGTATCCAAAAATCATCCTGAGCCTCTCTGCTAATGGTT FFFFFFFFFFAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF NH:i:1  HI:i:1  AS:i:0  nM:i:0  NM:i:0
```

I suspect that this inconsistent behavior has something to do with paired-end overlap merging (`--peOverlapNbasesMin`). I suspect that after performing a chimeric alignment with the merged read, when the reads are unmerged again, the supplementary gets linked to the wrong mate by accident, because the unmerging step cannot distinguish between mate1 and mate2, since both have the same sequence.

It is important to note that the linking to representative or anchor is in fact deterministic, i.e., when I run STAR with the exact same input data and parameters, the output is identical (at least in my tests). However, when I shuffle the input FastQs or align just a single problematic read (for debugging), it can happen that STAR links some supplementaries to anchors, which were previously linked to representatives, and vice versa. Moreover, I noticed that a lot more incorrect linkings happen, when the argument of `--chimMultimapNmax` is greater than 1. In other words, the problem was already present with the old chimeric alignment algorithm, but there must be another bug in the new chimeric alignment algorithm that aggravated the issue. Another observation I made is also worth mentioning: I tried to debug the code myself. For the sake of debugging, I inserted a bunch of status messages via `cerr` into the function `ReadAlign::peOverlapChimericSEtoPE` to get some insight into what is going wrong (without success, though). The messages definitely did not change any of the logic. However, depending on whether the status messages were there or not, STAR produced different output. I suspect that some variables related to the linking of supplementary and representative are not initialized properly. When I inserted the status messages, the binary code must have changed in a way that they were initialized differently. STAR still behaved deterministically, i.e., consecutive runs with the same binary gave the same result, but the binaries with vs. without status messages produced different outputs. This may be worth keeping in mind when trying to debug the issue.

This edge case is probably not relevant in the majority of cases, because it is statistically unlikely that the insert size is exactly identical to the read length. However, I recently came across a library with an average insert size that was smaller than the read length. I had to trim the adapters, because STAR would discard most reads as `unmappable, too short` otherwise. This resulted in FastQ files where 90% of the reads in FastQ1 were identical to the reads in FastQ2. And then the problem affected a large fraction of the data all of a sudden. It may be worth fixing this inconsistent behavior of STAR for such samples, because about half of the data of such samples becomes unusable due to having an invalid format.

I prepared [an example pair of FastA files](https://github.com/alexdobin/STAR/files/5900427/paired_fasta_files.zip) with lots of chimeric reads, all of which match the described edge case (read length == insert size). I cannot give you a specific example read that produces an incorrect alignment, because as explained above, the behavior is not consistent and depends on the binary and the exact input data (and the parameters, of course). So your output may be different from mine. But once you have alignments, you can use the following command to extract anchors that were linked to the supplementary. There should be plenty.

```
samtools view Aligned.out.bam | gawk '!and($2,2048) && /SA:Z:/ && ($6~/^[0-9]+M[0-9]+S$/ && !and($2,16) || $6~/^[0-9]+S[0-9]+M$/ && and($2,16))'
```

I used the following parameters with Gencode36 as assembly/annotation. I guess the important parameters are `--peOverlapNbasesMin 10`, `--chimOutType WithinBAM HardClip` and `--chimMultimapNmax 0` or `100`.

```
--outFilterMultimapNmax 50 --alignSJstitchMismatchNmax 5 -1 5 5 --alignSplicedMateMapLminOverLmate 0.5 --peOverlapNbasesMin 10 --chimSegmentMin 10 --chimScoreDropMax 30 --chimScoreSeparation 1 --chimScoreJunctionNonGTAG 0 --chimJunctionOverhangMin 10 --chimOutType WithinBAM HardClip --chimSegmentReadGapMax 3 --chimMultimapNmax 0 or 100
```

Kind regards,
Sebastian

**Comment by alexdobin** [comment]
Hi Sebastian,

thanks for the detailed report and investigation.
This looks like a bug, especially the indeterministic behavior - I will run it through valgrind.
I will look into it after I make 2.7.8a release, hopefully, next week.

Cheers
Alex

**Comment by suhrig** [comment]
Hi Alex, any progress on this?

**Comment by suhrig** [comment]
I have found the bug and implemented a fix. I am currently testing it and will submit a pull request soon.
