### ISSUE TITLE
STARsolo missing information between splice junctions in features.tsv and matrix.mtx?

### ISSUE THREAD

**Issue by carmelle-cat** [alexdobin/STAR#1138]
Hello Alex,

I'm currently working with 10x data and need splice junction counts from each cell to do alternative splicing analysis. I used `--soloFeatures SJ` to get this information. I first worked on a smaller subset of my data since the sparse matrix from the MEX format can be very large. From this smaller subset, features.tsv has 86 total splice junctions detected. However, when I manually checked the matrix file, there are only counts for 38 out of the 86 splice junctions. So 48 of the splice junctions from the features.tsv seem to have read counts from last column of the features.tsv file, but when converting to the sparse matrix, these rows/junctions have no reads for any cell. If they contribute no information to the final counts matrix, why are they listed in the features.tsv file? Is there some sort of filtering happening when matrix.mtx is generated? If so, is there an output file that I can check to verify these filtered counts?

Finally, running `--soloFeatures Gene` outputs filtered MEX files but that doesn't seem to be the case for `--soloFeatures SJ` Why can't the features and barcodes from the `--soloFeatures SJ` run be filtered?

Many thanks for your time!

All the best,
Carmelle

**Comment by alexdobin** [comment]
Hi Carmelle,

the features.tsv file is a sym-link to the SJ.out.tab which contains all detected splice junctions.
For solo counting, only splice junctions supported by uniquely mapping reads are counted, so some of the junctions will not be present in the matrix.mtx . I think this should explain your observations.

Filtering is not done for SJs. I think it makes more sense to use the cells filtered by gene expression, i.e. ```Solo.out/Gene/filtered/barcodes.tsv```. Note that you can run --soloFeatures Gene SJ to get both the Gene and SJ matrices.

Cheers
Alex

**Comment by carmelle-cat** [comment]
Thanks! The solo counts make sense! I also used the filtered barcodes from Gene to filter my matrix from SJ. :)
-Carmelle-
