### ISSUE TITLE
% of unmapped reads too short very high

### ISSUE THREAD

**Issue by lcabus-flomics** [alexdobin/STAR#1143]
Hi Alex,

I'm running STAR with a fastq of 150bp paired-end, with the UMI extracted and the trimming already done. This reads come from a cell-free long RNA experiment, so they should be fragmented, but not have bad quality.
When running STAR, the % of reads unmapped: too short is extremely high (around 80%). I tried lowering the parameters --outFilterScoreMinOverLread and --outFilterMatchNminOverLread to 0.3 (as suggested in https://github.com/alexdobin/STAR/issues/169), but it still gives a % of unmapped reads of around 50%. I have tried running the STAR for both fastq files separately, but it doesn't increase the mapping. I also have checked some of the unmapped reads doing a blast and I have seen that some have very good scores against human genome (one had 100% query coverage and 100% and 100% identity).

I also have seen that the majority of the reads are intronic (60%), with a 30% of the reads being intergenic and only 10% being exonic. This distribution is the same independently of the filtering parameters used.

Lowering the parameters --outFilterScoreMinOverLread and --outFilterMatchNminOverLread to 0 solves the issue, but I'm worried that I'm mapping some reads that should be discarded, do you have some recommendations on how to continue?

Thank you very much,
Lluc

**Comment by alexdobin** [comment]
Hi Lluc,

reducing ```--outFilterScoreMinOverLread``` and ```--outFilterMatchNminOverLread``` will certainly reduce the fidelity of mapping, i.e. you will get more false alignments.
Please send me the Log.final.out file, it may have hints of why the mapping rate is low (mapped length, error rates).
The perfect matches by BLAST are most likely the reads that map to too many loci (also please check that the genome sequence you are using is not masked).

Cheers
Alex

**Comment by lcabus-flomics** [comment]
Hi Alex,

I was running STAR with a masked genome sequence, running it with an unmasked genome brings the mapping rate up to >90%.
I have seen, however, that the number of exonic reads is reduced from 2.7M to 1.5M, do you have an idea of why could this be happening? I put here both the `.final.out ` files, if you can take a look I would be very grateful.

Thank you very much,
Lluc

[mapped_to_masked_genome.final.out.log](https://github.com/alexdobin/STAR/files/5982446/mapped_to_masked_genome.final.out.log)
[mapped_to_unmasked_genome.final.out.log](https://github.com/alexdobin/STAR/files/5982447/mapped_to_unmasked_genome.final.out.log)

**Comment by alexdobin** [comment]
Hi Lluc,

the unmasked genome mapping Log.final seems to be from SE run (input read length 93) while the masked genome is PE run (readLen= 198). Hopefully, the PE mapping to unmasked genome looks as good as SE.

You may see more exonic reads in the unmasked genome because by masking the genome (which will more often mask repeat-like regions in the introns) you are forcing the reads to map to wrong loci. You can compare the alignments for a few reads to confirm this.
How do you check whether the reads are exonic? Even 2.7M out of 22M seems to be too low.

Cheers
Alex

**Comment by lcabus-flomics** [comment]
Hi Alex,

Okay, you are right, I only generate the mapping from one fastq, doing the mapping for the paired-end improved the mapping, although the results of the exons are very similar in the mapping against the masked genome or the unmasked genome, I obtained 2.8M exons.

I check if the reads are exonic using qualimap, I attach here the results of the program for both masked and unmasked genome.

Thank you very much,
Lluc

[masked_rnaseq_qc_results.txt](https://github.com/alexdobin/STAR/files/6008247/masked_rnaseq_qc_results.txt)
[unmasked_rnaseq_qc_results.txt](https://github.com/alexdobin/STAR/files/6008248/unmasked_rnaseq_qc_results.txt)

**Comment by alexdobin** [comment]
Hi Lluc,

I am not familiar with qualimap.
It seems that both the % of intronic and integenic reads is high.
As a second opinion, you can count the number of reads per gene using --quantMode GeneCounts.
It counts reads towards a gene if a read overlaps that gene exon(s), i.e. both purely exonic and exon/intron reads will be counted.
The sum genic counts over the total number of uniquely mapped reads should roughly agree with the % of exonic reads.

Cheers
Alex
