### ISSUE TITLE
Allow Smartseq cell barcodes to be in fastq format?

### ISSUE THREAD

**Issue by cnk113** [alexdobin/STAR#1144]
Hello,

I was wondering instead of manually adding the CB for each individual fastq, would it be possible to input all the CB in a fastq file?
This is similar [zUMI's](https://github.com/sdparekh/zUMIs/wiki/Protocol-specific-setup) format to process the Smart-seq3 format.

Thanks,
Chang

**Comment by alexdobin** [comment]
Hi Chang,

since SmarSeq data has distinct "barcodes" for each FASTQ file (rather than each read), you need to have a per-file barcode listed in the manifest. These "barcodes" can be simply the file names.

Cheers
Alex

**Comment by cnk113** [comment]
I see, I have a unique library structure of my reads where I have a conventional CB+UMI on a read. 
On another read I have another barcode, so I'm actually running STAR solo twice, one for the read and CB+UMI and the other for the read and different barcode.
I'm specifically using CB_samTagOut for the other barcode and I was wondering if position based dedeplication was supported on that parameter? The barcode I have on that read is not a UMI.

**Comment by alexdobin** [comment]
Hi Chang,

if you have an unconventional barcode configuration, the best way may be to try to convert it to a more conventional one.
For instance, you can cut the 2nd barcode from the 2nd read and place it on the 1st read next to the 1st barcode. Then you can set up the CB_UMI_Complex with two whitelists for two barcodes.

Cheers
Alex
