### ISSUE TITLE
Error when using STAR+RSEM on denovo-built transcriptome: The adjacent two lines do not represent the two mates of a paired-end read! (RSEM assumes the two mates of a paired-end read should be adjacent)

### ISSUE THREAD

**Issue by juanchoule** [alexdobin/STAR#1168]
Hello,

I am using STAR+RSEM to quantify the expression of denovo-built transcripts. There is no reference genome available. 

I used the following commands:

STAR --readFilesCommand zcat --runThreadN $SLURM_NTASKS \
--genomeDir /path/to/dir \
--readFilesIn /path/to/reads_R1.PE_1.fastq.gz /path/to/reads_R2.PE_2.fastq.gz \
--outSAMtype BAM SortedByCoordinate --outSAMunmapped Within --outSAMstrandField None \
--twopassMode Basic --outFilterMultimapNmax 10 --outFilterMismatchNmax 0 --seedSearchStartLmax 40 \
--alignEndsType EndToEnd --alignIntronMax 1 --alignIntronMin 2 --scoreDelOpen -10000 --scoreInsOpen -10000 \
--outFileNamePrefix transcripts.out

Followed by RSEM:

rsem-calculate-expression -p $SLURM_NTASKS --bam --paired-end \
path/to/transcripts.outAligned.sortedByCoord.out.bam \
RSEMref \
transcript.expression

However, I am getting this error:
Warning: Detected a read pair whose two mates have different names--GWNJ-0901:522:GW1909262519th:2:1119:2950:6952 and GWNJ-0901:522:GW1909262519th:2:2105:26017:31019!
Read GWNJ-0901:522:GW1909262519th:2:1119:13849:3928: The adjacent two lines do not represent the two mates of a paired-end read! (RSEM assumes the two mates of a paired-end read should be adjacent)

I am using these versions:
star/2.7.1a
rsem/1.3.0

Any idea what is happening?
Thanks
Juan

**Comment by alexdobin** [comment]
Hi Juan,

RSEM require "unsorted" BAM file, where mate alignments are next to each other.
Please use ```--outSAMtype BAM Unsorted``` option.

Cheers
Alex

**Comment by juanchoule** [comment]
Hi Alex,
it works now.
many thanks!
Juan
