### ISSUE TITLE
PCR duplicates issue when WASP tag included

### ISSUE THREAD

**Issue by AL-Roberts** [alexdobin/STAR#1177]
Hi,

I would like to use WASP correction and remove PCR duplicates from my RNA-Seq data for ASE analysis.

However, using --runMode inputAlignmentsFromBAM with BAMs which include WASP tags (following --runMode alignReads) throws an error.

Is there a way around this?

Many thanks in advance,

Amy

**Comment by alexdobin** [comment]
Hi Amy,

what STAR commands are you using? What error do you see?
If you can send me the Log.out files, it would be great.

Cheers
Alex

**Comment by AL-Roberts** [comment]
Hi Alex,

Here's the error I get:
Mar 23 16:26:37 ..... reading from BAM, remove duplicates, output BAM
Segmentation fault (core dumped)

And attached is the Log.out file where you can see the STAR commands.
[testLog.out.txt](https://github.com/alexdobin/STAR/files/6191290/testLog.out.txt)

Thank you,

Amy

**Comment by alexdobin** [comment]
Hi Amy,

I could reproduce the seg-fault, will work to debug it.

Thanks!
Alex

**Comment by alexdobin** [comment]
Hi Amy,

actually, the seg-fault in my tests was occurring because it could not open the file listed in ```--inputBAMfile```.
Could you please check that the file exists and has proper read permission and BAM formatting (e.g. check that ```samtools index``` works).

Thanks!
Alex

**Comment by AL-Roberts** [comment]
Hi Alex,

I was able to index the bam file using samtools without issues.

All the best,

Amy

**Comment by alexdobin** [comment]
Hi Amy,

could you try to deduplicate with the latest release, 2.7.8a?
If this does not work, could you subset the BAM file to a small set (~100k) of reads that still cause the seg-fault and send it to me?
I would need to replicate the problem on my system.

Cheers
Alex

**Comment by AL-Roberts** [comment]
Hi Alex,

Sorry for the delay. I've tested the deduplication with the latest release 2.7.8a and I get the same problem.

I will send you a subset of my BAM file by email. Please let me know if you need anything else.

All the best,

Amy

**Comment by alexdobin** [comment]
Hi Amy,

sorry for the long delay, this issue slipped out of my mind.
I finally figure out what the problem was - the file you sent me did not contain AS tags, which are required for deduplication, as the read with the highest score (AS) is selected to be the representative, while the lower score reads are considered duplicates.
I have added a check in the code to throw an error instead of seg-fault.
Still, you would need to re-generate your BAM files with the AS tag. Another tag that's required is NH.

Cheers
Akex

**Comment by AL-Roberts** [comment]
Hi Alex,

Thank you so much for getting back to me on this. Apologies for not realising I was missing a necessary tag!

Thank you for your time.

All the best,

Amy

________________________________
