### ISSUE TITLE
*OUTPUT FILE* error

### ISSUE THREAD

**Issue by hchetia** [alexdobin/STAR#1178]
Running STAR v 2.7.6a with a custom reference and paired-end RNAseq fastq files, I get the following error-
BAMoutput.cpp:27:BAMoutput: exiting because of *OUTPUT FILE* error: could not create output file 336_STARtmp//BAMsort/20/16
SOLUTION: check that the path exists and you have write permission for this file. Also check ulimit -n and increase it to allow more open files.

The path does exist with all permissions.
I checked the ulimit which is 1024.
My workspace resides in a shared HPC environment without sudo privilages.
Please help.

**Comment by alexdobin** [comment]
Hi @hchetia 

you have several options here:
1. Try to increase the max number of open files with ```ulimit -n 5000```. If that's not allowed, you can ask sys-admin to do it for you.
2. Reduce the number of threads you are using: ~16 threads or less should use <1024 open files.
3. Output unsorted BAM from STAR, and then sort it with samtools sort.

Cheers
Alex

**Comment by hchetia** [comment]
Thanks Alex.
