### ISSUE TITLE
STAR results changing drastically between mapping to masked and unmasked genomes

### ISSUE THREAD

**Issue by lcabus-flomics** [alexdobin/STAR#1179]
Hi Alex,

I have tried mapping to the masked and unmasked genomes with one sample to see the difference between them, and the differences were very high. Specifically, there were two genes that were found with a TPM number of +240,000 and +120,000 that were not found in the mapping against the unmasked genome. What should I do here? Is it possible that those are artifacts?

Thank you very much!
Lluc

**Comment by alexdobin** [comment]
Hi Lluc,

mapping to a masked genome is dangerous, as you will be forcing some reads to map into sub-optimal loci compared to the unmasked genome. You can try to trace those reads that mapped into these genes in the masked genome - where are they mapping in the unmasked genome? If they map with higher quality (fewer mismatches)  in the unmasked genome, then the high-TPM are artifacts of the masked genome.

Masking can be useful to remove completely identical sequences from the genome. Even in these cases, it's dangerous for the boundaries of such regions.

Cheers
Alex

**Comment by lcabus-flomics** [comment]
Hi Alex,

Sorry, It was the other way around, in the mapping against the unmasked genome I found 2 genes extremely expressed that were not found in the mapping against the masked genome.

**Comment by alexdobin** [comment]
Hi Lluc,

were these genes masked in the masked genome? This would be a simple explanation.
What tool are you using for calculating TPMs and what parameters?
Some tools may produce very high TPMs for very short transcripts (such as non-coding RNA), because they are designed to work with long mRNA transcripts.
For such short transcripts, it's probably better to just count the reads that overlap them.

Cheers
Alex

**Comment by lcabus-flomics** [comment]
Hi Alex,

Yes, those genes are masked, that is why they didn't appear in the unmasked genome. For the calculation of counts and TPMs I used RSEM, with default parameters. Talking to other people, they told me that maybe I should do a mapping against the unmasked genome and filtering of the reads that map to the repetitive regions, since those could be more expressed due to reads mapping multiple times to the same gene, which could be the case of those highly expressed genes in my samples, what do you think about it?

**Comment by alexdobin** [comment]
Hi Lluc,

if these genes have paralogs, it's possible, in principle, that RSEM would collect the multi-mappers from all paralogs and assign them to only these genes. This would happen if only these genes have some unique mappers, while all other paralogs only have multimappers. You can check this by counting the number of unique and multimapping reads overlapping the genes' loci.

Cheers
Alex
