### ISSUE TITLE
Not getting any alignments 

### ISSUE THREAD

**Issue by hchetia** [alexdobin/STAR#1186]
I am running an alignment of rnaseq reads to a set of 100 reference genes which is rich in homopolymers.
Tried all parameters, but I dont get any alignments.
STAR version 2.7.8a
Default parameters.
Input are lane-wise concatenated novaseq outputs into R1 & R2 (works fine with bwa mem)
I tried to use bbmap to check for possible errors in the fastqs but none.

Snapshot of the log below.
![image](https://user-images.githubusercontent.com/64626735/112178823-78bc5900-8bd0-11eb-8064-b36f212cee54.png)

**Comment by ogola89** [comment]
I am getting a similar issue with single reads, none are being aligned to GRCm39

**Comment by alexdobin** [comment]
Hi @hchetia, @ogola89 

I think these are two different issues - would be better to separate them into two.

@hchetia,
you are mapping to a small subset of gene sequences? 
This is a non-standard operation and will require tweaking of the parameters.
What % of reads do you expect to map? What mismatch/indel rate do you expect?

@ogola89,
you are mapping to GRCm39, which should be a standard operation, so should work out of the box.
Please send me the Log.out and Log.final.out files.

Cheers
Alex

**Comment by ogola89** [comment]
@alexdobin okay I will make a new issue for it

**Comment by hchetia** [comment]
Hi Alex,
I donot have any threshold for the % of reads, but using bwa mem I got 3-4% reads that multi-mapped.
I do expect very low mismatch rate. Going by the calculation in the manual- 0.04*300 = 12 per paired read for my 150*2 PE reads). Actually I don't even expect that many mismatches. 
And I am not sure about indel rates at all.
A point that I must mention is that my reference has a LOT of triplet repeats.
What could I tweak to get alignments?

**Comment by alexdobin** [comment]
Hi @hchetia 

the next question is how many loci do the reads map to? If >50, you would need to adjust
```--winAnchorMultimapNmax``` and ```--outFilterMultimapNmax```. I would start with 100 and then increase it to 200, 500, 1000.

Cheers
Alex

**Comment by hchetia** [comment]
Thanks Alex, trying these now.

**Comment by hchetia** [comment]
100 for the params --winAnchorMultimapNmax and --outFilterMultimapNmax lead to no results.
Scaled up to 200, getting the foll. error-

**WARNING: not enough space allocated for transcript. Did not process all windows for read A00815:87:HNC2JDRXX:1:2102:23601:31093
   SOLUTION: increase alignTranscriptsPerReadNmax and re-run**

Also increased ulimit to 20000 and reran, but same error.

**Comment by alexdobin** [comment]
Hi @hchetia 

it would be good to check the alignments that bwa-mem gets - how many loci do they map to?
Can you post bwa-mem output for a few of the aligned reads?

Please try to increase ```--alignTranscriptsPerReadNmax 50000```
Also, there are two more parameters you may need to scale up by a factor 5-10:
--alignTranscriptsPerWindowNmax       default=100
    int>0: max number of transcripts per window
--alignTranscriptsPerReadNmax               deafult=10000
    int>0: max number of different alignments per read to consider

Cheers
Alex
