### ISSUE TITLE
what are the reads in Chimeric.out.sam?

### ISSUE THREAD

**Issue by ibphuangchen** [alexdobin/STAR#1188]
Hi Alex,

I run the STAR on a paired fastq RNAseq files with chimeric "--chimOutType SeparateSAMold", when I looked into the Chimeric.out.sam file, I found some of the reads were not from my fastq files. Where did they come from?

A example:

A00667:31:H5KTNDRXY:1:1110:22824:28902	99	8	56073124	3	100M	=	56073754	1005	CCTGGCTCAATACTGATGGAAGTAATCTGCTTAACAATCTCAGAAGGACTGTGCAAGTCAATGAGTCGCTTGTGAATTCTCATCTGGAAACGATCCCACG	FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFF:FFF:F	NH:i:2	HI:i:1	AS:i:184	nM:i:0
A00667:31:H5KTNDRXY:1:1110:22824:28902	147	8	56073754	3	15M291N69M16S	=	56073124	-1005	TCAAGTCAGCACACACCTTTTCCAAGGATTTTACGTTGCGGCTTGTTAGGGTGATTCGAATTCGGTGAATTGCCACCTCCGGCTCCAACTGTACAGAGGC	FFFFFFFFFFFFFFF,FFFFFFFFFFF:FFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF,:F,FFFFFFFFF	NH:i:2	HI:i:1	AS:i:184	nM:i:0
A00667:31:H5KTNDRXY:1:1110:22824:28902	385	7	134511599	3	16M84S	8	56073124	0	GCCTCTGTACAGTTGGAGCCGGAGGTGGCAATTCACCGAATTCGAATCACCCTAACAAGCCGCAACGTAAAATCCTTGGAAAAGGTGTGTGCTGACTTGA	FFFFFFFFF,F:,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFF:FFFFFFFFFFF,FFFFFFFFFFFFFFF	NH:i:2	HI:i:2	AS:i:15	nM:i:0

I searched the reads and found that the first one was from my read-1 fastq, and the third one was from my read-2 fastq. However, the second one "TCAAGTCAGCACACACCTTTTCCAAGGATTTTACGTTGCGGCTTGTTAGGGTGATTCGAATTCGGTGAATTGCCACCTCCGGCTCCAACTGTACAGAGGC" was not from either of my fastq files. Where did it come from?

Below is my command:

STAR \
    --runMode alignReads \
        --runThreadN 20 \
        --genomeDir $starRef \
        --readFilesIn $fastq1 $fastq2\
        --readFilesCommand zcat \
        --outSAMunmapped Within KeepPairs \
    --outSAMtype BAM Unsorted \
    --chimOutType SeparateSAMold \
    --chimJunctionOverhangMin 10 --chimScoreMin 1 --chimScoreDropMax 30 \
    --chimScoreJunctionNonGTAG 0 --chimScoreSeparation 1 --alignSJstitchMismatchNmax 5 -1 5 5 --chimSegmentReadGapMax 3 \
    --chimSegmentMin 10 \
		--outFileNamePrefix $DIR/157_chimera_separate

Thanks in advance!!
Chen

**Comment by alexdobin** [comment]
Hi Chen,

the 2nd SAM line is mapped to the (-)strand (SAM flag 147), and according to SAM standards the read sequences is reported from the (+)strand, i.e. it's reverse complemented. This is why you cannot grep it from FASTQ. Generally, it's better to look for the reads using the read ID.

Cheers
Alex

**Comment by ibphuangchen** [comment]
> Hi Chen,
> 
> the 2nd SAM line is mapped to the (-)strand (SAM flag 147), and according to SAM standards the read sequences is reported from the (+)strand, i.e. it's reverse complemented. This is why you cannot grep it from FASTQ. Generally, it's better to look for the reads using the read ID.
> 
> Cheers
> Alex

Thanks a lot!
