### ISSUE TITLE
star final log file 1st pass vs. 2nd pass

### ISSUE THREAD

**Issue by ibphuangchen** [alexdobin/STAR#1195]
Hi Alex,

I run a pair-end RNAseq STAR mapping using both 1-pass and 2-pass mapping. Below is the Log.final.out for 1-pass:

                             

> Started job on |	Mar 31 17:58:18
>                              Started mapping on |	Mar 31 17:58:35
>                                     Finished on |	Mar 31 18:23:40
>        Mapping speed, Million of reads per hour |	248.20
> 
>                           Number of input reads |	103761081
>                       Average input read length |	161
>                                     UNIQUE READS:
>                    Uniquely mapped reads number |	92489544
>                         Uniquely mapped reads % |	89.14%
>                           Average mapped length |	161.29
>                        Number of splices: Total |	47351614
>             Number of splices: Annotated (sjdb) |	46700947
>                        Number of splices: GT/AG |	46742773
>                        Number of splices: GC/AG |	358334
>                        Number of splices: AT/AC |	57206
>                Number of splices: Non-canonical |	193301
>                       Mismatch rate per base, % |	0.31%
>                          Deletion rate per base |	0.01%
>                         Deletion average length |	1.47
>                         Insertion rate per base |	0.01%
>                        Insertion average length |	1.31
>                              MULTI-MAPPING READS:
>         Number of reads mapped to multiple loci |	6745459
>              % of reads mapped to multiple loci |	6.50%
>         Number of reads mapped to too many loci |	151479
>              % of reads mapped to too many loci |	0.15%
>                                   UNMAPPED READS:
>      Number of reads unmapped: too many mismatches |	0
>          % of reads unmapped: too many mismatches |	0.00%
>             Number of reads unmapped: too short |	4300564
>                  % of reads unmapped: too short |	4.14%
>                 Number of reads unmapped: other |	74035
>                      % of reads unmapped: other |	0.07%
>                                   CHIMERIC READS:
>                        Number of chimeric reads |	1587244
>                               % of chimeric reads |	1.53%

******
and below is the final output for 2-pass mapping

                             

>                                Started job on |	Apr 01 09:58:38
>                              Started mapping on |	Apr 01 10:06:04
>                                     Finished on |	Apr 01 10:31:09
>        Mapping speed, Million of reads per hour |	248.20
>                           Number of input reads |	103761081
>                       Average input read length |	161
>                                     UNIQUE READS:
>                    Uniquely mapped reads number |	92332740
>                         Uniquely mapped reads % |	88.99%
>                           Average mapped length |	161.29
>                        Number of splices: Total |	47594198
>             Number of splices: Annotated (sjdb) |	47416649
>                        Number of splices: GT/AG |	46907684
>                        Number of splices: GC/AG |	415439
>                        Number of splices: AT/AC |	58294
>                Number of splices: Non-canonical |	212781
>                       Mismatch rate per base, % |	0.31%
>                          Deletion rate per base |	0.01%
>                         Deletion average length |	1.47
>                         Insertion rate per base |	0.01%
>                        Insertion average length |	1.31
>                              MULTI-MAPPING READS:
>         Number of reads mapped to multiple loci |	6137830
>              % of reads mapped to multiple loci |	5.92%
>         Number of reads mapped to too many loci |	230129
>              % of reads mapped to too many loci |	0.22%
>                                   UNMAPPED READS:
>       Number of reads unmapped: too many mismatches |	0
>             % of reads unmapped: too many mismatches |	0.00%
>             Number of reads unmapped: too short |	4753493
>                  % of reads unmapped: too short |	4.58%
>                 Number of reads unmapped: other |	306889
>                      % of reads unmapped: other |	0.30%
>                                   CHIMERIC READS:
>                        Number of chimeric reads |	1570737
>                             % of chimeric reads |	1.51%
> 

I have always noticed that comparing to the 1-pass mode, the 2-pass mode has a higher proportion of reads being "unmapped: too short" (e.g.4.58% vs 4.14%) and a lower portion of reads being "mapped to multiple loci" (e.g. 5.92% vs. 6.50%). In my other mappings where 1-pass detected more multiple loci mapping, the difference is even more obvious. Is it because STAR assigns some of 1-pass multiple-loci-mapped reads into "unmapped too short/others" in the second pass mapping? If yes, could you briefly explain in a high level why is that?

Also, to my understanding, 2-pass mapping aims to increase the sensitivity of chimeric read detection. But why in lots of cases (such as in this example), the 1-pass detected even more 'chimeric reads' than the 2-pass mode (1587244 vs. 1570737)?

Below is my command to run STAR:

STAR \
    --runMode alignReads \
        --runThreadN 20 \
        --genomeDir $starRef \
        --readFilesIn $fastq1 $fastq2\
        --readFilesCommand zcat \
        --outSAMunmapped Within KeepPairs \
    --outSAMtype BAM Unsorted \
    --quantMode TranscriptomeSAM \
    --chimOutType SeparateSAMold \
     --chimJunctionOverhangMin 10 --chimScoreMin 1 --chimScoreDropMax 30 \
    --chimScoreJunctionNonGTAG 0 --chimScoreSeparation 1 --alignSJstitchMismatchNmax 5 -1 5 5 --chimSegmentReadGapMax 3 \
    --chimSegmentMin 20

The only difference for 2-pass was adding a "--twopassMode Basic ".

Thanks in advance!

Chen

**Comment by alexdobin** [comment]
Hi @ibphuangchen 

typically, 2-pass alignment results in fewer unmapped reads compared to 1-pass.
However, there are possibilities why there could be a reduction in mappability. In the 2nd pass, the search space is increased with junctions sequences from the 1st pass - so some seeds that were barely acceptable in the 1st pass, become unacceptable in the 2nd pass because they map to too many loci. You can try to investigate this further by increasing ```--winAnchorMultimapNmax``` from default 50 to, say 100 or 200. This will increase mappability for both 1st and 2nd pass.

The 2nd pass increases the sensitivity for normally spliced alignments, and because of that, it decreases false positives for chimeric alignments - that why you are seeing fewer chimeric alignments.

Cheers
Alex

**Comment by ibphuangchen** [comment]
Thank you Alex for the clear explanation!
