### ISSUE TITLE
STARsolo SmartSeq merge output(question)

### ISSUE THREAD

**Issue by wenjingxxu** [alexdobin/STAR#1197]
Hello Alex,
I've used STAR for SmartSeq2 alignments with the following STARsolo option:

STAR --runThreadN 24 \
--genomeDir ./starindex75bp \
--readFilesIn ./fastqfile/${file}_1.fastq.gz ./${file}_2.fastq.gz \
--readFilesCommand zcat \
--outFileNamePrefix aligned${file} \
--outFilterMismatchNoverLmax 0.1 \
--outFilterMatchNmin 10 \
--outFilterMatchNminOverLread 0 \
--outFilterScoreMinOverLread 0 \
--outMultimapperOrder Random \
--soloType SmartSeq \
--outSAMattrRGline ID:${file} \
--soloUMIdedup Exact \
--soloStrand Unstranded

It ran successfully and I got the alignedSolo.out/Gene/filtered directory with barcodes.tsv, features.tsv, matrix.mtx files that I can load into Seurat. _However, for each cell/"barcode" there was a separate alignedSolo.out/Gene/filtered directory_. Is there an option that I can get the merged cell output directly from STAR( I mean the output from all cells/"barcodes" is in the same alignedSolo.out/Gene/filtered directory)?

Thanks a lot,
Wenny

**Comment by alexdobin** [comment]
Hi Wenny,

I guess you figure it out yourself:
you would need to specify all files in a manifest.tsv file (3 columns, read1 \t read2 \t "barcode") and input it with ```--readFilesManifest manifest.tsv``` instead of ```--readFilesIn```.

Cheers
Alex

**Comment by wenjingxxu** [comment]
Yes! Thank you Alex for the explanation!
