### ISSUE TITLE
Unable to generate genome index using --genomeTransferType Diploid

### ISSUE THREAD

**Issue by henrik783** [alexdobin/STAR#1199]
I am trying out the new STARconsensus functionalities. I am especially interested in haplotyping individual reads using the `ha` SAM attribute (although I understand it is unsupported).

However, I have not been able to create a diploid genome index. At least it seems to be a very lengthy process. 
Using STAR 2.7.8a on my hardware takes around 30 minutes to generate a genome index using the command: 
`STAR --runMode genomeGenerate --runThreadN 12 --genomeDir Output --genomeFastaFiles ucsc.hg19.fasta --sjdbGTFfile gencode.v19.annotation.sorted.gtf --sjdbOverhang 100`

Producing a transformed haploid genome index takes a bit longer, around 1h:
`STAR --runMode genomeGenerate --runThreadN 12 --genomeDir Output --genomeFastaFiles ucsc.hg19.fasta --sjdbGTFfile gencode.v19.annotation.sorted.gtf --sjdbOverhang 100 --genomeTransformType Haploid --genomeTransformVCF NPM1.vcf`

However, making a transformed diploid genome index takes much longer (I stopped it at around 10 h). This was using the command: 
`STAR --runMode genomeGenerate --runThreadN 12 --genomeDir Output --genomeFastaFiles ucsc.hg19.fasta --sjdbGTFfile gencode.v19.annotation.sorted.gtf --sjdbOverhang 100 --genomeTransformType Diploid --genomeTransformVCF NPM1.vcf`

The file NPM1.vcf contains only a single 4bp insertion. The process stalled at the first `sorting Suffix Array chunks and saving them to disk...` for around 10 hours.

Is this expected or is it a bug?

**Comment by alexdobin** [comment]
Hi @henrik783 

the Diploid feature is still under development, you are welcome to experiment with it, but it may not work properly.
I will release it in the summer, hopefully.
Please try ```--genomeSuffixLengthMax 300``` (it can be as small as your read length), it should make the run-time reasonable (~1-2 hours).

Cheers
Alex

**Comment by henrik783** [comment]
Hi @alexdobin 

Thank you very much for help! I can confirm that using `--genomeSuffixLengthMax 300` helped. With this option, the diploid genome index was generated in ~1.5 hours.

I have also tested mapping to the genome, which seems to work fine. So far, my tests with the ha-tag indicates that this is assigned properly (although I was surprised that the alt-allele in my VCF was assigned "1" and the ref-allele was assigned "2"). I have added a new `case` statement in ReadAlign_alignBAM.cpp to be able to get the new ha attribute in a sorted BAM-filen. I assume this functionality was intentionally excluded for now since the feature is not yet released.

Will be happy to help if you need any specific testing of this feature.

**Comment by Neiluj49** [comment]
Hello Folks Hello Alex, i open this thread to know a little bit more about the diploid feature development ? Is it still in progress  ? Tis for your reply ! Cheers

**Comment by alexdobin** [comment]
Hi @Neiluj49 

it is under development and we hope to get it out in 1-2 months.

**Comment by Neiluj49** [comment]
Tks Alex !
It could be a perfect timing for our work .
Very exciting to try it !
See u


Le 6 févr. 2023 à 21:38, Alexander Dobin ***@***.***> a écrit :



Hi @Neiluj49<https://github.com/Neiluj49>

it is under development and we hope to get it out in 1-2 months.

**Comment by Neiluj49** [comment]
Hello @alexdobin , what could you say about the diploid feature development ?

**Comment by alexdobin** [comment]
Hi @Neiluj49 

We have a pre-release with diploid feature, if you want to try it out:
https://github.com/dobinlab/STAR_pre_releases/releases/tag/2.7.10b_diploid_2023-05-02
