### ISSUE TITLE
starLong with sjdb=599 => bad_alloc

### ISSUE THREAD

**Issue by ulah** [alexdobin/STAR#120]
Hi,
I'm trying to run star on some 454 fastq's I still have. Unfortunately, I get some bad_alloc errors which seem to be related to the sjdbOverhang parameter.
When I generate a genome index with sjdbOverhang 599, everything works fine. However, when I'm trying to map reads to the genome, I only get:

> terminate called after throwing an instance of 'std::bad_alloc'
> what():  std::bad_alloc

I'm using star 2.5.1b, my *_Log.out is attached
[Star251b_test_Log.out.zip](https://github.com/alexdobin/STAR/files/161233/Star251b_test_Log.out.zip)

I should add that everything also works fine, if I use sjdbOverhang 100 for genome generation and mapping.

Any help is much appreciated!
Best,
Urs

**Comment by ulah** [comment]
Any comment or solution on that? How much can I expect mapping sensitivity to be influenced when I use a sjdbOverhang of 100? What's your suggestion for using this parameter with pacbio or ONT reads?

**Comment by alexdobin** [comment]
Hi Urs,

sorry for belayed reply.
I will check what is causing this error, but I do not recommend using sjdbOverhang >150. In the absolute majority of cases, 100 is enough. Please check this post for more details:
[https://groups.google.com/d/msg/rna-star/h9oh10UlvhI/BfSPGivUHmsJ](url)

Cheers
Alex

**Comment by bounlu** [comment]
Hi Alex,

The link is broken. So do you suggest to use sjdbOverhang = 100 for genome generation for long PacBio reads?

**Comment by alexdobin** [comment]
Hi @bounlu 

for some reason github refuses to follow the link, but if you copy/paste it into your browser, it works.
Indeed, sjdbOverhang = 100 is recommended for any reads longer than 150.

Cheers
Alex
