### ISSUE TITLE
Conceptual difference between "Gene" and "Velocyto"-spliced matrices

### ISSUE THREAD

**Issue by flo-compbio** [alexdobin/STAR#1201]
Hi,

I've run STARsolo 2.7.8a with the "Gene" and "Velocyto" quantification modes, and everything seems to work great! I'm just wondering if anyone could explain to me what if any the difference is between the "normal" expression matrix generated with the "Gene" option, and the spliced matrix generated by the "Velocyto" option. They are not identical, but I don't understand what the difference is between those two matrices in terms of how gene expression levels are quantified.

Best,
Florian

**Comment by alexdobin** [comment]
Hi Florian,

This is a good question, and the answer is somewhat complicated.
The counting schemes of UMIs for Gene and Velocyto spliced are similar but have some important differences.
For Gene, every read that is concordant to any number of transcripts from a single gene is counted towards that gene.
With ```--soloUMIfiltering   MultiGeneUMI``` you can deal with UMI that have multiple reads mappping to different gene - it will pick the gene with the largest number of reads.

The policy for Velocyto-spliced is more stringent.
All reads with one UMI have to be fully exonic, and not overlap any annotated introns.
With this extra requirement, we are losing ~20% of UMIs compared to Gene calculation.
If some reads overlap introns, and others are fully exonic for the same gene, they are counted in the ambiguous.
Typically, these are ~15% of the Gene UMIs.
If any reads overlap different genes (introns or exons), or no gene at all, they are discarded (~5%).

You should see a better agreement between Gene and a sum spliced+ambiguous  matrices, but there will still be ~5% difference.

Cheers
Alex

**Comment by flo-compbio** [comment]
Hi Alex,

Thank you for this excellent answer, that's very helpful!

Best,
Florian
