### ISSUE TITLE
Are you sure the fifo file won't overflow ?

### ISSUE THREAD

**Issue by homerl** [alexdobin/STAR#1202]
I am not a biology major and it looks too dangerous.
https://github.com/alexdobin/STAR/blob/ffb66fb04e2642d1c2df87a31344552487ec491d/source/Parameters_openReadsFiles.cpp#L27

**Comment by alexdobin** [comment]
Hi Homer,

fifo files will not overflow because they open in the (default) blocking mode.

Cheers
Alex

**Comment by homerl** [comment]
Hi Alex
    Thank you.
