### ISSUE TITLE
Error in STAR output file Aligned.out.sam

### ISSUE THREAD

**Issue by zlatanimobic** [alexdobin/STAR#1209]
Hi, 

I faced the problem with samfile generated by this command:

STAR-2.7.8a/bin/MacOSX_x86_64/STAR --runThreadN 60 --genomeDir /Volumes/HDD/Homo_sapiens/Ensembl/GRCh37/STARindex --sjdbGTFfile /Volumes/HDD/Homo_sapiens/Ensembl/GRCh37/Homo_sapiens.GRCh37.87.gtf --sjdbOverhang 99 --readFilesIn DK19080_19.qc.fastq --outFilterMultimapNmax 100 --seedSearchStartLmax 12 --alignSJoverhangMin 15 --outFilterMatchNminOverLread 0 --outFilterScoreMinOverLread 0.3 --outFilterType BySJout --twopassMode Basic

Alignment finished successfully, but when i try to convert SAM to BAM using samtools the problem occured.

[W::sam_read1_sam] Parse error at line 218583
samtools view: error reading file "Aligned.out.sam"

Then, I checked line 218583 in Aligned.out.sam file. 
The line filled "00 00 00 00 00 00 00 00 00 00....." 

I found the same bug text in several lines.

This problem occuerd after adding the option "--outFilterType BySJout".

My enviornment is
OS: macOS Big Sur ver 11.2.3
memory: 64GB 2667MHz DDR4
STAR: 2.7.8-a

How to solve this problem? Thank you for your attention.

Best
Fumiaki
------------------
P.S　The commandline above mentioned run correctly after downgrading STAR version to 2.6.1.e.
       Is this a bug?

Regards
Fumiaki

**Comment by alexdobin** [comment]
Hi Fumiaki,

please try to run it with a smaller number of threads, ~20-30. Also, please make sure that no other STAR jobs are running in the same directory.

Cheers
Alex

**Comment by zlatanimobic** [comment]
> Hi Fumiaki,
> 
> please try to run it with a smaller number of threads, ~20-30. Also, please make sure that no other STAR jobs are running in the same directory.
> 
> Cheers
> Alex

Hi Alex

 Thank you for your reply.
 I tried to run with a number of thread as 20, and no jobs is running. But it doesn't work.

the commandlines and terminal jobs is shown below:
------
9:56 ~/Desktop $ jobs      
10:01 ~/Desktop $ ./STAR-2.7.8a/bin/MacOSX_x86_64/STAR --runThreadN 20 --genomeDir /Volumes/HDD/Homo_sapiens/Ensembl/GRCh37/STARindex_v2_7_8_a --sjdbGTFfile /Volumes/HDD/Homo_sapiens/Ensembl/GRCh37/Homo_sapiens.GRCh37.87.gtf --sjdbOverhang 99 --readFilesIn /Volumes/HDD/analysis/DK19132fastq/DK19132_01.qc.fastq --outFilterMultimapNmax 100 --seedSearchStartLmax 12 --alignSJoverhangMin 15 --outFilterMatchNminOverLread 0 --outFilterScoreMinOverLread 0.3 --twopassMode Basic --outFilterType BySJout   
Apr 21 10:07:57 ..... started STAR run
Apr 21 10:07:57 ..... loading genome
Apr 21 10:09:21 ..... processing annotations GTF
Apr 21 10:09:36 ..... inserting junctions into the genome indices
Apr 21 10:10:27 ..... started 1st pass mapping
Apr 21 10:13:21 ..... finished 1st pass mapping
Apr 21 10:13:21 ..... inserting junctions into the genome indices
Apr 21 10:14:14 ..... started mapping
Apr 21 10:17:17 ..... finished mapping
Apr 21 10:17:19 ..... finished successfully
10:17 ~/Desktop $ samtools view -bS Aligned.out.sam > DK19132_01.bam
[W::sam_read1_sam] Parse error at line 305028
samtools view: error reading file "Aligned.out.sam"
------

 Could you find any other solutions?

Regards
Fumiaki

**Comment by alexdobin** [comment]
Hi Fumiaki,

please send me the Log.out file.

Thanks!
Alex

**Comment by zlatanimobic** [comment]
> Hi Fumiaki,
> 
> please send me the Log.out file.
> 
> Thanks!
> Alex

Hi Alex, 

Here is the file.
[Log.out.txt](https://github.com/alexdobin/STAR/files/6381104/Log.out.txt)

Best
Fumiaki

**Comment by alexdobin** [comment]
Hi Fumiaki,

Log.out looks good, nothing suspicious.
Please check that you have enough disk space.
Next, please try to map a small subset of your fastq file, with ```--readMapNumber 100000```, and check if samtools conversion works on it.

Cheers
Alex

**Comment by alexdobin** [comment]
Hi Fumiaki,

this is a bug, caused by the --outFilterType BySJout option - see #1220.
I will fix it shortly.

Thanks!
Alex

**Comment by alexdobin** [comment]
Hi Fumiaki,

the 2.7.9a release should have fixed this issue, please try it out.

Cheers
Alex

**Comment by umjmwr** [comment]
Hi Alex, hope you are well. 

I have successfully aligned my RNAseq data using Star2.7.9a with read counts. 

My question is regarding the read count output file star creates. 

I am using RNA stranded data so according to the manual I should be using column 3 or 4 for my downstream DESeq analysis.  

Does it matter which column I use for my downstream DESeq analysis? 

In my data, sometimes columns 3 and 4 add up to a total which is the same as in column 2, however sometimes this is not the case. Is there a reason for this? Should it add up? 

If I am to choose between columns 3 and 4 should I choose one column only? or choose the highest read count from 3 or 4? 

best wishes
James

**Comment by alexdobin** [comment]
Hi James,

for stranded data, you **need** to choose column 3 or 4 according to the strandedness of your protocol: col 3 corresponds to read1 strand = RNA strand, and col 4 to the opposite orientation.
If you do not know the protocol strandedness, you can choose the column that has more reads than the other column for most genes.
col3 + col4 > col 2 (unstranded) for reads that map to genes overlapping on opposite strands. Such reads will be considered ambiguous for unstranded counting and not counted in col 2.

Cheers
Alex

**Comment by umjmwr** [comment]
Hi Alex, 

thank you for your message, now it makes sense, 

best wishes
James

**Comment by NikoHensley** [comment]
Hi Alex,

I am doing a two pass STAR pipeline, mapping reads for splice junction sites, and then using that output in a 2nd stage of mapping (as has been described previously). These steps all run smoothly, except when I do the 2nd pass at mapping using the SJ.out.tab from the first pass with --sjdbFileChrStartEnd, the output file is an unnamed .SAM even though I specify  --outSAMtype BAM SortedByCoordinate as well as a prefix name for the file. Essentially my first and second pass commands are the same (except for the splice junction file), and yet the outputs for the first is a .BAM and the second is a .SAM with no prefix. The .SAM files convert just fine to .BAM when using samtools after the fact, so I don't believe they are produced with errors.

Here is my code for the 1st pass:
STAR --runThreadN 40 \
     --readFilesManifest ./rna_groups.tsv \
     --genomeDir /genome/ncbi_dataset/data/GCA_002313205.1/ \
     --outSAMtype BAM SortedByCoordinate \
     --outFileNamePrefix Paired_pass_1  \
     --alignIntronMax 10000 \
     --outSAMunmapped Within KeepPairs &

Which outputs a .BAM file and a SJ file: 
Paired_pass_1Aligned.sortedByCoord.out.bam
Paired_pass_1SJ.out.tab

After filtering the SJ file and re-generating genome indices, I then-remap with the following code:
STAR --runThreadN 40 \
     --readFilesManifest ./rna_groups.tsv \
     --genomeDir /genome/ncbi_dataset/data/GCA_002313205.1/second_pass_index \ 
     --sjdbFileChrStartEnd ./Paired_pass_1SJ.out.tab \
     --outSAMtype BAM SortedByCoordinate \
     --outFileNamePrefix Paired_pass_2 \
     --alignIntronMax 10000 \
     --outSAMunmapped Within KeepPairs & 

However, this produces the .SAM file without the prefix. I am not sure if my specifications are incorrect or if it's the program? I'm using STAR-2.7.10a. Any insight would be appreciated.

**Comment by alexdobin** [comment]
Hi @NikoHensley 
please check the Log.out file for the parameters STAR read from the command line. It looks like there may be a problem with the formatting of the command line.
