### ISSUE TITLE
std::bad_alloc creating index for large genome

### ISSUE THREAD

**Issue by darneson** [alexdobin/STAR#121]
Hi,
I am trying to create an index for drop seq experiments using STAR. To fine tune our drop seq setup we need to have a mixture of human and mouse cell lines. Drop seq provides a meta fasta and gtf file for these combined genomes and although generating an index for the human genome is ~30GB of ram others have said creating an index for this meta genome is ~60GB of ram. In order for me to get this amount of ram in a reasonable amount of time on the queuing system for the cluster that I am on, I need to request quite a few nodes. I have played with various configurations of nodes and memory sizes and tried looking into the source code but cannot figure out exactly why the job dies either in the 
sorting Suffix Array chunks and saving them to disk...
OR
loading chunks from disk, packing SA...
phase.
Most recently, it ran out of memory which was the size of the Suffix Arrays:
 Max vmem         = 47.104G

Number of SA indices: 11106432700
**SA size in bytes: 47202338976**
Mar 07 10:26:40 ... starting to sort  Suffix Array. This may take a long time...
Number of chunks: 27;   chunks size limit: 3612116768 bytes
Mar 07 10:27:24 ... sorting Suffix Array chunks and saving them to disk...

This most recent job died using 8 cores with 24GB of memory each.
I cannot figure out how much memory STAR needs per node when doing multithreaded for Index generation.
Any guidance would be much appreciated.

**Comment by roryk** [comment]
Hi @darneson,

As a workaround, rather than generate a combination genome, you can align to both the human and mouse genome separately and disambiguate the reads using this: https://github.com/AstraZeneca-NGS/disambiguate

**Comment by alexdobin** [comment]
Hi Douglas,

the total amount of RAM needed should be ~60GB, and will be shared between cores. however,
it will be allocated by one core. Usually, if you allocate M bytes per core for N cores, M*N bytes should be available to each core.
If you asked for 24GB per core and 8 cores per node, that should be more than enough. 8GB per core with 8 cores is just fine. I believe Max vmem=47GB is the memory shared between all cores.

Why do you think this is the problem with memory allocation?

Please try to run with just one core requesting 64GB - it will take a few hours, but could be a workaround if it's really the memory per core problem.

Cheers
Alex
