### ISSUE TITLE
Star index issues to the step 4 

### ISSUE THREAD

**Issue by Kisekya** [alexdobin/STAR#1214]
Hello!
 
I am trying to index a reference genome on a pipeline with snakemake and I made this rule:

`rule reference_faidx_star:`
`   input:`
            `    "../resources/reference/Qrob_PM1N.fa"`
`    output:`
`        "../resources/reference/ref/"`
`    threads: 1`
 `   log:` 
  `      "../results/logs/star/star_index.log"`
`    params:`
`        gtf= "../resources/reference/gff_gtf/Qrob_PM1N_genes_20161004.gtf"`
`    message:`
 `       """`
  `      INDEX STAR `
`        """`
`    shell:`
     `   "STAR --runMode genomeGenerate --runThreadN {threads} --genomeDir {output} --genomeFastaFiles {input} --sjdbGTFfile {params.gtf}` --sjdbOverhang 149 --genomeSAindexNbases 12 "`

At first everything works but there is a break at step 4.
Only 4 files are created in my folder: chrLength.txt, chrNameLength.txt, chrName.txt, chrStart.txt, and the terminal displays this:

_____________________________________________________________________________________________________
 [Tue Apr 20 09:09:30 2021]
Job 4: 
        INDEX STAR 
        

Apr 20 09:09:30 ..... started STAR run
Apr 20 09:09:30 ... starting to generate Genome files
Apr 20 09:09:50 ... starting to sort Suffix Array. This may take a long time...
Apr 20 09:09:55 ... sorting Suffix Array chunks and saving them to disk...
/usr/bin/bash : ligne 1 :  7343 Processus arrêté      STAR --runMode genomeGenerate --runThreadN 1 --genomeDir ../resources/reference/ref/ --genomeFastaFiles ../resources/reference/Qrob_PM1N.fa --sjdbGTFfile ../resources/reference/gff_gtf/Qrob_PM1N_genes_20161004.gtf --sjdbOverhang 149 --genomeSAindexNbases 12 -limitGenomeGenerateRAM 25000000000
[Tue Apr 20 09:10:01 2021]
Error in rule reference_faidx_star:
    jobid: 4
    output: ../resources/reference/ref/
    log: ../results/logs/star/star_index.log (check log file(s) for error message)
    shell:
        STAR --runMode genomeGenerate --runThreadN 1 --genomeDir ../resources/reference/ref/ --genomeFastaFiles ../resources/reference/Qrob_PM1N.fa --sjdbGTFfile ../resources/reference/gff_gtf/Qrob_PM1N_genes_20161004.gtf --sjdbOverhang 149 --genomeSAindexNbases 12 
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!) 
_____________________________________________________________________________________________________

I don't understand what is wrong with this rule, where I don't write in bash?

I hope you can help me.
Thank you,
 Have a nice day!
Coralie

**Comment by alexdobin** [comment]
Hi Coralie,

please try to run it with multiple threads, say ```--runThreadN 4```.
If this does not help, please send me the Log.out file.

Cheers
Alex

**Comment by Kisekya** [comment]
Hi Alex, 

Thanks for your help.
I tried with 4 threads but it didn't work. I only have 4 CPUs so maybe my computer is not powerful enough?
Even with a wrapper I get the same error. My command is `snakemake --use-conda -j 4
`
Here is my Log.out file of my shell command:
```

Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 4
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	1	reference_faidx_star
	2

[Mon Apr 26 07:59:50 2021]
Job 1: 
        INDEX STAR 
        

[Mon Apr 26 08:00:36 2021]
Error in rule reference_faidx_star:
    jobid: 1
    output: ../resources/reference/ref/
    log: ../results/logs/star/star_index.log (check log file(s) for error message)
    shell:
        STAR --runMode genomeGenerate --runThreadN 4 --genomeDir ../resources/reference/ref/ --genomeFastaFiles ../resources/reference/Qrob_PM1N.fa --sjdbGTFfile ../resources/reference/gff_gtf/Qrob_PM1N_genes_20161004.gtf --sjdbOverhang 149 --genomeSAindexNbases 12 
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job reference_faidx_star since they might be corrupted:
../resources/reference/ref/
Skipped removing non-empty directory ../resources/reference/ref/
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/coralie/Bureau/epitree/workflow/.snakemake/log/2021-04-26T075950.701898.snakemake.log

```



and the Log from the wrappers:

```
Building DAG of jobs...
Creating conda environment https:/github.com/snakemake/snakemake-wrappers/raw/0.74.0/bio/star/align/environment.yaml...
Downloading and installing remote packages.
Environment for ../../../../../tmp/tmpr1_ivso8.yaml created (location: .snakemake/conda/0e9369c9)
Using shell: /usr/bin/bash
Provided cores: 4
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	1	reference_faidx_star
	2

[Mon Apr 26 07:54:42 2021]
Job 1: 
        INDEX STAR 
        

Activating conda environment: /home/coralie/Bureau/epitree/workflow/.snakemake/conda/0e9369c9
[Mon Apr 26 07:54:44 2021]
Error in rule reference_faidx_star:
    jobid: 1
    output: ../resources/reference/ref/
    log: ../results/logs/star/star_index.log (check log file(s) for error message)
    conda-env: /home/coralie/Bureau/epitree/workflow/.snakemake/conda/0e9369c9

RuleException:
CalledProcessError in line 29 of /home/coralie/Bureau/epitree/workflow/rules/star_align_rule.smk:
Command 'source /home/coralie/anaconda3/bin/activate '/home/coralie/Bureau/epitree/workflow/.snakemake/conda/0e9369c9'; set -euo pipefail;  /usr/bin/python3 /home/coralie/Bureau/epitree/workflow/.snakemake/scripts/tmpux2y86mu.wrapper.py' returned non-zero exit status 1.
  File "/home/coralie/Bureau/epitree/workflow/rules/star_align_rule.smk", line 29, in __rule_reference_faidx_star
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
Removing output files of failed job reference_faidx_star since they might be corrupted:
../resources/reference/ref/
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/coralie/Bureau/epitree/workflow/.snakemake/log/2021-04-26T075359.632127.snakemake.log
```

**Comment by alexdobin** [comment]
Hi Coralie,

what version of STAR are you using? I would recommend trying the latest 2.7.8a, you can download it from GitHub and run the executable.
If this does not help, please send me the Log.out file for the failed run, which STAR should have generated in the run directory.
It's probably best to do this testing without snakemake to catch the actual OS error.

Cheers
Alex

**Comment by Kisekya** [comment]
Hi @alexdobin,

I am really sorry, I never received any notification that you had replied to me...
I'm really sorry, in the end I did what you told me and it works. 
However I have a problem in my data so I will open another issue to ask this new question.

Thanks a lot.

Coralie

**Comment by alexdobin** [comment]
Sure, no worries.
