### ISSUE TITLE
Output BAM file

### ISSUE THREAD

**Issue by alfonso-lam** [alexdobin/STAR#1219]
Hi,
The stats of my BAM file generated by STAR v2.7.7a looks strange:

samtools flagstat  NGS21-002181-SP-032421Aligned.sortedByCoord.out.bam
6402496 + 0 in total (QC-passed reads + QC-failed reads)
270334 + 0 secondary
30538 + 0 supplementary
0 + 0 duplicates
6302897 + 0 mapped (98.44% : N/A)
0 + 0 paired in sequencing
0 + 0 read1
0 + 0 read2
0 + 0 properly paired (N/A : N/A)
0 + 0 with itself and mate mapped
0 + 0 singletons (N/A : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)

**0 read1 and 0 read2?** 

The command I used was:

STAR --runThreadN 96 --genomeDir hg19 --readFilesIn basespace/NGS21-002181-SP-032421_0_filtered_R1.fastq.gz,basespace/NGS21-002181-SP-032421_1_filtered_R1.fastq.gz,basespace/NGS21-002181-SP-032421_2_filtered_R1.fastq.gz,basespace/NGS21-002181-SP-032421_0_filtered_R2.fastq.gz,basespace/NGS21-002181-SP-032421_1_filtered_R2.fastq.gz,basespace/NGS21-002181-SP-032421_2_filtered_R2.fastq.gz --limitBAMsortRAM 46610365695 --outFileNamePrefix NGS21-002181-SP-032421 --outSAMtype BAM SortedByCoordinate --outSAMattributes NH NM MD --outSAMunmapped Within --outSAMmapqUnique 50 --outSAMattrRGline ID:1 SM:NGS21-002181-SP-032421 --outSAMtlen 2 --outSJfilterCountUniqueMin -1 2 2 2 --outSJfilterCountTotalMin -1 2 2 2 --outFilterType BySJout --outFilterIntronMotifs RemoveNoncanonical --peOverlapNbasesMin 10 --peOverlapMMp 0.1 --chimSegmentMin 12 --chimScoreDropMax 30 --chimScoreSeparation 5 --chimJunctionOverhangMin 12 --chimOutType WithinBAM --chimSegmentReadGapMax 5 --sjdbGTFfile scripts/hg19.refGene_PanCancer.gtf --quantMode TranscriptomeSAM --quantTranscriptomeBan Singleend --twopassMode Basic --readFilesCommand zcat

What did I miss?
Thanks a lot
Alfonso

**Comment by alfonso-lam** [comment]
Hi Alex, 
I found the problem... There must be a space between Reads 1 and Reads 2.  Not so obvious to see with so many text. Thanks

**Comment by alexdobin** [comment]
Hi Alfonso,

to simplify command line, you can use ```--readFilesManifest``` to specify the file that contain FASTQ names, each line containing tab-separated Read1 \t Read2 \t ReadGroup

Cheers
Alex
