### ISSUE TITLE
Missing NM tags on some transcriptome alignments

### ISSUE THREAD

**Issue by roryk** [alexdobin/STAR#122]
Hi Alex,

Using STAR 2.5.0c there are transcriptome alignments without either a NM or nM tag, which breaks some downstream tools. Do you think the missing tag could get added to those alignments? I can provide example data that generates the alignments with the missing tag if that would be helpful.

**Comment by alexdobin** [comment]
Hi Rory,

I believe no alignments in the Aligned.toTranscriptome.out.bam should have NM or nM tags.
The samtools calmd can be used re-calculate it.
I will put on my TODO list to add these parameters to the output.

Cheers
Alex
