### ISSUE TITLE
Unrecognized parameter name "genomeType" in input "genomeParameters.txt"

### ISSUE THREAD

**Issue by louiejtaylor** [alexdobin/STAR#1221]
We're encountering a weird STAR error that we're having trouble solving. We're using STAR version 2.7.8a which we installed via bioconda. The error that we're getting is:

    EXITING: FATAL INPUT ERROR: unrecoginzed parameter name "genomeType" in input "genomeParameters.txt"
    SOLUTION: use correct parameter name (check the manual)

I can't find anyone else with this particular error by googling; but people with similar errors (specifically the "unrecognized parameter name") seem to have had issues with version incompatibility, maybe with the version that the index was built with versus the version of the software actually doing the alignment? We built the STAR index with 2.7.8a as well, so I don't think that's the issue.

The part that's confusing to me is that we successfully ran data from a different dataset using this same index, but the error doesn't seem to relate to the data as far as I can tell.

Here's some additional information that might be useful, such as the contents of `genomeParameters.txt`:

```
### STAR   --runMode genomeGenerate      --runThreadN 8   --genomeDir /home/emma/STAR_DESeq2/STARindex_04252021   --genomeFastaFiles /home/emma/STAR_DESeq2/STARindex_04252021/GRCh38.p13.genome.fa      --sjdbGTFfile /home/emma/STAR_DESeq2/STARindex_04252021/gencode.v37.annotation.gtf   --sjdbOverhang 100
### GstrandBit 32
versionGenome   2.7.4a
genomeType      Full
genomeFastaFiles        /home/emma/STAR_DESeq2/STARindex_04252021/GRCh38.p13.genome.fa 
genomeSAindexNbases     14
genomeChrBinNbits       18
genomeSAsparseD 1
genomeTransformType     None
genomeTransformVCF      -
sjdbOverhang    100
sjdbFileChrStartEnd     - 
sjdbGTFfile     /home/emma/STAR_DESeq2/STARindex_04252021/gencode.v37.annotation.gtf
sjdbGTFchrPrefix        -
sjdbGTFfeatureExon      exon
sjdbGTFtagExonParentTranscript  transcript_id
sjdbGTFtagExonParentGene        gene_id
sjdbInsertSave  Basic
genomeFileSizes 3440747876 26264897055
```

For some reason, although we have 2.7.8a installed, the version it was built with (`versionGenome`) seems to be 2.7.4a? We've tried to rebuild a few times and the result has always been the same. I have no idea where this different version (2.7.4a) is originating; we don't have it installed on our system anywhere that I can see. 

Finally, in terms of other potentially useful information, we are running STAR in the context of [this Snakemake workflow](https://github.com/snakemake-workflows/rna-seq-star-deseq2)--I apologize if my description of the problem is incomplete; the logic of running STAR is buried way down in the pipeline and I don't feel like I completely understand it.

Thanks very much!

**Comment by alexdobin** [comment]
Hi Louis,

in the ```genomeParameters.txt``` file ```versionGenome   2.7.4a``` indicates the **earliest** STAR version this genome is compatible with. So 2.7.8a should work with this genome. Please send me the Log.out file of the version that caused this problem. Also, I would recommend using the executables distributed with STAR on GitHub, it makes it easier to track actual versions.

Cheers
Alex

**Comment by Candle15** [comment]
Hi Alex

I'm having the same error. Were you able to sort it out?

**Comment by alexdobin** [comment]
Hi @Candle15 

there was no follow-up, so I do not think there was an issue in the code.
Please send me Log.out file of the failed run.

Cheers
Alex

**Comment by floklimm** [comment]
FYI: I obtained this error when using a reference created with a different version of STAR than used for the alignment.
Recreating the reference genome with the same version fo STAR solved this problem.

**Comment by Justin1609** [comment]
Hi @alexdobin 

I am getting the following error when trying to run STAR script on the index I got as an output from crossmapper

[jasmus@n05 /scratch]$ module load app/STAR/2.7.4a
[jasmus@n05 /scratch]$ bash alignment_for_crossmapper.pbs
Aug 10 12:41:00 ..... started STAR run
Aug 10 12:41:00 ..... loading genome

EXITING: FATAL INPUT ERROR: unrecognized parameter name "genomeType" in input "genomeParameters.txt"
SOLUTION: use correct parameter name (check the manual)

Aug 10 12:41:00 ...... FATAL ERROR, exiting

The script I am running looks as follows:

`#!/bin/bash
#PBS -N justin_star_map
#PBS -l walltime=24:00:00
#PBS -l ncpus=32
#PBS -l mem=100GB
#PBS -q bix
#PBS -e prog.err
#PBS -o prog.out
#PBS -M jasmus@sun.ac.za
#PBS -m a

cd $PBS_O_WORKDIR

module load app/STAR/2.7.4a
STAR --runThreadN 10 --genomeDir /home/jasmus/Cleo_Raw_data/crossmap_out/STAR_index --sjdbGTFfile /home/jasmus/Cleo_Raw_data/crossmap_out/concat.gtf --sjdbOverhang 74 --readFilesIn /home/jasmus/Cleo_Raw_data/crossmap_out/wgsim_output/concat_75_read1.fastq  --outSAMtype BAM Unsorted --outFileNamePrefix /home/jasmus/Cleo_Raw_data/crossmap_out/STAR_output/concat_75_SE_ --outFilterMismatchNmax 5 --outFilterMultimapNmax 10000 --outFilterMismatchNoverReadLmax 0.04 --alignIntronMax 0`

I have attached the genomeParameters.txt file as well as the Log.out file

I am running this on a remotely hosted server, but I have solved the issue of the fifo file not being able to be created which I was previously experiencing. Any suggestions for this new error would be greatly appreciated.
[genomeParameters.txt](https://github.com/alexdobin/STAR/files/6960993/genomeParameters.txt)
[Log.out.txt](https://github.com/alexdobin/STAR/files/6960998/Log.out.txt)

**Comment by marwa38** [comment]
having same error and using the latest version haven't solved the problem

**Comment by alexdobin** [comment]
This is an old issue. Please open a new one and provide details for your specific case.

**Comment by ShadyYounis** [comment]
the error is gone when I used the new STAR version 2.7.9a

**Comment by Datacond** [comment]
@alexdobin 
Hi Alex
Recently, I have the same question and I have read the possible answers in Github.
My code is :
```
/public/home/zl/software/STAR-2.7.4a/bin/Linux_x86_64_static/STAR \
--runMode alignReads \
--runThreadN 10 \
--genomeDir ${index_dir} \
--readFilesCommand zcat \
--readFilesIn ${seq1_file} ${seq2_file} \
--outSAMtype BAM SortedByCoordinate \
--outBAMsortingThreadN 8
--outFileNamePrefix ${out_prefix}
```
Log.out :
```
WARNING: --limitBAMsortRAM=0, will use genome size as RAM limit for BAM sorting
Finished loading and checking parameters
Reading genome generation parameters:
### STAR   --runMode genomeGenerate      --runThreadN 33   --genomeDir /proj/STARmapping   --genomeFastaFiles /proj/Chromosomes.masked.fa      --genomeSAindexNbases 14   --genomeChrBinNbits 18   --limitGenomeGenerateRAM 100000000000
### GstrandBit=35
versionGenome                 2.7.4a     ~RE-DEFINED

EXITING: FATAL INPUT ERROR: unrecognized parameter name "genomeType" in input "genomeParameters.txt"
SOLUTION: use correct parameter name (check the manual)

Nov 07 10:41:09 ...... FATAL ERROR, exiting
```
Index generation used  one server.mapping used another server
STAR version for index generation is the same as STAR version for mapping(2.7.4a ).

**Comment by alexdobin** [comment]
Hi @Datacond 

please re-generate the genome with the same version you are using for mapping.
