### ISSUE TITLE
Same UMI for multiple genes in STARsolo

### ISSUE THREAD

**Issue by gheager** [alexdobin/STAR#1224]
Hi,

I have a question concerning the UMI deduplication in STARsolo. How does STARsolo deduplicate a UMI shared by several reads that are not assigned to the same gene? Are they counted separately?

Thanks a lot!
Guillaume

**Comment by alexdobin** [comment]
Hi Guillame,

the behavior for such inconsistent UMIs is determined by the *--soloUMIfiltering* option.
By default, there is no filtering, and they are counted separately (i.e. assigned to different genes).

*--soloUMIfiltering MultiGeneUMI* considers the number of reads per gene for a given CB/UMI. The counting is not done for genes that have fewer than the maximum read number. If max read number = 1, such inconsistent UMI is not counted for any genes.

*--soloUMIfiltering MultiGeneUMI_CR* is similar to the above, but it follows CellRanger's algorithm and checks the read number before and after UMI error correction.

Cheers
Alex

**Comment by gheager** [comment]
Hi Alex,

Thanks for your answer. It's nice to have these options.

Cheers,
Guillaume
