### ISSUE TITLE
Should complex cell barcodes be treated as simple ones?

### ISSUE THREAD

**Issue by alanlamsiu** [alexdobin/STAR#1227]
Hi Alex,

I am aware that several cell barcodes can be ligated by adapters to generate the primer sequences in some platform, such as inDrop and ddSeq. I understand that you have made an option to specify the complex cell barcode pattern in STARsolo, e.g. for inDrop. But do you agree that we can also treat the complex barcodes as simple ones, by concatenating the cell barcodes and adapters? I am thinking about this issue because errors could occur in equal frequency in either primer synthesis or sequencing. Do you any insights on this issue when using STARsolo?

Thanks!
Xiao

**Comment by alexdobin** [comment]
Hi Xiao,

definitely, if you can merge all barcode sequences into one, it should work fine.
I am not sure how this changes the treatment of barcode errors, it seems to me either way we need to allow for errors in the barcodes.

Cheers
Alex

**Comment by alanlamsiu** [comment]
Hi Alex,

I tend to merge all barcode and adapter sequences into one and the statistics generated by STARsolo looks fine. But I have no idea how to treatment the errors in the barcode or adapter regions differently as there is no prior knowledge about it.

Cheers,
Xiao
