### ISSUE TITLE
ungapped alignment

### ISSUE THREAD

**Issue by ATPs** [alexdobin/STAR#123]
I am using RSEM to analysize gene expression. I wanted to change the aligner to STAR, because it is much faster. I have the mRNA sequences, instead of genome sequence and gff3 file. I think the '--quantMode' option does not work for this case. 
I tried to align with star, and still it is very very fast. But the output is not compatible with RSEM. So I think if the '--quantTranscriptomeBan IndelSoftclipSingleend' like option can be applied to the reference "genome" sequence, this problem can be solved.

Thank you for this powerful and life-saving tool!

**Comment by alexdobin** [comment]
Hi Xiaolong,

if you map to mRNA sequences, you do not need to use the gff3 file and the --quantMode option.
The alignments to mRNAs (Aligned.out.bam) can be fed directly into RSEM.

The gff3 file and --quantMode TranscriptomeSAM is only used if you are mapping to the whole genome, but want to convert the alignments into transcriptomic coordinates.

Cheers
Alex

**Comment by ATPs** [comment]
I tried, but get warning from RSEM that RSEM does * not * support gapped alignments. I am using the newest version of RSEM. 

Anyway, I'll try again to see if I am using the right method.
Thank you, Alex.

**Comment by alexdobin** [comment]
Hi Xiaolong,

I forgot to tell you that if you are mapping to mRNA for RSEM, you would need to prohibit splicing, indels, and soft clipping (i.e. all operations except M in CIGAR). You can do this with:
--alignEndsType EndToEnd --alignIntronMax 1 --alignIntronMin 2  --scoreDelOpen -10000  --scoreInsOpen -10000 

Cheers
Alex

**Comment by ATPs** [comment]
I guess this is what I want. I did not realize the EndToEnd option.
Thank you a lot!

Best
Xiaolong
