### ISSUE TITLE
Chimeric reads with STARSolo

### ISSUE THREAD

**Issue by 14zac2** [alexdobin/STAR#1231]
Hi there!

I'm hoping to use STARSolo to detect chimeric in single-cell data, however I'm not sure the it is working as hoped. I previously ran STAR on the R2 reads of my single-cell (i.e. without the cell barcode) and STAR detected 8,283,135 chimeric reads. However, when I ran STARSolo on my reads + cell barcodes, the number of chimeric reads detected in the same sample is 57,590,807 which is way larger. I am worried that perhaps the chimeric algorithm included the cell barcode when looking for chimeric reads, which would most definitely make many of the reads look like chimeras. Do you know if STARSolo has the capacity to accurately detect chimeric reads?

Many thanks,
Zoe

**Comment by 14zac2** [comment]
Hi Alex,

Thanks for getting back to me so soon! That is also what I suspected, regarding the chimeric mapping. My command was as follows:

```
STAR \
--genomeDir ../../../index_STAR_woodchuck_mito_virus \
--runThreadN 20 \
--readFilesIn /home/L207_TLH_S7_L001_R2_001.fastq.gz,\
/home/L207_TLH_S7_L002_R2_001.fastq.gz,\
/home/L207_TLH_S7_L003_R2_001.fastq.gz,\
/home/L207_TLH_S7_L004_R2_001.fastq.gz,\
/home/L207_TLH_S7_L005_R2_001.fastq.gz,\
/home/L207_TLH_S7_L006_R2_001.fastq.gz,\
/home/L207_TLH_S7_L007_R2_001.fastq.gz,\
/home/L207_TLH_S7_L008_R2_001.fastq.gz \
/home/L207_TLH_S7_L001_R1_001.fastq.gz,\
/home/L207_TLH_S7_L002_R1_001.fastq.gz,\
/home/L207_TLH_S7_L003_R1_001.fastq.gz,\
/home/L207_TLH_S7_L004_R1_001.fastq.gz,\
/home/L207_TLH_S7_L005_R1_001.fastq.gz,\
/home/L207_TLH_S7_L006_R1_001.fastq.gz,\
/home/L207_TLH_S7_L007_R1_001.fastq.gz,\
/home/L207_TLH_S7_L008_R1_001.fastq.gz \
--soloCBwhitelist ../../737K-august-2016.txt \
--genomeSAsparseD 3 \
--soloCBmatchWLtype 1MM_multi_Nbase_pseudocounts \
--soloUMIfiltering MultiGeneUMI_CR \
--soloUMIdedup 1MM_CR \
--soloCellFilter  EmptyDrops_CR \
--readFilesCommand gunzip -c \
--outFileNamePrefix ./starSolo_output/ \
--genomeLoad NoSharedMemory \
--outSAMtype BAM Unsorted \
--outSAMunmapped Within \
--outBAMcompression 0 \
--outFilterMultimapNmax 1 \
--outFilterMismatchNmax 3 \
--chimSegmentMin 10 \
--chimOutType WithinBAM SoftClip \
--chimJunctionOverhangMin 10 \
--chimScoreMin 1 \
--chimScoreDropMax 37 \
--chimScoreJunctionNonGTAG 0 \
--chimScoreSeparation 1 \
--alignSJstitchMismatchNmax 5 -1 5 5 \
--chimSegmentReadGapMax 3
```
I tried including the parameter `--soloType CB_UMI_Simple` but this threw the error `EXITING because of fatal PARAMETERS error: --soloUMIdedup=1MM_CR is not allowed for --soloType CB_UMI_Simple
SOLUTION: used allowed options: Exact or 1MM_All or 1MM_Directional` so I left it out. It is possible that this is my problem and I still need to fiddle with the parameters a bit more. I was trying to get my parameters make the run similar to CellRanger v5 which I have been using.

Thanks,
Zoe

**Comment by 14zac2** [comment]
I just wanted to quickly mention that I updated STAR from version 2.7.5c to 2.7.8a which seems to have impacted the above error. I will see if this also changes the results.

**Comment by 14zac2** [comment]
These changes make much more sense. I now have 4512345 or 1.80% chimeric reads. It must have been a version control and parameter issue making STAR read the barcodes as cDNA.

**Comment by alexdobin** [comment]
Hi Zoe,

these numbers make more sense.
All reads are indeed in the BAM file, the cell barcodes are just added to the normal STAR alignments. Note that for reads that do not map uniquely to genes (i.e. do not have GX/GN tags), the CB/UMI error correction is not performed.

Cheers
Alex

**Comment by 14zac2** [comment]
Thanks Alex!

I just have one more comment on that. In the end, I decided to filter my bam file by cell barcode. I tried using samtools and the CB to isolate the desired cells from a list of barcodes, but these didn't appear to keep any chimeric reads (I'm guessing that's what you mean by reads that do not uniquely map to a single gene are not corrected), so I'm now using the CR tag. Although I can't work with corrected data, this seems to be the best option.

Many thanks again for your insight!
Zoe

**Comment by alexdobin** [comment]
Hi Zoe,

you can, in principle, do a "manual" correction this way by creating CR -> CB lookup table from all alignments in the SAM file.
Then correct CR tags using the correspondence table.

I will switch on the CB error correction for all reads in the future.

Cheers
Alex

**Comment by synnimeng** [comment]
> Hi Zoe,
> 
> you can, in principle, do a "manual" correction this way by creating CR -> CB lookup table from all alignments in the SAM file. Then correct CR tags using the correspondence table.
> 
> I will switch on the CB error correction for all reads in the future.
> 
> Cheers Alex

Hi Alex,

I wonder if you have added CB error correction function for all reads in the latest version. I didn't find any information about that.

Sincerely,
Synni
