### ISSUE TITLE
BRB-seq / Quant-Seq 3' tag bulk RNA-seq analysis with STARsolo

### ISSUE THREAD

**Issue by tomsing1** [alexdobin/STAR#1232]
Dear Alex,

Congrats on the new STARsolo preprint. I am using a commercial variant of the BRB-seq protocol (called [QuantSeq](https://www.lexogen.com/quantseq-3mrna-sequencing/#quantseqworkflow)) to generate bulk RNA-seq data with UMIs.

I would love to use STARsolo to get from demultiplexed FASTQ files to a deduplicated count matrix. I have seen your example for SmartSeq scRNA-seq data, which contains neither cell barcodes (CB) nor UMIs. In my case, **I have UMIs, but no CB**, e.g. all reads in the FASTQ file are from the same (bulk) sample.

Perhaps you could help me get started with an example of the STAR options that I could use?

Many thanks,
Thomas

**Comment by alexdobin** [comment]
Hi Thomas,

Thanks!
There is no direct option to run it without CBs but with UMIs.
But I think you can hack around it this way:
You need to add 1 base (say A) to the end of the UMI read. This will be your "cell barcode", which you need to place in a passlist file (it will contain only one letter A).

You can do it on the fly with process substitution, something like:
```
--readFilesIn <(zcat cDNAread.gz) <(zcat UMIread.gz | awk '{if (NR%2==0) $0=$0 "A"; print}')
--soloUMIstart 1 --soloUMIlen <umiLength> --soloCBstart <umiLength+1> --soloCBlen 1
--soloType CB_UMI_Simple --soloCBwhitelist passlist.txt
```

Cheers
Alex

**Comment by tomsing1** [comment]
Just posting what I learned, in case it's helpful to others using the QuantSeq library preparation kit. 
It turns out QuantSeq-UMI libraries contain

- a 6 NT UMI at the start of the read and
- a constant 4 nt spacer (`TATA`)

So I can use the latter as a dummy cell barcode (CB).

Combining the STAR settings recommended by Lexogen (see [here](https://www.lexogen.com/quantseq-data-analysis/)) and @alexdobin 's suggestion, I am using the following arguments now:

```
FASTQ="fastq/test.fastq.gz"
INDEX="index"
CORES=12
PASSLIST="passlist.txt"
OUTDIR="results"

echo "TATA" > "${PASSLIST}"

STAR \
  --readFilesIn "${FASTQ}" \
  --genomeDir "${INDEX}" \
  --runThreadN "${CORES}" \
  --readFilesCommand "gzip -cd" \
  --clip3pAdapterSeq polyA \
  --outFilterType BySJout \
  --outFilterMultimapNmax 20 \
  --alignSJoverhangMin 8 \
  --alignSJDBoverhangMin 1 \
  --outFilterMismatchNmax 999 \
  --outFilterMismatchNoverLmax 0.1 \
  --alignIntronMin 20 \
  --alignIntronMax 1000000 \
  --alignMatesGapMax 1000000 \
  --outSAMattributes NH HI NM MD \
  --outSAMtype BAM SortedByCoordinate \
  --clip5pNbases 39 \
  --soloBarcodeMate 1 \
  --soloType CB_UMI_Simple \
  --soloCBstart 7 \
  --soloCBlen 4 \
  --soloUMIstart 1 \
  --soloUMIlen 6 \
  --soloCellFilter None \
  --soloCBwhitelist "${PASSLIST}" \
  --outFileNamePrefix "${OUTDIR}/" \
  --soloMultiMappers Uniform EM \
  --soloStrand Forward
```

**Comment by alexdobin** [comment]
Hi Thomas,

thanks a lot for sharing your experience with this protocol, it will be helpful to other users!

Cheers
Alex

**Comment by grst** [comment]
Hi @tomsing1, 

thanks for sharing, this is really useful! 
I understand most of the parameters, but was wondering where you got the `39` for `--clip5pNbases 39 \` from? 

Cheers, 
Gregor

**Comment by tomsing1** [comment]
Good catch @grst ! That was a copy-paste carry-over from the [Starsolo README](https://github.com/alexdobin/STAR/blob/master/docs/STARsolo.md#barcode-and-cdna-on-the-same-mate). 
Corrected!
