### ISSUE TITLE
Ram requirement 

### ISSUE THREAD

**Issue by mortunco** [alexdobin/STAR#124]
Hello,

Even though I have read you seqanswer threads I couldnt obtain a certain answer for my question. I am intending to align ~20 Gb fastq files of 10  + reference hg19. How much ram should I need to process this data ?

Thank you for your time,

Best,

Tunc.

**Comment by alexdobin** [comment]
Hi Tunc,

for 20 Gbase reference, you would need ~20*9=180GBytes.
You can reduce this amount by using --genomeSAsparseD <N>, which will require
20*(1+8/N) Gbytes.

Cheers
Alex

**Comment by mortunco** [comment]
Dear Alex thanks for the rapid answer but i believe you missunderstood me. My reference is hg19 ( 3gb). Each of my RNAseq fastq files are 20 Gb.

Thanks in advance,

Tunc.

**Comment by alexdobin** [comment]
Hi Tunc,

the size of the files does not affect the required RAM. 

Cheers
Alex
