### ISSUE TITLE
Segmentation fault (core dumped) error

### ISSUE THREAD

**Issue by lyj95618** [alexdobin/STAR#1240]
Hello,

I am running a pipeline that runs the STAR version 2.6.1c with the WASP mode. I requested 1 node with 10 cores and 80GB RAM on the cluster. The indices are created with the same version of STAR. I received the Segmentation fault (core dumped) error. I checked the log file, it seemed to get stuck after the threads were created. Any help will be appreciated! 

Quick note: I have also tried to run STAR on this sample without `--varVCFfile` and `--waspOutputMode` and the alignment worked normally and no error came out.

Thank you very much
Laur

Here is my STAR command and attached is the log file from STAR

STAR --runMode alignReads \
        --runThreadN 10 \
        --varVCFfile $vcf \
        --waspOutputMode SAMtag \
        --readFilesCommand zcat \
        --readFilesIn $read1 $read2 \
        --genomeDir $index \
        --outFileNamePrefix $prefix \
        --twopassMode Basic \
        --sjdbGTFfile $gtf \
        --outFilterType BySJout \
        --limitSjdbInsertNsj 1200000 \
        --outSAMstrandField intronMotif \
        --outFilterIntronMotifs None \
        --alignSoftClipAtReferenceEnds Yes \
        --quantMode TranscriptomeSAM GeneCounts \
        --outSAMtype BAM Unsorted \
        --outSAMattrRGline ID:$samplename  SM:$samplename  PL:ILLUMINA \
        --outSAMattributes All \
        --outSAMunmapped Within \
        --outSAMprimaryFlag AllBestScore \
        --chimSegmentMin 15 \
        --chimJunctionOverhangMin 15 \
        --chimOutType Junctions \
        --chimMainSegmentMultNmax 1 \
        --genomeLoad NoSharedMemory
[cp26wasp_441Log.txt](https://github.com/alexdobin/STAR/files/6503299/cp26wasp_441Log.txt)

**Comment by alexdobin** [comment]
Hi Laur,

2.6.1c is quite old, please switch to a more recent version, preferrably the latest.
If it does not reslove the issues, please try to map with a minimal set of parameters: 
```--genomeDir ... --readFilesCommand zcat --readFilesIn```

Cheers
Alex

**Comment by lyj95618** [comment]
Hi Alex,

Thanks for your reply. After some detective work, the problem was resolved. This was due to the presence of an asterisk sign in the ALT column for some of the variants in the vcf file. I am not sure why it caused the segmentation fault. After removing those varaints, things are normal now.

example row:
6	43469667	.	T	* 	1407.60	PASS	AC=1;AF=0.625	GT	0|1

Thanks
Laur

**Comment by alexdobin** [comment]
Hi Laur,

thanks for letting me know! I should do more careful parsing of the VCFs to filter out such cases.

Cheers
Alex
