### ISSUE TITLE
Results Question: High uniquely mapped reads percent

### ISSUE THREAD

**Issue by JonEilers** [alexdobin/STAR#1241]
Hi, 
I have been mapping rna-seq data to some fruit tree genomes and by all appearances getting good results. Recently, a PI felt that those results were too good to be true which has resulted in me trying to find information on mapping rates. See below for one example and the command used. I have generated similar results using data from several different cultivar rna-seq datasets. All were mapped to the same genome which is highly contiguous and contains chromosome scale scaffolds. Is the result realistic and does the command seem appropriate? 

command
```bash
star \
	--runThreadN 7 \
	--limitBAMsortRAM 6443418567 \
	--alignIntronMax 10000 \
	--outSAMtype BAM SortedByCoordinate \
	--outFileNamePrefix  /Users/jon.eilers/Desktop/PRJNA611986_redclapp_anthocyanin/star_mapped_bam/red_clapp_anthocyanin \
	--outSAMstrandField intronMotif \
	--genomeDir /Users/jon.eilers/Desktop/pyrus_genome_index \
	--readFilesIn
```

results
```bash
                                 Started job on |	Mar 08 21:51:01
                             Started mapping on |	Mar 08 21:51:08
                                    Finished on |	Mar 09 00:20:39
       Mapping speed, Million of reads per hour |	278.11

                          Number of input reads |	693024259
                      Average input read length |	150
                                    UNIQUE READS:
                   Uniquely mapped reads number |	633697209
                        Uniquely mapped reads % |	91.44%
                          Average mapped length |	148.86
                       Number of splices: Total |	276291006
            Number of splices: Annotated (sjdb) |	0
                       Number of splices: GT/AG |	273495069
                       Number of splices: GC/AG |	2405577
                       Number of splices: AT/AC |	154972
               Number of splices: Non-canonical |	235388
                      Mismatch rate per base, % |	0.75%
                         Deletion rate per base |	0.06%
                        Deletion average length |	2.84
                        Insertion rate per base |	0.02%
                       Insertion average length |	2.62
                             MULTI-MAPPING READS:
        Number of reads mapped to multiple loci |	20270067
             % of reads mapped to multiple loci |	2.92%
        Number of reads mapped to too many loci |	17973859
             % of reads mapped to too many loci |	2.59%
                                  UNMAPPED READS:
  Number of reads unmapped: too many mismatches |	0
       % of reads unmapped: too many mismatches |	0.00%
            Number of reads unmapped: too short |	21030295
                 % of reads unmapped: too short |	3.03%
                Number of reads unmapped: other |	52829
                     % of reads unmapped: other |	0.01%
                                  CHIMERIC READS:
                       Number of chimeric reads |	0
                            % of chimeric reads |	0.00%
```

**Comment by alexdobin** [comment]
Hi Jon,

usually, it's the opposite problem, with % of unique mappers too low. :)
I do not see anything seriously suspicious in these results. They look like the best human or mouse libraries.
A bit odd thing is that the mismatch rate is quite high (~0.75% vs typical ~<0.5%), but the mappability is still very good.
Is your species expected to be sequence-divergent to the reference, with, say ~0.5% substitution rate?

One possibility of seeing such a low (for plants) multimapping rate is that the genome assembly was somehow "scrubbed" off the repeat sequences, while it still contains most of the transcribed sequences.

Do you have transcript annotation for this genome? It is highly recommended to use it if you have, it will likely further improve mappability. If you do not have annotations, than the 2-pass alignment is a good option (```--twoPassMode Basic```), which will recover more spliced reads.

Cheers
Alex

**Comment by thomasperson** [comment]
What commands where used to generate pyrus_genome_index?

**Comment by JonEilers** [comment]
See below for command used to generate genome index

```bash
star  \
--runThreadN 7 \
--runMode genomeGenerate \
--genomeDir /Users/jon.eilers/Desktop/For_Jon/star_index \
--genomeFastaFiles /Users/jon.eilers/Desktop/For_Jon/Pyrus_communis_DAnjou_chr.v0.1.fa \
--genomeSAindexNbases 13
```

**Comment by JonEilers** [comment]
see below for command used to generate genome index
```bash
star \
--runThreadN 7 \
--runMode genomeGenerate \
--genomeDir /Users/jeilers/Desktop/star_mapping \
--genomeFastaFiles /Users/jeilers/Desktop/PyrusCommunis_BartlettDHv2.0.fasta \
--genomeSAindexNbases 13
```

**Comment by JonEilers** [comment]
Gotcha. So the annotations for this genome are pretty bad. A number of genes we were interested were missing from genome annotations. If I were to use that flag, would those missing genes not have reads mapped to them?

**Comment by thomasperson** [comment]
Dunno.  We're me, I'd just add the missing genes to the GTF.

**Comment by alexdobin** [comment]
Hi Thomas, Jon,

when annotations (GTF) are used, the mapping is still done against the whole genome. Annotations just help to find alignments for read that are spliced over annotated junctions. It does **not** prevent mapping to unannotated regions of the genome or unannotated splices. It does give some preference to reads mapped to annotated junctions.

Adding annotations - even if they are of poor quality - is always beneficial.
For poor quality annotations, the 2-pass alignment is recommended to improve mapping for unannotated junctions.

Cheers
Alex
