### ISSUE TITLE
genomeGenerate takes a long time (> 5 days， 2 genome fastas)

### ISSUE THREAD

**Issue by Liying1996** [alexdobin/STAR#1252]
Hi! I have a problem on building index when I used 2 genomeFastaFiles .
Here is my codes:

> STAR \
> 	--runThreadN 16 \
> 	--runMode genomeGenerate \
> 	--limitGenomeGenerateRAM 62000000000 \
> 	--genomeDir STAR_idx_diploid \
> 	--genomeFastaFiles ~/GIAB_hg38/pgenome_HG001/HG001_hap1.fa ~/GIAB_hg38/pgenome_HG001/HG001_hap2.fa \
> 	--outFileNamePrefix STAR_idx_diploid_

But It took a lone time and still running...
Here is the log:

> May 25 02:05:15 ..... started STAR run
> May 25 02:05:15 ... starting to generate Genome files
> May 25 02:09:50 ... starting to sort Suffix Array. This may take a long time...
> May 25 02:11:16 ... sorting Suffix Array chunks and saving them to disk...

And I'm sure that my free RAM is enough `(free -g):`

```
      total        used        free      shared  buff/cache   available
 Mem:            503         307         116           0          80         187
 Swap:            29           2          26
```

But I can build the index successfully when I used only 1 fasta file (HG001_hap1.fa or HG001_hap2.fa), it takes only 0.5 hour.
code:

> STAR \
> 	--runThreadN 16 \
> 	--runMode genomeGenerate \
> 	--genomeDir STAR_idx_diploid2 \
> 	--genomeFastaFiles ~/GIAB_hg38/pgenome_HG001/HG001_hap2.fa \
> 	--outFileNamePrefix STAR_idx_diploid2_

log:

> May 24 23:08:34 ..... started STAR run
> May 24 23:08:34 ... starting to generate Genome files
> May 24 23:10:46 ... starting to sort Suffix Array. This may take a long time...
> May 24 23:11:27 ... sorting Suffix Array chunks and saving them to disk...
> May 24 23:34:30 ... loading chunks from disk, packing SA...
> May 24 23:37:15 ... finished generating suffix array
> May 24 23:37:15 ... generating Suffix Array index
> May 24 23:43:19 ... completed Suffix Array index
> May 24 23:43:19 ... writing Genome to disk ...
> May 24 23:43:28 ... writing Suffix Array to disk ...
> May 24 23:44:45 ... writing SAindex to disk
> May 24 23:44:54 ..... finished successfully

I don't know what went wrong？Could you give me some suggestions?
Thanks for any help :)

**Comment by alexdobin** [comment]
Hi Liying

it looks like you are building the index for two haplotypes, which means there are long identical sequences, which significantly increases the suffix array sorting time.
To reduce the time, please specify ```--genomeTransformOutput 500```
Instead of 500, you can specify the maximum read length for your samples, which will be even faster.

Cheers
Alex

**Comment by Liying1996** [comment]
Thank you very much! I'll have a try!
