### ISSUE TITLE
Error when running soloType SmartSeq and outSAMattributes

### ISSUE THREAD

**Issue by sarah-chapin** [alexdobin/STAR#1253]
I am trying to run STARsolo with the following command:

`STAR \
            --soloType SmartSeq \
            --readFilesManifest manifest.txt \
            --readFilesCommand zcat \
            --soloUMIdedup Exact \
            --soloStrand Unstranded \
            --soloFeatures Gene \
            --runThreadN {threads} \
            --genomeDir {params.index} \
            --outReadsUnmapped Fastq \
            --outSAMtype BAM SortedByCoordinate \
            --outSAMattributes CR CY UR UY CB UB \
`
I want to access the sequences, quality scores, cell barcodes, and UMI's for solo demultiplexing, so that the large BAM file output can be split and qc can then be run. However, I receive the following error:

`EXITING because of FATAL INPUT ERROR: --outSAMattributes contains CR/CY/UR/UY/CB/UB tags which are not allowed for --soloType SmartSeq
SOLUTION: re-run STAR without these attribures`

Is there a way to run STARsolo SmartSeq and obtain the outSAMattributes for solo demultiplexing?

My STAR version is 2.7.8.

**Comment by alexdobin** [comment]
Hi Sarah,

the SmartSeq does not normally contain cell barcodes or UMIs, as each cell is stored in a separate fastq file.
You can add *RG* to the *--outSAMattributes* list (e.g. *--outSAMattributes NH HI nM AS RG*) which will add RG tag to each alignment from the 3rd column of the file manifest. This way you can track which alignments belonged to which cells.

Cheers
Alex

**Comment by sarah-chapin** [comment]
Hi Alex,

Thanks for the help. This worked quite well.

Best,
Sarah
