### ISSUE TITLE
Does STAR use "remap_original_location" field from the annotation gtf file?

### ISSUE THREAD

**Issue by Biojenifer** [alexdobin/STAR#1255]
Hi!

In order to create STAR reference index I had to format chromosome names from the gtf file in order to fit them with the reference fasta file. So I had to transform "chr2" to "2", for example. And I also has to format mitochondrial chromosome from "M" to "MT".

I did this in the corresponding chromosome field. However, I have just realized that there is another field in the gtf, named "remap_original_location", which also contains chromosome coordinates for each feature. I wasn´t aware of this field so I didn´t transform it. The pipeline worked okay, but I would like to know if this could generate some problems for downstream analysis. 

Do you know if STAR uses this field, or if it just uses chr start and end corresponding fields.

This is a part of the gtf I used, downloaded from GENCODE release 35: gencode.v35lift37.annotation.gtf

`1 HAVANA gene 11869 14409 . + . gene_id "ENSG00000223972.5_4"; gene_type "transcribed_unprocessed_pseudogene"; gene_name "DDX11L1"; level 2; hgnc_id "HGNC:37102"; havana_gene "OTTHUMG00000000961.2_4"; remap_status "full_contig"; remap_num_mappings 1; remap_target_status "overlap";`

`1 HAVANA transcript 11869 14409 . + . gene_id "ENSG00000223972.5_4"; transcript_id "ENST00000456328.2_1"; gene_type "transcribed_unprocessed_pseudogene"; gene_name "DDX11L1"; transcript_type "processed_transcript"; transcript_name "DDX11L1-202"; level 2; transcript_support_level 1; hgnc_id "HGNC:37102"; tag "basic"; havana_gene "OTTHUMG00000000961.2_4"; havana_transcript "OTTHUMT00000362751.1_1"; remap_num_mappings 1; remap_status "full_contig"; remap_target_status "overlap";`

`1 HAVANA exon 11869 12227 . + . gene_id "ENSG00000223972.5_4"; transcript_id "ENST00000456328.2_1"; gene_type "transcribed_unprocessed_pseudogene"; gene_name "DDX11L1"; transcript_type "processed_transcript"; transcript_name "DDX11L1-202"; exon_number 1; exon_id "ENSE00002234944.1_1"; level 2; transcript_support_level 1; hgnc_id "HGNC:37102"; tag "basic"; havana_gene "OTTHUMG00000000961.2_4"; havana_transcript "OTTHUMT00000362751.1_1"; remap_original_location "chr1:+:11869-12227"; remap_status "full_contig";`

`1 HAVANA exon 12613 12721 . + . gene_id "ENSG00000223972.5_4"; transcript_id "ENST00000456328.2_1"; gene_type "transcribed_unprocessed_pseudogene"; gene_name "DDX11L1"; transcript_type "processed_transcript"; transcript_name "DDX11L1-202"; exon_number 2; exon_id "ENSE00003582793.1_1"; level 2; transcript_support_level 1; hgnc_id "HGNC:37102"; tag "basic"; havana_gene "OTTHUMG00000000961.2_4"; havana_transcript "OTTHUMT00000362751.1_1"; remap_original_location "chr1:+:12613-12721"; remap_status "full_contig";`
`

As you can see, field 1 (field chr) is formatted '1', while field remap_original_location (when it exist) is formatted 'chr1'. Would this affect the alignment, the gene counting, the chimeric reads detection  or any other output from STAR?

Thanks!

**Comment by alexdobin** [comment]
Hi @Biojenifer 

remap_original_location is not used by STAR.
The only tags that are used are gene_id and transcript_id.

Cheers
Alex

**Comment by Biojenifer** [comment]
Nice! Thanks!
