### ISSUE TITLE
Running STARsolo without Annotation

### ISSUE THREAD

**Issue by Cheyujlee** [alexdobin/STAR#1259]
Dear STAR team,

Thank you for creating the software! But currently, we are having trouble running STARsolo without an annotation file. Whereas before, we never ran into trouble running (bulk) STAR without an annotation file. Is this a STARsolo-specific issue? Below is our log file.

Thank you for your help,
Cheyu.

`STAR --runThreadN 32 --outFileNamePrefix /lv_scratch/scratch/cheyul1/excessSTAR-2.7.8a/j10_run0/virus/output/ --genomeDir /lv_scratch/scratch/cheyul1/excessSTAR-2.7.8a/indices/virus.genomeDir/ --readFilesIn /lv_scratch/scratch/cheyul1/excessSTAR-2.7.8a/j10_run0/human/output/Unmapped.out.mate1.fastq /lv_scratch/scratch/cheyul1/excessSTAR-2.7.8a/j10_run0/human/output/Unmapped.out.mate2.fastq --soloType CB_UMI_Simple --soloCBwhitelist /lv_scratch/scratch/cheyul1/excessSTAR-2.7.8a/737K-august-2016.txt --soloCBstart 1 --soloCBlen 16 --soloUMIstart 17 --soloUMIlen 10`

STAR version: 2.7.9a   compiled: 2021-05-04T09:43:56-0400 vega:/home/dobin/data/STAR/STARcode/STAR.master/source
Jun 03 19:00:39 ..... started STAR run
Jun 03 19:00:39 ..... loading genome

Transcriptome.cpp:14:Transcriptome: exiting because of *INPUT FILE* error: could not open input file /lv_scratch/scratch/cheyul1/excessSTAR-2.7.8a/indices/virus.genomeDir//geneInfo.tab
Solution: check that the file exists and you have read permission for this file
          SOLUTION: utilize --sjdbGTFfile /path/to/annotations.gtf option at the genome generation step or mapping step

Jun 03 19:00:43 ...... FATAL ERROR, exiting

**Comment by alexdobin** [comment]
Hi Cheyu,

STARsolo does require the annotation file - its task is to quantify the gene expression, so it needs to know where the genes are.
Do you just want to map the reads and have the cell barcode CB tag added to the BAM file?
This can be done with ```--soloType CB_samTagOut```, and adding CB and UR (uncorrected UMI) to the attributes list, e.g.
```--outSAMattributes NH HI nM AS CB UR```. Note that the 1st file in ```--readFilesIn``` should be cDNA and the 2nd file should be barcode read.

Chers
Alex

**Comment by Cheyujlee** [comment]
Hi Alex,

Thank you for responding so fast! I have just done what you have said and the result was successful. I did indeed want to map the reads only to the genome, count the mappings, and include the cell barcode CB tag in the output BAM file. Thank you for your help!

Have a good day,
Cheyu.

**Comment by jsimonas** [comment]
Hi, just wanted to inform that  `--soloType CB_samTagOut` does not work without annotations on the 2.7.11b version.
