### ISSUE TITLE
Softmasked alignments in transcriptome BAM preventing RSEM from running

### ISSUE THREAD

**Issue by ifiddes** [alexdobin/STAR#126]
I am getting soft masked sequences in my transcriptome SAM.

Invocation example:

STAR --genomeDir STAR_references/PWK_PhJ --readFilesIn /hive/groups/recon/projs/mus_strain_cactus/data/assembly_rel_1505/fastqs/ftp-mouse.sanger.ac.uk/REL-1505-RNA-Seq/fastq/PWK_PhJ/rna-seq/unc/brain/SRR1924506_2.fastq.gz /hive/groups/recon/projs/mus_strain_cactus/data/assembly_rel_1505/fastqs/ftp-mouse.sanger.ac.uk/REL-1505-RNA-Seq/fastq/PWK_PhJ/rna-seq/unc/brain/SRR1924506_1.fastq.gz --outFileNamePrefix aligned_new_reference/PWK_PhJ/unc/brain/SRR1924506/ --outTmpDir /scratch/tmp/tmp6zVr3r/localTempDir/tmp_tYWlY4xkHZ --runThreadN 8 --outSAMunmapped Within --outSAMtype BAM SortedByCoordinate  --outBAMcompression -1 --outFilterType BySJout --outSAMattributes NH HI AS NM MD --outFilterMultimapNmax 20 --outFilterMismatchNmax 999 --outFilterMismatchNoverReadLmax 0.04 --alignIntronMin 20 --alignIntronMax 1000000 --alignMatesGapMax 1000000 --alignSJoverhangMin 8 --alignSJDBoverhangMin 1 --sjdbScore 1 --readFilesCommand zcat --quantMode TranscriptomeSAM --quantTranscriptomeBan Singleend --
outWigType wiggle --limitBAMsortRAM 80000000000

Error example:

rsem-calculate-expression --bam aligned_new_reference/CAST_EiJ/unc/brain/SRR1920270/Aligned.toTranscriptome.out.bam  STAR_references/CAST_EiJ/CAST_EiJ RSEM --paired-end
rsem-parse-alignments STAR_references/CAST_EiJ/CAST_EiJ RSEM.temp/RSEM RSEM.stat/RSEM aligned_new_reference/CAST_EiJ/unc/brain/SRR1920270/Aligned.toTranscriptome.out.bam 3 -tag XM
Read SRR1920270.261793: RSEM currently does not support gapped alignments, sorry!

grep for offending reads:

samtools view aligned_new_reference/CAST_EiJ/unc/brain/SRR1920270/Aligned.toTranscriptome.out.bam | grep SRR1920270.261793
SRR1920270.261793	419	jg18715.t1	549	3	99M1S	=	626	177	AGCAGATGAAATGTTAAGCCGAGGGTTCAAGGATCAGATCTNTGACATATTCCAGAAGCTCAACAGCAACACACAGGTAGTTTTGTTGTCTGCTACAATC	^P\cccc``e[ceeeafaadcP[bdHP^cc`ef]eZX^a_^BONUaeWa]S\bHWed`c_c]HZ\GUZHZZTZ]PT\ZTTYTZGX^^X^`BBBBBBBBB	NH:i:2	HI:i:1
SRR1920270.261793	339	jg18715.t1	626	3	100M	=	549	-177	TAGTTTTGTTGTCTGCTACAATGCCTTCTGATGTCCTTGAGGTGACCAAGAAATTTATGAGAGACCCTATTCGGATTCTTGTCAAGAAGGAAGAATTGAC	BBBBBBa_caa_ZUGGMHHMH_Qdb^V\S_b\UGWHgbb]ae^XW[_^^XIISXfaaa_[[ffcddXHeb`[J[JYRffgbY``J[aeb^Wb`\`\c^Y	NH:i:2	HI:i:1
SRR1920270.261793	419	jg18715.t2	501	3	99M1S	=	578	177	AGCAGATGAAATGTTAAGCCGAGGGTTCAAGGATCAGATCTNTGACATATTCCAGAAGCTCAACAGCAACACACAGGTAGTTTTGTTGTCTGCTACAATC	^P\cccc``e[ceeeafaadcP[bdHP^cc`ef]eZX^a_^BONUaeWa]S\bHWed`c_c]HZ\GUZHZZTZ]PT\ZTTYTZGX^^X^`BBBBBBBBB	NH:i:2	HI:i:2
SRR1920270.261793	339	jg18715.t2	578	3	100M	=	501	-177	TAGTTTTGTTGTCTGCTACAATGCCTTCTGATGTCCTTGAGGTGACCAAGAAATTTATGAGAGACCCTATTCGGATTCTTGTCAAGAAGGAAGAATTGAC	BBBBBBa_caa_ZUGGMHHMH_Qdb^V\S_b\UGWHgbb]ae^XW[_^^XIISXfaaa_[[ffcddXHeb`[J[JYRffgbY``J[aeb^Wb`\`\c^Y	NH:i:2	HI:i:2

**Comment by ifiddes** [comment]
I realized that the command 'quantTranscriptomeBan' is not longer documented. Has this been removed/is this the problem?

**Comment by alexdobin** [comment]
Hi Ian,

the --quantTranscriptomeBan is described on p.38 of the manual.
By default, it bans soft clipping in the Aligned.toTranscriptome.out.bam output and this makes it compatible with RSEM. Since you changed this option to --quantTranscriptomeBan Singleend , the soft-clipping is allowed, making it incompatible with RSEM.

Cheers
Alex

**Comment by ifiddes** [comment]
Hi Alex,

Sorry for the confusion. Thanks for the information.
