### ISSUE TITLE
Few or No Reads Aligned to Specific Reference Chromosome / Contig in STAR Alignment

### ISSUE THREAD

**Issue by cwarden45** [alexdobin/STAR#1261]
Hi,

I am using a custom reference sequence for some RNA-Seq analysis.  It is mostly comprised of the main galGal5 chromosomes (but 1 is smaller because it relates to the region being assembled) and 4 additional contigs from some assembled sequence.  The 4 additional contigs are the following sizes: 412,369 bp, 148,501 bp, 138,921 bp, and 45,013 bp.

If I use a TopHat2 alignment, the alignments to **all 4 contigs** look more-or-less like I would expect.  However, I wanted to compare the splice junction tables from STAR.

The 1st 3 contigs look good for the STAR alignment.  **However, the 4th contig (the 45,013 bp one) has little or no alignments using STAR.**

**This is the command that I used to generate the reference**:

`/net/isi-dcnl/ifs/user_data/Seq/STAR-2.5/bin/Linux_x86_64_static/STAR --runMode genomeGenerate --genomeDir ./ --genomeFastaFiles $combinedRef`

And these are the 4 sets of parameters that I have tested (but still have little or no alignments per-sample for Contig4).

**Alignment Parameter Set 1)**: `$STAR --genomeDir $REFref --readFilesIn $READ1 $READ --runThreadN 4 --outFileNamePrefix $OUTPREFIX --twopassMode Basic --outSAMstrandField intronMotif`

**Alignment Parameter Set 2)**: `$STAR --genomeDir $REFref --readFilesIn $READ1 $READ --runThreadN 4 --outFileNamePrefix $OUTPREFIX --alignIntronMax 2000 --twopassMode Basic --outSAMstrandField intronMotif`

**Alignment Parameter Set 3)**: `$STAR --genomeDir $REFref --readFilesIn $READ1 $READ --runThreadN 4 --outFileNamePrefix $OUTPREFIX --alignIntronMax 2000 --alignMatesGapMax 5000 --twopassMode Basic --outSAMstrandField intronMotif`

**Alignment Parameter Set 4)**: `$STAR --genomeDir $REFref --readFilesIn $READ1 $READ --runThreadN 4 --outFileNamePrefix $OUTPREFIX --alignIntronMax 2000 --outFilterMultimapNmax 50 --outFilterMismatchNoverLmax 0.1 --outFilterIntronMotifs RemoveNoncanonical --twopassMode Basic --outSAMstrandField intronMotif`

I believe the `--alignIntronMax 2000` parameter is needed to help seeing too many splice junctions between other members of the gene family on the same contig.  However, I think the other parameters may or may not be needed.

There are large sequence duplications, but the alignments look OK in the duplicated regions between Contig1 and Contig2.  Additionally, the alignment rate to Contig4 is not always 0, so I don't think that I currently see anything obvious like accidentally omitting that sequence from the reference.

Can you please help me troubleshoot this issue?

Thank you very much.

Sincerely,
Charles

**Comment by cwarden45** [comment]
Hi Alex,

Thank you very much!

There are gene copies on Contigs 1, 2 and 4 (4 being the small one where the STAR alignments don't appear).

I am confused why there are alignments to the copies on Contig1 and Contig2, but not Contig 4.

However, I will look into the effect of turning of the `--twopassMode` (and maybe the `--winAnchorMultimapNmax`).

Thank you again!

Sincerely,
Charles

**Comment by alexdobin** [comment]
Hi Charles,

if you have exact sequence copies, you should see alignments to all of them (or none if ```--outFilterMultimapNmax``` is exceeded). I would recommend checking it manually for a few reads.

Cheers
Alex

**Comment by cwarden45** [comment]
Also, if it helps, this is what happens if I look for all the alignments for 1 read in one of the gene copies (with paired-end RNA-Seq reads):

```
[username@server Folder]$ samtools view SRR924539_4contig.bam | grep SRR924539.20108212 -
SRR924539.20108212      419     Contig1 326413  3       16M114N84M      =      326602   372     CCCTTCTTCTCCTTCCCTGACTTGCTCTTCCACACCACCAATCCAACAACAACAGCGATGACAGCCACAAAGGCAACGACCGGTTCTGGCACAATGAGGA    CCCFFFFFHHHFHIJJJJJJJJIJJJIJJJJJJJJJJJJJJIJIIIJJJJIGGIEIIJIGIIGHFHHHFFFFEDEEDDDDDB##################    NH:i:2  HI:i:2 AS:i:192 nM:i:5  XS:A:-
SRR924539.20108212      339     Contig1 326602  3       43M83N57M       =      326413   -372    ACGACCGCTCCGGCCACAATGGGGATCAGGTTGGGCTGTGGCTCCCACAAGAAGAGGCCAGGCTGGGGCAGGCTGGCGTGCTCCACGCAGCACTGGTACT    @BB>DDBB<DDDDDCCDCDCDDCDCDBDDDDDDDDEDDEFFDCGHJJJIJJJJJIJIGJJJJJJJJJIJJJIJIJJJJJJJJJJJJJHHHHHFFFFFB@@    NH:i:2  HI:i:2 AS:i:192 nM:i:5  XS:A:-
SRR924539.20108212      163     Contig2 5283    3       16M114N84M      =      5472     372     CCCTTCTTCTCCTTCCCTGACTTGCTCTTCCACACCACCAATCCAACAACAACAGCGATGACAGCCACAAAGGCAACGACCGGTTCTGGCACAATGAGGA    CCCFFFFFHHHFHIJJJJJJJJIJJJIJJJJJJJJJJJJJJIJIIIJJJJIGGIEIIJIGIIGHFHHHFFFFEDEEDDDDDB##################    NH:i:2  HI:i:1 AS:i:192 nM:i:5  XS:A:-
SRR924539.20108212      83      Contig2 5472    3       43M83N57M       =      5283     -372    ACGACCGCTCCGGCCACAATGGGGATCAGGTTGGGCTGTGGCTCCCACAAGAAGAGGCCAGGCTGGGGCAGGCTGGCGTGCTCCACGCAGCACTGGTACT    @BB>DDBB<DDDDDCCDCDCDDCDCDBDDDDDDDDEDDEFFDCGHJJJIJJJJJIJIGJJJJJJJJJIJJJIJIJJJJJJJJJJJJJHHHHHFFFFFB@@    NH:i:2  HI:i:1 AS:i:192 nM:i:5  XS:A:-

```
It seems to me like allowing 3 alignments should have been enough to cover the gene copy on Contig4.  However, I am currently looking at the effect of the 2-pass alignment, and I will continue to troubleshoot.

**Comment by cwarden45** [comment]
Because Contig 4 is an order of magnitude smaller than the others, I also went back to the reference indexing step.

So, I am also testing adding the parameter `--genomeChrBinNbits 14`.  Hopefully, I have understood what that parameter does, and I will report the the result of the testing (when available).

**Comment by cwarden45** [comment]
As a partial update, with a qualitative assessment of the alignment in IGV, I think skipping the 2-pass alignment _might have increased the Contig4 alignment somewhat_.  So, I will leave that parameter at the default value.

However, the alignment still looks very different than I think it should.  For example, with TopHat2 (or STAR, on Contig1 and Contig2) most genes have some level of coverage across the whole genome.  However, even with the possibly increased alignment, there is usually not more than 1-2 fragments (with duplicates for the same genomic position) per gene with the STAR alignment on Contig4, and the divergence in IGV looks much higher than I think should have been allowed (and there is little or no variation in the reads versus the reference in the gene copies for Contig1 or Contig2).

I am not sure if it will help, but the alternative index is now created and I have started those alignments.

**Comment by cwarden45** [comment]
I apologize that I am still encountering the same issue (with the alternate indexed reference, as well as testing adding the `--winAnchorMultimapNmax 200` parameter).

If possible, do you have any other troubleshooting suggestions?

Thank you very much for your help!

**Comment by cwarden45** [comment]
As an update, I created a new reference sequence where **each chromosome / contig was within 1 line**.

For the 1st 2 alignments that have completed, this seems to have fixed the problem with the most clear problem with the Contig4 alignments.

So, I think something about concatenating files from different places with different lengths of sequence in the FASTA file might have caused a problem.

I hope that this might help others, if they encounter a similar problem!
