### ISSUE TITLE
Error installing on MacBook Pro M1

### ISSUE THREAD

**Issue by Rosie23** [alexdobin/STAR#1265]
Having problems installing STAR on my MacBook Pro M1. When I run make I get the following error;
"g++-11: error: unrecognized command-line option '-mavx2'"

make STARforMacStatic CXX=/opt/homebrew/Cellar/gcc/11.1.0_1/bin/g++-11
date: illegal option -- -
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
cd opal && \
	/opt/homebrew/Cellar/gcc/11.1.0_1/bin/g++-11 -c -I./ -std=c++11   -O3 -std=c++11 -fopenmp -D'COMPILATION_TIME_PLACE=" :/Users/rosie/Downloads/STAR-master/source"' -D'COMPILE_FOR_MAC' -pipe -Wall -Wextra  -mavx2 opal.cpp
g++-11: error: unrecognized command-line option '-mavx2'
make: *** [opal/opal.o] Error 1

Any help would be much appreciated.

**Comment by Rosie23** [comment]
Fixed, manage to install it via Conda, yay!

**Comment by alexdobin** [comment]
Hi Rosie,

it's great that bioconda has it compiled, do they specify the flags they used?
I do not have an M1 Mac, so cannot try it myself.
I googled around for the proper flags to use with M1, and it seems the compiler support for it is lacking.
One option to try would be "native":
```make CXX_SIMD_FLAGS=-march=native```
It should be the safest option, but it may not yet work on M1.

Cheers
Alex

**Comment by thouchin-cpu** [comment]
Hey Rosie,
How were you able to install conda for m1?

**Comment by Rosie23** [comment]
Yes managed to install it, thanks

**Comment by mfansler** [comment]
@thouchin-cpu @Rosie23 might be worth noting that, last I checked, Bioconda merely redistributes the compiled versions that this repository provides. So, installing through Conda is unlikely to be a native build and instead is just emulating x86_64.

**Comment by chanaDrori** [comment]
Hi, I am trying to build the docker image on mac pr M1, and it failed with the same error. 
https://github.com/alexdobin/STAR/blob/master/extras/docker/Dockerfile
Do you have any flag for the make that can resolve it?
Thanks.

**Comment by jalilsharif** [comment]
I have a Mac m2, and I get the following error:
```
date: illegal option -- -
usage: date [-jnRu] [-I[date|hours|minutes|seconds]] [-f input_fmt]
            [-r filename|seconds] [-v[+|-]val[y|m|w|d|H|M|S]]
            [[[[mm]dd]HH]MM[[cc]yy][.SS] | new_date] [+output_fmt]
cd opal && \
	c++ -c -I./ -std=c++11   -O3 -std=c++11 -fopenmp -D'COMPILATION_TIME_PLACE=" :/Users/anon/Downloads/STAR/source"' -D'GIT_BRANCH_COMMIT_DIFF=""' -pipe -Wall -Wextra  -std=c++11 opal.cpp
clang: error: unsupported option '-fopenmp'
make: *** [opal/opal.o] Error
```
using conda does not work either.

**Comment by jalilsharif** [comment]
@akhst7 

I did follow your suggestion, and now the error I am getting is as follows:

```
bam_cat.c:57:10: fatal error: cstring: No such file or directory
   57 | #include <cstring>
      |          ^~~~~~~~~
compilation terminated.
make: *** [bam_cat.o] Error 1
```

**Comment by akhst7** [comment]
@jalilsharif 

can you post outputs of following;

```
clang -v
Xcode-select -v
sw_vers 
```

**Comment by jalilsharif** [comment]
@akhst7 
'''
$ clang -v                                         
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: arm64-apple-darwin22.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

$ Xcode-select -v 
Xcode-select version 2397.

$ sw_vers
ProductName:		macOS
ProductVersion:		13.3.1
BuildVersion:		22E261
'''

**Comment by akhst7** [comment]
@jalilsharif 

Here is my clang version
```
clang -v
Homebrew clang version 16.0.1
Target: arm64-apple-darwin22.4.0
Thread model: posix
InstalledDir: /opt/homebrew/opt/llvm/bin
```
I am not 100% sure if the apple supplied clang complains about omp support.  but you could have brew version of clang by installing the latest llvm 16.0.1 as mine;

```
brew info llvm
==> llvm: stable 16.0.1 (bottled), HEAD [keg-only]
Next-gen compiler infrastructure
https://llvm.org/
/opt/homebrew/Cellar/llvm/16.0.1 (6,779 files, 1.5GB)
  Poured from bottle using the formulae.brew.sh API on 2023-04-06 at 10:42:56
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/llvm.rb
License: Apache-2.0 with LLVM-exception
==> Dependencies
Build: cmake ✔, swig ✘
Required: python@3.11 ✔, six ✔, z3 ✔, zstd ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
To use the bundled libc++ please add the following LDFLAGS:
  LDFLAGS="-L/opt/homebrew/opt/llvm/lib/c++ -Wl,-rpath,/opt/homebrew/opt/llvm/lib/c++"

llvm is keg-only, which means it was not symlinked into /opt/homebrew,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

If you need to have llvm first in your PATH, run:
  echo 'export PATH="/opt/homebrew/opt/llvm/bin:$PATH"' >> ~/.zshrc

For compilers to find llvm you may need to set:
  export LDFLAGS="-L/opt/homebrew/opt/llvm/lib"
  export CPPFLAGS="-I/opt/homebrew/opt/llvm/include"
==> Analytics
install: 1,210 (30 days), 66,198 (90 days), 458,769 (365 days)
install-on-request: 1,110 (30 days), 57,897 (90 days), 356,579 (365 days)
build-error: 18 (30 days)
```

As stated, all you have to do is to set the llvm path in your bashrc and restart your shell.  

BTW,  what steps did you take to install Star  ?

**Comment by jalilsharif** [comment]
@akhst7 

I have installed llvm now.

I did the following changes
```
#CXXFLAGS_SIMD ?= -mavx2
```

then ```cd source```


finally

``` 
make STARforMacStatic CXX=/opt/homebrew/Cellar/gcc/12.2.0/bin/gcc-12
```

**Comment by akhst7** [comment]
try a following and see what ;

`make STARforMacStatic CXX=g++-12`

**Comment by davincios** [comment]
> @akhst7
> 
> I have installed llvm now.
> 
> ran
> 
> `echo 'export PATH="/opt/homebrew/opt/llvm/bin:$PATH"' >> ~/.zshrc`
> 
> I did the following changes
> 
> ```
> #CXXFLAGS_SIMD ?= -mavx2
> ```
> 
> then `cd source`
> 
> finally
> 
> ```
> make STARforMacStatic CXX=/opt/homebrew/Cellar/gcc/12.2.0/bin/gcc-12
> ```

I have them mavx2 issue on Mac M1, and followed the discussion and steps taken, the only thing I don't understand is what changes you made here:

"I did the following changes: #CXXFLAGS_SIMD ?= -mavx2" 

Could you please help?

Best,
Vincent

**Comment by mfansler** [comment]
@davincios edit [the Makefile](https://github.com/alexdobin/STAR/blob/45fe3dd0a74048b40a91dd58f8f008e66dae3b58/source/Makefile#L45) to comment out that flag.

**Comment by davincios** [comment]
> @davincios looks like they edited [the Makefile](https://github.com/alexdobin/STAR/blob/45fe3dd0a74048b40a91dd58f8f008e66dae3b58/source/Makefile#L45) to comment out that flag.

Awesome thank you!!

Now I am getting this issue...work in progress...

`zsh
incent@Vincents-MacBook-Air-3 source % make STARforMacStatic CXX=/opt/homebrew/Cellar/gcc/13.1.0/bin/gcc-13

date: illegal option -- -
usage: date [-jnRu] [-I[date|hours|minutes|seconds]] [-f input_fmt]
            [-r filename|seconds] [-v[+|-]val[y|m|w|d|H|M|S]]
            [[[[mm]dd]HH]MM[[cc]yy][.SS] | new_date] [+output_fmt]
Depend.list:1: *** missing separator.  Stop.`

**Comment by davincios** [comment]
Update: 
You have to run:

$make clean

 to remove previous builds, after which it will build and then you get a new error: 
 
 /opt/homebrew/Cellar/gcc/13.1.0/bin/gcc-13 -c  -pipe -Wall -Wextra -O3 bam_cat.c
bam_cat.c:57:10: fatal error: cstring: No such file or directory
   57 | #include <cstring>
      |          ^~~~~~~~~
compilation terminated.
make: *** [bam_cat.o] Error 1

**Comment by mfansler** [comment]
@davincios g++

**Comment by mjsteinbaugh** [comment]
I can confirm that setting `CXXFLAGS_SIMD=-std=c++11` fixes the build issue for me on Apple Silicon. Here's my build script, for reference:

https://github.com/acidgenomics/koopa/blob/main/lang/bash/include/install/common/shared/star.sh

Best,
Mike
