### ISSUE TITLE
Unmapped Files Contain Many Mappable Reads But Status 00

### ISSUE THREAD

**Issue by DarioS** [alexdobin/STAR#1267]
I have total RNA-seq data and I ran the Unmapped.out.mate1 file for one cancer sample through HUMAnN microbiome profiler as a test. 99.2% of reads did not map to the bacterial reference genomes. I then went to BLAST a few of the reads and found many good hg38 matches. Something striking is that many of them have N as the second base at the beginning of the file (about the first dozen).

```
@A00121:71:HFFY2DSXX:2:1101:15573:1031 0:N:  00
CNAAGTTTCTGTGCTTCAGCAGATCTGTTACTGCCACCCATTATCAAGCCATAGGTATGCACGTGGTGAGTCATCAGCTCCTTAAGAACACCAAAGGTTTGCATGGCTAGTTCTCTAGTAGGTGAGAGAATAA
+
F#FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
@A00121:71:HFFY2DSXX:2:1101:1985:1047 0:N:  00
CNCAGAGAAAGACAGCCTGGGCGCAGGCCCACCTCCCCTGGGGTCTCGGGACTGCGTGTGTCTGACAGTACAGGCAGGGGCCAGGCTGACATCTCCCT
+
F#FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
@A00121:71:HFFY2DSXX:2:1101:4842:1047 0:N:  00
CNTCTTGAACTCTCTCTTCAAAGTTCTTTTCAACTTTCCCTTACGGTACTTGTTGACTATCGGTCTCGTGCCGGTATTTAGCCTTAGATGGAGTTTACCACCCGCTTT
+
F#:FFFFFFF,:FF,F:F:FFFFFFFFFFFFFFF,FF,FF:FFF:FFFF,,:FFFF::F,F,FFFFFFFFFFFFFF,FFF,FF:,F,F,,:F,FFFF:FF,FFFF,FF
@A00121:71:HFFY2DSXX:2:1101:21549:1047 0:N:  00
ANCACGGGAGTTTTGACCTGCTCCGTTTCCGACCTGGGCCGGTTCACCCCTCCTTAGGCAACCTGGTGGTCCCCCGCTCCCGGGAGGTCACCATATTGATGCCGAACTTAGTGCGGACACCCGA
+
F#FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFF
@A00121:71:HFFY2DSXX:2:1101:31620:1047 0:N:  00
CNGCCCTACTCAGGATACCGCTAAGTAAAACAAAGCTTTCATATACGGGAGTATCACCCTCTATGCTTAATCTTTCCAGATTATTCTATTAGCTAAGTTTAGTCTATATCGCAG
+
F#FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFF,FFFFFFFFFFFFFFFFFFFFF,FFFFFFFFFFFFF:FFFFFF:FF:F,:,FFFFFFFFFFFF
```

Let's take the first read and look at its alignment. It aligns perfectly to DDX18, ignoring the first two bases of the read.

```
Identities:131/131(100%),  Gaps:0/131(0%), Strand: Plus/Minus

Query  3    AAGTTTCTGTGCTTCAGCAGATCTGTTACTGCCACCCATTATCAAGCCATAGGTATGCAC  62
            ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
Sbjct  981  AAGTTTCTGTGCTTCAGCAGATCTGTTACTGCCACCCATTATCAAGCCATAGGTATGCAC  922

Query  63   GTGGTGAGTCATCAGCTCCTTAAGAACACCAAAGGTTTGCATGGCTAGTTCTCTAGTAGG  122
            ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
Sbjct  921  GTGGTGAGTCATCAGCTCCTTAAGAACACCAAAGGTTTGCATGGCTAGTTCTCTAGTAGG  862

Query  123  TGAGAGAATAA  133
            |||||||||||
Sbjct  861  TGAGAGAATAA  851
```

Let's take the sixth read and look at its alignment. It aligns perfectly to KRT6B, ignoring the first three bases of the read.

```
Identities:147/147(100%),  Gaps:0/147(0%), Strand: Plus/Minus

Query  4     GGTCCAGGTTGCGGTTGTTGTCCATGGATAGCACCACGGATGTGTCTGAGATGTGGGTCT  63
             ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
Sbjct  1056  GGTCCAGGTTGCGGTTGTTGTCCATGGATAGCACCACGGATGTGTCTGAGATGTGGGTCT  997

Query  64    GCATCTGGGACAGCTCTGCATCATACAAGGCTCTCAGGAAGTTGATCTCATCTGTAAGAG  123
             ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
Sbjct  996   GCATCTGGGACAGCTCTGCATCATACAAGGCTCTCAGGAAGTTGATCTCATCTGTAAGAG  937

Query  124   TGTCTGCCTTGGCTTGCAGTTCAACCT  150
             |||||||||||||||||||||||||||
Sbjct  936   TGTCTGCCTTGGCTTGCAGTTCAACCT  910
```

The reads have different lengths because they have been trimmed by cutadapt. For ease of testing, the FASTQ entries for the pair of reads corresponding to the first example (after adapter trimming) is

```
@A00121:71:HFFY2DSXX:2:1101:15573:1031 1:N:0:CCAAGTCT+AAGGATGA
CNAAGTTTCTGTGCTTCAGCAGATCTGTTACTGCCACCCATTATCAAGCCATAGGTATGCACGTGGTGAGTCATCAGCTCCTTAAGAACACCAAAGGTTTGCATGGCTAGTTCTCTAGTAGGTGAGAGAATAA
+
F#FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
```

and

```
@A00121:71:HFFY2DSXX:2:1101:15573:1031 2:N:0:CCAAGTCT+AAGGATGA
GGGGGGGGGGGGGGGGGGGGGGGGGGGGAGGAAGAAAAAACAAAAAAAAAAAAAAATAAATTAAATAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
+
FFFFFFFFFFFFFFFF:F:F:::::,,,,,,,,,,,,,,,,,,,:,:,,,,,,,,,,,,,:,,,,,,,,,,,,,,,,:F,,,F:,:,F,,::,:,,,,:,,,:,,,,,F,,F,,:,,F:F,,:F,,F::FF:,FF,::FF::,::,:,F
```

This problem happens with version 2.7.3 of the software. I read the user manual and was reminded that if one read of a read pair is not mapped, both reads will end up in the unmapped files, but the reads shown above have 00 status which is "both mates were not mapped". However, as I have demonstrated above, one of the reads in the pair has an excellent genomic alignment, so I would at least expect to see status 10 instead of 00. Could it have something to do with the merging of overlapping pairs?

**Comment by alexdobin** [comment]
Hi Dario,

01 and 10 in Unmapped output serve to mark those cases where the PE read is mapped as a whole (i.e. passed mapped filtering and is output to Aligned.out.*), but one of the mates is not mapped even partially (i.e. it's not output to Aligned.out.bam).
If a PE read is not mapped as a whole, it will get 00 tag, as the mapping filter is not applied to separate mates.

The workaround for your case would be to map the Unmapped files as single-end to the human genome again, and then map the resulting unmapped read to the bacterial reference.
Or you can remap the Unmapped reads to the human genome with relaxed mapping filter, allowing for SE alignments:
```--outFilterScoreMinOverLread 0.33 --outFilterMatchNminOverLread 0.33```
Then you will see 01 and 10 in the Unmapped file for reads where only one mate maps to the human genome, and you can remapped them to the bacterial reference.

Generally, an even better approach is to map to combined human/bacterial reference.

Cheers
Alex

**Comment by DarioS** [comment]
Ah, O.K. For the benefit of other readers finding this, I use `--outFilterMismatchNoverReadLmax 0.1` which discards reads for which the mismatches are more than 10% of the reads. Because the filter applies to a paired read overall, not to each of its constituent reads independently, if the first read perfectly matches the human genome but the second read is all garbage, the pair of reads will both be discarded.
