### ISSUE TITLE
Genome indexes generation incomplete

### ISSUE THREAD

**Issue by maringa780** [alexdobin/STAR#1269]
I've been trying to generate the genome indexes but the process stops after a few minutes. I've attached the Log file I get. I'm not sure why this keeps happening. This was done using 250G memory cpu. Please assist (below are the links for the genome sequence file and gtf file I used). 
**Genome sequence file:** http://ftp.ensembl.org/pub/release-104/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz 
**GTF file:** http://ftp.ensembl.org/pub/release-104/gtf/homo_sapiens/Homo_sapiens.GRCh38.104.gtf.gz

Thank you

[Log.zip](https://github.com/alexdobin/STAR/files/6665405/Log.zip)

**Comment by alexdobin** [comment]
Hi @maringa780 

please add ```--runThreadN 2``` (or more threads, up to the number of processor cores). On some systems the default 1 causes problems for some reason.
Also, I would avoid specifying ```--limitGenomeGenerateRAM```, it's only needed if you have <32GB of RAM.

Cheers
Alex

**Comment by maringa780** [comment]
> Hi @maringa780
> 
> please add `--runThreadN 2` (or more threads, up to the number of processor cores). On some systems the default 1 causes problems for some reason.
> Also, I would avoid specifying `--limitGenomeGenerateRAM`, it's only needed if you have <32GB of RAM.
> 
> Cheers
> Alex

Hi @alexdobin 

It's working well now, thank you!

-John
