### ISSUE TITLE
Mapping Single-Cell Microwell-seq Datasets such as BD Rhapsody

### ISSUE THREAD

**Issue by Cheyujlee** [alexdobin/STAR#1273]
Dear STAR team,

Thank you for creating such a fast aligner! I had much success mapping droplet-based single-cell 10X sequencing reads, but I am currently having trouble mapping a microwell-seq dataset from BD Rhapsody cDNA Kit (BD Biosciences, 633773). The dataset is a paired-end seq both ends with reads of 150 bp.

My questions are: What would I need to specify in my command line? Would they be the same as droplet-based 10X (CB, UMI, whitelist)? And would there need to be any additional options?

I am currently having a hard time finding the lengths of the cell barcodes/UMI and whitelists in the BD rhapsody system, so not having to specify them would be a lot more convenient for me.

Much thanks!
Cheyu.

**Comment by alexdobin** [comment]
Hi Cheyu,

I do not have experience with BD Rhapsody, but there here is a suggestion from other users: https://github.com/alexdobin/STAR/issues/1111.
Please try it out and let me know whether it works.

Cheers
Alex

**Comment by alexdobin** [comment]
Hi Cheyu,

right, ```--soloType CB_UMI_Complex``` requires whitelists.
I think this page contains the links to them as CLS1,2,3:
https://teichlab.github.io/scg_lib_structs/methods_html/BD_Rhapsody.html
You would need to save them as 3 separate files and supply these files in the ```--soloCBwhitelist BD_CLS1.txt BD_CLS2.txt BD_CLS3.txt``` .

If you try it out, please let me know how it goes. It's important to check that you are detecting barcodes in most reads, these metrics are written in ```Solo.out/Barcodes.stats``` file.

Cheers
Alex

**Comment by Cheyujlee** [comment]
Ah I see! Sorry for the clumsiness. I will give it a try now.

Thank you!
Cheyu.

**Comment by Cheyujlee** [comment]
Hi Alex,

The solution worked perfectly! Thank you for always moderating and giving help! I will close this issue now.

Thanks!
Cheyu.

**Comment by cathalgking** [comment]
@Cheyujlee Did you manage to align the BD Rhapsody data with STAR? How did you do it? I am trying to align a BD Rhapsody single-cell dataset with Abseqs.
