### ISSUE TITLE
malloc issue?

### ISSUE THREAD

**Issue by cnk113** [alexdobin/STAR#1277]
Hey Alex,

I've been trying to run a normal 10x run, but it seems to giving me this error:
```
Jun 23 15:34:33 ..... started STAR run
Jun 23 15:34:33 ..... loading genome
Jun 23 15:35:04 ..... started mapping
Jun 23 16:16:43 ..... finished mapping
Jun 23 16:16:49 ..... started Solo counting
malloc(): invalid size (unsorted)
Aborted (core dumped)
```
It seems to always happen at the same place, I've tried this with the BAM file (from the same run as the fastq) as input.
In the Solo.out folder I have the Barcode.stats file, but the GeneFull dir is empty.
[Log (2).txt](https://github.com/alexdobin/STAR/files/6705392/Log.2.txt)
[Log.progress.txt](https://github.com/alexdobin/STAR/files/6705393/Log.progress.txt)

**Comment by cnk113** [comment]
So I may have an idea on this error I've had recent similar runs where the output of the **raw** matrix (EM mtx if that matters) where the mtx format is impossible to load into R as a single matrix b/c the number of non-zero entries in this dataset exceeds the integer limit of R. I've had to just split the mtx into two and load it in. I'm assuming this error may occur in the matrix generation process as well?

**Comment by alexdobin** [comment]
Hi Chang,

1st post: you are using ```--soloUMIlen 12``` which implies 10X v2 protocol, but you are supplying the v2 barcode whitelits (737k).
This could be a problem as it does not seem to detect any valid barcodes.

2nd post: what is the number of non-zero elements in the EM matrix - it should be reported in the 3rd column of the 3rd line, and it should agree with the number of lines in the .mtx files - 3.

Cheers
Alex

**Comment by cnk113** [comment]
This is the 10x multiome, specifically the RNA portion so it follows the v3 lib structure but different WL.

Sorry I was mistaken on the non-zero, it had to with non-integer values, the raw matrix loads but the em matrix doesn't due to a float error `Error in readMM(file = matrix.loc) : element type 'float' not recognized` this is also from another 10x multiome library that I sequenced with the one that is currently failing to run. I had a similar issue in a different dataset where the non-zero entries exceeded 2e9. Although the em matrix here loads into scanpy but not R, so it's still likely an R issue.

**Comment by alexdobin** [comment]
But the malloc problem remains, right?
Could you post Solo.out/Barcodes.tsv file for the failed run.

**Comment by cnk113** [comment]
```
                                        nNoAdapter              0
                                            nNoUMI              0
                                             nNoCB              0
                                            nNinCB              0
                                           nNinUMI           6462
                                   nUMIhomopolymer         249041
                                          nTooMany              0
                                          nNoMatch       32594557
                               nMismatchesInMultCB              0
                                       nExactMatch      668965478
                                    nMismatchOneWL        7281159
                                 nMismatchToMultWL        6684713
```

**Comment by cnk113** [comment]
Also I noticed you recently added a script to regenerate the matrix from the bam, it might be nice if the mapping is finished for the bam file to be outputted before any counting is done.

**Comment by alexdobin** [comment]
Hi Chang,

the barcode and UMI error correction (which are recorded into BAM) are done at the counting step, so the BAM cannot be written before counting is finished, unfortunately.
The Barcodes.stats looks fine, most reads get matched to the whitelist.

For the next step, could you try to run it for a smal subset of reads with ```--readMapNumber 100000``` to see if the error is still occuring.

Cheers
Alex

**Comment by cnk113** [comment]
Hey Alex,

Setting `--readMapNumber 100000` works!

Best,
Chang

**Comment by alexdobin** [comment]
Hi Chang,

could you share the FASTQs with me?
I need to reproduce the error.
Another path is to increase the number of reads, to see when it breaks.

Cheers
Alex

**Comment by cnk113** [comment]
Sadly I think that may be hard to do, these are patient samples which would be bureaucratically hard (time-consuming) to do. I'll try to test in parallel with increasing number of reads and get back to you. Also it's a lot of reads.

**Comment by cnk113** [comment]
So when running --readMapNumber 500000000
I got this 
```
Jul 09 14:17:09 ..... started STAR run
Jul 09 14:17:17 ..... loading genome
Jul 09 14:17:41 ..... started mapping
Jul 09 14:57:42 ..... finished mapping
Jul 09 14:57:46 ..... started Solo counting
Jul 09 15:31:56 ..... finished Solo counting
Jul 09 15:31:56 ..... started sorting BAM

EXITING because of fatal ERROR: not enough memory for BAM sorting:
SOLUTION: re-run STAR with at least --limitBAMsortRAM 65335086933
Jul 09 15:31:56 ...... FATAL ERROR, exiting
```
And with --readMapNumber 800000000
```
Jul 09 14:18:16 ..... started STAR run
Jul 09 14:18:16 ..... loading genome
Jul 09 14:18:30 ..... started mapping
Jul 09 15:17:45 ..... finished mapping
Jul 09 15:17:49 ..... started Solo counting
malloc(): invalid size (unsorted)
Aborted (core dumped)
```

**Comment by alexdobin** [comment]
Hi Chang,

this is going to be hard to debug...
Can you try a few more runs (without ```--outSAMtype BAM   SortedByCoordinate``` to speed it up):
1. ```--soloFeatures Gene``` not GeneFull
2. Remove multimappers option:  ``` --soloMultiMappers Uniform   EM```

This will help to narrow it down.
Also, have you tried to run the same command on a public dataset for the same technology and (at least) the same number of reads?

Cheers
Alex

**Comment by cnk113** [comment]
Hey Alex,

When I did Gene and turned of both MM params and no BAM, I get it to finish.

Best,
Chang

**Comment by alexdobin** [comment]
Hi Chang,

thanks! Can you also do the other combinations:
```--soloFeatures Gene --soloMultiMappers Uniform EM```
and
```--soloFeatures Gene``` without multimappers?

Thanks!
Alex

**Comment by cnk113** [comment]
Both parameters work.

**Comment by alexdobin** [comment]
Thanks for the tests!
I will try to run this configuration on a large (>700M reads) public dataset, hoping that it will throw the error.
If not, the only option would be for you to run it on your dataset in a debug mode.

**Comment by alexdobin** [comment]
Hi Chang,

sorry for the long delay, I finally got time to look into it. I have run a few large datasets, >1B reads, and could not reproduce the error, unfortunately. If you are willing to debug it on you machine, I can guide you through the process.

Cheers
Alex

**Comment by cnk113** [comment]
Yeah with the new version of STAR, I don't seem to get this error.
