### ISSUE TITLE
Many genes with zero counts in transcript mode (GeneFull) but not in exon mode (Gene)

### ISSUE THREAD

**Issue by jbengler** [alexdobin/STAR#1279]
Hi Alex,

I am currently using STARsolo on a Smartseq2 dataset of isolated nuclei and would like to include intronic reads in counting. When comparing `Gene` and `GeneFull` counts from the same run I realised that several thousand genes that get proper counts in `Gene` mode get zero counts in `GeneFull` mode.

One example is ENSG00000132639 aka SNAP25.
I am using the most recent ENSEMBL GTF: `Homo_sapiens.GRCh38.104.gtf`

It seems like the mapping works fine, but the counting algorithm discards all reads within SNAP25. Maybe because it thinks they are ambiguous?

Do you by any chance have an idea how to solve this problem?
[Log.out](https://github.com/alexdobin/STAR/files/6714614/Log.out.txt)

Best
Broder

**Comment by alexdobin** [comment]
Hi Broder,

if alignments overlap exons of SNAP25 and introns of another gene, they will be considered ambiguous for GeneFull but not for Gene counting. The best way to check it is to make browser tracks (UCSC browser or IGV) for BAM file and the GTF.

Cheers
Alex

**Comment by jbengler** [comment]
Hi Alex,

thanks a lot for your quick answer!

Of course you are right. In case of SNAP25 there is another gene called SNAP25-AS1 that has a huge transcript that "steals" all the reads from SNAP25.

In my naive view the `GeneFull` counts sounded like something you definitely want to do with single nuclei data. Now I start realizing the trade off. Some of the ~8,500 genes that are lost in `GeneFull` mode might actually be meaningful.

Best
Broder

**Comment by alexdobin** [comment]
Hi Broder,

you are exactly right, this is a significant issue with counting for pre-mRNA.
I am working on some solutions that prioritize:
1. Count reads that overlap exons (i.e. "Genes" counting) first, and in the 2nd stage, count reads that overlap introns.
2. CellRanger has recently implemented ```--include-introns``` option that works along the same lines, but is a bit more complex, I am still trying to figure out what it does exactly.

Cheers
Alex

**Comment by jbengler** [comment]
Hi Alex,

it would be really great to have such a feature in STARsolo. I would definitely give it a try!

Best
Broder

**Comment by jbengler** [comment]
Hi Alex,

just saw the new `--soloMultiMappers` feature. Thanks a lot!

Do you have a recommendation which flavour of `--soloMultiMappers` to choose.
And do all of them work with `--soloType SmartSeq` and `--include-introns GeneFull`?

Best
Broder

**Comment by alexdobin** [comment]
Hi Broder,

the most commonly used strategy for multimappers is Expectation Maximization ("EM").
Another useful option is "Uniform" - it simply distributes multi-gene UMIs to all genes.

Multimapping options will work with GeneFull but not with SmartSeq (yet).

Cheers
Alex

**Comment by jbengler** [comment]
Hi Alex,

thanks for your recommendation!

I am looking forward to the multimapping options for SmartSeq data.

Best
Broder

**Comment by jbengler** [comment]
Hi Alex,

sorry to bother you again. Coming back to your post from 5 Oct 2021:
> Multimapping options will work with GeneFull but not with SmartSeq (yet).

I still have this SmartSeq data set I would like to align with `--soloType SmartSeq` and `--include-introns GeneFull`.

Is there still a chance that you implement this feature?
Is there a point in waiting for it?

Thanks a lot!
Broder

**Comment by alexdobin** [comment]
Hi Broder,

sorry, no ETA for multimapping counting for SmartSeq. It uses a different counting scheme (no UMI) and it would require an EM implementation from scratch.
If you need to include multimapping reads, you can use STAR-RSEM pipeline for each cell separately, though, of course, this is a different quantification scheme, as  RSEM quantifies transcripts probabilistically.

Cheers
Alex

**Comment by jbengler** [comment]
Hi Alex,

thanks for your answer! I see that SmartSeq data is not so much around anymore and the effort that is needed to tackle this  niche case might not make it a high priority. I will look into the RSEM alternative you mention.

Best
Broder
