### ISSUE TITLE
Single mismatch in accurate reads obscures a correct spliced alignment

### ISSUE THREAD

**Issue by clb1000** [alexdobin/STAR#128]
Hello Alex,
      I have encountered a situation that appears to me to be an incorrect STAR alignment that I would expect to be a somewhat common case in typical sequencing data sets. In short, in my hands STAR is not able to do a spliced alignment (with an 11bp overhang) due to the presence of a single basepair mismatch in the vicinity of the splice junction in a read.

Here is the read pair. In Read2 I have starred the mismatches relative to hg38. (For hg38, both of the starred C nucleotides are G.)
```
>Read1
CAAGATGTGTGACTTCACCGAAGACCAGACCGCAGAGTTCAAGGAGGCCTTCCAGCTGTTTGACCGAACAGGTGATGGCAAGATCCTGTACA
>Read2
GCCCTCATCACATCCCCACACTGGCTGTACAGGATCTTGCCATCACCTGTTCGGTCAAACAGCTGGAAGGCC*C*CCTTGAACTCTGCG*C*TCTGG
```

Regardless of the input parameter value combinations for STAR (and I have tried a great many), here is the SAM output:
```
Read1      99      chr12   56158398        255     7M279N28M875N57M        =       56159584        1271    CAAGATGTGTGACTTCACCGAAGACCAGACCGCAGAGTTCAAGGAGGCCTTCCAGCTGTTTGACCGAACAGGTGATGGCAAGATCCTGTACA    *    NH:i:1  HI:i:1  AS:i:195        nM:i:1  NM:i:0  MD:Z:92 jM:B:c,21,21    jI:B:i,56158405,56158683,56158712,56159586
Read2     147     chr12   56159584        255     8S85M   =       56158398        -1271   CCAGAGCGCAGAGTTCAAGGGGGCCTTCCAGCTGTTTGACCGAACAGGTGATGGCAAGATCCTGTACAGCCAGTGTGGGGATGTGATGAGGGC   *   NH:i:1  HI:i:1  AS:i:195        nM:i:1  NM:i:1  MD:Z:12A72      jM:B:c,-1       jI:B:i,-1
```
The problem is the soft clipping of Read2. Instead of soft-clipping, the read should be bridging the splice junction chr12:56158712-56159586 (just like Read1 does in its CIGAR part "28M875N57M"). In bridging this splice junction, STAR would pick up 10 matches and 1 mismatch, resulting in a better score. 

If I change either one (and just one) of the starred C nucleotides to G, then the STAR output is correct in that the splice junction is bridged:
```
Read1      99      chr12   56158398        255     7M279N28M875N57M        =       56158701        1271    CAAGATGTGTGACTTCACCGAAGACCAGACCGCAGAGTTCAAGGAGGCCTTCCAGCTGTTTGACCGAACAGGTGATGGCAAGATCCTGTACA    *   NH:i:1  HI:i:1  AS:i:213        nM:i:1  NM:i:0  MD:Z:92 jM:B:c,21,21    jI:B:i,56158405,56158683,56158712,56159586
Read2      147     chr12   56158701        255     11M875N82M      =       56158398        -1271   CCAGACCGCAGAGTTCAAGGGGGCCTTCCAGCTGTTTGACCGAACAGGTGATGGCAAGATCCTGTACAGCCAGTGTGGGGATGTGATGAGGGC   *   NH:i:1  HI:i:1  AS:i:213        nM:i:1  NM:i:1  MD:Z:20A72      jM:B:c,21       jI:B:i,56158712,56159586
```
My questions:
    1) Shouldn't the spliced alignment be favored by STAR?
    2) Is there a parameter setting that would enable STAR to find the spliced alignment? (I cannot find one).

I am using STAR_2.5.1b. I would include some example parameter settings that recapitulate the above problem, but in my hands all parameter settings recapitulate the above problem. So, any will do.

Regards,
Christian

**Comment by alexdobin** [comment]
Hi @clb1000 

this is a current limitation in STAR algorithm - it will not detect a splice with a short overhang and mismatches on both sides, even if the junction is annotated.
Note that it still finds the correct alignment for the rest of the read, so this alignment is only "partially incorrect". 
In the simulation, this happens to be the main source of soft-clipping, so I am working on algorithm enhamcements to be released over summer.

Cheers
Alex
