### ISSUE TITLE
Possible manual error regarding  --genomeSAindexNbases for small genomes

### ISSUE THREAD

**Issue by AlexBlais74** [alexdobin/STAR#1281]
Hello
I am preparing an index for a small prokaryotic genome. In the manual section 2.2.5, we are instructed to scale down the value of genomeSAindexNbases. I think there may be an error in the instructions. If the examples provided are correct, it is not log2 but log10 that should be used. Also, to remove ambiguity, additional parentheses should be used to make it clear that it is the genome length that should be halved, not its logarithm.

Thanks
Alex

**Comment by alexdobin** [comment]
Hi Alex,

it's log2, e.g. {log2(1e6)}/2-1 ~ 8.97 ~ 9.
I will add the extra parenthesis to the manual.

Cheers
Alex

**Comment by AlexBlais74** [comment]
Thanks for the the quick reply and for correcting my high-school math skills, Alex!
