### ISSUE TITLE
Reads with highly repetitive sequences not mapped by STAR but mapped by Salmon

### ISSUE THREAD

**Issue by red-plant** [alexdobin/STAR#1283]
Dear Dr. Dobin,

I am working with a sample of RNAseq from Arabidopsis' sperm-cells (SRR7945266 to SRR7945268). This same data was extremely slow to map with Salmon, but Dr. Patro kindly fixed it (https://github.com/COMBINE-lab/salmon/issues/527) and maps around 85%. Now, I need to map to the genome, I trying tweaking the seeding parameters to no avail, I get over 85% on "too short" I'm assuming the aligner is having a similar problem.

Do you think this could be solved in STAR? I'm attaching a few thousand reads of the first library in case they're of any use. 
[sub1.fq.gz](https://github.com/alexdobin/STAR/files/6735879/sub1.fq.gz)
[sub2.fq.gz](https://github.com/alexdobin/STAR/files/6735880/sub2.fq.gz)

Thanks
-José

**Comment by red-plant** [comment]
Hmm, turns out trimming with fastp -3 -4 -x solved the issue. Sorry again. Never faced such a problem with STAR, to which I usually feed untrimmed reads and works slightly better.

**Comment by alexdobin** [comment]
Hi José,

if the fragment insert size is < PE read length, the trimming is important, as the mappable portions of the reads are small and thus they cannot pass the filtering.

Cheers
Alex
