### ISSUE TITLE
Troubleshooting False Positives in Low-to-Medium Coverage Splice Junctions (in region with large duplications)

### ISSUE THREAD

**Issue by cwarden45** [alexdobin/STAR#1296]
Hi,

This is a separate question, but it relates to the project from [here]( https://github.com/alexdobin/STAR/issues/1261).

Basically, I am using the unique and multimap splice junctions to evaluate gene annotations for some assembled contigs.

In general, there are large duplications (with gene copies that are 100% identical), but there are still some genes that have unique reads.

For a number of genes, the multimap and unique read counts look like they should.  For example, if there are multiple gene copies, then there should really not be any unique junctions for those genes (at least not for internal junctions, I would say).

However, in the interests of trying to polish the alignments, I have noticed the following where I would appreciate any help:

**1)**	Sometimes, there are small fractions of unique reads mixed among the larger counts of multi-mapped reads in the genes with multiple identical copies.

**2)**	Contig 3 is supposed to stand out as having some extra unique reads.  By many measures, it does match what we expect.  However, there is at least one example from Contig 3 where the separation of unique and multi-mapped reads looks less clear (which I have included below).

**3)**	Also, I think I need to improve my code, but it looks like I am seeing extra junctions not part of the gene model in Contigs 2-4.  I haven’t completely ruled out the possibility of a bug on my part.  However, I thought I should mention something for overall troubleshooting purposes.

**4)**	In most cases, the STAR and TopHat2 alignments match.  However, there is 1 gene without any coding exons where there appear to be extra splice junctions (with low coverage) from STAR that are not present in the TopHat2 alignment.  So, those lower coverage junctions in the STAR alignment look like they could be false positives.

These are the commands that I am using to run STAR:
`STAR  --genomeDir $REF --readFilesIn $RI $R2 --runThreadN $THREADS --outFileNamePrefix $OUT --alignIntronMax 2000 --outFilterMismatchNoverLmax 0.1 --outFilterIntronMotifs RemoveNoncanonical --outSAMstrandField intronMotif`

I think this is the junction (on Contig 3) where the ratio of unique to multmapped reads is closest to 1:

<table>
  <tbody>
    <tr>
      <th align="center">Sample</th>
      <th align="center">Reads</th>
    </tr>
    <tr>
	    <td align="left">Sample1</td>
            <td align="center">(76 u : 111 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample2</td>
            <td align="center">(11 u : 9 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample3</td>
            <td align="center">(26 u : 23 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample4</td>
            <td align="center">(44 u : 53 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample5</td>
            <td align="center">(25 u : 17 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample6</td>
            <td align="center">(9 u : 5 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample7</td>
            <td align="center">(7 u : 4 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample8</td>
            <td align="center">(2 u : 0 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample9</td>
            <td align="center">(3 u : 1 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample10</td>
            <td align="center">(12 u : 9 m)</td>
    </tr> 
   <tr>
	    <td align="left">Sample11</td>
            <td align="center">(21 u : 18 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample12</td>
            <td align="center">(25 u : 24 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample13</td>
            <td align="center">(17 u : 21 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample14</td>
            <td align="center">(4 u : 3 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample15</td>
            <td align="center">(157 u : 195 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample16</td>
            <td align="center">(10 u : 2 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample17</td>
            <td align="center">(1 u : 1 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample18</td>
            <td align="center">(17 u : 12 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample19</td>
            <td align="center">(16 u : 18 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample20</td>
            <td align="center">(4 u : 8 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample21</td>
            <td align="center">(10 u : 8 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample22</td>
            <td align="center">(83 u : 129 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample23</td>
            <td align="center">(33 u : 27 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample24</td>
            <td align="center">(0 u : 2 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample25</td>
            <td align="center">(3 u : 5 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample26</td>
            <td align="center">(50 u : 45 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample27</td>
            <td align="center">(21 u : 14 m)</td>
    </tr>
</tbody>
</table>

**“u” = unique reads
“m”=multi-map reads**

If it helps for me to provide an example where you have mostly multimapped reads but <10% unique reads, then you can also see this example (from Contig 1):

<table>
  <tbody>
    <tr>
      <th align="center">Sample</th>
      <th align="center">Reads</th>
    </tr>
    <tr>
	    <td align="left">Sample1</td>
            <td align="center">(5 u : 1592 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample2</td>
            <td align="center">(12 u : 742 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample3</td>
            <td align="center">(10 u : 739 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample4</td>
            <td align="center">(0 u : 186 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample5</td>
            <td align="center">(1 u : 108 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample6</td>
            <td align="center">(1 u : 67 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample7</td>
            <td align="center">(0 u : 46 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample8</td>
            <td align="center">(1 u : 8 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample9</td>
            <td align="center">(3 u : 56 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample10</td>
            <td align="center">(8 u : 710 m)</td>
    </tr> 
   <tr>
	    <td align="left">Sample11</td>
            <td align="center">(10 u : 1425 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample12</td>
            <td align="center">(0 u : 343 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample13</td>
            <td align="center">(0 u : 104 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample14</td>
            <td align="center">(1 u : 178 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample15</td>
            <td align="center">(5 u : 1853 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample16</td>
            <td align="center">(4 u : 229 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample17</td>
            <td align="center">(2 u : 222 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample18</td>
            <td align="center">(46 u : 5046 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample19</td>
            <td align="center">(51 u : 5223 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample20</td>
            <td align="center">(0 u : 104 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample21</td>
            <td align="center">(0 u : 127 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample22</td>
            <td align="center">(49 u : 9313 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample23</td>
            <td align="center">(1 u : 379 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample24</td>
            <td align="center">(0 u : 19 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample25</td>
            <td align="center">(0 u : 75 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample26</td>
            <td align="center">(24 u : 2896 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample27</td>
            <td align="center">(12 u : 1572 m)</td>
    </tr>
</tbody>
</table>

There are **3 identical copies of the gene containing the above junction**, so I don’t think there should be any uniquely aligned reads spanning the junctions.  In this case, I think the multi-mapped reads are much larger and show what we want to show.  However, if the unique reads were smaller, then I think that would be better (and perhaps give us better confidence when we see intermediate level junction counts in other genes, such as the **first junction example**).

**In general, do you have any suggestions  of any alternative parameters that might clean up the alignments a little more?**

Thank you very much for your help!

Sincerely,
Charles

**Comment by alexdobin** [comment]
Hi Charles,

there are a number of different issues here, so let's try to sort them out one by one. I would start with:

> 3) Also, I think I need to improve my code, but it looks like I am seeing extra junctions not part of the gene model in Contigs 2-4. I haven’t completely ruled out the possibility of a bug on my part. However, I thought I should mention something for overall troubleshooting purposes.

STAR (by default) will produce junctions that are novel (unannotated), i.e. not present in the transcript/gene models you supplied in the GTF file. This is important to have in mind when you look at the other issues, as it may explain your other observation.

>1) Sometimes, there are small fractions of unique reads mixed among the larger counts of multi-mapped reads in the genes with multiple identical copies.

I guess I am not exactly sure what you mean by "gene" and "contig".
I imagine that "gene" is a sequence where the transcript models (sequential collection of exons) are defined. Genes will contain both intronic and exonic regions.
"Contigs" contain multiple "genes" with intergenic sequences between them.
If there are multiple genes that are exact copies, then the reads that map entirely inside such genes have to be multimappers.
However, if a read maps partially to the intergenic space or multiple genes, it may map uniquely.

>4) In most cases, the STAR and TopHat2 alignments match. However, there is 1 gene without any coding exons where there appear to be extra splice junctions (with low coverage) from STAR that are not present in the TopHat2 alignment. So, those lower 
coverage junctions in the STAR alignment look like they could be false positives.

You would need to look at the STAR and TopHat2 alignments to check whose alignment is "better", i.e. contains fewer mismatches.

Cheers
Alex

**Comment by cwarden45** [comment]
My understanding is that the introns (and I believe 2000 bp flanking) should be identical for the "gene copies".

So, I think this matches your understanding.

Thank you for recommending that I check for mutations if there appears to be a difference.  The splice junction track in IGV is fairly easy to view, although these need to be in the minority of reads.  So, that might take some extra effort (or at least scrolling), but it is something that I had not thought of and I can look into that if I think there is something important.

I also ran some testing if I add `--alignSJoverhangMin 20 --alignSJDBoverhangMin 20`:

<table>
  <tbody>
    <tr>
      <th align="center">Sample</th>
      <th align="center">Reads</th>
    </tr>
    <tr>
	    <td align="left">Sample1</td>
            <td align="center">(76 u : 111 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample2</td>
            <td align="center">(11 u : 9 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample3</td>
            <td align="center">(26 u : 23 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample4</td>
            <td align="center">(26 u : 23 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample5</td>
            <td align="center">(25 u : 17 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample6</td>
            <td align="center">(9 u : 5 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample7</td>
            <td align="center">(7 u : 4 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample8</td>
            <td align="center">(2 u : 0 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample9</td>
            <td align="center">(3 u : 1 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample10</td>
            <td align="center">(12 u : 9 m)</td>
    </tr> 
   <tr>
	    <td align="left">Sample11</td>
            <td align="center">(21 u : 18 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample12</td>
            <td align="center">(25 u : 24 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample13</td>
            <td align="center">(17 u : 21 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample14</td>
            <td align="center">(4 u : 3 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample15</td>
            <td align="center">(157 u : 195 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample16</td>
            <td align="center">(10 u : 2 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample17</td>
            <td align="center">(1 u : 1 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample18</td>
            <td align="center">(17 u : 12 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample19</td>
            <td align="center">(17 u : 12 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample20</td>
            <td align="center">(4 u : 8 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample21</td>
            <td align="center">(10 u : 8 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample22</td>
            <td align="center">(83 u : 129 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample23</td>
            <td align="center">(33 u : 27 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample24</td>
            <td align="center">(0 u : 2 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample25</td>
            <td align="center">(3 u : 5 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample26</td>
            <td align="center">(50 u : 45 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample27</td>
            <td align="center">(21 u : 14 m)</td>
    </tr>
</tbody>
</table>

<table>
  <tbody>
    <tr>
      <th align="center">Sample</th>
      <th align="center">Reads</th>
    </tr>
    <tr>
	    <td align="left">Sample1</td>
            <td align="center">(5 u : 1592 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample2</td>
            <td align="center">(12 u : 742 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample3</td>
            <td align="center">(10 u : 739 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample4</td>
            <td align="center">(0 u : 186 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample5</td>
            <td align="center">(1 u : 108 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample6</td>
            <td align="center">(1 u : 67 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample7</td>
            <td align="center">(0 u : 46 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample8</td>
            <td align="center">(1 u : 8 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample9</td>
            <td align="center">(3 u : 56 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample10</td>
            <td align="center">(8 u : 710 m)</td>
    </tr> 
   <tr>
	    <td align="left">Sample11</td>
            <td align="center">(10 u : 1425 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample12</td>
            <td align="center">(0 u : 343 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample13</td>
            <td align="center">(0 u : 104 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample14</td>
            <td align="center">(1 u : 178 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample15</td>
            <td align="center">(5 u : 1853 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample16</td>
            <td align="center">(4 u : 229 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample17</td>
            <td align="center">(2 u : 222 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample18</td>
            <td align="center">(46 u : 5046 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample19</td>
            <td align="center">(51 u : 5223 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample20</td>
            <td align="center">(0 u : 104 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample21</td>
            <td align="center">(0 u : 127 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample22</td>
            <td align="center">(49 u : 9313 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample23</td>
            <td align="center">(1 u : 379 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample24</td>
            <td align="center">(0 u : 19 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample25</td>
            <td align="center">(0 u : 75 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample26</td>
            <td align="center">(24 u : 2896 m)</td>
    </tr>
    <tr>
	    <td align="left">Sample27</td>
            <td align="center">(12 u : 1572 m)</td>
    </tr>
</tbody>
</table>

I will also post another comment with some other statistics related to the unique-to-multimap ratios.

However, my sense is that the other parameters might have helped a little, but I think it didn't make a big difference in the results.  So, I will close the ticket.

Nevertheless, if others have additional suggestions, then i would be interested in hearing them!

**Comment by cwarden45** [comment]
If it helps, there is also this plot, there I think there slight disadvantage to the newer strategy, assuming a more clear difference in unique to multi-mapped reads per junction is "good".  The grey line represents points values that would have been the same with both alignments.

![combined_splice_junctions-STAR-median_unique_to_multimap_ratio-v3-param9](https://user-images.githubusercontent.com/7663033/125701481-2a604ddb-576f-494c-a4c0-10de2b85a716.png)
