### ISSUE TITLE
Super slow loading for SMART-seq 2 using Star-solo(2.7.9.a)

### ISSUE THREAD

**Issue by yuzhong1997** [alexdobin/STAR#1297]
Hi,

I've have been trying to use star-solo to get count matrix for my smart-seq 2 datasets. It's super quick to start mapping if I got 5~100 fastq files in my manifest.tsv file, but It seems does not work if thousands of fastq files there. Does anybody see it before? My simple codes show following:

nohup STAR --runThreadN 60 \
--genomeDir /genome_ref/star_mouse \
--readFilesManifest /metadata/smart_seq.tsv \
--readFilesCommand zcat \
--soloType SmartSeq \
--soloUMIdedup Exact \
--soloStrand Unstranded \
--outFileNamePrefix /result/SRR_PRJNA322317/SRR_PRJNA322317_ \
--outSAMtype None \
> /log/SRR_PRJNA322317_star_solo.log &

**Comment by alexdobin** [comment]
Hi @yuzhong1997 

I have tested it with up to 1000 files and it worked fine.
Could you please send me the Log.out and Log.progress.out files for a big run.

Cheers
Alex

**Comment by yuzhong1997** [comment]
> Hi @yuzhong1997
> 
> I have tested it with up to 1000 files and it worked fine.
> Could you please send me the Log.out and Log.progress.out files for a big run.
> 
> Cheers
> Alex

Hi Alex,

My log.out file seems too long to read. I just paste the top 10 and the end of 10 lines as following:

############################################# Head
STAR version=2.7.9a
STAR compilation time,server,dir=2021-05-04T09:43:56-0400 vega:/home/dobin/data/STAR/STARcode/STAR.master/source
##### Command Line:
STAR --runThreadN 50 --genomeDir /genome_ref/star_mouse --readFilesManifest /metadata/smart_seq.tsv --readFilesCommand zcat --soloType SmartSeq --soloUMIdedup Exact --soloStrand Unstranded --outFileNamePrefix /result/test_SRR_PRJNA322317/SRR_PRJNA322317_ --outSAMtype None
##### Initial USER parameters from Command Line:
outFileNamePrefix                 /result/test_SRR_PRJNA322317/SRR_PRJNA322317_
###### All USER parameters from Command Line:
runThreadN                    50     ~RE-DEFINED
genomeDir                     /genome_ref/star_mouse     ~RE-DEFINED
readFilesManifest             /metadata/smart_seq.tsv        ~RE-DEFINED
readFilesCommand              zcat        ~RE-DEFINED
soloType                      SmartSeq     ~RE-DEFINED
soloUMIdedup                  Exact        ~RE-DEFINED
soloStrand                    Unstranded     ~RE-DEFINED
outFileNamePrefix             /result/test_SRR_PRJNA322317/SRR_PRJNA322317_     ~RE-DEFINED
outSAMtype                    None        ~RE-DEFINED
##### Finished reading parameters from all sources

##### Final user re-defined parameters-----------------:
runThreadN                        50
genomeDir                         /genome_ref/star_mouse
readFilesCommand                  zcat   
readFilesManifest                 /metadata/smart_seq.tsv   
outFileNamePrefix                 /result/test_SRR_PRJNA322317/SRR_PRJNA322317_
outSAMtype                        None   
soloType                          SmartSeq
soloStrand                        Unstranded
soloUMIdedup                      Exact   

-------------------------------
##### Final effective command line:
STAR   --runThreadN 50   --genomeDir /genome_ref/star_mouse   --readFilesCommand zcat      --readFilesManifest /metadata/smart_seq.tsv      --outFileNamePrefix /result/test_SRR_PRJNA322317/SRR_PRJNA322317_   --outSAMtype None      --soloType SmartSeq   --soloStrand Unstranded   --soloUMIdedup Exact   
----------------------------------------

Reading input file names and read groups from readFileManifest /metadata/smart_seq.tsv
/fastq/SRR_PRJNA322317/SRR3557168.sra.fastq.gz  -       ID:SRR3557168
/fastq/SRR_PRJNA322317/SRR3560011.sra.fastq.gz  -       ID:SRR3560011
/fastq/SRR_PRJNA322317/SRR3558288.sra.fastq.gz  -       ID:SRR3558288
/fastq/SRR_PRJNA322317/SRR3558852.sra.fastq.gz  -       ID:SRR3558852
/fastq/SRR_PRJNA322317/SRR3559135.sra.fastq.gz  -       ID:SRR3559135

############################################# Tail
zcat      "/fastq/SRR_PRJNA322317/SRR3559658.sra.fastq.gz"
echo FILE 3823
zcat      "/fastq/SRR_PRJNA322317/SRR3558220.sra.fastq.gz"
echo FILE 3824
zcat      "/fastq/SRR_PRJNA322317/SRR3557322.sra.fastq.gz"
echo FILE 3825
zcat      "/fastq/SRR_PRJNA322317/SRR3559103.sra.fastq.gz"
echo FILE 3826
zcat      "/fastq/SRR_PRJNA322317/SRR3556763.sra.fastq.gz"

And, there is nothing left in my Log.progress.out file. Just weird. Thanks for your help.

Yu

**Comment by yuzhong1997** [comment]
Hi Alex @alexdobin,

Here are my files. Thanks for your help!

Yu
[run.zip](https://github.com/alexdobin/STAR/files/6820531/run.zip)

**Comment by yuzhong1997** [comment]
> Hi @yuzhong1997
> 
> I have tested it with up to 1000 files and it worked fine.
> Could you please send me the Log.out and Log.progress.out files for a big run.
> 
> Cheers
> Alex

**Comment by alexdobin** [comment]
Hi Yu,

nothing suspicious in the Log.out...
All the 3827 file are mapped, so the issue must be in the post-mapping (solo counting) steps.
Please check that you are not running out of space on the disk, as the temp files are going to be large.
The next thing would be to try to run it for ~1000 files, to see if it still breaks.

Cheers
Alex

**Comment by yuzhong1997** [comment]
Hi Alex, @alexdobin 

Actually, it seems like never start mapping even align with the reference, except that writing some log file (e.g "zcat" command), because I was inspecting the progress via "htop", and there is no CPU or memory activity. I suppose my disk space is enough to hold these.
Another interesting thing is like when I try to run it for ~1k files, it works (start mapping) from time to time. Just weird. So I assume that it would pre-calculate the memory or space it would take, and it will not do anything if it exceeds some like threshold? Thanks.

Yu

**Comment by yuzhong1997** [comment]
Hi Alex, @alexdobin

Interesting! I just made a new docker for this pipeline and it works now! But I'm still confused about what happened before. Maybe it is like a system issue. Anyway, thank you for your great work~ :-)

Yu

**Comment by alexdobin** [comment]
Hi Yu,

thanks for letting me know that it worked. It's hard to debug some issues, especially system-related.

Cheers
Alex
