### ISSUE TITLE
Installation error in Ubuntu 14.1

### ISSUE THREAD

**Issue by liangcmu** [alexdobin/STAR#130]
When I get the most recent version of STAR through gethub, and 

$ make STAR

I got the following error:
...
Parameters_openReadsFiles.cpp: In member function ‘void Parameters::openReadsFiles()’:
Parameters_openReadsFiles.cpp:58:97: warning: ignoring return value of ‘int system(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
                 system(("ls -lL " + file1 + " > "+ outFileTmp+"/readFilesIn.info 2>&1").c_str());
                                                                                                 ^
Parameters_openReadsFiles.cpp:30:20: warning: variable ‘imate’ might be clobbered by ‘longjmp’ or ‘vfork’ [-Wclobbered]
          for (uint imate=0;imate<readNmates;imate++) {//open readIn files
                    ^
make[1]: Leaving directory `/usr/local/genome/STAR/STAR-STAR_2.5.0a/source'

I will appreciate if you can provide some solution.

**Comment by alexdobin** [comment]
Hi @liangcmu 

this is not an error, just a warning which I cannot switch off.
The STAR executable should  have been made, please try to run it.

Cheers
Alex

**Comment by smoe** [comment]
You get an overview on latest versions shipping with Ubuntu here:
https://launchpad.net/ubuntu/+source/rna-star
The Debian Med folks have their own Ubuntu PPA and can possibly help with various backports also for trusty. Ping me if you have any respective interest.
