### ISSUE TITLE
Can I run STAR on split FASTQs and combine/merge the outputs?

### ISSUE THREAD

**Issue by RamRS** [alexdobin/STAR#1302]
Hi,

One of my samples keeps failing on STAR runs, so I split each FASTQ into parts and I'm running them separately. I tried using 128GB RAM, but even so the runs kept failing, hence I decided to use partial FASTQs. 

Here are the (numerous) parameters I use:

```
STAR --genomeDir /genome/dir \
--outFilterType BySJout \
--outFilterMultimapNmax 20 \
--alignSJoverhangMin 8 \
--alignSJstitchMismatchNmax 5 -1 5 5 \
--alignSJDBoverhangMin 10 \
--outFilterMismatchNmax 999 \
--outFilterMismatchNoverReadLmax 0.04 \
--alignIntronMin 20 \
--alignIntronMax 100000 \
--alignMatesGapMax 100000 \
--genomeLoad NoSharedMemory \
--outSAMmapqUnique 60 \
--outSAMmultNmax 1 \
--outSAMstrandField intronMotif \
--outSAMtype BAM Unsorted \
--outReadsUnmapped None \
--outFileNamePrefix sample1_part1. \
--outSAMattrRGline ID:GRPundef \
--chimSegmentMin 12 \
--chimJunctionOverhangMin 12 \
--chimSegmentReadGapMax 3 \
--chimMultimapNmax 10 \
--chimMultimapScoreRange 10 \
--chimNonchimScoreDropMin 10 \
--chimOutJunctionFormat 1 \
--quantMode GeneCounts \
--twopassMode Basic \
--peOverlapNbasesMin 12 \
--peOverlapMMp 0.1 \
--readFilesIn  sample1_part1_R1.fastq sample1_part1_R2.fastq \
--runThreadN 1
```

Along with the `Aligned.out.bam`, `Chimeric.out.junction`, `ReadsperGene.out.tab` and `SJ.out.tab`, I'll be sorting each BAM then generating wiggle files using STAR as shown in this post: https://www.biostars.org/p/234437/#235241

How can I merge each of these output files across parts?

**Comment by alexdobin** [comment]
Hi Ram,
could you please send me the Log.out file for the failed run?
In principle, unsorted Aligned.out.bam files can be concatenated with ```samtools cat```.
```Chimeric.out.junction``` files can be simply concatenated together.
```ReadsperGene.out.tab``` have to summed element by element.
```SJ.out.tab``` are harder to merge since splice junctions are collapsed.

However, since you are using 2-pass mode, the mapping results depend on all the other reads in the sample, so a run with split FASTQs will not produce exactly the same results.

Cheers
Alex

**Comment by RamRS** [comment]
Thank you for the response, @alexdobin 

I ended up running the full FASTQs with the maximum RAM I could get my hands on, and it worked. Can I send the `Log.out` over email? I'd rather not share it with the public.
