### ISSUE TITLE
why barcode whitelist is necessary for the CB_UMI_Complex mode?

### ISSUE THREAD

**Issue by yuzhong1997** [alexdobin/STAR#1306]
Hi Alex, @alexdobin 

I'm just wondering how star-solo works using indrop_v1or v2 data (CB_UMI_Complex) without passing any whitelist.
Clearly, it will return errors if I do not provide any whitelist using the CB_UMI_Complex mode. But it works fine for drop-seq.

As you may know, it's usually not easy to find the whitelist specifically for these library types. So any ideas? Thanks.

Yu

**Comment by alexdobin** [comment]
Hi Yu,

the InDrop had multiple versions, and the earlier one had simple barcode geometry, so CB_UMI_Complex may not be needed.
If you know CB/UMI start/length, you can supply it to STARsolo, and use no-whitelists mode.

Cheers
Alex

**Comment by yuzhong1997** [comment]
Hi Alex, @alexdobin 

Yeah, it seems like in_drops-V3 works well using CB_UMI_Simple mode after data preprocessing. But actually In_drops_V1 and V2 both hold one barcode with variable length and the other fixed barcode, along with the fixed UMI. And it's necessary to provide whitelists corresponding to each cell barcode. My concern is how to run cb_umi_complex without passing whitelists. Thanks. 

Yu

**Comment by alexdobin** [comment]
Hi Yu,

CB_UMI_Complex cannot be run without the barcode list. I can share the barcodes from the inDrop paper (I think), not sure which version is that.

Cheers
Alex

**Comment by yuzhong1997** [comment]
Hi Alex, @alexdobin 

OK, I see. Thanks for your clarification. I've already have the barcodes for IndropsV1~V3, just wanna check out the concern that I have previously. Thanks anyway!

Yu
