### ISSUE TITLE
Reproducing Exact CellRanger Cell Counts

### ISSUE THREAD

**Issue by cwarden45** [alexdobin/STAR#1307]
Hi,

In general, I think being able to use STARsolo to produce a different estimate of cells is an advantage.

However, I also have an interest in being able to produce the exact same cell counts in a shorter period of time.

I think I might need to submit a separate ticket for the 1st sample, but you can get some sense of what I am talking about in the table below:

<table>
  <tbody>
    <tr>
      <th align="center">Method</th>
      <th align="center">SRR13313130</th>
      <th align="center">10x_pbmc_5k</th>
    </tr>
    <tr>
	    <td align="left">CellRanger</td>
            <td align="center">9,974 cells</td>
            <td align="center">4,956 cells</td>
    </tr>
    <tr>
	    <td align="left">STARsolo</td>
            <td align="center">7,587 cells</br><i>(Summary.csv)</i></td>
            <td align="center">4,586 cells</br><i>(Summary.csv)</i></td>
    </tr>
</tbody>
</table>

For example, the 10x_pbmc_5k the cell counts are fairly close but they are not exactly the same.

I am using the following commands for the 2 programs:

**CellRanger:**
```
ID=5k_pbmc_v3

module load cellranger/5.0.0
cellranger count --id=$ID --fastqs=../Reads --sample=$ID --chemistry=auto --localcores=6 --localmem=40 --transcriptome=/net/isi-dcnl/ifs/user_data/Seq/Chromium_data/databases/SARS_COV_2-hg38
```

**STARsolo:**
```
ID=5k_pbmc_v3

R1a=../Reads/5k_pbmc_v3_S1_L001_R1_001.fastq.gz
R1b=../Reads/5k_pbmc_v3_S1_L002_R1_001.fastq.gz
R1c=../Reads/5k_pbmc_v3_S1_L003_R1_001.fastq.gz
R1d=../Reads/5k_pbmc_v3_S1_L004_R1_001.fastq.gz

R2a=../Reads/5k_pbmc_v3_S1_L001_R2_001.fastq.gz
R2b=../Reads/5k_pbmc_v3_S1_L002_R2_001.fastq.gz
R2c=../Reads/5k_pbmc_v3_S1_L003_R2_001.fastq.gz
R2d=../Reads/5k_pbmc_v3_S1_L004_R2_001.fastq.gz

REF=/net/isi-dcnl/ifs/user_data/Seq/Ref/STAR/SARS_COV_2-hg38
CBWL=/net/isi-dcnl/ifs/user_data/Seq/Chromium_data/3M-february-2018.txt

module load STAR/2.7.9a

STAR --genomeDir $REF --readFilesIn $R2a,$R2b,$R2c,$R2d $R1a,$R1b,$R1c,$R1d --runThreadN 4 --outFileNamePrefix $ID --soloType CB_UMI_Simple --soloCBlen 16 --soloUMIlen 12 --soloCBwhitelist $CBWL --soloBarcodeReadLength 28 --readFilesCommand zcat --soloCBmatchWLtype 1MM_multi_Nbase_pseudocounts --soloUMIfiltering MultiGeneUMI_CR --soloUMIdedup 1MM_CR --clipAdapterType CellRanger4 --outFilterScoreMin 30 --outSJtype Standard --outSAMtype BAM SortedByCoordinate
```

I was trying to use something similar to the [STARsolo preprint](https://www.biorxiv.org/content/10.1101/2021.05.05.442755v1).

However, should I be changing the STARsolo commands/parameters?

Thank you very much!

Sincerely,
Charles

**Comment by alexdobin** [comment]
Hi Charles,

you would need to add ```--soloCellFilter EmptyDrops_CR``` to match CellRanger's filtering (calling).

Cheers
Alex

**Comment by cwarden45** [comment]
Hi Alex,

Thank you very much.

I apologize that I did not notice that was missing (when it was in fact within the supplemental table for the preprint, under "_Figures: real data comparisons; speed/RAM benchmarks_").

I have started re-processing that sample.  If everything is the same (for the 10x_pbmc_5k sample), then I will close this ticket.

Thanks Again,
Charles

**Comment by cwarden45** [comment]
I have confirmed that I get the same exact cell counts with the **10x_pbmc_5k** dataset, with the following command:

```
ID=5k_pbmc_v3

R1a=../Reads/5k_pbmc_v3_S1_L001_R1_001.fastq.gz
R1b=../Reads/5k_pbmc_v3_S1_L002_R1_001.fastq.gz
R1c=../Reads/5k_pbmc_v3_S1_L003_R1_001.fastq.gz
R1d=../Reads/5k_pbmc_v3_S1_L004_R1_001.fastq.gz

R2a=../Reads/5k_pbmc_v3_S1_L001_R2_001.fastq.gz
R2b=../Reads/5k_pbmc_v3_S1_L002_R2_001.fastq.gz
R2c=../Reads/5k_pbmc_v3_S1_L003_R2_001.fastq.gz
R2d=../Reads/5k_pbmc_v3_S1_L004_R2_001.fastq.gz

REF=/net/isi-dcnl/ifs/user_data/Seq/Ref/STAR/SARS_COV_2-hg38
CBWL=/net/isi-dcnl/ifs/user_data/Seq/Chromium_data/3M-february-2018.txt

module load STAR/2.7.9a

STAR --genomeDir $REF --readFilesIn $R2a,$R2b,$R2c,$R2d $R1a,$R1b,$R1c,$R1d --runThreadN 4 --outFileNamePrefix $ID --soloType CB_UMI_Simple --soloCBlen 16 --soloUMIlen 12 --soloCBwhitelist $CBWL --soloBarcodeReadLength 28 --readFilesCommand zcat --soloCBmatchWLtype 1MM_multi_Nbase_pseudocounts --soloUMIfiltering MultiGeneUMI_CR --soloUMIdedup 1MM_CR --soloCellFilter EmptyDrops_CR --clipAdapterType CellRanger4 --outFilterScoreMin 30 --outSJtype Standard --outSAMtype BAM SortedByCoordinate
```

I think there may be an additional issue with the other dataset, but I will first test this parameter set.  If needed, I will then submit a separate ticket for the v2 sample.
