### ISSUE TITLE
Using the output file parameter --outfileNamePrefix

### ISSUE THREAD

**Issue by huntjb** [alexdobin/STAR#131]
Hi Alex
we have a user on campus that is having some issues with the --outfileNamePrefix parameter.
I understand that the default is ./ for the local directory, so in order to specify a subdirectory can we simply use

./subdir/prefix

is this syntax permissable?

It could be a permissions issue that I am also investigating

Many thanks in advance
regards
Jon

**Comment by alexdobin** [comment]
Hi Jon,

the value of the --outfileNamePrefix is directly prepended to all file names, so ./subdir/prefix should write all files as ./subdir/prefixFileName. The ./subdir/ directory should exist and be writable. ./ represents the workind directory from which STAR is run.
To avoid confusion, I would generally recommend using absolute paths.

Cheers
Alex
