### ISSUE TITLE
non-zero status 1

### ISSUE THREAD

**Issue by yukoyoshida** [alexdobin/STAR#1311]
Hi, I have a problem with STAR starting step.
I receive this message every time.
↓
Jul 30 16:15:21 ..... started STAR run
Command exited with non-zero status 1
0.00user 0.00system 0:00.01elapsed 0%CPU (0avgtext+0avgdata 2896maxresident)k
0inputs+0outputs (0major+772minor)pagefaults 0swaps

Could you please let me know some advices,
Thank you.

Yuko

**Comment by paulmenzel** [comment]
Please tell is the exact version, you are using, and how you obtained it.

Please give the exact command line, you are executing. (Preferable a minimal example.)

Lastly, please mark up your reports appropriately [using GtiHub Markdown](https://guides.github.com/features/mastering-markdown/), so readers have it easy to detect code sequences. Remember, this is unpaid support, so make it as easy for supporters as possible.

**Comment by yukoyoshida** [comment]
Thank you,

I an using STAR version: 2.7.9a , I installed it by ubuntu as below,

wget https://github.com/alexdobin/STAR/archive/2.7.9a.tar.gz
tar -xzf 2.7.9a.tar.gz
sudo apt-get update
sudo apt-get install make

I did these command,
↓
/usr/bin/time STAR  --runThreadN 4 
--runMode genimeGenerate 
--genomeDir ws1$\Ubuntu\home\yyoshida\001_STAR_index 
--genomeFastaFiles ws1$\Ubuntu\home\yyoshida\GRCm39.primary_assembly.genome.fa 
--limitGenomeGenerateRAM 3000000000 
--sjdbGTFfile genecode.vM27.annotation.gtf 
--sjdbOverhang 100

↓
yyoshida@DESKTOP-UJP2C73:~/tools$ /usr/bin/time STAR  --runThreadN 4 --runMode genimeGenerate --genomeDir ws1$\Ubuntu\home\yyoshida\001_STAR_index --genomeFastaFiles ws1$\Ubuntu\home\yyoshida\GRCm39.primary_assembly.genome.fa --limitGenomeGenerateRAM 3000000000 --sjdbGTFfile genecode.vM27.annotation.gtf --sjdbOverhang 100
        STAR --runThreadN 4 --runMode genimeGenerate --genomeDir ws1$Ubuntuhomeyyoshida001_STAR_index --genomeFastaFiles ws1$UbuntuhomeyyoshidaGRCm39.primary_assembly.genome.fa --limitGenomeGenerateRAM 3000000000 --sjdbGTFfile genecode.vM27.annotation.gtf --sjdbOverhang 100
        STAR version: 2.7.9a   compiled: 2021-05-04T09:43:56-0400 vega:/home/dobin/data/STAR/STARcode/STAR.master/sourceJul 30 16:47:21 ..... started STAR run
Command exited with non-zero status 1
0.00user 0.00system 0:00.01elapsed 0%CPU (0avgtext+0avgdata 2896maxresident)k
0inputs+0outputs (0major+773minor)pagefaults 0swaps

Could you please let me know some advices,
Thank you.

Yuko

**Comment by alexdobin** [comment]
Hi Yuko,

there is a typo in ```--runMode genimeGenerate```,  it should be ```--runMode genomeGenerate```.
Also, are you trying to run it on Windows, judging by the directory paths?

Cheers
Alex

**Comment by yukoyoshida** [comment]
Hi Alex, Thank you so much.
Yes, I am trying to run it on Windows.
I changed command as you said,
and, I got another problem as below,
↓

yyoshida@DESKTOP-UJP2C73:~/tools$ /usr/bin/time STAR --runMode genomeGenerate --genomeDir ../yyoshida/001_STAR_index --genomeFastaFiles ref/GRCm39.primary_assembly.genome.fa --sjdbGTFfile ref/genecode.v
M27.annotation.gtf --sjdbOverhang 100
        STAR --runMode genomeGenerate --genomeDir ../yyoshida/001_STAR_index --genomeFastaFiles ref/GRCm39.primary_assembly.genome.fa --sjdbGTFfile ref/genecode.vM27.annotation.gtf --sjdbOverhang 100
        STAR version: 2.7.9a   compiled: 2021-05-04T09:43:56-0400 vega:/home/dobin/data/STAR/STARcode/STAR.master/source
Jul 31 11:19:16 ..... started STAR run
Jul 31 11:19:16 ... starting to generate Genome files
Jul 31 11:19:51 ..... processing annotations GTF

FATAL error, could not open file pGe.sjdbGTFfile=ref/genecode.vM27.annotation.gtf

Jul 31 11:19:51 ...... FATAL ERROR, exiting
Command exited with non-zero status 104
28.34user 6.48system 0:34.83elapsed 99%CPU (0avgtext+0avgdata 5351328maxresident)k
0inputs+0outputs (0major+1340497minor)pagefaults 0swaps
yyoshida@DESKTOP-UJP2C73:~/tools$

could not open  annotation.gtf  file. Could you please let me know about it, again.
Thank you,

Yuko

**Comment by yukoyoshida** [comment]
Hi Alex,
I found my mistake.
gencode.vM27 should be gencode.
It worked.
Thank you very much for your kindness,
Yuko

**Comment by alexdobin** [comment]
Great, thanks for letting me know!
