### ISSUE TITLE
Running STARsolo on Public 10x 5` GEX v2 Sample

### ISSUE THREAD

**Issue by cwarden45** [alexdobin/STAR#1314]
Hi,

I have [another ticket](https://github.com/alexdobin/STAR/issues/1307) where very helpful assistance was provided in order to get matching cell counts with CellRanger and STARsolo (for the example _10x_pbmc_5k_ dataset).

However, I have made a similar parameter modification, and I am still getting discordant results for the other sample.

So, I think there is some other issue in how I am trying to configure STARsolo to run for this sample (which is a different type of 10x sample).

Even with the extra parameter, the cell counts are the same as before:

<table>
  <tbody>
    <tr>
      <th align="center">Method</th>
      <th align="center">SRR13313130</th>
    </tr>
    <tr>
	    <td align="left">CellRanger</td>
            <td align="center">9,974 cells</td>
    </tr>
    <tr>
	    <td align="left">STARsolo</td>
            <td align="center">7,587 cells</br><i>(Summary.csv)</i></td>
    </tr>
</tbody>
</table>

I think one of the main reasons that I think there is an extra problem is that the per-cell gene counts are very well correlated with the _10x_pbmc_5k_ sample, but the correlation is much lower for the public lung sample from a COVID-19 patient:

![correlation-raw_count](https://user-images.githubusercontent.com/7663033/127784383-6764caed-2226-4d17-bda0-841605d0362b.png)

Also, with either strategy, there are 0 reads aligned to the coronavirus sequence from NC_045512.2 in the custom reference.  However, I will focus on the 1st 2 points (different cell counts and less well correlated gene counts per cell).

Here are the commands that I am using to run the programs:

**CellRanger:**
```
ID=5309-CT-2

module load cellranger/5.0.0
cellranger count --id=$ID --fastqs=../Reads --sample=$ID --chemistry=auto --localcores=6 --localmem=40 --transcriptome=/net/isi-dcnl/ifs/user_data/Seq/Chromium_data/databases/SARS_COV_2-hg38
```

**STARsolo:**
```

ID=5309-CT-2
R1=../Reads/5309-CT-2_S01_L005_R1_001.fastq.gz
R2=../Reads/5309-CT-2_S01_L005_R2_001.fastq.gz

REF=/net/isi-dcnl/ifs/user_data/Seq/Ref/STAR/SARS_COV_2-hg38
CBWL=/net/isi-dcnl/ifs/user_data/Seq/Chromium_data/737K-august-2016.txt

module load STAR/2.7.9a

STAR --genomeDir $REF --readFilesIn $R2 $R1 --runThreadN 4 --outFileNamePrefix $ID --soloType CB_UMI_Simple --soloCBlen 16 --soloUMIlen 10 --soloCBwhitelist $CBWL --soloBarcodeReadLength 150 --readFilesCommand zcat --soloCBmatchWLtype 1MM_multi_Nbase_pseudocounts --soloUMIfiltering MultiGeneUMI_CR --soloUMIdedup 1MM_CR --soloCellFilter EmptyDrops_CR --clipAdapterType CellRanger4 --outFilterScoreMin 30 --outSJtype Standard --outSAMtype BAM SortedByCoordinate
```

I am not sure if it helps, but there is also this [separate ticket](https://github.com/COMBINE-lab/salmon/issues/682) where poor white list concordance was observed with Alevin.  We basically compromised and I closed the ticket when I was able to run the program with a specified number of cells.  However, I did not compare those results to anything, in part because I don't think the white list concordance was ever great (with the provided file, which is what was recommended from 10x).

Do you have any suggestions about what I might need to change when running STARsolo?

Thank you very much.

Sincerely,
Charles

**Comment by alexdobin** [comment]
Hi Charles,

The first thing I would suggest is to use in STARsolo run the same STAR index that was used for CellRanger.
Inside /net/isi-dcnl/ifs/user_data/Seq/Chromium_data/databases/SARS_COV_2-hg38 there should be a subdirectory (star/?) which you can supply as ```--genomeDir``` in STARsolo run. Let's see if this improves the agreeement.

Cheers
Alex

**Comment by cwarden45** [comment]
Hi Alex,

Thank you again for your help.

I am not sure if there might have been some miscommunication, but I used the same reference for all samples.

So, for the _10x_pbmc_5k_ example dataset, I reproduced the main/general conclusions.  However, I did not use the exact same reference as in the preprint.

_Nevertheless, I will look into using the STAR reference from CellRanger._

In the Alevin link, switching between using `-lISF` and `-lISR` didn't seem to help.

However, what I did not already mention is that I originally used the v3 white list for both samples.  Eventually, I figured out that I needed to use a different White List for 2 samples.  One of the things that confirmed that was much better white list concordance (>90%) reported for both samples with the different white list for `bustools inspect`.

If that might help understand what is going on, here are the commands that I used:

```
module load kallisto/0.46.0
module load kallistobus/0.26.0

kallisto bus -i $REF -o $ID -x 10xV2 -t 4 $R1 $R2
bustools inspect -w $CBWL -p $ID/output.bus > $ID\_stats.txt
```

And this is the selected portion of the output:

```
Number of barcodes in agreement with whitelist: 376504207 (92.594139%)
Number of reads with barcode in agreement with whitelist: 377451225 (92.596920%)
```

Also, in the STARsolo **Summary.csv** file, I think the percentage was also supposed to be high (>94%):

```
Number of Reads,702927738
Reads With Valid Barcodes,0.948583
Sequencing Saturation,0.834938
Q30 Bases in CB+UMI,0.953373
Q30 Bases in RNA read,0.76514
Reads Mapped to Genome: Unique+Multiple,0.650166
Reads Mapped to Genome: Unique,0.601593
Reads Mapped to Gene: Unique+Multipe Gene,0.0111581
Reads Mapped to Gene: Unique Gene,0.00556654
Estimated Number of Cells,7587
Unique Reads in Cells Mapped to Gene,2445505
Fraction of Unique Reads in Cells,0.624989
Mean Reads per Cell,322
Median Reads per Cell,244
UMIs in Cells,419774
Mean UMI per Cell,55
Median UMI per Cell,43
Mean Gene per Cell,29
Median Gene per Cell,25
Total Gene Detected,11789
```

I will double-check (or maybe triple-check) that I can't find an alternative mapping between CellRanger and STARsolo barcodes in the existing quantification that are better correlated with each other.

It is certainly possible that there is something important that I am not understanding.  However, I think [visualization b) on slide 6](https://www.bioconductor.org/help/course-materials/2019/CSAMA/materials/lectures/Group3_10x_VDJ.pdf) of some training materials that I found matches the expectation that the barcode should be in R1 and the cDNA should primarily be on R2 (as well as matching page 18 in [this document](https://assets.ctfassets.net/an68im79xiti/1Ap6qQysq80oQAGacem7RD/6f895796e18c38a14ef1e8b8ff79a82c/CG000331_ChromiumNextGEMSingleCell5-v2_RevB.pdf)).

Additionally, I took an IGV screenshot of GAPDH for CellRanger and STARsolo:

![IGV_GAPDH-10v2](https://user-images.githubusercontent.com/7663033/128383475-57cdd95c-1c3f-4bc3-a998-c5c23c8d9f64.png)


Coverage increases at the 5` end of the gene, in both alignments.  I think R1 and R2 are both being aligned with CellRanger, which explains some "first of pair" reads in the top visualization.  However, for STARsolo, I think these do end to be mostly R2 reads (if you scroll down).

I will post an update about using the STAR reference from within CellRanger.  However, if this helps explain anything that might not have been clear before, please let me know.

Thanks Again,
Charles

**Comment by cwarden45** [comment]
I am not sure how crucial it is for troubleshooting, but I get the following error message if I try to use the CellRanger STAR reference:

```
	STAR --genomeDir /net/isi-dcnl/ifs/user_data/Seq/Chromium_data/databases/SARS_COV_2-hg38/star --readFilesIn ../../Reads/5309-CT-2_S01_L005_R2_001.fastq.gz ../../Reads/5309-CT-2_S01_L005_R1_001.fastq.gz --runThreadN 4 --outFileNamePrefix 5309-CT-2 --soloType CB_UMI_Simple --soloCBlen 16 --soloUMIlen 10 --soloCBwhitelist /net/isi-dcnl/ifs/user_data/Seq/Chromium_data/737K-august-2016.txt --soloBarcodeReadLength 150 --readFilesCommand zcat --soloCBmatchWLtype 1MM_multi_Nbase_pseudocounts --soloUMIfiltering MultiGeneUMI_CR --soloUMIdedup 1MM_CR --soloCellFilter EmptyDrops_CR --clipAdapterType CellRanger4 --outFilterScoreMin 30 --outSJtype Standard --outSAMtype BAM SortedByCoordinate
	STAR version: 2.7.9a   compiled: 2021-05-04T09:43:56-0400 vega:/home/dobin/data/STAR/STARcode/STAR.master/source
Aug 05 11:23:22 ..... started STAR run
Aug 05 11:23:23 ..... loading genome

EXITING because of FATAL ERROR: Genome version: 2.7.1a is INCOMPATIBLE with running STAR version: 2.7.9a
SOLUTION: please re-generate genome from scratch with running version of STAR, or with version: 2.7.4a

Aug 05 11:23:23 ...... FATAL ERROR, exiting
```

These are the commands that I used for that test:

```
ID=5309-CT-2
R1=../../Reads/5309-CT-2_S01_L005_R1_001.fastq.gz
R2=../../Reads/5309-CT-2_S01_L005_R2_001.fastq.gz

REF=/net/isi-dcnl/ifs/user_data/Seq/Chromium_data/databases/SARS_COV_2-hg38/star
CBWL=/net/isi-dcnl/ifs/user_data/Seq/Chromium_data/737K-august-2016.txt

module load STAR/2.7.9a

STAR --genomeDir $REF --readFilesIn $R2 $R1 --runThreadN 4 --outFileNamePrefix $ID --soloType CB_UMI_Simple --soloCBlen 16 --soloUMIlen 10 --soloCBwhitelist $CBWL --soloBarcodeReadLength 150 --readFilesCommand zcat --soloCBmatchWLtype 1MM_multi_Nbase_pseudocounts --soloUMIfiltering MultiGeneUMI_CR --soloUMIdedup 1MM_CR --soloCellFilter EmptyDrops_CR --clipAdapterType CellRanger4 --outFilterScoreMin 30 --outSJtype Standard --outSAMtype BAM SortedByCoordinate
```

**Comment by cwarden45** [comment]
Hi Alex,

Because I noticed that CellRanger was performing a paired-end alignment (and it looked like STARsolo was performing a single-end alignment with R2), I tested **trimming R1** to force both programs to only use R2.

Also, because I was asked to check other QC metrics during a journal club presentation last week, I have also added some statistics that I thought might be relevant:

<table>
  <tbody>
    <tr>
      <th align="center">Method</th>
      <th align="center">Cell Counts</th>
      <th align="center">Mean Genes per Cell</th>
      <th align="center">Median UMI per Cell</th>
      <th align="center">Mean Reads per Cell</th>
      <th align="center">Valid Barcodes</th>
      <th align="center">Sequencing Saturation</th>
     <th align="center">Reads Mapped to Genome</th>
     <th align="center">Reads Mapped to Genes/Transcriptome</th>
    </tr>
    <tr>
	    <td align="left">CellRanger</td>
            <td align="center">9,186 cells</td>
            <td align="center">401 genes</td>
            <td align="center">1,009 UMI/td>
            <td align="center">76,522 reads/td>
            <td align="center">94.8%/td>
            <td align="center">87.7%/td>
            <td align="center">64.4%/td>
            <td align="center">21.7%/td>
    </tr>
    <tr>
	    <td align="left">STARsolo</td>
            <td align="center">7,587 cells</br><i>(Summary.csv)</i></td>
            <td align="center">29 genes</td>
            <td align="center">43 UMI/td>
            <td align="center">322 reads/td>
            <td align="center">94.9%/td>
            <td align="center">83.5%/td>
            <td align="center">65.0%/td>
            <td align="center">1.1%/td>
    </tr>
</tbody>
</table>

The cell counts are relatively more similar, but they are still not the same.

For the STAR metrics, I used the _Unique+Multipe_ counts to be compare to CellRanger.

Importantly, the cell correlations also still noticeably differ for this sample:

![correlation-raw_count-trim_R1](https://user-images.githubusercontent.com/7663033/128766593-7e00b66e-0c53-48c4-ac0e-9c0b23201e62.png)

**Do you have any other recommendations for troubleshooting?**

Based upon the gene/UMI/read metrics (and gene/transcriptome alignment rate), it seems to me like the CellRanger alignment and quantification may be preferable.  However, I am not sure if there is something that I can change in STARsolo in order to get more similar results.

I wonder if there might somehow be a GTF issue, but the same reference (and GTF) was used for the other (3` GEX v3) sample where the CellRanger and STARsolo correlations look great.  So, I am not sure if there is something else that I might be missing.

Thank You,
Charles

**Comment by alexdobin** [comment]
Hi Charles,

sorry for the delay.
I think the issue is that this is the 5' protocol as opposed to the standard 3' protocol.
Sorry I did not catch it before. I think the crucial difference is the orientation (strand) of the reads.
For 5' you need to use ```--soloStrand Reverse```.
Please try it first with the trimmed reads. 
If it shows good agreement, there is also a way to map both ends of cDNA fragment.

Cheers
Alex

**Comment by cwarden45** [comment]
Hi Alex,

Thank you very much.  Those results look much better:

<table>
  <tbody>
    <tr>
      <th align="center">Method</th>
      <th align="center">Cell Counts</th>
    </tr>
    <tr>
	    <td align="left">CellRanger</td>
            <td align="center">9,186 cells</td>
    </tr>
    <tr>
	    <td align="left">STARsolo</td>
            <td align="center">9,154 cells</br><i>(Summary.csv)</i></td>
    </tr>
</tbody>
</table>

![correlation-raw_count-trim_R1-v2](https://user-images.githubusercontent.com/7663033/129609483-6a7f5677-15e3-4ba1-9d47-0baeeecc3edd.png)


You can see that the CellRanger results are not perfectly reproduced.  However, in terms of the addressing the most serious concerns, I will close the ticket.

However, if you can help with the following, then that would be very much be appreciated:

**1)** Is there an additional parameter change to get the **exact same cell counts** with the trimmed R1 (for CellRanger versus STARsolo)?

**2)** If I provide the untrimmed R1, am I correctly understanding that there are additional changes that I can make in order for STARsolo to perform a **paired-end** alignment and quantification (that matches CellRanger, at least for these initial tests)?

Thank you very much!

Sincerely,
Charles
