### ISSUE TITLE
Downsampling

### ISSUE THREAD

**Issue by Gotumbtai** [alexdobin/STAR#1319]
Hi Alex,

I am trying to do downsampling from the samples because there is a large dispersion in the read numbers. I am wondering if the downsampling from original FASTQ files could affect STAR behaviors, so if I should do it from BAM files after mapping. I would be grateful if you give your thoughts. 

Best regards,

**Comment by alexdobin** [comment]
Hi @Gotumbtai 

I think it's easier to downsample from the FASTQ files.
In principle, you can downsample from *unsorted* BAM, if you output unmapped reads (```--outSAMunmapped Within```), and do *not* use ```--outFilterType BySJout   --twopassMode Basic```.

Cheers
Alex

**Comment by Gotumbtai** [comment]
Hi Alex,

Thank you for your kind suggestion!
