### ISSUE TITLE
cstring issue with compiling STAR on mac

### ISSUE THREAD

**Issue by cwarden45** [alexdobin/STAR#132]
Hi,

I am using a homebrew to install gcc to avoid issues with clang.

I have tried compiling STAR with the following command in the source folder:

     make STARforMacStatic CXX=/usr/local/Cellar/gcc/5.3.0/bin/gcc-5

However, I get the following error message:

/usr/local/Cellar/gcc/5.3.0/bin/gcc-5 -c  -O3 -pipe -Wall -Wextra  bam_cat.c
bam_cat.c:57:19: fatal error: cstring: No such file or directory
compilation terminated.
make: *** [bam_cat.o] Error 1

Can you please help me troubleshoot?

Thanks,
Charles

**Comment by alexdobin** [comment]
Hi @cwarden45 

there appears to be a problem with the brew gcc installation. The error means that it cannot find cstring - one of the basic C libraries. I have found this thread that might still be relevant:
https://github.com/Homebrew/legacy-homebrew/issues/44600
It seems like their solution was to reinstall gcc compiling from source with
$ brew reinstall --build-from-source gcc

You can also try to manually compile this file with clang
$ gcc -c -O3 bam_cat.c
and then continue with make. The samtools C code is compiled with clang without problems.

Yet another option is to use precompiled executables.

Cheers
Alex

**Comment by cwarden45** [comment]
Hi Alex,

Thanks for the suggestion.  On my computer, the brew reinstall from source
fails.  However, the pre-compiled binary seems to be working fine.

I apologize for over-looking that file.

Best,
Charles

**Comment by snovod** [comment]
Hi Alex,
I am running into the same problem, but the brew reinstall and manually compiling with with clang is running into errors.

$ gcc -c -O3 bam_cat.c 
bam_cat.c:57:10: fatal error: 'cstring' file not found
#include <cstring>
         ^
1 error generated.

Do you have any suggestions about how to get around this or what the problem might be?
Thanks,
Sam

**Comment by alexdobin** [comment]
Hi Sam,

please open a new issue rather than using the Closed one which are hard to see.
This problem points to some kind of library problem with clang. 
I would recommend that you install the true gcc and its libraries with brew.

Cheers
Alex
