### ISSUE TITLE
"genomeType" error message 

### ISSUE THREAD

**Issue by Justin1609** [alexdobin/STAR#1323]
Hi @alexdobin 

I am getting the following error when trying to run STAR script on the index I got as an output from crossmapper

[jasmus@n05 /scratch]$ module load app/STAR/2.7.4a
[jasmus@n05 /scratch]$ bash alignment_for_crossmapper.pbs
Aug 10 12:41:00 ..... started STAR run
Aug 10 12:41:00 ..... loading genome

EXITING: FATAL INPUT ERROR: unrecognized parameter name "genomeType" in input "genomeParameters.txt"
SOLUTION: use correct parameter name (check the manual)

Aug 10 12:41:00 ...... FATAL ERROR, exiting

The script I am running looks as follows:

`#!/bin/bash
#PBS -N justin_star_map
#PBS -l walltime=24:00:00
#PBS -l ncpus=32
#PBS -l mem=100GB
#PBS -q bix
#PBS -e prog.err
#PBS -o prog.out
#PBS -M jasmus@sun.ac.za
#PBS -m a

cd $PBS_O_WORKDIR

module load app/STAR/2.7.4a
STAR --runThreadN 10 --genomeDir /home/jasmus/Cleo_Raw_data/crossmap_out/STAR_index --sjdbGTFfile /home/jasmus/Cleo_Raw_data/crossmap_out/concat.gtf --sjdbOverhang 74 --readFilesIn /home/jasmus/Cleo_Raw_data/crossmap_out/wgsim_output/concat_75_read1.fastq  --outSAMtype BAM Unsorted --outFileNamePrefix /home/jasmus/Cleo_Raw_data/crossmap_out/STAR_output/concat_75_SE_ --outFilterMismatchNmax 5 --outFilterMultimapNmax 10000 --outFilterMismatchNoverReadLmax 0.04 --alignIntronMax 0`

I have attached the genomeParameters.txt file as well as the Log.out file

I am running this on a remotely hosted server, but I have solved the issue of the fifo file not being able to be created which I was previously experiencing. Any suggestions for this new error would be greatly appreciated.
[genomeParameters.txt](https://github.com/alexdobin/STAR/files/6960993/genomeParameters.txt)
[Log.out.txt](https://github.com/alexdobin/STAR/files/6960998/Log.out.txt)

_Originally posted by @Justin1609 in https://github.com/alexdobin/STAR/issues/1221#issuecomment-895932764_

**Comment by alexdobin** [comment]
Hi Justin,

the genome generation was successful.
I see that you are loading the STAR 2.7.4a module, but the genome was generated with 2.7.9a.
Please try to run the same version of STAR for mapping.

Cheers
Alex

**Comment by Justin1609** [comment]
Hi @alexdobin 

I managed to get STAR to complete the mapping successfully by making sure the versions were the same. Thanks for the help, I appreciate it.

Kind regards

Justin

**Comment by alexdobin** [comment]
Hi Justin,

excellent, thanks for letting me know.
In general, the genome backward compatibility is one-way:
You can map with newer versions of STAR on genomes generated with older versions, e.g., 2.7.9 can map with genomes generated by any version starting from 2.7.4a.
However, the genomes generated with newer version may not work for mapping with older versions, e.g., genomes generated with 2.7.8a will not work with 2.7.7 or earlier versions.

Cheers
Alex
