### ISSUE TITLE
Did i do the right process for building the 2-pass index? 

### ISSUE THREAD

**Issue by bryanwong0610** [alexdobin/STAR#1330]
Hi @alexdobin ,

I wanted to call SNP by using STAR 2-pass Mode for starting.So for protocol I knew there were 2 index I should build .
The 1st index build code was "STAR --runThreadN 6 --runMode genomeGenerate --genomeDir /home/bryan0610/reference --genomeFastaFiles /home/bryan0610/reference/Homo_sapiens.GRCh38.dna.primary_assembly.fa --sjdbGTFfile /home/bryan0610/reference/Homo_sapiens.GRCh38.99.gtf --sjdbOverhang 99"  And it was working .

But when I was building the 2-pass index , I've deleted the parameter "--sjdbGTFfile", it couldn't work.
Here is my code:
 STAR --runMode genomeGenerate --genomeDir /mnt/e/secondpass/236127_2nd_pass/index_for_snp/ --genomeFastaFiles /home/bryan0610/reference/Homo_sapiens.GRCh38.dna.primary_assembly.fa -–sjdbFileChrStartEnd /home/bryan0610/star_result/236127_o_1.SJ.out.tab --runThreadN 6
EXITING because of INPUT ERROR: could not open genomeFastaFile: -–sjdbFileChrStartEnd

So did I do the wrong processing? Or should I adding the parameter "-- sjdbGTFfile" 

And the 2nd issue I confused is I have 7 samples , should I need build each sample a 2nd-pass index for the 2nd pass mapping?

**Comment by alexdobin** [comment]
Hi Bryan,

I think the problem is in the formatting of the command line, it seems that the 2nd dash in -–sjdbFileChrStartEnd is a different character, so it does not recognize it as a parameter.

I would recommend including the GTF in the 2nd pass genome generation for consistency.

Cheers
Alex

**Comment by bryanwong0610** [comment]
Hi @alexdobin 
The advice you give me helped me a lot, and the formatting may the major issue causing the bug which due to the Chinese IME.
And I found out that maybe the GTF file is also a essential file for the 2nd pass index generation , because if I didn't add it into the command line ,the index could not generate either.
Finally, I sincerely thank you for recovering my problem .
bryan
