### ISSUE TITLE
EXITING because of INPUT ERROR: could not open genomeFastaFile: -

### ISSUE THREAD

**Issue by Woqo** [alexdobin/STAR#1334]
Hi，
thank you for this software!
I would like to use it for my analysis.
But when I am trying I get this error ：

 STAR --runMode genomeGenerate \ --genomeDir /home/xuzhixiang/ \ --genomeFastaFiles /home/xuzhixiang/GCF_000001215.4_Release_6_plus_ISO1_MT_genomic.fna \ --sjdbGTFfile /home/xuzhixiang/GCF_000001215.4_Release_6_plus_ISO1_MT_genomic.gff
 
##then show following：
        STAR version: 2.7.9a   compiled: 2021-05-04T09:43:56-0400 vega:/home/dobi                                   n/data/STAR/STARcode/STAR.master/source
Aug 21 20:50:52 ..... started STAR run
Aug 21 20:50:52 ... starting to generate Genome files

EXITING because of INPUT ERROR: could not open genomeFastaFile: -

Aug 21 20:50:52 ...... FATAL ERROR, exiting

```

Can you give me some advice?
Thanks!

**Comment by alexdobin** [comment]
Hi @Woqo 

this looks like a problem with the formatting of the command line. I would remove the backslashes \ so that it's one line. You should be able to use backslashes for multiline commands, but you need to make sure there are no spaces after them.

Cheers
Alex

**Comment by Woqo** [comment]
Hi, Alex
  Thanks for your help! It had been solved. 

Cheers
Woqo
