### ISSUE TITLE
soloCellFilter identical results between EmptyDrops_CR and CellRanger2.2

### ISSUE THREAD

**Issue by dbrg77** [alexdobin/STAR#1339]
Hello, thanks for making STARsolo. We started to use it on a daily basis for our single cell data processing, and it helps us a lot.

We recently came across a few problems with the `soloCellFiltering` runMode. First, it seems the released version (v2.7.9a) gave a segmentation fault whenever we use `--runMode soloCellFiltering`. Then it turns out that we have to clone the latest GitHub and compile.

I cloned the repository on 26th Aug, and compiled it successfully. Then, when I run the binary using `STAR/bin/Linux_x86_64/STAR`. I got the following error: 

```
/home/xichen/tools/STAR/bin/Linux_x86_64/STAR: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/xichen/tools/STAR/bin/Linux_x86_64/STAR)
/home/xichen/tools/STAR/bin/Linux_x86_64/STAR: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /home/xichen/tools/STAR/bin/Linux_x86_64/STAR)
```

Then, the binary `STAR/bin/Linux_x86_64_static/STAR` worked without any errors, so I used that to filter cells that I got from published data sets. Based on the document, the options `--soloCellFilter  EmptyDrops_CR` and `--soloCellFilter  CellRanger2.2` should work differently. However, the results looked exactly the same.

This is the data I have:

```
$ tree raw

raw
|-- barcodes.tsv
|-- features.tsv
`-- matrix.mtx
```

I ran `soloCellFiltering` on them with different `soloCellFilter` options:

```
# with CellRanger2.2
~/tools/STAR/bin/Linux_x86_64_static/STAR --runMode soloCellFiltering raw/ cr2.2/ --soloCellFilter CellRanger2.2

# with EmptyDrops_CR
~/tools/STAR/bin/Linux_x86_64_static/STAR --runMode soloCellFiltering raw/ dropcr/ --soloCellFilter EmptyDrops_CR
```

Then, I got identical results:

```
$ md5sum cr2.2/*.* dropcr/*.*

9c3beff108531b8eb9e97c0b2fcdd98d  cr2.2/barcodes.tsv
dadb954c53ae1e384833d34d09a9b0e7  cr2.2/features.tsv
34fd27ac0bc70116e6f8c64fed7c4273  cr2.2/matrix.mtx
9c3beff108531b8eb9e97c0b2fcdd98d  dropcr/barcodes.tsv
dadb954c53ae1e384833d34d09a9b0e7  dropcr/features.tsv
34fd27ac0bc70116e6f8c64fed7c4273  dropcr/matrix.mtx
```

The test data can be found here: https://xc1-temp.oss-cn-shenzhen.aliyuncs.com/raw.tar.gz

md5: `97285ebb4c20f88a529fd61ba0543b7a  raw.tar.gz`

I tried a few data sets, but they all give the same results regardless of the `soloCellFilter` options in use. Could you help? Thank you !

Regards,
Xi

**Comment by alexdobin** [comment]
Hi Xi,

in principle, it is possible that the two filtering methods produce the same results.
Could you please send me the Log.out files for the two runs?

Cheers
Alex

**Comment by dbrg77** [comment]
Hi Alex,

Thanks for the reply. Files attached. 

[CellRanger2.2.log](https://github.com/alexdobin/STAR/files/7077779/CellRanger2.2.log)
[EmptyDrops_CR.log](https://github.com/alexdobin/STAR/files/7077786/EmptyDrops_CR.log)

I actually forgot to check the `Log.out` file, and I just looked at them. It seems that `EmptyDrops_CR` thinks all CBs are valid (no empty cells found), but the output files are identical. I assume in the case of `EmptyDrops_CR`, all CBs should be written in the filtered output.

Xi

**Comment by alexdobin** [comment]
Hi Xi,

it looks like the "raw" data contains only 2039 cells, which means that it was already pre-filtered somehow. How did you generate the raw matrices?
Both --soloCellFilter EmptyDrops_CR and --soloCellFilter CellRanger2.2 algorithms start with the same procedure to find non-empty cells: cells with UMI count > 1/10*MaxUMIcount. CellRanger2.2 stops there, but EmptyDrops_CR finds additional non-empty cells.
In this case, all cells have counts > 1/10*MaxUMIcount, so there are no empty cells, and hence the outcomes are exactly the same.

Cheers
Alex

**Comment by dbrg77** [comment]
Hi Alex,

Thanks for the explanation, and now I understand. The data is from a published paper, and I simply downloaded the matrix from GEO. I'm not sure if they are raw or filtered.

Anyway, maybe I did not explain well. My problem is the output of `CellRanger2.2` and `EmptyDrops_CR` are the same. There are a total of 5,875 barcodes in `raw`. `CellRanger2.2` says 2,039 of them are true cells. Therefore, it outputs a filtered matrix with 2,039 cells. That's fine.

`EmptyDrops_CR` says no empty drops are found, and all of them are true cells. Therefore, I expect `EmptyDrops_CR` not to do any filtering, and simply return a filtered matrix that is identical to the original raw matrix, containing 5,875 cells.

However, the current situation is that `EmptyDrops_CR` returns a matrix with 2,039 cells (identical to `CellRanger2.2` output), even it says no empty drops are found. I expect the output of `EmptyDrops_CR` to be the same as raw.

I hope this makes sense, or am I missing something?

Xi

**Comment by alexdobin** [comment]
Hi Xi,

I think I am still a bit confused... Could you please send me the "raw" files (matrix,features,barcodes)?

Cheers
Alex

**Comment by dbrg77** [comment]
Hi Alex,

Sure, you can download the raw files from here: https://xc1-temp.oss-cn-shenzhen.aliyuncs.com/raw.tar.gz

Thanks!

Xi

**Comment by alexdobin** [comment]
Hi Xi,

I checked it, and this file seems to contain only a small number of cells: 5874 cells.
For EmptyDrop_CR filtering, we need to define cells that are "truly empty", i.e. have very low UMI count.
These are taken from 45000-90000 range, sorted descending by the UMI count.
Since we only have ~6k cells in this case, there no way to define ambient RNA expression in empty cells, and so no additional non-empty cells are detected. I have changed this warning message to make it clear:

> emptyDrops_CR filtering: total number of cells: nCB=5874 is smaller than emptyCellMinIndex=45000, which is the starting index for the *true empty* cells. The additional non-empty cells will not be detected.

Cheers
Alex

**Comment by dbrg77** [comment]
Hi Alex,

I just realised that I forgot to reply. Sorry about this.
Thank you very much for your explanation. Now, it is clear.

I have another two minor questions regarding the `--runMode soloCellFiltering` functionality:

First, if I run the program simply as:

```
STAR --runMode soloCellFiltering --soloCellFilter EmptyDrops_CR \
raw filtered
```

Then, I will get the resulting file in the current running directory with the name:

```
filteredbarcodes.tsv
filteredfeatures.tsv
filteredmatrix.mtx
```

I think the intended behaviour should be creating a directory named `filtered`, right? Maybe this is a small formatting bug.

Second, I notice that a directory called `_STARtmp/` is generated and remained there in the running directory. I assume it is needed during the run. If I run two processes together, will this cause problems? For example, in my currently directory, I have two raw matrix from different experiments, like this:

```
.
|-- raw1
|   |-- barcodes.tsv
|   |-- features.tsv
|   `-- matrix.mtx
`-- raw2
    |-- barcodes.tsv
    |-- features.tsv
    `-- matrix.mtx
```

I filter them using:

```
STAR --runMode soloCellFiltering --soloCellFilter EmptyDrops_CR raw1 filtered1/
STAR --runMode soloCellFiltering --soloCellFilter EmptyDrops_CR raw2 filtered2/
```

If I submit jobs to computing farms, the two commands are run in parallel. I assume they both need the content from `_STARtmp/` during the run. Will this cause problem?

Thank you.

Regards,
Xi

**Comment by alexdobin** [comment]
Hi Xi,

Sorry for the delayed reply.

The last parameter for the ```--runMode soloCellFiltering``` option is the prefix for the output files, so if you need to write files in the separate directory, you need ```filtered/```

The _STARtmp directory is not really used, I will fix the code to prevent creating it. It will not interfere with other runs.

**Comment by dbrg77** [comment]
Thanks for the info, Alex. It is very clear now.

I will close the issue.

Thanks,
Xi
