### ISSUE TITLE
Mapping to an "artificial" scaffold is very slow! 

### ISSUE THREAD

**Issue by fcamara7** [alexdobin/STAR#134]
Hi Alex,

I have just started using your STAR aligner and find it extremely fast, and based on what I have been told by colleagues who have been using it for other projects, also very accurate. 

In my case I have mapped over 100M paired-end reads to a bird assembly (>1.1Gb) and that only took one hour which is great. Unfortunately I have failed to get the program to work properly in the one instance described below:

One thing I do in our genome annotation projects is to map the same set of reads that we map against the assembly being annotated, to what I call an "artificial" scaffold which I subsequently use to evaluate the accuracy of the ab initio prediction programs used in our pipeline.

For our purposes and an "artificial" scaffold is a made up of ~500 concatenated "real" genes from the organism being annotated interspersed by approximately 1000 nucleotides of genomic sequence. The particular scaffold I am having problems with, is about 12Mbases in length.  The job of aligning the same reads I previously mapped to the full assembly in just one hour, in this case takes a long, long time. I suppose the program is getting "stuck" as obviously most of the input reads do not map to the scaffold in question....Strangely the GEM mapper (which we had been using in this type of projects until now) must deal with this problem in a different manner as it does the same job quite fast.

The STAR command line I am using to run this job (as well as the alignment against the entire assembly) is:

STAR --genomeDir $GENOMEDIR --readFilesIn $READDIR/${tissue}_read1.fastq.gz  $READDIR/${tissue}_read2.fastq.gz --readFilesCommand zcat --alignIntronMin 30 --alignIntronMax 50000 --outFilterMismatchNoverLmax 0.05 --runThreadN 6 --outFileNamePrefix $STARDIR/$results/${tissue} --outSAMstrandField intronMotif --outSAMtype BAM SortedByCoordinate --outSAMattrIHstart 0

Is there any other parameter(s) I should use to speed up things for aligning the 100-nt Illumina reads just to the artificial scaffold I just described?

Thanks a lot in advance for your assistance!

Francisco

**Comment by alexdobin** [comment]
Hi @fcamara7 

what you observe is a "normal" behavior for STAR current algorithm, please see this thread:
https://groups.google.com/d/msg/rna-star/I1phytOigdE/59LDaMQIEgAJ
You can try a "quick" solution to this problem - reduce --seedPerWindowNmax to 30 (or maybe even 10). However, it does not always work, and it also reduces the mapping accuracy.

The solution that I strongly recommend is to supply STAR with the full reference.
In your case, you can add the whole genome to your artificial scaffold. If you do not want to deal with multimappers that map to the genes on the scaffold and on the whole genome, you can mask the genes in the genome with N. This solution will both accurate and fast.

Cheers
Alex

**Comment by fcamara7** [comment]
Hi again Alex,

Thank you for the clarification! I actually found the thread a bit before I got your message and proceeded to try the suggested strategy and it does work perfectly.

Cheers,

Francisco
