### ISSUE TITLE
older genomeVersion while used latest version of star?

### ISSUE THREAD

**Issue by marwa38** [alexdobin/STAR#1340]
I have an up-to-date STAR version where I am using on my university cluster and when I check modules loaded (by module list), again I found the latest version which is loaded. 
![image](https://user-images.githubusercontent.com/68851733/131242888-5acbbd35-c2b1-4d75-a380-1403e5359aa5.png)
Also when I check the Log.out (attached) file I found it is the latest version STAR 2.7.9.a 
[Log.out.txt](https://github.com/alexdobin/STAR/files/7072104/Log.out.txt)

But when I check the genomParameters.txt (attached) I found an older version STAR (versionGenome 2.7.4a) but I don't know why, I rechecked again after star indexing, the modules that are loaded and only the latest is found. 
[genomeParameters.txt](https://github.com/alexdobin/STAR/files/7072103/genomeParameters.txt)

Why the genome version is older? it is the most updated and very recent release of Salmo_salar on rapid release of Ensembl
http://ftp.ensembl.org/pub/rapid-release/species/Salmo_salar/GCA_905237065.2/

Here is my STAR code if you need to have a look at:
STAR --runThreadN 24 --runMode genomeGenerate --genomeDir starIndex --genomeFastaFiles Salmo_salar-GCA_905237065.2-unmasked.fa --sjdbGTFfile Salmo_salar-GCA_905237065.2-2021_07-genes.gtf --sjdbOverhang 100

Also another relevant error which is relevant to this is the genomeType 
What should I do to resolve the genomeType name produced?
![image](https://user-images.githubusercontent.com/68851733/131243594-d95fe6f0-170f-4295-8d2b-a2e96923ead2.png)

Could you please advise on this?

**Comment by alexdobin** [comment]
Hi @marwa38 

versionGenome is the latest STAR version the genome can be generated with and is still compatible with the current STAR version. So, for 2.7.9a, any genome generated with 2.7.4a or older is compatible.
However, the reverse is not true: if you generated the genome with the 2.7.9a you cannot use it for mapping with older versions of STAR. The best solution always is to generate the genome with the same version you are using for mapping.

Cheers
Alex

**Comment by marwa38** [comment]
I am using the latest version of STAR for indexing which is used as input in nf.core/rnaseq for mapping which have the latest version of STAR.

**Comment by alexdobin** [comment]
Then it should have worked...
Could you please send me the Log.out files for both genome generation and mapping?

**Comment by marwa38** [comment]
Thanks Alex
Very much, nf-core doesn't seem to me to have a log file for mapping. but I shared with you the genome generation one before. I rechecked nf-core and found out to be different version of STAR 2.7.6a and not the most up-to-date one I thought it be (2.7.9a)
I consider that ticket is resolved.
