### ISSUE TITLE
Error running star - error: could not create output file 

### ISSUE THREAD

**Issue by polaxgr** [alexdobin/STAR#1344]
Hi all, newbie to STAR aligner. I dont have a very capable pc. It has 9 cores and 64gb RAM. My command is the following:

STAR --runThreadN 5 --genomeDir /Users/genome_Dir --readFilesIn /Users/data/Rna_seq_hl_nm/RNA-seq_HL_SVI_0h_rep1.fastqsanger.gz /Users/data/Rna_seq_hl_nm/RNA-seq_HL_SVI_0h_rep2.fastqsanger.gz --readFilesCommand zcat --sjdbGTFfile /Users/genome_Dir/GRCh38.p13_genomic.gtf --outSAMtype BAM SortedByCoordinate --limitBAMsortRAM 60

and the full error is the following:

BAMoutput.cpp:27:BAMoutput: exiting because of *OUTPUT FILE* error: could not create output file ./_STARtmp//BAMsort/4/47
SOLUTION: check that the path exists and you have write permission for this file. Also check ulimit -n and increase it to allow more open files.

Any suggestions? Thanks in advance!

**Comment by alexdobin** [comment]
Hi @polaxgr 

this is likely a problem with limit for number of open files, please try
```ulimit -n 4000```. You may need to use sudo for this command.
Also, ```--limitBAMsortRAM``` should be the number of bytes, for 60GB: ```--limitBAMsortRAM 60000000000```

Cheers
Alex
