### ISSUE TITLE
STAR does not compile under MacOS 11.5.2 Clang 

### ISSUE THREAD

**Issue by rayhendricks** [alexdobin/STAR#1348]
Steps to reproduce:

1. Unzip STAR
2. cd source
3. edit makefile with: 

```
make CXXFLAGSextra=-march=native
make LDFLAGSextra=-flto CXXFLAGSextra="-flto -march=native"

```
4. make STARforMacStatic
5. error is make STARforMacStatic
[error.txt](https://github.com/alexdobin/STAR/files/7116365/error.txt)

**Comment by rayhendricks** [comment]
Looks like clang does not support compiling star right now.  Did not realize that.

**Comment by alexdobin** [comment]
Hi Ray,

indeed clang does not support OMP which is require for STAR. You would to install gcc compiler.

Cheers
Alex

**Comment by rayhendricks** [comment]
Hi Alex,

I'm running ' make STARforMacStatic CXX=/opt/homebrew/Cellar/gcc/11.2.0' to
compile STAR via gcc as installed by homebrew as I have an Apple Silicon
macbook and want to run STAR natively, but make is not working.  I have
installed GCC with 'brew install gcc', not sure why that's not working.
Any ideas? Do I have to put the g++8 after the directory?

Best,

Ray Hendricks

**Comment by alexdobin** [comment]
Hi Ray,

yes, CXX should be the path to the executable file.
Please let me know if it works, I am curious to see if it can be compiled on M1 processors.

Cheers
Alex

**Comment by rayhendricks** [comment]
Hi Alex,

Yes so it looks like it works when I comment out `CXXFLAGS_SIMD ?= -mavx2` in line 35 of the makefile and build with `CXX=/opt/homebrew/Cellar/gcc/11.2.0/bin/g++-11` and then `chmod +rwx STAR`.  I think it looks like this has to do with[ gcc not realizing that ARM64 does not have avx support](https://github.com/stereolabs/zed-tracking-viewer/issues/5).    

Hope that helps

Ray

**Comment by alexdobin** [comment]
Hi Ray,

Great, thanks for letting me know. I think you can also do (instead of commenting out the line):
$ make CXX=/opt/homebrew/Cellar/gcc/11.2.0/bin/g++-11 CXXFLAGS_SIMD=""

Cheers
Alex
