### ISSUE TITLE
Incompatible mate alignments. Expected behavior?

### ISSUE THREAD

**Issue by ghost** [alexdobin/STAR#135]
Hi Alex,
      I have the following output for a read pair: 

`mate1  163 chr20   59037258    255 23M1185N38M =   59037258    58384   TTCGTTCTTGCTGCACCAATAAGAGACTTCACAATGGAAGGCAGTCCCCACTCTGTGCTGA   JF-<FJFAFJFFJAF<7FFF7<FJJJFFJFJJJJJJ7J<AAAJJJFFJJJFJJJJF7AFJF   NH:i:1  HI:i:1  AS:i:142    nM:i:0  NM:i:0  MD:Z:61 jM:B:c,22   jI:B:i,59037281,59038465`

`mate2    83    chr20   59037258    255 23M1185N27M57138N11M    =   59037258    -58384 TTCGTTCTTGCTGCACCAATAAGAGACTTCACAATGGAAGGCAGTCCCCACTCTGTGCCGC    FJJJA-A-<AFJ<JFF<JJFAAJJJA<<JJJJJJJJJJJFJJFFA777<<AFA7JA77-J<   NH:i:1  HI:i:1  AS:i:142    nM:i:0  NM:i:0  MD:Z:61 jM:B:c,22,2 jI:B:i,59037281,59038465,59038493,59095630`

The alignment for mate1 has match positions within the implied intron skip positions of mate2. So, the two alignments are not consistent with each other. Why is such a paired alignment reported? Is there a way to prevent such conflicting alignments from being reported?
                Thank you,
                 Christian

**Comment by alexdobin** [comment]
Hi Christian,

there is no setting at the moment to filter such alignments. I need to check whether it's easy to do or not -  will do next week.

Cheers
Alex
