### ISSUE TITLE
STAR solo for dropseq data

### ISSUE THREAD

**Issue by JihedC** [alexdobin/STAR#1357]
Hi,

First of all thank you for the software, the documentation is very good and I could use it properly on 10X scRNA-seq data. 
I have a question concerning the cell barcodes and the UMI.

I would like to use the alignment generated by STAR solo in the [scTE pipeline](https://github.com/JiekaiLab/scTE). And for that I need to have the CR and UR included as below:
```
$ samtools view test.bam
A00269:12:H7YF2DMXX:2	0	chr10	55902580	255	50M	*	0	0	GTTCTCTCCGTATGTGAGCATGGGAGATACATCCCAGAAAGGCAGAAGGG	FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	NH:i:1	HI:i:1	AS:i:49	nM:i:0	CR:Z:CTAGAGTGTTTCGCTC	CY:Z:FFFFFFFFFFFFFFFF	UR:Z:TACATGACGC	UY:Z:FFFFFFFFFF
A00269:13:H7YF2DMXX:2	0	chr10	55902784	255	50M	*	0	0	ATAATCTTTGAGATCTCTGGTGAAAATAAGTAGCATAAAGGACAGAATCA	FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	NH:i:1	HI:i:1	AS:i:49	nM:i:0	CR:Z:CTAGAGTGTTTCGCTC	CY:Z:FFFFFFFFFFFFFFFF	UR:Z:TACATGACGC	UY:Z:FFFFFFFFFF
A00269:14:H7YF2DMXX:2	0	chr13	67837311	255	50M	*	0	0	CTGTTCATTATTTGAGGAAATCAGGACAGGAAATCAAACATGGCAGAATC	FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	NH:i:1	HI:i:1	AS:i:49	nM:i:0	CR:Z:ATCGAGTGTTTCGCTC	CY:Z:FFFFFFFFFFFFFFFF	UR:Z:TACATGACGC	UY:Z:FFFFFFFFFF
A00269:15:H7YF2DMXX:2	0	chr14	114380523	255	50M	*	0	0	GATCCAGATTAATTGAGACTGTTGATCCTCCTACAGGGTCGCCCTTCTCC	FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	NH:i:1	HI:i:1	AS:i:49	nM:i:0	CR:Z:CTAGAGTGTTTCGCTC	CY:Z:FFFFFFFFFFFFFFFF	UR:Z:TACATGACGC	UY:Z:FFFFFFFFFF
```

It worked well when I used 10X data but gives me weird UMI and barcodes when I use Dropseq datasets. I think that the problem comes from the fact that I don't really understand where I can find the information about the barcode in the dropseq datasets.

The read 1 contains this:

```
@SRR6365733.1 1/1
TTGAGNAAGAGCAAAGGCAT
+
AAAAA#//EEE/E6EEEE6E
@SRR6365733.2 2/1
CGGTCNTACTATAAACAGGA
+
AAAAA#EEEEAEEEEEEEEE
@SRR6365733.3 3/1
GGAGCNCTTACCGGCGAACG
+
AA/AA#EEEEEEEEEEEAEE
```

While the read 2 contains (I guess) the cDNA sequence:

```
@SRR6365733.110 110/2
ACTGTGTGATCGNCCCTNNNTNNNNNATGNTANNGNGNNNCNNNAATAGT
+
AAA/A<A/<<</#/<//###/#####/A/#AA##/#/###/###/A/A</
@SRR6365733.111 111/2
AGCCAGCCAGCCTGTAGCNNTNNNNNAAGNCANNTNANNNTNNNACC
+
A/AAA/EEA/<E//<//6##/#####///#6/##/#/###/###/66
```

And my script to generate the alignment is the following:

```
STAR --genomeDir $INDEX \
    --readFilesIn $READS/SRX3461254_T1_2.fastq.gz $READS/SRX3461254_T1_1.fastq.gz \
    --soloUMIlen 12 --soloType CB_UMI_Simple --soloCBwhitelist None  \
    --soloBarcodeReadLength 0 \
    --outSAMtype BAM SortedByCoordinate \
    --outSAMattributes NH HI nM AS CR UR CB UB \
    --readFilesCommand zcat \
    --outFilterMultimapNmax 100 \
    --winAnchorMultimapNmax 100 \
    --outMultimapperOrder Random  #\
    --runRNGseed 777 --outSAMmultNmax 1\
    --outFileNamePrefix Kernfeld_e12/e12_rep3
```

The alignment is done but unfortunately the barcode and UMI written in the BAM file do not really make sense:

```
SRR6365735.78995521     16      chr1    3000081 255     2S48M   *       0       0       CCCCCTTCTCCCCCCCGGTTTTTTTTTTTTTTTTTTTTTTTTTTTGGGTG      ////////////////////<EEEEEEEAEEEEEEEEEEEEEEAEA/AAANH:i:1  HI:i:1  nM:i:7  AS:i:33 CR:Z:NNNNNNNNNNNNNNNN   UR:Z:NNNNNNNNNNNN       CB:Z:-  UB:Z:-
SRR6365735.11175222     0       chr1    3000096 255     35M14S  *       0       0       GCTTTTTTTTTTTTTTTTTTTTTTTTTTGGGGGGGGGGGGGGTGGGGGG       /////A6</666//6///6/<///////////6//A/E<EAE//</<//NH:i:1   HI:i:1  nM:i:1  AS:i:32 CR:Z:ACACAAAAAAAAAAAA   UR:Z:AAAANNNNNNNN       CB:Z:-  UB:Z:-
```

A lot of them are just a series of Ns. I was wondering if you had experience on how to configure STAR to extract the umi and barcodes from Dropseq experiments?

I found 1 issues that seemed similar but it didn't work for me, I still get the same weird barcodes and umi in the BAM file
#1211.

It would be great! 
Thanks in advance!

**Comment by alexdobin** [comment]
Hi Jihed,

yo need to figure out that start and length for both CellBarcode and UMI in your data. I am not sure if these are standard for all Drop-seq flavors. Most likely the first N bases are CB and the next 20-N bases are UMI (since the total length of your barcode reads is 20). Then you can specify ```--soloCBstart 1 --soloCBlen N --soloUMIstart N+1 --soloUMIlen 20-N```.
However, you need to figure out what N is - from the description of the protocol that was sued to create these libraries.

Cheers
Alex

**Comment by JihedC** [comment]
Thank Alex for your reply. 
I will try that, the data was published few years ago I hope they described the protocol!

**Comment by JihedC** [comment]
Hi 
I have contacted the lab that generated the dataset and they gave me the information I needed, it's super nice. I tried with the parameters:
`--soloCBstart 1 --soloCBlen 12--soloUMIstart 13 --soloUMIlen 8` 

and it seems to have worked :)  

```
SRR6365749.75305521	0	chr1	3010774	255	13M4305N32M5S	*	0	0	ACATTGGGGGAACTGTGATCATCCACTTATGTGTTTGCTAGTCCTAGTCT	//AAA6//////EAEE/////<AA//<EEE<E<E//AA//</A/A<AEEA	NH:i:1	HI:i:1	nM:i:4	AS:i:34	CR:Z:AGGACGCCAAAA	UR:Z:TACCGTTA	CB:Z:AGGACGCCAAAA	UB:Z:TACCGTTA
```
So I leave this here, if someone ever wants to remap Dropseq data with star solo, [here is the protocol for CB and UMI](http://mccarrolllab.org/wp-content/uploads/2015/05/figure-2D.png)

Cheers!
