### ISSUE TITLE
Reoccuring "Segmentation fault (core dumped)" error

### ISSUE THREAD

**Issue by nataschamay** [alexdobin/STAR#136]
Hi Alex,

Sometime at the end of last year, I tried troubleshooting this problem and your suggestion was to upgrade to the latest commit at that time. The error went away at that time... but now it returned when I am trying to run a mapping again.

The reference genome has 41k contigs, so I used the same "genomeCreate" settings as last time: **--genomeSAindexNbases 10 --genomeChrBinNbits 10**

**Comment by nataschamay** [comment]
[I'm so sorry, I think I hit something that published the post too soon...]

Hi Alex,

I am trying to run STARlong to map PacBio Isoseq sequences to a reference genome, but I keep getting a "Segmentation fault" error, no matter what I try...

Sometime at the end of last year, I tried troubleshooting this problem and your suggestion was to upgrade to the latest commit at that time. The error went away at that time... but now it returned when I am trying to run a mapping again.

I had tried your suggestion from [elsewhere](https://github.com/alexdobin/STAR/issues/82#issuecomment-156487246) to compile from source... but that doesn't work:

**make clean**
cd ./extras/doc-latex && latexmk -C -output-directory=../.././doc -jobname=STARmanual STARmanual
/bin/sh: latexmk: command not found
make: *** [clean] Error 127
**make STARlong**
make: *** No rule to make target `STARlong'.  Stop.

I also tried using the [latest commit](https://github.com/alexdobin/STAR/releases/tag/2.5.1b), but that didn't help too.

What else could I try?

Thank you so much!

~ Natascha

------

Details of my STARlong run:

The reference genome has **41k contigs**, so I used the same "genomeCreate" settings as last time: **--genomeSAindexNbases 10 --genomeChrBinNbits 10**

My STARlong command is as follows:

/data/software/STAR-STAR_2.5.0_commit454728d/bin/Linux_x86_64/STARlong \
--runMode alignReads \
--readNameSeparator space \
--outSAMattributes NH HI NM MD \
--outFilterMultimapScoreRange 1 \
--outFilterMismatchNmax 2000 \
--scoreGapNoncan -20 \
--scoreGapGCAG -4 \
--scoreGapATAC -8 \
--scoreDelOpen -1 \
--scoreDelBase -1 \
--scoreInsOpen -1 \
--scoreInsBase -1 \
--alignEndsType Local \
--seedSearchStartLmax 50 \
--seedPerReadNmax 100000 \
--seedPerWindowNmax 1000 \
--alignTranscriptsPerReadNmax 100000 \
--alignTranscriptsPerWindowNmax 10000 \
--genomeDir /data/rgg_data/Tilapia_Genome/Mos_Tilapia_Genome_Computomics/63ContaminantRemoved/STAR_Genome_Index_bin10_SAindex10 \
--readFilesIn Til_Isoseq_SW_collapsed.fasta

**Comment by alexdobin** [comment]
Hi Natascha,

to compile STARlong, please 
$ cd source/
$ make clean
$ make STARlong

Also, please re-generate the genome with the latest version.
If the compiled executable still throws the seg-fault, please send me the Log.out file.

Do you remember which version you used when the error went away - this could be helpful to track the problem.

Cheers
Alex

**Comment by nataschamay** [comment]
Hi Alex,

The version I used when the error went away was [STAR 2.5 commit 454728d](https://github.com/alexdobin/STAR/commit/454728dadcce1fc3a69018f480259a2ae2e06572)
I found my previous issue report too, for your reference:
https://github.com/alexdobin/STAR/issues/89

This time round, I tried your suggestion of compiling STARlong in source/ and regenerating the genome:

-rwxr-xr-x. 1 natascha bio-info 12313884 Jan 23 04:18 STAR-2.5.1b/bin/Linux_x86_64_static/STAR
-rwxr-xr-x. 1 natascha bio-info 1912145 **Apr 25** 16:40 STAR-2.5.1b/source/STARlong

ll STAR_Genome_Index_bin10_SAindex10_20160425/
total 8404176
-rw-r--r--. 1 natascha bio-info     212896 Apr 25 18:18 chrLength.txt
-rw-r--r--. 1 natascha bio-info    1165988 Apr 25 18:18 chrNameLength.txt
-rw-r--r--. 1 natascha bio-info     953092 Apr 25 18:18 chrName.txt
-rw-r--r--. 1 natascha bio-info     447475 Apr 25 18:18 chrStart.txt
-rw-r--r--. 1 natascha bio-info 1085239296 Apr 25 18:26 Genome
-rw-r--r--. 1 natascha bio-info        849 Apr 25 18:18 genomeParameters.txt
-rw-r--r--. 1 natascha bio-info 7511719260 Apr 25 18:26 SA
-rw-r--r--. 1 natascha bio-info    6116787 Apr 25 18:26 SAindex


However, the segmentation fault is still happening:

/home/natascha/STAR-2.5.1b/source/STARlong --runMode alignReads --readNameSeparator space --outSAMattributes NH HI NM MD --outFilterMultimapScoreRange 1 --outFilterMismatchNmax 2000 --scoreGapNoncan -20 --scoreGapGCAG -4 --scoreGapATAC -8 --scoreDelOpen -1 --scoreDelBase -1 --scoreInsOpen -1 --scoreInsBase -1 --alignEndsType Local --seedSearchStartLmax 50 --seedPerReadNmax 100000 --seedPerWindowNmax 1000 --alignTranscriptsPerReadNmax 100000 --alignTranscriptsPerWindowNmax 10000 --genomeDir /stor2/Tilapia_Genome/Computomics_scaffolds/Q1527_v2_63ContaminantsRemoved/STAR_Genome_Index_bin10_SAindex10_20160425 --readFilesIn Til_Isoseq_FW_collapsed.fasta
Apr 26 10:07:45 ..... Started STAR run
Apr 26 10:07:45 ..... Loading genome
Apr 26 10:07:49 ..... Started mapping
Segmentation fault (core dumped)


I have attached the Log.out file for your reference.

Thank you so much for your help.

Regards,
Natascha
[Log.out.txt](https://github.com/alexdobin/STAR/files/235813/Log.out.txt)

**Comment by alexdobin** [comment]
Hi Natascha,

nothing suspicious in the Log.out.txt file...

If you try to map a small number of reads (in your previous example you had test.fasta file), does it still seg-fault?
Would it be possible for you to send me the link to the genome, and the minimalistic set of reads that cause the seg-fault?

Cheers
Alex

**Comment by nataschamay** [comment]
Thanks for helping to sort this out Alex! :)

It worked after I used your suggestion to set the alignWindowsPerReadNmax parameter.
Initially it still seg-faulted when I tried setting the parameter to 20000. 
Then, as you recommended, I increased the parameter setting to 200000 and the job completed.

Thanks again!

**Comment by alexdobin** [comment]
Hi Natascha,

thanks for letting me know!

Cheers
Alex
