### ISSUE TITLE
Discrepancies between solo counts and BAM with "--soloUMIdedup NoDedup" option

### ISSUE THREAD

**Issue by VincentGardeux** [alexdobin/STAR#1361]
Hi,

I'm using STAR solo from v.2.7.9a to count reads assigned to a bulk multiplexed library.
In particular, I'm using these options for UMI dedup:  "--soloUMIdedup NoDedup 1MM_Directional Exact"

Once I got the output matrices (and transformed the .mtx to dense count matrices), I ended up seeing a difference with another [read counting tool](https://github.com/DeplanckeLab/FastReadCounter) that I developed (not the point here).

Basically, the Exact-UMI matrix is strictly identical to my output. But the Nodedup is not (but only in very little number of mismatches).
So I went along and checked the reads in the output BAM file where I found these mismatches.

**Here is one example:**
- For gene ENSG00000000457 and barcode CTCAGAGCAGAC, the NoDedup option counts 20 reads, but when I grep the bam, I found 39 reads (see grepped .sam file [here](https://updeplasrv1.epfl.ch/ENSG00000000457_CTCAGAGCAGAC.sam))

You probably will see that there are only 20 reads with primary alignments. So at this point, I also thought that maybe STARsolo was not counting secondary alignments. However, I checked another barcode (TAGTAGCACGCA) for the same gene, and this time STARsolo counts 3 read counts, as I can find in the SAM. In particular, there is one non-primary alignment that is counted by STAR (see grepped .sam file [here](https://updeplasrv1.epfl.ch/ENSG00000000457_TAGTAGCACGCA.sam)).

So I was wondering if this was a bug with multiple-aligned reads / Nodedup option, where most of the time secondary alignments are counted, but in rare cases, they may be discarded? 
Or if it was linked to another feature of STAR that I failed to notice?

Thanks in advance!

**Comment by alexdobin** [comment]
Hi Vincent,

in the example you posted, all reads except one appear twice, i.e. each read has two alignments to the same gene. Each read is counted only once towards the gene, so the counts are smaller than the number of alignments.

Cheers
Alex

**Comment by VincentGardeux** [comment]
Oh I see.

So the rationale would be that secondary alignments are counted if primary/secondary are on different genes, but not if it comes from the same read on the same gene?

It makes sense actually. Can you confirm that this is what the behaviour is?

Thanks for the fast answer!

**Comment by alexdobin** [comment]
The policy for counting "unique-gene" reads is formulated like this:
1. For each read, only "transcript" alignments are considered, defined as alignments concordant with one or more transcripts.
2. A read is counted towards a gene if all of its "transcript" alignments correspond to this one gene. If a read has transcript alignments from more than one gene ("multi-gene" read), it's not counted.
