### ISSUE TITLE
Run Solo Counting only? 

### ISSUE THREAD

**Issue by krejciadam** [alexdobin/STAR#1364]
Hi!
  I have a huge scRNA-seq dataset (1.2 TB). Processing failed as I ran out of memory during solo counting, I have 2 questions related to such large datasets: 

- Is there a way to limit memory used during solo counting? 

- I have (unsorted) `Aligned.out.bam`. Can I run just solo counting using this file as input? I understand this should be possible with newer STAR versions, but I'm not sure from the documentation how to set the parameters when my `Aligned.out.bam` was created by STAR. 

Thanks a lot!

**Comment by alexdobin** [comment]
Hi @krejciadam 

could you please send me the Log.out file for the large run?

Thanks!
Alex

**Comment by krejciadam** [comment]
Unfortunately, it is not a public dataset and I can't share it. I'm not aware of anything this large. One option would be a simulated dataset, but the question is whether it is worth it. This was really a weird exception and in most scenarios, I don't see why anyone would have more than say 2, max. 3 Billion reads in a single dataset. I was really more after the option to easily run just solo counting on `Aligned.out.bam` - I think that would be pretty useful.

**Comment by alexdobin** [comment]
Hi @krejciadam 

right, such cases are pretty rare. I guess I will wait for such a large public dataset to pop up. :)
I have a script to get the counts from the BAM file, if it contains the error-corrected barcodes and UMI (CB/UB tags).
However, generating the BAM file with these tags requires even more RAM than simple counting.

Cheers
Alex

**Comment by krejciadam** [comment]
Makes sense! 
Would you mind sharing that script? I think it can be still quite useful in other scenarios. Like when after a run, I realize that I want also `Velocyto` in addition to `Gene` output which I didn't generate previously.  It would be great to be able to get this without the need to re-map.

**Comment by alexdobin** [comment]
Hi @krejciadam 

this script https://github.com/alexdobin/STAR/issues/1257#issuecomment-854973531 only works for Gene counts (CB sam tag), the velocity assignments (spliced/unspliced/ambig) are presently not recorded in the BAM file.

Cheers
Alex

**Comment by krejciadam** [comment]
Thanks! It is still helpful (and would actually solve my original problem). I think I can close this now.
