### ISSUE TITLE
float vs. real in .mtx files?

### ISSUE THREAD

**Issue by bugneville** [alexdobin/STAR#1369]
Importing _float_ .mtx files (e.g., like those from multimapping) in R for downstream analysis is currently [not straightforward](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=6746&group_id=61&atid=297).  Would there be any limitations if STAR just output these files as _real_ instead?

**Comment by bugneville** [comment]
Apologies for not responding sooner.

No -- i meant _real_ instead of _float_.  It appears if you simply change the header in the .mtx from _float_ to _real_, the .mtx files can be read into R by the various packages (most of which appear to depend on the Matrix R package?).  Is there any limitation with _only_ real precision vs. _float_ that you can imagine?

**Comment by alexdobin** [comment]
Hi @bugneville 

you are right, we indeed need to use "real" not "float" in the matrix market header.
I will fix it in the next release.

Thanks!
Alex

**Comment by bugneville** [comment]
thanks @alexdobin!
