### ISSUE TITLE
(less than) Minor issue

### ISSUE THREAD

**Issue by douglas-adamoski** [alexdobin/STAR#137]
Hi!

When STAR is checking the genome provided, it mistypes chromosomes:

_Genome version is compatible with current STAR version
Number of real (reference) **chromosmes**_

On 2.5.1b.

Best,
Douglas A

**Comment by alexdobin** [comment]
Hi Douglas,

Fixed the typo, thanks! 

Cheers
Alex

**Comment by douglas-adamoski** [comment]
Hi Alex,

Thanks for the amazing software ;-)

Best,
Douglas
