### ISSUE TITLE
Override the nNinUMI parameter?

### ISSUE THREAD

**Issue by VincentGardeux** [alexdobin/STAR#1378]
Hi,

I've recently been working with sequencing data coming from Iseq rather than Hiseq.
And I was puzzled for a while by the demultiplexing ratios that were very low compared to Hiseq.
Then, after some checkings, I realized that the reads had completely correct barcodes, but they could not be demultiplexed because of "nNinUMI", which, if I understand correctly, comes from the fact that the UMI contains N in its sequence?
What did you set this rule for?

Is there a way to override this parameter? Like allowing N's in the UMIs, or a certain number of N's in the UMIs?

Cheers

**PS:** I figured that there was a weird effect that makes the last nucleotide of the UMI to be of bad quality in our Iseq runs. This probably is the reason for an overrepresentation of Ns at the last UMI position. I could trim the R1 to get rid of the issue, but I was still wondering if an option could be set to control this nNinUMI parameter?

**Comment by alexdobin** [comment]
Hi Vincent,

sorry, I forgot that you also need to specify ```--soloBarcodeReadLength 0``` to prevent STARsolo from checking whether barcode read length is equal to CB+UMI length.

Cheers
Alex

**Comment by VincentGardeux** [comment]
Thanks Alex!
