### ISSUE TITLE
Abort trap when using --genomeLoad LoadAndExit

### ISSUE THREAD

**Issue by graurelien** [alexdobin/STAR#138]
Hi,

I'm trying to load the genome using the "shared memory" mode to save memory before analyzing several FASTQ files, but an error occur _immediately_ when launching the command : 
`STAR --genomeLoad LoadAndExit --genomeDir myGenomeDirectory/`
Here's the output : 
```
Apr 26 13:35:05 ..... Started STAR run
Apr 26 13:35:05 ..... Loading genome
Abort trap: 6
```
[Log.out.zip](https://github.com/alexdobin/STAR/files/236551/Log.out.zip)
note: same issue with LoadAndKeep when launching a reads alignment.

However when I launch a reads alignement with the following command line, everything works fine : 
`STAR --runThreadN 8 --genomeDir myGenomeDirectory/ --readFilesIn $fastq --outFileNamePrefix $outdir --readFilesCommand gunzip -c --outSAMtype BAM SortedByCoordinate --quantMode GeneCounts`

For information, I'm on Mac OS X 10.11 (El Capitan) with 32GB RAM. 

Can you please help me troubleshoot?

Many thanks in advance
Regards

**Comment by alexdobin** [comment]
Hi @graurelien 

this could be a problem with max shared RAM allowed for your Linux.
Please check this link for more details on configuring shared RAM fo Mac OS X:
http://www.spy-hill.com/~myers/help/apple/SharedMemory.html

What is the output of
$ grep shm /etc/sysctl.conf

The two important parameters you would nee to set by editing  /etc/sysctl.conf
kern.sysv.shmmax: 32000000000
kern.sysv.shmall: 7812500

Then you will need to reboot, or you can also try sysctl -p (this work on Linux, not sure about OS X).

Please let me know if this solves the problem..

Cheers
Alex

**Comment by graurelien** [comment]
Hi Alex,

Thanks a lot, this solves my problem of shared memory. 
Just for information, the file /etc/sysctl.conf didn't exist on my system, so I created it with the following lines : 
```
kern.sysv.shmmax=32000000000
kern.sysv.shmmin=1
kern.sysv.shmmni=128
kern.sysv.shmseg=32
kern.sysv.shmall=7812500
```

Note that the command `LoadAndExit` works, but I still get the same error `Abort trap: 6` when I use `Remove`. However, the genome is removed from the memory anyway, so it's not a big deal...

**Comment by alexdobin** [comment]
Hi @graurelien 

sounds good!
Since the "Remove" error does not interfere with operations seriously, let's consider it solved for the moment.

Cheers
Alex
