### ISSUE TITLE
std::bad_alloc when specifying '+' strand to custom chromosomes in gtf file (but not - strand)

### ISSUE THREAD

**Issue by amberzshen** [alexdobin/STAR#1382]
Hi Alex,

Thanks for making this fantastic tool.

We are using STARsolo to quantify transcripts using GRCh38 (.fa + .gtf) concatenated with a set of "custom" chromosomes which are HLA sequences with different genomic variants. When supplying the custom chromosomes, we just tack the sequences onto the .fa file, then supply some extra lines in the .gtf file as so:

<img width="917" alt="Screen Shot 2021-10-24 at 8 53 19 AM" src="https://user-images.githubusercontent.com/60327289/138595065-e1d93bc2-1008-4cc8-a758-fbb803987ca8.png">

We run in two-pass mode since we want STARsolo to be able to define the splicing junctions on our custom chromosomes. Interestingly, the strand designation for the custom chromosomes (specifying "+" versus "-" strand in the gtf file) seems to impact whether the job is able to finish. If we specify "+" strand in our gtf file for the custom chromosomes (which should be the correct strand), we get a memory error (std::bad_alloc, which seems like a memory issue). The step that it appears to stop at is “inserting junctions into the genome indices”. However, if we (incorrectly) specify "-" strand in the gtf file, STARsolo runs to completion (but we get much lower than expected counts for the custom chromosomes, as is expected because we specified the wrong strand). Ideally, we want the version with the "+" strand to work. Any suggestions / insights into what is causing this different behavior depending on the + vs. - designation in the gtf file? Both versions detect the same number of splicing junctions in the SJ.out.tab file. We've been giving it 500 GB and tried it with 16 threads, 8 threads, and 1 thread.

Thank you for the help!

Best,
Amber

**Comment by alexdobin** [comment]
Hi Amber,

thanks! Nothing suspicious in the Log.out, so it was probably lack of RAM on the specific nodes.

Cheers
Alex
