### ISSUE TITLE
STARsolo settings for Smart-seq2: trimming

### ISSUE THREAD

**Issue by apredeus** [alexdobin/STAR#1387]
Hi Alex,

I was wondering if `STARsolo` Smart-seq2 processing includes any adapter trimming by default? 

So far I tried to run it like this (would be good to get feedback on this command!): 

```bash 
STAR --runThreadN $CPUS --genomeDir $REF --runDirPerm All_RWX --outSAMtype None \
--outFilterScoreMinOverLread 0.3 --outFilterMatchNminOverLread 0.3 --soloType SmartSeq \
--readFilesManifest $TAG.manifest.tsv --soloUMIdedup Exact --soloStrand Unstranded \
--soloFeatures Gene GeneFull --soloOutFileNames output/ genes.tsv barcodes.tsv matrix.mtx
```

I tried to remove adapters from my reads before running `STARsolo`, but the output of `bbduk` actually performed worse (fewer mapped and fewer uniquely mapped reads), and the output of `trim_galore` have errored out because something it did with the reads (probably non-matching number of R1/R2, or zero length reads, or something like that).

The manual also mentions `--clipAdapterType` option has the default "Hamming" - so does this mean that STAR does some sort of adapter trimming by default? 

Thank you!

**Comment by alexdobin** [comment]
Hi Alex,

there is no trimming by default, but you can switch it on by supplying the 3' adapter sequence:
```--clip3pAdapterSeq <3' adapter sequence>```
But external trimmers (trimgalore, cutadapt, etc) should work as well, but you need to make sure they produce the well-behaved output: no 0-length reads, and consistent read1 / read2 .

Cheers
Alex

**Comment by apredeus** [comment]
Thank you for the clarification, much appreciated!
