### ISSUE TITLE
Count reads per Chromosome

### ISSUE THREAD

**Issue by demis001** [alexdobin/STAR#139]
I have mapped  the reads to the probe sequence without annotation. I don't have the annotation gtf file. Is there anyway, I can count using  STAR count feature before I go to far? 

 I an looking something equivalent to "samtools idxstats *.bam" that summaries the read count per chromosome. Sorry, I am new to STAR , I have used bowtie, bwa and novo align for long time

Thanks

**Comment by alexdobin** [comment]
Hi Dereje,

there is no direct command in STAR to do the "per-reference" counting.
However, you can trick STAR into doing this by creating an artificial annotations (GTF), with "exons" fully covering each of the references, and gene_id and transcript_id attributes being the references' names. Then --quantMode GeneCounts will count the number of reads per reference.
Note that presently STAR only counts unique mappers, while samtools idxstats will count all alignments.

Cheers
Alex

**Comment by demis001** [comment]
Hi Alex,

Thanks, I used "samtools idxstat" in the implementation, and it is sufficient for what I need. I thought it isn't necessary to add additional function if STAR would have that functionality. 

Thank you for the response!
Dereje
