### ISSUE TITLE
STAR & StringTie giving poor BUSCO results

### ISSUE THREAD

**Issue by sjfleck** [alexdobin/STAR#1390]
Hello, I recently used STAR v2.7.9a to generate inputs for StringTie and BRAKER for part of the annotation pipeline for a few plant genomes.

With BRAKER, the resulting protein file had ~86% of complete eudicots_odb10 BUSCOs, so I'm not too concerned there. On the other hand, when I ran StringTie, the resulting transcripts only had ~17% of complete BUSCOS. I would look into StringTie more as the problem, but I also tried HISAT2 & StringTie together and found ~76% of the complete BUSCOs within the transcripts. 

Here are my commands. Let me know if you see where I can improve:

STAR:
STAR --runMode genomeGenerate \
--limitGenomeGenerateRAM 125000000000 \
--runThreadN 16 \
--genomeDir $PWD"/" \
--genomeFastaFiles $GENOME \
--genomeSAindexNbases 10

STAR --runMode alignReads \
--runThreadN 16 \
--readFilesIn $READS1 $READS2 \
--genomeDir $PWD"/" \
--readFilesCommand zcat

SAMTOOLS:
samtools view -o $SAMPLE.bam -Su -@ 16 Aligned.out.sam
samtools sort -u -o $SAMPLE.sorted.bam -O BAM -@ 16 $SAMPLE.bam

STRINGTIE:
stringtie $SAMPLE.sorted.bam -o $SAMPLE.gtf -p 16 -v 

TRANSDECODER:
gtf_genome_to_cdna_fasta.pl $GTF $GENOME > StringTie.HISAT.fasta

Any recommendation would be greatly appreciated. Thank you in advance

**Comment by alexdobin** [comment]
Hi @sjfleck 

it's hard to explain the observations at the end of the pipeline.
I would start by comparing mapping statistics for STAR and HISAT: Number of unique and multimappers, mapped length, error rate. The multimappers can affect strongly the precision of assembled transcripts.
Next, I would look at the detected junctions. Non-canonical junctions may result in spurious transcripts, so it may be helpful to filter them out.

Cheers
Alex

**Comment by sjfleck** [comment]
Thank you for the quick reply. I'm rerunning the job now and will check all those stats when it finishes. 

I actually noticed in the manual that:

--outSAMattrIHstart default: 1. int>=0: start value for the IH attribute. 0 may be required by some downstream software, such as Cuffinks or StringTie.

I'm currently running it with "--outSAMattrIHstart 0" as well as "--outSAMtype BAM SortedByCoordinate" so I don't need to bother running:

samtools view -o $SAMPLE.bam -Su -@ 16 Aligned.out.sam
samtools sort -u -o $SAMPLE.sorted.bam -O BAM -@ 16 $SAMPLE.bam

between STAR and StringTie. I'm hoping that this helps. I'll report ASAP

**Comment by sjfleck** [comment]
I ran STAR again using this command:

STAR --runMode alignReads \
--runThreadN 16 \
--readFilesIn $READS1 $READS2 \
--genomeDir $PWD"/" \
--readFilesCommand zcat \
--outFileNamePrefix $SAMPLE. \
--outSAMattrIHstart 0 \
--outSAMtype BAM SortedByCoordinate

followed by my stringtie command above and I got the exactly same mapping and assembly results. I took a snap shot of the the STAR and HISAT2 mapping stats, but I'm not seeing an obvious issue yet. It looks pretty comparable to the HISAT2 stats.
<img width="689" alt="Screen Shot 2021-11-01 at 10 21 56 PM" src="https://user-images.githubusercontent.com/53409202/139777266-34d22f96-6701-499e-bfb2-8484c88a85f5.png">

I think I'm using the commands correctly and STAR should recognize the reads as paired end. I'll look into filtering junctions, but do you see anything in the mapping stats that might indicate an issue? Thanks

I'll also check with StringTie more to see if this is something on their end.

**Comment by alexdobin** [comment]
Hi @sjfleck 

it looks like STAR outputs more alignments than HISAT2. What filtering is HISAT2 using?
You can try to increase the stringency of the alignments with ```--outFilterScoreMinOverLread 0.95```.

Cheers
Alex

**Comment by sjfleck** [comment]
The only filter I used for HISAT2 was setting the max intron length to 20,000. This might be a little big, but I saw an issue on the Trinity github page where 99.99% all of their plant's introns were within 19,000 bp. 

hisat2 --max-intronlen 20000 -p 16 --dta -x $SAMPLE -1 $READS1A,$READS1B,$READS1C -2 $READS2A,$READS2B,$READS2C -S $SAMPLE.sam

I actually just come across this in the manual "--outSAMstrandField intronMotif". The manual says it's a "Cufflinks-like strand field" but you can't find it by searching "cufflinks". When I copy and paste the text from the PDF I get, "Cu inks-like strand  eld", so maybe that's why I missed it. 

I'm running this new command and if I get poor results again, I'll use "--outFilterScoreMinOverLread 0.95":
STAR --runMode alignReads \
--runThreadN 16 \
--readFilesIn $READS1 $READS2 \
--genomeDir $PWD"/" \
--readFilesCommand zcat \
--outFileNamePrefix $SAMPLE. \
--outSAMstrandField intronMotif \
--outSAMattributes All \
--outSAMattrIHstart 0 \
--outSAMtype BAM SortedByCoordinate

Thanks!

**Comment by sjfleck** [comment]
UPDATE: the last attempt resulted in an improvement (very similar to HISAT2/StringTie results):

C:75.7%[S:39.5%,D:36.2%],F:9.5%,M:14.8%,n:2326
1761 Complete BUSCOs (C)
919 Complete and single-copy BUSCOs (S)
842 Complete and duplicated BUSCOs (D)
221 Fragmented BUSCOs (F)
344 Missing BUSCOs (M)
2326 Total BUSCO groups searched

I'll also try tweaking some parameters to see if I can improve the score. Thanks!
