### ISSUE TITLE
--genomeGenerate fails starting from the .g release on some files

### ISSUE THREAD

**Issue by roryk** [alexdobin/STAR#14]
Hi Alex,

STAR version .g and .h segfaults when building the genome for these two files: https://gist.github.com/roryk/3ddf5590a97114272702 

The .f release works okay, though.

**Comment by alexdobin** [comment]
Hi Rory,

thanks for reporting the problem, I believe I have fixed - please try out the patch I have just pushed to GitHub master. If it works, I will make a tagged release.

Cheers
Alex
