### ISSUE TITLE
Issue with --alignEndsType Extend5pOfRead1

### ISSUE THREAD

**Issue by apaytuvi** [alexdobin/STAR#140]
I am using STAR (2.5.1b) with the following options:

```
--alignEndsType Extend5pOfRead1
--outFilterMismatchNoverLmax 0.05
--outFilterMatchNminOverLread 0
--outFilterScoreMinOverLread" 0
--outFilterMultimapNmax 9999
```

I want all reads with 5% or more mismatches relative to the mapped part of the read filtered (SE data). I attach a figure that shows an example of a read that is miss-placed. It has 21 mismatches at the 5' part of the read! I'm just using `Extend5pOfRead1` to keep the 5' part of the read unclipped and unchanged with very low number or without mismatches.

![screenshot from 2016-04-29 11 38 42](https://cloud.githubusercontent.com/assets/11228225/14912836/2ac62d24-0dff-11e6-91a6-87b679009bdd.png)

**Comment by alexdobin** [comment]
Hi @apaytuvi 

I think the end of the read with 21 mismatches is soft-clipped, your parameters would not allow for so many mismatches.
But, if this is the 5' end of the read1, it should not be soft-clipped.

Could you please extract this alignment from the SAM file and send it to me along with the Log.out file.

Cheers
A;ex

**Comment by apaytuvi** [comment]
Hi @alexdobin 

These are the alignments. That read is a multi-mapper (maps 2 times) but, for me, the first alignment is the valid one. The second alignment is the one I've shown, and has too much mismatches at the 5' non soft-clipped end.
```
SRR2075614.459861	0	7	110116024	3	29M122S	*	0	0	TGCAATTCTGAATTTTGACTAACGAAGCTAGCTTCTATGTGCTCCATCTGTAGCAGGGAGGGTCTCTGTCTCTCTAATTGTTGATTGGCTAGAGTAAGAATGAGCACACCTGTGGTATGACACGTGGTACGGCAGACCTGTCCCATAGGAG	CCCCBFFFFFFFGGGGGGGGGGHGGGGGHHHHHHHHHHHHHHHHHHHHHHHHHHHHHGGGGGGHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHGHHHHHHHHHHHHHHGHHHHHHHHHHHHHGHHGHHHGGGGGGHHHHHHHHHHHHHHH	NH:i:2	HI:i:1	AS:i:28	nM:i:0	RG:Z:1
SRR2075614.459861	256	7	126686310	3	71M80S	*	0	0	TGCAATTCTGAATTTTGACTAACGAAGCTAGCTTCTATGTGCTCCATCTGTAGCAGGGAGGGTCTCTGTCTCTCTAATTGTTGATTGGCTAGAGTAAGAATGAGCACACCTGTGGTATGACACGTGGTACGGCAGACCTGTCCCATAGGAG	CCCCBFFFFFFFGGGGGGGGGGHGGGGGHHHHHHHHHHHHHHHHHHHHHHHHHHHHHGGGGGGHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHGHHHHHHHHHHHHHHGHHHHHHHHHHHHHGHHGHHHGGGGGGHHHHHHHHHHHHHHH	NH:i:2	HI:i:2	AS:i:27	nM:i:21	RG:Z:1
```

**Comment by alexdobin** [comment]
Hi @apaytuvi 

the 2nd alignment with many mismatches at the 5' has the alignment score (AS tag) of 27, within the allowe range (1) of the top score of 28 - this is why STAR outputs it. Presently STAR only checks the number of mismatches (and other filters) only for the top alignment - this why the 2nd alignment is output. I am thinking of coding filters that would apply to all of the multi-mapping alignments. For now, you would need to filter them out manually.

Cheers
Alex

**Comment by apaytuvi** [comment]
Hi @alexdobin 

Thank you for the reply. Is there a way -by modifying the STAR source- to output only those multimappers with the same AS score than the primary alignment? Thus, in my case, since the first alignment has an AS > than the one in the second alignment, only the first one would be output.

**Comment by alexdobin** [comment]
You can do this with 
--outFilterMultimapScoreRange 0
However, it may not solve all the problems, since for some reads (hopefully very few) the multi-alignments may have exactly the same score.

**Comment by apaytuvi** [comment]
Thank you @alexdobin 

How is `AS` calculated? Can I increase the mismatch penalty?

**Comment by alexdobin** [comment]
Good idea, but unfortunately, match/mismatch penalties are hard-coded +/-1 :(
I think I will bite the bullet and implement filtering for all multi-mappers.

**Comment by apaytuvi** [comment]
@alexdobin 

Thanks, it would be great! 

By changing `--maxScore` in line 17 of Transcript_alignScore.cpp couldn't I increase the mismatch penalty?

The last question; is there a way to tune how many bases will map end-to-end and how many bases will align in a local way? I think now half of the read maps end-to-end with the option `--alignEndsType Extend5pOfRead1`.

**Comment by alexdobin** [comment]
> Couldn't I increase the mismatch penalty by changing --maxScore in line 17 of Transcript_alignScore.cpp?

No, it's not the only place where it's hardcoded.

> The last question, for sure: is there a way to tune how many bases will map end-to-end and how many bases will align in a local way?  I think now half of the read maps end-to-end with the option --alignEndsType Extend5pOfRead1.

Not sure I am following your question. with Extend5pOfRead1, only the 5' of the read1 is extended all the way to the end, all other ends are locally aligned, i.e. allow for soft-clipping.

**Comment by apaytuvi** [comment]
Let's give an example. I have some examples where a read of 100bp do not map due to too much mismatches. When I force a clipping of 20nt at the 3' for example, the read maps. Why? The local alignment should prevent those mismatches. I work with Hi-C data and lots of times part of a read comes from a loci and part of the read from another.

Given that behaviour, I suspected that a minimum of X bases are forced to be aligned end to end at the 5' end. You say 5' end is aligned end to end. What is the 5' end, from bases 1 to 10? To 30? When does it change to Local?

**Comment by alexdobin** [comment]
5' in our case simply means the left end of the sequence.
In the Extend* modes the alignment is forced to extend all the way to the end(s).
Otherwise it's local, i.e. it may be soft-clipped to prevent too many mismatches.

Please send me the example of the alignment in question.

**Comment by apaytuvi** [comment]
For example, the read I posted `SRR2075614.459861`. I do an iterative mapping, clipping 20nt from the 3' end with `clip3pNbases`. This read maps in round 5, when I've cut 80nt. Since my reads have 151nt long, the maximum length in round 5 is 71nt. If you see the second alignment, the one with lots of mismatches, it has a length of 71nt. Therefore, it seems that `Extend5pOfRead1` does not work in this case.

**Comment by alexdobin** [comment]
Hi @apaytuvi 

for both alignments of this read STAR does not clip any bases from the 5' (no S before M in the CIGAR). It only clips the bases from the 3' (S at the end of CIGAR).  This is the way the Extend5pOfRead1 option is designed to work.

Cheers
Alex

**Comment by apaytuvi** [comment]
Indeed. For this reason, the read should be mapped in round 1, not when I force clipping X bases 3'...

**Comment by alexdobin** [comment]
Hi @apaytuvi 

I think I see your point now.
The alignment you have shown is with --clip3pNbases 80,
and without this clipping you do not see any alignments at all. Is this what you observe?

Please send me the Log.out file for this run - I need to check all the parameters.

Cheers
Alex

**Comment by apaytuvi** [comment]
Exactly, without this clipping, the read is is unmapped due to too many mismatches. I attach the `Log.out`.
[5Log.out.txt](https://github.com/alexdobin/STAR/files/250678/5Log.out.txt)

**Comment by apaytuvi** [comment]
How is it going, @alexdobin?

**Comment by alexdobin** [comment]
Hi @apaytuvi 

sorry, it slipped my attention. This require a bit of work - will get back to you tomorrow.

Cheers
Alex

**Comment by alexdobin** [comment]
Hi @apaytuvi 

sorry for all the delays. Here is the explanation for your observations:

If you trim 80b, the two aligments have very similar scores, and the best alignment is the one with only 29 bases mapped, and no mismatches, while the 2nd alignment is the one with 71 bases mapped, and 21 mismatches:
1       0       chr7    110116024       3       29M122S *       0       0       * *       NH:i:2  HI:i:1  AS:i:28 nM:i:0
1       256     chr7    126686310       3       71M80S  *       0       0       * *       NH:i:2  HI:i:2  AS:i:27 nM:i:21

If you do not trim 80b, the best alignment is:
1       0       chr7    126686310       255     151M    *       0       0       * *       NH:i:1  HI:i:1  AS:i:107        nM:i:21
with 151b mapped and 21 mismatches. Note, that the alignment score AS=107 >> 28=AS for the  best alignment with trimming - so only one alignment is reported in this case. Note, that to get this alignment, you have to allow large number of mismatches with --outFilterMismatchNmax 9999 - this option was missing from the Log.out file you sent me.

Cheers
Alex

**Comment by apaytuvi** [comment]
Hi @alexdobin ,

thanks for the reply. I still don't understand that. `Extend5pOfRead1` should soft-clip the mismatches at the 3' while keeping the 5' without clipping. This means that 

`1 0 chr7 110116024 3 29M122S * 0 0 * * NH:i:2 HI:i:1 AS:i:28 nM:i:0`

should appear.

**Comment by alexdobin** [comment]
STAR will only report the top alignments according to their alignment scores (AS in the SAM file). The 29M122S alignment has a much lower alignment score than the 151M alignment, even though the former has 0 mismatches and the latter has 21 mismatches. 

You can, in principle, increase the range of the sub-par scored alignments that are output as multimappers by increasing --outFilterMultimapScoreRange. In your case, --outFilterMultimapScoreRange 80 will allow   both alignments. However, for other reads this will lead to output of too many useless sub-par alignments.

Cheers
Alex

**Comment by apaytuvi** [comment]
@alexdobin

Thanks for the explanation. No way no get the best alignment without mismatches (the one with 29M), right?
