### ISSUE TITLE
the exact meaning of genomeSAindexNbases

### ISSUE THREAD

**Issue by linpei26** [alexdobin/STAR#1400]
Hello Alex and everyone!

I wish to ask a simple question: 

What is the exact meaning of the parameter genomeSAindexNbases which is used for building genome index by STAR? 
Thanks!
Best,

Pei

**Comment by alexdobin** [comment]
Hi Pei,

this is the length of the k-mer that's used to "pre-index" the suffix array.
The default (14) works well for the human genome.
For smaller genomes, it needs to be scaled with the length of the genome to avoid long k-mers absent in the genome.

Cheers
Alex

**Comment by linpei26** [comment]
Hi Alex!

So glad to hear from you!
Dose the K-mers work like the word_size in Blastn?
Thank you so much!

Pei

**Comment by linpei26** [comment]
So, dose STAR building index by compressing simple repeat "word" into kmers?
For example, if there is ACGACGACG, then ACG x 3 would be recorded in the index? here K = 3 for the k-mers.

**Comment by alexdobin** [comment]
Hi Pei,

STAR's index is the classic suffix array. The "preindex" specifies positions of the k-mers (defined by --genomeSAindexNbases) in the suffix array. It does not affect accuracy of the search, just the speed.

Cheers
Alex

**Comment by linpei26** [comment]
Hi Alex,
Thank you so much!
You explain quite well!
Best,

Pei
