### ISSUE TITLE
SAM attribute HI

### ISSUE THREAD

**Issue by cherrie-g** [alexdobin/STAR#1402]
Hi, 
There is one thing about multiple alignment I'm wondering. We know the SAM attributes NH and HI indicate multiple alignment atrribute in sam files. And I want to know that, does there any principle of HI index? For example, is it index under some principles that the best alignment in the multiple alignment would be the top? Or it just random indexing? 

Thank you.

**Comment by alexdobin** [comment]
Hi @cherrie-g 

by default, HI index follows the order in which alignments are found, so every time you run STAR with the same parameters, the order will be the same for each read.
If you want to randomize it, you would need to use *--outMultimapperOrder Random* .

Cheers
Alex

**Comment by cherrie-g** [comment]
Thanks a lot.
