### ISSUE TITLE
fatal input ERROR while STAR mapping

### ISSUE THREAD

**Issue by yuyoshid** [alexdobin/STAR#1403]
Hi,
I am trying to use STAR for mapping. I did as below, (single-end)

STAR --runMode alignReads --genomeDir ../001_STAR_index --readFilesIn ../yy001miRNAtrimfile/output_1.fq --outSAMtype BAM SortedByCoordinate --runThreadN 4 --outFileNamePrefix 1output --quantMode TranscriptomeSAM

but I got the message every time,

EXITING because of fatal input ERROR: could not open readFilesIn=../yy001miRNAtrimfile/output_1.fq

Please let me know how to resolve the problem.
Thank you.

Yuko

**Comment by yuyoshid** [comment]
Hi, 
I found my mistake.
I should do ,
STAR --runMode alignReads --genomeDir ../../001_STAR_index --readFilesIn ../../yy001miRNAtrimfile/output_1.fq ,
It works.

Sorry for bothering you,
Thank you very much.

Yuko

**Comment by alexdobin** [comment]
Great! All the best with your analyses!
