### ISSUE TITLE
Using STAR for mouse RNA-seq alignment, which parameters of STAR besides the basic ones would be better to use in practice?

### ISSUE THREAD

**Issue by lkqnaruto** [alexdobin/STAR#1405]
Hi

Currently I have pair-end mouse RNA-seq data. 3 Tissues with 17 samples/tissue. Length of the sequence is from 100bp to 150bp. My goal is to perform DEG after the alignment. This is my first time to use STAR for alignment. I have carefully went through the STAR manual. Besides the basic parameters, I notice there are a lot of more advanced options to do in STAR. So I wonder, in practice, which parameters should I also consider to use? Below is my own set up.

Step 1:
```
                       STAR --runThreadN 12 \
                                 --runMode genomeGenerate \
                                 --genomeDir genomedir \
                                 --genomeFastaFiles ./ref/GRCm39.primary_assembly.genome.fa \
                                 --sjdbGTFfile ./ref/gencode.vM27.primary_assembly.annotation.gtf \
                                 --sjdbOverhang 100
```
Step 2:
```
                       STAR --runThreadN 12 \
                                 --runMode alignReads \
                                 --twopassMode None \
                                 --genomeDir genomedir \
                                 --sjdbGTFfile ref/gencode.vM27.primary_assembly.annotation.gtf \
                                 --sjdbOverhang 100 \
                                 --readFilesIn "R1_001_trim.fastq.gz" "R2_001_trim.fastq.gz" \
                                 --readFilesCommand zcat \
                                 --outFileNamePrefix "./align_output/try1_" \
                                 --outSAMtype BAM SortedByCoordinate \
```
Which other parameters do you think I should use? may be set "twopassMode" to "basic"? I saw mamy people doing that. Thanks in advance!

**Comment by alexdobin** [comment]
Hi @lkqnaruto 

the default parameters are typically good for an initial run. Then, if you see issues with the mapping (e.g. looking at the Log.final.out file), you can tweak the parameters.
*--twopassMode Basic* indeed improves the sensitivity of alignments, especially those with novel splices, but it might be an overkill for the standard DGE analysis.

Some parameters that maybe worth tweaking are listed below with brief explanations. They are used in ENCODE bulk RNA-seq pipelines:
```
--outFilterType                  BySJout    //reduces the number of "spurious" junctions
--outFilterMultimapNmax          20         //max number of multiple alignments allowed for a read: if exceeded, the read is consi>
--alignSJoverhangMin             8          //min overhang for unannotated junctions
--alignSJDBoverhangMin           1          //min overhang for annotated junctions
--outFilterMismatchNmax          999        //max number of mismatches per pair (absolute)
--outFilterMismatchNoverLmax     0.06       //max number of mismatches per pair relative to read length: for 2x100b, max number of>
--alignIntronMin                 20         //min intron
--alignIntronMax                 1000000    //max intron
--alignMatesGapMax               1000000    //max genomic distance between pairs
```

Cheers
Alex

**Comment by lkqnaruto** [comment]
> Hi @lkqnaruto
> 
> the default parameters are typically good for an initial run. Then, if you see issues with the mapping (e.g. looking at the Log.final.out file), you can tweak the parameters. _--twopassMode Basic_ indeed improves the sensitivity of alignments, especially those with novel splices, but it might be an overkill for the standard DGE analysis.
> 
> Some parameters that maybe worth tweaking are listed below with brief explanations. They are used in ENCODE bulk RNA-seq pipelines:
> 
> ```
> --outFilterType                  BySJout    //reduces the number of "spurious" junctions
> --outFilterMultimapNmax          20         //max number of multiple alignments allowed for a read: if exceeded, the read is consi>
> --alignSJoverhangMin             8          //min overhang for unannotated junctions
> --alignSJDBoverhangMin           1          //min overhang for annotated junctions
> --outFilterMismatchNmax          999        //max number of mismatches per pair (absolute)
> --outFilterMismatchNoverLmax     0.06       //max number of mismatches per pair relative to read length: for 2x100b, max number of>
> --alignIntronMin                 20         //min intron
> --alignIntronMax                 1000000    //max intron
> --alignMatesGapMax               1000000    //max genomic distance between pairs
> ```
> 
> Cheers Alex

So should I set ``--twopassMode`` to None?

**Comment by alexdobin** [comment]
*--twopassMode None* is the default option, so you do not have to set it explicitly.

**Comment by lkqnaruto** [comment]
> _--twopassMode None_ is the default option, so you do not have to set it explicitly.

Thank you for the reply, and happy holidays!
