### ISSUE TITLE
Compact genome settings

### ISSUE THREAD

**Issue by francicco** [alexdobin/STAR#1413]
Hi,

Some times ago I was trying to figure out the best parameter to run Mikado for small insect genomes where intergenic space is very small. I'm asking that because these annotations tend to fuse nearby genes together. I think you guys started to impelent somemthing. Is there any update regarding it?

Cheers
Francesco

**Comment by alexdobin** [comment]
Hi Francesco,

not sure if I can answer this question...
Mikado is not affiliated with STAR.
Overlapping transcripts create problems for gene quantification in general.
There are some ideas out there to prune or combine overlapping transcripts, but I cannot point out anything specific.

Cheers
Alex

**Comment by francicco** [comment]
sorry my bad, I two pages opened at the same time. you can delete it!!!
: )
F
