### ISSUE TITLE
Mapping speed rate abnormally slow

### ISSUE THREAD

**Issue by MelanieP25** [alexdobin/STAR#1414]
Hi,

I use STAR for years but recently I had a problem of mapping speed rate. I’m trying to map paired-end reads on mouse genome (GRCm38). The mapping speed rate is about 1-2 M reads / hour instead of 50-100 M reads / hour usually. I have 27 samples, meaning it will take several weeks. I tried several things including re-run old reads from a previous experiment on the exact same genome with the exact same command line and with those reads, the mapping speed rate is about 50 M/reads. I looked at the logs for the sample that is already done and everything seems okay. I have read a similar issue published 1 year ago, I don’t know if, by now, you have an explanation ?
Btw, I’m working on a distant server with 1T RAM and 64 CPUs.
I thank you for your time and I attached the log files:
[F_KO93Log.final.out.txt](https://github.com/alexdobin/STAR/files/7635246/F_KO93Log.final.out.txt)
[F_KO93Log.out.txt](https://github.com/alexdobin/STAR/files/7635247/F_KO93Log.out.txt)
[F_KO93Log.progress.out.txt](https://github.com/alexdobin/STAR/files/7635248/F_KO93Log.progress.out.txt)

Mélanie

**Comment by alexdobin** [comment]
Hi Mélanie

the parameters and mapping stats look good...
Could you try to map untrimmed reads - to check that trimming did not introduce any issues?
If it does not help, please send me ~1M reads for testing.

Cheers
Alex

**Comment by MelanieP25** [comment]
Hi Alex,

I also suspected the trimming step so I already tried to map the raw reads but the problem is still the same.
Here is a link with a subset of my reads:
https://we.tl/t-a33v6kNFLz

Thank you for your time.
Cheers,
Mélanie

**Comment by alexdobin** [comment]
Hi Mélanie

thanks! I confirmed that the mapping speed is unusually slow for these reads. I am investiagting what's causing it.

Cheers
Alex

**Comment by MelanieP25** [comment]
Hi Alex,

Thanks a lot ! Let me know if you find the cause.

Cheers,
Mélanie

**Comment by alexdobin** [comment]
Hi Mélanie

the slowdown is caused by one locus - Tnnt3 gene, which has very small exons and appears to be highly expressed in your data.
You can increase the speed by reducing *--seedPerWindowNmax*: with 30, the speed increase by a factor of ~10, and with 20 by ~40. The latter is close to the normal mapping speed. This will reduce the mapping sensitivity: you will loose 0.1% of mapped reads with 20, and ~1% with 30.

Cheers
Alex

**Comment by MelanieP25** [comment]
Hi Alex,

Thanks a lot ! I would never have suspected something like that ! Indeed, with _--seedPerWindowNmax_ it works much better.
Thank you for the time you spent on that.

Cheers,
Mélanie
