### ISSUE TITLE
STAR only detect 7 out of 136050 input reads

### ISSUE THREAD

**Issue by Michandr** [alexdobin/STAR#1417]
Hello,

I'm trying to align a fasta file with 136050 reads to a gff-annotated genome. The job runs, and there are no errors. I have all expected output files. The Log.out file says the code ran to completion. However, when I look at the Log.final.out file, STAR only read in 7 input reads. 

1. I've seen that some other people have had this problem when upstream programs accidentally entered blank lines in the middle of their fastq files, but I do not detect any blank lines in my fasta file. Are there any other formatting errors to look out for that might prematurely truncate STAR's reading of input reads? I've tried reformatting my fasta headers to no effect so I don't think it's the fasta headers.
2. I've checked around the 7th read in my fasta file, and just by eye I don't detect anything wrong. Does STAR read the fasta file in order?  

![image](https://user-images.githubusercontent.com/63808273/144672526-803906bb-82da-42f1-babd-6a2c92dcd2c0.png)

**Comment by alexdobin** [comment]
Hi Michandr

you are mapping FASTQ files, not FASTA files, right?
It is likely to the formatting of the FASTQ file is corrupted.
You can try to download FASTQs from SRA and check if you can map them.

Cheers
Alex

**Comment by Michandr** [comment]
I am mapping FASTA files. I wanted to validate a de novo assembly by mapping against a genome.

**Comment by alexdobin** [comment]
Hi @Michandr 

these "reads" are probably long, so you would need to use STARlong executable.
Also, other aligners such as GMAP or minimap2 may be more suitable for long reads.

Cheers
Alex
