### ISSUE TITLE
std::out_of_range in STARsolo when using custom barcode and UMI length and BAM input

### ISSUE THREAD

**Issue by zburkett** [alexdobin/STAR#1420]
I'm trying to re-map reads using STARsolo that were previously aligned to a reference genome. When adding the following params: `--soloBarcodeReadLength 0 --soloCBlen 8 --soloUMIlen 6`, the latter two which reflect the length of the XZ (Cell barcode) and UB (UMI) tags, I'm getting an out of range error:

```
Dec 07 20:38:35 ..... started STAR run
Dec 07 20:38:35 ..... loading genome
Dec 07 20:38:46 ..... started mapping
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr
Aborted (core dumped)
```

Below is the full command to run the program:
```
STAR --genomeDir /mnt/ref_data/hg38-mm10/STAR-2.7.9a/ \
      --soloType CB_UMI_Simple \
      --readFilesType SAM SE \
      --readFilesIn reannotated.bam \
      --soloCBwhitelist None \
      --readFilesSAMattrKeep None \
      --readFilesCommand samtools view -F 0x100 \
      --outSAMtype BAM SortedByCoordinate \
      --soloInputSAMattrBarcodeSeq XZ UB \
      --soloInputSAMattrBarcodeQual YZ UZ \
      --outSAMattributes NH HI nM AS CR UR CB UB GX GN sS sQ sM \
      --runThreadN $(nproc) \
      --soloBarcodeReadLength 0 \
      --soloCBlen 8 \
      --soloUMIlen 6 
```
Any guidance on how to proceed?

**Comment by alexdobin** [comment]
Hi @zburkett 

you also need to specify ```--soloUMIstart```, the 1st base of the UMI in the barcode sequence, which should be 15 in your case.

Cheers
Alex

**Comment by zburkett** [comment]
Thanks Alex, don't know how I managed to overlook that. Closing issue!
