### ISSUE TITLE
STARsolo --soloUMIdedup for paired-end alignment

### ISSUE THREAD

**Issue by camelest** [alexdobin/STAR#1421]
Hi, first of all, thank you so much for this wonderful tool.

I'm trying STARsolo on 10x Chromium 5'-scRNA-seq, which carries CB and UMI (+ partially cDNA) in R1 and wondering how --soloUMIdedup works in paired-end alignment. 

More specifically, 
(1) does STARsolo collapse reads based on 
1. all of the CB, UMI, R1 position and R2 position or
2. CB, UMI and R1 position or
3. CB, UMI and R2 position ?

(2) Does this differ when we specify different --soloUMIdedup options?  Especially for 1MM_All, 1MM_Directional_UMItools and 1MM_CR, are there any differences? I think for the original UMI-tools, the default works without --paired-end option. Is this option turn on in 1MM_Directional_UMItools?

(3) Does this differ when we use --soloBarcodeMate 1 (as we need to do in 5'-scRNA-seq)?

Thank you so much for your help.

**Comment by alexdobin** [comment]
Hi @camelest 

the Solo deduplication is based solely on UMI sequences: reads with <=1mismatch in UMIs are collapsed.
It does not take into account at alignment coordinates.

Cheers
Alex

**Comment by camelest** [comment]
Hi, @alexdobin, thank you so much for your clarification. 

Just one more thing to confirm, then basically these --soloUMIdedup options don't really change the bam file itself, but only change the UB tags in the bam and the count matrix. Is this understanding correct?

**Comment by alexdobin** [comment]
Hi @camelest 

(1)
the 1MM_Directional_UMItools uses the "Directional" UMI collapsing scheme from the UMItools, but it is not designed to work as UMItools "dedup" option.

1MM_CR option is designed to match (as close as possible) the CellRanger UMI collapsing. The UMI collapsing indeed happens within UMIs with the same CellBarcode and gene assignment.

(2)
Indeed, UMI collapsing options only add the "corrected" UB sequence and affect the counts in the matrix.mtx.

Cheers
Alex

**Comment by camelest** [comment]
Hi, @alexdobin 

Thank you so much for your quick response and detailed explanation.

Best,

**Comment by camelest** [comment]
So sorry to bother you, @alexdobin 

One more thing to clarify, by "the 1MM_Directional_UMItools uses the "Directional" UMI collapsing scheme", do you mean we could expect STARsolo with this option to group reads in the same way as UMI-tools, but the choice of the representative reads and the collapsing (as performed in dedup) is not performed?

Thank you again for your help.

Best,

**Comment by alexdobin** [comment]
Hi @camelest 

this option implements UMI collapsing algorithm similar to the UMI-tools "directional" algorithm described in the UMI-tools paper. This algorithm does not rely on alignment coordinates, just UMI sequences. It includes the selection of the "representative" UMI sequence. I am not sure how it relates to the UMI-tool collapsing based on alignment coordinates.

Cheers
Alex

**Comment by camelest** [comment]
Hi @alexdobin,

thank you so much for your multiple kind help. I will look into it more on some sample data.
Thank you again for your help.

**Comment by ColeWunderlich** [comment]
Hey Alex,

Just to clarify, is `1MM_All` collapsing per-gene/locus (within a CB) or per-CB (not caring about gene assignment)?  My understanding was it is per-gene, where exact alignment location doesn't matter but aligning to a given gene does.

**Comment by alexdobin** [comment]
Hi Cole,

1MM_All will look at all UMIs with the same CB and gene, and collapse those that differ by <=1 mismatch.
An arbitrary UMI sequence is selected to represent all UMI that are collapsed.
