### ISSUE TITLE
STAR gives nondeterministic and incorrect ordering of unsorted outputs

### ISSUE THREAD

**Issue by tgbrooks** [alexdobin/STAR#1423]
I am experiencing a problem where STAR gives inconsistent and incorrect alignment ordering in the output bam files. I am running using the options ` --outSAMtype BAM   Unsorted  --outSAMunmapped Within   KeepPairs` so I expect the output reads to be the same order as the input fastq files. However, that was not the case for some of my files. I then tried rerunning STAR and found that its output is inconsistent and does not always yield the same results. I believe that this is not intended behavior, though perhaps I am running something improperly.

I have attached the results of two runs of STAR v2.7.9a: the log files as well as output of `samtools view Aligned.out.bam | head -n 100`. The first of the runs is in the expected order, the second one is not. I first noticed this on STAR v2.7.6a.

I was unable to reproduce this problem using a smaller fastq file of just 10,000 lines: running STAR 10 times on these files all gave the same results and in the expected order. My full fastq files are quite large so I have not shared them, but if they are necessary, please let me know and I will find a way to get them to you. For now, I have shared those first 10,000 lines of the fastq files too.

[STAR_test.zip](https://github.com/alexdobin/STAR/files/7707454/STAR_test.zip)

**Comment by alexdobin** [comment]
Hi Thomas,

*--outSAMunmapped Within KeepPairs* only guarantees that mates (read1/read2) are output next to each other.
It does not keep the order of the output reads the same as in the input file.
The order cannot be kept unless you use only one thread.

Cheers
Alex

**Comment by tgbrooks** [comment]
Hi Alex,

Thank you for the clarification.
