### ISSUE TITLE
Can I make STARsolo report if 10x TSO is detected?

### ISSUE THREAD

**Issue by ms-gx** [alexdobin/STAR#1427]
Is there an option to make STARsolo report via a flag, that a 10x TSO was detected? Did not find anything, but asking to make sure.

I am talking about the case were I use: `--clipAdapterType CellRanger4`

**Comment by alexdobin** [comment]
Hi Michael,

you cad *cN* tag to the list of SAM tags in *--outSAMattributes*. It will output the number of bases clipped from the 5' (TSO) and 3' (polyA).

Cheers
Alex
