### ISSUE TITLE
FATAL INPUT ERROR: empty value for parameter "readFilesIn" in input "Command-Line"

### ISSUE THREAD

**Issue by TSolDour** [alexdobin/STAR#1433]
Hello Alex, 

I have some problems running STAR in a PBS Job array mode, to align reads.fastq against a reference genome.

My PBS script is as follow : 

---------------------------------------------------------------------------------------------------------------------------------
#!/usr/bin/env bash
#PBS -N STAR-alignment-array
#PBS -q omp
#PBS -l walltime=72:00:00
#PBS -l ncpus=10
#PBS -l mem=800g
#PBS -J 1-96

#This script uses to align reads against reference genome.

#Activate STAR's conda environment:
. /appli/bioinfo/star/2.7.9a/env.sh

#To get log out in the script's directory:
cd ${PBS_O_WORKDIR}

# Path to store genome indices:
GENOMEDIR=$SCRATCH/Star_indices

# Path to fasta files to be mapped:
R1=$(ls /home1/datawork/tsoldour/PESTO_RNAseq/raw-Data/*_R1_001.fastq.gz | awk "NR==${PBS_ARRAY_INDEX}")
R2=$(ls /home1/datawork/tsoldour/PESTO_RNAseq/raw-Data/*_R2_001.fastq.gz | awk "NR==${PBS_ARRAY_INDEX}")

# Running STAR alignment :
STAR --runThreadN 4 --runMode alignReads \
--genomeDir $GENOMEDIR \
--readFilesCommand zcat \
--readFilesIn $R1 $R2 \
--quantMode GeneCounts \
--outSAMtype BAM Unsorted SortedByCoordinate \
--outReadsUnmapped Fastx &> ${PBS_JOBNAME}.e${PBS_JOBID%.*} 2>&1

-----------------------------------------------------------------------------------------------------------------------------------

I guess my script is quite good, but the job killed with this error message in the Log.out : 
"FATAL INPUT ERROR: empty value for parameter "readFilesIn" in input "Command-Line"" 

I don't understand what the problem is because "redFilesIn" isn't empty... 

Please, do you have an idea to help myself ?

Thank you ! 

Thomas.

**Comment by alexdobin** [comment]
Hi Thomas,

all STAR parameters should be on one line. You can use line continuation symbols \
to break up the line, but you need to be careful not to put spaces or other characters after it:

```
STAR --runThreadN 4 --runMode alignReads \
--genomeDir $GENOMEDIR \
--readFilesCommand zcat \
--readFilesIn $R1 $R2 \
--quantMode GeneCounts \
--outSAMtype BAM Unsorted SortedByCoordinate \
--outReadsUnmapped Fastx &> ${PBS_JOBNAME}.e${PBS_JOBID%.*} 2>&1
```
Cheers
Alex

**Comment by TSolDour** [comment]
Hi Alex, 
Thank you for your answer. 
I actually used line continuation symbols. I don't know why they didn't appear when I copy/paste the script from my text editor to github, but they are there ! Thus, I don't think the problem comes from it.

Perhaps seeing the entire Log.out might help ?

------------------------------------------------------------------------------------------------------------
STAR version=2.7.9a
STAR compilation time,server,dir=2021-05-04T09:43:56-0400 vega:/home/dobin/data/STAR/STARcode/STAR.master/source
##### Command Line:
STAR --runThreadN 4 --runMode alignReads --genomeDir /home1/scratch/tsoldour/Star_indices --readFilesCommand zcat --readFilesIn --quantMode GeneCounts --outSAMtype BAM Unsorted SortedByCoordinate --outReadsUnmapped Fastx
##### Initial USER parameters from Command Line:
###### All USER parameters from Command Line:
runThreadN                    4     ~RE-DEFINED
runMode                       alignReads        ~RE-DEFINED
genomeDir                     /home1/scratch/tsoldour/Star_indices     ~RE-DEFINED
readFilesCommand              zcat        ~RE-DEFINED

EXITING: FATAL INPUT ERROR: empty value for parameter "readFilesIn" in input "Command-Line"
SOLUTION: use non-empty value for this parameter

Jan 01 13:58:06 ...... FATAL ERROR, exiting
----------------------------------------------------------------------------------------------------------------

Or maybe the job array configuration is wrong, but I don't know if you know how it works ?

Thank you,
Thomas.

**Comment by alexdobin** [comment]
Hi Thomas,

checking Log.out is always a good idea, starting with the Command Line - this is what STAR sees as the command line.
In this case ```--readFilesIn``` has empty values, which means that $R1 and $R2 were not defined in your script.

Cheers
Alex

**Comment by TSolDour** [comment]
Hi Alex, 

It was actually a synthax error... The probleme is solved. 

Thanks for your help !
Thomas.
