### ISSUE TITLE
Question about clip3pAdapterSeq

### ISSUE THREAD

**Issue by haydensun** [alexdobin/STAR#1435]
Hi Alex,
I'm using STAR 2.7.9a with `--clip3pAdapterSeq polyA` to trim polyA tails since my library is 3' RNA-seq and 10%-20% of the total reads contains variable polyA length

I just want to make sure that  if a read contains RNA sequences, polyA tails and other remaining sequence after polyA (i.e. 50bp RNA sequence + 80bp polyA + 20bp remaining sequence), will this kind of `polyA + remaining sequence` also be trimmed?  Or controlled by `clip3pAdapterMMp`?

Thanks for your time!

**Comment by alexdobin** [comment]
Hi Hongduo,

no, ```--clip3pAdapterSeq polyA``` will only trim sequences that end with poly-A tails.
If you want to trim stretches of As as in your example, simply use ```--clip3pAdapterSeq AAAAAAAAAAAAAAA``` and adjust the number of As according to the length of polyA sequencein your adapter - in your example it's 80, though I would make it a bit shorter, say 60 or 70 to account for possible deletions.

Cheers
Alex

**Comment by haydensun** [comment]
Hi Alex,
Thanks for the explanation, the length of polyA in my data is quite dispersed and I guess I have to specify `--clip3pAdapterSeq polyA`  to remove them as long as possible.  

If adapter trimming in STAR is anchored at 3',  can I increase `clip3pAdapterMMp`  a little bit (e.g. 0.15-0.2) to remove `polyA + non poly-A` together? Will the non poly-A sequence be regraded as mismatches if their relative lengths satisfying the cutoff?

Thank you so much for your kind help!

**Comment by alexdobin** [comment]
Hi Hongduo,

yes, any non-A bases will be counted as mismatches, so if you use ```--clip3pAdapterMMp 0.2```, it can trim, for instance, 50A+10nonA sequences.

Cheers
Alex

**Comment by haydensun** [comment]
It really helps, thanks so much!
