### ISSUE TITLE
Question about multimappers in single-cell data

### ISSUE THREAD

**Issue by bvaldebenitom** [alexdobin/STAR#1438]
Dear Alex and STAR team,

I'm testing the multimapper options implemented in STAR 2.7.9a, and have a couple of questions:
1. According to the [STARsolo manual](https://github.com/alexdobin/STAR/blob/master/docs/STARsolo.md#multi-gene-reads), there are four options to handle multimapping reads, and "_any combination of these options can be specified_". In turn, this generates one file per method indicated with the `--soloMultiMappers`. Do these options only affect results at the count level (i.e., only the Mtx files), or does the BAM file changes at all? I'm curious as there is still only one BAM file generated. 
2. If there are changes in the BAM files, is there any specific tag to look for?
3. Do these options work for bulk RNA-Seq data?

Thanks in advance!

**Comment by alexdobin** [comment]
Hi @bvaldebenitom 

1. The BAM file is not affected, as Solo counting does not affect the alignments. 
2. New SAM tags (gx/gn) can be used for multi-gene reads, which will list the gene id/name for multi-gene reads, unlike GX/GN tags that only work for unique-gene reads. You would need to use this branch to try this option: https://github.com/alexdobin/STAR/tree/dev_ExonOverIntron
3. No, Solo options only work for single-cell data. In principle, you can hack it to work for bulk RNA-seq data by assigning faux cell barcode and UMI to all reads, and using ```--soloUMIdedup NoDedup``` option.

Cheers
Alex

**Comment by bvaldebenitom** [comment]
Thanks for the informative reply @alexdobin. Everything clear now. 

Thanks for releasing v2.7.10.a!!!
