### ISSUE TITLE
Jobs keep getting 'Killed' unsure why

### ISSUE THREAD

**Issue by JCSzamosi** [alexdobin/STAR#1439]
I'm running STAR 2.7.9a on Ubuntu 20.04 with 12 cores and 32GB of RAM available (plus a 2GB swap file which I should probably increase). I'm telling STAR to use 8 threads.

I'm mapping a pretty large number (~100M) of 100bp paired-end reads to the mouse genome, and each time the job ends before it's finished and the only message it gives is "Killed". Exactly where in the job it is when that happens can vary, but it never says anything more informative. My guess is that it's dying because it's running out of RAM. Is there a way for me to limit its RAM use? Or is something else causing this? Examples of my code and the output are given below. Many thanks!

Calling STAR:
```
STAR --runThreadN 8 \
		--genomeDir $ref \
		--readFilesIn $R1 $R2 \
		--readFilesCommand gunzip -c \
		--sjdbGTFfile $gtf \
		--sjdbOverhang 49 \
		--outFilterMultimapNmax 20 \
		--alignSJoverhangMin 8 \
		--outFilterMismatchNmax 999 \
		--outFilterMismatchNoverReadLmax 0.04 \
		--alignIntronMin 20 \
		--alignIntronMax 1000000 \
		--alignMatesGapMax 1000000 \
		--alignSJDBoverhangMin 1 \
		--outFileNamePrefix $outdir/$sample/ \
		--outSAMtype BAM SortedByCoordinate \
		--peOverlapMMp 0.1 \
```

STAR output:

```
	STAR version: 2.7.9a   compiled: 2021-05-04T09:43:56-0400 vega:/home/dobin/data/STAR/STARcode/STAR.master/source
Jan 05 06:40:21 ..... started STAR run
Jan 05 06:40:21 ..... loading genome
Jan 05 06:50:56 ..... processing annotations GTF
Jan 05 06:51:27 ..... inserting junctions into the genome indices
./scripts/02_map.sh: line 17: 1650913 Killed
```

There's nothing in the script on line 17 that could possibly cause this. It's just the `done` line in the for loop that's calling STAR.

**Comment by alexdobin** [comment]
Hi @JCSzamosi 

this looks like not-enough-RAM problem.
Since the process breaks at the step of inserting the junctions into the genome, the first thing to try is to add ```--sjdbGTFfile $gtf --sjdbOverhang 49``` parameters at the genome generation step and remove them from the mapping step.

Cheers
Alex

**Comment by JCSzamosi** [comment]
RAM definitely seems to be the problem. I added those lines to the genome generation step, and then it started dying.
```
Jan 11 11:16:48 ... starting to generate Genome files
Jan 11 11:17:39 ..... processing annotations GTF
Jan 11 11:18:08 ... starting to sort Suffix Array. This may take a long time...
Jan 11 11:18:27 ... sorting Suffix Array chunks and saving them to disk...
./scripts/index_genome.sh: line 20: 608389 Killed                  STAR --runThreadN 10 --runMode genomeGenerate --sjdbGTFfile $gtf --sjdbOverhang 49 --genomeDir $out --genomeFastaFiles $ref
```
Do I have any options here other than finding a machine with more RAM?

Thanks again!

**Comment by JCSzamosi** [comment]
I see that I can limit RAM requirements with `--genomeSAsparseD`, but I'm not sure what scale that operates on. Should I set it to 2? 10? 100? What counts as a "large" value?

**Comment by alexdobin** [comment]
Hi @JCSzamosi 

This is indeed the right parameter to reduce RAM consumption, I think ```--genomeSAsparseD 2``` should be sufficient to in your case.

Cheers
Alex

**Comment by JCSzamosi** [comment]
This did fix the problem! I was able to re-generate the genome and map the reads. Thank you!
