### ISSUE TITLE
"--outSAMorder PairedKeepInputOrder" does not work with "--runThreadN"

### ISSUE THREAD

**Issue by jiwoongbio** [alexdobin/STAR#144]
It generates "Segmentation fault".

**Comment by alexdobin** [comment]
Hi Jiwoong,

please send me the Log.out file of the failed run.

Cheers
Alex

**Comment by jiwoongbio** [comment]
Hi Alex,

Thanks for your quick response.
I am not sure that this reply can reach to you and it includes the attached
file, "Log.out.txt".
- Because the file is too big to put the content into the github page, so I
try to share the file using this mail.
I hope this mail and the attachment work.
Thanks.

Best Regards,
Jiwoong


On Tue, May 3, 2016 at 4:42 PM, alexdobin <notifications@github.com> wrote:

> Hi Jiwoong,
>
> please send me the Log.out file of the failed run.
>
> Cheers
> Alex
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/alexdobin/STAR/issues/144#issuecomment-216673763>
>

STAR version=STAR_2.5.1b_modified
STAR compilation time,server,dir=Tue May 3 01:15:16 CDT 2016 bronco.swmed.edu:/home/jiwoongbio/src/STAR/source
##### DEFAULT parameters:
versionSTAR                       20201
versionGenome                     20101   20200   
parametersFiles                   -   
sysShell                          -
runMode                           alignReads
runThreadN                        1
runDirPerm                        User_RWX
runRNGseed                        777
genomeDir                         ./GenomeDir/
genomeLoad                        NoSharedMemory
genomeFastaFiles                  -   
genomeSAindexNbases               14
genomeChrBinNbits                 18
genomeSAsparseD                   1
genomeSuffixLengthMax             18446744073709551615
readFilesIn                       Read1   Read2   
readFilesCommand                  -   
readMatesLengthsIn                NotEqual
readMapNumber                     18446744073709551615
readNameSeparator                 /   
inputBAMfile                      -
bamRemoveDuplicatesType           -
bamRemoveDuplicatesMate2basesN    0
limitGenomeGenerateRAM            31000000000
limitIObufferSize                 150000000
limitOutSAMoneReadBytes           100000
limitOutSJcollapsed               1000000
limitOutSJoneRead                 1000
limitBAMsortRAM                   0
limitSjdbInsertNsj                1000000
outTmpDir                         -
outTmpKeep                        None
outStd                            Log
outReadsUnmapped                  None
outQSconversionAdd                0
outMultimapperOrder               Old_2.4
outSAMtype                        SAM   
outSAMmode                        Full
outSAMstrandField                 None
outSAMattributes                  Standard   
outSAMunmapped                    None   
outSAMorder                       Paired
outSAMprimaryFlag                 OneBestScore
outSAMreadID                      Standard
outSAMmapqUnique                  255
outSAMflagOR                      0
outSAMflagAND                     65535
outSAMattrRGline                  -   
outSAMheaderHD                    -   
outSAMheaderPG                    -   
outSAMheaderCommentFile           -
outBAMcompression                 1
outBAMsortingThreadN              0
outSAMfilter                      None   
outSAMmultNmax                    18446744073709551615
outSAMattrIHstart                 1
outSJfilterReads                  All
outSJfilterCountUniqueMin         3   1   1   1   
outSJfilterCountTotalMin          3   1   1   1   
outSJfilterOverhangMin            30   12   12   12   
outSJfilterDistToOtherSJmin       10   0   5   10   
outSJfilterIntronMaxVsReadN       50000   100000   200000   
outWigType                        None   
outWigStrand                      Stranded   
outWigReferencesPrefix            -
outWigNorm                        RPM   
outFilterType                     Normal
outFilterMultimapNmax             10
outFilterMultimapScoreRange       1
outFilterScoreMin                 0
outFilterScoreMinOverLread        0.66
outFilterMatchNmin                0
outFilterMatchNminOverLread       0.66
outFilterMismatchNmax             10
outFilterMismatchNoverLmax        0.3
outFilterMismatchNoverReadLmax    1
outFilterIntronMotifs             None
clip5pNbases                      0   
clip3pNbases                      0   
clip3pAfterAdapterNbases          0   
clip3pAdapterSeq                  -   
clip3pAdapterMMp                  0.1   
winBinNbits                       16
winAnchorDistNbins                9
winFlankNbins                     4
winAnchorMultimapNmax             50
scoreGap                          0
scoreGapNoncan                    -8
scoreGapGCAG                      -4
scoreGapATAC                      -8
scoreStitchSJshift                1
scoreGenomicLengthLog2scale       -0.25
scoreDelBase                      -2
scoreDelOpen                      -2
scoreInsOpen                      -2
scoreInsBase                      -2
seedSearchLmax                    0
seedSearchStartLmax               50
seedSearchStartLmaxOverLread      1
seedPerReadNmax                   1000
seedPerWindowNmax                 50
seedNoneLociPerWindow             10
seedMultimapNmax                  10000
alignIntronMin                    21
alignIntronMax                    0
alignMatesGapMax                  0
alignTranscriptsPerReadNmax       10000
alignSJoverhangMin                5
alignSJDBoverhangMin              3
alignSJstitchMismatchNmax         0   -1   0   0   
alignSplicedMateMapLmin           0
alignSplicedMateMapLminOverLmate    0.66
alignWindowsPerReadNmax           10000
alignTranscriptsPerWindowNmax     100
alignEndsType                     Local
alignSoftClipAtReferenceEnds      Yes
alignEndsProtrude                 0   ConcordantPair   
chimSegmentMin                    0
chimScoreMin                      0
chimScoreDropMax                  20
chimScoreSeparation               10
chimScoreJunctionNonGTAG          -1
chimJunctionOverhangMin           20
chimOutType                       SeparateSAMold
chimFilter                        banGenomicN   
chimSegmentReadGapMax             0
sjdbFileChrStartEnd               -   
sjdbGTFfile                       -
sjdbGTFchrPrefix                  -
sjdbGTFfeatureExon                exon
sjdbGTFtagExonParentTranscript    transcript_id
sjdbGTFtagExonParentGene          gene_id
sjdbOverhang                      100
sjdbScore                         2
sjdbInsertSave                    Basic
quantMode                         -   
quantTranscriptomeBAMcompression    1
quantTranscriptomeBan             IndelSoftclipSingleend
twopass1readsN                    18446744073709551615
twopassMode                       None
##### Command Line:
/home/jiwoongbio/src/STAR/source/STAR --runMode alignReads --genomeDir /home/jkim23/reference/STAR/hg19 --readFilesIn sample.QC/sample.1.fastq.gz_filtered.gz sample.QC/sample.2.fastq.gz_filtered.gz --runThreadN 16 --readFilesCommand zcat --outFileNamePrefix sample.STAR/ --twopassMode Basic --outSAMorder PairedKeepInputOrder
##### Initial USER parameters from Command Line:
outFileNamePrefix                 sample.STAR/
###### All USER parameters from Command Line:
runMode                       alignReads     ~RE-DEFINED
genomeDir                     /home/jiwoongbio/reference/STAR/hg19     ~RE-DEFINED
readFilesIn                   sample.QC/sample.1.fastq.gz_filtered.gz   sample.QC/sample.2.fastq.gz_filtered.gz        ~RE-DEFINED
runThreadN                    16     ~RE-DEFINED
readFilesCommand              zcat        ~RE-DEFINED
outFileNamePrefix             sample.STAR/     ~RE-DEFINED
twopassMode                   Basic     ~RE-DEFINED
outSAMorder                   PairedKeepInputOrder     ~RE-DEFINED
##### Finished reading parameters from all sources

##### Final user re-defined parameters-----------------:
runMode                           alignReads
runThreadN                        16
genomeDir                         /home/jiwoongbio/reference/STAR/hg19
readFilesIn                       sample.QC/sample.1.fastq.gz_filtered.gz   sample.QC/sample.2.fastq.gz_filtered.gz   
readFilesCommand                  zcat   
outFileNamePrefix                 sample.STAR/
outSAMorder                       PairedKeepInputOrder
twopassMode                       Basic

-------------------------------
##### Final effective command line:
/home/jiwoongbio/src/STAR/source/STAR   --runMode alignReads   --runThreadN 16   --genomeDir /home/jkim23/reference/STAR/hg19   --readFilesIn sample.QC/sample.1.fastq.gz_filtered.gz   sample.QC/sample.2.fastq.gz_filtered.gz      --readFilesCommand zcat      --outFileNamePrefix sample.STAR/   --outSAMorder PairedKeepInputOrder   --twopassMode Basic

##### Final parameters after user input--------------------------------:
versionSTAR                       20201
versionGenome                     20101   20200   
parametersFiles                   -   
sysShell                          -
runMode                           alignReads
runThreadN                        16
runDirPerm                        User_RWX
runRNGseed                        777
genomeDir                         /home/jiwoongbio/reference/STAR/hg19
genomeLoad                        NoSharedMemory
genomeFastaFiles                  -   
genomeSAindexNbases               14
genomeChrBinNbits                 18
genomeSAsparseD                   1
genomeSuffixLengthMax             18446744073709551615
readFilesIn                       sample.QC/sample.1.fastq.gz_filtered.gz   sample.QC/sample.2.fastq.gz_filtered.gz   
readFilesCommand                  zcat   
readMatesLengthsIn                NotEqual
readMapNumber                     18446744073709551615
readNameSeparator                 /   
inputBAMfile                      -
bamRemoveDuplicatesType           -
bamRemoveDuplicatesMate2basesN    0
limitGenomeGenerateRAM            31000000000
limitIObufferSize                 150000000
limitOutSAMoneReadBytes           100000
limitOutSJcollapsed               1000000
limitOutSJoneRead                 1000
limitBAMsortRAM                   0
limitSjdbInsertNsj                1000000
outFileNamePrefix                 sample.STAR/
outTmpDir                         -
outTmpKeep                        None
outStd                            Log
outReadsUnmapped                  None
outQSconversionAdd                0
outMultimapperOrder               Old_2.4
outSAMtype                        SAM   
outSAMmode                        Full
outSAMstrandField                 None
outSAMattributes                  Standard   
outSAMunmapped                    None   
outSAMorder                       PairedKeepInputOrder
outSAMprimaryFlag                 OneBestScore
outSAMreadID                      Standard
outSAMmapqUnique                  255
outSAMflagOR                      0
outSAMflagAND                     65535
outSAMattrRGline                  -   
outSAMheaderHD                    -   
outSAMheaderPG                    -   
outSAMheaderCommentFile           -
outBAMcompression                 1
outBAMsortingThreadN              0
outSAMfilter                      None   
outSAMmultNmax                    18446744073709551615
outSAMattrIHstart                 1
outSJfilterReads                  All
outSJfilterCountUniqueMin         3   1   1   1   
outSJfilterCountTotalMin          3   1   1   1   
outSJfilterOverhangMin            30   12   12   12   
outSJfilterDistToOtherSJmin       10   0   5   10   
outSJfilterIntronMaxVsReadN       50000   100000   200000   
outWigType                        None   
outWigStrand                      Stranded   
outWigReferencesPrefix            -
outWigNorm                        RPM   
outFilterType                     Normal
outFilterMultimapNmax             10
outFilterMultimapScoreRange       1
outFilterScoreMin                 0
outFilterScoreMinOverLread        0.66
outFilterMatchNmin                0
outFilterMatchNminOverLread       0.66
outFilterMismatchNmax             10
outFilterMismatchNoverLmax        0.3
outFilterMismatchNoverReadLmax    1
outFilterIntronMotifs             None
clip5pNbases                      0   
clip3pNbases                      0   
clip3pAfterAdapterNbases          0   
clip3pAdapterSeq                  -   
clip3pAdapterMMp                  0.1   
winBinNbits                       16
winAnchorDistNbins                9
winFlankNbins                     4
winAnchorMultimapNmax             50
scoreGap                          0
scoreGapNoncan                    -8
scoreGapGCAG                      -4
scoreGapATAC                      -8
scoreStitchSJshift                1
scoreGenomicLengthLog2scale       -0.25
scoreDelBase                      -2
scoreDelOpen                      -2
scoreInsOpen                      -2
scoreInsBase                      -2
seedSearchLmax                    0
seedSearchStartLmax               50
seedSearchStartLmaxOverLread      1
seedPerReadNmax                   1000
seedPerWindowNmax                 50
seedNoneLociPerWindow             10
seedMultimapNmax                  10000
alignIntronMin                    21
alignIntronMax                    0
alignMatesGapMax                  0
alignTranscriptsPerReadNmax       10000
alignSJoverhangMin                5
alignSJDBoverhangMin              3
alignSJstitchMismatchNmax         0   -1   0   0   
alignSplicedMateMapLmin           0
alignSplicedMateMapLminOverLmate    0.66
alignWindowsPerReadNmax           10000
alignTranscriptsPerWindowNmax     100
alignEndsType                     Local
alignSoftClipAtReferenceEnds      Yes
alignEndsProtrude                 0   ConcordantPair   
chimSegmentMin                    0
chimScoreMin                      0
chimScoreDropMax                  20
chimScoreSeparation               10
chimScoreJunctionNonGTAG          -1
chimJunctionOverhangMin           20
chimOutType                       SeparateSAMold
chimFilter                        banGenomicN   
chimSegmentReadGapMax             0
sjdbFileChrStartEnd               -   
sjdbGTFfile                       -
sjdbGTFchrPrefix                  -
sjdbGTFfeatureExon                exon
sjdbGTFtagExonParentTranscript    transcript_id
sjdbGTFtagExonParentGene          gene_id
sjdbOverhang                      100
sjdbScore                         2
sjdbInsertSave                    Basic
quantMode                         -   
quantTranscriptomeBAMcompression    1
quantTranscriptomeBan             IndelSoftclipSingleend
twopass1readsN                    18446744073709551615
twopassMode                       Basic
----------------------------------------


   Input read files for mate 1, from input string sample.QC/sample.1.fastq.gz_filtered.gz
-rw-rw-r--. 1 jiwoongbio jkim23 2010461598 Mar  3 07:55 sample.QC/sample.1.fastq.gz_filtered.gz

   readsCommandsFile:
exec > "sample.STAR/_STARtmp/tmp.fifo.read1"
echo FILE 0
zcat      "sample.QC/sample.1.fastq.gz_filtered.gz"


   Input read files for mate 2, from input string sample.QC/sample.2.fastq.gz_filtered.gz
-rw-rw-r--. 1 jiwoongbio jkim23 2010813051 Mar  3 07:55 sample.QC/sample.2.fastq.gz_filtered.gz

   readsCommandsFile:
exec > "sample.STAR/_STARtmp/tmp.fifo.read2"
echo FILE 0
zcat      "sample.QC/sample.2.fastq.gz_filtered.gz"

Finished loading and checking parameters
Reading genome generation parameters:
versionGenome                 20201        ~RE-DEFINED
genomeFastaFiles              /home/jiwoongbio/reference/hg19.fasta        ~RE-DEFINED
genomeSAindexNbases           14     ~RE-DEFINED
genomeChrBinNbits             18     ~RE-DEFINED
genomeSAsparseD               1     ~RE-DEFINED
sjdbOverhang                  100     ~RE-DEFINED
sjdbFileChrStartEnd           -        ~RE-DEFINED
sjdbGTFfile                   /biodata/igenome/Homo_sapiens/UCSC/hg19/Annotation/Genes/genes.gtf     ~RE-DEFINED
sjdbGTFchrPrefix              -     ~RE-DEFINED
sjdbGTFfeatureExon            exon     ~RE-DEFINED
sjdbGTFtagExonParentTranscripttranscript_id     ~RE-DEFINED
sjdbGTFtagExonParentGene      gene_id     ~RE-DEFINED
sjdbInsertSave                Basic     ~RE-DEFINED
Genome version is compatible with current STAR version
Number of real (reference) chromosmes= 93
1	chrM	16571	0
2	chr1	249250621	262144
3	chr2	243199373	249561088
4	chr3	198022430	492830720
5	chr4	191154276	691011584
6	chr5	180915260	882376704
7	chr6	171115067	1063518208
8	chr7	159138663	1234698240
9	chr8	146364022	1394081792
10	chr9	141213431	1540620288
11	chr10	135534747	1681915904
12	chr11	135006516	1817706496
13	chr12	133851895	1952972800
14	chr13	115169878	2086928384
15	chr14	107349540	2202271744
16	chr15	102531392	2309750784
17	chr16	90354753	2412511232
18	chr17	81195210	2502950912
19	chr18	78077248	2584215552
20	chr19	59128983	2662334464
21	chr20	63025520	2721579008
22	chr21	48129895	2784755712
23	chr22	51304566	2832990208
24	chrX	155270560	2884370432
25	chrY	59373566	3039821824
26	chr1_gl000191_random	106433	3099328512
27	chr1_gl000192_random	547496	3099590656
28	chr4_ctg9_hap1	590426	3100377088
29	chr4_gl000193_random	189789	3101163520
30	chr4_gl000194_random	191469	3101425664
31	chr6_apd_hap1	4622290	3101687808
32	chr6_cox_hap2	4795371	3106406400
33	chr6_dbb_hap3	4610396	3111387136
34	chr6_mann_hap4	4683263	3116105728
35	chr6_mcf_hap5	4833398	3120824320
36	chr6_qbl_hap6	4611984	3125805056
37	chr6_ssto_hap7	4928567	3130523648
38	chr7_gl000195_random	182896	3135504384
39	chr8_gl000196_random	38914	3135766528
40	chr8_gl000197_random	37175	3136028672
41	chr9_gl000198_random	90085	3136290816
42	chr9_gl000199_random	169874	3136552960
43	chr9_gl000200_random	187035	3136815104
44	chr9_gl000201_random	36148	3137077248
45	chr11_gl000202_random	40103	3137339392
46	chr17_ctg5_hap1	1680828	3137601536
47	chr17_gl000203_random	37498	3139436544
48	chr17_gl000204_random	81310	3139698688
49	chr17_gl000205_random	174588	3139960832
50	chr17_gl000206_random	41001	3140222976
51	chr18_gl000207_random	4262	3140485120
52	chr19_gl000208_random	92689	3140747264
53	chr19_gl000209_random	159169	3141009408
54	chr21_gl000210_random	27682	3141271552
55	chrUn_gl000211	166566	3141533696
56	chrUn_gl000212	186858	3141795840
57	chrUn_gl000213	164239	3142057984
58	chrUn_gl000214	137718	3142320128
59	chrUn_gl000215	172545	3142582272
60	chrUn_gl000216	172294	3142844416
61	chrUn_gl000217	172149	3143106560
62	chrUn_gl000218	161147	3143368704
63	chrUn_gl000219	179198	3143630848
64	chrUn_gl000220	161802	3143892992
65	chrUn_gl000221	155397	3144155136
66	chrUn_gl000222	186861	3144417280
67	chrUn_gl000223	180455	3144679424
68	chrUn_gl000224	179693	3144941568
69	chrUn_gl000225	211173	3145203712
70	chrUn_gl000226	15008	3145465856
71	chrUn_gl000227	128374	3145728000
72	chrUn_gl000228	129120	3145990144
73	chrUn_gl000229	19913	3146252288
74	chrUn_gl000230	43691	3146514432
75	chrUn_gl000231	27386	3146776576
76	chrUn_gl000232	40652	3147038720
77	chrUn_gl000233	45941	3147300864
78	chrUn_gl000234	40531	3147563008
79	chrUn_gl000235	34474	3147825152
80	chrUn_gl000236	41934	3148087296
81	chrUn_gl000237	45867	3148349440
82	chrUn_gl000238	39939	3148611584
83	chrUn_gl000239	33824	3148873728
84	chrUn_gl000240	41933	3149135872
85	chrUn_gl000241	42152	3149398016
86	chrUn_gl000242	43523	3149660160
87	chrUn_gl000243	43341	3149922304
88	chrUn_gl000244	39929	3150184448
89	chrUn_gl000245	36651	3150446592
90	chrUn_gl000246	38154	3150708736
91	chrUn_gl000247	36422	3150970880
92	chrUn_gl000248	39786	3151233024
93	chrUn_gl000249	38502	3151495168
--sjdbOverhang = 100 taken from the generated genome
Started loading the genome: Tue May  3 15:35:16 2016

checking Genome sizefile size: 3195630185 bytes; state: good=1 eof=0 fail=0 bad=0
checking SA sizefile size: 24262958993 bytes; state: good=1 eof=0 fail=0 bad=0
checking /SAindex sizefile size: 1565873619 bytes; state: good=1 eof=0 fail=0 bad=0
Read from SAindex: genomeSAindexNbases=14  nSAi=357913940
nGenome=3195630185;  nSAbyte=24262958993
GstrandBit=32   SA number of indices=5881929452
Shared memory is not used for genomes. Allocated a private copy of the genome.
Genome file size: 3195630185 bytes; state: good=1 eof=0 fail=0 bad=0
Loading Genome ... done! state: good=1 eof=0 fail=0 bad=0; loaded 3195630185 bytes
SA file size: 24262958993 bytes; state: good=1 eof=0 fail=0 bad=0
Loading SA ... done! state: good=1 eof=0 fail=0 bad=0; loaded 24262958993 bytes
Loading SAindex ... done: 1565873619 bytes
Finished loading the genome: Tue May  3 15:37:30 2016

Processing splice junctions database sjdbN=218273,   sjdbOverhang=100 
alignIntronMax=alignMatesGapMax=0, the max intron size will be approximately determined by (2^winBinNbits)*winAnchorDistNbins=589824
Created thread # 1
Created thread # 2
Created thread # 3
Created thread # 4
Starting to map file # 0
mate 1:   sample.QC/sample.1.fastq.gz_filtered.gz
mate 2:   sample.QC/sample.2.fastq.gz_filtered.gz
Created thread # 5
Created thread # 6
Created thread # 7
Created thread # 8
Created thread # 9
Created thread # 10
Created thread # 11
Created thread # 12
Created thread # 13
Created thread # 14
Created thread # 15

**Comment by nboley** [comment]
I'm also getting a segfault using the following command:
STAR-2.5.2a/bin/Linux_x86_64_static/STAR --runThreadN 16 --genomeDir ./GRCh38_standardcontigs.STAR_2.
5.2a_INDEX/ --readFilesIn test.R1.fastq   test.R2.fastq --outSAMtype BAM Unsorted --outSAMorder PairedKeepInputOrder

Removing either --runThreadN, --outSAMtype BAM Unsorted, or --outSAMorder PairedKeepInputOrder makes this problem go away.

**Comment by alexdobin** [comment]
Hi Jiwoong, Nathan,

sorry for belayed reply. The issues you are seeing are similar, but caused by different choice of parameters.

Nathan's case:
--outSAMtype BAM Unsorted 
is presently incompatible with 
--outSAMorder PairedKeepInputOrder
The latter option at the moment can only be used with SAM output (default --outSAMtype  SAM).
I have added an error throw to prevent this combination of parameters.
I have put the option to keep input order with BAM is on my TODO list.

Jiwoong's case:
There was a bug preventing --twopassMode Basic --outSAMorder PairedKeepInputOrder combination. I have fixed it, please try the latest patch on GitHub [master](https://github.com/alexdobin/STAR/archive/master.zip). 

Cheers
Alex
