### ISSUE TITLE
STARsolo -- only counting?

### ISSUE THREAD

**Issue by ms-gx** [alexdobin/STAR#1440]
Is it possible to run STARsolo only in a "counting" mode?

What I want to do:
1) 1st mapping run with STARsolo
2) Removal of specific reads from BAM via custom method
3) Use the BAM from last step, but no re-mapping of the data but just count based on provided GTF

Or would you use another tool in this case?

**Comment by alexdobin** [comment]
Hi Michael,

presently counting from BAM file is not possible. The workaround is to use the "filtered" BAM as input to STARsolo, which will re-map and re-count.
If you simply want to count CB/GX tags from the BAM file, it's straightforward. I have a simple awk script for that, but it's slow.

Cheers
Alex

**Comment by ms-gx** [comment]
This is an option, thanks!
If you can prove the awk script that would be great. Don't mind if slow for my application.

Can I avoid STAR to re-adjust splice-sites because it now has additional info from annotation which it did not have before.

**Comment by ms-gx** [comment]
Two follow-up questions:
1) Why do you suggest to count GX tags via an AWK script? Why not just use the mtx output?
2) How is the logic which assigns a read to a gene? Is it similar to the one from cellranger in case the read maps to several genes?

**Comment by alexdobin** [comment]
Hi Michael,

the script is in the STAR distribution: extras/scripts/soloCountMatrixFromBAM.awk
Usage:
```
samtools view Aligned.sortedByCoord.out.bam | awk -v fileWL=Solo.out/Gene/raw/barcodes.tsv -v fileGenes=Solo.out/Gene/raw/features.tsv  soloCountMatrixFromBAM.awk | sort -k2,2n -k1,1n > matrix.mtx
```

1. I thought you wanted to get the count matrix from the BAM file after filtering the BAM file. This is what this script does.
2. STARsolo uses the same policies as CellRanger to assign reads to gene. Reads that are assigned to one and only one gene are counted. I have --soloMultiMappers options to include multi-gene reads.

Cheers
Alex

**Comment by ms-gx** [comment]
Thanks much!
