### ISSUE TITLE
STAR does not compile under MacOS 12.0.1 with gcc compiler

### ISSUE THREAD

**Issue by Mint-1017** [alexdobin/STAR#1442]
Hi Alex,

I'm new to STAR and thank you so much for this wonderful mapping tool!
I tried compiling STAR under MacOS 12.0.1 with gcc compiler, but it always makes the same error.

How to reproduce:
1. Unzip STAR
`wget https://github.com/alexdobin/STAR/archive/2.7.9a.tar.gz
tar -xzf 2.7.9a.tar.gz
cd STAR-2.7.9a`

2. cd source and make
`cd source
make STARforMacStatic CXX=/usr/local/Cellar/gcc/11.2.0_3/bin/g++-11`

the error: g++-11: error: unrecognized command-line option '-stdlib=libc++'
make: *** [Makefile:88: SoloFeature_collapseUMI_Graph.o] Error 1

Help will be appreciated!!

Best,
Mint-1017

**Comment by alexdobin** [comment]
Hi Mint-1017

this looks like an issue with GCC installation / libraries.
I am not sure why this option  '-stdlib=libc++' is  passed to g++, it's not in the STAR Makefile.
Instead of compiling, you can try to use the precompiled executable bin/MacOSX_x86_64/STAR.

Cheers
Alex

**Comment by Mint-1017** [comment]
Hi Alex,

Thank you for your response!
I also tried compiling 

1. STAR 2.7.9.a with g++-8 (I installed via brew and typed`make STARforMacStatic CXX=/usr/local/Cellar/gcc@8/8.5.0/bin/g++-8`)
2. STAR 2.7.10.a with g++-11

but I got the same error: `g++-11: error: unrecognized command-line option '-stdlib=libc++'`
Precompiled executable worked!



By the way I'd like you to let me ask one thing.
README.md says,
```
# 2. Install gcc with brew:
brew install gcc **--without-multilib**
```
However, --without-multilib has already been removed. [https://github.com/Homebrew/homebrew-core/pull/16751]
So I really appreciate if you will remove this option so that we will not be confused:)


Thank you so much,

Mint-1017

**Comment by Mint-1017** [comment]
Hi Alex,

Sure! Here's the entire output.

```
date: illegal option -- -
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
/usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -c -D_FORTIFY_SOURCE=2 -isystem /opt/anaconda3/include  -O3 -std=c++11 -fopenmp -D'COMPILATION_TIME_PLACE=" :/Users/sakitakeshita/STAR-2.7.9a/source"' -D'COMPILE_FOR_MAC' -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -std=c++14 -fmessage-length=0 -isystem /opt/anaconda3/include SoloFeature_collapseUMI_Graph.cpp
g++-11: error: unrecognized command-line option '-stdlib=libc++'
make: *** [Makefile:88: SoloFeature_collapseUMI_Graph.o] Error 1
```

Best,
Mint-1017

**Comment by alexdobin** [comment]
Hi Mint-1017

it looks like there are a of extra parameters here, which are not specified by me in the Makefile.

-D_FORTIFY_SOURCE=2 -isystem /opt/anaconda3/include -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -std=c++14 -fmessage-length=0 -isystem /opt/anaconda3/include

What is the value of $CPPFLAGS variable (i.e. output of ```echo $CPPFLAGS```)?
If it's not empty, please set it to empty with ```export CPPFLAGS=""``` before compilation.

Cheers
Alex

**Comment by Mint-1017** [comment]
Hi Alex,

I checked and emptied $CPPFLAGS variable as below, but I still got a similar error.

```
echo $CPPFLAGS
-D_FORTIFY_SOURCE=2 -isystem /opt/anaconda3/include

export CPPFLAGS=""
```

Here' s the entire error massage
```
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
/usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -c   -O3 -std=c++11 -fopenmp -D'COMPILATION_TIME_PLACE=" :/Users/sakitakeshita/STAR-2.7.9a/source"' -D'COMPILE_FOR_MAC' -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -std=c++14 -fmessage-length=0 -isystem /opt/anaconda3/include SoloFeature_collapseUMI_Graph.cpp
g++-11: error: unrecognized command-line option '-stdlib=libc++'
make: *** [Makefile:88: SoloFeature_collapseUMI_Graph.o] Error 1
```

Best
Mint-1017

**Comment by alexdobin** [comment]
Hi Mint-1017

I am running out of ideas on how to explain this. It seems that some extra parameters are injected into the compilation command on your system.
Have you tried running the pre-compiled executable: bin/MacOSX_x86_64/STAR in the STAR distribution?

Cheers
Alex

**Comment by Mint-1017** [comment]
Hi Alex,

Yes, the pre-compiled executable worked well!
Thank you so much for everything:)

Best
Mint-1017

**Comment by alexdobin** [comment]
Hi Mint-1017,

great! Pre-compile executables are always the best to try first. Sorry I did not mention it from the start.

Cheers
Alex

**Comment by Oelsakha** [comment]
I have the same problem and I don't understand how to do Pre-compile executables. Can you help me please.

**Comment by alexdobin** [comment]
Hi @Oelsakha 

after you download and unzip STAR archive from GitHub, the executable will be inside the uncompressed folder: bin/Linux_x86_64_static/STAR
You should to specify full path to run it.
