### ISSUE TITLE
Extract SJ.out.tab from BAM

### ISSUE THREAD

**Issue by dg520** [alexdobin/STAR#1444]
Dear Alex,

I'm working on a large cohort of RNASeq dataset where BAM files are already available, but without `SJ.out.tab` file. It seems that I can use the scripts you include in the `extras/scripts` folder, as something like:
```
samtools view INPUT.unsorted.BAM | awk -f sjFromSAMcollapseUandM.awk | sort -k1,1, -k2,2n > OUTPUT.txt
```
to get some information. I have several questions:
1. It seems the above command only generates Columns 1, 2, 3, 7 and 8 compared to a default output in `SJ.out.tab`. How can I get the other columns in the post-alignment stage?
2. Can I use the same command if the input BAM is coordinate-sorted?
3. Is it possible to extract `SJ.out.tab` against an alternative GTF file that is NOT the one used for the alignment?

Thanks a lot!

Best,
Dadi

**Comment by alexdobin** [comment]
Hi Dadi,

1. Columns 4,5=strand,motif are based on the intron motif of the junctions, so you will need to check the genomic bases at the junction coordinates. For column 6 (annotation), so you will need to compare the junctions to the list of annotated junctions from the GTF. Column 9 (max overhang) is harder to extract, as you will need to extract overhnags for each read/junction and find the maximum one.

2. You can only use coordinate sorted BAM for single-end, not for paired-end reads. In the latter case the BAM has to be re-sorted by name.

3. Only column 6 (annotation) depends on the GTF file, and after extracting the junctions you can annotate the junctions against the list of annotated junctions from any GTF.

Cheers
Alex

**Comment by dg520** [comment]
Thank you so much for your insights, Alex!

**Comment by alexdobin** [comment]
To create junction file from BAM, please run the script shown in the 1st post.

**Comment by wyt14** [comment]
Hello, author. I am encountering the same issue as dg520. Could you please guide me on how to fill in the information for the other columns? Do you have any relevant code for the completion? Thank you very much!
