### ISSUE TITLE
Number of cell barcodes differ between CB tags and matrix.mtx

### ISSUE THREAD

**Issue by ms-gx** [alexdobin/STAR#1446]
If I grep the number of individual `CB` tags in the STARsolo BAM I get 13,361 unique barcodes.

However, in the raw `matrix.mtx` I get more features: 13,590. How is this possible?

(If I grep for uniqe `CR` tags, I get 22510.)

**Comment by alexdobin** [comment]
Hi Michael,

this should not happen, the number of CBs in the matrix should be <= the number of CBs in the BAM file.

Cheers
Alex

**Comment by ms-gx** [comment]
Oh, there was a mistake on my side. Now it fulfills the condition you mention above.

Additional question: the number of  barcodes in `raw/barcodes.tsv`, should it be equal to the unique CB tags in the BAM?

**Comment by alexdobin** [comment]
Hi Michael,

raw/barcodes.tsv contains the entire whitelist >> number of detected barcodes in the BAM file.
If you take the detected barcodes from matrix.mtx, they should match the barcodes in the alignments that contain both CB and GX (gene) tags.

Cheers
Alex

**Comment by ms-gx** [comment]
Hi Alex

Thanks much! Now I understand.
