### ISSUE TITLE
EXITING because of fatal ERROR: could not make temporary directory

### ISSUE THREAD

**Issue by boro2013** [alexdobin/STAR#145]
Hi all,

I want to use STAR for mapping, but first I'm trying to build the indexes of my reference hg (I use Ensembl hg), since it is recommended to build our own indexes I run the following command:

`STAR --runThreadN 12 --runMode genomeGenerate --outTmpDir tmp --genomeDir STAR_genome/ --genomeFastaFiles $ref_fa_dir --sjdbGTFfile $ref_gtf_dir --sjdbOverhang 100 --genomeChrBinNbits 15`

but I still get this error:
`EXITING because of fatal ERROR: could not make temporary directory: tmp`

What I already tried:
1- run the command without the --outTmpDir option
2- chmod 777 <running directory>
3- create the temp directory in advance, and "chmod" it to 777

Any idea, suggestions to fix that error ?

**Comment by alexdobin** [comment]
Hi @boro2013 

the tmp directory should exist and be writable in the working directory from which you run STAR.
Could you try using absolute path or the tmp?
If this does not help, please send me the Log.out file.

Cheers
Alex
