### ISSUE TITLE
Error on header record missing required tag after alignment 

### ISSUE THREAD

**Issue by fransdany** [alexdobin/STAR#1450]
Hi Everyone,

I'm trying to align the paired-end reads of SARS-CoV-2 sequence with STAR 2.7.1a and renamed it into SRA.bam
$ STAR --runThreadN 8 --runMode alignReads --genomeDir ~/Tes/Gen_Idx --readFilesIn ~/Tes/sra1_trim.fastq ~/Tes/sra2_trim.fastq --outSAMtype BAM Unsorted --limitBAMsortRAM 1007743684 --outSAMheaderHD @HD VN:1.4 SO:unsorted --outSAMattrRGline ID:0 PL:ILLUMINA LB:rna --outSAMattributes All

but when I checked the aligned .bam with Picard's ValidateSamFile, I got this result:

HISTOGRAM    java.lang.String
Error Type      Count
ERROR:HEADER_RECORD_MISSING_REQUIRED_TAG        1

I cross-checked with the samtools view for the respective .bam file
$ samtools view -h SRA.bam | head -n 5

and this is how the header looked :

@HD     VN:1.4  SO:unsorted
@SQ     SN:NC_045512.2  LN:29903
@PG     ID:STAR PN:STAR VN:2.7.3a       CL:STAR   --runMode alignReads   --runThreadN 8   --genomeDir /home/frans/Tes/Gen_Idx   --readFilesIn /home/frans/Tes/sra1_trim.fastq   /home/frans/Tes/sra2_trim.fastq      --limitBAMsortRAM 1007743684   --outSAMtype BAM   Unsorted      --outSAMattributes All      --outSAMattrRGline ID:0   PL:ILLUMINA   LB:rna      --outSAMheaderHD @HD   VN:1.4   SO:unsorted
@PG     ID:samtools     PN:samtools     PP:STAR VN:1.10 CL:samtools view -h SRA.bam
@RG     ID:0    PL:ILLUMINA     LB:rna

I wonder what step(s) I should do fix this issue. I don't want to ignore the error and I really want to figure out the source of the problem.

Thanks in advance for your help.

**Comment by alexdobin** [comment]
Hi @fransdany 

I believe all the standard tags have to have capital letters: @HD, @SQ, @PG, @suhrig 

Cheers
Alex

**Comment by fransdany** [comment]
Dear @alexdobin Alex,

Thank you for your reply. I have just found that this error on header record missing required tag appear is because I forgot to add SM in the outSAMattrRGline option. I don't really need to specify the outSAMheaderHD as well. I also insert outSAMmapqUnique at 60, otherwise the mapping quality will be extremely low (between 0-3) when I view the aligned file on IGV. In my case, I think the "proper" command should be like this:

STAR --runThreadN 8 --runMode alignReads --genomeDir ~/Tes/Gen_Idx \
--readFilesIn ~/Tes/sra1_trim.fastq ~/Tes/sra2_trim.fastq \
--outSAMtype BAM Unsorted --limitBAMsortRAM 1007743684 \
--outSAMmapqUnique 60 \
--outSAMattrRGline ID:0 PL:ILLUMINA LB:rna SM:1 \
--outSAMattributes All

This will remove errors at least on missing read group, NM_tag and header record missing required tag when you validate the .bam file as well as make the variant mapping quality score "more desirable." The sorting option should remain Unsorted though, if else it would return or even add new errors. Hence, I perform sorting and indexing with samtools after this step. Hope this could add more valuable information.


Regards,

Frans

**Comment by alexdobin** [comment]
Hi Frans,

your parameters look all good.
In principle, you can set Picard to not complaining about RG, NM and header tags, since these parameters are not really required by the SAM/BAM specifications. But I think GATK requires them.

Cheers
Alex
