### ISSUE TITLE
STAR mysteriously freezing at "Loading SA... "

### ISSUE THREAD

**Issue by sevahn** [alexdobin/STAR#1471]
Hi,

I have some RNA-seq reads that are 2x151 sequenced. I trimmed off the adapters with trimmomatic and wanted to align with STAR. 
 However, STAR just keeps mysteriously crashing at “Loading SA …” for some samples and “Finished loading the genome: TIMESTAMP” for other samples with no error in the “Log.progress.out” 

I googled around to no avail.

I’m stuck because:

(1) These “Log.progress.out” files look identical to a successful STAR run that I did with a different genome build.

(2) It’s not a memory/thread issue because upping either one doesn’t make STAR keep going, the log files still drop off with the same text I wrote above.

(3) I know that I’m passing non-empty trim files that I’m passing into STAR and I know I trimmed correctly because I checked the trimmed file hashes with a pipeline that did the same trimming and could map the trimmed reads with the STAR. 

(4) I’m 90% confident that I successfully did a correct genome build because I am able to reproduce this error with a different STAR version and genome build that I’ve used successfully.

The STAR version for the alignment and the STAR version for the genome build are the same (2.7.10a). Downloaded it from here https://anaconda.org/bioconda/star
I reproduce this same result with 2.7.3a too.

Help! And thank you!

**Comment by alexdobin** [comment]
Hi @sevahn 

please send me Log.out file for one of the failed runs.

Cheers
Alex

**Comment by sevahn** [comment]
This turned out to be a pipeline issue with a config file and memory limits rather than STAR itself; resolved!

**Comment by ylevmirom** [comment]
Im currently facing this issue, could you please elaborate on how you fixed this issue? @sevahn
