### ISSUE TITLE
Huge list of "Ignoring SAM validation error: ERROR::INVALID_ALIGNMENT_START"

### ISSUE THREAD

**Issue by asilvestris84** [alexdobin/STAR#1473]
Hi Alex,

i am using STAR (2.7.9a) consensus and after alignment i used picard MarkDuplicates which produced a very long list of errors:

Ignoring SAM validation error: ERROR::CIGAR_MAPS_OFF_REFERENCE:Read name MG01HX04:727:HKC2GCCXY:1:2105:14032:48336, Read CIGAR M operator maps off end of reference
Ignoring SAM validation error: ERROR::CIGAR_MAPS_OFF_REFERENCE:Read name MG01HX04:727:HKC2GCCXY:1:2105:14032:48336, Read CIGAR M operator maps off end of reference
Ignoring SAM validation error: ERROR::CIGAR_MAPS_OFF_REFERENCE:Read name MG01HX04:727:HKC2GCCXY:1:1219:23713:47738, Read CIGAR M operator maps off end of reference
Ignoring SAM validation error: ERROR::CIGAR_MAPS_OFF_REFERENCE:Read name MG01HX04:727:HKC2GCCXY:1:1219:23713:47738, Read CIGAR M operator maps off end of reference
Ignoring SAM validation error: ERROR::CIGAR_MAPS_OFF_REFERENCE:Read name MG01HX04:727:HKC2GCCXY:1:1202:23987:72227, Read CIGAR M operator maps off end of reference
Ignoring SAM validation error: ERROR::CIGAR_MAPS_OFF_REFERENCE:Read name MG01HX04:727:HKC2GCCXY:1:1202:23987:72227, Read CIGAR M operator maps off end of reference
Ignoring SAM validation error: ERROR::CIGAR_MAPS_OFF_REFERENCE:Read name MG01HX04:727:HKC2GCCXY:1:1111:22120:64949, Read CIGAR M operator maps off end of reference
Ignoring SAM validation error: ERROR::INVALID_ALIGNMENT_START:Record 15575984, Read name MG01HX04:727:HKC2GCCXY:1:1111:22120:64949, Mate Alignment start (242193644) must be <= reference sequence length (242193529) on reference chr2
Ignoring SAM validation error: ERROR::INVALID_ALIGNMENT_START:Record 15575984, Read name MG01HX04:727:HKC2GCCXY:1:1111:22120:64949, Alignment start (242193644) must be <= reference sequence length (242193529) on reference chr2
Ignoring SAM validation error: ERROR::CIGAR_MAPS_OFF_REFERENCE:Read name MG01HX04:727:HKC2GCCXY:1:1111:22120:64949, Read CIGAR M operator maps off end of reference
Ignoring SAM validation error: ERROR::INVALID_ALIGNMENT_START:Record 15575985, Read name MG01HX04:727:HKC2GCCXY:1:1111:22120:64949, Mate Alignment start (242193644) must be <= reference sequence length (242193529) on reference chr2
Ignoring SAM validation error: ERROR::INVALID_ALIGNMENT_START:Record 15575985, Read name MG01HX04:727:HKC2GCCXY:1:1111:22120:64949, Alignment start (242193644) must be <= reference sequence length (242193529) on reference chr2
Ignoring SAM validation error: ERROR::CIGAR_MAPS_OFF_REFERENCE:Read name MG01HX04:727:HKC2GCCXY:1:2205:22577:24814, Read CIGAR M operator maps off end of reference
Ignoring SAM validation error: ERROR::INVALID_ALIGNMENT_START:Record 15575986, Read name MG01HX04:727:HKC2GCCXY:1:2205:22577:24814, Mate Alignment start (242193947) must be <= reference sequence length (242193529) on reference chr2
Ignoring SAM validation error: ERROR::INVALID_ALIGNMENT_START:Record 15575986, Read name MG01HX04:727:HKC2GCCXY:1:2205:22577:24814, Alignment start (242193899) must be <= reference sequence length (242193529) on reference chr2
Ignoring SAM validation error: ERROR::CIGAR_MAPS_OFF_REFERENCE:Read name MG01HX04:727:HKC2GCCXY:1:2205:22577:24814, Read CIGAR M operator maps off end of reference
Ignoring SAM validation error: ERROR::INVALID_ALIGNMENT_START:Record 15575987, Read name MG01HX04:727:HKC2GCCXY:1:2205:22577:24814, Mate Alignment start (242193899) must be <= reference sequence length (242193529) on reference chr2
Ignoring SAM validation error: ERROR::INVALID_ALIGNMENT_START:Record 15575987, Read name MG01HX04:727:HKC2GCCXY:1:2205:22577:24814, Alignment start (242193947) must be <= reference sequence length (242193529) on reference chr2
Ignoring SAM validation error: ERROR::CIGAR_MAPS_OFF_REFERENCE:Read name MG01HX04:727:HKC2GCCXY:1:2118:30797:20700, Read CIGAR M operator maps off end of reference
Ignoring SAM validation error: ERROR::INVALID_ALIGNMENT_START:Record 15575988, Read name MG01HX04:727:HKC2GCCXY:1:2118:30797:20700, Mate Alignment start (242194929) must be <= reference sequence length (242193529) on reference chr2

the command line I used to build the index: /home/useradmin/exe/STAR-2.7.9a/bin/Linux_x86_64/STAR   --runMode genomeGenerate      --runThreadN 20   --genomeDir ./   --genomeFastaFiles ./GRCh38.primary_assembly.genome.fa      --genomeTransformType Haploid   --genomeTransformVCF ./chr_common_all_20180418.vcf   --sjdbGTFfile ./gencode.v39.annotation.gtf   --sjdbOverhang 150

the command line I used in the mapping step: /home/useradmin/exe/STAR-2.7.9a/bin/Linux_x86_64/STAR --runThreadN 10 --genomeDir /mnt/NAS/ArcRNA/STAR_index_GRCh38 --readFilesIn 1740R-48-09_S17_L003_R1_001.fq 1740R-48-09_S17_L003_R2_001.fq --outSAMtype BAM Unsorted --twopassMode Basic --outSAMstrandField intronMotif --outSAMattributes All --outFilterType BySJout --outFilterMultimapNmax 1 --outFilterMismatchNmax 999 --outFilterMismatchNoverLmax 0.04 --alignIntronMin 20 --alignIntronMax 1000000 --alignMatesGapMax 1000000 --alignSJoverhangMin 8 --alignSJDBoverhangMin 1 --genomeTransformOutput SAM

can you kindly help me understand what's going on here? Many thanks in advance! ;)

**Comment by asilvestris84** [comment]
My mistake in providing the vcf for building the index. Sorry.

**Comment by suyanan** [comment]
use the STAR-2.7.8a version to run (use this genome fasta https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/004/681/135/GCA_004681135.1_ASM468113v1/GCA_004681135.1_ASM468113v1_genomic.fna.gz):
```
STAR-2.7.8a/bin/Linux_x86_64/STAR --outSAMtype BAM SortedByCoordinate --runThreadN 32 --genomeDir /DATA/database/genome/Hericium_alpestre/ASM468113v1/star_index --readFilesIn  /outputEI0-1/quality_control/EI0-1_clean_R1.fq.gz /outputEI0-1/quality_control/EI0-1_clean_R2.fq.gz --twopassMode Basic --readFilesCommand zcat --outFileNamePrefix /outputEI0-1/mapping/EI0-1. --outTmpDir /outputEI0-1/mapping/EI0-1.STARtmp --outSAMattrRGline ID:EI0-1 SM:EI0-1 LB:EI0-1 PL:ILLUMINA --sjdbOverhang 149 --quantMode TranscriptomeSAM GeneCounts --outReadsUnmapped None --outSAMstrandField intronMotif --outSAMunmapped Within --chimSegmentMin 12 --chimJunctionOverhangMin 8 --chimOutJunctionFormat 1 --alignSJDBoverhangMin 10 --alignMatesGapMax 100000 --alignIntronMax 100000 --alignSJstitchMismatchNmax 5 -1 5 5 --chimMultimapScoreRange 3 --chimScoreJunctionNonGTAG -4 --chimMultimapNmax 20 --chimNonchimScoreDropMin 10 --peOverlapNbasesMin 12 --peOverlapMMp 0.1 --alignInsertionFlush Right --alignSplicedMateMapLminOverLmate 0 --alignSplicedMateMapLmin 30
```
then use GATK to markduplicates by:
```
/home/research/software/gatk-4.5.0.0/gatk MarkDuplicates --CREATE_INDEX true -I /outputEI0-1/mapping/EI0-1.Aligned.sortedByCoord.out.bam -O /outputEI0-1/mapping/EI0-1.sorted.dedup.bam -M /outputEI0-1/mapping/EI0-1.metrics --TMP_DIR /outputEI0-1/mapping 
```
**I got the wrong message:**
![image](https://github.com/alexdobin/STAR/assets/16696416/ebbeef8b-818c-4972-b1ac-e70f85c71633)

the problem reads is:
A00151:15120:HYLKCDSX2:3:2622:13058:3966	99	SFCI01000303.1	25522	255	150M	=	25731	288	CATGGTAATGATAGCGGAAGGGCAATGGAGAGGATGGTCCACCGAACCAAACGAACTCTATAGTCTAGCACATAATAAGCCACGAAGCAAAGGAAAAGGAGGAAACAAGCGCCCCAGGAAAGGCAGGCGACATGCCCGAGCGCGAGCAGA	FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	NH:i:1	HI:i:1	AS:i:207	nM:i:10	RG:Z:EI0-1
A00151:15120:HYLKCDSX2:3:2622:13058:3966	147	SFCI01000303.1	25731	255	46S79M25S	=	25522	-288	ACATGACCACGGATCTCAGCCTCCAATAAATACCAGCCCCAGCACATCAGAGCGTGCTCTTCCTCTGCGCTCTCGCCACCGTGCCCCAGAAGTCCGCCGGGCCAGACGCATTCGCGACGACCTCGACGCCCGCCCACTGCTTCCGCCACG	FFFFFFFFFFFFFF:FFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	NH:i:1	HI:i:1	AS:i:207	nM:i:10	RG:Z:EI0-1


can you kindly help me understand what's going on here? Many thanks

**Comment by suyanan** [comment]
R2 reads mapped to the chrom end with 79M25S: the 79M bases is the chorm end while the 25S is beyond the chrom end.

use gatk CleanSam (Cleans a SAM/BAM/CRAM files, soft-clipping beyond-end-of-reference alignments and setting 
MAPQ to 0 for unmapped reads), to fix these reads, then result is OK.

but, you can also check this alignment to fix it, the chrom tail sequence is :
```
TAGTCAGGAAGAGATCATAGTCCATTACAATTTGTGTACCGTATCCTCCCGCAAGGTCTAAGTAGAAGCAACGTGAACAAAACGCCATCTAAGGGCGTCGCCGATGGCAAGCATCGAGAAATGCAGAATGCAT
GATAATGATAGCGGAAGGGCAATGGAAAGGATGGTCCACCGCACCAAACGAACTCTATAGTCTAGCACATAATAAGCCACGAAGCAAAGATAAACAAGGAAACAAGCGCCCCAGGAAAGGCAGGCGACAtgcccgagcgcgagcaga(R1 150M map)
aGCCGCTGCCCACACATGACCACGGATCTCAGCCTCCAATAAATACCAGCCCCCACAGC
TCAGAGcgcgctcttcctctgcgCTCTCGCCACCGTGGCCCAGAAGTCCGCCGGGCCAGACGCGTTCGCGACGACCTC(R2 79M map)
```

**Comment by suyanan** [comment]
R2 reads mapped to the chrom end with 79M25S: the 78M bases is the chorm end while the 26S is beyond the chrom end.

use GATK CleanSam, this alignment is:
![image](https://github.com/alexdobin/STAR/assets/16696416/6af0aac5-989f-494b-a2b0-6337abe0bb50)

then GATK Markduplicates is ok.
chomr SFCI01000303.1 tail sequence is :
```
TAGTCAGGAAGAGATCATAGTCCATTACAATTTGTGTACCGTATCCTCCCGCAAGGTCTAAGTAGAAGCAACGTGAACAAAACGCCATCTAAGGGCGTCGCCGATGGCAAGCATCGAGAAATGCAGAATGCAT
GATAATGATAGCGGAAGGGCAATGGAAAGGATGGTCCACCGCACCAAACGAACTCTATAGTCTAGCACATAATAAGCCACGAAGCAAAGATAAACAAGGAAACAAGCGCCCCAGGAAAGGCAGGCGACAtgcccgagcgcgagcaga(R1 150M map)
aGCCGCTGCCCACACATGACCACGGATCTCAGCCTCCAATAAATACCAGCCCCCACAGC
TCAGAGcgcgctcttcctctgcgCTCTCGCCACCGTGGCCCAGAAGTCCGCCGGGCCAGACGCGTTCGCGACGACCTC(R2 79M map)
```
