### ISSUE TITLE
primary alignment and secondary alignments

### ISSUE THREAD

**Issue by yiranzhimo** [alexdobin/STAR#1475]
Hello, I feel confused about How STAR chooses the primary alignment and the secondary alignments.

one of the examples of my aligned bam file is below:

```
DP8400020970TLL1C001R00300000907	16	NC_052533.1	75979959	0	93M7S	*	0	0	CATCTATCATCCCGACACGGAAAAAGCTTCCAGTGGCTCATCTGCTGCAGTACATCTTTCCTGAATGCTGTCTGTCTCAACGCAAACAGCCTCCAGAACG	EBBEDEDFFC=C:ECFCBEEEB@(DEDD?AEDFFDFF>CDBCFFEBEFFECDEE8=?ADAD>FDFEEDDF6DDF*D>E@CEFECDDDDD8@*:BDE?C<E	NH:i:7	HI:i:1	AS:i:87	nM:i:2	UR:Z:GGCAGCGTCA	CB:Z:GAGTAGATTGAGTGGACACC	RE:A:A
DP8400020970TLL1C001R00300000907	272	NC_052533.1	75987679	0	93M7S	*	0	0	*	*	NH:i:7	HI:i:2	AS:i:87	nM:i:2	UR:Z:GGCAGCGTCA	CB:Z:GAGTAGATTGAGTGGACACC
DP8400020970TLL1C001R00300000907	272	NC_052533.1	75976099	0	93M7S	*	0	0	*	*	NH:i:7	HI:i:3	AS:i:87	nM:i:2	UR:Z:GGCAGCGTCA	CB:Z:GAGTAGATTGAGTGGACACC
DP8400020970TLL1C001R00300000907	272	NC_052533.1	75983819	0	93M7S	*	0	0	*	*	NH:i:7	HI:i:4	AS:i:87	nM:i:2	UR:Z:GGCAGCGTCA	CB:Z:GAGTAGATTGAGTGGACACC
DP8400020970TLL1C001R00300000907	272	NC_052533.1	75991539	0	93M7S	*	0	0	*	*	NH:i:7	HI:i:5	AS:i:87	nM:i:2	UR:Z:GGCAGCGTCA	CB:Z:GAGTAGATTGAGTGGACACC
DP8400020970TLL1C001R00300000907	272	NC_052533.1	75968390	0	93M7S	*	0	0	*	*	NH:i:7	HI:i:6	AS:i:87	nM:i:2	UR:Z:GGCAGCGTCA	CB:Z:GAGTAGATTGAGTGGACACC
DP8400020970TLL1C001R00300000907	272	NC_052533.1	75972238	0	93M7S	*	0	0	*	*	NH:i:7	HI:i:7	AS:i:87	nM:i:2	UR:Z:GGCAGCGTCA	CB:Z:GAGTAGATTGAGTGGACACC
```

As the STAR manual shows: 
> This default behavior can be changed with --outSAMprimaryFlag AllBestScore option, which will output all alignments with the best score as primary alignments (i.e. 0x100 bit in the FLAG unset).

But in the example, the scores are almost identical, so how does STAR choose the primary alignment？

**Comment by alexdobin** [comment]
Hi @yiranzhimo 

with default parameters, there is no specific rule to choose the primary alignment out of the top-scoring alignment.
STAR selects as primary the first top-scoring alignment it finds. It is deterministic, i.e. every time it maps the same read, the same primary alignment will be marked.

There is an ability to randomize the order of alignments (and thus the primary alignment) with ```--outMultimapperOrder Random``` option.

If you need a specific primary selection scheme, you can do it in the post-mapping processing, since STAR outputs **all** top-scoring alignments.

Cheers
Alex

**Comment by yiranzhimo** [comment]
> Hi @yiranzhimo
> 
> with default parameters, there is no specific rule to choose the primary alignment out of the top-scoring alignment. STAR selects as primary the first top-scoring alignment it finds. It is deterministic, i.e. every time it maps the same read, the same primary alignment will be marked.
> 
> There is an ability to randomize the order of alignments (and thus the primary alignment) with `--outMultimapperOrder Random` option.
> 
> If you need a specific primary selection scheme, you can do it in the post-mapping processing, since STAR outputs **all** top-scoring alignments.
> 
> Cheers Alex

Okay, I got it, Thank you!
