### ISSUE TITLE
Cell Ranger xf tag

### ISSUE THREAD

**Issue by mbahin** [alexdobin/STAR#1479]
Hi Alex,

I just ran into Cell Ranger `xf` BAM tag (cf [here](https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/output/bam), second table, last line).
Maybe this is more or less redundant with `AS` tag but it seems to me a bit more straightforward?
This is just an idea but it seems interesting to retrieve only one read representative of a UMI (I like it but it may be a bit niche...).

Cheers,
Mathieu

**Comment by alexdobin** [comment]
Hi Mathieu,

I am not sure how CellRanger decided which read is representative.
All reads with the same CB/UMI/Gene are supposedly coming from the same RNA molecule.

Cheers
Alex

**Comment by mbahin** [comment]
Hi Alex,

I also wonder how they choose...
My previous approach, when I need to have one representative read per UMI is to the the one with the maximum AS tag score. I guess it's the same and you can close the issue :).

Cheers,
Mathieu

**Comment by alexdobin** [comment]
Hi Mathieu,

right, the highest alignment score read makes sense.
Another approach could be to take the read closest to the 3' of one of the gene transcripts... but it's more laborious.

Cheers
Alex
