### ISSUE TITLE
Incomplete mapping

### ISSUE THREAD

**Issue by Gotumbtai** [alexdobin/STAR#1480]
Hi Alex,

I am mapping my fastq files that were well mapped to a genome in a previous trial, but the current mapping was incomplete. While I was using Ver. 2.7.9a, I am using Ver. 2.7.10a for the current trial for the fastq files from rat tissues. The reference genome was either "Rattus_norvegicus.Rnor_6.0.dna.toplevel.fa + Rattus_norvegicus.Rnor_6.0.104.gtf" or "Rattus_norvegicus.mRatBN7.2.dna.toplevel.fa + Rattus_norvegicus.mRatBN7.2.105.gtf" (I tried both but the result was not changed).
I am using Mac OS 12.1 with 48GB RAM, and the free space is more than 400GB (I also tried larger storage (6TB), but it also did not work).

I am attaching the Log.out file. Thank you for your advice.
[infhp_unt_1_out_Log.out.txt](https://github.com/alexdobin/STAR/files/8042001/infhp_unt_1_out_Log.out.txt)

**Comment by Gotumbtai** [comment]
Thank you Alex,
Because I am a beginner, I would appreciate it if you could guide me on how to apply the patch, please. Thank you for your help.

**Comment by alexdobin** [comment]
Hi @Gotumbtai 

the eaiest way is to use the pre-compiled executables for Mac:
https://github.com/alexdobin/STAR/releases/download/2.7.10a_alpha_220207/STAR_MacOSX_x86_64.zip

Cheer
Alex

**Comment by Gotumbtai** [comment]
Sorry for my poor understanding. Does it mean just drag and drop the decompressed file to the terminal?

**Comment by alexdobin** [comment]
First, you decompress the file into a folder, and then, when you run the STAR command line, you need to specify the full path to the STAR executable.
