### ISSUE TITLE
Strand information for non-canonical junctions

### ISSUE THREAD

**Issue by erajshafiq** [alexdobin/STAR#1487]
Hi, 

Is there a way to determine the strand for non-canonical splice junctions (Intron motif '0' from SJ.out.tab) file? 

Thanks!

**Comment by alexdobin** [comment]
Hi Eraj,

if the RNA-seq data is stranded, you can check the strand of alignments that cross the non-canonical junction to determine its strand.

Cheers
Alex

**Comment by erajshafiq** [comment]
Thanks!
