### ISSUE TITLE
gene ID bam tag

### ISSUE THREAD

**Issue by pmBarlev** [alexdobin/STAR#149]
This is a feature request.

I suggest adding an attribute option which would list all the gene_id's which a read overlaps. E.g., following 10x tags (http://software.10xgenomics.com/single-cell/pipelines/latest/output/bam), a bam tag of the form GX:Z:ENSMUSG000000001,ENSMUSG0000002. 

This is useful when UMI barcodes are used, and de-duplication is performed before counting.

**Comment by alexdobin** [comment]
Hi @pmBarlev 

this is a great suggestion, thanks!
Will put it on my TODO list.

Cheers
Alex

**Comment by pmBarlev** [comment]
No, thank you ;-)

Another bam tag option that would be useful, is something like BWA-MEM's `-c` option,  which takes  tags appended to the fastq readname line (usually during a pre-processing step), and implants them in the bam entry. Such an option is a convenient way to insert the UMI-barcode tags in the bam.

**Comment by mbourgey** [comment]
Hi Alex, I totally agree with pmBarlev regarding these 2 features. They could definitively be a great add-on for single cell processing.
Do you you know if there is any plan for the integration of these 2 features ?

Thank you

Mathieu

**Comment by serine** [comment]
@alexdobin and @pmBarlev Are there any thought/news about UMI based support? 

I was doing some reading about what would/should UMI tag look like in BAM files. [This discussion.](https://github.com/samtools/hts-specs/issues/109#issuecomment-158190238) It looks like **RX** is the tag to use and it should include your UMI sequence. In addition there should be **MI** tag that uniquely identifies each UMI (which is still a bit unclear to me why?, but essentially for de-duplication purpose if the read with the same UMI mapps to two different location those could be distinguished through **MI** tag, the bit that I don't understand is whether that event is true biological or an artefact of the mapping )

Irrespective I was trying to figure out what will `bwa mem -C` do and what is the syntax for that is.. haven't at this stage...

Right now I have both barcode and UMI in the FASTQ read name (header) e.g 

```
@NB551311:19:HKW35BGX5:1:11101:12833:1048:TAGCGCTC:ACTACAAAGTT
```

where `TAGCGCTC:ACTACAAAGTT` is BARCODE:UMI, that is cellular barcode to separate different samples in multiplexed sequencing and UMIs tagging individual molecules prior to PCR, allowing later on (post mapping?) to de-duplicate the BAM file.

If this is the case should/could STAR grab both things and stick them into BC=BARCODE and BX=UMI
note that this is 10x genomic convention, official [SAMtags.pdf](https://github.com/samtools/hts-specs/blob/master/SAMtags.pdf) suggest to use BC and RX instead. 

OR should STAR aligner allow some other way of adding UMI information into BAM files, e.g similar to `-C` option in `bwa mem` (how?). If the UMI information isn't in the FASTQ read name then it can either be in the sequence read itself Or in separate FASTQ file (R2), either way STAR would need to do additional processing/demultiplexing to get BARCODE and UMI information. 

To me the former idea seems simpler to implement at least in the short term, it  has disadvantage of "breaking" / interfering with Iliumina's (any other sequencers) FASTQ header formatting. However for Ilumina at  least they have this in they [bcl2fastq manua, page 19](https://support.illumina.com/content/dam/illumina-support/documents/documentation/software_documentation/bcl2fastq/bcl2fastq2_guide_15051736_v2.pdf) 

```
@Instrument:RunID:FlowCellID:Lane:Tile:X:Y:UMI ReadNum:FilterFlag:0:IndexSequence or SampleNumber
```
One can assume that last thing in the FASTQ header (before the comment, bit to the right of the space) is UMI. Grab that and stick it into BX/RX tag `BX:Z:AATTCCGG`. 

I think `picard MarkDuplicates` already supports UMI based de-duplication, given that there is a tag in the BAM to leverage from.

```
READ_ON_BARCODE_TAG=BX
```

need to double check that !

What do you  guys think?

I should add that in our case we have two FASTQ files that are further demultiplexed into several other per sample FASTQ's. Those resulting FASTQ's have modified header with BARCODE:UMI entries. This is a separate step before alignment. And this is what I mean, if I could flag to STAR that these fastq have UMI in the header, please stick them into BX tag, no other magic is required. 
Cellular barcode isn't relevant for our particular case and can be simply ignored, but going forward you would want to support this for scRNA-seq I'm guessing

**Comment by alexdobin** [comment]
Hi Kirill

this is a very timely discussion as I will start actively working on it next week.
It seems to me adding BC and RX or BX tag is the way to go.

I can accommodate different FASTQ formats, both the bcl2fastq output, and the BARCODE:UMI one.
I am also thinking of extracting the UMI directly from the FASTQ reads as the bcl2fastq may not always be run with the correct parameters.

Cheers
Alex

**Comment by serine** [comment]
@alexdobin sorry about late ish reply had lots of work dropped on me.. yes that would be great. That is extraction of UMI and BARCODE from FASTQ header. More importantly is add that UMI/BARCODE info into bam file under right tag. 

I actually messed around a bit with your source. and quick and dirty implementation would be to include to include these lines

```
              case ATTR_BX:
                  *outStream<<"\tBX:Z"<<strrchr(readName, ':');
                   break;
```
[somewhere here](https://github.com/alexdobin/STAR/blob/5dbd58c9119ec7d1fafc0bba8723739588df4f5e/source/ReadAlign_outputTranscriptSAM.cpp#L287) I obviously don't do any checking there for when UMI doesn't exists and/or of a correct format.. 

I got really confused by what is  `attrN`. I thought  that what was building up bam tags, like a list of key:value pairs that you then write out, and I was trying to hack into that.. 

```
--- a/source/ReadAlign_alignBAM.cpp
+++ b/source/ReadAlign_alignBAM.cpp
@@ -274,0 +275,2 @@ int ReadAlign::alignBAM(Transcript const &trOut, uint nTrOut, uint iTrOut, uint
+
+
@@ -397,0 +400,3 @@ int ReadAlign::alignBAM(Transcript const &trOut, uint nTrOut, uint iTrOut, uint
+                    case ATTR_BX:
+                        attrN+=bamAttrArrayWriteInt(readName,"BX",attrOutArray+attrN,P);
+                        break;
```

Anyway I think that would be good implementation. This will enable (I believe) use of conventional picard MarkDuplicates utilising UMI information and thus removal of true PCR duplicates for example. As one immediate example

**Comment by lparsons** [comment]
Output of the `BX` tag for UMIs would be helpful for us too, any update on this?

**Comment by alexdobin** [comment]
Hi Lance, Kirill,

I had to work on other things and dropped the ball on this, but I am coming back to work more om single-cell pipelines. Do not hesitate to bump up your requests within 2-3 weeks.

Cheers
Alex

**Comment by yech1990** [comment]
@alexdobin 
Any progress on this feature request?

I think it is also necessary to **add cell barcode, UMI barcode tags to each record of `STARsolo` output**, which is indispensable in downstream analysis.

**Comment by alexdobin** [comment]
Hi YC,

the gene tag GX:Z: will be out in the next release, hopefully next week.
Uncorrected  CB and UMI can already be output with by adding CR,CY,UR,UY tags to the --outSAMattributes option.
Corrected CB and UMI (and the rest of CellRanger tags) are high on my list, hopefully in the next 2-3 weeks.

Cheers
Alex

**Comment by yech1990** [comment]
@alexdobin 

`--outSAMattributes CR,CY,UR,UY` trigger the following error...

```
EXITING because of FATAL INPUT ERROR: unknown/unimplemented SAM atrribute (tag): CR,CY,UR,UY
SOLUTION: re-run STAR with --outSAMattributes that contains only implemented attributes

Mar 15 21:42:05 ...... FATAL ERROR, exiting
```

**Comment by yech1990** [comment]
```bash
$ STAR --version
2.7.0e_0314
```

**Comment by yech1990** [comment]
After reading the source code, I figure out that I pass the argument in a wrong way. 
The correct format should be `--outSAMattributes CR CY UR UY`

It is a little confusing in the document. 

```
outSAMattributes                Standard
    string: a string of desired SAM attributes, in the order desired for the output SAM
                                NH HI AS nM NM MD jM jI XS MC ch ... any combination in any order
                                None        ... no attributes
                                Standard    ... NH HI AS nM
                                All         ... NH HI AS nM NM MD jM jI MC ch
                                vA          ... variant allele
                                vG          ... genomic coordiante of the variant overlapped by the read
                                vW          ... 0/1 - alignment does not pass / passes WASP filtering. Requires --waspOutputMode SAMtag
                                CR,CY,UR,UY ... sequences and quality scores of cell barcodes and UMIs for the solo* demultiplexing
                                Unsupported/undocumented:
                                rB          ... alignment block read/genomic coordinates
                                vR          ... read coordinate of the variant
```

- `All` is a argument, it look as if `CR,CY,UR,UY` is another argument.
- When passing arguments `vA`, `CR`..., do I still need to add additional parameters for `NH HI AS nM`? I can't find the description  in the document either.

**Comment by yech1990** [comment]
another error....

```bash
STAR ...........  ----outSAMattributes NH HI AS nM CR CY UR UY
```

```
Mar 15 21:54:10 ..... started STAR run
Mar 15 21:54:10 ..... loading genome
Mar 15 21:54:19 ..... started 1st pass mapping
Mar 15 21:57:44 ..... finished 1st pass mapping
Mar 15 21:57:45 ..... inserting junctions into the genome indices
Mar 15 21:58:56 ..... started mapping

EXITING because of FATAL BUG: unknown/unimplemented SAM atrribute (tag): 17
SOLUTION: contact Alex Dobin at dobin@cshl.edu
```

**Comment by alexdobin** [comment]
Hi YC,

Will remove commas from the manual. 
You need to list all the tags, as you did in the last post.
These new tags require BAM output, i.e. --outSAMtype BAM Unsorted {and/or} SortedByCoordinate 

Cheers
Alex

**Comment by jfreimer** [comment]
Hi Alex,

I was just wondering about the status of the GX:Z tag? I didn't see it in the release notes. Also is there any update on "Corrected CB and UMI (and the rest of CellRanger tags) are high on my list, hopefully in the next 2-3 weeks."

Thanks

**Comment by alexdobin** [comment]
Hi Jake,

timely question... just got it implemented on the development branch:
https://github.com/alexdobin/STAR/tree/soloDevelop
You can add CR UR CB UB GX GN  (in any combination) to the --outSAMattributes list when you are running STARsolo. Note that CB and UB require sorted BAM output, i.e. 
--outSAMtype BAM SortedByCoordinate 

Please test it and let me know how it goes - it will speed up the official release. :)

Cheers
Alex

**Comment by jfreimer** [comment]
Hi Alex,

I am developing a modified single cell sequencing protocol and was hoping to test the gene name output in bam without the umi/barcode info in read 2 to start. It looks like "--soloBarcodeReadLength 0” tells starSolo not to check for the barcode read, is that correct? If starSolo requires a barcode read, I can run with something for now as a test. I tried to run it without the barcode read and got an error.

/oak/stanford/groups/pritch/users/jake/seq/test/STAR/bin/Linux_x86_64/STAR --genomeDir ${JAKE}/genome/human/star_human2.7 --readFilesIn ../1_umitest_R2_subsample.fq.gz --readFilesCommand zcat --outSAMtype BAM SortedByCoordinate --outFilterMultimapNmax 1 --soloType Droplet --outSAMattributes GN --soloCBwhitelist None --soloStrand Unstranded --soloBarcodeReadLength 0
Aug 06 15:19:33 ..... started STAR run
Aug 06 15:19:33 ..... loading genome
Aug 06 15:21:25 ..... started mapping
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr
Aborted

Attached is the log file.

Thanks
