### ISSUE TITLE
EXITING because of fatal input ERROR:could not open readFilesIn=Read1

### ISSUE THREAD

**Issue by Chris-lang478** [alexdobin/STAR#1496]
Hello,
The command line is :
STAR runThreadN 20 genomeDir /xxxx/xxxx/xxxx/xxxx/index_dir/ readFilesIn SRRxxxxx_1.fastq SRRxxxxxxxx_2.fastq outFileNamePrefix L00

I've checked the path by "ls -l"command.  My data is from GEOdataset,SRA format and then splited by fasterq-dump. I've read all answers about "error :could not open readFilesIn=Read1",but i can't find a solution.
  
The log.out is :

<img width="412" alt="image" src="https://user-images.githubusercontent.com/99639869/155849523-8b8b8166-4dc3-432d-8e18-ef27f981025e.png">

**Comment by Chris-lang478** [comment]
I‘ve fixed it. Something wrong in my command line.  I wrote as STAR \  --\, I just changed it without \,then it work.

**Comment by arnuld-acog** [comment]
> I‘ve fixed it. Something wrong in my command line. I wrote as STAR \ --, I just changed it without ,then it work.

Hi Chris, I am having exactly same error. What you mean when you say "Something wrong in my command-line"? What did you fix?
