### ISSUE TITLE
Wrong chromosome lengths for chromosomes passed in by genomeFastaFiles

### ISSUE THREAD

**Issue by chihlee** [alexdobin/STAR#150]
Parameter file:
~~~~
genomeDir /scratch/9531364.1.whole/f22dik16.fvh/root/Sequence/STARindex2
genomeFastaFiles "/scratch/9531364.1.whole/f22dik16.fvh/root/Sequence/ExtraFasta/extra.fa" "/scratch/9531364.1.whole/f22dik16.fvh/root/Sequence/ERCC/ercc.fa"
~~~~

SAM header:
~~~~
@SQ     SN:chr21        LN:48129895
@SQ     SN:chr22        LN:51304566
@SQ     SN:chrX LN:155270560
@SQ     SN:chrY LN:59373566
@SQ     SN:chr11_gl000202_random        LN:59373566
@SQ     SN:chr17_gl000203_random        LN:40103
@SQ     SN:chr17_gl000204_random        LN:37498
~~~~

Looks like this is due to a bug in **genomeScanFastaFiles.cpp**. P->chrStart.size()>0 is not enough when we have both genomeDir and genomeFastaFiles in the parameter file. Perhaps changing 0 to a variable will do it.
~~~~
if (!flagRun && P->chrStart.size()>0) P->chrLength.push_back(N-P->chrStart.at(P->chrStart.size()-1)); //true length of the chr
~~~~

**Comment by alexdobin** [comment]
Hi @chihlee 

I am not sure what is wrong with the chr lengths in the SAM header - could you elaborate?

Cheers
Alex

**Comment by chihlee** [comment]
In the SAM header, the length of chr11_gl000202_random is the same as that of chrY, which is wrong. The length of chr11_gl000202_random should be 40103, the length of chr17_gl000203_random should be 37498 and so on. Looks like chrLength got one extra 59373566 inserted after chrY so everything is shifted down by 1.

This happens only when FASTAs (to be indexed on the fly) are provided in addition to the index.

**Comment by alexdobin** [comment]
Hi @chihlee 

I see the problem now. Could you please send me the Log.out file?

Cheers
Alex

**Comment by chihlee** [comment]
@alexdobin Log.out sent to your CSHL email.

**Comment by alexdobin** [comment]
Hi Chih,

you were right - this was a bug, thanks for pointing it out!
I have fixed it in the latest patch on GitHub [master](https://github.com/alexdobin/STAR/archive/master.zip), please try it out and let me know if it works as expected now.

Cheers
Alex

**Comment by chihlee** [comment]
Hello Alex,

I tried the master and the SAM header looks good. Thanks!

Best,
Steve
