### ISSUE TITLE
STAR mapping --outFilterMultimapNmax: error

### ISSUE THREAD

**Issue by sanchezalcaniz** [alexdobin/STAR#1500]
Hi 

I am using STAR for my RNAseq mapping and I came across a problem. I want to allow the reads to map to one loci so I am using the next option:
--outFilterMultimapNmax 1
 
the full command I use is:
STAR --runThreadN 15 \
--readFilesCommand zcat \
--genomeDir gustRNAseq/dmel_index \
--sjdbGTFfile gustRNAseq/dmel_gtf/dmel-all-r6.44.gtf \
--readFilesIn gustRNAseq/Data_seq/File_1_R1.fastq.gz gustRNAseq/Data_seq/File_1_R2.fastq.gz \
--outFileNamePrefix gustRNAseq/Data_STAR_aligned/File_1_STAR_aligned/File_1_STAR_aligned \
--outSAMtype BAM SortedByCoordinate \
--twopassMode Basic \
--outSAMstrandField intronMotif \
--outFilterIntronMotifs RemoveNoncanonical \ 
--outFilterMultimapNmax 1

everything works, and I got a BAM file as output with a final log file indicating the number of aligned reads. However I got this error:
bash: --outFilterMultimapNmax: command not found...

I do not know how to solve the problem as I have not been able to find the solution in the manual neither in any other place.

Thanks
Juan

**Comment by alexdobin** [comment]
Hi Juan,

this is a problem with formatting of the command lines, please check that you have no spaces after "\" symbol.

Best,
Alex

**Comment by sanchezalcaniz** [comment]
Hi Alex

I tried and that solved the problem!!

Thank you so much
Juan

------------------------------------------------------------------------------------------------------------------------------------------------------------------
Juan A. Sánchez-Alcañiz, PhD
Group Leader, Ramón y Cajal Fellow
Instituto de Neurociencias UMH-CSIC
Lab. 209
Campus de San Juan
Avda. Ramón y Cajal s/n
03550 San Juan de Alicante (Alicante)
Spain
+34965233772

***@***.***
http://in.umh-csic.es/IP/SanchezAlcaniz.html
