### ISSUE TITLE
Correct use of STAR "--outFilterScoreMin 1" setting?

### ISSUE THREAD

**Issue by cwarden45** [alexdobin/STAR#1507]
Hi,

I recently noticed something curious that seemed to be captured if the STAR mapping quality score was exactly 0, when visualizing the alignment using IGV.

For example, you can see some very high 5` coverage of a gene candidate that we/I think may largely come from a locus that has not yet been characterized (versus the coverage for the other exons, which is more similar):

![YLEC8_high_coverage_0_mapping_quality](https://user-images.githubusercontent.com/7663033/157977051-5408c500-50f2-4faa-b717-54dabcc70d36.png)

If I look at the TopHat2 alignments, then I don't see this same trend.  However, the image above made me wonder what would happen if I excluded the reads (for all gene annotations being checked).

If only for visualization, then I believe that I can filter the .bam files with samtools.  However, I am using the in the **_SJ.out.tab** file for the gene annotation evidence, so I was hoping that changing a STAR parameter would _both_ remove the reads for visualization as well as provide alternative splice junction counts to check for the impact of changing this parameter.

However, the problem is that the screenshot above comes from **after** the `--outFilterScoreMin 1` parameter was added, and my understanding is that my attempt to filter reads with mapping qualities of exactly 0 was not successful.

I can also check some individual reads within 2 regions of that gene:

**High Coverage, Test Filtering**:
```
SRR924582.33071302	419	Contig1	228948	0	28M2D50M106N22M	=	228992	250	TCCTGTTGGTCTCCTTCTCCCATAGCGGGTGGAAGTATTGGACTCCAGCAGCAATATCTGTACATCCTCTTCTGGGAGCTTGTTGGGATCCTTCTCCTCT	CCCFFFFFHHHHHJJJJJJJJJJJJIJJJ?HHFIIDHIJJJJJJJJJJJJIIJJJHHHHGHHFFFDFFFEEEEECDDDDDDDDDDDDDCDDDDDCDDDDD	NH:i:6	HI:i:2	AS:i:192	nM:i:0	XS:A:-
SRR924582.33071302	419	Contig1	228948	0	28M2D50M106N22M	=	231956	3214	TCCTGTTGGTCTCCTTCTCCCATAGCGGGTGGAAGTATTGGACTCCAGCAGCAATATCTGTACATCCTCTTCTGGGAGCTTGTTGGGATCCTTCTCCTCT	CCCFFFFFHHHHHJJJJJJJJJJJJIJJJ?HHFIIDHIJJJJJJJJJJJJIIJJJHHHHGHHFFFDFFFEEEEECDDDDDDDDDDDDDCDDDDDCDDDDD	NH:i:6	HI:i:3	AS:i:191	nM:i:0	XS:A:-
SRR924582.13414158	419	Contig1	228950	0	78M106N22M	=	228997	253	CTGTTGGTCTCCTTCTCCCATAGCGGGTGTGGAAGTATTGGACTCCAGCAGCAATATCTGTACATCCTCTTCTGGGAGCTTGTTGGGATCCTTCTCCTCT	CCCFFFFFHHHHHJJJJJJHJIJIJJJGHGHIFHHAGIIIJIIJJJJIJJFHIJJIHHHHHHHFFFFFFDEEEEEEDDDDDDDDDDDBCDDDDCDCCC<>	NH:i:6	HI:i:2	AS:i:198	nM:i:0	XS:A:-
SRR924582.13414158	419	Contig1	228950	0	78M106N22M	=	231961	3217	CTGTTGGTCTCCTTCTCCCATAGCGGGTGTGGAAGTATTGGACTCCAGCAGCAATATCTGTACATCCTCTTCTGGGAGCTTGTTGGGATCCTTCTCCTCT	CCCFFFFFHHHHHJJJJJJHJIJIJJJGHGHIFHHAGIIIJIIJJJJIJJFHIJJIHHHHHHHFFFFFFDEEEEEEDDDDDDDDDDDBCDDDDCDCCC<>	NH:i:6	HI:i:3	AS:i:197	nM:i:0	XS:A:-
SRR924582.36289643	355	Contig1	228950	0	78M106N22M	=	228981	237	CTGTTGGTCTCCTTCTCCCATAGCGGGCGTGGAAGTATTGGACTCCAGCAGCAATATCTGTACATCCTCTTCTGGGAGCTTGTTGGGATCCTTCTCCTCT	??<:A:+2ADDDABE<CBBF@FIE>EE0@D@ACEC==7=CADC>@@EDD@CAADDDADA@@A@DD<AA>5>;5:3555=<3><:220<3<>>AAA>AA?A	NH:i:6	HI:i:2	AS:i:196	nM:i:1	XS:A:-
SRR924582.36289643	355	Contig1	228950	0	78M106N22M	=	231945	3201	CTGTTGGTCTCCTTCTCCCATAGCGGGCGTGGAAGTATTGGACTCCAGCAGCAATATCTGTACATCCTCTTCTGGGAGCTTGTTGGGATCCTTCTCCTCT	??<:A:+2ADDDABE<CBBF@FIE>EE0@D@ACEC==7=CADC>@@EDD@CAADDDADA@@A@DD<AA>5>;5:3555=<3><:220<3<>>AAA>AA?A	NH:i:6	HI:i:3	AS:i:195	nM:i:1	XS:A:-
SRR924582.3243513	403	Contig1	228950	0	78M106N22M	=	228923	-233	CTGTTGGTCTCCTTCTCCCATAGCGGGTGTGGAAGTATTGGACTCCAGCAGCAATATCTGTACATCCTCTTCTGGGAGCTTGTTGGGATCCTTCTCCTCT	?BDDDD@?BBBCBDDA?CCDDDDDFFFHHHHJJJJJJJJIIHIIJJJJJJJJIJJJIIJJIIJJJJJIJJJJJJJJJJJJJJJJJJJHHHHHFFFFFBB;	NH:i:6	HI:i:5	AS:i:198	nM:i:0	XS:A:-
SRR924582.25836351	339	Contig1	228950	0	78M106N22M	=	228923	-233	CTGTTGGTCTCCTTCTCCCATAGCGGGTGTGGAAGTATTGGACTCCAGCAGCAATATCTGTACATCCTCTTCTGGGAGCTTGTTGGGATCCTTCTCCTNT	DDDDDBBDDDAC@@DDDCDDDDDDFFHHHHHJIJJIGHHHGFIDIJJJJJIJJJJJJJJGIGJGIJJJJJJJJJJJIJJJIGJJJJJHHHHHFFFDB4#C	NH:i:6	HI:i:2	AS:i:192	nM:i:2	XS:A:-
SRR924582.29637943	403	Contig1	228950	0	71M113N29M	=	228920	-243	CTGTTGGTCTCCTTCTCCCATAGCGGGTGTGGAAGTATTGGACTCCAGCAGCAATATCTGTACATCCTCTTCTTGTTGGGATCCTTCTCCTCTGGTGTGC	DDDDDDDBDBBDDDDDDDDDDDDDFFFHHHHHHJJJJJJJJHJJJJJJJJJJJJJJJJJJIHJJGJJJJJJIJJJJIGJICJJJJJJHHHHHFFFFFCCC	NH:i:10	HI:i:7	AS:i:197	nM:i:0	XS:A:-
SRR924582.46009938	403	Contig1	228950	0	78M106N22M	=	228932	-224	CTGTTGGTCTCCTTCTCCCATAGCGGGTGTGGAAGTATTGGACTCCAGCAGCAATATCTGTACATCCTCTTCTGGGAGCTTGTTGGGATCCTTCTCCTCT	DDDDDDDDDDDDDDDDDDDDBDDDFFHHHHHIJJJJJJJIJHJIJJJJIIJIJJJJJJJJIHJJJJJJJJJJJJJJJJJJJJJJJJJHHHHHFFFFFCCC	NH:i:6	HI:i:5	AS:i:196	nM:i:0	XS:A:-
```

**More "Expected" Coverage, Larger Fraction OK?**:
```
SRR924582.19018356	99	Contig1	227876	3	67M276N33M	=	228218	423	CATCGCTCCATGTCCACTGGGCGTCCTCTTCTTCCCTGTGCAGCCCGATCCAACAGTTTGCCGGGCCCATCTCCTCCGCACTGCCTATGGTGGCCAGGGA	CCCFFFFFHHHHHJJJJJJJJJJIJJJJIIIJJJJJJJIJJJJJJJJIJJIJJJJFEHGHHHFFDDDDDDDDDCDACDDDDDCDCDDDDD@C@BDADDBB	NH:i:2	HI:i:1	AS:i:179	nM:i:0	XS:A:-
SRR924582.34661263	419	Contig1	227879	3	64M276N36M	=	228296	516	CGCTCCATGTCCACTGGGCGTCCTCTTCTTCCCTGTGCAGCCCGATCCAACAGTTTGCCGGGCCCATCTCCTCCGCACTGCCTATGGTGGCCAGGGAAGC	CCCFFFFFHHHHHJJJJIJJJIJJJJJIJJJJJIJJJJJJJJJJFGIJIJIJJHIJIIHHFFDDDDDDDCDDDDDDDDDDDDDDDDD@C?BDCBDD####	NH:i:2	HI:i:2	AS:i:197	nM:i:0	XS:A:-
SRR924582.32571232	83	Contig1	227879	3	64M276N36M	=	227796	-459	CGCTCCATGTCCACTGGGCGTCCTCTTCTTCCCTGCGCAGCCCGATCCAACAGTTTGCCGGGCCCATCTCCTCCGCACTGCCTATGGTGGCCAGGGAAGC	<DDCDDDDDCDDDDDDDDDDDDDCDDDDDDDDDDDDDDDDDDDEEEFFFFFFHHHJIJJIIJJJIHEIIJIHJJJIHJJJJJJJJJJHHHHHFFFFFCCC	NH:i:2	HI:i:1	AS:i:192	nM:i:3	XS:A:-
SRR924582.52015109	83	Contig1	227879	3	64M276N36M	=	227796	-459	CGCTCCATGTCCACTGGGCGTCCTCTTCTTCCCTGTGCAGCCCGATCCAACAGTTTGCCGGGCCCATCTCCTCCGCACTGCCTATGGTGGCCAGGGAAGC	BDDDDDDDDDDDDDDDDDDDDDDCCCBDDDDDDDDDDDDDDDDEEEFFFFFFHHHIJJJJIJJJJJIIGJIEJIJJJJIJJJJJIHDHHHHHFFFFFCCC	NH:i:2	HI:i:1	AS:i:198	nM:i:0	XS:A:-
SRR924582.62973869	83	Contig1	227879	3	64M276N36M	=	227863	-392	CGCTCCATGTCCACTGGGCGTCCTCTTCTTCCCTGTGCAGCCCGATCCAACAGTTTGCCGGGCCCATCTCCTCCGCACTGCCTATGGTGGCCAGGGAAGC	<DDDDDDDDCDDDDDDDDDDDDDDCDA<DBDDDDDDDDDDDDDEEEFFFEFFHHHGJJJJJJJJJJHIGJIGJIIIHJGJJIJJJJJHHHHHFFFFFCCC	NH:i:2	HI:i:1	AS:i:179	nM:i:0	XS:A:-
SRR924582.54773464	99	Contig1	227882	3	61M276N39M	=	228244	462	TCCATGTCCACTGGGCGTCCTCTTCTTCCCTGTGCAGCCCGATCCAACAGTTTGCCGGGCCCATCTCCTCCGCACTGCCTATGGTGGCCAGGGAAGCTCC	C@CFFFFFHHHHHJJJJJJJIIJJHIJJIJJJJIGIJJJJJJIHIGHIIJIIJJEHIHFDCDDDCCDCDCDDDDD<CDDD>ACCCDBBDCBBB8<BAD@:	NH:i:2	HI:i:1	AS:i:196	nM:i:1	XS:A:-
SRR924582.29452887	163	Contig1	227886	3	57M276N43M	=	227918	408	TGTCCACTGGGCGTCCTCTTCTTCCCTGTGCAGCCCGATCCAACAGTTTGCCGGGCCCATCTCCTCCGCACTGCCTATGGTGGCCAGGGAAGCTCCGTGG	CCBFFFFFHHHHHJJJJJJJJJJJJJJJHJJJJIIJJIJJJJJJJJHIJJIIJJHFFDDDEDDDDDDDDDDDDDDDDDDD>CBDDDBDDDDDDCDDDA<>	NH:i:2	HI:i:1	AS:i:198	nM:i:0	XS:A:-
SRR924582.6823550	419	Contig1	227895	0	69M726N31M	=	227941	872	GGCGTCCTCTTCTTCCCTGTGCAGCCCGATCCAACAGTTTGCCGGGCCCTGGAAGCGCATCATGAAATCCGGTCGATATCACCAGCACCACCAGCATGAG	CCCFFFFFHHHHHJJJJJJJIJIHIJJIJJJJJJJJJIJIJIJGHIIIJHHHHHFFFDDDDDDDDDCDDDDDBDDDBDDDDDCDDDDDDDDDBBBCDDCC	NH:i:6	HI:i:4	AS:i:198	nM:i:0	XS:A:-
SRR924582.6823550	419	Contig1	227895	0	69M726N31M	=	230895	3836	GGCGTCCTCTTCTTCCCTGTGCAGCCCGATCCAACAGTTTGCCGGGCCCTGGAAGCGCATCATGAAATCCGGTCGATATCACCAGCACCACCAGCATGAG	CCCFFFFFHHHHHJJJJJJJIJIHIJJIJJJJJJJJJIJIJIJGHIIIJHHHHHFFFDDDDDDDDDCDDDDDBDDDBDDDDDCDDDDDDDDDBBBCDDCC	NH:i:6	HI:i:6	AS:i:197	nM:i:0	XS:A:-
SRR924582.11433055	419	Contig1	227895	0	69M726N31M	=	227934	865	GGCGTCCTCTTCTTCCCTGTGCAGCCCGATCCAACAGTTTGCCGGGCCCTGGAAGCGCATCATGAAATCCGGTCGATATCACCAGCACCACCAGCATGAG	CCCFFFFFHHHDHJJJJJJIJJIJJJJJJJJJJGJJJHIJJJJHBHIJJHEEHHFFFDDDDDDDDDDDDDDD@BDBDDDDEDDDBBCBDDDBDBDDA>CC	NH:i:6	HI:i:4	AS:i:198	nM:i:0	XS:A:-
```

Here is the full command that I am using to generate that alignment:
```
STAR --genomeDir $REF --readFilesIn $R1 R2 --runThreadN 4 --outFileNamePrefix $STARPREFIX --outFilterScoreMin 1 --alignIntronMax 2000 --alignSJoverhangMin 20 --alignSJDBoverhangMin 20 --outFilterMismatchNoverLmax 0.1 --outFilterIntronMotifs RemoveNoncanonical --outSAMstrandField intronMotif
```

**So, I would very much appreciate it if if you can answer any or all of the following questions:**

**1)** Am I correctly understanding that `--outFilterScoreMin 1` should be removing the reads with mapping qualities of exactly 0 from _both_ the **.bam** file and counting for the splice junction evidence in the **_SJ.out.tab** file?

**2)** Am I correct that it looks like this change in parameter was not carried out?  If so, is there something like a different parameter that is not compatible for this setting? 

**3)** Out of curiosity, should there really be something important that could be different from multi-mapped reads with mapping scores of exactly 0 (versus mapping qualities of 1 or 3)?  There are large duplications and gene copies that are 100% identical, so most genes need to count multi-mapping reads for the region that this project is trying to study.

Thank you very much!

Sincerely,
Charles

**Comment by alexdobin** [comment]
Hi Charles,

the MAPQ (column 5) in the BAM file represents the multimapping status of the read, with 255 reserved for unique mappers, and the values below are for multimappers, according to this formula MAPQ=int(10*log10(1/Nloci)). MAPQ=0 is for Nloci>=5.

On the other hand, ```--outFilterScoreMin``` controls the alignments score, which is output as AS attribute.
The minimum threshold of this score is also controlled by ```--outFilterScoreMinOverLread0.66 (default)```, so changing just ```--outFilterScoreMin``` will not change the filtering, since the former condition is more stringent.

Best,
Alex

**Comment by cwarden45** [comment]
Hi Alex,

Thank you very much for your response.

I think this answers part **3)** in that there should be 5 or more mapped loci for reads that I/we are expecting to largely come from other loci.

The other multimapped mapping quality scores are positive (but small), but I see that the STAR manual says that he mapping quality is **int(-10*log10(1-1/Nmap))**  for multi-mapped reads.  This is slightly different than what you described, but I think there were just a couple typos.

If that is the case, then I the scores should be able to be described as follows:

<table>
  <tbody>
    <tr>
      <th align="center">Nloci</th>
      <th align="center">MAPQ</th>
    </tr>
    <tr>
            <td align="center">1</td>
            <td align="center">255</td>
    </tr>
    <tr>
            <td align="center">2</td>
            <td align="center">3</td>
    </tr>
    <tr>
            <td align="center">3</td>
            <td align="center">2</td>
    </tr>
    <tr>
            <td align="center">4</td>
            <td align="center">1</td>
    </tr>
    <tr>
            <td align="center">5 (or more)</td>
            <td align="center">0</td>
    </tr>
</tbody>
</table>

For questions **1)** and **2)**, am I correctly understanding that there is not a way to test excluding the multimapped reads with alignment scores of 0 (which in turn would also decrease the reads considered for the paired **_SJ.out.tab** file)?

In the version of STAR that I am using (v2.5), I see that **outFilterScoreMin** is defined as "*alignment will be output only if its score is higher than or equal to this value*", **outFilterScoreMinOverLread** is defined as "*same as outFilterScoreMin, but  normalized to read length (sum of mates' lengths for paired-end reads)*", and **outFilterMismatchNoverLmax** is defined as "*alignment will be output only if its ratio of mismatches to read length is less than or equal to this value.*"

I tested removing `--outFilterMismatchNoverLmax 0.1`, but that still did not have the desired effect (there were still reads with MAPQ=0).  Also, I found that to be helpful, so I hope that I can keep that parameter.

If the more stringent criteria is used, then I think that I am confused why alignments are still being produced if `--outFilterScoreMin 1`.  However, I am not sure if adding a smaller *outFilterScoreMinOverLread* might help.

Also, it looks like the default for **outFilterMultimapNmax** is 10.  So, I will also try setting that to 4.

If that doesn't work and you can confirm that there is not in fact a way to accomplish what I am trying to do (remove reads with MAPQ of 0 from both alignment and splice junction evidence), then I will close the ticket.

Thank you again!

Sincerely,
Charles

**Comment by alexdobin** [comment]
Hi Charles,

your formula for MAPQ is correct! I will fix my post.
```--outFilterMultimapNmax 4``` should indeed remove MAPQ=0 reads.

Best,
Alex

**Comment by cwarden45** [comment]
Hi Alex,

I will need to take some time to look at the effect for the full set of gene candidate annotations.  However, I think `--outFilterMultimapNmax 4` has accomplished what I was trying to achieve:

**Alignment Visualization**:

![STAR_param12](https://user-images.githubusercontent.com/7663033/158684038-6c90927b-8874-463d-9dbd-b1cc79737c01.png)

Coverage is now more even between the 2 gene candidates contained within the window above.

**Multimapped Splice Junction Counts**:
*Before*:
```
Contig1	227634	227770	2	2	0	0	9	44
Contig1	227634	227856	2	2	0	0	463	50
Contig1	227702	227856	2	2	0	0	2	35
Contig1	227943	228218	2	2	0	0	33	47
Contig1	227964	228218	2	2	0	0	2264	50
Contig1	227964	228689	2	2	0	0	45	47
Contig1	228054	228218	2	2	0	0	1	45
Contig1	228297	228689	2	2	0	0	1	21
Contig1	228303	228689	2	2	0	0	2	31
Contig1	228401	228664	2	2	0	0	1	38
Contig1	228401	228689	2	2	0	0	1783	50
Contig1	228801	228879	2	2	0	0	1	32
Contig1	228801	228885	2	2	0	0	1035	50
Contig1	229021	229133	2	2	0	0	2	46
Contig1	229028	229133	2	2	0	0	451	50
Contig1	229034	229127	1	1	0	0	2	39
Contig1	229041	229133	2	2	0	0	11926	50
Contig1	229073	229133	2	2	0	0	36	46
Contig1	229087	229133	2	2	0	0	2	47
Contig1	229189	229460	2	2	0	0	3	26
Contig1	229216	229460	2	2	0	0	11253	50
Contig1	229224	230012	1	1	0	0	1	25
Contig1	229232	229460	2	2	0	0	16	47
Contig1	229238	229460	2	2	0	0	6	38
Contig1	229262	229460	2	2	0	0	4462	50
Contig1	229265	229460	2	2	0	0	20807	50
```
*After*:
```
Contig1	227634	227856	2	2	0	0	424	50
Contig1	227702	227856	2	2	0	0	2	35
Contig1	227943	228218	2	2	0	0	33	47
Contig1	227964	228218	2	2	0	0	2093	50
Contig1	227964	228689	2	2	0	0	25	47
Contig1	228303	228689	2	2	0	0	2	31
Contig1	228401	228664	2	2	0	0	1	38
Contig1	228401	228689	2	2	0	0	1777	50
Contig1	228801	228879	2	2	0	0	1	32
Contig1	228801	228885	2	2	0	0	1019	50
Contig1	229028	229133	2	2	0	0	3	33
Contig1	229041	229133	2	2	0	0	37	50
Contig1	229216	229460	2	2	0	0	77	50
Contig1	229262	229460	2	2	0	0	3	50
Contig1	229265	229460	2	2	0	0	1	33
```

So, I will now close the ticket.

Thank you very much for your help!

Sincerely,
Charles
