### ISSUE TITLE
Junction locations, exon expression levels

### ISSUE THREAD

**Issue by amadeusX** [alexdobin/STAR#151]
Dear Alex,
Starting from BAM files downloaded from ENCODE (generated by your STAR), how can we extract junctions and exon-level expressions?
Thank you.

Steve
Istvan (Steve) Ladunga
sladunga@unl.edu

**Comment by alexdobin** [comment]
Hi Steve,

for junctions, I have a simple awk script in the extras/scripts/ directory of the STAR distribution. You can use it as follows:

$ samtools view Aligned.out.bam | awk -f sjFromSAMcollapseUandM.awk | sort -V > SJ

SJ will contain intron coordinates and unique/multiple counts (i.e. columns 1,2,3,7,8 of the SJ.out.tab which STAR produces for every run).

For exon-level expression, you would need to use an isoform quantification algorithm, such as RSEM or Cufflinks. You can also simply count reads that ovelrap exons using bedtools.

Cheers
Alex

**Comment by amadeusX** [comment]
Privet Alex,


Spasibo bolshoe za pomosh! Ya predprochitayu picat SAM file chtobi xranit pamyat, no rabotaet prekrashno! Eshe nado podtrevdit introni, na perviy glaz, vse v porjadke!


Izvniy za oshibki::)))


Spasibo bolshoe,


Istvan

Istvan (Steve) Ladunga
Professor of Computational Biology
Department of Statistics
346C Hardin Hall North

Lincoln, NE 68583-0963
Phone: (402) 472-6074<tel:%28402%29%20472-6074>
sladunga@unl.edu<mailto:sladunga@unl.edu>

________________________________

**Comment by amadeusX** [comment]
Hi Alex,

Thank you so much for your help! This has solved the issue.

Kind regards,

Istvan
