### ISSUE TITLE
Identify gene-cell matrix incorporated reads in the BAM file

### ISSUE THREAD

**Issue by AHPool** [alexdobin/STAR#1516]
Hi,

I have a question regarding the STARSolo output BAM file. Namely, I am trying to identify which subset of reads in the "Aligned.sortedByCoord.out.bam" file constitute the final feature-barcode matrix. Specifically, I am wondering whether there is a bam tag that I could extract from the file (for example with Bioconductor::GenomicAligments library in R). In Cell Ranger output BAM files the xf tag serves this purpose but despite extensive efforts I have not found anything in the STARSolo output BAM. I've explored a handful of tags to little avail (NH HI AS nM GX GN sM sQ etc.).

Thank you in advance!

**Comment by alexdobin** [comment]
Hi @AHPool,

the reads that have valid CB, UB and GX tags contribute to the count matrix.
The reads with the same CB/UB/UMI tags contribute one to the counts (i.e. are "collapsed").

**Comment by AHPool** [comment]
Excellent, thank you, this resolved my issue! Just to specify for someone who is trying to figure out the same problem - all CB and UB sequences that fall below the set length of barcode sequences, also need to be removed. Thank you again!
