### ISSUE TITLE
Use STARsolo with Split-seq data

### ISSUE THREAD

**Issue by jentiger82** [alexdobin/STAR#1517]
I would like to analyze my Split-seq data using STARsolo. I have several questions in regard to that. With Split-seq you have an UMI (base 1-10 in read 2) and three separate barcodes (bases 11-18, 49-56 and 87-94). This corresponds to CB_UMI_Complex. In this case, do I use several whitelist files, so one for each part of the barcode? Do I have to define --soloCBstart, --soloCBlen, --soloUMIstart, --soloUMIlen und --soloBarcodeReadLength? How does --soloCBposition have to look like (I assume: 0_10_0_17 0_48_0_55 0_86_0_93)? The third part of the barcode (87-94) also corresponds to the sample barcode, in this case I am combining random hexamer and poly-T primers, so the same cell can have two different barcodes. Is there a way to take care of this, similar to zUMIs?

Thanks, Jenny

**Comment by alexdobin** [comment]
Hi Jenny,

here are the parameters I have tested for the commercial Split-seq data, relatively recent:
```
soloType                          CB_UMI_Complex
soloCBposition                    0_10_0_17 0_48_0_55 0_78_0_85
soloUMIposition                   0_0_0_9
soloCBwhitelist                   CB23.txt   CB23.txt   CB1.txt
soloCBmatchWLtype                 EditDist_2
clipAdapterType                   CellRanger4
clip5pAdapterSeq                  AAGCAGTGGTATCAACGCAGAGTGAATGGG
```

**Comment by jentiger82** [comment]
The following settings worked for me (when not using the commercial version of the SPLiT-seq kit):
STAR --runMode alignReads --runThreadN 4 --genomeDir /home/jenny/Documents/Annotation/m39_STAR --readFilesIn SL1_R1.fastq.gz SL1_R2.fastq.gz --readFilesCommand zcat --outFileNamePrefix ./SL1. --outSAMattributes NH HI nM AS CR UR CB UB GX GN sS sQ sM --outSAMtype BAM SortedByCoordinate --outFilterScoreMinOverLread 0 --outFilterMatchNminOverLread 0 --outFilterMatchNmin 0 --soloType CB_UMI_Complex --soloCBwhitelist /home/jenny/Documents/barcodeList.txt /home/jenny/Documents/barcodeList.txt /home/jenny/Documents/barcodeList.txt --soloBarcodeReadLength 0 --soloCBposition 0_10_0_17 0_48_0_55 0_86_0_93 --soloUMIposition 0_0_0_9 --soloCBmatchWLtype EditDist_2 --soloFeatures Gene GeneFull Velocyto --soloMultiMappers EM --soloCellReadStats Standard

However, to continue one needs to merge barcodes if the polyT and random hexamer primers in the RT reaction were combined in one well. For this I wrote a Python script, which also creates separate SAM files for each sample based on barcode 1. I can make it available to everyone, who is interested. After this step one has to re-run STARsolo for the actual quantification using SAM file input. However, I am wondering how I have to change the settings above as I have the resolved barcodes in CR and UR SAM file tags? Do I just leave out --soloCBposition and --soloUMIposition?

Thanks, Jenny

**Comment by LJK1991** [comment]
Hello Alex and Jenny,
I am also trying to analyze SPLiT-seq samples and i had the same question as Jenny.
I am pretty much running the same command as Jenny and was wondering whether the estimated cells actually make any sense in this case, because the first barcoding are actually half the barcodes due to the fact one being hexamers and the other PolyT. 

I guess you can indeed write some function to sum the reads om of the same cell/well in the count matrix, but wouldn't it be easier to do it beforehand in the SAM/BAM? mainly because you could then apply the --soloCellFilter options

Regards, 
Lucas

**Comment by jentiger82** [comment]
Dear Alex and Lucas,

I indeed am running the merging script using the SAM files created with the first round of STARsolo. I am exchanging the barcode from the polyT primer with the one from the random hexamer and based on this barcode I also assign the mapped read to the associated sample. To re-run the STARsolo quantification with the adapted SAM file I also remove the _ from the combined barcode. I prefer this as I will obtain SAM files for each sample as well. 
Best, Jenny

**Comment by alexdobin** [comment]
Hi Jenny and Lucas,

Jenny's approach is certainly valid!
Another option would be to operate directly on the barcode FASTQ file: split it by sample and replace hexamer barcodes with polydT.

**Comment by jelber2** [comment]
@alexdobin are you making these whitelists by using something such as https://github.com/CGATOxford/UMI-tools

> soloType                          CB_UMI_Complex
> soloCBposition                    0_10_0_17 0_48_0_55 0_78_0_85
> soloUMIposition                   0_0_0_9
> soloCBwhitelist                   CB23.txt   CB23.txt   CB1.txt
> soloCBmatchWLtype                 EditDist_2
> clipAdapterType                   CellRanger4
> clip5pAdapterSeq                  AAGCAGTGGTATCAACGCAGAGTGAATGGG

**Comment by alexdobin** [comment]
Hi Jean,

these whitelists are specific to Split-seq.

**Comment by jelber2** [comment]
Thanks, I thought maybe these were not known prior to the experiment (random sequences not from pre-determined whitelist)

**Comment by BlayvasD** [comment]
Hi Alex and Jenny,

Where can I find the whitelists "CB23.txt" and "CB1.txt"?

Thank you,
David.

**Comment by alexdobin** [comment]
Hi David,

I got them from collaborators who got them from the company.
It's probably best to request them directly from the company support to make sure they are up-to-date.

**Comment by ainsku** [comment]
Hi Alex

I'm trying to align Split-seq data with STAR and I do get uniquely mapped reads ~60%, but the barcodes are not recognised correctly. In the bam output file the cell barcode sequence is the combined barcodes from the three whitelists combined with underscores `CR:Z:ACCCTAAC_CCTAACCG_GGTATGAA` and there is no cell barcode or UMI barcode identifiers `CB:Z:-  UB:Z:-`. Here is the command I use for running STAR, the 2nd and 3rd whitelist are the same and I've converted both into a txt file with only the column that has the barcode in them.

Thanks for your help and an amazing tool!

Best, Aino

`STAR --readFilesIn $R1 $R2 --outFileNamePrefix $out --genomeLoad NoSharedMemory --genomeDir /my/path/GRCh38_rel109_gencode_rel43_index --readFilesCommand zcat --runThreadN $cores --soloType CB_UMI_Complex --soloCBwhitelist $whitelist1 $whitelist2 $whitelist2 --soloBarcodeReadLength 0 --soloCBposition 0_10_0_17 0_48_0_55 0_78_0_85 --soloUMIposition 0_0_0_9 --soloCBmatchWLtype 1MM --soloFeatures GeneFull_Ex50pAS --soloMultiMappers EM --outSAMattributes NH HI nM AS CR UR CB UB GX GN sS sQ sM --outSAMtype BAM SortedByCoordinate >/dev/null`
