### ISSUE TITLE
STAR mapping error using STARconsensus due to chromosome length mismatches

### ISSUE THREAD

**Issue by jcm6t** [alexdobin/STAR#1526]
Alex,
Thanks for supporting STAR.

This is a little complicated but bear with me.

We are using STARconsensus to handle a genetic indel in one particular gene. The gene is a transfected human transgene into mouse and so we have spiked the mouse genome with the transgene as a separate pseudo chromosome (NM_003661.3 in this case). So the experiment contains two groups of mice carrying one of two genotypes of the transgene - one with 6 bp insertion and one without the insertion. We expect one full length transcript from the transgene but of course interested in any novel SJs STAR may find.

There are 6 exons in the tg and the last, 6th exon contains this 6bp indel. We added the full transcript sequence to the genome fasta file without any other 'padding' around the gene, so the pseudo chromosome is exactly equal to the length of the transgene with the 6bp insertion.

The full-length spiked-in tg/transcript is 2863 in length which becomes 2857 for mice with the deletion genotype of the tg.

Index generation seemed to work using a single entry sparse VCF file to represent this indel with --genomeTransformVCF and Haploid setting.

At mapping time we saw the error:

!!!!! WARNING: while processing sjdbGTFfile=mmu_transgene.gtf, line:
NM_003661.3	<abbreviated...> 
 exon end = 2863 is larger than the chromosome NM_003661.3 length = 2857 , will skip this exon

In our 'spiked' GTF file, exon 6 was annotated as 
NM_003661.3	NCBI_RefSeq	exon	483   2863	.	+	. etc...

Therefore what we think is happening is that at mapping time, STAR is comparing the GTF to the chromosome lengths in STAR-INDEX, but is not properly handling the chromosome length changes due to the indel. 

We checked in STAR-Index/ChrNameLength.txt, and found:

NM_003661.3	2857

 ie the pseudo chromosome transgene with the smaller of the two chromosome lengths and is clearly not compatible with the full length transgene.

At mapping time we included the option:
   --genomeTransformOutput SAM SJ

 to transform both SAM and SJ since the user guide said "string(s)" . STAR did not raise an error at this option setting - we wondered if it really should only have one string selected.

Presumably this is likely to be a more general issue than the very specific case here and we might have been the ones to detect it because we were focusing on a single genetic variant in this very artificial situation. The user guide does state that STARconsensus will handle a VCF containing indels, but it raises the question of how to handle the alternative chr sizes vis-a-vis the GTF annotation positions.

Thanks very much.

**Comment by alexdobin** [comment]
Hi @jcm6t 

sorry for the delayed reply.
If you used the GTF file at the genome generation step, you cannot (and do not need to) use it again at the mapping step.

**Comment by jcm6t** [comment]
okay - thanks
