### ISSUE TITLE
Feature Quantification in STARsolo

### ISSUE THREAD

**Issue by sjroth** [alexdobin/STAR#1529]
Hi, I was wondering if it is possible to quantify the mapping to particular genomic features for STARsolo output. That is, what percentage of reads map to exons vs. introns in order to verify that a sample is snRNA-seq rather than scRNA-seq. I know that STARsolo outputs the basic stats of what aligns to the genome and transcriptome. I was wondering if this could be extended.

**Comment by sjroth** [comment]
Thank you. That is very helpful. Out of curiosity: is there a way to get percentages for each genomic feature?

**Comment by alexdobin** [comment]
What do you mean by "genomic features"?
UTR, CDS etc? 
This is not implemented, but you can hack a special GTF that will list  these features as "exons" of separate transcripts.

**Comment by alexdobin** [comment]
For each of these features you would need to create a separate GTF file:
1. Extract only line with the feature (say UTR,CDS) in field 3
2. Replace field 3 with "exon"
3. Replace transcript_id with a unique identifier (e.g. line number
4. At the mapping stage, use this GTF in ```--sjdbGTFfile``` option
