### ISSUE TITLE
Duplicated headers in fastq

### ISSUE THREAD

**Issue by raquelgarza** [alexdobin/STAR#1531]
Hi, 

I am wondering how would STAR deal with duplicated headers in an input fastq file (completely different sequence). I am aware this is not ideal and shouldn't happen, but in the hypothetical scenario that this is the case I would like to know - does STAR re-index the fastq somehow or does it rely on the read header?

Thanks, and thank you for the wonderful software!

**Comment by alexdobin** [comment]
Hi @raquelgarza 

STAR does not check the read ids in the FASTQ for uniqueness, it simply copies the names to the BAM file, so if you have duplicate read ids, the BAM file will have issues.
You can add a unique identifier to the read ids in the FASTQ before mapping.
Or you can use ```--outSAMreadID Number``` option which will output the read index in the FASTQ instead if read ids.

**Comment by raquelgarza** [comment]
Thank you so much! This is exactly what I was looking for. 
Just wondering, is there a way to keep the header and add the number?

**Comment by alexdobin** [comment]
This would require changing the read ids before mapping.

**Comment by raquelgarza** [comment]
Ok! Thank you. This is all the information I needed, so I'll close this issue.
