### ISSUE TITLE
MAPQ=255 and xf:i:25 (Extra alignment flags in BAM according to 10X)

### ISSUE THREAD

**Issue by WT215** [alexdobin/STAR#1532]
Hello,

I have a BAM file from 10X, and since 10X used STAR for alignment, I wonder whether should I look at `MAPQ=255` or `xf:i:25` to keep confidently mapped reads?

What is the difference between the two fields? Is `MAPQ=255` equal to `xf:i:25`? 

Many thanks!

**Comment by alexdobin** [comment]
Hi @WT215 

MAPQ=255 marks the reads that map uniquely to the genome.
I am not exactly sure about xf:i:25, since this is a tag added by CellRanger not STAR.
I suspect that these are reads that map uniquely to genes and have valid cell barcodes.
