### ISSUE TITLE
seg fault when using GeneFull_ExonOverIntron or GeneFull_Ex50pAS

### ISSUE THREAD

**Issue by joycekang** [alexdobin/STAR#1533]
Hi Alex,

Thanks so much for developing this awesome method. We have been trying to experiment with the different versions of GeneFull, but haven't been able to get the `GeneFull_ExonOverIntron` or `GeneFull_Ex50pAS` versions to run. We use the same exact command that works perfectly for GeneFull, except changing the `--soloFeatures` (example below). The genome generation works fine, but once the 1st pass mapping begins, there is a seg fault (core dumped). Is there something that we're perhaps missing?

Also - we were wondering how GeneFull and GeneFull_ExonOverIntron deal with multimapping. From my understanding, the main limitation of GeneFull (and reason why we'd want GeneFull_ExonOverIntron) is when there are cases like an intron of Gene A falling within an exon of Gene B. In that case, we'd want a read mapping to the overlapping part to be assigned to Gene B in the GeneFull_ExonOverIntron case, but it would be ambiguous in the simple GeneFull case. If multimapping were turned on, is the expected behavior to split the count between Gene A and B in the GeneFull case, but then the read is treated as uniquely mapped to Gene B in the GeneFull_ExonOverIntron case? (Apologies in advance if this is already explained somewhere, and thanks so much for your help!)

Joyce

--

STAR version: 2.7.10a   compiled: 2022-03-11T01:08:49-0500 cn003.research.partners.org:/PHShome/jbk37/tools/STAR-2.7.10a/source
	STAR --genomeDir /data/srlab2/jkang/scHLA/personalized_final/Randolph2021_NewPanel/testing/HMN171215_NI_GeneFull_ExonOverIntron_gtf2_index/ --readFilesIn /data/srlab2/jkang/scHLA/personalized_final/Randolph2021_NewPanel/testing/data/HMN171215_NI_shuffled.bam --runThreadN 4 --runDirPerm All_RWX --soloUMIlen 10 --outFileNamePrefix /data/srlab2/jkang/scHLA/personalized_final/Randolph2021_NewPanel/testing/pers_results/HMN171215_NI_GeneFull_ExonOverIntron_gtf2/HMN171215_NI_GeneFull_ExonOverIntron_gtf2_ --soloType CB_UMI_Simple --soloCBwhitelist /apps/lib-osver/cellranger/1.3.1/cellranger-cs/1.3.1/lib/python/cellranger/barcodes/737K-august-2016.txt --soloCBmatchWLtype 1MM_multi_Nbase_pseudocounts --soloUMIdedup 1MM_CR --soloFeatures GeneFull_ExonOverIntron --soloBarcodeReadLength 0 --soloMultiMappers EM --twopassMode Basic --outSAMtype BAM SortedByCoordinate --outSAMunmapped Within --readFilesType SAM SE --readFilesCommand samtools view -F 0x100 --soloInputSAMattrBarcodeSeq CR UR --soloInputSAMattrBarcodeQual CY UY --readFilesSAMattrKeep None --outSAMattributes CR CY UR UY GX GN CB UB
	STAR version: 2.7.10a   compiled: 2022-03-11T01:08:49-0500 cn003.research.partners.org:/PHShome/jbk37/tools/STAR-2.7.10a/source
Apr 24 19:47:15 ..... started STAR run
Apr 24 19:47:15 ..... loading genome
Apr 24 19:47:43 ..... started 1st pass mapping

--

line 58: 265533 Segmentation fault      (core dumped)

**Comment by alexdobin** [comment]
Hi Joyce,

please try this patch, which should have solved the seg-fault in 2.7.10a:
https://github.com/alexdobin/STAR/releases/tag/2.7.10a_alpha_220314

> If multimapping were turned on, is the expected behavior to split the count between Gene A and B in the GeneFull case, but then the read is treated as uniquely mapped to Gene B in the GeneFull_ExonOverIntron case?

Yes, this is correct: the assignment to one or multiple genes happens first, and only then the EM is applied to multi-gene reads.

**Comment by joycekang** [comment]
Hi Alex,

Thanks - just gave the new patch a try, but unfortunately I'm still getting the seg fault at the same step (first pass mapping). 

        /PHShome/jbk37/tools/STAR --genomeDir /data/srlab2/jkang/scHLA/personalized_final/Randolph2021_NewPanel/testing/HMN171215_NI_GeneFull_Ex50pAS_index/ --readFilesIn /data/srlab2/jkang/scHLA/personalized_final/Randolph2021_NewPanel/testing/data/HMN171215_NI_shuffled.bam --runThreadN 4 --runDirPerm All_RWX --soloUMIlen 10 --outFileNamePrefix /data/srlab2/jkang/scHLA/personalized_final/Randolph2021_NewPanel/testing/pers_results/HMN171215_NI_GeneFull_Ex50pAS/HMN171215_NI_GeneFull_Ex50pAS_ --soloType CB_UMI_Simple --soloCBwhitelist /apps/lib-osver/cellranger/1.3.1/cellranger-cs/1.3.1/lib/python/cellranger/barcodes/737K-august-2016.txt --soloCBmatchWLtype 1MM_multi_Nbase_pseudocounts --soloUMIdedup 1MM_CR --soloFeatures GeneFull_Ex50pAS --soloBarcodeReadLength 0 --soloMultiMappers EM --twopassMode Basic --outSAMtype BAM SortedByCoordinate --outSAMunmapped Within --readFilesType SAM SE --readFilesCommand samtools view -F 0x100 --soloInputSAMattrBarcodeSeq CR UR --soloInputSAMattrBarcodeQual CY UY --readFilesSAMattrKeep None --outSAMattributes CR UR gx gn CB UB
        STAR version: 2.7.10a_alpha_220314   compiled: 2022-03-14T12:56:30-04:00 :/home/dobin/data/STAR/STARcode/STAR.master/source
Apr 30 15:09:36 ..... started STAR run
Apr 30 15:09:37 ..... loading genome
Apr 30 15:09:50 ..... started 1st pass mapping
--
Segmentation fault      (core dumped) $CMD

**Comment by alexdobin** [comment]
Hi Joyce,

could please you try to run it without ```--twopassMode Basic``` to see if this is what causes the seg-fault?

**Comment by joycekang** [comment]
Hi Alex,

Thanks so much - turning off `--twopassMode Basic` did fix the seg-fault issue!

For the Exon_50pAS option, were hoping to use the twopassMode feature to detect splice junctions for use in the exon prioritizing procedure - is this capability a possibility (without causing a seg fault)?

Thanks again,
Joyce

**Comment by alexdobin** [comment]
Hi Joyce,
I am checking the code, this looks like a bug that should not be hard to fix.

**Comment by joycekang** [comment]
Thanks so much, Alex!

On a related note, I think we have noticed a related bug in `Gene` mode where the novel splice junctions detected using `--twopassMode` aren't being used in the counting step for extra chromosomes. Just to clarify, we provide extra personalized chromosomes added to the end of GRCh38, where each chromosome is the full genomic sequence of an HLA allele (including both introns and exons). We don't have allelic splice junction info so just label the entire sequence in the .gtf file as "exon". What we observe (from inspecting the resulting BAM file and looking at GX/GN tags) is that reads spanning an intron (discovered by twopassMode and having N's in the CIGAR string) don't get counted towards the gene (GX:Z:-, top half of screenshot). The only reads that get counted (GX:Z:IMGT_DPB1) are those without any introns in the middle (bottom half of screenshot). Ideally, we would also want to count the reads spanning introns as long as they are concordant with the twopassMode splice junctions. I bring this up in the context of this issue because I wonder if it's a related bug in how novel introns/exon junctions discovered from --twopassMode are affecting the final gene assignment/counts. 

If this isn't as straightforward of a fix then no worries - this is the issue that motivated us to want to use GeneFull_Exon50pAS instead of Gene to avoid this issue altogether. thanks so much again!

![image](https://user-images.githubusercontent.com/12923683/166809756-6f33a327-0249-47b2-aa63-810340773e64.png)

**Comment by alexdobin** [comment]
Hi Joyce,

the junctions detected in the 1st pass are used for better detection of splicing to these junctions.
However, the new junctions are not used to define new transcripts, and thus cannot be used for counting reads towards annotated genes, so the 2-pass mapping is probably not helpful in your case.

If you can infer the transcripts for these extra chromosomes from the standard HLA annotations, it's best to add them to the annotations. If you need to create novel transcripts, you would need to use a tool like Cufflinks or StringTie, which will generate a GTF file with novel transcripts, which can be added to the standard GTF and given to STAR.

Using GeneFull options will also count these alignments.

**Comment by joycekang** [comment]
Hi Alex,

Thanks so much for the explanation - we didn't realize that the 2-pass mapping wasn't being used for transcript counting. Does 2-pass mode affect the final UMI counts matrix in any way, or is it only used for counting SJ? Would 2-pass mode still be helpful in terms of the exon prioritization scheme for `Exon50pAS`? 

Using GeneFull options would probably be easiest for us, but thank you for the suggestion to look into Cufflinks or StringTie - I didn't know those tools could help generate a GTF file and can try those out if GeneFull options don't work.

Joyce

**Comment by alexdobin** [comment]
Hi Joyce,

The 2-pass mapping does not change the gene annotations.
But the 2-pass mapping affects the alignments, so it will affect counts, but only marginally.
The main effect is to increase the number of reads spliced to novel junctions, but occasionally the alignments to annotated genes are also affected.

**Comment by chubukov** [comment]
I think I'm getting a similar bug. I tried all combinations of options for `--soloFeatures` and `--soloMultiMappers`. 
- `Gene` works with any `--soloMultiMappers` option
- `Unique` works with any `--soloFeatures` option
- All other combinations lead to a segmentation fault

Here's the command I used
```
/home/vchubukov/STAR-2.7.10a_alpha_220314/source/STAR   --genomeDir /net/seq/data2/projects/prime_seq/genome   --readFilesIn /net/seq/data2/sequencers/220517_A01698_0024_AHF7CHDSX
3/fastq_no_split/N701_S1_R2_001.fastq.gz /net/seq/data2/sequencers/220517_A01698_0024_AHF7CHDSX3/fastq_no_split/N701_S1_R1_001.fastq.gz   --soloType CB_UMI_Simple   --soloCellRead
Stats Standard   --clip3pAdapterSeq AAAAAAAAAA   --clip3pAdapterMMp 0.1   --soloCBstart 1   --soloCBlen 12   --soloUMIstart 13   --soloUMIlen 16   --soloCBwhitelist /net/seq/data2
/projects/prime_seq/barcodes-combined.txt   --soloCellFilter  EmptyDrops_CR 1344 .99 10 45000 90000 100000 0.01 20000 0.01 10000   --quantMode "TranscriptomeSAM"   --soloFeatures 
Gene   --soloMultiMappers EM   --outSAMunmapped Within   --outFilterType BySJout   --outSAMattributes NH HI AS NM MD CR CY UR UY GX GN CB UB   --outFilterMultimapNmax 20     --out
FilterMismatchNmax 999     --outFilterMismatchNoverReadLmax 0.04     --alignIntronMin 20     --alignIntronMax 1000000     --alignMatesGapMax 1000000     --alignSJoverhangMin 8    
 --alignSJDBoverhangMin 1   --sjdbScore 1   --readFilesCommand zcat   --runThreadN 10   --limitBAMsortRAM 30000000000   --outSAMtype BAM SortedByCoordinate   --outSAMheaderComment
File commentslong.txt   --outSAMheaderHD '@HD' 'VN:1.4' 'SO:coordinate'   --limitOutSJcollapsed 5000000
```

**Comment by chubukov** [comment]
Hi Alex
I got the same result. 
Here's one Log file https://gist.github.com/chubukov/99acabb78ec4218e805a9800a10f4775

I'll note that this is pooled 3' sequencing data, not single-cell (so many more reads/"cell" than typical single cell). Also many of the parameters are left over from our traditional RNA-seq pipeline and may well be inappropriate.

**Comment by alexdobin** [comment]
Hi Victor,

could you please check if it seg-faults for a smaller subset of reads, e.g. with ```--readMapNumber 1000000```

Thanks!
Alex

**Comment by chubukov** [comment]
Hi Alex,

Everything ran successfully with ` --readMapNumber 1000000`

V

**Comment by alexdobin** [comment]
Hi Victor,

I have fixed a bug that was causing segfaults in another issue #1543 with this patch:
https://github.com/alexdobin/STAR/releases/tag/2.7.10a_alpha_220601

I have a feeling that it might be related to the segfault you are seeing, as it's supposed to happen if you ask for Solo multimappers, and there is an atypically larger number of reads for some cell barcodes.

Please try this patch, and if it still segfaults, I am afraid I will need to get a minimal sample of your data that still causes the error.

Thanks!
Alex

**Comment by chubukov** [comment]
@alexdobin they all ran successfully with the new patch 🎉

**Comment by alexdobin** [comment]
Great, thanks for testing it!
