### ISSUE TITLE
unable to initiate starsolo

### ISSUE THREAD

**Issue by echothefox** [alexdobin/STAR#1537]
I am trying to run starsolo on my 10x 3' sequencing but it seems the code is not running:

$ STAR --genomeDir /Users/GenomeDir --readFilesIn /Volumes/Sequencing/scRNAseq/AB-ZL-10X-1S-ZLT_S1_L001_R2_001.fastq /Volumes/Sequencing/scRNAseq/AB-ZL-10X-1S-ZLT_S1_L001_R1_001.fastq --soloType CB_UMI_Simple --soloCBwhitelist /Volumes/Sequencing/scRNAseq/whitelist10x.txt --soloUMIlen 12 --soloCBlen 16 --soloUMIstart 17 --soloCBstart 1 --soloBarcodeReadLength 0 --outFilterScoreMin 30 --soloCBmatchWLtype 1MM_multi_Nbase_pseudocounts --soloUMIfiltering MultiGeneUMI_CR --soloUMIdedup 1MM_All --outSAMtype BAM Unsorted --runThreadN 16 --outFileNamePrefix 10xaligned --soloCellFilter CellRanger2.2 --soloFeatures GeneFull
Abort trap: 6

Can someone please help on this? Thank!

**Comment by echothefox** [comment]
It seems like the gcc was not working properly. I managed to play around with gcc and it turns out I have multiple versions of it...Anyway, I end up use the pre-compiled executables in bin/MacOSX_x86_64/ and it is now working.

**Comment by echothefox** [comment]
--clipAdapterType CellRanger4 command does not work when I use the pre-compiled executables in bin/MacOSX_x86_64/STAR....  it returns Illegal instruction:4 . Unclear how it would be.

**Comment by alexdobin** [comment]
Hi @echothefox 

are you using Rosetta to run it? It was compiled on an Intel Mac.

**Comment by echothefox** [comment]
> Hi @echothefox
> 
> are you using Rosetta to run it? It was compiled on an Intel Mac.

It is Intel processor

**Comment by alexdobin** [comment]
This is strange...
Do you know the processor name? Does it support SIMD-AVX instructions?
The ```--clipAdapterType CellRanger4``` option uses them.

**Comment by echothefox** [comment]
> This is strange... Do you know the processor name? Does it support SIMD-AVX instructions? The `--clipAdapterType CellRanger4` option uses them.

the Mac use Intel Xeon processor so I think it support AVX

**Comment by alexdobin** [comment]
Hi @echothefox 

I think the only solution is to compile the code on your mac.
