### ISSUE TITLE
Segmentation fault 

### ISSUE THREAD

**Issue by Neiluj49** [alexdobin/STAR#1545]
Hello folks,
I work on a Debian server
`cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"`

I need to analyse RNAseq data and I successfully generated a genome index with my favorite one.
Once I switch to the alignment step, I have a segmentation fault.
Does anyone encounter this type of problem ?
I paste here the report of the run.
Tks a lot for your replies.
Cheers 
Julien
`Running STAR with parameters for RW
2.7.10a
	STAR --runMode alignReads --runThreadN 16 --twopassMode Basic --peOverlapNbasesMin 10 --readFilesCommand gunzip -c --genomeDir /mnt/home2/jjeauffre/../../gdo/gdo/Genomic_data/Rosa_OB/RefGenome_ind
ex_OBDH_1.0/ --readFilesIn /mnt/home2/jjeauffre/data/trimmed_data/vero20200726/test1/T0D-5_S1_R1_paired.fq.gz /mnt/home2/jjeauffre/data/trimmed_data/vero20200726/test1/T0D-5_S1_R2_paired.fq.gz --sjdbInser
tSave All --outFilterType BySJout --outFilterMultimapNmax 10 --outFilterMismatchNmax 16 --alignIntronMin 20 --alignIntronMax 20000 --alignMatesGapMax 20000 --outFilterIntronMotifs RemoveNoncanonicalUnanno
tated --outFileNamePrefix /mnt/home2/jjeauffre/data/trimmed_data/vero20200726/test1/T0D-5_S1_ --outSAMprimaryFlag AllBestScore --outFilterMultimapScoreRange 0 --outSAMtype BAM SortedByCoordinate --outSAMu
nmapped Within --outSAMattributes Standard --quantMode GeneCounts --sjdbGTFtagExonParentGene gene_id
	STAR version: 2.7.10a   compiled: 2022-04-06T13:53:04+0200 :/usr/local/src/STAR-2.7.10a/source
Apr 30 18:54:39 ..... started STAR run
Apr 30 18:54:39 ..... loading genome
Apr 30 18:55:28 ..... started 1st pass mapping
Segmentation fault
All done!`

**Comment by alexdobin** [comment]
Hi @Neiluj49 

please try this patch, it fixes bugs causing sea-faults:
https://github.com/alexdobin/STAR/releases/tag/2.7.10a_alpha_220314

**Comment by Neiluj49** [comment]
Tks for your fast reply Alex !
Finally my favorite IT team explained to me that they'll migrate the server installation to a new cluster with a more recent environment.
I tested it; and it worked.
Cheers !
