### ISSUE TITLE
multimapping bug

### ISSUE THREAD

**Issue by scideas** [alexdobin/STAR#1549]
Hi Alex, 

We have been using the --soloMultiMappers option for STARsolo and have been continually encountering segmentation fault or "invalid pointer" errors for low depth samples, with around 1 million reads or less (mean reads/cell = 500). None of the available approaches for multimapping have worked after testing all of them (i.e. EM). 

No errors are generated for the low-depth samples when we remove multimapped read quantification.

You can see from the screenshot below that the samples make it through mapping before hitting the assorted errors.
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/48698173/167147278-b8b05b5d-35af-4491-a2b9-84d677535903.png">

Thank you for your help,
Aaron

**Comment by alexdobin** [comment]
Hi Aaron,

could you please try this patch:
https://github.com/alexdobin/STAR/releases/tag/2.7.10a_alpha_220506
It fixes the problem with multimappers for samples with a small number of cells.

**Comment by scideas** [comment]
That did the trick! Thanks for the quick turnaround

**Comment by alexdobin** [comment]
Thanks for testing!
