### ISSUE TITLE
Segmentation Fault 11 Related to BAM Output with GeneFull STARSolo Quantification

### ISSUE THREAD

**Issue by skvanburen** [alexdobin/STAR#1558]
Hello,

I have been encountering a "Command terminated by signal 11" error when trying to output BAM files using GeneFull in STAR Solo.  I have seen the similar issues #1469 and and #1465 but unfortunately, even after using the newest release you have posted (2.7.10a_alpha_220506), I am still encountering the error.  The command I am using is given below, along with the first 1000 R1 and R2 reads that should be able to reproduce the error.  The error does occur when trying to output either sorted or unsorted BAM files, but the code runs successfully when not outputting a BAM file so I think it must be related to this.  Please let me know if you need any other information from me.

Thanks,
Scott

[SampleR1Reads.fastq.txt](https://github.com/alexdobin/STAR/files/8690785/SampleR1Reads.fastq.txt)
[SampleR2Reads.fastq.txt](https://github.com/alexdobin/STAR/files/8690786/SampleR2Reads.fastq.txt)

```
/n/home04/skvanburen/bin/STAR-2.7.10a_alpha_220506/source/STAR --runThreadN 10 --soloType CB_UMI_Simple --soloCBwhitelist 3M-february-2018.txt --soloCBstart 1 --soloCBlen 16 --soloUMIstart 17 --soloUMIlen 12 --soloBarcodeReadLength 1 --genomeDir STARIndex --readFilesCommand cat --readFilesIn SampleR2Reads.fastq SampleR1Reads.fastq --outFileNamePrefix STAROutput/ --soloFeatures GeneFull --genomeLoad NoSharedMemory --outSAMtype BAM Unsorted --outSAMattributes NH CR CY UR UY GX GN gx gn sM sS sQ --soloStrand Forward --clipAdapterType CellRanger4 --outFilterScoreMin 30 --soloCBmatchWLtype 1MM_multi_Nbase_pseudocounts --soloUMIfiltering MultiGeneUMI_CR --soloUMIdedup 1MM_CR --soloMultiMappers Unique
```

**Comment by alexdobin** [comment]
Hi Scott,

thanks for reporting the issue, I fixed it in this release:
https://github.com/alexdobin/STAR/releases/tag/2.7.10a_alpha_220517

Cheers
Alex
