### ISSUE TITLE
Error: outSAMtype value parsed as single string after upgrade to latest version

### ISSUE THREAD

**Issue by andrews-matt** [alexdobin/STAR#1566]
Hi Alex,

I recently upgraded from v2.5.3a to 2.7.10a and have been running into a curious issue: despite the exact same command line usage, STAR v2.7.10a is now reading in any parameters that include a space as a single string. This is specifically an issue for the --outSAMtype parameter, which reports the following error:
```
EXITING because of fatal input ERROR: unknown value for the first word of outSAMtype: BAM SortedByCoordinate
SOLUTION: re-run STAR with one of the allowed values of outSAMtype: BAM or SAM
```
I do not see how this could be due to user error, as my command line simply reads `--outSAMtype=BAM SortedByCoordinate` with no quotation marks involved. This is the same command line I have used with STAR v2.5.3a for nearly 3 years: the only thing that has changed is the upgrade to v2.7.10a. I wanted to ask if there has been any change to the software that would cause the parameter values to be read as a single string? Thanks in advance.

For more info: I submit my jobs to a HPC through SLURM. The STAR log that results in an error (using v2.7.10a) reads:
```
##### Final user re-defined parameters-----------------:
...
outSAMtype                        "BAM SortedByCoordinate"  
```
while a previous log from a successful job (using v2.5.3a) reads:
```
##### Final user re-defined parameters-----------------:
...
outSAMtype                        BAM   SortedByCoordinate
```

Reading in the R1 and R2 files as part of the --readFilesIn parameter is also being parsed as a single string by the new version.

**Comment by alexdobin** [comment]
Hi Matt,

no changes to parameters input were made lately.
It seems the multi-word parameters get quotes around them for some reason, so STAR sees them as single-word.
It probably has something to do with how SLURM interpreter.

**Comment by andrews-matt** [comment]
Thanks Alex, it being due to SLURM was my thought too. It is just odd that nothing has changed on my end except the STAR version, which is why I asked if STAR interprets parameter inputs differently now.
I'll follow this up internally. Appreciate the response.
