### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by zeryas** [alexdobin/STAR#1567]
Hi, i'am having this persistent error occuring when trying to " make STAR", here is the output  : 

.../usr/include/c++/12.1.0/bits/unordered_map.h:590:7: note: candidate: 'std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::iterator std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::insert(const_iterator, const value_type&) [with _Key = long long unsigned int; _Tp = std::array<long long unsigned int, 15>; _Hash = std::hash<long long unsigned int>; _Pred = std::equal_to<long long unsigned int>; _Alloc = std::allocator<std::pair<const long long unsigned int, std::array<long long unsigned int, 15> > >; iterator = std::__detail::_Insert_base<long long unsigned int, std::pair<const long long unsigned int, std::array<long long unsigned int, 15> >, std::allocator<std::pair<const long long unsigned int, std::array<long long unsigned int, 15> > >, std::__detail::_Select1st, std::equal_to<long long unsigned int>, std::hash<long long unsigned int>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::iterator; const_iterator = std::__detail::_Insert_base<long long unsigned
int, std::pair<const long long unsigned int, std::array<long long unsigned int, 15> >, std::allocator<std::pair<const long long unsigned int, std::array<long long unsigned int, 15> > >, std::__detail::_Select1st, std::equal_to<long long unsigned int>, std::hash<long long unsigned int>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::const_iterator;
value_type = std::pair<const long long unsigned int, std::array<long long unsigned int, 15> >]'
  590 |       insert(const_iterator __hint, const value_type& __x)
      |       ^~~~~~
/usr/include/c++/12.1.0/bits/unordered_map.h:590:7: note:   candidate expects 2 arguments, 1 provided
/usr/include/c++/12.1.0/bits/unordered_map.h:596:7: note: candidate: 'std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::iterator std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::insert(const_iterator, value_type&&) [with _Key = long long unsigned int; _Tp = std::array<long long unsigned int, 15>; _Hash = std::hash<long long unsigned int>; _Pred = std::equal_to<long long unsigned int>; _Alloc = std::allocator<std::pair<const long long unsigned int, std::array<long long unsigned int, 15> > >; iterator = std::__detail::_Insert_base<long long unsigned int, std::pair<const long long unsigned int, std::array<long long unsigned int, 15> >, std::allocator<std::pair<const long long unsigned int, std::array<long long unsigned int, 15> > >, std::__detail::_Select1st, std::equal_to<long long unsigned int>, std::hash<long long unsigned int>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::iterator; const_iterator = std::__detail::_Insert_base<long long unsigned int,
std::pair<const long long unsigned int, std::array<long long unsigned int, 15> >, std::allocator<std::pair<const long long unsigned int, std::array<long long unsigned int, 15> > >, std::__detail::_Select1st, std::equal_to<long long unsigned int>, std::hash<long long unsigned int>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::const_iterator; value_type = std::pair<const long long unsigned int, std::array<long long unsigned int, 15> >]'
  596 |       insert(const_iterator __hint, value_type&& __x)
      |       ^~~~~~
/usr/include/c++/12.1.0/bits/unordered_map.h:596:7: note:   candidate expects 2 arguments, 1 provided
/usr/include/c++/12.1.0/bits/unordered_map.h:627:7: note: candidate: 'void std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::insert(std::initializer_list<typename std::_Hashtable<_Key, std::pair<const _Key, _Val>, _Alloc, std::__detail::_Select1st, _Pred, _Hash, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<std::__not_<std::__and_<std::__is_fast_hash<_Hash>, std::__is_nothrow_invocable<const _Hash&, const _Key&> > >::value, false, true> >::value_type>) [with _Key = long long unsigned int; _Tp = std::array<long long unsigned int, 15>; _Hash = std::hash<long long unsigned int>; _Pred = std::equal_to<long long unsigned int>; _Alloc = std::allocator<std::pair<const long long unsigned int, std::array<long long unsigned int, 15> > >; typename std::_Hashtable<_Key, std::pair<const _Key, _Val>, _Alloc, std::__detail::_Select1st, _Pred, _Hash, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<std::__not_<std::__and_<std::__is_fast_hash<_Hash>, std::__is_nothrow_invocable<const _Hash&, const _Key&> > >::value, false, true> >::value_type = std::pair<const long long unsigned int, std::array<long long unsigned int, 15> >]'
  627 |       insert(initializer_list<value_type> __l)
      |       ^~~~~~
/usr/include/c++/12.1.0/bits/unordered_map.h:627:43: note:   no known conversion for argument 1 from '<brace-enclosed initializer list>' to 'std::initializer_list<std::pair<const long long unsigned int, std::array<long long unsigned int, 15> > >'
  627 |       insert(initializer_list<value_type> __l)
      |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
SoloCommon.h: In member function 'void SoloReadFlagClass::countsAddNoCBarray(std::array<long long unsigned int, 15>&)':
SoloCommon.h:74:42: error: no match for 'operator[]' (operand types are 'std::array<long long unsigned int, 15>' and 'unsigned int')
   74 |             flagCountsNoCB[ibit] += arrIn[ibit];
      |                                          ^
make: *** [Makefile:99: SoloBarcode.o] Error 1 

Any idea how to solve this ? 

Thank you

**Comment by alexdobin** [comment]
Hi YasmineZ

this was fixed with this PR: https://github.com/alexdobin/STAR/pull/1550
Please download the code from github master and try compiling.

**Comment by zeryas** [comment]
Hi @alexdobin 

Thank you very much for your quick reply ! 

I downloaded STAR with "git clone https://..../STAR.git" and compiled it in the source folder as mentioned in your STARmanual, 
First the compilation ends with these lines : 

...nome_genomeGenerate.o genomeParametersWrite.o genomeScanFastaFiles.o genomeSAindex.o Genome_insertSequences.o insertSeqSA.o funCompareUintAndSuffixes.o funCompareUintAndSuffixesMemcmp.o TimeFunctions.o ErrorWarning.o streamFuns.o stringSubstituteAll.o Transcriptome.o Transcriptome_quantAlign.o Transcriptome_geneFullAlignOverlap.o ReadAlign_quantTranscriptome.o Quantifications.o Transcriptome_geneCountsAddAlign.o sjdbLoadFromFiles.o sjdbLoadFromStream.o sjdbPrepare.o sjdbBuildIndex.o sjdbInsertJunctions.o mapThreadsSpawn.o Parameters_readFilesInit.o Parameters_openReadsFiles.cpp Parameters_closeReadsFiles.cpp Parameters_readSAMheader.o bam_cat.o serviceFuns.o GlobalVariables.cpp BAMoutput.o BAMfunctions.o ReadAlign_alignBAM.o BAMbinSortByCoordinate.o signalFromBAM.o bamRemoveDuplicates.o BAMbinSortUnmapped.o  -pthread -Lhtslib -Bstatic -lhts -Bdynamic -lz
Parameters_openReadsFiles.cpp: In member function ‘void Parameters::openReadsFiles()’:
Parameters_openReadsFiles.cpp:25:20: warning: variable ‘imate’ might be clobbered by ‘longjmp’ or ‘vfork’ [-Wclobbered]
   25 |          for (uint imate=0;imate<readFilesNames.size();imate++) {//open readIn files
      |                    ^~~~~

and second, i don't have the bin folder in my STAR repository from where i usually lunch STAR..

I already did install and work with STAR on another wrokstation and i didn't encounter any of these issues, 

Can you please help with this problem ? 

Greatfully ! 

YasmineZ

**Comment by alexdobin** [comment]
Hi YasmineZ

these warnings at the end of compilations are fine, it completed successfully.
The compiled executable resides in the source/ folder, and is called STAR.
You can run it by specifying full path: ```/.../source/STAR```

Cheers
Alex

**Comment by zeryas** [comment]
Hi @alexdobin 

Problem SOLVED, thank you very much ! 

Bests, 

YasmineZ
