### ISSUE TITLE
no reason killed about STAR

### ISSUE THREAD

**Issue by chaoyanggu** [alexdobin/STAR#1569]
hi，
 I used to be able to run STAR normally, but it has been killed always for no reason when I use it again now. I don't know how to solve it.
my shell as follows:
/software/STAR-2.7.2b/source/STAR   --runThreadN 4 --runMode genomeGenerate  --genomeDir  ./STAR_Index/   --genomeFastaFiles ./ref_genome.fa   --sjdbGTFfile ./ref_annot.gtf      --sjdbOverhang 149

and the error is :
May 26 15:29:03 ..... started STAR run
May 26 15:29:03 ... starting to generate Genome files
Killed

or

May 26 14:34:01 ..... started STAR run
May 26 14:34:01 ... starting to generate Genome files
ex.sh: line 1: 2195411 Killed

**Comment by alexdobin** [comment]
Hi @chaoyanggu 

this is likely caused by insufficient RAM. How much RAM do you have and how big is the genome?

**Comment by ylevmirom** [comment]
Hi, 
I'm having the same issues here.. working on wheat genome (10GB)
sufficient amount of RAM `MiB Mem : 128478.2 total` (theoretically)

```
./STAR/bin/Linux_x86_64/STAR --runThreadN 12 \
     --genomeSAsparseD 2 \
     --genomeSAindexNbases 14 \
     --genomeDir /media/8TB/yael/Glumes/RNAseq/STAR_index/index_genome \
     --readFilesCommand gunzip -c \
     --readFilesIn file1.fastq.gz file2.fastq.gz 
```

this is the error I'm getting when mapping (the index is fine): 

Feb 25 15:55:47 ..... started STAR run
Feb 25 15:55:47 ..... loading genome
/media/8TB/yael/G/RNAseq/STAR_map.sh: line 6: 4139604 Killed 

any suggestions? 

many thanks, 

Yael

**Comment by alexdobin** [comment]
Hi Yael,

please send me the Log.out file.

**Comment by ylevmirom** [comment]
Hi Alex, 

Attached here one of my attempts. 
I also tried with the minimal options, but at all attempts i get this segmentation fault. 

Thanks, 

Yael 
[22007FL-05-01-07_S7Log.log](https://github.com/alexdobin/STAR/files/14465981/22007FL-05-01-07_S7Log.log)

**Comment by alexdobin** [comment]
Hi Yael,

most often jobs are killed because of RAM overflow.

**Comment by ylevmirom** [comment]
Thank you. I managed to get it working on an independent server, had to add memory to the swp, though I still haven't figured it out on a slurm cluster..

Thanks, 

Yael
