### ISSUE TITLE
Why do CB/UB tags require SortedByCoordinate?

### ISSUE THREAD

**Issue by chubukov** [alexdobin/STAR#1575]
I'm curious about the following (from the documentation):
>
>CB UB
>error-corrected cell barcodes and UMIs for solo* demultiplexing.
>Requires {outSAMtype BAM SortedByCoordinate.

Suppose I wanted to have individual BAM files for each cell(*). It seems like it would be more efficient to split the large BAM by `CB` first, and then sort the individual ones. Is there a way to enable this?

(*)not really individual cells, we're using STARSolo for pooled 3' sequencing.

**Comment by alexdobin** [comment]
Hi Victor,

the way CB/UB output is implemented now, it only works with the Sorted BAM file output.
If you need to get coordinate-sorted BAM files split by CB, you can simply split the full sorted file by CB without changing the order of the reads, and the resulting (thousands of) files will be automatically sorted.

Cheers
Alex

**Comment by chubukov** [comment]
Thanks Alex, that's what we do now. Just occurred to me that it should be more efficient to split -> sort as opposed to sort -> split.
