### ISSUE TITLE
Duplicate in @SQ lines

### ISSUE THREAD

**Issue by alanfoleynibrt** [alexdobin/STAR#1576]
Hi

Thank you Alex for STAR, I've used it many times and it's worked great. However, I'm having an issue with remapping. 

I've remapped a BAM file using STAR. My aim is to call mtDNA variants in scRNAseq data from the BD Rhapsody. Ideally I'd go from BAM file to variant calling using the GATK RNAseq variant calling pipeline (https://gatk.broadinstitute.org/hc/en-us/articles/360035531192-RNAseq-short-variant-discovery-SNPs-Indels-)

I used this code to remap a BAM file output from sevenbridges (BD Rhapsody™ WTA Analysis Pipeline):

"
"/home/alan/AbSeq/STAR-2.7.10a/source/STAR" --runThreadN 30 --genomeDir $reference_genome_dir/star2 \
--runMode alignReads \
--readFilesType SAM SE \
--readFilesIn $reference_genome_dir/justKX576660.bam \
--readFilesCommand samtools view \
--genomeFastaFiles $reference_genome_dir/KX576660.fasta \
--outSAMtype BAM SortedByCoordinate \
--sjdbGTFfile $reference_genome_dir/KXgtf3.gtf \
--limitBAMsortRAM 212004670141
"

however when I run downstream SplitNCigar :

"
"/home/alan/gatk-4.2.6.1/gatk" SplitNCigarReads \
-R "/home/alan/KX576660/reference_genome/unshifted/KX576660.fasta" \
-I Aligned.sortedByCoord.out.bam \
-O Aligned.sortedByCoord.out.CIGAR.bam
"

I get the error "Cannot add sequence that already exists in SAMSequenceDictionary: KX576660.1"

I thought it might be an issue with my BAM header so I ran

"
samtools view -H Aligned.sortedByCoord.out.bam > header.sam
"

And I saw the header has duplicated @SQ rows:

"
@HD	VN:1.4	SO:coordinate
@SQ	SN:KX576660.1	LN:16283
@SQ	SN:KX576660.1	LN:16283
@PG	ID:STAR	PN:STAR	VN:2.7.10a	CL:/home/alan/AbSeq/STAR-2.7.10a/source/STAR   --runMode alignReads      --runThreadN 30   --genomeDir /home/alan/AbSeq/yujuanKX/gatksnv//star2   --genomeFastaFiles /home/alan/AbSeq/yujuanKX/gatksnv//KX576660.fasta      --readFilesType SAM   SE      --readFilesIn /home/alan/AbSeq/yujuanKX/gatksnv//justKX576660.bam      --readFilesCommand samtools   view      --limitBAMsortRAM 212004670141   --outSAMtype BAM   SortedByCoordinate      --sjdbGTFfile /home/alan/AbSeq/yujuanKX/gatksnv//KXgtf3.gtf
@CO	user command line: /home/alan/AbSeq/STAR-2.7.10a/source/STAR --runThreadN 30 --genomeDir /home/alan/AbSeq/yujuanKX/gatksnv//star2 --runMode alignReads --readFilesType SAM SE --readFilesIn /home/alan/AbSeq/yujuanKX/gatksnv//justKX576660.bam --readFilesCommand samtools view --genomeFastaFiles /home/alan/AbSeq/yujuanKX/gatksnv//KX576660.fasta --outSAMtype BAM SortedByCoordinate --sjdbGTFfile /home/alan/AbSeq/yujuanKX/gatksnv//KXgtf3.gtf --limitBAMsortRAM 212004670141
"

I'm not sure why this has happened. I checked my reference fasta files and they only have one entry for ">KX576660.1". I tried deleting one of the @SQ lines and when I try to rerun SplitNCigar I get this error:

"
Reference name for '1' not found in sequence dictionary
"

Do you by any chance know what's happening here? Or a way to circumvent this?

Alan

**Comment by alexdobin** [comment]
Hi Alan,

please remove ```--genomeFastaFiles /home/alan/AbSeq/yujuanKX/gatksnv//KX576660.fasta``` form the mapping command, since you already included this chromosome when you generated the genome index.

Cheers
Alex

**Comment by alanfoleynibrt** [comment]
This worked perfectly

Thank you very much Alex!
