### ISSUE TITLE
star index too large for the genome size?

### ISSUE THREAD

**Issue by marwa38** [alexdobin/STAR#1578]
Hello 

Could you please let me know why I am getting this warning message?
This is my second genome I used star tool to create the star index and I got an error. 
Here is my main sh (starIndex_nf-core.sh) :
```
#!/bin/bash
#SBATCH --partition=spot-compute
#SBATCH --ntasks=24
#SBATCH --time=24:00:00
#SBATCH --mem-per-cpu=4g
#SBATCH --mail-user=m.Tawfik.19@abdn.ac.uk
#SBATCH --mail-type=ALL

module load star-2.7.1a

STAR --runThreadN 24 --runMode genomeGenerate --genomeDir ./starIndex/ --genomeFastaFiles Salmo_salar-GCA_905237065.2-unmasked.fa --sjdbGTFfile Salmo_salar-GCA_905237065.2-2021_07-genes.gtf --sjdbOverhang 100


```
And I tried to make changes after I go the following warning by adding  --genomeSAindexNbases 13 but still didn't work. 
Here are my fasta and gtf file (genome and annotation) from NCBI, not sure what is the problem with the genome, if you could please help me with that?

```
bash starIndex_nf-core.sh
Jun 10 20:58:19 ..... started STAR run
Jun 10 20:58:19 ... starting to generate Genome files
WARNING: --genomeSAindexNbases 14 is too large for the genome size=400031744, which may cause seg-fault at the mapping step. Re-run genome generation with recommended --genomeSAindexNbases 13
```
Many thanks 
M

**Comment by alexdobin** [comment]
Hi M,

this warning message is not a problem unless you get a seg-fault at the mapping stage.
The recommended value of --genomeSAindexNbases 13 is just slightly lower than the default 14, so it's unlikely to cause the problems.

Cheers
Alex
