### ISSUE TITLE
Segfault at mapping

### ISSUE THREAD

**Issue by JBreunig** [alexdobin/STAR#1580]
I apologize if this is a repeat as I saw a few segfault issues at the "mapping" step.  Strangely, I'm getting a segfault with a brand new 10X V3 3' dataset (although an older but still somewhat recent 10X V3 dataset works fine with the same code).  (Also, these same new fastqs aligned ok with the new CellRanger version.)  I tried several versions of STAR and still get the segfault just after starting the mapping step.  Attaching the Log.out file.

I tried without multimapping but got the same error.

> Jun 14 09:36:00 ..... started STAR run
> Jun 14 09:36:01 ..... loading genome
> Jun 14 09:36:18 ..... processing annotations GTF
> Jun 14 09:36:24 ..... inserting junctions into the genome indices
> Jun 14 09:37:09 ..... started mapping
> Segmentation fault (core dumped

[Log.out.txt](https://github.com/alexdobin/STAR/files/8901771/Log.out.txt)

**Comment by alexdobin** [comment]
Hi @JBreunig 

you have several files for read1 and read2, and they should be listed with a comma separated lists like this:

```
--readFilesIn GBM7_S2_L001_R2_001.fastq.gz,GBM7_S2_L002_R2_001.fastq.gz 
  GBM7_S2_L001_R1_001.fastq.gz,GBM7_S2_L002_R1_001.fastq.gz
```

i.e.
```
--readFilesIn R2_L1,R2_L2   R1_L1,R1_L2
```

**Comment by JBreunig** [comment]
[smacks face] sorry I missed that...thanks!
