### ISSUE TITLE
STAR alignment 

### ISSUE THREAD

**Issue by dbhayal9** [alexdobin/STAR#1591]
Hii,

I am using STAR version 2.7.10a. for alignment of fastq files against mouse reference genome GRCm38.
i successfully index and done alignment. it did not gave me any error but i got alignment only 0.08%.

same alignment i did with tophat2 and HISAT2 it gave me 94% alignment.
please rectify my issue.

reference genome and GTF file downloaded from ensmble.
system has 24 CPU.
paired end reads has approx 55 M read x 2
average read length 125 bp

here i am attaching script which i was used.
#####################This is for indexing:######################
./STAR 
     --runThreadN 20 
     --runMode genomeGenerate 
     --genomeDir /media/hps2/Deepak/JIT_001/Genome/Mus38STARindex/ 
     --genomeFastaFiles /media/hps2/mm38.fa 
     --sjdbGTFfile /media/hps2/mm38.gtf 
     --sjdbOverhang 124

Jun 22 10:23:51 ..... started STAR run
Jun 22 10:23:51 ... starting to generate Genome files
Jun 22 10:25:03 ..... processing annotations GTF
Jun 22 10:25:47 ... starting to sort Suffix Array. This may take a long time...
Jun 22 10:26:15 ... sorting Suffix Array chunks and saving them to disk...
Jun 22 10:52:56 ... loading chunks from disk, packing SA...
Jun 22 11:00:23 ... finished generating suffix array
Jun 22 11:00:23 ... generating Suffix Array index
Jun 22 11:05:49 ... completed Suffix Array index
Jun 22 11:05:50 ..... inserting junctions into the genome indices
Jun 22 11:12:36 ... writing Genome to disk ...
Jun 22 11:13:03 ... writing Suffix Array to disk ...
Jun 22 11:16:34 ... writing SAindex to disk
Jun 22 11:16:56 ..... finished successfully

####################output files after successfully indexing###########
-rwxrwxrwx 1 root root  29M Jun 22 10:25 exonGeTrInfo.tab
-rwxrwxrwx 1 root root 2.2M Jun 22 10:25 geneInfo.tab
-rwxrwxrwx 1 root root 9.3M Jun 22 10:25 transcriptInfo.tab
-rwxrwxrwx 1 root root  12M Jun 22 10:25 exonInfo.tab
-rwxrwxrwx 1 root root 7.9M Jun 22 10:25 sjdbList.fromGTF.out.tab
-rwxrwxrwx 1 root root  721 Jun 22 10:25 chrStart.txt
-rwxrwxrwx 1 root root  539 Jun 22 10:25 chrName.txt
-rwxrwxrwx 1 root root  493 Jun 22 10:25 chrLength.txt
-rwxrwxrwx 1 root root 1.1K Jun 22 10:25 chrNameLength.txt
-rwxrwxrwx 1 root root 8.0M Jun 22 11:05 sjdbInfo.txt
-rwxrwxrwx 1 root root 6.3M Jun 22 11:05 sjdbList.out.tab
-rwxrwxrwx 1 root root  738 Jun 22 11:12 genomeParameters.txt
-rwxrwxrwx 1 root root 2.7G Jun 22 11:13 Genome
-rwxrwxrwx 1 root root  21G Jun 22 11:16 SA
-rwxrwxrwx 1 root root 1.5G Jun 22 11:16 SAindex
-rwxrwxrwx 1 root root  20K Jun 22 11:17 Log.out

############################This is for alignment################

./STAR 
--genomeDir /Genome/Mus38STARindex/ 
--runThreadN 12 
--readFilesIn Control-1_trimmed_1.fastq Control-1_trimmed_2.fastq 
--sjdbGTFfile /media/hps2/mm38.gtf 
--genomeLoad NoSharedMemory 
--outFileNamePrefix /CONTROL38/control. 
--outSAMtype BAM SortedByCoordinate 
--quantMode TranscriptomeSAM GeneCounts 
--outBAMsortingThreadN 20 
--outSAMunmapped Within 
--outFilterType BySJout 
--outFilterMultimapNmax 20 
--alignSJoverhangMin 8 
--alignSJDBoverhangMin 1 
--outFilterMismatchNmax 999 
--outFilterMismatchNoverReadLmax 0.04 
--alignIntronMin 20 
--alignIntronMax 1000000 
--alignMatesGapMax 1000000 
--outSAMattributes All 
--chimSegmentMin 12 
--chimJunctionOverhangMin 12 
--chimOutJunctionFormat 1 
--alignSJstitchMismatchNmax 5 -1 5 5 
--chimNonchimScoreDropMin 10 
--chimMultimapNmax 0 
--chimOutType WithinBAM Junctions SeparateSAMold 
--outFilterScoreMinOverLread 0.3 
--outFilterMatchNminOverLread 0.3 
--sjdbScore 1
	
Jun 22 12:19:47 ..... started STAR run
Jun 22 12:19:50 ..... loading genome
Jun 22 12:23:55 ..... processing annotations GTF
Jun 22 12:24:31 ..... inserting junctions into the genome indices
Jun 22 12:28:27 ..... started mapping
Jun 22 13:05:01 ..... finished mapping
Jun 22 13:05:07 ..... started sorting BAM
Jun 22 13:14:03 ..... finished successfully

############This is the files which was generated###############
total 41G
drwxrwxrwx 2 root root    0 Jun 22 12:24 control._STARgenome
-rwxrwxrwx 1 root root 101M Jun 22 13:05 control.Aligned.toTranscriptome.out.bam
-rwxrwxrwx 1 root root 7.2M Jun 22 13:05 control.SJ.out.tab
-rwxrwxrwx 1 root root 1.4M Jun 22 13:05 control.ReadsPerGene.out.tab
-rwxrwxrwx 1 root root 3.2K Jun 22 13:14 control.Log.progress.out
-rwxrwxrwx 1 root root  32G Jun 22 13:14 control.Chimeric.out.sam
-rwxrwxrwx 1 root root  22K Jun 22 13:14 control.Log.out
-rwxrwxrwx 1 root root 2.0K Jun 22 13:14 control.Log.final.out
-rwxrwxrwx 1 root root 4.1G Jun 22 13:14 control.Chimeric.out.junction
drwxrwxrwx 2 root root    0 Jun 22 13:14 control._STARtmp
-rwxrwxrwx 1 root root 5.2G Jun 22 13:14 control.Aligned.sortedByCoord.out.bam

##################### control.Log.final.out ################```
                               

```
> Started job on |       Jun 22 12:19:47
>                            Started mapping on |       Jun 22 12:28:27
>                                   Finished on |       Jun 22 13:14:03
>      Mapping speed, Million of reads per hour |       73.09
>                         Number of input reads |       55551656
>                     Average input read length |       248
>                                   UNIQUE READS:
>                  Uniquely mapped reads number |       42711
>                       Uniquely mapped reads % |       0.08%
>                         Average mapped length |       163.44
>                      Number of splices: Total |       702
>           Number of splices: Annotated (sjdb) |       286
>                      Number of splices: GT/AG |       638
>                      Number of splices: GC/AG |       29
>                      Number of splices: AT/AC |       3
>              Number of splices: Non-canonical |       32
>                     Mismatch rate per base, % |       5.48%
>                        Deletion rate per base |       0.01%
>                       Deletion average length |       2.01
>                       Insertion rate per base |       0.01%
>                      Insertion average length |       2.74
>                            MULTI-MAPPING READS:
>       Number of reads mapped to multiple loci |       11765819
>            % of reads mapped to multiple loci |       21.18%
>       Number of reads mapped to too many loci |       184378
>            % of reads mapped to too many loci |       0.33%
>                                 UNMAPPED READS:
> Number of reads unmapped: too many mismatches |       0
>          % of reads unmapped: too many mismatches |       0.00%
>           Number of reads unmapped: too short |       575304
>                % of reads unmapped: too short |       1.04%
>               Number of reads unmapped: other |       393283
>                    % of reads unmapped: other |       0.71%
>                                CHIMERIC READS :
>                      Number of chimeric reads |       42590161
>                           % of chimeric reads |       76.67%
```

**Comment by alexdobin** [comment]
Hi @dbhayal9 

this is likely the problem with Read1 and Read2 orientations, which prevents it from mapping as concordant pairs. Please try to map Read1 and Read2 separately.

**Comment by dbhayal9** [comment]
Hii @alexdobin,

Yes you are right it was R1 and R2 problem.

Now its working (i saw Log.progress file) but i am getting an error like:

EXITING because of FATAL ERROR: could not create output file /media/hps2/Deepak/JIT_001/github/PDTH1/PDTH1._STARtmp//FilterBySJoutFiles.mate1.thread0
Solution: check that you have permission to write this file

Even i increased ulimit 65536. still getting same error.  but Log.progress file showing 90% mapped aligned.

Thanks in advance.

**Comment by dbhayal9** [comment]
Hii @alexdobin,

Using Unsorted BAM and decreasing Threads worked for me fine.

Thanks alot.
