### ISSUE TITLE
Custom output suffixes

### ISSUE THREAD

**Issue by fgvieira** [alexdobin/STAR#1593]
STAR specifies output file name through a prefix, but the suffixes are hard-coded. When running STAR as a part of a workflow, it would be nice to be able to specify each output file path/name separately. Would this be possible?

Maybe by providing STAR with a text file with the list of suffixes of every output file to use?

thanks,

**Comment by alexdobin** [comment]
Hi Filipe,

this is not possible, the file names are hardcoded.
You can always rename them after the run, of course.
