### ISSUE TITLE
Variable mapping rate when using smart-seqv4 kit for ultra-low amounts of RNA

### ISSUE THREAD

**Issue by Lucas-Di-Pietro** [alexdobin/STAR#1595]
Hello all,

I have tried using the Takara Smart-seq v4 kit for RT and cDNA amplification in small quantitites of initial RNA on drosophila samples (less than 10ng).

On a first run, which was done in a novaseq, we got variable amounts of unmapped reads (from 90% to 10% of the total reads, depending on the sample) that were mapped to multiple genome. Since the main sources of contamination were human and yeast, we believed to know our main sources of contamination and decided to change our protocols in order to minimize any contamination as much as we could. 

I tested the new protocol in a low-depth run using a miseq, and the contamination seems to be mostly gone because I do not see any reads mapping specifically to human and very few to yeast. However, there are still high and variable quantities (from more than 50 to 20%) of the reads that remain unmapped. These are classified as "too short" by STAR (this problem also existed in the novaseq run, but I was focused on the contamination problem first). 

I don't think that the main problem now is contamination, because none of the unmapped reads are able to map specifically to any one possible contaminating genome. They are able to map unespecifically to multiple genomes (anything from plants, to fungi) if you use a FastQ screen against the main known genomes, and I believe that is the case because they are "random artifacts" that remained from the RT and amplification steps that can be mapped to anything given enough leniency. 

I wanted to know if anyone has any idea as to how minimize these unmapped reads either in the bioinformatics steps or before.

I also wanted to know if, given that I remain with enough total mapped reads at the end (more than 5 million is what I'm aiming for as "good enough"), if I can still trust my data or not. 

I am attaching some prints from the reports.

1 - FastQ screen of novaseq run with yeast/human contamination problems
2-  novaseq run - mapped vs unmapped (too short) reads with star

3- FastQ screen of miseq run in which I don't see human/yeast contamination, but "mapped to multiple loci" sequences are still there. 
4-  miseq run - mapped vs unmapped (too short) reads with star

thank you, all.

L

![1- novaseqrun_contamination](https://user-images.githubusercontent.com/108468738/176679172-c379500a-dcf6-4c49-b0d1-037354dc8824.PNG)
![2- novaseq-mapped-unamapped](https://user-images.githubusercontent.com/108468738/176679214-9c1c0884-9df9-4420-abf5-147fd2dfaaed.PNG)
![3 - miseqrun-nocontamination](https://user-images.githubusercontent.com/108468738/176679231-675dfabb-9b58-49b9-8676-f597d8ac40ee.PNG)
![4 - miseq-mapped-unmapped](https://user-images.githubusercontent.com/108468738/176679239-f2480d95-2553-4e87-ba48-7252810a64c6.PNG)

**Comment by alexdobin** [comment]
Hi Lucas-Di-Pietro 

if the reads map to multiple loci in multiple genomes, unfortunately, I do not think there is anything that can be done on the bioinformatics side: these sequences are too non-specific to be useful.

**Comment by Lucas-Di-Pietro** [comment]
Hello alex.

Ok, I see.

Thank you very much, anyway.
