### ISSUE TITLE
STAR 2.7.10a_alpha_220601 terminates with signal 11, Segmentation fault

### ISSUE THREAD

**Issue by wlkath** [alexdobin/STAR#1608]
Hi, 

I'm running STAR version=2.7.10a_alpha_220601 on some 10x 3' data.   

STAR_2.7.10a --runThreadN 20 --soloType CB_UMI_Simple --soloUMIlen 12 --soloCellFilter EmptyDrops_CR --soloFeatures GeneFull --soloCBwhitelist ./3M-february-2018.txt --genomeDir /home/kath/storage2/dmel104_10a --outFilterType BySJout --alignIntronMax 100000 --quantMode GeneCounts --outSAMtype BAM SortedByCoordinate --limitBAMsortRAM 4715576210 --soloOutFileNames ZT00_10a_solo.out/ ZT00_features.tsv ZT00_barcodes.tsv ZT00_matrix.mtx --outFileNamePrefix ZT00_10a_ --readFilesCommand "zcat" --readFilesPrefix /home/kath/b1042/fatbody_sc_ZT/01.RawData/ZT0/ --readFilesIn ZT0_CKDL220015693-1A_H37TGDSX5_S1_L004_R2_001.fastq.gz ZT0_CKDL220015693-1A_H37TGDSX5_S1_L004_R1_001_trimmed.fastq.gz  

The run makes it to 

Jul 24 09:34:39 ..... started Solo counting
Jul 24 09:34:39 ... Starting Solo post-map for GeneFull
Jul 24 09:34:39 ... Finished allocating arrays for Solo 1.91906 GiB

and then segfaults.    STAR version 2.7.9a is able to complete without error with the same run parameters. 

Here's the output of  gdb ~/bin/STAR_2.7.10a core.23748

Program terminated with signal 11, Segmentation fault.
#0  0x000000000046a1dc in SoloReadFeature::inputRecords(unsigned int**, unsigned int, std::vector<unsigned int, std::allocator<unsigned int> >&, std::vector<readInfoStruct, std::allocator<readInfoStruct> >&, SoloReadFlagClass&, std::vector<unsigned int, std::allocator<unsigned int> >&, std::vector<unsigned int, std::allocator<unsigned int> >&) ()
Missing separate debuginfos, use: debuginfo-install glibc-2.17-326.el7_9.x86_64 libgcc-4.8.5-44.el7.x86_64 libgomp-4.8.5-44.el7.x86_64 libstdc++-4.8.5-44.el7.x86_64 zlib-1.2.7-20.el7_9.x86_64

Going further with gdb than this is beyond my normal experience but I'm hoping it at least suggests possibilities. 

Thanks,
- Bill

**Comment by alexdobin** [comment]
Hi Bill,

Please try to run it on a small subset of reads, say 100k, with ```--readMapNumber 100000```.
If it still sega-faults, please send me this subset of reads.

Thanks!
Alex

**Comment by wlkath** [comment]
Alex, 

Yes, the same error occurs on the subset of reads.   

Here's the command I used:

STAR --runThreadN 20 --soloType CB_UMI_Simple --soloUMIlen 12 --soloCellFilter EmptyDrops_CR --soloFeatures GeneFull --soloCBwhitelist ./3M-february-2018.txt --genomeDir /home/kath/storage2/dmel104_10a --outFilterType BySJout --alignIntronMax 100000 --quantMode GeneCounts --outSAMtype BAM SortedByCoordinate --limitBAMsortRAM 4715576210 --soloOutFileNames ZT00_10a_solo.out/ ZT00_features.tsv ZT00_barcodes.tsv ZT00_matrix.mtx --outFileNamePrefix ZT00_10a_ --readFilesCommand "zcat" --readFilesPrefix /home/kath/b1042/fatbody_sc_ZT/01.RawData/ZT0/ --readMapNumber 100000 --readFilesIn Sampled_100k_R2.fq.gz Sampled_100k_R1.fq.gz  

Thanks,

- Bill

[Sampled_100k_R1.fq.gz](https://github.com/alexdobin/STAR/files/9204280/Sampled_100k_R1.fq.gz)
[Sampled_100k_R2.fq.gz](https://github.com/alexdobin/STAR/files/9204281/Sampled_100k_R2.fq.gz)

**Comment by alexdobin** [comment]
Hi @wlkath 

I could not reproduce the seg-fault with your FASTQ and parameters, but I used the complete GTF from ENSEMBL.
Could you please send me the filtered GTF as well as Log.out file for the failed run.
Also, I fixed another potential seg-fault, if you could test this patch it would be great:
https://github.com/alexdobin/STAR/releases/tag/2.7.10a_alpha_220818

Thanks!
Alex

**Comment by wlkath** [comment]
Thanks, Alex.   I'll check out the latest alpha version. 

In the meantime, here are the GTF and log files that were generated. 

[gtf_and_logs.zip](https://github.com/alexdobin/STAR/files/9377119/gtf_and_logs.zip)

**Comment by wlkath** [comment]
Alex,

2.7.10a_alpha_220818 completes without the seg-fault, so your patch has resolved the issue. 

Thanks very much for the fix!

Best regards,

- Bill

**Comment by alexdobin** [comment]
Great, many thanks for testing it, Bill!
