### ISSUE TITLE
--soloFeatures does not interfere with std STARsolo run?

### ISSUE THREAD

**Issue by ms-gx** [alexdobin/STAR#1609]
I am pretty sure this is the case, but just to clarify: If I run STARsolo with parameters `--soloFeatures Gene GeneFull SJ Velocyto`, this will not interfere with the "standard" STARsolo execution, but those are more like "add-ons" executed in addition, right?

**Comment by alexdobin** [comment]
That's correct, each feature calculation is independent of the other. The CB/UMI/GX tags in the BAM are for the first feature in the list (Gene in this case).

**Comment by ms-gx** [comment]
How do you mean "The CB/UMI/GX tags in the BAM are for the first feature in the list (Gene in this case)"? I guess they are independent from `--soloFeatures` parameters, no?

**Comment by alexdobin** [comment]
The tags in the BAM file depend on which feature (Gene, GeneFull, etc) is used for quantification. The feature that is used corresponds to the first feature in the ```--soloFeatures``` list.
