### ISSUE TITLE
Unable to download release

### ISSUE THREAD

**Issue by ketancmaheshwari** [alexdobin/STAR#161]
The release page here https://github.com/alexdobin/STAR/blob/4ad2100644d70e54e9145f52dcb3ba2312ad4a88/release results in 404 not found.

**Comment by dsguo** [comment]
# Get latest STAR source from releases
wget https://github.com/alexdobin/STAR/archive/STAR_2.5.2a.tar.gz
tar -xzf STAR_2.5.2a.tar.gz
cd STAR_2.5.2a

This wget method of download also leads to 404 Error. git clone works though

**Comment by brspurri** [comment]
The link in the `README` is incorrect. Correct link is: [https://github.com/alexdobin/STAR/archive/2.5.2a.tar.gz](https://github.com/alexdobin/STAR/archive/2.5.2a.tar.gz).
