### ISSUE TITLE
Why same read in different data size has different alignment?

### ISSUE THREAD

**Issue by chenzemin** [alexdobin/STAR#1625]
The following figure is the align result in 0.5M data.
![image](https://user-images.githubusercontent.com/37295211/184279611-59148c20-6dde-4565-93b7-d216088a3736.png)

The following figure is the align result in 2M data.
![image](https://user-images.githubusercontent.com/37295211/184279659-4d4590a3-269c-4d6b-9dd5-f911de196bff.png)

**Comment by alexdobin** [comment]
What is the difference between 0.5M and 2M data?

**Comment by chenzemin** [comment]
I just extract different size of data from the same data.

**Comment by chenzemin** [comment]
The original PE data has 20M reads. I randomly extract 0.5M, 1M, 1.5M and 2M reads for align.

**Comment by chenzemin** [comment]
I want to analyze the impact of different data size on the results of star-fusion analysis.

My STAR version is 2.7.8a.
My star-fusion version is v1.10.0.

The STAR run parameters I use are as follows(This is also almost a built-in star align parameter for star-fusion):
`STAR `
`--readFilesIn {input.R1} {input.R2} ` 
`--runThreadN {threads} `
`--outReadsUnmapped None `
`--chimSegmentMin 12 `
`--chimJunctionOverhangMin 8 `
`--chimOutJunctionFormat 1 `
`--alignSJDBoverhangMin 10 `
`--alignMatesGapMax 100000 `
` --alignIntronMax 100000 `
`--alignSJstitchMismatchNmax 5 -1 5 5 `
`--outSAMstrandField intronMotif `
`--outSAMunmapped Within `
`--alignInsertionFlush Right `
`--alignSplicedMateMapLminOverLmate 0 `
`--alignSplicedMateMapLmin 30 `
`--outSAMtype BAM SortedByCoordinate `
`--outSAMattrRGline {params.outSAMattrRGline} `
`--chimMultimapScoreRange 3 `
`--chimScoreJunctionNonGTAG -4 `
`--chimMultimapNmax 20 `
`--chimNonchimScoreDropMin 10 `
`--chimOutType Junctions WithinBAM SoftClip `
`--peOverlapNbasesMin 12 `
`--genomeLoad NoSharedMemory `
`--twopassMode Basic `
`--readFilesCommand 'gunzip -c' `
`--quantMode GeneCounts `
`--outFileNamePrefix star/`

**Comment by alexdobin** [comment]
Hi @chenzemin 

if you are using ```--twopassMode Basic``` option, the mapping of each read may depend on other reads. If you have more reads, it's more likely that a novel junction will be confidently detected in the 1st pass, and then other reads will be able to be mapped spliced to that junction.

**Comment by chenzemin** [comment]
Thank you @alexdobin
