### ISSUE TITLE
What's the point of including gtf annotation ?

### ISSUE THREAD

**Issue by lalalagartija** [alexdobin/STAR#1626]
Hi, 
I am aligning with STAR using an annotation file in gtf format but nowhere in the output I see any information containing gene names and such. What is the point of giving gtf annotation ? Second question is, if a gtf file is given, will star map outside the gtf regions ? the GTF file was done solely on automatig ORFing so I am not sure of it's quality. 

Thanks !

**Comment by alexdobin** [comment]
Hi @lalalagartija 

annotations are used to extract the known splice junctions to assist in mapping spliced reads.
Also, they are used for gene quantification options.

**Comment by lalalagartija** [comment]
Ah, great, I will try that second option too ! Thanks
