### ISSUE TITLE
soloAdapterSequence in sci-RNA-seq3

### ISSUE THREAD

**Issue by dbrg77** [alexdobin/STAR#1629]
Hi Alex,

I've been trying to use `starsolo` to process [sci-RNA-seq3](https://teichlab.github.io/scg_lib_structs/methods_html/sci-RNA-seq3.html) data. The Read 1 contains the barcodes and UMI, and the structure is like this:

<img width="1610" alt="Screenshot 2022-08-13 at 20 00 38" src="https://user-images.githubusercontent.com/7750032/184493142-49b2bc92-b267-429f-9166-0c8f6cd1bf51.png">

Basically, Read 1 will be:

```
9 or 10bp Hairpin BC + CAGAGC + 8bp UMI + 10bp RT BC
```

The cell barcodes are the combination of the Hairpin and RT BCs. However, due to the variable length of the Hairpin BC, we cannot use the Read start (`0_0`) as the reference point. These are the parameters that seem to work, using the short `CAGAGC` as the anchor:

```
--readFilesIn sci-rna-seq3/data/SRR7827206_2.fastq.gz sci-rna-seq3/data/SRR7827206_1.fastq.gz \
--soloType CB_UMI_Complex \
--soloAdapterSequence CAGAGC \
--soloCBposition 0_0_2_-1 3_9_3_18 \
--soloUMIposition 3_1_3_8 \
--soloCBwhitelist sci-rna-seq3/data/hairpin_whitelist.txt sci-rna-seq3/data/RT_whitelist.txt \
--soloCBmatchWLtype 1MM
```

No errors reported. This produced expected number of cells compared to the publication and 75% valid cell barcodes in the whitelist. I guess it was okay, though I expect a bit more percentage of valid barcodes, but maybe I should tweak `--soloCBmatchWLtype 1MM`.

My question is regarding `--soloAdapterSequence CAGAGC`. The anchor `CAGAGC` is kind of short. It does not exist in either the Hairpin BC or the RT BC. However, it can appear in the 8-bp UMI region. When this happens, there will be two `CAGAGC` in the read.

The first one is the intended one, the second one is in the UMI. In this case, how `star` will behave? Is it always using the first occurrence? If this is the case, I think we are good here, but I just want to confirm.

Thank you very much!

Regards,
Xi

**Comment by alexdobin** [comment]
Hi Xi,

that's correct, it will always use the first instance of the sequence match.

**Comment by dbrg77** [comment]
Thank you!!! That's good to know!
Closing the issue.

Xi
