### ISSUE TITLE
Missing UB and/or CB in STARsolo BAM

### ISSUE THREAD

**Issue by apredeus** [alexdobin/STAR#1634]
Hello Alex, 

I was wondering why sometimes STARsolo BAM file does not contain the sequence of the UMI, or both CB and the UMI? (there's dash instead). 

E.g. for this read (this is 10x v1 read1), 

```
@D00456:161:CA18GANXX:7:2105:19763:56681
GAACCAACTGCAGTAACGGGGGGC
+
JJJJJJJJJJJJJJJJJJJJJJJJ
```

The alignment is this: 

```
D00456:161:CA18GANXX:7:2105:19763:56681 16      chr1    3213677 255     98M     *       0       0       TAGAAGCCAAGTGTCTTCTTGGAGCTTTACTGTGGCAAGGTAATATTTTTTTTCATTTCAACAAAAGATCAGAGTATTGTAGTGGAAATCTTGCTTGA      7FFFFFFFFFBF<F7//B/F<FFFBBFFFFFF<FFFFFFFFFBFFB77/<<FFFFB<</FFFFFFFFBFFFFFBBBF/FFBFFFFF<FBF<FBBBBBB      NH:i:1  HI:i:1  AS:i:96 nM:i:0  GX:Z:ENSMUSG00000051951 GN:Z:Xkr4       CB:Z:GAACCAACTGCAGT     UB:Z:-
```

Why would the UMI not be reported here? Some other alignments have both CB and UB as "-". 

Thank you, as always!

**Comment by alexdobin** [comment]
Hi Alex,

CB and UB are only output if the CB and UMI sequences pass filtering.
If CB is not in the pass-list it will not be output. UMIs are filtered against homopolymer and also against multi-gene UMI, if you used ```--soloUMIfiltering MultiGeneUMI*``` option.

**Comment by apredeus** [comment]
Thank you! 

The reason it came up is that I was trying to convert a STARsolo bam back to fastq - I wanted to run STARsolo on a filtered BAM using exact same settings, but when BAM file is provided the standard clipping option (`--clipAdapterType CellRanger4`) throws an error (perhaps it's not decoded as a paired-end BAM?). Regular `bamtofastq` utility provided by 10X does not work, since the BAM is missing RG tag. and probably the absence of CR/UR would also be a problem. 

What I'm saying is, maybe it would be good to make a more 10X-like BAM file default?

**Comment by alexdobin** [comment]
Hi Alex,

I think ```bamtofastq``` works off the CR/UR ("raw" barcode sequence) tags, so you would have to have them if you want to use it.
What parameters did you use for the run with BAM as input?

**Comment by apredeus** [comment]
Sorry, totally forgot I haven't answered here. I'm not sure what I was doing wrong - I think might have been `--readFilesType SAM PE` instead of `--readFilesType SAM SE`? 

For other users benefit, the extra (BAM-specific) options are these: 

`--readFilesIn test.bam --readFilesType SAM SE --readFilesCommand samtools view --soloInputSAMattrBarcodeSeq CR UR --soloInputSAMattrBarcodeQual CY UY`

You can drop the `--soloInputSAMattrBarcodeQual` (fake quals will be used), and use CB/UB if that's the only thing your BAM file has.
