### ISSUE TITLE
Installation on Mac M1, 

### ISSUE THREAD

**Issue by boomath** [alexdobin/STAR#1635]
I am a new user for RNA seq analysis, kindly help me for this:  while installing on Mac M1, I am get the error on using the 'make' command.
 
(base) boomathipandi@dhcp-10-110-244-97 ~ % make STARforMac for Mac OS X
make: *** No rule to make target `STARforMac'.  Stop.

Without this command success, I was tried to run the code "(base) boomathipandi@dhcp-10-110-244-97 ~ % STAR —-runMode genomeGenerate —-genomeDir ref/ --genomeFastaFiles /Users/boomathipandi/ref/Mus_musculus.GRCm39.dna_sm.primary_assembly.fa --sjdbGTFfile /Users/boomathipandi/Mus_musculus.GRCm39.107.gtf -runThreadN64
STAR: Bad Option: --genomeFastaFiles.
Usage:	STAR cmd [options] [-find] file1 ... filen [find expression]

Use	STAR -help
and	STAR -xhelp
to get a list of valid cmds and options.

Use	STAR H=help
to get a list of valid archive header formats.

Use	STAR diffopts=help
to get a list of valid diff options."

May I know, why at every stages it is giving the bad option command is arising?

Is this because of having problem in Build STAR process? 

Kindly help me this out.

**Comment by alexdobin** [comment]
On Mac, it's best to try the precompiled executable bin/MacOSX_x86_64/STAR inside the STAR unzipped distribution.

**Comment by boomath** [comment]
Thank you so much for your response. When I run in the Mac intel it is running, however, for Mac M1 I tried, but failed. (I bought very recently)

(base) boomathipandi@boomathis-mbp MacOSX_x86_64 % STAR -runMode genomeGenerate -genomeDir /Users/boomathipandi/ref/ --genomeFastaFiles /Users/boomathipandi/Mus_musculus.GRCm39.dna_sm.primary_assembly.fa --sjdbGTFfile /Users/boomathipandi/Mus_musculus.GRCm39.107.gtf --runThreadN 16

STAR: Bad Option: -genomeDir.
Usage:	STAR cmd [options] [-find] file1 ... filen [find expression]

Use	STAR -help
and	STAR -xhelp
to get a list of valid cmds and options.

Use	STAR H=help
to get a list of valid archive header formats.

Use	STAR diffopts=help
to get a list of valid diff options.

Is this correct? or 

Do I need to use anything different code. can you give me the code to execute it. Kindly pls help me for this.

**Comment by alexdobin** [comment]
You need to specify full path to the STAR executable. It looks like there is another app called STAR that's being called.

**Comment by boomath** [comment]
Thank you so much. Now I got it, It started to run.

**Comment by thisisamirv** [comment]
> On Mac, it's best to try the precompiled executable bin/MacOSX_x86_64/STAR inside the STAR unzipped distribution.

Thank you so much. I just copied that STAR file into /usr/local/bin and then ran:

`cp STAR /usr/local/bin`

Now everything is fine.
