### ISSUE TITLE
STAR align for multiple runs

### ISSUE THREAD

**Issue by bapoorva** [alexdobin/STAR#1637]
Hi,

I have a single cell RNASeq experiment that has 2 runs and 2 lanes per sample. Basically, i have 
Sample1_Lane1_Run1_Read1
Sample1_Lane1_Run1_Read2
Sample1_Lane2_Run1_Read1
Sample1_Lane2_Run1_Read2

Sample1_Lane1_Run2_Read1
Sample1_Lane1_Run2_Read2
Sample1_Lane2_Run2_Read1
Sample1_Lane2_Run2_Read2

How do I specify this in STARSolo -readFilesIn argument ? From the documentation, I can see it's comma separated list for R1 and R2. 

```
--readFilesIn Read2_Lane1.fastq.gz,Read2_Lane2.fastq.gz,Read2_Lane3.fastq.gz  Read1_Lane1.fastq.gz,Read1_Lane2.fastq.gz,Read1_Lane3.fastq.gz
```

Just not sure now to include multiple runs

Thanks

**Comment by alexdobin** [comment]
Hi Apoorva,

do you want the runs to be mapped combined? If so, use the comma separated lists, i.e.
```
--readFilesIn Sample1_Lane1_Run1_Read2,Sample1_Lane2_Run1_Read2,Sample1_Lane1_Run2_Read2,Sample1_Lane2_Run2_Read2   
Sample1_Lane1_Run1_Read1,Sample1_Lane2_Run1_Read1,Sample1_Lane1_Run2_Read1,Sample1_Lane2_Run2_Read1
```

**Comment by bapoorva** [comment]
Got it. Thank you
