### ISSUE TITLE
inserting junctions into the genome indices taking too long

### ISSUE THREAD

**Issue by ibrahimkurt** [alexdobin/STAR#1639]
Hi Alex,

Thanks for this useful tool.

I am running STAR genomeGenerate on mm9 reference as following on my local M1 pro laptop (10 cores, 16GB RAM):

`./STAR --runMode genomeGenerate --genomeDir /Users/ibrahimkurt/data/genomes/ --genomeFastaFiles /Users/ibrahimkurt/data/genomes/mm9.fa --sjdbGTFfile /Users/ibrahimkurt/data/genomes/gencode.vM1.annotation.gtf
`
```
STAR version: 2.7.10a   compiled:  :/Users/travis/build/alexdobin/travis-tests/STARcompile/source
Aug 25 20:32:04 ..... started STAR run
Aug 25 20:32:05 ... starting to generate Genome files
Aug 25 20:32:58 ..... processing annotations GTF
Aug 25 20:33:15 ... starting to sort Suffix Array. This may take a long time...
Aug 25 20:33:25 ... sorting Suffix Array chunks and saving them to disk...
Aug 25 22:26:51 ... loading chunks from disk, packing SA...
Aug 25 22:28:04 ... finished generating suffix array
Aug 25 22:28:04 ... generating Suffix Array index
Aug 25 22:32:04 ... completed Suffix Array index
Aug 25 22:32:05 ..... inserting junctions into the genome indices
```

It stays in this part for a long time (>12 hours). Reading other posts, look like 16 GB is not ideal for mouse but I can still manage to get it done? Do you have any suggestions to make it work in case if it is stuck? I am also attaching the [Log.out.txt](https://github.com/alexdobin/STAR/files/9429792/Log.out.txt)

Thanks a lot!

**Comment by alexdobin** [comment]
Hi Ibrahim,

to fit mouse genome into 16GB RAM, please add ```--genomeSAsparseD 3 --genomeSAindexNbases 12 --limitGenomeGenerateRAM 14000000000``` options to your command line. Also, you need to make sure that other apps do not use a significant amount of RAM.

**Comment by ibrahimkurt** [comment]
Thanks a lot Alex, it worked and finished in an hour.
