### ISSUE TITLE
What does the `% of reads unmapped: too short` mean (short reads or short part of the read unaligned)?

### ISSUE THREAD

**Issue by joelostblom** [alexdobin/STAR#164]
Hi,
First, thanks for making STAR. It is a great aligner that has made it much easier for me to setup an RNA-seq workflow!

I recently analysed a 15-sample RNA-seq, and one of the samples has around 80 % in `% of reads unmapped: too short` in the `Log.final.out`-file and only about 17 % uniquely aligned reads.  I just wanted to clarify, does this mean that the read itself is too short (due to incorrect adapter trimming or something like that), or that the read can be of any length, but only a short sequence of the read aligned? I am suspecting the latter, since I tried before and after adapter trimming with the same result and the average input length is around 250 bp in both cases (paired ends), which is the same as for all the other samples.

Almost all the other samples have around 4 % too short reads and a unique alignment of about 90 %. I realize this is not directly related to STAR, but if you have any pointers to what reasons could cause one sample to misbehave like this, that would be greatly appreciated as well.

Cheers

**Comment by alexdobin** [comment]
Hi Joel,

"too short" literally means "alignment too short". This could either happen for normal-length read which are not mapping well, or for a read that was short (over-trimmed) before mapping,
The average trimmed length before mapping is reported is "average input length".

Cheers
Alex

**Comment by joelostblom** [comment]
Thanks for the clarification,
The "average input length" as reported by STAR is what I was referring to when I mentioned that reads are about 250 bp in length. So for some reason, the reads from this sample map poorly. I will keep exploring to find out why.

Is there an option in STAR that would allow me to output only those reads that are too short to align? I didn't see one in the manual, but maybe I just missed it.

**Comment by alexdobin** [comment]
Hi Joel,

You can output all unmapped reads into fasta/fastq files with --outReadsUnmapped Fastx, but you would not be able to tell whether these are "too short" or other - although typically most of the unmapped reads are classified as "too short".

Another option is to output unmapped read into the SAM/BAM files - then the "unmapped type" is marked with the uT:A:<n> tag, with n=1.

Cheers
Alex

**Comment by joelostblom** [comment]
Great, thank you Alex!

**Comment by Gig77** [comment]
I encountered this issue when in the two paired-end input FASTQ files mates are out-of-order (see also #169).

**Comment by raflynn** [comment]
Hi Alex, 
I wanted to follow up with this thread -- I also have been using STAR and noticed that >80% of my reads are being classified as "% of reads unmapped: too short". If I run FASTQC on the input FASTQ file I feed into STAR, the shortest read is 17nts, which should be long enough to map to the human genome (or at least not be unique and move to the multi-mapping read category). 

Is there a way to have STAR map shorter reads?
Thanks!
Ryan

**Comment by alexdobin** [comment]
Hi Ryan,

for a faster response, please start a new issue rather then posting in a closed one.
Please check this thread for a good discussion on unmapped "too short" alignments, and how to control their numbers.
[https://groups.google.com/d/msg/rna-star/UCUM5x9cXGk/VMuS0ZZtJMEJ](url)
Briefly, "too short" relates to the best alignment mapped length, not the read length itself.

Cheers
Alex

**Comment by raflynn** [comment]
Will do next time and thanks for getting back to me! I'll take a look at the link and keep looking into this issue. Ryan
