### ISSUE TITLE
Long Reads: quality string length is not equal to sequence length

### ISSUE THREAD

**Issue by marcDabad** [alexdobin/STAR#165]
Working with long reads (>2000) it crashes with "quality string length is not equal to sequence length" and checking it, that's not true. 

STAR shows me a fragment of the read, not all, could be a problem storing sequence?

**Comment by alexdobin** [comment]
Hi Marc,

sorry for belayed reply. Have you used the STARlong executable?
Did you compile it yourself? If so, did you do 'make clean' before 'make STARlong' ?

Cheers
Alex

**Comment by marcDabad** [comment]
It has been solved. When cluster admin installed star didn't use make clean before make STARlong.

Thanks!

**Comment by ibseq** [comment]
any more detailed info for us not so knowledgable...maybe some additional instructions :)

**Comment by alexdobin** [comment]
Hi @ibseq 

if you want to compile STARlong you need to run 'make clean' before compilation, i.e.
$ cd source
$ make clean
$ make STARlong

Cheers
Alex
