### ISSUE TITLE
Issue with mapping smallRNAseq data to a small custom genome

### ISSUE THREAD

**Issue by PeppeRNAi** [alexdobin/STAR#1657]
Hello. 

I need to map smallRNA-seq reads to a small custom genome (4Kb).

The command I use to generate this custom genome is:
STAR --runThreadN 16 --runMode genomeGenerate --genomeDir /.../1 --genomeFastaFiles /.../genome.fa --genomeSAindexNbases 4

The genome gets generated with no problem.

However, when I try to map a small artificial .fq file (attached), I get this output:
STAR --runThreadN 16 --genomeDir /.../1 --readFilesIn /Users/Guiseppe/Desktop/try.fq

Sep 16 13:17:02 ..... started STAR run
Sep 16 13:17:02 ..... loading genome
Sep 16 13:17:02 ..... started mapping
zsh: segmentation fault  STAR --runThreadN 16 --genomeDir /Users/Guiseppe/Desktop/1 --readFilesIn 

Could you please help me figuring out where the problem may be? I am enclosing the Log.out file too.

Thanks in advance

[genome.fa.txt](https://github.com/alexdobin/STAR/files/9586008/genome.fa.txt)
[try.fq.txt](https://github.com/alexdobin/STAR/files/9586009/try.fq.txt)
[Log.out.txt](https://github.com/alexdobin/STAR/files/9585999/Log.out.txt)

**Comment by alexdobin** [comment]
Hi @PeppeRNAi 

sorry for the delayed reply. The try.fq.txt file is not formatted properly - quality string lengths are not equal to the sequence lengths for several reads.

**Comment by PeppeRNAi** [comment]
Hi!

Thanks so much!

Giuseppe








Giuseppe Militello,PhD
Associate Director

Mirimus, Inc.
760 Parkside Ave.
Suite 227F
Brooklyn, NY 11226
***@***.***
+1-502-224-6009
