### ISSUE TITLE
terminate called after throwing an instance of 'std::out_of_range' during *alignment step*

### ISSUE THREAD

**Issue by b3b3gg** [alexdobin/STAR#1669]
Hello,

I am trying to map RNA-seq reads to an influenza genome (homemade fasta and gff3), however very early during alignment I get the error:

```
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 1) >= this->size() (which is 1)
```

Previous posts show this error during genome generation, but mine appear to be successfully created. I have included a transcript_id feature in the exon column and changed the sjdbGTFtagExonParentTranscript term to Parent/ID/Name without change. I have also converted the gff3 to gtf format, no changes. Could you make any suggestions to fix this? Example lines from gff3 below:

```
IAV1	PR8_34	gene	28	2307	.	+	.	ID=956536;Name=PB2
IAV1	PR8_34	transcript	28	2307	.	+	.	ID=NP_040987;Parent=956536;parent_name=PB2
IAV1	PR8_34	exon	28	2307	.	+	.	ID=exon:NP_040987:1;Parent=NP_040987;exon_number=1;exon_id=NP_040987.1;gene_id=PB2;transcript_id=PB2
IAV3	PR8_34	gene	25	2175	.	+	.	ID=956535;Name=PA
IAV3	PR8_34	transcript	25	2175	.	+	.	ID=NP_040986;Parent=956535;parent_name=PA
IAV3	PR8_34	exon	25	2175	.	+	.	ID=exon:NP_040986:1;Parent=NP_040986;exon_number=1;exon_id=NP_040986.1;gene_id=PA;transcript_id=PA
IAV3	PR8_34	gene	25	784	.	+	.	ID=13229134;Name=PA-X
IAV3	PR8_34	transcript	25	784	.	+	.	ID=YP_006495785;Parent=13229134;parent_name=PA-X
IAV3	PR8_34	exon	25	784	.	+	.	ID=exon:YP_006495785:1;Parent=YP_006495785;exon_number=1;exon_id=YP_006495785.1;gene_id=PA-X;transcript_id=PA-X
```

And here are the commands used:

`STAR --runMode genomeGenerate --genomeDir STAR/ --genomeFastaFiles IAV_PR8_refGenome.fa --sjdbGTFfile IAV_PR8_mod.gff3 --sjdbGTFtagExonParentTranscript Parent --sjdbOverhang 100 --genomeSAindexNbases 5 --outFileNamePrefix pr8`

`STAR --genomeDir ~/genomes/influenza/pr8/STAR/ --readFilesIn rep1/SRR7878052.fastq.gz,rep2/SRR7878055.fastq.gz,rep3/SRR7878064.fastq.gz  --readFilesCommand gunzip -c --outFilterType BySJout --outFilterMultimapNmax 20 --alignSJoverhangMin 8 --outSJfilterOverhangMin 12 12 12 12 --outSJfilterCountUniqueMin 1 1 1 1 --outSJfilterCountTotalMin 1 1 1 1 --outSJfilterDistToOtherSJmin 0 0 0 0 --outFilterMismatchNmax 999 --outFilterMismatchNoverReadLmax 0.04 --scoreGapNoncan -4 --scoreGapATAC -4 -–chimOutType WithinBAM HardClip --chimScoreJunctionNonGTAG 0 --alignSJstitchMismatchNmax −1 −1 −1 −1 --alignIntronMin 20 --alignIntronMax 1000000 --alignMatesGapMax 1000000 --outSAMtype BAM SortedByCoordinate --quantMode GeneCounts`

Thanks very much for any suggestions!!

**Comment by alexdobin** [comment]
Hi @b3b3gg 

please convert your GFF3 to GTF, using,e.g., gffread.

**Comment by alexdobin** [comment]
Hi @b3b3gg 

please post the Log.out file of the genome generation run.

**Comment by alexdobin** [comment]
Hi @b3b3gg 

nothing suspicious in the Log.out files. If you could send me the FASTA, GTF and a small subset of reads that cause the problem, I can take a look into it.

**Comment by alexdobin** [comment]
Hi @b3b3gg 

this issue was caused by the wrong symbols in --alignSJstitchMismatchNmax in you command line, long dashes instead of normal dashes:
--alignSJstitchMismatchNmax −1 −1 −1 −1
There is also the same issue with
-–chimOutType
I would recommend checking Log.out file after ```"##### Final user re-defined parameters-----------------:``` to see if the parameters STAR sees agree with your expectations.
