### ISSUE TITLE
STARsolo for Bulk RNA-seq with UMI

### ISSUE THREAD

**Issue by ilwookkim** [alexdobin/STAR#1672]
Hi Alex,

Good day!
I have couple of question of STARsolo for bulk RNA-seq  (stranded).
I read previous posts from multiple users about similar issue and I try to follow that.
And we would like to use UMI deduplication (1MM_Directional_UMItools) and finally want to quantifying transcripts using EM algorithm (e.g. RSEM etc.).
But I'm not 100% sure whether all parameter which I used are correct or not. 

Our workflow are as below: 

We used SMARTer Stranded Total RNA-Seq Kit v3 to add UMI for RNA-seq.
Only read2 has UMI.

```
UMI (8bp) - Linker (6bp) - cDNA
```

1.  We added fake cell barcode (AAAA) into all read2
```
# zcat ./readR2.fastq.gz | awk '{if (NR%2==0) $0="AAAA"$0; print}' | gzip > ./addCB/readR2.fastq.gz

AAAA - UMI (8bp) - Linker (6bp) - cDNA
```

2. Create cell barcode white list
```
echo "AAAA" > cbwhitelist.txt
```

3. Run STARsolo
```
STAR --readFilesIn readR1.fastq.gz ./addCB/readR2.fastq.gz \
  --readFilesCommand zcat \
  --genomeDir /path/genomeDir \
  --runThreadN 20 \
  --outSAMtype BAM SortedByCoordinate \
  --quantMode TranscriptomeSAM \
  --twopassMode Basic \
  --soloStrand Forward \
  --soloBarcodeMate 2 \
  --soloMultiMappers EM \
  --soloType CB_UMI_Simple \
  --soloCBstart 1 \
  --soloCBlen 4 \
  --soloUMIstart 5 \
  --soloUMIlen 8 \
  --soloUMIdedup 1MM_Directional_UMItools \
  --soloCBwhitelist cbwhitelist.txt \
  --soloBarcodeReadLength 12 \
  --clip5pNbases 0 18 \
  --soloFeatures Gene \
  --soloCellFilter None \
  --soloOutFileNames starsolo/solo \
  --outFileNamePrefix starsolo/output
```
I would like to know whether all the parameters are correct.

And I have a few other question regarding quantification.

1. There are 4 files in raw dir
```
UniqueAndMult-EM.mtx  barcodes.tsv  features.tsv  matrix.mtx
```
Is UniqueAndMult-EM.mtx file for gene quantification using EM algorithm and matrix.mtx for gene counts?

2. Output "Aligned.toTranscriptome.out.bam". Can I use this file directly for RSEM or Salmon to quantifying transcripts?
3. If so, is this result already de-duplicated quantification? 

Please let me know.
Thank you so much!

Best,
Kim

**Comment by alexdobin** [comment]
Hi Kim,

your parameters look good. Please check the CB/UMI statistics in these files to see if it makes sense:
```
Solo.out/Barcodes.stats
Solo.out/Gene/Features.stats
Solo.out/Gene/Summary.csv
```

```matrix.mtx``` contains the unique-gene counts, while ```UniqueAndMult-EM.mtx``` contains unique+multi-gene counts.

```Aligned.toTranscriptome.out.bam``` can be used directly with RSEM.
I believe Salmon-quantification uses genomic alignments, i.e. ```Aligned.sortedByCoordinate.bam```
However, these files are not deduplicated.

**Comment by ilwookkim** [comment]
Hi Alex,

Thanks a lot for the comment :)
```Aligned.toTranscriptome.out.bam``` and ```Aligned.sortedByCoordinate.bam``` files are not deduplicated. 
So if we want to use UMI deduplication, I should use umi dedplication tool usch as ```UMI tools```.
But possibly I could use ```UniqueAndMult-EM.mtx``` for DEG analysis using such as tximport from ```DESeq2```. 
Am I correctly understand?

**Comment by alexdobin** [comment]
Hi Kim,

```UniqueAndMult-EM.mtx``` indeed contains deduplicated counts.

**Comment by ilwookkim** [comment]
Hi Alex,

Thanks a lot for clarifying! :)
