### ISSUE TITLE
STARsolo GX tag choice when read overlapping 2 genes (MT genes)

### ISSUE THREAD

**Issue by mbahin** [alexdobin/STAR#1676]
Hi Alex,

I ran into a particular case lately.

I got interested into reads mapping to MT chromosome (on Human). The circular MT chr has contiguous genes and, for some reason (that I don't understand why the way...), some reads are overlapping two genes.
For example, I checked the region `MT:10,423-10,991` where I had `1,661,110` reads of which `1,130,945` are associated to a gene (GX tag on the BAM):
- `616,384` reads to ENSG00000198886 (MT-ND4)
- `514,561` reads to ENSG00000212907 (MT-ND4L)

Here is a screen of IG
<img width="1440" alt="Screen_WAH" src="https://user-images.githubusercontent.com/7046416/195291027-6f74c611-787d-43c8-bce5-343b6efa7568.png">

My question is how these reads are associated to one gene and not the other? Is it based on the overlap %? Are the missing ones considered multimappers?

Cheers,
Mathieu

**Comment by alexdobin** [comment]
Hi Mathieu,

for --soloFeatures Gene, reads will be counted if they fully overlap exons of a single gene.
In the figure above, the reads in the center should not be counted at all, since they protrude outside of both genes.
Though I am not sure what's plotted as "Ensembl Genes", we need to see all transcripts.

Cheers
Alex

**Comment by mbahin** [comment]
Hi Alex,

Thanks for your quick reply! :)
I have a better understanding of counts and the different options we have (`--soloFeatures GeneFull` for example!).
Regarding the counts, when a read overlaps exons of more than one gene, is there a way to assign the count to the most covered gene?

Cheers,
Mathieu

**Comment by alexdobin** [comment]
Hi Mathieu,

the multi-mapper algorithm in the newer versions of STAR can assign such multi-gene reads/UMIs to genes.
```--soloMultiMappers EM``` (or Rescue, PropUnique)

**Comment by mbahin** [comment]
Hi Alex,

Thanks, I'll switch to 2.7.10a! :)
I close the issue.

Cheers,
Mathieu
