### ISSUE TITLE
Assignment of reads to spliced/unspliced transcripts without realignment

### ISSUE THREAD

**Issue by miridg** [alexdobin/STAR#1677]
Hi Alex, 
I have a very big single RNA-seq data and I aligned and assigned the reads using STARsolo.
Now, I would like to assign the reads to another gtf file without realignment. 
Searching for this in previous posts, I saw that you have a script that assigns the reads to genes without realignment. 
Is there a similar script for assigning the reads to spliced or unspliced transcripts?
Thanks!
Miri.

**Comment by alexdobin** [comment]
Hi Miri,

I do not think I have a script like this.
In any case, a script like this won't be optimized and will run slower than remapping with new GTF.

**Comment by miridg** [comment]
OK. Thanks for the fast reply!!
