### ISSUE TITLE
core dump

### ISSUE THREAD

**Issue by baj12** [alexdobin/STAR#168]
Hi,

I am using STAR_2.5.0c and with the attached sequence as reference and the following as a query sequence I get a core dump:

@HZB41:00468:00472
TTTGAAAAGAGAGTTTTTTTTTTTTTA
+
8:>6>78988(./.-//88888888*8

I tried with the human genome as reference and got no problem. This is one of two sequences out of a few million that cause a core dump. I spent already a full day to identify this sequence and reduce it to that fragment. I am now hoping that it might be easier for you to go further. Or you already know about it and can tell me what to do???

Please let me know if you need any further information.

The last message from Log.out is:
alignIntronMax=alignMatesGapMax=0, the max intron size will be approximately determined by (2^winBinNbits)*winAnchorDistNbins=589824
Thread #0 end of input stream, nextChar=-1

 more xxx.Log.progress.out 
           Time    Speed        Read     Read   Mapped   Mapped   Mapped   Mapped Unmapped Unmapped Unmapped Unmapped
                    M/hr      number   length   unique   length   MMrate    multi   multi+       MM    short    other

Thanks for your kind help,

best,

Bernd

[NLAD8-31032016-seq.fasta.gz](https://github.com/alexdobin/STAR/files/345963/NLAD8-31032016-seq.fasta.gz)

**Comment by alexdobin** [comment]
Hi Bernd,

when you generated the genome, have you reduced --genomeSAindexNbases to 
min(14, log2(GenomeLength)/2 - 1) (as stated in the manual)?
If you did, please try to reduce it even more, and if it still does not work, please send me the Log.out file.

Cheers
Alex

**Comment by baj12** [comment]
I set it to 3 now and it works...
Thanks for the help.
Cheers,
Bernd
