### ISSUE TITLE
10X Sample Multiplexing in STARsolo

### ISSUE THREAD

**Issue by sjroth** [alexdobin/STAR#1687]
Hi @alexdobin,

Feature question for you. Is there a feature for 10X Sample Multiplexing in STARsolo? I'll include some links to the 10X docs.
https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/what-is-cellplex
https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/using/tutorial_cp

Thanks!
Sam

**Comment by alexdobin** [comment]
Hi Sam,

no, such option is not presently available.

**Comment by sjroth** [comment]
Ah! It's my hope that STARsolo will incorporate this in the future! I'll look out for it.

Thanks for the answer,
Sam

**Comment by lldelisle** [comment]
This would be awesome. I guess that meanwhile we can still split the BAM by cell barcode and gather counts using an analysis of the CMO. Has anyone already developed such a pipeline?
