### ISSUE TITLE
clarification of –outFilterMismatchNmax

### ISSUE THREAD

**Issue by joegeorgeson** [alexdobin/STAR#1691]
Dear STAR,

I would like to filter reads that have >5 mismatches in the alignment and apply the filter `–outFilterMismatchNmax 5` however if I run `samtools view -e '[nM]>5'` I still find many reads that have more than 5 mismatches (confirmed upon visual inspection). Should I expect these reads to be filtered with these parameters?

Below are all the relevant flags I pass (v2.7.9a);
`–outFilterMultimapNmax 10 –outFilterMultimapScoreRange 1 –outFilterScoreMin 10 –outFilterMismatchNmax 5 –alignEndsType Local --outSAMtype BAM SortedByCoordinate`

And I copied the first few reads below;
```
pos:7:1212:2233:41889      99      chr1    10001   255     9S105M  =       10010   123     CCTTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCGAACCCGAACCCGAACCCGAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAA      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF<BFFFF7FFFFB7FFFFFFBFFBFB/B<BFFFFF<F/FFFFF//FFB<B/7BFF/BFFFF<</      NH:i:1  HI:i:1  AS:i:201        nM:i:8
pos:7:1212:2233:41889      147     chr1    10010   255     114M    =       10001   -123    CCCTAACCCTAACCCTAACCCTAACCCGAACCCGAACCCGAACCCGAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCAACCCTAACCCTAAC      #####FF</77/BF7///FF7/F<<B</7/FBB<<BFFF</<FF</F/FFF<F<FFF<<FFFFFFFFFFFFFFFF<FFFFFFFFFFFFFFFFFFBBFFFFFFFFFFFFFFFFFF      NH:i:1  HI:i:1  AS:i:201        nM:i:8
pos:7:1316:5191:76907      99      chr1    14439   1       114M    =       14457   120     TTCTCTGGAAGCCTCTTAAGAACACAGTGGCGCAGTCTGGGTGGAGCCGTCCCCCCATGGAGCACAGGCAGACAGAAGTCCCCGCCACAGCTGTGTGGCCTCAAGCCAGCCTTC      FFFF<F<//<B////<<</<FBB<</BBB//<F/7//<<<FFFF<BF<F/FBFFFF<F/F<<FBFFFF/B//7FBB<7FBFFF<///7/</BF77FFBBFF</7BF/7BBF<F#      NH:i:4  HI:i:1  AS:i:194        nM:i:10
pos:7:1316:5191:76907      147     chr1    14457   1       102M12S =       14439   -120    AGATCACAGTGGCGCAGGCTGGGTGGAGCCGTCGCCCCAAGGAGAACAGGCAGACAGAAGGCCACGCCCCAGCTGTGTGGCCTCAAGCCAGACTTCCGCACCATGAAGCTGGAA      ##################################################################################################################      NH:i:4  HI:i:1  AS:i:194        nM:i:10
```

**Comment by alexdobin** [comment]
Hi @joegeorgeson 

the ```--outFilterMismatchNmax``` only controls the primary (top scoring) alignments. For multi-mappers, some of the additional alignments can have more mismatches. What is strange: you are using ```--lignEndsType Local``` which should prevent soft-clipping, but it still happens. Some of your options seem to have the wrong single dash instead of double dash --. Please check the Log.out file to see of the command lines options are correct.

**Comment by joegeorgeson** [comment]
Hi @alexdobin

Thank you very much for your reply, as you identified the single dash parameters are completely ignored by STAR.

**Comment by Abclisy** [comment]
Hi, I am using STAR solo, does STAR solo have a parameter like 'outFilterMismatchNmax' to set the threshold for mismatches?

**Comment by alexdobin** [comment]
Hi @Abclisy 

yes, STARsolo can use all the mapping parameters from STAR.

**Comment by Abclisy** [comment]
Thank you! @alexdobin
