### ISSUE TITLE
fail generating very little index - core dumped 

### ISSUE THREAD

**Issue by JRudewicz** [alexdobin/STAR#17]
Hi,

I seem to have a problem reported by others before but on a little file.
You can find the logs and working files here : https://gist.github.com/JRudewicz/1bca5f8e99dcb9f8afcb
Please let me know if you need anything else.

Thanks

**Comment by alexdobin** [comment]
Hi,

could you please try the latest patch https://github.com/alexdobin/STAR/releases/tag/STAR_2.4.0i
I believe this problem has been fixed.

Cheers
Alex

**Comment by JRudewicz** [comment]
Hi,
Yes it was my first reflex before post my issue. So the latest patch core dump too...
Regards,Justine
Date: Tue, 20 Jan 2015 15:24:58 -0800

**Comment by alexdobin** [comment]
Hi Justine,

I am getting a seg-fault with 2.4.0h, but not with 2.4.0i . 
Could you please compile 2.4.0i with "make gdb", run it within gdb, and let me know which line seg-faults?

Thanks a lot!
Alex
