### ISSUE TITLE
Star alignment killed after SAindex ...

### ISSUE THREAD

**Issue by stevetsa** [alexdobin/STAR#170]
Here is the Log.out file
[Log.out.txt](https://github.com/alexdobin/STAR/files/364704/smG28029Log.out.txt)

I cannot seem to find where the issue is. Pleas advise.  Thank you.

**Comment by alexdobin** [comment]
Hi @stevetsa 

sorry for belayed reply. Was there any message from the OS, such as "Segmentation fault".
how much RAM do you have? You would need ~2GB for this genome.
I would recommend reducing --genomeSAindexNbases to 10 at the genome generation step.

Cheers
Alex
