### ISSUE TITLE
Empty bam and no Log.Final.out

### ISSUE THREAD

**Issue by SophieAhmed** [alexdobin/STAR#1707]
Dear Alex ,I'm aligning 10X data using Star and starSolo option, the mapping is working and i can see the mapping rates in the Log.progress.out file, my bam files are created but remain empty and i don't have any Log.Final.out even though it runs to completion.
I used --runMode genomeGenerate to make my Star Genome before the alignment step.   I've never encountered this issue before, but this is my first time using STAR directly for 10X read mapping
Any advice?
here are my commands

```
module load bio/STAR/2.7.10a-GCC-11.2.0

for i in *_R2_001.fastq.gz 
do 
SAMPLE=$(echo ${i} | sed "s/_R2\_001.fastq\.gz//")
mkdir newbams/"${SAMPLE%_}"; echo ${SAMPLE}_R2_001.fastq.gz ${SAMPLE}_R1_001.fastq.gz

STAR --runMode alignReads --genomeDir StarGenomeFinal \
--readFilesIn ${SAMPLE}_R2_001.fastq.gz ${SAMPLE}_R1_001.fastq.gz  \
--readFilesCommand zcat \
--outFileNamePrefix newbams/"${SAMPLE%_}" \
--outFilterMultimapNmax 10 \
--outSAMtype BAM SortedByCoordinate \
--outSAMattributes CR UR CY UY CB UB \
--outReadsUnmapped Fastx \
--soloType CB_UMI_Simple \
--soloCBwhitelist 3M-february-2018.txt \
--soloCBstart 1 --soloCBlen 16 --soloUMIstart 17 --soloUMIlen 12 \
--soloCellFilter  EmptyDrops_CR \
--quantMode GeneCounts
```
and here are the output files created
ls newbams/
sample1_Aligned.sortedByCoord.out.bam  sample1_Solo.out            sample1_Unmapped.out.mate2
sample1_Log.out                        sample1_STARtmp
sample1_Log.progress.out               sample1_Unmapped.out.mate1

**Comment by akhst7** [comment]
@SophieAhmed,  
I am sort of running into the similar issue.  I am using one of the 10x dataset to see if I can address the no mapping issue but I am wondering if you solved the issue.   Please let me know. 

thanks.

**Comment by akhst7** [comment]
I figured this one out.  It was sort of a silly mistake.
