### ISSUE TITLE
STARsolo with 10x sample index

### ISSUE THREAD

**Issue by MartaBenegas** [alexdobin/STAR#1709]
Dear team,

I wanted to analyze the following open-source dataset of 10x Chromium for training purposes: https://www.10xgenomics.com/resources/datasets/1-k-brain-cells-from-an-e-18-mouse-v-3-chemistry-3-standard-3-0-0

It consists of 6 files:

- neuron_1k_v3_S1_**L001**_**I1**_001.fastq.gz
- neuron_1k_v3_S1_**L001**_R1_001.fastq.gz
- neuron_1k_v3_S1_**L001**_R2_001.fastq.gz
- neuron_1k_v3_S1_**L002**_**I1**_001.fastq.gz
- neuron_1k_v3_S1_**L002**_R1_001.fastq.gz
- neuron_1k_v3_S1_**L002**_R2_001.fastq.gz

Being the **I1** files the fastq containing the sample index (i7) for single index libraries: https://www.10xgenomics.com/support/single-cell-gene-expression/documentation/steps/sequencing/sample-index-sets-for-single-cell-3

As far as I understood, with this configuration each cell can be labeled with 4 different barcodes. Whow does STARsolo takes this into account? I haven't seen any option to provide the I1 files. 

Thanks in advance,
Marta.

**Comment by alexdobin** [comment]
Hi Marta,

the *I1* "index" read is used for multiplexing several samples into one Illumina run, so it's not needed for the STARsolo operation as long as you provide STARsolo with all R1 and R2 reads for each sample.

Cheers
Alex
