### ISSUE TITLE
Intronic read annotation in BAM for STARsolo

### ISSUE THREAD

**Issue by scideas** [alexdobin/STAR#1714]
Hey Alex, 
I am trying to extract read-level information about which alignments are intronic using the aligned BAM file output by STARsolo. I've been unable to find any tags that could be added to the BAM output to label reads deemed as intronic alignments- the only pertinent information I've found is the jI tag, indicating positions of the splice junctions, and the intronic "N" positional symbol for the alignments the CIGAR string. It looks like I will need to custom-write some code to extract this information from each STARsolo run. 

Is there an easy way that this intronic (and also ideally antisense) information could be optionally added via STAR to a tag in the BAM file? If not, could you please confirm which approach would be most efficient for extracting intronic alignments from the BAM and/or other files? At the moment, I'm looking at utilizing the jI tags along with the BAM's R2 sequence and CIGAR string in combination with the transcriptInfo file. 

Thanks for your help!

**Comment by alexdobin** [comment]
Hi @scideas 

presently there is no way to mark intronic or exonic alignments in a standard STAR run. 
However, you can try to hack STARsolo capabilities in this way.
First, run STAR with these extra parameters:
```--soloType SmartSeq --readFilesManifest /path/to/manifest.tsv --soloUMIdedup Exact --soloStrand Forward --soloFeature Gene --outSAMattributes NH HI AS nM GX GN```
The strandedness could be Forward, Reverse, or Unstranded.
This will label the exonic reads with GX/GN tags.
Then rerun STAR changing to ```--soloFeature GeneFull```, which will label both exonic and intronic reads with GX/GN.
Then you can compare the two BAM files to find reads that have the GX/GN tags in the 2nd run, but not in the first run - these will be intronic reads (including reads crossing exon/intron boundary).

**Comment by scideas** [comment]
Interesting- thank you for the info
