### ISSUE TITLE
Exon end is larger than chromosome length

### ISSUE THREAD

**Issue by manivenkatesan** [alexdobin/STAR#1716]
Hi Alex,

I'm coming across similar issues as raised in #963 and #988.  I'm using STAR version 2.7.10a 

I get these warnings (more examples in log file):

> !!!!! WARNING: while processing sjpbgtffile=/DATA/.../Homo_sapiens.GRCh38.106.gtf, line:
> 1	havana	exon	200669767	200669907	.	-	.	gene_id "ENSG00000118197"; gene_version "14"; transcript_id "ENST00000447706"; transcript_version "6"; exon_number "1"; gene_name "DDX59"; gene_source "ensembl_havana"; gene_biotype "protein_coding"; transcript_name "DDX59-206"; transcript_source "havana"; transcript_biotype "protein_coding"; exon_id "ENSE00001827363"; exon_version "1"; tag "basic"; transcript_support_level "2";
>  exon end = 200669907 is larger than the chrom
[min_failingset_venk 2.zip](https://github.com/alexdobin/STAR/files/10099134/min_failingset_venk.2.zip)
osome 1 length = 195154279 , will skip this exon

However, when I check my fasta file, it does start with position 1 and the length is larger than the exon end and I double checked I referenced to the correct fasta file:

> >1 dna:chromosome chromosome:GRCh38:1:1:248956422:1 REF
> NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
> NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
> NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN

I've attached parts of the Genome.fasta, Annot.gtf, Read1 and Read2 and the log file.

I can't seem to figure out the problem. Help would be much appreciated, thanks!
Many thanks,
Mani

[min_failingset_venk 2.zip](https://github.com/alexdobin/STAR/files/10099136/min_failingset_venk.2.zip)

**Comment by bkffadia** [comment]
I'm actually struggling with the same thing, 

> !!!!! WARNING: while processing sjdbGTFfile=/content/drive/MyDrive/gencode.v34.annotation.gtf, line:
chr8	HAVANA	exon	124945638	124945746	.	+	.	gene_id "ENSG00000249816.7"; transcript_id "ENST00000663642.1"; gene_type "lncRNA"; gene_name "LINC00964"; transcript_type "lncRNA"; transcript_name "LINC00964-253"; exon_number 3; exon_id "ENSE00002147318.1"; level 2; hgnc_id "HGNC:27226"; tag "TAGENE"; havana_gene "OTTHUMG00000165101.1"; havana_transcript "OTTHUMT00000519925.1";
 exon end = 124945746 is larger than the chromosome chr8 length = 229282 , will skip this exon

**Comment by alexdobin** [comment]
It seems the actual sequence length in the FASTA file is shorter than it should be.

**Comment by manivenkatesan** [comment]
I've uploaded just a portion of the FASTA file of chromosome 1, since it's otherwise a huge file. I downloaded the FASTA file from ENSEMBL, so I'm guessing it should be ok? Would you have any other suggestions, perhaps you have a preferred FASTA and GTF file that you use with STAR?

**Comment by alexdobin** [comment]
If you want to map to the entire chromosome, you would need to download the full sequence.
Or do you want to map to just a portion of the chromosome?

**Comment by manivenkatesan** [comment]
I want to map against the whole genome, so I downloaded the full human genome sequence from ensembl from these links. I used these files from the start and got the errors shown above (but I only uploaded a portion of chromosme 1 as an example of the FASTA file to my raised question since it's otherwise too large)

#Download reference files Download human reference genome: http://ftp.ensembl.org/pub/release-106/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz

#Download human gene annotation file: http://ftp.ensembl.org/pub/release-106/gtf/homo_sapiens/Homo_sapiens.GRCh38.106.gtf.gz

I am clueless why I'm getting the error. Do you recommend any specific FASTA and genome file to use with STAR, perhaps from gencode instead or a different ensembl genome release?

**Comment by alexdobin** [comment]
If you want to map to a portion of chromosome 1 as a test, you can ignore these warnings.

**Comment by manivenkatesan** [comment]
Thank you Alex, I'll do this as a test as suggested and upload the results.

**Comment by manivenkatesan** [comment]
Hi Alex, I simplified my snakemake pipeline bu splitting it into a human and mouse analysing pipeline and suddenly I don't get the error anymore. I'm not sure what caused the earlier problem. Either way thank you for your replies, much appreciated!
