### ISSUE TITLE
clarification of genomeConsensusFile in docs

### ISSUE THREAD

**Issue by cmatKhan** [alexdobin/STAR#1719]
With regards to the `genomeConsensusFile` setting, it is not clear to me what the format of this file is.

This is what my assumption is from the current docs:

If each of the input samples has known variants, they may be input per sample with `varVCFfile`. `genomeConsensusFile` may be used to specify sites for which the non-reference allele is the most common for this set of samples.

More clarification around what the `genomeConsensusFile` format is, preferably a minimal example of the file, and some mention of how using this setting and the `varVCFfile` setting interact (if at all) would be much appreciated. It would also be nice to have some mention of how either of these settings affects the `wasp` setting.

**Comment by alexdobin** [comment]
```--genomeConsensusFile``` was deprecated.
For STARconsensus runs, you would need to use ```--genomeTransformVCF``` and ```--genomeTransformType```.
However, they cannot be used with ```--varVCFfile```  or WASP options.

**Comment by cmatKhan** [comment]
I see re: `genomeConsebsusFile` -- i had an oldet copy of the docs. My bad.

To use the `wasp` setting, the `varVCFfile`is required, correct? Or is there another way to input variant info?

**Comment by alexdobin** [comment]
That's correct, the WASP VCF is imported via ```--varVCFfile``` option.
