### ISSUE TITLE
RSEM validation after deduplication

### ISSUE THREAD

**Issue by PenguinNell** [alexdobin/STAR#1722]
Dear Alex Dobin,

I ran into a problem generating files for RSEM. Aligned.toTranscriptome.out.bam file is not valid if I tried to remove duplicates before. There is an example of my code.
The problem is reproducible for different files. But if I get Aligned.toTranscriptome.out.bam at the step 1, RSEM says the file is valid. 

Could you advise anything to solve this problem?

Step 1
`STAR --runThreadN 20 --runMode alignReads --genomeDir GRCh38_r108_Ensembl/ --sjdbGTFfile GRCh38_r108_Ensembl/Homo_sapiens.GRCh38.108.gtf --sjdbOverhang 100 --readFilesIn test_R1_001.good.fq.gz test_R2_001.good.fq.gz --readFilesCommand zcat --outSAMtype BAM SortedByCoordinate --outFileNamePrefix test_`
	STAR version: 2.7.10a   compiled: 2022-01-14T18:50:00-05:00 :/home/dobin/data/STAR/STARcode/STAR.master/source
Dec 05 13:25:25 ..... started STAR run
Dec 05 13:25:25 ..... loading genome
Dec 05 13:25:43 ..... processing annotations GTF
Dec 05 13:26:01 ..... inserting junctions into the genome indices
Dec 05 13:27:45 ..... started mapping
Dec 05 13:28:21 ..... finished mapping
Dec 05 13:28:23 ..... started sorting BAM
Dec 05 13:28:28 ..... finished successfully

Step 2
`STAR --runThreadN 20 --limitBAMsortRAM 40000000000 --runMode inputAlignmentsFromBAM --bamRemoveDuplicatesType UniqueIdentical --inputBAMfile test_Aligned.sortedByCoord.out.bam --outFileNamePrefix test_markedDupl_`
Dec 05 13:28:40 ..... reading from BAM, remove duplicates, output BAM
Dec 05 13:29:05 ..... done

Step 3
`samtools view -b -F 0x400 test_markedDupl_Processed.out.bam > test_Aligned.removeDupl.bam`

Step 4
`samtools view test_Aligned.removeDupl.bam > test_Aligned_res.out.sam`

Step 5
`STAR --runThreadN 20 --runMode alignReads --genomeDir GRCh38_r108_Ensembl/ --sjdbGTFfile GRCh38_r108_Ensembl/Homo_sapiens.GRCh38.108.gtf --sjdbOverhang 100 --readFilesIn test_Aligned_res.out.sam --readFilesType SAM SE --quantMode TranscriptomeSAM GeneCounts --outFileNamePrefix test_`
	STAR version: 2.7.10a   compiled: 2022-01-14T18:50:00-05:00 :/home/dobin/data/STAR/STARcode/STAR.master/source
Dec 05 13:34:39 ..... started STAR run
Dec 05 13:34:39 ..... loading genome
Dec 05 13:34:57 ..... processing annotations GTF
Dec 05 13:35:15 ..... inserting junctions into the genome indices
Dec 05 13:36:47 ..... started mapping
Dec 05 13:36:56 ..... finished mapping
Dec 05 13:36:57 ..... finished successfully

Step 6
`rsem-sam-validator test_Aligned.toTranscriptome.out.bam`
The alignments of read A00835:243:H3GN5DRXY:2:2252:8576:8860 are not grouped together!
The input file is not valid!

**Comment by alexdobin** [comment]
Hi @PenguinNell 

I think you need to sort ```test_Aligned.removeDupl.bam``` by name, so that the PE reads are next to each other.
Also, you need to use ```--readFilesType SAM PE``` since these are PE reads.

**Comment by PenguinNell** [comment]
Hi Alex,

Thanks a lot! This solved the problem. 
And thank you for the comment about "PE".
