### ISSUE TITLE
I installed the 2.7.10b version with conda, but the index creates 2.5.3a.

### ISSUE THREAD

**Issue by yuki-asahikawa** [alexdobin/STAR#1727]
Hi Alex,
I installed the 2.7.10b version with conda, but the Log.out file created by index says STAR version=STAR_2.5.3a at the beginning. I tried to create a new conda virtual environment and install it there, but the result was the same. The mapping Log.out file also says STAR version=STAR_2.5.3a.
Can you please tell me the cause of this problem?

**Comment by alexdobin** [comment]
Hi @yuki-asahikawa 

if the 1st line of Log.out is not "STAR version=2.7.10b", then conda did not install it properly.
You do not really need conda for STAR installation, you can simply run the pre-compiled executable from STAR distribution.

**Comment by alexdobin** [comment]
Hi @yuki-asahikawa 
what is the output when you run STAR without any parameters - the download/uncompress/compiled executable.
You should see the version there.

**Comment by yuki-asahikawa** [comment]
The README.md file does indeed say STAR 2.7.10b, but when I run it, it is still 2.5.3a. It doesn't seem to be an easy solution, so I'm going to use this version for now. Thanks for your help.
