### ISSUE TITLE
Could not open genome file

### ISSUE THREAD

**Issue by nebskinner** [alexdobin/STAR#1729]
Hi,

I know this issue has come up for other people but I read those postings and still haven't been able to solve my problem.

When trying to do an alignment with STAR, I get the following error message: EXITING because of FATAL ERROR: could not open genome file ./GenomeDir//genomeParameters.txt

This is the script I ran:
#!/bin/bash
#SBATCH -t 24:00:00
#SBATCH --mem-per-cpu=40G

set -e

export PATH=$PATH:/home/gdskinnerlab/nes002/software/STAR-2.7.10b/source/

STAR \
--runThreadN 20\
--genomeDir /home/gdskinnerlab/nes002/HBV_visium/STAR_genome_indicesD \
--readFilesCommand zcat \
--readFilesIn /home/gdskinnerlab/nes002/HBV_visium/FASTA/concatenated/hLiver_N57_S2_R1_001.fastq.gz /home/gdskinnerlab/nes002/HBV_visium/FASTA/concatenated/hLiver_N57_S2_R2_001.fastq.gz \
--outSAMtype BAM Unsorted SortedByCoordinate \
--outReadsUnmapped \
–-chimOutType Junctions SeparateSAMold WithinBAM \
--chimSegmentMin 12 \
--chimJunctionOverhangMin 8 \
--chimMultimapNmax 20 \
--chimMultimapScoreRange 3 \
--chimNonchimScoreDropMin 10 \
–-chimScoreJunctionNonGTAG 0 \
--chimOutJunctionFormat 1 \
–-alignSJstitchMismatchNmax -1–1 -1–1 \
--outFileNamePrefix N57

I have an absolute path to my genome directory which I have triple checked. This is what I have in the directory:
drwxrwxrwx 2 nes002 gdskinnerlab        8192 Dec 17 10:58 .
drwxr-x--- 6 nes002 gdskinnerlab        8192 Dec 17 10:25 ..
-rwxrwxrwx 1 nes002 gdskinnerlab        1205 Dec 17 06:46 chrLength.txt
-rwxrwxrwx 1 nes002 gdskinnerlab        3137 Dec 17 06:46 chrNameLength.txt
-rwxrwxrwx 1 nes002 gdskinnerlab        1932 Dec 17 06:46 chrName.txt
-rwxrwxrwx 1 nes002 gdskinnerlab        2140 Dec 17 06:46 chrStart.txt
-rwxrwxrwx 1 nes002 gdskinnerlab    58416610 Dec 17 06:46 exonGeTrInfo.tab
-rwxrwxrwx 1 nes002 gdskinnerlab    24032712 Dec 17 06:46 exonInfo.tab
-rwxrwxrwx 1 nes002 gdskinnerlab     2494546 Dec 17 06:46 geneInfo.tab
-rwxrwxrwx 1 nes002 gdskinnerlab  3219407892 Dec 17 10:19 Genome
-rwxrwxrwx 1 nes002 gdskinnerlab        1002 Dec 17 10:19 genomeParameters.txt
-rwxrwxrwx 1 nes002 gdskinnerlab       43764 Dec 17 10:19 Log.out
-rwxrwxrwx 1 nes002 gdskinnerlab 24966210954 Dec 17 10:19 SA
-rwxrwxrwx 1 nes002 gdskinnerlab  1565873619 Dec 17 10:19 SAindex
-rwxrwxrwx 1 nes002 gdskinnerlab    11729950 Dec 17 10:08 sjdbInfo.txt
-rwxrwxrwx 1 nes002 gdskinnerlab    11586431 Dec 17 06:46 sjdbList.fromGTF.out.tab
-rwxrwxrwx 1 nes002 gdskinnerlab     9189032 Dec 17 10:08 sjdbList.out.tab
-rwxrwxrwx 1 nes002 gdskinnerlab    16438264 Dec 17 06:46 transcriptInfo.tab

This is the Log.out file for genome generation:
[Log.out.txt](https://github.com/alexdobin/STAR/files/10252152/Log.out.txt)

This is the Log.out file for the alignment attempt:
[N57Log.out.txt](https://github.com/alexdobin/STAR/files/10252153/N57Log.out.txt)

Thanks so much for your help!
Nicole

**Comment by nebskinner** [comment]
Sorry -- such a dumb mistake.

Can I ask one more question? In the junction output, a chromosome donor and acceptor is listed. How do you differentiate them (ie, how can you differentiate between a fragment from Chr 3 being inserted in Chr 6 versus a fragment of Chr 6 being inserted in Chr 3)? I ask because I've used this function to identify insertions of viral DNA into the human genome but many of the human-viral chimeras are listed as actually resulting from human DNA being inserted into the viral genome.

**Comment by alexdobin** [comment]
Hi Nicole,
these "donor" vs "acceptor" designations are arbitrary, no call is made about the direction of the actual transcript.

**Comment by nebskinner** [comment]
Thanks so much!
