### ISSUE TITLE
Unable to coordinate sort Aligned.out.bam using picard for STAR versions 2.5.2a

### ISSUE THREAD

**Issue by genetalks-fred** [alexdobin/STAR#173]
Hi there:
I have used STAR latest version v2.5.2a on my cancer RNA-seq data, when i use picard sort my Aligned.out.bam, An error "SAM validation error: ERROR: Record 1223, Read name HISEQ:604:C7A86ANXX:6:1102:4986:8056, Mate Alignment start (630645564) must be <= reference sequence length (133851895) on reference 12" happend.

While searched froum i found this issues has been resolved (https://github.com/alexdobin/STAR/issues/146), but i still get this error.

STAR commond:
./software/STAR-2.5.2a/bin/STAR --runThreadN 8 --outFilterType BySJout --outFilterMultimapNmax 20 --alignSJoverhangMin 13 --alignSJDBoverhangMin 7 --outSAMstrandField intronMotif --outFilterIntronMotifs RemoveNoncanonical --outSAMattrIHstart 0 --outSAMtype BAM Unsorted --chimSegmentMin 35 --chimOutType WithinBAM  --genomeDir --readFilesIn ..

The alignment records:
HISEQ:604:C7A86ANXX:6:1102:4986:8056    65      3       141264214       255     109M    12      630645564       0       AGCTTCCAATCATAACAAACACCAAGCGGGAGCAGGTGTCCTACATGGCAGGAGCAGGAACAGGAGAGAGAGTGGGGAGGTACTACATACTTTTTTTTTTTTTTTTTTT   BBBBBFFFFFFBBBFFFFFFFFFFFFFFFFFFFBFFFFF/FFFFFB/FFFFFFB<FFFFFBFFBFF/FFBFFFBFFFFFFFFFFFFFFFFFFFF<FFFFFFFFFFFFBF   NH:i:1  HI:i:1  AS:i:107        nM:i:0  NM:i:0
HISEQ:604:C7A86ANXX:6:1102:4986:8056    129     12      110289724       255     125M    3       1836287318      0       CTCACTGCAACCTCCACCTCCCGGGTTCAAGCGATTCTCCTGCCTCAGCCTCCTAAGTAGCTGGAACTACAGGCGTGCGCCACCATGCCCAGCTAATTTTTTATATTTTTAGTAGCGATGGGGTT   BBBBB/BFFFFFFFFFFFFFFFFF/<<<BFFFFFFBFFFFFFFF</FFFFFFFFF<FFFFFBBB<BFBFF/FFF<FBFFFFFFFBBFFFF/<BFFFBFFBFFFF/BFFFF<<FBFFFFFFFFFFB   NH:i:1  HI:i:1  AS:i:121        nM:i:1  NM:i:1

Really need your help.
Thanks
Fred

**Comment by alexdobin** [comment]
Hi Fred,

please try the latest master version: [https://github.com/alexdobin/STAR/archive/master.zip]
If it does not help, please try to run it without the --chimOutType WithinBAM option.
If nothing works, please send me the Log.out file, the link to genome fasta and gtf, and minimalist set of reads that reproduces the problem (it could be that this read alone is enough).

Cheers
Alex
