### ISSUE TITLE
STAR generateGenome hangs at sorting Suffix Array chunks

### ISSUE THREAD

**Issue by typist001** [alexdobin/STAR#1731]
I'm trying to generate a custom genome of all protein coding genes in hg38. The fasta file I generated is structured in a way were each gene is an individual record  instead of each chromosome. Overall, it's like I have 25k different "chromosomes". I then wanted to create a custom genome from this fasta file to use for mapping. To do this I've used the command below:

```
STAR --runThreadN 2 --runMode genomeGenerate --genomeDir ./star --genomeFastaFiles refseq_uniqgenes.fasta --genomeSAindexNbases 14 --genomeSAsparseD 3 --genomeChrBinNbits 17 --limitGenomeGenerateRAM 16357785866
```

I calculated both the --genomeSAindexNbases and --genomeChrBinNbits based on the STAR manual. However, whenever I try to run genomeGenerate, STAR always hangs up at 'sorting Suffix Array chunks and saving them to disk' and just sits there for days. Is there something that I'm doing wrong? Any suggestions on how I may be able to get this to work? I'm desperate for any tips. I've been trying for days to get this to work, including trying to increase RAM to 128GB and Threads to 12 by running in on aws batch. I've attached my log.out file for reference

[Log.out.txt](https://github.com/alexdobin/STAR/files/10315012/Log.out.txt)

**Comment by alexdobin** [comment]
Hi @typist001 

since the "genome" sequence may be repetitive, this option might help to speed up genome generation:
```--genomeSuffixLengthMax 300```. The length here is the maximum read length you are planning to map.

**Comment by typist001** [comment]
Hi @alexdobin  I think this solved my problem!! Thank you so much for taking the time to offer guidance!
