### ISSUE TITLE
make error on centos6.2

### ISSUE THREAD

**Issue by falconer502** [alexdobin/STAR#174]
Hi:
I got the following error while trying to install STAR:

g++ -c   -O3 -pipe -std=c++11 -Wall -Wextra -fopenmp -D'COMPILATION_TIME_PLACE="Sat Aug 13 16:08:07 CST 2016 cluster.hpc.org:/home/wangyongqiang/biosoft/STAR-master/source"'  SuffixArrayFuns.cpp
{standard input}: Assembler messages:
{standard input}:1148: Error: expecting string instruction after `rep'
{standard input}:1738: Error: expecting string instruction after`rep'
{standard input}:1789: Error: expecting string instruction after `rep'
{standard input}:1853: Error: expecting string instruction after`rep'
make: **\* [SuffixArrayFuns.o] Error 1

I upgrade gcc (gcc 4.8.2) and binutils  (binutils.x86_64 0:2.20.51.0.2-5.44.el6) using command " sudo yum update binutils". But the error  still exist.
hope you can help me !
thank you very much !
best!

**Comment by alexdobin** [comment]
Hi @falconer502 

I have never seen such an error before. Googling shows that most people believe this is some compiler configuration problem. You can try to install a separate version of gcc (*not* updating the system gcc) from scratch to test this. Or you can use the pre-compiled binaries in the bin directory.

Cheers
Alex
