### ISSUE TITLE
Generating Index for a custom Fasta file

### ISSUE THREAD

**Issue by Shashankti** [alexdobin/STAR#1741]
Hello,

I have a fasta file which contains repetitive sequences, however I am unable to generate STAR index to perform the alignment.
On running
`STAR --runThreadN 16 \
--runMode genomeGenerate \
--genomeDir /scratch1/users/shashank.tiwari/RepElements \
--genomeFastaFiles /scratch1/users/shashank.tiwari/RepElements/9606.fasta \
--sjdbGTFfile /scratch1/users/shashank.tiwari/Final_fastq_files/Genome/Homo_sapiens.GRCh38.108.gtf \
--sjdbOverhang 75 --outFileNamePrefix L_75bp/human_index --limitGenomeGenerateRAM 15000000000 --genomeSAsparseD 2`

I am stuck on the output
`Jan 13 12:27:00 ..... started STAR run
Jan 13 12:27:00 ... starting to generate Genome files
WARNING: --genomeSAindexNbases 14 is too large for the genome size=422838272, which may cause seg-fault at the map$
Jan 13 12:27:02 ... starting to sort Suffix Array. This may take a long time...
Jan 13 12:27:03 ... sorting Suffix Array chunks and saving them to disk...
Jan 13 12:27:04 ... loading chunks from disk, packing SA...
Jan 13 12:27:04 ... finished generating suffix array
Jan 13 12:27:04 ... generating Suffix Array index
Jan 13 12:27:07 ... completed Suffix Array index
Jan 13 12:27:07 ..... processing annotations GTF
slurmstepd: error: *** JOB 14540466 ON amp086 CANCELLED AT 2023-01-15T08:26:55 DUE TO TIME LIMIT ***`

and the following output in the log.out

`WARNING: while processing pGe.sjdbGTFfile=/scratch1/users/shashank.tiwari/Final_fastq_files/Genome/Homo_sapiens.GRCh38.108.gtf: chromosome 'KI270713.1' not found in Genome fasta files for line:
KI270713.1      ensembl exon    35407   35916   .       +       .       gene_id "ENSG00000268674"; gene_version "2"; transcript_id "ENST00000601199"; transcript_version "2"; exon_number "1"; gene_source "ensembl"; gene_biotype "protein_coding"; transcript_source "ensembl"; transcript_biotype "protein_coding"; exon_id "ENSE00003108086"; exon_version "2"; tag "basic"; tag "Ensembl_canonical"; transcript_support_level "NA";
WARNING: while processing pGe.sjdbGTFfile=/scratch1/users/shashank.tiwari/Final_fastq_files/Genome/Homo_sapiens.GRCh38.108.gtf: chromosome 'KI270713.1' not found in Genome fasta files for line:
KI270713.1      ensembl exon    31698   32528   .       -       .       gene_id "ENSG00000277475"; gene_version "1"; transcript_id "ENST00000612315"; transcript_version "1"; exon_number "1"; gene_source "ensembl"; gene_biotype "protein_coding"; transcript_source "ensembl"; transcript_biotype "protein_coding"; exon_id "ENSE00003739404"; exon_version "1"; tag "basic"; tag "Ensembl_canonical"; transcript_support_level "NA";
WARNING: while processing pGe.sjdbGTFfile=/scratch1/users/shashank.tiwari/Final_fastq_files/Genome/Homo_sapiens.GRCh38.108.gtf: chromosome 'KI270713.1' not found in Genome fasta files for line:
KI270713.1      ensembl exon    21861   22024   .       -       .       gene_id "ENSG00000275405"; gene_version "1"; transcript_id "ENST00000619109"; transcript_version "1"; exon_number "1"; gene_name "U1"; gene_source "ensembl"; gene_biotype "snRNA"; transcript_name "U1.26-201"; transcript_source "ensembl"; transcript_biotype "snRNA"; exon_id "ENSE00003747303"; exon_version "1"; tag "basic"; tag "Ensembl_canonical"; transcript_support_level "NA";
`
Could you please suggest a way to generate index using the fasta file which I am attaching in the issue?

Thanks,
Shashank
[9606.txt](https://github.com/alexdobin/STAR/files/10425825/9606.txt)

**Comment by alexdobin** [comment]
Hi Shashank,

for very repetitive genomes, you will need to use --genomeSuffixLengthMax 300. This number should be larger than the maximum read length you are planning to map.

**Comment by Shashankti** [comment]
Hey Alex,

Thank you for your response, do you think I can use the same gtf file for the mapping, or should the `gtf` file be modified as well for indexing and alignment?

Thanks,
Shashank

**Comment by alexdobin** [comment]
Hi Shashank,

I am not sure what GTF modifications you are referring to.

**Comment by Shashankti** [comment]
Hey Alex,

I am sorry, I was confused about some of the running parameters. After reading the documentation I now have a clearer idea. Thank you for your help.
Best,
Shashank
