### ISSUE TITLE
Error: genomeGenerate killed

### ISSUE THREAD

**Issue by a-smith1** [alexdobin/STAR#1753]
Hi,

I am currently trying to run genome Generate on a MacPro in a containerized version of Docker I have created that has an Ubuntu base OS (20.04). Previously this has worked on all other linux machines (local and cloud) I have used this container on. But seem to be having Issues with this MacPro. The OS is HighSierra (unable to update due to legacy and IT issues).

I have 24 Threads and 64GiB Memory available.

The command I am using is:

```
STAR \
--runThreadN 20 \
--runMode genomeGenerate \
--genomeDir /binfx/STAR_BigMac \
--genomeFastaFiles /binfx/Reference/GRCh38_NCBI_109.20200522/GRCh38_NCBI_109.20200522.fa \
--sjdbGTFfile /binfx/Reference/GRCh38_NCBI_109.20200522/GRCh38_NCBI_109.20200522.gtf \
--limitBAMsortRAM 60000000000
```

Here is the docker run cmd:

```
docker run \
-v /Volumes/D\ Drive\ RAID\ Set\ 2/binfx:/binfx \
--rm -it \
mqmnd/star:amd-2.7.10b_alpha_220111
```

Here is the error message I keep getting, but I cant seem to figure out why this is happening, unless it is an issue with running it on Mac

```
STAR version: 2.7.10b_alpha_220111   compiled: 2023-01-25T04:34:07+00:00 33179766c63b:/STAR/source
Feb 07 23:09:15 ..... started STAR run
!!!!! WARNING: Could not move Log.out file from ./Log.out into /binfx/STAR_BigMac/Log.out. Will keep ./Log.out

Feb 07 23:09:15 ... starting to generate Genome files
Killed
```

Any help would be greatly appreciated!

**Comment by lopezCascales** [comment]
Hi Alex, I have a laptop wit 32GB of RAM, and 6 cores, but when I try to generate an index, appear a Killed message. I attache de log.out

STAR --runMode genomeGenerate --genomeDir ./indexes --genomeFastaFiles GCF_000001405.40_GRCh38.p14_genomic.fa --sjdbGTFfile GCF_000001405.40_GRCh38.p14_genomic.gtf --sjdbOverhang 50 --outFileNamePrefix human --runThreadN 6 --genomeSAsparseD 3 --genomeSAindexNbases 12

Mar 13 09:10:29 ..... started STAR run
Mar 13 09:10:29 ... starting to generate Genome files
Mar 13 09:11:04 ... starting to sort Suffix Array. This may take a long time...
Mar 13 09:11:09 ... sorting Suffix Array chunks and saving them to disk...
Killed

[humanLog.out.txt](https://github.com/alexdobin/STAR/files/10955097/humanLog.out.txt)

**Comment by alexdobin** [comment]
Hi Maria,

it seems that the Log.out file is from a different run. The error message in the file is:
```EXITING because of INPUT ERROR: could not open genomeFastaFile: GCF_000001405.40_GRCh38.p14_genomic.fa```

**Comment by alexmascension** [comment]
Hi! I'm having a similar error. In my case I'm running docker with this command:

```
docker run -it --rm -v $(pwd)/database:/database       quay.io/biocontainers/star:2.7.11a--h0033a41_0
```

Just to make sure that there is no problem with the directories I copy all necessary files:
```
mkdir STAR
cp database/genomes/GRCh38/genome.fasta STAR/genome.fasta
cp database/genomes/GRCh38/genes.gtf STAR/genes.gtf
```

And I run the command
```

STAR  \
            --runMode genomeGenerate \
            --genomeDir STAR \
            --genomeFastaFiles STAR/genome.fasta  \
            --sjdbGTFfile STAR/genes.gtf
```

The original command included the parameters `--runThreadN 9  --genomeSAindexNbases 14   --limitGenomeGenerateRAM 77000000000` but it also failed.

The output is the following:

```
Jan 22 09:55:01 ..... started STAR run
Jan 22 09:55:01 ... starting to generate Genome files
Jan 22 09:55:34 ... starting to sort Suffix Array. This may take a long time...
Jan 22 09:55:42 ... sorting Suffix Array chunks and saving them to disk...
Killed
```


Interestingly, running STAR (the same version) in local, with the same command and files, did not fail, so there must be something with the docker implementation.



[Log.out.txt](https://github.com/alexdobin/STAR/files/14008463/Log.out.txt)
[genome-genes.zip](https://1drv.ms/u/s!AjeKlLW-dT0vwXP_sQxUl_OetGfc?e=g5Gem6)

**Comment by alexdobin** [comment]
Hi Alex,

this could be an insufficient RAM issue; please check this post:
https://github.com/alexdobin/STAR/issues/2045#issuecomment-1909045139

**Comment by alexmascension** [comment]
Hi! 

I solved the issue by running another docker container that nf-core uses:

[quay.io/biocontainers/mulled-v2-1fa26d1ce03c295fe2fdcf85831a92fbcbd7e8c2@sha256:74c2d751f5090bdc543f8922f37ab52cc0fae1f295e73923e00a694a697535d9](quay.io/biocontainers/mulled-v2-1fa26d1ce03c295fe2fdcf85831a92fbcbd7e8c2@sha256:74c2d751f5090bdc543f8922f37ab52cc0fae1f295e73923e00a694a697535d9)

But if for some reason it happens again I'll take a look into the #2045 issue.

Thanks!

**Comment by alexmascension** [comment]
Hi! I had another issue and trying with the #2045 comment it works! 

Thanks!
