### ISSUE TITLE
Found BC difference between BAM tags and Barcodes.stats

### ISSUE THREAD

**Issue by mbahin** [alexdobin/STAR#1759]
Hi Alex,

Unless I'm mistaken, I found a discrepancy between the added counts of `yesWLmatchExact` (=1,355,010) and `yesOneWLmatchWithMM` (=193,851) in `Barcodes.stats` and the count of reads with a filled CB tag (=1,526,215 with the command `samtools view <path_.Aligned.sortedByCoord.out.bam> | grep -cv "CB:Z:-"`).

I ran the following STARsolo command at first:
```
STAR \
  --genomeDir <path_to_genome>
  --genomeLoad LoadAndKeep
  --readFilesIn <R1_file> <R2_file>
  --readFilesCommand zcat
  --outFileNamePrefix <prefix>
  --outSAMattributes CR CB UR UB GX GN AS NH
  --outSAMunmapped Within
  --soloType CB_UMI_Simple
  --soloCBwhitelist <whitelist>
  --soloUMIlen 10
  --runThreadN 15
  --outSAMtype BAM SortedByCoordinate
  --outFilterMultimapNmax 1
  --outFilterScoreMinOverLread 0
  --outFilterMatchNminOverLread 0.3
  --limitBAMsortRAM 10000000000
  --soloCellReadStats Standard
  --soloFeatures Gene GeneFull GeneFull_ExonOverIntron GeneFull_Ex50pAS
```

Am I misunderstanding something or is it some kind of strange behaviour?

Cheers,
Mathieu

**Comment by alexdobin** [comment]
Hi Mathieu

The values reported in Barcodes.stats are there as an estimate and may not exactly agree with what's reported in the BAM output. BAM file is the best place to look for the perfectly correct numbers.
