### ISSUE TITLE
Reference Size Limit

### ISSUE THREAD

**Issue by wrosan** [alexdobin/STAR#176]
I want to use STAR aligner on my RNAseq data. However, I am concerned about the note of caution written in the reference file I downloaded. The note was:

----> gzipped FASTA file with pseudomolecule sequences for the seven barley chromosomes
and one pseudomolecule composed of unanchored contigs.

CAUTION: This file should NOT be used as a reference for read mapping
with mappers such as BWA, Tophat or STAR as the BAM output format used
by these mappers limits the reference size to (2^29 - 1) bp (512 MB). <-----

The size of my reference file is 4.5GB and is it possible to still use it with STAR aligner? Can you help me with?

**Comment by alexdobin** [comment]
Hi @wrosan,

this is actually the BAM format limitation that does not allow for single "chromosomes" to be longer than 512MB. You can still use STAR with "SAM" output only. Another option is to break this long sequence into smaller pieces - the contigs boundaries would be good breakpoints.

Cheers
Alex
