### ISSUE TITLE
STAR inconsistently picks equivalent alignments for different reads

### ISSUE THREAD

**Issue by Redmar-van-den-Berg** [alexdobin/STAR#1760]
When there are multiple ways to align a read to the reference, it appears that STAR will randomly pick different options for different reads. This leads to issues with downstream variant calling, since the 'mutation' is spread out over multiple positions.

Here is an example for a G insertion in a 8bp poly-G stretch. On the top is the alignment according to the GSNAP aligner, which puts all the 'G' insertions at the start of the poly-G stretch.

At the bottom, you can see that STAR puts the insertion in 3 different positions.
![image](https://user-images.githubusercontent.com/15814544/218469152-544eaa4b-486b-4228-93a4-f50462c28273.png)

Note that this example with a poly-G stretch was chosen for simplicity, the same issue occurs with more complex alignments with multiple insertions and deletions, when multiple equivalent alignments are possible.

My question is if this is the intended behaviour, and whether there is an option I can use to force STAR to always pick the same alignment (e.g. always pick the right/left most representation of the alignment).

**Comment by alexdobin** [comment]
Hi Redmar,

this option might help:
```--alignInsertionFlush Right```
In general, I would recommend local realignment of STAR alignments that contain indels.
