### ISSUE TITLE
BAM Sorting failed

### ISSUE THREAD

**Issue by Rahul1711arora** [alexdobin/STAR#1762]
Hi, 

I have been running STARsolo on my datasets for a while and it runs fine But lately, I'm getting this problem with one dataset. 
The original files available for download were BAM files which were converted back to FASTQ with cellranger v6.1.2. I have been trying to run starsolo using the following parameters on these fastq files: 

```
STAR --genomeDir Dir/to/genome \
    --readFilesIn file_1_R2,file_2_R2,file_3_R2,file_4_R2,file_5_R2 \
    file_1_R1,file_2_R1,file_3_R1,file_4_R1,file_5_R1 \
    --readFilesCommand zcat \
    --outSAMtype BAM SortedByCoordinate \
    --outBAMsortingBinsN 200 \
    --outBAMsortingThreadN 5 \
    --limitBAMsortRAM 72023782130 \
    --outFileNamePrefix MS_S1_ \
    --soloType Droplet \
    --soloCellFilter  EmptyDrops_CR 3000 0.99 10 45000 90000 500 0.01 20000 0.01 10000 \
    --soloFeatures GeneFull SJ Velocyto \
    --soloMultiMappers Rescue \
    --outFilterScoreMin 30 \
    --soloCBwhitelist None \
    --soloCBmatchWLtype 1MM_multi_Nbase_pseudocounts \
    --soloUMIfiltering MultiGeneUMI_CR \
    --soloUMIdedup 1MM_CR \
    --outFilterMultimapNmax 1 \
    --alignIntronMin 25 \
    --alignIntronMax 1000000 \
    --alignSJoverhangMin 8 \
    --alignSJDBoverhangMin 3 \
    --clipAdapterType CellRanger4 \
    --limitSjdbInsertNsj 5000000 \
    --soloBarcodeReadLength 28 \
    --soloUMIlen 12
```

The mapping runs fine and so does the count. The BAM file generated starts getting sorted and it keeps running for long hours and the job fails. I tried to run it with 12 hour limit initially and then for 24 hours but failed each time. See below: 

```
STAR version: 2.7.10b   compiled: 2022-11-01T09:53:26-04:00 :/home/dobin/data/STAR/STARcode/STAR.master/source
Feb 14 11:01:05 ..... started STAR run
Feb 14 11:01:05 ..... loading genome
Feb 14 11:06:23 ..... started mapping
Feb 14 13:56:45 ..... finished mapping
Feb 14 13:56:46 ..... started Solo counting
Feb 14 13:59:56 ..... finished Solo counting
Feb 14 13:59:56 ..... started sorting BAM
```

It failed with the following message:

`Slurm Job_id=14324181 Name=MS_S1_starsolo Failed, Run time 1-00:00:10, TIMEOUT, ExitCode 0`

At this stage, I'm not sure what is the best approach as the original BAM files were deleted after converting them to FASTQs. 
Any help will be much appreciated. 

Best,
Rahul

**Comment by alexdobin** [comment]
Hi Rahul,

The original BAM was sorted, which caused trouble for STAR BAM sorting.
You have a couple of options:
1). Generate Unsorted BAM with STAR, then sort it with samtools.
2). Shuffle the original BAM file before generating BAMs with samtools collate.

**Comment by Rahul1711arora** [comment]
Hi Alex,

Thanks for the suggestion. It worked like a charm. 

I have now run into another situation with a second dataset. 

I have two fastqs: R1 and R2. the details about the method section from the publication suggests that 10x 3' library preparation was used with v3 kit. Therefore, default setting for `--soloBarcodeReadLength 28` and `--soloUMIlen 10` should be used with R1 containing the barcode and UMI. 

Unfortunately, the R1 file contains the reads which are of length 101bp. Similar is the case with R2. 

These are the first 3 reads from R1 file: 

`@SRR15503370.1 1/1
TNTTCCACAAGGGCATCTAAAGTCAGGGTTTTAATAAAGAGTCTGATATAGAGATGATTGTTTTGTTAAATATATAGAGGGATAAAAGGGCTGTTACAATA
+
:#,FFFFF:F:F:FFFFF:FF:FFFFF::FF:,F:,,:,F,:,:,FF,FF,,,,F,F,FF,:,FF,:FFFFFF,,F:FF,FF,:F,FF::F,,,,F,,,,:
@SRR15503370.2 2/1
CNAACCCGTACATTGCCCCCCTCAGGAAAATAATAAATATCATAATAAATCTATGCCATGGTCTCTAAGTCACATCCCATGTACTCTGCGTTTATACCCCA
+
F#FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF,,F,,:F,:,,,,,,,,,,,,,:FF,F:FFF:FF:FF,FFF:,FF:F,F,FF,F::FF:F,F:FF,,F,
@SRR15503370.3 3/1
ANGTCATCATCGGAAGGAGAATTATATTTGTTGTTGAGACTCTCAGAGACAAATTTTCTAATACCCACATCAAAAGATTTAGACAAACAGAAAAAGTCAAA
+
F#FFFFFFFFFFFFFFFFFFFFFFFFFFF,F,,,:,,,,,F,,,,,,,,,F,,F:F:F,FF,FFFF,FF,:FF,F,:F,,FFFFF,FF:,FFF,FF,F:,:`

Similarly, these are the first 3 reads from the file R2:

`@SRR15503370.1 1/2
GTCGCATCATAATCCTCTCTAAAGGACTTCAAACTCTACTCCCACTAATAGCTTTTTGATGACTTCTAGCAAGCCTCGCTAACCTCGCCTTACCCCCCACT
+
F,FFFF:FFFFF:FFFFFFF,FF:FF::F,FFFFFFF,:,F::FF,F:,,:FF,F:,:FFF:F,FF,FFFFF::FF,FF:FF:F,F:FFF:FFF,F:F:FF
@SRR15503370.2 2/2
AAGCAGTGGTATCAACGCAGAGTACATGGGATGTGACTTAGAGACCATGGCAAAAAAAAAAAAAAAAAAAAAAAAAATTACTGAGGGGGGCAATGTACGGG
+
FFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFF:FFFFF:FFFFFFFFFFFFFFFFFFFFFFFF:F,,,,,FFFFFFF,FF,,F,FFF
@SRR15503370.3 3/2
AAGCAGTGGTATCAACGCAGAGTACATGGGTTACCCTCCTACAAGCCTCAGAGTACTTCGAGTCTCCCTTCACCATTTCCGACGGCATCTACGGCTTAACA
+
FFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFF:FFFFFFFF:FFFFFFFFF::FFFFF,FFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFF`


In order to process a file like this, I found that a similar question was asked [here](https://github.com/alexdobin/STAR/issues/1631)

But what I understand from the original document for STARsolo command, that this is rather 10x 5' library sequencing kit. Do you think it is the case and that is why this needs additional arguments as suggested in the document? 

In line with the suggestion on the issue raised [here](https://github.com/alexdobin/STAR/issues/1631), I tried to run mapping with the following command: `--soloBarcodeReadLength 0`. But unfortunately, 0% reads were mapped. Therefore, I was wondering if you could suggest another quick fix for this? 

Thanks in advance

Best,
Rahul

**Comment by alexdobin** [comment]
Hi Rahul,

if this is 3' v3 library, it should be mapped with
```--readFilesIn Read2 Read1 --soloBarcodeReadLength 0 --soloUMIlen 12```
The first read from Read2 file BLATs well to chrM.

**Comment by Rahul1711arora** [comment]
Hi Alex, 

Apologies for the late reply. Thank you for your suggestion. Yes, after adding the argument `--soloUMIlen 12`, the mapping worked well. Thank you very much for your time and assistance. 

Thanks,
Rahul
