### ISSUE TITLE
extracting cell/gene/UMI read count vector

### ISSUE THREAD

**Issue by NikicaJEa** [alexdobin/STAR#1770]
Hi,

is it possible to extract cell/gene/UMI read count vector with StarSolo? 
E.g. 10 reads of cell1_gene1_UMI1, 20 reads of cell1_gene1_UMI2  etc..  Any guidance is much appreciated!

**Comment by alexdobin** [comment]
Hi @NikicaJEa 

to extract specific reads that mapped to cell/gene/UMI, you would need to process the BAM output: CB/GX/UB tags.

**Comment by NikicaJEa** [comment]
Thank you!
