### ISSUE TITLE
indexing genome with STAR version 2.7.3a gives versionGenome	2.7.1a

### ISSUE THREAD

**Issue by AonghusNaughton** [alexdobin/STAR#1773]
I can't understand why. I am trying to create a STAR index genome version 2.7.3.a for using with the zUMIs pipeline. I have STAR version 2.3.7a installed but for some reason it outputs an earlier version when creating an STAR index. 

`/disk2/user/aonnau/software/STAR-2.7.3a/source/STAR \
--runMode genomeGenerate \
--runThreadN 30 \
--genomeDir ../starIdx273a \
--genomeFastaFiles ../Homo_sapiens.GRCh38.dna.primary_assembly.fa \
--sjdbGTFfile ../Homo_sapiens.GRCh38.108.gtf \
--limitGenomeGenerateRAM=128000000000`

**Comment by AonghusNaughton** [comment]
`STAR-2.7.3a/source/STAR --version
2.7.3a`

**Comment by alexdobin** [comment]
I am not sure what you mean by "it outputs an earlier version when creating an STAR index".

**Comment by AonghusNaughton** [comment]
> I am not sure what you mean by "it outputs an earlier version when creating an STAR index".

Hi, apologies for my lack of clarity and thanks for getting back to quickly. What I meant was that when I use the genomeGenerate parameter with version STAR version 2.7.3a, the indexed genome version that gets created is 2.7.1a (according to versionGenome on the genomeParameters.txt file). This results in a warning when I run zUMIs pipeline, although it is not an issue as I initially thought so it's ok to close this thread. Thanks again!

**Comment by alexdobin** [comment]
The versionGenome in genomeParameters.txt defines backward compatibility: the earliest version of STAR that can be used to index the genome.
