### ISSUE TITLE
Error with --clip3pAdapterSeq option

### ISSUE THREAD

**Issue by vbenigno** [alexdobin/STAR#1775]
Hi Alex,

I run into an error if I specify two space-separated adapter sequences to be trimmed with the --clip3pAdapterSeq flag. This is the error that I get:

`EXITING because of fatal PARAMETER error: --clip3pAdapterSeq has to contain 1 values to match the number of mates.
SOLUTION: specify 1values in --clip3pAdapterSeq , for no clipping use -
Feb 28 14:07:18 ...... FATAL ERROR, exiting`

And this is the command (STAR version=2.7.10b):

`STAR --genomeDir ${directory}/genomeDir_split2 --runThreadN 32 \
--readFilesCommand zcat --readFilesIn ${directory}/SPLiTseq2_1_L1_R1_001.fastq.gz,${directory}/SPLiTseq2_1_L2_R1_001.fastq.gz,${directory}/SPLiTseq2_2_L1_R1_001.fastq.gz,${directory}/SPLiTseq2_2_L2_R1_001.fastq.gz ${directory}/SPLiTseq2_1_L1_R2_001.fastq.gz,${directory}/SPLiTseq2_1_L2_R2_001.fastq.gz,${directory}/SPLiTseq2_2_L1_R2_001.fastq.gz,${directory}/SPLiTseq2_2_L2_R2_001.fastq.gz \
--soloType CB_UMI_Complex --soloCBposition 0_10_0_17 0_48_0_55 0_78_0_85 \
--soloUMIposition 0_0_0_9 --soloCBwhitelist ${directory}/barcodes_r2_r3_solo_parse.txt ${directory}/barcodes_r2_r3_solo_parse.txt ${directory}/barcodes_r1_solo_all_parse.txt \
--soloCBmatchWLtype 1MM --soloUMIdedup 1MM_All --soloFeatures GeneFull \
--outFilterScoreMinOverLread 0 --outFilterMatchNminOverLread 0 \
--outFilterMatchNmin 20 --alignSJDBoverhangMin 1000 --alignSJoverhangMin 1000 --soloMultiMappers Uniform \
--outSAMattrRGline ID:SPLiTseq2_1_L1 , ID:SPLiTseq2_1_L2 , ID:SPLiTseq2_2_L1 , ID:SPLiTseq2_2_L2 --outFileNamePrefix "/scratch/vbenigno/starsolo_output/"  \
--clip3pAdapterSeq AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT --clip3pAdapterMMp 0.1`

If I run the exact same command but with only one sequence after the --clip3pAdapterSeq flag, it works just fine, and it recognizes that I have 4 fastq files for each mate. Do you know why it doesn't let me specify two adapter sequences even though I input two read mates?

Thanks

Valentina

**Comment by alexdobin** [comment]
Hi Valentina,

In your run, the second read file is the barcode read, and it cannot be trimmed. The clip options only work for trimmable reads.
