### ISSUE TITLE
STAR 2.4.1d installation error on CenterOS linux platform

### ISSUE THREAD

**Issue by wulc21** [alexdobin/STAR#178]
Dear professor, when I install the  STAR 2.4.1d  for the first time, I encounter the following problem, please give me a hand, thank you very much.

[noncode@gnode108 source]$ make STAR
Makefile:71: Depend.list: No such file or directory
make -C htslib lib-static
make[1]: Entering directory `/leofs/noncode/wulc/HCC_pvtt/software/STAR-STAR_2.4.1d/source/htslib'
gcc -g -Wall -O2 -I. -DSAMTOOLS=1 -c -o hts.o hts.c
In file included from /leofs/noncode/dxj/samtools-1.3/htslib-1.3/htslib/sam.h:30,
                 from /leofs/noncode/dxj/samtools-1.3/htslib-1.3/cram/cram_samtools.h:61,
                 from cram/cram.h:47,
                 from hts.c:11:
/leofs/noncode/dxj/samtools-1.3/htslib-1.3/htslib/hts.h:128: error: conflicting types for 'htsFile'
htslib/hts.h:58: note: previous declaration of 'htsFile' was here
/leofs/noncode/dxj/samtools-1.3/htslib-1.3/htslib/hts.h:306: error: conflicting types for 'hts_open'
htslib/hts.h:106: note: previous declaration of 'hts_open' was here
/leofs/noncode/dxj/samtools-1.3/htslib-1.3/htslib/hts.h:336: error: conflicting types for 'hts_close'
htslib/hts.h:113: note: previous declaration of 'hts_close' was here
/leofs/noncode/dxj/samtools-1.3/htslib-1.3/htslib/hts.h:361: error: conflicting types for 'hts_getline'
htslib/hts.h:115: note: previous declaration of 'hts_getline' was here
/leofs/noncode/dxj/samtools-1.3/htslib-1.3/htslib/hts.h:380: error: conflicting types for 'hts_set_threads'
htslib/hts.h:134: note: previous declaration of 'hts_set_threads' was here
/leofs/noncode/dxj/samtools-1.3/htslib-1.3/htslib/hts.h:389: error: conflicting types for 'hts_set_fai_filename'
htslib/hts.h:143: note: previous declaration of 'hts_set_fai_filename' was here
/leofs/noncode/dxj/samtools-1.3/htslib-1.3/htslib/hts.h:420: error: conflicting types for 'hts_pair64_t'
htslib/hts.h:178: note: previous declaration of 'hts_pair64_t' was here
/leofs/noncode/dxj/samtools-1.3/htslib-1.3/htslib/hts.h:435: error: conflicting types for 'hts_itr_t'
htslib/hts.h:192: note: previous declaration of 'hts_itr_t' was here
/leofs/noncode/dxj/samtools-1.3/htslib-1.3/htslib/hts.h:451: error: conflicting types for 'hts_idx_save'
htslib/hts.h:206: note: previous declaration of 'hts_idx_save' was here
/leofs/noncode/dxj/samtools-1.3/htslib-1.3/htslib/hts.h:509: error: conflicting types for 'hts_itr_query'
htslib/hts.h:216: note: previous declaration of 'hts_itr_query' was here
/leofs/noncode/dxj/samtools-1.3/htslib-1.3/htslib/hts.h:510: error: conflicting types for 'hts_itr_destroy'
htslib/hts.h:217: note: previous declaration of 'hts_itr_destroy' was here
/leofs/noncode/dxj/samtools-1.3/htslib-1.3/htslib/hts.h:514: error: conflicting types for 'hts_itr_query_func'
htslib/hts.h:221: note: previous declaration of 'hts_itr_query_func' was here
/leofs/noncode/dxj/samtools-1.3/htslib-1.3/htslib/hts.h:516: error: conflicting types for 'hts_itr_querys'
htslib/hts.h:223: note: previous declaration of 'hts_itr_querys' was here
In file included from /leofs/noncode/dxj/samtools-1.3/htslib-1.3/htslib/sam.h:30,
                 from /leofs/noncode/dxj/samtools-1.3/htslib-1.3/cram/cram_samtools.h:61,
                 from cram/cram.h:47,
                 from hts.c:11:
/leofs/noncode/dxj/samtools-1.3/htslib-1.3/htslib/hts.h:517: error: conflicting types for 'hts_itr_next'
htslib/hts.h:224: note: previous declaration of 'hts_itr_next' was here
/leofs/noncode/dxj/samtools-1.3/htslib-1.3/htslib/hts.h:578: error: redefinition of 'hts_reg2bin'
htslib/hts.h:250: note: previous definition of 'hts_reg2bin' was here
/leofs/noncode/dxj/samtools-1.3/htslib-1.3/htslib/hts.h:586: error: redefinition of 'hts_bin_bot'
htslib/hts.h:258: note: previous definition of 'hts_bin_bot' was here
/leofs/noncode/dxj/samtools-1.3/htslib-1.3/htslib/hts.h:597: error: redefinition of 'ed_is_big'
htslib/hts.h:269: note: previous definition of 'ed_is_big' was here
/leofs/noncode/dxj/samtools-1.3/htslib-1.3/htslib/hts.h:602: error: redefinition of 'ed_swap_2'
htslib/hts.h:274: note: previous definition of 'ed_swap_2' was here
/leofs/noncode/dxj/samtools-1.3/htslib-1.3/htslib/hts.h:606: error: redefinition of 'ed_swap_2p'
htslib/hts.h:278: note: previous definition of 'ed_swap_2p' was here
/leofs/noncode/dxj/samtools-1.3/htslib-1.3/htslib/hts.h:611: error: redefinition of 'ed_swap_4'
htslib/hts.h:283: note: previous definition of 'ed_swap_4' was here
/leofs/noncode/dxj/samtools-1.3/htslib-1.3/htslib/hts.h:616: error: redefinition of 'ed_swap_4p'
htslib/hts.h:288: note: previous definition of 'ed_swap_4p' was here
/leofs/noncode/dxj/samtools-1.3/htslib-1.3/htslib/hts.h:621: error: redefinition of 'ed_swap_8'
htslib/hts.h:293: note: previous definition of 'ed_swap_8' was here
/leofs/noncode/dxj/samtools-1.3/htslib-1.3/htslib/hts.h:627: error: redefinition of 'ed_swap_8p'
htslib/hts.h:299: note: previous definition of 'ed_swap_8p' was here
In file included from cram/cram.h:54,
                 from hts.c:11:
cram/cram_structs.h:696: error: nested redefinition of 'enum hts_fmt_option'
cram/cram_structs.h:696: error: redeclaration of 'enum hts_fmt_option'
cram/cram_structs.h:697: error: redeclaration of enumerator 'CRAM_OPT_DECODE_MD'
/leofs/noncode/dxj/samtools-1.3/htslib-1.3/htslib/hts.h:150: note: previous definition of 'CRAM_OPT_DECODE_MD' was here
cram/cram_structs.h:698: error: redeclaration of enumerator 'CRAM_OPT_PREFIX'
/leofs/noncode/dxj/samtools-1.3/htslib-1.3/htslib/hts.h:151: note: previous definition of 'CRAM_OPT_PREFIX' was here
cram/cram_structs.h:699: error: redeclaration of enumerator 'CRAM_OPT_VERBOSITY'
/leofs/noncode/dxj/samtools-1.3/htslib-1.3/htslib/hts.h:152: note: previous definition of 'CRAM_OPT_VERBOSITY' was here
cram/cram_structs.h:700: error: redeclaration of enumerator 'CRAM_OPT_SEQS_PER_SLICE'
/leofs/noncode/dxj/samtools-1.3/htslib-1.3/htslib/hts.h:153: note: previous definition of 'CRAM_OPT_SEQS_PER_SLICE' was here
cram/cram_structs.h:701: error: redeclaration of enumerator 'CRAM_OPT_SLICES_PER_CONTAINER'
/leofs/noncode/dxj/samtools-1.3/htslib-1.3/htslib/hts.h:154: note: previous definition of 'CRAM_OPT_SLICES_PER_CONTAINER' was here
cram/cram_structs.h:702: error: redeclaration of enumerator 'CRAM_OPT_RANGE'
/leofs/noncode/dxj/samtools-1.3/htslib-1.3/htslib/hts.h:155: note: previous definition of 'CRAM_OPT_RANGE' was here
cram/cram_structs.h:703: error: redeclaration of enumerator 'CRAM_OPT_VERSION'
/leofs/noncode/dxj/samtools-1.3/htslib-1.3/htslib/hts.h:156: note: previous definition of 'CRAM_OPT_VERSION' was here
cram/cram_structs.h:704: error: redeclaration of enumerator 'CRAM_OPT_EMBED_REF'
/leofs/noncode/dxj/samtools-1.3/htslib-1.3/htslib/hts.h:157: note: previous definition of 'CRAM_OPT_EMBED_REF' was here
cram/cram_structs.h:705: error: redeclaration of enumerator 'CRAM_OPT_IGNORE_MD5'
/leofs/noncode/dxj/samtools-1.3/htslib-1.3/htslib/hts.h:158: note: previous definition of 'CRAM_OPT_IGNORE_MD5' was here
cram/cram_structs.h:706: error: redeclaration of enumerator 'CRAM_OPT_REFERENCE'
/leofs/noncode/dxj/samtools-1.3/htslib-1.3/htslib/hts.h:159: note: previous definition of 'CRAM_OPT_REFERENCE' was here
cram/cram_structs.h:707: error: redeclaration of enumerator 'CRAM_OPT_MULTI_SEQ_PER_SLICE'
/leofs/noncode/dxj/samtools-1.3/htslib-1.3/htslib/hts.h:160: note: previous definition of 'CRAM_OPT_MULTI_SEQ_PER_SLICE' was here
cram/cram_structs.h:708: error: redeclaration of enumerator 'CRAM_OPT_NO_REF'
/leofs/noncode/dxj/samtools-1.3/htslib-1.3/htslib/hts.h:161: note: previous definition of 'CRAM_OPT_NO_REF' was here
cram/cram_structs.h:709: error: redeclaration of enumerator 'CRAM_OPT_USE_BZIP2'
/leofs/noncode/dxj/samtools-1.3/htslib-1.3/htslib/hts.h:162: note: previous definition of 'CRAM_OPT_USE_BZIP2' was here
cram/cram_structs.h:710: error: redeclaration of enumerator 'CRAM_OPT_SHARED_REF'
/leofs/noncode/dxj/samtools-1.3/htslib-1.3/htslib/hts.h:163: note: previous definition of 'CRAM_OPT_SHARED_REF' was here
cram/cram_structs.h:711: error: redeclaration of enumerator 'CRAM_OPT_NTHREADS'
/leofs/noncode/dxj/samtools-1.3/htslib-1.3/htslib/hts.h:164: note: previous definition of 'CRAM_OPT_NTHREADS' was here
cram/cram_structs.h:712: error: redeclaration of enumerator 'CRAM_OPT_THREAD_POOL'
/leofs/noncode/dxj/samtools-1.3/htslib-1.3/htslib/hts.h:165: note: previous definition of 'CRAM_OPT_THREAD_POOL' was here
hts.c:100: error: conflicting types for 'hts_open'
htslib/hts.h:106: note: previous declaration of 'hts_open' was here
hts.c: In function 'hts_open':
hts.c:124: error: 'htsFile' has no member named 'is_compressed'
hts.c:126: error: 'htsFile' has no member named 'is_kstream'
hts.c:130: error: 'htsFile' has no member named 'is_compressed'
hts.c:131: error: 'htsFile' has no member named 'is_kstream'
hts.c:138: error: 'htsFile' has no member named 'is_kstream'
hts.c:145: error: 'htsFile' has no member named 'is_compressed'
hts.c:146: error: 'htsFile' has no member named 'is_compressed'
hts.c:147: error: 'htsFile' has no member named 'is_compressed'
hts.c:151: error: 'htsFile' has no member named 'is_compressed'
hts.c:162: error: 'htsFile' has no member named 'is_kstream'
hts.c: At top level:
hts.c:194: error: conflicting types for 'hts_close'
htslib/hts.h:113: note: previous declaration of 'hts_close' was here
hts.c: In function 'hts_close':
hts.c:198: error: 'htsFile' has no member named 'is_compressed'
hts.c:214: error: 'htsFile' has no member named 'is_kstream'
hts.c: At top level:
hts.c:236: error: conflicting types for 'hts_set_threads'
htslib/hts.h:134: note: previous declaration of 'hts_set_threads' was here
hts.c:245: error: conflicting types for 'hts_set_fai_filename'
htslib/hts.h:143: note: previous declaration of 'hts_set_fai_filename' was here
hts.c:285: error: conflicting types for 'hts_getline'
htslib/hts.h:115: note: previous declaration of 'hts_getline' was here
hts.c:1044: error: conflicting types for 'hts_itr_query'
htslib/hts.h:216: note: previous declaration of 'hts_itr_query' was here
hts.c:1157: error: conflicting types for 'hts_itr_destroy'
htslib/hts.h:217: note: previous declaration of 'hts_itr_destroy' was here
hts.c:1193: error: conflicting types for 'hts_itr_querys'
htslib/hts.h:223: note: previous declaration of 'hts_itr_querys' was here
hts.c:1211: error: conflicting types for 'hts_itr_next'
htslib/hts.h:224: note: previous declaration of 'hts_itr_next' was here
make[1]: *** [hts.o] Error 1
make[1]: Leaving directory `/leofs/noncode/wulc/HCC_pvtt/software/STAR-STAR_2.4.1d/source/htslib'
make: *** [htslib/libhts.a] Error 2

**Comment by ATPs** [comment]
I think you do not need to try to install STAR. If you cloned the github STAR folder,  under this folder '../STAR/bin/', you will see three folder, and use the one in 'Linux_x86_64_static' folder.

**Comment by wulc21** [comment]
Thank you very much for your help. 

Actually, I want to identify the fusion event from my RNAseq data with STAT-Fusion. 

I also have download the github STAR folder and try to run the command line like this "**./STAR  --genomeFastaFiles /leofs/noncode/wulc/HCC_pvtt/hg19.fa --sjdbGTFfile /leofs/noncode/wulc/HCC_pvtt/gencode.v19.annotation.gtf**" udner the STAR-master/bin/Linux_x86_64_static folder.  Unfortunately, I got another error" "

####################      error information  ##################
EXITING because of fatal input ERROR: could not open readFilesIn=Read1

Aug 30 00:37:11 ...... FATAL ERROR, exiting

#######################################################

How can I solve this ploblem ？ thank you very much.

**Comment by wulc21** [comment]
Thank you very much for your help.

Actually, I want to identify the fusion event from my RNAseq data with STAT-Fusion.

I also have download the github STAR folder and try to run the command line like this "./STAR --genomeFastaFiles /leofs/noncode/hg19.fa --sjdbGTFfile /leofs/noncode/gencode.v19.annotation.gtf" udner the STAR-master/bin/Linux_x86_64_static folder. Unfortunately, I got another error" "

#################### error information ##################
EXITING because of fatal input ERROR: could not open readFilesIn=Read1

Aug 30 00:37:11 ...... FATAL ERROR, exiting

#######################################################

How can I solve this ploblem ？ thank you very much.

**Comment by alexdobin** [comment]
Hi @wulc21 

the command to generate the genome should look like:
STAR --runMode genomeGenerate --genomeDir ./ --genomeFastaFiles genome.fa --sjdbGTFfile annotations.gtf --runThreadN 12

Cheers
Alex

**Comment by wulc21** [comment]
Dear Alex
 
Amazing! Your kind recommendation is working !  I fell nothing can be  such a good feeling ! 

The default value of --runMode is  alignReads, that's the reason  why I enocounter the previous error.

Thank you very much for your timely kind help!

**Comment by wulc21** [comment]
Dear Alex

Amazing! Your kind recommendation is working ! I fell nothing can be such a good feeling !

The default value of --runMode is alignReads, that's the reason why I enocounter the previous error.

Thank you very much for your timely kind help!

######################### ############################################
[noncode@gnode108 Linux_x86_64_static]$ ./STAR --runMode genomeGenerate --genomeDir /leofs/noncode/reference/ --genomeFastaFiles /leofs/noncode/GRCh37_gencode_v19_CTAT_lib/ref_genome.fa --sjdbGTFfile /leofs/noncode/GRCh37_gencode_v19_CTAT_lib/ref_annot.gtf --runThreadN 12
Aug 30 08:30:33 ..... started STAR run
Aug 30 08:30:33 ... starting to generate Genome files
Aug 30 08:34:06 ... starting to sort Suffix Array. This may take a long time...
Aug 30 08:34:42 ... sorting Suffix Array chunks and saving them to disk...
Aug 30 09:46:33 ... loading chunks from disk, packing SA...
Aug 30 10:05:59 ... finished generating suffix array
Aug 30 10:05:59 ... generating Suffix Array index
Aug 30 10:15:49 ... completed Suffix Array index
Aug 30 10:15:49 ..... processing annotations GTF
Aug 30 10:16:43 ..... inserting junctions into the genome indices
Aug 30 10:22:37 ... writing Genome to disk ...
Aug 30 10:32:42 ... writing Suffix Array to disk ...
Aug 30 12:18:31 ... writing SAindex to disk
Aug 30 12:24:37 ..... finished successfully
#######################################################################
