### ISSUE TITLE
how STARsolo read the feature from gtf file?

### ISSUE THREAD

**Issue by DiegoSafian** [alexdobin/STAR#1781]
I am asking because after using star count, one can find the gene_id and gene_name (e.g. ENSPREG00000000644 and nr1i2)  in the feature.tsv file in ./gene/raw folder after using star count. I am wondering how STARsolo read the gtf to find ENSPREG00000000644 and nr1i2 and I also wonder if it is possible to edit this to select another feature of interest.

All the best,
Diego

**Comment by DiegoSafian** [comment]
solved

**Comment by alexdobin** [comment]
Hi @DiegoSafian 

it seems your GTF file is missing the `gene_biotype` field.
