### ISSUE TITLE
how to include both exonic and intronic reads in the Aligned.toTranscriptome.out.bam file

### ISSUE THREAD

**Issue by harshini-c** [alexdobin/STAR#1783]
Hello,

This is my first time using STAR, and I am trying to do isoform level analysis on my nuclear RNAseq dataset. I notice that a lot of mapped reads from the Aligned.out.bam are not included in the Aligned.toTranscriptome.out.bam file. Is there a way to make sure all mapped reads i.e both at exons and introns are present in the Aligned.toTranscriptome.out.bam. I will subsequently be usign RSEM to quantify isoform level expression counts for my analysis.

Your inputs in this regard will be highly helpful!

thank you.

**Comment by alexdobin** [comment]
Hi @harshini-c 

the ```Aligned.toTranscriptome.out.bam``` file includes only reads that fall within exons or are spliced according to transcript annotations in the GTF file. If you want to include reads that map to introns, i.e. pre-mRNA, you would need to modify GTF to include the pre-mRNA transcripts.

**Comment by harshini-c** [comment]
thank you @alexdobin for your prompt reply! 

Follow-up question -- 
After modifying the GTF file -- would the resulting `Aligned.toTranscriptome.out.bam` be compatible with RSEM? or do we need to  modify any parameters during STAR alignment?

**Comment by alexdobin** [comment]
Hi @harshini-c 

the ```Aligned.toTranscriptome.out.bam``` file will be compatible with BAM, if you give the same modified GTF to RSEM.
However, I don't know if RSEM will be able to quantify both primary and mature transcripts - as far as I understand, it's standard operation is to quantify mature transcripts. It would be best to ask RSEM authors about it.
