### ISSUE TITLE
standard STAR VS STARsolo

### ISSUE THREAD

**Issue by nolarifi** [alexdobin/STAR#1784]
hello Alex,

I'm a little bit confused. In fact I'm dealing with **scRNA seq** data generated by **paired end sequencing** . My question is could we apply standard STAR on this type of data or only STARsolo is adapted for single cell analysis ?
second question: if I want to detect variant calling should I use bam files generated by standard STAR or Starsolo ?

thank you in advance
I'm really greatful

**Comment by alexdobin** [comment]
Hi @nolarifi 

you can map only the cDNA read without Solo options - but it will not include the single-cell barcodes.
The BAM file generated with Solo options is the same as without, except that cell barcode and UMI tags are added.
It can be used for variant calling.

**Comment by nolarifi** [comment]
thank you very much for these informations
I have one more question : cellranger uses standar STAR or STARsolo because in some links they say that it uses standard and in others STARsolo. 
thank u

**Comment by alexdobin** [comment]
Hi @nolarifi 

Cellranger uses stanard STAR - for mapping cDNA sequences to the genome.
It uses its own algorithms to assigned reads to cell barcodes, alignments to genes, collapsing UMIs, etc.
STARsolo can produce results almost identical to Cellranger.

**Comment by nolarifi** [comment]
thank you very much
