### ISSUE TITLE
outFileNamePrefix not used when I create wig from input BAM

### ISSUE THREAD

**Issue by RamRS** [alexdobin/STAR#1785]
Hi,

When I align and create wiggle files from FASTQs using the default `--runMode` option, all my outputs (sorted BAM, wiggle, Log files) use the `--outFileNamePrefix` that I provide. However, doing it this way requires a lot of RAM for the sorted BAM output. I'd prefer to output unsorted BAM, sort using samtools then use `STAR --runMode inputAlignmentsFromBAM` to go from sorted BAM to wig as outlined here: https://www.biostars.org/p/234437/#235241

I added an `--outFileNamePrefix` to the command from that post but my outputs don't have this prefix. Instead, they are simply `Signal.*.wig` and `Log.out`. I'm using STAR v2.7.2a. Has this behavior been addressed in recent versions or is this still a known bug? Is there any way this can be addressed? I run multiple STAR commands in the same directory and without the prefix, concurrency will be impossible.

**Comment by alexdobin** [comment]
Hi @RamRS 

I have checked the latest version, and ```--outFileNamePrefix``` works properly with ```--runMode inputAlignmentsFromBAM --outWigType wiggle  ```

**Comment by RamRS** [comment]
I need to stick to v2.7.2a - I guess I'll need to use a directory based workaround for the moment. Thanks for checking, @alexdobin !

**Comment by RamRS** [comment]
Oops, this issue should never have existed. The option works with 2.7.2a as well, I made a copy-paste error where I'd pasted `outputFileNamePrefix` instead of `--outputFileNamePrefix`. My bad, sorry!
