### ISSUE TITLE
STARsolo with Multiplex Fixed RNA Profiling

### ISSUE THREAD

**Issue by MEladawi** [alexdobin/STAR#1787]
Hello--

I wanted to inquire, does STARsolo support the 10x MFRP chemistry (Multiplex Fixed RNA Profiling). Their tool (cellRanger) only supports mm10 and no support for mm39 in the probe reference file.

Thanks,

**Comment by alexdobin** [comment]
Hi Mahmoud,

STARsolo only supports 3' and 5' protocols out of the box.
There might be ways to make it support other protocols, but I am not familiar with this one.
As far as I remember Cellranger allows generating genome indexes for a custom FASTA/GTF, it might be easier to go that path.
