### ISSUE TITLE
mapping issue 

### ISSUE THREAD

**Issue by kalyanipashine** [alexdobin/STAR#1789]
hello!!
I am using STAR for mapping by files but its showing me this error:
![WhatsApp Image 2023-03-10 at 18 38 29](https://user-images.githubusercontent.com/112052476/224324410-93ef1088-b9b5-48e8-bbe5-19d9858eba99.jpg)
please help me with this!!!

**Comment by alexdobin** [comment]
Hi @kalyanipashine 

this means that sorting of the BAM requires ~41GB of RAM.
You can try to reduce it by increasing ```--outBAMsortingBinsN``` to 100 or 200 from the default 50.
If it does not work, you can output unsorted BAM and than sort it with samtools.

**Comment by kalyanipashine** [comment]
Hey @alexdobin 
It worked with unsorted bam then i sorted it with samtools...but is it necessary to index the bam file??

**Comment by alexdobin** [comment]
Hi @kalyanipashine 
This depends on whether the downstream tools require the BAM index.
If they do, ```samtools index``` should do the job.

**Comment by kalyanipashine** [comment]
hi @alexdobin 
thanks for helping!
i am closing this issue..
