### ISSUE TITLE
an unpleasant error during mapping the RNAseq reads to hg19 genome with STAR

### ISSUE THREAD

**Issue by wulc21** [alexdobin/STAR#179]
Dear professor,

I am trying to run STAR and map my RNAseq reads to hg19 genome for the first time. However I encounter the unpleasant error. Please give me a hand!

###################### command line 1 ##############################
./STAR --genomeDir /leofs/noncode/reference/ 
--readFilesIn /leofs/noncode/fastq/sample_1.fastq /leofs/noncode/fastq/sample_2.fastq 
--twopassMode Basic
--outReadsUnmapped None 
--chimSegmentMin 12
--chimJunctionOverhangMin 12 
--alignSJDBoverhangMin 10 
--alignMatesGapMax 200000 
--alignIntronMax 200000
--chimSegmentReadGapMax parameter 3
--alignSJstitchMismatchNmax 5 -1 5 5
--runThreadN 16 --limitBAMsortRAM 31532137230
--outSAMtype BAM SortedByCoordinate

###################### error information ############################
Aug 30 19:18:11 ..... started STAR run
Aug 30 19:18:11 ..... loading genome
Aug 30 19:36:56 ..... started mapping

EXITING because of FATAL ERROR: Read1 and Read2 are not consistent, reached the end of the one before the other one
SOLUTION: Check you your input files: they may be corrupted

Aug 30 19:45:04 ...... FATAL ERROR, exiting
###########################################################################

Then I simplify my parammeter, and run the following command line, unfortunately, I encounter the same erro infformation.

###################### command line 2 ##############################

./STAR --genomeDir /leofs/noncode/wulc/HCC_pvtt/reference/ --readFilesIn /leofs/noncode/sample_1.fastq /leofs/noncode/sample_2.fastq --runThreadN 16 --outSAMtype BAM SortedByCoordinate

###################### error information ############################

Aug 30 20:18:24 ..... started STAR run
Aug 30 20:18:24 ..... loading genome
Aug 30 20:36:56 ..... started mapping

EXITING because of FATAL ERROR: Read1 and Read2 are not consistent, reached the end of the one before the other one
SOLUTION: Check you your input files: they may be corrupted

Aug 30 20:45:04 ...... FATAL ERROR, exiting

###########################################################################

My RNAseq data (.SRA format) were download from NCBI SRA database and processed by SRA tollkit.

fastq-dump.exe -I --split-files path_file_1\SRR****.sra -O path_file_2\fastaq*

Rejected 1444636 reads because readlen < 1

read 23700746 sopts for SRR*******.sra

written 23700746 sopts for SRR*******.sra

############################# fastQC result ###########################
![per_base_quality](https://cloud.githubusercontent.com/assets/21299945/18091167/53f5225c-6efa-11e6-8f25-17d65c7a4284.png)
![kmer_profiles](https://cloud.githubusercontent.com/assets/21299945/18091172/5ab79de0-6efa-11e6-826d-83ee3a0a323b.png)
![per_base_sequence_content](https://cloud.githubusercontent.com/assets/21299945/18091182/5ed42628-6efa-11e6-958a-b6eac38c704d.png)

**Comment by alexdobin** [comment]
Hi @wulc21 

have you downloaded the files into Windows, and then transferred them to Linux?
This might cause some trouble, it's best to download the files directly into Linux.
Or you can convert the windows files with dos2unix utility.

If this does not help, please run
$ wc /leofs/noncode/fastq/sample_1.fastq /leofs/noncode/fastq/sample_2.fastq
$ head /leofs/noncode/fastq/sample_1.fastq /leofs/noncode/fastq/sample_2.fastq
$ tail /leofs/noncode/fastq/sample_1.fastq /leofs/noncode/fastq/sample_2.fastq

Cheers
Alex

**Comment by wulc21** [comment]
Hi @alexdobin ,

Dear professor, thank you very much for your recommendation. with your help, I have solved the problem.

##########################   Reason for the previous error   #########################

Previously, I downloaded the sra format original data from SRA database then processed into fastq format data under windows system with the command line **fastq-dump.exe -I --split-files path_file_1\SRR***.sra -O path_file_2\fastaq**. As a result,  two separate fastq file， named “SRR****_1.fastq” an"SRR****_2.fastq" , were generated. 

However, the two separate fastq file have different lines of reads, which means the there are single end  (not pair end) reads in the two separate fastq file. That's the reason for the previous error information, "**EXITING because of FATAL ERROR: Read1 and Read2 are not consistent, reached the end of the one before the other one**"

#############################   How  to  solve  this problem ########################

**step 1**

process the sra format data into separate fastq file for pair end sequencing data under linux with the following command line "fastq-dump   --split-3 /path/to/your/sra/file -O /path/to/your/output/path ", then 2 or 3 fastq format file will generate, named "Sample_1.fastq","Sample_2.fastq" and "Sample.fastq".

Both  "Sample_1.fastq" and "Sample_2.fastq" own the same lines of reads (mate pair) , and 

"Sample.fastq" will store the single end reads.


**step 2**

run STAR wiht the "Sample_1.fastq" and "Sample_2.fastq" 

###########################  Example of success   #################################

[noncode@gnode108 Linux_x86_64_static]$ ./STAR --genomeDir /leofs/noncode/reference/ --readFilesIn /leofs/noncode/sample_1.fastq /leofs/noncode/sample_2.fastq --runThreadN 16 --outSAMtype BAM SortedByCoordinate

Aug 31 16:44:18 ..... Started STAR run
Aug 31 16:44:18 ..... Loading genome

Aug 31 17:09:02 ..... Started mapping
Aug 31 17:09:10 ..... Started sorting BAM
Aug 31 17:09:14 ..... Finished successfully

############################################################################


Thank you very much ! Thank you!

**Comment by wulc21** [comment]
Hi @alexdobin ,

Dear professor, may I ask you a question?

How can I set the parameter for STAR if I want to calculate the differential expression genes  from STAR mapping result with software such as Cufflinks/Cuffdiff or DEseq and so on. 

Could you give me a recommendation or a example? Thank you very much!

**Comment by alexdobin** [comment]
Hi @wulc21 

section 4.2.3 of the manual describes the parameters necessary to run STAR with Cufflinks.
Briefly, for unstranded RNA-seq data you need --outSAMstrandField intronMotif .
For stranded RNA-seq data, you do not need any extra STAR parameters, but you will need to run Cufflinks with proper --library-type options. For example, cufflinks
... --library-type fr-firststrand should be used for the standard dUTP protocol, including
Illumina's stranded Tru-Seq.

For DEseq, you will need the read counts per gene. You can get the counts directly from STAR using --quantMode GeneCounts. Or you can use htseq-count or featureCounts software.

Cheers
Alex

**Comment by wulc21** [comment]
Dear @alexdobin 

Thank you very much for your precious time and patience, as well as your valuable suggestion.

Thank you very much.

**Comment by wulc21** [comment]
Dear @alexdobin

Thank you very much for your precious time and patience, as well as your valuable suggestion.

Thank you very much.

Sincerely yours
 
wulc21

**Comment by alexdobin** [comment]
You are welcome!
