### ISSUE TITLE
invalid arguments are silently ignored

### ISSUE THREAD

**Issue by suhrig** [alexdobin/STAR#18]
Hi,

STAR usually expects parameters to be prefixed by two dashes (e.g., --sjdbGTFfile). If one accidentally forgets one dash (e.g., -sjdbGTFfile), then the parameter is silently ignored. No error is thrown. This is dangerous for optional arguments, because it can lead to parameters being ignored without the user being aware of it. For the given example (sjdbGTFfile) this leads to genome indices being created without making use of the annotation. If you do not carefully study the log file and make sure that the effective command-line is identical to the original command-line, you will not know.

Another issue is that parameters are silently ignored when used in invalid contexts. For example, STAR does not throw an error when the parameter sjdbGTFfile is used in runMode alignReads. Users coming from other RNA-Seq aligners (such as TopHat) could mistakenly expect STAR to make use of the specified GTF file, because TopHat automatically generates a new index when a GTF file is specified for which there exists no index yet. I am not expecting STAR to do the same, but at least it should throw an error when parameters are used in the wrong context.

Regards,
Sebastian

**Comment by alexdobin** [comment]
Hi Sebastian,

these are good suggestions, and I will put these features on my TODO list. I have not upgraded the input system for a long time and it's getting a bit rusty... however, cannot promise a quick implementation since it's not "mission" critical.

Cheers
Alex
