### ISSUE TITLE
Unable to turn off splicing alignments with --alignIntronMax 1

### ISSUE THREAD

**Issue by kkoyano** [alexdobin/STAR#180]
Hi Alex,

I am using STAR as my aligner for small RNA sequencing to hg19 and I am trying to turn off the splicing alignments with using the option --alignIntronMax 1 as suggested. While --alignIntronMax 1 removes most of the spliced reads, I still have some alignments still being reported with large introns. Why is this? I am not really sure what I'm doing wrong? I have listed an example below: 

I have tried on 2 versions: 
STAR version --> STAR_2.5.2a_modified
STAR version --> STAR_2.5.2b

Command: 

```
STAR --outFilterMultimapNmax 100 --outFilterMismatchNmax 1 --alignEndsType EndToEnd --alignSoftClipAtReferenceEnds No --alignIntronMax 1 --outFileNamePrefix $outputDir --genomeDir $genomeDir --readFilesIn $input.fastq
```

$ cat Aligned.out.sam:

```
AAAAAA.122606   272 chr16   75276986    3   3M21260N16M *   0   0 GTTCGGCCCTCCAGCAGGT   JIGGHEHFGHFFFFFD@@@ NH:i:2  HI:i:2  AS:i:15 nM:i:1 
AAAAAA.3816846  272 chr16   75276986    3   3M21260N16M *   0   0   GTTCGGCCCTCCAGCAGGT JJJJJJHHHHHFFFFFCCC NH:i:2  HI:i:2  AS:i:15 nM:i:1
AAAAAA.13605558 272 chr16   75276986    3   3M21260N16M *   0   0   
GTTCGGCCCTCCAGCAGGT AAFGE@D?ABHFFDDF@@? NH:i:2  HI:i:2  AS:i:15 nM:i:1
AAAAAA.25789553 272 chr16   75276986    3   3M21260N16M *   0   0   GTTCGGCCCTCCAGCAGGT JJJJJJHHHHHFFFFFCCC NH:i:2  HI:i:2  AS:i:15 nM:i:1
AAAAAA.26360049 272 chr16   75276986    3   3M21260N16M *   0   0   GTTCGGCCCTCCAGCAGGT HFFG7HFFFDHDDDDD@@@ NH:i:2  HI:i:2  AS:i:15 nM:i:1
AAAAAA.290760   16  chr4    185695012   255 18M2608N20M *   0   0   GTTGGCTCTTCCCAGGTCCTCCATCGCCTTCATGCTGG  JJIIHGAHEIGIIJIGFHIGGJIIJHHHHHFFFFFCCC  NH:i:1  HI:i:1  AS:i:37 nM:i:0
```

$ cat input.fastq file:

```
@AAAAAA.122606 SN608:VB090:6:1101:827.60:5834.40:0:1:#0/1
ACCTGCTGGAGGGCCGAAC
+
@@@DFFFFFHGFHEHGGIJ
@AAAAAA.3816846 SN608:VB090:6:1115:1416.40:521.30:0:1:#0/1
ACCTGCTGGAGGGCCGAAC
+
CCCFFFFFHHHHHJJJJJJ
@AAAAAA.13605558 SN608:VB090:6:1316:89.80:6354.80:0:1:#0/1
ACCTGCTGGAGGGCCGAAC
+
?@@FDDFFHBA?D@EGFAA
@AAAAAA.25789553 SN608:VB090:6:2312:391.20:3452.10:0:1:#0/1
ACCTGCTGGAGGGCCGAAC
+
CCCFFFFFHHHHHJJJJJJ
@AAAAAA.26360049 SN608:VB090:6:2313:913.70:9805.60:0:1:#0/1
ACCTGCTGGAGGGCCGAAC
+
@@@DDDDDHDFFFH7GFFH
@AAAAAA.290760 SN608:VB090:6:1102:1863.40:3657.00:0:1:#0/1
CCAGCATGAAGGCGATGGAGGACCTGGGAAGAGCCAAC
+
CCCFFFFFHHHHHJIIJGGIHFGIJIIGIEHAGHIIJJ
```

Thanks for your help. Please let me know if you need more information. 

Best,
Kiku

**Comment by alexdobin** [comment]
Hi Kiku,

if you generated the genome indexes with annotations, you will splicing to annotated junctions, as --alignIntronMax only controls the annotated junctions. You can either (i) use genome with annotations and  --alignSJDBoverhangMin 999 (any number > read length) while mapping, or (ii) re-generate the genome without annotations.

Cheers
Alex

**Comment by mbraun1** [comment]
Hello,

I'm having the same problem - I can't get STAR to align without inserting SJ's. I tried re-indexing my genome (small, non-human) without annotation and aligned with the following commands:

STAR --runMode genomeGenerate --runThreadN 16 --genomeDir star_index --genomeFastaFiles path/to/fasta --genomeSAindexNbases 6 

STAR --runMode alignReads --runThreadN 16 --genomeDir path/to/directory --genomeLoad LoadAndRemove \
--readFilesIn path/to/file --outSAMunmapped Within --outFilterMultimapNmax 10 --outFilterMultimapScoreRange 1 \
--outFileNamePrefix path/to/file --outSAMattributes All --outSAMtype BAM Unsorted --outReadsUnmapped Fastx --outFilterScoreMin 10 \
--outFilterMismatchNoverReadLmax 0.1 --alignEndsType EndToEnd 


Any ideas why I'm still getting Splice Junctions when I look on IGV?

**Comment by alexdobin** [comment]
Hi @mbraun1 

to turn off splicing, you need to use ```--alignIntronMax 1``` in addition to not using GTF at the genome generation step. If this does not help, please send me the Log.out and Log.final.out files.

Cheers
Alex

**Comment by mbraun1** [comment]
That worked! Thank you for your help.

**Comment by MengjunWu** [comment]
Hi,

I came across this question when trying to understand how star align to splice junctions. Here you mentioned "--alignIntronMax only controls the annotated junctions"  but I understood it rather controls unannotated junctions and that's why one would generate genome index without annotation?  I saw in another question (http://seqanswers.com/forums/archive/index.php/t-61968.html), you answered "--alignIntronMax 1, i.e. maximum intron size =1 for unannotated junctions"
So I am a bit confused about this parameter, whether it controls annotated or unannotated junctions, could you help to clarify it?

Thanks a lot!

**Comment by alexdobin** [comment]
Hi @MengjunWu 

it was a typo in the explanation above, it's corrected now.
Thanks for pointing it out.
*--alignIntronMax* controls the max intron for unannotated junctions.

Cheers
Alex
