### ISSUE TITLE
UMIhomopolymer impact on barcode detection

### ISSUE THREAD

**Issue by mbahin** [alexdobin/STAR#1801]
Hi Alex,

I have a particular read construct and thus building up the BC-UMI read to match STAR expectations.
By mistake I got the UMI from a region where I had, in majority, polyT queue. When I fixed my mistake, I compared the new `Barcode.stats` file to the old one and I noted that UMI homopolymers seems to have an impact on barcode detection.
I had, on the one with UMI in the polyT:
```
noUMIhomopolymer         339,590
noNoWLmatch         884,395
```

And, on the "regular" one:
```
noUMIhomopolymer           1,576
noNoWLmatch        1,003,214
```
I would have expected that not found barcodes would be the same. But this, obviously, doesn't not sum the same amount so I guess that, in some way, when a UMIhomopolymer is found, the BC is automatically discarded?

Cheers,
Mathieu

**Comment by alexdobin** [comment]
Hi Mathieu,

indeed, the reads containing homo-polymer UMIs are not counted.

**Comment by mbahin** [comment]
Thanks!
