### ISSUE TITLE
Read names are not preserved

### ISSUE THREAD

**Issue by KleinSamuel** [alexdobin/STAR#1803]
Hello,

I have two FASTQ files containing one mate of paired-end reads each. 

The reads names are formatted like this:

_file.1.fastq_
sim-read-ENSP00000350256-0.1

_file.2.fastq_
sim-read-ENSP00000350256-0.2

After mapping them to a genome using STAR, the read names in the output SAM file are as follows:

_Aligned.out.sam_
sim-read-ENSP00000350256-0.1 [...]
sim-read-ENSP00000350256-0.1 [...]

(Note that the suffix **.2** is lost and both reads have the suffix **.1**)

I would like to know if this is wanted behavior and if so, what is the reason behind it?

(I am using STAR_2.7.2a on Linux x86_64 with default parameters)

Thanks!
Sam

**Comment by alexdobin** [comment]
Hi Sam,

this is the standadard behavior defined in SAM file specifications - the ends of the reads need to have exactly the same name (otherwise it won't be possible to find the ends corresponding to the same read).

**Comment by KleinSamuel** [comment]
Thanks for the reply Alex!

I do not quite understand what you mean by "it won't be possible to find the ends corresponding to the same read".

The reads in my example could be identified by their prefix even when the suffix .2 is preserved:
**sim-read-ENSP00000350256-0**.1
**sim-read-ENSP00000350256-0**.2

Furthermore, according to the SAM file specifications, the SEQ field can be empty (by using "*") which makes the read identification (from which FASTQ file the read originated from) rather complicated.

A possible use case for the identification of the read origin would be that I would not want to output the read sequence in the SAM file (to save space) because I already have all the FASTQ files containing the sequence. To retrieve the sequence for a mapped read, I would have to search the FASTQ file using the read's name which is not preserved for 50% of paired end reads.

I see why this would not matter to most users and probably break some downstream analysis that relies on having exactly the same read name for both pairs but an option to preserve the original read names would be great. 
Do you know if such an option already exists?

**Comment by alexdobin** [comment]
Hi Sam,

SAM specifications (and most downstream tools) require the read names for read1 and read2 to be exactly the same. These read names are used to find the read ends in case the SAM file is sorted by coordinate. The SAM FLAG contains information whether the specific SAM line is read1 or read2, so you can get the correspondence of each SAM line to the FASTQ.

**Comment by KleinSamuel** [comment]
You're absolutely correct! I just noticed that in the SAM specs chapter 1.4 there is a footnote stating that the 0x40 and 0x80 bits denote the R1 and R2 origin for paired end sequencing.
Thank you very much!
