### ISSUE TITLE
STARsolo logic for assigning reads to genes

### ISSUE THREAD

**Issue by bvaldebenitom** [alexdobin/STAR#1830]
Dear Alex and STAR developers,

I'm writing to ask about the logic used in STARsolo for assigning reads to genes. Particularly, I have noticed that some spliced reads are not annotated to a gene under certain conditions.

I'm looking at some reads that overlap with an exon of the gene RPS24:
<img width="613" alt="image" src="https://user-images.githubusercontent.com/31257257/232494780-3fec9b04-fd89-41e4-9fb2-c4cd36d805d3.png">

In the figure, you can see that the exon has a high read coverage. However, when looking at the reads, the GN tag is not assigned. What I have seen is that other parts of the spliced reads are not contained in other exons. For example, the one indicated with an arrow in the next figure:
<img width="613" alt="image" src="https://user-images.githubusercontent.com/31257257/232495345-88cf1ed2-116a-49c9-a25e-1b90240a9a01.png">

Does the CellRanger logic also holds for spliced reads in STARsolo? If I recall correctly, CellRanger only assigns reads to genes if they are in the same strand, and are fully contained within exons. Or is there any other consideration for spliced reads?

Thanks in advance for any input regarding this!

**Comment by alexdobin** [comment]
Hi @bvaldebenitom 

> Does the CellRanger logic also holds for spliced reads in STARsolo? If I recall correctly, CellRanger only assigns reads to genes if they are in the same strand, and are fully contained within exons. Or is there any other consideration for spliced reads?

Yes, this is correct.

**Comment by bvaldebenitom** [comment]
Thank you @alexdobin for the quick response!
