### ISSUE TITLE
how to recognize the read counts for positive strand and negative strand in the results of STAR geneCount?

### ISSUE THREAD

**Issue by eggprincess917** [alexdobin/STAR#1831]
Dear alexdobin,

I have a question about the results of STAR GeneCounts. I am a beginner of RNA-seq data analysis. My RNA-seq data is generated by single-end sequencing for PolyA enrichment of the RNA. Since the results of STAR geneCounts have four column. The first column is gene_id, if I understood correctly, the second column is read counts per gene (ignore the strand information about the reads). But for the 3rd and 4th column, I don't know which column strand for the positive strand, which column is reverse strand? I would appreciate it if you would like to give more explaination about column meaning. 

I am looking forward to your reply!

Many thanks and best,
Lingling.

**Comment by alexdobin** [comment]
Hi Lingling,

the 3rd column corresponds to the protocols that produce the 1st read sequence from the same strand as RNA, and the 4th column is the opposite.

**Comment by eggprincess917** [comment]
Thank you very much!
