### ISSUE TITLE
How to read barcodes from fastq labels?

### ISSUE THREAD

**Issue by hkevile** [alexdobin/STAR#1836]
Hello!

I'm trying to run STARsolo but am running into an issue when I try to read the barcodes from my samples.

The command I ran is:
`STAR --genomeDir ./genomes/STAR_page/ --readFilesIn ./fastq_files/L16_2877_S27_L004_R2_extracted.fastq.gz ./fastq_files/L16_2877_S27_L004_R1_extracted.fastq.gz --soloType CB_UMI_Simple --soloCBwhitelist /lab/page_human_data/haley2/10xv3_whitelist.txt --soloUMIlen 12 --soloMultiMappers EM --readFilesCommand zcat --soloBarcodeReadLength 28 --limitOutSJcollapsed 2000000`

which gave me an error message of:
```
EXITING because of FATAL ERROR in input read file: the total length of barcode sequence is 123 not equal to expected 28
Read ID=@A01100:68:H25L2DSX2:4:1101:1253:1000_TAAGCGTAGGACTATA_CTAAATTTAGCC ;  Sequence=GGCGCGCTCGGGGGGGGGTGGGGTTTTTTTCAAAATGTTTTTATTTAGATTGTTTCCCACACAGATTGACACAGTGTGCTTTTCTTGATGCTTCACCCATAACTCACACCCACCTTTCACCCT
```

The 16 BP sequence TAAGCGTAGGACTATA found in the Read ID is on the 10xv3_whitelist.txt file, and I believe the 12 BP sequence CTAAATTTAGCC in the Read ID is the UMI. I tried adding in the parameter `--soloBarcodeReadLength 0` as described in #1762 which allowed STARsolo to run, but resulted in none of the reads mapping the barcodes:

```
evile@fry /lab/page_human_data/haley2$ cat ./genomes/STAR_page/Solo.out/L16_2877/Summary.csv 
Number of Reads,343105156
Reads With Valid Barcodes,0.00771274
Sequencing Saturation,-nan
Q30 Bases in CB+UMI,0.261845
Q30 Bases in RNA read,0.919981
Reads Mapped to Genome: Unique+Multiple,0.929898
Reads Mapped to Genome: Unique,0.797141
Reads Mapped to Gene: Unique+Multiple Gene,0
Reads Mapped to Gene: Unique Gene,0
Estimated Number of Cells,0
Unique Reads in Cells Mapped to Gene,0
Fraction of Unique Reads in Cells,-nan
Mean Reads per Cell,0
Median Reads per Cell,0
UMIs in Cells,0
Mean UMI per Cell,0
Median UMI per Cell,0
Mean Gene per Cell,0
Median Gene per Cell,0
Total Gene Detected,0
```

I was wondering how/if it's possible to read the barcode from the Read ID rather than the sequence?

Please let me know if there is anything I can clarify or any more information I can provide. Thank you!

**Comment by alexdobin** [comment]
Hi @hkevile 

STARsolo can only read CB/UMI from the read sequence, not from the read ID.
How were these FASTQs created with the CB/UMI in the read ID?

**Comment by hkevile** [comment]
Hi @alexdobin !

After investigating the problem further, these files went through some processing before I used them. I was able to get the pre-processed version that had the CB/UMI in the read sequence which resolved this error!

**Comment by ansheng0** [comment]
> Hi @alexdobin !
> 
> After investigating the problem further, these files went through some processing before I used them. I was able to get the pre-processed version that had the CB/UMI in the read sequence which resolved this error! Thank you!

Hi @hkevile :
I encountered the same issue as you. Could you please provide your solution? Thank you.
