### ISSUE TITLE
When I was using the STAR to generate a reference genome index file, it showed a segmentation fault error.

### ISSUE THREAD

**Issue by jefflllyyy** [alexdobin/STAR#1841]
This is my command：nohup STAR --runThreadN 8 --runMode genomeGenerate --limitSjdbInsertNsj 2000000 --genomeSAindexNbases 11 --sjdbGTFfile ../../../genome/Oryza_sativa.IRGSP-1.0.55.gtf --genomeDir ./2_index --genomeFastaFiles ../../../genome/Oryza_sativa.IRGSP-1.0.dna.toplevel.fa --sjdbFileChrStartEnd ./*.tab &。
my Log.out:
Estimated genome size with padding and SJs: total=genome+SJ=790759552 = 388759552 + 402000000
GstrandBit=32
Number of SA indices: 749862054
Apr 25 21:37:32 ... starting to sort Suffix Array. This may take a long time...
Number of chunks: 8;   chunks size limit: 856985200 bytes
Apr 25 21:37:34 ... sorting Suffix Array chunks and saving them to disk...
Writing 74994544 bytes into ./2_index//SA_7 ; empty space on disk = 1391025336320 bytes ... done
Writing 855167936 bytes into ./2_index//SA_0 ; empty space on disk = 1390989434880 bytes ...Writing 837500648 bytes into ./2_index//SA_1 ; empty space on d
Writing 856747064 bytes into ./2_index//SA_6 ; empty space on disk = 1389320601600 bytes ... done
 done
Writing 846944920 bytes into ./2_index//SA_2 ; empty space on disk = 1388439896064 bytes ...Writing 837665288 bytes into ./2_index//SA_5 ; empty space on d
 done
Writing 841078160 bytes into ./2_index//SA_4 ; empty space on disk = 1386331668480 bytes ... done
Writing 848797872 bytes into ./2_index//SA_3 ; empty space on disk = 1385014489088 bytes ... done
Apr 25 21:39:28 ... loading chunks from disk, packing SA...
Apr 25 21:39:39 ... finished generating suffix array
Apr 25 21:39:39 ... generating Suffix Array index
Apr 25 21:39:47 ... completed Suffix Array index
Apr 25 21:40:19   Finished preparing junctions
Apr 25 21:40:19 ..... inserting junctions into the genome indices
Apr 25 21:44:54   Finished SA search: number of new junctions=1964583, old junctions=0
Apr 25 21:52:41   Finished sorting SA indicesL nInd=785827672
Genome size with junctions=783640735  388759552   394881183
GstrandBit1=32   GstrandBit=32
Apr 25 21:53:00   Finished inserting junction indices
Apr 25 21:54:06   Finished SAi

**Comment by jefflllyyy** [comment]
It exits when it reaches this step：STAR --runThreadN 8 --runMode genomeGenerate --limitSjdbInsertNsj 2000000 --genomeSAindexNbases 11 --sjdbGTFfile ../../../genome/Oryza_sativa.IRGSP
        STAR version: 2.7.10a   compiled: 2022-01-14T18:50:00-05:00 :/home/dobin/data/STAR/STARcode/STAR.master/source
Apr 25 21:36:22 ..... started STAR run
Apr 25 21:36:22 ... starting to generate Genome files
Apr 25 21:36:29 ..... processing annotations GTF
Apr 25 21:37:32 ... starting to sort Suffix Array. This may take a long time...
Apr 25 21:37:34 ... sorting Suffix Array chunks and saving them to disk...
Apr 25 21:39:28 ... loading chunks from disk, packing SA...
Apr 25 21:39:39 ... finished generating suffix array
Apr 25 21:39:39 ... generating Suffix Array index
Apr 25 21:39:47 ... completed Suffix Array index
Apr 25 21:40:19 ..... inserting junctions into the genome indices。

In addition, I have a total of 426 SJ.out.tab files. Could this be due to having too many files? I tried using the same command to build an index for 3 SJ.out.tab files and there were no errors.

**Comment by alexdobin** [comment]
Hi @jefflllyyy 

please send me the Log.out file of the failed run.

**Comment by jefflllyyy** [comment]
Thanks a lot!

Alexander Dobin ***@***.***> 于2023年5月10日周三 01:18写道：
