### ISSUE TITLE
More details about soloFeatures options 

### ISSUE THREAD

**Issue by ColineGardou** [alexdobin/STAR#1843]
Hi Alex,

I saw your explanation about the difference between `GeneFull`, `GeneFull_ExonOverIntron` and `GeneFull_Ex50pAS` `soloFeatures` parameters in the previous issue #1460 which was very helpful, thanks !
But I found some particular cases that I don’t understand. Alignement was realised with each of the four options was loaded in IGV and the reads are coloured according to the GX tag. The blue reads have no GX tag. I used a mixed species (human GRCh38.105 and mouse GRCm39.105) reference genome and I used  `--soloStrand Forward`. The STAR version is 2.7.10b.

**- 1st case**
![Capture d’écran 2023-04-26 à 10 48 49](https://user-images.githubusercontent.com/76946782/234871476-f0531c18-e8c4-46fb-a953-d9b2bf90fa4c.png)
If we are interested in the read framed in red, it was not counted with `Gene` and `GeneFull` but it was counted with `GeneFull_ExonOverIntron` and `Gene_full_Ex50pAS`. 

1.1. I don't understand why this read was not associated to ENST00000514057 with `Gene` . If I’am not wrong, `Gene` counting requires reads to be fully concordant with gene transcript and here, this reads is fully concordant with only 1 exon.

1.2. I think I understand why this read was not counted with `GeneFull` because this reads overlaps with two different genes (as 1-base overlap with the gene locus is needed), so it’s considered ambiguous and not counted. Is that right ? 

1.3 I don’t understand why this read was counted with `GeneFull_ExonOverIntron` and not with `Gene`. I thought that it was priotized when the read overlap with the full gene locus (same as `Gene` option).

**- 2nd case**
![Capture d’écran 2023-04-26 à 11 19 06](https://user-images.githubusercontent.com/76946782/234872585-dd588077-4640-4377-b7fa-92e9c420c304.png)
(The three genes are in the reverse strand.)

2.1. This reads was not counted with `GeneFull` because they mapped on the intron and exons of different genes ? Thus is due to the fact that only a 1-base overlap with the gene locus is needed even if a part of the read is outside of the full gene locus ? 

2.2. Why this reads was not counted on the exon over on the intron with `GeneFull_ExonOverIntron` ? 

2.3. Same question as 2.2 with `GeneFull_Ex50pAS` ? More than 50% of the read is exonic ? But  the intronic region was chosen.  
In the situation where a read mapped on 2 exonic regions >50%, `GeneFull_Ex50pAS` choose the one with the highest percentage ?

Thanks,
Coline

**Comment by alexdobin** [comment]
Hi Coline,

In your first case, it looks like the read was spliced. The "Gene" only counts reads that are spliced concordant to annotations.
GeneFull options do not have that requirement.

> 2.1. This reads was not counted with GeneFull because they mapped on the intron and exons of different genes ? Thus is due to the fact that only a 1-base overlap with the gene locus is needed even if a part of the read is outside of the full gene locus ?

Yes.

> 2.2. Why this reads was not counted on the exon over on the intron with GeneFull_ExonOverIntron ?

ExonOverIntron requires the read to be entirely within the exon(s) of one gene

>
2.3. Same question as 2.2 with GeneFull_Ex50pAS ? More than 50% of the read is exonic ? But the intronic region was chosen.
In the situation where a read mapped on 2 exonic regions >50%, GeneFull_Ex50pAS choose the one with the highest percentage ?

Ex50pAS does not select the highest %. If >50% of a read are within the exons of 2 genes, it will not be counted.
