### ISSUE TITLE
flagging in the BAM file the PCR duplicated reads

### ISSUE THREAD

**Issue by fansalon** [alexdobin/STAR#1848]
Hello,

I have recently started using STARsolo on single-cell RNA-seq dataset. For the specific type of study I am doing I would need to generate from the STARsolo-outputted BAM file a pseudobulk BAM file containing only the alignments associated to a given set of cell barcodes. 

However, it seems like the PCR duplicated reads are not flagged as duplicated in the BAM file, unlike cellranger that does flag the reads as duplicated. Is there a way to trace back the reads that have been considered as duplicated by STARsolo?

Thanks a lot,
Federico

**Comment by alexdobin** [comment]
Hi Federico,

the reads are considered duplicated by CellRanger if CB, UB and GX tags coincide.
