### ISSUE TITLE
Multiple-mappers

### ISSUE THREAD

**Issue by apaytuvi** [alexdobin/STAR#185]
I have thousands of sequences downloaded from NCBI. On one hand, I selected 10 and I've created with `wgsim` fastq data. On the other hand, I concated those thousands of sequences into 3 big sequences in a FASTA file. Then, I created  STAR index with that FASTA.

One out of the 10 sequences used to make the fastq data is `NR_125595.1`. This sequence is placed in the following position inside the FASTA file used to create the STAR index:

```
3       1143145 1144486 >gi|672239006|ref|NR_125595.1| Senegalimassilia anaerobia strain JC110 16S ribosomal RNA gene, partial sequence
```

When I map the fastq data against the STAR index with the folowing command:

```
`STAR --runThreadN 20 --genomeDir /Synology/pipeline_16s/test_data/db/NCBI_16s/ --readFilesIn /Synology/pipeline_16s/test_data/fake_dataset/reads.R1.fq /Synology/pipeline_16s/test_data/fake_dataset/reads.R2.fq --outSAMtype BAM Unsorted --alignIntronMax 1 --outFilterMismatchNmax 999 --outFilterMismatchNoverLmax 0.5 --outFilterMatchNminOverLread 0.33 --outFilterScoreMinOverLread 0.33 --outFilterMultimapNmax 999 --outFilterMultimapScoreRange 0 --outReadsUnmapped Fastx --genomeLoad LoadAndKeep
```

Some of the reads map uniquely where they don't have to. For example, the following read:

```
gi|672239006|ref|NR_125595.1|_852_951_0:0:0_0:0:0_46fc2 163
```

comes from sequence `NR_125595.1` and must map, at least, between coordinates 1143145-1144486 of the long sequence 3. However, it is reported as uniquely mapped in a different place:

```
gi|672239006|ref|NR_125595.1|_852_951_0:0:0_0:0:0_46fc2 163     3       11428202             55      100M    =       1142820 100     GTGGCCGAGAGGAGCCTGCACAGGTGGTGCATGGCTGTCG             TCAGCTCGTGTCGTGAGATGTTGGGTTAAGTCCCGCAACGAGCGCAACCCCTGCCCCGTG    IIIIIIIIIIIIIIII             IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII             IIII    NH:i:1  HI:i:1  AS:i:198        nM:i:0
gi|672239006|ref|NR_125595.1|_852_951_0:0:0_0:0:0_46fc2 83      3       11428202             55      100M    =       1142820 -100    GTGGCCGAGAGGAGCCTGCACAGGTGGTGCATGGCTGTCG             TCAGCTCGTGTCGTGAGATGTTGGGTTAAGTCCCGCAACGAGCGCAACCCCTGCCCCGTG    IIIIIIIIIIIIIIII             IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII             IIII    NH:i:1  HI:i:1  AS:i:198        nM:i:0
```

Why?

**Comment by alexdobin** [comment]
Hi @apaytuvi 

the read maps perfectly (no mismatches) so this is unlikely to be an alignment problem.
Maybe to coordinates in your fasta files got shifted? When you concatenated the sequences, did you make sure there was no "padding" in between?

Cheers
Alex

**Comment by apaytuvi** [comment]
You are right. My file was wrong. Thanks!
