### ISSUE TITLE
Does `--limitGenomeGenerateRAM` take effect with `--runMode alignReads` ?

### ISSUE THREAD

**Issue by rpadmanabhan** [alexdobin/STAR#1865]
**Background :** 

I have a base human STAR index which I need to update with some sequences dynamically. This particular set of sequences I have are very large in number - 73700 sequences, each about ~150 nt long. When I run STAR as follows it seems to have trouble allocating enough memory : 

```
$ STAR --genomeDir <my_index_dir> --genomeFastaFiles <73700_sequences_fasta> --runThreadN 36 --readFilesIn <my_fq>

STAR version: 2.7.10b   compiled: 2022-11-01T09:53:26-04:00 :/home/dobin/data/STAR/STARcode/STAR.master/source
May 24 11:02:20 ..... started STAR run
May 24 11:02:20 ..... loading genome

EXITING: fatal error trying to allocate genome arrays, exception thrown: std::bad_alloc
Possible cause 1: not enough RAM. Check if you have enough RAM 31751412058 bytes
Possible cause 2: not enough virtual memory allowed with ulimit. SOLUTION: run ulimit -v 31751412058

May 24 11:02:20 ...... FATAL ERROR, exiting
```

But I do have enough free memory :
```
              total        used        free      shared  buff/cache   available
Mem:          137Gi       1.2Gi       135Gi       5.0Mi       1.3Gi       135Gi
Swap:            0B          0B          0B
```

So I tried creating an index before alignment with the large sequences and the human genome and I got this error : 
```
May 24 11:19:22 ..... started STAR run
May 24 11:19:22 ... starting to generate Genome files

EXITING because of FATAL PARAMETER ERROR: limitGenomeGenerateRAM=31000000000is too small for your genome
SOLUTION: please specify --limitGenomeGenerateRAM not less than 59910040501 and make that much RAM available 

May 24 11:19:35 ...... FATAL ERROR, exiting
```
Using `limitGenomeGenerateRAM 59910040501` as suggested seems to work and the genome seems to be building.

**My Question :** 
I tried using `limitGenomeGenerateRAM 59910040501` as above but during alignment but it did not help and I got the same `thrown: std::bad_alloc exception` as before.  Is it possible to somehow specify this outside `--genomeGenerate` when you have to incrementally update the genome index ? 

Appreciate any suggestions here. Also, thank you very much for building STAR,  it is a fantastic tool that has served the RNAseq community well for these many years.

**Comment by alexdobin** [comment]
Hi @rpadmanabhan 

this values has to be specified at the genome generation step, as it's used for calculating some parameters for genome indexing. Additionally (for such a large number of extra contigs) it's best to adjust `--genomeChrBinNbits 16`, but it also needs to be done at the genome generation step.
