### ISSUE TITLE
determine read strand alignment from Chimeric.out.junction

### ISSUE THREAD

**Issue by eksyang** [alexdobin/STAR#187]
Hi Alex, 

From Chimeric.out.junction file, how do I determine to which strand the read aligns to wrt to the reference genome? this is critical information and I wonder what requires to determine that
thanks
Xiao

**Comment by alexdobin** [comment]
Hi Xiao,

the columns 3 and 6 are the strands of two chimeric pieces. Note, that it is assumed that the strand of the 1st mate agrees with the original RNA molecule, while the 2nd mate's strand is reversed.

Cheers
Alex
