### ISSUE TITLE
calculation formula of "Fraction of Unique Reads in Cells"

### ISSUE THREAD

**Issue by onmyojiyys** [alexdobin/STAR#1872]
May I know the calculation formula of the "Fraction of Unique Reads in Cells" indicator in STARsolo "Summary.csv" when analyzing single-cell transcriptome data?

**Comment by alexdobin** [comment]
Fraction of Unique Reads in Cells = Number of genic reads in filtered cells / Total number of genic reads

**Comment by onmyojiyys** [comment]
Thanks！
