### ISSUE TITLE
multi-mappers marking

### ISSUE THREAD

**Issue by HuGang-c** [alexdobin/STAR#1873]
Hi, Alex

Part of My RNA-seq data were come from mixed tissue from two speices. In some cases, I have to take mixed tissue for sequencing since the sample itself hard to separate. I also have pure RNA-seq data from these two species. The two species were plants in the same family but different genus. They are evoled indepently for million years, thus most of their genome sequence were distinguishable. 

For the mixed data, I am now trying to separate the reads _in silicon_. Procedures I am working are:

1. mapping the pure data via STAR 1st pass mode.
2. combine the two genome, the gtf files, the SJ.tab files from 1st step via cat, and then index the mixed genome.
4. mapping reads from mixed-tissue to mixed genome.
5. separete the bam file through genome location by samtools view. For species A, I get A.bam, for B, B.bam.
6. filter multi-mappers via NH tag (>1) in A.bam and B.bam.
7. compare the reads name of multi-mappers in A.bam and B.bam, the multi-mapped reads shown in both A.bam and B.bam should be the reads need to be separated more carefully. 

I get very few reads from step 7 (around 8000 reads in each sample), that's unexpected. 

By checking the bam file. I found their are some reads, which from my understanding, should be marked as multi-mappers but not.

For example,

**When mapping to the mixed genome, this read was marked as unique mapper which only be mapped to A genome.** 
A01994:53:HGJKMDSX5:4:1105:24424:2613	99	contig182	3221944	255	151M	=	3222078	285	GTGGGGAAGAGTCAAGAAGGATGATTCAAGTGATGAGTCACAGAGAGATGAATTTGAAGTAGAAGTTGAAACATTGGGGAAGATCAGGCACAAAAATATTGTGAGATTGTGGTGCTGTTGCAACTCCAGAGATTGCAAGCTTCTAGTTTAC	FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFF:F:FFFFFFFFFFFFFFFFFFFFFFFFFFFF::FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	NH:i:1	HI:i:1	AS:i:300	nM:i:0
A01994:53:HGJKMDSX5:4:1105:24424:2613	147	contig182	3222078	255	151M	=	3221944	-285	GCAAGCTTCTAGTTTACGAGTACATGCCAAATGGGAGCTTGGGAGATGTGTTGCATAGCAGTAAAGCAAGTTTGTTGGATTGGCCAACGAGGTATAAGATAGCTTTGGATGCGGCTGATGGGTTATCTTATTTGCATCATGATTGTGTTCC	FFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFF:FFFFFFFFFFFFFFFFFFF	NH:i:1	HI:i:1	AS:i:300	nM:i:0

**But the same reads can also be mapped to B genome.**
A01994:53:HGJKMDSX5:4:1105:24424:2613	99	chr2	6723677	255  151M	=	6723811	285	GTGGGGAAGAGTCAAGAAGGATGATTCAAGTGATGAGTCACAGAGAGATGAATTTGAAGTAGAAGTTGAAACATTGGGGAAGATCAGGCACAAAAATATTGTGAGATTGTGGTGCTGTTGCAACTCCAGAGATTGCAAGCTTCTAGTTTAC	FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFF:F:FFFFFFFFFFFFFFFFFFFFFFFFFFFF::FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	NH:i:HI:i:1	AS:i:280	nM:i:10
A01994:53:HGJKMDSX5:4:1105:24424:2613	147	chr2	6723811	255  151M	=	6723677	-285	GCAAGCTTCTAGTTTACGAGTACATGCCAAATGGGAGCTTGGGAGATGTGTTGCATAGCAGTAAAGCAAGTTTGTTGGATTGGCCAACGAGGTATAAGATAGCTTTGGATGCGGCTGATGGGTTATCTTATTTGCATCATGATTGTGTTCC	FFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFF:FFFFFFFFFFFFFFFFFFF	NH:i:HI:i:1	AS:i:280	nM:i:10

It seems this read can be mapped to both genome perfectly, but STAR did not mark it as multi-mapper when mapped it to the mixed genome. The only difference I noticed is the AS tag. I do not know if higher alignment score will influence the results for multi-mappers marking. 

The parameter used for mapping are:
STAR --genomeDir ab_genome --readFilesIn R1.fq.gz R2.fq.gz --readFilesCommand zcat --outSAMunmapped Within --outSAMtype BAM SortedByCoordinate --outFileNamePrefix ab_star --runThreadN 16

I want to know in which situation a multi-mappers will be marked by STAR and does I get seemly wrong results because of wrong procedure?

**Comment by alexdobin** [comment]
Hi @HuGang-c 

the alignment to the B-genome has `AS:i:280 nM:i:10`, i.e. 10 mismatches and much lower (280<300) alignment score - this is why only the alignment to A-genome is selected when mapping to A+B.

**Comment by HuGang-c** [comment]
Hi, Alex,

Thanks for your quick response. 

I did not notice the nM tag before and I misunderstand the CIGAR string. 

Thanks again.
