### ISSUE TITLE
stranded vs nonstranded vs reversestranded

### ISSUE THREAD

**Issue by Phylloxera** [alexdobin/STAR#1885]
Hello,

While trying to track down the reason for a discrepancy in my two pipelines (bbduk + STAR = pipeline 1; trimmomatic + HISAT2 + Stringtie = pipeline 2), I came across an issue, I think I've brought up before. mapping seems good in both pipelines. Using HISAT2+Stringtie, I get an average of 59.67M reads-per-library. In STAR, I get an average of 1.08M, 27.62M & 28.19M for stranded, nonstranded & reversestranded respectively. I have in my head that you said to not combine the columns, but it strikes me that if I combined nonstranded & reversestranded, I'd be much closer to the HISAT2 number. 
1. Is my memory correct that columns should not be combined?
2. Should I be unconcerned that regardless of whether nonstranded or reversestranded results are used, I'm looking at about 1/2 the number of mapped reads relative to hisat2?
3. Was this situation likely due to getting a gtf file with the wrong strandedness from the library prep? I've never seen a downloaded gtf file labeled with a strandedness, but I wouldn't really know where to look for this. Our core lab director's answer to me about the strandedness of a library prep didn't make any sense to me so I'm still completely confused about this issue. Looking [here](https://www.biostars.org/p/218995/) and [here](https://groups.google.com/g/rna-star/c/gZRJx3ElRNo) also has not eased my confusion.

The GTF file and trimming with bbduk are the same for the STAR vs HISAT2+Stringtie counts presented here.

version 2.7.10a
mapping options - --outFilterIntronMotifs RemoveNoncanonical --quantMode TranscriptomeSAM GeneCounts --outSAMtype BAM SortedByCoordinate

Sorry to keep coming back to this :(

**Comment by Phylloxera** [comment]
Hi @alexdobin 

That eases my mind considerably about the strandedness issue, thanks! I'd like some way to make my comparisons more 'apples to apples' if that makes sense. Would STAR + featureCounts or STAR + somethingelse make for a better comparison to hisat2+stringtie? i'd like my gene count matrices input to deseq2 to be comparable. Thanks again!

**Comment by alexdobin** [comment]
Hi @Phylloxera 

the compatible pipelines would be STAR+Stringtie vs HISAT2+Stringtie, or STAR ReadsPerGene vs HISAT2+featureCounts.
