### ISSUE TITLE
STARsolo Statistics Explanation

### ISSUE THREAD

**Issue by MartaBenegas** [alexdobin/STAR#1887]
Hi STAR team!

First, many thanks for creating the STARsolo tool, it's really useful! 

There are some statistics in the STARsolo-specific results that I don't understand and haven't found in the manual. So it'd be helpful if you could explain them or redirect me to the proper documentation. The list would be:

**Barcodes.stats**

- noNinCB
- noNinUMI
- noUMIhomopolymer

**Summary.csv**

- Sequencing Saturation --> How is it calculated?

**Features.stats**
In general, does this report refer to the reads? That is, the `noUnmapped` would be the number of unmapped reads, and the `noNoFeature` would be the number of reads not mapped to a feature?  etc.

Why there is a reference to the WhiteList in the feature report? :  `noTooManyWLmatches`, `noMMtoWLwithoutExact`, `yesWLmatch `, `yessubWLmatchExact`, `yessubWLmatch_UniqueFeature`.

It would be very helpful if you could explain them. 

Thank you in advance!

**Comment by MartaBenegas** [comment]
Hi @alexdobin, 

thank you for your answers so far! 

I would like to clarify this though: 

> The WL statistics describes the reads with features that match WL

With this WL, do you mean the list of features present in the GFF?

**Comment by alexdobin** [comment]
Hi @MartaBenegas,

sorry, it was a typo. I meant the reads with barcodes that match the whitelist (and features that match genes in the annotations).

**Comment by MartaBenegas** [comment]
Hi @alexdobin 
ok! Then, for example, the `noMMtoWLwithoutExact` would be the "number of reads associated to barcodes with multiple matches to the whitelist and without an exact match"? 

And what about the "sub" in `subMultiFeatureMultiGenomic`, `yessubWLmatchExact`, and `yessubWLmatch_UniqueFeature` ?

Sorry for the number of questions and many thanks to take the time to answer them!

**Comment by alexdobin** [comment]
Hi Marta,

the "no" prefix means that these are not counted in the matrix.
MMtoWLwithoutExact means the barcode matches to passlist with one mismatch, but there are no other reads matching to the same passlist entry. This is used in some counting schemes that try to replicate CellRanger behavior.

**Comment by MartaBenegas** [comment]
Ok, let's see if I got it:

**Barcoded Reads Stats:**
Reads not used for quantification because:
- noNoAdapter: Reads without an Adapter.
- noNoUMI: Reads not Associated to a Valid UMI
- noNoCB: Reads not Associated to a Valid Cell Barcode
- noNinCB: Reads with N's in Cell Barcodes
- noNinUMI: Reads with N's in UMIs
- noUMIhomopolymer: Reads  associated with a Homopolymeric UMI
- noNoWLmatch: Reads Without Match to the Whitelist
- noTooManyMM: Reads With Too Many Mismatches to the Whitelist
- noTooManyWLmatches: Reads With Too Many matches to the Whitelist

Reads used for the quantification:
- yesWLmatchExact: Reads with Exact Match to Whitelist
- yesOneWLmatchWithMM: Reads with One Match to the Whitelist with Mismatches
- yesMultWLmatchWithMM: Reads with Multiple Matches to the Whitelist with Mismatches


**Feature ReadsStats**
Reads not used for quantification because:

- noUnmapped: Unmapped Reads
- noNoFeature: Reads not Mapped to a Feature
- MultiFeature: Reads Aligned to Multiple Features
- subMultiFeatureMultiGenomic :question: 
- noTooManyWLmatches: Reads Not Counted Because their Barcoded pair has Too Many Matches to the Whitelist
- noMMtoWLwithoutExact: Reads Not Counted Because their Barcoded pair has Mismatches to the Whitelist and there's no more reads supporting that barcode

Reads used for the quantification:
- yesWLmatch: Reads whose Barcoded Pair has a Match to the Whitelist
- yessubWLmatchExact: :question: 
- yessubWLmatch_UniqueFeature: :question: 
- yesCellBarcodes: Reads Assossiated to a Valid Cell Barcode
- yesUMIs: Reads Assossiated to a Valid UMI

**Comment by alexdobin** [comment]
subMultiFeatureMultiGenomic: reads mapping to multiple genomic loci and multiple features (a subset of MultiFeature)
yessubWLmatchExact: reads with cell barcode exactly matched to the whitelist (a subset of yesWLmatch)
yessubWLmatch_UniqueFeature: reads with matched to the WL and unique feature (a subset of yesWLmatch)

**Comment by MartaBenegas** [comment]
Everything is clear now! Thanks for your time.

**Comment by zhouyiqi91** [comment]
> Ok, let's see if I got it:
> 
> **Barcoded Reads Stats:** Reads not used for quantification because:
> 
> * noNoAdapter: Reads without an Adapter.
> * noNoUMI: Reads not Associated to a Valid UMI
> * noNoCB: Reads not Associated to a Valid Cell Barcode
> * noNinCB: Reads with N's in Cell Barcodes
> * noNinUMI: Reads with N's in UMIs
> * noUMIhomopolymer: Reads  associated with a Homopolymeric UMI
> * noNoWLmatch: Reads Without Match to the Whitelist
> * noTooManyMM: Reads With Too Many Mismatches to the Whitelist
> * noTooManyWLmatches: Reads With Too Many matches to the Whitelist
> 
> Reads used for the quantification:
> 
> * yesWLmatchExact: Reads with Exact Match to Whitelist
> * yesOneWLmatchWithMM: Reads with One Match to the Whitelist with Mismatches
> * yesMultWLmatchWithMM: Reads with Multiple Matches to the Whitelist with Mismatches
> 
> **Feature ReadsStats** Reads not used for quantification because:
> 
> * noUnmapped: Unmapped Reads
> * noNoFeature: Reads not Mapped to a Feature
> * MultiFeature: Reads Aligned to Multiple Features
> * subMultiFeatureMultiGenomic ❓
> * noTooManyWLmatches: Reads Not Counted Because their Barcoded pair has Too Many Matches to the Whitelist
> * noMMtoWLwithoutExact: Reads Not Counted Because their Barcoded pair has Mismatches to the Whitelist and there's no more reads supporting that barcode
> 
> Reads used for the quantification:
> 
> * yesWLmatch: Reads whose Barcoded Pair has a Match to the Whitelist
> * yessubWLmatchExact: ❓
> * yessubWLmatch_UniqueFeature: ❓
> * yesCellBarcodes: Reads Assossiated to a Valid Cell Barcode
> * yesUMIs: Reads Assossiated to a Valid UMI

As Alex mentioned: Features.stats indeed refers to the number of reads, except yesCellBarcodes, yesUMIs
yesCellBarcodes: valid Barcode number
yesUMIs: UMI number
