### ISSUE TITLE
Correction of barcodes/UMI (STARsolo)

### ISSUE THREAD

**Issue by J0bbie** [alexdobin/STAR#1897]
Dear Alex,

When running STARsolo (CB_UMI_Complex) on some sci-RNA-seq3 sequencing data in which we add all the four pre-corrected/padded barcodes (4x10nt; 40nt) and UMI (8nt) into the R1 sequence, I can confirm that it identifies all exact matches with the sample-specific barcode whitelist which is great!

However (and I'm not sure if I'm missing anything obvious here), these barcodes (and UMI) are still corrected/masked with A (using `Exact` matching), e.g.:
```
CR:Z:CAGCTAGCGGAACCTAGCTTAAACCATAGTGACGACCTGC
CB:Z:AAAAAAAAGGAACCTAGCTTAAACCATAGTGACGACCTGC 

UR:Z:CAGAGCCC
UB:Z:AACAGAGCCC
```
Granted; when checking the input R1 sequences, all the barcodes (40nt) indeed had the same first 8nt and were therefore uninformative so I appreciate the masking.

Did I understand the masking of these barcode sequences correct or did I mess up something with the parameters/input?
Is it possible to disable this masking and use the CR:Z as-is (if `Exact`) as cellular barcode (barcodes.tsv) or would this generally be a bad idea?

Thanks in advance!

**Command**
```shell
STAR --genomeDir <index> --runThreadN <threads> \
--readFilesIn {input.R2} {input.R1} --readFilesCommand zcat \
--soloType CB_UMI_Complex --soloCBmatchWLtype Exact --soloCBwhitelist <whitelist> --soloCBposition  0_0_0_39 --soloUMIposition 0_40_0_47 \
--soloCellFilter EmptyDrops_CR --soloFeatures GeneFull --soloMultiMappers Uniform --soloUMIdedup Exact \
--outSAMtype BAM SortedByCoordinate --outSAMunmapped Within --outFileNamePrefix <samplename> \
--outSAMmultNmax 1 --outSAMstrandField intronMotif \
--outSAMattributes NH HI AS nM NM MD jM jI MC ch XS CR UR GX GN sM CB UB \
--twopassMode Basic --twopass1readsN -1

``` 

**Summary.csv for a single demultiplexed sample**
```text
Number of Reads,6452753
Reads With Valid Barcodes,1
Sequencing Saturation,0.548333
Q30 Bases in CB+UMI,1
Q30 Bases in RNA read,0.918092
Reads Mapped to Genome: Unique+Multiple,0.790438
Reads Mapped to Genome: Unique,0.696654
Reads Mapped to GeneFull: Unique+Multiple GeneFull,0.69081
Reads Mapped to GeneFull: Unique GeneFull,0.661388
Estimated Number of Cells,576
Unique Reads in Cells Mapped to GeneFull,2881254
Fraction of Unique Reads in Cells,0.675119
Mean Reads per Cell,5002
Median Reads per Cell,3280
UMIs in Cells,1358343
Mean UMI per Cell,2358
Median UMI per Cell,1660
Mean GeneFull per Cell,1401
Median GeneFull per Cell,1167
Total GeneFull Detected,17347
```

**Comment by alexdobin** [comment]
Hi Job,

STARsolo can only deal with barcodes <=31 bases.
To mitigate this, you can use multiple short barcodes with the CB_UMI_Complex scheme.

**Comment by J0bbie** [comment]
Hi Alex,

CB_UMI_Complex wasn't throwing an error (<31bp) when specifying a single 40nts barcode compared to CB_UMI_SIMPLE, so I thought it just accepted it. Specifying the 4 barcodes separately indeed generates the correct barcodes ids.

Thanks!

```
--soloType CB_UMI_Complex --soloCBmatchWLtype Exact \
--soloCBposition 0_0_0_9 0_10_0_19 0_20_0_29 0_30_0_39 --soloUMIposition 0_40_0_47 \
--soloCBwhitelist <wl1> <wl2> <wl3> <wl4>
```
