### ISSUE TITLE
short reads cause memory to blow up

### ISSUE THREAD

**Issue by roryk** [alexdobin/STAR#19]
Hi Alex,

I'm mapping to a genome that is relatively small, and STAR uses huge amounts of memory trying to map short reads, over 60 GB before I run out of memory. The reads have a minimum size of 20 bp. I posted the head and tail of the progress log file: 

```
Feb 03 10:05:35    141.3     2473523      190    99.0%    189.8     0.2%     0.0%     0.0%     0.0%     1.0%     0.0%
Feb 03 10:06:36    158.0     5442105      190    99.0%    190.1     0.2%     0.1%     0.0%     0.0%     0.9%     0.0%
Feb 03 10:07:36    145.1     7414834      190    99.0%    190.4     0.2%     0.1%     0.0%     0.0%     0.9%     0.0%
Feb 03 10:08:38    151.8    10370092      191    98.9%    190.8     0.2%     0.2%     0.0%     0.0%     0.9%     0.0%
Feb 03 10:09:38    153.9    13078382      191    98.9%    190.8     0.2%     0.2%     0.0%     0.0%     0.9%     0.0%
Feb 03 10:10:38    163.8    16649732      191    98.9%    190.7     0.2%     0.2%     0.0%     0.0%     1.0%     0.0%
Feb 03 10:11:39    165.3    19602262      190    98.9%    190.5     0.2%     0.2%     0.0%     0.0%     0.9%     0.0%
```

```
Feb 03 18:45:08     13.0   112499554      191    77.2%    190.6     0.2%     0.3%     0.0%     0.0%    22.6%     0.0%
Feb 03 18:47:49     12.9   112743799      191    77.0%    190.6     0.2%     0.3%     0.0%     0.0%    22.7%     0.0%
Feb 03 18:48:51     12.9   113108446      191    76.8%    190.6     0.2%     0.3%     0.0%     0.0%    22.9%     0.0%
Feb 03 18:50:45     12.9   113230231      191    76.7%    190.6     0.2%     0.3%     0.0%     0.0%    23.0%     0.0%
Feb 03 18:56:46     12.8   113351490      191    76.7%    190.6     0.2%     0.3%     0.0%     0.0%    23.1%     0.0%
Feb 03 19:02:55     12.6   113472737      191    76.6%    190.6     0.2%     0.3%     0.0%     0.0%    23.1%     0.0%
Feb 03 19:05:50     12.6   113594358      191    76.5%    190.6     0.2%     0.3%     0.0%     0.0%    23.2%     0.0%
Feb 03 19:07:04     12.6   113715626      191    76.5%    190.6     0.2%     0.3%     0.0%     0.0%    23.3%     0.0%
Feb 03 19:09:31     12.5   113958408      191    76.3%    190.6     0.2%     0.3%     0.0%     0.0%    23.4%     0.0%
Feb 03 19:11:39     12.5   114079534      191    76.3%    190.6     0.2%     0.3%     0.0%     0.0%    23.5%     0.0%
Feb 03 19:13:58     12.5   114322705      191    76.1%    190.6     0.2%     0.3%     0.0%     0.0%    23.6%     0.0%
```
Eventually it dies when I run out of memory on the machine. 

I put up a gist of the log file here: https://gist.github.com/roryk/3763737c82f5d534cfa8

Do you have any suggestions? Is there a minimum read size that would not trigger this?

**Comment by alexdobin** [comment]
Hi Rory,
this is very strange, I cannot imagine how STAR would use 60GB for this genome. Your parameters look OK.
It also looks like the mapping speed goes down significantly, though this may be caused by RAM swapping. I do not think that short reads would cause this. Do you expect that sequencing quality decreases towards the end of the file? If you take 1M reads from the end of the file, map them with 1 thread, do you see slow mapping and high memory usage? 

It would be nice if you could get me a portion of the file that still exhibits the problem, so that I can try it on my system.

Cheers
Alex

**Comment by roryk** [comment]
Hi Alex,

We tracked this down to a memory leak in sambamba, which we were piping the output of STAR to. Sorry to waste your time. Thanks so much.
