### ISSUE TITLE
Tab in MD tag

### ISSUE THREAD

**Issue by pigraul** [alexdobin/STAR#1902]
Hi,

I noticed a tab in the MD tag. What could be the cause of this, and is it avoidable?

`AGTGGAATGTTG_103201531      16      1       171283092       255     58M1D52M2D39M   *       0       0 ACCTAAATAAACAGCAAATAGTGTTAGGTCAGGGTGCCCTCACCTAAGTTGCTTTTTCTGACACCCCCACCTTACACATAAATTTAGTTATGTTTCTCATTGCTTTGCCCGCCCCCCCCATAACCTAGGTATACGAGGACATACCGGAG  FFFFFFF:FFFF,FFFFF:FFFFF:FFFFFFFFFFFFF:FFFFFF,FF,FFFFFFFFFFFFFFFFFFFF,FF:FF:FFFFF:FFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFF    NH:i:1  HI:i:1  AS:i:133        nM:i:2  NM:i:5  MD:Z:58^        11A40^CT0C38    jM:B:c,-1       jI:B:i,-1`

Thanks!

**Comment by alexdobin** [comment]
Hi @pigraul 

the "^" symbol corresponds to "D" (deletions) in the CIGAR.

**Comment by pigraul** [comment]
Hi @alexdobin ,

`"MD:Z:58^        11A40^CT0C38"`  a tab is after the "^"

**Comment by pigraul** [comment]
> Hi @alexdobin ,
> 
> `"MD:Z:58^ 11A40^CT0C38"` a tab is after the "^"

I checked the reference sequence, there is an "N".

**Comment by alexdobin** [comment]
What STAR version are you using? The latest version outputs correct MD tag:
`1	0	chr1	171283092	255	58M1D52M2D39M	*	0	0	ACCTAAATAAACAGCAAATAGTGTTAGGTCAGGGTGCCCTCACCTAAGTTGCTTTTTCTGACACCCCCACCTTACACATAAATTTAGTTATGTTTCTCATTGCTTTGCCCGCCCCCCCCATAACCTAGGTATACGAGGACATACCGGAG	*	MD:Z:58^N11A40^CT0C38
`

**Comment by pigraul** [comment]
STAR_2.6.1a.   I will try the latest version, thanks for your help @alexdobin .
