### ISSUE TITLE
STARsolo splice junction counting from multi-mapping UMIs

### ISSUE THREAD

**Issue by dbogdano** [alexdobin/STAR#1903]
Hello, 

Thank you for building and continuing to support STAR. When using STARsolo, would you be able to provide some clarification on how UMI based counts are distributed to splice junctions? For example, if I have a single UMI read that bridges two splice junctions, does each junction receive one count in the final SJ count matrix, or is the count split up in a manner similar to the soloMultiMappers Uniform method? 

For a second example, If I have two reads with the same UMI, originally derived from the same molecule, and which map to two different positions along the gene and bridge two different splice junctions, would each junction receive a whole UMI count, a fraction, or something else? 

Thanks again, 
Derek

**Comment by alexdobin** [comment]
Hi Derek,

 in both cases, each junction will receieve +1 UMI count. It's interpreted as the number of RNA molecules supporting each junction.
