### ISSUE TITLE
STAR is taking too long to map

### ISSUE THREAD

**Issue by RochaLAJ** [alexdobin/STAR#1904]
PC setup: Ryzen 7 2800x | 32GB RAM  | Fedora Linux | Running on SSD. 

I am working with scRNA-Seq, paired end and each fastq has 3GB.  
My run started at 4am, it's 12am now and my highest speed M/hr is 0.3. 

References used in GenomeGenerate: Gencode primary assembly, GTF basic annotation. 
I'm using all my cores and ram consumption is close to 22GB (1GB swap).

**Comment by RochaLAJ** [comment]
> Hi @RochaLAJ
> 
> this is indeed very slow. I would recommend mapping one of the 10X public datasets to check your system.

Hi @alexdobin 

I tested a local sample obtained from whole blood (ION S5, single end) and the highest speed M/hr was **40.0**, lowest **2.8**. Same machine, same pipeline, different samples. Any suggestion?

Thank you for your time and effort.

**Comment by alexdobin** [comment]
Hi @RochaLAJ 

40M/hr is also quite slow. It should typically be ~50M/hr per thread. I would recommend trying to map on a different machine.

**Comment by RochaLAJ** [comment]
> Hi @RochaLAJ
> 
> 40M/hr is also quite slow. It should typically be ~50M/hr per thread. I would recommend trying to map on a different machine.

Dear @alexdobin 
I tested the same pipeline that i used before on a different machine (Google Cloud). I used a modest setup: 8 Cpus, 64GB Ram (overkill) and 1TB SSD. STAR Worked as expected! Now i wonder what is happening with my local setup... in any case, thank you for the time and effort! 

All the best
