### ISSUE TITLE
STARsolo barcode correction (1 mismatch)

### ISSUE THREAD

**Issue by ColineGardou** [alexdobin/STAR#1910]
Hi Alex,

I found some particular cases about the BC correction that I don't understand: some barcodes with 1 mismatch are not corrected by STARsolo. 

I ran STARsolo using as an example one of the reads for which the BC has an uncorrected mismatch (the original BC is `CGTTAATGATGTCTTG` and the whitelist of BC contains `CGCTAATGATGTCTTG`, so there is a mismatch at the third bp). I try to give all of the whitelist or only the BC `CGCTAATGATGTCTTG` and I observed the same results. The STAR version is v.2.7.10b.

I ran STARsolo using:
- Options:
`--outSAMattributes CR CB UR UB GX GN AS NH --outSAMunmapped Within --soloType CB_UMI_Simple --soloUMIlen 10 --soloFeatures GeneFull_ExonOverIntron --outSAMtype BAM SortedByCoordinate --outFilterMultimapNmax 1 --outFilterScoreMinOverLread 0 --outFilterMatchNminOverLread 0 --outFilterMatchNmin 30`
- R1 fastq file:
```
@M08001:76:000000000-KR4TG:1:2103:11431:10546 1:N:0:AACGGTGG
TTCTAGCAAGCCTCGCTAACCTCGCCTTACCCCCCACTATTAACCTACTGGGAGAACTCTCTGTGCTAGTAACCACGTTCTCCTGATCAAA
+
GDGCGFGGGEGFFF@@CGGFFAECFEEGGG=FGGGGGFFGGGGGGGGGGGDGCCEGGGGGGGGFGGGGFGGGGGFGGCG?FFFFFFFFFDD
```
- R2 fastq file:
```
@M08001:76:000000000-KR4TG:1:2103:11431:10546
CGTTAATGATGTCTTGTCGTATCTGT
+
,,3,=,=895)5)3--CCCCCGGGGG
```
The resulting BAM:
```
M08001:76:000000000-KR4TG:1:2103:11431:10546	0	HsMT	11838	255	91M	*	0	0	TTCTAGCAAGCCTCGCTAACCTCGCCTTACCCCCCACTATTAACCTACTGGGAGAACTCTCTGTGCTAGTAACCACGTTCTCCTGATCAAA	GDGCGFGGGEGFFF@@CGGFFAECFEEGGG=FGGGGGFFGGGGGGGGGGGDGCCEGGGGGGGGFGGGGFGGGGGFGGCG?FFFFFFFFFDD	CR:Z:CGTTAATGATGTCTTG	UR:Z:TCGTATCTGT	GX:Z:ENSG00000198886	GN:Z:MT-ND4	AS:i:89	NH:i:1	CB:Z:-	UB:Z:-
```
And the Barcodes.stats:
```                                    
yesWLmatchExact     0
yesOneWLmatchWithMM      1
yesMultWLmatchWithMM     0
```
I don't understand why STARsolo doesn't correct this BC with 1 mismatch ? 
And why this BC is counted in `yesOneWLmatchWithMM` but not corrected in BAM ? 

Thanks for your help,
Coline

**Comment by alexdobin** [comment]
Hi Coline,

the matching of CBs to WL is controlled by the `--soloCBmatchWLtype` option.
It's `1MM_multi` by default. This option requires that CBs have at least one read with exact match.
I guess the CB in your example does not have any other reads with exact matches, to this match with one mismatch is not reported.

All options:
```
soloCBmatchWLtype           1MM_multi
    string:                 matching the Cell Barcodes to the WhiteList
                            Exact                           ... only exact matches allowed
                            1MM                             ... only one match in whitelist with 1 mismatched base allowed. Allowed CBs have to have at least one read with exact match.
                            1MM_multi                       ... multiple matches in whitelist with 1 mismatched base allowed, posterior probability calculation is used choose one of the matches.
                                                                Allowed CBs have to have at least one read with exact match. This option matches best with CellRanger 2.2.0
                            1MM_multi_pseudocounts          ... same as 1MM_Multi, but pseudocounts of 1 are added to all whitelist barcodes.
                            1MM_multi_Nbase_pseudocounts    ... same as 1MM_multi_pseudocounts, multimatching to WL is allowed for CBs with N-bases. This option matches best with CellRanger >= 3.0.0
                            EditDist_2                    ... allow up to edit distance of 3 fpr each of the barcodes. May include one deletion + one insertion. Only works with --soloType CB_UMI_Complex. Matches to multiple passlist barcdoes are not allowed. Similar to ParseBio Split-seq pipeline. 
```

**Comment by ColineGardou** [comment]
Hi Alex,

Yes, that's right. Thanks for your quick reply!
