### ISSUE TITLE
Building transcriptome index with buffer sequences between the transcripts

### ISSUE THREAD

**Issue by alexfriman** [alexdobin/STAR#1918]
We use STAR as part of a pipeline involving sliding window algorithm downstream. To map the mRNA reads I tried to build an artificial genome consisting of few scaffolds each consisting of 30K-100K spliced mouse transcripts with 5000 "N" symbols between the sequences.

STAR  2.7.10b was run using:
`STAR --runThreadN 63 --runMode genomeGenerate --genomeDir $workdir --genomeFastaFiles ${workdir}/micemRNAcollapsed.fa --genomeSAindexNbases 13`

Number of CPU cores is 64, allocated memory 490 GB.
After 4 days the index was still building.
When I tried to build an index from the same fasta file using Hisat2 , it was done in few minutes. Our pipeline uses STAR at many steps, and we would prefer to minimize number of different programs involved.

What can be adjusted to build this index using STAR?
5000 "N" buffer sequence is required since our sliding window is 1000 bases and we need to prevent overlapping of transcripts.
I also tried to make each transcript a fasta record. STAR builds the index and maps the library, but R crashes when I try to load the bam file.

Best regards,
Alex Friman

**Comment by alexdobin** [comment]
Hi Alex,

Building an index from the transcript sequences should be doable, even  if you string them together.
Please send me the Log.out file.

**Comment by alexfriman** [comment]
Hello Dr Dobin,

The output:
`[frimanav@biowulf mousemRNAcollapsed]$ cat Log.out 
STAR version=2.7.10b
STAR compilation time,server,dir=2023-03-02T16:30:57-05:00 cn3063:/usr/local/apps/STAR/DOWNLOADS/STAR-2.7.10b/source
STAR git: 
##### Command Line:
STAR --runThreadN 63 --runMode genomeGenerate --genomeDir /home/frimanav/data/genomes/mousemRNAcollapsed --genomeFastaFiles /home/frimanav/data/genomes/mousemRNAcollapsed/micemRNAcollapsed.fa --genomeSAindexNbases 13
##### Initial USER parameters from Command Line:
###### All USER parameters from Command Line:
runThreadN                    63     ~RE-DEFINED
runMode                       genomeGenerate        ~RE-DEFINED
genomeDir                     /home/frimanav/data/genomes/mousemRNAcollapsed     ~RE-DEFINED
genomeFastaFiles              /home/frimanav/data/genomes/mousemRNAcollapsed/micemRNAcollapsed.fa        ~RE-DEFINED
genomeSAindexNbases           13     ~RE-DEFINED
##### Finished reading parameters from all sources

##### Final user re-defined parameters-----------------:
runMode                           genomeGenerate   
runThreadN                        63
genomeDir                         /home/frimanav/data/genomes/mousemRNAcollapsed
genomeFastaFiles                  /home/frimanav/data/genomes/mousemRNAcollapsed/micemRNAcollapsed.fa   
genomeSAindexNbases               13

-------------------------------
##### Final effective command line:
STAR   --runMode genomeGenerate      --runThreadN 63   --genomeDir /home/frimanav/data/genomes/mousemRNAcollapsed   --genomeFastaFiles /home/frimanav/data/genomes/mousemRNAcollapsed/micemRNAcollapsed.fa      --genomeSAindexNbases 13
----------------------------------------

Number of fastq files for each mate = 1
ParametersSolo: --soloCellFilterType CellRanger2.2 filtering parameters:  3000 0.99 10
Finished loading and checking parameters
--genomeDir directory exists and will be overwritten: /home/frimanav/data/genomes/mousemRNAcollapsed/
Jul 27 06:49:32 ... starting to generate Genome files
/home/frimanav/data/genomes/mousemRNAcollapsed/micemRNAcollapsed.fa : chr # 0  "1" chrStart: 0
/home/frimanav/data/genomes/mousemRNAcollapsed/micemRNAcollapsed.fa : chr # 1  "100002" chrStart: 714342400
/home/frimanav/data/genomes/mousemRNAcollapsed/micemRNAcollapsed.fa : chr # 2  "200003" chrStart: 1431306240
/home/frimanav/data/genomes/mousemRNAcollapsed/micemRNAcollapsed.fa : chr # 3  "300004" chrStart: 2123628544
/home/frimanav/data/genomes/mousemRNAcollapsed/micemRNAcollapsed.fa : chr # 4  "400005" chrStart: 2635071488
/home/frimanav/data/genomes/mousemRNAcollapsed/micemRNAcollapsed.fa : chr # 5  "500006" chrStart: 3250061312
Chromosome sequence lengths: 
1	714315716
100002	716960031
200003	692239598
300004	511282588
400005	614802213
500006	465146722
Genome sequence total length = 3714746868
Genome size with padding = 3715366912
Estimated genome size with padding and SJs: total=genome+SJ=3916366912 = 3715366912 + 201000000
GstrandBit=32
Number of SA indices: 1560633578
Jul 27 06:49:54 ... starting to sort Suffix Array. This may take a long time...
Number of chunks: 73;   chunks size limit: 201372072 bytes
Jul 27 06:50:06 ... sorting Suffix Array chunks and saving them to disk...
`

**Comment by alexdobin** [comment]
Hi Alex,

it seems to me that the total size of the mRNA sequences is too large: "Number of SA indices: 156063357" represents the number of non-N bases. It should be a few hundred million bases.

**Comment by alexfriman** [comment]
Hello Dr Dobin,

When building mm10 whole genome index, STAR logged "Number of SA indices: 5305567000" and finished the task without any issues. Log file is attached
[Log.out.mm10.txt](https://github.com/alexdobin/STAR/files/12253531/Log.out.mm10.txt)

**Comment by alexfriman** [comment]
After exons deduplication the fasta file was 400 Mbytes and the index was generated in 30 seconds
