### ISSUE TITLE
STARsolo all Cell Barcode Statistics are 0

### ISSUE THREAD

**Issue by MartaBenegas** [alexdobin/STAR#1947]
Hi Team! 

I was looking into the statistics produced by STARsolo and realized that all the statistics in the Barcodes.stats are 0. I find it weird that no reads were discarded at all. Moreover, the statistics with the prefix "yes" (which refers to reads used for the quantification) can't be 0 since I obtained a matrix with 5631 cells and a mean reads per cell of 6054. 

In addition,  the "Reads With Valid Barcodes" in the Summary.csv is 1, which I think doesn't match with the "Mean Reads per Cell" of 6054.

What could be possibly happening here? 

Thanks in advance!

[Barcodes.txt](https://github.com/alexdobin/STAR/files/12596322/Barcodes.txt)
[counts.final.txt](https://github.com/alexdobin/STAR/files/12596324/counts.final.txt)
[Features.txt](https://github.com/alexdobin/STAR/files/12596325/Features.txt)
[Summary.csv](https://github.com/alexdobin/STAR/files/12596326/Summary.csv)

**Comment by alexdobin** [comment]
Hi Marta,

What STARsolo options are you using?
I think you are using an option that does not use barcode passlist (e.g. SmartSeq), so Barcode.stats does not get filled, and  the proportion of reads with valid barcodes =1=100%.

**Comment by MartaBenegas** [comment]
Hi Alex,

you're right, I wasn't providing the cell barcodes whitelist. However, I imagined that the same or similar statistics could be obtained with the cell barcodes calculated from the data itself. Wouldn't that be possible?

**Comment by alexdobin** [comment]
Hi Marta,

Without a passlist, all barcodes are allowed so that all stats will be zero except the total number of barcodes.
