### ISSUE TITLE
Can STAR align specific region?

### ISSUE THREAD

**Issue by bucongfan** [alexdobin/STAR#1949]
I have 100 SNP in the CDS region and I only want to know the alignment situation of these SNP-involved genes. 

Can I use some parameters to refine the alignment region to speed up this alignment process or simplify the size of the Index?

Thanks!

**Comment by alexdobin** [comment]
Hi @bucongfan 

No, this is not possible.
Since most of your reads will probably map to other regions, using a small reference will reduce the mapping speed.

**Comment by bucongfan** [comment]
Thanks @alexdobin !
