### ISSUE TITLE
STAR compilation error 

### ISSUE THREAD

**Issue by MilletA** [alexdobin/STAR#1952]
Hi,
I am getting an error message when trying to compile STAR on my Linux VirtualBox machine 

/software/STAR/source$ make STAR
xxd -i parametersDefault > parametersDefault.xxd
/bin/sh: 1: xxd: not found
Makefile:138: Depend.list: No such file or directory
make: *** [Makefile:152: parametersDefault.xxd] Error 127

or if re-make STAR

'rm' -f STAR.o Parameters.o
g++ -c   -O3 -std=c++11 -fopenmp -D'COMPILATION_TIME_PLACE="Tue Sep 19 03:36:38 PM PDT 2023 :/home/antoine/software/STAR/source"' -D'GIT_BRANCH_COMMIT_DIFF="On branch master ; commit 79affaae7d5e70221287762eab4e40679fad87f7 ; diff files: source/Makefile "' -pipe -Wall -Wextra STAR.cpp
STAR.cpp: In function ‘void usage(int)’:
STAR.cpp:52:45: error: ‘parametersDefault’ was not declared in this scope
   52 |         cout.write(reinterpret_cast<char *>(parametersDefault),
      |                                             ^~~~~~~~~~~~~~~~~
STAR.cpp:53:20: error: ‘parametersDefault_len’ was not declared in this scope
   53 |                    parametersDefault_len);
      |                    ^~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:100: STAR.o] Error 1

Can anybody help me with this problem?

Thanks,
Antoine

**Comment by alexdobin** [comment]
Hi Antoine,

you need to install xxd, e.g. https://www.codingninjas.com/studio/library/xxd-linux

**Comment by MilletA** [comment]
Hi Alex,

It works perfectly, thanks a lot :))
