### ISSUE TITLE
Reads unmapped too short 98% 

### ISSUE THREAD

**Issue by Sghnaway** [alexdobin/STAR#1956]
Hi everyone,

I am relatively new to bioinformatics, but i have attended a RNA-seq training course a few months back and i thought i could analyze the data myself. I am working on a cluster and the STAR version i am using is 2.7.10a.

I have received the fastaq files from the sequencing company and performed a -cutadapt to trim the illumina adaptors and -trimgalore to normalize the number of reads of the different replicates. I am attaching the multiqc file after the trimming and normalization. 

I have generated the genome index with the following code and using a gtf file and primary assembly.fa from ensamble: 
#!/bin/bash

# Define the paths to your genome and annotation files
genomeDir="/home/USSR/dr573/R/x86_64-pc-linux-gnu-library/dr573/genome_index/"
genomeFastaFiles="/home/USSR/dr573/R/x86_64-pc-linux-gnu-library/dr573/genome_index/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa"
annotationsGTF="/home/USSR/dr573/R/x86_64-pc-linux-gnu-library/dr573/genome_index/Homo_sapiens.GRCh38.110.gtf"

# Define the number of threads to use
numThreads=24  # Set the number of threads as needed

# Calculate sjdbOverhang based on ReadLength-1 (replace ReadLength with the actual read length)
readLength=150  # Replace with your actual read length
sjdbOverhang=$((readLength - 1))

# Path to STAR executable
STAR_exe="/usr/local/STAR-2.7.10a/bin/Linux_x86_64_static/STAR"  # Update with your STAR executable path

# Run STAR to generate the genome index
${STAR_exe} \
--runThreadN ${numThreads} \
--runMode genomeGenerate \
--genomeDir ${genomeDir} \
--genomeFastaFiles ${genomeFastaFiles} \
--sjdbGTFfile ${annotationsGTF} \
--sjdbOverhang ${sjdbOverhang}

I know from the multiqc that most my reads are 150bp long. 
Then this is the code for the alignment: 
#!/bin/bash

# Set directories (full paths)
fastq_dir="/home/USSR/dr573/R/x86_64-pc-linux-gnu-library/dr573/normalized_trimmed"
aligned_dir="/home/USSR/dr573/R/x86_64-pc-linux-gnu-library/dr573/normalized_trimmed_aligned"
featurecounts_dir="/home/USSR/dr573/R/x86_64-pc-linux-gnu-library/dr573/normalized_trimmed_featurecounts"

# Path to STAR executable
STAR_exe="/usr/local/STAR-2.7.10a/bin/Linux_x86_64_static/STAR"

# Loop over all the samples listed in samplenames.txt
while IFS= read -r p; do
echo "Processing sample: ${p}"

# Align reads using STAR and create output directories
${STAR_exe} \
--runThreadN 15 \
--genomeDir /home/USSR/dr573/R/x86_64-pc-linux-gnu-library/dr573/genome_index/ \
--readFilesCommand gunzip -c \
--readFilesIn ${fastq_dir}/${p}_R1.fastq.gz ${fastq_dir}/${p}_R2.fastq.gz \
--outSAMtype BAM SortedByCoordinate \
--outTmpDir ${aligned_dir}/${p}_outTmpDir \
--runMode alignReads \
--outFileNamePrefix ${aligned_dir}/${p}_ \
--limitOutSJcollapsed 1000000 \
--sjdbOverhang 149 \ # Adjusted for read length of up to 150
--outFilterMatchNmin 50 # allow output of short alignments

# Perform read counting using featureCounts
featureCounts -p -t exon -g gene_id \
-a /R/x86_64-pc-linux-gnu-library/dr573/genome_index/Homo_sapiens.GRCh38.110.gtf \
-o "${featurecounts_dir}/${p}" "${aligned_dir}/${p}_Aligned.sortedByCoord.out.bam"
done < samplenames.txt

I have tried this (https://github.com/alexdobin/STAR/issues/169) although to me it looks like i'm not mapping much at all. 
The alignment can finish correctly but the bam file size is about 30-40mb which i consider definitely too small. 

This is the log from star on one of the samples: 
                                 Started job on |	Sep 21 15:30:09
                             Started mapping on |	Sep 21 15:30:25
                                    Finished on |	Sep 21 15:34:06
       Mapping speed, Million of reads per hour |	356.64

                          Number of input reads |	21893840
                      Average input read length |	287
                                    UNIQUE READS:
                   Uniquely mapped reads number |	222613
                        Uniquely mapped reads % |	1.02%
                          Average mapped length |	179.46
                       Number of splices: Total |	125022
            Number of splices: Annotated (sjdb) |	124033
                       Number of splices: GT/AG |	123592
                       Number of splices: GC/AG |	1135
                       Number of splices: AT/AC |	86
               Number of splices: Non-canonical |	209
                      Mismatch rate per base, % |	0.92%
                         Deletion rate per base |	0.01%
                        Deletion average length |	1.65
                        Insertion rate per base |	0.00%
                       Insertion average length |	1.47
                             MULTI-MAPPING READS:
        Number of reads mapped to multiple loci |	17699
             % of reads mapped to multiple loci |	0.08%
        Number of reads mapped to too many loci |	2163
             % of reads mapped to too many loci |	0.01%
                                  UNMAPPED READS:
  Number of reads unmapped: too many mismatches |	0
       % of reads unmapped: too many mismatches |	0.00%
            Number of reads unmapped: too short |	21644166
                 % of reads unmapped: too short |	98.86%
                Number of reads unmapped: other |	7199
                     % of reads unmapped: other |	0.03%
                                  CHIMERIC READS:
                       Number of chimeric reads |	0
                            % of chimeric reads |	0.00%
[MultiQC Report.pdf](https://github.com/alexdobin/STAR/files/12714692/MultiQC.Report.pdf)

Could anyone please try to help me out? :D 
Many thanks in advance!!

**Comment by alexdobin** [comment]
Hi @Sghnaway 

1% is a very low mapping rate. One possibility is that trimming did not preserve the pairs in read1/2 files. You can check that by mapping raw (untrimmed) reads.

**Comment by Sghnaway** [comment]
Hi @alexdobin

Many thanks, I think you solved my issue! 
I tried to map the raw data and it resulted in over 80% of mapped reads.
