### ISSUE TITLE
Reads assigned to intergenic regions after mapping paired-end reads with cDNA on Read 1 

### ISSUE THREAD

**Issue by SofiaDrobysheva** [alexdobin/STAR#1998]
First of all, thank you for a great tool. 

Second, I will describe an issue I am currently having. I have paired-end fastq files which have the following properties:

1. R1 has UMI (12nt) and CB (10nt)
2. R1 also has cDNA
3. R1 structure is approximately: umi-cb-polyT-cDNA
4. R1 is 150 nt long
5. When looking at MultiQC reports I see that good quality cDNA on R1 starts from base 50 (hence I will be clipping the first 50 nt from the beginning of R1)
6. R2 is also 150 nt long with only cDNA

My goal is to map the above described fastqs in two ways (here referred to as condition 1 and condition 2):

Condition 1 - mapping only cDNA R2 and ignoring cDNA on R1

Condition 2 - mapping cDNA from R2 and R1 

My mapping command for condition 1:

```
STAR --genomeDir human_GRCh38_Ensembl \
        --readFilesIn L003_R2.fastq.gz,L004_R2.fastq.gz L003_R1.fastq.gz,L004_R1.fastq.gz \
        --readFilesCommand zcat \
        --soloType CB_UMI_Simple \
        --soloCBstart 13 \
        --soloCBlen 10 \
        --soloUMIstart 1 \
        --soloUMIlen 12 \
        --soloUMIdedup 1MM_All \
        --soloCBwhitelist barcodes.txt \
        --soloStrand Forward \
        --soloFeatures Gene GeneFull_Ex50pAS Velocyto \
        --soloMultiMappers Unique EM \
        --soloUMIfiltering - \
        --soloCellFilter CellRanger2.2 3000 0.99 10 \
        --soloCellReadStats Standard \
        --outSAMtype BAM SortedByCoordinate \
        --outSAMunmapped Within \
        --outSAMattributes NH HI nM AS CB UB GX GN
```

My mapping command for condition 2:

```
STAR --genomeDir human_GRCh38_Ensembl \
        --soloBarcodeMate 1 \
        --readFilesIn L003_R1.fastq.gz,L004_R1.fastq.gz L003_R2.fastq.gz,L004_R2.fastq.gz \
        --clip5pNbases 50 0 \
        --readFilesCommand zcat \
        --soloType CB_UMI_Simple \
        --soloCBstart 13 \
        --soloCBlen 10 \
        --soloUMIstart 1 \
        --soloUMIlen 12 \
        --soloUMIdedup 1MM_All \
        --soloCBwhitelist barcodes.txt \
        --soloStrand Forward \
        --soloFeatures Gene GeneFull_Ex50pAS Velocyto \
        --soloMultiMappers Unique EM \
        --soloUMIfiltering - \
        --soloCellFilter CellRanger2.2 3000 0.99 10 \
        --soloCellReadStats Standard \
        --outSAMtype BAM SortedByCoordinate \
        --outSAMunmapped Within \
        --outSAMattributes NH HI nM AS CB UB GX GN
```

Summary.csv output for condition 1:

Number of Reads,15356561
Reads With Valid Barcodes,0.789976
Sequencing Saturation,0.763592
Q30 Bases in CB+UMI,0.966645
Q30 Bases in RNA read,0.923424
Reads Mapped to Genome: Unique+Multiple,0.962322
Reads Mapped to Genome: Unique,0.916816
Reads Mapped to Gene: Unique+Multiple Gene,0.114307
Reads Mapped to Gene: Unique Gene,0.113482
Estimated Number of Cells,275
Unique Reads in Cells Mapped to Gene,1704128
Fraction of Unique Reads in Cells,0.977868
Mean Reads per Cell,6196
Median Reads per Cell,5087
UMIs in Cells,399296
Mean UMI per Cell,1451
Median UMI per Cell,1163
Mean Gene per Cell,741
Median Gene per Cell,657
Total Gene Detected,19181

Summary.csv output for condition 2:

Number of Reads,15356561
Reads With Valid Barcodes,0.789976
Sequencing Saturation,0.682756
Q30 Bases in CB+UMI,0.966645
Q30 Bases in RNA read,0.911064
Reads Mapped to Genome: Unique+Multiple,0.74289
Reads Mapped to Genome: Unique,0.714932
Reads Mapped to Gene: Unique+Multiple Gene,0.00886357
Reads Mapped to Gene: Unique Gene,0.00880848
Estimated Number of Cells,356
Unique Reads in Cells Mapped to Gene,134811
Fraction of Unique Reads in Cells,0.996622
Mean Reads per Cell,378
Median Reads per Cell,183
UMIs in Cells,42741
Mean UMI per Cell,120
Median UMI per Cell,52
Mean Gene per Cell,73
Median Gene per Cell,42
Total Gene Detected,12412

I use 2.7.10a version of STAR

From Summary.csv for condition 2 ( = mapping R1 and R2 cDNA) I see that “_Reads Mapped to Gene: Unique+Multiple Gene_” and “_Reads Mapped to Gene: Unique Gene_” are very-very low. Does it mean that my reads are aligned to intergenic regions? Also, I am confused why reads are no longer assigned to genes after I map with cDNA from R1.

Hence my question is whether I am making a mistake in my mapping command, or if something is wrong with my reads? 

I would very much appreciate any advice on how to troubleshoot and how to understand what happened! 

Thank you in advance! 

//Sofia

**Comment by alexdobin** [comment]
Hi Sofia,

Let's first look at condition 1, where the number of genic reads is quite low:
`Reads Mapped to Gene: Unique+Multiple Gene,0.114307`
The first thing to check is the same number in the `GeneFull_Ex50pAS/Summary.csv` file to see if more reads are mapping to introns.
Another thing to try is to run with a different strand configuration: `--soloStrand Reverse`.

**Comment by SofiaDrobysheva** [comment]
Hi Alexander, 

Thank you for your reply!

You are right, the `Reads Mapped to Gene: Unique+Multiple Gene,0.114307` is indeed quite low. After looking into the data I think the reason for the low Reads Mapped to Gene value is due to the low quality of the data that I used in this example.

However, I am still confused that is once I include the cDNA on Read 1, the number of Reads Mapped to Gene drops even further, from `Reads Mapped to Gene: Unique+Multiple Gene,0.114307` to `Reads Mapped to Gene: Unique+Multiple Gene,0.00886357`. 

Should it be expected to get a lower _Reads Mapped to Gene_ value (having more reads mapping to introns or not mapping at all) once reads are mapped as paired-end?

Thank you in advance for any input!

**Comment by alexdobin** [comment]
Hi Sofia,

Since the mapping rate of one mate is already pretty low, the probability that both mates map will be even lower.
Another possibility is that the mates overlap improperly after 1st mate trimming. You can try to resolve by setting `--alignEndsProtrude` to 10 or 20 or 50, to see if it helps with mappability.

**Comment by SofiaDrobysheva** [comment]
Hi Alexander, 

Thank you! I will try it.
