### ISSUE TITLE
Segfault with a particular read agains small genome

### ISSUE THREAD

**Issue by tdido** [alexdobin/STAR#20]
Up to 2.4.0j I was suffering from issue #17. Now I'm able to build my genome, but I've identified a single particular read that causes a segfault when aligning. Test data here: https://gist.github.com/tdido/55c94c003c21b4f3620d. Run parameters are as follows:

    STAR --runMode genomeGenerate --genomeDir genome/ --genomeFastaFiles genome.fasta
    STAR --genomeDir genome/ --readFilesIn test_single_fail.fastq

Additionally, if you change one of the first 'A's in the poly-A stretch of the read to any other nucleotide, the alignment completes with no problems.

**Comment by alexdobin** [comment]
Hi,
this is an old issue with small genomes in STAR, please see the following post:
https://groups.google.com/forum/#!msg/rna-star/vNB4_I1FU2k/RcWqPRrXxj4J
If you use --genomeSAindexNbases 5 at the genome generation step, the error at the mapping stage should disappear.

Cheers
Alex

**Comment by tdido** [comment]
Ah, I see. Thanks for the reference. Is the mailing list the best place to try and track open bugs, or do you use some other tracker?
