### ISSUE TITLE
memory issue with some samples 

### ISSUE THREAD

**Issue by patidarr** [alexdobin/STAR#200]
Hi,

I am running out of memory for few of my samples even when I gave >500GB ram. 
here is my command line:
`#!/bin/sh
set -eo pipefail
MEM=`echo "${SLURM_MEM_PER_NODE} / 1024 "|bc`
LOCAL="/lscratch/${SLURM_JOBID}/"
THREADS=${SLURM_CPUS_ON_NODE}

module load STAR/2.4.0d
cd ${LOCAL}/
# run 1st pass

STAR --outTmpDir STEP1          --genomeDir /data/Clinomics/Ref/khanlab/Index/STAR_hg19_index           --readFilesIn /data/khanlab/projects/DATA/Sample_TTC516seq_T_D26GWACXX/Sample_TTC516seq_T_D26GWACXX_R1.fastq.gz /data/khanlab/projects/DATA/Sample_TTC516seq_T_D26GWACXX/Sample_TTC516seq_T_D26GWACXX_R2.fastq.gz              --readFilesCommand zcat         --outSAMtype BAM SortedByCoordinate             --outFileNamePrefix TTC516seq_T_D26GWACXX     --runThreadN ${THREADS}          --outFilterMismatchNmax 2
echo "Finished Step 1"
# make splice junctions database file out of SJ.out.tab, filter out non-canonical junctions

mkdir GenomeForPass2
awk -f /data/Clinomics/Tools/ngs_pipeline-dev/scripts/SJDB.awk TTC516seq_T_D26GWACXXSJ.out.tab > GenomeForPass2/TTC516seq_T_D26GWACXX.out.tab.Pass1.sjdb
echo "Finished Step 2"
# generate genome with junctions from the 1st pass

STAR --outTmpDir STEP2          --genomeDir GenomeForPass2              --runMode genomeGenerate                --genomeSAindexNbases 8         --genomeFastaFiles /data/Clinomics/Ref/khanlab/ucsc.hg19.fasta          --sjdbFileChrStartEnd GenomeForPass2/TTC516seq_T_D26GWACXX.out.tab.Pass1.sjdb          --sjdbOverhang 100              --runThreadN ${THREADS}
echo "Finished Step 3"
# run 2nd pass with the new genome

STAR --outTmpDir STEP3          --genomeDir GenomeForPass2              --runThreadN ${THREADS}         --outSAMattributes All          --readFilesIn /data/khanlab/projects/DATA/Sample_TTC516seq_T_D26GWACXX/Sample_TTC516seq_T_D26GWACXX_R1.fastq.gz /data/khanlab/projects/DATA/Sample_TTC516seq_T_D26GWACXX/Sample_TTC516seq_T_D26GWACXX_R2.fastq.gz              --outSAMtype BAM SortedByCoordinate             --sjdbGTFfile /data/Clinomics/Ref/khanlab/GTF/06302016_refseq.gtf              --readFilesCommand zcat         --outFileNamePrefix TTC516seq_T_D26GWACXX_ucsc
mv -f TTC516seq_T_D26GWACXX_ucscAligned.sortedByCoord.out.bam /data/khanlab/projects/processed_DATA//TTC516/20130600/TTC516seq_T_D26GWACXX/TTC516seq_T_D26GWACXX.star_UCSC.bam
mv -f TTC516seq_T_D26GWACXX_ucscSJ.out.tab /data/khanlab/projects/processed_DATA//TTC516/20130600/TTC516seq_T_D26GWACXX/TTC516seq_T_D26GWACXX_ucsc.SJ.out.tab
echo "Finished Step 4"
`
and STDOUT:
`
[+] Loading STAR 2.4.0d
Oct 18 23:39:24 ..... Started STAR run
Oct 18 23:44:57 ..... Started mapping
Oct 19 00:02:46 ..... Started sorting BAM
Max memory needed for sorting = 25708200070
`
I ran this command with --mem=600G --cpus-per-task=20

I got the same code working on >1000 samples with 60G & 32 cpus but there are ~10 samples I am always failing whatever mem/cpus I provide. 

Any suggestions?

Regards,
Rajesh

**Comment by alexdobin** [comment]
Hi Rajesh,

please send me the Log.out file for one of the failed run.
It seems that the problem occurs at the BAM sorting stage.
One option would be to switch to a newer version of STAR (at least 2.4.0k) which handles the sorting better.

Cheers
Alex

**Comment by patidarr** [comment]
Hi Alex,

After using v 2.5.2a I finished up to "generate genome with junctions from the 1st pass" but got error in following code.
STAR --outTmpDir STEP3          --genomeDir GenomeForPass2              --runThreadN ${THREADS}         --outSAMattributes All          --readFilesIn /data/khanlab/projects/DATA/Sample_TTC516seq_T_D26GWACXX/Sample_TTC516seq_T_D26GWACXX_R1.fastq.gz /data/khanlab/projects/DATA/Sample_TTC516seq_T_D26GWACXX/Sample_TTC516seq_T_D26GWACXX_R2.fastq.gz              --outSAMtype BAM SortedByCoordinate             --sjdbGTFfile /data/Clinomics/Ref/khanlab/GTF/06302016_refseq.gtf              --readFilesCommand zcat         --outFileNamePrefix TTC516seq_T_D26GWACXX_ucsc
STDOUT

Oct 19 16:13:13 ..... started STAR run
Oct 19 16:13:13 ..... loading genome
Oct 19 16:13:55 ..... processing annotations GTF

STDERR 
Fatal INPUT FILE error, no valid exon lines in the GTF file: /data/Clinomics/Ref/khanlab/GTF/06302016_refseq.gtf
Solution: check the formatting of the GTF file. Most likely cause is the difference in chromosome naming between GTF and FASTA file.


and I think there is no Log.out file.


I have been using the gtf file for almost everything, and it worked perfectly with the older version.

Thanks,
Rajesh

**Comment by alexdobin** [comment]
Hi Rajesh,
please send me a few lines from the GTF file, and a few lines from the chrName.txt file from the genome directory. 
Thanks!
Alex

**Comment by patidarr** [comment]
Hi Alex,

Here it is:
`
[patidarr@login01 hg19]$ head Index/STAR_hg19_index/chrName.txt
chrM
chr1
chr2
chr3

[patidarr@login01 hg19]$ head GTF/06302016_refseq.gtf
1       refGene CDS     10002739        10002793        .       -       0       gene_id "LZIC"; transcript_id "NM_001316974"; exon_number "7"; exon_id "NM_001316974.7"; gene_name "LZIC";
1       refGene CDS     100111874       100111918       .       +       0       gene_id "PALMD"; transcript_id "NM_017734"; exon_number "1"; exon_id "NM_017734.1"; gene_name "PALMD";
1       refGene CDS     100127875       100127955       .       +       0       gene_id "PALMD"; transcript_id "NM_017734"; exon_number "2"; exon_id "NM_017734.2"; gene_name "PALMD";
1       refGene CDS     100133198       100133322       .       +       0       gene_id "PALMD"; transcript_id "NM_017734"; exon_number "3"; exon_id "NM_017734.3"; gene_name "PALMD";
1       refGene CDS     100152232       100152346       .       +       1       gene_id "PALMD"; transcript_id "NM_017734"; exon_number "4"; exon_id "NM_017734.4"; gene_name "PALMD";
`
These two files are working well with any of the following versions.
STAR/2.4.0d       STAR/2.4.0j       STAR/2.4.0k       STAR/2.4.1d

its just 2.5.2a and above giving error.

Thanks,
Rajesh

**Comment by alexdobin** [comment]
Hi Rajesh,

I think STAR made a correct guess - "Most likely cause is the difference in chromosome naming between GTF and FASTA file." In the FASTA, you chromosomes are named as chr1,chr2,chr3, ... while  in the gtf they are names 1,2,3, ... (1st field in the GTF). The older versions of STAR silently ignored this problem.

Also. does the GTF file has any lines with "exon" in the 3rd field - the lines you sent me all contain CDS. STAR only uses "exon" lines. You may need to do some conversions of your gtf file.

Cheers
Alex

**Comment by patidarr** [comment]
Hi Alex,

I don't have exon in the GTF file and I have been using this same pair of
STAR index and GTF file for >3000 samples on older version and it worked,
would it be possible to accommodate this in new version?

Regards,
Rajesh

Patidar

**Comment by alexdobin** [comment]
Hi Rajesh,

if GTF does not have any exon lines, STAR - in the old or new version - does not extract or use any information from the GTF file, so you can simply omit this file for the runs with the new version - the results will not change.

Cheers
Alex
