### ISSUE TITLE
Multimapping of a single read in terms of both correct and mismatched alignments.

### ISSUE THREAD

**Issue by Bbbbqsh** [alexdobin/STAR#2001]
Dear Alex, 

When using STAR for alignment, I encountered an issue. The following is a specific description of the issue (please forgive my poor English)

I have a read from tRNA-Leu located on chr16. The sequence of the read has a 1nt mismatch at the 3' end compared to the tRNA sequence. I am attempting to map the read to the tRNA. The sequences of read and tRNA are as follows:
```
tRNA-Leu      GTGAGACCTTCTGAGGTG      
read	      GTGAGACCTTCTGAGGTA
```

After running STAR, I observed that this read is mapped to a segment of identical sequence on chr1. STAR has classified it as a unique alignment. Due to the short length of this read (18nt), I am unable to determine how many same sequences exist in the hg38 genome using BLAT.

So, I attempted to adjust parameters such as `--outFilterMultimapScoreRange 2/4/10` in order to map this read to my target tRNA. But none proved effective.

According to my understanding, when a read is uniquely mapped to a certain sequence, it seems that STAR cannot output cases where this read could mapped to other positions in the presence of mismatches. So, for this situation, how should I configure STAR's parameters to make it output the alignment results to tRNA, even if the read has a completely identical sequence on chr1? Or is STAR unable to handle this scenario?

Thanks,
Gan

**Comment by alexdobin** [comment]
Hi Gan,

finding all mapping loci with mismatches is not guaranteed, especially with short sequences.
You can try to increase sensitivity with something like --seedSearchStartLmax 10 --winAnchorMultimapNmax 200

**Comment by Bbbbqsh** [comment]
Hi Alex,

Thank you for your response and assistance. After posing this question, I separately extracted the tRNA genome from hg38 and mapped the reads to the tRNA genome. In the end, STAR mapped the read to tRNA 3'-trailer sequence successfully.

Upon reading your reply, I tried the parameters you mentioned. When using the entire hg38 genome as the reference, I still couldn't map the mentioned read to the trailer of tRNA. The alignment results stilled show only the unique mapping of the read to chr1. Nevertheless, your help still deepened my understanding of STAR's parameters. Please allow me to express my gratitude to you again.

Gan
