### ISSUE TITLE
STAR diploid transform for insertions

### ISSUE THREAD

**Issue by mparker2** [alexdobin/STAR#2002]
Dear @alexdobin ,

Thanks for maintaining STAR! I've been trying out the STAR diploid feature and it is very cool. The VCFs I am using are generated from whole genome alignments of two different Arabidopsis accessions, and contain some indels that are larger than the read length of the dataset I am mapping. I am wondering what happens to reads that map entirely to insertions during the coordinate transformation step? Are they reported as unmapped?

**Comment by alexdobin** [comment]
Hi @mparker2 

Such reads should be reported as unmapped, but I have never checked that - if you can select and check them, it would be great.

**Comment by mparker2** [comment]
Hi @alexdobin,

Thanks for the response. I found some alignments that just had 1 matching reference base (reported as `149S1M` or `1M149S`), but no 0-length alignments: <img width="988" alt="image" src="https://github.com/alexdobin/STAR/assets/15102604/91f331c0-69e5-4e58-8e2e-1fdc18b109db">
I identified some reads that should map to this 2365 bp indel. None of them were reported by STAR diploid (I didn't use `--outSAMunmapped Within`). I would have to realign the data and keep unmapped reads to see if they still have the ha tag. Would they also be ignored in quantification (the indel falls within an annotated gene)?

**Comment by alexdobin** [comment]
Hi Matt,

If you do not see the reads, it means they were classified as unmapped. They will not be counted in quantification.

**Comment by mparker2** [comment]
Circling back to this issue (sorry)... I've noted that some tags such as CB are retained for unmapped reads, which is very useful. It would be similarly useful to retain ha:i:2 tags for reads that map to the second haplotype but cannot be transformed into haplotype 1 coordinate space. Would this be possible to do?

**Comment by alexdobin** [comment]
To see the alignments of such reads, you can run mapping without the back transformation.
