### ISSUE TITLE
STAR solo vs cellranger

### ISSUE THREAD

**Issue by jmzvillarreal** [alexdobin/STAR#2026]
Hi,
I have used STAR solo to align snRNAseq from 10X v3 using the following command:

STAR --genomeDir /h_sapiens/gencode/v38/star/2.7.10a --sjdbGTFfile /gencode.v38.primary_assembly.annotation.gtf --readFilesCommand zcat --readFilesIn h_91_R2.fastq.gz h_91_R1._28bp.fastq.gz --soloType Droplet --soloFeatures Gene --soloCBwhitelist /10X_whitelists/3M-february-2018.txt --outFilterMultimapNmax 50 --winAnchorMultimapNmax 50 --alignEndsType EndToEnd --outReadsUnmapped Fastx --soloUMIlen 12  --outSAMtype BAM SortedByCoordinate --outSAMattributes NH HI nM AS CR UR CB UB GX GN sS sQ sM --runThreadN 16

For several samples.
When I compare the results with cellranger:

cellranger count --id=h_91 --sample=h_91 --expect-cells=15000 --fastqs=/h_91 --transcriptome=/refdata-cellranger-arc-GRCh38-2020-A-2.0.0

The result are quite different in terms of number of counts, features and % mitochondrial reads...
How is this possible ?
Many thanks in advance.
Best,
Jaime.

**Comment by alexdobin** [comment]
Hi Jaime,

these explain how to run STARsolo to generate most similar to CellRanger results:
https://github.com/alexdobin/STAR/blob/master/docs/STARsolo.md#how-to-make-starsolo-raw-gene-counts-almost-identical-to-cellrangers
https://github.com/alexdobin/STAR/blob/master/docs/STARsolo.md#emptydrop-like-filtering

CellRanger 7 counts intronic reads, to match this behavior, you also need `--soloFeatures GeneFull_Ex50pAS`.

**Comment by jmzvillarreal** [comment]
Thanks for the quick reply ! using --soloFeatures GeneFull_Ex50pAS looks much better, specially taling into considering I am working with single nuclei where unspliced RNAs are abundant...
Best,
Jaime.
