### ISSUE TITLE
STAR wrongly marks paired-end reads as multi-mapping if they were pretrimmed (headcrop)

### ISSUE THREAD

**Issue by ckuenne** [alexdobin/STAR#203]
Hi all,

I just wanted to also file this officially as a bug report. The whole story can be found here: https://groups.google.com/forum/#!topic/rna-star/vXN1-f15wIU

In short: if paired-end reads are trimmed from the head before mapping and the fragment size was so small that the mates overlap to a large degree, reads are erroneously marked as multi-mapping and not counted as a successful mate. If R1 and R2 are mapped separately, they are correctly recognized as uniquely mapping.

Best,
Carsten

**Comment by alexdobin** [comment]
[https://groups.google.com/d/msg/rna-star/vXN1-f15wIU/LmDqa1lBAgAJ](url)

**Comment by DarioS** [comment]
This is related to #205. Sometimes, they end up in the chimeric SAM files.
