### ISSUE TITLE
Conda installation: Plain option missing?

### ISSUE THREAD

**Issue by KuechlerO** [alexdobin/STAR#2030]
Hi,
and first huge thx for your on-going work on this tool :)

I had some problems installing the newest version of STAR (2.7.11a) via Conda.
After installing STAR via Conda in my environment, I tried to execute star with `STAR --version`, but there's no output at all.
So I checked:

`which STAR` -> yes the environment STAR is returned
`cat .snakemake/conda/my_environment/bin/STAR` -> A bash script is returned.

And I realized that maybe there in the bash script the last lines might be missing:
The script loops over a list of SIMD instruction sets from most to least powerful (avx2, avx, sse4.1, ssse3, sse3, sse2, sse) and calls `test_and_run` for each one. If it finds a match, it runs the corresponding program and exits.
If it doesn't find a match, it falls back to a "plain" version of the program.
However, the plain version is not referenced in the script.
The last line is just a comment
`# fallback to plain option`

I guess this is the source of my error: No SIMD instruction set is supported, hence nothing is executed and I don't get my STAR output.

**Comment by alexdobin** [comment]
Hi Oliver,

I am not maintaining conda scripts for STAR, so not sure how to fix it.
You can try to run pre-compiled STAR executables: https://github.com/alexdobin/STAR/releases/download/2.7.11a/STAR_2.7.11a.zip. 
The SIMD instructions are only used for `--clipAdapterType CellRanger4` option. It should run fine if you are not using this option.

**Comment by KuechlerO** [comment]
Yes exactly, that works. Thx!
