### ISSUE TITLE
the difference between the gene counting result of TranscriptomeSAM and GeneCounts mode?

### ISSUE THREAD

**Issue by sheep-liu** [alexdobin/STAR#2032]
Hello,

I have been using STAR in the past for mapping and counting when I do bulk RNAseq analysis [gene level]. An example code is as follows:

```bash
STAR --runMode alignReads \
	--runThreadN 3 \
	--genomeDir ${reference} \
	--readFilesIn ${input_R1} ${input_R2} \
	--readFilesCommand zcat \
	--sjdbGTFfile ${gtf} \
	--outFileNamePrefix ${output_prefix} \
	--outSAMtype BAM SortedByCoordinate \
	--quantMode GeneCounts \
	--alignSJoverhangMin 8 \
	--alignSJDBoverhangMin 1 \
	--alignIntronMin 20 \
	--alignIntronMax 1000000 \
	--alignMatesGapMax 1000000 \
	--outFilterType BySJout \
	--outFilterMultimapNmax 10 \
	--outFilterMismatchNmax 999 \
	--outFilterMismatchNoverReadLmax 0.04 1>${std} 2>${err}
```

Recently I performed a bulk RNAseq analysis at **tx** level, I write the code as follows:

```bash
STAR --runMode alignReads \
	--runThreadN 3 \
	--genomeDir ${reference} \
	--readFilesIn ${input_R1} ${input_R2} \
	--readFilesCommand zcat \
	--sjdbGTFfile ${gtf} \
	--outFileNamePrefix ${sample_label}. \
	--outSAMtype BAM SortedByCoordinate \
	--quantMode TranscriptomeSAM \
	--alignSJoverhangMin 8 \
	--alignSJDBoverhangMin 1 \
	--alignIntronMin 20 \
	--alignIntronMax 1000000 \
	--alignMatesGapMax 1000000 \
	--outFilterType BySJout \
	--outFilterMultimapNmax 10 \
	--outFilterMismatchNmax 999 \
	--outFilterMismatchNoverReadLmax 0.04 1>${std} 2>${err}

rsem-calculate-expression \
	-p 3 --no-bam-output --alignments --paired-end \
	${sample_label}.Aligned.toTranscriptome.out.bam \
	${rsem_ref} \
	${sample_label}.RSEM 1>${std} 2>${err}
```

I get counting results at both gene and tx level. However, I find the gene counting result from TranscriptomeSAM mode is not similar with gene counting result from GeneCounts mode. (I do the correlation analysis and find that using the same data, the results of gene counting and transcript counting are not highly correlated)

Note: I used the same data to run star with TranscriptomeSAM and GeneCounts mode.

I do not know what is the difference between the gene counting result of TranscriptomeSAM and GeneCounts mode. And I am not sure which one I can use to do downstream analysis.

**Comment by alexdobin** [comment]
Hi @sheep-liu 

What correlation coefficient are you getting?
The gene counts should be similar to a certain extent.
However, the algorithms are quite different: GeneCounts is a simple counting of reads overlapping genes, while (TranscriptomeSAM->) RSEM is a sophisticated MLE algorithm that probabilistically assigns reads to transcripts.
What strand options are you using?

**Comment by sheep-liu** [comment]
I apologize for not making myself clear. Let me make the situation clearer.

I get the GeneCounts by running below script:

```bash
STAR --runMode alignReads \
	--runThreadN 3 \
	--genomeDir ${reference} \
	--readFilesIn ${input_R1} ${input_R2} \
	--readFilesCommand zcat \
	--sjdbGTFfile ${gtf} \
	--outFileNamePrefix ${output_prefix} \
	--outSAMtype BAM SortedByCoordinate \
	--quantMode GeneCounts \
	--alignSJoverhangMin 8 \
	--alignSJDBoverhangMin 1 \
	--alignIntronMin 20 \
	--alignIntronMax 1000000 \
	--alignMatesGapMax 1000000 \
	--outFilterType BySJout \
	--outFilterMultimapNmax 10 \
	--outFilterMismatchNmax 999 \
	--outFilterMismatchNoverReadLmax 0.04 1>${std} 2>${err}
```

Then I get the gene count matrix by integrate the  `${output_prefix}ReadsPerGene.out.tab` for every sample (2nd column value).

As for RSEM, I get the GeneCounts by running below script:

```bash
STAR --runMode alignReads \
	--runThreadN 3 \
	--genomeDir ${reference} \
	--readFilesIn ${input_R1} ${input_R2} \
	--readFilesCommand zcat \
	--sjdbGTFfile ${gtf} \
	--outFileNamePrefix ${sample_label}. \
	--outSAMtype BAM SortedByCoordinate \
	--quantMode TranscriptomeSAM \
	--alignSJoverhangMin 8 \
	--alignSJDBoverhangMin 1 \
	--alignIntronMin 20 \
	--alignIntronMax 1000000 \
	--alignMatesGapMax 1000000 \
	--outFilterType BySJout \
	--outFilterMultimapNmax 10 \
	--outFilterMismatchNmax 999 \
	--outFilterMismatchNoverReadLmax 0.04 1>${std} 2>${err}

rsem-calculate-expression \
	-p 3 --no-bam-output --alignments --paired-end \
	${sample_label}.Aligned.toTranscriptome.out.bam \
	${rsem_ref} \
	${sample_label}.RSEM 1>${std} 2>${err}
```

Then I get the gene count matrix by integrate the  `${sample_label}.RSEM.genes.results` for every sample (5nd column value: `expected_count`).

Lastly, I perform the pearson correlation analysis after remove genes that are 0 in all samples. The correlation result is as below:

![test](https://github.com/alexdobin/STAR/assets/52167840/023c638d-b2b7-4207-a77b-00be2a606c73)

I have 2 groups samples, A and B. Where A has 4 technical replicates and B has 2 technical replicates. The samples with names ending in RSEM indicate the gene counting obtained with RSEM.

The result I expect is that the correlation should be highest for the same sample, obtained using different methods, and should cluster together when clustering.

I hope I have made myself clear, and if there is anything you are unclear about, I can explain it in more detail. Thanks a lot.

**Comment by alexdobin** [comment]
Hi @sheep-liu 

The correlations between RSEM and GeneCounts are pretty high (>0.96) and seem OK to me.
As I mentioned the algorithms are very different, and it's hard to expect correlations higher than that.
You have very high correlations between replicates (>0.98), so it's not surprising they cluster together.

**Comment by sheep-liu** [comment]
I understand it. Thanks for your patience in answering, and I am grateful for that. @alexdobin
