### ISSUE TITLE
STAR solo parameters for 150bp reads

### ISSUE THREAD

**Issue by markddesimone** [alexdobin/STAR#2035]
Hi Alex, I am trying to use STARsolo to process a pair of files downloaded from:
https://www.ebi.ac.uk/ena/browser/view/SRX14453941

the library construction protocol states:
> Sequencing libraries were constructed following 10x Genomics 3' v2 standard protocols. 3' Single-cell RNA-Seq

There are two files SRR18316210_1.fastq.gz and SRR18316210_2.fastq.gz

the first 4 lines of each are:
@SRR18316210.1 A00284:21:H33VTDSXX:3:1101:2193:1000/2
NGACTTTCAAAGGAAGTGCACCTCAGAAACAACTAGATCAGCTGGGTGAGTGCGTCCCTCTATTGACTGTCACTGGAATGACAGGATTAATCTTCGTGAGACCAGAGTCTCGCTCAGGCTCTGGAGACTGTGGGCTGGGTGGGGGGGGCG
+
and:
@SRR18316210.1 A00284:21:H33VTDSXX:3:1101:2193:1000/3
ACAACAAGCAAGCATGCAGCTTACTGCTTGAAAGGGTCTTGCCTCACCCAGGCTAGAGTGCAGTGGCCTTTGAAGCTTACTACAGCCTCAAACTTCTGGGCTCAAGTGATCCTCAGCCTCCCAGTGGTCTTTGTAGACTGCCTGATGGAGT
+
respectively.

I don't know how to determine the correct parameters for STARsolo to process the barcode and UMI for these files.

I have tried:
```sh
--soloBarcodeReadLength 0 --soloCBstart 11 --soloCBlen 16 --soloUMIstart 1 --soloUMIlen 10
```
STAR completes successfully but there are very few counts, the maximum read count is 5.

my full command is:
```sh
STAR --runMode alignReads --runThreadN 20 --genomeDir /media/mark/ssd2/downloaded-tools/10x/refdata-gex-GRCh38-2020-A/star_2.7.11a --sjdbGTFfile /media/mark/ssd2/downloaded-tools/10x/refdata-gex-GRCh38-2020-A/genes/genes.gtf --clipAdapterType CellRanger4 --outFilterScoreMin 30 --soloCBmatchWLtype 1MM_multi_Nbase_pseudocounts --soloUMIfiltering MultiGeneUMI_CR --soloUMIdedup 1MM_CR --outSAMtype BAM SortedByCoordinate --readFilesCommand zcat --soloType CB_UMI_Simple --bamRemoveDuplicatesType UniqueIdenticalNotMulti --outSAMattributes NH HI AS nM GX CB UB GN sM sQ --soloFeatures GeneFull --soloMultiMappers Rescue --soloCBwhitelist /media/mark/ssd2/downloaded-tools/10x/737K-august-2016.txt --readFilesIn /media/mark/seagate6/BloodAndImmune/SRX14453941/SRR18316210_2.fastq.gz /media/mark/seagate6/BloodAndImmune/SRX14453941/SRR18316210_1.fastq.gz --outFileNamePrefix /media/mark/seagate7/BloodAndImmune/results/SRX14453941/SRR18316210_ --outTmpDir /media/mark/ssd2/tempSTAR --soloBarcodeReadLength 0 --soloCBstart 11 --soloCBlen 16 --soloUMIstart 1 --soloUMIlen 10
	STAR version: 2.7.11a   compiled: 2023-08-15T11:38:34-04:00 :/home/dobin/data/STAR/STARcode/STAR.master/source
Jan 07 18:01:40 ..... started STAR run
Jan 07 18:01:40 ..... loading genome
Jan 07 18:01:58 ..... processing annotations GTF
Jan 07 18:02:13 ..... inserting junctions into the genome indices
Jan 07 18:03:19 ..... started mapping
Jan 07 18:33:05 ..... finished mapping
Jan 07 18:33:10 ..... started Solo counting
Jan 07 18:33:13 ..... finished Solo counting
Jan 07 18:33:13 ..... started sorting BAM
Jan 07 18:50:29 ..... finished successfully
```

Any help greatly appreciated.

thank you

**Comment by alexdobin** [comment]
Hi @markddesimone 

for 10X v2, the following parameters should work:
`--soloBarcodeReadLength 0 --soloCBstart 1 --soloCBlen 16 --soloUMIstart 17 --soloUMIlen 10`
You may also need to try different ordering of Read1 and Read2 in `--readFilesIn` since it's not clear which read is the cDNA read (should go first) and which is the barcode read (second).

**Comment by markddesimone** [comment]
Hi Alex, thank you! Indeed these parameters work as you suggested.
