### ISSUE TITLE
STAR index generation killed after "inserting junctions into the genome indices"

### ISSUE THREAD

**Issue by beckyreese** [alexdobin/STAR#2037]
I am having trouble generating an index with STAR. It always kills at "inserting junctions into the genome indices". I have 32GB of RAM and I tried limiting the RAM used, but that didn't seem to work. Are there other flags I can use before I resort to buying another stick of RAM?

STAR --runThreadN 12 --runMode genomeGenerate -genomeDir ./ --genomeFastaFiles Homo_sapiens.GRCh38.dna.primary_assembly.fa --sjdbGTFfile Homo_sapiens.GRCh38.110.gtf --sjdbOverhang 149 --limitGenomeGenerateRAM 28000000000

Log file below. Thank you!!

[Log.txt](https://github.com/alexdobin/STAR/files/13882779/Log.txt)

**Comment by alexdobin** [comment]
Hi @beckyreese 

32GB is right on the border of what's needed for this genome.
If you cannot get a machine with more RAM, you would need to use `--genomeSAsparseD 2`.

**Comment by beckyreese** [comment]
Cheers, that's what I ended up trying and it worked! Thanks!
