### ISSUE TITLE
Segmentation fault (core dumped) multiple fastq paired-end samples

### ISSUE THREAD

**Issue by deepbiomed9** [alexdobin/STAR#204]
[SampleALog.out.txt](https://github.com/alexdobin/STAR/files/560156/SampleALog.out.txt)

Hi,
I am using STAR-2.5.2b on virtualbox with 65 gb of RAM assigned and 28 CPUs/threads.
When I ran STAR with single paired-end sample, it worked like a charm, very quick compared to TopHat but when I am trying to run STAR with multiple samples, I got the core dumped error.

1) d9@d9-VirtualBox:/media/sf_John/star/CR004/test_together_,$ '/media/sf_John/star/STAR-2.5.2b/bin/Linux_x86_64/STAR'   --runThreadN 28 --sjdbOverhang 99 --genomeDir '/media/sf_John/star/genome_build'  --readFilesIn '/media/sf_John/star/CR004/samples/CR004_S24_L005_R1_001.fastq', '/media/sf_John/star/CR004/samples/CR004_S24_L005_R2_001.fastq' '/media/sf_John/star/CR004/samples/CR004_S24_L006_R1_001.fastq', '/media/sf_John/star/CR004/samples/CR004_S24_L006_R2_001.fastq'   --outFileNamePrefix SampleA  --chimSegmentMin 20  

**Segmentation fault (core dumped)**

also tried 

2) d9@d9-VirtualBox:/media/sf_John/star/CR004/test_together_,$ '/media/sf_John/star/STAR-2.5.2b/bin/Linux_x86_64/STAR'   --sjdbOverhang 99 --genomeDir '/media/sf_John/star/genome_build'  --readFilesIn /media/sf_John/star/CR004/samples/*.fastq  --outFileNamePrefix SampleA  --chimSegmentMin 20

**Segmentation fault (core dumped)**

same error. I know this has to do something with memory but don't know how to resolve it.

Please guide.
Thanks
D

**Comment by alexdobin** [comment]
[https://groups.google.com/d/msg/rna-star/fIDrBJ2X-Y0/QTYni6t_AwAJ](url)
