### ISSUE TITLE
STAR alignment either crashing or throwing a "segmentation fault (core dropped)" erro

### ISSUE THREAD

**Issue by beckyreese** [alexdobin/STAR#2042]
Hi again-

I initially posted about having issues generating an index for the human genome with 32GB of RAM (issue #[2037)](https://github.com/alexdobin/STAR/issues/2037). I was able to get past that by using `--genomeSAsparseD 2` as follows:

`STAR --runThreadN 12 --runMode genomeGenerate -genomeDir ./ --genomeFastaFiles Homo_sapiens.GRCh38.dna.primary_assembly.fa --sjdbGTFfile Homo_sapiens.GRCh38.110.gtf --sjdbOverhang 149 --limitGenomeGenerateRAM 28000000000 --genomeSAsparseD 2`

Now I am at the alignment stage, and I am running into a new issue that I'm wondering is also related to my RAM availability. Whenever I run the following code, my terminal either crashes out completely or throws the error "line 21: 312446 Segmentation fault (core dumped)"

`STAR --runThreadN 12 --genomeDir /media/rnaseq/GenomeDir --readFilesIn SRRxxxxxxxx_val_1.fq.gz SRRxxxxxxxxx_val_2.fq.gz --readFilesCommand gunzip -c --outTmpDir /media/rnaseq/star_tmp --quantMode GeneCounts --outFileNamePrefix SRRxxxxxxxxx_val_1.fq.gz --outSAMtype BAM SortedByCoordinate
`

I have tried removing the `--runThreadN` to default to 1 thread and still came up with the same issue. Searching around, it seems this issue _could_ be related to not having enough RAM. I have read through the manual, and I'm not seeing an option akin to `--genomeSAsparseD` for the alignment step. Is there anything I can do code/flag wise before looking to run this on another machine/obtaining more RAM? According to the log file, my genome is only ~3.2 GB so I wouldn't think that alone is taking up too much RAM...

[SRRxxxxxx_val_1.fq.gzLog.out.txt](https://github.com/alexdobin/STAR/files/13967308/SRRxxxxxx_val_1.fq.gzLog.out.txt)

**Comment by alexdobin** [comment]
Hi @beckyreese 

Seg-faults are typically not related to RAM overflow.

Please try to run without these parameters:
`--outTmpDir /media/rnaseq/star_tmp   --outSAMtype BAM   SortedByCoordinate      --quantMode GeneCounts   `
If this resolves the issue, you can try adding these parameters one by one to see which one causes the problem.
If not, I would recommend trying to map another dataset to see

**Comment by beckyreese** [comment]
Hey @alexdobin 

I tried removing those parameters and and I have tried mapping to data from two completely different datasets (one of which is from a dataset I have previously been able to map with STAR at my old institution), and I am still getting the same error. Could there be an issue with my indices? Any other suggestions you can think of?

**Comment by alexdobin** [comment]
Hi @beckyreese 

A few more suggestions:
1. Map unzipped fastq files without `--readFilesCommand gunzip -c` .
2. Generate an index for one chromosome and try to map to it (this will check if RAM may still be the issue).
3. If you are using dynamically compiled executable, try the static one (and vice versa).
4. Compile STAR executable from source/
5. Run it on a different machine

**Comment by beckyreese** [comment]
Hi @alexdobin,

Much to my surprise, solution 1 has worked! I was able to map the reads using the most basic parameters. I need to play around with whether I can successfully add in the other parameters, but I at least have a minimal solution to work with. Thank you so very much!!

**Comment by alexdobin** [comment]
Hi @beckyreese 

The issue most likely is that the partition you are using is non-Linux and does not support fifo files require for on-the-fly unzipping.
If you specify a Linux partition in `--outTmpDir`, it should work.

**Comment by beckyreese** [comment]
Hi @alexdobin -

That was exactly the problem. I was trying to run the code on an external hard drive, but when I set up `--outTmpDir` to be a local folder on the computer I was able to use `--readFilesCommand gunzip -c`. Now my mapping is substantially faster as well! Many thanks again for all your help!
