### ISSUE TITLE
Any way to increase penalty for a mismatch?

### ISSUE THREAD

**Issue by karlestira** [alexdobin/STAR#2078]
I use STAR for FUSION detect. But some times the fusion partner's sequence is similar to the next exon(in gtf file). Mapping to fusion partner lead to 0 mismatches, and mapping to next exon lead to 5 mismatches in 16bp(this is very low quality).

However STAR will map to next exon(15bp), then softclip remaining bases, and no chimeric alignment output, lead to fusion false negative.

![b8a432237696e9a8819eaca7f3754742](https://github.com/alexdobin/STAR/assets/46447763/dd81b6aa-fff0-4db3-8658-38723c61a1fc)

If I increase alignSJDBoverhangMin to 18bp, I will get a correct chimeric alignment. But alignSJDBoverhangMin=18 is too big, lead to a lot of chimeric alignment between adjacent exons. 

I think this can be avoid by increase the penalty for a mismatch. But STAR do not have a option to set it. Can I have a way to adjust it(e.g. change the code if it is written as a const value)?

**Comment by alexdobin** [comment]
You can adjust the total number of mismatches allowed per read `--outFilterMismatchNmax`, but there is no way to limit mismatches per fragment.

**Comment by karlestira** [comment]
Well, I try to change STAR's code, and get a perfect result.

extendAlign.cpp: 
line 42, 83: Score -= scoreMatch;  -->  Score += scoreMisMatch;

IncludeDefine.h:
line 72 added: #define scoreMisMatch -4
(use -4 is because bwa use -4 for mismatch penalty, I think -2 or -3 maybe better)

However, this value cannot be modified after compilation.
Can a new feature be added to adjust the mismatch penalty during the chain extension stage?

**Comment by karlestira** [comment]
I think this maybe hard to adjust, so I will close this issue.
