### ISSUE TITLE
Soft-clipping Occurs When a SNP is Present

### ISSUE THREAD

**Issue by DarioS** [alexdobin/STAR#208]
A test case is

    >R1
    CTTTGACCCTCGCTGGGAAGCTTGATCGCCGCCTGTTCTCGCCAATCTCTATGCCTTTGCACTGCCCATCCTTGTAGATTTAAGATGTGAGTAGTTGATG
    >R2
    CAGTCTCCAGGCACTGTGCCACTGTGTGCCTTGGAAGCACCTGGCTTCTGTGGTCACTGCACATCATAATGAAAAGCCTGCTTTTTCTTTCAGAACACCC

It is mapped to hg19. Because there's a SNP in read 1, it gets soft clipped, rather than split, even though the overhang is large enough. I used `--outFilterMismatchNoverReadLmax 0.1` so this shouldn't happen.

**Comment by alexdobin** [comment]
Hi Dario,

please send me the parameters STAR used and the SAM output for these two reads.

Cheers
Alex

**Comment by DarioS** [comment]
I forgot which file the reads were in so I created 2 FASTQs, each with one of the reads in it. This time I got no mapping at all.

                                  UNMAPPED READS:
       % of reads unmapped: too many mismatches |	0.00%
                 % of reads unmapped: too short |	100.00%

The contents of one file are

    $ cat tmp1.fastq 
    @700666F:126:C8768ANXX:1:1103:1178:2024 1:N:0:AGTCAA
    CTTTGACCCTCGCTGGGAAGCTTGATCGCCGCCTGTTCTCGCCAATCTCTATGCCTTTGCACTGCCCATCCTTGTAGATTTAAGATGTGAGTAGTTGATG
    +
    =<<0EGGGGGGGGGGGGGGGGGGGGGFGGGGGGGGGGGGGGGGGGGGG>F<E@FGGGFEG>FGEGDE/EDGBFCFGGGGCGGGCGBGGGGFDGGGGCBDB

and of the second file are

    $ cat tmp2.fastq 
    @700666F:126:C8768ANXX:1:1103:1178:2024 2:N:0:AGTCAA
    CAGTCTCCAGGCACTGTGCCACTGTGTGCCTTGGAAGCACCTGGCTTCTGTGGTCACTGCACATCATAATGAAAAGCCTGCTTTTTCTTTCAGAACACCC
    +
    =<<0EGGGGGGGGGGGGGGGGGGGGGFGGGGGGGGGGGGGGGGGGGGG>F<E@FGGGFEG>FGEGDE/EDGBFCFGGGGCGGGCGBGGGGFDGGGGCBDD

The command is

    ##### Final effective command line:
    STAR   --runThreadN 4   --genomeDir /verona/nobackup/biostat/indexes/STAR/hg19withGENCODE25/   --genomeLoad LoadAndKeep   --readFilesIn tmp1.fastq   tmp2.fastq      --limitBAMsortRAM 16000000000   --outFileNamePrefix TESTING   --outSAMtype BAM   SortedByCoordinate      --outFilterMultimapNmax 1   --outFilterMismatchNoverReadLmax 0.1   --alignIntronMax 1000000   --alignMatesGapMax 1000000   --alignEndsProtrude 25   ConcordantPair      --chimSegmentMin 20

**Comment by alexdobin** [comment]
Hi Dario,

I have blatted these reads, and BLAT cannot find a good alignment for the 1st one (see below).
How do you think these reads should be mapped?

Cheers
Alex

   ACTIONS      QUERY           SCORE START  END QSIZE IDENTITY CHRO STRAND  START    END      SPAN
---------------------------------------------------------------------------------------------------
browser details 1                 68     1    68   100 100.0%    18   +    5238634   5238701     68
browser details 1                 30    69   100   100  96.9%     1   +  109177795 109177826     32
browser details 1                 23    42    67   100  96.0%     4   -   45860435  45860461     27
browser details 1                 22    71    93   100 100.0%     4   -   28268889  28268913     25
browser details 2                100     1   100   100 100.0%     1   +  109177960 109178059    100
browser details 2                 21     5    27   100  95.7%     7   -    3146201   3146223     23
browser details 2                 21    39    59   100 100.0%     2   +   10344626  10344646     21

**Comment by alexdobin** [comment]
Hi Dario

If I map just the read 1, STAR can find this chimeric junction:
R1      0       chr18   5238634 3       68M32S  *       0       0       * *       NH:i:2  HI:i:1  AS:i:66 nM:i:0
R1      256     chr1    109177795       3       68S32M  *       0       0       * *       NH:i:2  HI:i:2  AS:i:29 nM:i:1

However, the 32b piece on chr1 maps to +strand, and read 2 also maps to +strand nearby on chr1 - so they cannot form a non-chimeric alignment. i.e. there should be another chimeric (non-linear) junction in the unsequenced portion of the fragment between two mates.

Cheers
Alex

**Comment by DarioS** [comment]
Thank you for helping me understand that the strand of the reads is the problem in this scenario.
