### ISSUE TITLE
Installation error on a Mac

### ISSUE THREAD

**Issue by theokirkland** [alexdobin/STAR#2080]
I am trying to install STAR on an M1 Mac running Sonama 14.3.1.  I have download the files with git and am in the sources folder when I try to compile the files the following errors occur

theoneal@MacBook-Pro ~/STAR/STAR/source $ make STARforMacStatic CXX=/usr/local/Cellar/gcc/12.1.0/bin/g++-12
date: illegal option -- -
usage: date [-jnRu] [-I[date|hours|minutes|seconds]] [-f input_fmt]
            [-r filename|seconds] [-v[+|-]val[y|m|w|d|H|M|S]]
            [[[[mm]dd]HH]MM[[cc]yy][.SS] | new_date] [+output_fmt]
Makefile:138: Depend.list: No such file or directory
make -C htslib lib-static
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o kfunc.o kfunc.c
kfunc.c:1:10: fatal error: 'math.h' file not found
#include <math.h>
         ^~~~~~~~
1 error generated.
make[1]: *** [kfunc.o] Error 1
make: *** [htslib/libhts.a] Error 2

Do you have any suggestions?

Thanks

Theo

**Comment by alexdobin** [comment]
Hi Theo,

It looks like the math.h library is missing.
You can also try to use the pre-compiled STAR Mac executable.

**Comment by theokirkland** [comment]
Thanks - found the executable.   That works great
