### ISSUE TITLE
STARsolo knee-like cell filtering

### ISSUE THREAD

**Issue by mkazanov** [alexdobin/STAR#2086]
Hi Alex,

According to the STARsolo documentation, there are two options for cell filtering: knee-like and EmptyDrop-like filtering. While the EmptyDrop method references Lun et al.'s paper, the knee-like approach is not described.

Could you please provide a reference for the knee-like method, if available, or offer a more detailed explanation?

Thank you in advance,
Marat

**Comment by alexdobin** [comment]
Hi Marat,

This is a very simplistic calculation that replicates the old versions (<=2.2) of CellRanger.
1). Calculate robust maximum of UMI counts: default 99 percentile in the expected number of cells (3000 by default).
2). The UMI cutoff for cell calling is robust maximum divided by default 10.

These three parameters can be changed, the default values are:
`--soloCellFilter CellRanger2.2 3000 0.99 10`

**Comment by mkazanov** [comment]
Thank you!
