### ISSUE TITLE
ReadsPerGene.out.tab column values clarification

### ISSUE THREAD

**Issue by mkazanov** [alexdobin/STAR#2099]
Hi Alex,

Do I understand correctly that the values in the 2nd column of ReadsPerGene.out.tab (counts for unstranded RNA-seq) should be larger than those in columns 3 or 4? I noticed a case where the value in column 3 is larger than in column 2. Is this not a bug?

**Comment by alexdobin** [comment]
Hi Marat,

It can happen for reads mapping to genes overlapping on opposite strands. Such reads will be counted for stranded column, but not counted (ambiguous) for unstranded column.

**Comment by mkazanov** [comment]
Thank you, Alex!
