### ISSUE TITLE
Executables are Outdated

### ISSUE THREAD

**Issue by DarioS** [alexdobin/STAR#21]
I downloaded the static version of 2.4.0j and I found some binaries in a folder, but they were from 2.3.1z. Also, could the output be nicer if STAR is run without any parameters ? Other applications print a list of parameters in this situation.

**Comment by alexdobin** [comment]
Hi Dario,

which binaries have you found outdated? I checked dynamic and static Linux ones with --version, and they both are fine. I cannot check Mac binary at the moment.

Cheers
Alex

**Comment by DarioS** [comment]
I can't reproduce it. I found the version number in the Log.out file to be 2.3.1z. I may have been looking an outdated file. Today, I tried again. I get the latest version number in the log file.
