### ISSUE TITLE
Resolved: "BUG: next index is smaller than previous, EXITING" Error During Genome Index Generation with STAR

### ISSUE THREAD

**Issue by YAMIR-1138** [alexdobin/STAR#2100]
Hello, Alexander and the STAR community,

I encountered a persistent issue while generating a genome index with STAR version 2.7.11b for the GRCh38 human genome, which was presenting the following error during the suffix array generation phase: 
Mar 27 17:01:04 ... finished generating suffix array
Mar 27 17:01:04 ... generating Suffix Array index

BUG: next index is smaller than previous, EXITING

Mar 27 17:02:20 ...... FATAL ERROR, exiting

Initial Setup and Troubleshooting Attempts:

System Environment: Linux with 64GB RAM and over 1TB of disk space.
STAR Command: Utilized --runThreadN 31 aiming to leverage the system's capabilities.
Reference Files: Used GCA_000001405.15_GRCh38_no_alt_analysis_set.fna and GCA_000001405.15_GRCh38_full_analysis_set.refseq_annotation.gtf.gz from NCBI.
To address the issue, I undertook several troubleshooting steps:

Verified ample disk space and checked the integrity of the input files.
Created a new Conda environment specifically for STAR to rule out any conflicts or issues with package versions.
Experimented with alternative genome FASTA files and annotation GTFs to ensure the problem wasn't file-specific.
Despite these efforts, the error persisted until I adjusted the thread count.

Resolution:
Reducing the thread count from 31 to 20 (--runThreadN 20) resolved the issue, allowing the genome index generation to complete successfully.

I'm reaching out for a couple of reasons:

To assist anyone who might face a similar challenge.
To seek insights into why a higher thread count triggered this error. Could there be an underlying issue with how STAR manages threads or allocates memory, especially in specific environments? 

Thank you so much for your dedication to the development and support of STAR!

Cheers,
Yam

**Comment by alexdobin** [comment]
Hi Yam,

I recommend using PRImary FASTA and GTF files from GENCODE.
https://www.gencodegenes.org/human/

**Comment by YAMIR-1138** [comment]
Great, that solved the problem. Thank you very much!
