### ISSUE TITLE
Troubles installing STAR

### ISSUE THREAD

**Issue by Tcvalenzuela** [alexdobin/STAR#211]
Hi to all

I download in our ubuntu server the git version ( git clone https://github.com/alexdobin/STAR.git). Then the instructions says: 

" cd STAR
 "Build STAR"
make STAR"

But there is no STAR to be make "make", then nevermind, I enter to source to the "make STAR", but then the instructions says "make manual" but there is no manual again, and I can not install it, please maybe I am too naive, but I could not get it done.

**Comment by alexdobin** [comment]
Hi @Tcvalenzuela 

please try the following:
$ cd source
$ make

This should generate STAR executable. You can also use pre-compiled executables from bin/ .

Cheers
Alex
