### ISSUE TITLE
terminate called after throwing an instance of 

### ISSUE THREAD

**Issue by akhilpampana** [alexdobin/STAR#212]
i cant able to build my index as i am using version 2.4.1 d , please help me out 
 i am keeping phooto of my script. please let me know thatnk you
![capture](https://cloud.githubusercontent.com/assets/19439352/20123257/e1a67cae-a5eb-11e6-9307-e92f26471a60.PNG)

**Comment by alexdobin** [comment]
Hi @akhilpampana 

first of all, can you switch to one of the 2.5 versions, preferrably the latest 2.5.2b?
Also, please send me the Log.out file of the failed run.

Cheers
Alex

**Comment by akhilpampana** [comment]
hey thank you i got my problem solved , i got indexing problem so i had done it again . could u tell me whioch reference file should i use for indexing ?? i had used ucsc hg 19 but while allignment its not giving output

**Comment by alexdobin** [comment]
Hi @akhilpampana 

I would recommend the GENCODE, they have both FASTA and GTF:
[ftp://ftp.sanger.ac.uk/pub/gencode/Gencode_human/release_25/GRCh38.primary_assembly.genome.fa.gz](url)
[ftp://ftp.sanger.ac.uk/pub/gencode/Gencode_human/release_25/gencode.v25.primary_assembly.annotation.gtf.gz](url)

**Comment by akhilpampana** [comment]
thank you
