### ISSUE TITLE
Killed at generating Suffix Array index (genomeGenerate)

### ISSUE THREAD

**Issue by esraaelmligy** [alexdobin/STAR#2120]
Hello, I am trying to build a genome index for GRCh38.p12 genome and everything is fine until it reaches the generating suffix array step at which it gets killed. I know that genome indexing takes a lot of memory but i have 32 GB ram and about 500 GB free disk storage and upon search in previous issues, those seem sufficient to generate human genome index so i want to know what is the problem exactly and how can i fix it.

	./STAR --runThreadN 15 --runMode genomeGenerate --genomeDir ~/Refs --genomeFastaFiles ~/GRCh38.p12.genome.fa --sjdbGTFfile ~/gencode.v28.annotation.gtf --sjdbOverhang 149
	
STAR version: 2.7.11b   compiled: 2024-04-22T14:32:38+02:00 :/home/esraa/STAR-2.7.11b/source
Apr 22 14:49:23 ..... started STAR run
!!!!! WARNING: Could not move Log.out file from ./Log.out into ~/Log.out. Will keep ./Log.out

Apr 22 14:49:23 ... starting to generate Genome files
Apr 22 14:50:11 ..... processing annotations GTF
Apr 22 14:50:37 ... starting to sort Suffix Array. This may take a long time...
Apr 22 14:50:47 ... sorting Suffix Array chunks and saving them to disk...
Apr 22 15:30:43 ... loading chunks from disk, packing SA...
Apr 22 15:36:57 ... finished generating suffix array
Apr 22 15:36:57 ... generating Suffix Array index
Killed

**Comment by sepasure** [comment]
Hello, I have the same problem, I am in _Sotin Safix Arechunks Andesa Ventemtodisk ..._ After that it was Killid. Is your problem solved?

**Comment by esraaelmligy** [comment]
@sepasure Yes i tried some tricks and they solved the problem as it is actually caused by insufficient memory/RAM issue. 

I added the option "--genomeSAsparseD 2" and you can specify the number you want, but consider it wisely as some people have mentioned that assigining more than 3 makes a little difference in the results, another thing is running STAR alone without any other open terminals or processes, and making sure that i have enough swap memory, best thing is to run it after you have just logged in to your device.

**Comment by sepasure** [comment]
@esraaelmligy Thanks for the answer, after I used this instruction, it worked! Have a nice day☀

**Comment by esraaelmligy** [comment]
Glad it worked!
