### ISSUE TITLE
Version and options?

### ISSUE THREAD

**Issue by juansearch** [alexdobin/STAR#213]
I am working on a server where STAR is already installed, and I am unable to update to the latest version. I have no idea what version is installed, and many of the command-line options in the current version are unavailable. How can I determine the installed version and available options?

**Comment by alexdobin** [comment]
Hi Juan,

to get the version information:
$ STAR --version

For newer versions, running STAR without any parameters will give the list of all options.
Alternatively, you can look the the parametersDefault file in the STAR source directory.

Cheers
Alex

**Comment by juansearch** [comment]
Hi Alex,
Thank you for responding. I was able to find the version in the log file.
Sincerely,
-
Juan L. Rodriguez-Flores, Ph.D.
Department of Genetic Medicine
Weill Cornell Medicine
OFFICE: 1305 York Ave, 13th floor, Room Y-1334, New York NY 10065
PHONE: (646) 962 5553
EMAIL: jur2014@med.cornell.edu<mailto:jur2014@med.cornell.edu>
WEB: http://vivo.med.cornell.edu/display/cwid-jur2014
