### ISSUE TITLE
regarding mappability

### ISSUE THREAD

**Issue by akhilpampana** [alexdobin/STAR#214]
why the alignment rate is very small eventhough data is very good? i got alignment rate of 0.97 %

**Comment by alexdobin** [comment]
Hi @akhilpampana 

this is likely due to a catastrophic error, such as file formatting problems.
How do you transform your fastq files before mapping?

Cheers
Alex

**Comment by akhilpampana** [comment]
I just used sra tools to convert the sra to fastq

**Comment by alexdobin** [comment]
fastq-dump by default does not split paired-end reads into two files, you need to use --split-spot --split-files .

**Comment by alexdobin** [comment]
yes - these are fastq-dump options that should generate read 1/2 files for PE data

**Comment by akhilpampana** [comment]
K thank you, will let you know of i have any doubts rhank yoi

**Comment by akhilpampana** [comment]
hey i tried as you mentioned, my alignment quality increased from 0.97 to 36 %
