### ISSUE TITLE
Assign unmapped read position to mate coordinate

### ISSUE THREAD

**Issue by mozack** [alexdobin/STAR#217]
Hello and thanks for your wonderful mapper.

In cases where only one end of a read pair maps, it would be useful to have the unmapped read assign the coordinates of its mapped mate.  This issue follows up on:

https://groups.google.com/forum/#!topic/rna-star/6c2cJ8H1owU

From 2.4.1 of the SAM Spec: http://samtools.github.io/hts-specs/SAMv1.pdf

1 For a unmapped paired-end or mate-pair read whose mate is mapped, the unmapped read should
have RNAME and POS identical to its mate.

Thanks!

**Comment by alexdobin** [comment]
Hi Lisle,

STAR is supposed to do it. e.g.:
D2FC08P1:235:C26F5ACXX:3:1208:15732:14572       89      chr22   31564992        255     101M    *       0       0
D2FC08P1:235:C26F5ACXX:3:1208:15732:14572       165     *       0       0       *       chr22   31564992        0

Are you using one of the latest versions? The earlier versions may have had this problem.

Cheers
Alex

**Comment by mozack** [comment]
I just tried again with 2.5.2b

Here is the command:

`$STAR \
        --runThreadN 8 \
        --genomeDir $REF \
        --readFilesIn $FQ1 $FQ2 \
        --outSAMunmapped Within \
        --twopassMode Basic \
        --outSAMtype BAM SortedByCoordinate \
        --alignIntronMin 101 \
        --outFilterScoreMinOverLread .45  --outFilterMatchNminOverLread .45 \
        --outStd BAM_SortedByCoordinate > star.bam 2> star.log
`

Here are columns 1-9 of the first 10 records that are unmapped with a mapped mate:

`samtools view -f 0x04 -F 0x08 star.bam | cut -f 1-9 | head
seq.347	165	*	0	0	*	chr6	34213194	0
seq.1236	165	*	0	0	*	chr19	49305888	0
seq.1451	165	*	0	0	*	chr2	234378525	0
seq.1755	133	*	0	0	*	chr11	11984654	0
seq.2863	133	*	0	0	*	chr11	62656177	0
seq.3309	133	*	0	0	*	chr6	34213048	0
seq.3810	101	*	0	0	*	chr8	17933088	0
seq.4105	69	*	0	0	*	chr16	88008736	0
seq.4204	133	*	0	0	*	chrX	10204650	0
seq.5055	69	*	0	0	*	chr8	17919837	0`


Am I missing something else?

**Comment by alexdobin** [comment]
Hi Lisle,

these lines look OK to me - these reads are not mapped, so their own coordinates are not set (fields 3,4,6), but they point to the mapped mates coordinates (fields 7,8).

Cheers
Alex

**Comment by mozack** [comment]
Yes, the mate info is set fine.  However, I was looking for fields 3 and 4 (i.e. RNAME and POS) to be set to the coordinates of the mate.  This appears to be the SAM spec definition and recent bwa versions do have this behavior.

**Comment by alexdobin** [comment]
Hi Lisle,

I have checked the latest SAM specifications (attached below), and it looks like they recommend setting RNAME to * and POS to 0 for unmapped reads, although it's also possible to set it to other values.
I think it's currently uncommon to set the coordinates for unmapped reads and may lead to confusion in the downstream processing.
On the other hand, it's not hard to re-set these fields to anything you like (e.g. copy fields 7,8 into 3,4) after mapping.

Cheers
Alex

3. RNAME: Reference sequence NAME of the alignment. If @SQ header lines are present, RNAME (if not
‘*’) must be present in one of the SQ-SN tag. An unmapped segment without coordinate has a ‘*’ at
this field. However, an unmapped segment may also have an ordinary coordinate such that it can be
placed at a desired position after sorting. If RNAME is ‘*’, no assumptions can be made about POS
and CIGAR.
4. POS: 1-based leftmost mapping POSition of the first matching base. The first base in a reference
sequence has coordinate 1. POS is set as 0 for an unmapped read without coordinate. If POS is 0, no
assumptions can be made about RNAME and CIGAR.

**Comment by mozack** [comment]
OK,  thanks for the response.  Will go with post-processing the reads for these cases.
