### ISSUE TITLE
issues aligning to a genome supplemented with additional sequences

### ISSUE THREAD

**Issue by SchragaSchwartz** [alexdobin/STAR#218]
Dear Alex, 

I am trying to align my files against the human genome, supplemented with a set of additional sequences stored in a file called AviaSpikes.fa. The basic command I am using (with star version STAR_2.5.1b_modified) is:

STAR --genomeDir /home/labs/schwartzlab/schwartz/data/genomes/hg19/hg19_GenAnnot/STARV2/ --outSAMtype BAM SortedByCoordinate --outSAMprimaryFlag AllBestScore --readFilesIn /temp/LibM224poi_IP_alignment/LibM224poi_IPleft_merged.fastq /temp/LibM224poi_IP_alignment/LibM224poi_IPright_merged.fastq --runThreadN 8 --genomeFastaFiles /home/labs/schwartzlab/schwartz/data/genomes/nchg19/AviaSpikes.fa

AviaSpikes.fa is a simple fasta file with four spikes, each of which between 156-160 nucleotides long.

For some weird reason, in the header of the aligned bam file, the first of these sequences appears as though it were only 73 nucleotides long, and this generates errors when I then try to process the files downstream. I think the length of 73 is coming from other sequences (which are part of my human genome assembly) which are 73 bp long (see below). Have you ever run into something like this? I'd be grateful for any thoughts. 

Here's the output for the bamfile using samtools -view H (for looking at the header):

@HD     VN:1.4  SO:coordinate
@SQ     SN:chr10        LN:135534747
@SQ     SN:chr11        LN:135006516
@SQ     SN:chr12        LN:133851895
@SQ     SN:chr13        LN:115169878
@SQ     SN:chr14        LN:107349540
@SQ     SN:chr15        LN:102531392
@SQ     SN:chr16        LN:90354753
@SQ     SN:chr17        LN:81195210
@SQ     SN:chr18        LN:78077248
@SQ     SN:chr19        LN:59128983
@SQ     SN:chr1 LN:249250621
@SQ     SN:chr20        LN:63025520
@SQ     SN:chr21        LN:48129895
@SQ     SN:chr22        LN:51304566
@SQ     SN:chr2 LN:243199373
@SQ     SN:chr3 LN:198022430
@SQ     SN:chr4 LN:191154276
@SQ     SN:chr5 LN:180915260
@SQ     SN:chr6 LN:171115067
@SQ     SN:chr7 LN:159138663
@SQ     SN:chr8 LN:146364022
@SQ     SN:chr9 LN:141213431
@SQ     SN:chrM LN:16571
@SQ     SN:chrX LN:155270560
@SQ     SN:tdbD00000241AlaTGC   LN:71
@SQ     SN:tdbD00000666GluTTC   LN:72
@SQ     SN:tdbD00000667GluTTC   LN:72
@SQ     SN:tdbD00000970GlyGCC   LN:71
@SQ     SN:tdbD00000971GlyCCC   LN:71
@SQ     SN:tdbD00000972GlyTCC   LN:72
@SQ     SN:tdbD00001478LysTTT   LN:73
@SQ     SN:tdbD00001479LysCTT   LN:73
@SQ     SN:tdbD00001776LeuTAG   LN:82
@SQ     SN:tdbD00001777LeuAAG   LN:82
@SQ     SN:tdbD00002083AsnGTT   LN:74
@SQ     SN:tdbD00002084AsnGTT   LN:74
@SQ     SN:tdbD00002254ProAGG   LN:72
@SQ     SN:tdbD00002255ProTGG   LN:72
@SQ     SN:tdbD00002405GlnCTG   LN:72
@SQ     SN:tdbD00002406GlnGTT   LN:74
@SQ     SN:tdbD00002407GlnTTG   LN:72
@SQ     SN:tdbD00002599ArgACG   LN:73
@SQ     SN:tdbD00002600ArgTCG   LN:73
@SQ     SN:tdbD00002910SerTGA   LN:82
@SQ     SN:tdbD00002911SerAGA   LN:82
@SQ     SN:tdbD00002912SerAGA   LN:82
@SQ     SN:tdbD00002913SerTGA   LN:82
@SQ     SN:tdbD00002914SerCGA   LN:88
@SQ     SN:tdbD00003091ThrTGT   LN:73
@SQ     SN:tdbD00003092ThrTGT   LN:73
@SQ     SN:tdbD00003093ThrAGT   LN:74
@SQ     SN:tdbD00003259ValAAC   LN:73
@SQ     SN:tdbD00003260ValCAC   LN:73
@SQ     SN:tdbD00003261ValAAC   LN:73
@SQ     SN:tdbD00003262ValAAC   LN:73
@SQ     SN:tdbD00003263ValCAC   LN:73
@SQ     SN:tdbD00003264ValCAC   LN:73
@SQ     SN:tdbD00003505IniCAT   LN:72
@SQ     SN:tdbD00003506IniCAT   LN:72
@SQ     SN:tdbD00003670TyrGTA   LN:73
@SQ     SN:tdbD00003671TyrGTA   LN:73
@SQ     SN:oneUV2       LN:73
@SQ     SN:oneAflankG   LN:160
@SQ     SN:oneAflankT   LN:156
@SQ     SN:oneAflankC   LN:156

Thank you very much,
Schragi

**Comment by alexdobin** [comment]
Hi @SchragaSchwartz 

this bug was fixed in 2.5.2b, please try it out and let me know if it fixes the problem.

Cheers
Alex
