### ISSUE TITLE
Read Genome/SA/SAindex from FIFO streams

### ISSUE THREAD

**Issue by dinvlad** [alexdobin/STAR#221]
Hi Alex,

I'm trying to stream genome files from AWS S3, so instead of saving the files to a local genomeDir first, I create named (FIFO) pipes and write to them using AWS CLI. However, the Genome, SA, and SAindex pipes appear to be consumed incorrectly:
1) STAR reports the required RAM as a very large number (e.g. 108847334320095876), despite the total size of these files ~25 GB. I also have plenty of RAM on that machine (60 GB), and STAR runs well if I don't use streaming. So it's unable to determine the correct size if it reads SA and SAindex from a pipe.
2) If STAR reads SA and SAindex from local files instead, and only streams the Genome, it starts normally but then shortly after that fails with
    ```
    Dec 15 00:58:04 ..... started STAR run
    Dec 15 00:58:04 ..... loading genome
    Dec 15 00:58:17 ..... started mapping
    terminate called after throwing an instance of 'std::bad_alloc'
      what():  std::bad_alloc
    Aborted
    ```
All other files (genomeParameters.txt etc.) don't appear to be problematic.

I'm running STAR 2.5.2b with
```
--genomeDir /tmp --outFileNamePrefix /tmp/ --readFilesIn /tmp/input.fastq  
```
where all pipes reside under `/tmp`.

I've also used the same scripts for streaming files to other tools (Picard, Dropseq) and those work robustly with nontrivial file sizes (2-3GB).

Do you think it is possible to get it working with named pipes? S3 client writes to these through its stdout, so it should not be any different from any other writer. Or does STAR require random access to these files, in which case we cannot use the pipes..

Thanks

**Comment by dinvlad** [comment]
Unfortunately, it seems that currently STAR opens these files in ['random access' mode](https://github.com/alexdobin/STAR/blob/82020fadb2a34dff39884fa5b10fda2f0984bae9/source/Genome.cpp#L63):
```
stream.seekg (0, ios::end);
```
This is frustrating, since we only need to open and read them once into shared memory, after which the initial files are no longer needed. This prevents 'streaming' from S3 directly into shared memory at the beginning of analysis.

**Comment by dinvlad** [comment]
It seems that random access is only used to determine file sizes associated with the genome. Wouldn't it be better to determine these from a config file? Or supply them via command line parameters? If these options fail, it would be ok to default to the current behavior.

**Comment by alexdobin** [comment]
Hi Denis,

you are right, STAR indeed queries the size of the files which makes streaming impossible. Let me check if I can make a quick fix for that.

Cheers
Alex

**Comment by dinvlad** [comment]
Thanks Alex, that would be really helpful!

As a side note for a practical scenario, I also plan to run multiple jobs on the same host. Does STAR still need access to the initial file if it finds that the genome has already (or is being) loaded by another job? It'd be nice to avoid creating a separate pipe for the big files that would tell "nothing" to STAR if it only needs to know the genome size and/or its other parameters from config files and/or command line options. That would also save RAM used as a buffer by S3 copy command.

Obviously, any logic to resolve potential resource conflicts should be handled in my own code outside STAR, but it'd be great to know how STAR behaves in relation to these resources.
