### ISSUE TITLE
Exact Matches Are Sometimes Incorrectly Aligned

### ISSUE THREAD

**Issue by DarioS** [alexdobin/STAR#227]
Consider the following read, which I placed on its own into a file named `mini.fastq`.

```
@700666F:126:C8768ANXX:1:1101:10669:44605 1:N:0:GTCCGC
AAAAATATCAAGGACAGGATGCAGACAATTACGATGTCAAGTTATTTATACTGTTAGTAGTTAATGTAAAGACATACACTAAAACTACTCCAAGAATGGG
+
CCCCCGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGFGGGFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGEGGGGGGGEB
```

I used the command:

`STAR --readFilesIn mini.fastq --genomeDir indexes/STAR/hg38withGENCODE25/ --genomeLoad LoadAndKeep --outFileNamePrefix miniMapped`

The mapping produced by STAR is `... chr2    69141979        255     72M28S ...`. However, there's a perfect match on chromosome 22 found by BLAT.

```
SCORE START  END QSIZE IDENTITY CHRO STRAND  START    END      SPAN
--------------------------------------------------------------------
 100     1   100   100 100.0%    22   +   25723714  25723813    100

```

I use version 2.5.2b. STAR should be able to find exact matches like this. This read was originally part of a read pair where both reads had exact matches to the genome, but ended up in the chimeric mappings output file.

**Comment by alexdobin** [comment]
Hi Dario,

I have mapped this sequence with STAR and got the correct alignment:
1       16      chr22   25723714        255     100M    *       0       0       CCCATTCTTGGAGTAGTTTTAGTGTATGTCTTTACATTAACTACTAACAGTATAAATAACTTGACATCGTAATTGTCTGCATCCTGTCCTTGATATTTTT    *       NH:i:1  HI:i:1  AS:i:98 nM:i:0

Could you please send me the Log.out files from both genome generation and mapping?
Is it possible that the genome you are using has N-masked repeats?

Cheers
Alex

**Comment by DarioS** [comment]
When I downloaded the the FASTA files manually, I overlooked chr22.fa. Now, I am downloading it and will redo the genome generation and mapping of the reads.
