### ISSUE TITLE
Multi-mapping Reads Incorrectly Classified as Uniquely Mapping

### ISSUE THREAD

**Issue by DarioS** [alexdobin/STAR#229]
I used `--outFilterMultimapNmax 1` in my STAR mapping, but I notice some reads are not unique. For example, in my chimeric file I see a read

```
700666F:126:C8768ANXX:3:2207:13354:20645	0	chr4	49302918	3	70M30S	*	0	0	GAGGGTCAGGGAGAGGGTTTGAGACAGAATGAGGAGTGACTAATGTCTACAGGGTTTTTCTCTGGTCGGGAGTGACTATAGTCAAAGCAATTTAATTGTA	BBBCCGGGGGGGGGGGGFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGFFGGGGGGGGGGGGGGGGDGGGGGGGGGGGGGGGGGGGGGGGGGGG	NH:i:2	HI:i:1	AS:i:68	nM:i:0
700666F:126:C8768ANXX:3:2207:13354:20645	256	chr4	43305538	3	70S30M	*	0	0	GAGGGTCAGGGAGAGGGTTTGAGACAGAATGAGGAGTGACTAATGTCTACAGGGTTTTTCTCTGGTCGGGAGTGACTATAGTCAAAGCAATTTAATTGTA	BBBCCGGGGGGGGGGGGFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGFFGGGGGGGGGGGGGGGGDGGGGGGGGGGGGGGGGGGGGGGGGGGG	NH:i:2	HI:i:2	AS:i:27	nM:i:1
```

However, if I copy and paste it into BLAT, I see that it maps to dozens of locations in the genome, some of which are

```
SCORE START  END QSIZE IDENTITY CHRO STRAND  START    END      SPAN
--------------------------------------------------------------------
  73     1    75   100  98.7%     4   -   49318533  49318607     75
  73     1    75   100  98.7%     4   -   49510188  49510262     75
  73     1    75   100  98.7%    22   -   12178321  12178395     75
```

This read isn't mapping uniquely and so `--outFilterMultimapNmax 1` isn't working correctly.

**Comment by alexdobin** [comment]
Hi Dario,

This only affects the chimeric output, right?
I have added a parameter that should fix this problem, I think. 
Please try it the GitHub master with --chimMainSegmentMultNmax 1 .

Cheers
Alex

**Comment by DarioS** [comment]
But if `--chimMainSegmentMultNmax 1` is not used, why did I only see one pair of rows in the chimeric file for the read I used as an example? If, by default, STAR does not apply the value of `--outFilterMultimapNmax` to chimeric reads, there should be multiple pairs of rows in the chimeric file that have the same read ID. There is only one pair, however.

I don't know if it only affects the chimeric output. I was checking manually and only checked chimeric reads. I suppose it would, though.

**Comment by alexdobin** [comment]
Hi Dario,

the default behavior of STAR is to pick one of the multiple alignments of the main segment and then report a "unique" chimera. This probably should be called a bug - or at least unintended feature, as it does not agree with STAR's usual convention of reporting all multimapping loci or none. However,  at this moment I prefer to keep the old behavior as default, as a bug-fix would screw up people's pipelines. Note, this does not happen when the chimeric reads are output with --chimOutType WithinBAM option. This option will be mainstream in the future, at some point Chimeric.out.sam output will be deprecated.

Cheers
Alex

**Comment by DarioS** [comment]
That's weird, but now I understand how it works at present. I suppose you could get different results if you re-ran the mapping, since STAR nobody would use `--runRNGseed` and a single thread in practice with a large dataset.

I think that the new functionality will be better and look forward to its release.

**Comment by alexdobin** [comment]
--chimOutType WithinBAM had been implemented for awhile now. What I meant is that in the future I will keep it but will get rid of the Chimeric.out.sam output, which has all these compatibility problems.

**Comment by jasper1918** [comment]
Hi Alex,
As a follow-up to the multimapping reads not being present in Chimeric.out.sam file, I'm curious--would you still be keeping the Chimeric.out.junctions file(or some new development) that would list the multimapping chimeric reads in the future? Just asking before I embark on a parser of my own to utilize more mapping info during fusion calling.

**Comment by alexdobin** [comment]
Hi Jeff,

the output of multimapping chimeras is high on my TODO list, but I cannot give you the ETA for that.
The Chimeric.out.junction file is there to stay as it is part of STAR-Fusion, and it will be augmented to output of multimapping chimeras.

Cheers
Alex

**Comment by jasper1918** [comment]
Hi again Alex, 

Sorry to belabor the point but I am not seeing the behavior you describe above. Multimapping chimeric reads from the "WithinBAM" method are reporting a single unique alignment even when multimappers are present. The logic is throwing out multimapping chimeric reads as expected when they pass the threshold value. However, if they multimap less than the threshold the reporting is always a single random alignment. I was expecting the NH and HI flags to increment and multiple alignments to be reported. 

I have been running STAR(master branch) with these pertinent options:
```
--chimOutType WithinBAM
--chimMainSegmentMultNmax 5
--outFilterMultimapNmax 5
--outFilterMultimapScoreRange 1
--outMultimapperOrder Random
--outSAMattributes NH HI AS nM ch
```

The **non-chimeric** reads are as expected have multi-hits and are all present in the Aligned.sortedByCoord.out.bam(cols1-9,12,13):
```
Read19  419     1       13164332        0       35M285378N65M   =       13449785        285553  NH:i:5  HI:i:3
Read19  419     1       13164332        0       35M506233N65M   =       13670640        506408  NH:i:5  HI:i:4
Read19  419     1       13164332        0       35M285378N65M   =       13670640        506408  NH:i:5  HI:i:5
Read19  163     1       13449710        0       100M    =       13449785        175     NH:i:5  HI:i:1
Read19  83      1       13449785        0       100M    =       13449710        -175    NH:i:5  HI:i:1
Read19  339     1       13449785        0       100M    =       13164332        -285553 NH:i:5  HI:i:3
Read19  419     1       13670565        0       100M    =       13670640        175     NH:i:5  HI:i:2
Read19  339     1       13670640        0       100M    =       13670565        -175    NH:i:5  HI:i:2
Read19  339     1       13670640        0       100M    =       13164332        -506408 NH:i:5  HI:i:4
Read19  339     1       13670640        0       100M    =       13164332        -506408 NH:i:5  HI:i:5
```

There are no multimapping chimeric reads(ch flag) in Aligned.sortedByCoord.out.bam.

Here is one paired-read that should multimap to 3 locations in hg19(ensembl):
```
51422229        145     16      14942788        255     41M3458N59M     17      41177977        0       ATGAAATCCTCGCAACTCATCCAACCTGGGCGTTGAAAGAGGCAAGCACCACAGTGCGTGTAACCAACTCCAATGCCAATGCGGCCAGTCCCCTCATAGT    JIJJJJJIHHHGGIHHHHJJJJJGIJIJJJJIHJIGGIIJJIJJJJIHGGIJIJIHCCCDD?<DCDDDDEDCDA?*:7=BBF@EEDEEECCC>DDBB?@= NH:i:1  HI:i:1  AS:i:99 nM:i:0  ch:A:1  NM:i:0
51422229        97      17      41177977        255     88M1135N12M     16      14942788        0       AGTTATGTCCCCACCATGTTTGAGAACTACACTGCGAGCTTTGAGATCGACAAGCGCCGCATTGAGCTCAACATGTGGGACACTTCAGGTTCCTCTTACT    @FFFEDCBDDCDDAHHGHHHHG85>:12?BBBC@?=(>HG:>CDDDEEFHFFFFFF';=ABBB?DD:=7?5@BBCHGHGGHIIJIJJJJJJJJGB;7;?C NH:i:1  HI:i:1  AS:i:97 nM:i:1  ch:A:1  NM:i:1
```

Was the intent to always only report one chimeric alignment or to report all?

**Comment by alexdobin** [comment]
Hi Jeff,

unfortunately, at the moment the intent of --chimMainSegmentMultNmax (>1) parameter is to report only one (quasi) random chimeric alignment. I am not ready to report multimapping chimeras yet. I introduced this parameter to allow filtering out such chimeras altogether with --chimMainSegmentMultNmax 1, while ---chimMainSegmentMultNmax (>1) is there for compatibility with the old output which - unintentionally - allowed such chimeras.

When multimapping chimeric output is implemented, this parameter will make more sense.

Cheers
Alex
