### ISSUE TITLE
help menu?

### ISSUE THREAD

**Issue by brianjohnhaas** [alexdobin/STAR#23]
Hi Alex,

Great to see you on github. :) 

In running the binary, I noticed it just errors out if you don't give it parameters.  Usually -h | --help (or no parameters) will invoke some sort of usage info for the tool.   Would this be an option for STAR?  

I should mention that the manual (pdf) is very helpful.

many thanks,

~brian

**Comment by alexdobin** [comment]
Hi Brian,

it's good to hear from you! The help option is very high on my TODO list. In the meantime the easiest way to get all the up-to-date options is the parametersDefault file in source directory. This will be basically output of the --help option.

Cheers
Alex

**Comment by brianjohnhaas** [comment]
awesome!  Thanks, Alex! :)

On Thu, Feb 19, 2015 at 11:39 AM, alexdobin <notifications@github.com>
wrote:

> Hi Brian,
>
> it's good to hear from you! The help option is very high on my TODO list.
> In the meantime the easiest way to get all the up-to-date options is the
> parametersDefault file in source directory. This will be basically output
> of the --help option.
>
> Cheers
> Alex
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alexdobin/STAR/issues/23#issuecomment-75085550>.
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>
