### ISSUE TITLE
>80% Multi aligned reads

### ISSUE THREAD

**Issue by demis001** [alexdobin/STAR#231]
Hi All,

I have aligned 76 paired end ribo depleted RNA-Seq data against hg38 and got a weird result (>80% multi-aligned reads). I did several studies and migrated to STAR aligner recently due to its speed and specificity.  I never seen a result like this before. Any idea how to improve uniquely aligned reads?

`Number of input reads,39604861,54513811,39789101,35646974,30958463,33904316,43262537,46506370,39085052,39905129,36861229,37013799
Uniquely mapped reads number,6237109,10924014,7427968,6453310,5360515,5546638,8151961,8828776,7300425,7667281,6058161,6963376
Uniquely mapped reads %,15.75%,20.04%,18.67%,18.10%,17.32%,16.36%,18.84%,18.98%,18.68%,19.21%,16.44%,18.81%
Average mapped length,150.43,150.39,150.42,150.31,150.38,150.35,150.44,150.51,150.62,150.30,150.31,150.40
Number of reads mapped to multiple loci,30776136,39623813,29564414,26481745,23404523,26107040,32271109,34635500,29840094,29397826,28077840,27520194
Reads unmapped: too short %,6.45%,7.19%,6.91%,7.50%,6.99%,6.51%,6.46%,6.45%,4.89%,7.02%,7.30%,6.74%
`

@demis001

**Comment by alexdobin** [comment]
Hi Dereje,

could you please post (or send me) one of the Log.final.out files.
What are the parameters that you used for mapping?
The multimappers might be real, even if not desirable. For instance, for total RNA libraries, if ribo-depletion step does not work well, you may get a lot of rRNA reads that are typically multimappers.

Cheers
Alex

**Comment by demis001** [comment]
Yes, the data is a total RNA, I have checked the ribo depletion worked fine. I have checked the most represented sequence wasn't from rRNA during quality check. The RNA was extracted from a  Blood sample, I am assuming the Globin genes may be a problem. I will check that out next week.

`
 Started job on |	Jan 23 13:21:59
                             Started mapping on |	Jan 23 13:29:13
                                    Finished on |	Jan 23 17:04:30
       Mapping speed, Million of reads per hour |	11.04

                          Number of input reads |	39604861
                      Average input read length |	151
                                    UNIQUE READS:
                   Uniquely mapped reads number |	6237109
                        Uniquely mapped reads % |	15.75%
                          Average mapped length |	150.43
                       Number of splices: Total |	1147243
            Number of splices: Annotated (sjdb) |	1130683
                       Number of splices: GT/AG |	1138664
                       Number of splices: GC/AG |	4057
                       Number of splices: AT/AC |	526
               Number of splices: Non-canonical |	3996
                      Mismatch rate per base, % |	1.48%
                         Deletion rate per base |	0.01%
                        Deletion average length |	1.36
                        Insertion rate per base |	0.00%
                       Insertion average length |	1.46
                             MULTI-MAPPING READS:
        Number of reads mapped to multiple loci |	30776136
             % of reads mapped to multiple loci |	77.71%
        Number of reads mapped to too many loci |	34232
             % of reads mapped to too many loci |	0.09%
                                  UNMAPPED READS:
       % of reads unmapped: too many mismatches |	0.00%
                 % of reads unmapped: too short |	6.45%
                     % of reads unmapped: other |	0.00%
                                  CHIMERIC READS:
                       Number of chimeric reads |	0
                            % of chimeric reads |	0.00%

Thanks,

`

**Comment by vkaimal** [comment]
Hi Dereje,

Did you ever figure out why you were seeing so many multi-mapped reads? I'm observing the same thing (~50-70% multi-mapping) with Ribo-depleted whole blood RNA. Were globin genes the culprits? 

Thanks

**Comment by alexdobin** [comment]
Hi @vkaimal 

in total RNA-seq samples, large % of multimappers is often caused by incomplete ribo-depletion, i.e. the multimappers are the rRNA. I would count the reads that overlap rRNA repeats from RepeatMasker track.

Cheers
Alex

**Comment by vkaimal** [comment]
Hi Alex,

That was spot-on! Thanks for the tip!!

Cheers

**Comment by YichaoOU** [comment]
@alexdobin Can you provide an example of how to "count the reads that overlap rRNA repeats from RepeatMasker track."?

Thanks!

**Comment by alexdobin** [comment]
Hi Yichao,

at the moment, the easiest way is to use featureCounts with the rRNA repeats annotation (GTF formatted), and with multimapping reads counting allowed - since rRNA reads are usually multi-mappers.

Cheers
Alex
