### ISSUE TITLE
STAR not mapping properly

### ISSUE THREAD

**Issue by sagnikbanerjee15** [alexdobin/STAR#233]
Hello,

I have a fasta file of sequences which I wish to map back to a genome. This fasta file of sequences have been generated from the genome itself as a part of an experiment. But when I map back to the genome I get a .sam with only the headers and nothing else. When I open the Log.final.out file, t says that there are only 2 reads whereas the read file consists of about 250 sequences. Please help me with this.

Thank you

**Comment by alexdobin** [comment]
Hi @sagnikbanerjee15 

please send me the Log.final.out and Log.otu files.

Cheers
Alex

**Comment by sagnikbanerjee15** [comment]
Hello,

I checked the output and found that STAR considered most of the reads as being too small. Hence I went back and tried to create an index with a larger overhang. This is what I got as an error.

STAR --runThreadN 16 --runMode genomeGenerate --genomeDir /home/sagnik/y2h/data//blumeria/star_index_S1 --genomeFastaFiles /home/sagnik/y2h/data//blumeria/genome.fasta --sjdbGTFfile /home/sagnik/y2h/data//blumeria/transcriptome.gtf --sjdbOverhang 10794 
Jan 31 15:58:22 ..... started STAR run
Jan 31 15:58:22 ... starting to generate Genome files
Jan 31 15:58:37 ... starting to sort Suffix Array. This may take a long time...
Jan 31 15:58:41 ... sorting Suffix Array chunks and saving them to disk...
Jan 31 15:59:01 ... loading chunks from disk, packing SA...
Jan 31 15:59:06 ... finished generating suffix array
Jan 31 15:59:06 ... generating Suffix Array index
Jan 31 15:59:44 ... completed Suffix Array index
Jan 31 15:59:44 ..... processing annotations GTF
Jan 31 15:59:45 ..... inserting junctions into the genome indices

EXITING because of FATAL ERROR: cannot insert junctions on the fly because of strand GstrandBit problem
SOLUTION: please contact STAR author at https://groups.google.com/forum/#!forum/rna-star

Jan 31 16:22:43 ...... FATAL ERROR, exiting

Thank you

**Comment by alexdobin** [comment]
Hi @sagnikbanerjee15 

if you are mapping long reads (>300b) you need to use STARlong executable instead of standard STAR.
However, you do not need to re-generate the genome, the default --sjdbOverhang 100 is fine.
For mapping, these parameters are recommended:
STARlong --outFilterMismatchNmax 100  --seedSearchStartLmax 20 --seedPerReadNmax 100000  --seedPerWindowNmax 1000 --alignTranscriptsPerReadNmax 100000 --alignTranscriptsPerWindowNmax 10000

Cheers
Alex

**Comment by sagnikbanerjee15** [comment]
All right Thanks....
Will write back if I get stuck!!!
ᐧ

Sagnik Banerjee
Graduate Research Assistant
Bioinformatics and Computational Biology
Iowa State University

*"The moment I have realized God sitting in the temple of every human body,
the moment I stand in reverence before every human being and see God in him
- that moment I am free from bondage, everything that binds vanishes, and I
am free" - Swami Vivekananda*
