### ISSUE TITLE
Segmentation fault (core dumped) in Masked genome

### ISSUE THREAD

**Issue by lfaino** [alexdobin/STAR#235]
Dear Dev,
I have an issue with STAR mapper. 

I used the genome of rice to align some RNA-seq on it but I get an error.
to be more specific, I used the genome located at 
ftp://ftp.ensemblgenomes.org/pub/plants/release-34/fasta/oryza_sativa/dna/Oryza_sativa.IRGSP-1.0.dna.toplevel.fa.gz
and all goes fine. This is not a masked genome but a full genome

However, when I use the masked genome located at 
ftp://ftp.ensemblgenomes.org/pub/plants/release-34/fasta/oryza_sativa/dna/Oryza_sativa.IRGSP-1.0.dna_rm.toplevel.fa.gz

I get Segmentation Fault error.

Can you please help me?

Thanks
LF

**Comment by alexdobin** [comment]
Hi LF
please send me the Log.out file of the failed run. Masking should not be a problem, however, I generally do not recommend using masked genome for mapping, as you may be missing a lot of alignments, and the mapping speed may be reduced significantly.

Cheers
Alex

**Comment by alexdobin** [comment]
Hi LF 

I have generated the genome with default parameters for Oryza_sativa.IRGSP-1.0.dna_rm.toplevel.fa and it completed without a problem.

Cheers
Alex

**Comment by lfaino** [comment]
Hi Alex,
thanks for looking into it. 

My post was not complete, sorry. The problem that I have is not in the building of the index file but on the mapping of the short reads in the masked genome. 
I have used a masked genome to which I aligned short reads before on a smaller genome (30 MB) and it worked but not rice i get an error. 

the log file:
[Log.out.txt](https://github.com/alexdobin/STAR/files/768303/Log.out.txt)



the fastq that I used is located at 
https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=ERR748773

Cheers
LF

**Comment by lfaino** [comment]
Hi Alex, any news on my problem?

Thanks
LF

**Comment by alexdobin** [comment]
Hi LF 
sorry for the delay, this was a busy week for me.
I will try to map this data and will get back to you next week.

Cheers
Alex

**Comment by lfaino** [comment]
Hi Alex,
did you have time to check to the error that  i got? 

Cheers
Luigi

**Comment by alexdobin** [comment]
Hi Luigi,

I downloaded the reads with 
$ fastq-dump --split-spot --split-files ERR748773
It looks like a paired-end run, are you mapping only the first mate (from your Log.out file) on purpose?

Cheers
Alex

**Comment by alexdobin** [comment]
Hi Luigi,

I have reproduced the seg-fault with either SE or PE mapping.
It looks like it has something to do with highly repeatable sequences in the genome.
When I generated the genome with --genomeSAindexNbases 6, the problem seems to disappear, at least for few million reads that I mapped. Please try it out.

Cheers
Alex

**Comment by lfaino** [comment]
I used SE  and PE

Luigi

**Comment by alexdobin** [comment]
Hi Luigi,

I have mapped the full read set ERR748773 (PE), and it worked fine, though ~36% of the reads did not map.
So genome generation with --genomeSAindexNbases 6 solves the problem.

Cheers
Alex

**Comment by evolvedmicrobe** [comment]
If masking may introduced a lot of "N"'s, this might be solved by: https://github.com/alexdobin/STAR/pull/535
