### ISSUE TITLE
STAR index build is not completing

### ISSUE THREAD

**Issue by sagnikbanerjee15** [alexdobin/STAR#238]
Hello,

I am generating an index for a transcriptome using STAR. I wish to align some contigs to the transcriptome. The transcriptome basically is a fasta file containing all the transcripts. The size of the file is 2.1GB. The program is taking forever to complete. I am using 20 cores to run it. The program did not stuck because I can see the index files being updated. Please tell me if anything can be done by tweaking the parameters.

Thank you.

**Comment by sagnikbanerjee15** [comment]
Hello,

The job just finished after running for 3 days but it gave me the following error.
EXITING because of FATAL ERROR: cannot insert junctions on the fly because of strand GstrandBit problem
SOLUTION: please contact STAR author at https://groups.google.com/forum/#!forum/rna-star

Please help

**Comment by alexdobin** [comment]
Hi @sagnikbanerjee15 

please send me the Log.out file.

Cheers
Alex

**Comment by sagnikbanerjee15** [comment]
Hello,

Here is the log file. 

[Log.out.zip](https://github.com/alexdobin/STAR/files/797785/Log.out.zip)

**Comment by alexdobin** [comment]
Hi @sagnikbanerjee15 

you are using too large --sjdbOverhang, this is what likely causes the RAM overflow and GstranffBit problem. Even if you have very long reads, increasing --sjdbOverhang beyond 100 does not significnatly increase accuracy.

How long are your reads? You would need to use STARlong for mapping reads longer that 200-300b.

Cheers
Alex

**Comment by sagnikbanerjee15** [comment]
Oh I see.

My reads are maximum 151 bp long. So I guess I do not have to use STARlong

**Comment by alexdobin** [comment]
Hi Sagnik,

for 151b reads normal STAR should work fine - so you only need to reduce --sjdbOverhang to 150, or even leave it at default 100 for the genome generation.

Cheers
Alex
