### ISSUE TITLE
perfect mapping read not matched by STAR

### ISSUE THREAD

**Issue by dominik-handler** [alexdobin/STAR#239]
Hi,

I am using STAR to align my RNAseq data. Overall it works great, but I observed some weird thing with some sequences.
This particular sequence below is not mapped by STAR although it is perfectly aligning to the genome (multiple times though). So far I could not figure out why this is the case. In the Log.final.out it is classified as "
`% of reads unmapped: other"`

>NR_1195666
ATGGGGGACCGCTTGGGAACACCGCGTGTTG

I am using the Drosophila dm6 genome built with this command:
module load  star/2.5.2b

```
STAR --runThreadN 5 --runMode genomeGenerate --genomeDir ${UTILITY_LOCATION}star_${VERSION}/incl-Y/ \
  --genomeFastaFiles ${UTILITY_LOCATION}genome_no-Mito_no-rDNA_incl-Y.fa \
  --sjdbGTFtagExonParentTranscript Parent \
  --sjdbFileChrStartEnd ${UTILITY_LOCATION}star_${VERSION}/junctions_incl-Y.txt
```

I run STAR with these settings:
```
STAR --runThreadN 1 \
    --genomeDir star_r6.14 \
    --readFilesIn 5s.fa \
    --outFileNamePrefix star/ \
    ---outSAMmode NoQS --readFilesCommand cat  --alignEndsType EndToEnd --twopassMode Basic   \
    --outReadsUnmapped Fastx  --outMultimapperOrder Random --outSAMtype SAM --outFilterMultimapNmax 1000 -winAnchorMultimapNmax 2000 \
    --outFilterMismatchNmax 3 --seedSearchStartLmax 30 --outFilterMatchNminOverLread 0 \
    --outFilterType BySJout --alignSJoverhangMin 15 --alignSJDBoverhangMin 1 --outStd SAM > mapped-5s.star.sam
```

Is there any solution or explanation for this sequence?

Thank you,
Dominik

**Comment by alexdobin** [comment]
Hi Dominik,

this is likely because this sequence maps a large number of times > 50.
You can try to increase --winAnchorMultimapNmax and --outFilterMultimapNmax to 100 or more - until it maps.

Cheers
Alex
