### ISSUE TITLE
Use library information when outputting XS tag

### ISSUE THREAD

**Issue by jdidion** [alexdobin/STAR#24]
Currently, STAR only uses intron motif information to determine the strand output in the XS tag. Other aligners (TopHat, HISAT) allow library information to be explicitly specified. When aligning reads from a stranded library (fr-firststrand), the XS tags are highly discordant between STAR and HISAT. This is not an issue when using Cufflinks for assembly (since it allows the library type to be specified), but the new StringTie assembler does not have a way to specify the library type, and relies only on the strand reported in the XS tag.

**Comment by alexdobin** [comment]
This feature is high on my TODO list, hopefully will be added in the next month or so.

**Comment by dolittle007** [comment]
I have exactly the same problem. I am planning to make a RNA-seq pipeline using STAR-Stringtie-edgeR.

**Comment by alexdobin** [comment]
Hi @dolittle007 

please do not comment on a closed issue, since I may not see it quickly enough.
Is your data unstranded or stranded?
For the unstranded data, you can use --outSAMstrandField intronMotif option to add the XS flag to all spliced alignments.

Cheers
Alex

**Comment by dolittle007** [comment]
I am handling stranded library. Stringtie doesn't allow the library type to be specified, and require "XS" tag no matter the strandness. So it forces me to use Cufflinks instead.
Thank you
Ting-You Wang
