### ISSUE TITLE
Quality trim reads vs soft clipping in STAR

### ISSUE THREAD

**Issue by steggs13** [alexdobin/STAR#242]
I am aligning reads to the GrCh37 human reference genome using STAR and am confused as to how to get the most reliable results. At first I aligned my reads with no pre-processing using STAR and got essentially 2 groups: 1 group that aligned well, with 85-95+% of reads uniquely mapping, and another group with only about 60% uniquely mapping. I then tried using sickle to trim low quality reads (q<20). Reads that mapped 85-95+% unique lost about 1 million reads and map a similar % uniquely, and reads that mapped about 60% now map >80% but lost millions of uniquely mapped reads. My question is which pipeline should I trust? Though millions of reads are lost after quality trimming, on average ~90% of reads survive in every case, with the max % of reads lost being 21%. I know that a great feature of STAR is that it soft clips unreliable reads towards the 3' end, so should I be more interested in the raw number of mapping reads, or the percentage? Are the reads lost after quality trimming untrustworthy anyways, or since STAR soft clips should I not quality trim independent of the aligner? Any help would be greatly appreciated

**Comment by alexdobin** [comment]
Hi @steggs13 

I am not sure I understand how did you split the reads into the 2 groups.
Below are my general thoughts on trimming.

Trimming should result in the increases of multimapping reads at the expense of unique mappers, with overall (unique+multiple) mapping rate increase. 
There is a trade-off between sensitivity and precision for uniquely mapped reads. On one hand, if you trim the "incorrect" bases (sequencing errors in your case of QS trimming), you will eliminate false unique mappers - i.e. those that are supposed to be multimappers, but the incorrect bases accidentally made them unique - thus you gain precision for unique mappers. On the other hand, if you trim correct bases, you can make correct unique mappers into multimappers - thus you lose sensitivity for unique mappers.

If you want to quantify this trade-off, you would need to come up with a proxy for "ground truth".
For instance, you can calculate the number of unique mappers that overlap the annotated exons.
Your "sensitivity" (recall) would be this number divided by the total number of reads, while your "precision" would be this number divided by the number of unique mappers. Then you can make the precision-recall graph as a function of the trimming amount, and decide on the optimum trimming.

Cheers
Alex
