### ISSUE TITLE
Question reagarding a parameter in STAR

### ISSUE THREAD

**Issue by vikaskumar1019** [alexdobin/STAR#243]
Hi Alex

I am trying to use a program called TEtookit 
https://github.com/mhammell-laboratory/tetoolkit 
which says that I need to play around these two parameter in STAR called 
1. --outFilterMultimapNmax   2. --outAnchorMultimapNmax
I looked in the manual and parameter --outAnchorMultimapNmax is not available.
I guess this parameter is --winAnchorMultimapNmax. If I am correct?
Thanks.

**Comment by alexdobin** [comment]
Hi  @vikaskumar1019 

I think you are right and they meant --winAnchorMultimapNmax, it does affect the search for multimappers.

Cheers
Alex

**Comment by varsh1090** [comment]
Hi, I am also trying to use TEtools for multi mapped repetitive sequences and I was wondering if you could explain a bit more on what exactly --winAnchorMultimapNmax and --outFilterMultimapNmax do? Thanks!

**Comment by alexdobin** [comment]
Hi @varsh1090 

a read will not be considered mapped and output to SAM/BAM files if it maps to more than --outFilterMultimapNmax. Such reads are reported as mapping to too many loci in the Log.final.out file.

--winAnchorMultimapNmax is used to select anchor seeds - only seeds (exactly mapping portions of the read) that map to <= number of loci are considered anchors. Anchors define the genomic windows where a read mapping is attempted. For example, if you want to map read that map equally well to 100 loci, you would need to set --winAnchorMultimapNmax at leat 100, though I would recommend double that number.

Cheers
Alex
