### ISSUE TITLE
STAR cannot access BAM file

### ISSUE THREAD

**Issue by sagnikbanerjee15** [alexdobin/STAR#245]
Hello,

I have generated an index using STAR and I am using STARlong to map back contigs. I keep running into this issue.

Mar 12 20:52:13 ..... started STAR run
Mar 12 20:52:13 ..... loading genome
Mar 12 20:52:22 ..... processing annotations GTF
Mar 12 20:52:22 ..... inserting junctions into the genome indices
Mar 12 20:52:41 ..... started mapping
Mar 12 22:04:30 ..... started sorting BAM

EXITING because of FATAL ERROR: number of bytes expected from the BAM bin does not agree with the actual size on disk: 2294   0   16

Mar 12 22:04:30 ...... FATAL ERROR, exiting

The command I am running is:

<pre>
/home/sagnik/softwares/STAR/bin/Linux_x86_64/STARlong --outFilterMismatchNmax 100 --seedSearchStartLmax 20 --seedPerReadNmax 100000 --seedPerWindowNmax 1000 --alignTranscriptsPerReadNmax 100000 --alignTranscriptsPerWindowNmax 10000 --runThreadN 60 --genomeDir /home/sagnik/y2h/data/trimmed/../blumeria/indices/STAR_index --readFilesIn /home/sagnik/y2h/data/trimmed//S1/trinity_genome_unguided/trinity_16_100000.Trinity.fasta --outSAMtype BAM SortedByCoordinate --alignIntronMin 12 --alignIntronMax 12350  --sjdbGTFfile /home/sagnik/y2h/data/trimmed/../blumeria/transcriptome.gtf --outFileNamePrefix /home/sagnik/y2h/data/trimmed//S1/trinity_genome_unguided/evaluation3/star_blumeria_16_100000
</pre>

I also run the following command and it again runs into an error but this error is different from the one above.

<pre>
/home/sagnik/softwares/STAR/bin/Linux_x86_64/STAR --runThreadN 60 --genomeDir /home/sagnik/y2h/data/trimmed/../barley/indices/STAR_index --readFilesIn /home/sagnik/y2h/data/trimmed//S1/trinity_genome_unguided/trinity_16_100000.Trinity.fasta --outSAMtype BAM SortedByCoordinate  --sjdbGTFfile /home/sagnik/y2h/data/trimmed/../barley/transcriptome.gtf --alignIntronMin 20 --alignIntronMax 820000 --outFileNamePrefix /home/sagnik/y2h/data/trimmed//S1/trinity_genome_unguided/evaluation3/star_barley_16_100000
</pre>

ERROR:

Mar 13 08:34:10 ..... started STAR run
Mar 13 08:34:10 ..... loading genome
Mar 13 08:47:28 ..... processing annotations GTF
Mar 13 08:48:15 ..... inserting junctions into the genome indices
Mar 13 08:53:33 ..... started mapping
Mar 13 08:55:05 ..... started sorting BAM
[bam_cat] ERROR: fail to open output file '/home/sagnik/y2h/data/trimmed//S1/trinity_genome_unguided/evaluation3/star_barley_16_100000Aligned.sortedByCoord.out.bam'.
Mar 13 08:55:06 ..... finished successfully

The permissions of the folder . The file is being created by STAR. I do not understand why STAR is unable to access them again.

**Comment by alexdobin** [comment]
Hi Sagnik,

please send me the Log.out files of both runs.

Cheers
Alex

**Comment by sagnikbanerjee15** [comment]
Here Is one of the files. This is the one with the second run
ᐧ

Sagnik Banerjee
Graduate Research Assistant
Bioinformatics and Computational Biology
Iowa State University

*"The moment I have realized God sitting in the temple of every human body,
the moment I stand in reverence before every human being and see God in him
- that moment I am free from bondage, everything that binds vanishes, and I
am free" - Swami Vivekananda*

**Comment by alexdobin** [comment]
The file did not get attached...

**Comment by sagnikbanerjee15** [comment]
I could not attach the file in github. It would not allow me too. Please check you email.

**Comment by alexdobin** [comment]
Hi Sagnik,

which e-mail did you send it to? I cannot find it.

Cheers
Alex
