### ISSUE TITLE
Why do stranded counts sometimes exceed unstranded counts?

### ISSUE THREAD

**Issue by suzifei** [alexdobin/STAR#246]
Why do stranded counts sometimes exceed unstranded counts?

Here are some example genes in ReadsPerGene.out.tab for my single-end stranded RNA-seq data:

ENSMMUG00000003786	686	1038	147
ENSMMUG00000010072	98	4060	98
ENSMMUG00000044696	0	118	0

If I'm reading the manual correctly, shouldn't column3 + column4 = column2?

I'm seeing this occur in about 3% of my genes when I use Ensembl's latest macaque genome, but I've seen it happen in several different genomes.

**Comment by alexdobin** [comment]
Hi Suzi,

for genes that overlap on opposite strands, the reads that map into the overlap will be considered ambiguous (and not counted towards either gene) for unstranded counting, while they will be counted for stranded counting. Hence sum of stranded counts is >= unstranded.

Cheers
Alex

**Comment by suzifei** [comment]
Thanks Alex!
