### ISSUE TITLE
Installation in cygwin

### ISSUE THREAD

**Issue by GeoffRoberts123** [alexdobin/STAR#247]
I'm new to NGS, unix and STAR, so this could be a very simple issue.

I'm trying to install star through cygwin. GCC version is 5.x.x

I have amended the sharedmemory.cpp and parameters_openReads.cpp as described in previous help discussions.

Now on trying to compile the code i'm getting the error message 

sortSuffixesBucket.cpp: In function ‘void sortSuffixesBucket(char*, void*, int, int)’:
sortSuffixesBucket.cpp:27:43: warning: pointer of type ‘void *’ used in arithmetic [-Wpointer-arith]
         uint64_t iprev=*(uint64_t*)(ind+0*indSkip);
                                           ^
sortSuffixesBucket.cpp:31:37: warning: pointer of type ‘void *’ used in arithmetic [-Wpointer-arith]
             if (*(uint64_t*)(ind+id*indSkip)==iprev)
                                     ^
sortSuffixesBucket.cpp:43:43: warning: pointer of type ‘void *’ used in arithmetic [-Wpointer-arith]
                 iprev=*(uint64_t*)(ind+id*indSkip);
                                           ^
sortSuffixesBucket.cpp:62:49: warning: pointer of type ‘void *’ used in arithmetic [-Wpointer-arith]
                 charCount[G[*(uint64_t*)(ind+id*indSkip+8) + charShift]]++;//TODO can template uint64_t
                                                 ^
sortSuffixesBucket.cpp:62:57: warning: pointer of type ‘void *’ used in arithmetic [-Wpointer-arith]
                 charCount[G[*(uint64_t*)(ind+id*indSkip+8) + charShift]]++;//TODO can template uint64_t
                                                         ^
sortSuffixesBucket.cpp:62:72: warning: array subscript has type ‘char’ [-Wchar-subscripts]
                 charCount[G[*(uint64_t*)(ind+id*indSkip+8) + charShift]]++;//TODO can template uint64_t
                                                                        ^
sortSuffixesBucket.cpp:85:50: warning: pointer of type ‘void *’ used in arithmetic [-Wpointer-arith]
                     char c=G[*(uint64_t*)(ind+id*indSkip+8) + charShift];
                                                  ^
sortSuffixesBucket.cpp:85:58: warning: pointer of type ‘void *’ used in arithmetic [-Wpointer-arith]
                     char c=G[*(uint64_t*)(ind+id*indSkip+8) + charShift];
                                                          ^
sortSuffixesBucket.cpp:86:44: warning: array subscript has type ‘char’ [-Wchar-subscripts]
                     memcpy(ind1+charStart[c]*indSkip, ind+id*indSkip, indSkip);
                                            ^
sortSuffixesBucket.cpp:86:62: warning: pointer of type ‘void *’ used in arithmetic [-Wpointer-arith]
                     memcpy(ind1+charStart[c]*indSkip, ind+id*indSkip, indSkip);
                                                              ^
sortSuffixesBucket.cpp:87:32: warning: array subscript has type ‘char’ [-Wchar-subscripts]
                     charStart[c]++;
                                ^
sortSuffixesBucket.cpp:89:36: warning: pointer of type ‘void *’ used in arithmetic [-Wpointer-arith]
                 memcpy(ind+uB1[iu]*indSkip, ind1+uB1[iu]*indSkip, (uB2[iu]-uB1[iu])*indSkip);
                                    ^
Could someone please help?

Thanks
Geoff

**Comment by alexdobin** [comment]
Hi Geoff,

these are just compilation warnings, not errors. Did the compilation go through and generated the "STAR" executable?

Cheers
Alex

**Comment by GeoffRoberts123** [comment]
Hi Alex

Yes it did, and I've managed to get it to run and match up a trial data set, so all good - thank you!

GR

> Mr G Roberts MA (Cantab) MRCS
> PhD student and Specialty Registrar in General and Oesophago-gastric Surgery
> Metabolic Research Laboratories and MRC Metabolic Diseases Unit
> University of Cambridge
> WT-MRC Institute of Metabolic Science (Level 4)
> Addenbrooke's Site (B289), Cambridge, CB2 0QQ, UK
> 
> Sent by wireless telephony
