### ISSUE TITLE
Question RE: indexing a genome

### ISSUE THREAD

**Issue by kotoroshinoto** [alexdobin/STAR#248]
Iam generating a genome index with an accompanying genes GTF, (for humans, using igenomes files as input) cpu use becomes very low during the stage after it prints: " ..... inserting junctions into the genome indices"

is this normal? What is it doing that takes so long while having such low cpu use?

**Comment by kotoroshinoto** [comment]
its entirely possible that its doing a lot of read/write because I don't have enough RAM for it to hold everything in memory, I just want to make sure this is expected.

System has 32GB of ram, the process is currently holding ~21GB or so (and the OS reports 97% ram usage). 

If it is spending most of its time waiting for disk operations, then I guess low cpu usage would make sense.

**Comment by alexdobin** [comment]
Hi @kotoroshinoto 

the insertion of junctions into the genome should not take long time...
Please send me the Log.out file.

Cheers
Alex

**Comment by kotoroshinoto** [comment]
I probably don't have enough RAM for the task then. I imagine that had something to do with it

**Comment by kotoroshinoto** [comment]
it seems like the log is being overwritten by the log from my alignment attempt ... odd that it would write that into the genomedir instead of the sampledir

**Comment by kotoroshinoto** [comment]
never mind, it appears it appended to it, the genome build step log is there.

if the fpaste worked properly it should be visible here: https://paste.fedoraproject.org/paste/PS5iZQdgJbOdxu4ZizW3fF5M1UNdIGYhyRLivL9gydE=

**Comment by alexdobin** [comment]
Hi @kotoroshinoto 

the fpaste did not work for, the browser crashes on it for some reason.

Cheers
Alex
