### ISSUE TITLE
README.txt for http://labshare.cshl.edu/shares/gingeraslab/www-data/dobin/STAR/STARgenomes/

### ISSUE THREAD

**Issue by tommycarstensen** [alexdobin/STAR#249]
Is there a README somewhere describing the contents of this directory?

http://labshare.cshl.edu/shares/gingeraslab/www-data/dobin/STAR/STARgenomes/

Specifically I'm looking for files that would be suitable for human build 37 and 38. Thanks.

**Comment by alexdobin** [comment]
Hi Tommy,

I generally recommend that users generate their own genome indexes.
This way you will know exactly what assembly and annotations you are working with.
Also, you may want to include lab-specific things like spike-in sequences.
This also guarantees compatibility between STAR versions.

This directory contains a sample of generic indexes.
If you want to try it out for h38 you can use
[http://labshare.cshl.edu/shares/gingeraslab/www-data/dobin/STAR/STARgenomes/GENCODE/GRCh38_Gencode25/](url)
