### ISSUE TITLE
feature request: cram support

### ISSUE THREAD

**Issue by tommycarstensen** [alexdobin/STAR#250]
Does STAR currently support crams? If not, can I request this? I'm getting this error:

    [bam_header_read] EOF marker is absent. The input is probably truncated.
    [bam_header_read] invalid BAM binary header (this is not a BAM file).
    [main_samview] fail to read the header from "cram/21758_1#10.cram".

When using this command:

    $STAR \
     --runThreadN 16 \
     --genomeDir genome_index_37.75 \
     --readFilesIn cram/*#[1-9]*.cram \
     --readFilesCommand "samtools view -h" \

Thanks!

**Comment by tommycarstensen** [comment]
I read the manual a bit too quickly. It seems only fasta files are accepted as input. OK, so be it.

**Comment by y9c** [comment]
How about supporting CRAM as output? @alexdobin 

Thanks.
