### ISSUE TITLE
mapping paired-end reads in batch

### ISSUE THREAD

**Issue by MariannaPd** [alexdobin/STAR#253]
Hi all,
I've a set of PE reads (about 50 libraries) that I want to map against a genome.
Is there a command to do this batch alignment? 
I did it for SE reads with Phyton but I'm going crazy with PE reads.
Does anyone know a way to solve this issue?

Thanks to anyone who will help me!
Best
Marianna

**Comment by alexdobin** [comment]
Hi Marianna,

there is a possibility to map all the files together (via a comma separated list), but if you want to map each sample separately, you would need to start each job separately. 
I am not sure why it seems harder for the PE reads - you just need to have two lists of files and supply one name from each list.

Cheers
Alex

**Comment by MariannaPd** [comment]
Dear Alex, OK thank you. So Phyton scripting is the solution. I tried with two files but it didn't work. Probably there's a mistake in the script. I will fix it. Thank youBest MariannaIl 06 apr 2017 8:44 PM, alexdobin <notifications@github.com> ha scritto:Hi Marianna,
there is a possibility to map all the files together (via a comma separated list), but if you want to map each sample separately, you would need to start each job separately.
I am not sure why it seems harder for the PE reads - you just need to have two lists of files and supply one name from each list.
Cheers
Alex
