### ISSUE TITLE
Generate GeneCount table from pre-existing BAM?

### ISSUE THREAD

**Issue by bbimber** [alexdobin/STAR#254]
Hello,

I have BAMs generated by STAR, which were then merged into a single BAM.  Is there any way to get STAR to output the gene counts table (--quantMode = GeneCounts) from this existing BAM?

Thanks for any help,
Ben

**Comment by alexdobin** [comment]
Hi Ben,

no, this is not possible at the moment. You would need to use htseq.

Cheers
Alex

**Comment by bbimber** [comment]
ok, thanks
