### ISSUE TITLE
Aligning RIBO-seq reads using STAR

### ISSUE THREAD

**Issue by lucianobrocchieri** [alexdobin/STAR#255]
Hi Alex, I need to align a library of RIBO-seq reads that are on average 30 nt long to a 2Gbp genome. Can you recommend special parameter values that I should use in generating the genome and in running the STAR alignment with such short reads? Thanks for STAR and for any suggestion!

**Comment by alexdobin** [comment]
Hi Luciano,

I would recommend using annotations (GTF) - for such short reads it should significantly increase detection of splices. --sjdbOverhang parameter should be set to the maximum (or 90% percentile) of the read length.
To increase general mapping sensitivity for short reads, you can increase --winAnchorMultimapNmax from default 50 to 100 or 200, and reduce --seedSearchStartLmax from default 50 to 20 or 15.

Cheers
Alex
