### ISSUE TITLE
STAR genomeGenerate  using more RAM than needed

### ISSUE THREAD

**Issue by arnoldliaoILMN** [alexdobin/STAR#256]
I am running genomeGenerate on a 3GB genome but STAR ask for more memory

STAR --runMode genomeGenerate --runThreadN 20 --genomeDir /home/aliao/Star --genomeFastaFiles GCF_000233375.1_ICSASG_v2_genomic.fa

genome is below
ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/233/375/GCF_000233375.1_ICSASG_v2/GCF_000233375.1_ICSASG_v2_genomic.fna.gz 

EXITING because of FATAL PARAMETER ERROR: limitGenomeGenerateRAM=31000000000 is too small for your genome SOLUTION: please specify limitGenomeGenerateRAM not less than168253832576 and make that much RAM available

**Comment by alexdobin** [comment]
Hi @arnoldliaoILMN 

this genome has a lot scaffolds, and you need to scale the --genomeChrBinNbits parameter as
min(18, log2[max(GenomeLength/NumberOfReferences,ReadLength)]),
which is ~14 in your case.

Cheers
Alex
