### ISSUE TITLE
Huge "Genome" file in index with many (artificial) chromosomes?

### ISSUE THREAD

**Issue by flo-compbio** [alexdobin/STAR#257]
Hi,

I would like to understand why STAR generates such a large (40 GB) `Genome` file as part of the index in my case. My FASTA file is ~270 MB (uncompressed), but contains ~160,000 (artificial) chromosomes. I'm not providing STAR with an annotation file (`--sjdbGTFfile`) when generating the index. (The `SA` file is 2.4 GB, and the `SAindex` file is 1.7 GB.)

Thanks!

**Comment by flo-compbio** [comment]
Looking at the `chrStart.txt` file, it seems like STAR generates a sequence of length 262,144 bp for each of my artificial chromosomes, even though they are actually much shorter. Is this behavior expected?

**Comment by alexdobin** [comment]
Hi Florian,

by default STAR indeed pads each chromosome to the length of 2^18=262144 nt.
This is controlled by the --genomeChrBinNbits parameter =18 by default.
It is recommended that this parameter is scaled as min(18, log2[max(GenomeLength/NumberOfReferences,ReadLength)]).
For your genome it's ~11.

Cheers
Alex

**Comment by flo-compbio** [comment]
I see, thank you for the explanation! Closing this issue now.

Best, Florian
