### ISSUE TITLE
fail to align RNA-seq reads with insertions

### ISSUE THREAD

**Issue by ndaniel** [alexdobin/STAR#259]
STAR 2.5.2b fails to align RNA-seq reads with insertions.

```
STAR \
--genomeChrBinNbits 17 \
--genomeSAindexNbases 14 \
--runMode genomeGenerate \
--genomeSuffixLengthMax 10000 \
--runThreadN 4 \
--genomeDir star/ \
--genomeFastaFiles g.fa \
--outFileNamePrefix star/

STAR \
--twopass1readsN -1 \
--twopassMode Basic \
--genomeSAindexNbases 14 \
--sjdbOverhang 116 \
--alignIntronMax 244060 \
--outFilterMatchNmin 116 \
--outFilterMatchNminOverLread 0.6 \
--outFilterScoreMinOverLread 0.6 \
--alignSplicedMateMapLminOverLmate 0.6 \
--genomeDir star/ \
--runThreadN 4 \
--seedSearchStartLmax 17 \
--alignSJoverhangMin 17 \
--alignSJstitchMismatchNmax 5 -1 5 5 \
--outSJfilterOverhangMin 10 10 10 10 \
--outSJfilterCountUniqueMin 1 1 1 1 \
--outSJfilterCountTotalMin 1 1 1 1 \
--outSJfilterDistToOtherSJmin 0 0 0 0 \
--outSJfilterIntronMaxVsReadN 244060 244060 244060 \
--limitOutSAMoneReadBytes 100000000 \
--scoreGapNoncan -4 \
--scoreGapATAC -4 \
--readFilesIn reads.fq \
--outFileNamePrefix star-results/
```
and it gives these alignments:
```
2M-1	16	one	78140	255	78M7997N42M140606N67M	*	0	0	
2l-1	16	one	78154	255	64M7997N42M140606N64M	*	0	0	
4E-1	16	one	78180	255	38M7997N42M140606N63M	*	0	0	
3x-1	16	one	86168	255	89M140606N84M	*	0	0	
4Q-1	16	one	78175	255	43M7997N42M140606N76M	*	0	0	
4o-1	16	one	78166	255	52M7997N42M140606N80M	*	0	0	
5u-1	0	one	78154	255	64M7997N42M140606N75M	*	0	0	
8r-1	0	one	78167	255	51M7997N42M140606N80M	*	0	0	
8p-1	0	one	78167	255	51M7997N42M140606N87M	*	0	0	
9P-1	16	one	78168	255	50M7997N42M140606N83M	*	0	0	
```
whilst missing these all the alignments where an insertion is needed:
```
0C-1	16	two	6161	14	64M134471N10M8I21M13N87M	*	0	0
0Q-1	16	two	6160	9	65M134471N10M8I21M13N59M	*	0	0
11-1	16	two	6168	8	57M134471N10M8I21M13N62M	*	0	0
0u-1	16	two	6141	13	84M134471N10M8I21M13N62M	*	0	0
23-1	16	two	6160	10	65M134471N10M8I21M13N63M	*	0	0
5l-1	0	two	6166	14	59M134471N10M8I21M13N90M	*	0	0
5y-1	0	two	6150	12	75M134471N10M8I21M13N63M	*	0	0
BD-1	16	two	6166	10	59M134471N10M8I21M13N91M	*	0	0
BF-1	16	two	6153	12	72M134471N10M8I21M13N68M	*	0	0
```

**Comment by alexdobin** [comment]
Hi Daniel,

this insertion has a small 8b overhang next to the splice junction. If the junction is not annotated (or detected in the 1st pass), it may be hard for STAR to detect the insertion. 
If you could send me the sequence of the read, and it's expect alignment, as well as genome fasta/gtf, I can try to play with parameters to see if this insertion can be detected.

Cheers
Alex

**Comment by ndaniel** [comment]
Hi Alex,

[here](https://goo.gl/5FmEZx) are all the files needed. There is no GTF file. All these reads are from RNA-seq data from a human tumor cell line. Therefore one is free to align on the human genome BUT in order to make it easier I created here a much smaller synthetic genome. According to biological knowledge it is possible to have very short inserts within RNA which do not map on genome (like for example due to some errors in reference human genome sequence). I believe that here indeed one has real inserts in RNA but of course an aligner can transform those inserts into a string of non-standard nano-exons.

Cheers,
Daniel
