### ISSUE TITLE
how to support CDS without exon in refseq gff

### ISSUE THREAD

**Issue by wangyugui** [alexdobin/STAR#260]
Hi.

In most of case, there are both exon and CDS record in gff files.

but there are some CDS regions without exon info in GRCh38.p10 refseq gff files.

```
grep -v partial=true ${tmp_dir}/genes.gff |
	awk 'BEGIN{FS=OFS="\t"}{if($3=="CDS"){print $1,$4-1,$5}}' |
	uniq.awk |bedtools sort >${tmp_dir}/CDS.bed
awk 'BEGIN{FS=OFS="\t"}{if($3=="exon"){print $1,$4-1,$5}}' ${tmp_dir}/genes.gff |
	uniq.awk |bedtools sort |bedtools merge >${tmp_dir}/exon.bed		
bedtools subtract -f 1.0 -a ${tmp_dir}/CDS.bed -b ${tmp_dir}/exon.bed >${gff%/*}/CDS.without.exon.bed
```

'STAR --runMode genomeGenerate ' will access exon record (NOT CDS record) of gff file.

how to support them?
or we have to fix the gff files and add exon info to it?

**Comment by wangyugui** [comment]
most of them are gene of MT.
STAR will mapping to these region finally even without those exon info.
so this should not be a feature? This is a problem?

**Comment by alexdobin** [comment]
Hi @wangyugui 

I think this is a problem with RefSeq - or maybe with the GFF format itself that is not precise for describing the exon/transcript/gene hierarchy. I strongly prefer GTF which directly enforces this hierarchy. 

Does RefSeq supply GTF file? If not, I would recommend converting GFF to GTF - for instance you can use gffread script from Cufflinks. However, this will not solve this problem with "orphaned" CDSs, as gffread will only convert the "exon" lines.

The reads will be mapped to genomic loci of these CDSs even if they are not converted to exons. STAR uses the annotations for two purposes:
1. To extract the annotated splice junctions, and use them to improve mapping of spliced reads. If these CDSs are not splices with each other (which should be the case for MT), then omitting them will not affect mapping.
2. To convert genomic alignments to transcriptomic, and to count reads per gene with --quantMode options. Omitting these CDSs will remove the corresponding transcripts/genes from these operations.

Cheers
Alex

**Comment by wangyugui** [comment]
Now I am using the fixed gff files by an awk script.
(add exon info for those CDS)

GFF is more complex than gtf.  And there is no good gtf file provided from ncbi.
