### ISSUE TITLE
STAR genomeGenerate takes forever on a high-end server, very puzzling!!

### ISSUE THREAD

**Issue by lishen** [alexdobin/STAR#262]
I was trying to use STAR to build a genome index for mouse GRCm38 vM13 but it takes many hours without completion. I ran STAR on a Redhat Enterprise box with 120GB RAM and 48 cores. I set the number of threads to 20. Initially, STAR seemed to run smoothly, utilizing all 20 cores I provided. Then it suddenly reduced the CPU usage to only 1 core and seemed to put itself into "sleep" mode without any progress.

The STAR versions I used were 2.5.3a and 2.5.2b, same problem.

Here is my script:
`mkdir -p $OUT
STAR --runThreadN 20 
    --runMode genomeGenerate 
    --genomeDir $OUT 
    --genomeFastaFiles $GN_FA 
    --sjdbGTFfile $GTF 
    --sjdbOverhang 100`

Here is the stdout:
> May 05 23:25:03 ..... started STAR run
May 05 23:25:03 ... starting to generate Genome files
May 05 23:26:32 ... starting to sort Suffix Array. This may take a long time...
May 05 23:27:24 ... sorting Suffix Array chunks and saving them to disk...

And here are the last few lines of the log file:
> Number of SA indices: 5305567000
May 05 23:26:32 ... starting to sort Suffix Array. This may take a long time...
Number of chunks: 66;   chunks size limit: 765525008 bytes
May 05 23:27:24 ... sorting Suffix Array chunks and saving them to disk...
Writing 644939296 bytes into ../star/GRCm38_M13/SA_11 ; empty space on disk = 6255470215168 bytes ... done
Writing 528988088 bytes into ../star/GRCm38_M13/SA_9 ; empty space on disk = 6254822711296 bytes ... done
Writing 739284528 bytes into ../star/GRCm38_M13/SA_10 ; empty space on disk = 6254294175744 bytes ... done
Writing 561733688 bytes into ../star/GRCm38_M13/SA_14 ; empty space on disk = 6253551947776 bytes ... done
Writing 534301472 bytes into ../star/GRCm38_M13/SA_13 ; empty space on disk = 6252987973632 bytes ... done
Writing 641668312 bytes into ../star/GRCm38_M13/SA_2 ; empty space on disk = 6252453650432 bytes ... done
Writing 624227648 bytes into ../star/GRCm38_M13/SA_4 ; empty space on disk = 6251812364288 bytes ... done
Writing 736865056 bytes into ../star/GRCm38_M13/SA_7 ; empty space on disk = 6251190018048 bytes ... done
Writing 551434760 bytes into ../star/GRCm38_M13/SA_8 ; empty space on disk = 6250450223104 bytes ... done
Writing 637073584 bytes into ../star/GRCm38_M13/SA_17 ; empty space on disk = 6249901621248 bytes ... done
Writing 722909384 bytes into ../star/GRCm38_M13/SA_6 ; empty space on disk = 6249262010368 bytes ... done
Writing 743956096 bytes into ../star/GRCm38_M13/SA_5 ; empty space on disk = 6248536227840 bytes ... done
Writing 749730128 bytes into ../star/GRCm38_M13/SA_0 ; empty space on disk = 6247789314048 bytes ... done
Writing 583868952 bytes into ../star/GRCm38_M13/SA_16 ; empty space on disk = 6247044268032 bytes ... done
Writing 663518600 bytes into ../star/GRCm38_M13/SA_1 ; empty space on disk = 6246460874752 bytes ... done
Writing 710320928 bytes into ../star/GRCm38_M13/SA_18 ; empty space on disk = 6245794738176 bytes ... done
Writing 638033376 bytes into ../star/GRCm38_M13/SA_15 ; empty space on disk = 6245087526912 bytes ... done
Writing 667242008 bytes into ../star/GRCm38_M13/SA_12 ; empty space on disk = 6244446953472 bytes ... done
Writing 699468616 bytes into ../star/GRCm38_M13/SA_3 ; empty space on disk = 6243779383296 bytes ... done
Writing 645441864 bytes into ../star/GRCm38_M13/SA_31 ; empty space on disk = 6243090567168 bytes ... done
Writing 584365472 bytes into ../star/GRCm38_M13/SA_24 ; empty space on disk = 6242442555392 bytes ... done
Writing 604908944 bytes into ../star/GRCm38_M13/SA_22 ; empty space on disk = 6241855860736 bytes ... done
Writing 504633280 bytes into ../star/GRCm38_M13/SA_32 ; empty space on disk = 6241254801408 bytes ... done
Writing 656314504 bytes into ../star/GRCm38_M13/SA_21 ; empty space on disk = 6240749240320 bytes ... done
Writing 608958480 bytes into ../star/GRCm38_M13/SA_26 ; empty space on disk = 6240090714112 bytes ... done
Writing 608847536 bytes into ../star/GRCm38_M13/SA_23 ; empty space on disk = 6239479767040 bytes ... done
Writing 630510512 bytes into ../star/GRCm38_M13/SA_34 ; empty space on disk = 6238869188608 bytes ... done
Writing 677687488 bytes into ../star/GRCm38_M13/SA_38 ; empty space on disk = 6238238830592 bytes ...Writing 667193688 bytes into ../star/GRCm38_M13/SA_20 ; empty space on disk = 6238039588864 bytes ... done
 done
Writing 580252768 bytes into ../star/GRCm38_M13/SA_25 ; empty space on disk = 6236894162944 bytes ... done
Writing 681569760 bytes into ../star/GRCm38_M13/SA_33 ; empty space on disk = 6236312088576 bytes ... done
Writing 730281000 bytes into ../star/GRCm38_M13/SA_37 ; empty space on disk = 6235628314624 bytes ... done
Writing 634850712 bytes into ../star/GRCm38_M13/SA_30 ; empty space on disk = 6234897723392 bytes ...Writing 752168768 bytes into ../star/GRCm38_M13/SA_29 ; empty space on disk = 6234431746048 bytes ... done
 done
Writing 638226952 bytes into ../star/GRCm38_M13/SA_28 ; empty space on disk = 6233509302272 bytes ... done
Writing 733379816 bytes into ../star/GRCm38_M13/SA_27 ; empty space on disk = 6232872222720 bytes ... done
Writing 726110448 bytes into ../star/GRCm38_M13/SA_36 ; empty space on disk = 6232135929856 bytes ... done
Writing 752168768 bytes into ../star/GRCm38_M13/SA_35 ; empty space on disk = 6231414317056 bytes ... done

I checked online and it seems most people are either using a computer with limited computational resource or indexing a genome with many contigs. Neither applies to my situation. **Does anyone know what is going on?**

**Comment by alexdobin** [comment]
Hi @lishen 

120GB should be more than enough to build this genome.
What does top show - how many threads and how much RAM STAR is using?
Also, please send me the full Log.out file.

Cheers
Alex

**Comment by FRANKSTARLING69** [comment]
> I was trying to use STAR to build a genome index for mouse GRCm38 vM13 but it takes many hours without completion. I ran STAR on a Redhat Enterprise box with 120GB RAM and 48 cores. I set the number of threads to 20. Initially, STAR seemed to run smoothly, utilizing all 20 cores I provided. Then it suddenly reduced the CPU usage to only 1 core and seemed to put itself into "sleep" mode without any progress.
> 
> The STAR versions I used were 2.5.3a and 2.5.2b, same problem.
> 
> Here is my script: `mkdir -p $OUT STAR --runThreadN 20 --runMode genomeGenerate --genomeDir $OUT --genomeFastaFiles $GN_FA --sjdbGTFfile $GTF --sjdbOverhang 100`
> 
> Here is the stdout:
> 
> > May 05 23:25:03 ..... started STAR run
> > May 05 23:25:03 ... starting to generate Genome files
> > May 05 23:26:32 ... starting to sort Suffix Array. This may take a long time...
> > May 05 23:27:24 ... sorting Suffix Array chunks and saving them to disk...
> 
> And here are the last few lines of the log file:
> 
> > Number of SA indices: 5305567000
> > May 05 23:26:32 ... starting to sort Suffix Array. This may take a long time...
> > Number of chunks: 66;   chunks size limit: 765525008 bytes
> > May 05 23:27:24 ... sorting Suffix Array chunks and saving them to disk...
> > Writing 644939296 bytes into ../star/GRCm38_M13/SA_11 ; empty space on disk = 6255470215168 bytes ... done
> > Writing 528988088 bytes into ../star/GRCm38_M13/SA_9 ; empty space on disk = 6254822711296 bytes ... done
> > Writing 739284528 bytes into ../star/GRCm38_M13/SA_10 ; empty space on disk = 6254294175744 bytes ... done
> > Writing 561733688 bytes into ../star/GRCm38_M13/SA_14 ; empty space on disk = 6253551947776 bytes ... done
> > Writing 534301472 bytes into ../star/GRCm38_M13/SA_13 ; empty space on disk = 6252987973632 bytes ... done
> > Writing 641668312 bytes into ../star/GRCm38_M13/SA_2 ; empty space on disk = 6252453650432 bytes ... done
> > Writing 624227648 bytes into ../star/GRCm38_M13/SA_4 ; empty space on disk = 6251812364288 bytes ... done
> > Writing 736865056 bytes into ../star/GRCm38_M13/SA_7 ; empty space on disk = 6251190018048 bytes ... done
> > Writing 551434760 bytes into ../star/GRCm38_M13/SA_8 ; empty space on disk = 6250450223104 bytes ... done
> > Writing 637073584 bytes into ../star/GRCm38_M13/SA_17 ; empty space on disk = 6249901621248 bytes ... done
> > Writing 722909384 bytes into ../star/GRCm38_M13/SA_6 ; empty space on disk = 6249262010368 bytes ... done
> > Writing 743956096 bytes into ../star/GRCm38_M13/SA_5 ; empty space on disk = 6248536227840 bytes ... done
> > Writing 749730128 bytes into ../star/GRCm38_M13/SA_0 ; empty space on disk = 6247789314048 bytes ... done
> > Writing 583868952 bytes into ../star/GRCm38_M13/SA_16 ; empty space on disk = 6247044268032 bytes ... done
> > Writing 663518600 bytes into ../star/GRCm38_M13/SA_1 ; empty space on disk = 6246460874752 bytes ... done
> > Writing 710320928 bytes into ../star/GRCm38_M13/SA_18 ; empty space on disk = 6245794738176 bytes ... done
> > Writing 638033376 bytes into ../star/GRCm38_M13/SA_15 ; empty space on disk = 6245087526912 bytes ... done
> > Writing 667242008 bytes into ../star/GRCm38_M13/SA_12 ; empty space on disk = 6244446953472 bytes ... done
> > Writing 699468616 bytes into ../star/GRCm38_M13/SA_3 ; empty space on disk = 6243779383296 bytes ... done
> > Writing 645441864 bytes into ../star/GRCm38_M13/SA_31 ; empty space on disk = 6243090567168 bytes ... done
> > Writing 584365472 bytes into ../star/GRCm38_M13/SA_24 ; empty space on disk = 6242442555392 bytes ... done
> > Writing 604908944 bytes into ../star/GRCm38_M13/SA_22 ; empty space on disk = 6241855860736 bytes ... done
> > Writing 504633280 bytes into ../star/GRCm38_M13/SA_32 ; empty space on disk = 6241254801408 bytes ... done
> > Writing 656314504 bytes into ../star/GRCm38_M13/SA_21 ; empty space on disk = 6240749240320 bytes ... done
> > Writing 608958480 bytes into ../star/GRCm38_M13/SA_26 ; empty space on disk = 6240090714112 bytes ... done
> > Writing 608847536 bytes into ../star/GRCm38_M13/SA_23 ; empty space on disk = 6239479767040 bytes ... done
> > Writing 630510512 bytes into ../star/GRCm38_M13/SA_34 ; empty space on disk = 6238869188608 bytes ... done
> > Writing 677687488 bytes into ../star/GRCm38_M13/SA_38 ; empty space on disk = 6238238830592 bytes ...Writing 667193688 bytes into ../star/GRCm38_M13/SA_20 ; empty space on disk = 6238039588864 bytes ... done
> > done
> > Writing 580252768 bytes into ../star/GRCm38_M13/SA_25 ; empty space on disk = 6236894162944 bytes ... done
> > Writing 681569760 bytes into ../star/GRCm38_M13/SA_33 ; empty space on disk = 6236312088576 bytes ... done
> > Writing 730281000 bytes into ../star/GRCm38_M13/SA_37 ; empty space on disk = 6235628314624 bytes ... done
> > Writing 634850712 bytes into ../star/GRCm38_M13/SA_30 ; empty space on disk = 6234897723392 bytes ...Writing 752168768 bytes into ../star/GRCm38_M13/SA_29 ; empty space on disk = 6234431746048 bytes ... done
> > done
> > Writing 638226952 bytes into ../star/GRCm38_M13/SA_28 ; empty space on disk = 6233509302272 bytes ... done
> > Writing 733379816 bytes into ../star/GRCm38_M13/SA_27 ; empty space on disk = 6232872222720 bytes ... done
> > Writing 726110448 bytes into ../star/GRCm38_M13/SA_36 ; empty space on disk = 6232135929856 bytes ... done
> > Writing 752168768 bytes into ../star/GRCm38_M13/SA_35 ; empty space on disk = 6231414317056 bytes ... done
> 
> I checked online and it seems most people are either using a computer with limited computational resource or indexing a genome with many contigs. Neither applies to my situation. **Does anyone know what is going on?**

this is some time latter
