### ISSUE TITLE
ENCODE Settings Flag Missing in Manual

### ISSUE THREAD

**Issue by DarioS** [alexdobin/STAR#265]
In Section 3.2.2 of the manual, there's a set of flags each followed by a short description. At the bottom of page 7 of the PDF, there is a description of one of the flags, then the first line of page 8 is another description. I think there should be a flag in between the two descriptions. My educated guess is that the missing line of text is `--outFilterMismatchNoverReadLmax 0.06`.

Also, your numerical example for paired reads might be wrong. It states that 0.06 times 200 is 8. It is, in fact, 12. So, is the ENCODE value of this flag 0.06 or rather 0.04?

**Comment by alexdobin** [comment]
Hi Dario,

thanks for pointing out this problem, it will be fixed in the next patch.
ENCODE uses --outFilterMismatchNoverReadLmax 0.04 - hence 8 MM for 2x100b reads.

Cheers
Alex

**Comment by DarioS** [comment]
Additionally, the manual doesn't specify the units (e.g. Bytes) of the numbers input to `--limitBAMsortRAM`.

**Comment by alexdobin** [comment]
Hi Dario, 

thanks - will be fixed in the next release.

Cheers
Alex
