### ISSUE TITLE
genomeGenerate packing SA error ('std::bad_alloc')

### ISSUE THREAD

**Issue by jmaggi** [alexdobin/STAR#266]
Hi, 
I am trying to index the human genome. In order to do that, I gave in this command:

`STAR --runThreadN 6 --runMode genomeGenerate --genomeDir /home/immgpublic/STAR-2.5.3a/genome --genomeFastaFiles /home/immgpublic/SeqMule/database/human_g1k_v37.fasta --limitGenomeGenerateRAM 24000000000`

Unfortunately, we only have 24 GB RAM. That's why I needed to add the `--limitGenomeGenerateRAM` option.
However, the process does not finish and this is the error message displayed on the terminal:

`May 17 16:53:42 ... loading chunks from disk, packing SA...
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)`

I have no idea about what that means and how I should try to fix it.
Here is what the Log.out file contains:

STAR version=STAR_2.5.3a
STAR compilation time,server,dir=Fri Mar 17 11:35:46 EDT 2017 florence.cshl.edu:/sonas-hs/gingeras/nlsas_norepl/user/dobin/STAR/STAR.sandbox/source
##### DEFAULT parameters:
versionSTAR                       20201
versionGenome                     20101   20200   
parametersFiles                   -   
sysShell                          -
runMode                           alignReads
runThreadN                        1
runDirPerm                        User_RWX
runRNGseed                        777
genomeDir                         ./GenomeDir/
genomeLoad                        NoSharedMemory
genomeFastaFiles                  -   
genomeChainFiles                  -   
genomeSAindexNbases               14
genomeChrBinNbits                 18
genomeSAsparseD                   1
genomeSuffixLengthMax             18446744073709551615
genomeFileSizes                   0   
readFilesIn                       Read1   Read2   
readFilesCommand                  -   
readMatesLengthsIn                NotEqual
readMapNumber                     18446744073709551615
readNameSeparator                 /   
inputBAMfile                      -
bamRemoveDuplicatesType           -
bamRemoveDuplicatesMate2basesN    0
limitGenomeGenerateRAM            31000000000
limitIObufferSize                 150000000
limitOutSAMoneReadBytes           100000
limitOutSJcollapsed               1000000
limitOutSJoneRead                 1000
limitBAMsortRAM                   0
limitSjdbInsertNsj                1000000
outFileNamePrefix                 ./
outTmpDir                         -
outTmpKeep                        None
outStd                            Log
outReadsUnmapped                  None
outQSconversionAdd                0
outMultimapperOrder               Old_2.4
outSAMtype                        SAM   
outSAMmode                        Full
outSAMstrandField                 None
outSAMattributes                  Standard   
outSAMunmapped                    None   
outSAMorder                       Paired
outSAMprimaryFlag                 OneBestScore
outSAMreadID                      Standard
outSAMmapqUnique                  255
outSAMflagOR                      0
outSAMflagAND                     65535
outSAMattrRGline                  -   
outSAMheaderHD                    -   
outSAMheaderPG                    -   
outSAMheaderCommentFile           -
outBAMcompression                 1
outBAMsortingThreadN              0
outSAMfilter                      None   
outSAMmultNmax                    18446744073709551615
outSAMattrIHstart                 1
outSJfilterReads                  All
outSJfilterCountUniqueMin         3   1   1   1   
outSJfilterCountTotalMin          3   1   1   1   
outSJfilterOverhangMin            30   12   12   12   
outSJfilterDistToOtherSJmin       10   0   5   10   
outSJfilterIntronMaxVsReadN       50000   100000   200000   
outWigType                        None   
outWigStrand                      Stranded   
outWigReferencesPrefix            -
outWigNorm                        RPM   
outFilterType                     Normal
outFilterMultimapNmax             10
outFilterMultimapScoreRange       1
outFilterScoreMin                 0
outFilterScoreMinOverLread        0.66
outFilterMatchNmin                0
outFilterMatchNminOverLread       0.66
outFilterMismatchNmax             10
outFilterMismatchNoverLmax        0.3
outFilterMismatchNoverReadLmax    1
outFilterIntronMotifs             None
clip5pNbases                      0   
clip3pNbases                      0   
clip3pAfterAdapterNbases          0   
clip3pAdapterSeq                  -   
clip3pAdapterMMp                  0.1   
winBinNbits                       16
winAnchorDistNbins                9
winFlankNbins                     4
winAnchorMultimapNmax             50
winReadCoverageRelativeMin        0.5
winReadCoverageBasesMin           0
scoreGap                          0
scoreGapNoncan                    -8
scoreGapGCAG                      -4
scoreGapATAC                      -8
scoreStitchSJshift                1
scoreGenomicLengthLog2scale       -0.25
scoreDelBase                      -2
scoreDelOpen                      -2
scoreInsOpen                      -2
scoreInsBase                      -2
seedSearchLmax                    0
seedSearchStartLmax               50
seedSearchStartLmaxOverLread      1
seedPerReadNmax                   1000
seedPerWindowNmax                 50
seedNoneLociPerWindow             10
seedMultimapNmax                  10000
alignIntronMin                    21
alignIntronMax                    0
alignMatesGapMax                  0
alignTranscriptsPerReadNmax       10000
alignSJoverhangMin                5
alignSJDBoverhangMin              3
alignSJstitchMismatchNmax         0   -1   0   0   
alignSplicedMateMapLmin           0
alignSplicedMateMapLminOverLmate    0.66
alignWindowsPerReadNmax           10000
alignTranscriptsPerWindowNmax     100
alignEndsType                     Local
alignSoftClipAtReferenceEnds      Yes
alignEndsProtrude                 0   ConcordantPair   
chimSegmentMin                    0
chimScoreMin                      0
chimScoreDropMax                  20
chimScoreSeparation               10
chimScoreJunctionNonGTAG          -1
chimMainSegmentMultNmax           10
chimJunctionOverhangMin           20
chimOutType                       SeparateSAMold   
chimFilter                        banGenomicN   
chimSegmentReadGapMax             0
sjdbFileChrStartEnd               -   
sjdbGTFfile                       -
sjdbGTFchrPrefix                  -
sjdbGTFfeatureExon                exon
sjdbGTFtagExonParentTranscript    transcript_id
sjdbGTFtagExonParentGene          gene_id
sjdbOverhang                      100
sjdbScore                         2
sjdbInsertSave                    Basic
quantMode                         -   
quantTranscriptomeBAMcompression    1
quantTranscriptomeBan             IndelSoftclipSingleend
twopass1readsN                    18446744073709551615
twopassMode                       None
##### Command Line:
STAR --runThreadN 6 --runMode genomeGenerate --genomeDir /home/immgpublic/STAR-2.5.3a/genome --genomeFastaFiles /home/immgpublic/SeqMule/database/human_g1k_v37.fasta --limitGenomeGenerateRAM 24000000000
###### All USER parameters from Command Line:
runThreadN                    6     ~RE-DEFINED
runMode                       genomeGenerate     ~RE-DEFINED
genomeDir                     /home/immgpublic/STAR-2.5.3a/genome     ~RE-DEFINED
genomeFastaFiles              /home/immgpublic/SeqMule/database/human_g1k_v37.fasta        ~RE-DEFINED
limitGenomeGenerateRAM        24000000000     ~RE-DEFINED
##### Final user re-defined parameters-----------------:
runMode                           genomeGenerate
runThreadN                        6
genomeDir                         /home/immgpublic/STAR-2.5.3a/genome
genomeFastaFiles                  /home/immgpublic/SeqMule/database/human_g1k_v37.fasta   
limitGenomeGenerateRAM            24000000000

-------------------------------
##### Final effective command line:
STAR   --runMode genomeGenerate   --runThreadN 6   --genomeDir /home/immgpublic/STAR-2.5.3a/genome   --genomeFastaFiles /home/immgpublic/SeqMule/database/human_g1k_v37.fasta      --limitGenomeGenerateRAM 24000000000

##### Final parameters after user input--------------------------------:
versionSTAR                       20201
versionGenome                     20101   20200   
parametersFiles                   -   
sysShell                          -
runMode                           genomeGenerate
runThreadN                        6
runDirPerm                        User_RWX
runRNGseed                        777
genomeDir                         /home/immgpublic/STAR-2.5.3a/genome
genomeLoad                        NoSharedMemory
genomeFastaFiles                  /home/immgpublic/SeqMule/database/human_g1k_v37.fasta   
genomeChainFiles                  -   
genomeSAindexNbases               14
genomeChrBinNbits                 18
genomeSAsparseD                   1
genomeSuffixLengthMax             18446744073709551615
genomeFileSizes                   0   
readFilesIn                       Read1   Read2   
readFilesCommand                  -   
readMatesLengthsIn                NotEqual
readMapNumber                     18446744073709551615
readNameSeparator                 /   
inputBAMfile                      -
bamRemoveDuplicatesType           -
bamRemoveDuplicatesMate2basesN    0
limitGenomeGenerateRAM            24000000000
limitIObufferSize                 150000000
limitOutSAMoneReadBytes           100000
limitOutSJcollapsed               1000000
limitOutSJoneRead                 1000
limitBAMsortRAM                   0
limitSjdbInsertNsj                1000000
outFileNamePrefix                 ./
outTmpDir                         -
outTmpKeep                        None
outStd                            Log
outReadsUnmapped                  None
outQSconversionAdd                0
outMultimapperOrder               Old_2.4
outSAMtype                        SAM   
outSAMmode                        Full
outSAMstrandField                 None
outSAMattributes                  Standard   
outSAMunmapped                    None   
outSAMorder                       Paired
outSAMprimaryFlag                 OneBestScore
outSAMreadID                      Standard
outSAMmapqUnique                  255
outSAMflagOR                      0
outSAMflagAND                     65535
outSAMattrRGline                  -   
outSAMheaderHD                    -   
outSAMheaderPG                    -   
outSAMheaderCommentFile           -
outBAMcompression                 1
outBAMsortingThreadN              0
outSAMfilter                      None   
outSAMmultNmax                    18446744073709551615
outSAMattrIHstart                 1
outSJfilterReads                  All
outSJfilterCountUniqueMin         3   1   1   1   
outSJfilterCountTotalMin          3   1   1   1   
outSJfilterOverhangMin            30   12   12   12   
outSJfilterDistToOtherSJmin       10   0   5   10   
outSJfilterIntronMaxVsReadN       50000   100000   200000   
outWigType                        None   
outWigStrand                      Stranded   
outWigReferencesPrefix            -
outWigNorm                        RPM   
outFilterType                     Normal
outFilterMultimapNmax             10
outFilterMultimapScoreRange       1
outFilterScoreMin                 0
outFilterScoreMinOverLread        0.66
outFilterMatchNmin                0
outFilterMatchNminOverLread       0.66
outFilterMismatchNmax             10
outFilterMismatchNoverLmax        0.3
outFilterMismatchNoverReadLmax    1
outFilterIntronMotifs             None
clip5pNbases                      0   
clip3pNbases                      0   
clip3pAfterAdapterNbases          0   
clip3pAdapterSeq                  -   
clip3pAdapterMMp                  0.1   
winBinNbits                       16
winAnchorDistNbins                9
winFlankNbins                     4
winAnchorMultimapNmax             50
winReadCoverageRelativeMin        0.5
winReadCoverageBasesMin           0
scoreGap                          0
scoreGapNoncan                    -8
scoreGapGCAG                      -4
scoreGapATAC                      -8
scoreStitchSJshift                1
scoreGenomicLengthLog2scale       -0.25
scoreDelBase                      -2
scoreDelOpen                      -2
scoreInsOpen                      -2
scoreInsBase                      -2
seedSearchLmax                    0
seedSearchStartLmax               50
seedSearchStartLmaxOverLread      1
seedPerReadNmax                   1000
seedPerWindowNmax                 50
seedNoneLociPerWindow             10
seedMultimapNmax                  10000
alignIntronMin                    21
alignIntronMax                    0
alignMatesGapMax                  0
alignTranscriptsPerReadNmax       10000
alignSJoverhangMin                5
alignSJDBoverhangMin              3
alignSJstitchMismatchNmax         0   -1   0   0   
alignSplicedMateMapLmin           0
alignSplicedMateMapLminOverLmate    0.66
alignWindowsPerReadNmax           10000
alignTranscriptsPerWindowNmax     100
alignEndsType                     Local
alignSoftClipAtReferenceEnds      Yes
alignEndsProtrude                 0   ConcordantPair   
chimSegmentMin                    0
chimScoreMin                      0
chimScoreDropMax                  20
chimScoreSeparation               10
chimScoreJunctionNonGTAG          -1
chimMainSegmentMultNmax           10
chimJunctionOverhangMin           20
chimOutType                       SeparateSAMold   
chimFilter                        banGenomicN   
chimSegmentReadGapMax             0
sjdbFileChrStartEnd               -   
sjdbGTFfile                       -
sjdbGTFchrPrefix                  -
sjdbGTFfeatureExon                exon
sjdbGTFtagExonParentTranscript    transcript_id
sjdbGTFtagExonParentGene          gene_id
sjdbOverhang                      100
sjdbScore                         2
sjdbInsertSave                    Basic
quantMode                         -   
quantTranscriptomeBAMcompression    1
quantTranscriptomeBan             IndelSoftclipSingleend
twopass1readsN                    18446744073709551615
twopassMode                       None
----------------------------------------

Finished loading and checking parameters
May 17 16:27:32 ... starting to generate Genome files
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 0  "1" chrStart: 0
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 1  "2" chrStart: 249298944
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 2  "3" chrStart: 492568576
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 3  "4" chrStart: 690749440
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 4  "5" chrStart: 882114560
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 5  "6" chrStart: 1063256064
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 6  "7" chrStart: 1234436096
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 7  "8" chrStart: 1393819648
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 8  "9" chrStart: 1540358144
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 9  "10" chrStart: 1681653760
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 10  "11" chrStart: 1817444352
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 11  "12" chrStart: 1952710656
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 12  "13" chrStart: 2086666240
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 13  "14" chrStart: 2202009600
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 14  "15" chrStart: 2309488640
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 15  "16" chrStart: 2412249088
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 16  "17" chrStart: 2502688768
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 17  "18" chrStart: 2583953408
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 18  "19" chrStart: 2662072320
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 19  "20" chrStart: 2721316864
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 20  "21" chrStart: 2784493568
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 21  "22" chrStart: 2832728064
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 22  "X" chrStart: 2884108288
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 23  "Y" chrStart: 3039559680
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 24  "MT" chrStart: 3099066368
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 25  "GL000207.1" chrStart: 3099328512
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 26  "GL000226.1" chrStart: 3099590656
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 27  "GL000229.1" chrStart: 3099852800
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 28  "GL000231.1" chrStart: 3100114944
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 29  "GL000210.1" chrStart: 3100377088
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 30  "GL000239.1" chrStart: 3100639232
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 31  "GL000235.1" chrStart: 3100901376
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 32  "GL000201.1" chrStart: 3101163520
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 33  "GL000247.1" chrStart: 3101425664
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 34  "GL000245.1" chrStart: 3101687808
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 35  "GL000197.1" chrStart: 3101949952
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 36  "GL000203.1" chrStart: 3102212096
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 37  "GL000246.1" chrStart: 3102474240
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 38  "GL000249.1" chrStart: 3102736384
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 39  "GL000196.1" chrStart: 3102998528
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 40  "GL000248.1" chrStart: 3103260672
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 41  "GL000244.1" chrStart: 3103522816
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 42  "GL000238.1" chrStart: 3103784960
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 43  "GL000202.1" chrStart: 3104047104
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 44  "GL000234.1" chrStart: 3104309248
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 45  "GL000232.1" chrStart: 3104571392
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 46  "GL000206.1" chrStart: 3104833536
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 47  "GL000240.1" chrStart: 3105095680
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 48  "GL000236.1" chrStart: 3105357824
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 49  "GL000241.1" chrStart: 3105619968
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 50  "GL000243.1" chrStart: 3105882112
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 51  "GL000242.1" chrStart: 3106144256
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 52  "GL000230.1" chrStart: 3106406400
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 53  "GL000237.1" chrStart: 3106668544
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 54  "GL000233.1" chrStart: 3106930688
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 55  "GL000204.1" chrStart: 3107192832
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 56  "GL000198.1" chrStart: 3107454976
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 57  "GL000208.1" chrStart: 3107717120
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 58  "GL000191.1" chrStart: 3107979264
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 59  "GL000227.1" chrStart: 3108241408
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 60  "GL000228.1" chrStart: 3108503552
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 61  "GL000214.1" chrStart: 3108765696
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 62  "GL000221.1" chrStart: 3109027840
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 63  "GL000209.1" chrStart: 3109289984
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 64  "GL000218.1" chrStart: 3109552128
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 65  "GL000220.1" chrStart: 3109814272
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 66  "GL000213.1" chrStart: 3110076416
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 67  "GL000211.1" chrStart: 3110338560
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 68  "GL000199.1" chrStart: 3110600704
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 69  "GL000217.1" chrStart: 3110862848
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 70  "GL000216.1" chrStart: 3111124992
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 71  "GL000215.1" chrStart: 3111387136
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 72  "GL000205.1" chrStart: 3111649280
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 73  "GL000219.1" chrStart: 3111911424
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 74  "GL000224.1" chrStart: 3112173568
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 75  "GL000223.1" chrStart: 3112435712
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 76  "GL000195.1" chrStart: 3112697856
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 77  "GL000212.1" chrStart: 3112960000
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 78  "GL000222.1" chrStart: 3113222144
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 79  "GL000200.1" chrStart: 3113484288
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 80  "GL000193.1" chrStart: 3113746432
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 81  "GL000194.1" chrStart: 3114008576
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 82  "GL000225.1" chrStart: 3114270720
/home/immgpublic/SeqMule/database/human_g1k_v37.fasta : chr # 83  "GL000192.1" chrStart: 3114532864
Number of SA indices: 5729570440
May 17 16:28:45 ... starting to sort Suffix Array. This may take a long time...
Number of chunks: 28;   chunks size limit: 1776934136 bytes
May 17 16:29:01 ... sorting Suffix Array chunks and saving them to disk...
Writing 1581215896 bytes into /home/immgpublic/STAR-2.5.3a/genome/SA_2 ; empty space on disk = 23658287104 bytes ... done
Writing 1582872280 bytes into /home/immgpublic/STAR-2.5.3a/genome/SA_1 ; empty space on disk = 23659941888 bytes ... done
Writing 1645954584 bytes into /home/immgpublic/STAR-2.5.3a/genome/SA_3 ; empty space on disk = 23723024384 bytes ...Writing 1674938592 bytes into /home/immgpublic/STAR-2.5.3a/genome/SA_4 ; empty space on disk = 24195514368 bytes ... done
 done
Writing 1761461968 bytes into /home/immgpublic/STAR-2.5.3a/genome/SA_0 ; empty space on disk = 23838531584 bytes ... done
Writing 1756498368 bytes into /home/immgpublic/STAR-2.5.3a/genome/SA_5 ; empty space on disk = 23833567232 bytes ... done
Writing 1522030872 bytes into /home/immgpublic/STAR-2.5.3a/genome/SA_7 ; empty space on disk = 23599108096 bytes ...Writing 1556859200 bytes into /home/immgpublic/STAR-2.5.3a/genome/SA_6 ; empty space on disk = 24786694144 bytes ... done
 done
Writing 1763161264 bytes into /home/immgpublic/STAR-2.5.3a/genome/SA_8 ; empty space on disk = 23840239616 bytes ... done
Writing 1745845080 bytes into /home/immgpublic/STAR-2.5.3a/genome/SA_10 ; empty space on disk = 23822921728 bytes ...Writing 1757032360 bytes into /home/immgpublic/STAR-2.5.3a/genome/SA_9 ; empty space on disk = 23947800576 bytes ... done
 done
Writing 1665456768 bytes into /home/immgpublic/STAR-2.5.3a/genome/SA_11 ; empty space on disk = 23742533632 bytes ... done
Writing 1631464832 bytes into /home/immgpublic/STAR-2.5.3a/genome/SA_13 ; empty space on disk = 23708540928 bytes ... done
Writing 1749500864 bytes into /home/immgpublic/STAR-2.5.3a/genome/SA_12 ; empty space on disk = 23826579456 bytes ... done
Writing 1632325416 bytes into /home/immgpublic/STAR-2.5.3a/genome/SA_14 ; empty space on disk = 23709401088 bytes ...Writing 1616623920 bytes into /home/immgpublic/STAR-2.5.3a/genome/SA_15 ; empty space on disk = 23797854208 bytes ... done
 done
Writing 1658063776 bytes into /home/immgpublic/STAR-2.5.3a/genome/SA_16 ; empty space on disk = 23735140352 bytes ... done
Writing 1680788192 bytes into /home/immgpublic/STAR-2.5.3a/genome/SA_17 ; empty space on disk = 23757864960 bytes ... done
Writing 1496641016 bytes into /home/immgpublic/STAR-2.5.3a/genome/SA_20 ; empty space on disk = 23573716992 bytes ...Writing 1705248056 bytes into /home/immgpublic/STAR-2.5.3a/genome/SA_19 ; empty space on disk = 23883210752 bytes ... done
 done
Writing 1775535856 bytes into /home/immgpublic/STAR-2.5.3a/genome/SA_18 ; empty space on disk = 23852613632 bytes ... done
Writing 1658682376 bytes into /home/immgpublic/STAR-2.5.3a/genome/SA_22 ; empty space on disk = 23735754752 bytes ... done
Writing 1692788960 bytes into /home/immgpublic/STAR-2.5.3a/genome/SA_21 ; empty space on disk = 23769862144 bytes ... done
Writing 1679252448 bytes into /home/immgpublic/STAR-2.5.3a/genome/SA_23 ; empty space on disk = 23756324864 bytes ... done
Writing 1042853088 bytes into /home/immgpublic/STAR-2.5.3a/genome/SA_27 ; empty space on disk = 23119925248 bytes ... done
Writing 1552138200 bytes into /home/immgpublic/STAR-2.5.3a/genome/SA_25 ; empty space on disk = 23629209600 bytes ... done
Writing 1586986008 bytes into /home/immgpublic/STAR-2.5.3a/genome/SA_26 ; empty space on disk = 23664058368 bytes ... done
Writing 1664343280 bytes into /home/immgpublic/STAR-2.5.3a/genome/SA_24 ; empty space on disk = 23741415424 bytes ... done
May 17 16:53:42 ... loading chunks from disk, packing SA...

**Comment by alexdobin** [comment]
Hi @jmaggi

--limitGenomeGenerateRAM is not enough on its own. To fit human genome into 24GB you also need --genomeSAsparseD 2 .
Please let me know if this solves the problem.

Cheers
Alex

**Comment by jmaggi** [comment]
Hi @alexdobin 

Thanks for the fix. It worked!

Cheers
Jordi
