### ISSUE TITLE
STAR Inactivity

### ISSUE THREAD

**Issue by DarioS** [alexdobin/STAR#268]
STAR appears to do nothing for one hour.

```
May 30 14:12:21 ..... started STAR run
May 30 14:12:21 ..... loading genome
May 30 14:12:21 ..... started mapping

           Time    Speed        Read     Read   Mapped   Mapped   Mapped   Mapped Unmapped Unmapped Unmapped Unmapped
                    M/hr      number   length   unique   length   MMrate    multi   multi+       MM    short    other
May 30 15:15:48      0.1      118625      197    93.6%    197.6     0.1%     3.9%     0.0%     0.0%     2.5%     0.0%
May 30 15:29:47      0.8     1067369      197    93.5%    197.6     0.1%     3.9%     0.0%     0.0%     2.5%     0.0%
May 30 15:36:16      1.4     2012732      197    93.5%    197.6     0.1%     3.9%     0.0%     0.0%     2.5%     0.0%
    ...        ...
May 30 15:58:41     31.6    55949804      197    93.5%    197.6     0.1%     4.0%     0.0%     0.0%     2.5%     0.0%
```

In that hour, the RAM usage slowly increased from nothing to 30 GB, so perhaps the "started mapping" message was premature and STAR is performing operations on the genome which was already located somewhere in shared memory. I used the option `--genomeLoad LoadAndKeep` to try to use an existing genome. It was also only using 1 CPU and only started using 8 once the log file started being added to. There are dozens of other processes of other users running on the server.

**Comment by alexdobin** [comment]
Hi Dario,

if you have not been using the genome in the shared memory for a while, it gets paged out. Then, if you try to use it again, it will take a lot time for the system to get it back in RAM. It's better and faster to remove it from shared memory and load again. Generally, I would advice against using the shared memory unless you absolutely have to (e.g. you have a large number of very small jobs).

Cheers
Alex

**Comment by DarioS** [comment]
That's good advice.
