### ISSUE TITLE
EXITING because of FATAL ERROR: could not create output file

### ISSUE THREAD

**Issue by mdondrup** [alexdobin/STAR#269]
```
/Home/ii/michaeld/miniconda2/bin/STAR --runThreadN 100 --outBAMsortingThreadN 1 --outReadsUnmapped Fastx --sjdbInsertSave Basic --outSAMtype BAM SortedByCoordinate --limitBAMsortRAM 100000000000 --genomeLoad LoadAndKeep --seedSearchStartLmax 8 --outFilterMultimapNmax 100 --outFilterMismatchNoverLmax 0.5 --outFileNamePrefix ./20c2_S51_R1_001.fastq.gz. --readFilesCommand zcat --genomeDir /export/jonassenfs/michaeld/licebase/genomedata/lsal76 --readFilesIn 20c2_S51_R1_001.fastq.gz 20c2_S51_R2_001.fastq.gz
May 30 15:20:15 ..... started STAR run
May 30 15:20:16 ..... loading genome
May 30 15:20:16 ..... started mapping

EXITING because of FATAL ERROR: could not create output file ./20c2_S51_R1_001.fastq.gz._STARtmp//Unmapped.out.mate1.thread84
Solution: check that you have permission to write this file

```
However, I have no problem creating the file, and I have 13T available in the directory:
touch ./20c2_S51_R1_001.fastq.gz._STARtmp//Unmapped.out.mate1.thread31

versionSTAR             020201
    int>0: STAR release numeric ID. Please do not change this value!
versionGenome           020101 020200
    int>0: oldest value of the Genome version compatible with this STAR release. Please do not change this value!

Tested on CentOS 7:
Linux kjempefuru 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

- Installed from miniconda and also compiled from source. 
- Tested with and without option --outFileNamePrefix , no change

g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)

**Comment by mdondrup** [comment]
Seems to be related to the number of threads, up to 30 threads works, but it seems that my version of STAR is not able to handle more than 30 threads.

**Comment by mdondrup** [comment]
I found the reason. It is not a bug in Star but a problem with default ulimit settings for the Linux kernel and CentOS (1024) 
check `ulimit -n`
(The maximum number of open file descriptors (most systems do not allow this value to be set)

Star seems to open many temporary files and once the limit is reached, no more files can be created, hence the error. To avoid the error on larger multicore machines, increase the limit to >10000. My setting is now 16384 which has allowed for 180 threads in my test.

**Comment by jackyen2000** [comment]
Hi, I'm having similar issue with my STAR. I put 20 threads and there should be plenty for me to use. 

"EXITING because of FATAL ERROR: could not create output file sample1_p2__STARtmp//FilterBySJoutFiles.mate1.thread0"

this the error I'm getting. any suggestions? thanks
