### ISSUE TITLE
Align contigs instead of reads

### ISSUE THREAD

**Issue by sagnikbanerjee15** [alexdobin/STAR#273]
Hello,

I have assembled reads into contigs. Do you recommend using STAR to align the assembled contigs to the genome? Unlike short reads, which are typically less than 150 bp, the assembled contigs are much longer.

Thank you.

**Comment by alexdobin** [comment]
Hi Sagnik

for aligning long reads, you would need to use STARlong, please these this thread:
[https://groups.google.com/d/msg/rna-star/E2eevlGWFbQ/NFC-vgVXBwAJ](url)

Cheers
Alex
