### ISSUE TITLE
Add the mate cigar SAM tag (MC) for all records

### ISSUE THREAD

**Issue by nh13** [alexdobin/STAR#275]
There are a lot of tools that benefit from having the mate-cigar tag present, so that we do not need to re-sort the data to make adjacent reads from the same read pair

**Comment by alexdobin** [comment]
Hi Nils,

good suggestion- adding it to my TODO list.

Cheers
Alex

**Comment by NatPRoach** [comment]
Hello @alexdobin, was this ever done, or is it still on the TODO list somewhere? I'm finding that not all alignments are reporting mate CIGARs in releases as recent as 2.7.9a

**Comment by alexdobin** [comment]
Hi Nathan,

it was implemented in 2.5.4a. Please post a few SAM lines were this tag is missing.

**Comment by charlesshale** [comment]
I just ran v2.7.10b and it did not set mate CIGAR for a lot of reads. eg:

A00260:458:HJHNLDSX3:1:1221:22019:36057	16	chr6	96909318	255	3S148M	*	0	0	CGATCTGTTCTGGAATTTTGCATGTGTGTCACGAAGGCTTATTTTTGGACCTTCTTTCTGTCTTGGGACCCAGTTTTTAGATTCAACAATCTTGTGTGATTGGTCTTGATTTTGGTTCTGGACTATGCTTTGCAACCCTGCTTATCCCACA	FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	NH:i:1	HI:i:1	AS:i:146	nM:i:0	NM:i:0	MD:Z:148	jM:B:c,-1	jI:B:i,-1
A00260:458:HJHNLDSX3:1:1221:22019:36057	0	chr6	96909321	255	145M6S	*	0	0	GTTCTGGAATTTTGCATGTGTGTCACGAAGGCTTATTTTTGGACCTTCTTTCTGTCTTGGGACCCAGTTTTTAGATTCAACAATCTTGTGTGATTGGTCTTGATTTTGGTTCTGGACTATGCTTTGCAACCCTGCTTATCCCACAAGATCG	FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFF:FFFF	NH:i:1	HI:i:1	AS:i:143	nM:i:0	NM:i:0	MD:Z:145	jM:B:c,-1	jI:B:i,-1

Also noticed that these reads are missing the first 2 flags - READ_PAIRED and PROPER_PAIR. Under what circumstances are they not set?
