### ISSUE TITLE
long PacBio reads - issues with max read length allowed in STAR

### ISSUE THREAD

**Issue by annaquaglieri16** [alexdobin/STAR#276]
Hi Alex, 

when trying to align long reads RNA-Seq there is a limit in maximum read length allowed by STAR (as stated on https://github.com/PacificBiosciences/cDNA_primer/wiki/Bioinfx-study:-Optimizing-STAR-aligner-for-Iso-Seq-data#maxlen). Is it possible to change this threshold instead of trimming FASTQ files to the maximum allowed?
Sorry if this has been already addressed but I am not aware of it.

Also, is the --sjdbOverhang arguments relevant for the creation of the index in this case? I have seen people running with --sjdbOverhang 0 (default) for long reads but I am not too sure about the possible consequences.

Thanks,
Anna

**Comment by alexdobin** [comment]
Hi Anna,

sorry for belayed reply.
You would need to change the 
#define DEF_readNameLengthMax 50000
to your max read length in the IncludeDefine.h file in the source/ directory, and recompile with 
$ make clean
$ make STARlong

Cheers
Alex
