### ISSUE TITLE
Would like to use STAR with BASH pipe

### ISSUE THREAD

**Issue by charlesdavid** [alexdobin/STAR#278]
Hi Alex, I would like to be able to pipe the input files into STAR and pipe the output from STAR (specifically the Aligned.out.bam) to another program. My hope is to eliminate many intermediate files. So here are a few questions:

1. Does the most recent version of STAR support pipes?
2. If it does, should the input files be combined into one **interleaved** fastq file, or are two separate files needed?
3. Should they be sent through a device like /dev/stdin (for one interleaved file) or /dev/fd/1 and /dev/fd/2 (for two separate files)? Or does STAR use a hyphen to indicate piped input?
4. Should the output from STAR be sent to /dev/stdout when using the flag --outStd BAM?

Here is an example of what I have tried so far:

`
STF="${JAVA} $PICARD SamToFastq \
        I=${BAM} \
        F=/dev/stdout \
        CLIPPING_ATTRIBUTE=XT \
        CLIPPING_ACTION=2 \
        INTERLEAVE=true \
        NON_PF=true \
        TMP_DIR=${PROJECT}/TEMP"

STAR="STAR \
        --runThreadN 32 \
        --genomeDir ${INDEX} \
        --readFilesIn /dev/stdin \
        --chimSegmentMin 15 \
        --chimJunctionOverhangMin 15 \
        --alignMatesGapMax 20000 \
        --alignIntronMax 20000 \
        --outSAMtype BAM Unsorted \
        --outSAMstrandField intronMotif \
        --outFilterIntronMotifs RemoveNoncanonicalUnannotated \
        --outFileNamePrefix ${PREFIX} \
        --twopassMode Basic \
        --quantMode GeneCounts \
        --outQSconversionAdd -31 \
        --outStd BAM"
        
PTSS="${JAVA} $PICARD SortSam \
        I=/dev/stdin \
        O=/dev/stdout \
        SORT_ORDER=queryname"

MBA="${JAVA} $PICARD MergeBamAlignment \
        ALIGNED_BAM=/dev/stdin \
        UNMAPPED_BAM=${BAM} \
        OUTPUT=${OUT}/${PREFIX}.bam \
        R=${GENOME} \
        ADD_MATE_CIGAR=true \
        CLIP_ADAPTERS=true \
        CLIP_OVERLAPPING_READS=true \
        INCLUDE_SECONDARY_ALIGNMENTS=true \
        MAX_INSERTIONS_OR_DELETIONS=-1 \
        PRIMARY_ALIGNMENT_STRATEGY=BestMapq \
        ATTRIBUTES_TO_RETAIN=XS \
        MAX_RECORDS_IN_RAM=10000000 \
        VALIDATION_STRINGENCY=STRICT \
        SORT_ORDER=coordinate \
        CREATE_INDEX=true \
        TMP_DIR=${PROJECT}/TEMP"

COMMAND="${STF} | ${STAR} | ${PTSS} | ${MBA}"
`

**Comment by alexdobin** [comment]
Hi Charles,

STAR takes the input files from the files. The /dev/stdout[in] piping should work, but I think a better way is to use fifo files - then you can do it for paired end reads as well, e.g.
$ mkfifo R1 R2
$ picard ... F=R1 F2=R2 &
$ STAR ... --readFilesIn R1 R2

The output piping can be done with --outStd, but, again, the fifo files make for a more flexible piping.

Cheers
Alex

**Comment by hemantgujar** [comment]
Hi. 
this is what i tried. But is not working  
--readFilesIn stdin

**Comment by hemantgujar** [comment]
Hi 

I have problem with stdin. I used 

 --readFilesIn /dev/stdin

but didn't get expected results. Can anyone please help.  

[2cells_1tmpLog.final.zip](https://github.com/alexdobin/STAR/files/2963908/2cells_1tmpLog.final.zip)
[2cells_1tmpLog.progress.zip](https://github.com/alexdobin/STAR/files/2963910/2cells_1tmpLog.progress.zip)

 

Thanks

**Comment by alexdobin** [comment]
Hi @hemantgujar 

STAR cannot read from stdin presently.
It can work with process substitution
$ STAR ... --readFilesIn <(zcat read1.gz) <(zcat read2.gz)
It can also work with fifo files, as shown in the thread above, i.e. 

$ mkfifo R1 R2
$ <command to stream read1/2 sequences in to R1 and R2> &
$ STAR ... --readFilesIn R1 R2

Cheers
Alex

**Comment by hemantgujar** [comment]
thanks

**Comment by vortexing** [comment]
Not to dig up old stuff, but @alexdobin I tried this fifo setup with STAR in two pass mode and it looks like it received the input from the fifo, but didn't actually put anything IN the bam it made.  It looks like it got all the reads from the fifo it should've when I look in the *._STARpass1/Log.final.out but then there doesn't seem to be any second pass results. Any guidance?

**Comment by alexdobin** [comment]
Hi Amy,

the fifo setup (or any other "transient" files) will not work with the 2-pass mode, as STAR need to read the files twice, for 1st and 2nd pass.

Cheers
Alex

**Comment by vortexing** [comment]
Got it.  I did discover one pass worked yesterday so my fifo details WAS right, just hit that snag.  For this data type, one pass is fine anyway, so not only did this fifo then work but also it simplified the task!  Thanks for getting back to me about that though. :)

**Comment by sagardamle** [comment]
Related to this comment, I would like to create a STAR appliance in which STAR would launch and load the genome and junctions and then proceed to listen for reads using a fifo read stream.

The problem is once STAR receives reads through a named file stream it proceeds through alignment and then finishes and exist the app. 

My question is what if instead of exiting, STAR  merely waited for more reads to stream through.  It would make for a nice and fast alignment service.
