### ISSUE TITLE
Incorrect Coordinates In SJ.out.tab File

### ISSUE THREAD

**Issue by DarioS** [alexdobin/STAR#279]
I converted the splice junction file into a BED file to view with IGV and noticed that the junction objects never seem to have any spliced read support.

Top of STAR-generated SJ.out.tab
```
chr14   19008488        19014285        1       1       0       1       0       41
chr14   19204764        19229859        2       2       0       1       0       43
chr14   19254891        19256517        1       1       0       1       0       31
```

Top of converted SJ.bed
```
chr14   19008488        19014285        jxn     1       +
chr14   19204764        19229859        jxn     1       -
chr14   19254891        19256517        jxn     1       +

```

Also, the splice junctions between known exons of known genes are not found. The command did not set any options containing SJ in their name. I am testing version 2.5.3a.

![junctionsnoreads](https://user-images.githubusercontent.com/631218/27318208-8aeaa3c0-55ce-11e7-94c9-31e2b23d4c90.png)

If I use IGV to generate a Sashimi plot of the same genomic region, the junctions are as expected.

![sashimi](https://user-images.githubusercontent.com/631218/27318261-d82aba3a-55ce-11e7-9811-6204dc2fcb0f.png)

Weirdly, the junction items look like they span between small clusters of reads which have no evidence joining them, although the right-most one has no read support for its right side. There is no mapping quality filter being applied in IGV, so the alignments you see are all of them.

**Comment by alexdobin** [comment]
Hi Dario,

this definitely should not happen. Some junctions are filtered out from the SJ.out.tab file, but all junctions in the SJ.out.tab should be supported by alignments. Please try to use the extras/scripts/sjFromSAMcollapseUandM.awk script to extract the junctions from the SAM file, they should agree (except for filtering) with the SJ.out.tab file.

Cheers
Alex

**Comment by DarioS** [comment]
I made a mistake and was looking at some files in the same folder that used hg19 instead of hg38.
