### ISSUE TITLE
why is strand undefined in non-canonical junctions?

### ISSUE THREAD

**Issue by SebastianMO** [alexdobin/STAR#280]
Hello, 

I’m trying to analyze the “non-canonical” non-annotated spliced junctions of cerevisiae, as part of a project that aims to study splicing errors. However, I’m finding in the SJ.out.tab that all “non-canonical” junctions have undefined strand, which complicates the downstream analysis. Is this normal or am I missing something? How can I allow STAR to define strand on all junctions?  I’m using STAR_2.4.2a

Thanks in advance

**Comment by alexdobin** [comment]
Hi Sebastian

for unannotated junctions, the strand in SJ.out.tab is determined only by the intron motif for canonical junctions, and left undefined for non-canonical. In principle, if you have stranded libraries, you can figure out which strand the non-canonical junctions are on. I would suggest a couple of options:
1. You can modify the extras/scripts/sjFromSAMcollapseUandM.awk (which extracts the junctions from SAM file) to record the strand of the reads. 
2. You can run STAR with --outSAMattributes NH HI AS nM jM jI option. The jM jI options output the intron start/end and motif for each read. It would be easy then to parse the SAM file for non-canonical junctions and collect the strand of the reads.

You will need to be careful with the PE reads as the mates map on opposite strands.
Cheers
Alex

**Comment by SebastianMO** [comment]
Thanks Alex, your comments will be very helpful.
