### ISSUE TITLE
Need your help with argument values

### ISSUE THREAD

**Issue by sagnikbanerjee15** [alexdobin/STAR#281]
Hello,

I have decided to use STARlong to align full length cDNA contigs to a genome. Please find attached the length distribution of the contigs that I am attempting to align. Please suggest me appropriate values for the different parameters of STARlong. 

Thank you.
![harunanijo_transcripts_length_distribution](https://user-images.githubusercontent.com/23457977/27510165-d7fc2f62-58d0-11e7-8fd6-a5f2860c9ce9.png)

**Comment by alexdobin** [comment]
Hi Sagnik,

for starters, I would recommend these parameters:
--outFilterMismatchNmax 100 --seedSearchStartLmax 30 --seedPerReadNmax 100000   
-- seedPerWindowNmax 100 --alignTranscriptsPerReadNmax 100000 --alignTranscriptsPerWindowNmax 10000

Cheers
Alex

**Comment by sagnikbanerjee15** [comment]
All right 
Thank you.
