### ISSUE TITLE
Reads number statistic in Log.final.out

### ISSUE THREAD

**Issue by yewero** [alexdobin/STAR#282]
I used STAR (2.5.3a) to run alignments but when I checked the result in Log.final.out I found the reads numbers were not consistence with that from BAM flag.
My command line:
> STAR --runThreadN 2 --genomeDir Genomes/human/STARIndex --readFilesIn read1.fastq.gz --readFilesCommand zcat --outSAMtype BAM SortedByCoordinate --outFileNamePrefix test/ --outTmpDir STARtmp/ --genomeLoad LoadAndRemove --limitBAMsortRAM 31000000000 --outSAMunmapped Within

The Log.final.out:

>                                  Started job on |       Jun 27 20:46:20
>                              Started mapping on |       Jun 27 20:47:39
>                                     Finished on |       Jun 27 20:48:40
>        Mapping speed, Million of reads per hour |       129.74
> 
>                           Number of input reads |       2198291
>                       Average input read length |       50
>                                     UNIQUE READS:
>                    Uniquely mapped reads number |       1734514
>                         Uniquely mapped reads % |       78.90%
>                           Average mapped length |       49.49
>                        Number of splices: Total |       170178
>             Number of splices: Annotated (sjdb) |       167976
>                        Number of splices: GT/AG |       168051
>                        Number of splices: GC/AG |       1390
>                        Number of splices: AT/AC |       50
>                Number of splices: Non-canonical |       687
>                       Mismatch rate per base, % |       0.89%
>                          Deletion rate per base |       0.04%
>                         Deletion average length |       1.08
>                         Insertion rate per base |       0.03%
>                        Insertion average length |       1.05
>                              MULTI-MAPPING READS:
>         Number of reads mapped to multiple loci |       329696
>              % of reads mapped to multiple loci |       15.00%
>         Number of reads mapped to too many loci |       10540
>              % of reads mapped to too many loci |       0.48%
>                                   UNMAPPED READS:
>        % of reads unmapped: too many mismatches |       0.00%
>                  % of reads unmapped: too short |       5.21%
>                      % of reads unmapped: other |       0.41%
>                                   CHIMERIC READS:
>                        Number of chimeric reads |       0
>                             % of chimeric reads |       0.00%
> 

1. As for Uniquely mapped reads number, when I calculated the reads with "NH:i:1", I got 1758204 reads, which were different from that in Log (1734514)
> samtools view test/Aligned.sortedByCoord.out.bam | grep 'NH:i:1' | wc -l
> 1758204 

2. What is the folumar for the reads numbers list in the Log.final.out file? I didn't find it in the manual.

> Number of input reads = Uniquely mapped reads number + Number of reads mapped to multiple loci + Number of reads mapped to too many loci + Number of reads unmapped (not listed)

Is it right?

**Comment by alexdobin** [comment]
Hi @yewero 

grep 'NH:i:1' will also catch NH:i:10  - this is why you have more reads. You need to ensure "tab" after 1 for correct counting.

Equation 2. is correct.

Cheers
Alex

**Comment by yewero** [comment]
1. Thanks for the 1st question.
2. But when I used a test dataset, I found the equation should be:

> Number of input reads = Uniquely mapped reads number + Number of reads mapped to multiple loci +  Number of reads unmapped

The "Number of reads mapped to too many loci" should not be added again.

**Comment by gk7279** [comment]
@yewero - How did you calculate the unmapped reads? When I do the subtraction of totalreads-(unique+multiloci), I get a different number. And when I look at the percentage of unmapped reads, this number doesn't match.

**Comment by yewero** [comment]
@gk7279 - The count was from samtools:

> samtools view -f 4 test/Aligned.sortedByCoord.out.bam | wc -l
> 134081

So we can find the equation should be:

> Number of input reads (2198291) = Uniquely mapped reads number (1734514) + Number of reads mapped to multiple loci (329696) + Number of reads unmapped (134081)

Because `2198291 - 1734514 - 329696 - 134081 = 0`

**Comment by alexdobin** [comment]
Hi Feng,

in the BAM file, the reads that map to too many loci are output as unmapped, so the samtools view -f4 will count them, and then your equation is correct:
_Number of input reads = Uniquely mapped reads number  + Number of reads mapped to multiple loci + **Number of reads unmapped from BAM**_ 

However, in the Log.final.out file, the reads that map to too many loci are separated from unmapped reads, so 
_Number of input reads = Uniquely mapped reads number + Number of reads mapped to multiple loci + Number of reads mapped to too many loci + **Number of reads unmapped from _Log.final.out**_
Note that the last number is given only as a % of total reads, so there will be rounding error.

Cheers
Alex

**Comment by DarioS** [comment]
I wonder is there an explanation why total reads doesn't equal uniquely mapped reads + mapped to multiple loci + too many mismatches + too short + other + chimeric. The sum is surprisingly slightly greater than the total reads in the final log file.

**Comment by alexdobin** [comment]
Hi Dario,

total input read = uniquely mapped reads + mapped to multiple loci + mapped to too many loci  + too many mismatches + too short + other 

Chimeric alignments are counted separately - some of them are reported as mapped (if non-chimeric alignment passes the mapped filter), and some as unmapped (otherwise).

Cheers
Alex
