### ISSUE TITLE
Spike-in Documentation Improvement

### ISSUE THREAD

**Issue by DarioS** [alexdobin/STAR#283]
There's an old issue on this tracker which shows how to provide a spike-in file, but the parameter description of `--genomeFastaFiles` states it is only to be used in genome generation mode. This is contradictory. Perhaps a short section in the user manual should be devoted to this.

**Comment by gresteban** [comment]
The old issue happens to be this one #218?

**Comment by alexdobin** [comment]
Hi Dario,
thanks for pointing it out, I have updated the manual on github master.

Hi @gresteban 
the problem that Dario pointed to was with just the documentation.
I think I have fixed the #218 issue, but I have to heard back from the user.
If you are seeing this issue - please let me know.

Cheers
Alex
