### ISSUE TITLE
Overlapping Chimeric paired-end alignments are excluded (e.g. in FFPE data)

### ISSUE THREAD

**Issue by yhoogstrate** [alexdobin/STAR#285]
Dear Alex Dobin,

I am working with STAR to analyse fusion genes and by making use of the Chimeric sam file. During the analysis of an FFPE dataset I think I am experiencing a bug or an undesired feature, or I need some assistance in the choice of parameters.

FFPE data is typically more degraded, resuling in smaller RNA fragments. With respect to alignment of paired-end data, this often results in overlapping reads with an insert size close to 0. For reads spanning breakpoints, this means that both mates may contain evidence for the same breakpoint or one may contain that while the mate is overlapping one of the chimeric segments.

In my paired-end alignment (`--readFilesIn ..._R1 ..._R2`) I expected to find both chimType 1 and chimType 2 reads like I found with non degraded RNA data. However, I only found chimType 2 reads. To figure out whether my data actually does contain any chimType 1 reads, I aligned _R1 and _R2 both individually with chimeric settings enabled (`--readFilesIn ..._R1` & `--readFilesIn ..._R2`), and to my surpise the dataset does contain them. So, when I align with both _R1 and _R2 in a paired-end run, they end up in the unaligned file. I suspect that overlapping mates get an additional penalty?

This is a schematic representation of the problem:

```
------------chr1------|-----chr2-------------
                 [====:==>-----------<========] classical Chimeric read (chimType 1, chimRepresent 0)
[=======>-------<=====:==]                      classical Chimeric read (chimType 1, chimRepresent 1)
       [=======>------:----<========]           classical Chimeric read (chimType 2, chimRepresent -1)

                 [====:==>
                 <====:===]                     short fragment (FFPE) Chimeric read - both split

           [=======>
                 <====:===]                     short fragment (FFPE) Chimeric read - 1 split but overlapping

                 [====:==>
                        <========]              short fragment (FFPE) Chimeric read - 1 split but overlapping
```

What I am considering is running the paired end alignment with unmapped reads exported (`--outReadsUnmapped Fastq`) en then re-align the _R1 and _R2 independently in a second run. Do you know whether there is a more elegant way to extract the overlapping chimeric reads or can I be of help with implementing this?

Here some visuals to see what happens:
![image](https://user-images.githubusercontent.com/2264697/27738522-d8a98812-5dab-11e7-8450-f0fc00efa465.png)

All best,

Youri

**Comment by ndaniel** [comment]
@yhoogstrate 

I think that the best and effective strategy here (which is also the simplest) is to use a tool which merges the paired-end reads which overlap  before the alignment is done using STAR.

For example, running a tool which merges overlapping paired-end reads, like for example `bbmerge.sh` (from [BBMAP tools](https://sourceforge.net/projects/bbmap/)) would create two types of input FASTQ files, which are:
- paired-ends reads which were not merged (which are actually two FASTQ files) and these can be used as usual for STAR
- paired-end reads which are overlapping and are merged (without using GTF file), and which look now like single-end reads (that is one FASTQ file) and this FASTQ file can be given as input to STAR.

**Comment by alexdobin** [comment]
Hi @yhoogstrate,, Daniel,

An excellent suggestion from Daniel - this is the best way to deal with overlapping mates.
In the future, I am planning to implement a similar strategy inside the STAR mapping algorithm.

Cheers
Alex

**Comment by ndaniel** [comment]
Hi @alexdobin 

I guess that implementing this in STAR might get a little bit challenging because one needs to merge the reads, align the merged sequence, test if the merge alignment is better than the original alignment of the paired-end reads, un-merge the just merged alignment into the original reads (because otherwise it will look quite funny to have an aligner which aligns the input reads and see in the SAM file that the input reads got *longer* or some even disappeared). 

And by the way, this issue is directly linked to this one: https://github.com/alexdobin/STAR/issues/259 where the reads where obtained my merging the overlapping paired-end reads.

**Comment by alexdobin** [comment]
Hi Daniel,

very nice summary - this is exactly what needs to be done... 
I guess I could cut the corners a bit by outputting these merged reads into a separate SAM.

Sorry about the #259, I dropped the ball on it. Will work on it next week after the holidays.

Cheers
Alex

**Comment by ndaniel** [comment]
Hi,

maybe it would help also if the SAM format would have some kind of native support for extending reads. As far as I know SAM format supports only the case when reads gets shorter but not longer.

> I guess I could cut the corners a bit by outputting these merged reads into a separate SAM.

I guess that would be ok only for chimeric reads that support fusion genes. Even here would probably be nice to have some special/custom tag/flag in the SAM file to show that the mate reads were overlapping and were merged (the the size of the overlapping?).

**Comment by yhoogstrate** [comment]
Hi @ndaniel and @alexdobin,

I like the idea that Daniel proposes in the first reply and gets really close the ideal solution, but I have my concerns with reads that have a marginal overlap (let's say just 4 nt). The chance of finding two reads with 4nt overlap is so high that I assume it is not wise to merge them with bbmerge or similar software. As results those would still be excluded in the STAR alignment (although I don't know what amount of overlap is the treshold of STAR to exclude). Do you have any experience with this Daniel? And as Daniel knows obviously better than me, evidence for Fusion genes may be sparse and a few reads may be sufficient for detection. Therefore I would prefer to include as much as possible chimeric reads to increase confidence.

May I ask if there is an underlying thought in excluding overlapping chimeric reads (maybe something very evident that I overlooked), or is this more a cause/effect of the scoring mechanism? I am still convinced that e.g. by adding an argument like `--chimOverlappingMates` that corrects for the overlapping penalty and includes such reads, might be an interesting setting and I am willing to contribute to this if there is interest.


With respect to the annotation of overlap, the `PT:Z:` comes closest but this is intended for generic annotation and not specific for overlap, but it might be a starting point. I really like the idea Daniel proposes in the last post.


looking forward to your feedback :)

Youri
