### ISSUE TITLE
STAR genomeGenerate doesn't finish with low number of threads

### ISSUE THREAD

**Issue by TorHou** [alexdobin/STAR#287]
This may be connected to: #202

When I try to create the index for Drosophila melanogaster with

`./STAR --runMode genomeGenerate --genomeDir dm --genomeFastaFiles ../../../dm6.fa --runThreadN 1`
and I choose `runThreadN` too small, the process will get stuck at
`Jun 12 15:07:33 ... sorting Suffix Array chunks and saving them to disk...`
I have to set `runThreadN` to at least 3 so that it finishes. If i set `runThreadN` to 3 the process finishes in less that 4 minutes. The process I started with `--runThreadN 1` has not finished after 30 minutes (in earlier attempts it didn't finish after days.) 
Note that `dm6.fa` is 140 Megabytes big. I tried it with some viruses (up to 10 Megabytes file size) where I did not encounter that problem.

Log file 3 threads: 
[Log.out.zip](https://github.com/alexdobin/STAR/files/1119136/Log.out.zip)

Log file 1 threads (when process is still running): 
[Log.out.zip](https://github.com/alexdobin/STAR/files/1119137/Log.out.zip)

Current version I'm using: b51a6591b0942b129e1921bb6e5270dfb95a2116

**Comment by alexdobin** [comment]
Hi Torsten,

I could not reproduce this problem with dm6.fa file (downloaded from UCSC) and you parameters.
There is nothing suspicious in your Log.out files.
How much RAM do you have? It maybe a problem with STAR's RAM management, as by default it's allowed to use 31GB for genome generation - please try to run it with --limitGenomeGenerateRAM 2000000000 (or whatever your RAM limit is). 

In any case, if it worked with 3 threads, it's safe to use it, though I would still like to figure out what the problem was.

Cheers
Alex

**Comment by TorHou** [comment]
Hi Alex,
that solved it. I set --limitGenomeGenerate to 3 Gb and the process finished within a few minutes. 
When I ran the process without the parameter I didn't see anything suspicious: STAR behaved as if it knew the limitations of my laptop (8Gb RAM), the RAM didn't fill completely and the SWAP wasn't touched. That's why I didn't try utilizing this parameter before. 
Thanks very much. This can either be closed or you could take this as incentive to communicate the usage of this parameter even more .. or enforce it :)

**Comment by alexdobin** [comment]
Hi Torsten,

thanks for letting me know!
I think I would need to make some fixes in my code to prevent this problem. I think the default limit on the RAM should be equal to the max memory that the final index would occupy at the mapping step. Or better yet, I should catch this exception and reduce the RAM usage as necessary.

Cheers
Alex
