### ISSUE TITLE
Differences between GeneCounts and samtools idxstats

### ISSUE THREAD

**Issue by rafiyaari** [alexdobin/STAR#288]
Hi Alex,
Thank you for this great alignment tool. 
I would like to ask the following question:
When I compare reads per gene count produced by --quantMode GeneCounts to samtools idxstats of the bam file produced by --quantMode TranscriptomeSAM, I see different counts per gene.
If I understand correctly, higher reads per gene count can be explained by multi mappers. 
What can explain a lower reads per gene count? 
Does idxstats filter some of the reads reported by GeneCounts?
Thank you in advanced,
Rafi.

**Comment by alexdobin** [comment]
Hi Rafi,

alignments that are output into Aligned.toTranscriptome.out.bam have to agree perfectly with the transcript structure, while the ones used for GeneCounts have to simply overlap the exons by one base.
Also, by default no soft-clipping or indels are allowed in the Aligned.toTranscriptome.out.bam. Both of these may reduce the number of reads per gene in the Aligned.toTranscriptome.out.bam compared to the ReadsPerGene.out.tab.

Cheers
Alex

**Comment by rafiyaari** [comment]
Hi Alex,
This makes sense.
Thank you for the quick response.
My apologies that I forgot to answer.
Rafi
