### ISSUE TITLE
Manual: Recommends conflicting advice (do not include Haps/Patches; Do use Gencode)

### ISSUE THREAD

**Issue by jblachly** [alexdobin/STAR#29]
Briefly, the manual recommends in section 2.2.1 that patches and alternative haplotypes not be included. However, in section 2.2.2, GENCODE is recommended for mouse and human. While GENCODE is a superb annotation, the manual further indicates that GENCODE is advantageous because it includes a matching GTF and FASTA. However, the GENCODE FASTA file also includes patches and haplotypes. Thus, these pieces of advice are in conflict.

**Comment by alexdobin** [comment]
That's a good point, indeed the GENCODE fasta file needs to be "cleaned" from the haplotypes/patches. I will add instructions on how to clean-up GENCODE files in the next release.

**Comment by dkoppstein** [comment]
Hi, I noticed this issue and thought I'd mention that it's not clear what are patches and what are haplotypes in the Gencode genome assembly and annotation. Do you have a script for cleaning the Gencode FASTA by any chance?

**Comment by alexdobin** [comment]
Hi David,

if you comment on a closed issue, I amy not see it right away. Next time please reopen it, or start a new one. 

The recent releases of GENCODE contain the "primary assembly" files (marked as PRI) that contains all the scaffolds and exclude patches/haplotypes, e.g.:
[ftp://ftp.sanger.ac.uk/pub/gencode/Gencode_human/release_25/gencode.v25.primary_assembly.annotation.gtf.gz](url)
[ftp://ftp.sanger.ac.uk/pub/gencode/Gencode_human/release_25/GRCh38.primary_assembly.genome.fa.gz](url)

So now there is no need to filter the files.

Cheers
Alex
