### ISSUE TITLE
Add leftmost option to --outMultimapperOrder param?

### ISSUE THREAD

**Issue by wangyugui** [alexdobin/STAR#290]
Hi.

Can we add leftmost option to --outMultimapperOrder param?

If we align to leftmost  loci when Multimapper, then  we will get better different expression result such as cuffdiff?

' --outSAMprimaryFlag AllBestScore' can help novel transcript discovery, we need '--outMultimapperOrder leftmost   --outSAMprimaryFlag OneBestScore' to help different expression discovery?

```
blasr  --hitPolicy
       (all) Specify a policy to treat multiple hits from [all, allbest, random, randombest, leftmost]
      all       : report all alignments.
      allbest   : report all equally top scoring alignments.
      random    : report a random alignment.
      randombest: report a random alignment from multiple equally top scoring alignments.
       leftmost  : report an alignment which has the best alignmentscore and has the smallest mapping coordinate in any reference
```

**Comment by wangyugui** [comment]
or  NH:i:xx (Number of reported alignments that contains the query in the current record) is enough for cuffdiff?

**Comment by wangyugui** [comment]
We have 3 use cases:
1, some transcripts have diff transcript_id, but the transcripts  have same sequences.

2, some transcripts have same transcript_id, one is in primary, and others in ALT.

3, some transcripts have part same sequences.

**Comment by alexdobin** [comment]
Hi @wangyugui 

I am not sure why would we want to output the "leftmost" alignment for multimappers. This will certainly screw up the quantification of transcripts. Cufflinks is supposed to take care of multimappers, and it uses NH and HI tags as far as I know.

Cheers
Alex

**Comment by wangyugui** [comment]
Hi @alexdobin 

`Cufflinks is supposed to take care of multimappers, and it uses NH and HI tags as far as I know.`
so  the best option of STAR for cufflinks will be '--outFilterMultimapNmax 20 --outSAMmultNmax -1' like. '--outMultimapperOrder Random' is enough , and no needs of leftmost  policy.

BTW , '--outSAMprimaryFlag AllBestScore' is needed or can not be set?

Thanks a lot.
