### ISSUE TITLE
Fatal INPUT FILE error, no valid exon lines in the GTF file for arabidopsis

### ISSUE THREAD

**Issue by jakob-petereit** [alexdobin/STAR#291]
Hi,

When creating my genome index, I run into the Error:
Fatal INPUT FILE error, no valid exon lines in the GTF file.
Solution: check the formatting of the GTF file. Most likely cause is the difference in chromosome naming between GTF and FASTA file.

I read a fair bit about the error, but it was not in the accurate thread, so I opened a new Issue.

The problem is indeed, that GTF and FASTA file have different naming for the chromosomes, however I am not entirely sure, how to reformat them to match, as I don't know how STAR genome generate reads the FASTA file, what it then puts into which chrXXX.txt (which is probably the critical step) and what information needs to be in the ID line of the FASTA file.

Here a few example lines of the files - which I directly downloaded from Ensembl.
**cDNA FASTA File (omitted most of the sequences) - Arabidopsis thaliana build 34:**
`>AT1G19090.1 cdna chromosome:TAIR10:1:6589835:6592762:1 gene:AT1G19090 gene_biotype:nontranslating_CDS transcript_biotype:nontranslating_CDS
GAAAAAGGAAGCGGGAGAGGGGAGCCCAGTACTTGAGGACAGGAGAAGGATTGATTGTAC`
`>AT1G18320.1 cdna chromosome:TAIR10:1:6304360:6305689:1 gene:AT1G18320 gene_biotype:nontranslating_CDS transcript_biotype:nontranslating_CDS
CTACTCTCTTAACCTTTGAAATGGCTGATTCGAGTGCTGCTGAAACAACAACCGGTGCTT`

**GTF File - Arabidopsis thaliana build 34:**
`#!genome-build TAIR10
#!genome-version TAIR10
#!genome-date 2010-09
#!genome-build-accession GCA_000001735.1
#!genebuild-last-updated 2010-09
1	araport11	gene	3631	5899	.	+	.	gene_id "AT1G01010"; gene_name "NAC001"; gene_source "araport11"; gene_biotype "protein_coding";
1	araport11	transcript	3631	5899	.	+	.	gene_id "AT1G01010"; transcript_id "AT1G01010.1"; gene_name "NAC001"; gene_source "araport11"; gene_biotype "protein_coding"; transcript_source "araport11"; transcript_biotype "protein_coding";
1	araport11	exon	3631	3913	.	+	.	gene_id "AT1G01010"; transcript_id "AT1G01010.1"; exon_number "1"; gene_name "NAC001"; gene_source "araport11"; gene_biotype "protein_coding"; transcript_source "araport11"; transcript_biotype "protein_coding"; exon_id "AT1G01010.1.exon1";
1	araport11	CDS	3760	3913	.	+	0	gene_id "AT1G01010"; transcript_id "AT1G01010.1"; exon_number "1"; gene_name "NAC001"; gene_source "araport11"; gene_biotype "protein_coding"; transcript_source "araport11"; transcript_biotype "protein_coding"; protein_id "AT1G01010.1";`

**chrName.txt:**
AT1G19090.1
AT1G18320.1
AT5G11100.1
AT4G35335.1
AT1G60930.1
AT1G17000.1
AT3G55270.1
AT4G16150.1

How would you reformat the FASTA file to match the GTF annotation ?

**Comment by jakob-petereit** [comment]
I assume my mistake is trying this with CDNA as reference genome

**Comment by jakob-petereit** [comment]
Cheers, it worked with an old star version, which puzzled me a lot though.
Probably just a missing error message I guess.

Have a good one.
Jakob

**Comment by alexdobin** [comment]
Hi Jakob,

that's right - the old version did not see any "valid" exon lines either (i.e. with matching chromosome names), and so it simply ignored the GTF file. The new version generates the error message.

Cheers
Alex

**Comment by AJK91** [comment]
> Hi Jakob
> 
> indeed, if you are mapping to the cDNA sequences, you do not need to (and cannot) use the genomic annotations.
> 
> Cheers Alex

Dear Alex,
 I have encountered the same issue and as far as i understand this mapping step can be skipped. But I need to do the alignment that would catch fusion genes, so for the next step I would need file parameters.txt, which is generated during mapping. Is there any solution for this?

Thank you in advance, 
A.

**Comment by alexdobin** [comment]
Hi @AJK91 

you need mapping to detect fusion genes.
If you map to a collection of cDNAs (transcripts sequences), you do not need annotations (GTF), since each sequence corresponds to a different transcript/gene.

Cheers
Alex
