### ISSUE TITLE
Question: Are all output reads from STAR uniquely mapped?

### ISSUE THREAD

**Issue by gk7279** [alexdobin/STAR#293]
Hi Alex,

Here is my command

```
cd /home/user/Downloads/

/home/user/bin/STAR/STAR-2.5.3a/bin/Linux_x86_64/STAR --genomeDir /home/user/bin/STAR/index/ --genomeLoad LoadAndExit
ipcs

/home/user/bin/STAR/STAR-2.5.3a/bin/Linux_x86_64/STAR --runThreadN 24 --runMode alignReads --genomeDir /home/user/bin/STAR/index/ --sjdbGTFfile /home/user/bin/STAR/GTF/GRCm38_KGK_July2017_vM11.gtf --readFilesIn input.gz --outFileNamePrefix output --outFilterMultimapNmax 10 --outSAMmapqUnique 255 --outSAMtype BAM SortedByCoordinate --outSAMattributes All --quantMode GeneCounts --readFilesCommand zcat --outWigType bedGraph --outWigStrand Stranded --outWigNorm RPM

/home/user/bin/STAR/STAR-2.5.3a/bin/Linux_x86_64/STAR --genomeDir /home/user/bin/STAR/index/ --genomeLoad Remove
ipcs

rm -rf _STARtmp Log.progress.out Aligned.out.sam
```

Question1:

Are all output reads from the above alignment uniquely mapped(since I used 255)? If so - when I filter the BAM file using samtools, why are the numbers different? Why are there 24 more reads in the filtered bam compared to the final.out number?

```
samtools view outputAligned.sortedByCoord.out.bam | wc -l = 24397148
samtools view -bh -F 0x04 -q 255 -o filtered.bam outputAligned.sortedByCoord.out.bam
samtools view filtered.bam | wc -l = 15501295

samtools view -c -q 255 outputAligned.sortedByCoord.out.filtered.bam = 15501271
```

Question2:
Whenever I load the genome or remove the genome, there is a Log.out file and Aligned.out.sam file being generated with nothing inside them? How can I prevent these from being created?

Question3:
How do I get the total mapped reads info? Final.out file shows only uniquely mapped reads count.

I am a novice and still learning a plethora of STAR options. Thanks for any valuable pointers.

P.S.: STAR is freaking fast. Aligned my 19million reads under 2minutes.

Thanks

**Comment by alexdobin** [comment]
Hi @gk7279 

Q1. With --outFilterMultimapNmax 10 you are outputting both unique and multimappers with <=10 loci.
If you want unique mappers only, you would need --outFilterMultimapNmax 1 .

In your example, I am not sure why filtered.bam contains more reads than outputAligned.sortedByCoord.out.filtered.bam - filtered.bam must be a subset of the -q 255 outputAligned.sortedByCoord.out.filtered.bam. I have tried these commands on one of my BAM files and the counts always come out the same. Please try to do diff on SAM files obtained from the two BAMs to see which reads are different.

Q2. Unfortunately, there is no way to switch off creation of these files. I will put it on my TODO list.
However, you do not really need the to run the LoadAndExit command - simply **run all the mapping commands with --genomeLoad LoadAndKeep . Actually, you need to do it anyway, even if you using the separate LoadAndExit command.** The very first mapping job will load the genome if it's not already in the memory.

Q3. Log.final.out file shows the info for multi-mappers as well:
                             MULTI-MAPPING READS:
        Number of reads mapped to multiple loci |       505450
             % of reads mapped to multiple loci |       15.04%
        Number of reads mapped to too many loci |       4609
             % of reads mapped to too many loci |       0.14%

Cheers
Alex

**Comment by gk7279** [comment]
Thanks @alexdobin !

I prefer to have multimapped reads in my output BAM. So I will stick to the value of 10 and use samtools in downstream to filter.

One last question before closing this issue. I am trying to run two single end samples using comma as separator in the readfilesin option. But there aren't any folders created for separating two samples. The data gets rewritten. Should I use the outputprefix with comma separation also?

Kindly advice. Great tool by the way.

Cheers

**Comment by alexdobin** [comment]
Hi @gk7279 

With the comma separated list, the results  from all samples will be written into one directory - one  set of output files. If you need two separate BAM files, you would need to run two jobs in different directories or with different prefixes.

Cheers
Alex

**Comment by gk7279** [comment]
Thanks. The loadandkeep is throwing the same fatal error that is already reported. Even if I take out the GTF file, it still exists. So I think I will go with loading and removing as my earlier commands. Thanks for the help. Will come back to you if I need anything. Cheers and thanks for saving tons of time.
