### ISSUE TITLE
Illegal CIGAR string.

### ISSUE THREAD

**Issue by princethewinner** [alexdobin/STAR#294]
While running the HTSeq on the SAM file generated by STAR, I got the below error.
ValueError: ("Illegal CIGAR string '33478251'", 'line 4450763 of file SRR578233_Aligned.out.sam')

Lines from the SAM file in those area are attached.
[error_around.txt](https://github.com/alexdobin/STAR/files/1164759/error_around.txt)

SRR578233.3399884	256	**SRR578233.8376486	16**	chr17	33478251	1	21M2S	*	0	0	TCGCCACGTCTGATCTGAGGTGG	///////////////////////	NH:i:3	HI:i:1	AS:i:20	nM:i:0

It seems highlighted fields in the above is wrong.

I used 4 threads to generate the sam file. 

I rerun the experiment with the 1 thread and it was successful.

I am attaching the log file.
[SRR578233_Log.out.txt](https://github.com/alexdobin/STAR/files/1164775/SRR578233_Log.out.txt)

**Comment by alexdobin** [comment]
Hi Prashant

it seems that the same alignment was output twice partially overwriting itself.
Is this error reproducible - if you run the same job again, do you get it exactly the same?

Cheers
Alex
