### ISSUE TITLE
outFilterMismatchNoverReadLmax option

### ISSUE THREAD

**Issue by a-velt** [alexdobin/STAR#295]
Dear developers,

I have a question about the option outFilterMismatchNoverReadLmax.
I want a mapping identity of 95% between my reads and my reference. For now, I have a script to perform this filter after the STAR alignment. But, if I can perform this filter directly with STAR, it would be nice !

I have a question, if there is an indel in the alignment, is it taken into account with this option?

I ask this in comparison to the Tophat options, where there are two separate options for this purpose : 

-N/--read-mismatches:
mismatches (i.e. only substitutions, no indels)

--read-edit-dist:
mismatches + indels

Thank you and have a nice day.
Best,
Amandine

**Comment by alexdobin** [comment]
Hi Amandine,

--outFilterMismatchNoverReadLmax only takes into account the mismatches, not indels.
There are several options to control for "identity" - you would need to decide if they are exactly what you want.
1. If you define identity as the number of read bases matched to the reference (this will exclude msimatched/deleted/inserted bases), then the --outFilterMatchNmin and --outFilterMatchNminOverLread can be used to control min identity (number of bases or number of bases normalized to the read length). 

2. If you want to control edit distance, STAR can output  it (for each mate) as a standard NM tag - you need to add it to --outSAMattributes, e.g. --outSAMattributes NH HI AS nM NM .
Then you could use this tag for filtering after mapping. Note, that the NM does *not* include the soft clipped bases.

3. If you want to filter by edit distance while mapping, you can try to use the --outFilterScoreMinOverLread and --outFilterScoreMinOverLread that control the min alignments score, which sums penalties from mismatches (hard coded -2) and indels. If you use
--scoreDelOpen 0 --scoreDelBase -2 --scoreInsOpen 0  --scoreInsBase -2 --scoreGenomicLengthLog2scale   0
the resulting penalty will be 2*EditDistance .
Note, that for spliced alignments (N in the CIGAR) there are additional penalties that you may want to set to zero (or to whatever value you define it to be in your edit distance model): --scoreGap 0 --scoreGapNoncan 0  --scoreGapGCAG 0 --scoreGapATAC 0
Then, if you set --outFilterScoreMinOverLread 0.9, it will prohibit the alignments with edit distance > 0.05*ReadLength . Note that the soft clipped bases have an edit distance of 0.5 (hard-coded).
If you try this approach, please let me know how it goes.

Cheers
Alex

**Comment by a-velt** [comment]
Thank you for your answer. I will try with the NM tag or the options --outFilterMatchNmin and --outFilterMatchNminOverLread. 

One last question, I want to keep the primary alignments only, so I use the option --outSAMprimaryFlag OneBestScore and then I launch : 

samtools view -F 0x100 -bS Aligned.out.sam > Aligned.primary.sam

In the case of paired-end reads, if several alignments are the best, STAR keep a random alignment. But, the pairs are always concordant ? Is it the pair that is randomly selected or the read ?

Best,
Amandine

**Comment by alexdobin** [comment]
Hi Amandine,

by default, STAR only outputs the concordant pairs, and the primary alignment is selected as one of them.

Note, that by default the primary alignment is not selected randomly. For random selection, you would need to use --outMultimapperOrder Random .

Cheers
Alex

**Comment by a-velt** [comment]
Hi Alex,

I have a question. I have a pipeline which use STAR, and for some case, this pipeline give the paired-end reads like that : 

STAR ... --readFilesIn **sample_R1.fastq sample_R2.fastq**

and in few cases, in the other order : 

STAR ... --readFilesIn **sample_R2.fastq sample_R1.fastq**

is this a problem for STAR ? or does it recognize paired-end reads to the ID and not to the order given in the command?

Thank you,
Amandine

**Comment by alexdobin** [comment]
Hi Amandine,

this effectively changes the order of the mates and swaps their strands.
In most cases, the resulting alignments will be exactly the same, apart from changing the FLAG bits for first mate/second mate. There is a very small possibility of strand bias in STAR alignments, <1 read per million.

Cheers
Alex
