### ISSUE TITLE
What is STAR's RPM formula?

### ISSUE THREAD

**Issue by gk7279** [alexdobin/STAR#296]
Hi Alex,

How is the RPM calculated in STAR? How does it handle overlapping reads? Can you please share more info? 

Thanks

**Comment by alexdobin** [comment]
Hi @gk7279 

are you asking about the RPM in the wiggle output?

Cheers
Alex

**Comment by gk7279** [comment]
Hi Alex - yes.

**Comment by alexdobin** [comment]
Hi @gk7279 

for the --outWigNorm RPM, the number of reads crossing each base is divided by the total number of mapped reads, and multiplied by 1,000,000 .

Cheers
Alex
