### ISSUE TITLE
STAR Aligner Mapped SAMfile header

### ISSUE THREAD

**Issue by rajultayal** [alexdobin/STAR#299]
Hi 
I Use STAR for mapping everything goes fine with command for mapping but when I checked the output sam file with samtools it showing 
[bam_header_read] EOF marker is absent. The input is probably trunc
[bam_header_read] invalid BAM binary header (this is not a BAM file
[main_samview] fail to read the header from "JG62Aligned.out.sam".

**Comment by rajultayal** [comment]
Whether I have to use --outSAMattrRGline in mapping command for RG in SAM file

**Comment by alexdobin** [comment]
Hi @rajultayal 

what is the exact samtools command that you are using?

Cheers
Alex

**Comment by rajultayal** [comment]
Hi Alex thanks for replying.
I used  Ist command and the output bam is  for duplicate mark and split n
trim but when i used that file for GTAK Base recalibration it didnt worked
and Show @RG <https://gatkforums.broadinstitute.org/gatk/profile/RG>:id is
not a recognized platform  and after i modified with 2nd one the file
generated work for the GTAK Base recalibrion.

java  -jar picard.jar AddOrReplaceReadGroups I=WR315Aligned.out.sam
O=WR315_rg_added_sorted.bam SO=coordinate RGID=id RGLB=library
RGPL=platform RGPU=machine RGSM=sample


java -jar picard-tools AddOrReplaceReadGroups.jar
 INPUT=WR315_rg_added_sorted.bam OUTPUT=WR315_with_header.bam
SORT_ORDER=coordinate RGID=sample RGLB=sample RGPL=illumina RGSM=sample
RGPU=name CREATE_INDEX=true

Thanks

Regards
RaJUL
