### ISSUE TITLE
STAR fails to read Fastq header with trailing spaces

### ISSUE THREAD

**Issue by pjb7687** [alexdobin/STAR#300]
STAR fails to read Fastq header with trailing space(s), with following error:

```
ReadAlignChunk_processChunks.cpp:115:processChunks EXITING because of FATAL ERROR in input reads: unknown file format: the read ID should start with @ or >
```

Due to existence of ' ' (space) character in the end of the Fastq ID, STAR tries to find the second ID field. But since there is no second field but just the line ends, so the next line is falsely read as the second field. I confirmed that it works fine after I remove the trailing spaces in the header.

This makes STAR incompatible with Je 1.0 (https://gbcs.embl.de/portal/tiki-index.php?page=Je) which appends a space in the end of header line.

**Comment by alexdobin** [comment]
Hi Jeongbin,

I will fix this in the future releases. However, I am not sure why would anyone want to add space to the end of the read ID.

Cheers
Alex

**Comment by rgranit** [comment]
@alexdobin I'm having the same issue after cleaning the readers with trim-galore.. any suggestions?
