### ISSUE TITLE
about the parameter Sjdboverhang

### ISSUE THREAD

**Issue by YdlNAU** [alexdobin/STAR#302]
Dear author, think you contribute a lot.
I have a question about --Sjdboverhang parameter. I search the google and you manual, you said the ideal setting is length -1. this means maximum length-1 at one side and 1 at one side.
But I see the default value is 0(I use 2.4.0i); is this mans  it won't split reads, it can just mapping reads but can not identify junctions?
I had an experiment: I mapping eClip reads( ~45bp PE) to Repbase without gtf. the Repbase is a fasta file contain human repeat elements and is small(1.8M) ; I both build index using --Sjdboverhang 35 and don't set this parameter. and the results are really the same.
and I see the Log.final.out it support to split reads to map? could you please explain it ?

Here is the mapping log:

                          Number of input reads |       22925946
                      Average input read length |       81
                                    UNIQUE READS:
                   Uniquely mapped reads number |       521616
                        Uniquely mapped reads % |       2.28%
                          Average mapped length |       82.75
                       Number of splices: Total |       528
            Number of splices: Annotated (sjdb) |       0
                       Number of splices: GT/AG |       459
                       Number of splices: GC/AG |       60
                       Number of splices: AT/AC |       9
               Number of splices: Non-canonical |       0
                      Mismatch rate per base, % |       6.72%
                         Deletion rate per base |       0.11%
                        Deletion average length |       1.86
                        Insertion rate per base |       0.03%
                       Insertion average length |       1.40
                             MULTI-MAPPING READS:
        Number of reads mapped to multiple loci |       275786
             % of reads mapped to multiple loci |       1.20%
        Number of reads mapped to too many loci |       711
             % of reads mapped to too many loci |       0.00%
                                  UNMAPPED READS:
       % of reads unmapped: too many mismatches |       0.75%
                 % of reads unmapped: too short |       91.95%
                     % of reads unmapped: other |       3.82%

index building command is:
STAR --runMode genomeGenerate --runThreadN 5 --genomeDir human_Rep_V21_STARIndex_overhand0 --genomeFastaFiles human_Rep_V21/human_Rep_cat_humrep.refAndsub.ref_V21.fasta

**Comment by alexdobin** [comment]
Hi @YdlNAU 

you are using a pretty old version, the new version uses the default value of 100, which is good for most purposes.

Cheers
Alex
