### ISSUE TITLE
STARlong alignments cannot be indexed with samtools

### ISSUE THREAD

**Issue by steffi778** [alexdobin/STAR#303]
Hello alex,

I am trying STARlong for PacBio reads and I got a few issues. Firstly, I could not find any hints how to use STARlong in the manual... It would be great, if you could extend it. So I'am not really sure if I did everything right... It started with the index generation already - do I perform the normal genomeGenerate command with star or starlong? Which parameters are important for PacBio in this case?

For the mapping I used the recommended parameters of the following website https://github.com/PacificBiosciences/cDNA_primer/wiki/Bioinfx-study:-Optimizing-STAR-aligner-for-Iso-Seq-data

My command looked like this:
STARlong --runMode alignReads --genomeDir ../index_japonica/ --outSAMattributes NH HI NM MD --readNameSeparator space --outFilterMultimapScoreRange 1 --outFilterMismatchNmax 2000 --scoreGapNoncan -20 --scoreGapGCAG -4 --scoreGapATAC -8 --scoreDelOpen -1 --scoreDelBase -1 --scoreInsOpen -1 --scoreInsBase -1 --alignEndsType Local --seedSearchStartLmax 50 --seedPerReadNmax 100000 --seedPerWindowNmax 1000 --alignTranscriptsPerReadNmax 100000 --alignTranscriptsPerWindowNmax 10000 --readFilesIn ../../../data/Try3_1passes/A/lq_isoforms.fasta --outFileNamePrefix A_Nipponbare_jap_lq_ --runThreadN 10 --outSAMtype BAM SortedByCoordinate

The mapping process seemed to be ok. But when I started my analysis with samtools I got some problems.
The samtools flagstat statistics are not consistent with the STAR Log output as well as with the number of input reads. Also, when I try to index the bam files I get the following error 

[E::hts_idx_push] Region 31651750..898173732 cannot be stored in a bai index. Try using a csi index with min_shift = 14, n_lvls >= 6
samtools index: failed to create index for "A_Nipponbare_jap_lq_Aligned.sortedByCoord.out.bam": Numerical result out of range

I tried to create a csi index but the same error occurs... So, now I am not sure what STARlong is doing with this long reads and what the problem could be (google could not help me with this error messages...). Or does samtools have problems with it? I also tried gmap and BBmap and for these alignment files I did not get error messages for samtools. I am using star version 2.5.2a.

I hope you have any ideas and thank you for your help already,
Stephanie

**Comment by alexdobin** [comment]
Hi Stephanie,

the genome generation for STARlong is the same as for standard STAR.

Are there any "chromosomes" in the genome that are > 800Mb long? This what samtools seems to complain about. If you are not using the latets version of STAR, please try it.

Please try to find and send me the offending reads. My guess is that you can find them with
samtools view Aligned.sortedByCoord.out.bam | awk '$4>800000000 {print}' 

Cheers
Alex

**Comment by steffi778** [comment]
Hallo Alex,

at first thank you for your answer and sorry for the late reply, I was in holiday.

I used STAR 2.5.3a (I also generated a new index etc.) and mapped my data again... but I still get the same samtools index error. When I checked the alignments for "chromosomes" greater than 800mb I did not get any reads. The max. size for this alignment was 43248498 bp.

I am wondering if it has to do something with the reference, reads or parameters I set? When I mapp my high quality PacBio reads against the "good" Oryza sativa japonica reference I can index it with samtools. When I mapp my low quality PacBio reads against the reference, indexing doesnt work anymore.

When I am using another rice reference (which is probably a "bad" reference - it was released in 2005 and since then it was not updated) for the same input data, I can neither index the high quality or low quality alignments.

It would also be great if you could update the manual with some STARlong information...

Cheers,
Stephanie

**Comment by alexdobin** [comment]
Hi Stephanie,

this looks like a bug, and may happen only for a few specific reads mapped to specific reference.
I would need an example to replicate the problem and fix it. Can you share the BAM file with me?

Cheers
Alex

**Comment by steffi778** [comment]
Hey Alex,

I tried to change the read names in the bam file and I got the following error message:

samtools view -h A_Nipponbare_jap_lq_Aligned.sortedByCoord.out.bam | sed 's/|/_/g' | samtools view -Sb - > test_lq.bam
[E::sam_parse1] CIGAR and query sequence are of different length
[W::sam_read1] parse error at line 5898
[main_samview] truncated file.

So it seems the cigar string does not match with the sequence length in some cases. I will send you the bam file right away.

Cheers,
Stephanie

**Comment by steffi778** [comment]
Thanks to Alex, we know now it works with samtools 1.3

Cheers,
Stephie

**Comment by loven-doo** [comment]
Hi Alex and Stephanie,

I have similar problem mapping long reads with STARlong (STAR 2.5.3a): while samtools-1.6 view prepares bam file it crashes the same way ("CIGAR and query sequence are of different length"). Using of samtools-1.3 doesn't help. The error message is another ("samtools view: writing to "trunc.sam" failed: Success") but output sam file is just the same.
Thank you for your help.

Cheers,
Denis

**Comment by alexdobin** [comment]
Hi Denis,

please send me the Log.out of your STAR run.

Cheers
Alex

**Comment by loven-doo** [comment]
Hi Alex,

Samtools seems to improperly prepare long CIGARs. I have converted my bam file to sam successfully using bamtools. Zip archive with my Log.out file is attached.
[Log.out.zip](https://github.com/alexdobin/STAR/files/1642243/Log.out.zip)


Cheers
Denis

**Comment by alexdobin** [comment]
Hi Denis,

sorry for the belayed reply.  Nothing suspicious with the Log.out files. Maybe it's indeed a problem with samtools and long CIGARs. If you could send me a few reads where samtools fails, I will investigate further.

Cheers
Alex

**Comment by lw3259111** [comment]
@alexdobin Hello, i meet some problem  that is similar with it (samtools v1.6, )
`[E::hts_idx_push] Region 536872513..536872647 cannot be stored in a bai index. Try using a csi index with min_shift = 14, n_lvls >= 6
samtools index: failed to create index for "sort.bam": Numerical result out of range
`
and my chromosome is more than 800M,so how can i solve the problem,?

**Comment by alexdobin** [comment]
Hi @lw3259111 

it's impossible to generate "bai" index for chromosomes larger than 2^29.
You would need to use the other index, "csi"
$ samtools index -c Aligned.sortedByCoordinate.bam

Cheers
Alex

**Comment by lw3259111** [comment]
@alexdobin Thanks ,i have solved the problem with samtools 1.3.
