### ISSUE TITLE
--genomeLoad Remove requires a readfile

### ISSUE THREAD

**Issue by Skullschildi** [alexdobin/STAR#304]
Hello there, I'm new to github and started switching from bwa to STAR for the mapping in our lab. However, I have to map several reads against one reference, so I made use of the STAR argument "--genomeLoad LoadAndKeep", having the expected result. As Space and Memory are limited, I delete the *.fastq immediately and after all the mappings are done, I want to remove the genome from Memory using the "--genomeLoad Remove" option in a subsequent instance of STAR. 
Here's the issue:
If I do not pass a  valid .fastq-file, the error Message: "EXITING because of fatal input ERROR: could not open readFilesIn=read1" is displayed and the reference is lodged in the memory.

Am I using this right? To me, my workaround seems not ideal, I would suggest the "--genomeLoad Remove" to enable STAR to ignore any necessity to pass reads.

Thank you guys for your answer,

Christian

**Comment by alexdobin** [comment]
Hi Christian

I do not see this problem with the latest version of STAR.
Please send me the Log.out file of the --genomeLoad Remove command.

Cheers
Alex

**Comment by javanOkendo** [comment]
I am also facing the same problem with the STAR. See my cord below and advice `star_index=/global5/archive/projects/project12/transcriptomics/tb_HART_FIRST_BATCH/tb_hart_fitstbatch/new_workflow/star_index

filtered_reads=/global5/archive/projects/project12/transcriptomics/tb_HART_FIRST_BATCH/tb_hart_fitstbatch/new_workflow/output/2_trimmed_output/*.fq.gz

STAR --genomeDir ${star_index} --readFilesIn ${filtered_reads} --runThreadN 4 --outSAMtype BAM SortedByCoordinate --quantMode GeneCounts 
`

**Comment by alexdobin** [comment]
Hi @javanOkendo 

please send me the Log.out file.

Cheers
Alex
