### ISSUE TITLE
Installing STAR on Mac

### ISSUE THREAD

**Issue by wen02** [alexdobin/STAR#305]
Hello,

I can't install STAR on my mac. 

I installed gcc(7.1.0). 
I have clang-802.0.42
I have llvm 4.0.1

But I get this error
**clang: error: unsupported option '-fopenmp'
make: *** [Depend.list] Error 1**

I've tried the pre-compiled and get the following:

make StarforMac
**make: *** No rule to make target `StarforMac'.  Stop.**

can you help?

**Comment by alexdobin** [comment]
Hi @wen02 

for compiling on Mac, please use from the source/ directory:
$ make STARforMacStatic CXX=/path/to/gcc

Or you can simply use the precompiled executables bin/MacOSX_x86_64/STAR or bin/MacOSX_x86_64/STARlong

Cheers
Alex

**Comment by ForgetfulCoder** [comment]
Hi Alex I tried downloading it from the executables in bin, however the file won't open
