### ISSUE TITLE
Is star able to find unknown splicing?

### ISSUE THREAD

**Issue by simon0906** [alexdobin/STAR#306]
Hi alexdobin,

First thank you for developing this tool. I used to run Tophat which is pretty slow. Now I switch to STAR because it is super fast and easy to use. But here is the problem I got: usually using tophat gave me much more isoforms of which a large proportion is unknown splicing; however, STAR seems to only give those annotated. Is there any options so that STAR can identify new junctions?

Best,
Zhenyu

**Comment by alexdobin** [comment]
Hi @simon0906 

STAR - by default - will find unannotated splice junctions, and typically it finds more unannotated junctions than TopHat. What parameters are you using, and what kind of comparisons are you making?

Cheers
Alex

**Comment by simon0906** [comment]
Hi alexdobin,

Sorry for the confusion. I'm new to RNA-seq and don't have much knowledge about how these tools work. I now know what STAR doing. I misunderstood the output of STAR by comparing it to isoforms found by Cufflinks. STAR indeed found a bit more junctions than Tophat in much less time. By the way, is there any other way to do transcript assembly other than Cufflinks because it seems to take forever.

Thank you,
Zhenyu

**Comment by alexdobin** [comment]
Hi Zhenyu,

a lot of people use StringTie that is a successor to Cufflinks, and runs much faster.
I think it needs --outSAMattrIHstart 0 .

Cheers
Alex
