### ISSUE TITLE
problem of building genome index

### ISSUE THREAD

**Issue by shahaozi77** [alexdobin/STAR#309]
I keep receiving this error message when I tried to build genome index. 
Aug 07 16:21:25 ..... started STAR run
Aug 07 16:21:25 ... starting to generate Genome files
Aug 07 16:23:04 ... starting to sort Suffix Array. This may take a long time...
Aug 07 16:23:42 ... sorting Suffix Array chunks and saving them to disk...
   Aug 07 19:05:56 ... loading chunks from disk, packing SA...
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted

the log file has been attached, anyone could help? thanks in advance
[Log.txt](https://github.com/alexdobin/STAR/files/1208252/Log.txt)

**Comment by alexdobin** [comment]
Hi @shahaozi77 

how much RAM do you have? For the human genome you would need ~32GB.
You can bring it down to 16GB with --genomeSAsparseD 2 .

Cheers
Alex

**Comment by shahaozi77** [comment]
@alexdobin thank you. but I have requested 90G RAM for this  and also added the genomeSAsparseD option. and I still saw this error message,  I have no idea what is going on here.

**Comment by alexdobin** [comment]
Hi @shahaozi77 

90G should be more than enough to index this genome. Please try to run it on a different machine.

Cheers
Alex
