### ISSUE TITLE
Command line help menu

### ISSUE THREAD

**Issue by jgbradley1** [alexdobin/STAR#31]
This is a feature request. When I run the STAR command with a typo in the parameters it automatically creates an empty Aligned.out.sam file along with several Log* files. It would be helpful if a help menu was generated instead of various empty output files.

**Comment by alexdobin** [comment]
--help is high on my TODO list, will be released in a month or so. Removing empty files on exit is a bit harder, since STAR may be exiting at different points, and I would need to keep track of which files were created when, since I do not want to remove pre-existing user files.
