### ISSUE TITLE
Is it possible to run STAR with g++ in different directory?

### ISSUE THREAD

**Issue by ybiobb** [alexdobin/STAR#310]
I've compiled STAR from source using CXX=/path/to/g++

but it doesn't seem to mean that the compiled STAR's g++ dependency has changed.

I tried to run STAR but I got the error following : 

/home01/x1477hyk/prg/STAR-STAR_2.4.2a/source/STAR: /usr/lib64/libgomp.so.1: version `GOMP_4.0' not found (required by /home01/x1477hyk/prg/STAR-STAR_2.4.2a/source/STAR)
/home01/x1477hyk/prg/STAR-STAR_2.4.2a/source/STAR: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home01/x1477hyk/prg/STAR-STAR_2.4.2a/source/STAR)
/home01/x1477hyk/prg/STAR-STAR_2.4.2a/source/STAR: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home01/x1477hyk/prg/STAR-STAR_2.4.2a/source/STAR)
/home01/x1477hyk/prg/STAR-STAR_2.4.2a/source/STAR: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.11' not found (required by /home01/x1477hyk/prg/STAR-STAR_2.4.2a/source/STAR)
/home01/x1477hyk/prg/STAR-STAR_2.4.2a/source/STAR: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.9' not found (required by /home01/x1477hyk/prg/STAR-STAR_2.4.2a/source/STAR)
/home01/x1477hyk/prg/STAR-STAR_2.4.2a/source/STAR: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home01/x1477hyk/prg/STAR-STAR_2.4.2a/source/STAR)

Is there any way to solve this problem?

**Comment by alexdobin** [comment]
Hi @DasSKim 

I think you also need to specify in LD_LIBRARY_PATH the path to the g++ libraries.
Typically, they will be located in lib64/ directory in the g++ install directory.
So, before running STAR you would need to execute:
$ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path/to/g++/install/lib64/

Cheers
Alex
