### ISSUE TITLE
Seg Fault 

### ISSUE THREAD

**Issue by sunrash** [alexdobin/STAR#312]
Hi Alex!

I used a fusion filter from Brian Haas and encountered an error (seg fault)
Brian studied the question, and it is presumed that this is a rare bug. He put you in a CC, but I'm not sure that the letter came through.

The commands to run are:

STAR --runThreadN 2 --runMode genomeGenerate --genomeDir
finspector.fa.star.idx  --genomeFastaFiles finspector.fa
--limitGenomeGenerateRAM
40419136213  --sjdbGTFfile finspector.gtf  --sjdbOverhang 100

followed by:

STAR  --runThreadN 2  --genomeDir finspector.fa.star.idx  --outSAMtype BAM
SortedByCoordinate  --readFilesIn star-fusion.fusion_evidence_reads_1.fq
star-fusion.fusion_evidence_reads_2.fq  --twopassMode Basic  --alignMatesGapMax
100000  --alignIntronMax 100000  --alignSJDBoverhangMin 10
--genomeSuffixLengthMax
10000 --limitBAMsortRAM 20000000000 --outSAMfilter
KeepAllAddedReferences  --sjdbGTFfile
finspector.gtf  --alignSJstitchMismatchNmax 5 -1 5 5

and leads to seg fault

Initial data

Fq, gtf data : http://62.64.9.41/FA.tar  

```
STAR version=STAR_2.5.3a_modified
STAR compilation time,server,dir=Thu Jun 29 12:15:36 EDT 2017 florence.cshl.edu:/sonas-hs/gingeras/nlsas_norepl/user/dobin/STAR/STAR.sandbox/source
```

Log.Out 

```
Reading genome generation parameters:
versionGenome                 20201        ~RE-DEFINED
genomeFastaFiles              /u02/trasher/JK00002/FG_B/FusionInspector/fi_workdir/finspector.fa        ~RE-DEFINED
genomeSAindexNbases           14     ~RE-DEFINED
genomeChrBinNbits             18     ~RE-DEFINED
genomeSAsparseD               1     ~RE-DEFINED
sjdbOverhang                  100     ~RE-DEFINED
sjdbFileChrStartEnd           -        ~RE-DEFINED
sjdbGTFfile                   /u02/trasher/JK00002/FG_B/FusionInspector/fi_workdir/finspector.gtf     ~RE-DEFINED
sjdbGTFchrPrefix              -     ~RE-DEFINED
sjdbGTFfeatureExon            exon     ~RE-DEFINED
sjdbGTFtagExonParentTranscripttranscript_id     ~RE-DEFINED
sjdbGTFtagExonParentGene      gene_id     ~RE-DEFINED
sjdbInsertSave                Basic     ~RE-DEFINED
genomeFileSizes               2883584   541220        ~RE-DEFINED
Genome version is compatible with current STAR version
Number of real (reference) chromosomes= 11
1       MT-CO3--MT-CO1  7326    0
2       MT-ND1--MT-TQ   6028    262144
3       MT-ND1--MTATP6P1        6637    524288
4       MT-ND4--MT-ND2  7420    786432
5       MT-ND4L--MT-RNR2        6856    1048576
6       MT-ND5--MT-CO1  8354    1310720
7       MT-ND5--MT-ND4  8190    1572864
8       MT-ND6--MT-CO1  7067    1835008
9       MT-TS1--MT-CO1  6611    2097152
10      MT-TS1--MT-CO2  5753    2359296
11      MTATP6P1--MTCO2P12      6363    2621440
--sjdbOverhang = 100 taken from the generated genome
Started loading the genome: Wed Aug 16 06:55:52 2017

Genome: size given as a parameter = 2883584
SA: size given as a parameter = 541220
/SAindex: size given as a parameter = 1
Read from SAindex: genomeSAindexNbases=14  nSAi=357913940
nGenome=2883584;  nSAbyte=541220
GstrandBit=32   SA number of indices=131204
Shared memory is not used for genomes. Allocated a private copy of the genome.
Genome file size: 2883584 bytes; state: good=1 eof=0 fail=0 bad=0
Loading Genome ... done! state: good=1 eof=0 fail=0 bad=0; loaded 2883584 bytes
SA file size: 541220 bytes; state: good=1 eof=0 fail=0 bad=0
Loading SA ... done! state: good=1 eof=0 fail=0 bad=0; loaded 541220 bytes
Loading SAindex ... done: 1565873619 bytes
Finished loading the genome: Wed Aug 16 06:55:53 2017

To accomodate alignIntronMax=100000 redefined winBinNbits=15
To accomodate alignIntronMax=100000 and alignMatesGapMax=100000, redefined winFlankNbins=4 and winAnchorDistNbins=8
Aug 16 06:55:53 ..... processing annotations GTF
Processing sjdbGTFfile=/u02/trasher/JK00002/FG_B/FusionInspector/fi_workdir/finspector.gtf, found:
                22 transcripts
                22 exons (non-collapsed)
                0 collapsed junctions
Aug 16 06:55:53 ..... finished GTF processing
Aug 16 06:55:53   Loaded database junctions from the GTF file: /u02/trasher/JK00002/FG_B/FusionInspector/fi_workdir/finspector.gtf: 0 total junctions

Aug 16 06:55:53   Finished preparing junctions
Aug 16 06:55:53 ..... finished inserting junctions into genome
Created thread # 1
Created thread # 2
Created thread # 3
Thread #1 end of input stream, nextChar=-1
Completed: thread #2
Completed: thread #3
Completed: thread #0
```

**Comment by alexdobin** [comment]
Hi @sunrash 

since the finspector.fa "genome" is very small, you would need to reduce --genomeSAindexNbases to log2(genomeLength)/2-1 ~ 7 in your case. If it still seg-faults, you may need to reduce it even more.

Typically. FI would add this small file to the whole human genome index - then you do not need to tweak this parameter.

Cheers
Alex

**Comment by alexdobin** [comment]
Hi @sunrash 

did you specify --genomeSAindexNbases 7 at the genome generation step?
I tried it for your example and did not get the error.
Please send me the Log.out file.

Cheers
Alex

**Comment by mebbert** [comment]
@alexdobin, this solved my issue, thank you.

**Comment by labstructbioinf** [comment]
I had the same problem. The "min(14, log2(GenomeLength)/2 - 1)" equation suggested that --genomeSAindexNbases should be set to 10. This, however, resulted in a segmentation fault error. Reducing the parameter to 9 solved the problem.

**Comment by alexdobin** [comment]
Hi @labstructbioinf 

this scaling is approximate, at the moment you basically need to reduce this value until the seg-fault disappears. 

Cheers
Alex

**Comment by andrewrgross** [comment]
I'm encountering this problem, but when I tried to reduce the Genome SA index, I noticed in the log file that the index was still set for 14. Any help would be appreciated. Thanks!

**Comment by alexdobin** [comment]
Hi Andrew,

please post the Log.out file.

Cheers
Alex

**Comment by andrewrgross** [comment]
I'm sorry, I realized when I was copying the log file that I was looking at the Default parameters section instead the "Final parameters after user input". This worked! Thank you so much, especially for your fast response!
