### ISSUE TITLE
Running STAR with time limit

### ISSUE THREAD

**Issue by ybiobb** [alexdobin/STAR#313]
Hi Alex,

I really appreciate for answering my issue posted before.

It worked!

But another problem occurred.

I'm running STAR with 48hrs time limit and genomeGenerate doesn't finish in 48hrs with my machine.

Is there any method to run it faster or run genomeGenerate sequentially?

My code was : 

/home01/x1477hyk/prg/STAR-2.5.3a/bin/STAR --runThreadN 8 --runMode genomeGenerate --genomeDir /scratch2/x1477hyk/STAR_test_2/genomedir --genomeFastaFiles /scratch2/x1477hyk/STAR_test_2/Homo_sapiens_assembly38.fasta

Thanks, Dan

**Comment by alexdobin** [comment]
Hi Dan,

it should not take this long, please send me the Log.out file.

Cheers
Alex

**Comment by DasSKim** [comment]
@alexdobin 
Here is my Log.out file.

Please check it.

Thaks

[Log.zip](https://github.com/alexdobin/STAR/files/1253372/Log.zip)

Dan

**Comment by alexdobin** [comment]
Hi Dan,

you are using a genome assembly with a large number of alternative loci, haplotypes and decoys. This may require much more RAM than normal assemblies. Do you have to use this assmbly? If not, I would recommend GENCODE FASTA and GTF annotations:
[ftp://ftp.sanger.ac.uk/pub/gencode/Gencode_human/release_27/GRCh38.primary_assembly.genome.fa.gz](url)
[ftp://ftp.sanger.ac.uk/pub/gencode/Gencode_human/release_27/gencode.v27.primary_assembly.annotation.gtf.gz](url)

Cheers
Alex
