### ISSUE TITLE
Which annotation is good?

### ISSUE THREAD

**Issue by simon0906** [alexdobin/STAR#314]
Hi Alex,

I used .gtf file of UCSC hg19 as annotation and got a lot of no feature alignments. Is the gtf file not good enough? Do you have any recommended human genome annotation?

Best,
Zhenyu

**Comment by alexdobin** [comment]
Hi Zhenyu,

I would recommend using "primary" GTF and FASTA from GENCODE, e.g.:

[ftp://ftp.sanger.ac.uk/pub/gencode/Gencode_human/release_27/gencode.v27.primary_assembly.annotation.gtf.gz](url)

[ftp://ftp.sanger.ac.uk/pub/gencode/Gencode_human/release_27/GRCh38.primary_assembly.genome.fa.gz](url)

Cheers
Alex
