### ISSUE TITLE
Extract fasta sequence from STAR index

### ISSUE THREAD

**Issue by Averstic** [alexdobin/STAR#317]
Hi,
I have a bit of an issue here, I lost the original fasta sequence I used to create the STAR index.
It is a custom made, spacer linked concatenation of BAC sequences and I can't confidentially recreate it as the order of the BAC sequences wasn't specified.

Is it possible to extract the original fasta sequence out of the STAR index?

**Comment by alexdobin** [comment]
Hi @Averstic 

inside the genome directory:
$ cat Genome | tr '\0\1\2\3\4' 'ACGTN'  | tr -s '\5' '\n' > G1
This will create a file where each line corresponds to a single reference (chromosome) sequence.

Next check if the number of lines in G1 and chrName.txt is the same:
$ wc -l G1 chrName.txt
G1 may contains many more lines if you included GTF or splice junctions in the genome generation. 
Cut the first lines from G1 to make the numbers the same:
$ n=`wc -l chrName.txt | cut -d' ' -f1`; head -n $n G1 > G2

Add the ">" to the chr names:
$ sed 's/^/>/' chrName.txt > chN

Interleave chrN and G2:
$ paste -d'\n' chN G2 > Genome.fa

This should restore your genome FASTA file.

Cheers
Alex
