### ISSUE TITLE
Paired-end, huge % of reads mapped to multiple loci

### ISSUE THREAD

**Issue by stanfordfp** [alexdobin/STAR#318]
Hi Alex,
After searching many rna-seq aligner, I decide to use STAR as my first RNA-seq aligner. I got 97% of reads mapped to multiple loci and 0% Uniquely mapped reads (PE). I browsed github and google group and ran STAR using SE, finally got 84.8% Uniquely mapped reads and 12.85% of reads mapped to multiple loci. I used ENCODE setting from the manual: 

STAR --genomeDir /rnaseq/star --runThreadN 10 --readFilesCommand zcat --readFilesIn /rnaseq/trim/trimmed_gmp1.fastq.gz /rnaseq/trim/trimmed_gmp2.fastq.gz --outFileNamePrefix gmp_star --outFilterType BySJout --outFilterMultimapNmax 20 --alignSJoverhangMin 8 --alignSJDBoverhangMin 1 --outFilterMismatchNmax 999 --outFilterMismatchNoverReadLmax 0.04 --alignIntronMin 20 --alignIntronMax 1000000 --alignMatesGapMax 1000000 --outFilterScoreMinOverLread 0 --outFilterMatchNminOverLread 0 --outFilterMatchNmin 0 

Here is my output log (paired end):

  Number of input reads |       56949047
                      Average input read length |       151
                                    UNIQUE READS:
                   Uniquely mapped reads number |       723
                        Uniquely mapped reads % |       0.00%
                          Average mapped length |       67.39
                       Number of splices: Total |       17
            Number of splices: Annotated (sjdb) |       0
                       Number of splices: GT/AG |       17
                       Number of splices: GC/AG |       0
                       Number of splices: AT/AC |       0
               Number of splices: Non-canonical |       0
                      Mismatch rate per base, % |       5.54%
                         Deletion rate per base |       0.00%
                        Deletion average length |       1.00
                        Insertion rate per base |       0.00%
                       Insertion average length |       0.00
                             MULTI-MAPPING READS:
        Number of reads mapped to multiple loci |       55492070
             % of reads mapped to multiple loci |       97.44%
        Number of reads mapped to too many loci |       561293
             % of reads mapped to too many loci |       0.99%
                                  UNMAPPED READS:
       % of reads unmapped: too many mismatches |       0.00%
                 % of reads unmapped: too short |       0.00%
                     % of reads unmapped: other |       1.57%
                                  CHIMERIC READS:
                       Number of chimeric reads |       0
                            % of chimeric reads |       0.00%

Here is my output log (single end):
                  Number of input reads |       56949047
                      Average input read length |       75
                                    UNIQUE READS:
                   Uniquely mapped reads number |       48313657
                        Uniquely mapped reads % |       84.84%
                          Average mapped length |       69.20
                       Number of splices: Total |       31574
            Number of splices: Annotated (sjdb) |       0
                       Number of splices: GT/AG |       30043
                       Number of splices: GC/AG |       535
                       Number of splices: AT/AC |       57
               Number of splices: Non-canonical |       939
                      Mismatch rate per base, % |       0.29%
                         Deletion rate per base |       0.00%
                        Deletion average length |       1.64
                        Insertion rate per base |       0.00%
                       Insertion average length |       1.45
                             MULTI-MAPPING READS:
        Number of reads mapped to multiple loci |       7315706
             % of reads mapped to multiple loci |       12.85%
        Number of reads mapped to too many loci |       431988
             % of reads mapped to too many loci |       0.76%
                                  UNMAPPED READS:
       % of reads unmapped: too many mismatches |       0.00%
                 % of reads unmapped: too short |       0.00%
                     % of reads unmapped: other |       1.56%
                                  CHIMERIC READS:
                       Number of chimeric reads |       0
                            % of chimeric reads |       0.00%

How can I adjust these parameters to increase Uniquely mapped reads in my paired end data? Thanks.

Feng

**Comment by roryk** [comment]
What was the command line you ran for the single end sample?

It looks like your FASTQ file names might not be pointing to the right files, one is pointing to /rnaseq/trim/ and the other one is in /trim/.

Best,

Rory

**Comment by stanfordfp** [comment]
Hi Rory,

I used the exact same command for single end sample. The paired end samples are in the sample dir, I corrected it in the previous post.

Sincerely,
Feng

**Comment by alexdobin** [comment]
Hi @stanfordfp 

please try to run both SE-read1, SE-read2 and PE mapping without --outFilterScoreMinOverLread 0 --outFilterMatchNminOverLread 0 --outFilterMatchNmin 0 (these are not from ENCODE), and post the Log.final.out files.

Cheers
Alex

**Comment by stanfordfp** [comment]
Hi Alex,

Just update this issue. It turns out my colleague gave me two exactly same files (read1 and read2) as paired-end by mistake. After I correct the data, it worked perfect. Thanks.

    Number of input reads |       30566910
                      Average input read length |       152
                                    UNIQUE READS:
                   Uniquely mapped reads number |       26824426
                        Uniquely mapped reads % |       87.76%
                          Average mapped length |       151.42
                       Number of splices: Total |       18525229
            Number of splices: Annotated (sjdb) |       18388678
                       Number of splices: GT/AG |       18328755
                       Number of splices: GC/AG |       166963
                       Number of splices: AT/AC |       17553
               Number of splices: Non-canonical |       11958
                      Mismatch rate per base, % |       0.35%
                         Deletion rate per base |       0.00%
                        Deletion average length |       1.66
                        Insertion rate per base |       0.00%
                       Insertion average length |       1.20
                             MULTI-MAPPING READS:
        Number of reads mapped to multiple loci |       2278127
             % of reads mapped to multiple loci |       7.45%
        Number of reads mapped to too many loci |       32778
             % of reads mapped to too many loci |       0.11%
                                  UNMAPPED READS:
       % of reads unmapped: too many mismatches |       0.00%
                 % of reads unmapped: too short |       4.63%
                     % of reads unmapped: other |       0.06%
                                  CHIMERIC READS:
                       Number of chimeric reads |       53846
                            % of chimeric reads |       0.18%
Sincerely,
Feng
