### ISSUE TITLE
STAR produces empty bam files

### ISSUE THREAD

**Issue by ChenMorStory** [alexdobin/STAR#321]
Hi Alex,

I'm running a STAR (2.5.3a) command, which produces empty or small Bam files on some of my input files, while working fine with others.

The output of the command shows:
> Sep 07 19:29:11 ..... started STAR run
> Sep 07 19:29:11 ..... loading genome
> Sep 07 19:29:42 ..... started 1st pass mapping
> Sep 07 19:37:04 ..... finished 1st pass mapping
> Sep 07 19:37:05 ..... inserting junctions into the genome indices
> Sep 07 19:38:39 ..... started mapping
> Sep 07 19:46:47 ..... finished successfully

However, I notice that core*.(Some number here) fileד are constantly being created, and the command doesn't actually yield the expected output.

Here's the command I'm using:
STAR --runThreadN 6 --twopassMode Basic --genomeDir %s --readFilesIn %s %s --readFilesCommand gunzip -c --outFileNamePrefix %s --outFilterType BySJout --outReadsUnmapped Fastx --outSAMtype BAM Unsorted  --outSAMmode Full  --outFilterMultimapNmax 1  --outFilterMismatchNoverLmax 0.05   --outFilterMismatchNmax 8   --alignSJoverhangMin 8   --alignSJDBoverhangMin 1  --alignIntronMin 20   --alignIntronMax 1000000   --alignMatesGapMax 1000000  --quantMode TranscriptomeSAM GeneCounts

Any ideas how to tackle this one? It's urgent to me.

Thanks in advance!
Chen

**Comment by alexdobin** [comment]
Hi Chen,

Please send me the Log.out and Log.final.out files for one of the runs where empty BAM was created.
If it does not work for only some of the input files, the problem is likely with the input formatting.

Cheers
Alex

**Comment by PersistentlyHungry** [comment]
Hi Alex,

There you go, hope you find something useful in there.

Thanks for supporting!
Chen

[SRR821602Log.final.out.txt](https://github.com/alexdobin/STAR/files/1295419/SRR821602Log.final.out.txt)
[SRR821602Log.out.txt](https://github.com/alexdobin/STAR/files/1295420/SRR821602Log.out.txt)

**Comment by alexdobin** [comment]
Hi Chen,

the Log.final.out looks OK and it should produce non-empty BAM file.
However, the Log.out file seem to be cut very early in the run, which is strange.
One possibility is that you are running out of space on the disk, and so it does not write some files but writes others. This is especially true if you running many jobs simultaneously.

Please try to re-run this case again making sure that you have enough space. If this does not help, please send me the Log.out file and the output of
$ ls -lhR
in the STAR run directory.

Cheers
Alex

**Comment by Cumol** [comment]
I am also having a similar behavior. Cleared out some disk space and re-running it now, will update once I know more

**Comment by paulmenzel** [comment]
If you do not already, please try with the latest development version from the git repository.

    $ git clone https://github.com/alexdobin/STAR/
    $ cd STAR
    $ ./bin/Linux_x86_64/STAR --version

**Comment by Cumol** [comment]
@paulmenzel @alexdobin the problem persists.

The raw files (fastq files in txt.gz format) are processed fine with Salmon so the files are fine

**Comment by paulmenzel** [comment]
Am 07.11.18 um 17:23 schrieb Muad Abd El Hay:
> @paulmenzel @alexdobin the problem persists.
> 
> The raw files (fastq files in txt.gz format) are processed fine with
> Salmon so the files are fine

Can you upload the files somewhere, so that it can be reproduced?

**Comment by alexdobin** [comment]
Hi Muad,

have you tried to map these files after unzipping? It may be that the problem is with the zcat command.

Cheers
Alex

**Comment by Cumol** [comment]
Hi @alexdobin

The GTF file was unzipped when making the genome index.

I ran STAR with the unzipped file, something is different for sure.

It still doesn't run, but I am getting `Segmentation fault (core dumped)` as error. I have seen that someone on here too, so I will try to follow that trail.

**Comment by alexdobin** [comment]
Hi Muad,

please post or e-mail the Log.out file for the seg-faulted run.

Cheers
Alex

**Comment by alexdobin** [comment]
Hi Muad,

sorry for belayed reply.
The SA file appears to be corrupted, please try to re-generate the genome and then map again.

Cheers
Alex

**Comment by lovelymaoqin** [comment]
> Hi Chen,
> 
> the Log.final.out looks OK and it should produce non-empty BAM file.
> However, the Log.out file seem to be cut very early in the run, which is strange.
> One possibility is that you are running out of space on the disk, and so it does not write some files but writes others. This is especially true if you running many jobs simultaneously.
> 
> Please try to re-run this case again making sure that you have enough space. If this does not help, please send me the Log.out file and the output of
> $ ls -lhR
> in the STAR run directory.
> 
> Cheers
> Alex

Hi Alex,

I have Aligned.sortedByCoord.out.bam file,  but there's none in the BAMsort folder. I
> $ ls -lhR

partial of the contents shows like this 
./RND_STARtmp/BAMsort/0:
total 0
./RND_STARtmp/BAMsort/1:
total 0
./RND_STARtmp/BAMsort/10:
total 0
./RND_STARtmp/BAMsort/11:
total 0
./RND_STARtmp/BAMsort/12:
total 0
./RND_STARtmp/BAMsort/13:
total 0
./RND_STARtmp/BAMsort/14:
total 0


Not sure why? 
Would you give me some suggestions?

**Comment by alexdobin** [comment]
Hi @lovelymaoqin 

please send me the Log.out file of the failed run.

Cheers
Alex

**Comment by lovelymaoqin** [comment]
Hi Alex,

 Thanks for helping me check it. Here is the Log.out file

________________________________

**Comment by alexdobin** [comment]
Hi @lovelymaoqin 

the Log.out file did not get attached, you need to do it via web, not replying to email.

Cheers
Alex

**Comment by marzie-rasekh** [comment]
I have the same issue. I used a bam file to get the fastq files. I tried both samtools fastq and bedtools bam2fastq. bowtie2 and salmon run on the fastq files but STAR finishes with no errors but gives empty files. Looks like there is something about the input files. Because on the original fastq files it was running.

**Comment by teryyoung** [comment]
I meet this issue, too. finally I found this is because that my input fastq file is not gzip format; and I didn't use --readFilesCommand paramater, but defult is `zcat`, so there isn't content input to STAR.

I used STAR-2.7.10b, its document didn't mention this defult parameter.
