### ISSUE TITLE
Fail to make STAR with g++ 4.4.7

### ISSUE THREAD

**Issue by foriin** [alexdobin/STAR#322]
Hi, Alex! I've got an issue with trying to install STAR on my institute's server:

`cc1plus: error: unrecognized command line option "-std=c++11"`

I figured out that g++ is quite old:
`g++ (GCC) 4.4.7 20120313 (Red Hat 4.4.7-17)`
But I'm not an admin, so I can't update.

I've tried to change  "-std=c++11" option to  "-std=c++0x", but I've got a new round of errors in relation to random numbers generator:

`ReadAlign.h:32: error: ISO C++ forbids declaration of 'uniform_real_distribution' with no type
ReadAlign.h:32: error: invalid use of '::'
ReadAlign.h:32: error: expected ';' before '<' token`

Can you suggest how I should modify some files to get it running?

**Comment by alexdobin** [comment]
Hi @foriin 

there are many places where STAR uses c++11 features, so it would not be possible to go back.
Please try to use pre-compiled static version of STAR in the bin/Linux_x86_64_static/ directory of the STAR distribution. Also, even without admin privileges, you can install your own version of gcc and use it for compilation.

Cheers
Alex
