### ISSUE TITLE
Mask sequences at read level

### ISSUE THREAD

**Issue by marcDabad** [alexdobin/STAR#323]
There is any possibility to add this feature:

Change sequence to lowercase (at read) to 'mask' it and aligner assume it as softclipped sequence directly

Thanks.

**Comment by alexdobin** [comment]
Hi @marcDabad 

this will only work with SAM files - in the BAM format, lower/upper cases are not supported, so I am not sure if this is a good solution. I know parsing CIGARs is not fun. I could, in principle, add another SAM tag that will list the number of bases soft-clipped on each side.

Cheers
Alex
