### ISSUE TITLE
NOT FOUND Parameters_readSAMheader.o

### ISSUE THREAD

**Issue by lv06025158** [alexdobin/STAR#326]
Hi,

   I retrieved STAR repository by using git clone and tried to make. A Stop thrown out, as follows:

make: *** No rule to make target `Parameters_readSAMheader.o', needed by `STAR'.  Stop.

    In fact, I did not find the file named Parameters_readSAMheader.o in source directory. 
Could you guys check it out? 

    Thanks!

**Comment by alexdobin** [comment]
Hi @lv06025158 

fixed the problem, please clone it again.
I would recommend using tagged releases rather than cloning the master.
Master contains the latest features, but may be unstable - it's tested less thoroughly.

Cheers
Alex
