### ISSUE TITLE
problem about Installing STAR on Mac 

### ISSUE THREAD

**Issue by karosse** [alexdobin/STAR#327]
Hello,
1.When I make STARforMacStatic CXX , I get 

/bin/sh: /usr/local/Cellar/gcc/7.2.0: is a directory
make: *** [Depend.list] Error 126

2. When I simply use the precompiled executables STAR or STARlong , I get
twopass1readsN              -1
    int: number of reads to process for the 1st step. Use very large number (or default -1) to map all reads in the first step.

For more details see:
<https://github.com/alexdobin/STAR>
<https://github.com/alexdobin/STAR/blob/master/doc/STARmanual.pdf>
can you help?

**Comment by alexdobin** [comment]
Hi @karosse 

with make you need to specify to path to the g++ binary, i.e. somethng like
$ make STARforMacStatic CXX=/usr/local/Cellar/gcc/7.2.0/bin/g++

It seems like the pre-compiled binary runs, what is the actual STAR command line that you are using?

Cheers
Alex

**Comment by karosse** [comment]
very grateful, there still exist problems.
1. when
$ make STARforMacStatic CXX=/usr/local/Cellar/gcc/7.2.0/bin/g++-7
then get
 make: *** No rule to make target `Parameters_readSAMheader.o', needed by `STARforMacStatic'.  Stop.

2.When I simply run the precompiled executables STAR or STARlong, not using any command line, STAR logout like
...
twopass1readsN              -1
    int: number of reads to process for the 1st step. Use very large number (or default -1) to map all reads in the first step.

For more details see:
<https://github.com/alexdobin/STAR>
<https://github.com/alexdobin/STAR/blob/master/doc/STARmanual.pdf>
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting  expired sessions...none found.
