### ISSUE TITLE
Inserting junctions into the genome indices   

### ISSUE THREAD

**Issue by khurryum** [alexdobin/STAR#328]
Hi, 
My job keeps getting killed after the inserting junctions into genome indices step. 
Attached are my log files and the screen output. Any help will be greatly appreciated. 
Thanks. 
[slurm-20760.out.txt](https://github.com/alexdobin/STAR/files/1360634/slurm-20760.out.txt)
[Log.out.txt](https://github.com/alexdobin/STAR/files/1360635/Log.out.txt)

**Comment by alexdobin** [comment]
Hi @khurryum 

how much RAM did you allocate for this job?
You would need to allocate at least 32GB, but it would be safer to go a bit higher, say 35GB or 40GB.

Cheers
Alex

**Comment by khurryum** [comment]
yeah, you are absolutely right. I kept allocating 8000mb for 4 cpus. It worked when I bumped it up to 16000 mb/cpu. 

Thank you for your swift response. Much appreciated.
