### ISSUE TITLE
2.4.1a --sjdbOverhang=100 is not equal to the value at the genome generation step =50

### ISSUE THREAD

**Issue by jblachly** [alexdobin/STAR#33]
The new on-the-fly sjdb options conflict with premade genomes including a GTF.

In particular, my genome is generated with --sjdbOverhang 50 ; however the default value for sjdbOverhang=100 at the mapping stage conflicts with this and the run is aborted:

    $ STAR --genomeDir ~/data/ref/indices/STAR/GRCh37.NCBI.STAR50 --readFilesIn fastqgz/R1.fastq.gz fastqgz/R2.fastq.gz --readFilesCommand zcat --outFileNamePrefix SID/
    
    Apr 20 15:25:14 ..... Started STAR run
    Apr 20 15:25:14 ..... Loading genome
    
    EXITING because of fatal PARAMETERS error: present --sjdbOverhang=100 is not equal to the value at the genome generation step =50
    SOLUTION:
    
    Apr 20 15:25:14 ...... FATAL ERROR, exiting
    $

This can be mitigated by including --sjdbOverhang N at the mapping step, where N is how your genome was generated.

Solution should be disabling that check if no GTF file is included on-the-fly at the mapping step.

**Comment by alexdobin** [comment]
Thanks for the bug report - fixed in 2.4.1b.
