### ISSUE TITLE
Integrate patches from BioBuilds.org

### ISSUE THREAD

**Issue by paulmenzel** [alexdobin/STAR#330]
I noticed that [BioBuilds.org](https://biobuilds.org/) carries [three patches for STAR](https://github.com/biobuilds/biobuilds/tree/master/star/2.5.2b). Maybe they can be included.

**Comment by alexdobin** [comment]
Hi Paul,

thanks for the suggestion, and sorry for the long delay.
I am preparing a new release and included the clang-const-ness.patch patch and osx-link.patch .

clang-pointer-arith.patch is not needed anymore as I removed the function it patches. 

compile-id.patch is biobuild specific. 

local-htslib.patch is to make use  of local install of htslib, I am not ready for that yet.

Cheers
Alex
