### ISSUE TITLE
Chimeric alignment fails in paired-end mode, but succeeds in single-end mode

### ISSUE THREAD

**Issue by suhrig** [alexdobin/STAR#333]
Dear Alex,

I compared the chimeric alignments of STAR to the alignments of other fusion detection algorithms to find out, which reads STAR misses.

I noticed that for paired-end data, STAR often fails to determine a chimeric alignment, if the mates overlap to a large extent (small insert size). This is a known issue that has been reported previously in the bug tracker.

Some reads however do not overlap and still fail to be aligned. Interestingly, they can be aligned correctly by STAR in single-end mode.

I could give you a long list of examples, but I will limit myself to a few interesting cases that arise from validated fusions and that can be uniquely mapped by Blat with no even remotely similar hits elsewhere in the genome.

Example1 (interleaved FastQ):
```
@ERR358488.24040047/1 maps to chr1:107081309 with cigar 99M1S
CGGGGGGCCGAGGTGGGAGGATCACTTGAACCCAAAAGCGGAGGTTGCAGTGAGGCGAGATCATGCCATTGCCCTCCAGCATGAAGGGCTGGAGCGAGAA
+
CCCFFFDDDDDDD@DDDDDDDDDDDDDDDDDDDD8ABDBDDDDD?BDDDDCDDDDDDDDDBDDDDDDDDDDDDDDBDDDDDDDDDDDDBDDCDDDDDDBD
@ERR358488.24040047/2 maps to chr20:46131127 with cigar 100M
CTTTTGAAAGCTCCCCGCGTCGTCCTCCTGCTGCCCCGGCTCCTTAGCAGCTTCTGGGACGCACGGGAGGGAAAAGCCGCGGGGACCCCCCCCACCCCAG
+
CCCFFFFFHDHHHJJJIJJJJJJJJJJJJJJJJJJJJJJIGHFFFFFFEEEEEDDDDDDDDDDDDDDBDDDDDBDDDDDDDDDDBBDDDDDDDBBDDDDB
```

Example 2:
```
@ERR358488.37382477/1 maps to chr1:106759085 with cigar 100M
CTAGGATTCATGTCAAGTTGGTCCTCAAGTCTCAGGAAAGCTGGCTAGGGTGGATGGAGTCTCCTCTGCTCTTGTCCCATATCACACTTCAAATGAAGGA
+
CCCFFFFFHHGHHJJJJHIJIJIJJJJJJHIJJJIIIJJJJJIJJJJJIJGHIHIGJIIGIJGJJJJIJHHHHHHFFFFFFEDEECEDDDDCCCCDDCCB
@ERR358488.37382477/2 maps to chr3:63898402 with cigar 71M29S
CGCAGCCCCAGCGGCAGCAGCACCCGCCACCGCCGCCACGGCGCACACGGCCGGAGGACGGGGGGCCGGGCCGCGGCGCCACCTCGGCAGCCGGCATGGC
+
@@<;?)=?DDF?<@1?C1?F>GFD)08@<78;@8BFDDC//38875&<BB@8@###############################################
```

I noticed that in many cases one of the mates cannot be aligned fully (10-30 bases are clipped). Still this does not hold true in all cases and also does not explain why alignment in single-end mode is successful. Doesn't STAR revert to the same algorithm it uses for single-end alignment, when it looks for discordant mates? Can STAR be improved to also find these alignments when run in paired-end mode?

On a related note, here is a split-read that is not aligned, even though it has long, uniquely mapping stretches in both fused genes according to Blat (ARID1A and DOT1L):
```
CAGAAAGCGGAGAGTCACAGCGGGGCCAGGCCCTGGGGAGCGGAGCCTCCACCGCCCCCCTCATTCCCAGGATAAACATCACGATGCTGCTCATGAAATCATCGAGACCATCCGATGGGTCTGTGAAGAAATCCCGGATCTCAAGCTCGCT
```

All tests were done with STAR 2.5.3a using gene model Gencode V19 and assembly hs37d5 and the following parameters:
`--runThreadN 8 --genomeDir ... --genomeLoad NoSharedMemory --readFilesIn ... --outStd BAM_Unsorted --outSAMtype BAM Unsorted SortedByCoordinate --outSAMunmapped Within         --outFilterMultimapNmax 1 --outFilterMismatchNmax 3 --outFilterMismatchNoverLmax 0.3 --alignIntronMax 500000 --alignMatesGapMax 500000 --chimSegmentMin 10 --chimJunctionOverhangMin 10 --chimScoreMin 1 --chimScoreDropMax 30 --chimScoreJunctionNonGTAG 0 --chimScoreSeparation 1 --alignSJstitchMismatchNmax 5 -1 5 5 --chimSegmentReadGapMax 3 --chimMainSegmentMultNmax 10 --limitBAMsortRAM 110000000000`

Let me know, if you need further information.

Kind regards,
Sebastian

**Comment by alexdobin** [comment]
Hi Sebastian,

thanks for the interesting examples.

Example 1. In this case the problem is that there is a non-chimeric alignment with 100b of one mate mapped, and only 9b of the other mate mapped, with a long gap (~280kb) between mates. If you prohibit long gaps between mates with --alignIntronMax 50000, you will see the chimeric alignment.
Are you seeing a lot of cases like this - i.e. both mates map well and uniquely if mapped separately, but there is no chimeric output? I have to think if I can modify my chimeric algorithm to detect them.

Example 2. This can be recovered by increasing --chimScoreDropMax to >=37 , which allows chimeras with poorer alignment scores to be output.

Example 3. This can be recovered by reducing --alignSplicedMateMapLminOverLmate from the default 0.66. Any value below 0.56 will work in this case. This parameter defines the minimum mapped length of a spliced alignment. In general, for chimeric detection, I would recommend setting this value low, maybe even to 0.

Cheers
Alex

**Comment by suhrig** [comment]
Hi Alex,

This is indeed a phenomenon that affects quite a bunch of reads. Here are some more examples.
[unmapped_in_PE_mode_but_mapped_in_SE_mode.tar.gz](https://github.com/alexdobin/STAR/files/1480784/unmapped_in_PE_mode_but_mapped_in_SE_mode.tar.gz)

This time I did not pick reads from validated fusions, but simply took all reads where both mates map with CIGAR string 100M when using single-end mode. This applies to about 10^-4 of all reads that are unmapped in PE mode. Considering that not all reads have a CIGAR string of 100M, this can be considered a lower boundary.

When I set --alignIntronMax to 50000, --chimScoreDropMax to 37, and --alignSplicedMateMapLminOverLmate to 0 (thanks for the hint BTW), about 1/4 of the reads in the example file can be aligned as either chimeric or normal.

I hope this helps quantifying the problem,
Sebastian

**Comment by alexdobin** [comment]
Hi  Sebastian,

thanks for the estimate. I will look into fixing this problem.

Cheers
Alex

**Comment by suhrig** [comment]
Reviving this old issue ...

Thanks again for your advice regarding the optimized alignment parameters. I definitely see an overall improvement in the number of supporting reads. However, I noticed that some fusions lose support (in some cases to the extent that driver fusions lose almost all reads). I understand that "turning a knob" in one direction to improve one aspect usually comes at the expense of another. There is no infallible setting; it's always a balance. Nevertheless I investigated why alignment deteriorates for some chimeric reads, because it could serve as a basis for improvement of the alignment algorithm, or maybe you have some more advice to optimize even further.

I played around with `--alignSplicedMateMapLminOverLmate` and `--peOverlapNbasesMin`, which bring about the biggest improvement when aligning in single-end vs. paired-end mode. All tests were done with STAR 2.7.3a and hs37d5. I collected a few examples that fail to align properly in paired-end mode:

The following pair of reads fails to align the chimeric segment of read when `--alignSplicedMateMapLminOverLmate` is set to 0.5, because STAR prefers an alignment where 10 bases of the chimeric segment are spliced to an adjacent exon instead of to a different gene:
```
@SRR064286.7128798/1
GTGAGGATGGAGGAGCGTGAGGGGCAGCACATGGGTGTGGTCACGAAGGC
+
B@@9@B?BBB?BA?BAB>B9@A?A@:@??>7>A?A4A:A?:>>;=69;=>
@SRR064286.7128798/2
CTCCCAGCTGCGCAGGGCCTGCCAGGTGGCGCTCGGTTCCATGCAGGTGA
+
BBBBBBABABBA??A>?AA???A>??5=>@>>>>=A4===9=>99>>4>3
```

The next example is basically the same. When `--alignSplicedMateMapLminOverLmate` is < 0.66, a linear alignment with mismatches and clipped bases is preferred over a (correct) chimeric alignment:
```
@SRR064286.4177094/1
GGGGGGAAGGGGGGGCACGAAGGCTCATCATTCAAAATAAAACAAAATAA
+
BBBBBB=?BBBAA@A@A@A==@@@A>>@=>AA?@>:>A>:>==@???@@A
@SRR064286.4177094/2
GTGGTATTTGTCGAAGTTGATCCGGTGGTGATAGCATTGCTTTCGTGTAA
+
BBBB@BCBBB@BB><B?BBBAAABB:BA5A>=?>:6>@??@BA?A;@94:
```

And a third example: When `--alignSplicedMateMapLminOverLmate` is < 0.53, then instead of the (correct) chimeric alignment, STAR generates a linear alignment involving an adjacent exon (but only three bases of the chimeric segment are aligned to that exon and the rest is clipped):
```
@D9NJBVN1:309:D2621ACXX:7:2316:7345:38463/1
CTCTTGTAAGGAGGACAAGTCCAACTATTAAATTATTGAAGTGCAGCCCTTTGGATGTTCCACCAAAAGAACAGTAAATCACCTCAGCAACCTTTGGAGG
+
CCCFFFFFHHGHHJJJJJDIJJJJIJJJJJJJJJIIIGIIJJGEGHIJJJJIIFGGIHIIJIIHIIEHHJIJHHHAEHFFFFEECEEEEDDDDDDDDDDD
@D9NJBVN1:309:D2621ACXX:7:2316:7345:38463/2
CACAAATTGACGCAAATAGCGAAAGTAGTCATCAAAATCTGTGAACATGAGTTACAGATGTAGAGCTAAAACGACTGAAGGATGCTTTCAAGAGGACCTG
+
B@CFFFFFHGHHHIIGIGGIJIIIJHIJIIJJJJJJJJIIJJJIIJJJJJHHIJJHIIIJJFIJFIJHHHHFFFDDDEDDDDDDDDEDDDDDDDDBDDDD
```

This one is similar in effect, only that here `--peOverlapNbasesMin` is the culprit. When `--peOverlapNbasesMin` is used, a longer linear alignment with mismatches is preferred over a local chimeric alignment:
```
@SRR064286.5647586/1
CTTGCTTGTAAATGGGAAGTTTGGCTTATTTATCTCAGAAAGAGATCTTG
+
BCCCCCCCBCBACCCB>BBBCCCCBCBABCBABBCBABABAAA@>ABBBB
@SRR064286.5647586/2
TTCCCATTTACAAGCAAGATCTCTTTCTGAGATAAATAAGCCAAACTTCC
+
BCBBBBBBBBBBBBBBBBABBBBBBBBBB@B@AA@@BA@A@@@=>=A@?=
```

The following pair of reads is only aligned correctly in single-end mode. In paired-end mode, if `--peOverlapNbasesMin` is used, it is not aligned at all, which I find strange since the purpose of the parameter is to simulate single-end alignment. Otherwise (paired-end without `--peOverlapNbasesMin`), an erroneous chimeric alignment is produced:
```
@1WN/1
GTGCTCCTTTTGCTTTCCTCTGCCAGTCCCATACAGTAAGCATATGCTCATTGGAGTCATCAATAACACATAAATGAACACCTGAATCTGCTTTTGAAA
+
BC@DFFFFGGHFHIIJIJJJJIIJJJHIIJIIIGJJJIJIEIIJJIJJJJHIIIJJHHJGIJJJIJJJIIIJJJGHIJJIHHHHFFFDFFFEEEEEDDD
@1WN/2
TGGACTTGGCACTTTTGAGCGTGGAGTAGGATGCCTGGACTTTTCAAAAGCAGATTCAGGTGTTCATTTATGTGTTATTGATGACTCCAATGAGCATATGC
+
CCCFFFFFHHGGGJIJIIDGIGHIGH?CGH@FHHGIJIIJIJJIHGGIJJIIIHIJJJJJ=CCHGGHHHCHG?EADFDFFFEEDECCEDDDDDDDDDDDED
```

The following pair is aligned, but the supplementary alignment is missing, when `--peOverlapNbasesMin` is used:
```
@D9NJBVN1:309:D2621ACXX:7:2211:13624:96273/1
GTGAACGGAAAAGCTGGGAACCTTTCTTGCAAAAAAAAAGAAGCAAGTTCCGAAGTTCACTCTTGATTGCACCCACCCTGTAGAAGATGGAATCATGGAT
+
@?@DBDFFFAHFHIGEGICFGHAH@HG>FHGIGHGEFAFH?GCCEAEEHF;9B?C?@>;CC@CCCCCCCCACC??<<BBCC>ADCC>CCCCCCCCCCCCC
@D9NJBVN1:309:D2621ACXX:7:2211:13624:96273/2
CTCCACCAAGGTTCCCAGCTTTTCCGTTCACTTTGATCCTTTCTTGCAAAAACTGCTCAAAATTGGCAGCATCCATGATTCCATCTTCTACAGGGTGGGT
+
@@@DDFDFHHDAFEIDFHHHHICHHDFH@EGCGHGGBFEHHC?GBFGGHGHGHEGG@FG=CFHGIIIGGIE>AEHGHFEFFEFBDECEE;@CCCC5;=;8
```

If you have some time to kill and track down the cause of these alignment mistakes, I would be happy to learn about it. The most frequent case of incorrect alignment seems to be caused by `--alignSplicedMateMapLminOverLmate`, where STAR prefers a (poor-quality) linear alignment over a chimeric one, because it happens to find a few matching bases further downstream. A conceivable solution would be to have two separate parameters: one for normal alignment (`--alignSplicedMateMapLminOverLmate` = 0.66) and one for chimeric alignment (e.g., `--chimAlignSplicedMateMapLminOverLmate` = 0.5), such that the alignment quality of normal reads is not impaired, but chimeric alignment can be more flexible.

**Comment by suhrig** [comment]
Important update: Apparently, all the alignment errors introduced by tinkering with `--alignSplicedMateMapLminOverLmate` disappear when the new chimeric alignment detection is used (`--chimMultimapNmax`). Only the issues relating to `--peOverlapNbasesMin` remain.

**Comment by alexdobin** [comment]
Hi Sebastian,

thanks a lot for a thoughtful and thorough investigation. 

It also came up in my discussions with Brian Haas that --alignSplicedMateMapLminOverLmate negatively affects a number of fusions.

--alignSplicedMateMapLminOverLmate and --alignSplicedMateMapLmin define the minimum length of a spliced alignment for each mate. This was intended for non-chimeric alignments, to prevent a situation where only a small portion of a mate maps with a splice junction. For instance, if you have a 100b mate, and only 40b of it maps with a splice junction, it will not be allowed with the default --alignSplicedMateMapLminOverLmate 0.66
This works to prevent false splice junctions in normal reads, however, it does not work for chimeric reads, where we expect that only a portion of a mate maps non-chimerically. I suggest relaxing this requirement with --alignSplicedMateMapLminOverLmate 0 and --alignSplicedMateMapLmin 30, which would allow spliced segments as short as 30b. This may result in some incorrect novel splices for normal alignments, however, I believe this effect would be small.

I have other complaints about the --peOverlapNbasesMin option, so I need to review that code. Let's start with one of the examples where you see this problem, could you run it 3 times: (i) with this option, (ii) without it, (iii) as single end, and post the normal SAM alignments and the chimeric ones?

Thanks a lot!
Alex

**Comment by suhrig** [comment]
>  --alignSplicedMateMapLminOverLmate 0 and --alignSplicedMateMapLmin 30

Makes sense, since the confidence in an alignment does not increase as a function of the fraction of the read length but as a function of the total length of the alignment. The `...OverLmate` parameter affects longer reads harder, which is unjustified. Thanks for the advice. I can give this a try.

> about the --peOverlapNbasesMin option
> could you run it 3 times: (i) with this option, (ii) without it, (iii) as single end

The alignments of all of the three examples are given below.

I added a fourth time: single-end with manually merged reads. This one shows that usually `--peOverlapNbasesMin` is actually not to blame, because it faithfully recapitulates the single-end alignment of the merged reads. Only in the second example, the parameter causes STAR to misbehave (no alignment at all), but this one is not even related to chimeric alignment, strictly speaking.

So the real question is: Why do paired-end reads - when aligned in single-end mode - produce a different alignment than when I manually merge the reads and then align the merged reads in single-end mode? The answer may not be worth investigating. I could imagine that these are edge cases, which one simply cannot really do much about. Anyhow, for documentary purposes, here are the alignments:

**FIRST EXAMPLE**

paired-end
```
SRR064286.5647586	163	1	94342719	255	23S27M	=	94342711	41	CTTGCTTGTAAATGGGAAGTTTGGCTTATTTATCTCAGAAAGAGATCTTG	BCCCCCCCBCBACCCB>BBBCCCCBCBABCBABBCBABABAAA@>ABBBB	NH:i:1	HI:i:1	AS:i:73	nM:i:1	NM:i:0	SA:Z:1,94342742,+,23M27H,255,0;
SRR064286.5647586	83	1	94342711	255	1S49M	=	94342719	-41	GGAAGTTTGGCTTATTTATCTCAGAAAGAGATCTTGCTTGTAAATGGGAA	=?@A=>=@@@A@AB@@AA@B@BBBBBBBBBBABBBBBBBBBBBBBBBBCB	NH:i:1	HI:i:1	AS:i:73	nM:i:1	NM:i:1
SRR064286.5647586	2209	1	94342742	255	23M27H	=	94342711	0	CTTGCTTGTAAATGGGAAGTTTG	BCCCCCCCBCBACCCB>BBBCCC	NH:i:1	HI:i:1	AS:i:22	nM:i:0	NM:i:0	SA:Z:1,94342719,+,23S27M,255,0;
```

paired-end + `--peOverlapNbasesMin`
```
SRR064286.5647586	163	1	94342711	255	15S35M	=	94342711	49	CTTGCTTGTAAATGGGAAGTTTGGCTTATTTATCTCAGAAAGAGATCTTG	BCCCCCCCBCBACCCB>BBBCCCCBCBABCBABBCBABABAAA@>ABBBB	NH:i:1	HI:i:1	AS:i:79	nM:i:2	NM:i:1
SRR064286.5647586	83	1	94342711	255	1S49M	=	94342711	-49	GGAAGTTTGGCTTATTTATCTCAGAAAGAGATCTTGCTTGTAAATGGGAA	=?@A=>=@@@A@AB@@AA@B@BBBBBBBBBBABBBBBBBBBBBBBBBBCB	NH:i:1	HI:i:1	AS:i:79	nM:i:2	NM:i:1
```

single-end
```
SRR064286.5647586	16	1	94342711	255	1S49M	*	0	0	GGAAGTTTGGCTTATTTATCTCAGAAAGAGATCTTGCTTGTAAATGGGAA	=?@A=>=@@@A@AB@@AA@B@BBBBBBBBBBABBBBBBBBBBBBBBBBCB	NH:i:1	HI:i:1	AS:i:46	nM:i:1	NM:i:1
SRR064286.5647586	2048	1	94342742	255	19M31H	*	0	0	CTTGCTTGTAAATGGGAAG	BCCCCCCCBCBACCCB>BB	NH:i:1	HI:i:1	AS:i:18	nM:i:0	NM:i:0	SA:Z:1,94342715,+,19S31M,255,0;
SRR064286.5647586	0	1	94342715	255	19S31M	*	0	0	CTTGCTTGTAAATGGGAAGTTTGGCTTATTTATCTCAGAAAGAGATCTTG	BCCCCCCCBCBACCCB>BBBCCCCBCBABCBABBCBABABAAA@>ABBBB	NH:i:1	HI:i:1	AS:i:30	nM:i:0	NM:i:0	SA:Z:1,94342742,+,19M31H,255,0;
```

single-end + manually merged
```
SRR064286.5647586	0	1	94342711	255	15S49M	*	0	0	CTTGCTTGTAAATGGGAAGTTTGGCTTATTTATCTCAGAAAGAGATCTTGCTTGTAAATGGGAA	*	NH:i:1	HI:i:1	AS:i:46	nM:i:1	NM:i:1
```

**SECOND EXAMPLE**

paired-end
```
1WN	2129	3	31311802	255	81H17M1S	2	42513468	0	GGAAAGCAAAAGGAGCAC	JIJIIHFHGGFFFFD@CB	NH:i:1	HI:i:1	AS:i:16	nM:i:0	NM:i:0	SA:Z:2,42513509,-,11M1847N70M18S,255,1;
1WN	163	2	42513468	255	52M1847N49M	=	42513509	1969	TGGACTTGGCACTTTTGAGCGTGGAGTAGGATGCCTGGACTTTTCAAAAGCAGATTCAGGTGTTCATTTATGTGTTATTGATGACTCCAATGAGCATATGC	CCCFFFFFHHGGGJIJIIDGIGHIGH?CGH@FHHGIJIIJIJJIHGGIJJIIIHIJJJJJ=CCHGGHHHCHG?EADFDFFFEEDECCEDDDDDDDDDDDED	NH:i:1	HI:i:1	AS:i:177	nM:i:3	NM:i:2
1WN	83	2	42513509	255	11M1847N70M18S	=	42513468	-1969	TTTCAAAAGCAGATTCAGGTGTTCATTTATGTGTTATTGATGACTCCAATGAGCATATGCTTACTGTATGGGACTGGCAGAGGAAAGCAAAAGGAGCAC	DDDEEEEEFFFDFFFHHHHIJJIHGJJJIIIJJJIJJJIGJHHJJIIIHJJJJIJJIIEIJIJJJGIIIJIIHJJJIIJJJJIJIIHFHGGFFFFD@CB	NH:i:1	HI:i:1	AS:i:177	nM:i:3	NM:i:1	SA:Z:3,31311802,-,81H17M1S,255,0;
```

paired-end + `--peOverlapNbasesMin`
```
1WN	77	*	0	0	*	*	0	0	GTGCTCCTTTTGCTTTCCTCTGCCAGTCCCATACAGTAAGCATATGCTCATTGGAGTCATCAATAACACATAAATGAACACCTGAATCTGCTTTTGAAA	BC@DFFFFGGHFHIIJIJJJJIIJJJHIIJIIIGJJJIJIEIIJJIJJJJHIIIJJHHJGIJJJIJJJIIIJJJGHIJJIHHHHFFFDFFFEEEEEDDD	NH:i:0	HI:i:0	AS:i:192	nM:i:4	uT:A:2
1WN	141	*	0	0	*	*	0	0	TGGACTTGGCACTTTTGAGCGTGGAGTAGGATGCCTGGACTTTTCAAAAGCAGATTCAGGTGTTCATTTATGTGTTATTGATGACTCCAATGAGCATATGC	CCCFFFFFHHGGGJIJIIDGIGHIGH?CGH@FHHGIJIIJIJJIHGGIJJIIIHIJJJJJ=CCHGGHHHCHG?EADFDFFFEEDECCEDDDDDDDDDDDED	NH:i:0	HI:i:0	AS:i:192	nM:i:4	uT:A:2
```

single-end
```
1WN	16	2	42513509	255	11M1847N87M1S	*	0	0	TTTCAAAAGCAGATTCAGGTGTTCATTTATGTGTTATTGATGACTCCAATGAGCATATGCTTACTGTATGGGACTGGCAGAGGAAAGCAAAAGGAGCAC	DDDEEEEEFFFDFFFHHHHIJJIHGJJJIIIJJJIJJJIGJHHJJIIIHJJJJIJJIIEIJIJJJGIIIJIIHJJJIIJJJJIJIIHFHGGFFFFD@CB	NH:i:1	HI:i:1	AS:i:93	nM:i:2	NM:i:2
1WN	0	2	42513468	255	52M1847N49M	*	0	0	TGGACTTGGCACTTTTGAGCGTGGAGTAGGATGCCTGGACTTTTCAAAAGCAGATTCAGGTGTTCATTTATGTGTTATTGATGACTCCAATGAGCATATGC	CCCFFFFFHHGGGJIJIIDGIGHIGH?CGH@FHHGIJIIJIJJIHGGIJJIIIHIJJJJJ=CCHGGHHHCHG?EADFDFFFEEDECCEDDDDDDDDDDDED	NH:i:1	HI:i:1	AS:i:96	nM:i:2	NM:i:2
```

single-end + manually merged
```
1WN	0	2	42513468	255	52M1847N87M1S	*	0	0	TGGACTTGGCACTTTTGAGCGTGGAGTAGGATGCCTGGACTTTTCAAAAGCAGATTCAGGTGTTCATTTATGTGTTATTGATGACTCCAATGAGCATATGCTTACTGTATGGGACTGGCAGAGGAAAGCAAAAGGAGCAC	*	NH:i:1	HI:i:1	AS:i:132	nM:i:3	NM:i:3
```

**THIRD EXAMPLE**

paired-end
```
D9NJBVN1:309:D2621ACXX:7:2211:13624:96273	2129	5	87880987	255	69H14M17S	1	6253057	0	TGCAAGAAAGGTTCCCAGCTTTTCCGTTCAC	GHF>GH@HAHGFCIGEGIHFHAFFFDBD@?@	NH:i:1	HI:i:1	AS:i:13	nM:i:0	NM:i:0	SA:Z:1,6257724,-,69M31S,255,1;
D9NJBVN1:309:D2621ACXX:7:2211:13624:96273	163	1	6253057	255	58M4597N42M	=	6257724	4736	CTCCACCAAGGTTCCCAGCTTTTCCGTTCACTTTGATCCTTTCTTGCAAAAACTGCTCAAAATTGGCAGCATCCATGATTCCATCTTCTACAGGGTGGGT	@@@DDFDFHHDAFEIDFHHHHICHHDFH@EGCGHGGBFEHHC?GBFGGHGHGHEGG@FG=CFHGIIIGGIE>AEHGHFEFFEFBDECEE;@CCCC5;=;8	NH:i:1	HI:i:1	AS:i:166	nM:i:1	NM:i:0
D9NJBVN1:309:D2621ACXX:7:2211:13624:96273	83	1	6257724	255	69M31S	=	6253057	-4736	ATCCATGATTCCATCTTCTACAGGGTGGGTGCAATCAAGAGTGAACTTCGGAACTTGCTTCTTTTTTTTTGCAAGAAAGGTTCCCAGCTTTTCCGTTCAC	CCCCCCCCCCCCC>CCDA>CCBB<<??CCACCCCCCCC@CC;>@?C?B9;FHEEAECCG?HFAFEGHGIGHF>GH@HAHGFCIGEGIHFHAFFFDBD@?@	NH:i:1	HI:i:1	AS:i:166	nM:i:1	NM:i:1	SA:Z:5,87880987,-,69H14M17S,255,0;
```

paired-end + `--peOverlapNbasesMin`
```
D9NJBVN1:309:D2621ACXX:7:2211:13624:96273	163	1	6253057	255	58M4597N42M	=	6257724	4736	CTCCACCAAGGTTCCCAGCTTTTCCGTTCACTTTGATCCTTTCTTGCAAAAACTGCTCAAAATTGGCAGCATCCATGATTCCATCTTCTACAGGGTGGGT	@@@DDFDFHHDAFEIDFHHHHICHHDFH@EGCGHGGBFEHHC?GBFGGHGHGHEGG@FG=CFHGIIIGGIE>AEHGHFEFFEFBDECEE;@CCCC5;=;8	NH:i:1	HI:i:1	AS:i:166	nM:i:1	NM:i:0
D9NJBVN1:309:D2621ACXX:7:2211:13624:96273	83	1	6257724	255	69M31S	=	6253057	-4736	ATCCATGATTCCATCTTCTACAGGGTGGGTGCAATCAAGAGTGAACTTCGGAACTTGCTTCTTTTTTTTTGCAAGAAAGGTTCCCAGCTTTTCCGTTCAC	CCCCCCCCCCCCC>CCDA>CCBB<<??CCACCCCCCCC@CC;>@?C?B9;FHEEAECCG?HFAFEGHGIGHF>GH@HAHGFCIGEGIHFHAFFFDBD@?@	NH:i:1	HI:i:1	AS:i:166	nM:i:1	NM:i:1
```

single-end
```
D9NJBVN1:309:D2621ACXX:7:2211:13624:96273	2064	5	87880987	255	69H14M17S	*	0	0	TGCAAGAAAGGTTCCCAGCTTTTCCGTTCAC	GHF>GH@HAHGFCIGEGIHFHAFFFDBD@?@	NH:i:1	HI:i:1	AS:i:13	nM:i:0	NM:i:0	SA:Z:1,6257724,-,69M31S,255,1;
D9NJBVN1:309:D2621ACXX:7:2211:13624:96273	16	1	6257724	255	69M31S	*	0	0	ATCCATGATTCCATCTTCTACAGGGTGGGTGCAATCAAGAGTGAACTTCGGAACTTGCTTCTTTTTTTTTGCAAGAAAGGTTCCCAGCTTTTCCGTTCAC	CCCCCCCCCCCCC>CCDA>CCBB<<??CCACCCCCCCC@CC;>@?C?B9;FHEEAECCG?HFAFEGHGIGHF>GH@HAHGFCIGEGIHFHAFFFDBD@?@	NH:i:1	HI:i:1	AS:i:65	nM:i:1	NM:i:1	SA:Z:5,87880987,-,69H14M17S,255,0;
D9NJBVN1:309:D2621ACXX:7:2211:13624:96273	0	1	6253057	255	58M4597N42M	*	0	0	CTCCACCAAGGTTCCCAGCTTTTCCGTTCACTTTGATCCTTTCTTGCAAAAACTGCTCAAAATTGGCAGCATCCATGATTCCATCTTCTACAGGGTGGGT	@@@DDFDFHHDAFEIDFHHHHICHHDFH@EGCGHGGBFEHHC?GBFGGHGHGHEGG@FG=CFHGIIIGGIE>AEHGHFEFFEFBDECEE;@CCCC5;=;8	NH:i:1	HI:i:1	AS:i:99	nM:i:0	NM:i:0
```

single-end + manually merged
```
D9NJBVN1:309:D2621ACXX:7:2211:13624:96273	16	1	6253057	255	58M4597N81M31S	*	0	0	CTCCACCAAGGTTCCCAGCTTTTCCGTTCACTTTGATCCTTTCTTGCAAAAACTGCTCAAAATTGGCAGCATCCATGATTCCATCTTCTACAGGGTGGGTGCAATCAAGAGTGAACTTCGGAACTTGCTTCTTTTTTTTTGCAAGAAAGGTTCCCAGCTTTTCCGTTCAC	*	NH:i:1	HI:i:1	AS:i:136	nM:i:1	NM:i:1
```

**Comment by alexdobin** [comment]
Hi Sebastian,

very interesting, thanks!
I have looked into the 2nd case, and it seems to map fine with `--peOverlapNbasesMin 10`
```
1       163     chr2    42513468        255     52M1847N49M     =       42513509        1986    TGGACTTGGCACTTTTGAGCGTGGAGTAGGATGCCTGGACTTTTCAAAAGCAGATTCAGGTGTTCATTTATGTGTTATTGATGACTCCAATGAGCATATGC     *       NH:i:1  HI:i:1  AS:i:192        nM:i:4
1       83      chr2    42513509        255     11M1847N87M1S   =       42513468        -1986   TTTCAAAAGCAGATTCAGGTGTTCATTTATGTGTTATTGATGACTCCAATGAGCATATGCTTACTGTATGGGACTGGCAGAGGAAAGCAAAAGGAGCAC       *       NH:i:1  HI:i:1  AS:i:192        nM:i:4
```

Cheers
Alex

**Comment by suhrig** [comment]
> I have looked into the 2nd case, and it seems to map fine with `--peOverlapNbasesMin 10`

You're right, I used `--outFilterMismatchNmax 3` in addition, which caused the read to be dropped, when the peOverlap parameter is used, because it has 4 mismatches. So again, not really peOverlap to blame here. I think this issue can finally be closed, since the new chimeric detection and the parameters recommended by you solve most of the issues. Thanks again for all your help!
