### ISSUE TITLE
Mapping to new "chromosome" gives different results

### ISSUE THREAD

**Issue by RNAseq-er** [alexdobin/STAR#335]
While mapping an experimental dataset to the human genome, I found an interesting chimera (gene1/gene2) and decided to see if gene1 also interacted with other genes in some of the other sets of RNA seq data I have. 

I thought an easy way to do this would be to create a new genome, where I just appended the gene1 sequence as a new chromosome at the end of the human genome, index that and then map with parameters --outFilterMultimapNmax 99999  --outSAMprimaryFlag AllBestScore. The idea being that anything that would normally map to gene1 in the context of its original chromosome would also map to the new gene1 chromosome. The results would then be easier to filter out because I could just use awk to pull out "gene1" from the sam and junction files.

For some reason, chimeras that map to gene1 in its original space along the chromosome, are not mapping to the new "gene1" chromosome, even though they are exactly the same sequence. SJ.out.tab results are matching up (gene1 is splicing in its original chromosome and in the "new" chromosome at the same position), which makes me think there is some specific chimera setting I'm missing. Any ideas?

**Comment by alexdobin** [comment]
Hi @RNAseq-er 

if you simply duplicate the gene sequence, the reads that originally mapped uniquely to this gene will become multimappers. You should be able to see it in the SJ.out.tab file - all the junctions in these genes should be supported by multi-mappers and not unique mappers.  In the present version, chimeric detection does not work well with multimapping reads, i.e. not all multimapping chimeras will be output.

I would recommend that you mask the original gene1 sequence in the genome with "N" - this should restore chimeric detection for this gene.

Cheers
Alex
