### ISSUE TITLE
Unable to annotate Read Group with --outSAMattrRGline

### ISSUE THREAD

**Issue by dalameda** [alexdobin/STAR#336]
I tried to annotate resulting BAM file with STAR but I cannot make it to work. This is my command:

for i in *.cutadapt.fastq.gz
do
base_name=${i%.cutadapt.fastq.gz}
STAR --runThreadN 24 \
--genomeDir ~/datos/software/STAR/STARgenomes/GENCODE/hg19.v19 \
--readFilesIn ${i} \
--readFilesCommand zcat \
--outFileNamePrefix ../bam/${i%.fastq.gz}.star.hg19.RG7. \
--outSAMtype BAM SortedByCoordinate \
--quantMode GeneCounts \
--genomeLoad LoadAndKeep \
--outSAMunmapped Within \
--limitBAMsortRAM 20000000000 \
--outSAMattributes NH HI AS NM MD \
--outSAMattrRGline ID:${base_name}-RNAseq SM:${base_name} LB:${base_name}-3RNAseq PU:${base_name}-201710 PL:illumina\tCN:CIMA\tDT:2017-10-21T00:00:00-0400
done

*I also tried using fixed info for the tags instead of variables, and got the same result.

The result is a BAM file with ID annotation only. And it included a Z between ID: and the name of the sample. Example:

NB501241:9:HVVN5BGX2:3:22402:20690:12315        16      chr1    11859   1       59M     *       0       0       TTTTTTTTTCGTTAACTTGCCGTCAGCCTTTTCTTTGACCTCTTCTTTCTGTTCATGTG  EEEAAAEA/</EA</AAEAA<<A/<A66EEEE6EEEAE6EEEEE6EEEEEEEEEAAAAA     NH:i:3  HI:i:1  AS:i:56 NM:i:1  MD:Z:4C54       RG:Z:CPP_AML003-RNAseq

Many thanks for your support!

**Comment by alexdobin** [comment]
Hi @dalameda 

this is the expected behavior - each line in the BAM file gets the "RG:Z:${base_name}" tag, while the rest of the tags are added to one @RG line in the header of the file, i.e.
@RG ID:${base_name}-RNAseq SM:${base_name} LB:${base_name}-3RNAseq PU:${base_name}-201710 PL:illumina\tCN:CIMA\tDT:2017-10-21T00:00:00-0400

Cheers
Alex
