### ISSUE TITLE
Automated Docker build

### ISSUE THREAD

**Issue by ruchim** [alexdobin/STAR#339]
Hey Alex,

Are there plans to add a Dockerfile to this repo and have this repo automatically build & push docker images to dockerhub? It would be a wonderful thing to have a dockerized version STAR to be able to use it in any environment.

This is what I've been using currently.
```
FROM ubuntu:latest

RUN apt-get update

RUN apt-get install --yes \
	build-essential \
	gcc-multilib \
	apt-utils \
	zlib1g-dev \
	vim-common \
	git

# Get STAR source from git
RUN git clone https://github.com/alexdobin/STAR.git

# Build STAR
RUN cd /STAR/source && make STAR

# Add STAR path
ENV PATH /STAR/source:$PATH
```

**Comment by alexdobin** [comment]
Hi @ruchim 

this is a great suggestions, adding it to my TODO list.

Cheers
Alex
