### ISSUE TITLE
STAR-Fusion directory empty in release

### ISSUE THREAD

**Issue by brianjohnhaas** [alexdobin/STAR#34]
Hi Alex,

I'm wondering if something needs to be updated in how the submodule is being specified.... I just downloaded the latest release, and it has a STAR-Fusion/ directory but it's entirely empty.

Perhaps I need to make an official release (as opposed to a pre-release) for it to work?

best,

~brian

**Comment by alexdobin** [comment]
Hi Brian,

I have googled this question and it seems that GitHub does not include submodules into automatically generate releases (e.g. https://github.com/adobe/brackets/issues/9068).
It can be cloned with git clone --recursive ...
In the new release I will try to add a custom tarball with STAR-Fusion included.

Cheers
Alex

**Comment by brianjohnhaas** [comment]
Ah!  OK - no worries.  If you want to just put a URL in the documentation
or in the STAR-Fusion directory to tell folks how to pull it, that would
work too.  I wouldn't want it to be any extra work for you.  I know how
putting releases together can be a pain - and github sort of tries to make
it easy (when you don't have to upload things separately).

best,

~b

On Thu, Apr 23, 2015 at 6:24 PM, alexdobin <notifications@github.com> wrote:

> Hi Brian,
>
> I have googled this question and it seems that GitHub does not include
> submodules into automatically generate releases (e.g. adobe/brackets#9068
> <https://github.com/adobe/brackets/issues/9068>).
> It can be cloned with git clone --recursive ...
> In the new release I will try to add a custom tarball with STAR-Fusion
> included.
>
> Cheers
> Alex
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alexdobin/STAR/issues/34#issuecomment-95734850>.
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by alexdobin** [comment]
Another solution in 2.4.1c - I have added the entire directory of the latest STAR-Fusion release STAR-(Fusion-0.1.1). This seems better, since cloning into submodule will clone the current master, and not the latest release, unless the particular tag is checked out. Also, Manual and README now contain links to the STAR-Fusion github.
Hopefully this will be enough to point people in the right direction.
Cheers
Alex

**Comment by brianjohnhaas** [comment]
Fantastic!  Thanks!! :)

-Brian
(by iPhone)
