### ISSUE TITLE
Installing STAR on cluster

### ISSUE THREAD

**Issue by coolmak32** [alexdobin/STAR#340]
Hi, I want to create genome index using STAR. Therefore, I am trying to install the software on a cluster using. I followed all the steps as suggested by the manual:

wget https://github.com/alexdobin/STAR/archive/2.5.3a.tar.gz
tar -xzf 2.5.3a.tar.gz
cd STAR-2.5.3a
make STAR
I am getting error that " there is nothing to do with STAR".
Can somebody please tell what does that mean. I tried giving command for STAR but nothing comes up which left me assuming that it is not install yet. I am new to Linux system based computing so have no idea.

**Comment by wangyugui** [comment]
'find .  | grep STAR' will show there is already a file "STAR " exists.

**Comment by coolmak32** [comment]
Thanks Wangyugui, I have successfully installed STAR, but now when I am trying to create a genome index I am getting this error:
..... Started STAR run
... Starting to generate Genome files
... starting to sort  Suffix Array. This may take a long time...
... sorting Suffix Array chunks and saving them to disk...
Killed

**Comment by wangyugui** [comment]
It seems that there is no enough memory in this server.

**Comment by coolmak32** [comment]
Hello Wangyugui,
Thanks for your help. It was indeed error due to memory shortage. I have
fixed it and have started mapping. However, I am stuck at one of my sample.
Whenever I am running it I am getting following error:
quality string length is not equal to sequence length, fix your fastq file

@GWNJ-0842:178:GW171013516:2:1101:7263:42130

ATCGTACTTCACCACAGCAATAATTGTGAATTCTTGGGGCTTGTCAACAGCATCATTTACCTCTAAGCCATTAAGGACATTGACAGGCTCACTGTAGAAAAACGGTAGTTTAATTGGAGAATACAGCCCAGAGA

GGTCAGC

7AFFAFJFJJJF<F7--7777<FFFA-<JJJJA-<F-7AJF7A-FFFFFF-FFFFFJJJ<AA7<FFAJFA-7AJJA-<JAJFFFFF-AJAJJJFFJJJ-7F-F-----77FFJF

SOLUTION: fix your fastq file.

I have no clue how to search for this particular read and fix it. I read on
the google user forum on similar issue which was able to be resolved by
editing fasta file. Can you please help me out with this issue.


Thanks



Kuldeep Makwana
(Ph.D. candidate regulatory biology)
SR 271,BGES
Cleveland State University.
216-262-9156

**Comment by alexdobin** [comment]
Hi Kuldeep,

please send me the Log.out file of this run.

Cheers
Alex

**Comment by coolmak32** [comment]
Hello Professor Alex,
Thanks for responding, I incidentally deleted the log file for that
particular run but I encountered same problem with another sample. I am
hereby attaching the log file for that run below.


Kuldeep Makwana
(Ph.D. candidate regulatory biology)
SR 271,BGES
Cleveland State University.
216-262-9156

**Comment by alexdobin** [comment]
Hi Kuldeep,

I cannot see the attached file, could you try it again.

Cheers
Alex
