### ISSUE TITLE
Gff file parse problem

### ISSUE THREAD

**Issue by wangyugui** [alexdobin/STAR#341]
Hi

In some gff file,  there are some " gene " word in some attribute such as note,
but the word after " gene " in gff file was parsed as the attribute "gene".

In the following sample, the region3B  are reported as gene name in ReadsPerGene.out.tab

```
RefSeqViral_84  RefSeq  exon    1429472 1435853 .       -       .       ID=NC_001706_id1;Parent=NC_001706_rna0;Dbxref=GeneID:1261150;Note=Early gene region3B putative;gbkey=misc_RNA       1
RefSeqViral_84  RefSeq  exon    1436465 1451228 .       +       .       ID=NC_001706_id10;Parent=NC_001706_rna1;Dbxref=GeneID:1261160;Note=late gene region3B putative;gbkey=misc_RNA       1
```

**Comment by wangyugui** [comment]
sed 's# gene ##g' genes.gff will make STAR/ReadsPerGene.out.tab works well.

**Comment by wangyugui** [comment]
In this line, "gbkey" is parsed as "gene" name.

```
RefSeqViral_84        RefSeq  exon    170200      170338  .       -       .       ID=NC_000866_id6;Parent=NC_000866_rna0;Dbxref=GeneID:1258654;Note=small%2C stable RNA%3B species 1 RNA;gbkey=misc_RNA;product=rnaC
```

**Comment by wangyugui** [comment]
STAR failed to parse "Curated Genomic" word in 2nd item of gff too.

**Comment by wangyugui** [comment]
STAR failed parse "Curated Genomic/Curated Genomic%2CGnomon" in human refseq gff too.
just because a SPACE in the words.

**Comment by wangyugui** [comment]
convert to space to other char such as _ will make STAR works well.

**Comment by alexdobin** [comment]
Hi @wangyugui 

I strongly recommend converting the GFF files into GTF. The cufflinks package has the gffread file that works well most of the time.

You can try to process the GFF directly with 
--sjdbGTFtagExonParentTranscript Parent
--sjdbGTFtagExonParentGene ID (or whatever tag indicates the gene for each exon).

Cheers
Alex

**Comment by wangyugui** [comment]
Hi @alexdobin 

STAR works well when convert gff to gtf using gffread.
and STAR works well when convert char of SPACE in gff to char '_' too.

Hope this info is helpful to others.
