### ISSUE TITLE
Confusion with mapping

### ISSUE THREAD

**Issue by sagnikbanerjee15** [alexdobin/STAR#345]
Hello,

I have a sample of reads which I wish to map to both the transcriptome and the genome of the same organism. I have performed the mapping separately and it finished without any errors. As I was going through the output I found that one transcript (say t1) got several hits with many reads (This was when I aligned the reads to the transcriptome). But the problem is that the region of the genome from which that transcript originates did not get any hit (when I performed genome alignment). I pulled out all the 2888 reads which mapped to t1. Out of those 2888 reads only 4 were mapped when the mapping was performed with the whole genome. Even then 3 of those were mapped to some other chromosome to which t1 did not belong. This behavior is highly confusing. Any help will be appreciated.

Thank you.

**Comment by alexdobin** [comment]
Hi Sagnik,

are you using annotations to build the genome index?

Please map the 2,888 reads to the genome with --outSAMunmapped Within option, which will output the unmapped reads with the uT tag, which will tell you why the reads were not mapped.

Cheers
Alex

**Comment by sagnikbanerjee15** [comment]
Hello,

I think I figured out what the problem was. Many of the reads were multi mapped. So I redid it will a higher cut off and it worked fine.

Thanks

**Comment by sagnikbanerjee15** [comment]
Hello,

I am facing an additional problem with STAR now. I have a fasta file of reads. When I BLAST those reads with my cDNA database I get BLAST hits. Surprisingly enough, when I align the reads with STAR a bunch of them do not align at all. I have checked to find that the BLAST hits reveal that read which mapped to the transcriptome with 2 mismatches was not aligned to the same transcriptome by STAR. I have tried --outSAMunmapped Within option, but still the reads do not align.

Thank you.

**Comment by alexdobin** [comment]
Hi Sagnik,

How long are your reads?
to increase sensitivity of mapping, I would recommend reducing --seedSearchStartLmax from default 50 to 30,20,10, and increasing --winAnchorMultimapNmax from default 50 to 100,200,500 .

Cheers
Alex

**Comment by sagnikbanerjee15** [comment]
Thank you for your reply. The reads I am dealing with are on an average 150 bp long. I will try with the new settings and let you know about the results.

**Comment by alexdobin** [comment]
150b should be long enough to map with two mismatches even with default parameters.
Are the reads paired- or single-end? It might be that BLAST finds the alignment of only one end.

**Comment by sagnikbanerjee15** [comment]
The reads are single ended

**Comment by sagnikbanerjee15** [comment]
Hello,

I have tried all the settings but the read does not map. The read blasts to 3 sequences. But in STAR it does not map at all. The length of the read is 133 bp.

**Comment by alexdobin** [comment]
Hi Sagnik,

when you map this read with --outSAMunmapped Within, what is the uT tag of the unmapped alignment?

Cheers
Alex
