### ISSUE TITLE
Bases receiving 'N' when aligning

### ISSUE THREAD

**Issue by LCTRGA** [alexdobin/STAR#347]
Dear Alex 

We are performing stranded whole transcriptome sequencing of human tissue and are using STAR version 2.5.3a to align and perform gene counts. Our command is as follows:

nice §STARpath --runThreadN 16 --outSAMattributes All --genomeDir §path_to_wholegenomeFASTA --readFilesIn $merged.file --sjdbOverhang 74 --outFilterMultimapNmax 1 --twopassMode Basic --sjdbGTFfile hg19_genes.gtf --quantMode GeneCounts --outFileNamePrefix $output.file --outSAMtype BAM SortedByCoordinate --outSAMattrRGline ID:AA LB:AA SM:AA PL:ILLUMINA

Using this command we get the following log.final.out (see attachment). We get 59.13% uniquely mapped reads. When we visualize the output bam file in Tablet, long stretches of ‘N’ bases are mapped. The stretches are extremely long, and are longer than possible when performing single-end sequencing with 75 cycles.  We have attached a screenshot of the visualization. Do you know why we observe these long stretches? Could it be related with the STAR command, or is it a bug? 
When we inspect the ReadsPerGene.out.tab file, a large fraction of our reads end up in the ‘No_feature’ category. Do stretches with ‘N’ bases end up in this category? 

N_unmapped	25944188 -	25944188-	25944188
N_multimapping	0	- 0	  - 0
N_noFeature	36280261	- 36971758	- 36832040
N_ambiguous	17648	- 4641-	5158

We have analyzed the bam file with RNA-SeQC and according to this, 2.4% of our reads cover exon regions. A lot of reads, hence, covers introns and intergenic regions. Do you think these fractions are influenced by the stretches with ‘N’ bases? A screenshot from RNA-SeQC is attached. 
We have investigated multiple samples and chromosomes, and the pattern is the same. 

Thanks

Best regards 
Stine & Linea 

![rna-seqcreport](https://user-images.githubusercontent.com/33749191/32943409-5076a9bc-cb8c-11e7-904d-756b227c802c.jpg)

![screenshotalignment](https://user-images.githubusercontent.com/33749191/32943410-50b5e65e-cb8c-11e7-9815-e69c7aae38f8.jpg)

![log final out](https://user-images.githubusercontent.com/33749191/32943596-ec87545a-cb8c-11e7-8ded-24c5790386b5.jpg)

**Comment by alexdobin** [comment]
Hi Stine and Linea,

STAR cannot map entire reads to stretches of Ns. It may map read through a short stretch of Ns, no longer than ~1/3 of the read length.

I think this is a problem with visualization. I am not familiar with Tablet. Have you tried looking at UCSC genome browser or IGV?

Cheers
Alex

**Comment by LCTRGA** [comment]
Hi Alex 

We have tried to visualize the data in IGV as well. We still have long poly(N) reads aligning to the reference. Some of the poly(N) reads are 300,000 bp. By generating a fastqc report, we check the input file before running STAR. The per base N content is 0 (see below). 

![fastqcbeforestar](https://user-images.githubusercontent.com/33749191/33134690-acabc150-cfa0-11e7-8293-59aea9250d0f.jpg)

It, hence, looks like we get poly(N) reads after aligning with STAR. 

Kind regards, 
Stine and Linea

**Comment by alexdobin** [comment]
Hi Stine and Linea,

I am not sure what the Table output represent - I thought N were the genomic sequence, but now it seems you are saying that these huge stretches of Ns are actually read sequences. This is even more impossible :). You can search the SAM alignment file for these, and I am pretty sure you will not find them.

Maybe Table represents the splice junctions (N in the CIGAR) with Ns? Can you see in Table which read ID has these Ns stretches and grep these reads from the SAM file?
Also, if you can make an IGV snapshot it would be useful.

Cheers
Alex

**Comment by LCTRGA** [comment]
Hi Alex

Yes, it is our reads that have polyN sequences. We checked the BAM file, and it seems that you were right. The polyN stretches are not present in our reads here. It seems to be a visualization issue both in Tablet and IGV, when reads span splice junctions. 

Thank you for your help 

Kind regards, 
Stine and Linea

**Comment by alexdobin** [comment]
Hi Stine and Linea,

if you can try UCSC genome browser (i.e. if your genome assembly is compatible), it does display the BAM files correctly for spliced alignments.

Cheers
Alex
