### ISSUE TITLE
RSEM currently does not support gapped alignments, sorry!

### ISSUE THREAD

**Issue by LeilaKhajavi** [alexdobin/STAR#349]
STAR command:
for i in RNAseqFastq/*_R1_fastq.gz; do STAR --runThreadN 16 --genomeDir STAR/STAR_indices --sjdbGTFfile hg38_annotation.gtf --readFilesIn $i ${i%R1_fastq.gz}R2_fastq.gz --outFileNamePrefix STAR/BAMfiles/$(basename $i fastq.gz) --readFilesCommand zcat --sjdbOverhang 50 --outFilterType BySJout --outFilterMultimapNmax 20 --outMultimapperOrder Random --alignSJoverhangMin 8 --alignSJDBoverhangMin 1 --outFilterMismatchNmax 999 --outFilterMismatchNoverLmax 0.04 --alignIntronMin 20 --alignIntronMax 1000000 --alignMatesGapMax 1000000 --quantMode TranscriptomeSAM --alignSoftClipAtReferenceEnds No --outSAMstrandField intronMotif --outSAMmultNmax 1 --clip5pNbases 3 --outFilterIntronMotifs RemoveNoncanonical --outSAMtype BAM SortedByCoordinate; done

RSEM prepare reference:
rsem-prepare-reference -p 4 --gtf hg38_annotation.gtf hg38_genome.fa RSEM/hg38

RSEM canlculate
for i in STAR/*.toTranscriptome.out.bam; do rsem-calculate-expression --append-names --calc-ci --output-genome-bam --alignments --paired-end $i RSEM/hg38 RSEM/parALL/RNAseq_quals/$(basename $i _Aligned.toTranscriptome.out.bam); done

ERROR:
RSEM currently does not support gapped alignments, sorry!

which parameters in STAR? or RSEM? are causing this error?

**Comment by alexdobin** [comment]
Hi @LeilaKhajavi 

the commands look OK. Please cut out a few thousands reads from Aligned.toTranscriptome.out.bam, check that RSEM still complains, and send them to me.

Cheers
Alex

**Comment by LeilaKhajavi** [comment]
Hello!

Thank you for your response!
I was also given this suggestion:


1

Before you do this consider @Alex's answer (which I had included above).

if you generated the genome indexes with annotations, you will splicing to
annotated junctions, as --alignIntronMax only controls the annotated
junctions. You can either (i) use genome with annotations and
--alignSJDBoverhangMin 999 (any number > read length) while mapping, or
(ii) re-generate the genome without annotations.


Do you think it's worth running the mapping again with the adjusted
--alignSJDBoverhangMin 999 ?
I did generate the star indices with gtf annotation...

Also, the Commands listed were working well... I re-ran star with the
addition of --outMultimapperOrder Random
It's with this new alignment that I'm having issues with RSEM...

Thank you again for your time!
Leila


On Nov 22, 2017 04:02, "alexdobin" <notifications@github.com> wrote:

Hi @LeilaKhajavi <https://github.com/leilakhajavi>

the commands look OK. Please cut out a few thousands reads from
Aligned.toTranscriptome.out.bam, check that RSEM still complains, and send
them to me.

Cheers
Alex

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/alexdobin/STAR/issues/349#issuecomment-346229445>, or mute
the thread

**Comment by alexdobin** [comment]
Hi Leila,

you are right about the --clip5pNbases 3, this is what probably creates the problem for RSEM, but it's not indels but rather soft-clipping, I believe. If you need to trim the reads, you have to do it before supplying them to STAR. 

--outMultimapperOrder Random should not create any problems. 

--alignSJDBoverhangMin 999 does not apply in your case, I think. As far as I understood your pipeline, you are mapping to the whole genome sequence with annotations, not just to the transcriptome sequences, and then you are using the Aligned.toTranscriptome.out.bam file as input RSEM. In this case allowing splicing to the genome is all right, as these splices will be converted to unspliced alignments to the transcripts.

Cheers
Alex
