### ISSUE TITLE
Trimming of fastq/fasta names after "/"

### ISSUE THREAD

**Issue by mnsmar** [alexdobin/STAR#35]
Noticed that fastq or fasta names that have a `/` character are trimmed. For example `Name/1/2/3` is trimmed to `Name`. Is there a reason for this?
I have a fastq file in which the reads have the identifier after a `/` in the name. Therefore after the STAR alignment I get all alignments with the same name.
eg.

    Name/1
    Name/2
    Name/3
    ...

after the alignment I get a SAM with the following QNAMEs

    Name
    Name
    Name
    ...

**Comment by alexdobin** [comment]
Trimming read names after "/" was done to accommodate the old Illumina FASTQ format that had /1 /2 labels for read 1,2 . I guess I would need to make it optional, at the moment you would need to replace "/" with another symbol before mapping.

**Comment by mnsmar** [comment]
Thanks. I did just that replaced "/" with "|".
