### ISSUE TITLE
Anchor seeds

### ISSUE THREAD

**Issue by anBertoli** [alexdobin/STAR#353]
I'm trying to use STAR for the first time. I have some questions about the "anchor" seeds, I have already read the STAR paper.

1) From the supplementary: _In the current implementation, all the alignments that map less than a user defined value (typically 20-50) are selected as anchors._. Why so many matches? If STAR choose the MMP I expect one or a few matches in the genome.

2) If we have a read with 2 (X and Y) or multiple anchor seeds, each with multiple matches in the genome STAR will find the best alignment in each alignment window. Then, the genome is split into equally size bins, and all the anchor bins that are within a user defined distance to each other are lumped into one window. So now we have one or more X+Y windows and, excluding chimeric reads, the algorithm will take the best one alignment or consider the multi-mapping opportunity if both have an high score. Is this correct?

Best regards
Andrea Bertoli

**Comment by alexdobin** [comment]
Hi Andrea,

1.
The anchors are allowed to map to multiple loci for two reasons - (i) we want to be able to find all multimapping loci for reads that are multimappers; (ii) even if a read is a unique mapper, short MMPs  (next to junctions or mismatches) will map to a large number of loci, and we do not know which one is the correct one. This is controlled by --winAnchorMultimapNmax = 50 by default.

2. If two anchors map X and Y times to the genome, we will have X+Y windows at most - less if some anchors are close together.

Cheers
Alex
