### ISSUE TITLE
Reads unmaped with --outFilterMultimapNmax 1

### ISSUE THREAD

**Issue by biounix** [alexdobin/STAR#354]
Dear Alex,

I'm testing STAR (2.5.3a) with different parameters, one of them being the `--outFilterMultimapNmax`. I found that when using `--outFilterMultimapNmax 1` some reads are reported as unmapped. For instance:

> SN857:321:HT75MBCXY:1:1105:16459:71216	4	*	0	0	*	*	0	0	TCCTCTTGACTCCTTTAGATCTAGAAGGAGTCAAGAGGAAGAT	F@HIHIHECHIFHH@<CH1CHGH1@GHE111<1DF<1D?GEE?	NH:i:0	HI:i:0	AS:i:31	nM:i:0	uT:A:3

However, when using `--outFilterMultimapNmax 2` (or even  `--outFilterMultimapNmax 20`) with the rest of the parameters remaining identical, the same read is reported as:

> SN857:321:HT75MBCXY:1:1105:16459:71216	0	chr11	118493174	255	11S32M	*	0	0	TCCTCTTGACTCCTTTAGATCTAGAAGGAGTCAAGAGGAAGAT	F@HIHIHECHIFHH@<CH1CHGH1@GHE111<1DF<1D?GEE?	NH:i:1	HI:i:1	AS:i:31	NM:i:0	MD:Z:32

Given that the read is only reported to map in a unique position (NH:i:1), why is that read not being mapped when `--outFilterMultimapNmax 1`? I'm surely missing something here...

Thanks for your time.

**Comment by alexdobin** [comment]
Hi @gresteban 

sorry for belayed reply.
I could not reproduce this problem when mapping with default parameters to the h38 genome.
What parameters are you using? Have you tried to map this read alone?

Cheers
Alex
