### ISSUE TITLE
Usage StringTie with non-stranded libraries

### ISSUE THREAD

**Issue by ml439** [alexdobin/STAR#355]
Hi,

I've got some non-stranded libraries that I have aligned with STAR-RSEM. I now want to use StringTie to discover new transcripts. My problem is that StringTie seems to accept --rf or --fr for library orientation (StringTie/1.3.3) but there's no option for non-stranded libraries. Or is it? I've tried not adding any information for strand, or using --rf and the result is a gtf a lot smaller if I don't specify library orientation. On the other hand, when viewing on IGV the one where I have used --rf, there are transcripts that have the wrong orientation with the gene it maps to, so this is clearly not correct. Would you have any suggestion of how to solve the problem?

Thank you very much for your time and help,

Miriam

**Comment by alexdobin** [comment]
Hi Miriam,

I believe for unstranded data StringTie needs the XS (strand) atrribute for spliced alignments, for which it can be derived from the intron motif. You can add it to STAR SAM/BAM output with the 
--outSAMstrandField intronMotif 
option.

Cheers
Alex
