### ISSUE TITLE
Building from source

### ISSUE THREAD

**Issue by hsinyenwu** [alexdobin/STAR#356]
Hi Alex,
My system is Ubuntu 16.04.3 LTS and gcc 5.4.0
I cloned from github and ran make STAR then I got the following error message:

Makefile:91: Depend.list: No such file or directory
make -C htslib lib-static
make[1]: Entering directory '/opt/STAR/source/htslib'
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o kfunc.o kfunc.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o knetfile.o knetfile.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o kstring.o kstring.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o bgzf.o bgzf.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o faidx.o faidx.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o hfile.o hfile.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o hfile_net.o hfile_net.c
echo '#define HTS_VERSION "0.0.1"' > version.h
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o hts.o hts.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o sam.o sam.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o synced_bcf_reader.o synced_bcf_reader.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o vcf_sweep.o vcf_sweep.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o tbx.o tbx.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o vcf.o vcf.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o vcfutils.o vcfutils.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/cram_codecs.o cram/cram_codecs.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/cram_decode.o cram/cram_decode.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/cram_encode.o cram/cram_encode.c
cram/cram_encode.c: In function ‘process_one_read’:
cram/cram_encode.c:2167:10: warning: unused variable ‘brg’ [-Wunused-variable]
  SAM_RG *brg = sam_hdr_find_rg(fd->header, "UNKNOWN");
          ^
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/cram_index.o cram/cram_index.c
cram/cram_index.c: In function ‘cram_index_build’:
cram/cram_index.c:429:23: warning: variable ‘hpos’ set but not used [-Wunused-but-set-variable]
     off_t cpos, spos, hpos;
                       ^
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/cram_io.o cram/cram_io.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/cram_samtools.o cram/cram_samtools.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/cram_stats.o cram/cram_stats.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/files.o cram/files.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/mFILE.o cram/mFILE.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/md5.o cram/md5.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/open_trace_file.o cram/open_trace_file.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/pooled_alloc.o cram/pooled_alloc.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/sam_header.o cram/sam_header.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/string_alloc.o cram/string_alloc.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/thread_pool.o cram/thread_pool.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/vlen.o cram/vlen.c
cram/vlen.c: In function ‘vflen’:
cram/vlen.c:121:9: warning: variable ‘i’ set but not used [-Wunused-but-set-variable]
     int i;
         ^
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/zfio.o cram/zfio.c
ar -rc libhts.a kfunc.o knetfile.o kstring.o bgzf.o faidx.o hfile.o hfile_net.o hts.o sam.o synced_bcf_reader.o vcf_sweep.o tbx.o vcf.o vcfutils.o cram/cram_codecs.o cram/cram_decode.o cram/cram_encode.o cram/cram_index.o cram/cram_io.o cram/cram_samtools.o cram/cram_stats.o cram/files.o cram/mFILE.o cram/md5.o cram/open_trace_file.o cram/pooled_alloc.o cram/sam_header.o cram/string_alloc.o cram/thread_pool.o cram/vlen.o cram/zfio.o
ranlib libhts.a
make[1]: Leaving directory '/opt/STAR/source/htslib'
echo genomeScanFastaFiles.cpp ReadAlign_mapOneRead.cpp sjdbBuildIndex.cpp ReadAlign_quantTranscriptome.cpp bamRemoveDuplicates.cpp ReadAlign_outputTranscriptSAM.cpp ReadAlign_createExtendWindowsWithAlign.cpp readLoad.cpp binarySearch2.cpp sjdbInsertJunctions.cpp Transcriptome_geneCountsAddAlign.cpp genomeParametersWrite.cpp funCompareUintAndSuffixes.cpp ReadAlign_stitchPieces.cpp Parameters_readSAMheader.cpp BAMbinSortByCoordinate.cpp Transcriptome_quantAlign.cpp ReadAlign_outputAlignments.cpp STAR.cpp ReadAlignChunk.cpp Chain.cpp extendAlign.cpp ReadAlign_outputTranscriptCIGARp.cpp ErrorWarning.cpp Stats.cpp ReadAlign_calcCIGAR.cpp Parameters_openReadsFiles.cpp stitchAlignToTranscript.cpp TimeFunctions.cpp stitchGapIndel.cpp genomeSAindex.cpp signalFromBAM.cpp genomeGenerate.cpp Parameters_closeReadsFiles.cpp ReadAlign_CIGAR.cpp stitchWindowAligns.cpp Parameters.cpp sjSplitAlign.cpp Transcriptome.cpp ReadAlign_chimericDetection.cpp outputSJ.cpp ReadAlign_maxMappableLength2strands.cpp ReadAlignChunk_mapChunk.cpp serviceFuns.cpp ThreadControl.cpp Genome.cpp BAMbinSortUnmapped.cpp insertSeqSA.cpp streamFuns.cpp ReadAlignChunk_processChunks.cpp BAMoutput.cpp ReadAlign_multMapSelect.cpp Transcript_alignScore.cpp PackedArray.cpp ReadAlign_outputTranscriptSJ.cpp ReadAlign.cpp mapThreadsSpawn.cpp loadGTF.cpp ReadAlign_assignAlignToWindow.cpp ReadAlign_alignBAM.cpp funCompareUintAndSuffixesMemcmp.cpp InOutStreams.cpp stringSubstituteAll.cpp GlobalVariables.cpp sysRemoveDir.cpp Quantifications.cpp ReadAlign_storeAligns.cpp ReadAlign_stitchWindowSeeds.cpp SharedMemory.cpp ReadAlign_oneRead.cpp Genome_insertSequences.cpp Transcript.cpp SuffixArrayFuns.cpp sjdbLoadFromStream.cpp alignSmithWaterman.cpp SequenceFuns.cpp sortSuffixesBucket.cpp BAMfunctions.cpp OutSJ.cpp sjdbLoadFromFiles.cpp blocksOverlap.cpp sjdbPrepare.cpp bam_cat.c
genomeScanFastaFiles.cpp ReadAlign_mapOneRead.cpp sjdbBuildIndex.cpp ReadAlign_quantTranscriptome.cpp bamRemoveDuplicates.cpp ReadAlign_outputTranscriptSAM.cpp ReadAlign_createExtendWindowsWithAlign.cpp readLoad.cpp binarySearch2.cpp sjdbInsertJunctions.cpp Transcriptome_geneCountsAddAlign.cpp genomeParametersWrite.cpp funCompareUintAndSuffixes.cpp ReadAlign_stitchPieces.cpp Parameters_readSAMheader.cpp BAMbinSortByCoordinate.cpp Transcriptome_quantAlign.cpp ReadAlign_outputAlignments.cpp STAR.cpp ReadAlignChunk.cpp Chain.cpp extendAlign.cpp ReadAlign_outputTranscriptCIGARp.cpp ErrorWarning.cpp Stats.cpp ReadAlign_calcCIGAR.cpp Parameters_openReadsFiles.cpp stitchAlignToTranscript.cpp TimeFunctions.cpp stitchGapIndel.cpp genomeSAindex.cpp signalFromBAM.cpp genomeGenerate.cpp Parameters_closeReadsFiles.cpp ReadAlign_CIGAR.cpp stitchWindowAligns.cpp Parameters.cpp sjSplitAlign.cpp Transcriptome.cpp ReadAlign_chimericDetection.cpp outputSJ.cpp ReadAlign_maxMappableLength2strands.cpp ReadAlignChunk_mapChunk.cpp serviceFuns.cpp ThreadControl.cpp Genome.cpp BAMbinSortUnmapped.cpp insertSeqSA.cpp streamFuns.cpp ReadAlignChunk_processChunks.cpp BAMoutput.cpp ReadAlign_multMapSelect.cpp Transcript_alignScore.cpp PackedArray.cpp ReadAlign_outputTranscriptSJ.cpp ReadAlign.cpp mapThreadsSpawn.cpp loadGTF.cpp ReadAlign_assignAlignToWindow.cpp ReadAlign_alignBAM.cpp funCompareUintAndSuffixesMemcmp.cpp InOutStreams.cpp stringSubstituteAll.cpp GlobalVariables.cpp sysRemoveDir.cpp Quantifications.cpp ReadAlign_storeAligns.cpp ReadAlign_stitchWindowSeeds.cpp SharedMemory.cpp ReadAlign_oneRead.cpp Genome_insertSequences.cpp Transcript.cpp SuffixArrayFuns.cpp sjdbLoadFromStream.cpp alignSmithWaterman.cpp SequenceFuns.cpp sortSuffixesBucket.cpp BAMfunctions.cpp OutSJ.cpp sjdbLoadFromFiles.cpp blocksOverlap.cpp sjdbPrepare.cpp bam_cat.c
/bin/rm -f ./Depend.list
g++ -pipe -std=c++11 -Wall -Wextra -fopenmp -D'COMPILATION_TIME_PLACE="Thu Dec 7 21:58:24 EST 2017 :/opt/STAR/source"' -MM genomeScanFastaFiles.cpp ReadAlign_mapOneRead.cpp sjdbBuildIndex.cpp ReadAlign_quantTranscriptome.cpp bamRemoveDuplicates.cpp ReadAlign_outputTranscriptSAM.cpp ReadAlign_createExtendWindowsWithAlign.cpp readLoad.cpp binarySearch2.cpp sjdbInsertJunctions.cpp Transcriptome_geneCountsAddAlign.cpp genomeParametersWrite.cpp funCompareUintAndSuffixes.cpp ReadAlign_stitchPieces.cpp Parameters_readSAMheader.cpp BAMbinSortByCoordinate.cpp Transcriptome_quantAlign.cpp ReadAlign_outputAlignments.cpp STAR.cpp ReadAlignChunk.cpp Chain.cpp extendAlign.cpp ReadAlign_outputTranscriptCIGARp.cpp ErrorWarning.cpp Stats.cpp ReadAlign_calcCIGAR.cpp Parameters_openReadsFiles.cpp stitchAlignToTranscript.cpp TimeFunctions.cpp stitchGapIndel.cpp genomeSAindex.cpp signalFromBAM.cpp genomeGenerate.cpp Parameters_closeReadsFiles.cpp ReadAlign_CIGAR.cpp stitchWindowAligns.cpp Parameters.cpp sjSplitAlign.cpp Transcriptome.cpp ReadAlign_chimericDetection.cpp outputSJ.cpp ReadAlign_maxMappableLength2strands.cpp ReadAlignChunk_mapChunk.cpp serviceFuns.cpp ThreadControl.cpp Genome.cpp BAMbinSortUnmapped.cpp insertSeqSA.cpp streamFuns.cpp ReadAlignChunk_processChunks.cpp BAMoutput.cpp ReadAlign_multMapSelect.cpp Transcript_alignScore.cpp PackedArray.cpp ReadAlign_outputTranscriptSJ.cpp ReadAlign.cpp mapThreadsSpawn.cpp loadGTF.cpp ReadAlign_assignAlignToWindow.cpp ReadAlign_alignBAM.cpp funCompareUintAndSuffixesMemcmp.cpp InMakefile:91: Depend.list: No such file or directory
make -C htslib lib-static
make[1]: Entering directory '/opt/STAR/source/htslib'
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o kfunc.o kfunc.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o knetfile.o knetfile.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o kstring.o kstring.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o bgzf.o bgzf.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o faidx.o faidx.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o hfile.o hfile.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o hfile_net.o hfile_net.c
echo '#define HTS_VERSION "0.0.1"' > version.h
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o hts.o hts.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o sam.o sam.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o synced_bcf_reader.o synced_bcf_reader.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o vcf_sweep.o vcf_sweep.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o tbx.o tbx.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o vcf.o vcf.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o vcfutils.o vcfutils.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/cram_codecs.o cram/cram_codecs.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/cram_decode.o cram/cram_decode.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/cram_encode.o cram/cram_encode.c
cram/cram_encode.c: In function ‘process_one_read’:
cram/cram_encode.c:2167:10: warning: unused variable ‘brg’ [-Wunused-variable]
  SAM_RG *brg = sam_hdr_find_rg(fd->header, "UNKNOWN");
          ^
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/cram_index.o cram/cram_index.c
cram/cram_index.c: In function ‘cram_index_build’:
cram/cram_index.c:429:23: warning: variable ‘hpos’ set but not used [-Wunused-but-set-variable]
     off_t cpos, spos, hpos;
                       ^
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/cram_io.o cram/cram_io.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/cram_samtools.o cram/cram_samtools.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/cram_stats.o cram/cram_stats.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/files.o cram/files.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/mFILE.o cram/mFILE.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/md5.o cram/md5.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/open_trace_file.o cram/open_trace_file.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/pooled_alloc.o cram/pooled_alloc.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/sam_header.o cram/sam_header.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/string_alloc.o cram/string_alloc.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/thread_pool.o cram/thread_pool.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/vlen.o cram/vlen.c
cram/vlen.c: In function ‘vflen’:
cram/vlen.c:121:9: warning: variable ‘i’ set but not used [-Wunused-but-set-variable]
     int i;
         ^
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/zfio.o cram/zfio.c
ar -rc libhts.a kfunc.o knetfile.o kstring.o bgzf.o faidx.o hfile.o hfile_net.o hts.o sam.o synced_bcf_reader.o vcf_sweep.o tbx.o vcf.o vcfutils.o cram/cram_codecs.o cram/cram_decode.o cram/cram_encode.o cram/cram_index.o cram/cram_io.o cram/cram_samtools.o cram/cram_stats.o cram/files.o cram/mFILE.o cram/md5.o cram/open_trace_file.o cram/pooled_alloc.o cram/sam_header.o cram/string_alloc.o cram/thread_pool.o cram/vlen.o cram/zfio.o
ranlib libhts.a
make[1]: Leaving directory '/opt/STAR/source/htslib'
echo genomeScanFastaFiles.cpp ReadAlign_mapOneRead.cpp sjdbBuildIndex.cpp ReadAlign_quantTranscriptome.cpp bamRemoveDuplicates.cpp ReadAlign_outputTranscriptSAM.cpp ReadAlign_createExtendWindowsWithAlign.cpp readLoad.cpp binarySearch2.cpp sjdbInsertJunctions.cpp Transcriptome_geneCountsAddAlign.cpp genomeParametersWrite.cpp funCompareUintAndSuffixes.cpp ReadAlign_stitchPieces.cpp Parameters_readSAMheader.cpp BAMbinSortByCoordinate.cpp Transcriptome_quantAlign.cpp ReadAlign_outputAlignments.cpp STAR.cpp ReadAlignChunk.cpp Chain.cpp extendAlign.cpp ReadAlign_outputTranscriptCIGARp.cpp ErrorWarning.cpp Stats.cpp ReadAlign_calcCIGAR.cpp Parameters_openReadsFiles.cpp stitchAlignToTranscript.cpp TimeFunctions.cpp stitchGapIndel.cpp genomeSAindex.cpp signalFromBAM.cpp genomeGenerate.cpp Parameters_closeReadsFiles.cpp ReadAlign_CIGAR.cpp stitchWindowAligns.cpp Parameters.cpp sjSplitAlign.cpp Transcriptome.cpp ReadAlign_chimericDetection.cpp outputSJ.cpp ReadAlign_maxMappableLength2strands.cpp ReadAlignChunk_mapChunk.cpp serviceFuns.cpp ThreadControl.cpp Genome.cpp BAMbinSortUnmapped.cpp insertSeqSA.cpp streamFuns.cpp ReadAlignChunk_processChunks.cpp BAMoutput.cpp ReadAlign_multMapSelect.cpp Transcript_alignScore.cpp PackedArray.cpp ReadAlign_outputTranscriptSJ.cpp ReadAlign.cpp mapThreadsSpawn.cpp loadGTF.cpp ReadAlign_assignAlignToWindow.cpp ReadAlign_alignBAM.cpp funCompareUintAndSuffixesMemcmp.cpp InOutStreams.cpp stringSubstituteAll.cpp GlobalVariables.cpp sysRemoveDir.cpp Quantifications.cpp ReadAlign_storeAligns.cpp ReadAlign_stitchWindowSeeds.cpp SharedMemory.cpp ReadAlign_oneRead.cpp Genome_insertSequences.cpp Transcript.cpp SuffixArrayFuns.cpp sjdbLoadFromStream.cpp alignSmithWaterman.cpp SequenceFuns.cpp sortSuffixesBucket.cpp BAMfunctions.cpp OutSJ.cpp sjdbLoadFromFiles.cpp blocksOverlap.cpp sjdbPrepare.cpp bam_cat.c
genomeScanFastaFiles.cpp ReadAlign_mapOneRead.cpp sjdbBuildIndex.cpp ReadAlign_quantTranscriptome.cpp bamRemoveDuplicates.cpp ReadAlign_outputTranscriptSAM.cpp ReadAlign_createExtendWindowsWithAlign.cpp readLoad.cpp binarySearch2.cpp sjdbInsertJunctions.cpp Transcriptome_geneCountsAddAlign.cpp genomeParametersWrite.cpp funCompareUintAndSuffixes.cpp ReadAlign_stitchPieces.cpp Parameters_readSAMheader.cpp BAMbinSortByCoordinate.cpp Transcriptome_quantAlign.cpp ReadAlign_outputAlignments.cpp STAR.cpp ReadAlignChunk.cpp Chain.cpp extendAlign.cpp ReadAlign_outputTranscriptCIGARp.cpp ErrorWarning.cpp Stats.cpp ReadAlign_calcCIGAR.cpp Parameters_openReadsFiles.cpp stitchAlignToTranscript.cpp TimeFunctions.cpp stitchGapIndel.cpp genomeSAindex.cpp signalFromBAM.cpp genomeGenerate.cpp Parameters_closeReadsFiles.cpp ReadAlign_CIGAR.cpp stitchWindowAligns.cpp Parameters.cpp sjSplitAlign.cpp Transcriptome.cpp ReadAlign_chimericDetection.cpp outputSJ.cpp ReadAlign_maxMappableLength2strands.cpp ReadAlignChunk_mapChunk.cpp serviceFuns.cpp ThreadControl.cpp Genome.cpp BAMbinSortUnmapped.cpp insertSeqSA.cpp streamFuns.cpp ReadAlignChunk_processChunks.cpp BAMoutput.cpp ReadAlign_multMapSelect.cpp Transcript_alignScore.cpp PackedArray.cpp ReadAlign_outputTranscriptSJ.cpp ReadAlign.cpp mapThreadsSpawn.cpp loadGTF.cpp ReadAlign_assignAlignToWindow.cpp ReadAlign_alignBAM.cpp funCompareUintAndSuffixesMemcmp.cpp InOutStreams.cpp stringSubstituteAll.cpp GlobalVariables.cpp sysRemoveDir.cpp Quantifications.cpp ReadAlign_storeAligns.cpp ReadAlign_stitchWindowSeeds.cpp SharedMemory.cpp ReadAlign_oneRead.cpp Genome_insertSequences.cpp Transcript.cpp SuffixArrayFuns.cpp sjdbLoadFromStream.cpp alignSmithWaterman.cpp SequenceFuns.cpp sortSuffixesBucket.cpp BAMfunctions.cpp OutSJ.cpp sjdbLoadFromFiles.cpp blocksOverlap.cpp sjdbPrepare.cpp bam_cat.c
/bin/rm -f ./Depend.list
g++ -pipe -std=c++11 -Wall -Wextra -fopenmp -D'COMPILATION_TIME_PLACE="Thu Dec 7 21:58:24 EST 2017 :/opt/STAR/source"' -MM genomeScanFastaFiles.cpp ReadAlign_mapOneRead.cpp sjdbBuildIndex.cpp ReadAlign_quantTranscriptome.cpp bamRemoveDuplicates.cpp ReadAlign_outputTranscriptSAM.cpp ReadAlign_createExtendWindowsWithAlign.cpp readLoad.cpp binarySearch2.cpp sjdbInsertJunctions.cpp Transcriptome_geneCountsAddAlign.cpp genomeParametersWrite.cpp funCompareUintAndSuffixes.cpp ReadAlign_stitchPieces.cpp Parameters_readSAMheader.cpp BAMbinSortByCoordinate.cpp Transcriptome_quantAlign.cpp ReadAlign_outputAlignments.cpp STAR.cpp ReadAlignChunk.cpp Chain.cpp extendAlign.cpp ReadAlign_outputTranscriptCIGARp.cpp ErrorWarning.cpp Stats.cpp ReadAlign_calcCIGAR.cpp Parameters_openReadsFiles.cpp stitchAlignToTranscript.cpp TimeFunctions.cpp stitchGapIndel.cpp genomeSAindex.cpp signalFromBAM.cpp genomeGenerate.cpp Parameters_closeReadsFiles.cpp ReadAlign_CIGAR.cpp stitchWindowAligns.cpp Parameters.cpp sjSplitAlign.cpp Transcriptome.cpp ReadAlign_chimericDetection.cpp outputSJ.cpp ReadAlign_maxMappableLength2strands.cpp ReadAlignChunk_mapChunk.cpp serviceFuns.cpp ThreadControl.cpp Genome.cpp BAMbinSortUnmapped.cpp insertSeqSA.cpp streamFuns.cpp ReadAlignChunk_processChunks.cpp BAMoutput.cpp ReadAlign_multMapSelect.cpp Transcript_alignScore.cpp PackedArray.cpp ReadAlign_outputTranscriptSJ.cpp ReadAlign.cpp mapThreadsSpawn.cpp loadGTF.cpp ReadAlign_assignAlignToWindow.cpp ReadAlign_alignBAM.cpp funCompareUintAndSuffixesMemcmp.cpp InOutStreams.cpp stringSubstituteAll.cpp GlobalVariables.cpp sysRemoveDir.cpp Quantifications.cpp ReadAlign_storeAligns.cpp ReadAlign_stitchWindowSeeds.cpp SharedMemory.cpp ReadAlign_oneRead.cpp Genome_insertSequences.cpp Transcript.cpp SuffixArrayFuns.cpp sjdbLoadFromStream.cpp alignSmithWaterman.cpp SequenceFuns.cpp sortSuffixesBucket.cpp BAMfunctions.cpp OutSJ.cpp sjdbLoadFromFiles.cpp blocksOverlap.cpp sjdbPrepare.cpp bam_cat.c parametersDefault.xxd htslib >> Depend.list
g++: warning: parametersDefault.xxd: linker input file unused because linking not done
g++: warning: htslib: linker input file unused because linking not done
g++ -c   -O3 -pipe -std=c++11 -Wall -Wextra -fopenmp -D'COMPILATION_TIME_PLACE="Thu Dec 7 21:58:46 EST 2017 :/opt/STAR/source"'  SharedMemory.cpp
In file included from SharedMemory.cpp:5:0:
SharedMemory.h:156:9: error: ‘sem_t’ does not name a type
         sem_t * _sem;
         ^
SharedMemory.cpp: In constructor ‘SharedMemory::SharedMemory(key_t, bool)’:
SharedMemory.cpp:28:5: error: ‘_sem’ was not declared in this scope
     _sem=NULL;
     ^
Makefile:57: recipe for target 'SharedMemory.o' failed
make: *** [SharedMemory.o] Error 1
OutStreams.cpp stringSubstituteAll.cpp GlobalVariables.cpp sysRemoveDir.cpp Quantifications.cpp ReadAlign_storeAligns.cpp ReadAlign_stitchWindowSeeds.cpp SharedMemory.cpp ReadAlign_oneRead.cpp Genome_insertSequences.cpp Transcript.cpp SuffixArrayFuns.cpp sjdbLoadFromStream.cpp alignSmithWaterman.cpp SequenceFuns.cpp sortSuffixesBucket.cpp BAMfunctions.cpp OutSJ.cpp sjdbLoadFromFiles.cpp blocksOverlap.cpp sjdbPrepare.cpp bam_cat.c parametersDefault.xxd htslib >> Depend.list
g++: warning: parametersDefault.xxd: linker input file unused because linking not done
g++: warning: htslib: linker input file unused because linking not done
g++ -c   -O3 -pipe -std=c++11 -Wall -Wextra -fopenmp -D'COMPILATION_TIME_PLACE="Thu Dec 7 21:58:46 EST 2017 :/opt/STAR/source"'  SharedMemory.cpp
In file included from SharedMemory.cpp:5:0:
SharedMemory.h:156:9: error: ‘sem_t’ does not name a type
         sem_t * _sem;
         ^
SharedMemory.cpp: In constructor ‘SharedMemory::SharedMemory(key_t, bool)’:
SharedMemory.cpp:28:5: error: ‘_sem’ was not declared in this scope
     _sem=NULL;
     ^
Makefile:57: recipe for target 'SharedMemory.o' failed
make: *** [SharedMemory.o] Error 1

Any suggestion? Thanks!
Best,
Larry

**Comment by alexdobin** [comment]
Hi Larry,

this error indicates a problem with your glibc libraries - I suspect that the shared memory libraries are missing from your system, or are incomplete. You would need to check and update your glibc installation.

Alternatively,  you can use the precompiled STAR executables from the bin/ directory in the distribution.

Cheers
Alex

**Comment by hsinyenwu** [comment]
Yes, please. Sorry I never be able to figure it out. Maybe it’s the system I was using. My apologies!

Larry

**Comment by paulmenzel** [comment]
On 10/30/18 20:06, Hsin-Yen Larry Wu wrote:
> Yes, please. Sorry I never be able to figure it out. Maybe it’s the
> system I was using. My apologies!

No problems. Thank you for following up.

Larry, you should see a “close button” below the comment field, which
you can use to close the issue yourself.

**Comment by smoe** [comment]
Debian Med offers STAR as "rna-star" which is not unlikely to be already available for your version of Ubuntu.
