### ISSUE TITLE
Issue constructing genome index in STAR

### ISSUE THREAD

**Issue by NBaileyNCL** [alexdobin/STAR#357]
Hi all,

I ran the command:

STAR --runMode genomeGenerate --runThreadN 6 --genomeDir TgalRNAseqAnalysis2/SequenceData/TgalA1STARIndex/ --genomeFastaFiles TgalRNAseqAnalysis2/SequenceData/TgalA1Genome.fasta --sjdbGTFfile TgalRNAseqAnalysis2/SequenceData/TgalA1GenomeAnnotation.gtf --sjdbOverhang 99 --sjdbGTFfeatureExon CDS

resulting in an error processing the annotations:

Dec 08 15:38:45 ..... started STAR run
Dec 08 15:38:45 ... starting to generate Genome files
Dec 08 15:38:58 ... starting to sort Suffix Array. This may take a long time...
Dec 08 15:39:04 ... sorting Suffix Array chunks and saving them to disk...
Dec 08 15:39:34 ... loading chunks from disk, packing SA...
Dec 08 15:39:39 ... finished generating suffix array
Dec 08 15:39:39 ... generating Suffix Array index
Dec 08 15:40:10 ... completed Suffix Array index
Dec 08 15:40:10 ..... processing annotations GTF
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)
Aborted (core dumped)

As far as I know the annotations are the correct format, and I've checked other similar errors (and my chromosome names are the same in the fasta and gtf files)

Any help would be much appreciated,

Nick

**Comment by alexdobin** [comment]
Hi Nick,

Each exonic (i.e. field3=exon) line in the GTF has to have "transcript_id" and "gene_id" tags.
Please check it.

Cheers
Alex

**Comment by NBaileyNCL** [comment]
alex, 

Was just about to update this: 

problem solved as Alex said, there needs to be gene and transcript ids. When converting from embl to gff/gtf using biopython or seqret, these are automatically set to 'gene' and 'locus_tag' and so need to be changed.

Thanks for the help

Nick

**Comment by alexdobin** [comment]
Hi Nick,

thanks for sharing the solution!

Cheers
Alex

**Comment by brianpenghe** [comment]
I used the gtf or gff3 files [downloaded from ENSEMBLE](http://www.ensembl.org/Drosophila_melanogaster/Info/Index) but always got `what():  vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)`
Anything wrong with ENSEMBLE?

**Comment by alexdobin** [comment]
Hi @brianpenghe 

please send me the Log.out file of the failed run.

**Comment by brianpenghe** [comment]
Actually I solved the problem : ENSEMBL website's gtf file doesn't have "chr".
This command corrected the gtf `awk 'OFS="\t" {if (NR > 5) $1="chr"$1; print}' in.gtf > out.gtf`
