### ISSUE TITLE
Void pointer arithmetic in sortSuffixesBucket

### ISSUE THREAD

**Issue by Shians** [alexdobin/STAR#358]
[sortSuffixesBucket](https://github.com/alexdobin/STAR/blob/82020fadb2a34dff39884fa5b10fda2f0984bae9/source/sortSuffixesBucket.cpp) uses a few additions to void pointer `ind`, I think this is technically undefined behaviour in C. `gcc` implements this by pretending void has size 1, but `clang` fails with an error and I'm not sure what other compilers think of this.

**Comment by alexdobin** [comment]
Hi Shian

sorry for long delay. I am preparing a new release and looking at all the suggestions, The sortSuffixesBucket.cpp was an experimental code that I ended up not using. I will just remove it from the distribution for now, but may fix it in the future if I decide to use it.

Thanks for the suggestion.
Cheers
Alex
