### ISSUE TITLE
Generation of Wiggle from Bam doesn't work.

### ISSUE THREAD

**Issue by xuhangliu** [alexdobin/STAR#359]
Hi Alex,

I tried to generate Wiggle from Bam with STAR-2.5.3a using the following cmd:
STAR --runMode inputAlignmentsFromBAM --runThreadN 6 --readFilesIn Aligned.sortedByCoord.out.bam --outWigType wiggle --limitBAMsortRAM 6000000000

I got the following msg
Dec 29 19:27:03 ..... reading from BAM, output wiggle

However, I never got the wiggle files. And when I checked the processes using top, STAR is not running. Could you please help me solve this issue? Thank you!

Xuhang

**Comment by alexdobin** [comment]
Hi Xuhang,

you need to use --inputBAMfile Aligned.sortedByCoord.out.bam instead of --readFilesIn ...

Cheers
Alex

**Comment by xuhangliu** [comment]
Thank you for your help, Alex!

Xuhang
