### ISSUE TITLE
RAM error

### ISSUE THREAD

**Issue by jiffen** [alexdobin/STAR#361]
Hi,

I have transcriptome reference and mapping raw reads for variant calling. It gives me following error
RuntimeError: Error while running command "['STAR', '--runThreadN', '4', '--runMode', 'genomeGenerate', '--genomeDir', 'star_genome_idx', '--genomeFastaFiles', '/Volumes/scratch/macknightlab/jiffin/CUDH2107/trinity_300/super_transcripts/trinity_genes.fasta', '--sjdbGTFfile', '/Volumes/scratch/macknightlab/jiffin/CUDH2107/trinity_300/super_transcripts/trinity_genes.gtf', '--sjdbOverhang', '150', '--limitGenomeGenerateRAM', '50000000000']":

EXITING because of FATAL PARAMETER ERROR: limitGenomeGenerateRAM=50000000000is too small for your genome
SOLUTION: please specify --limitGenomeGenerateRAM not less than 148009325269 and make that much RAM available

Please let me know how to fix it. Thanks
Jiffin

**Comment by alexdobin** [comment]
Hi Jiffin,

you need to scale down the --genomeChrBinNbits parameter to log2(AverageTranscriptSize).
You can calculate the AverageTranscriptSize as total size of the FASTA file divided by the number of transcripts.

Cheers
Alex
