### ISSUE TITLE
color space?

### ISSUE THREAD

**Issue by lmjakt** [alexdobin/STAR#362]

**Comment by lmjakt** [comment]
Hi Alex,

(apologies for the empty comment, hit tab a bit too fast.. )

not really an issue per-se, but more of a question. How much work do you think it would be to add some color-space support to STAR? I'm guessing that modifications to the basic align functions should not be too difficult (aligning against a color space genome), but that the trouble would lie in making use of splice junction information and in generating bam files in base space. Having said that, I suspect there may be hidden problems since support has been dropped from most alignment programs. If you think that it would not be _that_ difficult, then I might consider having a go at it, as STAR runs so much faster than anything else that I have tried. I can't see that there are likely to be many other users for it, as nobody really uses color space data anymore, but we have a lot of old color space data and I'm getting tired of waiting for old aligners to finish.

cheers,

Martin

**Comment by alexdobin** [comment]
Hi Martin,

theoretically, it might not look hard to adjust the code for color space, however, practically I think it's going to be hard. The ACGTN nucleotides are hard-coded in many places in the code, unfortunately, and you would have to get it right every time.

Cheers
Alex

**Comment by lmjakt** [comment]
Hi Alex,

that's a pity as it's always such a relief to run STAR compared to what I
have to deal with with color space data.
Can you give me an example of where you have hard-coded ACTG nucleotides?
The only place that I can imagine you would use them would be for splice
site detection, which is something I don't need for my current data set. I
would have thought that if one double encodes the genome and sequences
(i.e. encodes the transitions as ACTG) then it ought to be possible to get
some sort of bam output in color-space by simply changing the reverse
complement behaviour (If there is an easy way to ignore splice site rules).
One could then take the resulting bam files and convert to sequence space
using the genome sequence: at which point one would have to consider the
other color-space properties.
If not really feasible, do you you know of any other software which makes
use of an uncompressed suffix array index, that might be easier to convert.

regardless, thanks for your reply and for writing STAR.

cheers,

Martin

--
Martin Jakt
Senior Researcher
Marine Genomics Research Group
Faculty of Biosciences and Aquaculture
University of Nordland
P.O. Box 1490, Bodø, Norway

**Comment by alexdobin** [comment]
Hi Martin,

I cannot wrap my head around whether simple replacement of ACGT with transitions will work. It may seem like it should overcome most of the ACGTN hard-encoding problems. It certainly will not work for junctions motifs and reverse complementarity. Splice motif rules can be ignored by setting the motif penalties to 0. In general, I am not sure how the splice junctions will be dealt with,  what if the junction has to break the dinucleotide?

Cheers
Alex

**Comment by alexdobin** [comment]
Hi Martin,

your idea about STAR's algorithm is basically correct, except in the 2nd step, instead of the Smith-Waterman, STAR assembles seeds into chains and then "stitches" the seeds into alignments.

If you are not interested in the junction, you could simply make the gap penalties very large.
However, the reverse complementarity is hard-coded throughout the algorithm, and I think this is going to be the main stumbling block. I think it would probably be easier to re-implement the whole stitching algorithm in color space. To be honest, I still think it's too much work with an unclear outcome. In addition, this part of the code is one of the oldest and messiest, just waiting to b re-written... 

Norway in the autumn sounds great! Unfortunately, my plans for the next several months are very unclear at the moment. I hope it gets resolved in the next few week, and I will get back to you before March 21st.

Cheers
Alex

**Comment by lmjakt** [comment]
Hi Alex,

sounds like it would be too much trouble to modify the STAR code for too
little gain. There is not that much color-space data around, and there
isn't going to be any new stuff produced. Nevertheless, I am happy that you
might be interested in coming to the NORBIS meeting and I hope that you
will be able to do so.

cheers,

Martin

--
Martin Jakt
Senior Researcher
Marine Genomics Research Group
Faculty of Biosciences and Aquaculture
University of Nordland
P.O. Box 1490, Bodø, Norway

**Comment by lmjakt** [comment]
Hi Alex,

just a quick note to check on your future plans for the autumn and whether
you will be able to attend the NORBIS meeting in the autumn (the location
will be Voss, close to Bergen). I had an email from the main organiser of
the school who is curious as to your availability.
I should say that everyone on the board would very much like it if you can
make and we are very much hoping for a positive answer.

cheers,

Martin

--
Martin Jakt
Senior Researcher
Marine Genomics Research Group
Faculty of Biosciences and Aquaculture
University of Nordland
P.O. Box 1490, Bodø, Norway

**Comment by alexdobin** [comment]
Hi Martin,

sorry, I am still in limbo about my plans for the autumn, so I would have to pass this great opportunity, unfortunately. Maybe next year?
Thanks a lot again!

Cheers
Alex

**Comment by lmjakt** [comment]
Hi Alex,

sorry to hear that you still don't have any certainty as to your future. I
don't really know when we'd need to confirm the speaker list, but I suspect
that we won't need to do so for another couple of months, so if you think
that your plans may solidify within the spring early summer that would
probably be alright. We will discuss this at the up-coming meeting. In any
case if you can't make it this year it is quite clear that we would
definitely like you the year after as well.
I'll keep you updated, and in the meanwhile hope that things sort
themselves out for you,

cheers,

Martin

--
Martin Jakt
Senior Researcher
Marine Genomics Research Group
Faculty of Biosciences and Aquaculture
University of Nordland
P.O. Box 1490, Bodø, Norway

**Comment by lmjakt** [comment]
Hi Alex,

if I am not mistaken I should congratulate you on getting a position at
CSHL; I hear it is a great place to work and hope that you are enjoying it.
I also hope that you would still be willing and able to give a keynote
presentation at our upcoming NORBIS* annual meeting. This year it will be
held in an old fort on an island in Oslofjord (Oscarsborg fortress)
sometime in October. The time has not yet been finalised, but obviously if
you are able to attend we would try to schedule around your needs.
If you should be interested, it should also be possible to arrange for you
to visit further north (eg. Bodø or Tromsø), which are perhaps somewhat
more interesting to visit than Oslo. Well, at least for the nature, and is
the time when you can expect to see aurora (weather permitting that is; and
the weather here is not the greatest).

yours,

Martin

*NORBIS: Norwegian research school in bionformatics and biostatistics;
although on the board, I am never sure of the official name as it is not an
acronym; in fact I think that the official name may simply be NORBIS and
that it doesn't actually stand for anything.
--
Martin Jakt
Senior Researcher
Marine Genomics Research Group
Faculty of Biosciences and Aquaculture
University of Nordland
P.O. Box 1490, Bodø, Norway

**Comment by alexdobin** [comment]
Hi Martin,

thank you very much! CSHL is indeed a great place to work, though starting a lab is not easy anywhere.

Thanks a lot for the invitation and for your patience. I will be happy to do it this year - October looks good for me. 

Cheers
Alex

P.S. If you need to reach me by e-mail: dobin @ cshl . edu

**Comment by lmjakt** [comment]
Hi Alex,
That's excellent news! I will get you i touch with the school coordinator
from my work email tomorrow to make sure that thing get organised
appropriately.
Cheers,
Martin
