### ISSUE TITLE
Genome loading different time for different samples

### ISSUE THREAD

**Issue by GrantHov** [alexdobin/STAR#363]
Dear Alex,

I am running STAR in `for` loop for multiple samples, and noticed that sometime the genome loading step takes around 7 min, but sometimes less than a minute (It is always the same genome and I didn't specify shared memery option in STAR command). I am wondering if this is a normal behaviour. 

Here is my command:
while read filename;do
	NAME=$(basename ${filename} .fastq.gz)
	echo "Started mapping $filename"
	STAR --runThreadN 20 --genomeDir ${GENOME_DIR} --sjdbGTFfile ${GTF} --sjdbFileChrStartEnd merged_SJ.out.tab \
--sjdbOverhang 49 --readFilesIn /users/tg/hhovhannisyan/col_cancer/raw_data/${filename} --readFilesCommand zcat \
--limitBAMsortRAM 4000000000 --outFileNamePrefix ${NAME}"_step2_" --outSAMtype BAM SortedByCoordinate --quantMode TranscriptomeSAM GeneCounts
	echo "Finished mapping $filename"
done <enrichment_1_files.txt

Here I paste stdout for different samples:

Started mapping Pool10_21566_ACTGAT.fastq.gz
Jan 17 11:11:32 ..... started STAR run
Jan 17 11:11:32 ..... loading genome
Jan 17 11:18:12 ..... processing annotations GTF
Jan 17 11:18:16 ..... inserting junctions into the genome indices
Jan 17 11:21:10 ..... started mapping
Jan 17 11:22:11 ..... started sorting BAM
Jan 17 11:22:34 ..... finished successfully
Finished mapping Pool10_21566_ACTGAT.fastq.gz
Started mapping Pool10_21566_AGTCAA.fastq.gz
Jan 17 11:22:35 ..... started STAR run
Jan 17 11:22:35 ..... loading genome
Jan 17 11:29:33 ..... processing annotations GTF
Jan 17 11:29:35 ..... inserting junctions into the genome indices
Jan 17 11:32:38 ..... started mapping
Jan 17 11:33:43 ..... started sorting BAM
Jan 17 11:34:11 ..... finished successfully
Finished mapping Pool10_21566_AGTCAA.fastq.gz
Started mapping Pool10_21566_ATTCCT.fastq.gz
Jan 17 11:34:12 ..... started STAR run
Jan 17 11:34:12 ..... loading genome
Jan 17 11:39:47 ..... processing annotations GTF
Jan 17 11:39:48 ..... inserting junctions into the genome indices
Jan 17 11:42:40 ..... started mapping
Jan 17 11:43:39 ..... started sorting BAM
Jan 17 11:43:52 ..... finished successfully
Finished mapping Pool10_21566_ATTCCT.fastq.gz
Started mapping Pool10_21566_CCGTCC.fastq.gz
Jan 17 11:43:54 ..... started STAR run
Jan 17 11:43:54 ..... loading genome
Jan 17 11:48:00 ..... processing annotations GTF
Jan 17 11:48:02 ..... inserting junctions into the genome indices
Jan 17 11:50:52 ..... started mapping
Jan 17 11:51:56 ..... started sorting BAM
Jan 17 11:52:19 ..... finished successfully
Finished mapping Pool10_21566_CCGTCC.fastq.gz
Started mapping Pool10_21566_CGTACG.fastq.gz
Jan 17 11:52:20 ..... started STAR run
Jan 17 11:52:20 ..... loading genome
Jan 17 11:54:34 ..... processing annotations GTF
Jan 17 11:54:36 ..... inserting junctions into the genome indices
Jan 17 11:56:56 ..... started mapping
Jan 17 11:58:05 ..... started sorting BAM
Jan 17 11:58:25 ..... finished successfully
Finished mapping Pool10_21566_CGTACG.fastq.gz
Started mapping Pool10_21566_GAGTGG.fastq.gz
Jan 17 11:58:27 ..... started STAR run
Jan 17 11:58:27 ..... loading genome
Jan 17 11:59:04 ..... processing annotations GTF
Jan 17 11:59:06 ..... inserting junctions into the genome indices
Jan 17 12:01:35 ..... started mapping
Jan 17 12:02:34 ..... started sorting BAM
Jan 17 12:02:48 ..... finished successfully
Finished mapping Pool10_21566_GAGTGG.fastq.gz
Started mapping Pool10_21566_GTGGCC.fastq.gz
Jan 17 12:02:49 ..... started STAR run
Jan 17 12:02:49 ..... loading genome
Jan 17 12:06:31 ..... processing annotations GTF
Jan 17 12:06:34 ..... inserting junctions into the genome indices
Jan 17 12:08:50 ..... started mapping
Jan 17 12:10:00 ..... started sorting BAM
Jan 17 12:10:23 ..... finished successfully
Finished mapping Pool10_21566_GTGGCC.fastq.gz
Started mapping Pool10_21566_GTTTCG.fastq.gz
Jan 17 12:10:25 ..... started STAR run
Jan 17 12:10:25 ..... loading genome
Jan 17 12:11:48 ..... processing annotations GTF
Jan 17 12:11:50 ..... inserting junctions into the genome indices
Jan 17 12:14:21 ..... started mapping
Jan 17 12:15:34 ..... started sorting BAM
Jan 17 12:15:55 ..... finished successfully
Finished mapping Pool10_21566_GTTTCG.fastq.gz
Started mapping Pool1_21557_ACAGTG.fastq.gz
Jan 17 12:15:57 ..... started STAR run
Jan 17 12:15:58 ..... loading genome
Jan 17 12:22:24 ..... processing annotations GTF
Jan 17 12:22:27 ..... inserting junctions into the genome indices
Jan 17 12:24:46 ..... started mapping
Jan 17 12:25:45 ..... started sorting BAM
Jan 17 12:26:06 ..... finished successfully
Finished mapping Pool1_21557_ACAGTG.fastq.gz
Started mapping Pool1_21557_ACTTGA.fastq.gz
Jan 17 12:26:07 ..... started STAR run
Jan 17 12:26:08 ..... loading genome
Jan 17 12:26:58 ..... processing annotations GTF
Jan 17 12:26:59 ..... inserting junctions into the genome indices
Jan 17 12:29:21 ..... started mapping
Jan 17 12:30:27 ..... started sorting BAM
Jan 17 12:30:53 ..... finished successfully
Finished mapping Pool1_21557_ACTTGA.fastq.gz
Started mapping Pool1_21557_ATCACG.fastq.gz
Jan 17 12:30:55 ..... started STAR run
Jan 17 12:30:55 ..... loading genome
Jan 17 12:31:37 ..... processing annotations GTF
Jan 17 12:31:39 ..... inserting junctions into the genome indices
Jan 17 12:34:10 ..... started mapping
Jan 17 12:35:17 ..... started sorting BAM
Jan 17 12:35:42 ..... finished successfully
Finished mapping Pool1_21557_ATCACG.fastq.gz
Started mapping Pool1_21557_CAGATC.fastq.gz
Jan 17 12:35:44 ..... started STAR run
Jan 17 12:35:44 ..... loading genome
Jan 17 12:36:31 ..... processing annotations GTF
Jan 17 12:36:32 ..... inserting junctions into the genome indices
Jan 17 12:38:46 ..... started mapping
Jan 17 12:40:08 ..... started sorting BAM
Jan 17 12:40:38 ..... finished successfully
Finished mapping Pool1_21557_CAGATC.fastq.gz
Started mapping Pool1_21557_CGATGT.fastq.gz
Jan 17 12:40:40 ..... started STAR run
Jan 17 12:40:40 ..... loading genome
Jan 17 12:47:30 ..... processing annotations GTF
Jan 17 12:47:32 ..... inserting junctions into the genome indices
Jan 17 12:49:55 ..... started mapping
Jan 17 12:50:57 ..... started sorting BAM
Jan 17 12:51:18 ..... finished successfully
Finished mapping Pool1_21557_CGATGT.fastq.gz
Started mapping Pool1_21557_GCCAAT.fastq.gz
Jan 17 12:51:20 ..... started STAR run
Jan 17 12:51:20 ..... loading genome
Jan 17 12:51:53 ..... processing annotations GTF
Jan 17 12:51:54 ..... inserting junctions into the genome indices

Thank you very much in advance.

**Comment by alexdobin** [comment]
Hi @GrantHov 

I think this is likely normal behavior. My explanation would be as follows. The very first time the genome is loaded, it takes ~7min. This is probably limited by the I/O of the disk or NFS on which the genome index resides. In consequent runs, sometimes takes as little as 30 seconds, because Linux tries to cache files in RAM, and depending on how much RAM you have and how much is used by other processes, in some cases the cached file will be very quickly loaded directly from RAM, avoiding the storage I/O bottleneck.

Since you are running a large number of small files (single cell RNA-seq), it would probably save you a lot of time if you used shared memory loading of the genome. Another option is to list all the files in --readFilesIn with different read group IDs, map everything into one BAM file, and then split the BAM by read groups.

Cheers
Alex

**Comment by GrantHov** [comment]
Hi Alex,

Thanks very much for detailed explanation, very useful as usual!
This is not single cell RNAseq anyway I might try out your suggestion in future.

Best,
Hrant
