### ISSUE TITLE
segmentation fault when mapping to tRNA index

### ISSUE THREAD

**Issue by chekula** [alexdobin/STAR#366]
I get 'Segmentation fault' when trying to map to tRNA index. mapping worked with the entire genome index. logout file attached. thank you.
[Logout.txt](https://github.com/alexdobin/STAR/files/1648860/Logout.txt)

..... started STAR run                              
..... loading genome                                
..... started mapping                               
Segmentation fault

**Comment by alexdobin** [comment]
Hi @chekula 

for small genomes, you need to scale down --genomeSAindexNbases as log2(GenomeLength)/2 - 1

Cheers
Alex
