### ISSUE TITLE
Mapping to the mitochondrial genome (mtDNA) -- rCRS idiosyncracies

### ISSUE THREAD

**Issue by BrynMarieR** [alexdobin/STAR#368]
The new version of the human genome (38) uses the revised Cambridge Reference Sequence for the mitochondrial genome. A "fun quirk" of that assembly is that there is an extra "N" added at position 3106/3107 (depending on which papers you consult) in order to standardise the numbering scheme and keep it backwards-compatible (clearly that worked out really well...)

As a result, most people in the field manually remove the "N" from the mitochondrial genome during mapping and re-add the "N" afterwards for analysis. Doing something like that manually seems silly. Would it be possible to add functionality to STAR to remove this extra "N" during mapping without requiring the user to manually edit genome assembly files? I'd be happy to write it and pull request it, if that's the limiting factor.

**Comment by alexdobin** [comment]
Hi Bryn,

one quick hack I would suggest is to "annotate" this one base insertion as a junction. This would make the mapping practically equivalent to the genome with removed N, but will keep the coordinates in the genome with N.

Cheers
Alex

**Comment by BrynMarieR** [comment]
Oh of course! Thanks for the suggestion.
