### ISSUE TITLE
Generate genome index- EXITING because of FATAL ERROR 

### ISSUE THREAD

**Issue by AMMMachado** [alexdobin/STAR#370]
Hello Alex,

I have a fasta file of sequences which I wish to map back to a genome. When i tried generate the genome reference the program give me the problem mention below. Additionally I have here the .log file. 

/STAR-2.5.4a/bin/Linux_x86_64/STAR \
> --runThreadN 22 --runMode genomeGenerate --genomeDir /STAR-2.5.4a/DLE \
> --genomeFastaFiles /STAR-2.5.4a/Genomes/GCF_002288925.1_ASM228892v2_genomic.fna \
> --sjdbGTFfile /STAR-2.5.4a/Genomes/GCF_002288925.1_ASM228892v2_genomic.gff --sjdbOverhang 100
Jan 31 11:39:08 ..... started STAR run
Jan 31 11:39:08 ... starting to generate Genome files
Jan 31 11:41:05 ... starting to sort Suffix Array. This may take a long time...
Jan 31 11:41:48 ... sorting Suffix Array chunks and saving them to disk...
Jan 31 12:06:22 ... loading chunks from disk, packing SA...
Jan 31 12:11:51 ... finished generating suffix array
Jan 31 12:11:51 ... generating Suffix Array index
Jan 31 12:17:02 ... completed Suffix Array index
Jan 31 12:17:02 ..... processing annotations GTF
Jan 31 12:17:27 ..... inserting junctions into the genome indices

EXITING because of FATAL ERROR: cannot insert junctions on the fly because of strand GstrandBit problem

SOLUTION: please contact STAR author at https://groups.google.com/forum/#!forum/rna-star

[Log.out.tar.gz](https://github.com/alexdobin/STAR/files/1682022/Log.out.tar.gz)

Tanks in advance 
André

**Comment by alexdobin** [comment]
Hi @AMMMachado 

since you genome has a large number of contigs, you need to scale --genomeChrBinNbits as log2(GenomeSize/NumberOfContigs) which is ~8 for your case, I think.

Cheers
Alex

**Comment by AMMMachado** [comment]
Hey Alex.

Your suggestion resulted and the problem was solved.

Thanks again.

Cheers
