### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by kibriadurlav** [alexdobin/STAR#371]
**Hi @alexdobin** 

I tried installing from source using git, but when I enter make STAR, I am having following error, 

make star
Makefile:91: Depend.list: No such file or directory
make -C htslib lib-static
make[1]: Entering directory '/home/kibria/STAR/source/htslib'
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o bgzf.o bgzf.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o faidx.o faidx.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o hfile.o hfile.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o hfile_net.o hfile_net.c
echo '#define HTS_VERSION "0.0.1"' > version.h
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o hts.o hts.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o sam.o sam.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o synced_bcf_reader.o synced_bcf_reader.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o vcf_sweep.o vcf_sweep.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o tbx.o tbx.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o vcf.o vcf.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o vcfutils.o vcfutils.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/cram_codecs.o cram/cram_codecs.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/cram_decode.o cram/cram_decode.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/cram_encode.o cram/cram_encode.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/cram_index.o cram/cram_index.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/cram_io.o cram/cram_io.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/cram_samtools.o cram/cram_samtools.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/cram_stats.o cram/cram_stats.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/files.o cram/files.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/mFILE.o cram/mFILE.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/md5.o cram/md5.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/open_trace_file.o cram/open_trace_file.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/pooled_alloc.o cram/pooled_alloc.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/sam_header.o cram/sam_header.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/string_alloc.o cram/string_alloc.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/thread_pool.o cram/thread_pool.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/vlen.o cram/vlen.c
cram/vlen.c: In function ‘vflen’:
cram/vlen.c:121:9: warning: variable ‘i’ set but not used [-Wunused-but-set-variable]
     int i;
         ^
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/zfio.o cram/zfio.c
ar -rc libhts.a kfunc.o knetfile.o kstring.o bgzf.o faidx.o hfile.o hfile_net.o hts.o sam.o synced_bcf_reader.o vcf_sweep.o tbx.o vcf.o vcfutils.o cram/cram_codecs.o cram/cram_decode.o cram/cram_encode.o cram/cram_index.o cram/cram_io.o cram/cram_samtools.o cram/cram_stats.o cram/files.o cram/mFILE.o cram/md5.o cram/open_trace_file.o cram/pooled_alloc.o cram/sam_header.o cram/string_alloc.o cram/thread_pool.o cram/vlen.o cram/zfio.o
ranlib libhts.a
make[1]: Leaving directory '/home/kibria/STAR/source/htslib'
echo Chain.cpp sjdbBuildIndex.cpp ReadAlign_quantTranscriptome.cpp ReadAlign_mapOneRead.cpp BAMoutput.cpp ReadAlign_outputTranscriptSAM.cpp readLoad.cpp sjdbInsertJunctions.cpp Stats.cpp Transcriptome_geneCountsAddAlign.cpp ReadAlign_stitchPieces.cpp funCompareUintAndSuffixes.cpp STAR.cpp Parameters_readSAMheader.cpp BAMbinSortByCoordinate.cpp Genome_insertSequences.cpp Transcriptome_quantAlign.cpp funCompareUintAndSuffixesMemcmp.cpp ReadAlign_outputAlignments.cpp ReadAlign_alignBAM.cpp ReadAlign_stitchWindowSeeds.cpp Quantifications.cpp ReadAlignChunk.cpp Transcriptome.cpp PackedArray.cpp ReadAlign_outputTranscriptCIGARp.cpp ErrorWarning.cpp Parameters_openReadsFiles.cpp sjdbLoadFromStream.cpp stitchAlignToTranscript.cpp TimeFunctions.cpp stitchGapIndel.cpp genomeSAindex.cpp signalFromBAM.cpp ReadAlign_calcCIGAR.cpp genomeGenerate.cpp outputSJ.cpp Parameters_closeReadsFiles.cpp stitchWindowAligns.cpp GlobalVariables.cpp Parameters.cpp sjSplitAlign.cpp ReadAlign_chimericDetection.cpp BAMfunctions.cpp ReadAlign_maxMappableLength2strands.cpp ReadAlignChunk_mapChunk.cpp serviceFuns.cpp binarySearch2.cpp ThreadControl.cpp Genome.cpp BAMbinSortUnmapped.cpp insertSeqSA.cpp streamFuns.cpp ReadAlignChunk_processChunks.cpp ReadAlign_createExtendWindowsWithAlign.cpp genomeParametersWrite.cpp ReadAlign_multMapSelect.cpp ReadAlign_outputTranscriptSJ.cpp SequenceFuns.cpp ReadAlign.cpp mapThreadsSpawn.cpp loadGTF.cpp ReadAlign_assignAlignToWindow.cpp stringSubstituteAll.cpp sysRemoveDir.cpp ReadAlign_storeAligns.cpp bamRemoveDuplicates.cpp InOutStreams.cpp SharedMemory.cpp ReadAlign_oneRead.cpp ReadAlign_CIGAR.cpp Transcript.cpp SuffixArrayFuns.cpp alignSmithWaterman.cpp extendAlign.cpp Transcript_alignScore.cpp sortSuffixesBucket.cpp OutSJ.cpp sjdbLoadFromFiles.cpp blocksOverlap.cpp sjdbPrepare.cpp genomeScanFastaFiles.cpp bam_cat.c
Chain.cpp sjdbBuildIndex.cpp ReadAlign_quantTranscriptome.cpp ReadAlign_mapOneRead.cpp BAMoutput.cpp ReadAlign_outputTranscriptSAM.cpp readLoad.cpp sjdbInsertJunctions.cpp Stats.cpp Transcriptome_geneCountsAddAlign.cpp ReadAlign_stitchPieces.cpp funCompareUintAndSuffixes.cpp STAR.cpp Parameters_readSAMheader.cpp BAMbinSortByCoordinate.cpp Genome_insertSequences.cpp Transcriptome_quantAlign.cpp funCompareUintAndSuffixesMemcmp.cpp ReadAlign_outputAlignments.cpp ReadAlign_alignBAM.cpp ReadAlign_stitchWindowSeeds.cpp Quantifications.cpp ReadAlignChunk.cpp Transcriptome.cpp PackedArray.cpp ReadAlign_outputTranscriptCIGARp.cpp ErrorWarning.cpp Parameters_openReadsFiles.cpp sjdbLoadFromStream.cpp stitchAlignToTranscript.cpp TimeFunctions.cpp stitchGapIndel.cpp genomeSAindex.cpp signalFromBAM.cpp ReadAlign_calcCIGAR.cpp genomeGenerate.cpp outputSJ.cpp Parameters_closeReadsFiles.cpp stitchWindowAligns.cpp GlobalVariables.cpp Parameters.cpp sjSplitAlign.cpp ReadAlign_chimericDetection.cpp BAMfunctions.cpp ReadAlign_maxMappableLength2strands.cpp ReadAlignChunk_mapChunk.cpp serviceFuns.cpp binarySearch2.cpp ThreadControl.cpp Genome.cpp BAMbinSortUnmapped.cpp insertSeqSA.cpp streamFuns.cpp ReadAlignChunk_processChunks.cpp ReadAlign_createExtendWindowsWithAlign.cpp genomeParametersWrite.cpp ReadAlign_multMapSelect.cpp ReadAlign_outputTranscriptSJ.cpp SequenceFuns.cpp ReadAlign.cpp mapThreadsSpawn.cpp loadGTF.cpp ReadAlign_assignAlignToWindow.cpp stringSubstituteAll.cpp sysRemoveDir.cpp ReadAlign_storeAligns.cpp bamRemoveDuplicates.cpp InOutStreams.cpp SharedMemory.cpp ReadAlign_oneRead.cpp ReadAlign_CIGAR.cpp Transcript.cpp SuffixArrayFuns.cpp alignSmithWaterman.cpp extendAlign.cpp Transcript_alignScore.cpp sortSuffixesBucket.cpp OutSJ.cpp sjdbLoadFromFiles.cpp blocksOverlap.cpp sjdbPrepare.cpp genomeScanFastaFiles.cpp bam_cat.c
'rm' -f ./Depend.list
g++ -pipe -std=c++11 -Wall -Wextra -fopenmp -D'COMPILATION_TIME_PLACE="Wed Feb 7 11:08:06 +06 2018 :/home/kibria/STAR/source"' -MM Chain.cpp sjdbBuildIndex.cpp ReadAlign_quantTranscriptome.cpp ReadAlign_mapOneRead.cpp BAMoutput.cpp ReadAlign_outputTranscriptSAM.cpp readLoad.cpp sjdbInsertJunctions.cpp Stats.cpp Transcriptome_geneCountsAddAlign.cpp ReadAlign_stitchPieces.cpp funCompareUintAndSuffixes.cpp STAR.cpp Parameters_readSAMheader.cpp BAMbinSortByCoordinate.cpp Genome_insertSequences.cpp Transcriptome_quantAlign.cpp funCompareUintAndSuffixesMemcmp.cpp ReadAlign_outputAlignments.cpp ReadAlign_alignBAM.cpp ReadAlign_stitchWindowSeeds.cpp Quantifications.cpp ReadAlignChunk.cpp Transcriptome.cpp PackedArray.cpp ReadAlign_outputTranscriptCIGARp.cpp ErrorWarning.cpp Parameters_openReadsFiles.cpp sjdbLoadFromStream.cpp stitchAlignToTranscript.cpp TimeFunctions.cpp stitchGapIndel.cpp genomeSAindex.cpp signalFromBAM.cpp ReadAlign_calcCIGAR.cpp genomeGenerate.cpp outputSJ.cpp Parameters_closeReadsFiles.cpp stitchWindowAligns.cpp GlobalVariables.cpp Parameters.cpp sjSplitAlign.cpp ReadAlign_chimericDetection.cpp BAMfunctions.cpp ReadAlign_maxMappableLength2strands.cpp ReadAlignChunk_mapChunk.cpp serviceFuns.cpp binarySearch2.cpp ThreadControl.cpp Genome.cpp BAMbinSortUnmapped.cpp insertSeqSA.cpp streamFuns.cpp ReadAlignChunk_processChunks.cpp ReadAlign_createExtendWindowsWithAlign.cpp genomeParametersWrite.cpp ReadAlign_multMapSelect.cpp ReadAlign_outputTranscriptSJ.cpp SequenceFuns.cpp ReadAlign.cpp mapThreadsSpawn.cpp loadGTF.cpp ReadAlign_assignAlignToWindow.cpp stringSubstituteAll.cpp sysRemoveDir.cpp ReadAlign_storeAligns.cpp bamRemoveDuplicates.cpp InOutStreams.cpp SharedMemory.cpp ReadAlign_oneRead.cpp ReadAlign_CIGAR.cpp Transcript.cpp SuffixArrayFuns.cpp alignSmithWaterman.cpp extendAlign.cpp Transcript_alignScore.cpp sortSuffixesBucket.cpp OutSJ.cpp sjdbLoadFromFiles.cpp blocksOverlap.cpp sjdbPrepare.cpp genomeScanFastaFiles.cpp bam_cat.c parametersDefault.xxd htslib >> Depend.list
g++: warning: parametersDefault.xxd: linker input file unused because linking not done
g++: warning: htslib: linker input file unused because linking not done
make: *** No rule to make target 'star'.  Stop.
root@OptiPlex-3020:/home/kibria/STAR/source# 

Any help will be highly appreciated!

Cheers,

Kibria.

**Comment by khllkcm** [comment]
Instead of `make star` try `make STAR`.
Build targets are case-sensitive.

**Comment by kibriadurlav** [comment]
Yeah I did with make STAR, but still that happens. If I remove line 20 from the bin Makefile, then also I receive an error.

**Comment by khllkcm** [comment]
Can you post the specific error message you got after running `make STAR`?

**Comment by alexdobin** [comment]
Hi Kibria,

it seems that it worked, just try to run it.
Also, you can always try the pre-compiled executables, in the bin/ directory.

Cheers
Alex

**Comment by kibriadurlav** [comment]
Hi @alexdobin  

Thank you for your reply. Yes, STAR is working now. But I am getting an error like this, 

./_STARtmp//readsCommand_read1: line 3: /dev/fd/63: Permission denied

Any idea? Sorry for being off topic.

**Comment by alexdobin** [comment]
Hi Kibria,

please post or e-mail me the Log.out file.

Cheers
Alex

**Comment by kibriadurlav** [comment]
Hi Alex,

Thank you for your reply. I re-downloaded the ENCODE fastq file, and this time it came up without any error, could be file wasn't downloaded properly. Anyway, thanks for your help. 

Cheers,
Kibria.
