### ISSUE TITLE
Precompiled binaries in 2.5.4a release say version=2.5.3a

### ISSUE THREAD

**Issue by suhrig** [alexdobin/STAR#372]
Hi Alex,

When I call the precompiled binaries (`bin/Linux_x86_64*/STAR*`) of the latest version (2.5.4a) with the argument `--version`, they say `2.5.3a_modified`. Is this intended or are the binaries built from code of version 2.5.3a?

Regards,
Sebastian

**Comment by alexdobin** [comment]
Hi @suhrig

thanks for pointing this out, I think I did not re-compile the binaries after changing the VERSION.
Will release 2.5.4b shortly.

Cheers
Alex

**Comment by alexdobin** [comment]
Please check the 2.5.4b with the correctly versioned executables.

**Comment by suhrig** [comment]
Can confirm: now the versions are updated. Thanks!
