### ISSUE TITLE
install issue on Mac

### ISSUE THREAD

**Issue by Verakhs** [alexdobin/STAR#375]
I am trying to install it on a Mac with no success. 

First I download it on Desktop
Then I find where the gcc is 

$ which gcc
/usr/bin/gcc

Then I tried to install it as follows:

make STARforMacStatic CXX=/usr/bin/gcc

which I got several errors I just copy the last errors here 

clang: warning: parametersDefault.xxd: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: htslib: 'linker' input unused [-Wunused-command-line-argument]
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
make: *** [Depend.list] Error 1

**Comment by Verakhs** [comment]
now I came to this error 
make STARforMacStatic CXX=/usr/bin/gcc
/usr/bin/gcc -c   -O3 -pipe -std=c++11 -Wall -Wextra -fopenmp -D'COMPILATION_TIME_PLACE="Mon Feb 12 18:02:34 CST 2018 :/Users/admin/Desktop/STAR-master/source"' -D'COMPILE_FOR_MAC'  SharedMemory.cpp
clang: error: unsupported option '-fopenmp'
make: *** [SharedMemory.o] Error 1

**Comment by alexdobin** [comment]
Hi Verakhs,

you are using the default OSX c++ compiler, clang, which does not have support for openMP.
You would need to install gcc, e.g. using Homebrew.
Or, you can try to use the pre-compiled Mac executables in the bin/ directory.

Cheers
Alex

**Comment by ramakrishnas** [comment]
Hi Alex,

we are stuck with the same error as above

c++ -c   -O3 -pipe -std=c++11 -Wall -Wextra -fopenmp -D'COMPILATION_TIME_PLACE="Tue Aug 28 13:46:40 CDT 2018 :/Users/mpisano/biotools/STAR-2.6.1a/source"' -D'COMPILE_FOR_MAC'  SharedMemory.cpp
clang: error: unsupported option '-fopenmp'
make: *** [SharedMemory.o] Error 1

any advice how we could resolve this. gcc installed using homebrew.

thanks
Rama

**Comment by alexdobin** [comment]
Hi Rama,

have you tried using the pre-compiled executable from  bin/MacOSX_x86_64/ ?

Cheers
Alex

**Comment by Rosswell** [comment]
@alexdobin there are a few issues surrounding this; I thought I'd add my explicit solution here since this has the most comments:

1. Install brew (http://brew.sh/)
2. `brew install gcc --without-multilib`
3. `export CXX=/usr/local/Cellar/gcc/8.2.0/bin/g++-8` 
   NOTE FOR FUTURE USERS: be sure to alter this path with whatever you have locally - gcc is v8.2.0 as of this writing
4. `make STARforMacStatic`

Hope this helps! Works for STAR 2.6.1d

**Comment by alexdobin** [comment]
Hi Ross,

thanks a lot for sharing your solution. I will add it to README file in the next release.

Cheers
Alex

**Comment by chahatupreti** [comment]
Hi Ross and Alex,

I tried what Ross had mentioned, but it upon running `make STARforMacStatic`, it gave me the error - 

`/bin/sh: ‎⁨/usr/local/Cellar/gcc/8.2.0/bin/g++-8: No such file or directory
`
Even though, when I go to the above folder, there indeed is this file. Could anyone help me out here?

Thanks,
Chahat

**Comment by chahatupreti** [comment]
Ok, so I was able to solve the issue. For some reason, using 

`
export CXX=/usr/local/Cellar/gcc/8.2.0/bin/g++-8` 

was giving the error. Changing it to - 

'CXX=/usr/local/bin/g++-8'
allowed me to install without error. What is wierd is that `/usr/local/Cellar/gcc/8.2.0/bin/g++-8` exists, so I am still not sure why it gives the `No such file or directory` error. Also, `/usr/local/bin/g++-8' is itself just an alias for `/usr/local/Cellar/gcc/8.2.0/bin/g++-8`, so ya, not sure!

**Comment by harsathAI** [comment]
It is showing Error: invalid option: --without-multilib Error. What to do?

**Comment by Rosswell** [comment]
@harsathAI what version of `gcc` are you trying to install?

**Comment by alexdobin** [comment]
Hi Harsath,

the easiest thing is to use the pre-compiled executables in bin/MacOSX_x86_64/

Cheers
Alex

**Comment by thisisamirv** [comment]
First:

`brew install gcc`

Then:

`brew link --overwrite gcc`

Finally in the source folder, run:

`make CXX=/usr/local/bin/g++-12`
