### ISSUE TITLE
--genomeChrBinNbits documentation contradictory description

### ISSUE THREAD

**Issue by ndaniel** [alexdobin/STAR#377]
Hi Alex,

in documentation of STAR 2.5.4b. [here](https://github.com/alexdobin/STAR/blob/master/doc/STARmanual.pdf) one has that  `--genomeChrBinNbits` should be

* at page 19:
```
min(18,log2[max(GenomeLength/NumberOfReferences,ReadLength)]).
```
* at page 6
```
min(18, log2(GenomeLength/NumberOfReferences)).
```

Which one is it?

Best Regards,
Daniel

**Comment by alexdobin** [comment]
Hi Daniel,

the min(18,log2[max(GenomeLength/NumberOfReferences,ReadLength)]) is the correct one, as I found out only recently. I will fix the manual, thanks for pointing it out. Of course, it only affects the cases where the average reference length is less than the read length, which should be pretty rare.

Cheers
Alex
