### ISSUE TITLE
ReadAlignChunk_processChunks.cpp:115:processChunks EXITING because of FATAL ERROR in input reads: unknown file format: the read ID should start with @ or > 

### ISSUE THREAD

**Issue by ranijames** [alexdobin/STAR#379]
Dear All,
I am using STAR aligner to align a single fastq file, using default parameters on 2-pass mode. But it is throwing following error,
ReadAlignChunk_processChunks.cpp:115:processChunks EXITING because of FATAL ERROR in input reads: unknown file format: the read ID should start with @ or > 
Any help or advice would be great 
Thank you

**Comment by alexdobin** [comment]
Hi @ranijames,

it seems you have a problem with the fastq files formatting. Please try to unzip your files before mapping and look at first few lines. If they look OK, try to map one read with --readMapNumber 1.
If it does not work, please send me the Log.out file.

Cheers
Alex

**Comment by santiagosnchez** [comment]
It would be nice to have ZLIB compression/decompression support. Having to decompress all your fastq file can be burdensome on small systems.

**Comment by alexdobin** [comment]
Hi Santiago,

at the moment, you can use --readFilesCommand zcat to unzompress the gzipped files on-the-fly.

Cheers
Alex

**Comment by jshaik1979** [comment]
The issue is not with the files themselves. The issue is with compression. STAR doesn't support compressed files. I had the same issue. works fine after unzipping the fastq files

**Comment by ayushiso** [comment]
I am facing the same issue, and it works fine with small values of --readMapNumber. However it gives this error if I do not specify the number of reads. Is there a way around this? Thanks!

**Comment by lcolladotor** [comment]
Uncompressing with zcat prior to running STAR helped us work around this issue on a SGE cluster. Might be the `fifo` issue you mentioned last year. Anyway, thank you for this thread!
