### ISSUE TITLE
Segmentation fault when aligning to small reference

### ISSUE THREAD

**Issue by tylo42** [alexdobin/STAR#380]
See the attached zip with the reference (GCF_002101675.1_ASM210167v1_genomic.fna), fastq with a single read (reads.fq), and script (test_case.sh) that builds and aligns with my arguments to reproduce the segmentation fault.

I built the index and aligned with the following commands.
```
./STAR --runMode genomeGenerate \
	--genomeDir ./genomeDir \
	--genomeFastaFiles ./GCF_002101675.1_ASM210167v1_genomic.fna \
	--genomeSAindexNbases 9 \
	--genomeChrBinNbits 15

./STAR --genomeLoad LoadAndKeep \
	--genomeDir ./genomeDir \
	--readFilesIn reads.fq \
	--outFileNamePrefix ./result/out \
	> /dev/null
```
[STAR_failure.zip](https://github.com/alexdobin/STAR/files/1752066/STAR_failure.zip)

**Comment by alexdobin** [comment]
Hi Tylee,

as described in the manual :) for small genomes, the parameter --genomeSAindexNbases must be scaled down to min(14, log2(GenomeLength)/2 - 1).

Cheers
Alex

**Comment by tylo42** [comment]
Genome length is 7601632 and there are 260 contigs.

For some reason I was doing min(14, log2(GenomeLength)/2 - **2**). When I change genomeSAindexNbases from 9 to 10, I still get the segmentation fault. I've also set genomeChrBinNbits to 15, min(18, log2(GenomeLength/NumberOfReferences)) = 14.8.

**Comment by alexdobin** [comment]
Hi Tyler,

Please try to go even lower with --genomeSAindexNbases, say 6 or even 4.
This is not a precise scaling as it depends on the k-mer composition of the genome.

Cheers
Alex
