### ISSUE TITLE
I can not map normally.can not get my bam file and the log.progress.out file is always 236

### ISSUE THREAD

**Issue by 909089617xx** [alexdobin/STAR#384]
Hi,I'm a green hand.about STAR. I have a problem maybe it is easy.......
when I use STAR to map .I can not get my bam file and the log.progress.out file is always 236.
my code is
`$ /home/aoyue/xujun/STAR-2.5.3a/bin/Linux_x84_64_static/STAR \
> --runThreadN 64 --genomeDir /home/aoyue/xujun/generateindex \
> --sjdbGTFfile /home/aoyue/xujun/generateindex/Zea_mays.AGPv4.38.gtf --sjdbOverhang 150 \
> --readFilesIn /home/aoyue/xujun/test-third/PL_BC10.fq \
> --outSAMtype BAM Unsorted`
Always stay in the map phase and can not get any result .
thanks very much.

**Comment by alexdobin** [comment]
Hi,

please send me the Log.out file.

Cheers
Alex

**Comment by 909089617xx** [comment]
thanks for you reply.i have solved this question.but i have another question.
the GeneCounts mode is similar with the HTSeq? i use the both method but i get the different result.the number of reads mapped to the gene in HTSeq is smaller,i am so wordering. and i 
 want to know what the different between the unmapped and no_feature in the output file ReadsPerGene.out.tab.
looking for you reply. thanks.

**Comment by alexdobin** [comment]
Hi,

the GeneCounts should be exactly equal to the ones produced by htseq-count.
If you have an example where this is not true, please send it to me.

Cheers
Alex

**Comment by 909089617xx** [comment]
thanks for your reply.
according to the STAR ,the reads are mapped to 45578 genes,but the HTSeq-count is 46272 genes.and the  __no_feature __ambiguous __too_low_aQual __not_aligned __alignment_not_unique are not same.i just know the HTSeq-count contains the mt genes more.following are the two files.
[ReadsPerGene.out.tab.txt](https://github.com/alexdobin/STAR/files/1813587/ReadsPerGene.out.tab.txt)
[output_usingbam.counts.txt](https://github.com/alexdobin/STAR/files/1813588/output_usingbam.counts.txt)
and i wordering what is the normal uniquely mapped rates.i have many data about different methods but the results look not good.
this is my code:
`

![image](https://user-images.githubusercontent.com/33317454/37438317-becfa1be-282c-11e8-9768-9cf4de0ba808.png)

`
and this is my log.final.out
![image](https://user-images.githubusercontent.com/33317454/37438378-095cb442-282d-11e8-95fd-bfecefae5b75.png)
is something wrong with my code.It is said that this data had a  highly sequencing depth but I can not get it according to the  document generated by genecount mode.here is the densityplot according to the ReadsPerGene.out.tab file
![image](https://user-images.githubusercontent.com/33317454/37438488-bf24b0d6-282d-11e8-9eb7-44af34b0d116.png)


this is my log.out file.
[Log.out.txt](https://github.com/alexdobin/STAR/files/1813625/Log.out.txt)
thinks a lt

**Comment by alexdobin** [comment]
Hi,

the ReadsPerGene and htseq files contain different number of lines - this means that you used different GTF files for STAR run and the htseq-count? This would explain the different counts.

You unique mapping rate is on the low side, and multimapped and unmapped rates are on the high side. I would recommend BLASTing a few of unmapped reads to see if there is any contamination. Also, interestingly, you have a very low splicing rate (number of splices / number of unique mappers).

Cheers
Alex

**Comment by 909089617xx** [comment]
no,i am sure i use the same GTF--Zea_mays.AGPv.38.gtf.waht is the problem with me?and can you tell me what the different between noFeature and unmapped? and i wording what the meaning of the count number of each gene in ReadPerGene.out.tab?it 
means uniquelly mapping?

i think the reason why the mapped result is not good  is because reads are the end of 3 which contains lots of T.
thanks a lot.

**Comment by alexdobin** [comment]
Hi,

please compare the list of gene names in the STAR output and htseq-count, they should coincide.

unmapped - no alignment to the genome
noFeature - aligned to the genome, but no overlap with exons

Cheers
Alex
