### ISSUE TITLE
Need recommendation about combining Single ended and Paired ended read alignments

### ISSUE THREAD

**Issue by sagnikbanerjee15** [alexdobin/STAR#385]
Hello,

I have two groups of data for the same sample. One is a single ended data and the other is paired ended. I have aligned the two data separately to the genome. For the downstream analysis, is it fine to merge the two alignment files and treat them as one? I have plans to perform assembling with stringtie and/or trinity.

Thanks.

**Comment by alexdobin** [comment]
Hi Sagnik,

it is possible to merge two BAM files with SE and PE alignments. However, the downstream software may or may not allow such mixture, you would have to just try it or ask their Authors.

Cheers
Alex
