### ISSUE TITLE
Unmapped Other in short, low complexity regions

### ISSUE THREAD

**Issue by IanHuntress** [alexdobin/STAR#386]
Hello,
In general, is STAR suitable for aligning reads that are quite different from the query (about 70% matches)? I am mapping short read archives with 150bp reads to a low complexity, short reference, 300bp (--genomeSAindexNbases=3). I have been tinkering with settings to make STAR as relaxed as possible, but I always end up with a large percent >95 unmapped other reads. I understand that --winAnchorMultimapNmax, is recommended when it appears that real reads are failing to anchor, but I am still finding very few obviously true reads.

Recommendations?

Thanks,
Ian

**Comment by alexdobin** [comment]
Hi Ian,

at present, I would not recommend STAR for error rate or divergency of >5%.  I am working on algorithms for higher error rate mapping, but it's a long term project.

Cheers
Alex
