### ISSUE TITLE
Transferring chromosome alignments to transcript alignments

### ISSUE THREAD

**Issue by sagnikbanerjee15** [alexdobin/STAR#388]
Hello,

I am using STAR to map my reads to the genome. I have the -quantMode TranscriptomeSAM mode on so that I can get the read maps transferred to the transcriptome. I have found cases where the cigar string changes when the map is transferred. For example, I have a read of length 117 which has the cigar string 3S114M in the *Aligned.sortedByCoord.out.bam file. When I search for the cigar string of the same read in the *Aligned.toTranscriptome.out.bam file I found that the cigar has changed to 117M. I aligned the read to only the transcriptome, by preparing an index proving the transcriptome in place of the genome, and I got the cigar string as 3S114M. Could you please let me know how I can get the correct cigar?

Thanks.

**Comment by alexdobin** [comment]
Hi Sagnik,

what you see is a feature designed to work with RSEM, by default. Since RSEM does not accept soft-clipped reads, the transcriptomic alignments have to be expanded through the soft-clipped bases, unless it violates the max number of mismatches allowed. If you are not using RSEM, you can specify --quantTranscriptomeBan Singleend (instead of default IndelSoftclipSingleend).

Cheers
Alex

**Comment by sagnikbanerjee15** [comment]
Thank you Alex!!

**Comment by sagnikbanerjee15** [comment]
Hello,

I was trying to run STAR but I keep running into the following issue. Could you please help with this?
Mar 10 12:08:05 ..... started sorting BAM
Max memory needed for sorting = 950262208

EXITING because of FATAL ERROR: number of bytes expected from the BAM bin does not agree with the actual size on disk: 839752750   0   16

Mar 10 12:08:05 ...... FATAL ERROR, exiting

EXITING because of FATAL ERROR: number of bytes expected from the BAM bin does not agree with the actual size on disk: 835727466   0   15

Mar 10 12:08:05 ...... FATAL ERROR, exiting

EXITING because of FATAL ERROR: number of bytes expected from the BAM bin does not agree with the actual size on disk: 832457357   0   14

Mar 10 12:08:05 ...... FATAL ERROR, exiting

EXITING because of FATAL ERROR: number of bytes expected from the BAM bin does not agree with the actual size on disk: 835163564   0   12

Mar 10 12:08:05 ...... FATAL ERROR, exiting

EXITING because of FATAL ERROR: number of bytes expected from the BAM bin does not agree with the actual size on disk: 854778928   0   11

Mar 10 12:08:05 ...... FATAL ERROR, exiting
Mar 10 12:08:05 ...... FATAL ERROR, exiting

EXITING because of FATAL ERROR: number of bytes expected from the BAM bin does not agree with the actual size on disk: 839849790   0   13

Mar 10 12:08:05 ...... FATAL ERROR, exiting
Thanks.

**Comment by sagnikbanerjee15** [comment]
Hello Alex,

I have fixed the above issue. Could you please tell me how I can both versions of transcriptome mappings from a single run of STAR.

Thanks.

**Comment by alexdobin** [comment]
Hi Sagnik,

you can run STAR with --outSAMtype BAM Unsorted (or SortedByCoordinate, or both) and --quantMode TranscriptomeSAM, which will generate both the genomic and transcriptomic BAMs.

Cheers
Alex
