### ISSUE TITLE
Issue with the 'Mapping RNA-seq Reads with STAR' paper?

### ISSUE THREAD

**Issue by mikecroucher** [alexdobin/STAR#389]
Hi

I'm helping someone run STAR on our HPC service.  As such, I am not a bioinformatician and I apologise if I'm soing something stupid.

 We are looking at 'Alternate Protocol 1: Generating Genome Indices' of the paper at https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4631051/ 

2. Says

Run STAR to generate genome indices specifying correct path to the genome FASTA and annotations GTF file:

Then gives this command

```
~/star/code/STAR-STAR_2.4.0k/bin/Linux_x86_64/STAR \
--runThreadN 12 --runMode genomeGenerate --genomeDir ./ \
--genomeFastaFiles ./Homo_sapiens.GRCh38.dna.primary_assembly.fa
```

There is no mention of the .gtf file in this command. Should there be?

Additionally, this output is listed

```
Inspect the generated files (sizes will vary depending on the genome size):

ls -sh1
4.0K chrLength.txt
4.0K chrNameLength.txt
4.0K chrName.txt
4.0K chrStart.txt
3.0G Genome
4.0K genomeParameters.txt
1.2G Homo_sapiens.GRCh38.79.gtf
3.0G Homo_sapiens.GRCh38.dna.primary_assembly.fa
 40K Log.out
 23G SA
1.5G SAindex
```

The person I am helping says 'Because of the above text, the STAR command hasn't worked because there should be a .gtf file in the output'

I think that the .gft file is input, not output. However, I can't see anywhere in the paper where it says we should have put the .gtf file in this directory.

Can you help please?

Cheers,
Mike

**Comment by alexdobin** [comment]
Hi Mike,

this is a mistake in the paper, the GTF file is not generated by STAR, it's an input file same as Homo_sapiens.GRCh38.dna.primary_assembly.fa - though it's not used in this particular "Protocol".
I am sorry for the inconvenience.

Cheer

**Comment by mikecroucher** [comment]
Thanks for the clarification. It's a pity that we can't do PRs on papers ;)
