### ISSUE TITLE
Transferring mapping to transcriptome

### ISSUE THREAD

**Issue by sagnikbanerjee15** [alexdobin/STAR#390]
Hello,

I have performed the alignment of a group of reads to the genome. The run of STAR has finished without any problem. I was wondering if I can now transfer the mappings to the transcriptome without having to run the complete process of STAR again.

Thanks.

**Comment by alexdobin** [comment]
Hi Sagnik,

this is impossible at the moment - you would need to re-run the mapping with --quantMode TranscriptomeSAM.

Cheers
Alex
