### ISSUE TITLE
STAR + RSEM for lncRNA

### ISSUE THREAD

**Issue by hirokomatsui** [alexdobin/STAR#392]
Hello,

I'm trying to analyze long non-coding RNA expression using STAR and RSEM.
I have generated STAR index using reference genome and lnc database GTF instead of transcriptome. The lnc database GTF includes the feature only "exon" and no transcript. I'm wondering if this makes a problem.

When I ran STAR alignment, the output Aligned.toTranscriptome.out.bam file includes soft-clipped CIGAR. So RSEM complained about that.

Here's the command lines to generate index and alignment. Is there any good way to solve this type of problem using STAR? I'm looking for the speed, so STAR would be the best choice for the aligner.

> STAR --runThreadN 32 --runMode genomeGenerate \
--sjdbOverhang 250 \
--genomeDir star_index/NONCODE \
--genomeFastaFiles /publicdata/hg19_20151104/hg19_sorted.fa \
--sjdbGTFfile star_index/NONCODE/NONCODEv5_hg19.lncAndGene.gtf

> STAR --runThreadN 32 \
--genomeDir star_index/NONCODE \
--genomeLoad NoSharedMemory \
--readFilesCommand zcat \
--readFilesIn fastq/R1.fastq.gz fastq/R2.fastq.gz \
--outSAMattributes All \
--outSAMunmapped Within \
--outSAMattrRGline ID:1 PL:ILLUMINA PU:AAAA LB:sample SM:sample \
--outFilterMultimapNmax 20 \
--outFilterMismatchNmax 999 \
--alignIntronMin 20 \
--alignIntronMax 1000000 \
--alignMatesGapMax 1000000 \
--outSAMtype BAM Unsorted \
--quantMode TranscriptomeSAM \
--outFileNamePrefix NONCODE/sample/

Best,
Hiroko

**Comment by alexdobin** [comment]
Hi Hiroko,

"exon" lines are the only lines that STAR reads. Please make sure that each line has "transcript_id" and "gene_id" tags.  However, I do not think this would cause the soft-clipping in the  Aligned.toTranscriptome.out.bam file. What does the RSEM error look like?

Cheers
Alex

**Comment by hirokomatsui** [comment]
Hi Alex,

RSEM output on STDERR:
RSEM does not support gapped alignments, sorry!

on STDOUT:
"rsem-parse-alignments /publicdata/rsem_reference_hg19_20180314/NONCODEv5_hg19.lncAndGene NONCODE/489aaf87-17d5-4483-908b-403bbbf06f95/.temp/ NONCODE/489aaf87-17d5-4483-908b-403bbbf06f95/.stat/ b NONCODE/489aaf87-17d5-4483-908b-403bbbf06f95/Aligned.toTranscriptome.out.bam -t 3 -tag XM" failed! Plase check if you provide correct parameters/options for the pipeline!

Every record in GTF file has gene_id and transcript_id defined. Here's an example of a line in GTF file:
chr1    NONCODEv5   exon    11871   14412   0   +   .   gene_id "NONHSAT000002.2"; transcript_id "NONHSAT000002.2";

Thank you,
Hiroko

**Comment by hirokomatsui** [comment]
I also see some CIGAR in the file, Aligned.toTranscriptome.out.bam, are very strange. e.g:

K00161:194:HNY7GBBXX:4:1101:30442:22801 403     NONHSAT167398.1 1218    3       103M1S  =       1217    103     GTC
TCTGACCTCAAAGATCTTAAAACTGTTTACTTACTCATCTCCCATGAGCAATTAATTTAATCTGAACCTCTCTTCCTTCTTAGGTGGAACCAAAAAAATC    JJJJJJJJJJJ
JJJJJJJJJJJJJJJFJJJJJJJJJJJJJJJJJJJJJFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFFFAA    NH:i:2  HI:i:2  RG:
Z:1
K00161:194:HNY7GBBXX:4:1101:30442:22801 355     NONHSAT167398.1 1217    3       268435455S104M1S        =       121
8       -103    GTCTCTGACCTCAAAGATCTTAAAACTGTTTACTTACTCATCTCCCATGAGCAATTAATTTAATCTGAACCTCTCTTCCTTCTTAGGTGGAACCAAAAA
AATCA   AAFFFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ  NH:i:2   HI:i:2  RG:Z:1

The reference transcript is:
chr13   NONCODEv5   exon    27837546    27842790    0   .   .   gene_id "NONHSAT167398.1"; transcript_id "NONHSAT167398.1";

which has unknown strand, '.' Can it be a problem?

Thanks you!

**Comment by alexdobin** [comment]
Hi Hiroko,

It looks like the "gene_id" and "transcript_id" are always the same in this GTF.
This is only allowed if all the genes are have single transcripts, is this the case?
The lack of strand may create a problem, please try to add the strand to all the exon lines.

Also, which version of STAR are you using?

Cheers
Alex

**Comment by hirokomatsui** [comment]
Hi Alex,

That's right. gene_id and transcript_id are always the same, and they are unique. So I think it's ok.
I'm using STAR_2.5.0a. I'll try to run as fixing the strand.
What problem can you think of if wrong strands were assigned?

Thanks,
Hiroko

**Comment by hirokomatsui** [comment]
Hi Alex,

RSEM now output errors:
The alignment of fragment K00161:194:HNY7GBBXX:4:1211:5101:38187 to transcript 242684 starts at -1 from the forward direction, which should be a non-negative number! It is possible that the aligner you use gave different read lengths for a same read in SAM file.

I see same messages for 6 reads, which were aligned to multiple transcripts.
I'm thinking maybe I should run the analysis in some other way because the GTF file I'm using for STAR index are actually includes only transcripts but said as exon. We have only transcript information but exon.

Thank you,
Hiroko

**Comment by hirokomatsui** [comment]
OK. Thank you for your help!
