### ISSUE TITLE
1 or 2 bp difference in the nearest acceptor/donor sites.

### ISSUE THREAD

**Issue by tangchao7498** [alexdobin/STAR#393]
Dear Alex and all,
I have run STAR(2.5.3a) with the default setting for some human RNA-seq data(100bp PolyA+), and used The output SJ.out.tab file for splice junction analyses. But I came across many cases in which the donor or acceptor sites are within only 1 or 2 bp distance from the next one, such as the following case:
Chr:Start-End
1:629566-907534
1:629566-907535

The junction end’s distance = 907535 – 907534 = 1

However, the GT-AG rule of splicing site makes these 1 or 2 bp distance very unlikely. I can understand the 3 bp difference since they were reported as NAGNAG motif.

I've counted the frequency of the junctions that the distance is less than or equal to 6 bp.

Distance | Frequency | No. all junctions | Percentage(%)
1 | 1263 | 363663 | 0.35
2 | 1731 | 363663 | 0.48
3 | 2111 | 363663 | 0.58
4 | 1972 | 363663 | 0.54
5 | 1039 | 363663 | 0.29
6 | 939 | 363663 | 0.26

As you can see, there are many cases the distance of the nearest donor/acceptor site to be 1 or 2 bp.

Have you come across this problem before, is it due to the alignment, or mismatch/indel in the read? Please let me know if you have any suggestions on how to deal with this problem.

Many thanks,
 Chao Tang

**Comment by alexdobin** [comment]
Hi Chao,

I believe we have seen similar levels of such shifted splicing in ENCODE data.
An interesting biological explanation for these difference could be the spliceosome errors, i.e. imprecise excision of introns. Of course, it's also possible that these are cloning/sequencing indels, personal indels, or reference assembly errors.

Cheers
Alex

**Comment by jsnedecor** [comment]
I actually am seeing an even odder situation where we're getting junctions of length zero. From SJ.out.tab: 

chr14	21023306	21023306	1	3	1	0	2	1

It's easy to filter after the fact, but it's very strange that something like this is added in the first place. Here are the reads overlapping this junction generated from this command in samtools: 

samtools view file_rep1.bam chr14:21023306-21023307 > empty_junction_chr14.txt

https://drive.google.com/file/d/1p6b0a-aAXHL3UZh3ECWDKzXfJIDrUlWq/view?usp=sharing

It's not critical, we can easily filter out these junctions afterwards, but I'm curious why they're happening.

**Comment by alexdobin** [comment]
Hi June,

sorry for the belayed reply, better to start a new topic than continue with the old one, as the old ones do not get on top of the list even if new comments are added.

This junction has a gap of 1 base, since SJ.out.tab encodes 1-based start and end of the intron, and it's extracted in the GENCODE annotations. I have asked them some time ago about such short introns (they have a few), and their answer was that it is used to preserve ORFs. It may be caused caused by an erroneous 1b insertion in the reference, or, even more likely, by a minor allele in the individual the reference was sequenced from.

Cheers
Alex

**Comment by jsnedecor** [comment]
Ah, I see. Like I said, not a huge deal, just odd to see.
