### ISSUE TITLE
Recommendations for GCC version

### ISSUE THREAD

**Issue by marcc-hpc** [alexdobin/STAR#394]
In the release notes:

RELEASEnotes.md: **STAR now uses essential c++11 features. Compiling from sources requires gcc 4.7.0 or later.**

Can you also add a note on the main README for those compiling from source?

Which GCC are you commonly working with - we'd like to match the compiler to the one used in development.

Thanks!

**Comment by alexdobin** [comment]
Hi @marcc-hpc

I am using 5.3.0 in development, but I always check the 4.7.0 can still compile it.

Cheers
Alex

**Comment by marcc-hpc** [comment]
Thanks, we are using 5.4.0 in our current compilation.

(Kevin)
