### ISSUE TITLE
Segfault when running 2.4.1c with a blank GTF file

### ISSUE THREAD

**Issue by jhart99** [alexdobin/STAR#40]
I ran across an unhandled exception while running a test case. 

    STAR --runMode genomeGenerate --genomeFastaFiles ${genomeRefFa} ${spikeInFa} --sjdbOverhang 100 --sjdbGTFfile ${combinedGtf} --runThreadN 12 --genomeDir ${starRefIndexDir} --outFileNamePrefix ${starRefIndexDir

Results in 

    May 08 03:43:03 ..... Processing annotations GTF
    8 Segmentation fault      (core dumped)

When $combinedGtf points to an existing yet blank file.

**Comment by alexdobin** [comment]
Hi Jonathan,

thanks a lot for reporting this bug. It will be fixed in 2.4.1e

Cheers
Alex
