### ISSUE TITLE
Feature Counting Exon vs. Non

### ISSUE THREAD

**Issue by bbimber** [alexdobin/STAR#400]
Hello,

I am trying to compare gene counts obtained from 10x data (which aligns using STAR, but calls features differently), against counts generated purely by STAR.  10x will only count reads within exons.  The STAR manual wasnt clear on this point: in --quantMode, will it count only those reads within annotated exons, or will other reads in that gene be counted?  We work in rhesus macaque, and there are sometimes problems w/ incomplete annotation, which I believe is resulting in zero counts through 10x's feature counting.

Thanks.

**Comment by alexdobin** [comment]
Hi @bbimber 

STAR counts any reads overlapping gene exons by at least one base.
With this rule, reads that reside entirely within introns are not counted.
Multimapping reads and reads that overlap exons from different genes are not counted.

I think the easiest way to resolve the discrepancies is to look at the alignment in the browser (e.g. IGV), count them manually for a few genes, and compare with the results from 10x counting or STAR counting.
I imagine one of the discrepancies coming from 10x counting only reads mapping exactly to the annotated 3' ends of the genes, while STAR would count any reads overlapping exons.

Cheers
Alex

**Comment by bbimber** [comment]
Hi Alex - thanks for the reply.  We'll be looking more carefully into this.
