### ISSUE TITLE
98% of reads not mapped

### ISSUE THREAD

**Issue by amit4mchiba** [alexdobin/STAR#402]
Hi, 

I wanted to perform genome-guided transcriptome assembly for a plants species. So, I performed RNA-seq for multiple tissues. I obtained genome from this site-https://genome.jgi.doe.gov/portal/pages/dynamicOrganismDownload.jsf?organism=Aofficinalis

I obtained genome assembly and annotation file (in gff3 format). Then I performed genome building through this command-
STAR --runThreadN 4 \
--runMode genomeGenerate \
--genomeDir /home2/amit8chiba/All_RNAseq_RD/Ryo-san_project/Trinity_all_A_officinale/A_officinale_genome_guided_assembly/A_offi_genome \
--genomeFastaFiles /home2/amit8chiba/All_RNAseq_RD/Ryo-san_project/Trinity_all_A_officinale/A_officinale_genome_guided_assembly/Aofficinalis_498_Aspof.V1.fa \
--sjdbGTFfile /home2/amit8chiba/All_RNAseq_RD/Ryo-san_project/Trinity_all_A_officinale/A_officinale_genome_guided_assembly/Aofficinalis_498_V1.1.gene_exons.gff3 \
--sjdbGTFtagExonParentTranscript Parent \
--sjdbOverhang 100

The genome build was successful and no error was issued. Then I performed Trimmomatic based low quality reads removal and adaptors removal, and thus obtained reads were mapped following this command-
STAR --runThreadN 4 \
--genomeDir /home2/amit8chiba/All_RNAseq_RD/Ryo-san_project/Trinity_all_A_officinale/A_officinale_genome_guided_assembly/A_offi_genome \
--readFilesIn /home2/amit8chiba/All_RNAseq_RD/Ryo-san_project/Trinity_all_A_officinale/A_officinale_genome_guided_assembly/A_offi_3T_calus_Tm_left.fastq /home2/amit8chiba/All_RNAseq_RD/Ryo-san_project/Trinity_all_A_officinale/A_officinale_genome_guided_assembly/A_offi_3T_calus_Tm_left.fastq \
--outSAMtype BAM SortedByCoordinate

Both plant species are the same although from different ecological locations. Results are surprising as only 2% of total reads were mapped and 98% were said as unmapped for being too short. I used Illumina paired end sequencing (2x100bps). While I never expected absolute matching for all reads, but this much of unmapped reads are surprising and not possible. Please advice me where i am wrong. I am attaching output files for genomeBuilding and mapping process.

[Log.out.zip](https://github.com/alexdobin/STAR/files/1918092/Log.out.zip)

**Comment by amit4mchiba** [comment]
Just to add on, I then decided to run mapping but using only one read instead of the pair. Interestingly, now, 99% of reads are getting mapped with 85% being unique. This is strange as it seems then the issue is while using paired end reads. Is there solution for this? Thank you in advance for your advice.

**Comment by alexdobin** [comment]
Hi @amit4mchiba 

please try to do the mapping without the Trimmomatic step, as it may have changed the order of the reads for read1 and read2. You need to use parameters in Trimmomatic that enforce the order of the reads - e.g. if it removes read1 it also need to remove read2.

Cheers
Alex
