### ISSUE TITLE
STAR as an alternative to NCBI BLAST

### ISSUE THREAD

**Issue by sagnikbanerjee15** [alexdobin/STAR#404]
Hello,

I was using BLAST to detect reads which map to the transcriptome. BLAST is sensitive but takes a very long time to complete. The libraries I am working with are pretty large (>10M). I was wondering if I could use STAR as an alternative to BLAST. Can you suggest the values of parameters which would make the STAR run very similar to BLAST but much faster?

Thanks.

**Comment by alexdobin** [comment]
Hi Sagnik,

what is the total length and the number of your references. It's doable, but might require a lot of RAM and will certainly require some tweaking of parameters.

Cheers
Alex

**Comment by sagnikbanerjee15** [comment]
Hello Alex,

I have several different libraries with varying sizes. For some libraries there are as many as 20M reads whereas some libraries have only 2M reads. In total there are 6852 fasta sequences in the reference. The reads in the libraries are derived from insert sequences which are flanked by a known vector sequence. Most of the reads will map perfectly with the transcriptome which is what I have to find. Could you please suggest some parameters which will quicken the search and be sensitive enough to recognize those reads?

Thank you.

**Comment by alexdobin** [comment]
Hi Sagnik,

STAR should not have any problems with the reads map perfectly.
What is the length of the reads?
Can you trim the known vector sequences from the reads before mapping?

Cheers
Alex

**Comment by sagnikbanerjee15** [comment]
Thank you Alex. I have been successful in mapping the reads to both the genome and the vector sequences using STAR. I have used the cigar string to perform trimming as well.
