### ISSUE TITLE
Install STAR on Mac + STAR command issues

### ISSUE THREAD

**Issue by hlhorsnell** [alexdobin/STAR#405]
Hi all,

New to GitHub and RNAseq so bare this is mind. I have been reading a number of threads on similar issue but have not been able to resolve my problems.

1st I downloaded and installed gcc via the home-brew software but then got this message when trying to compile STAR from source

eduroam-int-dhcp-97-99-151:STAR-2.5.4B harryhorsnell$ cd source
eduroam-int-dhcp-97-99-151:source harryhorsnell$ make STARforMacStatic CXX=/path/to/gcc
/path/to/gcc -c   -O3 -pipe -std=c++11 -Wall -Wextra -fopenmp -D'COMPILATION_TIME_PLACE="Tue 24 Apr 2018 09:06:56 BST :/Users/harryhorsnell/documents/LMCB/Rotation_3_Janos_Lab/STAR_source_code/STAR-2.5.4B/source"' -D'COMPILE_FOR_MAC'  SharedMemory.cpp
make: /path/to/gcc: No such file or directory
make: *** [SharedMemory.o] Error 1

eduroam-int-dhcp-97-99-151:source harryhorsnell$ make STARforMacStatic
c++ -c   -O3 -pipe -std=c++11 -Wall -Wextra -fopenmp -D'COMPILATION_TIME_PLACE="Tue 24 Apr 2018 09:07:16 BST :/Users/harryhorsnell/documents/LMCB/Rotation_3_Janos_Lab/STAR_source_code/STAR-2.5.4B/source"' -D'COMPILE_FOR_MAC'  SharedMemory.cpp
clang: error: unsupported option '-fopenmp'
make: *** [SharedMemory.o] Error 1

eduroam-int-dhcp-97-99-151:source harryhorsnell$ gcc
clang: error: no input files

Next I opened the precompiled STAR into mac terminal, then tried using the following command line and received the message below

./STAR --runThreadN 6 --runMode genomeGenerate --genomeDir /path/to/Users/harryhorsnell/Documents/LMCB/Rotation_3_Janos_Lab/Harry/RNAseq --genomeFastaFiles Mus_musculusv87.GRCm38.cdna.all.fa --sjdbGTFfile Mus_musculusv87.GRCm38.cdna.all.fa  ; exit;

eduroam-int-dhcp-97-99-151:~ harryhorsnell$ ./STAR --runThreadN 6 --runMode genomeGenerate --genomeDir /path/to/Users/harryhorsnell/Documents/LMCB/Rotation_3_Janos_Lab/Harry/RNAseq --genomeFastaFiles Mus_musculusv87.GRCm38.cdna.all.fa --sjdbGTFfile Mus_musculusv87.GRCm38.cdna.all.fa  ; exit;

-bash: ./STAR: No such file or directory
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

I am quite frustrated that I haven't figured it out myself because I imagine it is something quite basic, but hopefully the community can help me out here. 

Let me know if this is the wrong place for this kind of post and if I should include more information

Thanks in advance,
Harry

**Comment by alexdobin** [comment]
Hi Harry,

I would recommend that you first try the pre-compiled STAR executable from <STAR-distribution>/bin/MacOSX_x86_64/ - if it works, you do not need to worry about compilation.

If you want to compile, you need to install gcc before you can compile STAR - the c++ compiler on Mac, clang, does not have openMP support that STAR requires. The easiest way to install gcc is through Homebrew. After that, you will need to replact /path/to/gcc with the actual path where it got installed.

Cheers
Alex

**Comment by hlhorsnell** [comment]
Hi Alex,

Thanks for the reply, I have followed your advice and I have now got the STAR executable to work from the pre-complied STAR. 

Thanks again,
Harry
