### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by guillaume-rs** [alexdobin/STAR#407]
Hi Alex,

I used STAR to align the reads of 72 samples.
It worked perfectly except for one.

When I launch the command for this sample I get a segmentation fault error ("erreur de segmentation" in french) : 

~/Soft/STAR-master/source/STAR --genomeDir ./reference/genome/STAR_index --readFilesIn ./adapters_trimming/trimmed_fastq/${SAMPLE}_R1_001_trimmed.fastq ./adapters_trimming/trimmed_fastq/${SAMPLE}_R2_001_trimmed.fastq --outFileNamePrefix ./mapping/${SAMPLE}/${SAMPLE} --twopassMode Basic --outSAMtype BAM SortedByCoordinate; 
Apr 24 14:47:14 ..... started STAR run
Apr 24 14:47:14 ..... loading genome
Apr 24 14:47:21 ..... started 1st pass mapping
Erreur de segmentation (core dumped)

I tried with different number of threads and it did not change the outcome.
I've got 32 Go of RAM and It doesn’t seem to be fully used during the mapping.
I tried with a reduce fastq of 100000 reads, and it worked fine, so it is maybe linked to the size of my fastq (even if other samples with the same number of reads ended well)
I tried to reindex the genome with parameters : --genomeSAindexNbases 6 --genomeChrBinNbits 10 ,
but I still get the error.

Could you give me some hints to overcome this?
(enclosed the log files)

Thank you for your help,

Guillaume

[Np-BLog.progress.out.txt](https://github.com/alexdobin/STAR/files/1942889/Np-BLog.progress.out.txt)
[Np-BLog.out.txt](https://github.com/alexdobin/STAR/files/1942890/Np-BLog.out.txt)
[Np-BLog.final.out.txt](https://github.com/alexdobin/STAR/files/1942891/Np-BLog.final.out.txt)
[Np-BSJ.out.tab.txt](https://github.com/alexdobin/STAR/files/1942892/Np-BSJ.out.tab.txt)

**Comment by alexdobin** [comment]
Hi @guillaume-rs 

I think you have downloaded STAR from the "master". This is generally not recommended as it may contain an unstable developer version. Please download the latest release [https://github.com/alexdobin/STAR/releases/tag/2.6.0a](https://github.com/alexdobin/STAR/releases/tag/2.6.0a)
If the problem persists, please try to reduce the set of reads to the minimal one that still seg-faults
and send it to me. You can use --readMapNumber 200000 and then double it until the error re-appears.

Cheers
Alex

**Comment by guillaume-rs** [comment]
Hi Alex,

Thank you for the advice, I'll use the latest release instead of the developer version.
However it still brings the seg-faults error even with the latest release.
As you said I tried to reduce the set to the minimal one, it has 1600000 reads and you can download the R1 and R2 below:

https://drive.google.com/open?id=1y2vAo4KuI1UiItSS90g2Jvym1yVPpYhY
https://drive.google.com/open?id=1eEknpRBXykhD73Ie3Ir-vCKOnJW0LjpW

Thanks again for your help,

Guillaume

**Comment by alexdobin** [comment]
Hi Guillaume

thanks a lot for the files, I will try to reproduce the problem and fix it.

Cheers
Alex

**Comment by alexdobin** [comment]
Hi Guillaume

I could not reproduce the seg-fault, unfortunately. Which FASTA anf GFF3 did you use for the genome.
I used these ones:
ftp://ftp.ensemblgenomes.org/pub/plants/release-38/fasta/vitis_vinifera/dna/Vitis_vinifera.IGGP_12x.dna.toplevel.fa.gz
ftp://ftp.ensemblgenomes.org/pub/plants/release-38/gff3/vitis_vinifera/Vitis_vinifera.IGGP_12x.38.chr.gff3.gz

Also, did you re-generate genome with the latest STAR release?

Cheers
Alex

**Comment by alexdobin** [comment]
Hi Guillaume

never mind my previous e-mail, I think I found the problem fixed it.
You can *try* it out on GitHub master, I will make a 2.6.0b release tomorrow.

Cheers
Alex

**Comment by alexdobin** [comment]
Hi Guillaume

no, it was not specific to a fastq, but rather an access to an uninitialized variable, with some random initializations leading to the problem.
Thanks a lot for reporting the problem and testing the solution. I will release 2.6.0b with the fix tomorrow.

Cheers
Alex
