### ISSUE TITLE
failed to compile

### ISSUE THREAD

**Issue by kemin711** [alexdobin/STAR#409]
Parameters_openReadsFiles.cpp: In member function ‘void Parameters::openReadsFiles()’:
Parameters_openReadsFiles.cpp:61:98: warning: ignoring return value of ‘int system(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
                 system(("ls -lL " + rfName + " > "+ outFileTmp+"/readFilesIn.info 2>&1").c_str());
                                                                                                  ^
Parameters_openReadsFiles.cpp:33:20: warning: variable ‘imate’ might be clobbered by ‘longjmp’ or ‘vfork’ [-Wclobbered]
          for (uint imate=0;imate<readFilesIn.size();imate++) {//open readIn files

**Comment by alexdobin** [comment]
Hi Kemin,

these are warnings, not errors - if there were no other errors, the compilation should have gone through.

Cheers
Alex

**Comment by carloslizama** [comment]
Hey,

Im trying to index a genome with STAR. The computer as 32GB ram and Im using a linux machine.
All the time when I try to index STAR killed the process when its starting the indexing. 
Not sure if you have any clue or something I can try? 

Command line:
STAR --runThreadN 4 --runMode genomeGenerate --genomeDir /home/carlos/STAR/genomeDir --genomeFastaFiles /home/carlos/STAR/genome/Mus_musculus.GRCm38.dna.primary_assembly.fa --sjdbGTFfile /home/carlos/STAR/Mus_musculus.GRCm38.97.gtf --sjdbOverhang 74

 ..... started STAR run
 ... starting to generate Genome files
 ... starting to sort Suffix Array. This may take a long time...
 ... sorting Suffix Array chunks and saving them to disk...
Killed

Thanks
Carlos

**Comment by alexdobin** [comment]
Hi Carlos

for a quicker response please create a new issue in the future.

This looks like out of memory issues, but 32GB should be enough for this genome.
Are there any processes that use a lot of RAM? What's the output of free.
Also, please send me the Log.out file.

Cheers
Alex

**Comment by carloslizama** [comment]
Hi, 

I switch the genomeDir to a partition folder with 1 TB free, however at the middle of the index fall again. 
And I got a different problem,  I ran STAR again I got this message: (The folder has all the permits), not sure what that means:

genomeGenerate.cpp:209:genomeGenerate: exiting because of *OUTPUT FILE* error: could not create output file home/carlos/STAR/genomeDir/chrName.txt
Solution: check that the path exists and you have write permission for this file

This is the log file.

[Log.txt](https://github.com/alexdobin/STAR/files/3532305/Log.txt)

**Comment by alexdobin** [comment]
Hi Carlos,

I think you are missing the initial slash in
--genomeDir home/carlos/STAR/genomeDir 
it should be 
--genomeDir /home/carlos/STAR/genomeDir 

Cheers
Alex

**Comment by carloslizama** [comment]
Hi Alex,

I fix the / and still same error. 

carlos

**Comment by alexdobin** [comment]
Hi Carlos,
Please send me the Log.out of the new run.
Cheers
Alex

**Comment by carloslizama** [comment]
Sorry I forgot to attached.

**Comment by carloslizama** [comment]
[Log.txt](https://github.com/alexdobin/STAR/files/3536085/Log.txt)

**Comment by alexdobin** [comment]
It seems you still do not have the slash, look for this line in the Log.out file to check for your parameters:
##### Command Line:
STAR --runThreadN 4 --runMode genomeGenerate --genomeDir home/carlos/STAR/genomeDir --genomeFastaFiles /home/carlos/STAR/genome/Mus_musculus.GRCm38.dna.primary_assembly.fa --sjdbGTFfile /home/carlos/STAR/Mus_musculus.GRCm38.97.gtf --sjdbOverhang 100

Also, I would recommend switching to the latest STAR release 2.7.2a

**Comment by carloslizama** [comment]
sorry, this is the log file.

[Log.txt](https://github.com/alexdobin/STAR/files/3536101/Log.txt)

**Comment by alexdobin** [comment]
Did you create this directory:
/home/carlos/STAR/genomeDir 
You need to create it with mkdir before you run STAR.

**Comment by carloslizama** [comment]
ups I delete by mistake the folder. Star now star the indexing however stop: This is the problem  I reach last time.

 STAR --runThreadN 4 --runMode genomeGenerate --genomeDir /media/carlos/DATAPART1/genomeDir  --genomeFastaFiles /home/carlos/STAR/genome/Mus_musculus.GRCm38.dna.primary_assembly.fa  --sjdbGTFfile /home/carlos/STAR/Mus_musculus.GRCm38.97.gtf --sjdbOverhang 100
Aug 23 14:36:23 ..... started STAR run
Aug 23 14:36:23 ... starting to generate Genome files
Aug 23 14:37:14 ... starting to sort Suffix Array. This may take a long time...
Aug 23 14:37:28 ... sorting Suffix Array chunks and saving them to disk...
Aug 23 15:09:07 ... loading chunks from disk, packing SA...
Aug 23 15:14:21 ... finished generating suffix array
Aug 23 15:14:21 ... generating Suffix Array index
Aug 23 15:17:46 ... completed Suffix Array index
Aug 23 15:17:46 ..... processing annotations GTF
Aug 23 15:17:56 ..... inserting junctions into the genome indices
Killed

[Log.txt](https://github.com/alexdobin/STAR/files/3536371/Log.txt)

Thanks

**Comment by alexdobin** [comment]
Hi Carlos

this is likely to be out of memory problem, how much RAM do you have?
32GB should be enough for thsi genome.
Please check that other programs do not take too much RAM.

Cheers
Alex
