### ISSUE TITLE
FATAL ERROR. Check that you have enough space on the disk

### ISSUE THREAD

**Issue by arvchi** [alexdobin/STAR#410]
Trying to generate a genome index with STAR 2.5.3a on our computer cloud, but I get the following error:

```
genomeGenerate.cpp:298:genomeGenerate: exiting because of *OUTPUT FILE* error: could not write the output file */genomeDir/SA_13
fail()=1 ; bad()=1
Error while trying to write chunk # 0; 0 bytes
File size full = 938681352 bytes
File size on disk = 33558528 bytes
Solution: check that you have enough space on the disk
Empty space on disk = 3688629683216384 bytes

Apr 26 10:07:20 ...... FATAL ERROR, exiting
```
At this point, many of the files have already been written to genomeDir, but it stops here for a strange reason. Empty space on disk seems to be enough.

Any suggestions?

**Comment by alexdobin** [comment]
Hi @arvchi 

I would guess this is some kind of limitation for the total size of files written.
If you run it again, is the error message the same?
What is the output of ls -lh on the genomeDir directory after the run fails?

Cheers
Alex

**Comment by arvchi** [comment]
Hi, thanks for the quick reply. It was a problem on the server side with disk size allocations. Solved now, nothing wrong with STAR.
