### ISSUE TITLE
'Unterminated quoted string' error on make

### ISSUE THREAD

**Issue by idanbudin** [alexdobin/STAR#411]
I am trying to- make STAR, using gcc v 5.4.0 on ubuntu 16.04.
But I am getting the result in the attached "output" file (Makefile is also attached).
Any idea what can I do?
[output.txt](https://github.com/alexdobin/STAR/files/1958848/output.txt)
[Makefile.txt](https://github.com/alexdobin/STAR/files/1958850/Makefile.txt)

**Comment by alexdobin** [comment]
Hi @idanbudin 

I think this is the problem with "locale" date.
You should be able to circumvent it with
$ make COMPTIMEPLACE=-D'COMPILATION_TIME_PLACE=May4'

Cheers
Alex

**Comment by idanbudin** [comment]
I have finally found out that there is a recompiled binary file that I can use, so this Issue is irrelevant for me.
@alexdobin thanks for the help though!
