### ISSUE TITLE
Inserting junctions into genome indices - Taking a very long time

### ISSUE THREAD

**Issue by hlhorsnell** [alexdobin/STAR#412]
Hi All,

Harry again, I am working on a Mac with 8GB RAM and over 100GB of space on hard drive.

The computer handle the Mouse indexing perfectly fine until the inserting junctions into the genome indices, the CPU goes really low and after 7hrs had still not finished

The command line I used is below, and here is my log out file

[LogoutHH.txt](https://github.com/alexdobin/STAR/files/1959987/LogoutHH.txt)

./STAR --runThreadN 1 --runMode genomeGenerate --genomeSAindexNbases 12 --genomeDir /Users/harryhorsnell/Desktop/genomeDir --genomeFastaFiles Mus_musculus.GRCm38.dna.primary_assembly.fa --sjdbGTFfile Mus_musculus.GRCm38.92.gtf --genomeSAsparseD 2 --limitGenomeGenerateRAM 72152541226

Any suggestions,
Many Thanks,
Harry.

**Comment by alexdobin** [comment]
Hi Harry,

8GB will be a tight fit for a mouse genome. Please try --genomeSAsparseD 4 --limitSjdbInsertNsj 300000 --genomeSAindexNbases 10

Cheers
Alex

**Comment by yukongoldpotato96** [comment]
I think I should leave a reference for how long STAR can run on a 4 core, 16 RAM iMac computer:
It will take a little less than a hundred hours, like around ~98. So it will be perfect if you run this on a long weekend.
./STAR --runThreadN 4 --runMode genomeGenerate --genomeDir /Users/awlab/Downloads/genome --genomeFastaFiles GRCh38.primary_assembly.genome.fa --sjdbGTFfile gencode.v30.primary_assembly.annotation.gtf --sjdbOverhang 150
Jun 06 10:18:48 ..... started STAR run
Jun 06 10:18:48 ... starting to generate Genome files
Jun 06 10:20:03 ... starting to sort Suffix Array. This may take a long time...
Jun 06 10:20:16 ... sorting Suffix Array chunks and saving them to disk...
Jun 06 12:02:09 ... loading chunks from disk, packing SA...
Jun 06 12:19:58 ... finished generating suffix array
Jun 06 12:19:58 ... generating Suffix Array index
Jun 06 12:27:49 ... completed Suffix Array index
Jun 06 12:27:49 ..... processing annotations GTF
Jun 06 12:28:20 ..... inserting junctions into the genome indices
Jun 10 11:57:49 ... writing Genome to disk ...
Jun 10 11:58:58 ... writing Suffix Array to disk ...
Jun 10 12:15:13 ... writing SAindex to disk
Jun 10 12:19:43 ..... finished successfully

**Comment by alexdobin** [comment]
Hi YukKei,

I think your machine is running out of RAM and slows down because of swapping.
With 16GB of RAM, you would need to use --genomeSAsparseD 2 (or even 3) and --genomeSAindexNbases 12 .

Cheers
Alex

**Comment by yukongoldpotato96** [comment]
Thanks for the information, Alex!

Best wishes,
YukKei
