### ISSUE TITLE
How to install STAR Program in the PATH setting????

### ISSUE THREAD

**Issue by jlee110** [alexdobin/STAR#414]
Hi

I'm trying to use STAR-Fusion, and I can't seem to get started because of this error:

Error, cannot locate STAR program in the PATH setting at STAR-Fusion-v1.3.2/STAR-Fusion line 344.

I have so far tried:

cp star /usr/bin
cp star /bin
cp star /usr/local/bin

Thanks,
J

**Comment by alexdobin** [comment]
Hi J,

you would need to add path to STAR executable to the PATH variable, e.g.
$ export PATH=$PATH:/path/to/STAR

Cheers
Alex

**Comment by Biojenifer** [comment]
Hi! 

I've just done this but I am still getting the same error:

This is part of my PATH: `/mnt/netapp2/mygroup/programs/STAR/bin/Linux_x86_64/STAR`

And I am still getting the error: 
Error, cannot locate STAR program in the PATH setting at `/mnt/netapp2/mygroup/programs/STAR-Fusion/STAR-Fusion line 374.`

How can I solve this?

**Comment by alexdobin** [comment]
Hi @Biojenifer 

you would need to have just ```/mnt/netapp2/mygroup/programs/STAR/bin/Linux_x86_64/``` in you PATH variable (i.e. without STAR at the end).

Cheers
Alex
