### ISSUE TITLE
Documentation issue / bug with SAM input

### ISSUE THREAD

**Issue by jhart99** [alexdobin/STAR#416]
"--readFilesType SAM PE" gives unexpected results.  If used with a previously aligned bam file and samtools view, the majority of reads will fail to align as "Alignment too short".  

I think this is a documentation issue and the manual should be updated to reflect that the input file needs to be sorted by read name or unsorted as long as the pairs come out sequentially from samtools view.  If the same alignment is first converted back to FASTQ and aligned there is no problem.

**Comment by alexdobin** [comment]
Hi Jonathan,

you are right, I need to explain this options better - actually, it's designed for unmapped BAMs (uBAMs) and require (i) read mates to be together (not necessarily sorted by name) (ii) exactly one/two lines per SE/PE read, i.e. no multimappers or supplementary alignments, (iii) no SAM tags same as those added by STAR, as all SAM tags are transferred from the uBAM to the Aligned.out.BAM.

Cheers
Alex

**Comment by jhart99** [comment]
Thanks for the reply.  I was able to get this working with your hints with a small script to wrap around samtools view to strip out the mapping information, secondary alignments, tags, etc.  Thank you for the push in the right direction.  The script is at github.com/jhart99/bam2fastq called bam2sam.py should anyone find it useful to remap mapped BAM files.
