### ISSUE TITLE
SAM validation error: ERROR: Record Mate Alignment start must be <= reference sequence

### ISSUE THREAD

**Issue by asmariyaz23** [alexdobin/STAR#417]
I am running a STAR aligned BAM file through picard tools and getting the following error:

Exception in thread "main" htsjdk.samtools.SAMFormatException: SAM validation error: ERROR: Record 2242813, Read name NB501657:158:HLVY5BGX5:1:11101:10516:1662, Mate Alignment start (1797712351) must be <= reference sequence length (81195210) on reference chr17
at htsjdk.samtools.SAMUtils.processValidationErrors(SAMUtils.java:452)
at htsjdk.samtools.BAMFileReader$BAMFileIterator.advance(BAMFileReader.java:643)
at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:628)
at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:598)
at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:514)
at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:488)
at picard.sam.AddOrReplaceReadGroups.doWork(AddOrReplaceReadGroups.java:107)
at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:185)
at picard.cmdline.CommandLineProgram.instanceMainWithExit(CommandLineProgram.java:125)
at picard.sam.AddOrReplaceReadGroups.main(AddOrReplaceReadGroups.java:74)

The same sample when aligned with Tophat and run through these tools don't generate this error. Could you help explain why this maybe happening?

**Comment by alexdobin** [comment]
Hi @asmariyaz23 

please extract this read from the SAM file and send it to me, e.g.
$ grep ^NB501657:158:HLVY5BGX5:1:11101:10516:1662 Aligned.out.sam
and also the Log.out file.

Thanks
Alex

**Comment by asmariyaz23** [comment]
NB501164:653:HMT3NBGX5:1:11101:25008:3794	89	chrX	48159203	255	50M	*	0	0	GCCCAAGCCCAAGACTCTGCATGAACTGCTGGAGCGCATTGGCCTAGAGG	<E/AE/E/EEEEE/EEEEEEEEAEEEEE/EEEEAEEAAEEEEEEEAAAAA	NH:i:1	HI:i:1	AS:i:49	nM:i:0
NB501164:653:HMT3NBGX5:1:11101:25008:3794	165	*	0	0	*	chrX	1866389987	0	GACTTCACTCCCACCCCTTATGACA	AAAAA/AE/<E/A//A//AEAEEE/	NH:i:0	HI:i:0	AS:i:49	nM:i:0	uT:A:4
[Log.out.txt](https://github.com/alexdobin/STAR/files/1992435/Log.out.txt)

**Comment by alexdobin** [comment]
Hi @asmariyaz23 

the Log.out does not seem to agree with the alignments - the problematic alignment is unmapped, so the STAR command must have contained --outSAMunmapped Within , which is not what's recorded in the Log.out.
Also, please try to run it with the latest STAR patch 2.6.0c just for this one read.

Cheers
Alex

**Comment by asmariyaz23** [comment]
Hi @alexdobin 

Switching to newer version solved it!

Thank you!
Asma

**Comment by abeyeu** [comment]
I get the  same problem when I use latest STAR_2.6.0c and then  picard tools:

htsjdk.samtools.SAMFormatException: Error parsing text SAM file. Mate Alignment start (262143) must be <= reference sequence length (2608) on reference 3264_0|path0; File Dahua-4Aligned.out.cleaned.sam; Line 8141465
Line: ST-E00523:243:HCM3CCCXY:4:1201:13321:52766	163	3264_0|path0	2064	255	115M35S	=	262143	260167	CTGGTTCTCATAGGTCAGTCAAGGATAGATCCAAGTTTAATGGACGGGGGAGCTCAAATCCTACAAAATCTGTTGCACAGCCCGTTGATCTCTAGTTTGAAGAATCCCATCAATGGTAACCTATTATCCAGGTCTCAATCCACTTAAAAG	AAFFFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFJJJJJJJJJJJJJJJJJJJJJJJJJFJJJJJJJJJJJFJAJ<FF	NH:i:1	HI:i:1	nM:i:0	AS:i:199.

The read within the sam file:
ST-E00523:243:HCM3CCCXY:4:1201:13321:52766	163	3264_0|path0	2064	255	115M35S	=	262143	260167	CTGGTTCTCATAGGTCAGTCAAGGATAGATCCAAGTTTAATGGACGGGGGAGCTCAAATCCTACAAAATCTGTTGCACAGCCCGTTGATCTCTAGTTTGAAGAATCCCATCAATGGTAACCTATTATCCAGGTCTCAATCCACTTAAAAG	AAFFFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFJJJJJJJJJJJJJJJJJJJJJJJJJFJJJJJJJJJJJFJAJ<FF	NH:i:1	HI:i:1	nM:i:0	AS:i:199
ST-E00523:243:HCM3CCCXY:4:1201:13321:52766	83	3264_0|path0	262143	255	150S	=	2064	-260167	ATCAATGGTAACCTATTATCCAGGTCTCAATCCACTTAAAAGTGAATGTACATATTGAATTACAGTGTGAGGAGATGCACTCAATGATGCCATTTATTTCCTGCCAGCTGTGGTCACAATGGTAAAGTTAAGGAGATTGGCTTGGGGCCG	JJJJJJJJJJJJJJJJJFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFFFAA	NH:i:1	HI:i:1	nM:i:0	AS:i:199

Why this happed?

**Comment by alexdobin** [comment]
Hi @abeyeu 

please start a new issue for a prompt reply.
Please send me the Log.out file as well as the sequence of the "3264_0|path0" reference (or the whole genome sequence if you can).

Cheers
Alex

**Comment by seb-mueller** [comment]
Just adding information to this issue. I'm coming across it with a newer STAR version as well (2.7.3a)

```
Exception in thread "main" htsjdk.samtools.SAMFormatException: SAM validation error: ERROR: Record 50174348, Read name SL-NXA:HHV5JBGXF200419:HHV5JBGXF:4:13512:7463:19126, Alignment start (262143) must be <= reference sequence length (6957) on reference KZ773392
```

```
SL-NXA:HHV5JBGXF200419:HHV5JBGXF:4:13512:7463:19126     16      KZ773392        262143  1       3S14M   *       0       0       CATAACCCCCTTGGCTC       /AEEAAEA/EEEAA/6A       NH:i:3  HI:i:1  AS:i:13 nM:i:0
```
Funny enough, the `Alignment start` seems the same (**262143**) as reported by abeyeu despite a different genome and dataset, hard to believe this is coincidence, that's why I put that info here since it might help debugging. Having manually filtered this read fixed it for me, so no action required as for me, just wanted to leave this here as an information.

**Comment by alexdobin** [comment]
Hi @seb-mueller 

could you please send me the link to genome fasta/gtf that you are using here?
Also, what were your parameters for genome generation and mapping?

Thanks!
Alex

**Comment by ZhenyuZ** [comment]
We (GDC) saw something similar in one sample for a short decoy contig. It's complaining about the same start (262143)

**Comment by alexdobin** [comment]
Hi Zhenyu,

could you please send me the FASTA and GTF for the genome, and the erroneous SAM line(s)?
