### ISSUE TITLE
make STAR failed under CentOS 6.9 GCC 5.5

### ISSUE THREAD

**Issue by DuskLi** [alexdobin/STAR#419]
Hi,

I am install gcc 5.5 from source code .
I have make STAR with the following command in the sourdce folder:
**make STAR CXX=/opt/gcc-5.5.0/bin/gcc**

However, I get the following error message:
/opt/gcc-5.5.0/bin/gcc -c  -O3 -pipe -Wall -Wextra  bam_cat.c
bam_cat.c:57:19: fatal error: cstring: No such file or directory
compilation terminated.
make: *** [bam_cat.o] Error 1

Can you please help me troubleshoot?

Thanks,
DuskLi

**Comment by alexdobin** [comment]
Hi @DuskLi 

this is a problem with missing C libraries.
Have you tried the precompiled executables from the bin/ directory in the STAR distribution?

Cheers
Alex
