### ISSUE TITLE
Creating STAR index for PacBio Long reads

### ISSUE THREAD

**Issue by sagnikbanerjee15** [alexdobin/STAR#420]
Hello,

I am trying to create a STAR index using long reads derived from PacBio sequencing. I tried to run STAR in genomeGenerate mode but it keeps on failing. Do I need to tweak parameters? I have roughly 9.6M long reads.

Thank you.

**Comment by alexdobin** [comment]
Hi Sagnik,

if you have 9.6M "scaffolds", you would have to reduce --genomeChrBinNbits to log2(AverageScaffoldSize) to reduce RAM overhead.
However, I would recommend merging the read sequences into one super-contig.

Cheers
Alex

**Comment by sagnikbanerjee15** [comment]
All right Thanks. I will try that.
