### ISSUE TITLE
Fatal INPUT FILE error, no valid exon lines in the GTF file

### ISSUE THREAD

**Issue by sengoku93** [alexdobin/STAR#421]
Hi,

I am currently trying to generate a star genome index using the command below ( files were downloaded from gencode):

STAR --runMode genomeGenerate --runThreadN 28 --genomeDir /genomedirectory --genomeFastaFiles directory/gencode.v18.pc_transcripts.fa --sjdbGTFfile directory/gencode.v18.annotation.gtf  --sjdbOverhang 100 --limitGenomeGenerateRAM=66479046016

However I get the error below:

Fatal INPUT FILE error, no valid exon lines in the GTF file: directory/gencode.v18.annotation.gtf
Solution: check the formatting of the GTF file. Most likely cause is the difference in chromosome naming between GTF and FASTA file.

Even though I am downloading both fasta and gtf from Gencode, would there still be difference in chromosome naming. If so, how to you go about about changing names to be identical? Thank you!

Best,
Kristofer

**Comment by sengoku93** [comment]
Please let me know if you would like log.out file

**Comment by alexdobin** [comment]
Hi @sengoku93 

You are using the transcriptome FASTA but genome GTF.
do you want to map to the transcriptome (transcript sequences) or to the genome (chromosome sequences)? If the former, you do not need annotations GTF at all. If the latter, you would need to use genome FASTA ([ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_28/GRCh37_mapping/GRCh37.primary_assembly.genome.fa.gz](url)) and genome GTF which you already have.

Also, I would recommend using one of the latest versions of the GENCODE.

Cheers
Alex

**Comment by ARise-fox** [comment]
> 

Hi, I'm using the transcriptome fasta, and I want to map to the transcriptome (transcript sequences), If I dont need the annotations GTF, How would I deal with the error message:

> EXITING because of FATAL INPUT PARAMETER ERROR: when generating genome without annotations (--sjdbFileChrStartEnd or --sjdbGTFfile options)
> do not specify >0 --sjdbOverhang
> SOLUTION: re-run genome generation without --sjdbOverhang option

The input was:
STAR \
>   --runMode genomeGenerate \
>   --runThreadN 4 \
>   --genomeDir ~/BioAnalysis/STAR/Alb/Alb_index_2 \
>   --genomeFastaFiles ~/BioAnalysis/STAR/Alb/NM_009654_4_203-310.fa \
>   --sjdbOverhang 149 \
>   --limitGenomeGenerateRAM 15000000000 --genomeSAsparseD 2 --genomeSAindexNbases 8

**Comment by alexdobin** [comment]
Hi @ARise-fox 

if not using annotations, please do not specify ```--sjdbOverhang```.
