### ISSUE TITLE
How to assign the reads to two very similar gene sequences

### ISSUE THREAD

**Issue by cxde515** [alexdobin/STAR#425]
Hey people,

I have a question about the alignment. When I analyze the RNAseq data from mouse, I found there is a huge difference on specific Gene-a between WT and KO. Actually Gene-a is a pseudo gene and has a parent functional gene as Gene-A. I checked the sequences between Gene-a and Gene-A. To my surprise, they are almost the same only except for 3' UTR region. So I want to ask why the reads assigned to Gene-a not its parent Gene-A? (Gene-a is on chromosome X and Gene-A is on chromosome 15)
Thanks!

**Comment by alexdobin** [comment]
Hi @cxde515 

if a read maps to two or more loci with exactly the same sequence, it's reported as a multimapper. It is impossible to tell which locus the read came from by looking at just this one read. However, in some cases it is possible to "rescue" the multimappers using other reads that map uniquely close to only one of the loci. This is what gene/transcript quantification software such as RSEM do.

Cheers
Alex

**Comment by cxde515** [comment]
Hi Alex,

Many thanks for your response! So you mean this reads will be assigned
twice, if two genes have the exact sequence this reads perfectly matched
with? Then this assign is equal for both genes? is there any bias for this
situation?

Best,

Xi
