### ISSUE TITLE
Does the GTF need to be sorted when preparing the genome?

### ISSUE THREAD

**Issue by mebbert** [alexdobin/STAR#426]
Hi,

I imagine the manual would explicitly state this if it were necessary, but does the `GTF` file provided to `STAR` when preparing the genome (`--sjdbGTFfile`) need to be sorted according to the reference genome being used? 

`GTF` files seem to be poorly standardized, generally, but I was particularly surprised to find that the `hg38` reference genome provided by Ensembl and the corresponding `GTF` file are *not* sorted the same. The Ensemble `hg38` reference is sorted unix style (i.e., 1, 10, 11, ...) whereas the corresponding `GTF` file seems to be sorted naturally (i.e., 1, 2, 3, ...), at least in part. I did not verify the exact order for the `GTF`, but I do know it's not the same.

Really appreciate it.

**Comment by alexdobin** [comment]
Hi Mark,

GTF file does not need to be sorted in any way for STAR. STAR will import it and do all the necessary sorting internally.

Cheers
Alex

**Comment by mebbert** [comment]
Wonderful, thanks Alex.

**Comment by mebbert** [comment]
May also be worth mentioning that I contacted Ensembl about the discrepancy. They plan to address how the GTF is sorted going forward. The version I am currently using is 92, so it may be "fixed" in version 93.
