### ISSUE TITLE
Not all reads in fasta file are being mapped

### ISSUE THREAD

**Issue by sagnikbanerjee15** [alexdobin/STAR#428]
Hello Alex,

I have a fasta file with 3 long sequences. I am using STARlong to map those to the genome. I am executing the following command.

STARlong   --runThreadN 20   --genomeDir /work/LAS/rpwise-lab/sagnik/data/maize/genome/star_index_without_transcriptome   --readFilesIn Trinity-GG.fasta      --outSAMunmapped Within      --outFilterMismatchNmax 100   --seedSearchStartLmax 20   --seedPerReadNmax 100000   --seedPerWindowNmax 1000   --alignTranscriptsPerReadNmax 100000   --alignTranscriptsPerWindowNmax 10000
@CO     user command line: STARlong --outFilterMismatchNmax 100 --seedSearchStartLmax 20 --seedPerReadNmax 100000 --seedPerWindowNmax 1000 --alignTranscriptsPerReadNmax 100000 --alignTranscriptsPerWindowNmax 10000 --runThreadN 20 --genomeDir /work/LAS/rpwise-lab/sagnik/data/maize/genome/star_index_without_transcriptome --readFilesIn Trinity-GG.fasta --outSAMunmapped Within

Due to some reason the last sequence is not getting mapped. I have checked the output sam file. The sequence is not unmapped. I have the same problem with another file which has 2 sequences and the last sequence is not mapped.

Thank you.

**Comment by sagnikbanerjee15** [comment]
Hello Alex,

I think I figured out the problem. The fasta file I was providing was multi-line. Once I changed it to single line it worked without a glitch. 

Thank you.

**Comment by alexdobin** [comment]
Hi Sagnik,

it's supposed to work with multi-line FASTA - I will check it out.

Thanks!
Alex

**Comment by bumproo** [comment]
Hi Alex,

I'm running in to the same trouble that Sagnik wrote about. I've found the same behavior with 2.5.3a and 2.7.1a. I'm hoping to use star in place of blat. I have a test fasta file with 28 fasta sequences that range in length from 138-1584 nts

the command im using to map is hopefully similar to the blat-equivalence section of the star paper:

STAR --runMode alignReads --runThreadN 1 --outFilterMismatchNmax 100 \
--seedSearchLmax 30 --seedSearchStartLmax 30 \
--seedPerReadNmax 100000 --seedPerWindowNmax 100 --alignTranscriptsPerReadNmax 100000 \
--alignTranscriptsPerWindowNmax 10000 \
--genomeDir tcr_regions --outSAMtype BAM SortedByCoordinate \
--readFilesIn test2.fasta --outFileNamePrefix test2

the Log.final.out file reports 5 input reads for the run on the full 28 sequence query file. If I delete the first 5 sequences and re-run, Log.final.out reports 1 query sequence. Iterations of deleting the sequence that aligns and re-running will sometimes result in one being aligned, sometimes 2.

I see the same behavior when aligning to the full human genome or a small relevant subsection of the genome.

I also see similar results with fasta file of a few sequences obtained from the UCSC genome browser so the behavior is not caused by my fasta query file.

I also tested the multi- vs single- line fasta query mentioned by Sagnik but see the same behavior for each version.

My star 2.5.3a installation works perfectly for single and paired fastq files

Any ideas you have would be really welcome, thank you!

Charlie

**Comment by alexdobin** [comment]
Hi Charlie,

are you using the STARlong executables? It is required for long reads.

Cheers
Alex

**Comment by bumproo** [comment]
Hi Alex,

Thank you for writing back.

No on STARlong, I did not know about that…

I just tested it running with STARlong instead of STAR and all 28 seqs in the test set mapped, im sorry for the distraction!
‘
Thanks you very much both for this and the excellent software

Charlie

On Jun 21, 2019, at 11:49 AM, Alexander Dobin <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Charlie,

are you using the STARlong executables? It is required for long reads.

Cheers
Alex

**Comment by RussBainer** [comment]
Hi Alex, Love your tool. I am encountering a similar problem to the one described above, where the majority of the reads in my FASTA are not detected. 

My Fasta has about 800K reads: 

```
# grep '>' /data/fasta/collapsed_isoforms-7.fasta | wc 
828817  828817 58685441
```

And when I align it `STARlong` runs to completion: 

```
STARlong --outFilterMismatchNmax 100 --seedSearchStartLmax 20 --seedPerReadNmax 100000 --seedPerWindowNmax 1000 --alignTranscriptsPerReadNmax 100000 --alignTranscriptsPerWindowNmax 10000 --runThreadN 20 --genomeDir /data/reference/ --outSAMtype BAM SortedByCoordinate --readFilesIn /data/fasta/collapsed_isoforms-7.fasta
        /opt/conda/bin/STARlong-avx2 --outFilterMismatchNmax 100 --seedSearchStartLmax 20 --seedPerReadNmax 100000 --seedPerWindowNmax 1000 --alignTranscriptsPerReadNmax 100000 --alignTranscriptsPerWindowNmax 10000 --runThreadN 20--genomeDir /data/reference/ --outSAMtype BAM SortedByCoordinate --readFilesIn /data/fasta/collapsed_isoforms-7.fasta
        STAR version: 2.7.11a   compiled: 2023-09-15T02:58:53+0000 :/opt/conda/conda-bld/star_1694746407721/work/source
Feb 21 00:31:49 ..... started STAR run
Feb 21 00:31:49 ..... loading genome
Feb 21 00:32:06 ..... started mapping
Feb 21 00:32:19 ..... finished mapping
Feb 21 00:32:20 ..... started sorting BAM
Feb 21 00:32:20 ..... finished successfully
``` 
But then: 

```

                               Started job on |       Feb 21 00:31:49
                             Started mapping on |       Feb 21 00:32:06
                                    Finished on |       Feb 21 00:32:20
       Mapping speed, Million of reads per hour |       0.02

                          Number of input reads |       60
                      Average input read length |       649
                                    UNIQUE READS:
                   Uniquely mapped reads number |       58
                        Uniquely mapped reads % |       96.67%
                          Average mapped length |       647.97
                       Number of splices: Total |       83
            Number of splices: Annotated (sjdb) |       80
                       Number of splices: GT/AG |       82
                       Number of splices: GC/AG |       1
                       Number of splices: AT/AC |       0
               Number of splices: Non-canonical |       0
                      Mismatch rate per base, % |       0.09%
                         Deletion rate per base |       0.03%
                        Deletion average length |       1.20
                        Insertion rate per base |       0.05%
                       Insertion average length |       3.33
                             MULTI-MAPPING READS:
        Number of reads mapped to multiple loci |       2
             % of reads mapped to multiple loci |       3.33%
        Number of reads mapped to too many loci |       0
             % of reads mapped to too many loci |       0.00%
                                  UNMAPPED READS:
  Number of reads unmapped: too many mismatches |       0
       % of reads unmapped: too many mismatches |       0.00%
            Number of reads unmapped: too short |       0
                 % of reads unmapped: too short |       0.00%
                Number of reads unmapped: other |       0
                     % of reads unmapped: other |       0.00%
                                  CHIMERIC READS:
                       Number of chimeric reads |       0
                            % of chimeric reads |       0.00%
                            
```

Only the first 6 reads seem to be detected in the Fasta file. There is nothing obviously wrong with sequences 59-62 when I inspect them. 

Any thoughts? The sequences are provided as a multi-line fasta.

**Comment by alexdobin** [comment]
Hi @RussBainer,

Please check if it works if you convert multi-line fasta to single-line.

**Comment by rhiannon-schembri** [comment]
Hi Alex,

Sorry to bother, but I am having the same issue described here.

I have a fasta file with 49 longish (anywhere from 200-7000bp) sequences in it. They are de novo assembled transcripts generated with Trinity, which I am now trying to map to a reference genome to check against the annotated gene models of a couple of genes. They are not paired sequences. The headers look like this:

`>TRINITY_DN24_c0_g1_i1 len=550 path=[0:0-549]`

This is the code I've run:

`STARlong --genomeDir /g/data/fu80/scratchfiles/rnaseq/reference_zbf_star/ --readFilesIn reads.fa --outSAMtype BAM SortedByCoordinate --outFilterMismatchNmax 100 --seedSearchStartLmax 20 --seedPerReadNmax 100000 --seedPerWindowNmax 1000 --alignTranscriptsPerReadNmax 100000 --alignTranscriptsPerWindowNmax 10000`

STAR appears to run fine to completion:
` ~/miniconda3/envs/transcriptomics/bin/STARlong-avx2 --genomeDir /g/data/fu80/scratchfiles/rnaseq/reference_zbf_star/ --readFilesIn reads.fa --outSAMtype BAM SortedByCoordinate --outFilterMismatchNmax 100 --seedSearchStartLmax 20 --seedPerReadNmax 100000 --seedPerWindowNmax 1000 --alignTranscriptsPerReadNmax 100000 --alignTranscriptsPerWindowNmax 10000
        STAR version: 2.7.11a   compiled: 2023-09-15T02:58:53+0000 :/opt/conda/conda-bld/star_1694746407721/work/source
Oct 23 06:52:40 ..... started STAR run
Oct 23 06:52:40 ..... loading genome
Oct 23 06:53:21 ..... started mapping
Oct 23 06:53:22 ..... finished mapping
Oct 23 06:53:23 ..... started sorting BAM
Oct 23 06:53:23 ..... finished successfully`

But it only reads in 3 out of the 49 sequences.

` Started job on |       Oct 23 07:11:53
                             Started mapping on |       Oct 23 07:12:04
                                    Finished on |       Oct 23 07:12:05
       Mapping speed, Million of reads per hour |       0.01

                          Number of input reads |       3
                      Average input read length |       581
                                    UNIQUE READS:
                   Uniquely mapped reads number |       2
                        Uniquely mapped reads % |       66.67%
                          Average mapped length |       541.50
                       Number of splices: Total |       1
            Number of splices: Annotated (sjdb) |       0
                       Number of splices: GT/AG |       1
                       Number of splices: GC/AG |       0
                       Number of splices: AT/AC |       0
               Number of splices: Non-canonical |       0
                      Mismatch rate per base, % |       0.83%
                         Deletion rate per base |       0.00%
                        Deletion average length |       0.00
                        Insertion rate per base |       0.00%
                       Insertion average length |       0.00
                             MULTI-MAPPING READS:
        Number of reads mapped to multiple loci |       1
             % of reads mapped to multiple loci |       33.33%
        Number of reads mapped to too many loci |       0
             % of reads mapped to too many loci |       0.00%
                                  UNMAPPED READS:
  Number of reads unmapped: too many mismatches |       0
       % of reads unmapped: too many mismatches |       0.00%
            Number of reads unmapped: too short |       0
                 % of reads unmapped: too short |       0.00%
                Number of reads unmapped: other |       0
                     % of reads unmapped: other |       0.00%
                                  CHIMERIC READS:
                       Number of chimeric reads |       0
                            % of chimeric reads |       0.00%`

Initially I was using the fasta file as it was generated out of Trinity, i.e., a multi-line fasta, but after reading the above I converted it to a single-line fasta. This made no difference. I have tried using STAR and STARlong, with and without the additional parameters after --outSAMtype listed above. I've also tried deleting the bits of the headers after and including " len=[...]", in case that was somehow the issue.

I've tried it with STAR version 2.7.11a as above and 2.7.11b, both installed through conda. I also tried running it in a terminal session and through the PBS scheduler on the HPC, in case memory or processing power was somehow the issue. In all cases the result was the same, with just the first three sequences being mapped.

I also tried deleting the first 3 sequences, in case something in them was causing it to abort or stop reading. This resulted in it reading just sequence [4] (i.e., now the first) sequence in the file. I did this a few times, iteratively deleting the first sequence and then running it again, and each time it seemed to just read in the first one.

Do you have any thoughts on what could be the problem?
