### ISSUE TITLE
output log files only option

### ISSUE THREAD

**Issue by magaal** [alexdobin/STAR#43]
Hi - for performance reasons I am running STAR from a specific disk with the output going to that disk as well (which by default per the manual would be the directory the program was launched, the CWD) - is it possible to redirect the output of the log files only to a central location? this would help out immensely in a clustered configuration. Apologies if there is an easy answer to this - maybe a symlink...

**Comment by alexdobin** [comment]
Hi Mike,

there is no STAR option to do it, but symlinking the STAR log files from a central location to the STAR run directory should work.

Cheers
Alex
