### ISSUE TITLE
STAR fails with Unknown error 521 on NFS while creating fifo pipe for read2

### ISSUE THREAD

**Issue by jenzopr** [alexdobin/STAR#431]
Hi Alex,

I'm facing a strange issue with STAR (v2.6.0c) on an NFS share during paired-end mapping.
The call is
``` 
STAR --genomeDir /mnt/flatfiles/organisms/mouse/mm10_GRCm38/indices/star_GRCm38.p5_gencode.vM16/ --runThreadN 30 --readFilesIn trimmed/sample_R1.fastq.gz trimmed/sample_R2.fastq.gz --readFilesCommand zcat --outStd SAM --outSAMunmapped Within > sample.bam
```
and fails with
```
./_STARtmp//readsCommand_read2: 1: ./_STARtmp//readsCommand_read2: cannot create ./_STARtmp/tmp.fifo.read2: Unknown error 521
```

Strangely, `_STARtmp/tmp.fifo.read2` exists and is usable (I piped some content from a gzip'ed file into it and got it out in another session). Using STAR with unzipped (PE) files as input works as well.
Also, a single-end mapping with just `trimmed/sample_R1.fastq.gz` or `trimmed/sample_R2.fastq.gz` finishes without errors. 

Is there anything special about `_STARtmp/tmp.fifo.read2`?
Best and thank you for a short note how I could proceed to track down the error.
Jens

**Comment by alexdobin** [comment]
Hi Jens,

is this problem reproducible? Please remove _STARtmp and try it again.
Some suggestions about this error is to restart the NFS server.

Cheers
Alex

**Comment by jenzopr** [comment]
Hi Alex,

we spoke to the manufacturer of the software that manages our storage, and it seems that the problem arises from their side. 

Thanks a lot!
Jens
