### ISSUE TITLE
Index for Icalvum gives segmentation fault

### ISSUE THREAD

**Issue by adelomana** [alexdobin/STAR#433]
Hi, 

I'm working with a new organism and I successfully built the index, but it gives me a segmentation fault when STAR starts mapping reads. The reads can be mapped fine using the index of another organism, which makes me think I have a problem with the index. But I haven't seen anything out of normal in the index folder... I also tried an older version of STAR (2.5.4b), same segmentation fault. Any advice?

Attached log file and terminal messages (I use a simple Python scripting to get the files right, dissmiss those prints...).

Thanks so much for in advance for your help!

Adrian.

*Messages
reading sequence instances...
making genome index...

/proj/omics4tb/alomana/software/STAR-2.6.0c/bin/Linux_x86_64/STAR --runMode genomeGenerate --runThreadN 1 --genomeDir /proj/omics4tb/alomana/projects/ENIGMA/data/STARgenomeIndex --genomeFastaFiles /proj/omics4tb/alomana/projects/ENIGMA/data/annotation/genome/icalvum.NC_014830.1.2018.05.22.fasta --sjdbGTFfile /proj/omics4tb/alomana/projects/ENIGMA/data/annotation/genome/icalvum.NC_014830.1.2018.05.22.gff3 --sjdbGTFtagExonParentTranscript Parent --sjdbOverhang 77 --genomeSAindexNbases 10

Jun 10 18:56:02 ..... started STAR run
Jun 10 18:56:02 ... starting to generate Genome files
Jun 10 18:56:02 ... starting to sort Suffix Array. This may take a long time...
Jun 10 18:56:02 ... sorting Suffix Array chunks and saving them to disk...
Jun 10 18:56:06 ... loading chunks from disk, packing SA...
Jun 10 18:56:06 ... finished generating suffix array
Jun 10 18:56:06 ... generating Suffix Array index
Jun 10 18:56:07 ... completed Suffix Array index
Jun 10 18:56:07 ..... processing annotations GTF
Jun 10 18:56:07 ... writing Genome to disk ...
Jun 10 18:56:07 ... writing Suffix Array to disk ...
Jun 10 18:56:07 ... writing SAindex to disk
Jun 10 18:56:07 ..... finished successfully

calling STAR...

time /proj/omics4tb/alomana/software/STAR-2.6.0c/bin/Linux_x86_64/STAR --genomeDir /proj/omics4tb/alomana/projects/ENIGMA/data/STARgenomeIndex --runThreadN 1 --readFilesIn /proj/omics4tb/alomana/projects/ENIGMA/data/cleanFASTQ/00/L1_R1.clean.fastq /proj/omics4tb/alomana/projects/ENIGMA/data/cleanFASTQ/00/L1_R2.clean.fastq --outFileNamePrefix /proj/omics4tb/alomana/projects/ENIGMA/data/bam/00/

Jun 10 18:56:07 ..... started STAR run
Jun 10 18:56:07 ..... loading genome
Jun 10 18:56:07 ..... started mapping
sh: line 1: 27164 Segmentation fault      /proj/omics4tb/alomana/software/STAR-2.6.0c/bin/Linux_x86_64/STAR --genomeDir /proj/omics4tb/alomana/projects/ENIGMA/data/STARgenomeIndex --runThreadN 1 --readFilesIn /proj/omics4tb/alomana/projects/ENIGMA/data/cleanFASTQ/00/L1_R1.clean.fastq /proj/omics4tb/alomana/projects/ENIGMA/data/cleanFASTQ/00/L1_R2.clean.fastq --outFileNamePrefix /proj/omics4tb/alomana/projects/ENIGMA/data/bam/00/

real	0m0.574s
user	0m0.458s
sys	0m0.107s

*Log file
STAR version=STAR_2.6.0c
STAR compilation time,server,dir=Thu May 10 18:41:27 EDT 2018 florence.cshl.edu:/sonas-hs/gingeras/nlsas_norepl/user/dobin/STAR/STAR.master/source
##### DEFAULT parameters:
versionSTAR                       20201
versionGenome                     20101   20200   
parametersFiles                   -   
sysShell                          -
runMode                           alignReads
runThreadN                        1
runDirPerm                        User_RWX
runRNGseed                        777
genomeDir                         ./GenomeDir/
genomeLoad                        NoSharedMemory
genomeFastaFiles                  -   
genomeChainFiles                  -   
genomeSAindexNbases               14
genomeChrBinNbits                 18
genomeSAsparseD                   1
genomeSuffixLengthMax             18446744073709551615
genomeFileSizes                   0   
genomeConsensusFile               -
readFilesType                     Fastx   
readFilesIn                       Read1   Read2   
readFilesPrefix                   -
readFilesCommand                  -   
readMatesLengthsIn                NotEqual
readMapNumber                     18446744073709551615
readNameSeparator                 /   
inputBAMfile                      -
bamRemoveDuplicatesType           -
bamRemoveDuplicatesMate2basesN    0
limitGenomeGenerateRAM            31000000000
limitIObufferSize                 150000000
limitOutSAMoneReadBytes           100000
limitOutSJcollapsed               1000000
limitOutSJoneRead                 1000
limitBAMsortRAM                   0
limitSjdbInsertNsj                1000000
outTmpDir                         -
outTmpKeep                        None
outStd                            Log
outReadsUnmapped                  None
outQSconversionAdd                0
outMultimapperOrder               Old_2.4
outSAMtype                        SAM   
outSAMmode                        Full
outSAMstrandField                 None
outSAMattributes                  Standard   
outSAMunmapped                    None   
outSAMorder                       Paired
outSAMprimaryFlag                 OneBestScore
outSAMreadID                      Standard
outSAMmapqUnique                  255
outSAMflagOR                      0
outSAMflagAND                     65535
outSAMattrRGline                  -   
outSAMheaderHD                    -   
outSAMheaderPG                    -   
outSAMheaderCommentFile           -
outBAMcompression                 1
outBAMsortingThreadN              0
outBAMsortingBinsN                50
outSAMfilter                      None   
outSAMmultNmax                    18446744073709551615
outSAMattrIHstart                 1
outSAMtlen                        1
outSJfilterReads                  All
outSJfilterCountUniqueMin         3   1   1   1   
outSJfilterCountTotalMin          3   1   1   1   
outSJfilterOverhangMin            30   12   12   12   
outSJfilterDistToOtherSJmin       10   0   5   10   
outSJfilterIntronMaxVsReadN       50000   100000   200000   
outWigType                        None   
outWigStrand                      Stranded   
outWigReferencesPrefix            -
outWigNorm                        RPM   
outFilterType                     Normal
outFilterMultimapNmax             10
outFilterMultimapScoreRange       1
outFilterScoreMin                 0
outFilterScoreMinOverLread        0.66
outFilterMatchNmin                0
outFilterMatchNminOverLread       0.66
outFilterMismatchNmax             10
outFilterMismatchNoverLmax        0.3
outFilterMismatchNoverReadLmax    1
outFilterIntronMotifs             None
outFilterIntronStrands            RemoveInconsistentStrands
clip5pNbases                      0   
clip3pNbases                      0   
clip3pAfterAdapterNbases          0   
clip3pAdapterSeq                  -   
clip3pAdapterMMp                  0.1   
winBinNbits                       16
winAnchorDistNbins                9
winFlankNbins                     4
winAnchorMultimapNmax             50
winReadCoverageRelativeMin        0.5
winReadCoverageBasesMin           0
scoreGap                          0
scoreGapNoncan                    -8
scoreGapGCAG                      -4
scoreGapATAC                      -8
scoreStitchSJshift                1
scoreGenomicLengthLog2scale       -0.25
scoreDelBase                      -2
scoreDelOpen                      -2
scoreInsOpen                      -2
scoreInsBase                      -2
seedSearchLmax                    0
seedSearchStartLmax               50
seedSearchStartLmaxOverLread      1
seedPerReadNmax                   1000
seedPerWindowNmax                 50
seedNoneLociPerWindow             10
seedMultimapNmax                  10000
seedSplitMin                      12
alignIntronMin                    21
alignIntronMax                    0
alignMatesGapMax                  0
alignTranscriptsPerReadNmax       10000
alignSJoverhangMin                5
alignSJDBoverhangMin              3
alignSJstitchMismatchNmax         0   -1   0   0   
alignSplicedMateMapLmin           0
alignSplicedMateMapLminOverLmate    0.66
alignWindowsPerReadNmax           10000
alignTranscriptsPerWindowNmax     100
alignEndsType                     Local
alignSoftClipAtReferenceEnds      Yes
alignEndsProtrude                 0   ConcordantPair   
alignInsertionFlush               None
peOverlapNbasesMin                0
peOverlapMMp                      0.1
chimSegmentMin                    0
chimScoreMin                      0
chimScoreDropMax                  20
chimScoreSeparation               10
chimScoreJunctionNonGTAG          -1
chimMainSegmentMultNmax           10
chimJunctionOverhangMin           20
chimOutType                       Junctions   
chimFilter                        banGenomicN   
chimSegmentReadGapMax             0
chimMultimapNmax                  0
chimMultimapScoreRange            1
chimNonchimScoreDropMin           20
sjdbFileChrStartEnd               -   
sjdbGTFfile                       -
sjdbGTFchrPrefix                  -
sjdbGTFfeatureExon                exon
sjdbGTFtagExonParentTranscript    transcript_id
sjdbGTFtagExonParentGene          gene_id
sjdbOverhang                      100
sjdbScore                         2
sjdbInsertSave                    Basic
varVCFfile                        -
waspOutputMode                    None
quantMode                         -   
quantTranscriptomeBAMcompression    1
quantTranscriptomeBan             IndelSoftclipSingleend
twopass1readsN                    18446744073709551615
twopassMode                       None
##### Command Line:
/proj/omics4tb/alomana/software/STAR-2.6.0c/bin/Linux_x86_64/STAR --genomeDir /proj/omics4tb/alomana/projects/ENIGMA/data/STARgenomeIndex --runThreadN 1 --readFilesIn /proj/omics4tb/alomana/projects/ENIGMA/data/cleanFASTQ/00/L1_R1.clean.fastq /proj/omics4tb/alomana/projects/ENIGMA/data/cleanFASTQ/00/L1_R2.clean.fastq --outFileNamePrefix /proj/omics4tb/alomana/projects/ENIGMA/data/bam/00/
##### Initial USER parameters from Command Line:
outFileNamePrefix                 /proj/omics4tb/alomana/projects/ENIGMA/data/bam/00/
###### All USER parameters from Command Line:
genomeDir                     /proj/omics4tb/alomana/projects/ENIGMA/data/STARgenomeIndex     ~RE-DEFINED
runThreadN                    1     ~RE-DEFINED
readFilesIn                   /proj/omics4tb/alomana/projects/ENIGMA/data/cleanFASTQ/00/L1_R1.clean.fastq   /proj/omics4tb/alomana/projects/ENIGMA/data/cleanFASTQ/00/L1_R2.clean.fastq        ~RE-DEFINED
outFileNamePrefix             /proj/omics4tb/alomana/projects/ENIGMA/data/bam/00/     ~RE-DEFINED
##### Final user re-defined parameters-----------------:
runThreadN                        1
genomeDir                         /proj/omics4tb/alomana/projects/ENIGMA/data/STARgenomeIndex
readFilesIn                       /proj/omics4tb/alomana/projects/ENIGMA/data/cleanFASTQ/00/L1_R1.clean.fastq   /proj/omics4tb/alomana/projects/ENIGMA/data/cleanFASTQ/00/L1_R2.clean.fastq   
outFileNamePrefix                 /proj/omics4tb/alomana/projects/ENIGMA/data/bam/00/

-------------------------------
##### Final effective command line:
/proj/omics4tb/alomana/software/STAR-2.6.0c/bin/Linux_x86_64/STAR   --runThreadN 1   --genomeDir /proj/omics4tb/alomana/projects/ENIGMA/data/STARgenomeIndex   --readFilesIn /proj/omics4tb/alomana/projects/ENIGMA/data/cleanFASTQ/00/L1_R1.clean.fastq   /proj/omics4tb/alomana/projects/ENIGMA/data/cleanFASTQ/00/L1_R2.clean.fastq      --outFileNamePrefix /proj/omics4tb/alomana/projects/ENIGMA/data/bam/00/

##### Final parameters after user input--------------------------------:
versionSTAR                       20201
versionGenome                     20101   20200   
parametersFiles                   -   
sysShell                          -
runMode                           alignReads
runThreadN                        1
runDirPerm                        User_RWX
runRNGseed                        777
genomeDir                         /proj/omics4tb/alomana/projects/ENIGMA/data/STARgenomeIndex
genomeLoad                        NoSharedMemory
genomeFastaFiles                  -   
genomeChainFiles                  -   
genomeSAindexNbases               14
genomeChrBinNbits                 18
genomeSAsparseD                   1
genomeSuffixLengthMax             18446744073709551615
genomeFileSizes                   0   
genomeConsensusFile               -
readFilesType                     Fastx   
readFilesIn                       /proj/omics4tb/alomana/projects/ENIGMA/data/cleanFASTQ/00/L1_R1.clean.fastq   /proj/omics4tb/alomana/projects/ENIGMA/data/cleanFASTQ/00/L1_R2.clean.fastq   
readFilesPrefix                   -
readFilesCommand                  -   
readMatesLengthsIn                NotEqual
readMapNumber                     18446744073709551615
readNameSeparator                 /   
inputBAMfile                      -
bamRemoveDuplicatesType           -
bamRemoveDuplicatesMate2basesN    0
limitGenomeGenerateRAM            31000000000
limitIObufferSize                 150000000
limitOutSAMoneReadBytes           100000
limitOutSJcollapsed               1000000
limitOutSJoneRead                 1000
limitBAMsortRAM                   0
limitSjdbInsertNsj                1000000
outFileNamePrefix                 /proj/omics4tb/alomana/projects/ENIGMA/data/bam/00/
outTmpDir                         -
outTmpKeep                        None
outStd                            Log
outReadsUnmapped                  None
outQSconversionAdd                0
outMultimapperOrder               Old_2.4
outSAMtype                        SAM   
outSAMmode                        Full
outSAMstrandField                 None
outSAMattributes                  Standard   
outSAMunmapped                    None   
outSAMorder                       Paired
outSAMprimaryFlag                 OneBestScore
outSAMreadID                      Standard
outSAMmapqUnique                  255
outSAMflagOR                      0
outSAMflagAND                     65535
outSAMattrRGline                  -   
outSAMheaderHD                    -   
outSAMheaderPG                    -   
outSAMheaderCommentFile           -
outBAMcompression                 1
outBAMsortingThreadN              0
outBAMsortingBinsN                50
outSAMfilter                      None   
outSAMmultNmax                    18446744073709551615
outSAMattrIHstart                 1
outSAMtlen                        1
outSJfilterReads                  All
outSJfilterCountUniqueMin         3   1   1   1   
outSJfilterCountTotalMin          3   1   1   1   
outSJfilterOverhangMin            30   12   12   12   
outSJfilterDistToOtherSJmin       10   0   5   10   
outSJfilterIntronMaxVsReadN       50000   100000   200000   
outWigType                        None   
outWigStrand                      Stranded   
outWigReferencesPrefix            -
outWigNorm                        RPM   
outFilterType                     Normal
outFilterMultimapNmax             10
outFilterMultimapScoreRange       1
outFilterScoreMin                 0
outFilterScoreMinOverLread        0.66
outFilterMatchNmin                0
outFilterMatchNminOverLread       0.66
outFilterMismatchNmax             10
outFilterMismatchNoverLmax        0.3
outFilterMismatchNoverReadLmax    1
outFilterIntronMotifs             None
outFilterIntronStrands            RemoveInconsistentStrands
clip5pNbases                      0   
clip3pNbases                      0   
clip3pAfterAdapterNbases          0   
clip3pAdapterSeq                  -   
clip3pAdapterMMp                  0.1   
winBinNbits                       16
winAnchorDistNbins                9
winFlankNbins                     4
winAnchorMultimapNmax             50
winReadCoverageRelativeMin        0.5
winReadCoverageBasesMin           0
scoreGap                          0
scoreGapNoncan                    -8
scoreGapGCAG                      -4
scoreGapATAC                      -8
scoreStitchSJshift                1
scoreGenomicLengthLog2scale       -0.25
scoreDelBase                      -2
scoreDelOpen                      -2
scoreInsOpen                      -2
scoreInsBase                      -2
seedSearchLmax                    0
seedSearchStartLmax               50
seedSearchStartLmaxOverLread      1
seedPerReadNmax                   1000
seedPerWindowNmax                 50
seedNoneLociPerWindow             10
seedMultimapNmax                  10000
seedSplitMin                      12
alignIntronMin                    21
alignIntronMax                    0
alignMatesGapMax                  0
alignTranscriptsPerReadNmax       10000
alignSJoverhangMin                5
alignSJDBoverhangMin              3
alignSJstitchMismatchNmax         0   -1   0   0   
alignSplicedMateMapLmin           0
alignSplicedMateMapLminOverLmate    0.66
alignWindowsPerReadNmax           10000
alignTranscriptsPerWindowNmax     100
alignEndsType                     Local
alignSoftClipAtReferenceEnds      Yes
alignEndsProtrude                 0   ConcordantPair   
alignInsertionFlush               None
peOverlapNbasesMin                0
peOverlapMMp                      0.1
chimSegmentMin                    0
chimScoreMin                      0
chimScoreDropMax                  20
chimScoreSeparation               10
chimScoreJunctionNonGTAG          -1
chimMainSegmentMultNmax           10
chimJunctionOverhangMin           20
chimOutType                       Junctions   
chimFilter                        banGenomicN   
chimSegmentReadGapMax             0
chimMultimapNmax                  0
chimMultimapScoreRange            1
chimNonchimScoreDropMin           20
sjdbFileChrStartEnd               -   
sjdbGTFfile                       -
sjdbGTFchrPrefix                  -
sjdbGTFfeatureExon                exon
sjdbGTFtagExonParentTranscript    transcript_id
sjdbGTFtagExonParentGene          gene_id
sjdbOverhang                      100
sjdbScore                         2
sjdbInsertSave                    Basic
varVCFfile                        -
waspOutputMode                    None
quantMode                         -   
quantTranscriptomeBAMcompression    1
quantTranscriptomeBan             IndelSoftclipSingleend
twopass1readsN                    18446744073709551615
twopassMode                       None
----------------------------------------

Finished loading and checking parameters
Reading genome generation parameters:
### GstrandBit=0
versionGenome                 20201        ~RE-DEFINED
genomeFastaFiles              /proj/omics4tb/alomana/projects/ENIGMA/data/annotation/genome/icalvum.NC_014830.1.2018.05.22.fasta        ~RE-DEFINED
genomeSAindexNbases           10     ~RE-DEFINED
genomeChrBinNbits             18     ~RE-DEFINED
genomeSAsparseD               1     ~RE-DEFINED
sjdbOverhang                  77     ~RE-DEFINED
sjdbFileChrStartEnd           -        ~RE-DEFINED
sjdbGTFfile                   /proj/omics4tb/alomana/projects/ENIGMA/data/annotation/genome/icalvum.NC_014830.1.2018.05.22.gff3     ~RE-DEFINED
sjdbGTFchrPrefix              -     ~RE-DEFINED
sjdbGTFfeatureExon            exon     ~RE-DEFINED
sjdbGTFtagExonParentTranscriptParent     ~RE-DEFINED
sjdbGTFtagExonParentGene      gene_id     ~RE-DEFINED
sjdbInsertSave                Basic     ~RE-DEFINED
genomeFileSizes               4194304   33201155        ~RE-DEFINED
Genome version is compatible with current STAR version
Number of real (reference) chromosomes= 1
1	NC_014830.1	4024382	0
--sjdbOverhang = 77 taken from the generated genome
Started loading the genome: Sun Jun 10 18:56:07 2018

Genome: size given as a parameter = 4194304
SA: size given as a parameter = 33201155
SAindex: size given as a parameter = 1
Read from SAindex: pGe.gSAindexNbases=10  nSAi=1398100
nGenome=4194304;  nSAbyte=33201155
GstrandBit=32   SA number of indices=8048764
Shared memory is not used for genomes. Allocated a private copy of the genome.
Genome file size: 4194304 bytes; state: good=1 eof=0 fail=0 bad=0
Loading Genome ... done! state: good=1 eof=0 fail=0 bad=0; loaded 4194304 bytes
SA file size: 33201155 bytes; state: good=1 eof=0 fail=0 bad=0
Loading SA ... done! state: good=1 eof=0 fail=0 bad=0; loaded 33201155 bytes
Loading SAindex ... done: 6116787 bytes
Finished loading the genome: Sun Jun 10 18:56:07 2018

alignIntronMax=alignMatesGapMax=0, the max intron size will be approximately determined by (2^winBinNbits)*winAnchorDistNbins=589824

**Comment by alexdobin** [comment]
Hi Adrian,

please try to reduce --genomeSAindexNbases 10 to 8 or even 6.
The scaling of this parameter depends on the k-mer composition of the genome, not just the genome length.

Cheers
Alex

**Comment by adelomana** [comment]
Hi Alex, 

oh, it works! Values 7 and 6 work nicely. 

Thanks so much for your response, really helpful. And thanks for developing STAR, it's a great tool I use often.

Cheers, 
Adrian.

**Comment by alexdobin** [comment]
Great, thanks for letting me know!
Cheers
Alex
