### ISSUE TITLE
Generate two types of transcriptome alignments from single run

### ISSUE THREAD

**Issue by sagnikbanerjee15** [alexdobin/STAR#434]
Hello Alex,

I am mapping 21M to a large genome. I am also transferring the mappings to the corresponding transcriptome. I was wondering if I can generate the mappings to the transcriptome by using both the arguments (--quantTranscriptomeBan Singleend and IndelSoftclipSingleend) at the same time in a single run. I want to do quantify using RSEM which is why I need IndelSoftclipSingleend and I am also generating transcript coverage graph for each transcript, for which I think Singleend would be better since it has all the spliced information as well.

Thank you.

**Comment by alexdobin** [comment]
Hi Sagnik,

unfortunately, you cannot do it in one run - you would have to run it twice.
In principle, you can run it with --quantTranscriptomeBan Singleend and then filter out the transcriptome alignments that have indels or soft-clips. However, it's not exactly the same as --quantTranscriptomeBan IndelSoftclipSingleend - with this option STAR tries to extend the soft-clips to the end of the reads while checking that the number of mismatches is <= max allowed.

Cheers
Alex
