### ISSUE TITLE
rna STAR segmentation fault on specific samples

### ISSUE THREAD

**Issue by maanmi** [alexdobin/STAR#435]
Hi Alex, 

I have 5 different bacterial genomes and 3 sets of rna-seq data I want to map to each genome using a local x86_64 Linux machine with 6 CPU cores and 15 GB of memory. I generated the genome index like so:

STAR --runMode genomeGenerate --runThreadN 12 --genomeDir $genome --genomeFastaFiles $genome/*fna --sjdbGTFfile $genome/*gtf --genomeSAindexNbases=10

and performed the mapping like so:

STAR --runThreadN 12 --genomeDir genomes/$genome* --readFilesIn $sample'_R1.fastq' $sample'_R2.fastq' --alignIntronMax 1 --outFileNamePrefix mapping_results/$sample/$sample'_'

This process only worked for 3 out of 5 genomes, for the rest I am getting 'Segmentation fault'. The mapping logfile (attached) shows that the genome loads fine, but something goes wrong when creating the threads. I have no idea what could be different with those two sets, as their genome sizes are similar to the ones mapped successfully, as well as the amount of reads I am trying to map. 
I should note that mapping with toy input files with 16000 lines, it worked fine.

Any ideas would be much appreciated.

**Comment by alexdobin** [comment]
Hi @maanmi 

I think the problem might be that you have the "=" sign in --genomeSAindexNbases=10 , so STAR does not read this parameter correctly. Please try to tr-run the genome generation with the space instead i.e.  --genomeSAindexNbases 10
If it does not help, please try to reduce this value to 8 or even 6.

Cheers
Alex

**Comment by maanmi** [comment]
I worked with --genomeSAindexNbases 6! Thank you!

**Comment by alexdobin** [comment]
Great, thanks!
