### ISSUE TITLE
Read fifo not created in --outTmpDir unless a trailing slash exists

### ISSUE THREAD

**Issue by nathanhaigh** [alexdobin/STAR#436]
If `--outTmpDir` is specified without a tailing slash, the read fifo's are not created within that directory:

With `--outTmpDir /tmp/tmp.hXFLfB7hcf_STARtmp` the read fifo's are created as:

```bash
/tmp/tmp.hXFLfB7hcf_STARtmptmp.fifo.read1
/tmp/tmp.hXFLfB7hcf_STARtmptmp.fifo.read2
```

Instead of:

```bash
/tmp/tmp.hXFLfB7hcf_STARtmp/tmp.fifo.read1
/tmp/tmp.hXFLfB7hcf_STARtmp/tmp.fifo.read2
```

If the `--outTmpDir` is specified **with** a trailing slash (e.g. `--outTmpDir /tmp/tmp.hXFLfB7hcf_STARtmp/`), the fifo's are created in that directory as expected.

**Comment by alexdobin** [comment]
Hi Nathan,

it's a bug, thanks for pointing it out! Will fix it in the next patch.

Cheers
Alex
