### ISSUE TITLE
Updating STAR index

### ISSUE THREAD

**Issue by sagnikbanerjee15** [alexdobin/STAR#437]
Hello Alex,

Is it possible to check which fasta sequence ids were used to generate a given STAR index? I also was wondering if there is a chance to update a current index with more sequences.

Thank you.

**Comment by alexdobin** [comment]
Hi Sagnik.

the FASTA sequence ids are stored in the chrName.txt file in the genome directory.
You can add new genome sequences on-the-fly at the mapping stage by specifying --genomeFastaFiles
but you cannot replace/delete the old genome sequences.

Cheers
Alex
