### ISSUE TITLE
Default behavior - save unmapped reads to SAM/BAM output

### ISSUE THREAD

**Issue by ifiddes** [alexdobin/STAR#44]
I would like to request that the option --outSamUnmapped be set to default to saving unmapped reads. Many users of STAR will be unaware of this setting and will end up distributing SAM/BAM files without unmapped reads. This will hinder future reanalysis of these datasets.

The Cancer Genome Hub here at UCSC makes it policy to always store unmapped reads in alignment files.

**Comment by alexdobin** [comment]
Hi Ian,

this is a goo suggestion, however, I am afraid that changing default values will break people's pipelines. I need to poll users to see how often the unmapped reads are not stored.

Cheers
Alex

**Comment by alexdobin** [comment]
Hi Alex,

yes, this option is available for a long time, it's just not the default behavior: --outSAMunmapped Within.

Cheers
Alex

**Comment by iskandr** [comment]
Thanks!
