### ISSUE TITLE
Clarify concept of STAR

### ISSUE THREAD

**Issue by Sealzad** [alexdobin/STAR#440]
Hi, I would like to clarify something about STAR. I understand that it takes the RNAseq data reads, and align them based on an annotation file. Because it is a splice aware program, it can also recognise transcripts that were featured in the dataset. 

My question is  - would it also capture circular RNAs since the latter can be featured as fragments in opposite direction, and be paired with complementary strands. I.e., does STAR capture both linear and circular RNA(unbiasly) and record it in the sam file?

**Comment by Sealzad** [comment]
Hi Dr Alex, 

Sorry I missed it some details. What I meant is that the conventional alignment (without the chimeric junction),  is it possible that the aligner will take reads that are originally circRNA, and map it like a linear transcript instead?

**Comment by alexdobin** [comment]
Hi @Sealzad 

the reads that contain circular junction have to be reported as chimeric.
Some reads that may originate from circRNAs can have a linear structure, but they will be indistinguishable from the reads coming from linear transcripts.

Cheers
Alex

**Comment by Sealzad** [comment]
Dear Dr Alex,

Thank you very much! This is very important information for my debate.

Regards,
Johann
