### ISSUE TITLE
Reduce time to load large genomes

### ISSUE THREAD

**Issue by sagnikbanerjee15** [alexdobin/STAR#441]
Hello,

I am using STAR to align several different libraries (at least 6). All the libraries are being mapped to the same genome hence the STAR index is same. Based on a cursory analysis I found that the time required to load the genome is around 3 minutes. There are several short contigs in the genome. I was wondering if there is any method to keep the genome loaded in the memory from the previous run so that I can eliminate the need to load the same genome for subsequent runs. 

I can also map all the reads from different libraries to the same genome but the result needs to be put into different files.

Thank you.

**Comment by alexdobin** [comment]
Hi Sagnik,

there is a way to load the genome into shared memory and keep it there: use 
--genomeLoad LoadAndKeep
for all the jobs mapping to the same genome (i.e. the same --genomeDir).
After you are done, remove genome from shared memory with 
$ STAR --genomeLoad Remove --genomeDir ...

Cheers
Alex

**Comment by sagnikbanerjee15** [comment]
Thank you very much.
Sagnik Banerjee
Graduate Research Assistant
Bioinformatics and Computational Biology
Department of Plant Pathology and Microbiology
Dr. Roger Wise's Lab
Iowa State University

*"The moment I have realized God sitting in the temple of every human body,
the moment I stand in reverence before every human being and see God in him
- that moment I am free from bondage, everything that binds vanishes, and I
am free" - Swami Vivekananda*

ᐧ
