### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by jessie-wangjie** [alexdobin/STAR#443]
There was one read pair caused the "Segmentation fault" error. No other detailed log information about this error, only the "Segmentation fault".

I tested several parameters, looks like the --peOverlapNbasesMin.
If the --peOverlapNbasesMin was set from 1-7, the error "Segmentation fault" occurs, while the parameter was set larger than 8, the mapping ran successfully.

Here is the read pair. It was mapped to hg19 with gencode v19 annotation.
@mate1
ATCTGAGGAGTGTGGGGATGGAGGCATCTGAGGAGTGTGGGGATGGCTCTCAGCTGGGCCTATGCTGGTCATGAACGGTCCTGGAAAATGACTCCCTTCCT
+
CCCFFFFFCFAFDGIJIGIJJJJJJJJJJJJJJGI?FHGIJJJIJJJIJJJIIHHHHFFFFEEEEEEDDDDDDDDCBDDDDDDDDCCDCCDDCDDDDDDDD
@mate2
CTCAGATGCCTCCATCAACACCAAGCAGCAGTTTCTTAACCACGAAAAGTGAAGACACAATCTCCAAAATGAATGACTTCATGAGGATGCAGATACTGAAG
+
CCCFFFFFHHHHHJJJJJJJJJJJJJJJJJJIHIIJJJIJJJJJJJJJJFFGIIJJJJJIJJJJJHHHHHHFFFFFFEEEEEEDDDDDDDDDDDDDDEDDD

Thank you.

**Comment by alexdobin** [comment]
Hi Jie,

please try the patch on GitHub [master](https://github.com/alexdobin/STAR/archive/master.zip), I think I have fixed the problem.

Thanks!
Alex
