### ISSUE TITLE
Can't build index with version 2.6.0c

### ISSUE THREAD

**Issue by biocyberman** [alexdobin/STAR#444]
Version STAR_2.6.0c

My index command

```bash
STAR --genomeDir $PWD/star  --genomeFastaFiles $PWD/BRCAx.genes.fasta \
     --runThreadN 10 --limitGenomeGenerateRAM 30000000000 --genomeChrBinNbits 14 \
     --runMode genomeGenerate --genomeSAindexNbases 14 \
     --sjdbGTFfile $PWD/BRCAx.gtf
```

Error: 

`13994 Segmentation fault      (core dumped) STAR --genomeDir $PWD/star --genomeFastaFiles $PWD/BRCAx.genes.fasta --runThreadN 10 --limitGenomeGenerateRAM 30000000000 --genomeChrBinNbits 14 --runMode genomeGenerate --genomeSAindexNbases 14 --sjdbGTFfile $PWD/BRCAx.gtf`

Input files are in the attachment. I think there is something wrong with my GTF file because indexing without GTF work fine.

[brcax.tar.gz](https://github.com/alexdobin/STAR/files/2146425/brcax.tar.gz)

**Comment by biocyberman** [comment]
I think I know why. Coordinates in the GTF file and chromosome lengths in the fasta file do not match!

**Comment by alexdobin** [comment]
Hi @biocyberman 

if you have gene sequences in your FASTA file, you do not need to use annotations GTF.

Cheers
Alex
