### ISSUE TITLE
STAR Hung there if file is on NSF

### ISSUE THREAD

**Issue by kemin711** [alexdobin/STAR#446]
I think this is a design flaw when files are across a NSF.  It just hang there without doing any work. No exception, nothing.  Maybe the code needs to do something if no data flow into the program.

**Comment by alexdobin** [comment]
Hi @kemin711

it works fine over NFS as long as the partitions are all standard Linux.
Please try to map uncompressed FASTQ with default parameters, if it does not work, please send me the Log.out file.

Cheers
Alex
