### ISSUE TITLE
htslib issue

### ISSUE THREAD

**Issue by kemin711** [alexdobin/STAR#447]
If the system already has a version of htslib used by other application, then the copy/pasted htslib directory is also building a local version of htslib.so,  This can be a big issue.  If you run the STAR binary in the source directory, it was not able to load the dynamic library.  The way, htslib is link is a major problem.

**Comment by alexdobin** [comment]
Hi Kemin

STAR uses it's own version of htslib, and links it statically. I would not recommend using another htslib library.

Cheers
Alex
