### ISSUE TITLE
Output BAM file read pairing information incorrectly flagged?

### ISSUE THREAD

**Issue by ifiddes** [alexdobin/STAR#45]
I have not figured out what specifically is wrong, but when trying to extract paired reads from a STAR-generated BAM I ran into the following issue.

Samtools flagstat on a paired alignment output from STAR shows all reads properly paired and mapped.

```ku Fri May 22 11:22 brain $samtools flagstat ERR033000Aligned.sortedByCoord.out.bam
67014464 + 0 in total (QC-passed reads + QC-failed reads)
0 + 0 duplicates
67014464 + 0 mapped (100.00%:-nan%)
67014464 + 0 paired in sequencing
33507232 + 0 read1
33507232 + 0 read2
67014464 + 0 properly paired (100.00%:-nan%)
67014464 + 0 with itself and mate mapped
0 + 0 singletons (0.00%:-nan%)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)```

Attempts to extract these reads by using samtools bam2fq capturing singletons in a separate file has 97.5% of reads extracted as singletons.

```kolossus Fri May 22 11:23 brain $samtools view -b ERR033000Aligned.sortedByCoord.out.bam | samtools bam2fq -O -s single.fq - > paired.fq
[M::main_bam2fq] discarded 60937988 singletons
[M::main_bam2fq] processed 62480188 reads```

Sorting this BAM by name and taking alternate lines recovers 67014464 properly paired reads.

**Comment by alexdobin** [comment]
Hi Ian,

the Aligned.sortedByCoord.out.bam file is sorted by coordinate, so alignments of the mates are not always adjacent to each other. My guess is that bam2fq requires mates to be adjacent, which you achieved by sorting them by name. You should also be able to use the Unsorted bam from STAR  without re-sorting it. On the other hand, I think  Picard SamToFastq will work on the sorted by coordinate file.

Cheers
Alex
