### ISSUE TITLE
SJ.out.tab file is empty

### ISSUE THREAD

**Issue by crstumpf** [alexdobin/STAR#453]
I ran STAR to align reads for an experiment to analyze alternative splicing for this first time yesterday.  From the log files, it seems that everything has run ok, however the SJ.out.tab file is completely empty.  the Aligned.out.sam file looks ok so far, but I am still looking into that.  I used the default parameters and the genome files were from UCSC.  Please let me know if you have any suggestions and what other information you need to help.
Thank you,
Craig

**Comment by alexdobin** [comment]
Hi Craig,

are there any splices reported in the Log.final.out file?
Please send it to me together with the Log.out file.

Cheers
Alex

**Comment by crstumpf** [comment]
Alex,
There are splices reported.  I attached the files you asked for, along with the empty SJ.out.tab file in case that is at all helpful.
I appreciate any help you can provide.
Best,
Craig

**Comment by bugkillsme** [comment]
Hi Alex,
Did you solve the problem. I got the same problem.

Thanks,
Qian

**Comment by alexdobin** [comment]
Hi Qian,

it's hard to tell if it's the same problem, please start a new thread, and post the Log.out file for the run that generated empty SJ.out.tab.

Cheers
Alex

**Comment by bugkillsme** [comment]
Hi Alex,
Thanks for your immediate reply. Attached please find the Log.out file. 

Best,
Qian
[C1Log.out.txt](https://github.com/alexdobin/STAR/files/4815372/C1Log.out.txt)

**Comment by alexdobin** [comment]
Hi Qian,

please try to map unzipped fastqs. This could be a problem with fifo files on your partition, please see this post.
https://github.com/alexdobin/STAR/issues/831#issuecomment-581680508

Cheers
Alex

**Comment by bugkillsme** [comment]
Hi Alex,
I mapped unzipped fastqs and it worked! Much appreciated!

Thank you,
Qian

**Comment by alexdobin** [comment]
Hi Qian,

you should be able to work with zipped files if you set --outTmpDir  /path/to/linux/partition/tmp/ to point to a temp directory somewhere on a standard Linux partition (ext3, ext4 etc). 

Cheers
Alex

**Comment by bugkillsme** [comment]
Hi Alex,
I can work with zipped files now with the setting you recommended. Thank you so much!

Best,
Qian
