### ISSUE TITLE
Only report the multiply mapped reads with the best local alignment scores

### ISSUE THREAD

**Issue by jiarui-ding** [alexdobin/STAR#454]
Hi Alex,

For multiply mapped reads, STAR outputs them all but some alignments with better local alignment scores. So I'm wondering it is possible to only keep the alignments with the best local alignment scores. Thank you!

D00197:CC7W2ANXX180205:CC7W2ANXX:1:1101:10002:25511  16      X       40935045        0       3M54N43M48N3M1S *       0       0       GAGGTCGGGGGTCAGGTAGCTGTAGGTCTTAGAAATGGCATCAAAGGTGG      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBBBBB      NH:i:6  HI:i:1  AS:i:51 nM:i:0  NM:i:0
D00197:CC7W2ANXX180205:CC7W2ANXX:1:1101:10002:25511  272     X       40935045        0       3M54N47M        *       0       0       GAGGTCGGGGGTCAGGTAGCTGTAGGTCTTAGAAATGGCATCAAAGGTGG      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBBBBB      NH:i:6  HI:i:2  AS:i:50 nM:i:0  NM:i:0
D00197:CC7W2ANXX180205:CC7W2ANXX:1:1101:10002:25511  272     16      1962161 0       3M54N43M274N3M1S        *       0       0       GAGGTCGGGGGTCAGGTAGCTGTAGGTCTTAGAAATGGCATCAAAGGTGG      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBBBBB      NH:i:6  HI:i:3  AS:i:51 nM:i:0  NM:i:0
D00197:CC7W2ANXX180205:CC7W2ANXX:1:1101:10002:25511  272     16      1962161 0       3M54N47M        *       0       0       GAGGTCGGGGGTCAGGTAGCTGTAGGTCTTAGAAATGGCATCAAAGGTGG      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBBBBB      NH:i:6  HI:i:4  AS:i:50 nM:i:0  NM:i:0
D00197:CC7W2ANXX180205:CC7W2ANXX:1:1101:10002:25511  272     6       43538885        0       3M54N43M48N3M1S *       0       0       GAGGTCGGGGGTCAGGTAGCTGTAGGTCTTAGAAATGGCATCAAAGGTGG      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBBBBB      NH:i:6  HI:i:5  AS:i:51 nM:i:0  NM:i:0
D00197:CC7W2ANXX180205:CC7W2ANXX:1:1101:10002:25511  272     6       43538885        0       3M54N47M        *       0       0       GAGGTCGGGGGTCAGGTAGCTGTAGGTCTTAGAAATGGCATCAAAGGTGG      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBBBBB      NH:i:6  HI:i:6  AS:i:50 nM:i:0  NM:i:0

**Comment by alexdobin** [comment]
Hi @jiarui-ding 

this is possible with --outFilterMultimapScoreRange 0

Cheers
Alex
