### ISSUE TITLE
STAR trimming and quality control

### ISSUE THREAD

**Issue by hhg7** [alexdobin/STAR#455]
Hello,

a while ago, I was wondering why STAR produced significantly lower quality alignments after using a trimming tool https://www.biostars.org/p/298619/#298642.  I was then told by Devon Ryan 

> There's little point in trimming reads with STAR (or other tools that do local alignment), at most trim adapters and very low quality bases (phred scores up to ~3 or so). Presuming you did quality trimming, it's likely that the score you used was much too high, which decreased the number of bases that STAR would have otherwise aligned and therefore decreased the alignment scores. Even adapter trimming isn't perfect, since inevitably you'll end up trimming off a bit of sequence. For both our command line and Galaxy RNAseq workflows, we skip trimming entirely and use STAR with the raw reads. That tends to produce quite nice results.

I cannot use this quote in official work capacity, nor can I find any reference in the manual for it.  Is there official documentation for what Devon Ryan said?

**Comment by as-nobu** [comment]
Hello Alex,

You mentioned "short" and "long" RNA-seq in your answer.
What do you consider "short" and "long" to be in bp?
I

**Comment by alexdobin** [comment]
Hi @as-nobu


in this context, long and short refers to the original RNA length, not the length of the reads.

Short/long RNA boundary is typically defined at 200b.


Cheers

Alex

________________________________
