### ISSUE TITLE
Bus error with STAR_2.6.0a

### ISSUE THREAD

**Issue by kanekalla** [alexdobin/STAR#458]
Hi Alex,
I am unable to align the fastq files

Upon using the command :
STAR --runThreadN 4 --genomeDir /ref/mouse/star_ref/mm10_75b/ --readFilesCommand zcat --readFilesIn ER1.fastq.gz

Jul 23 21:56:50 ..... started STAR run
Jul 23 21:56:50 ..... loading genome
Bus error

**Comment by alexdobin** [comment]
Hi Kishore,

please send me the Log.out file. How much RAM do you have?

Cheers
Alex

**Comment by kanekalla** [comment]
[Log_copy.txt](https://github.com/alexdobin/STAR/files/2225320/Log_copy.txt)

**Comment by alexdobin** [comment]
Hi Kishore,

it will be hard to fit the mouse genome into 8GB of RAM. Ideally, you need 32GB, 16 is OK.
If you cannot get more RAM, we can try to play with parameters to fit it into 8GB.

Cheers
Alex
