### ISSUE TITLE
Duplicate readgroups (same ID) results in ERRORs downstream 

### ISSUE THREAD

**Issue by ellendejong** [alexdobin/STAR#459]
Hi,

Currently, I try to run Star Align on an unmapped bam as part of our RNA-Seq pipeline.  It looks like the alignment was succesful, since "std.out" prints following

> Jul 24 19:05:15 ..... started STAR run
Jul 24 19:05:15 ..... loading genome
Jul 24 19:09:41 ..... started 1st pass mapping
Jul 24 20:04:14 ..... finished 1st pass mapping
Jul 24 20:04:17 ..... inserting junctions into the genome indices
Jul 24 20:09:28 ..... started mapping
Jul 24 21:18:45 ..... started sorting BAM
Jul 24 21:22:57 ..... finished successfully

I also checked other log-files and I did not encounter anything unusual (but I could have missed something). 

However. Further down my pipeline, I was running a task that started complaining about multiple readgroups with the same ID. Then I discovered that my header of the aligned bam indeed **contains multiple @RG lines** (duplicates), which were **not in the original ubam**. I tried to solve this by parsing parameter "--outSAMattrRGline", but that was not the solution either. (Without this parameter, the bottom three @RG lines already exist)

(samtools/1.3, STAR/2.6.0c)

**Aligned, unsorted bam as output from STAR.** 
I cutted complete paths in this example, to make it more readible
> $ samtools view -H RNA-Seq_unsorted.bam 
@HD	VN:1.4
@SQ	SN:chr1	LN:248956422
@SQ	SN:chr2	LN:242193529
@SQ	SN:chr3	LN:198295559
@SQ	SN:chr4	LN:190214555
@SQ	SN:chr5	LN:181538259
@SQ	SN:chr6	LN:170805979
@SQ	SN:chr7	LN:159345973
@SQ	SN:chr8	LN:145138636
@SQ	SN:chr9	LN:138394717
@SQ	SN:chr10	LN:133797422
@SQ	SN:chr11	LN:135086622
@SQ	SN:chr12	LN:133275309
@SQ	SN:chr13	LN:114364328
@SQ	SN:chr14	LN:107043718
@SQ	SN:chr15	LN:101991189
@SQ	SN:chr16	LN:90338345
@SQ	SN:chr17	LN:83257441
@SQ	SN:chr18	LN:80373285
@SQ	SN:chr19	LN:58617616
@SQ	SN:chr20	LN:64444167
@SQ	SN:chr21	LN:46709983
@SQ	SN:chr22	LN:50818468
@SQ	SN:chrX	LN:156040895
@SQ	SN:chrY	LN:57227415
@SQ	SN:chrM	LN:16569
@PG	ID:STAR	PN:STAR	VN:STAR_2.6.0c	CL:STAR   --runThreadN 4   --genomeDir /references/STAR/   --readFilesType SAM   PE      --readFilesIn /inputs/SampleName.bam      --readFilesCommand samtools   view   -h      --outStd BAM_Unsorted   --outReadsUnmapped None   --outSAMtype BAM   Unsorted   SortedByCoordinate      --outSAMattrRGline ID:SampleName_BHFLYNDMXX   SM:SampleName   LB:SampleName   PL:Illumina   PU:180622_A00295_0057_BHFLYNDMXX   CN:Illumina      --alignIntronMax 100000   --alignMatesGapMax 100000   --alignSJDBoverhangMin 10   --alignSJstitchMismatchNmax 5   -1   5   5      --chimSegmentMin 12   --chimJunctionOverhangMin 12   --chimSegmentReadGapMax 0   --twopassMode Basic
@RG	ID:SampleName_BHFLYNDMXX	SM:SampleName	LB:SampleName	PL:Illumina	PU:180622_A00295_0057_BHFLYNDMXX	CN:Illumina
@CO	user command line: STAR --genomeDir references/STAR/ --runThreadN 4 --readFilesIn /inputs/SampleName.bam --readFilesType SAM PE --readFilesCommand samtools view -h --outStd BAM_Unsorted SortedByCoordinate --outSAMtype BAM Unsorted SortedByCoordinate --outSAMattrRGline ID:SampleName_BHFLYNDMXX SM:SampleName LB:SampleName PL:Illumina PU:180622_A00295_0057_BHFLYNDMXX CN:Illumina --twopassMode Basic --outReadsUnmapped None --chimSegmentMin 12 --chimJunctionOverhangMin 12 --alignSJDBoverhangMin 10 --alignMatesGapMax 100000 --alignIntronMax 100000 --chimSegmentReadGapMax parameter 3 --alignSJstitchMismatchNmax 5 -1 5 5
@RG	ID:SampleName_BHFLYNDMXX	SM:SampleName	LB:SampleName	PL:Illumina	PU:180622_A00295_0057_BHFLYNDMXX	CN:Illumina
@RG	ID:SampleName_BHFLYNDMXX	SM:SampleName	LB:SampleName	PL:Illumina	PU:180622_A00295_0057_BHFLYNDMXX	CN:Illumina
@RG	ID:SampleName_BHFLYNDMXX	SM:SampleName	LB:SampleName	PL:Illumina	PU:180622_A00295_0057_BHFLYNDMXX	CN:Illumina

**Original input unmapped bam**

> $ samtools view -H /inputs/SampleName.bam 
@HD	VN:1.5	GO:none	SO:coordinate
@RG	ID:SampleName_BHFLYNDMXX	SM:SampleName	LB:SampleName	PL:Illumina	PU:180622_A00295_0057_BHFLYNDMXX	CN:Illumina

Do you know what is happening? It is not specific for this unmapped bam, I have it all times.

**Comment by alexdobin** [comment]
Hi Ellen,

since you already have the read groups in the uBAM, you do not have to specify them again in the STAR command. Please try to map again without the --outSAMattrRGline  option.

Cheers
Alex

**Comment by alexdobin** [comment]
Hi Ellen,

thanks for the test, it does look like a bug. I will try to reproduce and fix it.

Cheers
Alex

**Comment by alexdobin** [comment]
Hi Ellen,

I tried to reproduce the problem on my test examples, and I do not observe it.
Could you please send me the BAM file? You can cut it down to just a few reads - if you can check that it still outputs 3RG lines. You are redirecting the unsorted output to a file via stdout, right?
Please send me the resulting file as well.

Thanks!
Alex

**Comment by ellendejong** [comment]
Hoi Alex,

I will come back on your request. 

Ellen.

**Comment by alexdobin** [comment]
Hi Ellen,

thanks a lot for the files - I can reproduce the problem now, and am working on a fix.

Cheers
Alex

**Comment by alexdobin** [comment]
Hi Ellen,

I have fixed the problem, please try the patch on GitHub [master](https://github.com/alexdobin/STAR/archive/master.zip).
Thanks a lot for your help!

Cheers
Alex

**Comment by ellendejong** [comment]
Thanks Alex.
