### ISSUE TITLE
Segmentation fault running STAR 2.4.1d Linux_x86_64

### ISSUE THREAD

**Issue by ctstackh** [alexdobin/STAR#46]
**LSF Options:**
```
bsub -n 12 -q normal -R span[hosts=1] -R rusage[mem=40000] -o lsf.out -e lsf.err
```
**Command Line:**
```
STAR --runThreadN 12 --outSAMtype BAM Unsorted SortedByCoordinate --quantMode TranscriptomeSAM GeneCounts --twopassMode Basic --genomeDir GRCh38.79.chrom1/ --readFilesIn fastq/SRR1039508_1.fastq fastq/SRR1039508_2.fastq
```
**lsf.err File:**

/gpfs/gpfs1/home/cs/.lsbatch/1432850412.956154: line 8: 14626 Segmentation fault      (core dumped) STAR --runThreadN 12 --outSAMtype BAM Unsorted SortedByCoordinate --quantMode TranscriptomeSAM GeneCounts --twopassMode Basic --genomeDir GRCh38.79.chrom1/ --readFilesIn fastq/SRR1039508_1.fastq fastq/SRR1039508_2.fastq

**lsf.out File:**

Exited with exit code 139.

Resource usage summary:

    CPU time :               22061.85 sec.
    Max Memory :             8534 MB
    Average Memory :         5596.50 MB
    Total Requested Memory : 40000.00 MB
    Delta Memory :           31466.00 MB
    (Delta: the difference between total requested memory and actual max usage.)
    Max Swap :               11843 MB

    Max Processes :          3
    Max Threads :            26

The output (if any) follows:

May 29 03:02:16 ..... Started STAR run
May 29 03:02:17 ..... Loading genome
May 29 03:02:50 ..... Started 1st pass mapping
May 29 03:35:28 ..... Finished 1st pass mapping
May 29 03:35:29 ..... Inserting junctions into the genome indices
May 29 03:35:49 ..... Started mapping

**Comment by alexdobin** [comment]
Hi Christian,

the --quantMode GeneCounts option is still not operational. Please try mapping without it.

Cheers
Alex
