### ISSUE TITLE
STAR mapping parameters

### ISSUE THREAD

**Issue by sagnikbanerjee15** [alexdobin/STAR#460]
Hello Alex,

I am currently working on a genome annotation project for which I am mapping short RNA-Seq from over 250 libraries. The libraries are from different bioprojects conducted over 10 years. Hence the average quality of the reads vastly differ from sample to sample. Since I have plenty of reads I wish to make my alignments as stringent as possible retaining the most confident alignments. I am planning to do adapter trimming and quality trim bases with very low quality using Trimmomatic. Here is an example of the parameters I am using for STAR mapping. Could you please go over the list and suggest changes if needed? I will later use Trinity for assembling. I am using python to generate the command for running STAR.

        cmd="STAR "

        cmd+=" --runThreadN "+options.cpu

        cmd+=" --genomeDir "+options.genome_dir

        cmd+=" --readFilesIn "+options.input_directory+"/"+run+".fastq "

        cmd+=" --outFileNamePrefix "+output_prefix

        cmd+=" --outSAMtype BAM SortedByCoordinate "

        cmd+=" --limitBAMsortRAM "

        cmd+=" --outBAMcompression 10 "

        cmd+=" --outBAMsortingThreadN 20 "

        cmd+=" --outWigType wiggle "

        cmd+=" --outReadsUnmapped Fastx "

        cmd+=" --outFilterMultimapNmax 1 " # Retain only uniquely mapped reads

        cmd+=" --outFilterMismatchNmax 999  "

        cmd+=" --alignIntronMin 20  "

        cmd+=" --alignIntronMax 1000000 "

        cmd+=" --alignSJoverhangMin 8 "

        cmd+=" --alignSJDBoverhangMin 1"

        cmd+=" --alignMatesGapMax 1000000 "

        cmd+=" --outFilterType BySJout "

        cmd+=" --outFilterMismatchNoverLmax 0.01 " # real: alignment will be output only if its ratio of mismatches to *mapped* length is less than or equal to this value.

        cmd+=" --outFilterMismatchNoverReadLmax 0.05 " # real alignment will be output only if its ratio of mismatches to *mapped* length is less than or equal to this value.

        cmd+=" --outSJfilterReads Unique " # which reads to consider for collapsed splice junctions output. Unique: uniquely mapping reads only

        cmd+=" --outSJfilterOverhangMin 30 12 12 12 "

Also I am having trouble understanding what a splice overhang is. Let us imagine we have the following alignment (where read 1 ends up having a spliced alignment). What will be the splice overhang?

Genome  ........AATTCTACTACAGCTACTATCATCAGCACAGCATCATCATCAGCATCACGTAGAT...........
Read1                                          GCTACTATCATCA----------------TCATCAG

In such a case what is the overhang? I do not understand why a max has to be set using the parameter --alignSJoverhangMin. I am not quite sure what an overhand is.  If I provide both outFilterMismatchNoverLmax and outFilterMismatchNoverReadLmax which parameter will get more preference?

**Comment by alexdobin** [comment]
Hi Sagnik,

you parameters look OK to me. 
--outFilterMismatchNoverLmax 0.01 is the max number of mismatches normalized to the mapped lengths (that can be < read length). This will be much more stringent (and thus will "win") than --outFilterMismatchNoverReadLmax 0.05 which is the max number of mismatches normalized to total read length.

Also, for stringency, you may want to increase --outFilterScoreMinOverLread and --outFilterMatchNminOverLread , I would recommend up to 0.9.

The overhang for each spliced alignment is the shortest of the spliced segments, i.e. TCATCAG in your case, 7b. This is controlled by --alignSJoverhangMin and --alignSJDBoverhangMin.
For a junction, the maximum of these shortest overhangs from all reads that cross this junction is calculated, and this controlled by --outSJfilterOverhangMin

Cheers
Alex

**Comment by sagnikbanerjee15** [comment]
Thank you very much Alex for your help.
