### ISSUE TITLE
Mapping Parameters for Dosophila

### ISSUE THREAD

**Issue by PatrickKratsch** [alexdobin/STAR#461]
Hi Alex,

Are there any changes you know to recommend for mapping to the Drosophila melanogaster reference genome? I have changed a few, such as --alignIntronMax, but am wondering whether there are others you know should be changed to optimise mapping. Thanks a lot.

Best,

Patrick

**Comment by alexdobin** [comment]
Hi Patrick,

the --alignIntronMax and --alignIntronMin are the ones that have to be changed for the Drosophila.

Cheers
Alex

**Comment by PatrickKratsch** [comment]
Thanks a lot, Alex. I'll change --alignIntronMin as well then.


Cheers,

Patrick

**Comment by Mitmischer** [comment]
What values should I choose for those? Should I make this decisions based on the mapping rate?
