### ISSUE TITLE
Multimapping chimeras in Chimeric.out.sam

### ISSUE THREAD

**Issue by suhrig** [alexdobin/STAR#462]
Dear Alex,

Since version 2.6.0 multimapping chimeras are reported, but only in the junctions file. Some fusion detection algorithms based on STAR use the chimeric alignments file directly. Are there plans to report multimappers in the Chimeric.out.sam file? If yes, do you have an idea when and how (which SAM flags)?

Regards,
Sebastian

**Comment by alexdobin** [comment]
Hi @suhrig 

I am planning to include the multimapping chimeras in the BAM chimeric output. On the other hand, I am planning to deprecate the Chimeric.out.sam output in the near future, as this output was not standardized.

Cheers
Alex

**Comment by suhrig** [comment]
Hi Alex,

Once Chimeric.out.sam is deprecated, will chimeras be reported elsewhere or will they not be reported at all? BWA, for example, uses the SA flag to store chimeras in the main alignments file (similar to the WithinBAM option). They can be quite helpful for visualization or for closer inspection. I actually find this to be one of the strengths of STAR that the supporting reads of a fusion can be inspected. Most fusion detection tools discard this information and it's difficult to find out what evidence a prediction is based on.

Regards,
Sebastian

**Comment by alexdobin** [comment]
Hi Sebastian,

as far as I understand, the STAR's WithinBAM option should work exactly like BWA's, which seems to be the agree with the SAM official recommendations for chimeric formatting. I do plan to fully support this format.

Cheers
Alex

**Comment by suhrig** [comment]
Hi Alex,

Have you found time to make some progress on this issue? I had a look at STAR's code to find out what would be necessary to report multi-mapping chimeric alignments in a standards-compliant fashion. With just a few modifications, I came up with a hacky version that reports multi-mapping chimeric alignments to the BAM file. I might find some more time to write a clean version, but before I invest a lot I would like to clarify some things, to avoid going in the wrong direction.

- First of all, are you still working on this? What's your timeline? I would not want your and my efforts to be redundant.

- What are the obstacles of implementing this?

- I see that the new chimeric read detection was moved to a new C++ class `ChimericAlign`, whereas the old detection method was part of the class `ReadAlign`. What is your strategy? Is this only a temporary solution to avoid conflicts with the old method and do you eventually plan to merge the code of the `ChimericAlign` class back into the `ReadAlign` class? Or do you plan to drop the chimeric code from the `ReadAlign` class altogether and only have a `ChimericAlign` class in the future? I want to make sure I'm going the right way, if I indeed find the time to work on this.

Regards,
Sebastian

**Comment by alexdobin** [comment]
Hi Sebastian,

sorry for the belayed reply. The multimapping chimeric detection is implemented in the ChimericDetection_chimericDetectionMult.cpp function, though the output is only into Chimeric.out.junction at the moment.

If you are interested in creating SAM output for the multimapping it would be a great contribution!

The "new" chimeric detection in ChimericSegmentm, ChimericAlign, and ChimericDetection classes will be the mainstream in the future, while I am planning to retire the "old" chimeric code ReadAlign_chimericDetection.cpp in the near future.

Cheers
Alex
