### ISSUE TITLE
bam file in temp directory

### ISSUE THREAD

**Issue by toddcreasy75** [alexdobin/STAR#463]
Hi,

I'm trying to figure out what is in the bam file that's in the temp directory from a STAR run. Does the bam file contain ALL the reads from the fastq files (aligned/unaligned)? I'm hoping to extract fastq files from them because I accidentally deleted the original fastq files.

Thanks for any help you can provide.

-todd

**Comment by alexdobin** [comment]
Hi @toddcreasy75 

by the temp directory, do you mean Aligned.out.bam the run directory? STAR is not supposed to create bam files in the _STARtmp directory. You can re-create FASTQ for mapped reads from Aligned.out.bam and also unmapped reads, if you used --outSAMunmapped Within .

Cheers
Alex

**Comment by toddcreasy75** [comment]
Hi Alex,

I should have been more descriptive. I actually ran RSEM *with* STAR with:

--keep-intermediate-files
--output-genome-bam 

I think this is what is generating that bam file in the .temp directories. Is that correct?

-todd

**Comment by alexdobin** [comment]
Hi Todd,

I think you should be able to re-create the FASTQ files from the RSEM BAM files, however, I think you will only get the reads that mapped to known transcripts - you will not get reads that mapped to intergenic or intronic space.

Cheers
Alex

**Comment by toddcreasy75** [comment]
Thanks, Alex. That's what I wasn't sure about. Didn't know if that specific bam file contained unmapped reads or not. Thanks for you help.
