### ISSUE TITLE
Mapping successfully, but all 0s in Log.final. out

### ISSUE THREAD

**Issue by bsun0802** [alexdobin/STAR#468]
Hi,

I was running STAR/RSEM pipeline and rsem complains that no `alignable.fq` found. The STAR finished with no error, 
```
Aug 09 20:23:51 ..... started STAR run
Aug 09 20:23:51 ..... loading genome
Aug 09 20:27:38 ..... started mapping
Aug 09 20:27:41 ..... finished successfully

```
But the Log.final.out contains nothing but 0 and an "NaN"

```
                                 Started job on |       Aug 10 10:30:54
                             Started mapping on |       Aug 10 10:34:41
                                    Finished on |       Aug 10 10:34:42
       Mapping speed, Million of reads per hour |       0.00

                          Number of input reads |       0
                      Average input read length |       0
                                    UNIQUE READS:
                   Uniquely mapped reads number |       0
                        Uniquely mapped reads % |       0.00%
                          Average mapped length |       0.00
                       Number of splices: Total |       0
            Number of splices: Annotated (sjdb) |       0
                       Number of splices: GT/AG |       0
                       Number of splices: GC/AG |       0
                       Number of splices: AT/AC |       0
               Number of splices: Non-canonical |       0
                      Mismatch rate per base, % |       -nan%
                         Deletion rate per base |       0.00%
                        Deletion average length |       0.00
                        Insertion rate per base |       0.00%
                       Insertion average length |       0.00
                             MULTI-MAPPING READS:
        Number of reads mapped to multiple loci |       0
             % of reads mapped to multiple loci |       0.00%
        Number of reads mapped to too many loci |       0
             % of reads mapped to too many loci |       0.00%
                                  UNMAPPED READS:
       % of reads unmapped: too many mismatches |       0.00%
                 % of reads unmapped: too short |       0.00%
                     % of reads unmapped: other |       0.00%
                                  CHIMERIC READS:
                       Number of chimeric reads |       0
                            % of chimeric reads |       0.00%
```

I was running the same pipeline for 3005 cells, most of them succeed, and I suspect that only the cells that have more than one input fastq files failed(I comma separated them as the value of option --readFilesIn of course). 

But the RSEM generated STAR command are too complex for me to understand it, I tried run with STAR default settings and there was no problem. So, could you please help me find what is the cause of this behavior? Following is the RSEM generated STAR command, which produce the error above:

```sh
/home/rcf-40/bos/panfs/software/STAR-2.6.0a/bin/Linux_x86_64/STAR --genomeDir /home/rcf-40/bos/3.scRNA-seq/genome/RSEM-M10-primary  --outSAMunmapped Within  --outFilterType BySJout  --outSAMattributes NH HI AS NM MD  --outFilterMultimapNmax 20  --outFilterMismatchNmax 999  --outFilterMismatchNoverLmax 0.04  --alignIntronMin 20  --alignIntronMax 1000000  --alignMatesGapMax 1000000  --alignSJoverhangMin 8  --alignSJDBoverhangMin 1  --sjdbScore 1  --runThreadN 8  --genomeLoad NoSharedMemory  --outSAMtype BAM Unsorted  --quantMode TranscriptomeSAM  --outSAMheaderHD \@HD VN:1.4 SO:unsorted  --outFileNamePrefix /home/rcf-40/bos/3.scRNA-seq/STAR-RSEM/GSM1475372/rsem.temp/rsem  --readFilesIn /home/rcf-40/bos/3.scRNA-seq/download/fastq/SRR1546264.fastq,/home/rcf-40/bos/3.scRNA-seq/download/fastq/SRR1546265.fastq
```

**Comment by bsun0802** [comment]
No worries, it is due to there is no more storage space on our university's cluster. 
3005 cells is a pretty large scale. 
So this is how STAR will behave when reaching space limit. Good to know 🤷‍♂️

**Comment by alexdobin** [comment]
Hi Bo,

I have to add the disk space checks into output operations.
Note that another possibility for the 0 input reads is that something is wrong with the input files.

Cheers
Alex

**Comment by bsun0802** [comment]
Thank you, no problem. I'm pretty sure the fastq files are solid.

And if you don't mind, may I ask you a question?   

If I want to remove the UMIs from the 5'end of the read, what is the convention to store this UMI sequence, I prepend the clipped reads to the head of the name of the read, i,e, the 1st and 3rd lines for each read in fastq files, right after the `@` and `+`symbol. 

like this 
```
@AATCAAGGG_SRR1548161.1 Run0236_AC3NLCACXX_L7_T1101_C1 length=42
AAGCAAGATGGCGAGCGCGCGGAACGAAAATCTGTGTGCCTA
+AATCAAGGG_SRR1548161.1 Run0236_AC3NLCACXX_L7_T1101_C1 length=42
HHHHIIIIHIIIIIIIIIDIIIIHHFFFDDEEDECCCBDDDC
```

But RSEM will complain "does not support clipped reads". So my current solution is to added the UMIs into run&lane information, after the name of the read. Because I don't want to throw out UMI information, I may need it in downstream analysis.

**Comment by alexdobin** [comment]
Hi Bo,

are you clipping the UMIs with the --clip5pNbases option?
This would result in soft-clipped reads which RSEM cannot work with.
You would need to completely remove the UMIs from the reads before mapping.
Adding the sequences to read names should not cause problems with RSEM.

Cheers
Alex

**Comment by littlejosh800** [comment]
How to read this? 26|10/30|12:54 AM|347.383.9099|TextMessaging|--|0.0|0.00		
27|10/30|12:54 AM|347.383.9099|TextMessaging|--|0.0|0.00
