### ISSUE TITLE
where is the pre-compiled STAR executable for Mac

### ISSUE THREAD

**Issue by corn23** [alexdobin/STAR#469]
Hi

According to the doc and your answer in other issues (eg @ #405 ), there is a pre-compiled STAR executable for Mac in /bin directory. But now I can't see it. Is it still available? Where can I find it. Thanks!

**Comment by alexdobin** [comment]
Hi @corn23 

If you download and unzip 2.6.0c, the Mac executable should be 
STAR-2.6.0c/bin/MacOSX_x86_64/STAR

Cheers
Alex
