### ISSUE TITLE
--sjdbOverhang=49 is not equal to the value at the genome generation step =0

### ISSUE THREAD

**Issue by MaxKman** [alexdobin/STAR#470]
Hi,

thanks for continously developing STAR. Great tool! I updated to STAR 2.6.0c and tried to use it with the [zUMIs pipeline ](https://github.com/sdparekh/zUMIs). I generated a genome index without a GTF file with the following command:

`/home/makaufm/STAR/bin/Linux_x86_64/STAR   --runMode genomeGenerate   --runThreadN 28   --genomeDir /data/max/00_reference/STAR_2.6.0c/hg19   --genomeFastaFiles /data/shared/dropseq/reference/hg19/hg19_ERCC.fasta`

when I then run the pipeline I get the following error
> EXITING because of fatal PARAMETERS error: present --sjdbOverhang=49 is not equal to the value at the genome generation step =0

This seems similar to a previously described solved, where sjdbOverhang was set to 100 for a genome index if not specified just that it is set to 0 now.

EDIT: I now generated a new index with STAR 2.5.4a (which was the version zUMIs 2.0 was tested with) and used the same version for mapping and did not have any problems.

Best Max

**Comment by alexdobin** [comment]
Hi @MaxKman 

this is likely a problem with different STAR versions for genome generation and running.
It also works fine if the genome is generated with 2.6.0c and mapping is done with 2.6.0c .

Cheers
Alex

**Comment by MaxKman** [comment]
Hey Alex,
thanks for the quick response. It could be the case that I accidentally created the STAR index with an older version of STAR. Is there a way to check what STAR version was used to create a genome index?

Best Max

**Comment by alexdobin** [comment]
Hi Max,

the first line of the Log.out file for the index generation run has the STAR version.

Cheers
Alex

**Comment by MaxKman** [comment]
Hey Alex,

in my case the log.out file was unfortunately overridden, when I produced the index with 2.5.4a. I think you can close the issue for now. I'll let you know if I run into the same problem again in the future.

Best Max

**Comment by jeaahakobyan** [comment]
Hi Alex,

I still have the issue with 2.7.1a with mouse genome(if this may have any effect). Both index generation and alignment are run with the same version. Is there anything else I have to check?

Best,
Anna

**Comment by alexdobin** [comment]
Hi Anna,

please send me the Log.out file.

Cheers
Alex

**Comment by alexdobin** [comment]
Hi Anna,

sorry for the belayed reply. I see two issues in the Log files:
1. Since the default ```--sjdbOverhang 100``` was used at the genome generation step, you cannot use ```--sjdbOverhang 149``` at the mapping stage. This is the cause of fatal error. To solve this, you would need to either re-generate the geome with ```--sjdbOverhang 149```, or drop it from the mapping command.

2. The annotations file that you have has .gff extension, but it looks like GTF formatted file, with transcript_id and gene_id in each exon line. So you would need to generate the genome without
```--sjdbGTFtagExonParentTranscript Parent```

Cheers
Alex
