### ISSUE TITLE
Compile STAR on MAC

### ISSUE THREAD

**Issue by Wenfei-Sun** [alexdobin/STAR#471]
Dear Alex,

Thanks a lot for keeping improving STAR!

I'm a first time user, with a problem to install STAR on my MAC.
After following "git clone https://github.com/alexdobin/STAR.git",

I simply can not get through "cd source"

with error information:
-bash: cd: source: No such file or directory
public-docking-als-2550:~ sunwenfei$ 

Best, Wenfei

**Comment by alexdobin** [comment]
Hi Wenfei,

You need to find the directory it was cloned into, than cd into it, and then cd into source.
What is output of ls after you do git clone?
I would recommend that you use pre-compiled Mac executables, which are inside bin/Mac.../ directory.

Cheers
Alex
