### ISSUE TITLE
Open the executable file on MacOS

### ISSUE THREAD

**Issue by pat22296** [alexdobin/STAR#473]
Hello alexdobin,
I don't know how to open the executable file I got from [here](https://github.com/alexdobin/STAR/tree/master/bin/MacOSX_x86_64). When I try to execute it a TextEdit window pops up. So it tried installing it through the source code, but I get the following error:

clang: error: unsupported option '-fopenmp'
make: *** [Depend.list] Error 1

Can you please tell me how to install from the executable ?

**Comment by alexdobin** [comment]
Hi @pat22296 

you have to run STAR executable from a terminal window.
Compiling on Mac requires installing gcc compiler at the moment.
Clang 3.8.0 is supposed to support OpenMP but I have not tried it yet.

Cheers
Alex
