### ISSUE TITLE
Number of threads to use

### ISSUE THREAD

**Issue by ClaireG18** [alexdobin/STAR#476]
Dear all,

STAR is extremely fast but I wonder if there is a recommendation in what is the optimal number threads to use?
I realized only a posteriori that I ran STAR using --runThreadN 36 on a machine with 32 CPUs. It did not give me any warning and it seemed to run fine.  How did STAR handle this issue? Does it mean I actually slowed down the computations?
Thank you

Claire

**Comment by alexdobin** [comment]
Hi Claire,

typically, using more threads then CPUs does not reduce mapping speed, though it does not increase it either. With a large number of threads, the bottleneck is most likely the disk write speed, as the output files (BAM/SAM) are usually big.

Cheers
Alex

**Comment by ClaireG18** [comment]
Hi Alex,
thanks for the answer. So if I understand correctly, using number of threads=number of CPUs should be for the future a good choice.  
Cheers

**Comment by alexdobin** [comment]
Hi Claire,

yes, this would be typically a good choice. Ideally, you would want to find the point of diminishing return, i.e. increase the number of threads until there is no more significant gain in mapping speed. Then you can use the remaining CPUs/cores for other tasks.

Cheers
Alex

**Comment by ClaireG18** [comment]
Thanks for the advice!
