### ISSUE TITLE
Which reference genome should be used?

### ISSUE THREAD

**Issue by thuhongle** [alexdobin/STAR#479]
Hi,
I am new in RNASEQ, as well as using STAR. I am wondering which reference genome for Rat from Ensembl should be used for alignment:

1.Rattus_norvegicus.Rnor_6.0.dna_sm.toplevel.fa.gz
2.Rattus_norvegicus.Rnor_6.0.dna_rm.toplevel.fa.gz
3.Rattus_norvegicus.Rnor_6.0.dna.toplevel.fa.gz

Note that the suggested "primary assembly" version is not available for Rat, so I have to take "top.level" one. 

Many thanks in advance!
Best wishes,
Thu

**Comment by thuhongle** [comment]
Many thanks Alex for your answer!

I have a problem need to ask for your help. 
I use STAR to (1) generate index Reference genome (Rat) and then (2) align read files using indexed ref genome. 
The (1) step seems working well, with log file as step1.log
The (2) step got problem, after several tests, it seems STAR could not read zipped fastq file.

- I tried using both --readFilesCommand zcat and --readFilesCommand gunzip -c, not working
- I have tried to use 2 versions 2.6.1a and 2.5.3a but nothing changed.
- I have tried to get 40 first lines from raw fastq.gz and feed to STAR, working well **(test5Log.out)**
- I tried to compress these 40-lines files into .gz file (reduced files)- not working **(test13Log.out)**

I attach here the the reduced files (file1.fastq.gz and file2.fastq.gz as read1 and read2), also the Log files of both test5 (unzipped-worked) and test13 (zipped-not worked), please could you have a test on them? 

Many thanks in advance!
[file1.fastq.gz](https://github.com/alexdobin/STAR/files/2340931/file1.fastq.gz)
[file2.fastq.gz](https://github.com/alexdobin/STAR/files/2340932/file2.fastq.gz)

[test5Log.out.txt](https://github.com/alexdobin/STAR/files/2340936/test5Log.out.txt)
[test13Log.out.txt](https://github.com/alexdobin/STAR/files/2340937/test13Log.out.txt)


Best,
Thu


I attached here the Log.out files and

**Comment by alexdobin** [comment]
Hi Thu,

is you output partition (outFileNamePrefix) FAT? FAT partitions do not support fifo files - this would explain the problems with gzip. You can check it by trying
$ mkfifo tmp1
on the output directory.

Please try to output to a Linux partition, or use --outTmpDir pointing to a Linux partition.

Cheers
Alex

**Comment by keremw** [comment]
Hi Thu and Alex,
Have you manged eventually to use STAR to align the rat genome? Have you used the GTF file provided by Ensemble to generate the genome using the GTF option?
Thanks,
Kerem

**Comment by alexdobin** [comment]
Hi @keremw 

I am not aware of any problems with the rat genome. Please make sure that you are using the genome without masking - i.e. Rattus_norvegicus.Rnor_6.0.dna.toplevel.fa.gz

Cheers
Alex

**Comment by keremw** [comment]
Thank you Alex!
