### ISSUE TITLE
how can I collect the full list of parameters used for a run (not only the ones I defined)

### ISSUE THREAD

**Issue by splaisan** [alexdobin/STAR#480]
I see the _/source/parametersDefault_ which reports many parameters.

I suspect that some may vary between versions and would like to report MY used params together with my data.

Can I collect these somehow or do I only have the ones I add to my command.

This would be nice for reproducibility between subversions (when something would change)

**Comment by alexdobin** [comment]
Hi Stephane

I am trying very hard not to change the default values (and in general the default behavior) to maximize reverse compatibility.

parametersDefault actually contains all the default parameters.
In principle, you can import these values into a new version run with --parametersFile /path/to/parametersDefault option followed by your parameters.

Another way to do it is to cut the parameters the lines after
##### Final parameters after user input ----------------------------------------
versionSTAR                       20201
versionGenome                     20101   20200
parametersFiles                   -

and before
----------------------------------------
in the Log.out file. These lines contain all default parameters for the current version and user parameters merged.
In the next release, I will remove these lines from Log.out and output them into a separate file.

Cheers
Alex

**Comment by splaisan** [comment]
This is very useful info. Thanks for the trick to get the parameters.
Would it be possible to reproduce this somewhere in your doc (if not there yet of course)
I am sure I will search for this again in the future (and many others)
Also I do not find much in the STAR -h about it

```
### Parameter Files
parametersFiles          -
    string: name of a user-defined parameters file, "-": none. Can only be defined on the command line.
```

maybe this could be detailed a bit more.

Thanks for the great app!

**Comment by splaisan** [comment]
One last, what should be the syntax in that text file?
including the '--' or without them; tab separated or space or either

dummy example

```
--limitBAMsortRAM 16000000000
--outSAMunmapped Within
--twopassMode Basic
--outFilterMultimapNmax 1
--quantMode TranscriptomeSAM
--runThreadN 20
```

thanks in advance for clarifying this last point

**Comment by alexdobin** [comment]
Hi Stephane,

the "parameters" file has simple formatting:
<parameterName> <value1> <value2> <value3> ...
i.e.
limitBAMsortRAM 16000000000
outSAMunmapped Within
twopassMode Basic
outFilterMultimapNmax 1
quantMode TranscriptomeSAM
runThreadN 20

Cheers
Alex
