### ISSUE TITLE
Low mapping rate : Short reads (low insert size) not mapped

### ISSUE THREAD

**Issue by ranjit58** [alexdobin/STAR#484]
Hi Alex,

I was recently investigating low mapping rate (~ 40-50%) in few RNASeq experiments. After evaluating the read pairs I realized that they have short insert size and many-time even identical sequences (just reverse complement of each other).I think they might be called discordant read pairs. However STAR aligner (even latest version) with default settings did not align them. Is this the intended behavior of STAR? Mapping the same read pair with other tools (kallisto, bwa-mem, hisat2) gave number > 95%. Actually STAR also mapped these with >90% mapping rate when just single end reads are used (instead of pair). I can create a small example set if you like.

thanks,
Ranjit

**Comment by alexdobin** [comment]
Hi Ranjit,

STAR should not have a problem with identical reverse complemented sequences for two mates.
If you could send a couple of examples, I will have a look.
One of the possible cases which STAR would filter by default is when trimming is done before mapping, and the mates ends protrude past each other (i.e. the -strand mate start is to the left of the +strand mate). You can allow such alignments with --alignEndsProtrude 10 ConcordantPair .
If you have a lot of overlapping reads, I would recommend trying the new option in STAR that merges overlapping mates before mapping: --peOverlapNbasesMin 10 .

Cheers
Alex

**Comment by ranjit58** [comment]
Hi Alex,

We did performed trimming before the alignment so its possible they might protrude past each other. I will check them and will get back to you.

thanks,
Ranjit
