### ISSUE TITLE
std::out_of_range error

### ISSUE THREAD

**Issue by Roghaiyeh** [alexdobin/STAR#485]
I am trying to make my index by STAR. every cods and paths are correct. It starts to run but it terminates saying the message below. could somebody help me how to solve it.
Thanks

terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check

**Comment by alexdobin** [comment]
Hi @Roghaiyeh 

please send me the Log.out file.

Cheers
Alex

**Comment by Roghaiyeh** [comment]
Dear Alex,

Now I have another problem. I lunched the STAR for alignments and mapping, then feuture counts for reading. The txt file that I had after reading is very strange I am attaching it here. It does not look normal. and no name of genes just numbers not in a good order. Could you help me what is the problem and what to do?

My Best,
Rugi
[counts.txt](https://github.com/alexdobin/STAR/files/2396517/counts.txt)

**Comment by Roghaiyeh** [comment]
Dear Alexx this is the error that i recieved and after I get a weired txt fule.

Warning: failed to find the gene identifier attribute in the 9th column of the provided GTF file.
The specified gene identifier attribute is 'gene-id'
The attributes included in your GTF annotation are 'gene_id "ENSOARG00000017577"; gene_version "1"; transcript_id "ENSOART00000019126"; transcript_version r "1"; gene_name "ING5"; gene_source "ensembl"; gene_biotype "protein_coding"; transcript_name "ING5-201"; transcript_source "ensembl"; transcript_biotype "; exon_id "ENSOARE00000174320"; exon_version "1";'

||    Features : 239130                                                       ||
||    Meta-features : 1                                                       ||
||    Chromosomes/contigs : 702                                               ||
||                                                                            ||
|| Process BAM file resultsAligned.sortedByCoord.out.bam...                   ||
||    Paired-end reads are included.                                          ||
||    Assign reads to features...                                             ||
||    Total reads : 33880102                                                  ||
||    Successfully assigned reads : 12941327 (38.2%)                          ||
||    Running time : 0.96 minutes                                             ||
||                                                                            ||
||                         Read assignment finished.                          ||
||                                                                            ||
|| Summary of counting results can be found in file "counts.txt.summary"

**Comment by Roghaiyeh** [comment]
it has been solved. was typo error :(((
