### ISSUE TITLE
seedSearchLmax causing segfault

### ISSUE THREAD

**Issue by pjongeneel** [alexdobin/STAR#486]
Hi there, in reference to https://groups.google.com/forum/#!topic/rna-star/-3slzCzJGnk, I was getting a segfault for various values of seedSearchLmax, while others seemed to work fine, with the same other parameters.

Here is an example command line
/reference/env/qa/apps/fusioncatcher/0.99.7c-p6/fusioncatcher/tools/star/source/STAR \
   --twopass1readsN -1 \
   --twopassMode Basic \
   --genomeSAindexNbases 14 \
   --sjdbOverhang 91 \
   --alignIntronMax 1405740 \
   --outFilterMatchNmin 9 \
   --outFilterMatchNminOverLread 0.15 \
   --outFilterScoreMinOverLread 0.15 \
   --alignSplicedMateMapLminOverLmate 0.15 \
   --genomeDir /FusionCatcher/test/gene-gene-star/ \
   --runThreadN 12 \
   --seedSearchStartLmax 2 \
   --alignSJoverhangMin 9 \
   --alignSJstitchMismatchNmax 5 -1 5 5 \
   --outSJfilterOverhangMin 10 10 10 10 \
   --outSJfilterCountUniqueMin 1 1 1 1 \
   --outSJfilterCountTotalMin 1 1 1 1 \
   --outSJfilterDistToOtherSJmin 0 0 0 0 \
   --outSJfilterIntronMaxVsReadN 1405740 1405740 1405740 \
   --limitOutSAMoneReadBytes 100000000 \
   --scoreGapNoncan -4 \
   --scoreGapATAC -4 \
   --limitSjdbInsertNsj 2000000 \
   --readFilesIn /FusionCatcher/test/reads_gene-gene_no-str_fixed.fq \
   --outFileNamePrefix /FusionCatcher/test/gene-gene-star-results

This command works. If you change --seedSearchStartLmax 9 it doesnt work.

I noticed that this had been intended to be fixed, but I couldnt find it in the release notes. Has this bug been fixed?

**Comment by pjongeneel** [comment]
also could you elaborate on the effects of changing this seed?

**Comment by alexdobin** [comment]
Hi @pjongeneel 

the parameter you are tweaking --seedSearchStartLmax is different from the one in post you reference (--seedSearchLmax). If you can send me a minimal example that reproduces the bug, I will look into it. Note that values <15 for this parameter are very aggressive and may require tweaking of other parameters to work.

Cheers
Alex
