### ISSUE TITLE
STAR 2.6.0c "FATAL ERROR: could not create output file ... Solution: check that you have permission to write this file"

### ISSUE THREAD

**Issue by ClaireG18** [alexdobin/STAR#488]
Dear Alex,

when running STAR-2.6.0c with --runThreadN 32 and --limitBAMsortRAM 20000000000 I get the fatal error in the title. If I reduce threads to 16, then mapping completes with no errors. I always used >30 threads with STAR-2.5.4a on the same machine.
What can be the issue due to?
Thanks,

Claire

**Comment by alexdobin** [comment]
Hi Claire,

this is likely to be the OS limiting the max number of open files. Please check 
$ ulimit -n
and set it to a larger number, e.g.
$ ulimit -n 10000

Cheers
Alex

**Comment by ClaireG18** [comment]
Thanks, I'll try that! Cheers
