### ISSUE TITLE
recommend use of build system like autotools or cmake

### ISSUE THREAD

**Issue by kotoroshinoto** [alexdobin/STAR#49]
for instance, users may already have a version of htslib installed which you could detect and link to automatically, as opposed to including it in your source.

it would also ease detection of compilers etc.

**Comment by kotoroshinoto** [comment]
you could easily use customized configure script as well, but build systems tend to be somewhat more adaptable.

**Comment by wookietreiber** [comment]
:+1:

**Comment by wookietreiber** [comment]
I could provide a PR if you'd like.

**Comment by alexf101** [comment]
+1 This would be useful for me too.
