### ISSUE TITLE
'could not open input file exonGeTrInfo.tab' Error when de novo align without gtf file

### ISSUE THREAD

**Issue by wangyugui** [alexdobin/STAR#490]
Hi,

'could not open input file exonGeTrInfo.tab' Error when de novo align without gtf file.

```
index.Log.out
Log.out of  de novo genome index building without existing gtf file
```

```

align.Log.out
Log.out of  STAR alignment
```
[log.zip](https://github.com/alexdobin/STAR/files/2395149/log.zip)

**Comment by alexdobin** [comment]
Hi @wangyugui 

if you want to use counting reads per gene (--quantMode GeneCounts), you would need to specify GTF file at the genome indexing step - otherwise STAR would not know the genes coordinates.

Cheers
Alex

**Comment by wangyugui** [comment]
thanks a lot.
