### ISSUE TITLE
Header of BAM is supressed 

### ISSUE THREAD

**Issue by PernilleYR** [alexdobin/STAR#492]
Hi! 

When aligning an unmapped BAM file the output BAM doesn't have the header of the unmapped BAM, for example if there was some read group they are supressed which is problematic for demultiplexing.

**Comment by alexdobin** [comment]
Hi @PernilleYR 

the BAM header is supposed to be copied - please try the latest version of STAR, and if it still does not work, please send me a short test example (i.e. a uBAM with header and a few reads only).

Cheers
Alex

**Comment by overcookedfrog** [comment]
I experiencing the same problem with v2.7.0f. The read group ID for each read is present, but the read group is not in the header which causes problems with downstream tools. The command I'm running is

```
~/STAR-2.7.0f/bin/Linux_x86_64_static/STAR \
        --readFilesIn sample.unmapped.bam \
        --readFilesType SAM PE \
        --readFilesCommand "samtools view" \
        --genomeDir genome \
        --outSAMtype BAM SortedByCoordinate
```

I've attached an example uBAM: [sample.unmapped.bam.zip](https://github.com/alexdobin/STAR/files/3164458/sample.unmapped.bam.zip)

If I manually supply `--outSAMattrRGline` on the command line (which feels a bit clunky) it adds the read group to the header but add the ID tag twice to each alignment line.

**Comment by alexdobin** [comment]
Hi @overcookedfrog 

to get the BAM header read and output by STAR you need
--readFilesCommand samtools view -h
Without -h, samtools view does not output the header.

Cheers
Alex

**Comment by overcookedfrog** [comment]
Hi @alexdobin thanks for that - it's embarrassingly obvious once pointed out!

**Comment by alexdobin** [comment]
No worries... probably need a better description in the manual.
