### ISSUE TITLE
[bug] Silent error causes false negative chimeric read

### ISSUE THREAD

**Issue by jaudoux** [alexdobin/STAR#495]
Dear @alexdobin ,

I have recently been using STAR to detect chimeric RNA in contigs for the DEkupl projet (https://github.com/Transipedia/dekupl-run).

I faced a problem with my toy test file where I introduced a synthetic chimeric RNA that was not detected by STAR. My command for running STAR (v2.6.1b) is the following : 

```
STAR --runThreadN 1 --genomeDir test_index//star --readFilesIn bug.fastq.tmp --outFileNamePrefix test_STAR/ --twopassMode None --outSAMtype None --outReadsUnmapped None --al
ignIntronMax 100000 --chimSegmentMin 12 --chimJunctionOverhangMin 12 --alignSJDBoverhangMin 10 --chimSegmentReadGapMax 3 --alignSJstitchMismatchNmax 5 -1 5 5
```

First, I tried this FASTA file with a synthetic chimeric RNA : 

```
>fusion
GGAGCATCTCACAGATACGTTTATTCATACCACAAAGTAAACACTATTCAGGTATGTAGTGATGTTCCACGTTCCTGTGGTTGTAGGAGGAGGCCTTTCGGATAGCACCCCCTAGTTCTGCCCCTCATATCTGCTTCCTTGGTCTCTCCTGATTACTTGCTGTTTCTTTTCTTTTTTT
```

The Chimeric.out.junction does record my chimeric RNA (chRNA)

```
22      41282761        -       22      41282940        -       1       0       1       fusion   41282762        102S76M 41282838        102M76S
```

However When the fusion is placed after this particular contig, it seems that a silent error occurs, and the chRNA is not found. Aside from the size of the contig (862nt), nothing looks strange in the input data.

```
>long-contig
GGCGTCCCTTCCCCAATTTCCACAGAGACGTGCTCACCGGCTACATATGTCATGATTCTATGTCCAACCACAGGCCCAACCCTCAGGACAGACCCCGCCACCCCCCTTCTCTGCAGCTCCTGGCAGGGACGGTGCACAGTGGTGCCGTGTGCAGGGGGCCAGCGCAGCCACTGGGCATCTGGGGCAGCGCTGGTCGCCTGGCCACCTCCTTGCTGGGGCCGCTGGGCCTCCGGCCTAGAAGGACAGGAAGCCATCCACCTCAAGGCGCAGGAAGGGGTCCAGCAGGGCCCGGAGCTTCCAGATGGTGGCACGGCTCAGCAGGGGCGGCACCAGCCCCTCGAAGGGCCTGGGGTTCACCATGTACACGTAGGCGACCAGCAGGGTGCCCAGCAGCAGCCTCAGGATCAGCAGCCTACGGGCGGTGGCAGTCAGGGCCAGGGGCACGCAGGGGGCCTGGGGGCTGGGCTCTGCCACACAGTCACCTACCAGAGCTGGCCTGCCAGGCCCTTGGAGCTTTCCAACTTTGGTCTCCCTTTCTGATGGGGAGGGGAGCCCACTCCGAGGGTCCAGGCTGAGGGCGGGGATCCCTGGCTTTGGGAAACCCTCCTCAGACAGGGCTCCCCGCACCGCAGCCCTGGCCCCTTCCTCCTGGACAGGCTCCTGCAGCCACTTTTCAGATGCCCCCCACCCTGGACCTGCTCTGCTGGAGCTCATTTCTCCCCCTTGCCCAAGCAGGGTGCTGGGTGGGGGGCTGGTCTCCAGACCCAGAGTGGGGCGTGGGGGGCTCACTGCCATGCTCGCCATCTGCGGCTCCTTCTTGGCCTGAGTGTGGCACTGGGCCCGCTCCCTGCAGAGGCCTCAC
>fusion
GGAGCATCTCACAGATACGTTTATTCATACCACAAAGTAAACACTATTCAGGTATGTAGTGATGTTCCACGTTCCTGTGGTTGTAGGAGGAGGCCTTTCGGATAGCACCCCCTAGTTCTGCCCCTCATATCTGCTTCCTTGGTCTCTCCTGATTACTTGCTGTTTCTTTTCTTTTTTT
```

Do you have a idea of what is happening ?

Best,
Jérôme.

**Comment by jaudoux** [comment]
@alexdobin I think it definitly comes from the contig size. I replaced the long contig with another one and the chRNA is not detected. But when I shorten the read to 650nt it does work!

**Comment by alexdobin** [comment]
Hi @jaudoux 

if you are aligning long reads, you need to use STARlong executable, otherwise STAR is not going to read the long reads.

Cheers
Alex

**Comment by jaudoux** [comment]
Hi @alexdobin,

Thanks for your answer. Actually I am not trying to align long or short reads but contigs reconstructed from RNA-Seq short reads, and I am mainly interested into finding chimeric RNA. Some of them are quite short (somehow similar to short reads) and other much longer. Do you recommend me to split my set into two subgroups, one that would be analyzed with STARlong and the other one with classic STAR executable?

Best,
Jérôme.

**Comment by alexdobin** [comment]
Hi Jérôme,

I think splitting into 2 subgroups by length is the best approach, with the boundary at 200-300b.
Also, you can try to use STARlong for all reads - it should work for short contigs, but may be a bit lest accurate.

Cheers
Alex

**Comment by jaudoux** [comment]
Hi @alexdobin ,

Thanks a lot, I'll try that and let you know.

Best,
Jérôme.
