### ISSUE TITLE
Killed:9 specifically when trying to align PE reads

### ISSUE THREAD

**Issue by jpropa25** [alexdobin/STAR#496]
I have been using STAR for several years and I'm a huge fan of the tool. I have been running into an issue lately that I was hoping to get some advice on. I have always run STAR on a linux based server, but recently I have been using my own desktop (32GB RAM DDR4; 6-cores with hyperthreading, MacOS; STAR is built from source). I was able to successfully generate genome indices and do an alignment for a single end RNA-seq experiment. I then shifted my focus to a separate experiment that has paired end reads. I rebuilt the indices (the reads in the paired end experiment were longer, so I had to change the argument from --sjdbOverhang 49 to --sjdbOverhang 99). These indices were also generated successfully (log attached). For reference, they are from the mouse mm10 assembly.

Here is where I started running into a problem. When running the alignment (log attached) I keep getting a Killed:9 message. The strange part about this is when I look at the progress log, it seems that the problem is coming after the reads have already been mapped (maybe I'm looking at that incorrectly). I have read that the killed:9 message is most frequently associated with RAM problems, but I was under the impression the most RAM intensive process was the genome build and that performs perfectly fine with default arguments. I have also read that you can adjust the --limitIObufferSize down to 100000000 or even 50000000 to try to reduce RAM; I tried that also to no avail. I'm wondering if I am right about the error being as a result from not enough RAM, if that is common for this step in the alignment, if it is common for this to be an issue specifically for paired end alignments and no single end alignments, and if there is anything I can do about this with respect to tweaking the effective command line. Thanks for your time!

[genomegeneratelog.log](https://github.com/alexdobin/STAR/files/2416779/genomegeneratelog.log)

[SRX1262258_pass.Log](https://github.com/alexdobin/STAR/files/2416780/SRX1262258_pass.Log)

[SRX1262258_pass.Log.progress.log](https://github.com/alexdobin/STAR/files/2416782/SRX1262258_pass.Log.progress.log)

**Comment by jpropa25** [comment]
Alex,

Thanks for the quick response and sorry for my delay in responding. I will download the newer version of STAR and try it with the top command; I will also use the older indices to see if that helps and get back to you.

As for the number of reads, there are just over 28M in the file for the log I posted. That's why I was surprised that it was mapping nearly everything and then being killed.

I will get back to you with the output from the other items.

Best,
Jim

**Comment by jpropa25** [comment]
Alex,

I have installed the more recent STAR 2.6.0c (again, built from source). I've now tried regenerating the genome indices using this newer version (maybe this wasn't necessary if the previous genome indices were generated with 2.6.0a? Nonetheless, I'm trying to get this working from start to finish on this system, so the problem will still remain the same.). Unfortunately I now seem to be having problems even generating the genome. I'm not sure if this is even a STAR issue or if there is something wrong with the way the MacOS is swapping the RAM, but maybe you can provide some insight. The genome generation gets a Killed: 9 message at the inserting junctions into the genome indices step. It seems strange because the physical memory used by STAR at the point of the process being killed is actually low, and seems as if most of it has gone to compressed memory, but the total physical memory used is still 32GB. I've attached the top output from during the inserting junctions process at the beginning of the step as well as right before the Killed:9 message appears here as well as the log. I've also tried limiting the genome generation RAM all the way down to 24GB to solve this (I'm not sure if that will even work for the mouse genome generation), to no avail.

One additional question I have is are there processes that won't fall under "STAR" in the processes list that are being run by the program? The reason I ask this is that before I start a STAR run I have around 4GB of physical memory being used by MacOS. However, as soon as the STAR run starts, the physical memory used seems to jump to the amount being used by STAR + 7GB (about 3GB unaccounted for). Is that normal for STAR? Thanks for the help, and sorry if this is more of a system problem than it is a STAR problem.


Best,
Jim

[Log.out.txt](https://github.com/alexdobin/STAR/files/2442401/Log.out.txt)

![screen shot 2018-10-03 at 10 02 51 am](https://user-images.githubusercontent.com/14877598/46416451-8e362380-c6f5-11e8-8ed1-c376b20540e3.png)
![screen shot 2018-10-03 at 10 05 00 am](https://user-images.githubusercontent.com/14877598/46416466-94c49b00-c6f5-11e8-89b2-217f8c425e9f.png)

**Comment by alexdobin** [comment]
Hi Jim,

sorry for belayed reply, I was trying to find a way to test limited memory configurations as I do not have access to a 32GB machine. The best I could was setting ulimit -v to 32G .
So I think that 32G should be enough to generate the genome, but barely. I need to clean up my code to reduce it well below 32G which is theoretically possible.
One parameter you can try is --limitSjdbInsertNsj 300000 to reduce the extra RAM required to insert the junctions. If it does not work, I would recommend indexing on a machine with RAM>32GB. Mapping should be fine with 32GB. Yet another option to completely avoid the RAM problems is to sparsify the suffix array with --genomeSAsparseD 2 .

Cheers
Alex
