### ISSUE TITLE
Cufflink runtimes super long after mapping with STAR

### ISSUE THREAD

**Issue by yukiriiin** [alexdobin/STAR#497]
Hi folks,

I have been working on sequencing analysis for the past 2 years. We started with tophat2 pairing with cufflinks and it was always working fine. Except when we get more and more samples, tophat2 is kind of slow at mapping. So we tried to switch to STAR and pair with cufflinks (we like the FPKM normalization done by cufflinks. We have tried salmon and the TPM by salmon sometimes seems not accurate - very few reads map to a gene, with like 200 TPM. So we decided to stick with cufflinks. However, here is the problem:

Initially we run cufflink with normal STAR commands, and cufflink will take forever for a simple RNA-seq sample (20-30 mil reads) - actually it never finish after a week. So I did some search online, and people were seeing some improvements in cufflink speed by giving the following commands:

```
--outFilterIntronMotifs RemoveNoncanonical
--outSAMstrandField intronMotif
```
these 2 were given as suggested in manual

```
--outFilterScoreMinOverLread 0.3
--outFilterMatchNminOverLread 0.3
```
And this do solve some of the problems - at least I can finish cufflink for a 30 mil reads sample in 7 hours now... (i7-6700, running with 6 threads. or Xeon 2.2GHz frequency with 14 threads. They are actually similar time).

Problems now is, with deeper sequencing, or paired-end sequencing, etc, it takes forever to finish cufflinks (the human sample I am running now took about 3 days - 72 hours for 1 sample, at 16 threads) and we cant afford that time any more (I have 50+ samples waiting...)

Is there some suggestions in speed up STAR paired cufflink pipeline? Thanks!

**Comment by alexdobin** [comment]
Hi @yukiriiin 

are you running Cufflinks in quantification only mode, or assembling transcripts?
The latter is especially prone to hang up on loci with a large number of reads.

I would not recommend using
--outFilterScoreMinOverLread 0.3
--outFilterMatchNminOverLread 0.3
as these will result in more poor quality mappings and will not reduce Cufflinks load.

Here are a couple of options I would suggest:

1. --alignEndsType EndToEnd
this will prohibit soft-clipping of the alignments making them look more like TopHat's

2. --alignIntronMax 100000
reduces the max allowed unannotated intron length

Cheers
Alex

**Comment by yukiriiin** [comment]
Hi Alex!

really nice talking to you!
I'll try the EndToEnd option. 
I do not need the assembly actually, but I think it is running that in cufflinks. That is also why it is so slow. I have been looking a lot about cufflinks and people are suggesting using stringtie instead. I have tried it and it is really way more faster. Is it accurate comparing to cufflinks in your opinion? Since string tie finish in 5 min per sample, I am thinking switching everything over.

Thanks,
Andy

**Comment by yukiriiin** [comment]
Hi Alex,

We have tried Salmon already. As you said, we thought for our quantification reason, we only need Salmon kind of quantification tool. However, in Salmon, comparing with STAR+cufflink (our old pipeline), we found genes with 200TPM in Salmon, and <1TPM with STAR+cufflink. By looking at the bam file in IGV, we believe STAR+cufflink is accurate (not much reads in that gene at all). That is why we kinda do it in the slower way: map it fully, then quantify with one of the assembly tool, for accuracy. The FPKM given by cufflinks and stringtie in quantification mode are still a little off with eachother. That is why I asked, like if the quantification by stringtie is more accurate. I guess I have to figure it out myself then lol. Thanks a lot for kindly answering my questions.

Thanks,
Andy

**Comment by alexdobin** [comment]
Hi Andy,

have you tried to run Salmon with alignment input (i.e. transcriptome BAM file).
The standard Salmon mode is the pseudo-alignment (with FASTQ input) that does produce somewhat different results than alignment. 

Compared to other quantification software (Cufflinks, eXpress, Sailfish, kallisto), RSEM produced the most accurate results in my experience - but I have not done comparisons with StringTie.

Cheers
Alex

**Comment by yukiriiin** [comment]
Hi Alex,

Yes, I have done Salmonn with the BAM file from STAR. It looks mostly identical to cufflinks. But I did a DE analysis between them and pull out the 600ish genes that are super different. That is when I found the problem. I'll try RSEM!
So far StringTie passed all quality checks (like no super over expressed genes with 100k TPM, etc. ). 

Thanks,
Andy

**Comment by alexdobin** [comment]
Hi Andy,

this is interesting, I was not expecting such a big difference between alignment-based quantifications. They used similar generative models. Looking forward to your RSEM assessment. :)

Thanks!
Alex
