### ISSUE TITLE
Not to output SAindex and SA file

### ISSUE THREAD

**Issue by corn23** [alexdobin/STAR#498]
Hi,

When I try to generate genome indexes with `--runMode genomeGenerate`, I found two huge files  generated `Genome` and `SA`. It's a little bit wield because the input files are quite small so I have no idea why so large files could be generated. 

Is it necessary  to keep these files?(I am creating test files. I want to get the alignment files from the man-made artificial `fasta` file and `reads` file with STAR) Is it possible not to output them? I try to add option `--sjdbInsertSave Basic` but didn't work.

Thanks!
Jiayu

**Comment by alexdobin** [comment]
Hi Jiayu,

please send me the Log.out file.

Cheers
Alex

**Comment by corn23** [comment]
[Log.out.txt](https://github.com/alexdobin/STAR/files/2435905/Log.out.txt)

Thanks!

Regards,
Jiayu

**Comment by alexdobin** [comment]
Hi Jiayu,

for a very small genome like yours, you would need to scale down --genomeChrBinNbits to 10 (chromosome padding) and --genomeSAindexNbases 3 (SAindex k-mer size). These should reduce the genome indexes sizes.
Also please switch to 2.6.1b, as 2.6.0a was buggy and is marked as pre-release.

Cheers
Alex

**Comment by corn23** [comment]
Thanks！:)

Jiayu
