### ISSUE TITLE
--quantMode GeneCounts always gives ReadsPerGene.out.tab with zero counts

### ISSUE THREAD

**Issue by rjg2186** [alexdobin/STAR#499]
@alexdobin 
When using --quantMode GeneCounts with paired-end read files, the gene counts is always zero. The GTF format and all other files are in correct format.

GTF file contents

```
NC_000932.1     RefSeq  exon    4       76      .       -       .       transcript_id "rna59917"; gene_id "gene37964"; gene_name "trnH";
NC_000932.1     RefSeq  CDS     383     1444    .       -       0       transcript_id "gene37965"; gene_id "gene37965"; gene_name "psbA";
NC_000932.1     RefSeq  exon    1717    1751    .       -       .       transcript_id "rna59918"; gene_id "gene37966"; gene_name "trnK";
NC_000932.1     RefSeq  exon    4311    4347    .       -       .       transcript_id "rna59918"; gene_id "gene37966"; gene_name "trnK";

```
command used
`STAR --runMode alignReads --runThreadN 10 --genomeDir ./genomeDir --genomeFastaFiles genome.fasta --sjdbGTFfile genomic.gtf --quantMode GeneCounts --readFilesIn R1.fastq R2.fastq`

**Comment by alexdobin** [comment]
Hi @rjg2186 

please send me the Log.out file.
This is likely to be a problem with annotations such as different chromosome names from the FASTA file.
You can get a second opinion running htseq-count or featureCounts on the Aligned.out.bam file.

Cheers
Alex

**Comment by rjg2186** [comment]
Hi @alexdobin 
Thanks for the reply.
The Log file in uploaded below.
[Log.out.txt](https://github.com/alexdobin/STAR/files/2434742/Log.out.txt)

I have sorted the Aligned.out.sam based on coordinates and used htseq-count with same GTF file and i do get gene counts in the output.

Thanks

**Comment by alexdobin** [comment]
Hi @rjg2186 

something strange happened in this run - you requested 10 threads but for some reason 90 threads were used. Please try to use the pre-compiled executable from the 2.6.1b release
[https://github.com/alexdobin/STAR/releases/tag/2.6.1b]( https://github.com/alexdobin/STAR/releases/tag/2.6.1b)
and send me the Log.out file.

Cheers
Alex

**Comment by rjg2186** [comment]
Hi @alexdobin 

Please find attached the Log.out file for the same input file with STAR-2.6.1b
[Log.out.txt](https://github.com/alexdobin/STAR/files/2437282/Log.out.txt)

Thanks

**Comment by alexdobin** [comment]
Hi @rjg2186 

aah, I figured out what the problem was, I think.
**In the mapping step, you should not specify --genomeFastaFiles genome.fasta** since you already did it at the genome indexing step. If you specify a FASTA file at the mapping step, it's added to the FASTA specified at the indexing step. In your case, it duplicated the genome, so all reads became multimappers and thus not counted.

Cheers
Alex
