### ISSUE TITLE
Makefile wrongly assumes presence of vim

### ISSUE THREAD

**Issue by kotoroshinoto** [alexdobin/STAR#50]
Makefile:71: Depend.list: No such file or directory
xxd -i parametersDefault > parametersDefault.xxd
/bin/sh: xxd: command not found

is this use of xxd necessary? What is it doing exactly?

**Comment by kotoroshinoto** [comment]
i'm not 100% sure this is provided by vim source, but i'm trying to build it at the moment, as asking yum what provides xxd returns vim related package name.

**Comment by wookietreiber** [comment]
Yeah, I think this is really weird, too. There should be a more elegant way than to depend on an editor.

**Comment by kotoroshinoto** [comment]
wasn't able to compile vim successfully first time around, i'll probably have to tinker with the build settings or chase down dependencies. the system we use for analysis is a cluster and I've no sudo access.

**Comment by alexdobin** [comment]
I have added the parametersDefault.xxd to the distribution. This file is not system dependent, so there is no need for user  to re-build it. Please get it from the github master.
Cheers
Alex

**Comment by wookietreiber** [comment]
Thanks. I guess, this issue can be closed now.
