### ISSUE TITLE
stop in the step .... processing annotations GTF. how to set --genomeChrBinNbits in wheat

### ISSUE THREAD

**Issue by 909089617xx** [alexdobin/STAR#503]
when i use STAR to generate index.the STAR always stop in the processing annotation GTF.
My search on the Internet turned out to be due to memory, so I set the parameter, --limitGenomeGenerateRAM 40000000000, according to the error message.
However, I still can't run it successfully.
Later,I set --genomeChrBinNbits 16 .(estimated according to the method you gave ), but it still doesn't work. What I use is wheat genome(13Gb)

**Comment by alexdobin** [comment]
Hi @909089617xx 

how much RAM do you have available?

Cheers
Alex

**Comment by 909089617xx** [comment]
Thank you very much for your quick reply.But I'm sorry I don't know much about our server.
but when i set the  --limitGenomeGenerateRAM 400000000000(add another 0 in previous size) there will a warning.The warning means that the program will terminate automatically if this value is not reached.
Someone had run STAR on our server before and she said it's going to use almost all of the memory for our server and we can set  160 threads.
thanks a lot.

**Comment by alexdobin** [comment]
Hi @909089617xx 

please try to set --limitGenomeGenerateRAM 80000000000
and send me the Log.out file if it still does not work.

Cheers
Alex

**Comment by 909089617xx** [comment]
Hi, Alex
The problem in generating index was accidentally solved.But now when I use STAR to alignment ,there is a same problem.The STAR always stop in the processing annotation GTF.
This is the Log.out file.

thanks a lot.
Cheers
Alex
[SiPAS-10am1Log.out.txt](https://github.com/alexdobin/STAR/files/2593709/SiPAS-10am1Log.out.txt)

**Comment by 909089617xx** [comment]
HI,Alex
I really need help.This is the error message.
![image](https://user-images.githubusercontent.com/33317454/48762797-c534b880-ece6-11e8-9677-3517a230e7dd.png)

**Comment by alexdobin** [comment]
Hi @909089617xx 

sorry for belayed reply.
Since you included the annotations in the genome generation step, you do not need to included them again in the mapping step - hopefully this will resolve the problem.
Also, I would generally recommend converting the GFF file into GTF (say with gffread from Cufflinks package).

Cheers
Alex

**Comment by 909089617xx** [comment]
Hi,Alex
Thank you very much for your reply.But i don not think that's the main problem.I have try all methods i can do to go through the process annotation GTF step, but it did not work. such as solve core dumped、regenerating index(it is also stop in the process annotation GTF step)、use GTF file 、use other STAR version and so on.
Is that what you mean?
![image](https://user-images.githubusercontent.com/33317454/48873318-27490700-ee28-11e8-8e18-c86c836cd16f.png)
but it does not work .
And this one 
![image](https://user-images.githubusercontent.com/33317454/48873339-40ea4e80-ee28-11e8-8331-f6491cd37bc0.png)
but i get an empty sam file.
I really really confusing about it.

**Comment by alexdobin** [comment]
Hi @909089617xx 

let's approach it in a systematic way, and change one thing at a time.
The first step would be to check the first few lines of your read fastq file, i.e.:
$ head -n 20 /path/to/file.fq
Next, please run STAR with mostly default parameters, i.e.
$ /path/to/STAR --genomeDir ... --readFilesIn ... --runThreadN 10
and check the Log.final.out file for mapping statistics, and SAM file for output alignments.
If this does not work, please send me the Log.out file from this run.

Cheers
Alex

**Comment by 909089617xx** [comment]
Hi,Alex
Fist, I do not think this is some wrong with my fq file.
![image](https://user-images.githubusercontent.com/33317454/48911641-3a061f00-eeae-11e8-9107-2dc13d0b722d.png)

but the result
![image](https://user-images.githubusercontent.com/33317454/48912117-c107c700-eeaf-11e8-9015-aa35253595d5.png)
![image](https://user-images.githubusercontent.com/33317454/48912159-dc72d200-eeaf-11e8-811c-643d9fa6d4f4.png)
[Log.out.txt](https://github.com/alexdobin/STAR/files/2608637/Log.out.txt)
I'm very sad about this result
Cheers
Jun

**Comment by alexdobin** [comment]
Hi Jun,

this looks like a problem with the fastq file.
Let's try to map just 5 first reads with this extra parameter --readMapNumber 5 
If it does not work, please cut the first 5 reads with
$ head -n20 file.fq > r5.fq
and try to map r5.fq.
If it still does not work, please send me this r5.fq file.

Cheers
Alex

**Comment by 909089617xx** [comment]
Hi,Alex
Thank you very much for your reply.
when i use the fllowing command. I can run it but i get a empty sam file.
![image](https://user-images.githubusercontent.com/33317454/48925348-ba07a580-eefd-11e8-8fa1-7998359df352.png)
and i also use this 
![image](https://user-images.githubusercontent.com/33317454/48925397-14a10180-eefe-11e8-959e-55b49069ec05.png)
this is the sam and log.out file.
[Aligned.out.sam.txt](https://github.com/alexdobin/STAR/files/2609473/Aligned.out.sam.txt)
[Log.out.txt](https://github.com/alexdobin/STAR/files/2609474/Log.out.txt)

**Comment by 909089617xx** [comment]
Hi,Alex
At present, I find one of the problem in my process.There is something wrong with my gff3 file. now i can use it to generate the index successfully.But i can not alignment.i can only get same empty sam file.
![image](https://user-images.githubusercontent.com/33317454/48941615-38446600-ef57-11e8-9a4b-f651e2e3e51f.png)
Cheers
Jun

**Comment by alexdobin** [comment]
Hi Jun,

it's good that the process completed with 5 reads. Empty SAM is likely due to none of the 5 reads mapped, you can check it in the Log.final.out file. 
The problem is somewhere in the full fastq file. Please try to increase --readMapNumber to 1000,10000, ... until you hit the number where the problem occurs. Then you can use binary search to find which read is problematic.

Cheers
Alex

**Comment by 909089617xx** [comment]
Hi,Alex
When I increase the reads number ,it will generate the error.Like the following picture.
![image](https://user-images.githubusercontent.com/33317454/48963186-6d3cd100-efc8-11e8-88a0-3ceed13439e7.png)
But i can not find some error in my fq file .All of the reads ID are start whith @. Do you feel following circumstance will report an error?
![image](https://user-images.githubusercontent.com/33317454/48963206-cf95d180-efc8-11e8-88ff-dd5be4576d4e.png)

**Comment by 909089617xx** [comment]
Hi,Alex,
Thank very much for you taking the time to answer my questions.There were a lot of problems when I ran my code, which eventually led to this incredible bugs.The coincidence makes incredible.But finally i solve them.Thanks a lot.
Cheers
Jun

**Comment by alexdobin** [comment]
Hi Jun,

happy to hear that you resolved the problem.

Cheers
Alex
