### ISSUE TITLE
Reproducing the Uniquely mapped reads number from Log.final.out

### ISSUE THREAD

**Issue by hbeale** [alexdobin/STAR#507]
I'm trying to compare results between tools. The tools use different metrics to report the number of uniquely mapped reads, so I'm trying to apply the STAR metric to output from other tools. However, I haven't been able to get samtools to reproduce the number STAR reports as "Uniquely mapped reads number" from Log.final.out. Based on [this comment](https://github.com/alexdobin/STAR/issues/282#issue-238862360), I tried to reproduce the "Uniquely mapped reads number" from Log.final.out with samtools as follows

`samtools view $f | awk '/NH:i:1\t/' | wc -l # 13212994`

For this sample, Log.final.out reported 6,606,511 uniquely mapped reads. The samtools + awk result is 13,212,994.   The discrepancy is only 14 reads (13212994/2 = 6,606,497). I'm pretty confident that I'm on the right track, but I'd like to be precise. Is there a way to use a third party tool to reproduce the "Uniquely mapped reads number" value reported in Log.final.out?

**Comment by alexdobin** [comment]
Hi @hbeale 

I think the discrepancy may come from the reads for which only one mate of the pair is mapped. The unmapped mate will be output with NH:i:0. I think the most general (albeit slow) way to count the unique reads is:
$ samtools view $f | awk '/NH:i:1\t/ {print $1} ' | sort | uniq | wc -l 

You can avoid sorting step if you know that the aligner outputs the mates consecutively. This is true for STAR's Aligned.out.bam but not for Aligned.SortedByCoordinate.bam.

Cheers
Alex

**Comment by hbeale** [comment]
Hi @alexdobin--

That worked perfectly. Thanks for the quick reply!

Best,
Holly
