### ISSUE TITLE
compressing Unmapped reads on the fly

### ISSUE THREAD

**Issue by splaisan** [alexdobin/STAR#510]
Hi Alex,

Is it possible to tweek
`--outReadsUnmapped Fastx
`
in order to compress with bgzip rather than saving plain text fastq for those reads. They tend to take space and I have now to do a post cleanup to reduce them.

Thanks
S

**Comment by alexdobin** [comment]
Hi Stephane,

this is not possible from within STAR, but you can try to use fifo files and run gzip (or bgzip) in parallel with mapping:
$ mkfifo Unmapped.out.mate1 Unmapped.out.mate2
$ cat Unmapped.out.mate1 | gzip > Unmapped.out.mate1.gz &
$ cat Unmapped.out.mate2 | gzip > Unmapped.out.mate2.gz &
$ STAR ...

Cheers
Alex

**Comment by splaisan** [comment]
This is brilliant. I did not realize you could create a fifo in advance, very elegant indeed. I should use fifo more often.
Thanks as always for your support
