### ISSUE TITLE
`exitWithError()` is not thread safe

### ISSUE THREAD

**Issue by paulmenzel** [alexdobin/STAR#514]
The method `exitWithError()` is not thread safe.

For example called from `BAMbinSortByCoordinate()`, run by each thread, the `delete P.inOut;` causes the descriptor to be closed, and the other threads trying to access it, fail.

**Comment by alexdobin** [comment]
Hi Paul,

well noted - thanks for pointing this out!
I will make a fix in the next release.

Cheers
Alex

**Comment by alexdobin** [comment]
Hi Paul,

I got it fixed in 2.6.1d, thanks a lot again.

Cheers
Alex
