### ISSUE TITLE
`ifstream.tellg()` returns -1 on error

### ISSUE THREAD

**Issue by paulmenzel** [alexdobin/STAR#516]
Currently, the code assumes, that `ifstream.tellg()` return non-negative values.

    source/BAMbinSortByCoordinate.cpp:        uint s1=bamInStream.tellg();
    source/Genome.cpp:        size=(uint) stream.tellg();
    source/Genome_genomeGenerate.cpp://         nSAbyte=(uint) oldSAin.tellg();

[Documentation][1]:

> ### Return Value
>
> The current position in the stream.
> 
> If either the stream buffer associated to the stream does not support the operation, or if it fails, the function returns -1.
> 
> streampos is an fpos type (it can be converted to/from integral types).
>
> […]

[1]: http://www.cplusplus.com/reference/istream/istream/tellg/

**Comment by alexdobin** [comment]
Hi Paul,

added checks in 2.6.1d, thanks a lot!

Cheers
Alex
