### ISSUE TITLE
inconsistent results between STAR & BLAT (no gap)

### ISSUE THREAD

**Issue by snowlover** [alexdobin/STAR#519]
Hi Alex,

I'm encountering an weird issue where STAR (2.6.1a) and BLAT has very different mapping results. when using BLAT, it clearly perfectly matched to the hg38 genome, while STAR says 2 mismatches (nM:2) for both paired ends of the fragment. Also, one read mapped to the same position as BLAT, but the other to a different position.

Could you please help ?

commands used were as below and input files attached. thank you very much.

```
STAR --genomeDir hg38-ref_genome.fa.star.idx  --outReadsUnmapped None  --chimSegmentMin 12  --chimJunctionOverhangMin 12  --alignSJDBoverhangMin 10  --alignMatesGapMax 100000  --alignIntronMax 100000  --alignSJstitchMismatchNmax 5 -1 5 5  --runThreadN 10 --outSAMstrandField intronMotif  --outSAMunmapped Within  --outSAMtype BAM Unsorted  --readFilesIn x1.fq x2.fq  --outSAMattrRGline ID:GRPundef  --chimMultimapScoreRange 10 --chimMultimapNmax 10 --chimNonchimScoreDropMin 10  --peOverlapNbasesMin 12 --peOverlapMMp 0.1  --genomeLoad NoSharedMemory  --twopassMode Basic

blat hg38-ref_genome.fa  x.fa  output.psl
```

[x.fa.txt](https://github.com/alexdobin/STAR/files/2568571/x.fa.txt)
[x.star.txt](https://github.com/alexdobin/STAR/files/2568572/x.star.txt)
[x1.fq.txt](https://github.com/alexdobin/STAR/files/2568573/x1.fq.txt)
[x2.fq.txt](https://github.com/alexdobin/STAR/files/2568574/x2.fq.txt)
[x.psl.txt](https://github.com/alexdobin/STAR/files/2568581/x.psl.txt)

**Comment by alexdobin** [comment]
Hi @snowlover 

I cannot reproduce the problem, STAR seems to map to the same loci as BLAT with your parameters:
UNC12-SN629:367:C3U9RACXX:4:2112:10939:58525    99      chr11   2131617 255     48M     =       2131735 166     TGCATGTGTGTGCTGTGTGCTGTGTTCATGTGTGTGCTGTGTGTGCGT      @CCFDFBDHHHFHHGHHBGHIDHBFFHFIJEHIHFHIGIGHFHGGII6        NH:i:1  HI:i:1AS:i:94 nM:i:0
UNC12-SN629:367:C3U9RACXX:4:2112:10939:58525    147     chr11   2131735 255     48M     =       2131617 -166    CGTGTGTGTGCTGTGTGTGCATGTGTGTGCTGTGTCTTTGTGTGTGTG      5HHF?IIIHHEE>EFBGGIIGJJJIIJIIGIJJJIFAHHHFFFFFC@C        NH:i:1  HI:i:1AS:i:94 nM:i:0

What version of STAR are you using? What FASTA file did you use to generate the genome (by any chance, maybe you used repeat-masked FASTA - this locus seems to contain repeated sequence)?

Cheers
Alex

**Comment by snowlover** [comment]
Hi Alex,

as wrote in the question, I used version '2.6.1a'. i used hg38 (the same reference file for both STAR and BLAT), and will repeat-masking results in 'N' bases or just lower-case letter bases ? i think maybe its due to the repeats, and i should use the latest STAR version ...

**Comment by alexdobin** [comment]
Hi @snowlover 

sorry, missed the version in the first post. 2.6.1a should be fine, but just in case please try 2.6.1c (or 2.6.1d I will release tomorrow), and also re-generate the genome with the same version.

Cheers
Alex

**Comment by snowlover** [comment]
Thanks, Alex
