### ISSUE TITLE
unexpected gzip error

### ISSUE THREAD

**Issue by nberlow** [alexdobin/STAR#521]
Hello, 

I recently upgraded to 2.6.1c to work with STAR-Fusion 1.5.0. I'm running the following command to align the fastq files to my reference genome and then call STAR-Fusion. I run both separately so I can also quantify using the same alignment.

The command is:

	${starDir}/STAR --genomeDir $genomeDir --readFilesIn $seqFiles --readFilesCommand zcat -runThreadN $threads \
	--twopassMode Basic --chimSegmentMin 12 --chimJunctionOverhangMin 12 --alignSJDBoverhangMin 10 \
	--alignMatesGapMax 100000 --alignIntronMax 100000 --chimSegmentReadGapMax 3 --alignSJstitchMismatchNmax 5 -1 5 5 \
	--chimOutJunctionFormat 1 --outSAMtype BAM Unsorted --outSAMunmapped Within --outFilterMultimapNmax 1 --quantMode TranscriptomeSAM \
	--outTmpDir ${sampleName}_STARtmp --outFileNamePrefix $sampleName.

I'm now running into issues with alignment ending quickly, seemingly not reading anything from the input files (gzipped fastq files).

Early in the alignment step, the following errors now appear:

gzip: invalid option -- 'u'
Try `gzip --help' for more information.
Try `gzip --help' for more information.
Nov 12 11:08:00 ..... started mapping
Nov 12 11:08:03 ..... finished successfully

I've tried switching to --readFilesCommand gunzip -c, with no change in error.

Any ideas what might be wrong?

Thanks!

**Comment by paulmenzel** [comment]
Am 12.11.18 um 20:15 schrieb nberlow:

> I recently upgraded to 2.6.1c to work with STAR-Fusion 1.5.0. I'm
> running the following command to align the fastq files to my
> reference genome and then call STAR-Fusion.
So with what version did it work? Could you please try the latest 
version from the master branch, and, if it is still reproducible, bisect 
the issue, cf `git bisect`, to find the commit introducing the regression?

**Comment by nberlow** [comment]
Using the newest master branch code did seem to fix this bug, thank you. As an FYI, the version that was not working was the version I downloaded from here:

https://github.com/alexdobin/STAR/releases

The releases link for 2.6.1c may not be up to date.

Thanks for your help!

-Noah

**Comment by kernco** [comment]
I just had the same problem with the same source: I accidentally put a single dash instead of a double dash in the argument following "--readFilesCommand zcat". So this isn't an issue with STAR itself, but maybe it could provide a more useful error message? Though it might be difficult to do that while maintaining the capability of having readFilesCommand support a command with arguments.

**Comment by alexdobin** [comment]
Exactly, single dash could be a parameter for the command, e.g.
--readFilesIn gunzip -c
