### ISSUE TITLE
Could we get sorted BAM with bai index

### ISSUE THREAD

**Issue by splaisan** [alexdobin/STAR#522]
Unless I missed it, It would be cool to have the first BAM header line telling it is coordinate sorted  (now: @HD     VN:1.4) and the corresponding .bai samtools index created on the fly. We now need to add the header row1 and index with third party tools.
Thanks

**Comment by alexdobin** [comment]
Hi Stephane,

if you use --outSAMtype BAM SortedByCoordinate
it should add the sorted tag:
@HD     VN:1.4  SO:coordinate
Please let me know if it does not work.

I am reluctant to include samtools index creation in STAR, as this is really a separate operation (even samtoools does it *after* sorting), and it usually does not take that much time.

Cheers
Alex
