### ISSUE TITLE
STAR fails on paired files where some reads have been emptied by cutadapt

### ISSUE THREAD

**Issue by splaisan** [alexdobin/STAR#523]
Is it possible to tell STAR to ignore read pairs (or empty read of a pair) when they are present or should I use cutadapt with '-m X' to avoid smaller than X read pair in which case which is a good value for X coming from reads of 75 to 150 bases after cutadapt which I will align to index of 75
Thanks

**Comment by alexdobin** [comment]
Hi Stephane,

STAR will complain about too short read length for empty reads, so you need to tell cutadapt to remove these pairs (both mates!). I would remove pairs for which one of the mates is <15b.

Cheers
Alex

**Comment by splaisan** [comment]
Hi Alex,

It was the snakemake wrapper asking for Unsorted (I overlooked it)
I added an extra module for sorting and indexing using picard to continue where the STAR wrapper ended
I also fixed the emptiness issue by requiring -m 50 in the cutadapt command to forget about shorter pairs (will try 15 another time to try to preserve more data)

Thanks for your support
