### ISSUE TITLE
STAR 2-pass alignment

### ISSUE THREAD

**Issue by xiaoshenyin** [alexdobin/STAR#524]
Hello,

In the GATK RNAseq variant calling pipeline, there are four steps for alignment using STAR:

1) STAR uses genome index files that must be saved in unique directories. The human genome index was built from the FASTA file hg19.fa as follows:

genomeDir=/path/to/hg19
mkdir $genomeDir
STAR --runMode genomeGenerate --genomeDir $genomeDir --genomeFastaFiles hg19.fa\  --runThreadN <n>

2) Alignment jobs were executed as follows:

runDir=/path/to/1pass
mkdir $runDir
cd $runDir
STAR --genomeDir $genomeDir --readFilesIn mate1.fq mate2.fq --runThreadN <n>

3) For the 2-pass STAR, a new index is then created using splice junction information contained in the file SJ.out.tab from the first pass:

genomeDir=/path/to/hg19_2pass
mkdir $genomeDir
STAR --runMode genomeGenerate --genomeDir $genomeDir --genomeFastaFiles hg19.fa
--sjdbFileChrStartEnd /path/to/1pass/SJ.out.tab --sjdbOverhang 75 --runThreadN <n>

4) The resulting index is then used to produce the final alignments as follows:

runDir=/path/to/2pass
mkdir $runDir
cd $runDir
STAR --genomeDir $genomeDir --readFilesIn mate1.fq mate2.fq --runThreadN <n>

In step 3), SJ.out.tab files generated from step 2) are used to create a new index for step 4). Since I did paired-ended sequencing for multiple samples, I have multiple pairs of fastq files. I did step 2) for each pair of fastq files (i.e. each sample), so many SJ.out.tab files are generated, each for one sample. For step 3), I have a question as below:

(a) should I input all SJ.out.tab files for all samples at one time to generate only one new index to be used for multiple separate analyses described in step 4) for all samples; or

(b) should I input just one SJ.out.tab file each time to generate one unique new index for each sample (i.e. multiple new indexes for multiple pairs of fastq files, each new index for each pair) and use the corresponding new index for corresponding samples/pairs of fastq files in step 4)?

Thanks.

**Comment by alexdobin** [comment]
Hi @xiaoshenyin 

both possibilities are valid, the "global" SJ.out.tab and the local one. There is a discussion about it in manual :) and on many posts here: [https://groups.google.com/forum/#!searchin/rna-star/2-pass%7Csort:date](https://groups.google.com/forum/#!searchin/rna-star/2-pass%7Csort:date)

The global approach is theoretically more accurate, however, in practice, it often requires careful filtering of the junctions, as there are might be too many novel junctions when they are collected from all samples. Without this filtering, the 2nd pass may slow down, and you may get more multimapping reads.

The local approach can be done automatically with --twopassMode Basic option - i.e. you do not need to re-generate the genome yourself.

Cheers
Alex

**Comment by xiaoshenyin** [comment]
Thanks.
