### ISSUE TITLE
Genome Reference Loading Time is Large 

### ISSUE THREAD

**Issue by kushdtu** [alexdobin/STAR#526]
@alexdobin 
Hey guys,

I am using AWS ec2 m4.4xLargemachine which have 64GB of RAM and 16 CPU's with 500GB volume to run STAR in it.

What I found that loading time of genome reference into memory for the first time is quite large ~45 mins in my case.
After the first run, it doesn't take that much time which makes sense because of Linux caching.

What do I want to know?
Is there any way to improve the loading time of genome reference even for the first time!

Any kind of help will be much appreciated.

**Comment by alexdobin** [comment]
Hi Kushal,

I think this is a problem with a slow "disk" I/O on the AWS machine.
Are you loading the genome from a "local" SSD disk, or EBS?
Have you checked how long it takes to just copy the files from EBS to a local disk?
If for some reason this is faster, you could copy the files first, and then load the genome from the local disk.

Cheers
Alex

**Comment by kushdtu** [comment]
Hi @alexdobin 

I am was using EBS volume with the ec2 machine. You were right that it was a problem of slow "disk" I/O of aws machine.

Loading time has been reduced to 4 to 5 mins for 25-30GB of genome reference when I used EFS(Elastic file system) with my ec2 machine. 

Will keep you guys posted if I am able to improve it further.

You can close this issue and thanks for your help :)

**Comment by alexdobin** [comment]
Hi Kushal,

thanks a lot for sharing your solution,

Cheers
Alex
