### ISSUE TITLE
Mapping issue with STAR

### ISSUE THREAD

**Issue by sagnikbanerjee15** [alexdobin/STAR#527]
Hello Alex,

I currently working with a genome fasta file which has 264085 references. The length of the genome is 587450705. Plugging those numbers in, I calculated the value of genomeSAindexNbases as 13 and genomeChrBinNbits as 11. The genome index generation step was completed without any errors. I have attached the Log.out file. I proceeded to map paired ended reads which resulted in an error. Here is what I got from the STAR run.

EXITING because of FATAL error, could not open file /work/LAS/rpwise-lab/sagnik/quality_check_genome_annotations/data/STAR_index_combined_all_reads_transcripts/sjdbInfo.txt
SOLUTION: check that the path to genome files, specified in --genomeDir is correct and the files are present, and have user read permsissions

Please note that I do not have any GTF file associated with the genome. The command I used for mapping the reads is - 
nohup STAR  --runThreadN 20  --genomeDir /work/LAS/rpwise-lab/sagnik/quality_check_genome_annotations/data/STAR_index_combined_all_reads_transcripts  --readFilesIn /work/LAS/rpwise-lab/sagnik/maize_gene_annotations/data/raw_fastq/SRR5488463_adapter_trimmed_1.fastq  --outFileNamePrefix /work/LAS/rpwise-lab/sagnik/quality_check_genome_annotations/data/STAR_SRR5488463_ 

Thank you.

[Log.out.txt.zip](https://github.com/alexdobin/STAR/files/2609488/Log.out.txt.zip)

**Comment by alexdobin** [comment]
Hi Sagnik,

please send me the Log.out file from the mapping run.
Also, please try the latest STAR patch, 2.6.1d.

Cheers
Alex

**Comment by sagnikbanerjee15** [comment]
Hi Alex,

Thanks for your reply. I will try out the patch. Please find attached the log file from the mapping.
Could you also please explain the difference between Linux_x86_64 and Linux_x86_64_static?

Thank you.
[STAR_SRR5488454_Log.out.zip](https://github.com/alexdobin/STAR/files/2613065/STAR_SRR5488454_Log.out.zip)

**Comment by sagnikbanerjee15** [comment]
Hi Alex,

I tried with the new patch but I keep getting the same error. Please let me know what other approaches I can take.

Thank you.

**Comment by alexdobin** [comment]
Hi Sagnik,

sorry for belayed reply.
Have you re-generated the genome with 2.6.1d and re-map with 2.6.1d? I cannot reproduce this problem in my tests.

Cheers
Alex
