### ISSUE TITLE
BAMoutput.cpp:27:BAMoutput: exiting because of *OUTPUT FILE* error

### ISSUE THREAD

**Issue by jeffinrockey** [alexdobin/STAR#529]
Dear Alex,
Could you please check on the below  in 2.6.1d.

_BAMoutput.cpp:27:BAMoutput: exiting because of *OUTPUT FILE* error: could not create output file SampleName-_STARtmp//BAMsort/19/26
SOLUTION: check that the path exists and you have write permission for this file. Also check ulimit -n and increase it to allow more open files._

But it do no seem to be be a ulimit issue as suggested. I tried lowering the thread number multiple times but issue still persisted.

Then **//BAMsort** appeared unusual due to **//**. So I changed  --outSAMtype BAM SortedByCoordinate to --outSAMtype BAM Unsorted. Then it successfully ran with even high number of threads.  

Could you please see if something is going wrong when SortedByCoordinate is set.

Jeffin

**Comment by alexdobin** [comment]
Hi Jeffin,

this seems to be the same issue as the one reported in #528 
Please try to run 2.6.1c in exactly the same configuration and send ne the Log.out file.

Cheers
Alex

**Comment by jianguozhouzunyimedicaluniversity** [comment]
Hi @alexdobin 
````
STAR version=2.7.1a
STAR compilation time,server,dir=Tue May 14 12:14:27 EDT 2019 vega:/home/dobin/data/STAR/STARcode/STAR.master/source
````
the output is :
````
BAMoutput.cpp:27:BAMoutput: exiting because of *OUTPUT FILE* error: could not create output file /home/zhou/raid/ncbi/dbGaP-24835/RNA_phs000452_PRJNA82747/CircRNA/STAR/SRR3083781/SRR3083781__STARtmp//BAMsort/19/4
SOLUTION: check that the path exists and you have write permission for this file. Also check ulimit -n and increase it to allow more open files.

Feb 02 18:12:11 ...... FATAL ERROR, exiting
````

**Comment by splaisan** [comment]
HI Alex, 

I have a similar issue with STAR 2.7.10b (samtools 1.18 freshly installed for good measure)

```
/opt/miniconda3/envs/star/bin/STAR-avx2 --runMode alignReads --runThreadN 24 --genomeDir pilon_correct/star_index --readFilesIn paired_reads/SRR18747273_1.fq.gz paired_reads/SRR18747273_2.fq.gz --readFilesCommand zcat --outFileNamePrefix pilon_correct/star_out/SRR18747273_mappings_ --outSAMtype BAM SortedByCoordinate

        STAR version: 2.7.10b   compiled: 2023-05-25T06:56:23+0000 :/opt/conda/conda-bld/star_1684997536154/work/source
Aug 22 16:08:12 ..... started STAR run
Aug 22 16:08:13 ..... loading genome
Aug 22 16:08:14 ..... started mapping

BAMoutput.cpp:27:BAMoutput: exiting because of *OUTPUT FILE* error: could not create output file pilon_correct/star_out/SRR18747273_mappings__STARtmp//BAMsort/20/16
SOLUTION: check that the path exists and you have write permission for this file. Also check ulimit -n and increase it to allow more open files.
```

And the same command without the last argument `--outSAMtype BAM SortedByCoordinate` worked

```
STAR   --runMode alignReads   --runThreadN ${nthr}   --genomeDir pilon_correct/star_index   --readFilesIn $R1 $R2   --readFilesCommand zcat   --outFileNamePrefix pilon_correct/star_out/${pfx}_mappings_
        /opt/miniconda3/envs/star/bin/STAR-avx2 --runMode alignReads --runThreadN 24 --genomeDir pilon_correct/star_index --readFilesIn paired_reads/SRR18747273_1.fq.gz paired_reads/SRR18747273_2.fq.gz --readFilesCommand zcat --outFileNamePrefix pilon_correct/star_out/SRR18747273_mappings_
        STAR version: 2.7.10b   compiled: 2023-05-25T06:56:23+0000 :/opt/conda/conda-bld/star_1684997536154/work/source
Aug 22 16:08:38 ..... started STAR run
Aug 22 16:08:38 ..... loading genome
Aug 22 16:08:40 ..... started mapping
Aug 22 16:13:02 ..... finished mapping
Aug 22 16:13:02 ..... finished successfully
```

N: my ulimit is unlimited

thanks for any idea to get the BAM output back

Stephane

**Comment by alexdobin** [comment]
Hi Stephane,

what is the output of `ulimit -n`? I do not think it's ever truly unlimited, even if `ulimit` says unlimited.

**Comment by splaisan** [comment]
Hi Alex, you are right, unlimited becomes 1024 with this command, I will try higher the value and run again
Cheers,
Stephane
