### ISSUE TITLE
CIGAR and query sequence are of different length

### ISSUE THREAD

**Issue by dinggens** [alexdobin/STAR#530]
Hello,

I've recently switched to STAR v2.6.1d (formerly 2.5.4a).
So far everything worked nice with the aligner but now an error occured when processing a sample.
Actually the error occurs when using _samtools_ (converting a SAM file produced with STAR to a BAM file), but obviously sth. is wrong with the SAM file.
The error message of the following call
`samtools view -F 260 -bS -q 30 Aligned.out.sam > Res.unsorted.bam`
is

> [E::sam_parse1] CIGAR and query sequence are of different length
> [W::sam_read1] Parse error at line 778807
> [main_samview] truncated file.

The previous STAR call was
```
STAR --runThreadN 8 \
	 --outSAMstrandField intronMotif \
	 --genomeDir $gendir \
	 --readFilesCommand zcat \
	 --readFilesIn infile_1.fq.gz infile_2.fq.gz \
	 --outFileNamePrefix outf/ \
	 --outReadsUnmapped Fastx
```
Thanks in advance for any hints!

**Comment by alexdobin** [comment]
Hi @dinggens 

does the Aligned.out.sam file is exactly 778807 lines long?
If so, it seems that the file was truncated, check it with
$ tail Aligned.out.sam
If this is the case, please try to re-run STAR.
If not, please extract the line 778807 and send it to me.

Cheers
Alex

**Comment by dinggens** [comment]
I reran STAR already with the same result.
This is line 778807
`A00470:148:HFYMMDMXX:1:1110:31729:12289 147     2       85549256        255     101M    =       85549218        -139    TAATGTAATA00470:148:HFYMMDMXX:1:1108:6876:11992 99      7       143876069       255     101M    =       143876157   189      GCCAGCCACACTGGTCACGAGGTTCCCAGGGAACGTGAACAGAACCCTTTCATCCTCCCCCTGGTTGGCCCAATCCCAGGCTTGTCCTCCTATGAGCAAGC   FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFA00470:148:HFYMMDMXX:1:1115:26648:23437     99      2       24850386        255 101M     =       24850546        261     CATTTGTGTTCCTGGGGGAAGGAAGGAGGCTGGGATCCAGGTGAACTGGCAAATGGGTCCCACAGTGGGGGACAGGAGTGCAGGGGAGAGAGGCCACCCAT   FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF        NH:i:1  HI:i:1  AS:i:200        nM:i:0`

**Comment by dinggens** [comment]
...and the SAM file has 135198535 lines in total.
Many thanks for your help!

**Comment by alexdobin** [comment]
Hi @dinggens 

this line is messed up, it looks like three lines merged together.
A few things I would suggest:
1. Run with the precompiled executables from bin/Linux_x86_64  and bin/Linux_x86_64_static, or compile your own with 
$ cd source && make
2. Change the number of threads from 8 to 4.
3. Cut a few thousands reads around the problematic read and run mapping.

If the problem still occurs for the same read, I would need a sample of your data to reproduce the problem on my system.

Cheers
Alex

**Comment by dinggens** [comment]
Running it with the precompiled executable from bin/Linux_x86_64 solved the problem.
Thank you so much!
