### ISSUE TITLE
Install STAR issue

### ISSUE THREAD

**Issue by zhengjiantao** [alexdobin/STAR#531]
My code is as follows:
cd STAR/source
make STAR

And then the information I get is:
![tim 20181205213149](https://user-images.githubusercontent.com/41890364/49516701-31154480-f8d5-11e8-8fcc-b407b1bcf9be.png)

Then, I try to use command:
cd STAR/bin/Linux_x86_64
STAR --version

But I get the an error:
The program 'STAR' is currently not installed. To run 'STAR' please ask your administrator to install the package 'rna-star'

For help~~
Thanks advanced!

**Comment by alexdobin** [comment]
Hi @zhengjiantao 

you need to either do
$ cd STAR/bin/Linux_x86_64
$ ./STAR --version
or 
$ STAR/bin/Linux_x86_6/STAR --version
or - better - include the full path to the PATH environment variable.
Also, the  bin/Linux_x86_64/ contains pre-compiled executable, if you want to use the executable that you just compiled, it's located in the source/ directory.

Cheers
Alex

**Comment by zhengjiantao** [comment]
> Hi @zhengjiantao
> 
> you need to either do
> $ cd STAR/bin/Linux_x86_64
> $ ./STAR --version
> or
> $ STAR/bin/Linux_x86_6/STAR --version
> or - better - include the full path to the PATH environment variable.
> Also, the bin/Linux_x86_64/ contains pre-compiled executable, if you want to use the executable that you just compiled, it's located in the source/ directory.
> 
> Cheers
> Alex

Thanks for Alex!
It worked. But I still confused the difference between them:
$ cd STAR/bin/Linux_x86_64
$ ./STAR --version
and
$ cd STAR/bin/Linux_x86_64
$ STAR --version

Maybe I use Windows a lot ~

**Comment by alexdobin** [comment]
Hi @zhengjiantao 

this is a Linux security feature, good discussion on why it's that way:
[https://unix.stackexchange.com/questions/4430/why-do-we-use-to-execute-a-file](url)
Actually, I believe some Linux shells can run local executables without the ./ path specification.

Cheers
Alex
