### ISSUE TITLE
Manual needs updating regarding NCBI reference

### ISSUE THREAD

**Issue by jrkirk61** [alexdobin/STAR#536]
In section 2.2.1 of the manual, it mentions that one should use:

- NCBI: "no alternative - analysis set": ftp://ftp.ncbi.nlm.nih.gov/genbank/
genomes/Eukaryotes/vertebrates_mammals/Homo_sapiens/GRCh38/seqs_for_alignment_
pipelines/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz

However, this ftp path no longer exists and that file no longer seems to exist. Additionally, the new genbank ftp path (ftp://ftp.ncbi.nlm.nih.gov/genomes/genbank/vertebrate_mammalian/Homo_sapiens/reference/GCA_000001405.27_GRCh38.p12) includes files that seem outdated compared to the latest assembly, so it doesn't seem very trustworthy. 

What are your recommendations for those who'd like to use NCBI's human genome?

**Comment by alexdobin** [comment]
Hi Jessica,

well noted! Will fix in the next release.
ENSEMBL or GENCODE fasta and gtf are the most robust at the moment.

Cheers
Alex
