### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by JessicaGKing** [alexdobin/STAR#537]
Hello,

I am new to STAR and ran into an error that I hope you can help me with.

After running the following bit of code:

**./STAR --genomeDir path/to/STAR_index_folder --readFilesIn SRR..._1.fastq SRR..._2.fastq --outFilterType BySJout --outFilterMultimapNmax 20 --outSAMunmapped Within --outFileNamePrefix SRR... --outSAMtype BAM SortedByCoordinate**

I got two types of errors:

Dec 17 12:53:08 ..... started STAR run
Dec 17 12:53:08 ..... loading genome
Dec 17 12:53:10 ..... started mapping
**Illegal instruction: 4**
Dec 17 12:54:24 ..... started STAR run
Dec 17 12:54:25 ..... loading genome
Dec 17 12:54:27 ..... started mapping
**Segmentation fault: 11**

All the best,

Jessica King

**Comment by paulmenzel** [comment]
On 12/17/18 17:12, JessicaGKing wrote:

> I am new to STAR and ran into an error that I hope you can help me
> with.
> 
> After running the following bit of code:
> 
> **./STAR --genomeDir path/to/STAR_index_folder --readFilesIn SRR..._1.fastq SRR..._2.fastq --outFilterType BySJout --outFilterMultimapNmax 20 --outSAMunmapped Within --outFileNamePrefix SRR... --outSAMtype BAM SortedByCoordinate**
> 
> 
> I got two types of errors:
> 
> Dec 17 12:53:08 ..... started STAR run
> Dec 17 12:53:08 ..... loading genome
> Dec 17 12:53:10 ..... started mapping
> **Illegal instruction: 4**
> Dec 17 12:54:24 ..... started STAR run
> Dec 17 12:54:25 ..... loading genome
> Dec 17 12:54:27 ..... started mapping
> **Segmentation fault: 11**

*Illegal instruction* normally means, that your system is older than
the one the binary was built on.

Can you please build STAR on the system you run it on?

**Comment by alexdobin** [comment]
Hi Jessica,

you would need to compile STAR from the source.
This requires installing gcc compiler, which can be done, for instance with Homebrew.

Cheers
Alex
