### ISSUE TITLE
Use loadGenome on cluster

### ISSUE THREAD

**Issue by Zepeng-Mu** [alexdobin/STAR#539]
Hi, I know this may not be a place for asking technical questions, but I am wondering whether I can use `--loadGenome LoadAndRemove` on an HPC cluster, where I am doing multiple alignments at the same time but using different jobs.

Thanks

**Comment by alexdobin** [comment]
Hi Zepeng,

the STAR forum is a better place to ask questions, actually:
[https://groups.google.com/forum/#!forum/rna-star](url)
The GitHub Issues is better suited for issues/problems.

I generally do not recommend using shared memory (--loadGenome LoadAndRemove)  in cluster environments. It would only make sense if you can guarantee that you jobs will run on the same nodes. Another possibility is to split your mapping runs into chunks, that are submitted as separate jobs - then  the runs in each chunk can use shared memory on the same node.

Cheers
Alex
