### ISSUE TITLE
Problem with mapping

### ISSUE THREAD

**Issue by bachiss** [alexdobin/STAR#540]
Hello,
I have reads of 76bp and want reads of 75bp, so I use bbduk to remove the extra base

bbduck.sh in=in.fastq.gz out=out.fastq.gz ftr=74

After I use STAR and this is the output:

_Started job on |	Dec 14 11:27:51
                             Started mapping on |	Dec 14 11:30:26
                                    Finished on |	Dec 14 12:15:51
       Mapping speed, Million of reads per hour |	83.50

                          Number of input reads |	63206038
                      Average input read length |	149
                                    UNIQUE READS:
                   Uniquely mapped reads number |	7498874
                        Uniquely mapped reads % |	11.86%
                          Average mapped length |	147.53
                       Number of splices: Total |	4048089
            Number of splices: Annotated (sjdb) |	3688209
                       Number of splices: GT/AG |	4030743
                       Number of splices: GC/AG |	14318
                       Number of splices: AT/AC |	1543
               Number of splices: Non-canonical |	1485
                      Mismatch rate per base, % |	0.75%
                         Deletion rate per base |	0.00%
                        Deletion average length |	1.46
                        Insertion rate per base |	0.00%
                       Insertion average length |	1.30
                             MULTI-MAPPING READS:
        Number of reads mapped to multiple loci |	5061720
             % of reads mapped to multiple loci |	8.01%
        Number of reads mapped to too many loci |	7111
             % of reads mapped to too many loci |	0.01%
                                  UNMAPPED READS:
       % of reads unmapped: too many mismatches |	0.00%
                 % of reads unmapped: too short |	80.09%
                     % of reads unmapped: other |	0.03%
                                  CHIMERIC READS:
                       Number of chimeric reads |	0
                            % of chimeric reads |	0.00%_

While if use 76bp-reads the output is:

_Started job on |	Dec 14 14:20:24
                             Started mapping on |	Dec 14 14:23:36
                                    Finished on |	Dec 14 15:19:00
       Mapping speed, Million of reads per hour |	68.45

                          Number of input reads |	63206038
                      Average input read length |	151
                                    UNIQUE READS:
                   Uniquely mapped reads number |	41173899
                        Uniquely mapped reads % |	65.14%
                          Average mapped length |	149.50
                       Number of splices: Total |	25831575
            Number of splices: Annotated (sjdb) |	24858331
                       Number of splices: GT/AG |	25695893
                       Number of splices: GC/AG |	111814
                       Number of splices: AT/AC |	12139
               Number of splices: Non-canonical |	11729
                      Mismatch rate per base, % |	0.60%
                         Deletion rate per base |	0.00%
                        Deletion average length |	1.54
                        Insertion rate per base |	0.00%
                       Insertion average length |	1.29
                             MULTI-MAPPING READS:
        Number of reads mapped to multiple loci |	18962841
             % of reads mapped to multiple loci |	30.00%
        Number of reads mapped to too many loci |	49168
             % of reads mapped to too many loci |	0.08%
                                  UNMAPPED READS:
       % of reads unmapped: too many mismatches |	0.00%
                 % of reads unmapped: too short |	4.70%
                     % of reads unmapped: other |	0.08%
                                  CHIMERIC READS:
                       Number of chimeric reads |	0
                            % of chimeric reads |	0.00%_

Why are there these differences in: Uniquely mapped reads %; % of reads mapped to multiple loci and % of reads unmapped: too short?
Thanks

**Comment by alexdobin** [comment]
Hi @bachiss 

I think the trimming introduced some problems - the mapping rate cannot change so much from just trimming the reads. You need to make sure that the order of the reads in the two fastq files did not change after trimming.

Cheers
Alex

**Comment by bachiss** [comment]
Hi @alexdobin
Thank you very much for reply, it was very useful.

Cheers
Bachisio
