### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by efratushava** [alexdobin/STAR#541]
I have a segmenttation fault when running STAR with multipule files in "readFilesIn":
My version: STAR_2.5.2b

My command:
STAR252 --readFilesIn /private7/common/Data/DataSets/AML/BeatAML/RNA150311JT_14-00817_GACTAGTA_L001_R1_001.fastq.gz /private7/common/Data/DataSets/AML/RNA150311JT_14-00817_GACTAGTA_L001_R1_002.fastq.gz /private7/common/Data/DataSets/AML/RNA150311JT_14-00817_GACTAGTA_L001_R1_003.fastq.gz /private7/common/Data/DataSets/AML/RNA150311JT_14-00817_GACTAGTA_L001_R1_004.fastq.gz /private7/common/Data/DataSets/AML/RNA150311JT_14-00817_GACTAGTA_L001_R1_005.fastq.gz /private7/common/Data/DataSets/AML/RNA150311JT_14-00817_GACTAGTA_L001_R1_006.fastq.gz /private7/common/Data/DataSets/AML/RNA150311JT_14-00817_GACTAGTA_L001_R1_007.fastq.gz /private7/common/Data/DataSets/AML/RNA150311JT_14-00817_GACTAGTA_L001_R1_008.fastq.gz /private7/common/Data/DataSets/AML/RNA150311JT_14-00817_GACTAGTA_L001_R2_001.fastq.gz /private7/common/Data/DataSets/AML/RNA150311JT_14-00817_GACTAGTA_L001_R2_002.fastq.gz /private7/common/Data/DataSets/AML/RNA150311JT_14-00817_GACTAGTA_L001_R2_003.fastq.gz /private7/common/Data/DataSets/AML/RNA150311JT_14-00817_GACTAGTA_L001_R2_004.fastq.gz /private7/common/Data/DataSets/AML/RNA150311JT_14-00817_GACTAGTA_L001_R2_005.fastq.gz /private7/common/Data/DataSets/AML/RNA150311JT_14-00817_GACTAGTA_L001_R2_006.fastq.gz /private7/common/Data/DataSets/AML/RNA150311JT_14-00817_GACTAGTA_L001_R2_007.fastq.gz /private7/common/Data/DataSets/AML/RNA150311JT_14-00817_GACTAGTA_L001_R2_008.fastq.gz --outFilterMultimapNmax 1 --genomeLoad NoSharedMemory  --genomeDir /private/dropbox/Genomes/Human/hg38.STAR --readFilesCommand zcat --outFileNamePrefix /private7/projects/ekushele/AML/BeatAML/try/14-00817 --outReadsUnmapped Fastx  --outSAMattributes All  --runThreadN 10 --outBAMsortingThreadN 5 --limitBAMsortRAM 35000000000   --twopassMode Basic  --outSAMtype BAM SortedByCoordinate

I get:
Segmentation fault (core dumped)

When running with "gdb" as suggested [here](https://github.com/alexdobin/STAR/issues/520) I get the result:

(gdb) run --readFilesIn /private7/common/Data/DataSets/AML/BeatAML/RNA150311JT_14-00817_GACTAGTA_L001_R1_001.fastq.gz /private7/common/Data/DataSets/AML/BeatAML/RNA150311JT_14-00817_GACTAGTA_L001_R1_002.fastq.gz /private7/common/Data/DataSets/AML/BeatAML/RNA150311JT_14-00817_GACTAGTA_L001_R1_003.fastq.gz /private7/common/Data/DataSets/AML/BeatAML/RNA150311JT_14-00817_GACTAGTA_L001_R1_004.fastq.gz /private7/common/Data/DataSets/AML/BeatAML/RNA150311JT_14-00817_GACTAGTA_L001_R1_005.fastq.gz /private7/common/Data/DataSets/AML/BeatAML/RNA150311JT_14-00817_GACTAGTA_L001_R1_006.fastq.gz /private7/common/Data/DataSets/AML/BeatAML/RNA150311JT_14-00817_GACTAGTA_L001_R1_007.fastq.gz /private7/common/Data/DataSets/AML/BeatAML/RNA150311JT_14-00817_GACTAGTA_L001_R1_008.fastq.gz /private7/common/Data/DataSets/AML/BeatAML/RNA150311JT_14-00817_GACTAGTA_L001_R2_001.fastq.gz /private7/common/Data/DataSets/AML/BeatAML/RNA150311JT_14-00817_GACTAGTA_L001_R2_002.fastq.gz /private7/common/Data/DataSets/AML/BeatAML/RNA150311JT_14-00817_GACTAGTA_L001_R2_003.fastq.gz /private7/common/Data/DataSets/AML/BeatAML/RNA150311JT_14-00817_GACTAGTA_L001_R2_004.fastq.gz /private7/common/Data/DataSets/AML/BeatAML/RNA150311JT_14-00817_GACTAGTA_L001_R2_005.fastq.gz /private7/common/Data/DataSets/AML/BeatAML/RNA150311JT_14-00817_GACTAGTA_L001_R2_006.fastq.gz /private7/common/Data/DataSets/AML/BeatAML/RNA150311JT_14-00817_GACTAGTA_L001_R2_007.fastq.gz /private7/common/Data/DataSets/AML/BeatAML/RNA150311JT_14-00817_GACTAGTA_L001_R2_008.fastq.gz -outFilterMultimapNmax 1 --genomeLoad NoSharedMemory  --genomeDir /private/dropbox/Genomes/Human/hg38.STAR --readFilesCommand zcat --outFileNamePrefix /private7/projects/ekushele/AML/BeatAML/try/14-00817 --outReadsUnmapped Fastx  --outSAMattributes All  --runThreadN 10 --outBAMsortingThreadN 5 --limitBAMsortRAM 35000000000   --twopassMode Basic  --outSAMtype BAM SortedByCoordinate
Starting program: /private/apps/bin/STAR252 --readFilesIn /private7/common/Data/DataSets/AML/BeatAML/RNA150311JT_14-00817_GACTAGTA_L001_R1_001.fastq.gz /private7/common/Data/DataSets/AML/BeatAML/RNA150311JT_14-00817_GACTAGTA_L001_R1_002.fastq.gz /private7/common/Data/DataSets/AML/BeatAML/RNA150311JT_14-00817_GACTAGTA_L001_R1_003.fastq.gz /private7/common/Data/DataSets/AML/BeatAML/RNA150311JT_14-00817_GACTAGTA_L001_R1_004.fastq.gz /private7/common/Data/DataSets/AML/BeatAML/RNA150311JT_14-00817_GACTAGTA_L001_R1_005.fastq.gz /private7/common/Data/DataSets/AML/BeatAML/RNA150311JT_14-00817_GACTAGTA_L001_R1_006.fastq.gz /private7/common/Data/DataSets/AML/BeatAML/RNA150311JT_14-00817_GACTAGTA_L001_R1_007.fastq.gz /private7/common/Data/DataSets/AML/BeatAML/RNA150311JT_14-00817_GACTAGTA_L001_R1_008.fastq.gz /private7/common/Data/DataSets/AML/BeatAML/RNA150311JT_14-00817_GACTAGTA_L001_R2_001.fastq.gz /private7/common/Data/DataSets/AML/BeatAML/RNA150311JT_14-00817_GACTAGTA_L001_R2_002.fastq.gz /private7/common/Data/DataSets/AML/BeatAML/RNA150311JT_14-00817_GACTAGTA_L001_R2_003.fastq.gz /private7/common/Data/DataSets/AML/BeatAML/RNA150311JT_14-00817_GACTAGTA_L001_R2_004.fastq.gz /private7/common/Data/DataSets/AML/BeatAML/RNA150311JT_14-00817_GACTAGTA_L001_R2_005.fastq.gz /private7/common/Data/DataSets/AML/BeatAML/RNA150311JT_14-00817_GACTAGTA_L001_R2_006.fastq.gz /private7/common/Data/DataSets/AML/BeatAML/RNA150311JT_14-00817_GACTAGTA_L001_R2_007.fastq.gz /private7/common/Data/DataSets/AML/BeatAML/RNA150311JT_14-00817_GACTAGTA_L001_R2_008.fastq.gz -outFilterMultimapNmax 1 --genomeLoad NoSharedMemory  --genomeDir /private/dropbox/Genomes/Human/hg38.STAR --readFilesCommand zcat --outFileNamePrefix /private7/projects/ekushele/AML/BeatAML/try/14-00817 --outReadsUnmapped Fastx  --outSAMattributes All  --runThreadN 10 --outBAMsortingThreadN 5 --limitBAMsortRAM 35000000000   --twopassMode Basic  --outSAMtype BAM SortedByCoordinate
[Thread debugging using libthread_db enabled]
Detaching after fork from child process 5586.
Detaching after fork from child process 5588.
Detaching after fork from child process 5590.
Detaching after fork from child process 5592.
Detaching after fork from child process 5594.
Detaching after fork from child process 5596.
Detaching after fork from child process 5600.
Detaching after fork from child process 5635.

Program received signal SIGSEGV, Segmentation fault.
0x0000000000474151 in Parameters::openReadsFiles() ()
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.212.el6.x86_64 libgcc-4.4.7-23.el6.x86_64 libgomp-4.4.7-23.el6.x86_64 libstdc++-4.4.7-23.el6.x86_64 zlib-1.2.3-29.el6.x86_64

What is the problem?

**Comment by paulmenzel** [comment]
Am 24.12.18 um 15:08 schrieb efratushava:
> I have a segmenttation fault when running STAR with multipule files in "readFilesIn": > My version: STAR_2.5.2b

Please try the latest release, or build STAR from the branch *master*.

[…]

> 0x0000000000474151 in Parameters::openReadsFiles() ()
> Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.212.el6.x86_64 libgcc-4.4.7-23.el6.x86_64 libgomp-4.4.7-23.el6.x86_64 libstdc++-4.4.7-23.el6.x86_64 zlib-1.2.3-29.el6.x86_64

If the crash is still reproducible in the latest version, please also 
execute the suggested command above before running STAR under GDB.
