### ISSUE TITLE
Bizzare mappings reported by STAR

### ISSUE THREAD

**Issue by sagnikbanerjee15** [alexdobin/STAR#543]
Hello Alex,

I am running STAR to align short reads to the genome and I am getting some mappings which are obviously spurious. On closer inspection, I found that some reads are being mapped with a splice length of around 285,209. This is incorrect since I fixed the max intron length at 20,000 with the argument '--alignIntronMax'. What is of even greater concern is that multiple mappings of the read have been reported but with different cigars. The obviously spurious alignment has not been marked secondary. Here are all the alignment of the read.

J00102:12:HLTG3BBXX:2:1219:31223:31681	16	chr2H_A	174196901	255	9M285209N141M	*	0	0	CGGATTCCCCAAAAAGATTGTTGTGAAGGCTCCCCTTAGGCCAGTATTCATAGCAGAGTACAGTGTCAATGACCTCTGCAATAATATATCGTCCGTTGCTCTGCACCAATTTTTTTTGTGCCTCACGGCAGTAAGCAACCAACTTGACGA	F777<AA-A<7-JAA777<-FFFFAJ<--<7JJJJAFJJJJJFJFJJ<FA<7JJFAF7<JJAJFFFJJJJAAA7A7AFFJFFA-FF<<JFJFAFJJJFJFJAFAA<A-AJFFJJJJJ7JJJJJJJJJJJJJJJJJJJFJJFFAFFFFAAA	NH:i:1	HI:i:1	AS:i:141	nM:i:2

J00102:12:HLTG3BBXX:2:1219:31223:31681	16	chr2H_A	174196901	255	9M285209N141M	*	0	0	CGGATTCCCCAAAAAGATTGTTGTGAAGGCTCCCCTTAGGCCAGTATTCATAGCAGAGTACAGTGTCAATGACCTCTGCAATAATATATCGTCCGTTGCTCTGCACCAATTTTTTTTGTGCCTCACGGCAGTAAGCAACCAACTTGACGA	F777<AA-A<7-JAA777<-FFFFAJ<--<7JJJJAFJJJJJFJFJJ<FA<7JJFAF7<JJAJFFFJJJJAAA7A7AFFJFFA-FF<<JFJFAFJJJFJFJAFAA<A-AJFFJJJJJ7JJJJJJJJJJJJJJJJJJJFJJFFAFFFFAAA	NH:i:1	HI:i:1	AS:i:141	nM:i:2

J00102:12:HLTG3BBXX:2:1219:31223:31681	16	chr2H_A	174482118	255	8S142M	*	0	0	CGGATTCCCCAAAAAGATTGTTGTGAAGGCTCCCCTTAGGCCAGTATTCATAGCAGAGTACAGTGTCAATGACCTCTGCAATAATATATCGTCCGTTGCTCTGCACCAATTTTTTTTGTGCCTCACGGCAGTAAGCAACCAACTTGACGA	F777<AA-A<7-JAA777<-FFFFAJ<--<7JJJJAFJJJJJFJFJJ<FA<7JJFAF7<JJAJFFFJJJJAAA7A7AFFJFFA-FF<<JFJFAFJJJFJFJAFAA<A-AJFFJJJJJ7JJJJJJJJJJJJJJJJJJJFJJFFAFFFFAAA	NH:i:1	HI:i:1	AS:i:136	nM:i:2

J00102:12:HLTG3BBXX:2:1219:31223:31681	16	chr2H_A	174482118	255	8S142M	*	0	0	CGGATTCCCCAAAAAGATTGTTGTGAAGGCTCCCCTTAGGCCAGTATTCATAGCAGAGTACAGTGTCAATGACCTCTGCAATAATATATCGTCCGTTGCTCTGCACCAATTTTTTTTGTGCCTCACGGCAGTAAGCAACCAACTTGACGA	F777<AA-A<7-JAA777<-FFFFAJ<--<7JJJJAFJJJJJFJFJJ<FA<7JJFAF7<JJAJFFFJJJJAAA7A7AFFJFFA-FF<<JFJFAFJJJFJFJAFAA<A-AJFFJJJJJ7JJJJJJJJJJJJJJJJJJJFJJFFAFFFFAAA	NH:i:1	HI:i:1	AS:i:136	nM:i:2

Please help.

Thank you.

**Comment by alexdobin** [comment]
Hi Sagnik,

sorry for the belayed reply.
This does not look right, indeed.
Please make sure that you are using the latest version of STAR.
if the problem remains, please send me the genome sequence (or just the chr2H_A).

Cheers
Alex
