### ISSUE TITLE
genome index with multiple reference sequences 

### ISSUE THREAD

**Issue by biozhao** [alexdobin/STAR#545]
Hi,
I encountered  a question during generate genome index with multiple reference sequences .
I don't know the result is right or not when i use the scripts as following:
cat gencode.v29.annotation.gtf my.gtf >> new.gtf
#!/usr/bin/bash
index_dir='/home/G/MSbox/index'
gtf='/home/G/MSbox/ref/new.gtf'
/home/lsl/arc/STAR-2.5.3a/bin/Linux_x86_64_static/STAR --runThreadN 15 --runMode genomeGenerate --genomeDir ${index_dir} --genomeFastaFiles /home/G/MSbox/ref/GRCh38.primary_assembly.genome.fa /home/G/MSbox/ref/HP.fna --sjdbGTFfile ${gtf} --sjdbOverhang 100

Is it necessary to sort new.gtf, or others commands to be done ? 
Thanks for your help!
Best,
zhao.

**Comment by alexdobin** [comment]
Hi Zhao,

this should be sufficient, but you need to make sure that the two annotations have distinct names for transcripts and genes.

Cheers
Alex

**Comment by biozhao** [comment]
Hi Alex

Thank you very much for reply!

Cheers
Zhao
