### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by JCSzamosi** [alexdobin/STAR#546]
I am running STAR 2.6.0a on Ubuntu 18.04 with 32GB of RAM, using the mouse genome downloaded from Gencode.

I generated the genome using the following command:

```
out=/PATH_TO/ReferenceGenomes/Mouse/Gencode/STAR
ref=/PATH_TO/ReferenceGenomes/Mouse/Gencode/GRCm38.primary_assembly.genome.fa

STAR --runThreadN 10 \
	--runMode genomeGenerate \
	--genomeDir $out \
	--genomeFastaFiles $ref \
```

Now I am trying to align paired-end (2x51bp) reads to it and getting a Segmentation Fault error. This is the command:

```
STAR --runThreadN 5 \
     --genomeDir /PATH_TO/ReferenceGenomes/Mouse/Gencode/STAR/ \
     --readFilesIn data//G1_S1_R1.fastq.gz data//G1_S1_R2.fastq.gz \
     --readFilesCommand gunzip -c \
     --sjdbGTFfile /PATH_TO/ReferenceGenomes/Mouse/Gencode/gencode.vM19.annotation.gtf \
     --sjdbOverhang 49 \
     --outFilterMultimapNmax 20 \
     --alignSJoverhangMin 8 \
     --outFilterMismatchNmax 999 \
     --outFilterMismatchNoverReadLmax 0.04 \
     --alignIntronMin 20 \
     --alignIntronMax 1000000 \
     --alignMatesGapMax 1000000 \
     --alignSJDBoverhangMin 1 \
     --outFileNamePrefix results/02_map//G1_S1/ \
     --outSAMtype BAM Unsorted \
     --peOverlapMMp 0.1
```

That command ran just fine when I subset the fastq.gz files down to just the first million reads. When I run it with `--runThreadN 10` it gives a segmentation fault, and when I run it as above with `--runThreadN 5` it gives the error `buffer size for SJ output is too small
Solution: increase input parameter --limitOutSJcollapsed`. When I increase that value, it goes back to giving a segmentation fault.

Any suggestions would be very much appreciated!

**Comment by alexdobin** [comment]
Hi @JCSzamosi 

versions 2.6.0a/b contained bugs and were removed from official releases.
Please switch to 2.6.0c, or - better - to the latest 2.6.1d :
[https://github.com/alexdobin/STAR/releases/tag/2.6.1d](https://github.com/alexdobin/STAR/releases/tag/2.6.1d)

Cheers
Alex
