### ISSUE TITLE
processing annotations GTF error 'std::out_of_range' when generating genome index

### ISSUE THREAD

**Issue by bgbrink** [alexdobin/STAR#548]
Hello everybody,

I get this error when I try to generate a STAR index for my genome. The respective fasta and gff files can be downloaded here: http://tritrypdb.org/common/downloads/release-41/TbruceiLister427/

I found some results on google related to this error that were caused by invalid chromosome names in the gff file, but I obtained both files from the same source and I could verify that this is not the case here. 

Dows STAR generate any additional logfiles that I could check?

```
STAR --runThreadN 16 --runMode genomeGenerate --genomeDir /work/project/ladsie_002/Tbrucei_Genomes/TriTrypDB-41/ --genomeFastaFiles /work/project/ladsie_002/Tbrucei_Genomes/TriTrypDB-41/TriTrypDB-41_TbruceiLister427_Genome.fasta --sjdbGTFfile /work/project/ladsie_002/Tbrucei_Genomes/TriTrypDB-41/TriTrypDB-41_TbruceiLister427.gff --sjdbOverhang 49
Jan 23 13:37:19 ..... started STAR run
Jan 23 13:37:19 ... starting to generate Genome files
Jan 23 13:37:19 ... starting to sort Suffix Array. This may take a long time...
Jan 23 13:37:19 ... sorting Suffix Array chunks and saving them to disk...
Jan 23 13:37:22 ... loading chunks from disk, packing SA...
Jan 23 13:37:23 ... finished generating suffix array
Jan 23 13:37:23 ... generating Suffix Array index
Jan 23 13:37:30 ... completed Suffix Array index
Jan 23 13:37:30 ..... processing annotations GTF
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check
```

Edit: I tested it with STAR_2.5.2a, STAR_2.5.3a, and STAR_2.6.0.c

**Comment by alexdobin** [comment]
Hi Benedikt,

I think the problem is that this GFF names transcripts "mRNA" instead of "transcript" (col.3).
You can replace "mRNA" with transcript in your file, and after that I would recommend converting the GFF to GTF first, e.g. using gffread from cufflinks package.

Cheers
Alex
