### ISSUE TITLE
can/should source/parametersDefault.xxd be removed?

### ISSUE THREAD

**Issue by smoe** [alexdobin/STAR#553]
Since https://github.com/alexdobin/STAR/blob/master/source/parametersDefault.xxd is autogenerated, should it possibly not be part of the source tree? Is it ok not to redistribute it with the Debian package's source tree?

The background to my question is that I have just removed the file since it was changed during the build, which in Debian has the intended effect that one cannot just go and continue with your life since apparently the original source tree got patched without that being formally recorded in the package's build instructions.

**Comment by alexdobin** [comment]
Hi Steffen,

I kept the .xxd file because some systems do not have xxd installed.
If your distribution is guaranteed to have it, then you can safely remove it.

Cheers
Alex
