### ISSUE TITLE
Segmentation fault, unable to run STAR

### ISSUE THREAD

**Issue by rikrdo89** [alexdobin/STAR#554]
Hi @alexdobin ,

I just installed STAR, and whenever I try to run it with any additional parameters (for instance, I tried `>STAR --version` ), I get the following error.
"Segmentation Fault (core dump)"

I am using Ubuntu 19.04.1 LTS, and I installed STAR v2.6.1b using bioconda with the command below:
`>conda install star`

Do you have any idea what may be wrong?  or is there any command I can use to make sure the installation went well? I believe `>STAR --version` is not allowed. when I run `>STAR` without any parameters, I get what it looks like the STAR man page.

Thank you. 

![image](https://user-images.githubusercontent.com/24930604/52171197-bfb40f80-2726-11e9-93d4-d4eeecaea415.png)

**Comment by alexdobin** [comment]
Hi @rikrdo89 

please try to use the pre-compiled executables.
Download:
$ wget https://github.com/alexdobin/STAR/archive/2.6.1d.tar.gz
Ungzip:
$ tar xvfz 2.6.1d.tar.gz
and run the executable from STAR-2.6.1d/bin/Linux_x86_64_static/ or STAR-2.6.1d/bin/Linux_x86_64/

Cheers
Alex
