### ISSUE TITLE
High rate of unmapped reads or multimapping; unmapped reads correspond to species of interest.

### ISSUE THREAD

**Issue by dejonggr** [alexdobin/STAR#555]
Hi there,

I've got some RNA-Seq data from 3 related species and regardless of the options, I've noticed very low rates of uniquely mapping reads. Here is an example output using STAR's default options:

>                                  Started job on |       Feb 03 16:01:52
>                              Started mapping on |       Feb 03 16:02:30
>                                     Finished on |       Feb 03 16:02:38
>        Mapping speed, Million of reads per hour |       8.50
> 
>                           Number of input reads |       18892
>                       Average input read length |       166
>                                     UNIQUE READS:
>                    Uniquely mapped reads number |       6594
>                         Uniquely mapped reads % |       34.90%
>                           Average mapped length |       162.56
>                        Number of splices: Total |       1715
>             Number of splices: Annotated (sjdb) |       1522
>                        Number of splices: GT/AG |       1691
>                        Number of splices: GC/AG |       15
>                        Number of splices: AT/AC |       0
>                Number of splices: Non-canonical |       9
>                       Mismatch rate per base, % |       0.73%
>                          Deletion rate per base |       0.01%
>                         Deletion average length |       2.09
>                         Insertion rate per base |       0.01%
>                        Insertion average length |       1.48
>                              MULTI-MAPPING READS:
>         Number of reads mapped to multiple loci |       1538
>              % of reads mapped to multiple loci |       8.14%
>         Number of reads mapped to too many loci |       36
>              % of reads mapped to too many loci |       0.19%
>                                   UNMAPPED READS:
>        % of reads unmapped: too many mismatches |       0.00%
>                  % of reads unmapped: too short |       56.76%
>                      % of reads unmapped: other |       0.00%
>                                   CHIMERIC READS:
>                        Number of chimeric reads |       0
>                             % of chimeric reads |       0.00%

Originally I was concerned about rRNA (the library prep used ribo-depletion) but they didn't map to any rRNA genes.

I've blasted the unmapped reads and the top hits mostly correspond to the same species with near-perfect or 100% sequence identity. I thought about this maybe being a problem with the reference genome but it seems like the indices were constructed correctly (perhaps there is something fundamentally wrong with the assemblies but they are from fairly well known Brassica species that have allegedly sufficient assemblies for the context of RNA-seq).

Do you have any suggestions? It would be difficult to proceed with such low mapping rates.

**Comment by dejonggr** [comment]
I mapped them separately to no avail (the results were pretty similar). However, I blasted the unmapped reads and they mostly all correspond to plastid genes which is disappointing.

**Comment by alexdobin** [comment]
Do you have the plastid genome(s) in the reference? Or maybe your plastids are divergent from the reference? These could be reasons STAR cannot map these reads.

**Comment by dejonggr** [comment]
I assembled an index based on the chloroplast genome and there was a rate of about 60% - 70% uniquely mapped reads - most of which corresponded to the psbA gene. I've never seen total RNA sequencing result in this much plastid RNA so maybe this can be seen as a cautionary tale for your users that attempt total RNA with ribo-depletion before considering chloroplastic reads.
