### ISSUE TITLE
Multi-sample 2-pass mapping, gzip: stdout: Broken pipe Segmentation fault

### ISSUE THREAD

**Issue by awchrist** [alexdobin/STAR#56]
Hi Alex,
First, I just want to say thank you for all of your great work.

I am having trouble with the 2nd pass step, while including annotations on the fly, for Multi-sample mapping. 
I believe another user had a similar issue but I'm not sure if they ever got back to you with the ouptut logs.
The Problem seems to be somewhat intermittent. With a loop script I started 3 samples and failed with this error. 
I also tried starting 96 at once and 89 of those failed with the same error. 

Here is my ErrLog of the run

```
Jul 20 12:49:08 ..... Started STAR run
Jul 20 12:49:08 ..... Loading genome
Jul 20 12:52:56 ..... Processing annotations GTF
Jul 20 12:53:54 ..... Inserting junctions into the genome indices

gzip: stdout: Broken pipe
/cm/local/apps/torque/var/spool/mom_priv/jobs/2054630.pnap-mgt1.cm.cluster.SC: line 47: 12656 Segmentation fault      (core dumped) /home/achristofferson/tools/STAR/bin/Linux_x86_64_static/STAR --runThreadN 16 --runMode alignReads --genomeDir /scratch/achristofferson/ref_genome --readFilesCommand zcat --sjdbGTFfile ${GTF_file} --sjdbOverhang ${read_length} --outFilterType BySJout --outFilterMultimapNmax 10 --outFilterMismatchNmax 10 --outSAMmapqUnique 60 --outSAMunmapped Within --limitOutSAMoneReadBytes 90000000 --outSAMtype SAM --alignIntronMin 20 --alignIntronMax 1000000 --alignMatesGapMax 1000000 --alignSJoverhangMin 8 --alignSJDBoverhangMin 1 --seedSearchStartLmax 30 --chimSegmentMin 15 --chimJunctionOverhangMin 15 --outReadsUnmapped Fastx --genomeLoad NoSharedMemory --outSAMattrRGline ${RGT} --outSAMmode Full --sjdbFileChrStartEnd ${SJ_out_tab} --limitSjdbInsertNsj 3000000 --readFilesIn ${FASTL1} ${FASTL2}

gzip: stdout: Broken pipe

gzip: stdout: Broken pipe

gzip: stdout: Broken pipe
```
Also here is the tail end of the Log.out file
```
Processing sjdbGTFfile=/home/achristofferson/ensembl_ref/Homo_sapiens.GRCh37.75.gtf, found:
                196501 transcripts
                1195764 exons (non-collapsed)
                344569 collapsed junctions
Jul 20 12:53:20 ..... Finished GTF processing
Jul 20 12:53:20   Loaded database junctions from the GTF file: /home/achristofferson/ensembl_ref/Homo_sapiens.GRCh37.75.gtf: 32248208 total junctions

Jul 20 12:53:54   Finished preparing junctions
Jul 20 12:53:54 ..... Inserting junctions into the genome indices
Jul 20 12:59:25   Finished SA search: number of new junctions=2812730, old junctions=0
```
This may be a separate issue, however is it normal to see so many WARNING lines in the Log.out saying?
chromosome 'HG1472_PATCH' not found in Genome fasta files for line:

HG1472_PATCH was just an example, not all of them say PATCH but a lot do.

Thanks again Alex

**Comment by awchrist** [comment]
Update: I believe this is a memory issue(not enough) on the sorting SA indicesL step
(step right after Finished SA search: number of new junctions=2812730). 

We have normal 48GB 16core nodes as well as a few 150GB 12core high memory nodes. 
I'm working with 16 stranded samples with ~80mil paired reads(160mil tot) each and 
another 80 unstranded samples with 20-230mil paired reads(40-460mil tot) each.
The samples that are completing on our 48GB memory nodes are the samples with lower read counts from the unstranded group.

As a test I used 2 of the 16 stranded samples using the high-mem nodes and they so far have gotten
past the sorting SA indicesL step and are starting to write to the SAM file.

The sorting SA indicesL step varies greatly from sample to sample. Once the "Finished sorting SA indicesL" step is written to the Log.out file, the time stamp difference between "Finished SA search: number of new junctions" and "Finished sorting SA indicesL"  is only 5-12 min.
However, in reality it took significantly longer(60-75min) to write "Finished sorting SA indicesL" to the Log.out and start writing reads to the SAM file.

Is this step suppose to be universal for all samples? ( In terms of memory usage and cpu hours)

**Comment by brunogrande** [comment]
Hello, @awchrist. I'm guessing that you're referring to [my issue](https://github.com/alexdobin/STAR/issues/47) in your post. Unfortunately, I had deleted the logs by the time Alex responded and didn't have the time to regenerate them. 

I'm now running STAR for some other RNA-seq libraries using the same approach, namely 2-pass alignment with annotations. I basically tried my approach described in that issue and ran into a segmentation fault when attempting on-the-fly method. I also tried reindexing the genome using the new junctions, but unlike last time, that also failed with a segmentation fault. 

I've kept the logs for all steps. See [this link](https://www.dropbox.com/sh/ww1hstq7tcaekfy/AADoruD5phD_ZZzeqogZyveBa?dl=0). 

1. The original genome indexing (which worked)
2. An attempt at the on-the-fly method for a sample
3. An attempt at reindexing the genome with the new junctions

@awchrist's theory about it being memory-related might explain another issue I'm having, where some STAR jobs will cause compute nodes (48 GB each, like Austin) to become unresponsive. IT tells me that STAR is taking up all of the node's RAM (despite me setting a limit). Let us know if we can provide more information to help debug this issue. I'll be more diligent this time!

**Comment by awchrist** [comment]
Hello, @brunogrande . I also switched to re-indexing the genome with the new junctions. I didn't get a seg fault with that method, however the second pass with new junctions did end up taking much longer (51 hours for one of my samples). 

I found a recommendation from Alex in one of his other posts to remove the MT junctions before making the new indexed genome, which I did not do. He mentioned doing this may reduce spurious mappings and reduce the chance of the second pass running longer.

If the variants I get back are all over the place I will start back at that step and remove all of the MT junctions. 

Austin

**Comment by brunogrande** [comment]
Perhaps the node I was running the genome reindexing on ran out of memory. 

As for the recommendation of removing chrM/MT junctions, I've included this step in my filtering (not that it helped prevent the segfault). Here's how I'm filtering at the moment. 

```bash
# Set filenames
PREFIX="all_samples_SJ"
EXT="tab"

# Concatenate all SJ.out.tab files
ALL_SJ="$PREFIX.$EXT"
cat ../1-launch_pipeline/2015-07-29_19-29-30/*_rnaseq_pipeline/outputs/1-star_first_pass/*_SJ.out.tab > "$ALL_SJ"

# Filter splice junctions according to:
# 1) Remove annotated junctions
# 2) Remove junctions in chrM
# 3) Ensure at least one uniquely mapped read
ALL_SJ_FILT="$PREFIX.filt_on_sample.$EXT"
awk 'BEGIN { FS=OFS="\t" } { if ( $6 == "0" && $1 != "chrM" && $7 >= 1 ){ print $0 } }' "$ALL_SJ" > "$ALL_SJ_FILT"

# Then, only consider the first four columns (sample-agnostic properties)
# Sort and run uniq -c in order to count the number of samples supporting
# the junction, and filter on having 2 or more samples
ALL_SJ_FILT2="$PREFIX.filt_on_cohort.$EXT"
cut -f1-4 "$ALL_SJ_FILT" | sort | uniq -c | perl -pe 's/^ +(\d+) (.*)/\1\t\2/' | awk 'BEGIN { FS=OFS="\t" } { if ( $1 >= 2 ){ print $2,$3,$4,$5 } }' | sort -k1,1 -k2,2n -k3,3 > "$PREFIX.filt_on_cohort.$EXT"

```

**Comment by brunogrande** [comment]
@awchrist, which version of STAR are you using? I'm now using the latest version, v2.4.2a. In my previous issue, I was using v2.4.1d. If you're using the latter version, that would explain why reindexing the genome worked for you.

**Comment by awchrist** [comment]
@brunogrande That must be it. I am using v2.4.2a. 
I'm starting to get concerned about my lack of filtering on the SJ.out.tab files. 
I thought that star does your filtering step 1 and 3 for you though.

**Comment by alexdobin** [comment]
Hi @awchrist, @brunogrande

sorry for belayed reply. I was on vacation with limited connectivity.
Have you tried increasing --limitSjdbInsertNsj?
By default, this parameter is set to 1,000,000, and you collected more junctions from all samples (2,812,730) - it might have caused the seg-fault.
On the other hand, this number of novel junctions is huge compared to annotated junctions (~300,000), and it may slowdown the 2nd pass mapping. I would definitely filter out the chrM junctions, and would probably filter out non-canonical junctions supported by few reads (say less than 5 or 10).

Cheers
Alex
