### ISSUE TITLE
Of Reads unmapped: too short 30%-40%

### ISSUE THREAD

**Issue by stevehxf** [alexdobin/STAR#560]
Hi Alex,

Due to the low amount of RNA yield, the library was built by pre-amplification. Raw data went through adaptors trimming by trim galore.

No matter the data was pre-trimmed or not. High % of reads unmapped: too short - from 35%-45%.

Here is one of the log I got from adaptor-trimmed fq.

Could you give me some advices? Thank you so much!

Best,
Steve

_____
                                 Started job on |	Feb 05 16:56:03
                             Started mapping on |	Feb 05 16:56:30
                                    Finished on |	Feb 05 16:59:39
       Mapping speed, Million of reads per hour |	113.01

                          Number of input reads |	5933158
                      Average input read length |	279
                                    UNIQUE READS:
                   Uniquely mapped reads number |	3318383
                        Uniquely mapped reads % |	55.93%
                          Average mapped length |	253.91
                       Number of splices: Total |	1058304
            Number of splices: Annotated (sjdb) |	967892
                       Number of splices: GT/AG |	1005636
                       Number of splices: GC/AG |	11300
                       Number of splices: AT/AC |	658
               Number of splices: Non-canonical |	40710
                      Mismatch rate per base, % |	0.73%
                         Deletion rate per base |	0.01%
                        Deletion average length |	1.66
                        Insertion rate per base |	0.02%
                       Insertion average length |	1.51
                             MULTI-MAPPING READS:
        Number of reads mapped to multiple loci |	485650
             % of reads mapped to multiple loci |	8.19%
        Number of reads mapped to too many loci |	727
             % of reads mapped to too many loci |	0.01%
                                  UNMAPPED READS:
       % of reads unmapped: too many mismatches |	0.00%
                 % of reads unmapped: too short |	35.82%
                     % of reads unmapped: other |	0.05%
                                  CHIMERIC READS:
                       Number of chimeric reads |	0
                            % of chimeric reads |	0.00%

**Comment by alexdobin** [comment]
Hi @stevehxf 

I would recommend a couple of tests:
1. Map read1/read2 separately (if your reads are PE).
2. Collect unmapped reads and BLAST them to check for contamination.

Cheers
Alex

**Comment by stevehxf** [comment]
Hi Alex,

Thanks for the reply.

I tried both.

1. Did not change very much.
2. I tried blast some of the unmapped reads. Looks like the middle part of the reads could be mapped to human transcripts completely. But the 5' or 3' end could not.

3. I used --outFilterScoreMinOverLread 0.5 --outFilterMatchNminOverLread 0.5. And it aligned much better. Uniquely mapped reads % went up to nearly 80%.

Any further suggestion?

Thank you!
Steve

**Comment by alexdobin** [comment]
Hi Steve,

did you see any pattern in the unmapped portions of the reads, e.g. adapter sequences, poor sequencing quality, etc?
Ideally, you want to figure out what went wrong with the sequence and fix it (e.g. by trimming) before mapping.
Reducing mapped length stringency by reducing --outFilterScoreMinOverLread  and --outFilterMatchNminOverLread will help, however, it may also bring in incorrect alignments.

Cheers
Alex

**Comment by stevehxf** [comment]
Hi Alex,

I am quite new in this field. Could you advise how can I clearly figure out the pattern? Is there any tools that I can analyze instead of blast one by one?

Actually, before I did mapping, I trimmed low Q bases (score<20) and adapter sequence by Trim Galore.

Thanks!
Steve

**Comment by alexdobin** [comment]
Hi Steve,

figuring out the pattern is more of an art. Your case - both read ends mapping poorly is unusual. Typically, the mappability problems arise at the 3' ends - e.g. untrimmed adapters or poor sequencing quality.
I would recommend FastQC tools for checking the general sequencing quality, and nucleotide overrepresentation at the ends.
It might be easier to use BLAT (UCSC genome browser) than BLAST, since the reads are mapping to the human genome.
The first question I would try to answer - is there a common motif for unmapped portions of the read, on 5' and 3'.

Cheers
Alex
