### ISSUE TITLE
Flag for no insertions or deltions

### ISSUE THREAD

**Issue by erl1234** [alexdobin/STAR#563]
I'm using STAR and having a little trouble trying to figure out how to map reads without allowing any insertions or deletions. Essentially, I am trying to map reads uniquely to the genome without any mismatches, insertions or deletions.
Thanks for your help

**Comment by alexdobin** [comment]
Hi @erl1234 

to prohibit indels you need to set:
--scoreDelOpen -1000    --scoreInsOpen -1000

Cheers
Alex
