### ISSUE TITLE
STARsolo: process BC+UMI reads with wrong length [enhancement]

### ISSUE THREAD

**Issue by landesfeind** [alexdobin/STAR#565]
Hi Alex,

would it be possible to add a solo*-parameter to only warn if length of barcode and UMI does not match the expected read length?

In our sequencing protocol we sequence(d) an additional nucleotide (i.e., BC+UMI+1). Initially we thought about correcting for 1bp insertion-sequencing errors.

This is a minor issue as we can strip the BC/UMI-read before STAR processing and it is more a convenience. 

Thanks a lot for your work,
Manuel

**Comment by alexdobin** [comment]
Hi Manuel

this is a good suggestion, thanks. I can implement a user-definable barcode read length, with a default value of 0 (read length must be equal to CB+UMI), and a special value of -1 (no check). I wanted to have this check by default in case RNA read and barcode read are switched.

Cheers
Alex

**Comment by landesfeind** [comment]
Hi Alex, your idea is even better because a length-check is clearly beneficial and warnings would pollute stdout in a way that "true/reasonable" warnings can easily be missed. Thanks a lot for your help!

**Comment by alexdobin** [comment]
Hi Manuel,

I have implemented the --soloBarcodeReadLength option for cases where --soloCBlen + --soloUMIlen is not equal to the barcode read length. You can either specify the true barcode read length; or 0, which omits the read length check altogether.
Please try it from Github [master](https://github.com/alexdobin/STAR/archive/master.zip).
I will make 2.7.0c release in a couple of days.

Cheers
Alex

**Comment by landesfeind** [comment]
Hi Alex,
I just gave it a try and it worked perfectly well for our use-case! 
Thanks a lot,
Manuel

**Comment by landesfeind** [comment]
Solved by 1f62384bf1c3be2312a2fe2ef29a15c8906f76b0
