### ISSUE TITLE
Trouble understanding XS tag

### ISSUE THREAD

**Issue by sagnikbanerjee15** [alexdobin/STAR#567]
Hello Alex,

I am aligning single ended unstranded RNA-Seq reads to the Arabidopsis genome. I have switched on all the tags using the argument -outSAMattributes NH HI AS nM NM MD jM jI XS ch. I went into the bam to check on some of the alignments and I found that the XS tag for some alignments have been set to + even though the read itself was aligned to the reverse strand. It seems to me that I am missing something here.

For example,

SRR1046909.5436064      16      1       3834    255     80M82N22M       *       0       0       CGAGGGAAACACTAGCCGCGACGTTGAAGTAGCCATCAGCGAGGTCAACATCTGTAGCTACGATCCTTGGAACTTGCGCTTCCAGTCAAAGTACAAATCGAG  %%%%%%%?;?:=?A8?BEBFEDDGD@EDEBGHHGEBGGGHGHHHHHHGHHHHHHHHHHHHGHHHHHH@>HHFGGGGHHGHHHHHHDGHHHHGHHEHHHHHHH  NH:i:1  HI:i:1  AS:i:98 nM:i:1  NM:i:1  MD:Z:3A98       jM:B:c,1        jI:B:i,3914,3995        XS:A:+

Thank you.

**Comment by alexdobin** [comment]
Hi Sagnik,

The XS flag is assigned only for spliced reads based on the intron motif of the junction.
For an unstranded library, the read may be sequenced from the 1st cDNA strand (opposite to RNA), but the intron motif allows to determine the actual RNA strand.

Cheers,
Alex

**Comment by sagnikbanerjee15** [comment]
Hi Alex,

Thanks for the explanation.

Thank you.
