### ISSUE TITLE
STAR aligner throws Segmentation fault after load GTF 

### ISSUE THREAD

**Issue by visivas** [alexdobin/STAR#570]
Hi, I am using STAR 2.7.0a. I indexed a GenCode human reference genome with the following command.
STAR --runThreadN 12 --runMode genomeGenerate --genomeDir $starIndexDir --genomeFastaFiles $fastaFile --sjdbGTFfile $gtfFile --sjdbOverhang 100

Then, I ran an RNA-Seq processing only the top 10000 reads in the fastq file with the following command.
STAR --runMode alignReads --runThreadN 1 --genomeDir $genomeDir --readFilesIn ${fq1} ${fq2} --readFilesCommand zcat --sjdbGTFfile $gftFile --readMapNumber 10000 --limitBAMsortRAM 10000000000 --outFileNamePrefix ${srrId}/${srrId}. --outReadsUnmapped Fastx --outSAMtype BAM SortedByCoordinate --outSAMattributes All --quantMode TranscriptomeSAM GeneCounts --outSAMattrRGline ID:$srrId --outFilterType BySJout  --alignWindowsPerReadNmax 200000 --genomeLoad LoadAndKeep

After 2-3 mins the job fails with a seg fault. 
Feb 15 18:34:41 ..... started STAR run
Feb 15 18:34:41 ..... loading genome
Feb 15 18:35:00 ..... processing annotations GTF
/var/spool/slurmd/job17110119/slurm_script: line 14: 57633 Segmentation fault      (core dumped) STAR --runMode alignReads --runThreadN 1 --genomeDir $genomeDir --readFilesIn ${fq1},${fq2} --readFilesCommand zcat --sjdbGTFfile $gftFile --readMapNumber 10000 --limitBAMsortRAM 10000000000 --outFileNamePrefix ${srrId}/${srrId}. --outReadsUnmapped Fastx --outSAMtype BAM SortedByCoordinate --outSAMattributes All --quantMode TranscriptomeSAM GeneCounts --outSAMattrRGline ID:$srrId --outFilterType BySJout --alignWindowsPerReadNmax 200000

Please let me know if need to regenerate indices with a lower --genomeChrBinNbits or --genomeSAindexNbases?

Thanks
Siva

**Comment by alexdobin** [comment]
Hi @visivas 

if you do not need STARsolo options, please use the latest stable version 2.6.1d

If you want to try STARsolo, please use the patch from Github master.

Cheers
Alex
