### ISSUE TITLE
Manual: STARsolo parameter `--soloOutFileNames` inverted description.

### ISSUE THREAD

**Issue by romanhaa** [alexdobin/STAR#572]
Just noticed that in the manual the description and default options for the STARsolo parameter `--soloOutFileNames` contradict each other. The 2nd and 3rd word are inverted. I don't know which of the two is correct (yet) but probably one is :)

**Comment by alexdobin** [comment]
Hi Roman,

thanks for pointing this out, I have fixed the manual (the text in the description had the lines inverted) in the[ 2.7.0d](https://github.com/alexdobin/STAR/releases/tag/2.7.0d).

Cheers
Alex

**Comment by romanhaa** [comment]
Thanks, I also found out today which was the right order :D

And btw, I already said it on Twitter but STARsolo is absolutely fantastic!
