### ISSUE TITLE
Segmentation fault after mapping started

### ISSUE THREAD

**Issue by dlsoltero** [alexdobin/STAR#573]
I'm testing STAR-2.7.0d on mac OS (pre-compiled version).

I made a test chromosome and test fastq file, constructed the index without problems then I run

$ STAR --runThreadN 1 --runMode alignReads --genomeDir ref --readFilesIn reads.fastq 

Feb 21 22:33:03 ..... started STAR run
Feb 21 22:33:03 ..... loading genome
Feb 21 22:33:05 ..... started mapping
Segmentation fault: 11

Any ideas?

p.d. I was the same error with the STAR-2.6.1d version.

**Comment by alexdobin** [comment]
Hi @dlsoltero 

please try the latest patch from Github [master](https://github.com/alexdobin/STAR/archive/master.zip).
Or fall back to the latest stable version [2.6.1d](https://github.com/alexdobin/STAR/releases/tag/2.6.1d).

Cheers
Alex

**Comment by dlsoltero** [comment]
Hi @alexdobin ,

I tried both version, and got exactly the same error with the precompiled macOS versions.

Additionally, I tried to install gcc with brew to compile it myself and got:

`
$ brew install gcc --without-multilib
`
Error: invalid option: --without-multilib

**Comment by dlsoltero** [comment]
Hi again,

So the problem apparently was that the sample reads I used were too short. I tried a length of 100 nt and if worked fine. So, I don't know if STAR doesn't really care about short reads or there may be a little bug there.

**Comment by alexdobin** [comment]
Hi @dlsoltero 

STAR should be able to work with short reads, it may not output alignments, but it should not crash.
Can you select a few reads which generate the error, and send them to me?

Cheers
Alex

**Comment by dlsoltero** [comment]
I used these files:

chromosomes.fas
> chr1A
> GCTAAATCGGCACTAGCTTGGACCTAAATGCGGTACACCGACCCTGACTA
> chr1B
> GCCAAATCGGCACTAGCTTGGACCTAAATGCGGTACACCGACCCTGAGTA
> 

reads.fastq:

> @seq1#0/1
> GACCTAAATGCGGTACACCGACCCTGACTA
> +
> \ccac\cccccccc\c^_ccSc\c\cBcZa
> @seq2#0/1
> ATCAAAAACGAGTCCAAAACCAGTCACACC
> +
> cac\ccaaccYY[acaQccccac[Yacc^c


`STAR --runThreadN 1 --runMode genomeGenerate --genomeDir ref --genomeFastaFiles chromosomes.fas `

`STAR --runThreadN 1 --runMode alignReads --genomeDir ref --readFilesIn reads.fastq 
`

**Comment by alexdobin** [comment]
What is the total genome size?
For small genomes, you need to scale --genomeSAindexNbases at the genome generation step as log2(GenomeLength)/2 - 1, e.g. if your total genome is 1M bases, you need --genomeSAindexNbases 9 .
If the seg-faults still occur, you may need to reduce this value further.

**Comment by ibrahimkurt** [comment]
Hi Alex,

I have a 1x50 bp single-end RNA-seq data at hand and running:

```
STAR --genomeDir /Users/ibrahimkurt/data/genomes/ \
    --readFilesCommand "gzip -d -c -f" \
    --readFilesIn /Users/ibrahimkurt/data/test_data/Castle_2014_BMC/ERR424933.CT26_RL2_L003_R1_001.fastq.gz \
    --outSAMmode Full \
    --outSAMattributes Standard \
    --outSAMunmapped None \
    --outReadsUnmapped Fastx \
    --outFilterMismatchNoverLmax 0.02 \
    --runThreadN 8 \
    --outSAMtype BAM SortedByCoordinate \
    --outFileNamePrefix ERR424933.
```

I am getting the same `Segmentation fault: 11` error. Googling the error made me think it was due to the system running out of memory. (https://stackoverflow.com/questions/12762944/segmentation-fault-11) But then I ran into this post. I am running STAR w/ mm9 on a machine w/ 16GB RAM. Do you think I also need the `--genomeSAindexNbases `adjustment? I think mm9 is 2,716,949,182 bases in length.

**Comment by ibrahimkurt** [comment]
Just tried w/ STAR version 2.7.9a and so far seems like working.
