### ISSUE TITLE
Problems about building genome index with large genome

### ISSUE THREAD

**Issue by Feilijiang** [alexdobin/STAR#574]
Hi,
 I used the STAR2.5.2a to build the genome index with a large genome. However, in the genomeDir directory, it produced many SA files like SA_14, SA_19 and so on ,and then it terminated. I set the RAM as the computer asked and I used the gff file with the option --sjdbGTFtagExonParentTranscript Parent.
 The axolotl genome is 32g and is it the reason?  Do you have some suggestions? Thank you very much.

STAR --runThreadN 96 --runMode genomeGenerate --genomeDir ./genomeDir/ --genomeFastaFiles ./GenebankGenome_Axolotl/GCA_002915635.2_ASM291563v2_genomic.fasta --sjdbGTFfile ./GenebankGenome_Axolotl/GCA_002915635.2_ASM291563v2_genomic.gff --sjdbGTFtagExonParentTranscript Parent --limitGenomeGenerateRAM 142784620586

**Comment by alexdobin** [comment]
Hi Feilijiang

32Gbase genome will require a lot of RAM - how much do you have?

Cheers
Alex

**Comment by Feilijiang** [comment]
I submit the job to a lsf system. and I use 3 server node and each node has 250G memory.

**Comment by alexdobin** [comment]
I am not familiar with lsf system.
Not sure if memory can be shared among 3 nodes efficiently.
Assuming the RAM limit is 250GB, you would need to use --genomeSAsparseD 2 to fit 32Gbase genome.
Also, how many contigs does the genome have?
If it does not work, please send me the Log.out file.

Cheers
Alex

**Comment by Feilijiang** [comment]
Adding --genomeSAsparseD 2 really resolved the problem. Thank you very much, Alex.

**Comment by alexdobin** [comment]
Sure!
You can further reduce the RAM requirements by increasing this value, at the expense of slower mapping speed.

**Comment by alexdobin** [comment]
Hi @zhongjixing 

sorry for the delayed reply.
This large genome will require a large amount of RAM ~200GB.
I would recommend limiting number of threads to 20:
```--runThreadN 20```.
Also, please try ```--genomeSuffixLengthMax 300```, this will help if you have many identical sequences in the genome.
Finally, increasing ```--genomeSAsparseD``` will also be helpful as it will reduce RAM requirements and speed-up index generation.
