### ISSUE TITLE
--readStrand in manual

### ISSUE THREAD

**Issue by freedog8** [alexdobin/STAR#575]
hi, 
there is a --readStrand option in the manual but cant't be used~~

output:
EXITING: FATAL INPUT ERROR: unrecoginzed parameter name "readStrand" in input "Command-Line-Initial"
SOLUTION: use correct parameter name (check the manual)

**Comment by alexdobin** [comment]
Hi @freedog8 

thanks for reporting it - this option is listed erroneously in the manual, I will remove it from the manual.
There is --soloStrand option, but it only applies to solo* outputs.

Cheers
Alex
