### ISSUE TITLE
duplicate reads filtering in "--waspOutputMode" 

### ISSUE THREAD

**Issue by Zliu-Omics** [alexdobin/STAR#576]
Thanks for integrating WASP algorithm! Just want to figure out how the duplicated reads were treated in the "--waspOutputMode" option. 

As in the original WASP paper, the duplicated reads were discarded randomly. I was wondering whether STAR also implemented this feature?  

Thanks,
Zhipeng

**Comment by alexdobin** [comment]
Hi @Zliu-Omics 

STAR-WASP maps reads to varints one by one, without using information from other reads - so it does not perform de-duplication. After this mapping is done, you can extract the reads that passed the WASP filtering (i.e. have vW:1 tag) from the BAM file, and deduplicate them using samtools rmdup command, or STAR deduplication commands.

Cheers
Alex

**Comment by khandaud15** [comment]
Hi Alex, I just tried waspoutmode on one 3 RNA seq samples, not sure when i did without waspoutmode, it took like 45 min to finish the alignment. But when I tried waspoutmode, Took 6 hours to complete. Is it normal when we do this, I am worried about the computation time. As well as does the waspoutmode perform mapping and remapping again to give the final output bam file. Or we need to use wasp intersecting-snps.py to get the filtered read and again remap after getting ban file. 

Thanks

**Comment by alexdobin** [comment]
Hi @khandaud15 

STAR-WASP remaps the reads that overlap variants, so you do not need to do the WASP re-mapping. For a typical case of personal variants, STAR-WASP does not slowdown significantly. However, if you have a lot of variants that are close to each other (i.e. many reads overlap multiple variants), it make slowdown the computation significantly, as it need to remap all possible combinations ~2^N where N is the number of variants per read.

Cheers
Alex
