### ISSUE TITLE
How to run `2-pass` mapping in STARsolo mode?

### ISSUE THREAD

**Issue by yech1990** [alexdobin/STAR#581]
For mutation calling within single cell RNA-seq data

**Comment by alexdobin** [comment]
Hi YC,

there appear to be some issues with 2-pass mapping for STARsolo, I am looking into it.

Cheers
Alex

**Comment by alexdobin** [comment]
Hi YC,

I have fixed the STARsolo problems with 2-pass, please try the patch on GitHub [master](https://github.com/alexdobin/STAR/archive/master.zip). If it works for you, I will release it as 2.7.0f.

Cheers
Alex

**Comment by yech1990** [comment]
Thank you @alexdobin ,

I will test it on my data.
