### ISSUE TITLE
Reduce the memory for wheat and the shared memory to used

### ISSUE THREAD

**Issue by 909089617xx** [alexdobin/STAR#583]
Hi,
New, i use STAR to deal with the RNA-seq data from wheat. But wheat genome is very large(15G),so there may be some tricks that i can use to make it faster and use less resources.
1.fist, i want to use this parameter --genomeChrBinNbits
you say these parameter should calculate by this min(18,log2[max(GenomeLength/NumberOfReferences,ReadLength)])
but in some messages you reply use this 
log2(averageTranscriptLength)-12
I want to know which one should i choose ?What do you recommend for this value in wheat?
2. --genomeLoad 
when i use LoadAndKeep and LoadAndExit .the genome seems like being shared,but when i run another file the genome is still need to be loaded.
![image](https://user-images.githubusercontent.com/33317454/54129528-689e0a80-4449-11e9-9015-f598572efe4e.png)
I am looking forward for your apply!
Best wishes!
Jun

**Comment by alexdobin** [comment]
Hi Jun,

--genomeChrBinNbits should be chosen as min(18,log2[max(GenomeLength/NumberOfReferences,ReadLength)])
GenomeLength/NumberOfReferences = average length of the chromosome/scaffold.
Also, you can reduce the index size with --genomeSAsparseD 2 (or even bigger numbers) at some expense to mapping speed.

For shared genome, it seems like genome was loaded OK. For sequential runs, you need to use --genomeLoad LoadAndKeep to use the genome that's already loaded. Actually, you do not need to use LaodAndExit at all - just use LoadAndKeep for all jobs. After some time, the genome gets paged out of RAM, so you would need to run --genomeLoad Remove, and then run all the jobs with --genomeLoad LoadAndKeep.

Cheers
Alex

**Comment by 909089617xx** [comment]
Hi,Alex,
Thank you very much.I have solved it!
Cheers
jun
