### ISSUE TITLE
Running STARSolo on Drop-Seq/Seq-Well Data

### ISSUE THREAD

**Issue by andyrussell** [alexdobin/STAR#584]
Hi Alex, 

Apologies if I have missed this somewhere but I am trying to run STARsolo on Seq-Well data (Drop-Seq has the same format), but I can't seem to find a suitable file for the --soloCBwhitelist flag. The barcodes in this method are split-and-pool randomly generated barcodes of 12 bp - would you suggest generating a whitelist file containing all possible combinations (or is it possible to create this file for use with STARsolo)? 

Thank you for any help you can give in advance, 

Andy

**Comment by alexdobin** [comment]
Hi Andy,

this is a good question that I am actually thinking about. At the moment, the whitelist is required. If you provide a list of all possible 12b barcodes, there will be no 1-mismatch error correction (if needed, this correction will have to be done downstream). Effectively, it means that all CB sequences are accepted -this is the easiest option to implement directly into STAR.

Cheers
Alex

**Comment by alexdobin** [comment]
Hi Andy

I have released a branch 
https://github.com/alexdobin/STAR/tree/solo_GeneFull
that has an option 
--soloCBwhitelist None
which works without the whitelist, so that you do not need to create a list of all possible barcodes. Error correction is not done in this case, and all distinct CBs are accepted.

If you decide to test it out, please let me know if it works or has any issues.

Cheers
Alex

**Comment by wir963** [comment]
@alexdobin I am also interested in running STARsolo on Seq-Well data. Did that branch make it into master? Do you have any updated suggestions about running STARsolo for Seq-Well data?

**Comment by alexdobin** [comment]
Hi @wir963 

if my understanding of the Seq-Well protocol is correct, you should be able to run it with `--soloCBwhitelist` None and properly adjusted `--soloCBstart --soloCBlen soloUMIstart --soloUMIlen`

Cheers
Alex

**Comment by wir963** [comment]
Sounds good - I'll give that a try. And to confirm, there (understandably) won't be any error correction to the cell barcodes?

**Comment by alexdobin** [comment]
Correct: without whitelist, there is no error correction. In principle, you can do the 1st pass without error correction, then select the cells above a certain threshold to be the "whitelist", and re-run with the whitelist - however, I am not sure if it's worth it, as you will add ~1-2% of reads to the whitelist cells (judging from 10X data), while at the same time you will be risking creating artificial doublets.
