### ISSUE TITLE
star output empty bam but log file is ok

### ISSUE THREAD

**Issue by jiaojiaoguo1205** [alexdobin/STAR#586]
Hi alexdobin

I used star to map eCLIP reads to repbase database but got empty bam file. However, the final.log.out and log.out seem fine. It said around 40% uniquely mapped reads. so it should output non-empty bam file. Could you give me any help? Thank you very much.

**Comment by alexdobin** [comment]
Hi @jiaojiaoguo1205 

please send me the Log.out file.

Cheers
Alex

**Comment by jiaojiaoguo1205** [comment]
> Hi @jiaojiaoguo1205
> 
> please send me the Log.out file.
> 
> Cheers
> Alex

Hi Alex, the log files are attached .Thank you very much.

[bamLog.final.out.txt](https://github.com/alexdobin/STAR/files/2971539/bamLog.final.out.txt)
[bamLog.out.txt](https://github.com/alexdobin/STAR/files/2971540/bamLog.out.txt)

**Comment by alexdobin** [comment]
Hi @jiaojiaoguo1205 

since you used --outStd BAM_Unsorted, the BAM was directed into stdout, not the file. If you remove this option, you will alignments in the BAM file.

Cheers
Alex

**Comment by jiaojiaoguo1205** [comment]
Hi Alex,

Thanks, I will try it. But I used --outStd BAM_Unsorted in other mapping (mapping to the hg19 not repbase), it can output the bam file. Is there any other possible reason? Thank you.

**Comment by jiaojiaoguo1205** [comment]
Hi Alex,
Sorry I found one mistake in my code. It missed one pipe in the second to last line so it didn't output to my bam file.

**Comment by alexdobin** [comment]
Hi @jiaojiaoguo1205 

thanks for letting me know.

Cheers
Alex
