### ISSUE TITLE
modifying the tag HI in the BAM alignment file to start at 0 is no longer needed starting at stringtie v1.1.0 release

### ISSUE THREAD

**Issue by freedog8** [alexdobin/STAR#589]
![image](https://user-images.githubusercontent.com/21093659/54434302-e3786580-4768-11e9-92c6-b23e1e280cdf.png)
It seems that the manual is out-of-date ^-^

**Comment by alexdobin** [comment]
Hi @freedog8 

thanks for pointing this out. I guess tool developers need to talk to each other more often.

Cheers
Alex
