### ISSUE TITLE
Extensive runtime

### ISSUE THREAD

**Issue by ctxchris** [alexdobin/STAR#595]
Hi,

I run STAR v2.5.3a on a 3Gbp genome with 130M 2x125bp PE reads in about 2 hours. The genome was not repeat-masked and a GTF file was used for the index construction.

Now I'm running STAR v2.6.1.b on a repeat-masked 1.5Gbp genome with 32M 2x150bp PE reads and no GTF file for the index construction. Options such as intron max, gap max etc. are pretty much the same as are the compute resources. This job is still running for over two days now.
Do you have an idea what could cause the long runtime?

Thanks,
Chris

**Comment by ctxchris** [comment]
Fixed with v2.7.0

**Comment by alexdobin** [comment]
Hi Christian

it's good that it's solved - however, I generally recommend against mapping to masked genomes, as the reads originating from masked regions will be forced to map to other places, which may cause slowdown and false alignments.

Cheers
Alex
