### ISSUE TITLE
Exact meaning of versionGenome in parametersDefault

### ISSUE THREAD

**Issue by wm75** [alexdobin/STAR#596]
I'm trying to understand which genome index version is expected by different STAR versions.
I've noticed that the versionGenome parameter in source/parametersDefault has changed *within* the 2.7.0 release series from `2.7.0c_0213` to `2.7.0d`. Does that mean that genomes built with 2.7.0c have to be rebuilt before using 2.7.0d or higher?

The description of that parameter confuses me. It says 

> latest genome index version compatible with this STAR release. Please do not change this value!

What does `latest` mean here? Does it imply that older versions might also work? Do you mean `earliest` instead, in the sense that STAR may maintain a certain level of backwards-compatibility sometimes so that it may work with different index versions? Or is it saying: there is no later genome version than 2.7.0d, thus, currently STAR 2.7.0d and higher are using the same version?
From looking at the corresponding code, I think it's that last alternative, but could you confirm my assumption?

**Comment by alexdobin** [comment]
Hi Wolfgang,

Good question, thanks for pointing it out!
The precise meaning is:
"There is no later genome version than 2.7.0d, thus, currently STAR 2.7.0d and higher are **generating and** using the same version"
I guess another way to say it is:
"Earliest version of the STAR whose genome index is compatible with the current version"

This defines backward compatibility, but there is no forward compatibility (i.e. 2.7.0a cannot use genome generated by 2.7.0d).

Also linking the Galaxy-STAR thread here; will reply to it with more details shortly.
https://github.com/galaxyproject/tools-iuc/issues/2316

Cheers
Alex

**Comment by bounlu** [comment]
@alexdobin This still creates ERROR when generating genome index with 2.7.0f though:

```
STAR version=2.7.0f
versionGenome                     2.7.0d
```

```
2019-05-02 20:35:53,311 MainThread WARNING toil.leader: Q/E/job0Av86V    EXITING because of FATAL ERROR: Genome version: 20201 is INCOMPATIBLE with running STAR version: 2.7.0f
2019-05-02 20:35:53,311 - toil.leader - WARNING - Q/E/job0Av86V    EXITING because of FATAL ERROR: Genome version: 20201 is INCOMPATIBLE with running STAR version: 2.7.0f
2019-05-02 20:35:53,311 MainThread WARNING toil.leader: Q/E/job0Av86V    SOLUTION: please re-generate genome from scratch with running version of STAR, or with version: 2.7.0d
```

**Comment by alexdobin** [comment]
Hi @bounlu,

you need to re-generate genome (--runMode genomeGenerate) with the version 2.7.0d or later.

Cheers,
Alex
