### ISSUE TITLE
STAR solo 2.7.0e

### ISSUE THREAD

**Issue by rbm78** [alexdobin/STAR#599]
Trying to run STARsolo on STAR 2.7.0.e with following commands
screen STAR --runThreadN 
                     --genomeDir 
                     --readFilesIn 
                     --readFilesCommand zcat 
                     --outFileNamePrefix 
                     --sjdbGTFfile
                     --soloType Droplet 
                     --soloCBwhitelist 
                     --soloUMIlen 12

Throwing error
EXITING: FATAL INPUT ERROR: unrecoginzed parameter name "soloType" in input "Command-Line-Initial"
SOLUTION: use correct parameter name (check the manual)

**Comment by alexdobin** [comment]
Hi @rbm78 

please make sure that you are running the 2.7.0e - you can check the first line of the Log.out file.

Cheers
Alex
