### ISSUE TITLE
Sorry: Again std::bad_alloc

### ISSUE THREAD

**Issue by balthasar0810** [alexdobin/STAR#601]
Dear all, I am trying to build a genome index for hg38. Allocated 100GB of RAM before:
STAR/bin/Linux_x86_64/STAR 
--runMode genomeGenerate 
--runThreadN 4
--genomeDir ./Homo_sapiens.GRCh38.dna.toplevel.STAR/ 
--genomeFastaFiles Homo_sapiens.GRCh38.dna.toplevel.fa 
--sjdbGTFfile ./gene_models/Homo_sapiens.GRCh38.95.gtf 
--sjdbOverhang 100 
--genomeSAsparseD 2 
--limitGenomeGenerateRAM 50000000000
I am getting std::bad_alloc...
Any help would be appreciated! Chris

**Comment by alexdobin** [comment]
Hi @balthasar0810 

the *toplevel* fasta is too big because it contains alternative haplotypes and patches.
Please use the *primary_assembly* fasta, e.g.
ftp://ftp.ensembl.org/pub/release-95/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz

Cheers
Alex

**Comment by balthasar0810** [comment]
Thanks so much!!
