### ISSUE TITLE
Raw counts from paired-end alignments compared with TPMCalculator

### ISSUE THREAD

**Issue by r78v10a07** [alexdobin/STAR#603]
Hi,
We have use the STAR with the option --quantMode GeneCounts but the resulting counts are no even close to the number of reads in the BAM files.

Could you, please, have a look at this issue https://github.com/ncbi/TPMCalculator/issues/41 and let us know your opinion?

Thanks,
Roberto

**Comment by alexdobin** [comment]
Hi Roberto,

STAR counts should be identical to htseq-count's with the same strand option.
If you find cases where this is not true, please send me an example: STAR BAM file, ReadsPerGene, and htseq-count output.

Cheers
Alex

**Comment by r78v10a07** [comment]
Hi Alex,
Thanks for you response. 
It is clear to me now that STAR counts reads in the same strand, therefore it should be approximately half of the properly paired reads that TPMCalculator counts.
No need of extra test. I'm closing the issue. 
Thanks!!
Roberto

**Comment by alexdobin** [comment]
STAR actually generates the counts for 3 types of strandedness (unstranded, reverse, forward), so you can pick up the right one for comparisons.
