### ISSUE TITLE
indrop

### ISSUE THREAD

**Issue by BhaktiDwivedi** [alexdobin/STAR#605]
Hi,
Can I use STARsolo algorithm for single cell RNA sequencing data from Indrop (1CellBio)?
Thank you for your help.

**Comment by alexdobin** [comment]
Hi Bhakti,

I think it might work as the technologies are similar.
If you can point me to a document where the read1/read2 are described in detail in terms of locations of Cell Barcode and UMI, I can suggest the required parameters.

Cheers
Alex

**Comment by BhaktiDwivedi** [comment]
Hi Alex,


Thank you for your response. I have attached the barcode structure and paper.


Regards,

Bhakti


________________________________

**Comment by alexdobin** [comment]
Hi Bhakti,

the attachment did not work - I cannot see it. Could you please try again - I think you need to do it via GitHub site.

Thanks!
Alex

**Comment by BhaktiDwivedi** [comment]
Sure. Sorry about that.

________________________________

**Comment by BhaktiDwivedi** [comment]
[
![barcode_structure](https://user-images.githubusercontent.com/10574965/55630256-41ee9d80-5783-11e9-878c-99820cfc8b0d.png)
](url)

**Comment by alexdobin** [comment]
Hi Bhakti,

Thanks!
Is there some sequence between barcode1 and barcode2?
Does read2 looks like:
Barcode1_8-12b|SomeSequence|Barcode2_8b|UMI_6b
If so, what is the length of the sequence in the middle?

Also, is there a "whitelist" for Barcode1/2?

Cheers
Alex

**Comment by BhaktiDwivedi** [comment]
Here is the link to the paper, if this helps answer any of the above questions.
https://iccb.med.harvard.edu/files/iccb/files/zilionis_et_al-2016-nature_protocols.pdf

Let me take a look.
Thank you.

**Comment by alexdobin** [comment]
The danger is that the commercial protocol might be somewhat different from the one described in the paper, in particular in terms of particular oligos that they are using.
Could you inquire directly with 1CellBio about it?

**Comment by BhaktiDwivedi** [comment]
ok

**Comment by BhaktiDwivedi** [comment]
Hi Alex,

Here it is:

1. Is there some sequence between barcode1 and barcode2? ### Yes
2. Does Read2 looks like: Barcode1_8-12b|SomeSequence|Barcode2_8b|UMI_6b ### Yes
3. If so, what is the length of the sequence in the middle? ### 22 bp long
4. And here is the whitelist" for Barcode1/2? 
[
[Barcode seqs (1).xlsx](https://github.com/alexdobin/STAR/files/3049492/Barcode.seqs.1.xlsx)
](url)

Thanks,
Bhakti

**Comment by alexdobin** [comment]
Hi Bhakti,

thanks a lot, I am getting closer to understanding it.
If the length of barcode1 fluctuates, then the read1 should contain some constant adapter sequence at the end as well?
This does complicate things somewhat, as it seems we cannot just specify the start and and end of the barcode(s). on read1.

Could you share with me a small set of barcode reads, a few thousand to a million?

Cheers
Alex

**Comment by c5creative** [comment]
FWIW, there is another project that allows you to export inDrop data to 10X - see https://github.com/caleblareau/indRop. So it'd be interesting to use STARsolo on such converted data...

**Comment by BhaktiDwivedi** [comment]
Hi Alex,
My apologies for the delay in my response. Is there an email that I send this to you instead of posting here? Please let me know. Thank you so much.
Regards,
Bhakti

**Comment by alexdobin** [comment]
Hi Bhakti,

no worries, I am just gearing up to implement complex barcode configurations. I hope to encode these complex configurations as a string similar to SAM CIGAR.

Cheers
Alex

**Comment by alexdobin** [comment]
My email is dobin at cshl dot edu

**Comment by BhaktiDwivedi** [comment]
Thank you. Just sent it.

**Comment by alexdobin** [comment]
Hi Bhakti,

I am sorry for the long delay - took me much longer to code it than I hoped...
The inDrop (and other "complex" barcodes) are implemented on the soloDevelop branch:
https://github.com/alexdobin/STAR/tree/soloDevelop

The following parameters have to be specified for inDrop data:
--soloType CB_UMI_Complex   --soloCBmatchWLtype 1  

adapter
--soloAdapterSequence GAGTGATTGCTTGTGACGCCTT   --soloAdapterMismatchesNmax 2 

whitelists for each cell barcode - the two columns of the from the excel file in your post:
--soloCBwhitelist inDropCB1.txt   inDropCB2.txt

positions of the two CBs and UMI
--soloCBposition 0_0_2_-1   3_1_3_8      --soloUMIposition 3_9_3_14

I have run it on your test example, as well as on publicly available inDrop data, and it seems to perform well.

If you decide to test it, please let me know how it goes.

Cheers
Alex

**Comment by BhaktiDwivedi** [comment]
Hi Alex,

Thank you so much for implementing this feature !

Let me run it and I will get back to you soon.

Regards,
Bhakti
________________________________

**Comment by piloter2** [comment]
Hi Alex,

We are trying to identify RNA-seq. reads from the Indrop method.
We've met error messages when we run your codes on my sample.
The current code I am using looks life this:

(base) van@gogh:/media/van/rawdata/human2$ STAR --soloType CB_UMI_Complex --soloCBwhitelist gel_barcode1_list.txt gel_barcode2_list.txt --soloCBposition 0_0_2_-1 3_1_3_8 --soloUMIposition 3_9_3_14 --genomeDir /media/van/rawdata/index/STAR_Homo_sapiens/ --runThreadN 12 --readFilesIn /media/van/rawdata/human2/Brain_Cancer_L001_R1_001.fastq.gz /media/van/rawdata/human2/Brain_Cancer_L001_R2_001.fastq.gz --outFileNamePrefix /media/van/analysis/human2/STAR/brain_tumor_ --outSAMtype BAM SortedByCoordinate --outSAMunmapped Within --outSAMattributes Standard

EXITING: FATAL INPUT ERROR: unrecognized parameter name "soloCBposition" in input "Command-Line-Initial"
SOLUTION: use correct parameter name (check the manual)

Aug 05 13:46:25 ...... FATAL ERROR, exiting

**Comment by alexdobin** [comment]
Hi @piloter2 

are you using the STAR from the https://github.com/alexdobin/STAR/tree/soloDevelop branch?
If you run
STAR --version
it should show
2.7.2x_0723_soloComplexBarcodes

Cheers
Alex

**Comment by piloter2** [comment]
I'm grateful for your reply.
I've found that the STAR was not updated into the 2.7.2x_0723_soloComplexBarcoded version as you told.

Sincerely,
JayM

**Comment by Qotov** [comment]
@alexdobin , why did you propose soloAdapterMismatchesNmax=2? 

Please have a look at InDrops code, they use a hamming threshold for adapter <=3 https://github.com/indrops/indrops/blob/2ad4669b72ea6ba794f962ed95b778560bdfde4a/indrops.py#L1424

**Comment by alexdobin** [comment]
Hi Alex,

I think I checked 1,2, and 3 mismatches in the adapter for a dataset, and there was no big increase in recovered barcodes for 3 mismatches. Thanks for pointing out that the "official" inDrops pipeline uses 3 mismatches, I will change my recommendations.

Cheers
Alex
