### ISSUE TITLE
Question about --outSAMstrandField, --outFilterIntronMotifs and --outFilterIntronStrands

### ISSUE THREAD

**Issue by wm75** [alexdobin/STAR#606]
From the documentation alone, I'm guessing, but I'm not entirely sure, that combining
`--outFilterIntronMotifs RemoveNoncanonicalUnannotated` and `--outFilterIntronStrands RemoveInconsistentStrands` would produce the same effect as using `--outSAMstrandField intronMotif` (just that the latter would also cause the XS tag to be written).
Is my understanding correct?
Thanks for your help!

**Comment by alexdobin** [comment]
Hi Wolfgang,

strictly speaking,  `--outSAMstrandField intronMotif ` requires that the strand of the read can be determined from splice junctions - either from annotations, or from the intron motif.
This indeed requires the same filtering as  `--outFilterIntronMotifs RemoveNoncanonicalUnannotated` and `--outFilterIntronStrands RemoveInconsistentStrands`. 
However, it will also filter out reads that contain annotated junctions without defined strand.

Cheers
Alex
