### ISSUE TITLE
STAR produces too small BAM files

### ISSUE THREAD

**Issue by galagoz** [alexdobin/STAR#607]
Hi all,

I've been generating BAM files using the STAR command below:

`for ((i=102; i<=305; i++)); do ./STAR --readFilesIn fastq/E08/SRR2930$i.fastq --outSAMunmapped Within --outSAMtype BAM SortedByCoordinate --outSAMmultNmax 1 --genomeDir STARindex --twopassMode Basic --runThreadN 12 --outFileNamePrefix 2930$i; done`

My fastq files are about 180mb and generated BAM files are about 75kb. I checked BAM files using samtools stats --split RG 2930107Aligned.sortedByCoord.out.bam | grep '^SN' and saw the following output for all BAM files:

```
SN  raw total sequences:    0
SN  filtered sequences: 0
SN  sequences:  0
SN  is sorted:  1
SN  1st fragments:  0
SN  last fragments: 0
SN  reads mapped:   0
SN  reads mapped and paired:    0   # paired-end technology bit set + both mates mapped
SN  reads unmapped: 0
SN  reads properly paired:  0   # proper-pair bit set
SN  reads paired:   0   # paired-end technology bit set
SN  reads duplicated:   0   # PCR or optical duplicate bit set
SN  reads MQ0:  0   # mapped and MQ=0
SN  reads QC failed:    0
SN  non-primary alignments: 0
SN  total length:   0   # ignores clipping
SN  bases mapped:   0   # ignores clipping
SN  bases mapped (cigar):   0   # more accurate
SN  bases trimmed:  0
SN  bases duplicated:   0
SN  mismatches: 0   # from NM fields
SN  error rate: 0.000000e+00    # mismatches / bases mapped (cigar)
SN  average length: 0
SN  maximum length: 30
SN  average quality:    0.0
SN  insert size average:    0.0
SN  insert size standard deviation: 0.0
SN  inward oriented pairs:  0
SN  outward oriented pairs: 0
SN  pairs with other orientation:   0
SN  pairs on different chromosomes: 0
```

Also, when I run samtools view 2930107Aligned.sortedByCoord.out.bam command, nothing shows up in terminal.

So, I was wondering what might be cause for the problem here, fastq files themselves or the code that generates BAM files? I know that the question is quite vague, sorry for that, but I'm not sure where to look at to solve the problem.

Then, I ran a single file, STAR worked without any problems on terminal, but gave the same problematic too small BAM file.

```
./STAR --readFilesIn fastq/E08/SRR2930160.fastq --outSAMunmapped Within --outSAMtype BAM SortedByCoordinate --outSAMmultNmax 1 --genomeDir STARindex --twopassMode Basic --runThreadN 12 --outFileNamePrefix 2930160
Apr 04 15:55:10 ..... started STAR run
Apr 04 15:55:10 ..... loading genome
Apr 04 15:55:26 ..... started 1st pass mapping
Apr 04 15:55:29 ..... finished 1st pass mapping
Apr 04 15:55:30 ..... inserting junctions into the genome indices
Apr 04 15:57:23 ..... started mapping
Apr 04 15:57:26 ..... finished mapping
Apr 04 15:57:27 ..... started sorting BAM
Apr 04 15:57:27 ..... finished successfully
```

And [here](https://pastebin.com/0jaai9GZ) is the log.

Thanks,
Gökberk

**Comment by alexdobin** [comment]
Hi Gökberk

it looks like a problem with the fastq file format.
How did you generate the SRR fastq file? What's the output of
$ head fastq/E08/SRR2930160.fastq

Cheers
Alex

**Comment by galagoz** [comment]
Hi Alex,

Thanks a lot for your quick response. I used sra-toolkit and `fastq-dump --split-3 SRRxxx.sra ` command to generate fastq files from SRR files.

```
goekberk@bonobo:~$ head fastq/E08/SRR2930160.fastq
@SRR2930160.1 1_3_1581_F3 length=50
T00022002233000000000220000220000220000000000330000
+SRR2930160.1 1_3_1581_F3 length=50
!JJJJJJJGJJGGEJJEE@..@7DII@D;JJ@@+=+???;;.2'4'$++'2
@SRR2930160.2 1_5_1428_F3 length=50
T12110222310221220132221000000021033300303223331130
+SRR2930160.2 1_5_1428_F3 length=50
!LLKLLKKKLLKKKLLKKKLLKKJKKJJJKKJIIKKIIJJJJI>JKF>:>A
@SRR2930160.3 1_6_61_F3 length=50
T31233310112021113210010132112023032001202321303320
```

Best,
Gökberk

**Comment by alexdobin** [comment]
The sequence lines (2,6,10...) look like Solid sequencer.
STAR does not support Solid reads, unfortunately.

**Comment by galagoz** [comment]
I see, thanks a lot for the feedback!
Cheers.

**Comment by SimonDMurray** [comment]
Hi @alexdobin,

Is it still the case that STAR does not support SOLiD reads?

Thanks,
Simon

**Comment by alexdobin** [comment]
Hi Simon,

STAR does not support SOLiD reads and I am not planning to work on it.
