### ISSUE TITLE
STARsolo: add CB and UB tags in output BAM as in CellRanger.

### ISSUE THREAD

**Issue by ghuls** [alexdobin/STAR#608]
STARsolo: add CB and UB tags in output BAM as in CellRanger.

**Comment by alexdobin** [comment]
This option is in the works, hopefully, will come out in the next release.

**Comment by alexdobin** [comment]
Implemented in soloDevelop branch.

**Comment by MYousry2002** [comment]
@alexdobin 
Hi Alex,
Does STARsolo now output bam files with the CB tag?
Thank you!
best,
Yousry
