### ISSUE TITLE
SNP calling based on STARsolo alignment

### ISSUE THREAD

**Issue by danshu** [alexdobin/STAR#611]
Hi,

I'm interested in SNP calling from 10x data following the GATK protocol. Cellranger does not seem to align reads using 2-pass mode, so I have to extract reads corresponding to filtered barcodes (https://kb.10xgenomics.com/hc/en-us/articles/360022448251-Is-there-way-to-filter-the-BAM-file-produced-by-10x-pipelines-with-a-list-of-barcode), map again using STAR 2 pass mode, and then add back CB, UB and RG tags using custom scripts.
I'm happy to know that you are planning to add CB and UB tags to the bam file (https://github.com/alexdobin/STAR/issues/608). Will you also add RG tags? I'm interested in lane-level RG tags as in cellranger output, while STAR seems to only allow sample-level RG tag.
If these tags are available in STARsolo output, I'd like to set --soloCBwhitelist to filtered cell barcodes from cellranger to generate a bam file ready for snp calling. Any other comments?

Best,
Quan

**Comment by ghuls** [comment]
@danshu 
Just in case it it useful for you.

Recently my samtools patch was merged:
https://github.com/samtools/samtools/commit/253271617e3198a38b3b311935d90616d57e75e3
which allows to filter BAM files based on values associated with a tag.

So https://kb.10xgenomics.com/hc/en-us/articles/360022448251-Is-there-way-to-filter-the-BAM-file-produced-by-10x-pipelines-with-a-list-of-barcode can be addapted like this:

Remove "BC:Z" part from filter file as you set the TAG as the first part of the "-D" parameter of samtools.

$ cat filter.txt

GCCAAATTCACATACG-1
GGACATTGTGATGATA-1
TCAGGTACATTAGGCT-1
...


Replace:

```
# Save the header lines
samtools view -H $BAM_FILE > SAM_header

# Filter alignments using filter.txt. Use LC_ALL=C to set C locale instead of UTF-8
samtools view $BAM_FILE | LC_ALL=C grep -F -f filter.txt > filtered_SAM_body

# Combine header and body
cat SAM_header filtered_SAM_body > filtered.sam

# Convert filtered.sam to BAM format
samtools view -b filtered.sam > filtered.bam
```

with:
```
# CellRanger.
samtools view -D "BC:filter.txt" -o ${BAM_FILE%.bam}.filtered.bam ${BAM_FILE}

# LongRanger.
samtools view -D "BX:filter.txt" -o ${BAM_FILE%.bam}.filtered.bam ${BAM_FILE}
``` 

Greetings,
Gert

**Comment by alexdobin** [comment]
Hi Quan,

by "lane-level" RG tags, do you mean the RG tags specific to each separate FASTQ file that you list in 
`--readFilesIn file1_R1,file2_R1,file3_R1  file1_R2,file2_R2,file3_R2`?
If so, this is already possible with 
`--outSAMattrRGline rg1 , rg2 , rg3 , ...`
Note that in the latter list commas have to be surrounded by spaces.

Cheers
Alex

**Comment by danshu** [comment]
@alexdobin @ghuls  Thanks!

**Comment by alexdobin** [comment]
CB/UB tags are implemented in soloDevelop branch

**Comment by rcosentino** [comment]
Hi, I have a follow-up question related to Quan's (@danshu) question. I want to do variant calling with GATK on STARsolo alignment of scRNA-seq data, but for each cell-independently. For that I would need to have a SM tag for each barcode. With STARsolo I can add the CB attribute, but I would need to have it in the SM tag, so GATK (and I guess any variant caller) knows from which cell each read is coming from. I could try to implement some tweaking like the one proposed [here](https://www.biostars.org/p/422761/ ), but I was wondering if there is a more straight forward solution that I am missing. Related to that, can STARsolo output a bam file for each barcode?
Cheers,

Raúl

**Comment by alexdobin** [comment]
Hi Raúl

it's best to start a new issue rather than reopen the old one.
I am not exactly sure what GATK requirements are. Do you want to rename the CB tag into SM? Or do you want to split the BAM by CB tag? Either way, you would need to do it in the post-mapping step.

Cheers
Alex
