### ISSUE TITLE
MAPQ(MQ) calculation rule for PE reads

### ISSUE THREAD

**Issue by radio1988** [alexdobin/STAR#615]
First, Thanks for this ultra-fast alignment tool!

Q1, My main question is:
If R1 has 1 Nmap , in chr1:10000, thus the MAPQ of R1 itself is 255
R2 has 2 Nmap, in chr1:10200 and chr2:9999, thus the MAPQ of R2 itself is 3
What will the the MAPQ for the sam line for R1 and R2 (two loci)?

* Nmap: number of loci mapped

Additionally:
Based on manual, `MAPQ=(int(-10*log10(1-1/Nmap)))`
So in theory MAPQ possibilities would be:
Nmap = 1, MAPQ = 255
Nmap = 2, MAPQ = 3
Nmap = 3, MAPQ = 1
Nmap = 4, MAPQ = 1
Nmap = 5, MAPQ = 0
Nmap = 6, MAPQ = 0
...

Q2, Am I correct? If I'm correct, what is the benefit of masking the difference of Nmap if Nmap ≥3 ? Would it make more sense to let MAPQ reflect Nmap in a wider range for easier manipulation/filter downstream?

Q3, I looked at my bam star output. column5 has numbers 0,1, 3, 155, 255 showed up. Where does 155 come from ?

Thanks a lot!

Ray

**Comment by radio1988** [comment]
For Q1, would Star report the following:
MAPQ(R1.chr1:10000) = 255
MAPQ(R2.chr1:10200) = 255
MAPQ(R2.chr2:9999) = 3

So that we can filter and keep both R1 and R2 with MAPQ>30?

**Comment by alexdobin** [comment]
Hi @radio1988 

Q1: STAR reports the alignment for the PE read rather than separately for R1/R2, so MAPQ is the same for R1/R2

Q2: This is correct, the MAPQ values depend on the number of loci a read maps to, and are limited to a few values. The MAPQ for unique mappers can be set by --outSAMmapqUnique and is 255 by default.
If you want to get the actual number of loci a read maps to, it's given by NH:i: tag in the SAM.

Q3: MAPQ=155 should not happen, please send me the lines that contain it.

Cheers
Alex

**Comment by radio1988** [comment]
Thank you Alex!

Q1: Will the MAPQ for this fragment be 255 or 3? Or something in between?

Q2: Thanks! This works

Q3: Sorry, MAPQ=155 must have been a mistake. I can't re-produce it now.

Best regards,
Ray

**Comment by alexdobin** [comment]
Hi Ray,

if a paired read maps to 2 places (even if one mate alignment is the same), it's considered a multimapper and gets MAPQ=3.

Cheers
Alex

**Comment by radio1988** [comment]
Thanks Alex, would it make more sense to consider this case a unique mapping and give it the MAPQ of the higher read in the pair?

**Comment by alexdobin** [comment]
Hi Ray,

the mates of a PE read represent the sequences of the ends of one RNA fragment (a.k.a. "insert").
If one of the ends maps to 2 places (both concordant with the other end), we cannot position the insert uniquely, and it has to be considered a multimapper.

Cheers
Alex
