### ISSUE TITLE
STARlong remnant in Makefile

### ISSUE THREAD

**Issue by thomasKuilman** [alexdobin/STAR#616]
Thanks for a great tool! I noticed that there is still a referral to STARlong in the Makefile of STAR 2.0.7f:

`'mv' STAR STARlong ../bin`

I assume STARlong has been deprecated; at least it is not in the `/STAR-2.7.0f/source` folder. When running a make install this throws an error.

**Comment by alexdobin** [comment]
Hi Thomas,

this command was under the install target in Makefile, which was obsolete and I removed it.
STARlong is fine, it's still is an alpha-release.

Cheers
Alex
