### ISSUE TITLE
Long reads in fasta file truncate input

### ISSUE THREAD

**Issue by CloXD** [alexdobin/STAR#618]
Hello,
first of all, thank you for the software.
I met this strange behavior trying to align a fasta file containing sequences of different length (up to few Kb): as soon as STAR meet a sequence longer than 557 bp, It won't read any more reads, raise no error and just align the ones that he already read and the  557bp of the long sequence.
I tried to increase --limitIObufferSize unsuccessfully ( same behavior or badalloc() if too high).
Is there a way to bypass this limit?
Thanks in advance

Claudio

**Comment by CloXD** [comment]
Looking in the codes, in readLoad there is DEF_readSeqLengthMax, that is defined in includeDefine and is increased to 500K if COMPILE_FOR_LONG_READS is defined.... so it should be enough to define the COMPILE_FOR_LONG_READS before compilation.
Sorry for the disturb!

**Comment by alexdobin** [comment]
Hi Claudio

that's right, or you could do 
$ make clean
$ make STARlong

Cheers
Alex
