### ISSUE TITLE
Chimeric.out.junction from STAR BAM generated using --peOverlapNbasesMin

### ISSUE THREAD

**Issue by nairasha** [alexdobin/STAR#619]
Hi alexdobin,

I have FFPE RNA samples that have very short RNA fragments and therefore overlapping paired-end RNA-Seq reads, and my interest lies in detecting gene fusions. 
I have used the --peOverlapNbasesMin parameter to obtain all possible chimera reads and I am able to see them in the STAR BAM (SA tags). My next goal is to run STAR-Fusion by using Chimeric.out.junction as input. I realize that for --peOverlapNbasesMin,   currently --chimOutType WithinBAM is what works and --chimOutType Junctions is not acceptable.

Question - is there a stand-alone way to still generate the Chimeric.out.junction file from the STAR BAM that was generated using --peOverlapNbasesMin?

Thanks so much!
nairasha

**Comment by alexdobin** [comment]
Hi @nairasha 

STAR will generate the Chimeric.out.junction file if you use both --peOverlapNbasesMin M and --chimMultimapNmax  N>0 options. The latter parameter will define the number of loci a chimera can map to, if you want unique chimeras only, you need N=1,

Cheers
Alex

**Comment by nairasha** [comment]
Alex, thank you so much for your reply.

I am using STAR version 2.6.1c and the providing --peOverlapNbasesMin 20 and --chimMultimapNmax 1 gives me the following message. Should I use a more recent STAR version for the two parameters to work together?

EXITING because of fatal PARAMETERS error: --chimMultimapNmax 0 (default old chimeric detection) and --peOverlapNbasesMin > 0 (merging ovelrapping mates) presently only works with --chimOutType WithinBAM
SOLUTION: re-run with --chimOutType WithinBAM

**Comment by alexdobin** [comment]
Hi @nairasha 

2.6.1c should be fine, though 2.6.1d is the most stable version.
Please send me the Log.out file.

Cheers
Alex

**Comment by nairasha** [comment]
Thank you for looking into this, Alex. 
Please see attached. Thanks - Asha
[FFPE_sample.Log.out.txt](https://github.com/alexdobin/STAR/files/3122519/FFPE_sample.Log.out.txt)

**Comment by alexdobin** [comment]
Hi Asha,

the command line from your Log.out (pasted below) does not seem to contain --chimMultimapNmax 1
please try it again.

Cheers
Alex

...--runThreadN 4 --outBAMsortingThreadN 4 --outSAMtype BAM SortedByCoordinate --twopassMode Basic --twopass1readsN -1 --outFileNamePrefix R224-CP-FFPE_S3. --outSAMattrRGline ID:Mayo PU:MAPRSeqV3 SM:R224-CP-FFPE_S3. PL:RNASeq LB:Illumina --limitBAMsortRAM 66330294591 --chimSegmentMin 12 --chimJunctionOverhangMin 12 --alignSJDBoverhangMin 10 --alignMatesGapMax 200000 --alignIntronMax 200000 --outSAMstrandField intronMotif --outSAMunmapped Within --chimOutType Junctions --peOverlapNbasesMin 20 --peOverlapMMp 0.01

**Comment by nairasha** [comment]
Thanks a lot, Alex. Sorry my bad, I had been looking at the wrong output as I had several tests running. 
My run using --peOverlapNbasesMin 20 and --chimMultimapNmax 1 worked beautifully. Thanks much for all the help! - Asha

**Comment by alexdobin** [comment]
Great, thanks for letting me know!

**Comment by nairasha** [comment]
Alex, one more question - is it possible to generate the Chimeric.out.sam also when using the --peOverlapNbasesMin parameter? I noticed that it errors out when given both junctions and separate sam 
--chimOutType Junctions SeparateSAMold.

My team supports the development of a clinical RNASeq assay for fresh frozen samples. We have developed an in-house fusion visualization module which uses STAR's Chimeric.out.junction and Chimeric.out.sam files as input. Now the assay is being developed for FFPE, and hence the question.

Thanks again
Asha

**Comment by alexdobin** [comment]
Hi Asha,

unfortunately, this is not possible -  actually, I am planning to deprecate chimeric SAM output in favor of WithinBAM output, which is very similar, but you need to filter the chimeric alignments from BAM. At the moment,  --peOverlapNbasesMin > 0 will work only 
(i) with --chimMultimapNmax=0 and --chimOutType WithinBAM
or
(ii) with --chimMultimapNmax>0 and  --chimOutType Junctions

I am planning to allow
--peOverlapNbasesMin > 0 --chimMultimapNmax>0 --chimOutType WithinBAM Junctions
in the future.

Cheers
Alex

**Comment by nairasha** [comment]
That sounds good, Alex. Thanks so much for all your help - Asha

**Comment by nairasha** [comment]
Hi Alex,

Two quick questions:

1) about fusion reads for FFPE samples - since overlapping mates can be merged into single reads (using --peOverlapNbasesMin) to enable chimera detection, in such cases when STAR-Fusion reports fusion supporting reads (JunctionReads & SpanningFrags), are the numbers calculated by counting both reads in the pair separately, or are they counted just once since they are merged into a single read? 
I have a fusion in an FFPE sample for which Tophat-Fusion reports ~ 1000 reads and ~500 from STAR-Fusion, hence the question. Please let me know if you'd like more details. 

2) I guess this question may be answered by the above, but just to confirm, for JunctionReads & SpanningFrags, does STAR-Fusion only count fusion supporting reads as fragments (R1 and R2 form one fragment) and not count singleton reads (R1 or R2) that may span the fusion junction?

Thanks much!
Asha

**Comment by alexdobin** [comment]
Hi Asha,

it's better to ask this question in the STAR-Fusion group: https://github.com/STAR-Fusion/STAR-Fusion
but I believe that PE read mates are always counted as jus one read.

Cheers
Alex

**Comment by nairasha** [comment]
Oh sorry, didn't realize there was a separate page for STAR-Fusion , will do so. Thanks Alex!
