### ISSUE TITLE
Multiple input files (--readFilesIn)

### ISSUE THREAD

**Issue by sung** [alexdobin/STAR#62]
Hi,
A very minor comment to the manual (page 19) - I thought it would be helpful to see how multiple input files can be listed from '--readFilesIn' parameter. 
For example:
--readFilesIn Read1A.fq,Read1B.fq Read2A.fq,Read2B.fq

Thanks,
Sung

**Comment by alexdobin** [comment]
Hi Sung,

thanks for a good suggestion, I will add it to the manual.

Cheers
Alex
