### ISSUE TITLE
terminate called recursively during genomeGenerate

### ISSUE THREAD

**Issue by DmitriKazmin** [alexdobin/STAR#621]
I'm generating a genome index, and I'm running into the following issue: 

command line: 
`STAR --runThreadN 16 --runMode genomeGenerate --genomeDir ~/work/genomes/human/GRCh38p12/Genome_for_ATAC_seq --genomeFastaFiles ~/work/genomes/human/GRCh38p12/GRCh38.p12.genome.fa --sjdbGTFfile ~/work/genomes/human/GRCh38p12/gencode.v30.annotation.gtf --sjdbOverhang 41 `

Output: 
Apr 18 11:25:49 ..... started STAR run
Apr 18 11:25:49 ... starting to generate Genome files
Apr 18 11:27:15 ... starting to sort Suffix Array. This may take a long time...
Apr 18 11:27:37 ... sorting Suffix Array chunks and saving them to disk...
terminate called recursively
terminate called recursively
Aborted

Memory: 32 GB
OS: CentOS 7.x

Am I doing something wrong? 

Thank you very much for your help.

**Comment by alexdobin** [comment]
Hi Dmitri,

32GB may not be enough to generate this genome. Please use --genomeSAsparseD 2.

Cheers
Alex
