### ISSUE TITLE
uT attribute is not described in the manual

### ISSUE THREAD

**Issue by aushev** [alexdobin/STAR#623]
There is a SAM attribute `uT` (I guess, `unmapType`) which is not described in the manual (section 4.2.2). 
Also, `RG` and `MC` should be probably added to the list of attributes "NH HI NM MD have standard meaning <...>".

**Comment by alexdobin** [comment]
Hi @aushev 

sure, will add the desriptions in the next release.

Cheers
Alex

**Comment by apredeus** [comment]
Interestingly, I get this error with `STAR` v2.7.9a when running `STARsolo` for Smart-seq2: 

> EXITING because of FATAL INPUT ERROR: unknown/unimplemented SAM atrribute (tag): uT
> SOLUTION: re-run STAR with --outSAMattributes that contains only implemented attributes

**Comment by alexdobin** [comment]
Hi Alex,

the uT tag is a default tag for unmapped reads, so it cannot be specified in the list of tags.

Cheers
Alex

**Comment by apredeus** [comment]
Got it, thank you!
