### ISSUE TITLE
FreeBSD port available

### ISSUE THREAD

**Issue by outpaddling** [alexdobin/STAR#624]
FYI:

STAR has been committed to the FreeBSD ports collection.
It might be helpful to users if you could post a message like
the following on your website:

Regards,

    Jason

star can be installed on FreeBSD via the FreeBSD ports system.

To install via the binary package, simply run:

    pkg install star

This will very quickly install a binary using only highly-portable
optimizations, much like apt-get, yum, etc.

FreeBSD ports can just as easily be built and installed from source,
although it will take longer (for the computer, not for you):

    cd /usr/ports/biology/star
    make install

Building from source allows installing to a different prefix, compiling with
native optimizations, and in some cases, building with non-default options
such as different compilers or dependencies, e.g.:

    make CFLAGS+=-march=native install

To report issues with a FreeBSD port, please submit a PR at:

    https://www.freebsd.org/support/bugreports.html

For more information, visit https://www.freebsd.org/ports/index.html.

**Comment by alexdobin** [comment]
Added description to README

**Comment by outpaddling** [comment]
The pkg install command above is actually incorrect.  I just noticed this in your install in structions.  This conflicted with another package named "star", so I renamed this package to "rna-star" (which matches the Debian package and the pkgsrc package soon to be committed).
