### ISSUE TITLE
Segmentation fault on GTF with no splice junctions

### ISSUE THREAD

**Issue by chihlee** [alexdobin/STAR#625]
Hello Alex,

We are using STAR 2.6.1a on a bacterial genome and the GTF contains no splice junctions. After loading the GTF, STAR fails with segmentation fault. I'm guessing it assumes there are at least one splice junction somewhere in the code as it runs to completion if we add a dummy splice junction to the GTF.

I realize that we don't have to use STAR as there are no splice junctions. However, STAR is the only aligner in our RNA-Seq pipeline so it would be nice if we can support this use case (no junctions) in STAR. It would be great if we can back-port this fix into the last version that supports the old index format so we don't have to re-build all the STAR indices.

Please see the attached for the FASTA and GTF:
[genome.zip](https://github.com/alexdobin/STAR/files/3102291/genome.zip)
Please let me know if you need more information. Thanks!

Best,
Steve

**Comment by alexdobin** [comment]
Hi Steve,

please send me the Log.out file of the failed run.

Cheers
Alex

**Comment by chihlee** [comment]
Hello Alex,

Here you go: [Log.zip](https://github.com/alexdobin/STAR/files/3108560/Log.zip)

Best,
Steve

**Comment by alexdobin** [comment]
Hi Steve,

for small genomes, at the genome generation step the --genomeSAindexNbases has to be scaled as
int(log2(GenomeSize)/2-1), which is in your case ~9.
Please let me know if this resolves the problem.

Cheers
Alex

**Comment by chihlee** [comment]
Hello Alex,

We did do that but STAR still crashed with segmentation fault.
Adding a dummy splice junction to the GTF fixed the issue though.

Best,
Steve

**Comment by alexdobin** [comment]
Hi Steve,

the Log.zip file that you sent still has --genomeSAindexNbases 14  
### /opt/illumina/RnaGenomeGenerator/STAR   --runMode genomeGenerate   --runThreadN 8   --genomeDir /data/scratch/OutputFolder/root/Sequence/STARindex2   --genomeFastaFiles ../WholeGenomeFasta/genome.fa      --genomeSAindexNbases 14   --genomeChrBinNbits 18   --genomeSAsparseD 1

Could you please send me the Log.out with the genome generated with --genomeSAindexNbases 9?
And also a few reads that you are mapping, the minimal set that still seg-faults.
I am not getting seg-faults with some random reads.

Cheers
Alex

**Comment by chihlee** [comment]
Hello Alex,

You are right. We got the formula wrong for genomeSAindexNbases so it was set to 14. Let me fix it and see if I can still reproduce the error. Now I'm not sure why that dummy junction fixed the issue. I'll get back to you after fixing genomeSAindexNbases. Thank you so much for looking into this issue!

Best,
Steve

**Comment by chihlee** [comment]
Hello Alex,

Fixing the formula for genomeSAindexNbases indeed fixed the issue for me. I have no idea why my workaround fixed the issue but I'll close the it for now. Thank again for your help!

Best,
Steve

**Comment by alexdobin** [comment]
Hi Steve,

great, thanks for letting me know. This problem depends on the genome sequence in a complex way, and adding just one junction may change it. I am planning to issue a warning at the genome generation step to enforce the right parameter choice.

Cheers
Alex
