### ISSUE TITLE
error about star genomegenerate killed

### ISSUE THREAD

**Issue by littlenapoleon** [alexdobin/STAR#626]
Hi! I got an error after qsub STAR genomeGenerate, and found not full files were generated except chrLength.txt,chrNameLength.txt,chrName.txt and chrStart.txt.why?
`STAR --runThreadN 12 --runMode genomeGenerate --genomeDir /home/youpu/ncbi/public/sra/genomedir --genomeFastaFiles /home/youpu/ncbi/public/sra/Homo_sapiens.GRCh38.95.dna.toplevel.fa --sjdbGTFfile /home/youpu/ncbi/public/sra/Homo_sapiens.GRCh38.95.gtf --limitGenomeGenerateRAM 160000000000
`
The error log is
`/home/youpu/personaldata/uploaddata/star_genome_generate: line 1:  3215 Killed                  STAR --runThreadN 12 --runMode genomeGenerate --genomeDir /home/youpu/ncbi/public/sra/genomedir --genomeFastaFiles /home/youpu/ncbi/public/sra/Homo_sapiens.GRCh38.95.dna.toplevel.fa --sjdbGTFfile /home/youpu/ncbi/public/sra/Homo_sapiens.GRCh38.95.gtf --limitGenomeGenerateRAM 160000000000
`

**Comment by alexdobin** [comment]
Hi @littlenapoleon 

please use the primary_assembly faster (not toplevel), i.e. 
ftp://ftp.ensembl.org/pub/release-95/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz

Cheers
Alex

**Comment by littlenapoleon** [comment]
Thank you! It works! but why can't I use toplevel to generate genome index? I remember several month ago I can successfully generate the index by toplevel genomeFastaFiles.

**Comment by alexdobin** [comment]
In principle, it can be done with enough RAM. However, it will produce a lot of multimappers mapping to alt haplotypes and patches.
