### ISSUE TITLE
STAR does not complete mapping

### ISSUE THREAD

**Issue by wolfgangrumpf** [alexdobin/STAR#627]
This is similar to another issue but not exactly, so I thought I'd create a new issue.

I'm running STARlong on PacBio data.  The mapping does not complete - I always get an error with thread 17 (Thread #17 end of input stream, nextChar=-1).  Then when Joining threads, it stops after joining 17 or 18.  This is usually about 20 minutes into the run.  I DO get an output file, but the job never completes - the CPU usage drops to zero but never actually terminates.  What can I do to troubleshoot this further?

**Comment by wolfgangrumpf** [comment]
Also - the EOF marker is absent (says stringtie), so STARlong never did complete....

**Comment by alexdobin** [comment]
Hi Wolfgang,

please send me the Log.out file.

Cheers
Alex

**Comment by wolfgangrumpf** [comment]
Here are the logs.  Not much of interest other than it just stops, as far as I can tell.  And this run I did run using 16 cores (on a system of 48)....
[logs.zip](https://github.com/alexdobin/STAR/files/3127620/logs.zip)

**Comment by wolfgangrumpf** [comment]
What most frustrating is that if I keep trying to run the alignment, eventually it goes all the way through (the log says ALL DONE).  There's no consistency that I can detect.

**Comment by wolfgangrumpf** [comment]
Here's an interesting thing with my most recent attempt:  on the 48 core system the processor usage never exceeded 700% (suggesting only 7 cores used).  Here's the output from the logs for this run:

Completed: thread #7
Completed: thread #3
Completed: thread #2
Completed: thread #6
Completed: thread #4
Completed: thread #5
Completed: thread #1
Joined thread # 1
Joined thread # 2
Joined thread # 3
Joined thread # 4
Joined thread # 5
Joined thread # 6
Joined thread # 7

Stops after 7.  Related to core usage?

**Comment by wolfgangrumpf** [comment]
Update:  ran the same sample with only 7 cores and it completed.  Hardly definitive, but....I'll try running a few more with 7 cores and see if I ever get any failure.

**Comment by alexdobin** [comment]
Hi Wolfgang,

may I ask you to do a few more tests:
1. Try using both static and dynamic precompiled executable.
2. Compile STARlong on your system from within source/ directory with 
$ make STARlong
3. Run without optional outputs parameters:
STARlong --runMode alignReads --genomeDir /gpfs0/home/gdlauberlab/rwr002/STAR/GRCh38 --readFilesIn fam16.fastq --runThreadN 16 --readNameSeparator space --outFilterMultimapScoreRange 1 --outFilterMismatchNmax 2000 --scoreGapNoncan -20 --scoreGapGCAG -4 --scoreGapATAC -8 --scoreDelOpen -1 --scoreDelBase -1 --scoreInsOpen -1 --scoreInsBase -1 --alignEndsType Local --seedSearchStartLmax 50 --seedPerReadNmax 1000000 --seedPerWindowNmax 1000 --alignTranscriptsPerReadNmax 100000 --alignTranscriptsPerWindowNmax 10000
4. Run STAR instead of STARlong

These will help to localize the problem.

Thanks a lot!
Alex

**Comment by wolfgangrumpf** [comment]
Can do!  It'll take me a day or so to get around to all of this....

**Comment by wolfgangrumpf** [comment]
I've completed 4 of the 5 variations above; here are the results:

Precompiled:  dynamic fails in the same way as previously
Precompiled:  static completes and releases CPUs but still only uses 7 no matter what I tell it
STAR (not STARlong) fails:  quality string length not equal to sequence length (PacBio sequences)
STARlong with fewer parameters:  fails in the same way as previously

So progress, at least - I can use the static precompile and get everything to run, albeit with only 7 cpus.

**Comment by alexdobin** [comment]
Hi Wolfgang,

great, thanks a lot for the tests!
STAR split the input FASTQ file into chunks of fixed size (~10,000-100,000 reads), and the number of chunks can be smaller than the number of threads if your files are small. If this is the case, STAR will only use the number of threads = number of chunks. You can see it at the end of Log.out files while 7 threads are still running, the other threads will be "joined" (i.e. terminated) immediately.

The fact that the static but not dynamic executable works means that there was some multithreading library incompatibility. While the static executable should work fine, the safest path is to compile STAR on your server.

Cheers
Alex

**Comment by wolfgangrumpf** [comment]
Thanks, Alex!  This is a managed server, so I'll talk to the admin and ask him to recompile it!
