### ISSUE TITLE
Different % alignment in Log Final & sum of ReadsPerGene

### ISSUE THREAD

**Issue by andrebolerbarros** [alexdobin/STAR#629]
Hi everyone,

I'm using STAR to align my reads against Mus musculus genome. After aligned, I'm using the Log.final.out to assess the quality of the assessment (% uniquely mapped, etc.). Considering I want to use gene counts to import in DESeq2, I use the corresponding `--quantMode GeneCounts` option.

However, after removing the first 4 lines of each ReadsPerGene file and selecting the corresponding column for the strandness of the data, the total sum of counts does not correspond to the number of reads aligned in Log.Final.Out.

Could someone help me understand the discrepancy?

Thanks!

**Comment by alexdobin** [comment]
Hi André

the sum of counts over all reads should be < the "number of unique mappers" in Log.final.out, as the former represents only reads that overlap annotated genes, while the latter also included the reads mapping to introns and intergenic space.

Cheers
Alex

**Comment by andrebolerbarros** [comment]
Thanks for the answer, Alex!

Is there any kind of rule of thumb to assess the quality of the alignment in the ReadsPerGene file?

**Comment by alexdobin** [comment]
Couple of things to check:
1. Ratio of reads mapping to genes / total number of unique mappers. This is usually ~75-95%, lower number may be indicative of problems with libraries and/or annotations
2. The diversity of expressed genes, you can look at it by plotting cumulative distributions of read counts per gene. We do not want only a few genes to take most of the read counts. 

Cheers
Alex
