### ISSUE TITLE
How repeat length defined in Chimeric.out.junction?

### ISSUE THREAD

**Issue by lamz138138** [alexdobin/STAR#630]
Hi, I had gone though Chimeric.out.junction, and found column 8 and column 9 is repeat length. How these value defined? Are they defined according to soft-masked reference (repeat sequence is lowercase)?

**Comment by alexdobin** [comment]
Hi @lamz138138 

these "repeats" are identical short (a few bases) sequences at the donor and acceptor sites of the junctions, e.g. 4b ACGT repeat, top sequence read, bottom - genome:
```
ACGT        CAAT                 
||||        ||||
ACGT    ACGTCAAT
```
Cheers
Alex

**Comment by lamz138138** [comment]
Hi, @alexdobin 

Thanks for your reply.  How identical short sequences defined, how many of them? Are they from a database?

**Comment by alexdobin** [comment]
Hi @lamz138138 

for each junction, STAR looks for identical sequences around donor and acceptor site in the genome.
Since the sequences are identical, the junctions can be shifted within them without introducing mismatches, so this number gives us information about how well the junction boundaries are defined.

Cheers
Alex

**Comment by lamz138138** [comment]
Hi @alexdobin 

I am still feeling confused, take above as an example, the sequence is ACGTCAAT,  after mapping to genome, the donor sequence is ACGT and acceptor is CAAT. Then, 1) compare this sequence to predefined repeat sequence (may from a database, soft-masked sequence, or all sequence around all junctions); 2) compare ACGT to CAAT.  If it is 1, then if sequence match one repeats, then output the length of longest repeat sequence. If it is 2, output the length of the identical length. For this case, ACGT not match CAAT, so should be 0?   

Can you help me figure out the process?

**Comment by alexdobin** [comment]
Hi @lamz138138 

there is no "predefined" repeat sequence, we are looking for a repeated sequence around the donor/acceptor site. In this example, first we check one base to the left of the donor and acceptor sites, they match (T), which means that, in principle, we can move the junction position 1 base left without introducing mismatches: 
```
ACG        TCAAT                 
|||        |||||
ACGT    ACGTCAAT
```
Then we continue checking 2,3,4 bases until we find first mismatch (not shown before, here is how it should look like:
```
GACGT        CAAT                 
|||||        ||||
GACGT   TACGTCAAT
```
Cheers
Alex

**Comment by lamz138138** [comment]
Hi @alexdobin 
I got it, thanks for the clarification.

Best regard!
