### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by JWellsBio** [alexdobin/STAR#631]
Makefile 99: recipe for target 'bgzf.o' failed
fatal error: zlib.h: No such file or directory

**Comment by alexdobin** [comment]
Hi Jason,

you need to install standard zlib-devel library, e.g.
$ yum install zlib-devel

Cheers
Alex

**Comment by JWellsBio** [comment]
thanks Alex, working on a Windows system with some restrictions but this got me close enough. thanks for all your hard work on STAR!

**Comment by alexdobin** [comment]
Thanks!

**Comment by entgck** [comment]
When i type- "make STAR" in source
This comes out:
make -C htslib lib-static
make[1]: Entering directory '/mnt/c/users/chuank/desktop/STAR-2.7.3a/source/htslib'
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o bgzf.o bgzf.c
In file included from bgzf.c:38:
htslib/bgzf.h:33:10: fatal error: zlib.h: No such file or directory
   33 | #include <zlib.h>
      |          ^~~~~~~~
compilation terminated.
make[1]: *** [Makefile:99: bgzf.o] Error 1
make[1]: Leaving directory '/mnt/c/users/chuank/desktop/STAR-2.7.3a/source/htslib'
Makefile:99: Depend.list: No such file or directory
make: *** [Makefile:109: htslib/libhts.a] Error 2

Please assist
