### ISSUE TITLE
stuck during transcriptome alignment

### ISSUE THREAD

**Issue by pchiang5** [alexdobin/STAR#632]
Hello,

I successfully built index from the fasta file of human transcriptome (Gencode Protein-coding transcript sequences) with the following command:

STAR --runThreadN 2 --runMode genomeGenerate --genomeDir gencode.v30.pc_transcripts_index --genomeFastaFiles gencode.v30.pc_transcripts.fa --genomeChrBinNbits =12 

The format of the fasta file:

========================================================================
 
\>ENST00000641515.2|ENSG00000186092.6|OTTHUMG00000001094.4|OTTHUMT00000003223.4|OR4F5-202|OR4F5|2618|UTR5:1-60|CDS:61-1041|UTR3:1042-2618|
CCCAGATCTCTTCAGTTTTTATGCCTCATTCTGTGAAAATTGCTGTAGTCTCTTCCAGTT...

=========================================================================

I also generated the corresponding GTF file with the format below:

=========================================================================

ENST00000641515.2|ENSG00000186092.6|OTTHUMG00000001094.4|OTTHUMT00000003223.4|OR4F5-202|OR4F5|2618|UTR5:1-60|CDS:61-1041|UTR3:1042-2618|	pfurio	exon	0	2662	.	+	.	gene_id  ENSG00000186092.6 ; transcript_id  ENST00000641515.2	ENST00000641515.2|ENSG00000186092.6|OTTHUMG00000001094.4|OTTHUMT00000003223.4|OR4F5-202|OR4F5|2618|UTR5:1-60|CDS:61-1041|UTR3:1042-2618|_0_2662	;

=========================================================================

When I tried to use STARsolo with the following command:
STAR --runThreadN 2 --soloType Droplet --genomeDir gencode.v30.pc_transcripts_index  --readFilesIn 'Undetermined_S0_L002_R1_001.fastq.gz' 'UMIBC_L002.fastq.gz' --genomeSAsparseD 2 --outSAMtype BAM SortedByCoordinate --outFilterMultimapNmax 1 --readFilesCommand zcat --soloCBwhitelist whitelist.csv  --soloCBstart 9 --soloCBlen 8 --soloStrand Reverse --soloUMIdedup 1MM_NotCollapsed --alignSJoverhangMin 999  --outFilterMismatchNoverReadLmax 0  --soloUMIstart 1 --soloUMIlen 8 --sjdbGTFfile gencode.v30_PC.gtf

STAR just kept running at the following state.

========================================================================

May 01 14:00:44 ..... started STAR run
May 01 14:00:44 ..... loading genome
May 01 14:00:50 ..... processing annotations GTF
May 01 14:00:51 ..... started mapping

=======================================================================

The CPU was 100% used and there was no output in the log.progress.out file after a long time:

=======================================================================
   Time    Speed        Read     Read   Mapped   Mapped   Mapped   Mapped Unmapped Unmapped Unmapped Unmapped
                    M/hr      number   length   unique   length   MMrate    multi   multi+       MM    short    other

========================================================================

The last few lines of the Log.out file looked like this:

=========================================================================

99731	ENST00000361789.2|ENSG00000198727.2|-|-|MT-CYB-201|MT-CYB|1141|CDS:1-1141|	1141	216798512
Started loading the genome: Wed May  1 14:00:44 2019

Genome: size given as a parameter = 216799655
SA: size given as a parameter = 1786951596
SAindex: size given as a parameter = 1
Read from SAindex: pGe.gSAindexNbases=14  nSAi=357913940
nGenome=216799655;  nSAbyte=1786951596
GstrandBit=32   SA number of indices=433200386
Shared memory is not used for genomes. Allocated a private copy of the genome.
Genome file size: 216799655 bytes; state: good=1 eof=0 fail=0 bad=0
Loading Genome ... done! state: good=1 eof=0 fail=0 bad=0; loaded 216799655 bytes
SA file size: 1786951596 bytes; state: good=1 eof=0 fail=0 bad=0
Loading SA ... done! state: good=1 eof=0 fail=0 bad=0; loaded 1786951596 bytes
Loading SAindex ... done: 1565873619 bytes
Finished loading the genome: Wed May  1 14:00:49 2019

alignIntronMax=alignMatesGapMax=0, the max intron size will be approximately determined by (2^winBinNbits)*winAnchorDistNbins=589824
winBinNbits=16 > pGe.gChrBinNbits=0   redefining:
winBinNbits=0
May 01 14:00:50 ..... processing annotations GTF
Processing pGe.sjdbGTFfile=gencode.v30_PC.gtf, found:
		99730 transcripts
		99730 exons (non-collapsed)
		0 collapsed junctions
May 01 14:00:51 ..... finished GTF processing
May 01 14:00:51   Loaded database junctions from the GTF file: gencode.v30_PC.gtf: 0 total junctions

May 01 14:00:51   Finished preparing junctions
May 01 14:00:51 ..... finished inserting junctions into genome
Loaded transcript database, nTr=99730
Loaded exon database, nEx=99730
Created thread # 1
Starting to map file # 0
mate 1:  Undetermined_S0_L002_R1_001.fastq.gz
mate 2:   UMIBC_L002.fastq.gz

====================================================================

STARsolo handled smoothly with the same input files and parameters when I used human genome fasta and the corresponding Gencode GTF file. 

Did the long names of each fasta sequence lead to the failure with the transcript fasta file? Is there any way I can address the issue?

Thank you.
Po

**Comment by alexdobin** [comment]
Hi Po,

STARsolo is not designed to work with mapping to transcriptome, could you explain why you would want to do that?

Cheers
Alex

**Comment by pchiang5** [comment]
Hi Alex,

I did this for the reasons below:

1. STAR took >32G (the limit of my RAM) when I tried to align reads to the joint human-mouse genome. 

2. My samples were already purified by polyA pull-down and reads were from the last 50bp of the mRNA. I found a lot of reads still aligned to genomic DNA (no polyA tail) even with high-stringency parameters. I wonder what I would have from transcriptome-only mapping.

Thanks,
Po-Min

**Comment by alexdobin** [comment]
Hi Po-Min,

did you use --genomeSAsparseD 2 for combined mouse-human genome and it took more than 32GB?
Note that you need to use this parameter (and --sjdbGTFfile) at the genome generation step.
You can also try --genomeSAsparseD 3, that will surely fit the mouse-human genome in 32GB.

In my experience, Drop-seq-like scRNA-seq techniques always yield a large proportion (~25%) of intronic reads, it's not just mapping artifact.

Cheers
Alex

**Comment by pchiang5** [comment]
> Hi Po-Min,
> 
> did you use --genomeSAsparseD 2 for combined mouse-human genome and it took more than 32GB?
> Note that you need to use this parameter (and --sjdbGTFfile) at the genome generation step.
> You can also try --genomeSAsparseD 3, that will surely fit the mouse-human genome in 32GB.
> 
> In my experience, Drop-seq-like scRNA-seq techniques always yield a large proportion (~25%) of intronic reads, it's not just mapping artifact.
> 
> Cheers
> Alex

Thanks Alex!
