### ISSUE TITLE
Terminated at genome indexing!

### ISSUE THREAD

**Issue by yifangt** [alexdobin/STAR#633]
Hello Alex!
I met error when index the wheat genome of size ~13GB.
```
[1]+  Aborted                 (core dumped) STAR  --runMode genomeGenerate --runThreadN 36 
terminate called after throwing an instance of 'std::out_of_range'
  2   what():  vector::_M_range_check

```
STAR 2.7.0f was installed thru conda environment without any problem. And my command line is:
```
STAR --runMode genomeGenerate 
--runThreadN 36 
--genomeDir ${GENOME_DIR} 
--genomeFastaFiles ${FASTA} 
--limitGenomeGenerateRAM 128000000000 
--sjdbGTFfile ${GFF3} --sjdbOverhang 99 
> ${LOG_DIR}/indexing.log 
2> ${LOG_DIR}/indexing.err
```
Do you have any clue of this problem? 
My only suspect so far is the GTF file in GFF3 format which is not addressed in the manual and I am not sure the gff3 is compatible.
Thanks!

**Comment by alexdobin** [comment]
Hi Yifang,

please try to generate the genome without the GFF file first.
For 13Gbase genome you would need ~130GB of RAM (128 should be fine).

Cheers
Alex

**Comment by yifangt** [comment]
Indexing worked with the GTF file instead of GFF, and it seems the gff3 file is the cause.
Thanks!

**Comment by alexdobin** [comment]
Great, thanks for letting me know!
GTF is a better format to use with STAR.
