### ISSUE TITLE
Warning Thrown during Index Generation with GRCh38.p12

### ISSUE THREAD

**Issue by ColeWunderlich** [alexdobin/STAR#635]
Hello, when building an index for GRCh38.p12 using the primary assembly from [Gencode](https://www.gencodegenes.org/human/) I received the following error.

`WARNING: long repeat for junction # 263498 : chr15 88855522 88855578; left shift = 14; right shift = 255`

This build used the latest `.fasta` and `.gtf` primary assembly files from Gencode (GRCh38.p12) with a --sjdbOverhang of 136 

I am wondering if this is something I need to address or if it is safe to ignore the warning.

**Comment by alexdobin** [comment]
Hi Cole,

if there are only a few warnings like that, they can be safely ingored. It means that the junction boundaries are not well defined (i.e. can be shifted).

Cheers
Alex
