### ISSUE TITLE
too short % high when both pairs aligned

### ISSUE THREAD

**Issue by firatuyulur** [alexdobin/STAR#637]
Hi Alex,

I've seen many cases like mine in the issues but couldn't find the solution. Briefly, I am given rnaseq bam files but not fastq files. and I need to do mut calling on them. as mutect2 is  the caller, I followed GATKs best practice that requires 2 step alignment with STAR. so, i did bam2fq from samtools and split the pairs using 

cat "$bams".fastq | grep '^@.*/1$' -A 3 --no-group-separator > "$bams"_r1.fastq; 
cat "$bams".fastq | grep '^@.*/2$' -A 3 --no-group-separator > "$bams"_r2.fastq;

When I do my alignment using both the pairs my alignment is ~20% and ~80% is unmapped: too short. As I read many issues like mine, someone suggested sorting the fastq files and I sorted my fastqs using 

cat x_r1.fastq | paste - - - - | sort -k1,1 -S 3G | tr '\t' '\n' > sorted_x_r1.fastq 

when I look at the first few lines of my sorted pairs, they look ok to me. yet the alignment rate dropped to ~1% and unmapped too short is not ~99%. Then I saw your suggestion about just aligning one pair. And with aligning only one pair, now I finally have ~90% uniquely mapped reads.

What do you think I should do now? What do you think is causing this dramatic change once both the pairs are used?

I am attaching a glimpse of every file I used.

[sorted_x_r1.txt](https://github.com/alexdobin/STAR/files/3163842/sorted_x_r1.txt)
[sorted_x_r2.txt](https://github.com/alexdobin/STAR/files/3163843/sorted_x_r2.txt)
[x_r1.txt](https://github.com/alexdobin/STAR/files/3163844/x_r1.txt)
[x_r2.txt](https://github.com/alexdobin/STAR/files/3163845/x_r2.txt)

**Comment by alexdobin** [comment]
Hi @firatuyulur 

this means the PE reads are still not properly sorted. Is the number of lines in read1/2 files the same?
If not, it means the BAM file had unpaired alignments - you would need to filter them out, i.e. keep only paired alignments before creating/sorting fastq.
I would recommend using Picard SamToFastq command, which will convert BAM to correct FASTQs in one run, though it's not fast.

Cheers
Alex

**Comment by firatuyulur** [comment]
Hi @alexdobin ,
Previously, I used a python script to get rid of the unpaired reads and the # lines were the same in read1 and 2. Still low alignment rate was the result. Right now I did picard samtofastq and aligned with 10k and 1m reads separately. It seems to work with uniquely mapped reads rate over 90%. Thanks for the suggestion, it worked for me.
Fırat
