### ISSUE TITLE
Question about the best way to do 2-pass mapping with multiple samples

### ISSUE THREAD

**Issue by aleighgreen** [alexdobin/STAR#638]
Hello, I was hoping to get a slight understanding of the best way to do two-pass mapping with multiple samples. From the STAR manual:

"8.1 Multi-sample 2-pass mapping.
For a study with multiple samples, it is recommended to collect 1st pass junctions from all samples.
1. Run 1st mapping pass for all samples with ”usual” parameters. Using annotations is recom- mended either a the genome generation step, or mapping step.
2. Run 2nd mapping pass for all samples , listing SJ.out.tab files from all samples in --sjdbFileChrStartEnd /path/to/sj1.tab /path/to/sj2.tab ....
"

So for this first mapping step, I have samples from various conditions, condition 1, 2, 3 etc. And for each of the those conditions, I have multiple samples, A, B, C, etc and then for each sample I have multiple lanes: lane1.fast1,fast2, lane2.fast1,fast2. 

So when the manual advises "run 1st pass mapping for all samples". Does this mean I should run it as:

`--readfilesIn cond1.sampleA.lane1,cond1.sampleB.lane1,cond2.sampleA,lane1.,cond3.sampleB.lane1`....etc

Or, should I run first past mapping for each condition separately. 

OR what I've done so far is run first pass mapping for each sample individually, combining all the lanes per sample. 

And then I would take all the output SJ.tab files and feed those into my second pass mapping. 

I have reason to suspect that there may be different splicing effects in each of my conditions, does that matter here? 

Follow up question from this, is after my after my first pass mapping I've got all these bams. But when I run the second pass, I'll run again on the same fastqs I'm going to want to run the second pass, right? So are the bams produced in the first mapping step temporary files I should ignore? Can I specific a way to not output a bam in the first step so I'm not producing irrelevant files if that's the case?

This is human data btw, so I would suspect that the splice junctions are relatively well characterized by the GTF I provided when I did the genome building section. 

Thank you!

**Comment by alexdobin** [comment]
Hi Anna-Leigh,

running all conditions separately and concatenating SJ.out.tab files will produce results very similar to running all samples together, but not exactly the same, because the filtering of junctions output to SJ.out.tab depends on the reads that are mapping in the single run. Running all samples together will allow more novel junctions to pass the filtering, and it also may be a bit more convenient. However, if you have a large number of novel junctions detected in the 1st pass (~>500k), you will likely need to filter them before supplying them to the 2nd pass.

The BAM files in the 1st pass are indeed irrelevant and you can avoid them with --outSAMtype None in the 1st pass.

Cheers
Alex

**Comment by aleighgreen** [comment]
Thank you for the rapid response. Probably could have figured out the --outSAMtype none if I'd read the manual more throughly >.<

Would it matter if I expect differences in the novel junctions between conditions at all, running them all at once or separately?

I seem to have an awful lot of 'novel junctions' in my first pass about 190k - 300k per sample(ran in a per sample mode to start). Are those sort of numbers expected? What kinds of filtering are recommended?

**Comment by alexdobin** [comment]
Hi Anna-Leigh,

unless you want to do filtering (before 2nd pass) based on the junction detection in separate samples, running all together or separately should not matter much.
The large number of novel junctions is typical for deep sequencing (>100M reads), most of them are supported by very few reads and can be filtered out based on the read threshold (col. 7 unique, col. 8 multi-mappers). I would also filter non-canonical junctions (col5==0) and mitochondrion junctions.

Cheers
Alex

**Comment by aleighgreen** [comment]
Would you advise using the `outSJfilterReads` set to unique then on the first pass?

given that I have done it sample by sample so I have an SJ.out.tab for each sample; if I want to concatenate these files into one "SJ.all.tab" is it fine to just concat them? Or should I sum them, for example

Sj.out.tab1

1 | 1 | 14830 | 14929 | 2 | 2 | 0 | 0 | 1 | 35
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
2 | 1 | 14830 | 14969 | 2 | 2 | 0 | 2 | 55 | 70
3 | 1 | 14830 | 185490 | 2 | 2 | 0 | 0 | 10 | 18
4 | 1 | 15039 | 15795 | 2 | 2 | 1 | 1 | 19 | 60
5 | 1 | 15226 | 185746 | 2 | 2 | 0 | 0 | 4 | 69
6 | 1 | 15226 | 185757 | 2 | 2 | 0 | 3 | 0 | 48
7 | 1 | 15796 | 186316 | 2 | 2 | 0 | 0 | 3 | 37
8 | 1 | 15948 | 16606 | 2 | 2 | 1 | 8 | 9 | 22
9 | 1 | 16766 | 16857 | 2 | 2 | 1 | 52 | 52 | 73
10 | 1 | 17056 | 17232 | 2 | 2 | 1 | 102 | 91 | 74

SJ.out.tab2

1 | 1 | 11845 | 12009 | 1 | 1 | 0 | 0 | 1 | 51
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
2 | 1 | 13115 | 183634 | 1 | 1 | 0 | 0 | 4 | 26
3 | 1 | 14830 | 14929 | 2 | 2 | 0 | 0 | 2 | 67
4 | 1 | 14830 | 14969 | 2 | 2 | 0 | 2 | 50 | 71
5 | 1 | 14830 | 185490 | 2 | 2 | 0 | 0 | 7 | 19
6 | 1 | 14844 | 14969 | 2 | 2 | 0 | 0 | 1 | 69
7 | 1 | 15039 | 15795 | 2 | 2 | 1 | 3 | 32 | 68
8 | 1 | 15226 | 185746 | 2 | 2 | 0 | 0 | 8 | 71
9 | 1 | 15948 | 16606 | 2 | 2 | 1 | 8 | 22 | 44
10 | 1 | 16311 | 16606 | 2 | 2 | 0 | 1 | 0 | 75

GIven that row 1 in SJ.1 and row 3 in SJ.2 are the same junction, should I sum their read counts first? Or just stick the tab files together end to end. 

Thank you!

Sj.out.tab2

**Comment by aleighgreen** [comment]
Would you also advise filtering out junctions on the unlocalized contigs?

**Comment by alexdobin** [comment]
Hi Anna-Leigh,

when reading sj file --sjdbFileChrStartEnd, STAR will only use the first four fields (i.e. chr/start/end/strand), so you do not need to worry about any other fields. However, you can use these field for filtering before concatenating the files together, for instance, if you want to keep only junctions supported by unique mappers, you will require col7 (number of unique reads) > 0 - you do not need ro re-run 1st pass with different outSJfilter options.

I would recommend filtering out the (novel) junctions from the scaffolds - most likely you do not want to deal with them, and often they are false positives from highly expressed unspliced loci (such as rRNA) that will slow down the 2-pass mapping.

Cheers
Alex

**Comment by aleighgreen** [comment]
Thank you so much the quick answers!
