### ISSUE TITLE
STARsolo SegFault with --outSAMunmapped Within

### ISSUE THREAD

**Issue by PedalheadPHX** [alexdobin/STAR#639]
I can get a reproducible segfault when setting the flag to write unmapped reads to the SAM/BAM

#### Completes Successfully
`/home/jkeats/downloads/STAR-2.7.0f/source/STAR --runMode alignReads --runThreadN 19 --genomeDir /scratch/jkeats/starSOLO_tests/starSOLO_100 --genomeLoad NoSharedMemory --readFilesType Fastx --readFilesIn MC1685_0003_1_LN_MNC_T2_X5SCR_K17932_HN3WLBBXX_AGCCAATT_L004_R2_001.fastq.gz,MC1685_0003_1_LN_MNC_T2_X5SCR_K17932_HN3WLBBXX_CTAGGTGA_L004_R2_001.fastq.gz,MC1685_0003_1_LN_MNC_T2_X5SCR_K17932_HN3WLBBXX_GATACGCC_L004_R2_001.fastq.gz,MC1685_0003_1_LN_MNC_T2_X5SCR_K17932_HN3WLBBXX_TCGTTCAG_L004_R2_001.fastq.gz MC1685_0003_1_LN_MNC_T2_X5SCR_K17932_HN3WLBBXX_AGCCAATT_L004_R1_001.fastq.gz,MC1685_0003_1_LN_MNC_T2_X5SCR_K17932_HN3WLBBXX_CTAGGTGA_L004_R1_001.fastq.gz,MC1685_0003_1_LN_MNC_T2_X5SCR_K17932_HN3WLBBXX_GATACGCC_L004_R1_001.fastq.gz,MC1685_0003_1_LN_MNC_T2_X5SCR_K17932_HN3WLBBXX_TCGTTCAG_L004_R1_001.fastq.gz --readFilesCommand zcat --outFileNamePrefix MC1685_0003_1_LN_MNC_T2_X5SCR_K17932_ --outSAMmode Full --outSAMunmapped None --outSAMmapqUnique 255 --outSAMattributes Standard CR CY UR UY --soloType Droplet --soloCBwhitelist /packages/cellranger/3.0.2/cellranger-cs/3.0.2/lib/python/cellranger/barcodes/737K-august-2016.txt --soloFeatures Gene --soloUMIdedup 1MM_All --soloCBstart 1 --soloCBlen 16 --soloUMIstart 17 --soloUMIlen 10 --soloBarcodeReadLength 0 --soloStrand Reverse --soloOutFileNames Solo.out/ MC1685_0003_1_LN_MNC_T2_X5SCR_K17932_genes.tsv MC1685_0003_1_LN_MNC_T2_X5SCR_K17932_barcodes.tsv MC1685_0003_1_LN_MNC_T2_X5SCR_K17932_matrix.mtx MC1685_0003_1_LN_MNC_T2_X5SCR_K17932_matrixSJ.mtx`

#### Fails with segfault message

`/var/spool/slurm/job2633085/slurm_script: line 101: 300406 Segmentation fault      (core dumped)`

##### Code causing segfault
`/home/jkeats/downloads/STAR-2.7.0f/source/STAR --runMode alignReads --runThreadN 19 --genomeDir /scratch/jkeats/starSOLO_tests/starSOLO_100 --genomeLoad NoSharedMemory --readFilesType Fastx --readFilesIn MC1685_0003_1_LN_MNC_T2_X5SCR_K17932_HN3WLBBXX_AGCCAATT_L004_R2_001.fastq.gz,MC1685_0003_1_LN_MNC_T2_X5SCR_K17932_HN3WLBBXX_CTAGGTGA_L004_R2_001.fastq.gz,MC1685_0003_1_LN_MNC_T2_X5SCR_K17932_HN3WLBBXX_GATACGCC_L004_R2_001.fastq.gz,MC1685_0003_1_LN_MNC_T2_X5SCR_K17932_HN3WLBBXX_TCGTTCAG_L004_R2_001.fastq.gz MC1685_0003_1_LN_MNC_T2_X5SCR_K17932_HN3WLBBXX_AGCCAATT_L004_R1_001.fastq.gz,MC1685_0003_1_LN_MNC_T2_X5SCR_K17932_HN3WLBBXX_CTAGGTGA_L004_R1_001.fastq.gz,MC1685_0003_1_LN_MNC_T2_X5SCR_K17932_HN3WLBBXX_GATACGCC_L004_R1_001.fastq.gz,MC1685_0003_1_LN_MNC_T2_X5SCR_K17932_HN3WLBBXX_TCGTTCAG_L004_R1_001.fastq.gz --readFilesCommand zcat --outFileNamePrefix MC1685_0003_1_LN_MNC_T2_X5SCR_K17932_ --outSAMmode Full --outSAMunmapped Within --outSAMmapqUnique 255 --outSAMattributes Standard CR CY UR UY --soloType Droplet --soloCBwhitelist /packages/cellranger/3.0.2/cellranger-cs/3.0.2/lib/python/cellranger/barcodes/737K-august-2016.txt --soloFeatures Gene --soloUMIdedup 1MM_All --soloCBstart 1 --soloCBlen 16 --soloUMIstart 17 --soloUMIlen 10 --soloBarcodeReadLength 0 --soloStrand Reverse --soloOutFileNames Solo.out/ MC1685_0003_1_LN_MNC_T2_X5SCR_K17932_genes.tsv MC1685_0003_1_LN_MNC_T2_X5SCR_K17932_barcodes.tsv MC1685_0003_1_LN_MNC_T2_X5SCR_K17932_matrix.mtx MC1685_0003_1_LN_MNC_T2_X5SCR_K17932_matrixSJ.mtx`

**Comment by alexdobin** [comment]
Hi Jonathan,

I fixed this problem in this branch: https://github.com/alexdobin/STAR/tree/solo_GeneFull
please check it out. I will make a new release within the next few days.

Cheers
Alex

**Comment by PedalheadPHX** [comment]
Hi Alex,

That branch definitely fixes the problem!  As always thanks for all the work you put in for the community of the years

**Comment by alexdobin** [comment]
Hi Jonathan,

sure, thanks - 2.7.1a is out now.

Cheers
Alex
