### ISSUE TITLE
EXITING because of FATAL GENOME INDEX FILE error: transcriptInfo.tab is corrupt, or is incompatible with the current STAR version

### ISSUE THREAD

**Issue by hardeep587** [alexdobin/STAR#641]
Hi, 

I am trying to run the STAR aligner (STAR-2.7.0f) and get the following error: 

EXITING because of FATAL GENOME INDEX FILE error: transcriptInfo.tab is corrupt,  or is incompatible with the current STAR version

Here are the commands I have used

Generate index: 
STAR --runThreadN 2 --runMode genomeGenerate --genomeDir dir/  --genomeFastaFiles GRCh37_latest_primary_assembly.fna GRCh37_latest_genomic.gff  --sjdbOverhang 100 --limitGenomeGenerateRAM=8825541333 --genomeSAsparseD 2

Mapping: 

STAR --genomeDir dir/ --outSAMunmapped Within --outFilterType BySJout --outSAMattributes NH HI AS NM MD --outFilterMultimapNmax 20 --outFilterMismatchNmax 999 --outFilterMismatchNoverLmax 0.04 --alignIntronMin 20 --alignIntronMax 1000000 --alignMatesGapMax 1000000 --alignSJoverhangMin 8 --alignSJDBoverhangMin 1 --sjdbScore 1 --runThreadN 8 --genomeLoad NoSharedMemory --outSAMtype BAM Unsorted --quantMode TranscriptomeSAM --outSAMheaderHD @HD VN:1.4 SO:unsorted --outFileNamePrefix sample1 --readFilesCommand zcat --readFilesIn sample1_R1_001.fastq.gz sample1_R2_001.fastq.gz

Here are the relevant contents of the log file: 

Started loading the genome: Wed May 15 15:34:05 2019

Genome: size given as a parameter = 3162497574
SA: size given as a parameter = 24045796602
SAindex: size given as a parameter = 1
Read from SAindex: pGe.gSAindexNbases=14  nSAi=357913940
nGenome=3162497574;  nSAbyte=24045796602
GstrandBit=32   SA number of indices=5829284024
Shared memory is not used for genomes. Allocated a private copy of the genome.
Genome file size: 3162497574 bytes; state: good=1 eof=0 fail=0 bad=0
Loading Genome ... done! state: good=1 eof=0 fail=0 bad=0; loaded 3162497574 bytes
SA file size: 24045796602 bytes; state: good=1 eof=0 fail=0 bad=0
Loading SA ... done! state: good=1 eof=0 fail=0 bad=0; loaded 24045796602 bytes
Loading SAindex ... done: 1565873619 bytes
Finished loading the genome: Wed May 15 15:35:12 2019

Processing splice junctions database sjdbN=236022,   pGe.sjdbOverhang=100
To accommodate alignIntronMax=1000000 redefined winBinNbits=18
To accommodate alignIntronMax=1000000 and alignMatesGapMax=1000000, redefined winFlankNbins=4 and winAnchorDistNbins=8

EXITING because of FATAL GENOME INDEX FILE error: transcriptInfo.tab is corrupt, or is incompatible with the current STAR version
SOLUTION: re-generate genome index
May 15 15:35:12 ...... FATAL ERROR, exiting

Please could you advise on how to get around this error?

All the best, 

Hardeep

**Comment by alexdobin** [comment]
Hi Hardeep,

please re-generate the index with the same version of STAR (2.7.0f).

Cheers
Alex

**Comment by hardeep587** [comment]
I have tried this multiple times - and keep getting the same error. Do you have any other advice on this?

**Comment by torchij** [comment]
Hello, I am in the same boat, rebuilding hasn't worked for me either.

**Comment by hardeep587** [comment]
> Hello, I am in the same boat, rebuilding hasn't worked for me either.

Are you also using version 2.7.0f ?

**Comment by alexdobin** [comment]
Hi Hardeep, @torchij 

please send me the Log.out files for the genome generation and failed mapping run.

Cheers
Alex

**Comment by hardeep587** [comment]
Genome generation: 
[GRCh37_latest_primary_assembly.RSEMLog_out.txt](https://github.com/alexdobin/STAR/files/3187948/GRCh37_latest_primary_assembly.RSEMLog_out.txt)

Failed mapping: 
[T32057_CAGATC_L007_R1_001Log_out.txt](https://github.com/alexdobin/STAR/files/3187943/T32057_CAGATC_L007_R1_001Log_out.txt)

**Comment by alexdobin** [comment]
Hi  Hardeep,

in the genome generation Log.out the last line is:
May 14 11:46:57 ... sorting Suffix Array chunks and saving them to disk...
so the genome generation job did not complete properly. The Log.out will have "ALL DONE!" as the last line if it completed properly.

Please run the genome generation again with an empty directory (i.e. remove ref2).
Also, I would recommend using absolute paths for all the file and directory names you specify for STAR, and increase the number of threads for genome generation.

Cheers
Alex

**Comment by torchij** [comment]
> Hi Hardeep, @torchij
> 
> please send me the Log.out files for the genome generation and failed mapping run.
> 
> Cheers
> Alex

I'm trying a fresh install of the latest genome, so will report if any problems.
Thanks Alex.

**Comment by hardeep587** [comment]
> Hi Hardeep,
> 
> in the genome generation Log.out the last line is:
> May 14 11:46:57 ... sorting Suffix Array chunks and saving them to disk...
> so the genome generation job did not complete properly. The Log.out will have "ALL DONE!" as the last line if it completed properly.
> 
> Please run the genome generation again with an empty directory (i.e. remove ref2).
> Also, I would recommend using absolute paths for all the file and directory names you specify for STAR, and increase the number of threads for genome generation.
> 
> Cheers
> Alex

Thank you for this quick feedback - it wasn't obvious from the ref build log file that it had failed. I will try out your recommendations.
