### ISSUE TITLE
STAR mapping to incorrect junction

### ISSUE THREAD

**Issue by sagnikbanerjee15** [alexdobin/STAR#642]
Hello,

I am currently working on a pipeline to annotate genomes and I am testing it on Arabidopsis. The first step of this process is to map reads to the genome. For that, I used the following parameters:
--outSAMtype BAM SortedByCoordinate
--outFilterMultimapNmax 250
--outFilterMismatchNmax 999  "
--alignIntronMin 20  
--alignIntronMax 10000 
--outFilterScoreMinOverLread 0.90 
--outFilterMatchNminOverLread 0.90 
--outSJfilterOverhangMin 1 1 1 1 
--outSJfilterCountUniqueMin 5 5 5 5 
--outSJfilterCountTotalMin 10 10 10 10 
--outSAMattributes NH HI AS nM NM MD jM jI XS 

Since I am doing genome annotation I have intentionally left out the existing annotation file. I found some loci in the genome where reads have incorrectly mapped. I looked at the annotation file to determine that a splice junction in one of the transcripts were not detected correctly. In fact, it was not detected at all but a nearby spurious junction was created as a result of the mapping. In the attached figure, the first alignment is what STAR has reported. You can see that there are 3 mismatches in the reported alignment. On closer inspection, I found that there is the correct alignment creates a different splice junction which can be achieved without any mismatches. I have rerun STAR by setting the value of `outFilterMismatchNmax` to 1, but in that setting, STAR does not map the read in question. Please help.

Thank you.
<img width="1270" alt="Screen Shot 2019-05-15 at 8 10 09 PM" src="https://user-images.githubusercontent.com/23457977/57819442-1b426000-774e-11e9-863a-47f9f98f2e87.png">

**Comment by alexdobin** [comment]
Hi Sagnik,

if I understand it correctly, the correct alignment has the AT/AC intron motif, which STAR considers semi-canonical and penalizes heavily by default (-8, the penalty for 3 mismatches is -6). You can reduce this penalty with --scoreGapATAC, e.g. to completely remove the penalty use --scoreGapATAC 0, or to make it equivalent to 1 mismatch use --scoreGapATAC -2.

Cheers
Alex
