### ISSUE TITLE
STAR-Fusion interacting with STAR error

### ISSUE THREAD

**Issue by JWellsBio** [alexdobin/STAR#643]
Running latest release of STAR-Fusion. Tried running but received this:

Sorry, version [STAR_2.5.3a] is not supported. Please use at least STAR version 2.7.0f
        To upgrade, obtain the latest STAR here: https://github.com/alexdobin/STAR/releases

Updated to latest version of STAR (2.7.1), put both in PATH, but still receiving error. Help?

**Comment by alexdobin** [comment]
Hi Jason,

please try 2.7.0f, as 2.7.1a is only 1 day old and might not work with STAR-Fusion.

Cheers
Alex
