### ISSUE TITLE
STARSolo Filtered Count Matrix

### ISSUE THREAD

**Issue by mtekman** [alexdobin/STAR#644]
Hi Alex, thanks for all the hard work!

I have a question regarding the output matrices when specifying a whitelist of barcodes.

At the moment I am trying to replicate a count matrix generated using CellRanger (Chromium V2). The output matrix yields around 3000 cells.

When I run STARsolo I obtain the full set of whitelisted barcodes of 737,000 cells! (I am using the `737K-august-2016.txt` barcodes using the ChromiumV2 protocol (26bp in Read 1))

I dug a little bit deeper into the topic and discovered [this](https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/output/matrices) page on the 10X site that talks about the output matrices generated:

| Type | Description |
|------|-------------|
| Unfiltered feature-barcode matrix | Contains every barcode from fixed list of known-good barcode sequences. This includes background and cell associated barcodes |
| Filtered feature-barcode matrix | Contains only detected cellular barcodes. |

Doing a diff between my `diff -b Solo.out/barcodes.tsv  737K-august-2016.txt` yields nothing, so I believe the matrix given by STARsolo is the first Type given in the above table. 

Looking into the CellRanger source I found in `cellranger-cs/2.1.1/lib/python/cellranger/stats.py` several different ways in which the matrix is filtered, namely using quantile based filtering or some cutoff threshold.

My question:

 1. Is there any way to get the filtered feature-barcode output matrix?
 1. Is filtering even within the scope of STAR?

Thanks

Edit: I can get somewhat the same level of cells by filtering out any cells with total transcripts less than 2000, but this is just my arbitrary cutoff.

**Comment by alexdobin** [comment]
Hi Mehment,

indeed, STARsolo outputs unfiltered matrices and barcodes.
There are many approaches to do the filtering, with many adjustable parameters, and I did not want to hard-code them into STARsolo algorithm.

CellRanger V2 did a very basic filtering of the count matrices.
I have an awk script that performs the same filtering using the unfiltered STARsolo matrices as input:
https://github.com/alexdobin/STAR/blob/master/extras/scripts/soloBasicCellFilter.awk
Run this script:
`$ awk -f soloBasicCellFilter.awk barcodes.tsv matrix.mtx`
and it will create barcodes.tsv.filtered  matrix.mtx.filtered files.

There are some hard-coded parameters in the BEGIN portion of the script:
```
    maxCells=3000;          # expected number of cells
    maxPercentile=0.99;     # cell expression (UMI) percentile for defining the robust maximum UMI count
    maxMinRatio=10;         # the maximum to minimum UMI count ratio, minimum UMI count defines the cell filtering cutoff
```
As far as I know, CellRanger V3 uses [EmptyDrops](https://doi.org/10.1186/s13059-019-1662-y), a more sophisticated cell filtering approach. This tool uses unfiltered matrices, and has a number of adjustable parameters. It should be easy to incorporate it into the the mapping pipeline downstream of STARsolo output.

Cheers
Alex

**Comment by mtekman** [comment]
This is fantastic, thank you so much!
