### ISSUE TITLE
error 'kill' was not declared in this scope

### ISSUE THREAD

**Issue by DelaVegaPablo** [alexdobin/STAR#645]
Hello Alex, 

I have been trying to compile STAR using cygwin on Windows 10 and I keep getting the following error:

Parameters_closeReadsFiles.cpp:11:13: error: 'kill' was not declared in this scope
kill(readFilesCommandPID[imate],SIGKILL);

Could you please advise?  

Thank you,

**Comment by alexdobin** [comment]
Hi @DelaVegaPablo 

I heard about successful cygwin ports of STAR, but I have not done it myself.
My suspicion is that you need to install a library for calling system commands - such as kill.

Cheers
Alex
