### ISSUE TITLE
variable barcode read length starsolo

### ISSUE THREAD

**Issue by ersgupta** [alexdobin/STAR#646]
Hi guys,
I am using starSolo with dropseq data. I perform adaptor and low qual trimming of raw reads so I get variable length for barcode reads. With this data, I get an error `"the total length of barcode sequence is 112 not equal to expected 150"`. Should I use the absolute raw reads for starSolo?
Thanks

**Comment by alexdobin** [comment]
Hi Saurabh,

barcode read should not be trimmed!
What are the UMI and cell barcode lengths in your samples?
Presently, STARsolo can only deal with CB<=32b and UMI<=16b.

Cheers
Alex

**Comment by ersgupta** [comment]
Thanks Alex. I am running with raw reads now, no error so far. Read length is 150bp which includes CB=12bp and UMI=8bp.
