### ISSUE TITLE
TranscriptomeSAM and outFilterMultimapNmax

### ISSUE THREAD

**Issue by DarioS** [alexdobin/STAR#649]
Does setting `--outFilterMultimapNmax` to 1 also cause all multi-mapping reads to be discarded from the transcriptome BAM if I specify `--quantMode TranscriptomeSAM` ? I'd like the filter to only apply to the genomic alignments and have no limit for the transcriptomic alignments. Some discussion about this relationship could be added to the user guide.

**Comment by alexdobin** [comment]
Hi Dario,

--outFilterMultimapNmax filter only applies to genomic alignments. If an alignment passes this filter, it is converted to all possible transcriptomic alignments and all of them are output. I think this is exactly what you want to do. I will add this explanation to the manual.

Cheers
Alex

**Comment by DarioS** [comment]
No, not that. When I am mapping to the genome and doing ordinary counting, I want to avoid uncertainty and randomness in the counts so I only allow unique alignments. But, when I do RSEM for resolving reads mapping to multiple locations, I would also like to use the reads that align to multiple genes and were discarded in the original alignment.

**Comment by alexdobin** [comment]
Ahh, I see. In this case you could include genomic multimappers at the mapping stage, and then filter them in the downstream processing: by MAPQ<255 or HI:i: >1. Also, counting tools (STAR GeneCounts, featureCounts, htseq-count) count unique mappers and discard multimappers.

**Comment by DarioS** [comment]
Oh, interesting. I am using Bioconductor software, which is not able to ignore the multi-mapping reads.
