### ISSUE TITLE
Genome indexing stops at generate genome files

### ISSUE THREAD

**Issue by emailjack** [alexdobin/STAR#650]
Hi

I am trying to index the zebrafish. I am running on a node of 35Gb memory on my University cluster. I am using this code:

STAR --runThreadN 8 --runMode genomeGenerate --genomeDir /fastdata/mdt16j/STAR/genome --genomeFastaFiles /fastdata/mdt16j/STAR/Danio_rerio_GRCz11.fa --sjdbGTFfile /fastdata/mdt16j/STAR/Danio_rerio.GRCz11.96.gtf --sjdbOverhang 100 --genomeSAsparseD 2

All I see interactively is:

May 28 15:27:39 ..... started STAR run
May 28 15:27:40 ... starting to generate Genome files

Then is goes back to my terminal input and stops.
Below is the log.out 

[logout.docx](https://github.com/alexdobin/STAR/files/3228236/logout.docx)

Any advice?

Cheers

**Comment by alexdobin** [comment]
Hi @emailjack 

the genome appears to have a large number of "alternative" sequences (CHR_ALT) which bloat the genome size to 50GB. You would need to take them out as they are not very useful for RNA-seq mapping.

Cheers
Alex

**Comment by hreinwal** [comment]
Hi @alexdobin, 
thank you very much for the advice. I am using the same ref. genome from the zebrafish (GRCz11) and I am having the same problem that STAR asks for 140 GB of RAM. I have two questions considering your comment and I hope they are not too silly: 
1) How do I find out if my references genome has a lot of alternative sequences?
2) How do I remove them as you suggested?

Cheers,
Hannes

**Comment by alexdobin** [comment]
Hi Hannes,

I believe ENSEMBL has the primary assembly for GRCz11 here:
[ftp://ftp.ensembl.org/pub/release-98/fasta/danio_rerio/dna/Danio_rerio.GRCz11.dna.primary_assembly.fa.gz](url)
This file should include all the necessary sequences but no alts or patches.

Cheers
Alex
