### ISSUE TITLE
bad_alloc with star solo 2.7.0f

### ISSUE THREAD

**Issue by codymowery** [alexdobin/STAR#651]
Hi Alex! I am running star solo with the following command using star 2.7.0f, even after (presumably) overshooting memory demands with 125gb RAM and 20gb scratch memory.

`STAR  --genomeDir ${ref} --readFilesIn ${r3_cdna_file} ${r1r2_file} --soloOutFileNames ./sampleA_solo_ --soloType Droplet --readFilesCommand zcat --soloCBwhitelist ${whitelist} --soloCBlen 8 --soloUMIstart 9 --soloBarcodeReadLength 30`

Error reads as follows:

`May 30 08:06:16 ..... started STAR run
May 30 08:06:16 ..... loading genome
May 30 08:07:56 ..... started mapping
May 30 08:10:18 ..... finished mapping
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
/var/spool/sge/wynton/qb3-id84/job_scripts/5297256: line 32: 40319 Aborted                 (core dumped) STAR --genomeDir ${ref} --readFilesIn ${r3_cdna_file} ${r1r2_file} --soloOutFileNames ./sampleA_solo_ --soloType Droplet --readFilesCommand zcat --soloCBwhitelist ${whitelist} --soloCBlen 8 --soloUMIstart 9 --soloBarcodeReadLength 30`

I appreciate any suggestions!

**Comment by codymowery** [comment]
To add, Log.out file reads as follows:

`STAR version=2.7.0f
STAR compilation time,server,dir=Thu Mar 28 16:14:02 EDT 2019 vega:/home/dobin/data/STAR/STARcode/STAR.master/source
##### DEFAULT parameters:
versionGenome                     2.7.0d
parametersFiles                   -   
sysShell                          -
runMode                           alignReads
runThreadN                        1
runDirPerm                        User_RWX
runRNGseed                        777
genomeDir                         ./GenomeDir/
genomeLoad                        NoSharedMemory
genomeFastaFiles                  -   
genomeChainFiles                  -   
genomeSAindexNbases               14
genomeChrBinNbits                 18
genomeSAsparseD                   1
genomeSuffixLengthMax             18446744073709551615
genomeFileSizes                   0   
genomeConsensusFile               -
readFilesType                     Fastx   
readFilesIn                       Read1   Read2   
readFilesPrefix                   -
readFilesCommand                  -   
readMatesLengthsIn                NotEqual
readMapNumber                     18446744073709551615
readNameSeparator                 /   
inputBAMfile                      -
bamRemoveDuplicatesType           -
bamRemoveDuplicatesMate2basesN    0
limitGenomeGenerateRAM            31000000000
limitIObufferSize                 150000000
limitOutSAMoneReadBytes           100000
limitOutSJcollapsed               1000000
limitOutSJoneRead                 1000
limitBAMsortRAM                   0
limitSjdbInsertNsj                1000000
limitNreadsSoft                   18446744073709551615
outFileNamePrefix                 ./
outTmpDir                         -
outTmpKeep                        None
outStd                            Log
outReadsUnmapped                  None
outQSconversionAdd                0
outMultimapperOrder               Old_2.4
outSAMtype                        SAM   
outSAMmode                        Full
outSAMstrandField                 None
outSAMattributes                  Standard   
outSAMunmapped                    None   
outSAMorder                       Paired
outSAMprimaryFlag                 OneBestScore
outSAMreadID                      Standard
outSAMmapqUnique                  255
outSAMflagOR                      0
outSAMflagAND                     65535
outSAMattrRGline                  -   
outSAMheaderHD                    -   
outSAMheaderPG                    -   
outSAMheaderCommentFile           -
outBAMcompression                 1
outBAMsortingThreadN              0
outBAMsortingBinsN                50
outSAMfilter                      None   
outSAMmultNmax                    18446744073709551615
outSAMattrIHstart                 1
outSAMtlen                        1
outSJfilterReads                  All
outSJfilterCountUniqueMin         3   1   1   1   
outSJfilterCountTotalMin          3   1   1   1   
outSJfilterOverhangMin            30   12   12   12   
outSJfilterDistToOtherSJmin       10   0   5   10   
outSJfilterIntronMaxVsReadN       50000   100000   200000   
outWigType                        None   
outWigStrand                      Stranded   
outWigReferencesPrefix            -
outWigNorm                        RPM   
outFilterType                     Normal
outFilterMultimapNmax             10
outFilterMultimapScoreRange       1
outFilterScoreMin                 0
outFilterScoreMinOverLread        0.66
outFilterMatchNmin                0
outFilterMatchNminOverLread       0.66
outFilterMismatchNmax             10
outFilterMismatchNoverLmax        0.3
outFilterMismatchNoverReadLmax    1
outFilterIntronMotifs             None
outFilterIntronStrands            RemoveInconsistentStrands
clip5pNbases                      0   
clip3pNbases                      0   
clip3pAfterAdapterNbases          0   
clip3pAdapterSeq                  -   
clip3pAdapterMMp                  0.1   
winBinNbits                       16
winAnchorDistNbins                9
winFlankNbins                     4
winAnchorMultimapNmax             50
winReadCoverageRelativeMin        0.5
winReadCoverageBasesMin           0
scoreGap                          0
scoreGapNoncan                    -8
scoreGapGCAG                      -4
scoreGapATAC                      -8
scoreStitchSJshift                1
scoreGenomicLengthLog2scale       -0.25
scoreDelBase                      -2
scoreDelOpen                      -2
scoreInsOpen                      -2
scoreInsBase                      -2
seedSearchLmax                    0
seedSearchStartLmax               50
seedSearchStartLmaxOverLread      1
seedPerReadNmax                   1000
seedPerWindowNmax                 50
seedNoneLociPerWindow             10
seedMultimapNmax                  10000
seedSplitMin                      12
alignIntronMin                    21
alignIntronMax                    0
alignMatesGapMax                  0
alignTranscriptsPerReadNmax       10000
alignSJoverhangMin                5
alignSJDBoverhangMin              3
alignSJstitchMismatchNmax         0   -1   0   0   
alignSplicedMateMapLmin           0
alignSplicedMateMapLminOverLmate    0.66
alignWindowsPerReadNmax           10000
alignTranscriptsPerWindowNmax     100
alignEndsType                     Local
alignSoftClipAtReferenceEnds      Yes
alignEndsProtrude                 0   ConcordantPair   
alignInsertionFlush               None
peOverlapNbasesMin                0
peOverlapMMp                      0.01
chimSegmentMin                    0
chimScoreMin                      0
chimScoreDropMax                  20
chimScoreSeparation               10
chimScoreJunctionNonGTAG          -1
chimMainSegmentMultNmax           10
chimJunctionOverhangMin           20
chimOutType                       Junctions   
chimFilter                        banGenomicN   
chimSegmentReadGapMax             0
chimMultimapNmax                  0
chimMultimapScoreRange            1
chimNonchimScoreDropMin           20
chimOutJunctionFormat             0   
sjdbFileChrStartEnd               -   
sjdbGTFfile                       -
sjdbGTFchrPrefix                  -
sjdbGTFfeatureExon                exon
sjdbGTFtagExonParentTranscript    transcript_id
sjdbGTFtagExonParentGene          gene_id
sjdbOverhang                      100
sjdbScore                         2
sjdbInsertSave                    Basic
varVCFfile                        -
waspOutputMode                    None
quantMode                         -   
quantTranscriptomeBAMcompression    1
quantTranscriptomeBan             IndelSoftclipSingleend
twopass1readsN                    18446744073709551615
twopassMode                       None
soloType                          None
soloCBstart                       1
soloUMIstart                      17
soloCBlen                         16
soloUMIlen                        10
soloBarcodeReadLength             1
soloCBwhitelist                   -
soloStrand                        Forward
soloOutFileNames                  Solo.out/   genes.tsv   barcodes.tsv   matrix.mtx   matrixSJ.mtx   
soloFeatures                      Gene   
soloUMIdedup                      1MM_All   
##### Command Line:
STAR --genomeDir /ye/netapp/jimmie.ye/ref/star/grch38/grch38_star_74overhang/ --readFilesIn /ye/yelabstore3/cidseq/data/190506-1_miniseq/190424-1_fastq/190422-1/190422-1_sampleA_S1_L001_R3_001.fastq.gz /ye/yelabstore3/cidseq/data/190506-1_miniseq/190424-1_fastq/190422-1/sciseq/190422-1_sampleA_S1_L001.bc2-bc1-umi.Rscript.fastq.gz --soloOutFileNames ./sampleA_solo_ --soloType Droplet --readFilesCommand zcat --soloCBwhitelist /ye/yelabstore3/cidseq/scripts/scicrop_bcs.txt --soloCBlen 8 --soloUMIstart 9 --soloBarcodeReadLength 30
##### Initial USER parameters from Command Line:
###### All USER parameters from Command Line:
genomeDir                     /ye/netapp/jimmie.ye/ref/star/grch38/grch38_star_74overhang/     ~RE-DEFINED
readFilesIn                   /ye/yelabstore3/cidseq/data/190506-1_miniseq/190424-1_fastq/190422-1/190422-1_sampleA_S1_L001_R3_001.fastq.gz   /ye/yelabstore3/cidseq/data/190506-1_miniseq/190424-1_fastq/190422-1/sciseq/190422-1_sampleA_S1_L001.bc2-bc1-umi.Rscript.fastq.gz        ~RE-DEFINED
soloOutFileNames              ./sampleA_solo_        ~RE-DEFINED
soloType                      Droplet     ~RE-DEFINED
readFilesCommand              zcat        ~RE-DEFINED
soloCBwhitelist               /ye/yelabstore3/cidseq/scripts/scicrop_bcs.txt     ~RE-DEFINED
soloCBlen                     8     ~RE-DEFINED
soloUMIstart                  9     ~RE-DEFINED
soloBarcodeReadLength         30     ~RE-DEFINED
##### Finished reading parameters from all sources

##### Final user re-defined parameters-----------------:
genomeDir                         /ye/netapp/jimmie.ye/ref/star/grch38/grch38_star_74overhang/
readFilesIn                       /ye/yelabstore3/cidseq/data/190506-1_miniseq/190424-1_fastq/190422-1/190422-1_sampleA_S1_L001_R3_001.fastq.gz   /ye/yelabstore3/cidseq/data/190506-1_miniseq/190424-1_fastq/190422-1/sciseq/190422-1_sampleA_S1_L001.bc2-bc1-umi.Rscript.fastq.gz   
readFilesCommand                  zcat   
soloType                          Droplet
soloUMIstart                      9
soloCBlen                         8
soloBarcodeReadLength             30
soloCBwhitelist                   /ye/yelabstore3/cidseq/scripts/scicrop_bcs.txt
soloOutFileNames                  ./sampleA_solo_   

-------------------------------
##### Final effective command line:
STAR   --genomeDir /ye/netapp/jimmie.ye/ref/star/grch38/grch38_star_74overhang/   --readFilesIn /ye/yelabstore3/cidseq/data/190506-1_miniseq/190424-1_fastq/190422-1/190422-1_sampleA_S1_L001_R3_001.fastq.gz   /ye/yelabstore3/cidseq/data/190506-1_miniseq/190424-1_fastq/190422-1/sciseq/190422-1_sampleA_S1_L001.bc2-bc1-umi.Rscript.fastq.gz      --readFilesCommand zcat      --soloType Droplet   --soloUMIstart 9   --soloCBlen 8   --soloBarcodeReadLength 30   --soloCBwhitelist /ye/yelabstore3/cidseq/scripts/scicrop_bcs.txt   --soloOutFileNames ./sampleA_solo_   

##### Final parameters after user input--------------------------------:
versionGenome                     2.7.0d
parametersFiles                   -   
sysShell                          -
runMode                           alignReads
runThreadN                        1
runDirPerm                        User_RWX
runRNGseed                        777
genomeDir                         /ye/netapp/jimmie.ye/ref/star/grch38/grch38_star_74overhang/
genomeLoad                        NoSharedMemory
genomeFastaFiles                  -   
genomeChainFiles                  -   
genomeSAindexNbases               14
genomeChrBinNbits                 18
genomeSAsparseD                   1
genomeSuffixLengthMax             18446744073709551615
genomeFileSizes                   0   
genomeConsensusFile               -
readFilesType                     Fastx   
readFilesIn                       /ye/yelabstore3/cidseq/data/190506-1_miniseq/190424-1_fastq/190422-1/190422-1_sampleA_S1_L001_R3_001.fastq.gz   /ye/yelabstore3/cidseq/data/190506-1_miniseq/190424-1_fastq/190422-1/sciseq/190422-1_sampleA_S1_L001.bc2-bc1-umi.Rscript.fastq.gz   
readFilesPrefix                   -
readFilesCommand                  zcat   
readMatesLengthsIn                NotEqual
readMapNumber                     18446744073709551615
readNameSeparator                 /   
inputBAMfile                      -
bamRemoveDuplicatesType           -
bamRemoveDuplicatesMate2basesN    0
limitGenomeGenerateRAM            31000000000
limitIObufferSize                 150000000
limitOutSAMoneReadBytes           100000
limitOutSJcollapsed               1000000
limitOutSJoneRead                 1000
limitBAMsortRAM                   0
limitSjdbInsertNsj                1000000
limitNreadsSoft                   18446744073709551615
outFileNamePrefix                 ./
outTmpDir                         -
outTmpKeep                        None
outStd                            Log
outReadsUnmapped                  None
outQSconversionAdd                0
outMultimapperOrder               Old_2.4
outSAMtype                        SAM   
outSAMmode                        Full
outSAMstrandField                 None
outSAMattributes                  Standard   
outSAMunmapped                    None   
outSAMorder                       Paired
outSAMprimaryFlag                 OneBestScore
outSAMreadID                      Standard
outSAMmapqUnique                  255
outSAMflagOR                      0
outSAMflagAND                     65535
outSAMattrRGline                  -   
outSAMheaderHD                    -   
outSAMheaderPG                    -   
outSAMheaderCommentFile           -
outBAMcompression                 1
outBAMsortingThreadN              0
outBAMsortingBinsN                50
outSAMfilter                      None   
outSAMmultNmax                    18446744073709551615
outSAMattrIHstart                 1
outSAMtlen                        1
outSJfilterReads                  All
outSJfilterCountUniqueMin         3   1   1   1   
outSJfilterCountTotalMin          3   1   1   1   
outSJfilterOverhangMin            30   12   12   12   
outSJfilterDistToOtherSJmin       10   0   5   10   
outSJfilterIntronMaxVsReadN       50000   100000   200000   
outWigType                        None   
outWigStrand                      Stranded   
outWigReferencesPrefix            -
outWigNorm                        RPM   
outFilterType                     Normal
outFilterMultimapNmax             10
outFilterMultimapScoreRange       1
outFilterScoreMin                 0
outFilterScoreMinOverLread        0.66
outFilterMatchNmin                0
outFilterMatchNminOverLread       0.66
outFilterMismatchNmax             10
outFilterMismatchNoverLmax        0.3
outFilterMismatchNoverReadLmax    1
outFilterIntronMotifs             None
outFilterIntronStrands            RemoveInconsistentStrands
clip5pNbases                      0   
clip3pNbases                      0   
clip3pAfterAdapterNbases          0   
clip3pAdapterSeq                  -   
clip3pAdapterMMp                  0.1   
winBinNbits                       16
winAnchorDistNbins                9
winFlankNbins                     4
winAnchorMultimapNmax             50
winReadCoverageRelativeMin        0.5
winReadCoverageBasesMin           0
scoreGap                          0
scoreGapNoncan                    -8
scoreGapGCAG                      -4
scoreGapATAC                      -8
scoreStitchSJshift                1
scoreGenomicLengthLog2scale       -0.25
scoreDelBase                      -2
scoreDelOpen                      -2
scoreInsOpen                      -2
scoreInsBase                      -2
seedSearchLmax                    0
seedSearchStartLmax               50
seedSearchStartLmaxOverLread      1
seedPerReadNmax                   1000
seedPerWindowNmax                 50
seedNoneLociPerWindow             10
seedMultimapNmax                  10000
seedSplitMin                      12
alignIntronMin                    21
alignIntronMax                    0
alignMatesGapMax                  0
alignTranscriptsPerReadNmax       10000
alignSJoverhangMin                5
alignSJDBoverhangMin              3
alignSJstitchMismatchNmax         0   -1   0   0   
alignSplicedMateMapLmin           0
alignSplicedMateMapLminOverLmate    0.66
alignWindowsPerReadNmax           10000
alignTranscriptsPerWindowNmax     100
alignEndsType                     Local
alignSoftClipAtReferenceEnds      Yes
alignEndsProtrude                 0   ConcordantPair   
alignInsertionFlush               None
peOverlapNbasesMin                0
peOverlapMMp                      0.01
chimSegmentMin                    0
chimScoreMin                      0
chimScoreDropMax                  20
chimScoreSeparation               10
chimScoreJunctionNonGTAG          -1
chimMainSegmentMultNmax           10
chimJunctionOverhangMin           20
chimOutType                       Junctions   
chimFilter                        banGenomicN   
chimSegmentReadGapMax             0
chimMultimapNmax                  0
chimMultimapScoreRange            1
chimNonchimScoreDropMin           20
chimOutJunctionFormat             0   
sjdbFileChrStartEnd               -   
sjdbGTFfile                       -
sjdbGTFchrPrefix                  -
sjdbGTFfeatureExon                exon
sjdbGTFtagExonParentTranscript    transcript_id
sjdbGTFtagExonParentGene          gene_id
sjdbOverhang                      100
sjdbScore                         2
sjdbInsertSave                    Basic
varVCFfile                        -
waspOutputMode                    None
quantMode                         -   
quantTranscriptomeBAMcompression    1
quantTranscriptomeBan             IndelSoftclipSingleend
twopass1readsN                    18446744073709551615
twopassMode                       None
soloType                          Droplet
soloCBstart                       1
soloUMIstart                      9
soloCBlen                         8
soloUMIlen                        10
soloBarcodeReadLength             30
soloCBwhitelist                   /ye/yelabstore3/cidseq/scripts/scicrop_bcs.txt
soloStrand                        Forward
soloOutFileNames                  ./sampleA_solo_   
soloFeatures                      Gene   
soloUMIdedup                      1MM_All   
----------------------------------------


   Input read files for mate 1, from input string /ye/yelabstore3/cidseq/data/190506-1_miniseq/190424-1_fastq/190422-1/190422-1_sampleA_S1_L001_R3_001.fastq.gz
-rw-r--r--. 1 codymowery ye 82242948 May  7 08:57 /ye/yelabstore3/cidseq/data/190506-1_miniseq/190424-1_fastq/190422-1/190422-1_sampleA_S1_L001_R3_001.fastq.gz

   readsCommandsFile:
exec > "./_STARtmp/tmp.fifo.read1"
echo FILE 0
zcat      "/ye/yelabstore3/cidseq/data/190506-1_miniseq/190424-1_fastq/190422-1/190422-1_sampleA_S1_L001_R3_001.fastq.gz"


   Input read files for mate 2, from input string /ye/yelabstore3/cidseq/data/190506-1_miniseq/190424-1_fastq/190422-1/sciseq/190422-1_sampleA_S1_L001.bc2-bc1-umi.Rscript.fastq.gz
-rw-r--r--. 1 codymowery ye 58194723 May 29 18:11 /ye/yelabstore3/cidseq/data/190506-1_miniseq/190424-1_fastq/190422-1/sciseq/190422-1_sampleA_S1_L001.bc2-bc1-umi.Rscript.fastq.gz

   readsCommandsFile:
exec > "./_STARtmp/tmp.fifo.read2"
echo FILE 0
zcat      "/ye/yelabstore3/cidseq/data/190506-1_miniseq/190424-1_fastq/190422-1/sciseq/190422-1_sampleA_S1_L001.bc2-bc1-umi.Rscript.fastq.gz"

Turning on Genomic->Transcriptomic coordinate conversion for STARsolo
May 30 08:06:16Finished reading CB whitelist sequences: 48
Finished loading and checking parameters
Reading genome generation parameters:
### STAR   --runMode genomeGenerate   --runThreadN 8   --genomeDir ./grch38_star_74overhang   --genomeFastaFiles ./seqs/grch38_r95.all.fa      --sjdbGTFfile ./annotations/Homo_sapiens.GRCh38.95.gtf   --sjdbOverhang 74
### GstrandBit=32
versionGenome                 2.7.0d     ~RE-DEFINED
genomeFastaFiles              ./seqs/grch38_r95.all.fa        ~RE-DEFINED
genomeSAindexNbases           14     ~RE-DEFINED
genomeChrBinNbits             18     ~RE-DEFINED
genomeSAsparseD               1     ~RE-DEFINED
sjdbOverhang                  74     ~RE-DEFINED
sjdbFileChrStartEnd           -        ~RE-DEFINED
sjdbGTFfile                   ./annotations/Homo_sapiens.GRCh38.95.gtf     ~RE-DEFINED
sjdbGTFchrPrefix              -     ~RE-DEFINED
sjdbGTFfeatureExon            exon     ~RE-DEFINED
sjdbGTFtagExonParentTranscripttranscript_id     ~RE-DEFINED
sjdbGTFtagExonParentGene      gene_id     ~RE-DEFINED
sjdbInsertSave                Basic     ~RE-DEFINED
genomeFileSizes               3145264814   24653611434        ~RE-DEFINED
Genome version is compatible with current STAR
Number of real (reference) chromosomes= 25
1	10	133797422	0
2	11	135086622	133955584
3	12	133275309	269221888
4	13	114364328	402653184
5	14	107043718	517210112
6	15	101991189	624427008
7	16	90338345	726663168
8	17	83257441	817102848
9	18	80373285	900464640
10	19	58617616	980942848
11	1	248956422	1039663104
12	20	64444167	1288699904
13	21	46709983	1353187328
14	22	50818468	1400111104
15	2	242193529	1450967040
16	3	198295559	1693188096
17	4	190214555	1891631104
18	5	181538259	2081947648
19	6	170805979	2263613440
20	7	159345973	2434531328
21	8	145138636	2593914880
22	9	138394717	2739142656
23	MT	16569	2877554688
24	X	156040895	2877816832
25	Y	57227415	3034054656
--sjdbOverhang = 74 taken from the generated genome
Started loading the genome: Thu May 30 08:06:16 2019

Genome: size given as a parameter = 3145264814
SA: size given as a parameter = 24653611434
SAindex: size given as a parameter = 1
Read from SAindex: pGe.gSAindexNbases=14  nSAi=357913940
nGenome=3145264814;  nSAbyte=24653611434
GstrandBit=32   SA number of indices=5976633074
Shared memory is not used for genomes. Allocated a private copy of the genome.
Genome file size: 3145264814 bytes; state: good=1 eof=0 fail=0 bad=0
Loading Genome ... done! state: good=1 eof=0 fail=0 bad=0; loaded 3145264814 bytes
SA file size: 24653611434 bytes; state: good=1 eof=0 fail=0 bad=0
Loading SA ... done! state: good=1 eof=0 fail=0 bad=0; loaded 24653611434 bytes
Loading SAindex ... done: 1565873619 bytes
Finished loading the genome: Thu May 30 08:07:55 2019

Processing splice junctions database sjdbN=361078,   pGe.sjdbOverhang=74 
alignIntronMax=alignMatesGapMax=0, the max intron size will be approximately determined by (2^winBinNbits)*winAnchorDistNbins=589824
Loaded transcript database, nTr=206534
Loaded exon database, nEx=1261907
Starting to map file # 0
mate 1:   /ye/yelabstore3/cidseq/data/190506-1_miniseq/190424-1_fastq/190422-1/190422-1_sampleA_S1_L001_R3_001.fastq.gz
mate 2:   /ye/yelabstore3/cidseq/data/190506-1_miniseq/190424-1_fastq/190422-1/sciseq/190422-1_sampleA_S1_L001.bc2-bc1-umi.Rscript.fastq.gz
Thread #0 end of input stream, nextChar=-1
Completed: thread #0
May 30 08:10:21 ... Starting Solo post-map for Gene
May 30 08:10:21 ... Finished allocating arrays for Solo 0.0215704 GB
May 30 08:10:21 ... Finished reading reads from Solo files nCB=44, nReadPerCBmax=78480, nMatch=1433626
May 30 08:10:21 ... Finished collapsing UMIs`

**Comment by alexdobin** [comment]
Hi @codymowery 

not sure what's going on, there should not be large array allocations at that point...
Could you share the fastq files, as well as the whitelist, I will try to reproduce the problem.

Cheers
Alex

**Comment by codymowery** [comment]
I realized soon after posting that you released 2.7.1a, which appears to resolve the issue. Thanks anyway!

**Comment by alexdobin** [comment]
Great, thanks!
