### ISSUE TITLE
Variant location is 0-based or 1-based from vG (-varVCFfile ) ? 

### ISSUE THREAD

**Issue by heyuan7676** [alexdobin/STAR#652]
Hi Alex,

I'm using STAR to do alignment and I'd like to identify the variant which each read maps to. I use `--varVCFfile ${vcfFn} --outSAMattributes NH HI AS nM NM MD vA vG --outSAMtype BAM SortedByCoordinate`. 

In the output, there are some line where the variant location in `vG` is smaller than the 1-based start of the read (4th column in sam output). One line is attached for example:
`HISEQ:373:C6HBMANXX:3:1101:20693:4035	0	6	162234638	255	50M	*	0	0	CTAATACTTTTCATATTTATTTTAAAATTTGCATTATGTTTTATATTTAT	BBBBBFFFFFFFFFFFFFFFFFFFFFFFFFBFFFFFFFFFFFFFFFFFFF	NH:i:1	HI:i:1	AS:i:49	nM:i:0	NM:i:0	MD:Z:50	vA:B:c,1	vG:B:i, 162234637 `

In this line, the read maps to chromosome 6: 162234638  (1-based), and the variant location is 162234637. 

I didn't find the detailed vG in the documentation, and I'm guessing it is 0-based. Can you verify this? Thank you!

Best,
Yuan

**Comment by alexdobin** [comment]
Hi Yuan,

indeed, the variant coordinate in the vG field is 0-based. 
I am thinking now that this was a bad choice, and I should make it 1-based   -  as the SAM and VCF coordinates.

Cheers
Alex

**Comment by heyuan7676** [comment]
Thank you for verifying!

Best,
Yuan

**Comment by miramou** [comment]
Thank you for this ! I Just wanted to bump this post, and note that it'd be really helpful if the documentation included that vG is 0-indexed whereas VCFs are commonly 1-indexed. I've been trying to figure out why I couldn't match all the variants called by STAR with the entries of the VCF I passed via -varVCFfile. This issue shed light on what I should've realized before (but hadn't), which led to a good bit of confusion on my part.

Best,
Mira

**Comment by s-hoyt** [comment]
Hi Alex, In what version of STAR was this update made? I am also having this issue, and I think the version on my compute cluster is pretty old. 

Thanks,
Stephanie

**Comment by alexdobin** [comment]
Hi Stephanie,

there was no change in STAR - the vG coordinates are still 0-based.
