### ISSUE TITLE
 Segmentation fault after mapping

### ISSUE THREAD

**Issue by lijing28101** [alexdobin/STAR#653]
Hi, I tried both version 2.5 and 2.7. Both were failed after mapping with same error.
Only show `Segmentation fault      (core dumped)` 
My reference genome is zea mays, the annotation file just a test with several lines.
I set my memory with 100 GB, and node with 16 cores.
Here is my code
```
 /home/jingli/bin/STAR-2.7.1a/source/STAR \
      --runThreadN 16 \
      --genomeDir $dir \
      --genomeLoad NoSharedMemory \
      --runMode alignReads \
      --sjdbGTFfile $gtf \
      --sjdbOverhang $len \
      --readFilesIn $read1 $read2 \
      --readFilesCommand zcat \
      --outFileNamePrefix ${out}_ \
      --outSAMtype BAM SortedByCoordinate \
      --outBAMsortingThreadN 4 \
      --limitBAMsortRAM 30000000000 \
      --outWigType bedGraph  \
      --outWigStrand Unstranded
```
Here is my log file
[star_log.txt](https://github.com/alexdobin/STAR/files/3249606/star_log.txt)

Could you help me to figure out the problem?
Thanks!

**Comment by alexdobin** [comment]
Hi @lijing28101 

please try to map without the gff file. Not sure if the formatting of that file is correct, it has only 10 exons and no junctions.

Cheers
Alex

**Comment by lijing28101** [comment]
Hi Alex,

I tried to map without gff file, but it still have the same error. And the log file stop at the same place.

Best,
Jing

**Comment by alexdobin** [comment]
Hi Jing,

have you made any changes to the Zea_mays.B73.v4 fasta? Your file is called "clean". :)
Could you please try to use the standard B73.v4 fasta and check if the problem persists?

Cheers
Alex

**Comment by lijing28101** [comment]
Hi Alex,

It failed when I used the original fasta file, since the header of
chromosome is longer than gff file.
I just change the header. I don't think it is the reason for the
segmentation fault.

Best,
Jing

**Comment by alexdobin** [comment]
Hi Jing,

all right, in this case, I need to replicate the error on my side. Could you send me a minimalistic set of reads that still causes the seg-fault. You could check the number of reads mapped before the seg-fault in the Log.progress.out file. 

Cheers
Alex

**Comment by lijing28101** [comment]
Hi Alex,

I download the reads from the link:
ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR965/ERR965625/

And there is nothing in the Log.progress.out file.
```
           Time    Speed        Read     Read   Mapped   Mapped   Mapped   Mapped Unmapped Unmapped Unmapped Unmapped
                    M/hr      number   length   unique   length   MMrate    multi   multi+       MM    short    other
```

Best,
Jing

**Comment by alexdobin** [comment]
Hi @lijing28101 

I have mapped this sample to the AGPv4 genome, and it completed without a problem.
Please try to generate the genome and map with the precompiled STAR executables in bin/Linux*

Cheers
Alex

**Comment by lijing28101** [comment]
Hi @alexdobin 

Did you change the header in the genome? Or just used the original file download from maizeGDB?

Thanks,
Jing

**Comment by alexdobin** [comment]
Hi Jing,

I have used this FASTA file:
ftp://ftp.ensemblgenomes.org/pub/plants/release-36/fasta/zea_mays/dna/Zea_mays.AGPv4.dna.toplevel.fa.gz
and I have not made any changed the FASTA.

Cheers
Alex
