### ISSUE TITLE
--soloFeatures GeneFull not generating genes.tsv

### ISSUE THREAD

**Issue by guilhermesena1** [alexdobin/STAR#654]
Hello,

First off thank you so much for this amazing tool I use in a daily basis since the beginning of my PhD!

I am processing a drop-seq dataset ([SRR6049392](https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR6049392)) trying both --soloFeatures Gene and GeneFull, and noticed that the genes.tsv file is not generated with GeneFull option. I was wondering if this is a design choice or if maybe I'm setting some flag that is disabling the file generation since it should be the exact same file with either option.

This is how I run it:

```
STAR \
   --outFileNamePrefix test \
   --quantMode GeneCounts \ 
   --outSAMtype BAM SortedByCoordinate \ 
   --outSAMattributes NH HI NM MD CR CY UR UY \ 
   --bamRemoveDuplicatesType UniqueIdentical  \
   --runThreadN 16  \
   --outBAMsortingThreadN 16 \ 
   --genomeDir /path/to/STAR_index \ 
   --sjdbGTFfile /path/to/genes.gtf  \
   --sjdbGTFtagExonParentGeneName gene_name \ 
   --soloType Droplet  \
   --soloCBlen 12  \
   --soloUMIstart 13 \ 
   --soloUMIlen 8  \
   --soloBarcodeReadLength 1 \ 
   --soloCBwhitelist None   \
   --soloStrand Unstranded  \
   --soloFeatures GeneFull  \
   --readFilesIn SRR6049392_2.fastq SRR6049392_1.fastq \
```
With the same settings but with Gene option on --soloFeatures the file is generated. 
Thank you very much in advance!

**Comment by alexdobin** [comment]
Hi Guilherme

thanks for reporting this, looks like a bug.
The gene list is exactly the same for Gene and GeneFull, if you use --soloFeatures Gene GeneFull in one run it will generate the genes.tsv file, which applies to both Gene and GeneFull outputs.
However, it needs to generate this file even for singular --soloFeatures GeneFull run, will fix it in the next release.

Thanks!
Alex

**Comment by guilhermesena1** [comment]
Hi Alex,

perfect! I was not aware we could use multiple options for solo parameters, that actually solves it for my case.

Thank you very much for the clarification!
