### ISSUE TITLE
Repeats masked reference genomes

### ISSUE THREAD

**Issue by Carlos210892** [alexdobin/STAR#655]
Does STAR support genomes whose repetitions have previously been masked?

**Comment by alexdobin** [comment]
Hi Carlos,

if the repeats are masked as Ns, STAR will assume that the nucleotides at those positions are unknown. If you have repeats masked with lower-case acgt, you would need to convert them to Ns. However, I generally do not recommend masking the repeats, as it will force those reads that originate in repeats to map (falsely) somewhere else in the genome.

Cheers
Alex

**Comment by Carlos210892** [comment]
Hi Alex:

Thanks for the detailed response.

Best regards,
Carlos
