### ISSUE TITLE
Segfault after mapping starts

### ISSUE THREAD

**Issue by benhg** [alexdobin/STAR#657]
Hello,

I'm running STAR on a small HPC cluster and am getting a segfault before the mapping process can finish up. Here's how I'm calling it:

```
STAR --runMode alignReads --runThreadN 48 --genomeDir m1704/genome_directory --readFilesIn m1704/lane2-s022-indexRPI23-GAGTGG-MP3_WB_S22_L002_R1_001.fastq m1704/lane2-s022-indexRPI23-GAGTGG-MP3_WB_S22_L002_R2_001.fastq --outFileNamePrefix m1704/22

``` 

And here's the output:

```Jun 05 17:37:37 ..... started STAR run
Jun 05 17:37:37 ..... loading genome
Jun 05 17:37:37 ..... started mapping
Segmentation fault (core dumped)
```

The node it's running on has 500GB of memory, and it shouldn't be running out.

Thanks

**Comment by alexdobin** [comment]
Hi Ben,

is this a small genome, and if so, have you scaled the --genomeSAindexNbases as 
min(14, log2(GenomeLength)/2 - 1) ?

If this does not help, please send me the Log.out file.

Cheers
Alex

**Comment by benhg** [comment]
Hi Alex,

I have just found this post: (https://groups.google.com/forum/#!topic/rna-star/6csLuVjxiR0)

--genomeSAindexNbases was set before as as min(14, log2(GenomeLength)/2 - 1).

Now, setting it to 2 manually has fixed the problem.

Perhaps I could write an error handler that logs this as a likely problem when this segfault occurs. Is that something that might be useful for the project?

Thanks very much,
Ben

**Comment by alexdobin** [comment]
Hi Ben,

in the latest release, I had added a warning that the parameter is not scale properly at the genome generation step. I think it would be a good idea to do it also for the mapping step.

Cheers
Alex
