### ISSUE TITLE
-vA 1/2/3 in output from -varVCFfile. 

### ISSUE THREAD

**Issue by heyuan7676** [alexdobin/STAR#658]
Hi Alex,

I'm trying to get the exact variants on which reads map to, and I'm trying to get the information from the read sequence and the location of the variant. 

I'm a little confused about what does -vA mean in the output of -varVCFfile? In the document, it said "vA outputs which allele is detected in the read: 1 or 2 match one of the genotype alleles". Does it mean A/T, or C/G ? 

ie. a read ACTGA, where the first neutiotide is a variant. How should I interpret the result with vA:B:c,1, vA:B:c,2 and result with vA:B:c,3? 

Thank you!

Best,
Yuan

**Comment by alexdobin** [comment]
Hi Yuan,

the vA tag tells you whether the variant matches the genotypes listed in the VCF file.
E.g., in the VCF you have
chr1    931042  .   C       T       .       .       .       .       0/1
Then vA=1 will mean C and vA=2 will mean T. vA=3 means it's neither C or T.
I probably should have a tag that lists just the base in the read.

Cheers
Alex

**Comment by heyuan7676** [comment]
Thank you! So it doesn't matter what the read actually is? 

For example, 
the mapping result from STAR is: ... A(variant)CTG ... , vA:B:c, 2.
the VCF file for this variant is:      chr1 931042 . A G ... 0/1

Then the read should be mapped to variant G, even though the read itself has an A? 

Best,
Yuan

**Comment by alexdobin** [comment]
vA depends on the variant base in the read.
In your example, if the read has A in the variant position, vA will be 1.

**Comment by heyuan7676** [comment]
Got you. Thanks!
Do you recommend filtering out reads with vA=3?

**Comment by heyuan7676** [comment]
Hi Alex,

I went back to the mapping results, and looked at two random reads. 

Read 1:
`HWI-ST1309F:198:C6RFFANXX:6:2101:11642:85319	0	22	16045019	255	50M	*	0	0	AGAGATTCAAAACTGCTCATGGAAAAGATAAGTTCACCTCAGTGAGTTGA	BBBBBFFFFFFFFFBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	NH:i:1	HI:i:1	AS:i:45	nM:i:2	NM:i:2	MD:Z:34G1A13	vA:B:c,1,1	vG:B:i,16045052,16045054	vW:i:1`

For VCF file of the variant chr1: 16045053:
`chr22	16045053	chr22_16045053_G_C_b38	G	C`

From `vA=1`, the variant at location 16045053 should be `G`;
From the variant location 16045053 and the read's location 16045019, the 35th nt in the read `AGAGATTCAAAACTGCTCATGGAAAAGATAAGTTCACCTCAGTGAGTTGA` is the variant, which is `C`.

For read 2, the situation is that the two variant from two sources match.

Could you let me know if I should use "vA" or the read's information? 


Best,
Yuan

**Comment by alexdobin** [comment]
Hi Yuan,

what was the genotype of this variant? If it was 1/0, i.e.
chr22   16045053        chr22_16045053_G_C_b38  G       C       .       .       .       .       1/0
then for this individual, the "1st" haplotype has C, and the "2nd" haplotype is G.
Since the read has C, STAR reports it as haplotype 1.

Cheers
Alex

**Comment by Lizd0630** [comment]
Hi Alex,

Can I use common SNP vcf file (make it heterozygous: 1/0) from dbSNP as  -varVCFfile input for I haven't matched vcf file of RNAseq? Will this  disturb alignment if there is no SNP in some loci of sample?

**Comment by alexdobin** [comment]
Hi Li,

yes, this is possible - however, it may become too slow if you have too many SNPs. I would recommend filtering SNPs by allele frequency, e.g. only include those with AF>1% .

Cheers
Alex

**Comment by Lizd0630** [comment]
thank you, 
best wishes!
