### ISSUE TITLE
Supplying a FASTA directory instead of a .fa file causes STAR genomeGenerate to hang

### ISSUE THREAD

**Issue by kohpangwei** [alexdobin/STAR#66]
When running STAR --runMode genomeGenerate, if you supply --genomeFastaFiles with the folder your FASTA file is in (vs. the actual FASTA file), STAR chugs away forever on a single core. It should return an error message instantly.

**Comment by alexdobin** [comment]
Thanks for pointing this out. it's fixed in the latest patch.
