### ISSUE TITLE
Parameters_closeReadsFiles.cpp:12:13: error: ‘kill’ was not declared in this scope

### ISSUE THREAD

**Issue by DelaVegaPablo** [alexdobin/STAR#661]
Hello Alex, 

I have not been able to compile STAR as I keep getting the error below.

I have include the signal.h library and the iostream headers in the Parameters_closeReadsFiles.cpp file with no success.  Could you please advise, 

Thank you very much

Parameters_closeReadsFiles.cpp: In member function ‘void Parameters::closeReadsFiles()’:
Parameters_closeReadsFiles.cpp:12:13: error: ‘kill’ was not declared in this scope
             kill(readFilesCommandPID[imate],SIGKILL);
             ^~~~
make: *** [Makefile:115: STAR] Error 1

**Comment by alexdobin** [comment]
Hi @DelaVegaPablo 

this is likely a problem with the gcc/glibc installation on your server. You can try the precompiled STAR executables in the bin/Linux* directories, or compile on another server, or install a separate gcc instance.

Cheers
Alex

**Comment by DelaVegaPablo** [comment]
Hi Alex,

Thank you very much for your reply. I have installed Linux in my computer
and things are running now.  I will close the issue first thing tomorrow.

I am sure I will have many more questions to bother you with, but I want
you to know I really appreciate the fact you took the time to answer my
question.

Best regards,

Pablo

**Comment by alexdobin** [comment]
Sure, thanks, Pablo!
