### ISSUE TITLE
generate Chimera.out.junction from STAR BAM

### ISSUE THREAD

**Issue by nairasha** [alexdobin/STAR#663]
Hi Alex,

Is there a straightforward/stand-alone way to re-generate Chimera.out.junction files from existing STAR aligned BAMs? 

We have processed all samples in GTEx through STAR (v2.5.2b), but unfortunately while archiving the results, the Chimera.out.junction files were deleted. I now have a project that needs these files and as you can imagine, it is going to be onerous to go back and re-download .sra for all the GTEx samples again.

The STAR aligner parameters we used were:

STAR   --runThreadN 4   --genomeDir /GRCh38/star_index   --readFilesIn SRR1404887_1.fastq.gz   SRR1404887_2.fastq.gz      --readFilesCommand /bin/zcat      --limitBAMsortRAM 56330294591   --outFileNamePrefix SRR1404887.   --outSAMtype BAM   SortedByCoordinate      --outSAMstrandField intronMotif   --outSAMunmapped Within      --outBAMsortingThreadN 4   --alignIntronMax 200000   --alignMatesGapMax 200000   --alignSJDBoverhangMin 10   --chimSegmentMin 12   --chimJunctionOverhangMin 12   --twopass1readsN 18446744073709551615   --twopassMode Basic

Thanks much in advance!
Asha

**Comment by alexdobin** [comment]
Hi Asha,

unfortunately, there is no way to do this - chimeric alignments are not recorded in BAM files unless --chimOutType WithinBAM option is used.

Cheers
Alex

**Comment by nairasha** [comment]
Good to know, thanks for your response, Alex.
Asha

**Comment by sterding** [comment]
> Hi Asha,
> 
> unfortunately, there is no way to do this - chimeric alignments are not recorded in BAM files unless --chimOutType WithinBAM option is used.
> 
> Cheers
> Alex

Hi Alex,

With --chimOutType WithinBAM option is used, how can we easily generate Chimera.out.junction from STAR BAM? Which flag do you recommend to use?

Thanks,
-Xianjun

**Comment by yeswzc** [comment]
I have the same question.
Do anyone know how to " easily generate Chimera.out.junction from STAR BAM With --chimOutType WithinBAM option used" ?

Thanks!

**Comment by alexdobin** [comment]
Hi Zhichao,

there is no simple option at the moment, but it would be a great contribution! :)

Cheers
Alex

**Comment by yeswzc** [comment]
> Hi Zhichao,
> 
> there is no simple option at the moment, but it would be a great contribution! :)
> 
> Cheers
> Alex

Thanks, Alex. I can put them into a separate sam file.
Cheers.

**Comment by kkotkowska** [comment]
Hi Alex,
Is there now a possibility to retrieve the Chimeric.out.junction content from a  BAM With --chimOutType WithinBAM option used?

Thanks,
Klara
