### ISSUE TITLE
STAR installation problem

### ISSUE THREAD

**Issue by hyl317** [alexdobin/STAR#664]
Hi, I encountered the following error while trying to install STAR on Debian GNU/Linux 8.11. Not sure. Noting the first line "Depend.list" No such file or directory. Does that mean there is something wrong with gcc (I checked my gcc version, it is 4.9.2; I saw from previous post that 4.7.0 or newer would be fine)? Thx in advance! 
yh362@mocha:~/tools/STAR/source$ make STAR
Makefile:97: Depend.list: No such file or directory
make -C htslib lib-static
make[1]: Entering directory '/data/home/yh362/tools/STAR/source/htslib'
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o kfunc.o kfunc.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o knetfile.o knetfile.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o kstring.o kstring.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o bgzf.o bgzf.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o faidx.o faidx.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o hfile.o hfile.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o hfile_net.o hfile_net.c
echo '#define HTS_VERSION "0.0.1"' > version.h
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o hts.o hts.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o sam.o sam.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o synced_bcf_reader.o synced_bcf_reader.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o vcf_sweep.o vcf_sweep.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o tbx.o tbx.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o vcf.o vcf.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o vcfutils.o vcfutils.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/cram_codecs.o cram/cram_codecs.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/cram_decode.o cram/cram_decode.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/cram_encode.o cram/cram_encode.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/cram_index.o cram/cram_index.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/cram_io.o cram/cram_io.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/cram_samtools.o cram/cram_samtools.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/cram_stats.o cram/cram_stats.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/files.o cram/files.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/mFILE.o cram/mFILE.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/md5.o cram/md5.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/open_trace_file.o cram/open_trace_file.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/pooled_alloc.o cram/pooled_alloc.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/sam_header.o cram/sam_header.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/string_alloc.o cram/string_alloc.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/thread_pool.o cram/thread_pool.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/vlen.o cram/vlen.c
cram/vlen.c: In function ‘vflen’:
cram/vlen.c:121:9: warning: variable ‘i’ set but not used [-Wunused-but-set-variable]
     int i;
         ^
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o cram/zfio.o cram/zfio.c
ar -rc libhts.a kfunc.o knetfile.o kstring.o bgzf.o faidx.o hfile.o hfile_net.o hts.o sam.o synced_bcf_reader.o vcf_sweep.o tbx.o vcf.o vcfutils.o cram/cram_codecs.o cram/cram_decode.o cram/cram_encode.o cram/cram_index.o cram/cram_io.o cram/cram_samtools.o cram/cram_stats.o cram/files.o cram/mFILE.o cram/md5.o cram/open_trace_file.o cram/pooled_alloc.o cram/sam_header.o cram/string_alloc.o cram/thread_pool.o cram/vlen.o cram/zfio.o
ranlib libhts.a
make[1]: Leaving directory '/data/home/yh362/tools/STAR/source/htslib'
echo SoloRead.cpp SoloFeature_processRecords.cpp ReadAlignChunk.cpp Transcriptome.cpp Chain.cpp ReadAlign_outputTranscriptCIGARp.cpp ErrorWarning.cpp Stats.cpp blocksOverlap.cpp Transcript_generateCigarP.cpp SoloReadFeature_record.cpp ChimericAlign.cpp SoloReadBarcode.cpp Parameters_openReadsFiles.cpp sjdbLoadFromStream.cpp stitchAlignToTranscript.cpp TimeFunctions.cpp stitchGapIndel.cpp GlobalVariables.cpp signalFromBAM.cpp ReadAlign_calcCIGAR.cpp Genome_genomeGenerate.cpp outputSJ.cpp Parameters_closeReadsFiles.cpp SoloFeature_collapseUMI.cpp stitchWindowAligns.cpp Parameters.cpp ReadAlign_createExtendWindowsWithAlign.cpp ReadAlign_chimericDetection.cpp SoloRead_record.cpp binarySearch2.cpp BAMfunctions.cpp sjAlignSplit.cpp ReadAlign_maxMappableLength2strands.cpp ReadAlignChunk_mapChunk.cpp serviceFuns.cpp ThreadControl.cpp Genome_insertSequences.cpp sjdbInsertJunctions.cpp genomeParametersWrite.cpp ReadAlign_chimericDetectionPEmerged.cpp BAMbinSortUnmapped.cpp insertSeqSA.cpp streamFuns.cpp ReadAlignChunk_processChunks.cpp BAMoutput.cpp ReadAlign_multMapSelect.cpp Transcript_alignScore.cpp ReadAlign_chimericDetectionOldOutput.cpp ReadAlign_chimericDetectionOld.cpp PackedArray.cpp ReadAlign_outputVariation.cpp ReadAlign_outputTranscriptSJ.cpp funCompareUintAndSuffixesMemcmp.cpp SequenceFuns.cpp ReadAlign.cpp Transcriptome_geneFullAlignOverlap.cpp loadGTF.cpp ReadAlign_assignAlignToWindow.cpp genomeSAindex.cpp stringSubstituteAll.cpp ChimericDetection.cpp SoloReadBarcode_getCBandUMI.cpp Transcriptome_geneCountsAddAlign.cpp sysRemoveDir.cpp Transcript_variationAdjust.cpp ReadAlign_waspMap.cpp ReadAlign_storeAligns.cpp InOutStreams.cpp SharedMemory.cpp genomeScanFastaFiles.cpp sjdbPrepare.cpp ReadAlign_oneRead.cpp ReadAlign_mappedFilter.cpp ReadAlign_CIGAR.cpp Transcript_variationOutput.cpp ParametersSolo.cpp Transcript.cpp SuffixArrayFuns.cpp alignSmithWaterman.cpp extendAlign.cpp ChimericAlign_chimericStitching.cpp OutSJ.cpp sjdbLoadFromFiles.cpp ReadAlign_peOverlapMergeMap.cpp ReadAlign_quantTranscriptome.cpp sjdbBuildIndex.cpp Genome.cpp Variation.cpp ReadAlign_outputTranscriptSAM.cpp ReadAlign_mapOneRead.cpp ChimericAlign_chimericJunctionOutput.cpp readLoad.cpp mapThreadsSpawn.cpp SoloReadFeature.cpp ChimericDetection_chimericDetectionMult.cpp Quantifications.cpp SoloReadFeature_inputRecords.cpp ChimericSegment.cpp ReadAlign_stitchPieces.cpp funCompareUintAndSuffixes.cpp SoloFeature.cpp bamRemoveDuplicates.cpp STAR.cpp Parameters_readSAMheader.cpp BAMbinSortByCoordinate.cpp Solo.cpp Transcriptome_quantAlign.cpp ReadAlign_outputAlignments.cpp ReadAlign_alignBAM.cpp SoloFeature_outputResults.cpp ReadAlign_stitchWindowSeeds.cpp bam_cat.c
SoloRead.cpp SoloFeature_processRecords.cpp ReadAlignChunk.cpp Transcriptome.cpp Chain.cpp ReadAlign_outputTranscriptCIGARp.cpp ErrorWarning.cpp Stats.cpp blocksOverlap.cpp Transcript_generateCigarP.cpp SoloReadFeature_record.cpp ChimericAlign.cpp SoloReadBarcode.cpp Parameters_openReadsFiles.cpp sjdbLoadFromStream.cpp stitchAlignToTranscript.cpp TimeFunctions.cpp stitchGapIndel.cpp GlobalVariables.cpp signalFromBAM.cpp ReadAlign_calcCIGAR.cpp Genome_genomeGenerate.cpp outputSJ.cpp Parameters_closeReadsFiles.cpp SoloFeature_collapseUMI.cpp stitchWindowAligns.cpp Parameters.cpp ReadAlign_createExtendWindowsWithAlign.cpp ReadAlign_chimericDetection.cpp SoloRead_record.cpp binarySearch2.cpp BAMfunctions.cpp sjAlignSplit.cpp ReadAlign_maxMappableLength2strands.cpp ReadAlignChunk_mapChunk.cpp serviceFuns.cpp ThreadControl.cpp Genome_insertSequences.cpp sjdbInsertJunctions.cpp genomeParametersWrite.cpp ReadAlign_chimericDetectionPEmerged.cpp BAMbinSortUnmapped.cpp insertSeqSA.cpp streamFuns.cpp ReadAlignChunk_processChunks.cpp BAMoutput.cpp ReadAlign_multMapSelect.cpp Transcript_alignScore.cpp ReadAlign_chimericDetectionOldOutput.cpp ReadAlign_chimericDetectionOld.cpp PackedArray.cpp ReadAlign_outputVariation.cpp ReadAlign_outputTranscriptSJ.cpp funCompareUintAndSuffixesMemcmp.cpp SequenceFuns.cpp ReadAlign.cpp Transcriptome_geneFullAlignOverlap.cpp loadGTF.cpp ReadAlign_assignAlignToWindow.cpp genomeSAindex.cpp stringSubstituteAll.cpp ChimericDetection.cpp SoloReadBarcode_getCBandUMI.cpp Transcriptome_geneCountsAddAlign.cpp sysRemoveDir.cpp Transcript_variationAdjust.cpp ReadAlign_waspMap.cpp ReadAlign_storeAligns.cpp InOutStreams.cpp SharedMemory.cpp genomeScanFastaFiles.cpp sjdbPrepare.cpp ReadAlign_oneRead.cpp ReadAlign_mappedFilter.cpp ReadAlign_CIGAR.cpp Transcript_variationOutput.cpp ParametersSolo.cpp Transcript.cpp SuffixArrayFuns.cpp alignSmithWaterman.cpp extendAlign.cpp ChimericAlign_chimericStitching.cpp OutSJ.cpp sjdbLoadFromFiles.cpp ReadAlign_peOverlapMergeMap.cpp ReadAlign_quantTranscriptome.cpp sjdbBuildIndex.cpp Genome.cpp Variation.cpp ReadAlign_outputTranscriptSAM.cpp ReadAlign_mapOneRead.cpp ChimericAlign_chimericJunctionOutput.cpp readLoad.cpp mapThreadsSpawn.cpp SoloReadFeature.cpp ChimericDetection_chimericDetectionMult.cpp Quantifications.cpp SoloReadFeature_inputRecords.cpp ChimericSegment.cpp ReadAlign_stitchPieces.cpp funCompareUintAndSuffixes.cpp SoloFeature.cpp bamRemoveDuplicates.cpp STAR.cpp Parameters_readSAMheader.cpp BAMbinSortByCoordinate.cpp Solo.cpp Transcriptome_quantAlign.cpp ReadAlign_outputAlignments.cpp ReadAlign_alignBAM.cpp SoloFeature_outputResults.cpp ReadAlign_stitchWindowSeeds.cpp bam_cat.c
'rm' -f ./Depend.list
g++ -pipe -std=c++11 -Wall -Wextra -fopenmp -D'COMPILATION_TIME_PLACE="Mon Jun 17 16:50:33 EDT 2019 :/home/yh362/tools/STAR/source"' -MM SoloRead.cpp SoloFeature_processRecords.cpp ReadAlignChunk.cpp Transcriptome.cpp Chain.cpp ReadAlign_outputTranscriptCIGARp.cpp ErrorWarning.cpp Stats.cpp blocksOverlap.cpp Transcript_generateCigarP.cpp SoloReadFeature_record.cpp ChimericAlign.cpp SoloReadBarcode.cpp Parameters_openReadsFiles.cpp sjdbLoadFromStream.cpp stitchAlignToTranscript.cpp TimeFunctions.cpp stitchGapIndel.cpp GlobalVariables.cpp signalFromBAM.cpp ReadAlign_calcCIGAR.cpp Genome_genomeGenerate.cpp outputSJ.cpp Parameters_closeReadsFiles.cpp SoloFeature_collapseUMI.cpp stitchWindowAligns.cpp Parameters.cpp ReadAlign_createExtendWindowsWithAlign.cpp ReadAlign_chimericDetection.cpp SoloRead_record.cpp binarySearch2.cpp BAMfunctions.cpp sjAlignSplit.cpp ReadAlign_maxMappableLength2strands.cpp ReadAlignChunk_mapChunk.cpp serviceFuns.cpp ThreadControl.cpp Genome_insertSequences.cpp sjdbInsertJunctions.cpp genomeParametersWrite.cpp ReadAlign_chimericDetectionPEmerged.cpp BAMbinSortUnmapped.cpp insertSeqSA.cpp streamFuns.cpp ReadAlignChunk_processChunks.cpp BAMoutput.cpp ReadAlign_multMapSelect.cpp Transcript_alignScore.cpp ReadAlign_chimericDetectionOldOutput.cpp ReadAlign_chimericDetectionOld.cpp PackedArray.cpp ReadAlign_outputVariation.cpp ReadAlign_outputTranscriptSJ.cpp funCompareUintAndSuffixesMemcmp.cpp SequenceFuns.cpp ReadAlign.cpp Transcriptome_geneFullAlignOverlap.cpp loadGTF.cpp ReadAlign_assignAlignToWindow.cpp genomeSAindex.cpp stringSubstituteAll.cpp ChimericDetection.cpp SoloReadBarcode_getCBandUMI.cpp Transcriptome_geneCountsAddAlign.cpp sysRemoveDir.cpp Transcript_variationAdjust.cpp ReadAlign_waspMap.cpp ReadAlign_storeAligns.cpp InOutStreams.cpp SharedMemory.cpp genomeScanFastaFiles.cpp sjdbPrepare.cpp ReadAlign_oneRead.cpp ReadAlign_mappedFilter.cpp ReadAlign_CIGAR.cpp Transcript_variationOutput.cpp ParametersSolo.cpp Transcript.cpp SuffixArrayFuns.cpp alignSmithWaterman.cpp extendAlign.cpp ChimericAlign_chimericStitching.cpp OutSJ.cpp sjdbLoadFromFiles.cpp ReadAlign_peOverlapMergeMap.cpp ReadAlign_quantTranscriptome.cpp sjdbBuildIndex.cpp Genome.cpp Variation.cpp ReadAlign_outputTranscriptSAM.cpp ReadAlign_mapOneRead.cpp ChimericAlign_chimericJunctionOutput.cpp readLoad.cpp mapThreadsSpawn.cpp SoloReadFeature.cpp ChimericDetection_chimericDetectionMult.cpp Quantifications.cpp SoloReadFeature_inputRecords.cpp ChimericSegment.cpp ReadAlign_stitchPieces.cpp funCompareUintAndSuffixes.cpp SoloFeature.cpp bamRemoveDuplicates.cpp STAR.cpp Parameters_readSAMheader.cpp BAMbinSortByCoordinate.cpp Solo.cpp Transcriptome_quantAlign.cpp ReadAlign_outputAlignments.cpp ReadAlign_alignBAM.cpp SoloFeature_outputResults.cpp ReadAlign_stitchWindowSeeds.cpp bam_cat.c parametersDefault.xxd htslib >> Depend.list
g++: warning: parametersDefault.xxd: linker input file unused because linking not done
g++: warning: htslib: linker input file unused because linking not done
g++ -c   -O3 -pipe -std=c++11 -Wall -Wextra -fopenmp -D'COMPILATION_TIME_PLACE="Mon Jun 17 16:51:02 EDT 2019 :/home/yh362/tools/STAR/source"'  ParametersSolo.cpp
g++ -c   -O3 -pipe -std=c++11 -Wall -Wextra -fopenmp -D'COMPILATION_TIME_PLACE="Mon Jun 17 16:51:02 EDT 2019 :/home/yh362/tools/STAR/source"'  SoloRead.cpp
In file included from Genome.h:7:0,
                 from Transcript.h:7,
                 from SoloReadFeature.h:7,
                 from SoloRead.h:5,
                 from SoloRead.cpp:1:
SharedMemory.h:156:9: error: ‘sem_t’ does not name a type
         sem_t * _sem;
         ^
Makefile:67: recipe for target 'SoloRead.o' failed
make: *** [SoloRead.o] Error 1

**Comment by alexdobin** [comment]
Hi Yilei,

this indicates a problem with standard glibc libraries.
You can use pre-compiled STAR executables from the bin/* directories, or try to compile on a different server, or install a separate version of gcc/glibc.

Cheers
Alex
