### ISSUE TITLE
STARsolo option [--force cell]

### ISSUE THREAD

**Issue by tingchiafelix** [alexdobin/STAR#666]
Hi,
I'm wondering if any function in STARsolo is similar to "--force-cell" opion in 10X genome pipeline (Cell Ranger)?

--force-cell: Force pipeline to use this number of cells, bypassing the cell detection algorithm. Use this if the number of cells estimated by Cell Ranger is not consistent with the barcode rank plot.

Thanks,
TC

**Comment by alexdobin** [comment]
Hi TC,

presently, STAR only generates "raw" matrices, i.e. no filtering of cells is done.
I have an awk script to do this filtering, it is discussed here: https://github.com/alexdobin/STAR/issues/644

The --force-cell option in CellRanger, does it produce exactly that number of cells in the output? I can add such an option to my script.

Cheers
Alex

**Comment by tingchiafelix** [comment]
Hi Alex,
Thanks for your help. Yes, we hope we can generate the number of cells that we set up in the output. It'll be awesome if you can add this option to your script.

I also have a related question. We ran two different samples A and B by using different chemistry reagents (SingleCell 3' v2/v3) because we tried to move forward to new reagent. Basically, the script that I used was the same to run STARsolo, but the only difference is the length of cell barcode (v2 for 26 and v3 for 28). The issue is that the matrix.mtx generated by sample B with single cell 3' v3 has way smaller file size than sample A. I have no clue why is happened. Can you please take a look at the .log files and give us some guides?

Sample A:
[Log_sampleA.out.txt](https://github.com/alexdobin/STAR/files/3315916/Log_sampleA.out.txt)

Sample B:
[Log_sampleB.out.txt](https://github.com/alexdobin/STAR/files/3315918/Log_sampleB.out.txt)

**Comment by alexdobin** [comment]
Hi TC,

will add the exact number of cells to the script shortly.
For the v3 chemistry, the UMI length is 12 (hence the barcode read length is 16+12=28) so you would need to ass --soloUMIlen 12 . After rerunning with this parameter, please send the Solo.out/Gene.stats files for both v2 and v3 runs.

Cheers
Alex

**Comment by tingchiafelix** [comment]
Hi Alex,
I did ran the sample with UMI length (12) in STARsolo agian for sample B. Attached are the Gene.stats files for both v2 and v3 run. Thanks for taking your time to do the troubleshooting.

SampleA:
[SampleA_Gene.stats.txt](https://github.com/alexdobin/STAR/files/3331280/SampleA_Gene.stats.txt)
SampleB:
[SampleB_Gene.stats.txt](https://github.com/alexdobin/STAR/files/3331281/SampleB_Gene.stats.txt)

Best,
TC

**Comment by alexdobin** [comment]
Hi TC

I have updated the soloBasicCellFilter.awk script on GitHub master, now you can specify exactCells parameter which will sort the cells by the number of UMIs, and output the top exactCells. If several cells have exactly the same number of UMIs as the cell at the exactCells place, all of the will be output, so sometimes you can have few more cells than the exactCells (bad name for the parameter I guess... almost exactCells :).

Could you please send me the Log.out file for the SampleB run with --soloUMIlen 12 ?

Cheers
Alex

**Comment by tingchiafelix** [comment]
Hi Alex,
I really appreciate all the work you have done. :) 

Here is the Log.out file. 
[Log_sampleB_rerun.out.txt](https://github.com/alexdobin/STAR/files/3336207/Log_sampleB_rerun.out.txt)

Thanks,
TC

**Comment by alexdobin** [comment]
Hi TC, 

I think you are running this sample with v2 barcode list:
--soloCBwhitelist  /data/MoCha/SingleCell/cellranger-3.0.2/cellranger-cs/3.0.2/lib/python/cellranger/barcodes/737K-august-2016.txt

The v3 barcodes should be in 3M-february-2018.txt.gz file you would need to gunzip it for STARsolo.

Please let me know if this solves the problem.

Cheers
Alex

**Comment by tingchiafelix** [comment]
Hi Alex,
Yes, I appreciate your help. 

Best,
TC
