### ISSUE TITLE
problems with STAR 2.7.1a installation on High Sierra

### ISSUE THREAD

**Issue by alikhuseynov** [alexdobin/STAR#667]
Hi Alex,
I'm having an issue to install the latest STAR release on High Sierra. I don't get anything like "Fatal error" mostly lots of warnings. However in the end the STAR is not installed properly and I cannot use it. 
## some info:
Xcode version 10.1
I used: brew install gcc
--without-multilib option is not needed if you use Xcode >10.0
My gcc is: /usr/local/Cellar/gcc/9.1.0/bin/g++-9
##
I guess it has something to do with the gcc version.

Attached is .txt of my install commands and the output with all the warnings. 
[star_install_bug.txt](https://github.com/alexdobin/STAR/files/3312292/star_install_bug.txt)

MANY Thanks for your help!
Alik

**Comment by alexdobin** [comment]
Hi Alik,

none of these errors are fatal, indeed. Was the "STAR" executable generated?
If compilation does not work, you can try the pre-compiled executables in bin/MacOSX_x86_64/

Cheers
Alex

**Comment by alikhuseynov** [comment]
Hi Alex,
No, it did not generate them.. 
I just installed STAR using conda venv without building it. 
best
Alik

**Comment by alexdobin** [comment]
Hi Alik,

great, thanks - I will now recommend users to use conda to install STAR on Macs.

Cheers
Alex
