### ISSUE TITLE
different alignment at indel region

### ISSUE THREAD

**Issue by gorliver** [alexdobin/STAR#669]
Hi Alex,
It seems STAR has a different way to align reads contain indels. Bellow is a igv screenshot. From top to bottom is the alignemnt from tophat2, STAR and bwa-MEM.
![image](https://user-images.githubusercontent.com/15271446/59980876-9f97c680-95c9-11e9-9e83-3986eb9157c1.png)
This is the tophat2 and bwa alignment, one insertion was created:
refer: TTTTTTCATTTG- AAGGTT
read: TTTTTTCATTTGGAAGGTT

This is the STAR alignment, no insertion but generated 4 mismatches:
refer: -TTTTTTCATTTGAAGGTT
read: TTTTTTCATTTGGAAGGTT

I have tried
` --outFilterMatchNmin 0 --scoreDelOp
en 0 --scoreDelBase 0 --scoreInsOpen 0 --scoreInsBase 0 `
and
`--seedSearchStartLm
ax 20 --winAnchorMultimapNmax 200 --seedMultimapNmax 100000` and they make no difference.
The alignments from tophat2 and bwa make more sense. Is there a way to fine tune the behavior of STAR at indel regions?
Many thanks,
Gorliver

**Comment by alexdobin** [comment]
Hi Gorliver,

STAR normally does not catch the indels with short overhangs - 6b in your case. In principle, you can try to increase the --seedMultimapNmax parameter to 1000000 (or more) from the default 10000. This parameter determines how many time short seeds are allowed to map to the whole genome - 6b on average will map ~1M times to the genome. However, this may slow down the mapping significantly.

Cheers
Alex

**Comment by gorliver** [comment]
Hi Alex,
Thanks for the response. 
I'm doing a cross speices RNA-seq alignment and I found many short indels and high level of SNPs. Do you have any suggestions for this kind of alignment using STAR?

Gorliver

**Comment by alexdobin** [comment]
Hi Gorliver,

STAR can tolerate (reasonably) high level of SNVs, with some tweaking of parameters. The indels, however, will be problematic. In general, if you allow novel splice junctions, they will compete with indels for alignments with short overhangs. E.g., a 6b overhang will occur randomly in the genome every 4^6~4,000 bases - so it's hard to tell if this is an indel, or a novel splice. I would recommend mapping to the transcriptome (i.e. a collection of annotated transcripts) and using more indel-friendly aligner such as bwa-mem.

Cheers
Alex

**Comment by gorliver** [comment]
Hi Alex,
Many thanks for your advice!

**Comment by wangjiawen2013** [comment]
@alexdobin 
I don't quite know about the `--scoreDelOpen` and `--scoreDelBase`. What's the difference between them ? what are they used for (such as contributing to MAPQ or something else) ? And does STAR use them to filter the alignments ?
![image](https://github.com/user-attachments/assets/f831718c-fb45-41a6-ba17-09a43a292078)
