### ISSUE TITLE
--quantMode GeneCounts give unstranded results for a stranded trueseq library

### ISSUE THREAD

**Issue by agroppi** [alexdobin/STAR#672]
I'm using STAR 2.7.1a
I have indexed the human primary assembly from Gencode and the corresponding gtf.

My command : 
```
STAR \
--runThreadN 20 \
--genomeDir /mnt/cbib/bank/Gencode_release_30/genome \
--sjdbGTFfile /mnt/cbib/bank/Gencode_release_30/gencode.v30.primary_assembly.annotation.gtf \
--readFilesCommand gunzip -c \
--readFilesIn $FILE1,$FILE2 \
--outFilterType BySJout \
--outFilterMultimapNmax 20 \
--alignSJoverhangMin 8 \
--alignSJDBoverhangMin 1 \
--outFilterMismatchNmax 999 \
--outFilterMismatchNoverReadLmax 0.04 \
--quantMode GeneCounts \
--alignIntronMin 20 \
--alignIntronMax 1000000 \
--alignMatesGapMax 1000000
```
The RNA seq (paired end) was performed by using the Kit Illumina TruSeq Stranded mRNA.

But when I look in the file `ReadsPerGene.out.tab` I'm unable to find the corresponding column.
More in favour of an unstranded experiment.

What sould I take in account in the subsequent DESeq2 analysis ?

Thanks

PS : here are one ReadsPerGene.out.tab 
[ReadsPerGene.out.tab.zip](https://github.com/alexdobin/STAR/files/3330363/ReadsPerGene.out.tab.zip)
and lhe logs 
[Log.zip](https://github.com/alexdobin/STAR/files/3330365/Log.zip)

**Comment by alexdobin** [comment]
Hi Alexis,

in --readFilesIn Read1.fq and Read2.fq  have to be separated by space, not by comma.

You are listing the Read1 and Read2 files in a comma-separated list:
`--readFilesIn /mnt/cbib/RNAStar/fastp_QC_filtered/P1-INDOX-CHAUF-8H_R1.fastq.gz,/mnt/cbib/RNAStar/fastp_QC_filtered/P1-INDOX-CHAUF-8H_R2.fastq.gz`
which STAR interprets as two files of single-end reads.

Cheers
Alex

**Comment by agroppi** [comment]
Thank you @alexdobin :)
