### ISSUE TITLE
STAR not mapping reads from multiple unmapped BAMs

### ISSUE THREAD

**Issue by overcookedfrog** [alexdobin/STAR#674]
When running STAR to align reads from multiple unmapped BAMs, it doesn't complain but the output only contains reads from the first uBAM. Is this bug or an expected feature? If I merge the uBAMs prior to aligning (with for example samtools), STAR produces the output I expect: alignments from all reads with read groups properly assigned.

Responses to other issues suggest that FIFOs or process substitution should work; however, the following fails
```
STAR \
  --runThreadN 8 \
  --readFilesIn <(samtools merge -f /dev/stdout RG1.unmapped.bam RG2.unmapped.bam) \                                                     
  --readFilesType SAM PE \
  --readFilesCommand "samtools view -h" \
  --genomeDir genome \
  --outSAMtype BAM SortedByCoordinate \
  --outSAMunmapped Within
```
with 
```
[W::sam_read1] Parse error at line 1       
[main_samview] truncated file.          
[E::bgzf_uncompress] Inflate operation failed: invalid distance too far back
[E::bgzf_read] Read block operation failed with error 1 after 0 of 4 bytes
[main_samview] truncated file.           
Jun 28 12:27:45 ..... started STAR run     
Jun 28 12:27:45 ..... loading genome    
Jun 28 12:27:46 ..... started mapping            
Jun 28 12:27:47 ..... finished mapping
Jun 28 12:27:47 ..... started sorting BAM
Jun 28 12:27:47 ..... finished successfully
```
Despite the "finished successfully" the BAM file is missing data.

Currently, the only way I can include all data is to merge prior to running STAR and create a real file. This is obviously not very efficient and takes up more disk space. Is there a way to get STAR to include all data without creating the merged file?

Thanks.

**Comment by alexdobin** [comment]
Hi @overcookedfrog 

no need to merge BAM files, you can simply do 
--readFilesIn RG1.unmapped.bam,RG2.unmapped.bam                                            
--readFilesType SAM PE
--readFilesCommand samtools view -h
Note that the files should be separated by commas but no spaces (the same rule as used for fastqs from different samples).

Cheers
Alex
