### ISSUE TITLE
about the genomeGenerate error

### ISSUE THREAD

**Issue by sjtuyf** [alexdobin/STAR#676]
Hi，I am using star software during  the analysis of RNA_seq snp calling. I have tried many times, but always failed. So I want your help if you are free.
       The command is '/lustre/home/acct-clslj/clslj-3/ChangYafei/softwares/STAR_2.7.1a/STAR-2.7.1a/source/STAR --runMode genomeGenerate --genomeDir /lustre/home/acct-clslj/clslj-3/ChangYafei/cancer_rna_seq_hg38/bj_01/gatk_25T/first_pass/index_1 --genomeFastaFiles ../genome/hg38.fasta --sjdbGTFfile ../genome/hg38_ucsc.gtf --sjdbOverhang 149'
       The error information is 
Genome_genomeGenerate.cpp:217:genomeGenerate: exiting because of *OUTPUT FILE* error: could not create output file /lustre/home/acct-clslj/clslj-3/ChangYafei/cancer_rna_seq_hg38/bj_01/gatk_25T/first_pass/index_1/chrName.txt
SOLUTION: check that the path exists and you have write permission for this file. Also check ulimit -n and increase it to allow more open files.

Jul 02 11:18:21 ...... FATAL ERROR, exiting
       You can see more details from the attached file.
[2312229_err.txt](https://github.com/alexdobin/STAR/files/3348173/2312229_err.txt)
[2312229.out.txt](https://github.com/alexdobin/STAR/files/3348174/2312229.out.txt)
[Log.out.txt](https://github.com/alexdobin/STAR/files/3348175/Log.out.txt)

       The length of each fastq is 150，the size of each is 12g.
       ulimit -n is 1024 in my server, and the file have read or write permission. So i do not know what the problem is.
       I am really want to get some help from you. Thanks a lot.

Best
yafei

**Comment by alexdobin** [comment]
Hi Yafei,

what is the output of
ls -lR /lustre/home/acct-clslj/clslj-3/ChangYafei/cancer_rna_seq_hg38/bj_01/gatk_25T/first_pass/

Cheers
Alex

**Comment by sjtuyf** [comment]
Hello, I have solved this problem, by mkdir index_1 file by myself. I think the reason is I do not have the write permission by the script. It is so weird.  In short, it is ok now.

Thank again.
Yafei

**Comment by alexdobin** [comment]
Great, thanks for letting us know!
