### ISSUE TITLE
Index Regeneration `2.7.0f` -> `2.7.1a`?

### ISSUE THREAD

**Issue by sklages** [alexdobin/STAR#677]
`2.7.1a` release notes state that I need to regenerate genome indexes. 

I definitely have to do this when upgrading from `2.6.x` to current version. 

Do I have to regenerate genome indexes when doing the minor upgrade from  `2.7.0f` to `2.7.1a`.? That's not very clear (to me) ..

**Comment by alexdobin** [comment]
Hi @sklages,

2.7.1a does require genome re-generation, if you use the older index with it, it should generate an error.
As I am adding new *solo features, I need to update the genome generation more often than usual.
On the other hand, of you are not using *solo options, you can stay with 2.6.1d for now, as other parts of the code had not been changed.

Cheers
Alex
