### ISSUE TITLE
How to generate Chimeric.out.sam/bam from Aligned.sortedByCoord.out.bam(--WithinBam)

### ISSUE THREAD

**Issue by Li-Yupeng** [alexdobin/STAR#678]
Hello!
    I use ' --chimOutType WithinBAM' as it recommends (2.7.1a). Emmm... but how can generate Chimeric.out.sam/bam from Aligned.sortedByCoord.out.bam? @_@
    Thanks! ^_^

**Comment by alexdobin** [comment]
Hi Li-Yupeng,

if you add "ch" to --outSAMattributes list, you can extract the chimeric alignments from Aligned.out.bam by grepping for lines that contain "ch:A:1" SAM tag.

Cheers
Alex

**Comment by Li-Yupeng** [comment]
> 
> 
> Hi Li-Yupeng,
> 
> if you add "ch" to --outSAMattributes list, you can extract the chimeric alignments from Aligned.out.bam by grepping for lines that contain "ch:A:1" SAM tag.
> 
> Cheers
> Alex

That's really helpful! 
    I tried to find solution from the manual (2.7), but it may don't clarify what "ch" means for a novice such as me. I should learn more. 

Thanks a lot!
Li-Yupeng
