### ISSUE TITLE
Unexpected end of file 

### ISSUE THREAD

**Issue by anthonyagudelox3** [alexdobin/STAR#679]
This is the line that I ran to get the error. 

`STAR --runThreadN 8 --genomeDir /gpfs/scratch/aagudel1/STARgenome --readFilesIn /gpfs/scratch/aagudel1/RNASeq_Jun_2019/RNASeq_June_2019_UAUV/T60/FCH2MMYBBXY_L1_CHKPEI00001610_Index-CHKPEI85219030284_1.fq.gz /gpfs/scratch/aagudel1/RNASeq_Jun_2019/RNASeq_June_2019_UAUV/T60/FCH2MMYBBXY_L1_CHKPEI00001610_Index-CHKPEI85219030284_2.fq.gz --outFilterIntronMotifs RemoveNoncanonical --outSAMstrandField intronMotif --readFilesCommand zcat --outFileNamePrefix /gpfs/scratch/aagudel1/RNASeq_Jun_2019/STAR_FILES/FCH2MMYBBXY_L1_CHKPEI00001610_Index-CHKPEI85219030284_ --outFilterMultimapNmax 1 --outReadsUnmapped unampped_FCH2MMYBBXY_L1_CHKPEI00001610_Index-CHKPEI85219030284 --outSAMtype BAM SortedByCoordinate 
`

```
module: loading 'star/2.6.1b'
Jul 03 11:10:24 ..... started STAR run
Jul 03 11:10:24 ..... loading genome
Jul 03 11:11:10 ..... started mapping

gzip: /gpfs/scratch/aagudel1/RNASeq_Jun_2019/RNASeq_June_2019_UAUV/T60/FCH2MMYBBXY_L1_CHKPEI00001610_Index-CHKPEI85219030284_2.fq.gz: unexpected end of file

EXITING because of FATAL ERROR in reads input: short read sequence line: 0
Read Name=@K00133:520:H2MMYBBXY:1:2105:30858:9350
Read Sequence====
DEF_readNameLengthMax=50000
DEF_readSeqLengthMax=650

Jul 03 11:17:05 ...... FATAL ERROR, exiting
```

I am running STAR paired end. 

I seem to be having the issue with this when I try to run STAR on this sample. I have seen others post a similar issue, (EXITING because of FATAL ERROR) and they have mentioned that it may be due to an issue in the adapter trimming step. However, I was curious as to what it means when 1 of my paired ends has an "unexpected end of file". As I do not believe it is an adapter trimming issue.

**Comment by alexdobin** [comment]
Hi @anthonyagudelox3 

it looks like a problem with the fastq file, as you get the gzip error:
gzip: /gpfs/scratch/aagudel1/RNASeq_Jun_2019/RNASeq_June_2019_UAUV/T60/FCH2MMYBBXY_L1_CHKPEI00001610_Index-CHKPEI85219030284_2.fq.gz: unexpected end of file
May be the file got corrupted?

Cheers
Alex
