### ISSUE TITLE
Documentation on the "core.X" file?

### ISSUE THREAD

**Issue by boylermaker** [alexdobin/STAR#681]
Hi, I've just started using STAR, and it's been quite productive so far--very well documented. I noticed that after indexing a genome with it, I got a mysterious file named 'core.12311' in my working directory. It's quite large (17 GB) and seems to consist mostly of nonsense, possibly it's a binary file? The first few lines are:

ELF>@@8F??*@@PP@s???s??p	p	?
 ?2?
B?2?

What is this file? I can't find anything in the manual about it, or in the logfile for the STAR run that produced it. Can it be safely deleted? Is there a way to get it to output to a different directory along the lines of --outFileNamePrefix or similar?

**Comment by boylermaker** [comment]
I thought the indexing had successfully finished up, but in fact it had been aborted at one point, so presumably this is just some temporary file. My apologies for spamming you!

**Comment by alexdobin** [comment]
Hi @boylermaker 
Correct - that was "cored dump" from a crashed run, the OS does it on its own.
Cheers
Alex
