### ISSUE TITLE
alignSJstitchMismatchNmax Explanation

### ISSUE THREAD

**Issue by DarioS** [alexdobin/STAR#684]
From the one-sentence explanation, I don't understand what it does. Can there be a worked example? I am deliberating between STAR-Fusion's recommendation of 5 -1 5 5 or keep the default of 0 -1 0 0.

**Comment by brianjohnhaas** [comment]
Alex Dobin recommended this a while back.

-via googleFi

**Comment by alexdobin** [comment]
Hi Dario, Brian,

the STAR-Fusion parameters seemed to work better for several fusion examples that we considered. However, the effect were relatively small, and the default STAR values will work fine in most cases as well.

Cheers
Alex
