### ISSUE TITLE
Is it possible to specify --chimOutType as both Junctions and WithinBAM using STAR Fusion's recommended parameters for STAR?

### ISSUE THREAD

**Issue by jtquach1** [alexdobin/STAR#685]
Hi, 

I am using the recommended parameters that STAR Fusion uses for running STAR align, along with some minor edits.

Edits:
- --outSAMtype BAM Unsorted SortedByCoordinate \
- --readFilesCommand zcat \
- --chimOutType Junctions WithinBAM \
- --outFileNamePrefix $output_dir

Parameters:
```
STAR \
	--genomeDir $ref_genome_path \
	--readFilesIn ${sample_path}BT474f_1.fq.gz ${sample_path}BT474f_2.fq.gz \
	--twopassMode Basic \
	--outReadsUnmapped None \
	--chimSegmentMin 12 \
	--chimJunctionOverhangMin 12 \
	--alignSJDBoverhangMin 10 \
	--alignMatesGapMax 100000 \
	--alignIntronMax 100000 \
	--chimSegmentReadGapMax 3 \
	--alignSJstitchMismatchNmax 5 -1 5 5 \
	--runThreadN 16 \
	--outSAMstrandField intronMotif \
	--outSAMunmapped Within \
	--outSAMtype BAM Unsorted SortedByCoordinate \
	--outSAMattrRGline ID:GRPundef \
	--chimMultimapScoreRange 10 \
	--chimMultimapNmax 10 \
	--chimNonchimScoreDropMin 10 \
	--peOverlapNbasesMin 12 \
	--peOverlapMMp 0.1 \
	--chimOutJunctionFormat 1 \
	--readFilesCommand zcat \
	--chimOutType Junctions WithinBAM \
	--outFileNamePrefix $output_dir
```
I am getting this message: 

`EXITING because of fatal PARAMETERS error: --chimMultimapNmax > 0 (new chimeric detection) presently only works with --chimOutType Junctions
SOLUTION: re-run with --chimOutType Junctions`

That being said, would it be possible to specify Junctions and WithinBAM simultaneously with STAR align (or at least in the future)? I do know that the STAR align manual doesn't specify 

`--chimOutType Junctions WithinBAM`

as neither being a valid nor invalid option- I assumed I could use both values since doing

`--outSAMtype BAM Unsorted SortedByCoordinate \`

is possible. 

The reason why I want to specify both WithinBAM and Junctions is because I would like to

- examine the discordant reads from the Aligned.sortedByCoord.out.bam file and also 
- use the Chimeric.out.junction file to kickstart STAR Fusion. 

I'm currently running STAR Fusion in non-kickstart mode, but it seems to be taking an abnormal amount of time for the tiny BT474f_1.fq.gz and BT474f_2.fq.gz from the [STAR Fusion testing data](https://github.com/STAR-Fusion/STAR-Fusion/tree/master/testing/data).

(However, if there is a specific reason why WithinBAM is disallowed based on the above error message, I am also happy to learn about that reason!)

**Comment by alexdobin** [comment]
Hi Joyce,

you are using --chimMultimapNmax 10, which is a "new" chimeric detection algorithm, allowing detection of multimapping chimeras. Presently, it can only output Chimeric.out.junction file and cannot output chimeric alignments within the BAM file. You can use --chimOutType Junctions WithinBAM with --chimMultimapNmax 0 ("old" unique chimeric detection) and without --peOverlap* options.

Cheers
Alex

**Comment by jtquach1** [comment]
> Hi Joyce,
> you are using --chimMultimapNmax 10, which is a "new" chimeric detection algorithm, allowing detection of multimapping chimeras. Presently, it can only output Chimeric.out.junction file and cannot output chimeric alignments within the BAM file. You can use --chimOutType Junctions WithinBAM with --chimMultimapNmax 0 ("old" unique chimeric detection) and without --peOverlap* options.
> Cheers
> Alex

Thanks, Alex!

**Comment by brownmp** [comment]
Hello! 
I was wondering if the option of keeping chimeric reads in the BAM along with creating the Chimeric.out.junction file is still not available. 
Thank you for your time!

~MBrown

**Comment by alexdobin** [comment]
Hi @brownmp 

you should be able to do it starting from 2.7.6a release.

Cheers
Alex

**Comment by andrea-de-micheli** [comment]
Hi Alex,

Can you confirm this would work in the latest STAR version: **--chimOutType WithinBAM Junctions SeparateSAMold** ?
I would like to keep the chimeric reads in the Aligned.out.bam and generate the Chimeric.out.sam file. I also need the Chimeric.out.junction file for my pipeline.

Many thanks for your support!

Best,
Andrea
