### ISSUE TITLE
STAR aborts at the very end when running with shared genome and --quantMode TranscriptomeSAM

### ISSUE THREAD

**Issue by kajetanb** [alexdobin/STAR#69]
STAR version STAR_2.4.1d 

After setting

    sysctl -w kernel.shmall=8000000
    sysctl -w kernel.shmmax=32000000000

running

    $ STAR --genomeDir genome_dir --genomeLoad LoadAndExit

is successfully, then

    $ STAR --genomeDir genome_dir --readFilesIn Test.fastq --genomeLoad LoadAndKeep --quantMode TranscriptomeSAM
    Aug 26 14:39:47 ..... Started STAR run
    Aug 26 14:39:47 ..... Loading genome
    Aug 26 14:39:47 ..... Started mapping
    Aug 26 14:39:54 ..... Finished successfully
    *** Error in `STAR': double free or corruption (!prev): 0x00000000011a3270 ***
    Aborted (core dumped)

but 

    $ STAR --genomeDir genome_dir --readFilesIn Test.fastq --genomeLoad LoadAndKeep

finishes without error message and also

    $ STAR --genomeDir genome_dir --genomeLoad Remove
    $ STAR --genomeDir genome_dir --readFilesIn Test.fastq --genomeLoad LoadAndKeep --quantMode TranscriptomeSAM

does not throw any error, only when repeating the command from above (`STAR --genomeDir genome_dir --readFilesIn Test.fastq --genomeLoad LoadAndKeep --quantMode TranscriptomeSAM`) 
I get the same error message.

Thanks,
Kajetan

**Comment by alexdobin** [comment]
Hi Kajetan,

could you please try it with the latest version, 2.4.2a?

Cheers
Alex

**Comment by kajetanb** [comment]
Hi Alex,
thanks a lot! It is working with the version 2.4.2a.
Best,
Kajetan
