### ISSUE TITLE
STAR cannot read read IDs modified with UMI

### ISSUE THREAD

**Issue by laurapspector** [alexdobin/STAR#690]
Here is an example of a read ID I started with for paired-end sequencing:
@M03525:380:000000000-CDJ38:1:1101:13087:1473 1:N:0:TCGCCTTA

I first used Je demultiplex on my samples, which removed the space-separated part containing the read 1/2 info plus index (i.e., '1:N:0:TCGCCTTA'). I then used umi-tools to extract UMIs from my reads, which were joined to the remainder of the read ID by an underscore, so they look like this:
@M03525:380:000000000-CDJ38:1:1101:13087:1473_GGTGTGCGTGGA 

When I run STAR using the FASTQ files with read IDs like this it results in the error:
EXITING because of FATAL ERROR in reads input: quality string length is not equal to sequence length
@M03525:380:000000000-CDJ38:1:1101:13087:1473_GGTGTGCGTGGA
+
@M03525:380:000000000-CDJ38:1:1101:15214:1492_CGTGACATGGGG 
SOLUTION: fix your fastq file

I believe it's happening because I lack the space-separated part of the read ID. If I manually replace the underscore shown above with a space, STAR runs without this error. However, I need to keep the UMI linked to the header for downstream deduplication. Is there a work-around for this? Based on the single cell tutorial for umi-tools, it looks like if I could somehow avoid removing the space-separated part during demultiplexing, the UMI would get added to the first part of the read ID so even if the space-separated part were removed during mapping I would still have the UMI.

**Comment by alexdobin** [comment]
Hi Laura,

I will check if the absence of the second field in read name actually causes the problem.
The workaround, for now, could be to create the read name with two fields, i.e.
@M03525:380:000000000-CDJ38:1:1101:13087:1473_TCGCCTTA 1:N:0:TCGCCTTA

Cheers
Alex

**Comment by alexdobin** [comment]
Hi Laura,

I have checked 2.6.1d and 2.7.1a, and both work with read name that contain no 2nd field.
So the problem is somewhere else in the formatting.

Cheers
Alex
