### ISSUE TITLE
how can I get 2.5.x version

### ISSUE THREAD

**Issue by Winnie912** [alexdobin/STAR#692]
I use 2.7.1 to map RNAseq, but it keeps return : killed 9.
I want to use  2.5.x version to map. how can I get 2.5.x version?

**Comment by sklages** [comment]
Well, just have a look at the [releases page](https://github.com/alexdobin/STAR/releases)?
Why do you think `2.5.x` will work where `2.7.x` fails?

**Comment by alexdobin** [comment]
Hi @Winnie912 

indeed, it's unlikely that reverting to older version will solve this problem. All the version are available here:
https://github.com/alexdobin/STAR/releases

This problem is often caused by insufficient RAM - what genome are you trying to map to, and how much AM do you have.

Cheers
Alex

**Comment by Winnie912** [comment]
> 嗨@ Winnie912
> 
> 实际上，恢复旧版本不太可能解决这个问题。所有版本都可以在这里找到：[https](https://github.com/alexdobin/STAR/releases)：
> [//github.com/alexdobin/STAR/releases](https://github.com/alexdobin/STAR/releases)
> 
> 这个问题通常是由RAM不足引起的 - 您想要映射到哪个基因组，以及您有多少AM。
> 
> 干杯
> 亚历克斯

thx~ I am trying to map mus mouse 10 genome. and I have 16 GB 2400 MHz DDR4 macOS...

**Comment by Winnie912** [comment]
> Hi @Winnie912
> 
> indeed, it's unlikely that reverting to older version will solve this problem. All the version are available here:
> https://github.com/alexdobin/STAR/releases
> 
> This problem is often caused by insufficient RAM - what genome are you trying to map to, and how much AM do you have.
> 
> Cheers
> Alex

thx~ I am trying to map mus mouse 10 genome. And for RAM,  I have 16 GB 2400 MHz DDR4 macOS...

**Comment by alexdobin** [comment]
Hi @Winnie912 

for 16GB of RAM, you would need to use --genomeSAsparseD 2 at the genome generation step. If it still does not fit, increase it to 3.

Cheers
Alex
