### ISSUE TITLE
Neither output nor error when running STAR

### ISSUE THREAD

**Issue by LEIyuechen** [alexdobin/STAR#693]
HI ALex,

I got a problem that when I run STAR, there is neither output nor error print. However, not all samples would face the problem. The star.log is "..... loading genome" and stops. When I try command again, it works. I always use sge system to qsub the jobs and some jobs of samples that with this problem with show CPU=0 for a long time, no error/exit, no output, which is confused me. 

my code is,
STAR --outSAMtype BAM Unsorted --chimOutJunctionFormat 1 --readFilesIn ${fq1} ${fq2} --readFilesCommand zcat --outFileNamePrefix ${oud}/${sample}_${libname}_ --twopassMode Basic --outReadsUnmapped None --chimSegmentMin 12 --chimJunctionOverhangMin 12 --alignSJDBoverhangMin 10 --alignMatesGapMax 100000 --alignIntronMax 100000 --chimSegmentReadGapMax 3 --alignSJstitchMismatchNmax 5 -1 5 5 --runThreadN 16 --outSAMstrandField intronMotif --sjdbGTFfile ${gtf} --genomeDir ${refdir}

How could I do to solve this problem?
Hope your reply.

Best,
LEI

**Comment by alexdobin** [comment]
Hi @LEIyuechen 

if the problem disappears after you re-run the code for the same sample with the same parameters, it's likely to be caused by some local problem with file system or RAM. How much RAM are you requesting from sge?
If you send me a Log.out file of a failed run I can check if there are any hints there.
I would recommend that you try to copy the STAR genome directory into local drive on each node before executing STAR mapping command.

Cheers
Alex

**Comment by LEIyuechen** [comment]
Hi Alex,

Thank you for your reply.
I am requesting from sge for cpu/p=16 and memory=35G for each sample. I think it is supposed to be enough.

My Log.out file is shown as below: At first, it is information for parameters, which is set as previous command. However, at the bottom of file, there is showed that,  

"""  Input read files for mate 1, from input string /mnt/GenePlus001/rd/outline/20190510/align_test/output/QC/180008559FR_180008559FR_HUM_C_GC1A_597_A_RD1_A/180008559FR_180008559FR_HUM_C_GC1A_597_A_RD1_A_rmrfq.1.gz
-rw-rw-r-- 1 rd rd 5358683741 Jul 23 14:56 /mnt/GenePlus001/rd/outline/20190510/align_test/output/QC/180008559FR_180008559FR_HUM_C_GC1A_597_A_RD1_A/180008559FR_180008559FR_HUM_C_GC1A_597_A_RD1_A_rmrfq.1.gz

   readsCommandsFile:
exec > "/mnt/GenePlus001/rd/outline/20190510/align_test/output/Align/180008559FR_180008559FR_HUM_C_GC1A_597_A_RD1_A/180008559FR_180008559FR_HUM_C_GC1A_597_A_RD1_A__STARtmp/tmp.fifo.read1"
echo FILE 0
zcat      "/mnt/GenePlus001/rd/outline/20190510/align_test/output/QC/180008559FR_180008559FR_HUM_C_GC1A_597_A_RD1_A/180008559FR_180008559FR_HUM_C_GC1A_597_A_RD1_A_rmrfq.1.gz"""

So is it any problems you can find out for it? 
Hope your reply.


Best, 
LEI

**Comment by alexdobin** [comment]
Hi LEI,

I would need to look at the whole Log.out file to check for problems. You can email it to me 
dobin @ cshl.edu 
if you do not want to post it.

Cheers
Alex

**Comment by LEIyuechen** [comment]
Hi Alex, 

The whole Log.out file is as below: (I also send email to dobin@cshl.edu)

STAR version=STAR_2.6.1d
STAR compilation time,server,dir=Fri Nov 16 17:02:31 EST 2018 florence.cshl.edu:/sonas-hs/gingeras/nlsas_norepl/user/dobin/STAR/STAR.master/source
##### DEFAULT parameters:
versionSTAR                       20201
versionGenome                     20101   20200   
parametersFiles                   -   
sysShell                          -
runMode                           alignReads
runThreadN                        1
runDirPerm                        User_RWX
runRNGseed                        777
genomeDir                         ./GenomeDir/
genomeLoad                        NoSharedMemory
genomeFastaFiles                  -   
genomeChainFiles                  -   
genomeSAindexNbases               14
genomeChrBinNbits                 18
genomeSAsparseD                   1
genomeSuffixLengthMax             18446744073709551615
genomeFileSizes                   0   
genomeConsensusFile               -
readFilesType                     Fastx   
readFilesIn                       Read1   Read2   
readFilesPrefix                   -
readFilesCommand                  -   
readMatesLengthsIn                NotEqual
readMapNumber                     18446744073709551615
readNameSeparator                 /   
inputBAMfile                      -
bamRemoveDuplicatesType           -
bamRemoveDuplicatesMate2basesN    0
limitGenomeGenerateRAM            31000000000
limitIObufferSize                 150000000
limitOutSAMoneReadBytes           100000
limitOutSJcollapsed               1000000
limitOutSJoneRead                 1000
limitBAMsortRAM                   0
limitSjdbInsertNsj                1000000
outTmpDir                         -
outTmpKeep                        None
outStd                            Log
outReadsUnmapped                  None
outQSconversionAdd                0
outMultimapperOrder               Old_2.4
outSAMtype                        SAM   
outSAMmode                        Full
outSAMstrandField                 None
outSAMattributes                  Standard   
outSAMunmapped                    None   
outSAMorder                       Paired
outSAMprimaryFlag                 OneBestScore
outSAMreadID                      Standard
outSAMmapqUnique                  255
outSAMflagOR                      0
outSAMflagAND                     65535
outSAMattrRGline                  -   
outSAMheaderHD                    -   
outSAMheaderPG                    -   
outSAMheaderCommentFile           -
outBAMcompression                 1
outBAMsortingThreadN              0
outBAMsortingBinsN                50
outSAMfilter                      None   
outSAMmultNmax                    18446744073709551615
outSAMattrIHstart                 1
outSAMtlen                        1
outSJfilterReads                  All
outSJfilterCountUniqueMin         3   1   1   1   
outSJfilterCountTotalMin          3   1   1   1   
outSJfilterOverhangMin            30   12   12   12   
outSJfilterDistToOtherSJmin       10   0   5   10   
outSJfilterIntronMaxVsReadN       50000   100000   200000   
outWigType                        None   
outWigStrand                      Stranded   
outWigReferencesPrefix            -
outWigNorm                        RPM   
outFilterType                     Normal
outFilterMultimapNmax             10
outFilterMultimapScoreRange       1
outFilterScoreMin                 0
outFilterScoreMinOverLread        0.66
outFilterMatchNmin                0
outFilterMatchNminOverLread       0.66
outFilterMismatchNmax             10
outFilterMismatchNoverLmax        0.3
outFilterMismatchNoverReadLmax    1
outFilterIntronMotifs             None
outFilterIntronStrands            RemoveInconsistentStrands
clip5pNbases                      0   
clip3pNbases                      0   
clip3pAfterAdapterNbases          0   
clip3pAdapterSeq                  -   
clip3pAdapterMMp                  0.1   
winBinNbits                       16
winAnchorDistNbins                9
winFlankNbins                     4
winAnchorMultimapNmax             50
winReadCoverageRelativeMin        0.5
winReadCoverageBasesMin           0
scoreGap                          0
scoreGapNoncan                    -8
scoreGapGCAG                      -4
scoreGapATAC                      -8
scoreStitchSJshift                1
scoreGenomicLengthLog2scale       -0.25
scoreDelBase                      -2
scoreDelOpen                      -2
scoreInsOpen                      -2
scoreInsBase                      -2
seedSearchLmax                    0
seedSearchStartLmax               50
seedSearchStartLmaxOverLread      1
seedPerReadNmax                   1000
seedPerWindowNmax                 50
seedNoneLociPerWindow             10
seedMultimapNmax                  10000
seedSplitMin                      12
alignIntronMin                    21
alignIntronMax                    0
alignMatesGapMax                  0
alignTranscriptsPerReadNmax       10000
alignSJoverhangMin                5
alignSJDBoverhangMin              3
alignSJstitchMismatchNmax         0   -1   0   0   
alignSplicedMateMapLmin           0
alignSplicedMateMapLminOverLmate    0.66
alignWindowsPerReadNmax           10000
alignTranscriptsPerWindowNmax     100
alignEndsType                     Local
alignSoftClipAtReferenceEnds      Yes
alignEndsProtrude                 0   ConcordantPair   
alignInsertionFlush               None
peOverlapNbasesMin                0
peOverlapMMp                      0.01
chimSegmentMin                    0
chimScoreMin                      0
chimScoreDropMax                  20
chimScoreSeparation               10
chimScoreJunctionNonGTAG          -1
chimMainSegmentMultNmax           10
chimJunctionOverhangMin           20
chimOutType                       Junctions   
chimFilter                        banGenomicN   
chimSegmentReadGapMax             0
chimMultimapNmax                  0
chimMultimapScoreRange            1
chimNonchimScoreDropMin           20
chimOutJunctionFormat             0   
sjdbFileChrStartEnd               -   
sjdbGTFfile                       -
sjdbGTFchrPrefix                  -
sjdbGTFfeatureExon                exon
sjdbGTFtagExonParentTranscript    transcript_id
sjdbGTFtagExonParentGene          gene_id
sjdbOverhang                      100
sjdbScore                         2
sjdbInsertSave                    Basic
varVCFfile                        -
waspOutputMode                    None
quantMode                         -   
quantTranscriptomeBAMcompression    1
quantTranscriptomeBan             IndelSoftclipSingleend
twopass1readsN                    18446744073709551615
twopassMode                       None
##### Command Line:
/mnt/X500/farmers/wuzp/RNA/RNAseq/bin/rnaseq-align/bin/STAR --outSAMtype BAM Unsorted --chimOutJunctionFormat 1 --readFilesIn /mnt/GenePlus001/rd/outline/20190613/wangjun/output/QC/180025975FR_180025975FR_HUM_C_GC0A_553_Z_0_A/180025975FR_180025975FR_HUM_C_GC0A_553_Z_0_A_rmrfq.1.gz /mnt/GenePlus001/rd/outline/20190613/wangjun/output/QC/180025975FR_180025975FR_HUM_C_GC0A_553_Z_0_A/180025975FR_180025975FR_HUM_C_GC0A_553_Z_0_A_rmrfq.2.gz --readFilesCommand zcat --outFileNamePrefix /mnt/GenePlus001/rd/outline/20190613/wangjun/output/Align/180025975FR_180025975FR_HUM_C_GC0A_553_Z_0_A/180025975FR_180025975FR_HUM_C_GC0A_553_Z_0_A_ --twopassMode Basic --outReadsUnmapped None --chimSegmentMin 12 --chimJunctionOverhangMin 12 --alignSJDBoverhangMin 10 --alignMatesGapMax 100000 --alignIntronMax 100000 --chimSegmentReadGapMax 3 --alignSJstitchMismatchNmax 5 -1 5 5 --runThreadN 16 --outSAMstrandField intronMotif --sjdbGTFfile /mnt/X500/farmers/leiyc/RNA_pipeline/pipeline/RNAseq/db/Homo_sapiens.GRCh37.87.gtf --genomeDir /mnt/X500/farmers/leiyc/RNA_pipeline/pipeline/RNAseq/db/ref
##### Initial USER parameters from Command Line:
outFileNamePrefix                 /mnt/GenePlus001/rd/outline/20190613/wangjun/output/Align/180025975FR_180025975FR_HUM_C_GC0A_553_Z_0_A/180025975FR_180025975FR_HUM_C_GC0A_553_Z_0_A_
###### All USER parameters from Command Line:
outSAMtype                    BAM   Unsorted        ~RE-DEFINED
chimOutJunctionFormat         1        ~RE-DEFINED
readFilesIn                   /mnt/GenePlus001/rd/outline/20190613/wangjun/output/QC/180025975FR_180025975FR_HUM_C_GC0A_553_Z_0_A/180025975FR_180025975FR_HUM_C_GC0A_553_Z_0_A_rmrfq.1.gz   /mnt/GenePlus001/rd/outline/20190613/wangjun/output/QC/180025975FR_180025975FR_HUM_C_GC0A_553_Z_0_A/180025975FR_180025975FR_HUM_C_GC0A_553_Z_0_A_rmrfq.2.gz        ~RE-DEFINED
readFilesCommand              zcat        ~RE-DEFINED
outFileNamePrefix             /mnt/GenePlus001/rd/outline/20190613/wangjun/output/Align/180025975FR_180025975FR_HUM_C_GC0A_553_Z_0_A/180025975FR_180025975FR_HUM_C_GC0A_553_Z_0_A_     ~RE-DEFINED
twopassMode                   Basic     ~RE-DEFINED
outReadsUnmapped              None     ~RE-DEFINED
chimSegmentMin                12     ~RE-DEFINED
chimJunctionOverhangMin       12     ~RE-DEFINED
alignSJDBoverhangMin          10     ~RE-DEFINED
alignMatesGapMax              100000     ~RE-DEFINED
alignIntronMax                100000     ~RE-DEFINED
chimSegmentReadGapMax         3     ~RE-DEFINED
alignSJstitchMismatchNmax     5   -1   5   5        ~RE-DEFINED
runThreadN                    16     ~RE-DEFINED
outSAMstrandField             intronMotif     ~RE-DEFINED
sjdbGTFfile                   /mnt/X500/farmers/leiyc/RNA_pipeline/pipeline/RNAseq/db/Homo_sapiens.GRCh37.87.gtf     ~RE-DEFINED
genomeDir                     /mnt/X500/farmers/leiyc/RNA_pipeline/pipeline/RNAseq/db/ref     ~RE-DEFINED
##### Finished reading parameters from all sources

##### Final user re-defined parameters-----------------:
runThreadN                        16
genomeDir                         /mnt/X500/farmers/leiyc/RNA_pipeline/pipeline/RNAseq/db/ref
readFilesIn                       /mnt/GenePlus001/rd/outline/20190613/wangjun/output/QC/180025975FR_180025975FR_HUM_C_GC0A_553_Z_0_A/180025975FR_180025975FR_HUM_C_GC0A_553_Z_0_A_rmrfq.1.gz   /mnt/GenePlus001/rd/outline/20190613/wangjun/output/QC/180025975FR_180025975FR_HUM_C_GC0A_553_Z_0_A/180025975FR_180025975FR_HUM_C_GC0A_553_Z_0_A_rmrfq.2.gz   
readFilesCommand                  zcat   
outFileNamePrefix                 /mnt/GenePlus001/rd/outline/20190613/wangjun/output/Align/180025975FR_180025975FR_HUM_C_GC0A_553_Z_0_A/180025975FR_180025975FR_HUM_C_GC0A_553_Z_0_A_
outReadsUnmapped                  None
outSAMtype                        BAM   Unsorted   
outSAMstrandField                 intronMotif
alignIntronMax                    100000
alignMatesGapMax                  100000
alignSJDBoverhangMin              10
alignSJstitchMismatchNmax         5   -1   5   5   
chimSegmentMin                    12
chimJunctionOverhangMin           12
chimSegmentReadGapMax             3
chimOutJunctionFormat             1   
sjdbGTFfile                       /mnt/X500/farmers/leiyc/RNA_pipeline/pipeline/RNAseq/db/Homo_sapiens.GRCh37.87.gtf
twopassMode                       Basic

-------------------------------
##### Final effective command line:
/mnt/X500/farmers/wuzp/RNA/RNAseq/bin/rnaseq-align/bin/STAR   --runThreadN 16   --genomeDir /mnt/X500/farmers/leiyc/RNA_pipeline/pipeline/RNAseq/db/ref   --readFilesIn /mnt/GenePlus001/rd/outline/20190613/wangjun/output/QC/180025975FR_180025975FR_HUM_C_GC0A_553_Z_0_A/180025975FR_180025975FR_HUM_C_GC0A_553_Z_0_A_rmrfq.1.gz   /mnt/GenePlus001/rd/outline/20190613/wangjun/output/QC/180025975FR_180025975FR_HUM_C_GC0A_553_Z_0_A/180025975FR_180025975FR_HUM_C_GC0A_553_Z_0_A_rmrfq.2.gz      --readFilesCommand zcat      --outFileNamePrefix /mnt/GenePlus001/rd/outline/20190613/wangjun/output/Align/180025975FR_180025975FR_HUM_C_GC0A_553_Z_0_A/180025975FR_180025975FR_HUM_C_GC0A_553_Z_0_A_   --outReadsUnmapped None   --outSAMtype BAM   Unsorted      --outSAMstrandField intronMotif   --alignIntronMax 100000   --alignMatesGapMax 100000   --alignSJDBoverhangMin 10   --alignSJstitchMismatchNmax 5   -1   5   5      --chimSegmentMin 12   --chimJunctionOverhangMin 12   --chimSegmentReadGapMax 3   --chimOutJunctionFormat 1      --sjdbGTFfile /mnt/X500/farmers/leiyc/RNA_pipeline/pipeline/RNAseq/db/Homo_sapiens.GRCh37.87.gtf   --twopassMode Basic

##### Final parameters after user input--------------------------------:
versionSTAR                       20201
versionGenome                     20101   20200   
parametersFiles                   -   
sysShell                          -
runMode                           alignReads
runThreadN                        16
runDirPerm                        User_RWX
runRNGseed                        777
genomeDir                         /mnt/X500/farmers/leiyc/RNA_pipeline/pipeline/RNAseq/db/ref
genomeLoad                        NoSharedMemory
genomeFastaFiles                  -   
genomeChainFiles                  -   
genomeSAindexNbases               14
genomeChrBinNbits                 18
genomeSAsparseD                   1
genomeSuffixLengthMax             18446744073709551615
genomeFileSizes                   0   
genomeConsensusFile               -
readFilesType                     Fastx   
readFilesIn                       /mnt/GenePlus001/rd/outline/20190613/wangjun/output/QC/180025975FR_180025975FR_HUM_C_GC0A_553_Z_0_A/180025975FR_180025975FR_HUM_C_GC0A_553_Z_0_A_rmrfq.1.gz   /mnt/GenePlus001/rd/outline/20190613/wangjun/output/QC/180025975FR_180025975FR_HUM_C_GC0A_553_Z_0_A/180025975FR_180025975FR_HUM_C_GC0A_553_Z_0_A_rmrfq.2.gz   
readFilesPrefix                   -
readFilesCommand                  zcat   
readMatesLengthsIn                NotEqual
readMapNumber                     18446744073709551615
readNameSeparator                 /   
inputBAMfile                      -
bamRemoveDuplicatesType           -
bamRemoveDuplicatesMate2basesN    0
limitGenomeGenerateRAM            31000000000
limitIObufferSize                 150000000
limitOutSAMoneReadBytes           100000
limitOutSJcollapsed               1000000
limitOutSJoneRead                 1000
limitBAMsortRAM                   0
limitSjdbInsertNsj                1000000
outFileNamePrefix                 /mnt/GenePlus001/rd/outline/20190613/wangjun/output/Align/180025975FR_180025975FR_HUM_C_GC0A_553_Z_0_A/180025975FR_180025975FR_HUM_C_GC0A_553_Z_0_A_
outTmpDir                         -
outTmpKeep                        None
outStd                            Log
outReadsUnmapped                  None
outQSconversionAdd                0
outMultimapperOrder               Old_2.4
outSAMtype                        BAM   Unsorted   
outSAMmode                        Full
outSAMstrandField                 intronMotif
outSAMattributes                  Standard   
outSAMunmapped                    None   
outSAMorder                       Paired
outSAMprimaryFlag                 OneBestScore
outSAMreadID                      Standard
outSAMmapqUnique                  255
outSAMflagOR                      0
outSAMflagAND                     65535
outSAMattrRGline                  -   
outSAMheaderHD                    -   
outSAMheaderPG                    -   
outSAMheaderCommentFile           -
outBAMcompression                 1
outBAMsortingThreadN              0
outBAMsortingBinsN                50
outSAMfilter                      None   
outSAMmultNmax                    18446744073709551615
outSAMattrIHstart                 1
outSAMtlen                        1
outSJfilterReads                  All
outSJfilterCountUniqueMin         3   1   1   1   
outSJfilterCountTotalMin          3   1   1   1   
outSJfilterOverhangMin            30   12   12   12   
outSJfilterDistToOtherSJmin       10   0   5   10   
outSJfilterIntronMaxVsReadN       50000   100000   200000   
outWigType                        None   
outWigStrand                      Stranded   
outWigReferencesPrefix            -
outWigNorm                        RPM   
outFilterType                     Normal
outFilterMultimapNmax             10
outFilterMultimapScoreRange       1
outFilterScoreMin                 0
outFilterScoreMinOverLread        0.66
outFilterMatchNmin                0
outFilterMatchNminOverLread       0.66
outFilterMismatchNmax             10
outFilterMismatchNoverLmax        0.3
outFilterMismatchNoverReadLmax    1
outFilterIntronMotifs             None
outFilterIntronStrands            RemoveInconsistentStrands
clip5pNbases                      0   
clip3pNbases                      0   
clip3pAfterAdapterNbases          0   
clip3pAdapterSeq                  -   
clip3pAdapterMMp                  0.1   
winBinNbits                       16
winAnchorDistNbins                9
winFlankNbins                     4
winAnchorMultimapNmax             50
winReadCoverageRelativeMin        0.5
winReadCoverageBasesMin           0
scoreGap                          0
scoreGapNoncan                    -8
scoreGapGCAG                      -4
scoreGapATAC                      -8
scoreStitchSJshift                1
scoreGenomicLengthLog2scale       -0.25
scoreDelBase                      -2
scoreDelOpen                      -2
scoreInsOpen                      -2
scoreInsBase                      -2
seedSearchLmax                    0
seedSearchStartLmax               50
seedSearchStartLmaxOverLread      1
seedPerReadNmax                   1000
seedPerWindowNmax                 50
seedNoneLociPerWindow             10
seedMultimapNmax                  10000
seedSplitMin                      12
alignIntronMin                    21
alignIntronMax                    100000
alignMatesGapMax                  100000
alignTranscriptsPerReadNmax       10000
alignSJoverhangMin                5
alignSJDBoverhangMin              10
alignSJstitchMismatchNmax         5   -1   5   5   
alignSplicedMateMapLmin           0
alignSplicedMateMapLminOverLmate    0.66
alignWindowsPerReadNmax           10000
alignTranscriptsPerWindowNmax     100
alignEndsType                     Local
alignSoftClipAtReferenceEnds      Yes
alignEndsProtrude                 0   ConcordantPair   
alignInsertionFlush               None
peOverlapNbasesMin                0
peOverlapMMp                      0.01
chimSegmentMin                    12
chimScoreMin                      0
chimScoreDropMax                  20
chimScoreSeparation               10
chimScoreJunctionNonGTAG          -1
chimMainSegmentMultNmax           10
chimJunctionOverhangMin           12
chimOutType                       Junctions   
chimFilter                        banGenomicN   
chimSegmentReadGapMax             3
chimMultimapNmax                  0
chimMultimapScoreRange            1
chimNonchimScoreDropMin           20
chimOutJunctionFormat             1   
sjdbFileChrStartEnd               -   
sjdbGTFfile                       /mnt/X500/farmers/leiyc/RNA_pipeline/pipeline/RNAseq/db/Homo_sapiens.GRCh37.87.gtf
sjdbGTFchrPrefix                  -
sjdbGTFfeatureExon                exon
sjdbGTFtagExonParentTranscript    transcript_id
sjdbGTFtagExonParentGene          gene_id
sjdbOverhang                      100
sjdbScore                         2
sjdbInsertSave                    Basic
varVCFfile                        -
waspOutputMode                    None
quantMode                         -   
quantTranscriptomeBAMcompression    1
quantTranscriptomeBan             IndelSoftclipSingleend
twopass1readsN                    18446744073709551615
twopassMode                       Basic
----------------------------------------


   Input read files for mate 1, from input string /mnt/GenePlus001/rd/outline/20190613/wangjun/output/QC/180025975FR_180025975FR_HUM_C_GC0A_553_Z_0_A/180025975FR_180025975FR_HUM_C_GC0A_553_Z_0_A_rmrfq.1.gz
-rw-rw-r-- 1 rd rd 789058483 Aug 12 17:37 /mnt/GenePlus001/rd/outline/20190613/wangjun/output/QC/180025975FR_180025975FR_HUM_C_GC0A_553_Z_0_A/180025975FR_180025975FR_HUM_C_GC0A_553_Z_0_A_rmrfq.1.gz

   readsCommandsFile:
exec > "/mnt/GenePlus001/rd/outline/20190613/wangjun/output/Align/180025975FR_180025975FR_HUM_C_GC0A_553_Z_0_A/180025975FR_180025975FR_HUM_C_GC0A_553_Z_0_A__STARtmp/tmp.fifo.read1"
echo FILE 0
zcat      "/mnt/GenePlus001/rd/outline/20190613/wangjun/output/QC/180025975FR_180025975FR_HUM_C_GC0A_553_Z_0_A/180025975FR_180025975FR_HUM_C_GC0A_553_Z_0_A_rmrfq.1.gz"


   Input read files for mate 2, from input string /mnt/GenePlus001/rd/outline/20190613/wangjun/output/QC/180025975FR_180025975FR_HUM_C_GC0A_553_Z_0_A/180025975FR_180025975FR_HUM_C_GC0A_553_Z_0_A_rmrfq.2.gz
-rw-rw-r-- 1 rd rd 809548521 Aug 12 17:37 /mnt/GenePlus001/rd/outline/20190613/wangjun/output/QC/180025975FR_180025975FR_HUM_C_GC0A_553_Z_0_A/180025975FR_180025975FR_HUM_C_GC0A_553_Z_0_A_rmrfq.2.gz

   readsCommandsFile:
exec > "/mnt/GenePlus001/rd/outline/20190613/wangjun/output/Align/180025975FR_180025975FR_HUM_C_GC0A_553_Z_0_A/180025975FR_180025975FR_HUM_C_GC0A_553_Z_0_A__STARtmp/tmp.fifo.read2"
echo FILE 0
zcat      "/mnt/GenePlus001/rd/outline/20190613/wangjun/output/QC/180025975FR_180025975FR_HUM_C_GC0A_553_Z_0_A/180025975FR_180025975FR_HUM_C_GC0A_553_Z_0_A_rmrfq.2.gz"

Hope your reply.


Best,
Lei

**Comment by alexdobin** [comment]
Hi Lei,

is the output partition normal linux partition - in particular, does it support fifo files.
Please try:

**Comment by alexdobin** [comment]
Also, if you run the same example multiple times, do you have the same problem?
It seems that the process hangs before it starts loading the genome...

**Comment by LEIyuechen** [comment]
Hi Alex,

The all output of fifo files is showed as below:
/mnt/GenePlus001/rd/outline/20190510/align_test/output/QC/180008559FR_180008559FR_HUM_C_GC1A_597_A_RD1_A/180008559FR_180008559FR_HUM_C_GC1A_597_A_RD1_A_rmrfq.2.gz

However, I have tried the command for "mkfifo /mnt/GenePlus001/rd/outline/20190510/align_test/output/Align/180008559FR_180008559FR_HUM_C_GC1A_597_A_RD1_A/180008559FR_180008559FR_HUM_C_GC1A_597_A_RD1_A__STARtmp/tmp.fifo.read1". And there's no output, but an new empty file(tmp.fifo.read) appears. 

And, if I run the same example multiplt times, it will work without problems when second time, seldom work for third time. 

Hope your reply
Best,
Lei

**Comment by alexdobin** [comment]
Hi Lei,

it looks like the fifo files work, so it's another problem...
And since the run works some times, it's likely to be a system problem.
Are the  /mnt/ partitions network-mounted? If so, please this run from a completely local partition - this includes the genome directory, input fastq, and output directory. If this works consistently, you can try to figure out which of the three (genome directory, input fastq, and output directory) is a culprit. Then you could stage the data for your runs, i.e. temporarily copy it to the local partition.

Cheers
Alex
