### ISSUE TITLE
Using STAR to align and generate GeneCounts from fastq files "terminate called after throwing an instance of 'std::bad_alloc'   what():  std::bad_alloc" then "bash: syntax error near unexpected token `(' " after --genomeChrBinNbits fix

### ISSUE THREAD

**Issue by jasonsaunderswilliams** [alexdobin/STAR#694]
Hi,

I tried the follwing fix: https://github.com/alexdobin/STAR/issues/103

For the std::bad_alloc error. 
I'm sure it will work, but I get this error when I add the 
--genomeChrBinNbits} = min(18, log2(GenomeLength/NumberOfReferences)) command
as it is written in the STAR manual...

bash: syntax error near unexpected token `('

My full command is
docker run -ti --rm -v /data/Jason:/data/Jason -v /data/Jason:/inputfiles stevetsa/star STARlong --runThreadN 1 --runMode alignReads --outFilterMultimapNmax 1 --outFilterMatchNmin 35 --outSAMtype BAM Unsorted SortedByCoordinate --quantMode GeneCounts --twopassMode Basic --genomeDir /data/Jason/Genome_Directory_STAR/ --genomeChrBinNbits = min(18, log2(GenomeLength/NumberOfReferences)) --readFilesIn /data/Jason/SRX4156394_1.fastq /data/Jason/SRX4156394_2.fastq --outFileNamePrefix /data/Jason/RNASeq_SRX4156394

Thanks in advance.

Jason

**Comment by alexdobin** [comment]
Hi Jason,

what genome are you mapping to, and what command did you use to generate the index?
You need to use --genomeChrBinNbits at the genome generation step, and you need to make the actual calculation of min(18, log2(GenomeLength/NumberOfReferences)) for you genome, and supply STAR with the rounded integer number.
Also, I would not recommend using STARlong for Illumina reads.

Cheers
Alex

**Comment by jasonsaunderswilliams** [comment]
Thanks Alex,

Let me know if you’d prefer me to reply to the following on GitHub, but I am asking a new question also which other people seemed to have
experienced problems with:

I got a little mixed up there. I have actually managed to get some gene counts for the sequencing runs we did and I now understand better the
genome generation step -I used hg38 - and  also the difference between aligning to transcriptome / genomes and their respective advantages/ disadvantages.
I will run these again using STAR and not STARlong as you recommended.

Separately, I am having problems with RNA seq data from ENA / SRA. When I run them through STAR I get either 0 or very small gene counts.
Clearly I need to adjust my parameters somehow, the data I tried running from the ENA for example were these:

https://www.ebi.ac.uk/ena/data/view/SRR8181382

As an amateur bioinformatician I can’t tell what adjustments I should make to my STAR command line depending on the sequencing parameters.
The only piece of information I can see here in the archive is that they used an Illumina 2500. This doesn’t mean much to me.

Here’s the command line.

sudo docker run -ti --rm -v /home/ubuntu/work/Jason/:/home/ubuntu/work/Jason/ -v /home/ubuntu/work/Jason:/inputfiles stevetsa/star STARlong --runThreadN 1 --runMode alignReads --outFilterMultimapNmax 1 --outFilterMatchNmin 35 --outSAMtype BAM Unsorted SortedByCoordinate --quantMode GeneCounts --twopassMode Basic --genomeDir /home/ubuntu/work/Jason/Genomes/genomedirectory/ --readFilesIn /home/ubuntu/work/Jason/SRR8181382_1.fastq.gz /home/ubuntu/work/Jason/SRR8181382_1.fastq.gz --readFilesCommand zcat --outFileNamePrefix /home/ubuntu/work/Jason/RNASeq_SRR8181382
Jul 22 14:59:48 ..... started STAR run
Jul 22 14:59:48 ..... loading genome
Jul 22 15:08:05 ..... started 1st pass mapping
Jul 22 18:37:19 ..... finished 1st pass mapping
Jul 22 18:37:21 ..... inserting junctions into the genome indices
Jul 22 18:39:47 ..... started mapping
Jul 22 22:05:46 ..... started sorting BAM
Jul 22 22:05:47 ..... finished successfully

I attach the log.out file and the genecount file.

Thank you for your help and please let me know if you think it would be useful for others
If I post this as a new issue.

Best wishes,

Jason

________________________________

**Comment by jasonsaunderswilliams** [comment]
Hi Alex, I have now resolved this second problem. Incorrect filepath! Apologies.

**Comment by alexdobin** [comment]
Hi Jason,

thanks for letting me know!

Cheers
Alex

**Comment by alexdobin** [comment]
Hi Jason,

if I am not mistaken, you resolved this problem?
If not, or if you have further questions, please do not hesitate to bump it up.

Cheers,
Alex

**Comment by jasonsaunderswilliams** [comment]
Hi Alex,

Yes, thank you so much.

All the best,

Jason
