### ISSUE TITLE
Genome indexing error -- terminate called after throwing an instance of 'std::bad_alloc'   what():  std::bad_alloc

### ISSUE THREAD

**Issue by GatorShan** [alexdobin/STAR#695]
Dear Alex,

This is Shan. Could you please help me to figure out the following error while I am trying to index our genome?

Error I got:
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
/tmp/slurmd/job39445512/slurm_script: line 29: 15659 Aborted                 (core dumped) STAR...

Here are some information about our draft genome: 808Mb; 12,310 scaffold. The sequencing platform is HiSeq X, 2X150bp.

I used the following command (I requested 4 CPUs, and 25G RAM/CPU):
STAR --runMode genomeGenerate \
	--runThreadN 4 \
	--genomeDir ${OUT} \
	--genomeFastaFiles ${IN}/Tdub.V1.fasta \
	--sjdbGTFfile ${IN}/Tdub.V1.rm.gtf \
	--sjdbOverhang 149 \
	--genomeChrBinNbits 16 \
	--limitGenomeGenerateRAM 95000000000

The last 5 lines from the Log.out file is:
Jul 19 19:32:44 ... loading chunks from disk, packing SA...
Jul 19 19:33:31 ... finished generating suffix array
Jul 19 19:33:31 ... generating Suffix Array index
Jul 19 19:37:16 ... completed Suffix Array index
Jul 19 19:37:16 ..... processing annotations GTF

Thanks ahead for your kind help! Please let me know if you need any additional info.

Best,

Shan

**Comment by alexdobin** [comment]
Hi Shan,
your genome should fit into 25GB of RAM. Please send me the Log.out file of the failed run.
Cheers
Alex

**Comment by GatorShan** [comment]
Dear Alex,

Thanks for your kind response! Please find the attached Log.out file (in txt format
[Log.out.txt](https://github.com/alexdobin/STAR/files/3418709/Log.out.txt)
) from the most recent failed run -- I requested 1 CPU with 28 GB of RAM this time.

Best,

Shan

**Comment by alexdobin** [comment]
Hi Shan,

everything seems to be fine until it starts processing the GTF file...
Could you post a few lines of the GTF file?

Cheers
Alex

**Comment by GatorShan** [comment]
Hi Alex,

Yes! Here are the first 10 lines of the gtf file:
Tdub_V1_scaffold_12310	maker	exon	1	312	.	+	.	transcript_id "TragDub21528-RA"; gene_id "TragDub21528"; gene_name "TragDub21528";
Tdub_V1_scaffold_12310	maker	CDS	1	312	.	+	0	transcript_id "TragDub21528-RA"; gene_id "TragDub21528"; gene_name "TragDub21528";
Tdub_V1_scaffold_12310	maker	exon	1	321	.	+	.	transcript_id "TragDub28271-RA"; gene_id "TragDub28271"; gene_name "TragDub28271";
Tdub_V1_scaffold_12310	maker	CDS	1	321	.	+	0	transcript_id "TragDub28271-RA"; gene_id "TragDub28271"; gene_name "TragDub28271";
Tdub_V1_scaffold_12310	maker	exon	1	384	.	-	.	transcript_id "TragDub10460-RA"; gene_id "TragDub10460"; gene_name "TragDub10460";
Tdub_V1_scaffold_12310	maker	CDS	1	384	.	-	0	transcript_id "TragDub10460-RA"; gene_id "TragDub10460"; gene_name "TragDub10460";
Tdub_V1_scaffold_12310	maker	exon	1	471	.	+	.	transcript_id "TragDub24829-RA"; gene_id "TragDub24829"; gene_name "TragDub24829";
Tdub_V1_scaffold_12310	maker	CDS	1	471	.	+	0	transcript_id "TragDub24829-RA"; gene_id "TragDub24829"; gene_name "TragDub24829";
Tdub_V1_scaffold_12310	maker	exon	1	555	.	+	.	transcript_id "TragDub24439-RA"; gene_id "TragDub24439"; gene_name "TragDub24439";
Tdub_V1_scaffold_12310	maker	CDS	1	555	.	+	0	transcript_id "TragDub24439-RA"; gene_id "TragDub24439"; gene_name "TragDub24439";

BTW, I used gffread to change the format from gff to gtf:
gffread Tdub.V1.rm.gff -T -o Tdub.V1.rm.gtf

Thanks again!!

Shan

**Comment by alexdobin** [comment]
Hi Shan,

these few lines look OK in terms of tags. The only suspicious thing is that all exons start at 1 and overlap... hopefully this is not the case for all of them :).
Have you looked at this GTF in a browser to make sure looks reasonable?

Cheers
Alex

**Comment by GatorShan** [comment]
Thanks Alex! I will check the GTF file again and let you know soon.

Best,

Shan

**Comment by GatorShan** [comment]
Hi Alex, it seems like our gtf file is incorrect. We will figure that out and use the new gtf file to re-run STAR. I will keep you updated.
Thanks for your kind help!
Shan

**Comment by alexdobin** [comment]
Thanks for letting me know!
