### ISSUE TITLE
STAR build index not completing after 23 hours using chromosomes 1,2,3,4,5,6 from hg37

### ISSUE THREAD

**Issue by george-weingart** [alexdobin/STAR#698]
I am  trying to build an index using chromosomes 1-6 from hg37 (http://www.cureffi.org/2013/02/01/the-decoy-genome)

After 23 hours I cancelled the job.
When I ran the build index against chromosome 1 it ran in 15 minutes.
Does it make sense that the job building index from chromosomes 1-6 runs so long?
Am I doing something wrong?

I am enclosing the log of the job I cancelled.

The real objective was to use all the chromosomes in hg37 and build an index from them,  but wanted to be careful and run one chromosome, then 6 chromosomes and if that works, build an index from all chromosomes.

The job I am submitting looks as follows:

 
----------------------------------------------------------------
#!/bin/bash
module load STAR/2.7.0e-fasrc01
LocChrs="db3_chromosomes_in_sep_recs/chromosomes"
OutputIndexLoc="GenomeDir_hg37_chromosomes_1_6_Index"
mkdir ${OutputIndexLoc}
echo "Started building index"
date

STAR --runMode genomeGenerate --genomeFastaFiles ${LocChrs}/db3_1.fa ${LocChrs}/db3_2.fa ${LocChrs}/db3_3.fa ${LocChrs}/db3_2.fa ${LocChrs}/db3_4.fa ${LocChrs}/db3_5.fa ${LocChrs}/db3_6.fa --genomeDir  ${OutputIndexLoc}

date
echo "Ended building index"
-------------------------------------------------------------------

**Comment by alexdobin** [comment]
Hi @george-weingart 

the Log.out file did not get attached - it will be very helpful in diagnosing the problem.

Cheers
Alex

**Comment by george-weingart** [comment]
[Log_1_6_bad.txt](https://github.com/alexdobin/STAR/files/3419597/Log_1_6_bad.txt)

Hi Alex,  
I enclosed the log of the run I had to cancel after 23 hours (Log_1_6_bad.txt) which consisted of trying to build an index using chromosomes 1,2,3,4,5,6 from the human genome (hg37)

**But perhaps we can focus on the main goal:**

I want to build an index of all the human genome.  I use as source hg37 (http://www.cureffi.org/2013/02/01/the-decoy-genome)

Have you generated an index using the whole genome?  Is it too big ?

I have got around the problem by generating an index for each chromosome and running a search on each index.  That worked,  but it took 40 hours which is prohibitive.

Below is a table that shows how much time it took running using single chromosomes (Build and Search)

![Screen Shot 2019-07-22 at 5 51 00 PM](https://user-images.githubusercontent.com/3250181/61674594-56f72a00-aca9-11e9-823c-0f49f4e12a01.png)

### Bottom line:

1. Can you let me know if it is feasible to build an index from the whole human genome (eg. hg37) ?
2. Do you see anything in the log I sent you that could explain why,  building an index using as input chromosomes 1,2,3,4,5,6 would run more than 23 hours,  when every single build runs minutes ?

I will try to run again chromosomes 1-6,  perhaps there was a system glitch at the time....

### I am enclosing Logs for build of chromosomes 1-6 and results of searches against chromosome 1 and 2

Thanks!!
George Weingart







[Log_bldindx_db3_1.log](https://github.com/alexdobin/STAR/files/3419647/Log_bldindx_db3_1.log)
[Log_bldindx_db3_2.log](https://github.com/alexdobin/STAR/files/3419648/Log_bldindx_db3_2.log)
[Log_bldindx_db3_3.log](https://github.com/alexdobin/STAR/files/3419649/Log_bldindx_db3_3.log)
[Log_bldindx_db3_4.log](https://github.com/alexdobin/STAR/files/3419650/Log_bldindx_db3_4.log)
[Log_bldindx_db3_5.log](https://github.com/alexdobin/STAR/files/3419651/Log_bldindx_db3_5.log)
[Log_bldindx_db3_6.log](https://github.com/alexdobin/STAR/files/3419652/Log_bldindx_db3_6.log)
[Log_bldindx_db3_7.log](https://github.com/alexdobin/STAR/files/3419653/Log_bldindx_db3_7.log)
[Log_bldindx_db3_8.log](https://github.com/alexdobin/STAR/files/3419654/Log_bldindx_db3_8.log)
[Results_db3_1Log.final.log](https://github.com/alexdobin/STAR/files/3419657/Results_db3_1Log.final.log)
[Results_db3_1Log.log](https://github.com/alexdobin/STAR/files/3419658/Results_db3_1Log.log)
[Results_db3_1Log.progress.log](https://github.com/alexdobin/STAR/files/3419659/Results_db3_1Log.progress.log)
[Results_db3_2Log.final.log](https://github.com/alexdobin/STAR/files/3419660/Results_db3_2Log.final.log)
[Results_db3_2Log.log](https://github.com/alexdobin/STAR/files/3419662/Results_db3_2Log.log)
[Results_db3_2Log.progress.log](https://github.com/alexdobin/STAR/files/3419663/Results_db3_2Log.progress.log)

**Comment by george-weingart** [comment]
Hi Alex,
See comments above,  but in the meantime, I submitted a bldindx for the whole genome - lets see how long it runs.  Here is the log so far (10 minutes into the job)
[Log.out.txt](https://github.com/alexdobin/STAR/files/3427598/Log.out.txt)

**Comment by george-weingart** [comment]
I was able to generate the whole genome index.  Took 1 hour and 40 minutes.
Obviously, when I was trying to run chromosomes 1,2,3,4,5,6 together there was a system problem in the server and the job ran and ran and ran.
Thanks!

**Comment by alexdobin** [comment]
Hi @george-weingart 

good news - thanks for letting me know. There was nothing suspicious in the output files, so your conjecture about a system problem is likely correct. Also, you can speed-up the indexing with multi-threading (i.e. --runThreadN <N>).

Cheers
Alex
