### ISSUE TITLE
GenomeGenerate not using multi cores?

### ISSUE THREAD

**Issue by raviv** [alexdobin/STAR#70]
Hi,

I'm running
```
STARlong --runMode genomeGenerate --genomeDir . --genomeFastaFiles ../../Pepper.v.1.5.total.chr.fasta --sjdbFileChrStartEnd ../align_1pass/SJ.out.tab --sjdbOverhang 75 --runThreadN 16
```
And it seems to be using only one core although I specified runThreadN 16

Thanks,
Raviv.

**Comment by alexdobin** [comment]
Hi Raviv,

only the most intensive parts of the genome generation are threaded, you should see multi-core usage between STAR messages "starting to sort  Suffix Array. This may take a long time..." and "loading chunks from disk, packing SA..."

Cheers
Alex
