### ISSUE TITLE
Not able to get unmapped reads in sam file

### ISSUE THREAD

**Issue by Muskan3195** [alexdobin/STAR#700]
Hi,
I am not able to get unmapped reads in sam file even when I am using "--outSAMunmapped Within" 
The command I am using to retrieve SAM file having mapped and unmapped read is 
/home/zhuobuer/STAR-2.7.0d/bin/Linux_x86_64/STAR -- runMode alignReads --genomeDir star_index_ncbi/ --readFilesIn trimmed/B290_30_2_1_val_1.fq trimmed/B290_30_2_2_val_2.fq --outFileNamePrefix 30_align --outSAMunmapped Within 

Please, let me know if some one know what is the issue here

**Comment by alexdobin** [comment]
Hi Muskan,

first, please try the latest version 2.7.1a. 
How many unmapped reads are reported in the Log.final.out?
How do you check for unmapped reads in the SAM file?

Cheers
Alex

**Comment by Muskan3195** [comment]
I tried it with latest version and resolved it.
Thanks for your help.

Muskan
