### ISSUE TITLE
Star does not align as many SRs as bowtie2: Is there a way to modify Star run parms so it aligns as many as bowtie2 ?

### ISSUE THREAD

**Issue by george-weingart** [alexdobin/STAR#701]
Hi,

We are trying to eliminate all Human short reads from a synthetic file containing 4 million SRs comprised of 90% human  and 10% microbial SRs. Our index consists of the human genome, taken from hg37 (http://www.cureffi.org/2013/02/01/the-decoy-genome)

Star runs faster than Bowtie2,  but Bowtie2 provides better results (Bowtie2 Precision=99.7%, Star=79.3%;  Recalls are similar)

### The question:

Can you recommend how to modify  the parameters of Star so that we get results at least as good as Bowtie2?  I am enclosing the logs of both runs. We use --very-sensitive-local option for Bowtie2 and defaults for Star.

Thanks!

### DETAILS :  
The results of the alignment are as follows:
![Screen Shot 2019-07-25 at 6 36 00 PM](https://user-images.githubusercontent.com/3250181/61919706-ae94d000-af0b-11e9-962d-533b66653b7e.png)

### More in detail:
![Screen Shot 2019-07-25 at 6 36 16 PM](https://user-images.githubusercontent.com/3250181/61919736-d1bf7f80-af0b-11e9-870a-4279c2db3ce1.png)

### The Star Log files are :
[ResultsLog.progress.out.txt](https://github.com/alexdobin/STAR/files/3433843/ResultsLog.progress.out.txt)
[ResultsLog.out.txt](https://github.com/alexdobin/STAR/files/3433844/ResultsLog.out.txt)
[ResultsLog.final.out.txt](https://github.com/alexdobin/STAR/files/3433845/ResultsLog.final.out.txt)

**Comment by alexdobin** [comment]
Hi @george-weingart 

this is an interesting experiment. These are genomic DNA reads, right? It seems like there is no splicing going on.

One parameter you definitely need to change, is --outFilterMultimapNmax 10000 to prevent the reads that map to "too many loci: output as unmapped - this will account for 53560 "unmapped" reads. Other parameters to play with are --outFilterMatchNminOverLread and --outFilterScoreMinOverLread. They are both =0.66 by default, you can set one of them to 0 and vary the other down to 0.2, which should reduce the number of human reads unmappable to the human genome (but will increase the number of bacterial reads mapped to the human genome as a trade-off).

Cheers
Alex

**Comment by george-weingart** [comment]
Hi Alex!
Yes, those are DNA files.

I ran Star with the parameters:
--outFilterMultimapNmax 10000 --outFilterMatchNminOverLread 0 --outFilterScoreMinOverLread 0.2

### Results:
![Screen Shot 2019-07-26 at 4 18 15 PM](https://user-images.githubusercontent.com/3250181/61986025-4274a380-afc1-11e9-86e9-57e69f05f4bf.png)

### More in detail:
![Screen Shot 2019-07-26 at 4 18 07 PM](https://user-images.githubusercontent.com/3250181/61986062-4dc7cf00-afc1-11e9-8a95-65924c9ce095.png)

### Log files:
[Results_GenomeLog.progress.out.txt](https://github.com/alexdobin/STAR/files/3437599/Results_GenomeLog.progress.out.txt)
[Results_GenomeLog.out.txt](https://github.com/alexdobin/STAR/files/3437600/Results_GenomeLog.out.txt)
[Results_GenomeLog.final.out.txt](https://github.com/alexdobin/STAR/files/3437601/Results_GenomeLog.final.out.txt)

### My analysis:
Precision increased from 79% to 94%, we detect 87,069 more human reads but Bowtie2 still matches 16,029 more Human SRs to the Human Genome index.
But, the biggest issue is that we classify erroneously 148,142 microbial SRs out of all 400,000 (Reflected in the recall dropping from 100% to 63%).

Yes,  we could run Star first and then, take the unmapped SRs and run Bowtie2 - that input file to Bowtie2 is smaller and the run time of Star + Bowtie2 that way is shorter than just running Bowtie2.   But it is cumbersome and cumbersome things break....
We would like to use Star only instead of Bowtie2.

Perhaps we can tune the parms a bit more? 
I woud do it without troubling you, but I don't know the internals of Star - don't know which direction to modify them...

Thanks again !

**Comment by alexdobin** [comment]
Hi @george-weingart 

one thing to do is to optimize --outFilterScoreMinOverLread 0.2, varying it from 0.2 up to 0.66 (default), which would basically give you a precision-recall curve.
The next parameter to optimize would be --seedSearchStartLmax = 50 by default. You can try to reduce down to ~15, which should increase the sensitivity of the alignments.

I think the best way to figure out what's going on is to look at the reads that Bowtie maps to the human genome and STAR does not. Do they have a lot of mismatches or indels or soft-clips?
If you can share the FASTQs with me along with Bowtie alignments, I can look into it  - sometime next week.

Cheers
Alex

**Comment by george-weingart** [comment]
Hi Prof. Dobin!

Thanks for your response.
Let me follow up with Prof. Huttenhower - I'll reply Thursday.

Thanks very  much,
George Weingart PhD
Huttenhower Lab
Harvard School of Public Health

**Comment by george-weingart** [comment]
Hi Prof. Dobin,

I got approval from Prof. Huttenhower to send you the data, if you want to
look at it.

Index:
It is a  3.0 Gb fasta file.  How can I share that with you ?
We build an index from hg37 and decoys (
http://www.cureffi.org/2013/02/01/the-decoy-genome/)
We add to it Human contaminants that we take form:
"Human contamination in bacterial genomes has created thousands of spurious
proteins” -   Salzberg et. al. 2019

Data
It is a 1Gb fastq file comprised of 4 million short reads, 90% human that
start with ID "ERR" and 10% microbial short reads that all start with id
"rd|"
How can I share that with you ?

Stating the super obvious: We want to remove as many Human short reads as
possible while keeping the maximum microbial short reads,  beating the
results of Bowtie2 that I sent before.

Thanks and best regards,

George Weingart PhD
Huttenhower Lab
Harvard School of Public Health

**Comment by alexdobin** [comment]
Hi George,

sorry for the long delay.
Here are the STAR parameters that will give you results similar to Bowtie's:
```
# output one alignment per read to reduce SAM/BAM size
--outSAMmultNmax 1 

# for mapping DNA (unspliced)
--alignIntronMax 1 --winBinNbits 7    

# control scoring
--scoreGenomicLengthLog2scale 0 --scoreDelOpen 0 --scoreInsOpen 0 --scoreDelBase -1 --scoreInsBase -1

# multimappers
---outFilterMultimapNmax -1 -winAnchorMultimapNmax 3000 --seedPerReadNmax 30000 --alignWindowsPerReadNmax 30000 --seedPerWindowNmax 1000

# output filters
 --outFilterMatchNminOverLread 0 --outFilterScoreMinOverLread 0 --outFilterScoreMin 27
```

Last parameter is the most crucial one, it determines the trade-off between FP and FN (see the table). It defines the minimum alignment score threshold. Bowtie should have a similar parameter.

--outFilterScoreMin | Human reads mapped to human genome | Bacterial reads mapped to human genome
-- | -- | --
26 | 1177 | 1069
27 | 1271 | 482
28 | 1407 | 268

Hope this helps - please let me know if you have any questions.
Cheers
Alex

**Comment by george-weingart** [comment]
Hi Prof Dobin !

Thank you very much !

I will try and will let you know the resutls.

Also,  I want to see the other side of the spectrum, meaning:   What
happens when we analyze a file that is comprised of 10% human and 90%
microbial.
Will send you the result of that one as well.
My hope is that the same set of parameters will provide optimized results
for both sides of the spectrum,  because in the real world,  we do not know
what percentage of microbial vs human we get (Our goal is get rid of the
human data).

Eric / Curtis,
Would you like to add to that ?

Will keep you posted and thanks again !
Best regards,

George Weingart PhD
Huttenhower Lab
Harvard School of Public Health

**Comment by george-weingart** [comment]
Hi Prof. Dobin,

I ran a job with the parameters you prescribed - I am not clear on the
output:  All the files except for the ParmsLog.out are empty.
I must be doing something wrong.....
Here is the job and I am enclosing the log.

Can you guide me how to get the unmatched file?

Thanks!
George Weingart PhD
Huttenhower Lab
Harvard School of Public Health

#!/bin/bash

module load STAR/2.7.0e-fasrc01

LocInput
=/srv/export/hutlab12_nobackup/share_root/data/KneadData_eval/matrix_dbs_mappers/H90M10/human_microbial_mixed.fastq

RootLoc="
/srv/export/hutlab12_nobackup/share_root/data/KneadData_eval/matrix_dbs_mappers/star
"

p1="--outSAMmultNmax 1 --alignIntronMax 1 --winBinNbits 7
--scoreGenomicLengthLog2scale 0 --scoreDelOpen 0 --scoreInsOpen 0
--scoreDelBase -1 --scoreInsBase -1"

p2="--outFilterMultimapNmax -1 -winAnchorMultimapNmax 3000
--seedPerReadNmax 30000 --alignWindowsPerReadNmax 30000 --seedPerWindowNmax
1000"

p3="--outFilterMatchNminOverLread 0 --outFilterScoreMinOverLread 0
--outFilterScoreMin 27"

################################################OtherParms="--outReadsUnmapped
Fastx "

date

echo "Started searching"

STAR --outSAMmode Full --genomeDir ${RootLoc}/GenomeDirIndex_db3_Genome
--readFilesIn  ${LocInput} --outFileNamePrefix
${RootLoc}/Results_New_Parms/Results_New_Parms
${p1} ${p2} ${p3}

echo "Ended Searching"

date

**Comment by george-weingart** [comment]
Hi Prof. Dobin,

Just wanted to let you know that I am going to be on vacations abroad from
August 26 through September 17th - not taking my PC with me.

.... Didn't want you to think I was rude if I don't respond.

So I will follow up with you when I return from vacation ?

Thanks and best regards,

George Weingart PhD
Huttenhower Lab
Harvard School of Public Health

**Comment by george-weingart** [comment]
Hi Prof. Dobin,
I sent it yesterday in my previous email
Can you see if you  received it?
