### ISSUE TITLE
STAR solo BAM annotation

### ISSUE THREAD

**Issue by nh3** [alexdobin/STAR#702]
Hi,

Is it possible to add "corrected" cell and UMI barcode as tags in produced BAM when running in solo mode?

This would make it much easier to extract alignments for particular cells and/or molecules.

Many thanks,
Ni

**Comment by alexdobin** [comment]
Hi Ni,

yes - this ability was recently implemented. 
It's available on the development branch:
https://github.com/alexdobin/STAR/tree/soloDevelop

You can add CB UB for corrected cell barcode and UMI to --outSAMattributes list.
You will have to use --outSAMtype BAM SortedByCoordinate.
Uncorrected barcodes and qualities are recorded with  CR CY UR UY.

If you try it out, please let me know how it goes.
I will make an official release 2.7.2a after more testing.

Cheers
Alex
