### ISSUE TITLE
'N_noFeature  0  528  470' in ReadsPerGene.out.tab reported by STAR 2.6.1d/2.6.1e

### ISSUE THREAD

**Issue by wangyugui** [alexdobin/STAR#703]
Hi,

'N_noFeature  0  528  470' in ReadsPerGene.out.tab reported by STAR 2.6.1d/2.6.1e.

Is this a bug?

```
$awk '$3>0' ${bam_md_dir}/ReadsPerGene.out.tab
N_multimapping  2       2       2 (bug?)
N_noFeature     0       528     470    (bug?)
ENSG00000180433 998     470     528
```

Best Regards

**Comment by alexdobin** [comment]
Hi @wangyugui 

why do think it's a bug?

Cheers
Alex

**Comment by wangyugui** [comment]
Hi,

```
N_multimapping  2       2       2 (bug?)
N_noFeature     0       528     470    (bug?)
```
should be ?
```
N_multimapping  4       2       2 
N_noFeature     998       528     470
```

column 2: counts for unstranded RNA-seq
column 3: counts for the 1st read strand aligned with RNA (htseq-count option -s yes)
column 4: counts for the 2nd read strand aligned with RNA (htseq-count option -s reverse)

should 'column 2==column3+column4'?

**Comment by alexdobin** [comment]
Hi @wangyugui 

no, unstranded count does not have to be equal to the sum of two strands.

N_multimapping is the total number of multimapping reads, which are not counted at all, so the number is the same for each column.
N_noFeature: if a read overlaps a gene on the opposite strand, it will be counted as noFeature for one of the stranded columns, but will be counted towards the gene (and not as noFeature) in the unstranded column. Hence N_noFeature(unstranded) can be < N_noFeature(+) + N_noFeature(-).

Similar considerations for gene counts:
https://groups.google.com/d/msg/rna-star/qFLxINhF7cI/D0v-BRtpDAAJ

Cheers
Alex

**Comment by wangyugui** [comment]
Thanks a lot
