### ISSUE TITLE
STARSolo gene list

### ISSUE THREAD

**Issue by tingchiafelix** [alexdobin/STAR#704]
Hi Alex,
Thanks for your help last time. With regard to the gene list of STARSolo, is any way that we can replace our own gene list to run the STARSolo? We found the gene list of STARSolo includes too much RNA components which we like to remove. If this is possible, we're thinking the small gene list will probabaly speed up the mapping. Thank you in advance.

Best,
TC

**Comment by alexdobin** [comment]
Hi TC,

the STARsolo uses the genes that were provided in the GTF file at the genome generation step.
You would need to filter that GTF file to keep only the genes you want. If you need help doing that, please let me know, I might have an awk script somewhere to do that.

Note that you can also use CellRanger's FASTA and GTF that are heavily filtered, probably along the lines you want to do it, e.g.
refdata-cellranger-GRCh38-1.2.0/fasta/genome.fa
refdata-cellranger-GRCh38-1.2.0/genes/genes.gtf

Cheers
Alex

**Comment by tingchiafelix** [comment]
Hi Alex,
Thank you for your suggestion. I go for CellRnager's FASTA and GTF files for now. If I need to filter the GTF file, I'll let you know for the awk script. Thanks agian for your help.

Best,
TC
