### ISSUE TITLE
gencode GR38 contigs affecting genome index generation 

### ISSUE THREAD

**Issue by angela-wei** [alexdobin/STAR#705]
Hello,

I am trying to generate a genome index using human GR38 fasta/gtf files from [Gencode ](https://www.gencodegenes.org/human/release_29.html) through STAR/2.7.0e. 

This is the command I am running:
`/path/to/STAR \
--runThreadN 3 \
--runMode genomeGenerate \
--genomeDir /path/to/OVERHANG_74 \
--genomeFastaFiles /path/to/GR38/GRCh38.primary_assembly.genome.fa \
--sjdbGTFfile /path/to/gencode.v29.chr_patch_hapl_scaff.annotation.gtf \
--sjdbOverhang 74 \
--outFileNamePrefix /path/to/output/`

However, in my Log.out document, I am seeing many warning messages similar to the following: 
`WARNING: while processing pGe.sjdbGTFfile=/path/to/gencode.v29.chr_patch_hapl_scaff.annotation.gtf: chromosome 'KQ759759.1' not found in Genome fasta files for line:
KQ759759.1      HAVANA  exon    19270   19510   .       -       .       gene_id "ENSG00000283350.1"; transcript_id "ENST00000636545.1"; gene_type "protein_coding"; gene_name "MUC6"; transcript_type "protein_coding"; transcript_name "MUC6-216"; exon_number 3; exon_id "ENSE00003794402.1"; level 2; protein_id "ENSP00000490759.1"; tag "basic"; havana_gene "OTTHUMG00000165140.4"; havana_transcript "OTTHUMT00000382120.2";`

I'm not quite sure why I am getting these warnings, as I downloaded both files from Gencode. If you could explain why I am getting these warnings, and how it affects the genome index generated, I would appreciate it.

**Comment by alexdobin** [comment]
Hi Angela,

for the primary FASTA, you would need to use primary (PRI) GTF, i.e. ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_29/gencode.v29.primary_assembly.annotation.gtf.gz

Primary FASTA / primary GTF is the best combination to use.

Cheers
Alex

**Comment by angela-wei** [comment]
Thank you for the quick response, using primary assembly FASTA/GTF files got rid of the warning messages.
