### ISSUE TITLE
STAR fatal error in reads input: short read sequence line: 0

### ISSUE THREAD

**Issue by mbassalbioinformatics** [alexdobin/STAR#708]
Hi
Trying to run STAR as part of the zUMI's package on an indrop set of fq files.  For some reason this set of files keeps failing with the errors
```
EXITING because of FATAL ERROR in reads input: short read sequence line: 0
Read Name=@SRR7665185.94
Read Sequence====
DEF_readNameLengthMax=50000
DEF_readSeqLengthMax=650
```

The fq files arent filtered/trimmed with any program prior to running.  Any advice as to what could be the problem would be greatly appreciated!

log.out.
[star.log.out.txt](https://github.com/alexdobin/STAR/files/3459221/star.log.out.txt)

**Comment by alexdobin** [comment]
Hi @mbassalbioinformatics 

it indicates problem with formattion of FASTQ files.
Does zUMI transform the FASTQ files before STAR mapping.
You would need to look at the FASTQ files that are fed to STAR with --readFilesIn.
Please grep for this read and the next lines with
`grep -A5 ^@SRR7665185.94   read.fastq`

Cheers
Alex

**Comment by alexdobin** [comment]
Also, STARsolo now supports the inDrop barcodes:
https://github.com/alexdobin/STAR/issues/605#issuecomment-514330615
If you decide to test it out, will be happy to help with any issues.

**Comment by mbassalbioinformatics** [comment]
> Hi @mbassalbioinformatics
> 
> it indicates problem with formattion of FASTQ files.
> Does zUMI transform the FASTQ files before STAR mapping.
> You would need to look at the FASTQ files that are fed to STAR with --readFilesIn.
> Please grep for this read and the next lines with
> `grep -A5 ^@SRR7665185.94 read.fastq`
> 
> Cheers
> Alex

Thanks for the quick response.  As far as im aware, zUMIs doesnt modify the reads prior to mapping, only counting.
I ran the grep command and rightly so there are a couple of reads that show up as -- only.  so they would be the problem.  

As these are indrop files, Theres 4 fq files, is there a simple awk command to remove these reads from the fq files? As I have multiple fq sets all with the same problem for some reason.  sorry I known this is an off-topic question.

**Comment by mbassalbioinformatics** [comment]
In case anyone else has the same issue with fq files.  For some reason my files had reads where only 3 lines were printed for the read not the usual 4 - ie
```
@SRR7665185.95 NS500422:430:HT5GYBGXY:1:11101:7296:1120 length=61
TGTCCCGAGTAGCTGGGATTACAGGCACCCGCCACCATGCCTGGCTAATGTTGGTCAGGCT
--
```

So to clear this up from the fq files can use the following sed commands

```bash
# match "--" and delete the 2 lines before it then pipe into sed and delte the line with the pattern!
sed -e:b -e'$!{N;1,2bb' -e\} -e'/\n--/!P;D' < <input_file> | sed '/--/d' > <output_file>
```

wrap this up in a loop in any language of your choice to iterate through your files and you should hopefully be good to go!

**Comment by alexdobin** [comment]
Hi @mbassalbioinformatics 

I think some of your messages got lost on this thread, though I still got them by e-mail.
If you need to correct the problems with FASTQ file (e.g. remove some incomplete read records), you need to make sure that the correction applies to both read1 and read2 (e.g., if reads are removed, they have to be removed from both files).

Cheers
Alex

**Comment by mbassalbioinformatics** [comment]
Hi @alexdobin 

My apologies I thought I'd found the problem (hence original messages) but that was wrong.

So the situation as it stands is that based on the grep command you suggested I use, the reads appear to be the right length and nothing is wrong with them.  So I'm still curious as to why STAR might be picking up the reads incorrectly.  Can I maybe email you the output of the grep command for you to have a look at and maybe advise please?

**Comment by alexdobin** [comment]
Hi @mbassalbioinformatics 

could you post the output of the grep command, i.e.
`grep -A5 ^@SRR7665185.94 read.fastq`
Note that fastq file has to be the one that zUMI feeds to STAR.

Cheers
Alex

**Comment by mbassalbioinformatics** [comment]
The output is a 25mb txt, you want me to post the entire output here or email?

**Comment by alexdobin** [comment]
Not sure why it's so large... it's supposed to match one read, and output 5 lines after that.
Please post the first 20 lines of the output.

**Comment by mbassalbioinformatics** [comment]
```
@SRR7665185.94 NS500422:430:HT5GYBGXY:1:11101:22019:1120 length=61
GCAGTTTTAAGTTATTAGTTTTTAAAATCAGTACTTTTTAATGGAAACAACTTGACCAAAA
+SRR7665185.94 NS500422:430:HT5GYBGXY:1:11101:22019:1120 length=61
AAAAAEEEAEEEEEEEEEEEEEEEEEEEEEE<AEEAEEAEEEEEEEEEEEEEEAEEEEEEE
@SRR7665185.95 NS500422:430:HT5GYBGXY:1:11101:7296:1120 length=61
TGTCCCGAGTAGCTGGGATTACAGGCACCCGCCACCATGCCTGGCTAATGTTGGTCAGGCT
--
@SRR7665185.940 NS500422:430:HT5GYBGXY:1:11101:5897:1475 length=61
TGGTGCTAATCTGCCCGCAGGACGGCATGGAGGCCATCCCCAACCCCTTCATCCAGCAGCA
+SRR7665185.940 NS500422:430:HT5GYBGXY:1:11101:5897:1475 length=61
AAAAAEEEEEEEEEEEAE/EEAEEEEEEAEEEEEEEEAEEE//EEEE<EE/EEEEEEEE</
@SRR7665185.941 NS500422:430:HT5GYBGXY:1:11101:8987:1475 length=61
CCCCGCTTCTACTAAAAATACAAAAATTAGCCAGGCATGGTGGCGTGTGCCTTTTATCCCA
+SRR7665185.941 NS500422:430:HT5GYBGXY:1:11101:8987:1475 length=61
AAAAAEEEAEEEEA6E/EAEEEEEEEEEEEEE//EE/AEE/<</E/AEEE<6EEE/AAAE/
@SRR7665185.942 NS500422:430:HT5GYBGXY:1:11101:21433:1477 length=61
GGGAATTTCAAAGTTTTTTTTTTTTTTTTTTTTTTGTTTTGTGGATATTTTTTTTGTATTT
+SRR7665185.942 NS500422:430:HT5GYBGXY:1:11101:21433:1477 length=61
66AAAEEEEE//EEEEEEEEEEEEAEEAEAEEE/E/AAEE/////E/<6/<E/<A//6/6A
@SRR7665185.943 NS500422:430:HT5GYBGXY:1:11101:10517:1477 length=61
```

**Comment by alexdobin** [comment]
Hi @mbassalbioinformatics 

this read looks fine indeed. Now, could you feed this fastq file directly to STAR, with just --genomeDir and --readFilesIn options, to see if it produces the error.

Thanks!
Alex

**Comment by mbassalbioinformatics** [comment]
Tried the recommended parameters and it worked fine.  I then went back to zUMI's developers and it seemed there was a slight incompatibility with long read names generated by fastq-dump and it getting passed to STAR.  Re-running fastq-dump with slightly different parameters fixed all the issues and STAR alignment worked fine. 
Thanks for your help through all this!

**Comment by alexdobin** [comment]
Happy to hear it worked out!

**Comment by ghartoularos** [comment]
Just for anyone who comes here in the future, I had the same error message, and the read raising the error looked completely fine. My error was raised from trying to input 2 fastqs of the same library split over 2 lanes using wildcard expansion: `--readFilesIn MY-SAMPLE_S97_L00*`. It seems `--readFilesIn` only takes 1 argument for single-end, or 2 arguments for paired-end. Concatenating the reads from multiple lanes and then running on the concatenated worked fine.

**Comment by roni-fultheim** [comment]
Hi, I'm also getting this error.
Used the above to find the read:
@SRR5088832.sra.28135572 HWI:1:X:5:2101:18206:51042 length=51
GCACCAAGCTGTAAACTTCAATATTTATTTCAAAGTCATTGGATACATCTT
+
@BBCCGGGGGGGGFGGGEGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG

And it looks fine. Any idea what can be causing this?
Thank you
@alexdobin

**Comment by alexdobin** [comment]
Hi @roni-fultheim 

what error are you getting?
Please send me the Log.out file.

Cheers
Alex

**Comment by roni-fultheim** [comment]
Hi,

thanks for answering. I'm getting this error, for many files of a dataset
(but not all). I have trimmed and filtered the reads before alignment using
PrinSeqLite, I've been using this program for a while and there was never
any problem. Duplicates were removed using internal program (again, never
had a problem). Do you have any idea what this is?
I used also seqtk for trimming and filtering with similar results.

*ERROR:*
EXITING because of FATAL ERROR in reads input: short read sequence line: 0
Read Name=@SRR5088825.sra.26364800
Read Sequence====
DEF_readNameLengthMax=50000
DEF_readSeqLengthMax=650

Dec 03 10:31:33 ...... FATAL ERROR, exiting

See attached sample log,

thank you,

Roni

**Comment by roni-fultheim** [comment]
Hi,

I am still encountering the same issue. Any help would be appreciated. No
matter what I do this happens, including re-downloading all data.

Thank you,

Roni

**Comment by alexdobin** [comment]
Hi Roni,

please start a new issue - I may miss posts in the Closed issues.

Please try to map raw data, without trimming. If it works, it means the issue is with trimming software.
To check the problem, please grep the read in question, from both Read1 and Read2

```zcat Read1.fastq.gz | grep -A3 @SRR5088825.sra.26364800```

Cheers
Alex

**Comment by roni-fultheim** [comment]
issue was found, the problem was singleton reads. Maybe the error should be
better documented.
What helped me eventually figure this out was running STAR 2.6, where the
same problem occurred with a different error message (clearer message)

Thank you
