### ISSUE TITLE
STAR alignment EXITING because of FATAL ERROR

### ISSUE THREAD

**Issue by NaneFox** [alexdobin/STAR#709]
Hi there, 
I ran into the following problem - running star/2.5.2b:
 
EXITING because of FATAL ERROR: could not open genome file /n/scratch2/cf139/refgenome-susscrofa/pig_genome_index/Genome
 
SOLUTION: check that the path to genome files, specified in --genomeDir is correct and the files are present, and have user read permsissions
 
Aug 01 08:51:35 ...... FATAL ERROR, exiting

Besides I checked for the err and out files from generating the index - which displayed the following:

Writing 2418324408 bytes into pig_genome_index/SA_5 ; empty space on disk = 411802249314304 bytes ... done
Writing 3798080240 bytes into pig_genome_index/SA_4 ; empty space on disk = 411687433392128 bytes ... done
Jul 26 02:43:37 ... loading chunks from disk, packing SA...
Jul 26 02:45:05 ... finished generating suffix array
Jul 26 02:45:05 ... generating Suffix Array index
 
BUG: next index is smaller than previous, EXITING
 
Jul 26 02:45:05 ...... FATAL ERROR, exiting

The people from HMSRC tried to run it to downloading new GTF and Fasta files or newer versions of STAR. They ran into the same problem as I did. 
Maybe you know whats going on & can give me some advice.

Thank you so much,

Nane

**Comment by kthlnktng** [comment]
Hello!

I'm one of the support folks from the [HPC cluster](https://wiki.rc.hms.harvard.edu/display/O2/O2) that @NaneFox is using.

To add to her post, the STAR command used was:

```
STAR --runThreadN 4 \
--runMode genomeGenerate \
--genomeDir pig_genome_index \
--genomeFastaFiles /n/scratch2/cf139/refgenome-susscrofa/Sus_scrofa.Sscrofa11.1.dna_rm.toplevel.fa \
--sjdbGTFfile /n/scratch2/cf139/refgenome-susscrofa/Sus_scrofa.Sscrofa11.1.97.gtf \
--sjdbOverhang 99
```

The job is running in the same directory that `pig_genome_index` is located in. This directory (`pig_genome_index`) does have the proper ownership and permissions associated with it. The FASTA and GTF files do exist at the specified locations, with the appropriate ownership/permissions.

The STAR versions this error has happened under were:
* `2.5.2b`
* `2.7.0f`

And the FASTA and GTF files used were for _Sus scrofa_, accessible from Ensembl at these locations:
* `ftp://ftp.ensembl.org/pub/release-97/fasta/sus_scrofa/dna/Sus_scrofa.Sscrofa11.1.dna_rm.toplevel.fa.gz`
*  `ftp://ftp.ensembl.org/pub/release-97/gtf/sus_scrofa/Sus_scrofa.Sscrofa11.1.97.gtf.gz`

Best,
Kathleen Keating
Harvard Medical School Research Computing

**Comment by alexdobin** [comment]
Hi Nane and Kathleen,

the issue is caused by the repeat-masking in the FASTA file.
Please use the unmasked file:
ftp://ftp.ensembl.org/pub/release-97/fasta/sus_scrofa/dna/Sus_scrofa.Sscrofa11.1.dna.toplevel.fa.gz
It worked fine in my genome generation run.

Cheers
Alex

**Comment by NaneFox** [comment]
Hi Alex,

Thank you so much.
I will do so.

Cheers,
Christiane
