### ISSUE TITLE
Segmentation fault (core dumped) Error

### ISSUE THREAD

**Issue by bm153** [alexdobin/STAR#712]
Hi Alex, 

I'm having a Segmentation Fault error and I can't figure out what's going wrong. 

Command: 

`STAR --runThreadN 20 --genomeDir mm10_STAR_index/ --readFilesIn CKR9180804_S35_R1_001_CK35_RMG33_2a_L.fastq CKR9180804_S35_R2_001_CK35_RMG33_2a_L.fastq CKR9180804_S36_R1_001_CK36_RMG33_2b_L.fastq CKR9180804_S36_R2_001_CK36_RMG33_2b_L.fastq CKR9180805_S14_R1_001_CK14_RMG28_3b_L.fastq CKR9180805_S14_R2_001_CK14_RMG28_3b_L.fastq CKR9180804_S39_R1_001_CK39_RMG32_2a_L.fastq CKR9180804_S39_R2_001_CK39_RMG32_2a_L.fastq CKR9180804_S40_R1_001_CK40_RMG32_2b_L.fastq CKR9180804_S40_R2_001_CK40_RMG32_2b_L.fastq CKR9180805_S17_R1_001_CK17_RMG31_3a_L.fastq CKR9180805_S17_R2_001_CK17_RMG31_3a_L.fastq CKR9180805_S18_R1_001_CK18_RMG31_3b_L.fastq CKR9180805_S18_R2_001_CK18_RMG31_3b_L.fastq --outFilterType BySJout --outFilterMultimapNmax 20 --outSAMunmapped Within --outFileNamePrefix MDM2_ --outSAMtype BAM SortedByCoordinate `

I get the 

> Segmentation fault (core dumped)

straight away.

I can send over the log.out file if needed. 

I've got 48GB of memory and 24CPUs available. 

Thanks!

**Comment by alexdobin** [comment]
Hi @bm153 
are these single-end read from multiple lanes that you want to be mapped all together?
If so, you need to separate the file names with commas without any spaces.

Cheers
Alex

**Comment by bm153** [comment]
Hi Alex, 

No, these are Paired End reads in the format [Read1] [Read2]

Best,
Bash

**Comment by alexdobin** [comment]
Hi Bash,

in this case you need to create two comma-separated list for Read1 and Read2, and separate those by space, i.e.
--readFilesIn    A_R1,B_R1,C_R1    A_R2,B_R2,C_R2

Cheers
Alex

**Comment by bm153** [comment]
Hi Alex, 

I'm now getting the following error:

```
Aug 09 18:25:24 ..... loading genome
Aug 09 18:26:24 ..... started mapping

BAMoutput.cpp:27:BAMoutput: exiting because of *OUTPUT FILE* error: could not create output file MDM2kd__STARtmp//BAMsort/19/30
SOLUTION: check that the path exists and you have write permission for this file. Also check ulimit -n and increase it to allow more open files.

Aug 09 18:26:46 ...... FATAL ERROR, exiting
```

**Comment by alexdobin** [comment]
Hi Bash,

this means that you need to increase the max number of  open files, e.g.
$ ulimit -n 5000

Cheers
Alex

**Comment by bm153** [comment]
Fixed the problem! 

Thank you very much Alex!

**Comment by WellJoea** [comment]
when submit  the STAR shell script with qsub command， the problem also raise, despite setting the  ulimit -n 81920

**Comment by alexdobin** [comment]
Hi @WellJoea 

how many threads are you using?

Cheers
Alex
