### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by guptapa** [alexdobin/STAR#719]
Hi,
I am using STAR-2.6.0a for custom genome index and paired end reads and getting following error:

EXITING because of fatal error: buffer size for SJ output is too small
Solution: increase input parameter --limitOutSJcollapsed
Aug 23 08:37:22 ...... FATAL ERROR, exiting

options I used:
--genomeLoad NoSharedMemory --genomeDir --runThread 1 --readFilesIn --outSAMtype BAM Unsorted --limitOutSJcollapsed int>0 --outFileNamePrefix 

same error with and without using this flag : --limitOutSJcollapsed int>0

**Comment by alexdobin** [comment]
Hi Paul,

--limitOutSJcollapsed requires a positive integer number. The default value is usually fine, please first try without specifying this parameter at all.
Also, I would recommend using more recent stable releases such as 2.6.1d or 2.7.2a .

Cheers
Alex

**Comment by guptapa** [comment]
Hi Alex,
As per your recommendation I used 2.7.2a but again got same error:

EXITING because of fatal error: buffer size for SJ output is too small
Solution: increase input parameter --limitOutSJcollapsed

Aug 24 00:06:49 ...... FATAL ERROR, exiting

I didn’t use —limitOutSJcollapsed flag in my script.

Parul

**Comment by guptapa** [comment]
Here you go!



Parul

**Comment by guptapa** [comment]
Hi Alex,
I hope this would work, let me know if not.

Thanks,
Parul

**Comment by guptapa** [comment]
Thanks much Alex.

Parul

**Comment by DiracZhu1998** [comment]
> Got it, thanks!
> Nothing suspicious in the Log.out file.
> So it seems like you do need to increase --limitOutSJcollapsed .
> The default value is 1000000, I would try increasing it to 2000000 and if it does not help, 5000000, i.e.
> --limitOutSJcollapsed 2000000
> 
> Cheers
> Alex

Hi Alex, I couldn't figure out the explanation of this parameter < limitOutSJcollapsed >, may you specify it again? Thanks a lot !
Dirac

**Comment by alexdobin** [comment]
Hi Dirac,

STAR records the splice junctions detected in the mapped reads, and --limitOutSJcollapsed defines the maximum number of splice junctions. It is used to pre-allocate arrays to store SJ information.

Cheers
Alex

**Comment by tallulandrews** [comment]
I get the same error working with some single nucleus RNAseq data. Is there a parameter somewhere I should change for single nucleus RNAseq data (lots of intronic / immature mRNAs), or perhaps I should edit the gtf file?

**Comment by alexdobin** [comment]
Hi @tallulandrews 

if you get the same error, you need to increase ```--limitOutSJcollapsed``` from the default 1000000 to 2000000 or even larger.
Generally, there are no specific parameters for nuclear RNA.

Cheers
Alex

**Comment by alexdobin** [comment]
Hi Alan,

yes, this problem will always generate exit code 104, but other problems may generate this code as well.

**Comment by alanhoyle** [comment]
We're trying to make a workflow that auto-scales resources when a job fails.  Is the only way to determine what to scale to parse the logs?  

The current version starts by explictly setting the default:  `--limitOutSJcollapsed 100000` and doubles on each attempt (up to 8000000)

Is there a list of exit codes?  Is there a list of things that would scale automatically?  Historically, this is the only error we've seen that gets addressed this way, but I haven't reviewed the code to see if there are others.  

Thank you @alexdobin !

**Comment by alexdobin** [comment]
Hi Alan,

in the beginning, I was trying to keep different exit codes for different classes of errors, but since no one was using them, I stopped doing carefully.
I think I should just make automatically reallocate arrays that are controlled by this parameter to avoid it altogether.
If there are other similar situations, please let me know. Most of them should be triggered very rarely as long as you close to default parameters, and the samples are not very extreme.
