### ISSUE TITLE
soloFeatures question

### ISSUE THREAD

**Issue by zhangguy** [alexdobin/STAR#729]
Hi @alexdobin ,
If we do ```--soloFeatures Gene SJ GeneFull```, STAR will generate three mtx files. If I want to count reads that map to exons, introns and splice junctions as effective reads for a gene, should I add up all three mtx or just use matrixGeneFull.mtx?
Thanks!

**Comment by alexdobin** [comment]
Hi @zhangguy 

no, these classes should not be summed.

- Gene counts contain all reads (UMIs) that are compatible with the transcripts of one gene. They will contain spliced reads but not reads that overlap introns.
- SJ counts contain all reads that are spliced, both annotated and novel.
- GeneFull contains all reads that overlap the gene locus (i.e. interval between gene start and gene end). They will contain all counts from Gene, and also intronic reads, and reads spliced with novel junctions within the gene locus.

Cheers
Alex
