### ISSUE TITLE
number of mismatches reported in the NM tag

### ISSUE THREAD

**Issue by igordot** [alexdobin/STAR#73]
I have a 2x50 run. I ran STAR 2.4.2a with `--outFilterMismatchNoverLmax 0.05` (alignment will be output only if its ratio of mismatches to *mapped* length is less than this value). I assume I should not have any reads with more than 5 mismatches. However, I still get alignments with over 20 mismatches or higher based on the NM tag. The nM tag (number of mismatches per pair) maxes out at 5, which makes sense. Why is there such a discrepancy between the two tags?

**Comment by alexdobin** [comment]
Hi Igor,

NM tag counts N-bases in the read or the genome as mismatches, while the nM does not.
You can check this by looking at the read sequence, and the MD tag.
If this explanation does not work, please send me an example.

Cheers
Alex

**Comment by igordot** [comment]
That was very helpful. Thanks.
