### ISSUE TITLE
Read counts different between sparse and non-sparse genome index

### ISSUE THREAD

**Issue by hermidalc** [alexdobin/STAR#730]
Hi @alexdobin - first want to say excellent library and manual, and thank you for making a conda-forge package of it.

I noticed that with everything else being exactly the same, that if I mapped reads using a sparser genome index created with e.g. ``--genomeSAsparseD 3`` then gene read counts for a sample are somewhat different than those mapped using a genome index with the default setting.  Why is this the case?  It seemed from the manual and online discussions regarding this parameter that it only saves memory, but I guess it also results in slightly reduced accuracy?

**Comment by alexdobin** [comment]
Hi Leandro,

I have not made the conda-forge package, you would need to thanks someone else for that. 😎

Sparsifying the genome option does affect the mapping slightly, indeed.
With --genomeSAsparseD 3, every 3rd suffix in the genome is indexed. To compensate for that, the seed search is initiated 3 times for every seed search start position, shifted by one base. However, it is not exactly the same as one search for a complete suffix array. The changes are marginal though, <0.1% of the reads affected in my tests.

Cheers
Alex

**Comment by hermidalc** [comment]
Thank you for the explanation. I see the same in my runs the read counts between both settings aren’t hugely different.
