### ISSUE TITLE
Running out of memory 

### ISSUE THREAD

**Issue by galeadmn** [alexdobin/STAR#732]
Hi,
I've built an index for Macaca_mulatta Ensembl release 97.  I used a CentOS machine with 314GB of RAM to build the index. I am trying to run STAR --quantMode GeneCounts but run out of memory on smaller machines (RAM = 64GB). Is it possible to run on smaller servers than the one used to build the index?

This is the command I used to build the index:

STAR --runThreadN 80 --limitGenomeGenerateRAM=256609344554   --runMode genomeGenerate --genomeDir /franklin/STAR_INDICES/Macaca_mulatta --genomeFastaFiles /franklin/STAR_INDICES/Macaca_mulatta/Macaca_mulatta.Mmul_8.0.1.dna.toplevel.fa --sjdbGTFfile /franklin/STAR_INDICES/Macaca_mulatta/Macaca_mulatta.Mmul_8.0.1.97.gtf

This is the command that I am trying to run:

/usr/local/bin/STAR  --genomeLoad LoadAndExit --twopassMode Basic --quantMode GeneCounts --runThreadN 6  --genomeDir /vol01/genome/Macaca_mulatta/8.0.1.97 --readFilesIn /share/IL15_PBMC/results_trimgalore/211_O10_31954_40_2h_1_RNA_mRNA_run03_S5_nohmrRNA_R1_001.fastq.gz /share/IL15_PBMC/results_trimgalore/211_O10_31954_40_2h_1_RNA_mRNA_run03_S5_nohmrRNA_R2_001.fastq.gz --outFileNamePrefix /share/IL15_PBMC/results_star//211_O10_31954_40_2h_1_RNA_mRNA_run03_S5_ --readFilesCommand zcat   --clip5pNbases 1 --clip3pNbases 24

This is the error info in /var/log/messages:
Sep  6 19:41:45 holmes kernel: Mem-Info:
Sep  6 19:41:45 holmes kernel: active_anon:15048661 inactive_anon:1037139 isolated_anon:0#012 active_file:250 inactive_file:3924 isolated_file:0#012 unevictable:0 dirty:1 writeback:0 unstable:0#012 slab_reclaimable:119328 slab_unreclaimable:22360#012 mapped:878 shmem:772 pagetables:48496 bounce:0#012 free:55289 free_pcp:708 free_cma:0
Sep  6 19:41:45 holmes kernel: Node 0 Normal free:45116kB min:45212kB low:56512kB high:67816kB active_anon:30546904kB inactive_anon:1796972kB active_file:944kB inactive_file:11116kB unevictable:0kB isolated(anon):0kB isolated(file):0kB present:33554432kB managed:33011200kB mlocked:0kB dirty:4kB writeback:0kB mapped:3148kB shmem:2736kB slab_reclaimable:236492kB slab_unreclaimable:32240kB kernel_stack:2512kB pagetables:97148kB unstable:0kB bounce:0kB free_pcp:1472kB local_pcp:80kB free_cma:0kB writeback_tmp:0kB pages_scanned:23846 all_unreclaimable? yes
Sep  6 19:41:45 holmes kernel: lowmem_reserve[]: 0 0 0 0
Sep  6 19:41:45 holmes kernel: Node 1 DMA free:15888kB min:20kB low:24kB high:28kB active_anon:0kB inactive_anon:0kB active_file:0kB inactive_file:0kB unevictable:0kB isolated(anon):0kB isolated(file):0kB present:15988kB managed:15904kB mlocked:0kB dirty:0kB writeback:0kB mapped:0kB shmem:0kB slab_reclaimable:0kB slab_unreclaimable:16kB kernel_stack:0kB pagetables:0kB unstable:0kB bounce:0kB free_pcp:0kB local_pcp:0kB free_cma:0kB writeback_tmp:0kB pages_scanned:0 all_unreclaimable? yes
Sep  6 19:41:45 holmes kernel: lowmem_reserve[]: 0 3071 31996 31996
Sep  6 19:41:45 holmes kernel: Node 1 DMA32 free:119976kB min:4304kB low:5380kB high:6456kB active_anon:2341316kB inactive_anon:644592kB active_file:0kB inactive_file:12kB unevictable:0kB isolated(anon):0kB isolated(file):0kB present:3378660kB managed:3145156kB mlocked:0kB dirty:0kB writeback:0kB mapped:4kB shmem:4kB slab_reclaimable:23800kB slab_unreclaimable:4340kB kernel_stack:160kB pagetables:7584kB unstable:0kB bounce:0kB free_pcp:120kB local_pcp:0kB free_cma:0kB writeback_tmp:0kB pages_scanned:547 all_unreclaimable? yes
Sep  6 19:41:45 holmes kernel: lowmem_reserve[]: 0 0 28925 28925
Sep  6 19:41:45 holmes kernel: Node 1 Normal free:40176kB min:40568kB low:50708kB high:60852kB active_anon:27306424kB inactive_anon:1706992kB active_file:56kB inactive_file:4568kB unevictable:0kB isolated(anon):0kB isolated(file):0kB present:30146560kB managed:29619364kB mlocked:0kB dirty:0kB writeback:0kB mapped:360kB shmem:348kB slab_reclaimable:217020kB slab_unreclaimable:52844kB kernel_stack:2896kB pagetables:89252kB unstable:0kB bounce:0kB free_pcp:1240kB local_pcp:172kB free_cma:0kB writeback_tmp:0kB pages_scanned:12167 all_unreclaimable? yes
Sep  6 19:41:45 holmes kernel: lowmem_reserve[]: 0 0 0 0
Sep  6 19:41:45 holmes kernel: Node 0 Normal: 58*4kB (UE) 268*8kB (UE) 99*16kB (UEM) 56*32kB (UE) 30*64kB (UE) 9*128kB (UM) 4*256kB (U) 5*512kB (UEM) 32*1024kB (UM) 0*2048kB 0*4096kB = 45176kB
Sep  6 19:41:45 holmes kernel: Node 1 DMA: 0*4kB 0*8kB 1*16kB (U) 0*32kB 2*64kB (U) 1*128kB (U) 1*256kB (U) 0*512kB 1*1024kB (U) 1*2048kB (M) 3*4096kB (M) = 15888kB
Sep  6 19:41:45 holmes kernel: Node 1 DMA32: 324*4kB (UE) 139*8kB (UEM) 58*16kB (UE) 39*32kB (UE) 17*64kB (UE) 9*128kB (UEM) 6*256kB (UEM) 6*512kB (UE) 102*1024kB (EM) 2*2048kB (M) 0*4096kB = 119976kB
Sep  6 19:41:45 holmes kernel: Node 1 Normal: 146*4kB (UE) 337*8kB (UEM) 114*16kB (UEM) 101*32kB (UEM) 31*64kB (UE) 8*128kB (UE) 2*256kB (UM) 2*512kB (EM) 1*1024kB (M) 13*2048kB (M) 0*4096kB = 40528kB
Sep  6 19:41:45 holmes kernel: Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=1048576kB
Sep  6 19:41:45 holmes kernel: Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=2048kB
Sep  6 19:41:45 holmes kernel: Node 1 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=1048576kB
Sep  6 19:41:45 holmes kernel: Node 1 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=2048kB
Sep  6 19:41:45 holmes kernel: 233783 total pagecache pages
Sep  6 19:41:45 holmes kernel: 228730 pages in swap cache
Sep  6 19:41:45 holmes kernel: Swap cache stats: add 32996758, delete 32766873, find 10379/11921
Sep  6 19:41:45 holmes kernel: Free swap  = 0kB
Sep  6 19:41:45 holmes kernel: Total swap = 33030140kB
Sep  6 19:41:45 holmes kernel: 16773910 pages RAM
Sep  6 19:41:45 holmes kernel: 0 pages HighMem/MovableOnly
Sep  6 19:41:45 holmes kernel: 326004 pages reserved
Sep  6 19:41:45 holmes kernel: SLUB: Unable to allocate memory on node -1 (gfp=0x8010)
Sep  6 19:41:45 holmes kernel:  cache: kmalloc-128, object size: 128, buffer size: 128, default order: 0, min order: 0

**Comment by alexdobin** [comment]
Hi @galeadmn 

please send me the Log.out file.

Cheers
Alex

**Comment by galeadmn** [comment]
[211_O10_31954_40_2h_1_RNA_mRNA_run03_S5_Log.out.txt](https://github.com/alexdobin/STAR/files/3592578/211_O10_31954_40_2h_1_RNA_mRNA_run03_S5_Log.out.txt)
Here it is.

**Comment by alexdobin** [comment]
Hi @galeadmn 

this assembly has a lot of contigs and thus requires scaling down the --genomeChrBinNbits parameter as log2[GenomeLength/NumberOfReferences] ~log2[3e9/3e5] ~ 13

Many small contigs will slow down mapping, I would recommend filtering them or combining the short ones into one large super-contig.

Cheers
Alex
