### ISSUE TITLE
Question : How to Count reads mapped only at 5'end and 3' end

### ISSUE THREAD

**Issue by agroppi** [alexdobin/STAR#738]
Is there a way by using STAR to count the reads mapped for each gene only at : 
- 5' end (let's say the first exon or the 5'UTR)
- 3' end (let's say the last exon or the 3'UTR)
?
Thanks

**Comment by alexdobin** [comment]
Hi Alexis,

presently, there is no option in STAR to do it.

You could use the following trick: create a gtf file with only the exons for which you want to count the reads. Each of the exons has to have a unique transcript_id which you can keep the same as in the original GTF. If you want separate counting for each of this exons, you need to give them unique gene_id. If you want to aggregate counting over all 5' of a given gene, you can keep gene_id from the GTF.

Then feed this new file to STAR at the mapping step (keep the original GTF at the genome generation step) as --sjdbGTFfile new.gtf

Cheers
Alex

**Comment by agroppi** [comment]
Hi Alex,

Thanks for this answer and advice :) 

Cheers 

Alexis
