### ISSUE TITLE
SAM/BAM Header all LN:0

### ISSUE THREAD

**Issue by ctcncgr** [alexdobin/STAR#74]
Hello all,

one of my co-workers noticed some very odd behavior from STAR the other day.  We have checked it a number of times and it seems highly consistent.

This command produces LN:0 for all reference headers:

The files gave me a bad header (chr with length 0) whe I ran this
/sw/compbio/STAR/2.4.2a/STAR --genomeDir $ref \
--readFilesIn $R1a $R2a \
--alignTranscriptsPerReadNmax 10000 \
--winAnchorMultimapNmax 50 \
--outFilterMismatchNoverLmax 0.3 \
--alignIntronMax 1000\
--runThreadN 8 --readFilesCommand zcat --twopassMode Basic --outSAMtype 
BAM SortedByCoordinate

The headers are fine when running this:

/sw/compbio/STAR/2.4.2a/STAR --genomeDir $ref --readFilesIn $R1 $R2 \
--outFilterMismatchNoverLmax 0.06 \
--alignIntronMax 1000 \
--runThreadN 8 --readFilesCommand zcat --twopassMode Basic --outSAMtype 
BAM SortedByCoordinate

It seems like when --alignTranscriptsPerReadNmax 10000 --winAnchorMultimapNmax 50 is added, for some reason the headers come out with LN:0

Thanks

**Comment by alexdobin** [comment]
Hi @ctcncgr,

I could not reproduce this problem on my test datasets. It must some kind of memory corruption, but valgrind does not detect any problems. Could you send me a minimalistic read set that replicates this problem? I would also need a link to genome fasta anf gtf.

Cheers
Alex

**Comment by ctcncgr** [comment]
Hey Alex,

I'm not sure I can actually do this as I don't believe this is public
data.  Let me ask, this was on behalf of a co-worker.  I can get a public
set of appropriate size and see if I can reproduce the error.  I will get
back to you.

Thank you for the response
