### ISSUE TITLE
Too many nCellBarcodes detected

### ISSUE THREAD

**Issue by LuciaJim** [alexdobin/STAR#742]
Hi Alex,
I'm running STARsolo with paired-end 125bp data from 10x from which I can expect a maximum cell recovery of 10k cells. However, when I check the Gene.stats file I see nCellBarcodes output is much larger than this.

Here you can see the Gene.stats file:

> 
                                         Barcodes:
                                       nNinBarcode          18148
                                   nUMIhomopolymer         121783
                                          nTooMany              0
                                          nNoMatch        8728048
                                              Gene:
                                         nUnmapped         167548
                                        nNoFeature      114319070
                                     nAmbigFeature        2585757
                             nAmbigFeatureMultimap        2585757
                                          nTooMany          68687
                                     nNoExactMatch         112577
                                       nExactMatch      179053992
                                            nMatch      180629370
                                     nCellBarcodes         237688
                                             nUMIs       16183779

I also attach the Log.final.out:

>                               
                                 Started job on |       Sep 18 12:09:53
                             Started mapping on |       Sep 18 12:10:08
                                    Finished on |       Sep 18 12:42:12
       Mapping speed, Million of reads per hour |       573.96

                          Number of input reads |       306750988
                      Average input read length |       125
                                    UNIQUE READS:
                   Uniquely mapped reads number |       266803135
                        Uniquely mapped reads % |       86.98%
                          Average mapped length |       123.61
                       Number of splices: Total |       63279157
            Number of splices: Annotated (sjdb) |       60084058
                       Number of splices: GT/AG |       62261187
                       Number of splices: GC/AG |       260250
                       Number of splices: AT/AC |       37145
               Number of splices: Non-canonical |       720575
                      Mismatch rate per base, % |       0.48%
                         Deletion rate per base |       0.01%
                        Deletion average length |       1.57
                        Insertion rate per base |       0.01%
                       Insertion average length |       1.22
                             MULTI-MAPPING READS:
        Number of reads mapped to multiple loci |       16627434
             % of reads mapped to multiple loci |       5.42%
        Number of reads mapped to too many loci |       385095
             % of reads mapped to too many loci |       0.13%
                                  UNMAPPED READS:
     Number of reads unmapped: too many mismatches |       0
       % of reads unmapped: too many mismatches |       0.00%
            Number of reads unmapped: too short |       22764252
                 % of reads unmapped: too short |       7.42%
                Number of reads unmapped: other |       171072
                     % of reads unmapped: other |       0.06%
                                  CHIMERIC READS:
                       Number of chimeric reads |       0
                            % of chimeric reads |       0.00%

And my full command:

> 
    STAR --runThreadN 60 --genomeDir /gtf/star --soloType Droplet --soloCBwhitelist /whiteList.txt --readFilesIn /17Nv_31416_AGCGAA_S1_L001_R2_001.fastq.gz,/17Nv_31416_CCGTGT_S2_L001_R2_001.fastq.gz,/17Nv_31416_GAAACC_S3_L001_R2_001.fastq.gz,/17Nv_31416_TTTCTG_S4_L001_R2_001.fastq.gz /17Nv_31416_AGCGAA_S1_L001_R1_001.fastq.gz,/17Nv_31416_CCGTGT_S2_L001_R1_001.fastq.gz,/17Nv_31416_GAAACC_S3_L001_R1_001.fastq.gz,/17Nv_31416_TTTCTG_S4_L001_R1_001.fastq.gz --soloCBstart 1 --soloCBlen 16 --soloUMIstart 17 --soloUMIlen 10 --soloBarcodeReadLength 0 --soloStrand Forward --soloFeatures Gene --soloUMIdedup 1MM_All --outFileNamePrefix /starSOLO_runs/17Nv/17Nv —-quantMode GeneCounts TranscriptomeSAM --readFilesCommand gunzip -c & 

Thank you very much for your nice work!
Best,
Lucia

**Comment by alexdobin** [comment]
Hi Lucia,

the statistics here are for raw unfiltered cells - i.e. all barcodes that have been detected.
If you want the filtered barcodes, you can 
1. Use extras/scripts/soloBasicCellFilter.awk from STAR distribution
2. Switch to latest STARsolo on soloDevelop branch (it will be officially released as 2.7.3 in a few days). It will generate a filtered set of cells, and also has Summary file with filtered cell statistics.
Both 1,2 use CellRanger 2 simple cell filtering strategy.
3. CellRanger 3 uses EmptyDrops package for filtering, which you can apply to STARsolo raw results.

Cheers
Alex

**Comment by LuciaJim** [comment]
Ok, thank you for your quick response.

Best,
Lucia
