### ISSUE TITLE
packing SA std::bad_alloc

### ISSUE THREAD

**Issue by barkasn** [alexdobin/STAR#75]
I encountered the following error when running genomeGenerate on a 16 core 30GB c4.4xlarge AWS instance, using the latest version of STAR from git.

$ STAR --runThreadN 15 --runMode genomeGenerate --genomeDir ~/extmount/work/databank/genomes/ensembl/GRCm38/STARindex/ --genomeFastaFiles ~/extmount/work/databank/genomes/ensembl/GRCm38/fasta/Mus_musculus.GRCm38.dna.toplevel.fa  --sjdbGTFfile ~/extmount/work/databank/genomes/ensembl/GRCm38/annotation/Mus_musculus.GRCm38.82.gtf --sjdbOverhang 100
Oct 03 15:19:14 ..... Started STAR run
Oct 03 15:19:14 ... Starting to generate Genome files
Oct 03 15:21:45 ... starting to sort  Suffix Array. This may take a long time...
Oct 03 15:22:08 ... sorting Suffix Array chunks and saving them to disk...
Oct 03 15:50:55 ... loading chunks from disk, packing SA...
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

**Comment by alexdobin** [comment]
Hi @barkasn,

the ENSEMBL "toplevel" files contain patches and alternative haplotypes that you usually do not need for RNA-seq mapping, significantly increasing the genome size - this is what probably caused RAM overflow. Please use the "primary_assmebly" files instead.

Cheers
Alex
