### ISSUE TITLE
How is the primary alignment chosen for --outMultimapperOrder=Old_2.4? [question]

### ISSUE THREAD

**Issue by sjackman** [alexdobin/STAR#751]
Hi, Alex. How is the primary alignment chosen with `--outMultimapperOrder=Old_2.4` when the alignments have equal alignment score? Is a pseudo-random number generator (PRNG) involved, and if so, how is that PRNG seeded, and is it reseeded for each read? Could you please point me to the location in the code where the primary alignment is chosen?

Thank you!
Shaun

**Comment by sjackman** [comment]
The root cause of my issue in different results between two runs of STAR was due to `--outSAMmultNmax=-1` selecting a different primary alignment than `--outSAMmultNmax=10`, which was surprising behaviour to me. You can close this issue.

**Comment by alexdobin** [comment]
Hi Shaun,

the --outMultimapperOrder=Old_2.4 did not have randomization, so it should be exactly reproducible from run to run. I do not think it should be affected by --outSAMmultNmax=10 - could you tell me exactly what options you were using when you saw different primary alignments.

Thanks
Alex

**Comment by sjackman** [comment]
Hi, Alex. Here is the line of code that causes `--outSAMmultNmax=10` to yield a different primary alignment than `--outSAMmultNmax=-1`.
https://github.com/alexdobin/STAR/blob/a25e95534ea57a7872e90055f66b3ae17a09e913/source/ReadAlign_multMapSelect.cpp#L83

**Comment by alexdobin** [comment]
Hi Shaun,

thanks for pointing it out, I forgot about it. :)
The logic was that if we are limiting the number of output alignments to SAM, we should output the ones that have the highest score first - otherwise they will be lost in favor of lower score alignments. This still makes sense to me. :)

Cheers
Alex

**Comment by sjackman** [comment]
That does make sense to me as well. What's surprising is that `--outSAMmultNmax=999` produces a different primary alignment than `--outSAMmultNmax=-1`. It's fine to say that's a wont-fix issue. It was just unexpected and surprising.

**Comment by alexdobin** [comment]
Agree - this was not described anywhere, and I added it to the manual for now.

**Comment by sjackman** [comment]
Thanks!
