### ISSUE TITLE
No Chimeric.out.sam file out when using --chimOutType SepareteSAMold

### ISSUE THREAD

**Issue by jzj2035198** [alexdobin/STAR#752]
I am using STAR 2.7.2b. According to the manual, when STAR receives the parameter--chimOutType SepareteSAMold, it will out Chimeric.out.sam file, but in fact, only Chimeric.out.junction is generated. I hope you can fix it. Thanks

**Comment by BenLangmead** [comment]
Do you know when this will be available in an official release?  Asking for a project where we'd like to have this output, but are willing to rewind to 2.7.1a if the fix is not likely to arrive in an official release soon.

**Comment by alexdobin** [comment]
Hi Ben,

will push out 2.7.2c today.

Cheers
Alex

**Comment by alexdobin** [comment]
https://github.com/alexdobin/STAR/releases/tag/2.7.2c

**Comment by alexdobin** [comment]
Needed another patch - there was no header in Chimeric.out.sam:
https://github.com/alexdobin/STAR/releases/tag/2.7.2d

**Comment by nservant** [comment]
Hi Alex,
Any way to have the Chimeric.out.sam file generated with STAR 2.7.2b ?
I'm asking that for compatibility issue with STAR-fusion
https://github.com/STAR-Fusion/STAR-Fusion/wiki/STAR-Fusion-release-and-CTAT-Genome-Lib-Compatibility-Matrix
Thanks

**Comment by alexdobin** [comment]
Hi Nicolas,

I believe 2.7.2d (or even 2.7.3a) should work fine with STAR-Fusion v1.8.0.
The bugs fixed in 2.7.2d (vs 2.7.2b) were exactly to correct the Chimeric.out.sam output.

Cheers
Alex

**Comment by nservant** [comment]
Thanks Alex.
I was thinking about conda dependencies. I'm think that using STAR 2.7.3a and STARfusion 1.8.1 leads to conflicts.
```
  - bioconda::star=2.7.3a
  - bioconda::star-fusion=1.8.1
```
But don't worry, I'll find a way to pass through this ... waiting for the next conda release.
Thanks
