### ISSUE TITLE
cufflinks fails with STAR bam

### ISSUE THREAD

**Issue by Xiaofei-git** [alexdobin/STAR#753]
Dear Alex, 

I got error when I run cufflinks with STAR bam as below. 
I used merged bam from multiple samples, is the error related to read group?

It is Illumina’s stranded Tru-Seq, so I used "--library-type fr-firststrand" for downstream cufflinks assembly.

Do you have any ideas about the error? Thank you so much! 

Here is the STAR code that I used:

STAR --genomeDir star_index_2ndPass --readFilesIn ${ARRAYFILE}_1.fastq.gz ${ARRAYFILE}_2.fastq.gz --outSAMunmapped Within --outFilterType BySJout \
 --outSAMattributes All --chimSegmentMin 12 --chimSegmentReadGapMax 3 --outFilterMultimapNmax 20   --outFilterMismatchNmax 999   \
 --outFilterMismatchNoverReadLmax 0.04   --alignIntronMin 20   --alignIntronMax 1000000   --alignMatesGapMax 1000000   \
 --alignSJoverhangMin 8 --alignSJDBoverhangMin 1 --outSAMtype BAM SortedByCoordinate  --readFilesCommand zcat \
 --outFilterIntronMotifs RemoveNoncanonical --outFileNamePrefix atlas_${ARRAYFILE}_2ndPass_ \
 --clip5pNbases 0 --seedSearchStartLmax 50 --outSAMstrandField intronMotif --runThreadN 12 --genomeLoad LoadAndKeep --limitBAMsortRAM 30000000000

cufflinks ERROR:
........

0%^M> Processing Locus 1:656117-656268             [                         ]   0%cufflinks: biascorrection.cpp:667: int BiasCorrectionHelper::add_read_group(boost::shared_ptr<const ReadGroupProperties>): Assertion `eff_len > 0' failed.

/var/spool/p6444/bnbcompute22/job_scripts/62296749: line 27: 28318 Aborted                 (core dumped) cufflinks -p 12 -o ../../../assembly/cufflinks -g Sorghum.gff3 -M rRNA_mask.gff3 --library-type fr-firststrand -u atlas_merged.bam

**Comment by Xiaofei-git** [comment]
I got same error from cufflinks ever I used the bam from a single sample.

**Comment by alexdobin** [comment]
Hi @Xiaofei-git 

this option may help, please try to re-map with it:
--alignSoftClipAtReferenceEnds   No

Cheers
Alex

**Comment by Xiaofei-git** [comment]
> Hi @Xiaofei-git
> 
> this option may help, please try to re-map with it:
> --alignSoftClipAtReferenceEnds No
> 
> Cheers
> Alex

I will try and let you know, thanks a lot!

**Comment by Xiaofei-git** [comment]
> Hi @Xiaofei-git
> 
> this option may help, please try to re-map with it:
> --alignSoftClipAtReferenceEnds No
> 
> Cheers
> Alex

I re-mapped with this "--alignSoftClipAtReferenceEnds No", but still got that error with Cufflinks 2.2.1.
However, there was no error with Cufflinks 2.1.1, and the assembly was successfully completed no matter I used "--alignSoftClipAtReferenceEnds No" or not.

**Comment by alexdobin** [comment]
Hi Xiaofei

thanks for sharing your solution. I do not think Cufflinks is updated any longer, so there is no way to figure out what's going with its versions, and you would have to use whatever version works... :(

Cheers
Alex

**Comment by Xiaofei-git** [comment]
> Hi Xiaofei
> 
> thanks for sharing your solution. I do not think Cufflinks is updated any longer, so there is no way to figure out what's going with its versions, and you would have to use whatever version works... :(
> 
> Cheers
> Alex

Thanks a lot!
