### ISSUE TITLE
genomeGenerate Killed: 9

### ISSUE THREAD

**Issue by qin218** [alexdobin/STAR#754]
Hi there,

I am running the following code to generate genome indexes:

STAR --runMode genomeGenerate --genomeDir STARgenome --genomeFastaFiles Homo_sapiens.GRCh38.dna.toplevel.fa --sjdbGTFfile Homo_sapiens.GRCh38.98.gtf --sjdbOverhang 74

And I got the "Killed: 9" message after about 1h.
Any chance that anyone here knows what could be the problem?
Thanks,
Qin

**Comment by qin218** [comment]
Just to update, I tried to use 
Homo_sapiens.GRCh38.dna.primary_assembly.fa 
instead of 
Homo_sapiens.GRCh38.dna.toplevel.fa 

`STAR --runMode genomeGenerate --genomeDir STARgenome --genomeFastaFiles Homo_sapiens.GRCh38.dna.primary_assembly.fa --sjdbGTFfile Homo_sapiens.GRCh38.98.gtf --sjdbOverhang 74
Oct 07 10:10:18 ..... started STAR run
Oct 07 10:10:18 ... starting to generate Genome files
Oct 07 10:14:15 ... starting to sort Suffix Array. This may take a long time...
Oct 07 10:14:48 ... sorting Suffix Array chunks and saving them to disk...
 
Killed: 9
`
Got the "Killed :9" again after several hours.

**Comment by alexdobin** [comment]
Hi @qin218 

the primary_assembly is the right file to use, and it should fit into 32GB of RAM, but ideally you want to have at least a few Gigabytes more.
How much RAM do you have?

Cheers
Alex

**Comment by qin218** [comment]
Hi Alex, I have 16GB RAM now. I am at the "inserting junctions into the genome indices" step for 18 hours. Is this normal? The computer is still responsive. Thanks, Qin

**Comment by alexdobin** [comment]
To fit it into 16GB of RAM, please use
--genomeSAsparseD 3 --genomeSAindexNbases 12

**Comment by qin218** [comment]
It has been running for more than one day in total. Do you think it's worth just waiting or restart again with the above 2 options added?

**Comment by alexdobin** [comment]
Yes, definitely re-run it with these options. Default options will not work with RAM=16GB.

**Comment by qin218** [comment]
Thanks, Alex!

**Comment by alexdobin** [comment]
And also use --runThreadN = number of cores, it will speed up the calculation - should only take a few hours.

**Comment by qin218** [comment]
Hi Alex, I added --genomeSAsparseD 3 --genomeSAindexNbases 12 --runThreadN 2 to run the genome generation again, but at the "inserting junctions into the genome indices" step for 24 hours already. I guess 16Gb RAM is just not enough?

**Comment by alexdobin** [comment]
Hi Qin,

16GB should be enough with these parameters (and primary fasta). Could you please send me the Log.out file, and also a screenshot of the "top" command (sorted by memory i.e. with shift-M).

Thanks!
Alex

**Comment by Ariunaa5000** [comment]
Hi Alex, 

I am also having a similar issue where my STAR index is getting killed right after  sorting suffix array step. The following is what I have. Do you have any suggestion?

May 05 13:01:39 ..... started STAR run
May 05 13:01:39 ... starting to generate Genome files
May 05 13:02:55 ... starting to sort Suffix Array. This may take a long time...
May 05 13:03:26 ... sorting Suffix Array chunks and saving them to disk...
Making_indexes: line 15: 14158 Killed                  STAR --runThreadN 8 --ru                              nMode genomeGenerate --genomeDir /mydirectory --genomeFastaFiles A673_combined_fastq.1.fasta --sjdbGTFfile A673_combined_fastq1_lifted_cleaned_sort_name_filtered.gtf --sjdbOverhang 100

I can also provide you with the out file. 

Ariunaa

**Comment by alexdobin** [comment]
Hi Ariunaa

please send me the Log.out file.

Cheers
Alex

**Comment by Ariunaa5000** [comment]
Hi Alex, 

Thank you for your prompt reply. 

I can't attach the files here. So I will send you an email at your cshl address. Hope that is okay. 

Thanks so much for your help! 

Ariunaa

**Comment by alexdobin** [comment]
Hi Ariunaa

thanks for the files! 
Since you have a large number of scaffolds in the genome (~30k), please try to reduce --genomeChrBinNbits to log2(GenomeLength/NumberOfReferences), I think it's ~16 in your case.

Cheers
Alex

**Comment by primukh** [comment]
Hi Alex,

Here’s my log.out file:

**Comment by alexdobin** [comment]
Hi @primukh 

the file did not get attached, you need to do it on the website.

Cheers
Alex

**Comment by primukh** [comment]
Hi! I am so sorry about the error. Somehow, it won't let me upload the text file. Hope you can view this pdf. 
Again, thanks for your help!

[Log.pdf](https://github.com/alexdobin/STAR/files/4589945/Log.pdf)

**Comment by Ariunaa5000** [comment]
Hi Alex, 

This might be a too basic question. How do I specify  --genomeChrBinNbits to 16? I have tried:
  
--genomeChrBinNbits16
--genomeChrBinNbits 16
--genomeChrBinNbits=16
--genomeChrBinNbits = 16
--genomeChrBinNbits log2(GenomeLength/NumberOfReferences)

It fails around the same time with everyone of these and still show  genomeChrBinNbits                 18 in the log file. 

I apologize. And I appreciate your help! 

Ariunaa

**Comment by alexdobin** [comment]
Hi @primukh,

you are using a very old STAR release, please switch to the latest one (2.7.3a).

Cheers
Alex

**Comment by primukh** [comment]
Thank you so much for your advice, Alex! It started working once I switched to using the recent release.


On May 9, 2020, at 7:39 PM, Alexander Dobin <notifications@github.com<mailto:notifications@github.com>> wrote:

This message was sent from a non-IU address. Please exercise caution when clicking links or opening attachments from external sources.



Hi @primukh<https://github.com/primukh>,

you are using a very old STAR release, please switch to the latest one (2.7.3a).

Cheers
Alex

**Comment by Ariunaa5000** [comment]
Hi Alex, 

I tried it again with hg19 to make STAR indexes. And it's failing at the same step. Any suggestion?

Ariunaa

**Comment by Ariunaa5000** [comment]
> Hi Alex,
> 
> This might be a too basic question. How do I specify --genomeChrBinNbits to 16? I have tried:
> 
> --genomeChrBinNbits16
> --genomeChrBinNbits 16
> --genomeChrBinNbits=16
> --genomeChrBinNbits = 16
> --genomeChrBinNbits log2(GenomeLength/NumberOfReferences)
> 
> It fails around the same time with everyone of these and still show genomeChrBinNbits 18 in the log file.
> 
> I apologize. And I appreciate your help!
> 
> Ariunaa

I think part worked just fine. I can see 

genomeChrBinNbits             12    

in the user defined parameters.

**Comment by Ariunaa5000** [comment]
> Hi Alex,
> 
> I tried it again with hg19 to make STAR indexes. And it's failing at the same step. Any suggestion?
> 
> Ariunaa
Figured it out. I was using a wrong command to run the jobs on our cluster. Thank you for your help! I will delete these comments soon not to confuse other people.

**Comment by DenisHedgehog** [comment]
Hello!
I have a similar problem. Upper solutions didn't work.
Attaching log.out file
Thanks
[Log.out.txt](https://github.com/alexdobin/STAR/files/5249859/Log.out.txt)

**Comment by Vita-github** [comment]
Hi @alexdobin ,

I am facing a similar problem as mentioned above. I am running STAR on Ubuntu VirtualBox with 12GM dedicated RAM.
I'm attaching the log file.
[log.out.pdf](https://github.com/alexdobin/STAR/files/5627596/log.out.pdf)

Thank you, Vita

**Comment by maximus3219** [comment]
I have also got similar problem. The program got killed after "generating suffix array index"
I have 32G RAM for my computer.
I am using STAR 2.7.7a version
Attached please find the log file.
Thank you.

[Log.out.txt](https://github.com/alexdobin/STAR/files/5802677/Log.out.txt)
