### ISSUE TITLE
GenomeGenerate uses only one thread

### ISSUE THREAD

**Issue by frymor** [alexdobin/STAR#756]
Im running STAR within a conda environment ( not that it matter, just for the sake of completeness).
When I uses this command:

`STAR --runThreadN 8 --runMode genomeGenerate --genomeDir data/starIndex/ --genomeFastaFiles data/genome.fa --sjdbGTFfile data/genome.gtf --sjdbOverhang 100`

it uses only one thread (based on the `htop` command).

**Comment by alexdobin** [comment]
Hi @frymor 

not all parts of genomeGenerate are parallelized, only the most intensive ones. After a few minutes after it starts - when it says "... sorting Suffix Array chunks and saving them to disk...", you should see multiple threads being used.

Cheers
Alex

**Comment by frymor** [comment]
thanks. I'll watch for it.
