### ISSUE TITLE
STAR genomeGenerate error

### ISSUE THREAD

**Issue by pustian** [alexdobin/STAR#759]
command:  nohup STAR --runMode genomeGenerate --genomeDir ./hg38_star/ --runThreadN 4 --genomeFastaFiles ./Homo_sapiens.GRCh38.dna.primary_assembly.fa --sjdbGTFfile ./Homo_sapiens.GRCh38.93.gtf &
result：EXITING because of FATAL problem while generating the suffix array
The number of indices read from chunks = 5891698126 is not equal to expected nSA=5891698134
SOLUTION: try to re-run suffix array generation, if it still does not work, report this problem to the author

**Comment by pustian** [comment]
I got 'Number of SA indices: 5891698126' at Log.out.  With the same data, I run the command, I got  'Number of SA indices: 5891698134'.

**Comment by alexdobin** [comment]
Hi @pustian 

please try one of the latest releases, 2.6.1d or 2.7.3a. If it does not work, please send me the Log.out file.

Cheers
Alex

**Comment by pustian** [comment]
I can't get ‘Number of SA indices: 5891698126' at Log.out while re-run--I re-download the data, maybe the data has something wrong. Now the error is the same with #244.    Thanks.

**Comment by alexdobin** [comment]
Hi @pustian 

please send me the Log.out file of the failing run.

Thanks!
Alex
