### ISSUE TITLE
Can I use quantmode to count intron read counts?

### ISSUE THREAD

**Issue by gongyuTang123** [alexdobin/STAR#764]
We are using STAR to analyze one of our FFPE sequencing results. 
The log.final.out file looks fine to me.
 Number of input reads |	47854398
                      Average input read length |	302
                                    UNIQUE READS:
                   Uniquely mapped reads number |	39489307
                        Uniquely mapped reads % |	82.52%
                          Average mapped length |	275.57
                       Number of splices: Total |	8306897
            Number of splices: Annotated (sjdb) |	8295443
                       Number of splices: GT/AG |	8189661
                       Number of splices: GC/AG |	103108
                       Number of splices: AT/AC |	7672
               Number of splices: Non-canonical |	6456
                      Mismatch rate per base, % |	0.96%
                         Deletion rate per base |	0.08%
                        Deletion average length |	2.08
                        Insertion rate per base |	0.02%
                       Insertion average length |	1.86
                             MULTI-MAPPING READS:
        Number of reads mapped to multiple loci |	6437295
             % of reads mapped to multiple loci |	13.45%
        Number of reads mapped to too many loci |	80368
             % of reads mapped to too many loci |	0.17%
                                  UNMAPPED READS:
       % of reads unmapped: too many mismatches |	0.65%
                 % of reads unmapped: too short |	2.88%
                     % of reads unmapped: other |	0.34%
                                  CHIMERIC READS:
                       Number of chimeric reads |	682136
                            % of chimeric reads |	1.43%

But when we use quantmode to count sequence aligned to transcriptomes. I notice a lot of sequences are considered noFeature. We guess because some parts of the sequence could be aligned to the intron. Is there any easy to check how many sequences have been to intron?

N_unmapped	5237738	5237738	5237738
N_multimapping	6437295	6437295	6437295
N_noFeature	26157323	32561020	32593864
N_ambiguous	1261456	400008	400931

**Comment by gongyuTang123** [comment]
Hi Alex,

I figure this out by using following command. 

--sjdbGTFfile *.gtf --sjdbGTFfeatureExon gene --sjdbGTFtagExonParentTranscript gene_id --sjdbGTFtagExonParentGene gene_name

And in this way, the no feature part is reduced to ~5%. But seems like the intron and exon parts are counted together. Is there any way to count intron and exon parts separately but at the same time?

Thanks,
Gongyu

**Comment by alexdobin** [comment]
Hi Gongyu,

this is not possible at the moment, though this feature is on my TODO list.
If you run it twice, you can subtract the standard (--sjdbGTFfeatureExon exon) results from the (--sjdbGTFfeatureExon gene) results to get purely intronic reads.

Cheers
Alex

**Comment by gongyuTang123** [comment]
Get it, thanks.
