### ISSUE TITLE
InputAlignmentsfromBAM not working in the latest release

### ISSUE THREAD

**Issue by zitoa** [alexdobin/STAR#770]
Hello Alex,

I have been using STAR in the past and now just installed the latest release. A few questions: I have tried to use the --runMode inputAlignmentsFromBAM but apparently it does not work:  'EXITING because of fatal INPUT ERROR: at the moment --runMode inputFromBAM only works with --outWigType bedGraph OR --bamRemoveDuplicatesType Identical'.
Is there a way to overcome this issue or do I need to convert back my BAM to fastq and then align with STAR?

Thank you,
Antonino

**Comment by alexdobin** [comment]
Hi Antonio,

the --runMode inputAlignmentsFromBAM option utilizes alignments from mapped BAM files.

If you need to re-map the BAM files (unsorted or sorted by name, does not matter if they are mapped or unmapped), you would need to specify
```--readFilesType SAM SE``` for single-end
or
```--readFilesType SAM PE``` for paired-end
and 
```--readFilesCommand samtools view   --readFilesIn File.bam```

Cheers
Alex

**Comment by zitoa** [comment]
Hi Alex,

thank you, I will test it shortly and will let you know if any issues.
Thank you for the inclusion of WASP pipeline for mapping bias correction. It will save tens of lines. 
I had a further question:
Does the WASP mode '--waspOutputMode SAMtag' require a '--varVCFfile file.vcf' containing only biallelic (SNPs) heterozygous variants segregating within the individual or, alternatively, both homozygous and heterozygous variants can be kept in the VCF file? I assume that, in both cases (but especially in the latter case) the vG ad vA SAM attributes (added by --outSAMattributes) will be of great help and would be highly recommended.

Cheers,
Antonino

**Comment by alexdobin** [comment]
Hi Antonio,

homozygous variants are simply ignored, and multiallelic SNPs are allowed, so you do not have to filter the VCF files.

Cheers
Alex

**Comment by zitoa** [comment]
Hi Alex, great thank you!
Cheers
Antonino

**Comment by riasc** [comment]
Hi @alexdobin, I would have to get back to this thread. I want to remaps reads that have been previously mapped by BWA-MEM2. However, when I start the mapping it stays forever in the state and won't continue..
```
..... reading from BAM, output wiggle
```
I'm calling STAR like this:
```
STAR --genomeDir /GRCh38/ --readFilesCommand samtools view --readFilesIn testsam.bam --readFilesType SAM SE --runMode inputAlignmentsFromBAM --outWigType bedGraph --outFileNamePrefix testsam_STAR --runThreadN 40
```

The BAMfile is pretty small.. about 100K entries. Am I missing something? Or is there a known bug when coming from BWA? I'm using 2.7.8a_2021-03-08

Thanks

**Comment by alexdobin** [comment]
Hi Richard,

if you want to *remap* reads from BAM, please omit ```--runMode inputAlignmentsFromBAM ``` option.
Also, you would want to ensure that each read is taken only once from the BAM file, i.e. no non-primary SAM lines are included with ```--readFilesCommand samtools view -F0x100``` .

Cheers
Alex

**Comment by riasc** [comment]
Hello Alex,
thank you very much for your fast answer. I have to bug you one last time. Now I'm getting the following:
```
samtools view: writing to standard output failed: Broken pipe
samtools view: error closing standard output: -1
```
What is the recommended samtools version to use with STAR? I'm on 1.11..

Thanks

**Comment by alexdobin** [comment]
Hi Richard,

the samtools version should not really matter, as long as it produces standard SAM.
Please send me the Log.out file.
Also, please try to run with SAM file as input: first create SAM file:
```
samtools view -F0x100 A.bam > A.sam
```
then run STAR without ```--readFilesCommand samtools view -F0x100```
```
STAR ... --readFilesIn A.sam --readFilesType SAM SE
```
Cheers
Alex

**Comment by riasc** [comment]
Hi Alex,
thanks again. Indeed, it works like a charm when I do this directly from SAM. I have these files as SAMs anyway. 
Maybe something went wrong with the conversion to BAM as it seems to work with another arbitrary BAM file.

Thanks
