### ISSUE TITLE
SJ.out.tab missing de novo junctions

### ISSUE THREAD

**Issue by luyoutao** [alexdobin/STAR#771]
Hi developer, thanks for developing STAR. 

I observed something odd and want to understand. I have three splicing junctions as shown below (only uniquely mapped reads are shown)

![Picture1](https://user-images.githubusercontent.com/29523868/67960997-7b7c6f80-fbd1-11e9-835d-5b7006d0f558.png)

In this region, SJ.out.tab spits out junction A, 
> chr11   5523468 5524238 1       1       1       152     0       75
> chr11   5523468 5524307 1       1       0       2       0       53
> chr11   5523468 5530181 1       1       0       1       0       39

and C
> chr11   5524385 5524684 1       1       1       215     3       74
> chr11   5524385 5524751 1       1       0       1       0       22
> chr11   5524385 5530181 1       1       0       3       0       35

but B (a non-canonical and unannotated one) is missing. Interestingly, in the figure you can see that there are at least two dozen reads spliced at B. That means, STAR has no problem finding spliced alignments but just fails to report in SJ.out.tab. 

I used default --outSJfilter* parameters. To make sure B is not filtered out by --outSJfilter*, I manually checked some reads and did not find any below --outSJfilter* thresholds. 

What is odd is that, if I extract one read pair from above figure and make three duplicates (in order to meet the --outSJfilterCountUniqueMin criterion), then align them only, STAR can output all the three junctions in SJ.out.tab:
> chr11   5523468 5524238 1       1       1       4       0       17
> chr11   5524278 5524303 0       0       0       4       0       39
> chr11   5524385 5524684 1       1       1       4       0       13

Note that chr11   5524278 is where junction B starts. 

So, do you have any clue for this puzzle? 

Thanks,

**Comment by alexdobin** [comment]
Hi @luyoutao 

your last experiment seems to point that the junction does not pass the --outSJfilterCountUniqueMin criterion. Have you tried --outSJfilterCountUniqueMin 1 1 1 1?
Maybe all the other reads are multimappers?
Please try to map with --outSAMattributes NH HI nM AS jI jM
which will add SAM tags with junction info to each read, and then extract the reads that contain this junction.

Cheers
Alex
