### ISSUE TITLE
outSAMtype

### ISSUE THREAD

**Issue by osmanwa** [alexdobin/STAR#775]
Hi, I am attempting to run star with the following parameters:

```'STAR' '--runMode alignReads' '--alignIntronMax' '1000000' '--alignIntronMin' '20' '--alignMatesGapMax' '1000000' '--alignSJDBoverhangMin' '1' '--alignSJoverhangMin' '8' '--chimJunctionOverhangMin' '15' '--genomeDir' '/cromwell_root/cromwell-execution/cwl_temp_file_424a0905-e88a-4fa4-b4a3-60ab9df7d8c4.cwl/424a0905-e88a-4fa4-b4a3-60ab9df7d8c4/call-Alignment/inputs/67843678/star' '--sjdbGTFfile' '/cromwell_root/cromwell-execution/cwl_temp_file_424a0905-e88a-4fa4-b4a3-60ab9df7d8c4.cwl/424a0905-e88a-4fa4-b4a3-60ab9df7d8c4/call-Alignment/inputs/-595689600/gencode.v31.annotation.gtf' '--limitOutSAMoneReadBytes' '90000000' '--outFilterIntronMotifs' 'RemoveNoncanonical' '--outFilterMismatchNmax' '10' '--outFilterMismatchNoverLmax' '0.1' '--outFilterMultimapNmax' '10' '--outFilterType' 'BySJout' '--outReadsUnmapped' 'Fastx' '--outSAMmapqUnique' '255' '--outSAMstrandField' 'intronMotif' '--outSAMtype' 'BAM SortedByCoordinate' '--outSAMmode' 'Full' '--sjdbOverhang' '99' '--readFilesCommand' 'zcat' '--runThreadN' '6' '--seedSearchStartLmax' '30' '--readFilesIn' '/cromwell_root/cromwell-execution/cwl_temp_file_424a0905-e88a-4fa4-b4a3-60ab9df7d8c4.cwl/424a0905-e88a-4fa4-b4a3-60ab9df7d8c4/call-Alignment/inputs/1454424683/RNA-T-01-01_S6_R1_001.fastq.gz' '/cromwell_root/cromwell-execution/cwl_temp_file_424a0905-e88a-4fa4-b4a3-60ab9df7d8c4.cwl/424a0905-e88a-4fa4-b4a3-60ab9df7d8c4/call-Alignment/inputs/1454424683/RNA-T-01-01_S6_R2_001.fastq.gz'```

But I keep getting this error no matter what permutation of the the `outSAMtype` I use:

```
EXITING because of fatal input ERROR: unknown value for the first word of outSAMtype: BAM SortedByCoordinate
SOLUTION: re-run STAR with one of the allowed values of outSAMtype: BAM or SAM

Nov 06 14:13:49 ...... FATAL ERROR, exiting

EXITING because of fatal input ERROR: unknown value for the first word of outSAMtype: BAM SortedByCoordinate
SOLUTION: re-run STAR with one of the allowed values of outSAMtype: BAM or SAM

Nov 06 14:13:49 ...... FATAL ERROR, exiting```

Can anyone tell me what I'm doing wrong here?

**Comment by ryan-williams** [comment]
seems like the `'--outSAMtype' 'BAM SortedByCoordinate'` is getting split into bash arguments incorrectly:
- `--outSAMtype`
- `BAM SortedByCoordinate`
as opposed to:
- `--outSAMtype`
- `BAM`
- `SortedByCoordinate`
fairly sure it's a problem upstream on our end @osmanwa; can close this

**Comment by alexdobin** [comment]
Thanks for sorting it out...
STAR never needs quotes in parameter values except if there is a space in the value string.
