### ISSUE TITLE
Setting number of junctions to 1 during DNA reads mapping

### ISSUE THREAD

**Issue by marapara** [alexdobin/STAR#778]
Hi Alex,

I was trying to map DNA reads (not RNA-seq reads) with --limitOutSJoneRead 1.
But I keep getting this error until I set the number of junctions back to its default of 1000:

EXITING because of fatal error: buffer size for SJ output is too small
Solution: increase input parameter --limitOutSJoneRead

I appreciate your suggestions regarding this issue.

**Comment by alexdobin** [comment]
Hi @marapara 

To prohibit splicing, please use 
--alignIntronMin 1
and do not use --limitOutSJoneRead (i.e. keep it default).

Also, when generating genome index, do not use annotations (GTF).

Cheers
Alex

**Comment by marapara** [comment]
Thanks, Alex.
That is very helpful!

**Comment by marapara** [comment]
Hi Alex,


Thanks a lot for your reply. I would have never thought of this.


Cheers,

Maria


________________________________

**Comment by ghuls** [comment]
@alexdobin Shouldn't it be: `--alignIntronMax 1` as `--alignIntronMax` should be higher than `--alignIntronMin` to disable splicing?

Also which other parameters are recommended?
```
# output one alignment per read to reduce SAM/BAM size
--outSAMmultNmax 1 

# for mapping DNA (unspliced)
--alignIntronMax 1 --winBinNbits 7    

# control scoring
--scoreGenomicLengthLog2scale 0 --scoreDelOpen 0 --scoreInsOpen 0 --scoreDelBase -1 --scoreInsBase -1

# multimappers
---outFilterMultimapNmax -1 -winAnchorMultimapNmax 3000 --seedPerReadNmax 30000 --alignWindowsPerReadNmax 30000 --seedPerWindowNmax 1000

# output filters
 --outFilterMatchNminOverLread 0 --outFilterScoreMinOverLread 0 --outFilterScoreMin 27
```
https://github.com/alexdobin/STAR/issues/701

**Comment by alexdobin** [comment]
Hi Gert,

you are right, my mistake, it should be --alignIntronMax 1.
Hopefully, it did not cause any serious issues.

Thanks!
Alex
