### ISSUE TITLE
strange segmentation fault error

### ISSUE THREAD

**Issue by daxue1** [alexdobin/STAR#78]
When I used 10 mouse sequences as reference, mapping was ok. However, when I used 10 human sequences as references, a segmentation fault error occurred. Human sequences are very similar to the mouse sequences in terms of length and seq names. If I replaced human seq names with mouse seq names, same error occurred. However, if I replaced human seq by mouse seq (keep names unchanged), NO error occurred. The FASTQ file (only 25 36-bp reads), human and mouse sequences, index script and mapping script are in [this link](https://www.dropbox.com/s/ab221oheuybrd11/rnaStar.test.zip?dl=0) (compressed, file size 2.5KB). Is this a bug? I used latest 2.4.2a. Thanks in advance.

**Comment by alexdobin** [comment]
Hi @daxue1 

this error is most likely the "small genome error" which should be corrected by reducing --genomeSAindexNbases. You used 7, but please try to go even lower. The problem is sequence dependent, so it may work fine for some small sequences but not for others.

Cheers
Alex
