### ISSUE TITLE
Very large temporary files and cryptic error

### ISSUE THREAD

**Issue by kriemo** [alexdobin/STAR#782]
First, thanks for all of your hard work on creating  (and maintaining) such a great tool. I have been using it for years.

Recently, I have had trouble aligning some RNA-seq libraries due to getting errors related to incorrect quality string and read lengths. However these errors are not reproducible, and  the quality scores and read sequences lengths in the fastqs are in fact the same. 

Here is an example error, included for reference for others:
```bash
EXITING because of FATAL ERROR in reads input: quality string length is not equal to sequence length
@HWI-ST382:111:D0P73ACXX:1:1205:9013:101193
CTCCATCTAAAACTAAATATAACCATGAGACCGATAGTAAACAAGTACCGTGAGGGAAAGTTGAAAAGAACTCTGAATAGAGAGTTAAACAGAGATCGGA
@@@FADDEGFHDHGGDGHGGIGHJGHJFHIIJJGEEIJIIJIIJEBBC>FFHIGGGGHFFFFGHFFFFDEEEECCCCCD@>CDD:>ADCCDACCDACAB?
SOLUTION: fix your fastq file
```

I eventually tracked down the issue to be related to a disk quota error due to running out of available disk space, which is surprising because I had at least a Tb of free space (STAR was on a large linux cluster). When running 4 concurrent STAR alignments on moderately sized fastqs (~5Gb compressed file sizes) I would see disk usage over a 1 Tb during the mapping stage, resulting in eventually exceeding my disk quota, and triggering the preceding error message. 

To reproduce this behavior I generated a smaller test dataset with 1 million paired end reads (from encode, can provide if needed, ~80Mb file sizes ) to reproduce this behavior. The reads were mapped to the drosophila genome (`BDGP6`) using multiple threads and requesting a sorted output bam file. 

```bash
~/bin/STAR-2.7.3a/bin/Linux_x86_64/STAR \
  --runThreadN 12 \
  --genomeDir $idx \
  --readFilesIn r1.fq.gz r2.fq.gz \
  --readFilesCommand gunzip -c \
  --outSAMtype BAM SortedByCoordinate \
  --outFileNamePrefix sorted/
```

During this run disk usage peaked at 98 Gb:

```bash
# results of running `du` on the output directory every 5 seconds
13:10:42	129M
13:10:47	72K
13:10:52	73K
13:10:57	73K
13:11:02	73K
13:11:07	73K
13:11:12	80K
13:11:17	80K
13:11:23	80K
13:11:28	80K
13:11:33	80K
13:11:39	80K
13:11:44	80K
13:11:49	80K
13:11:54	80K
13:12:00	80K
13:12:05	2.8G
13:12:10	23G
13:12:16	63G
13:12:21	44G
13:12:26	2.0G
13:12:31	512M
13:12:37	512M
13:12:42	512M
13:12:47	512M
13:12:52	512M
13:12:58	512M
13:13:03	6.7G
13:13:09	38G
13:13:14	98G
13:13:19	69G
13:13:24	19G
13:13:29	1.8G
13:13:34	287M
```

If instead I run STAR with `--outSAMtype BAM Unsorted` the disk usage is much lower:

```
~/bin/STAR-2.7.3a/bin/Linux_x86_64/STAR \
  --runThreadN 12 \
  --genomeDir $idx \
  --readFilesIn r1.fq.gz r2.fq.gz \
  --readFilesCommand gunzip -c \
  --outSAMtype BAM Unsorted \
  --outFileNamePrefix no_sort/

```` 

During this run disk usage peaked at only 1.6 Gb:

```bash
# results of running `du` on the output directory every 5 seconds
13:07:23	129M
13:07:28	72K
13:07:34	72K
13:07:39	72K
13:07:44	72K
13:07:49	74K
13:07:54	74K
13:07:59	74K
13:08:04	74K
13:08:09	74K
13:08:14	74K
13:08:19	74K
13:08:24	74K
13:08:29	74K
13:08:34	74K
13:08:39	1.6G
13:08:44	1.6G
13:08:49	1.6G
13:08:54	1.6G
13:08:59	1.6G
13:09:04	147M
13:09:09	147M
13:09:14	147M
13:09:19	147M
13:09:24	147M
13:09:29	147M
13:09:34	147M
13:09:39	1.6G
13:09:44	1.6G
13:09:49	1.6G
```

Is it expected for STAR to use a large amount of disk space for temporary files when sorting the output bam? 

Thanks!

Here are the logs from these runs:
[Sorted_Log.out.txt](https://github.com/alexdobin/STAR/files/3865992/Sorted_Log.out.txt)
[No_sort_Log.out.txt](https://github.com/alexdobin/STAR/files/3865995/No_sort_Log.out.txt)

**Comment by alexdobin** [comment]
Hi Kriemo,

these disk usage numbers look too high. Even for unsorted, 1.6GB BAM for 80MB is too much. Are there a lot of multimappers?
The sorted runs should use more disk space, as they store uncompressed temp files, but it should increase disk usage only by a factor of ~3.
Also. the large and fast fluctuations of RAM usage for the sorted case are weird. Is your filesystem network-attached? Have you tried to run these jobs using local disks?

Cheers
Alex

**Comment by kriemo** [comment]
Alex,
  Thanks for the quick response. I'm pretty sure that the filesystem is network attached. If I run the same test on a laptop, I don't see the disk usage spikes seen on the cluster. The final bam file size ends up being `264M` for the unsorted bam in both cases with 36.78% multi mapped reads. 

Disk usage for a local run using ` --outSAMtype BAM SortedByCoordinate` on MacOS with 6 threads

```bash
15:25:41	148K
15:25:46	148K
15:25:51	148K
15:25:56	148K
15:26:01	148K
15:26:06	148K
15:26:11	148K
15:26:16	148K
15:26:21	148K
15:26:26	 93M
15:26:31	340M
15:26:37	346M
15:26:42	346M
15:26:47	346M
15:26:52	346M
15:26:57	346M
15:27:02	346M
15:27:07	346M
15:27:12	346M
15:27:17	346M
15:27:22	349M
15:27:27	384M
15:27:32	544M
15:27:37	740M
15:27:42	742M
15:27:47	742M
15:27:52	742M
15:27:57	742M
15:28:02	742M
15:28:07	742M
15:28:12	743M
15:28:17	815M
15:28:22	884M
15:28:27	910M
15:28:32	913M
15:28:37	913M
15:28:42	913M
15:28:47	913M
15:28:52	918M
15:28:57	951M
15:29:02	280M
15:29:07	289M
15:29:12	289M
15:29:17	289M
```

I suspect that there must be some issue with the filesystem. Do you have any suggestions for any changes that I can make to avoid having these disk usage spikes? If not I can work around this issue on the cluster using samtools to sort the Unsorted bam output. 

Thanks,
Kent

**Comment by alexdobin** [comment]
Hi Kent,

the laptop disk usage numbers make sense. I am not sure why the other filesystem misbehaves... maybe the sysadmin can give you better advice. If the nodes on your cluster have local disks, the best approach is to write temp files locally, thus avoiding the NFS problems altogether - plus, it might make the execution faster. This can be done with --outTmpDir /path/to/temp/dir/ option. The queing system on the cluster should give you access to the local temp dir, e.g. for SGE this is env-variable $TMPDIR

Using samtools should work as well, though samtools also uses temp files.

Cheers
Alex

**Comment by kriemo** [comment]
Hi Alex,
  Thanks for the suggestions. Using the `--outTmpDir` option and setting it to a new directory name under `/tmp/` seems to have fixed the issue. 

disk usage on the cluster:
```bash
10:00:20	60K
10:00:25	60K
10:00:30	60K
10:00:35	60K
10:00:40	60K
10:00:45	60K
10:00:50	60K
10:00:55	60K
10:01:00	60K
10:01:05	60K
10:01:10	60K
10:01:15	142M
10:01:20	657M
10:01:25	851M
10:01:30	855M
10:01:35	855M
10:01:40	855M
10:01:45	855M
10:01:50	855M
10:01:55	855M
10:02:00	855M
10:02:05	855M
10:02:10	871M
10:02:15	939M
10:02:20	1.6G
10:02:25	947M
10:02:30	287M
```

Thanks!
Kent

**Comment by alexdobin** [comment]
Hi Kent

great - thanks for letting us know, it will help other users with similar problems.

Cheers
Alex
