### ISSUE TITLE
Test Data for STARsolo

### ISSUE THREAD

**Issue by mtekman** [alexdobin/STAR#784]
Hi there,
I'm trying to create small test data (<1MB per input) to run on STARsolo so that I can update the wrapper on Galaxy, but I am getting a few segfaults that I can't seem to get around unless I use whole datasets.

My naive approach was to take a BAM file that was output by STARsolo, and then subselect for a few detected genes and a few detected barcodes, and then running it on a genome.

But I keep getting weird segfaults, and gdb tells me that it occurs at the `SoloFeature::cellFiltering()` function.

I've included a Galaxy history with the input datasets:
https://usegalaxy.eu/u/mehmet-tekman/h/starsolo-informative-subset

and the commandline I run on `STAR v2.7.3a`

```
STAR --runThreadN 16 --genomeLoad NoSharedMemory 
 --genomeDir tempstargenomedir 
 --readFilesIn 
  inputs/subset_pbmc_1k_v3_S1_L001_R1_001.fastq.gz
  inputs/subset_pbmc_1k_v3_S1_L001_R2_001.fastq.gz
--readFilesCommand cat --soloType Droplet
--soloCBwhitelist inputs/3M-february-2018.txt
--soloBarcodeReadLength 0 --soloCBstart 1 --soloCBlen 16 --soloUMIstart 17 --soloUMIlen 10 --soloStrand Forward --soloFeatures Gene --soloUMIdedup 1MM_All
```

any info on this would be appreciated, or maybe some test data I can use?

**Comment by alexdobin** [comment]
Hi Mehmet,

I think the easiest way to create a test case would be to head first 1M reads from the two fastq files.

There are a couple of issues in the command above:
--readFilesIn should list cDNA read first, and Barcode read next, for 10X data this means Read2 first, Read1 second
--readFilesCommand should be zcat if the files are gzipped

Cheers
Alex

**Comment by mtekman** [comment]
Thanks Alex

The inputs were actually plain-text (despite the names), and for read input order I already tried both ways and it still segfaulted.

I did some more digging, and I think it simply has to do with the minimum number of detected barcodes STAR solo expects to see.

(***Note:*** You can skip the section below between the h-lines, I just wrote it up here in case it helps someone)

*****


Included in the shared history (https://usegalaxy.eu/u/mehmet-tekman/h/starsolo-genomegenerate-chr22) are the following datasets:

 * subset_pbmc_1k_v3_S1_L001_R1_001.fastq
 * subset_pbmc_1k_v3_S1_L001_R2_001.fastq
 * 3M-february-2018.txt
 * gencode.v32.primary_assembly.annotation.gtf
 * GRCh38.primary_assembly.genome.fa

The fasta and the GTF are downloaded straight from the GRCh38 Gencode website. The pbmc datasets are a few subsetted reads of a 10X dataset. The 3M-feb is the full set of barcodes from the CellRanger 3 pipeline.

**Subsetting the FASTA and GTF**

I removed all sequences and annotations except for those that were on chr22, to give the following two files:

 * gencode.v32.primary_assembly.annotation.chr22.gtf
 * GRCh38.primary_assembly.genome.chr22.fa

Then I generated STAR indices (v2.7.3a)

```
STAR
 --runMode genomeGenerate
 --genomeDir STAR22ONLY
 --genomeFastaFiles GRCh38.primary_assembly.genome.chr22.fa
 --sjdbOverhang 75
 --sjdbGTFfile gencode.v32.primary_assembly.annotation.chr22.gtf
 --genomeSAindexNbases 2
 --runThreadN 16
```

This ran fine.

**Subsetting the Barcodes**

I then took the 3M-february-2018.txt file and tried to reduce the file size from 111MB to something more usable, like 1MB, and this is where the segfauls started to occur.

The command I used for all runs is:

```
STAR
  --runThreadN 16
 --genomeLoad NoSharedMemory
 --genomeDir STAR22ONLY
 --readFilesIn subset_pbmc_1k_v3_S1_L001_R2_001.fastq\  
                     subset_pbmc_1k_v3_S1_L001_R1_001.fastq
 --readFilesCommand cat
 --soloType CB_UMI_Simple
 --soloCBwhitelist <BARCODE FILE>
 --soloBarcodeReadLength 0
 --soloCBstart 1 --soloCBlen 16 --soloUMIstart 17 --soloUMIlen 10
 --soloStrand Forward --soloFeatures Gene --soloUMIdedup 1MM_All
```
where I swapped `<BARCODE FILE>` with different subsets of barcodes.

The subsets were generated via:

`awk "NR%$NUM==1" < inputs/3M-february-2018.txt > inputs/3M-february-2018.sub$NUM.txt`

and I ran the above STAR command on the following where `NUM` was one of 10,20,30,40,50,100:

 * 3M-february-2018.sub100.txt (`segfaults`)
 * 3M-february-2018.sub50.txt (`segfaults`)
 * 3M-february-2018.sub40.txt (ran fine)
 * 3M-february-2018.sub30.txt (ran fine)
 * 3M-february-2018.sub20.txt (ran fine)
 * 3M-february-2018.sub10.txt (ran fine)

at this stage I thought it was just the *number* of barcodes, and that it needs at least (sub50) 130,000 barcodes for it to function. 

But then I tried:

```
awk "NR%50==43" < inputs/3M-february-2018.txt > inputs/3M-february-2018.sub50_43.txt
```

and this worked, which lead me to the idea that it was more to do with the amount of detected barcodes.

After a bit of trial and error, I settled on 600 barcodes that would not cause STAR to segfault:
 * subsetted.barcodes.txt

*****

**Subsetting the GTF and FASTA again**

Currently my read pairs and barcodes are under 1MB, but I have no idea how to reduce the genome  and GTF size.

I previously tried to use a transcriptome of the few genes detected in my output BAM file, but am I correct in assuming that STAR solo does not work with a transcriptome?

I take it that if I subset the genome, I will need to update the position of all features in the corresponding GTF?

**Comment by alexdobin** [comment]
Hi Mehmet,

I think the seg-faults you were observing happen when STAR did not detect any genic reads for the small subset of barcodes you put on your list. To avoid that, you can extract the cell barcodes from the subset of reads you are using (i.e. first 16b from Read2), sort|uniq it, and then grep for them from the original white-list.

STAR can map to the transcriptome, but you would need to create transcript sequence .fasta with chromosomes=transcript_id, and a special GTF with exon lines that have chromosomes=transcript_id, start=1, end=transcriptLength, transcript_id and gene_id from original GTF.
However, I generally do not recommend mapping scRNA-seq data against transcriptome only, so educationally it will be a bad example.

If you want to create a more realistic example, you could map the entire sample as usual with CR/UR tags output, sort the BAM file by coordinate, and then extract only reads that map to a few kilobases region, that contains a few genes. 10X has bamtofastq tool, I believe, that can convert these BAMs to FASTQ.

Cheers
Alex

**Comment by bgruening** [comment]
@alexdobin thanks for your help here. The segfault is new only in the very recent release, and I think in any case it should not segfault is should return an error message that we could catch, right?

Which test data are you using? Maybe its worth to share this as well, so downstream integrations could reuse that?

Thanks again!

**Comment by alexdobin** [comment]
Hi @bgruening @mtekman 

I had already fixed the problem I am suspecting was causing this crash, you can try the develop branch:
https://github.com/alexdobin/STAR/tree/develop

The seg-fault only occurred if no cells matching whitelist were detected, which should not happen with real datasets.

Cheers
Alex

**Comment by mtekman** [comment]
Excellent! I will test and close the issue on success!
