### ISSUE TITLE
different motifs for the same junction while collapsing junctions

### ISSUE THREAD

**Issue by xc611** [alexdobin/STAR#786]
Hi, 

I tried star 2.6.1d and 2.7.0f with newly built mm10 index, both versions gave me this error,but only for this sample, other 10 samples run fine.

Please help.

Jack

STAR/2.6.1d/bin/STAR --genomeDir RefGenomes/mm10_all/RSEM/mm10_genM9_star_rsem_overhang125 --outSAMunmapped Within --outFilterType BySJout --outFilterMultimapNmax 20 --outFilterMismatchNmax 999  --outFilterMismatchNoverLmax 0.04  --alignIntronMin 20  --alignIntronMax 1000000  --alignMatesGapMax 1000000  --alignSJoverhangMin 8  --alignSJDBoverhangMin 1  --sjdbScore 1 --readFilesCommand zcat --readFilesIn Sample_10_RoKO1/10_RoKO1_trimmed_R1.fastq.gz Sample_10_RoKO1/10_RoKO1_trimmed_R2.fastq.gz --outFileNamePrefix Sample_10_RoKO1/10_RoKO1_1p_ --runThreadN 8 --outFilterMatchNminOverLread 0.66 --outSAMtype BAM Unsorted --quantMode TranscriptomeSAM --peOverlapNbasesMin 10 --alignEndsProtrude 10 ConcordantPair
Nov 26 21:42:46 ..... started STAR run
Nov 26 21:42:46 ..... loading genome
Nov 26 21:47:51 ..... started mapping

EXITING becaues of BUG: different motifs for the same junction while collapsing junctions
chr7 6258631 6259338 1 0 1 -3

Nov 26 22:55:46 ...... FATAL ERROR, exiting

**Comment by alexdobin** [comment]
Hi Jack

how did you build the index for STAR?

Cheers
Alex

**Comment by chenv3** [comment]
Hi Alex,

I recently had also run into this bug while analyzing a sample against a hg38 reference. As a very quick summary of what I saw, I ran into the same error while running STAR 2.7.0f and 2.7.5b on a human sample. I did not have the same error when using STAR 2.5.4b. The error went away (for 2.7.0f I haven't tried 2.7.5b yet) when I removed the `peOverlapNbasesMin` parameter.

For a longer description of what I have done, please continue reading.

I first tried running both STAR 2.7.0f and 2.7.5b. The command I used was the same for both, just swapping out for the STAR version with its appropriate reference.

```
STAR/2.7.0f/bin/STAR --genomeDir STAR/2.7.0f/genes-150 --outSAMunmapped Within --outFilterType BySJout \
--outFilterMultimapNmax 20 --outFilterMismatchNmax 999  --outFilterMismatchNoverLmax 0.04  --alignIntronMin 20 \
--alignIntronMax 1000000  --alignMatesGapMax 1000000  --alignSJoverhangMin 8  --alignSJDBoverhangMin 1  \
--sjdbScore 1 --readFilesCommand zcat --readFilesIn Sample_95_62731_Baseline/95_62731_Baseline_trimmed_R1.fastq.gz \
Sample_95_62731_Baseline/95_62731_Baseline_trimmed_R2.fastq.gz --outFileNamePrefix \
Sample_95_62731_Baseline/95_62731_Baseline_1p_ --runThreadN 8 --outFilterMatchNminOverLread 0.66 \
--outSAMtype BAM Unsorted --quantMode TranscriptomeSAM --peOverlapNbasesMin 10 \
--alignEndsProtrude 10 ConcordantPair
Aug 05 16:45:09 ..... started STAR run
Aug 05 16:45:09 ..... loading genome
Aug 05 16:45:30 ..... started mapping

EXITING becaues of BUG: different motifs for the same junction while collapsing junctions
chr11 1922892 1923048 1 0 1 -3

Aug 05 17:03:08 ...... FATAL ERROR, exiting
```

I had a separate index for each version with the following command:
`STAR --runThreadN 16 --runMode genomeGenerate --genomeDir ./genes-150 --genomeFastaFiles ./ref.fa --sjdbGTFfile ./genes.gtf --sjdbOverhang 149 --outTmpDir tmp_150`
This command was also used for creating an index for 2.5.4b that I used for my next set of testing.

Running the sample using STAR 2.5.4b worked. I also had to remove the `peOverlpNbasesMin` parameter. And so the command used was:
`STAR-2.5.4b/STAR --genomeDir STAR/2.5.4b/genes-150 --outSAMunmapped Within --outFilterType BySJout --outFilterMultimapNmax 20 --outFilterMismatchNmax 999  --outFilterMismatchNoverLmax 0.04  --alignIntronMin 20  --alignIntronMax 1000000  --alignMatesGapMax 1000000  --alignSJoverhangMin 8  --alignSJDBoverhangMin 1  --sjdbScore 1 --readFilesCommand zcat --readFilesIn Sample_95_62731_Baseline/95_62731_Baseline_trimmed_R1.fastq.gz Sample_95_62731_Baseline/95_62731_Baseline_trimmed_R2.fastq.gz --outFileNamePrefix Sample_95_62731_Baseline/95_62731_Baseline_1p_ --runThreadN 8 --outFilterMatchNminOverLread 0.66 --outSAMtype BAM Unsorted --quantMode TranscriptomeSAM --alignEndsProtrude 10 ConcordantPair`
```
Aug 06 14:38:52 ..... started STAR run
Aug 06 14:38:52 ..... loading genome
Aug 06 14:39:26 ..... started mapping
Aug 06 15:55:54 ..... finished successfully
```

When I then reran the sample using 2.7.0f while removing the `peOverlpNbasesMin` parameter, I no longer ran into that issue:
```
STAR/2.7.0f/bin/STAR --genomeDir STAR/2.7.0f/genes-150 --outSAMunmapped Within --outFilterType BySJout \
--outFilterMultimapNmax 20 --outFilterMismatchNmax 999  --outFilterMismatchNoverLmax 0.04  --alignIntronMin 20 \
--alignIntronMax 1000000  --alignMatesGapMax 1000000  --alignSJoverhangMin 8  --alignSJDBoverhangMin 1  \
--sjdbScore 1 --readFilesCommand zcat --readFilesIn Sample_95_62731_Baseline/95_62731_Baseline_trimmed_R1.fastq.gz \
Sample_95_62731_Baseline/95_62731_Baseline_trimmed_R2.fastq.gz --outFileNamePrefix \
Sample_95_62731_Baseline/95_62731_Baseline_1p_ --runThreadN 8 --outFilterMatchNminOverLread 0.66 \
--outSAMtype BAM Unsorted --quantMode TranscriptomeSAM --alignEndsProtrude 10 ConcordantPair
Aug 06 16:54:08 ..... started STAR run
Aug 06 16:54:08 ..... loading genome
Aug 06 16:54:43 ..... started mapping
Aug 06 18:21:11 ..... finished mapping
Aug 06 18:21:11 ..... finished successfully
```

Thanks

**Comment by alexdobin** [comment]
Hi @chenv3 

I had never been able to trace this BUG, but this is the first time where it's dependent on `--peOverlapNbasesMin`.
I would need to reproduce it - would you be able to share the FASTQs and the genome FASTA/GTF?

Thanks!
Alex

**Comment by chenv3** [comment]
Hi Alex

Sure, I would be able to share those files. I do most of my sharing of FASTQs and the like through Globus. I was wondering if I could just send you a globus link.

Thanks

**Comment by alexdobin** [comment]
Hi @chenv3 

I have not used Globus before, not sure how it works. If I can get links to download the files, it should be fine.
Alternatively, you can upload the files here:
https://dropfiles.cshl.edu/requests/uSo3OtdIMA6Yd0Zt1UQUhj

Thanks!
Alex

**Comment by chenv3** [comment]
Hi Alex,

It took me a few tries, but I believe I finally sent the files. Please let me know if there is anything missing.

Thanks

**Comment by alexdobin** [comment]
Hi Vicky,

sorry about the belayed reply, here is another link for downloads:
https://dropfiles.cshl.edu/requests/RJkFjkFiF9L8QdlrHHfb5e

Thanks a lot!
Alex

**Comment by chenv3** [comment]
Hi Alex,

The file should be sent. Hopefully it worked better this time.

Thanks,
Vicky

**Comment by alexdobin** [comment]
Hi Vicky.

thanks a lot, I got the file. Let's hope now that I can reproduce the error.

Cheers
Alex

**Comment by alexdobin** [comment]
Hi Vicky,

I reproduced the error and should be able to debug it now.
Thanks a lot again for your help with test files!

Cheers
Alex

**Comment by alexdobin** [comment]
Hi Vicky,

I apologize again - before I got to fix the bug, I have lost the first files you sent me due to RAID failure on my server
I still have the R1 file on dropfiles, but the first request expired, unfortunately.
Would you be able to resend those files ```test_trimmed_R2.fastq.gz, ref.fasta, ref.gtf```:
https://dropfiles.cshl.edu/requests/L6LD9gYPIihMLQ5pL7NZ7V

Very sorry for the trouble,
Alex

**Comment by chenv3** [comment]
Hi Alex,

I have sent the files again using the link you've provided. Please let me know if there are any problems with this latest transfer.

Thanks,
Vicky

**Comment by alexdobin** [comment]
Hi Vicky,

many thanks, got the files, and started to debug.

Cheers
Alex

**Comment by alexdobin** [comment]
Hi Vicky,

I believe I fixed this bug, now it runs without any issues on your data
Please try the 2.7.6a release.
Thanks a lot for supplying the test files!

Cheers
Alex

**Comment by chenv3** [comment]
Hi Alex,

Sorry, it's been a while, but when I tested the new release on what I have, I didn't run into an issues. 

Thanks,
Vicky

**Comment by alexdobin** [comment]
Hi Vicky,

great, thanks a lot for checking it and for help with testing!

Cheers
Alex
