### ISSUE TITLE
Core Dump with DNA alignment

### ISSUE THREAD

**Issue by jasper1918** [alexdobin/STAR#79]
Hi Alex,

I have been working with STAR Chimeric output as one component of a DNA breakpoint pipeline I have been developing. The results have been quite good and we are getting excellent sensitivity/specificity against a set of known samples.

I have a handful of samples though that will always lead to a core dump by STAR even when run with minimal parameters as follows:

STAR.2.4.1d --readFilesIn Sample_1.fastq.gz Sample_2.fastq.gz  --genomeDir path/STAR_Human --runThreadN 8 --readFilesCommand zcat --chimOutType SeparateSAMold --chimSegmentMin 20  --outFileNamePrefix  sample. --alignIntronMax 1

I have done some minimal debugging with GDB and found the error to trace to stitchWindowAligns.cpp:295 and one step back to stitchWindowAligns.cpp:348. 

Any ideas of what is going on here or of any specific parameter usage that might alleviate the problem?

I have the log files if you want them.

Cheers,

Jeff

**Comment by alexdobin** [comment]
Hi Jeff,

could you send me a minimalist read set that replicates this problem?
One of the ways to do it is as follows. If you are debugging, and frame into a function that belongs to ReadAlign::, you can print the readName variable - the name of the read where the error occurred.
Then you can extract this read from FASTQs and check that the error is still happening.

I would also need a link to the genome fasta.

Cheers
Alex

**Comment by jasper1918** [comment]
I was able to trace the error to a particular read and recreate the error. Files and info have been emailed. 

Thanks!

**Comment by alexdobin** [comment]
Fixed in the latest master.
