### ISSUE TITLE
outSAMattributes CR and CY without STARsolo

### ISSUE THREAD

**Issue by jvikkula** [alexdobin/STAR#790]
Hi,

Is it possible to use CR and CY tags, without using STARsolo (i.e. to get the cell barcode to the bam file, but not to perform counting)?

I am currently running this command (STAR version 2.7.3a):

```
STAR \
        --runThreadN 12\
        --genomeDir genome_dir \
        --genomeLoad LoadAndRemove \
        --readFilesCommand gunzip -c \
        --readFilesIn sample_1.fastq.gz sample_2.fastq.gz \
        --outFileNamePrefix sample \
        --outSAMtype BAM Unsorted \
        --outSAMattributes NH HI AS nM CR CY
```

But this is giving me a following error:

`
EXITING because of FATAL INPUT ERROR: --outSAMattributes contains CR/CY/UR/UY/CB/UB tags, but --soloType is not set
SOLUTION: re-run STAR without these attribures, or with --soloType set
`

What is the correct way to get the cell barcodes to the bam file?

Thanks,
Johanna

**Comment by alexdobin** [comment]
Hi Johanna,

it is not possible to completely switch off counting at the moment, but you can minimize by creating a file (say WL.txt) with just one faux barcode sequence (same length as your actual barcodes) and using these prameters:
`
--soloType Droplet --soloCBwhitelist WL.txt --soloFeatures Gene GN --soloCellFilter None 
--outSAMattributes NH HI CR UR GX --outSAMtype BAM Unsorted 
`

Cheers
Alex

**Comment by jvikkula** [comment]
Hi Alex, 

Thanks for your answer!

Does this require that the data is droplet based? 

(I'm not able to get this work yet, but I believe now that the problem is in my fastq files so that they are not properly formatted...)

-Johanna

**Comment by alexdobin** [comment]
Hi Johanna,

it does not have to be droplet, but it needs to have the CB/UMI in one read, and cDNA in the other read. Then you need to specify the following options to match your barcoding scheme.

Cheers
Alex
```
soloCBstart                 1
    int>0: cell barcode start base

soloCBlen                   16
    int>0: cell barcode length

soloUMIstart                17
    int>0: UMI start base

soloUMIlen                  10
    int>0: UMI length

soloBarcodeReadLength       1
    int: length of the barcode read
                            1   ... equal to sum of soloCBlen+soloUMIlen
                            0   ... not defined, do not check
```

**Comment by alexdobin** [comment]
Hi Johanna,

it does not have to be "droplet"-based, the only requirement is that the barcode (CB+UMI) is on a separate read.

Cheers
Alex
