### ISSUE TITLE
High percentage of unmapped reads - too short (~40-55%) perhaps resulting in low read counts for genes that showed high expression when mapped using GSNAP – recommendations for troubleshooting?

### ISSUE THREAD

**Issue by apfuentes** [alexdobin/STAR#793]
Hi,
Thanks a lot for developing such great tool and for assisting questions of its users. 

I encountered the issue of having about 50% of the reads unmapped - too short, when using STAR with default parameters:

![image](https://user-images.githubusercontent.com/19496177/71038967-57de9b80-2123-11ea-9ff5-b4ac1ab38c70.png)
 
**Data:** Single-end 50 bp RNA-seq data of 16 samples of a fish species with reference genome. I inherited this data from a former graduate student who used GSNAP for read mapping instead of STAR. He found highly expressed genes which I don’t find as such. Thus, I wanted to discard that the low read counts I found are not due to the low read mapping obtained with STAR.

I run STAR as part of a pipeline implemented in Nextflow. Below is the code used for generating the index:
```
STAR --runMode genomeGenerate \
--runThreadN ${task.cpus} \
--sjdbGTFfile $gtf \
--genomeDir star/ \
--genomeFastaFiles $fasta
```
Code used for read mapping with STAR:
```
STAR --genomeDir $index \
--sjdbGTFfile $gtf \
--readFilesIn $reads \
--runThreadN ${task.cpus} \
--twopassMode Basic \
--outWigType bedGraph \
--outSAMtype BAM SortedByCoordinate $avail_mem \
--readFilesCommand zcat \
--runDirPerm All_RWX $unaligned \
--outFileNamePrefix $prefix $seq_center

samtools index ${prefix}Aligned.sortedByCoord.out.bam
```
I read all the similar posts I found published in Github and in Google groups. The most frequent recommendations you provided were to examine:

1. Unordered paired-end reads in the fastq files (after trimming)
2. Poor sequencing quality
3. Contamination with primer-dimers (clip off Illumina adapters)
4. Contamination from other species, or sample divergence from the reference genome
5. rRNA contamination:
    - library prep.
    - non-chromosomal scaffolds excluded from the genome generation

I assessed each of these points for my data, which I discuss below:

1. Discarded, all my data is single-end.
2. Discarded, sequence quality is high for all samples and along the reads.

![image](https://user-images.githubusercontent.com/19496177/71039002-6cbb2f00-2123-11ea-8be8-87c16c420e2a.png)
![image](https://user-images.githubusercontent.com/19496177/71039018-7349a680-2123-11ea-8531-4752d6096783.png)

3. Discarded, performed read trimming with Trimmomatic (also applied filter of minimum read length of 36 bp, thus reads length distribution ranges from 36 to 50bp):

- Reads before trimming
![image](https://user-images.githubusercontent.com/19496177/71039040-7fcdff00-2123-11ea-8330-922cb2a2bd8d.png)

- Reads after trimming
![image](https://user-images.githubusercontent.com/19496177/71039053-85c3e000-2123-11ea-87e7-17c7ce2c490f.png)
  
4. As I am using the reference genome of the species, I wouldn’t expect too high sample divergence respect to it.

I run BLAST for a few unmapped reads and found that some of them have high sequence similarity with mtDNA of the study species:
 
![image](https://user-images.githubusercontent.com/19496177/71039071-92e0cf00-2123-11ea-9cf0-4f2f44644ed7.png)

![image](https://user-images.githubusercontent.com/19496177/71039083-95dbbf80-2123-11ea-8fec-6e03c33ba81d.png)

![image](https://user-images.githubusercontent.com/19496177/71039093-9bd1a080-2123-11ea-9d96-88bae80754d7.png)

with mtDNA of other fish species
 
![image](https://user-images.githubusercontent.com/19496177/71039101-a2601800-2123-11ea-886e-abcedededf94.png)

Mouse?
![image](https://user-images.githubusercontent.com/19496177/71039106-a5f39f00-2123-11ea-8732-e7fb4a417a3c.png)

5. Library preparation included poli-A selection, for which I’d expect rRNA should be inexistent or low…

Since none of these 5 factors seem to be strongly affecting the quality of the RNA-seq data, I decided to perform some tests of STAR parameters. From the numerous posts on this regard, I tested (for two samples – Ber and HAR - with ~50% of unmapped reads too short):

Three minimum read lengths:
- Untrimmed reads: minimum read length = 50 bp
- Trimmed reads, minimum read length set to 36 bp
- Trimmed reads, minimum read length set to 30 bp

Four mapping parameters (changed one at a time):
- **Default**
- **0-0-20**: `--outFilterScoreMinOverLread 0 --outFilterMatchNminOverLread 0 --outFilterMatchNmin 20`, to allow alignments with 20 or more bases matches.
- **0-0-30**: `--outFilterScoreMinOverLread 0 --outFilterMatchNminOverLread 0 --outFilterMatchNmin 30`, to allow alignments with 30 or more bases matches.
- **100k-10**: Set max and min intron length: `--alignIntronMin 10`and `--alignIntronMax 100,000` (for comparison, defaults set to : --alignIntronMin 20, --alignIntronMax 1,000,000)

The results of these tests are summarized in the plot below. Each row corresponds to some of the main mapping statistics generated by STAR (% Uniquely mapped reads, % Reads unmapped – too short, % Mismatch rate per base, % reads mapped to multiple loci). Note that the plot is vertically divided in two, left (for sample Ber) and right (for sample HAS):

![Screenshot 2019-12-17 at 18 02 16 (2)](https://user-images.githubusercontent.com/19496177/71039722-1e0e9480-2125-11ea-9aa1-138cef1ff9c7.png)

**Some conclusions from these tests:**
- Read trimming does not seem to significantly affect overall mapping stats
- Setting minimum alignment length to 20 bp (star-0-0-20) does increase the % of uniquely mapped reads and reduce % of unmapped reads too short, but with the tradeoff of increasing the % of mismatch rate per base and of reads mapped to multiple loci
- Setting minimum alignment length to 30 bp (star-0-0-30) has an intermediate effect to the previous test
- Setting the max and min intron length to `--alignIntronMin 10` and `--alignIntronMax 100,000`, respectively, offered similar results as using default parameters

From a conservative point of view, I’d choose the default parameters because the % of mismatch rate per base and of read mapped to multiple loci is low respect to the other two tests, but this does not solve the issue of high % of unmapped reads – too short. 

**What else should be tested?**
After reading your publication entitled "Optimizing RNA-Seq Mapping with STAR", I wonder what other tests should be performed, for example:

- Generate a new index but modifying `--sjdbOverhang` to max(ReadLength)-1 = 49
  - It is recommended that `--sjdbOverhang > --seedSearchStartLmax`. Thus, should I set `--seedSearchStartLmax` to 48?

- Change maximum and minimum intron sizes (`--alignIntronMin`  and `--alignIntronMax`) to values obtained from the correspondent GTF file to the genome assembly

- Modify mismatches parameters `--outFilterMismatchNmax`    (=10 by default), `--outFilterMismatchNoverLmax` (=0.3 by default), `--outFilterMismatchNoverReadLmax` (=1 by default).
   - Not sure which value ranges should be tested accounting for instance for SNPs, any recommendations?

- Since the reads are too short (36 to 50 bp long), should an end-to-end alignment be preferable, using`--alignEndsType EndToEnd`?

**Remaining questions:**
- Would these be appropriate parameters to test, or what others?
- How to know which parameter combination is the best?
- Is there any why to make STAR mapping aware of a known dataset of SNPs? Perhaps this could help to adjust mismatch penalties...

Thanks in advance for any help!

Angela

**Comment by alexdobin** [comment]
Hi Angela,

very thorough investigation!
Do most of the unmapped reads map well to mitochondrion RNA?
Also, for the mapped reads, what % maps to the mitochondrion genome?
One possibility is that your samples have a large proportion of mitochondrion RNA, the mitochondrion genome included in the reference is not matching well with your samples.
This would also explain the error rate that's on the high side - 1% even with default parameters.

How many homo/hetero-zygous SNPs do you have - divided by the genome length? If it's >0.1, it would be helpful to replace the homozygous SNPs in the genome, and also consider mappingto a diploid genome.

Cheers
Alex

**Comment by apfuentes** [comment]
Hi Alex,
Thanks a lot for your recommendations and prompt response.

Actually, the reference genome I first used for read mapping only included chromosomes. Thus, I repeated read mapping using:
- A reference genome including chromosomes, unplaced scaffolds, and the mitochondrial genome
- Included the flag `--sjdbOverhang 49` (ReadLength - 1) for index generation and running

I am glad to share that these two changes considerably improved the  % of uniquely mapped reads (from ~50% to ~80% !!):
```
cat *Log.final.out | grep "Uniquely mapped reads %"
                        Uniquely mapped reads % |	86.82%
                        Uniquely mapped reads % |	87.91%
                        Uniquely mapped reads % |	88.47%
                        Uniquely mapped reads % |	83.03%
                        Uniquely mapped reads % |	87.53%
                        Uniquely mapped reads % |	77.59%
                        Uniquely mapped reads % |	78.92%
                        Uniquely mapped reads % |	87.11%
                        Uniquely mapped reads % |	86.47%
                        Uniquely mapped reads % |	86.46%
                        Uniquely mapped reads % |	73.47%
                        Uniquely mapped reads % |	86.17%
                        Uniquely mapped reads % |	85.62%
                        Uniquely mapped reads % |	84.83%
                        Uniquely mapped reads % |	86.34%
                        Uniquely mapped reads % |	84.35%
```
The mismatch rate stayed the same though, around 1.4% for all samples:
```
cat *Log.final.out | grep "Mismatch rate per base, %"
                      Mismatch rate per base, % |	1.42%
                      Mismatch rate per base, % |	1.39%
                      Mismatch rate per base, % |	1.42%
                      Mismatch rate per base, % |	1.46%
                      Mismatch rate per base, % |	1.44%
                      Mismatch rate per base, % |	1.44%
                      Mismatch rate per base, % |	1.46%
                      Mismatch rate per base, % |	1.37%
                      Mismatch rate per base, % |	1.39%
                      Mismatch rate per base, % |	1.39%
                      Mismatch rate per base, % |	1.46%
                      Mismatch rate per base, % |	1.40%
                      Mismatch rate per base, % |	1.42%
                      Mismatch rate per base, % |	1.42%
                      Mismatch rate per base, % |	1.37%
                      Mismatch rate per base, % |	1.41%
```
In your previous message recommended "to replace the homozygous SNPs in the genome, and also consider mapping to a diploid genome". The reference genome I have access to is haploid, so I am not sure how to map reads against a haploid genome. 

I am pretty happy with the new results but was wondering if you consider pertinent to continue exploring the possibility of reducing the mismatch rate % (for differential gene expression analysis).

Thanks,
Angela

**Comment by alexdobin** [comment]
Hi Angela,

I think that your mapping % looks good for standard downstream analyses (quantification, DE etc).
If you have phased variants for your individual, you could venture into creating a "personal" genome (say with AlleleSeq), however, this would require more elaborate downstream pipeline as you will have alignments in the diploid coordinate.

If you have just species-specific unphased (non-personal) variants you can create a haploid genome with these variants (you can hack AlleleSeq for that as well).

Both of these should reduce the mismatch rate and further increase the mapping rate, and also make the mapping rate more accurate.

Cheers
Alex

**Comment by apfuentes** [comment]
Thanks a lot for the recommendations!
Best,

Angela

**Comment by George-Zhou02** [comment]
@apfuentes 
May I ask what species you sequenced? I have also found similar situations in some fish. Thank you very much！
