### ISSUE TITLE
Segfault when mapping to index from Azospirillum brasilense

### ISSUE THREAD

**Issue by tbooth** [alexdobin/STAR#795]
Hi,

I have a standard RNA pre-processing pipeline based on STAR that has been working well for a whole variety of genomes, including bacteria. But today I attempted to add the Azospirillum_brasilense genome to the collection of references and it results in a segfault whenever I try to map against the index.

I know STAR is not recommended for prokaryotes but the process has worked nicely with other bacterial genomes. I don't understand what is so different about this one.

I though it might be the same bug as #396 but the workaround suggested there does not help.

```
$ STAR-2.7.3a/bin/Linux_x86_64/STAR --runMode genomeGenerate --genomeDir star_AbAZ39_p1_crunch4.fa/ --genomeFastaFiles AbAZ39_p1_crunch4.fa --genomeSAindexNbases 9 --genomeChrBinNbits 16
$ STAR-2.7.3a/bin/Linux_x86_64/STAR --genomeDir star_AbAZ39_p1_crunch4.fa/ --readFilesIn foo?.fastq --outFileNamePrefix startest --outSAMtype BAM Unsorted --outSAMunmapped Within
Dec 19 13:48:59 ..... started STAR run
Dec 19 13:48:59 ..... loading genome
Dec 19 13:48:59 ..... started mapping
Segmentation fault (core dumped)
```

Reference is at:
```
ftp://ftp.ensemblgenomes.org/pub/bacteria/release-45/fasta/bacteria_71_collection/azospirillum_brasilense/dna/Azospirillum_brasilense.ASM63247v2.dna.toplevel.fa.gz
```

The file **AbAZ39_p1_crunch4.fa** (attached) is just a section of the first chromosome from the reference with any degenerate bases switched to N's (as I though that might be an issue). If you delete just a few bases from the last line of this file and rebuild the index it then stops segfaulting. If I take any other chromosome from the reference and try to index it individually I get segfaults on all of those too.

The files foo1.fastq and foo2.fasta are just come random control reads as the reads used don't seem to matter.

Any ideas?

Many thanks.

**Comment by tbooth** [comment]
[AbAZ39_p1_crunch4.fa.gz](https://github.com/alexdobin/STAR/files/3984002/AbAZ39_p1_crunch4.fa.gz)

**Comment by alexdobin** [comment]
Hi Tim,

this is a small genome, and so you need to reduce 
`--genomeSAindexNbases as log2(GenomeSize)/2-1
`
In your case, it will be `--genomeSAindexNbases 10`
If you have a large proportion of Ns, you may need to make this value even smaller, until segfault disappears, as it is related to the k-mers content in the genome.

Cheers
Alex

**Comment by tbooth** [comment]
Hi Alex,

Many thanks for that. I was following the recommendation and using 10. Not understanding what the parameter did I'd tried increasing it but not decreasing it. A value of 8 seems to work nicely.

Cheers,

TIM

**Comment by alexdobin** [comment]
Hi Tim,

great - thanks for letting me know. 
I missed it that you already tried  --genomeSAindexNbases 9.
It's good that 8 worked in your case. At the moment, this value needs to be manually selected, unfortunately. I hope to fix it in the future.

Cheers
Alex
