### ISSUE TITLE
GeneFull mode and GX tag (STARsolo)

### ISSUE THREAD

**Issue by johnchamberlin** [alexdobin/STAR#796]
Does quantifying with GeneFull affect the output BAM file in any way? e.g. do intronic reads now get assigned a GX tag. Thanks,

**Comment by alexdobin** [comment]
Hi John,

GeneFull does not modify anything in the BAM file. The GX and GN tags will still refer only to reads that overlap exons, i.e. counted with Gene option.
I will implement a separate tag for the GeneFull gene overlap.

Cheers
Alex

**Comment by johnchamberlin** [comment]
Thanks for your continued efforts. I think that adding mapping statistics like intron, exon, intergenic, and even antisense would be very useful as well. JC

**Comment by seanken** [comment]
Hope all is well! Following up on this since I had a similar question--for GeneFull, has a new gene tag been added that includes reads overlapping introns? Haven't stumbled upon it in the documentation and wasn't anything super obvious glancing at the commits but just want to check I am not overlooking it. Thanks!

**Comment by alexdobin** [comment]
Hi Sean,

in the latest version (2.7.7a), if you use ```--soloFeatures GeneFull``` (and no ```Gene```), the GX/GN tags will mark genes that overlap full gene loci, exons and introns.

Cheers
Alex

**Comment by seanken** [comment]
Hey,

Thanks!

Best wishes,

Sean

**Comment by alexdobin** [comment]
Hi Sean,

I was testing this feature, and found a bug - even with ```--soloFeatures GeneFull``` the GX still contains information from ```Gene``` overlap (i.e. does not include intronic reads). I am fixing in in the next release, 2.7.8a.

Cheers
Alex

**Comment by alexdobin** [comment]
Hi Sean,

this issue was fixed in https://github.com/alexdobin/STAR/releases/tag/2.7.8a.

Cheers
Alex

**Comment by seanken** [comment]
Thanks! Excited to give it a try!
