### ISSUE TITLE
next index is smaller than previous

### ISSUE THREAD

**Issue by xiuru** [alexdobin/STAR#797]
Hi Alex,
This is my first time using STAR to analysis RNA-seq data and i am trying to build an index for maize genome. Fasta and gtf files were downloaded from Ensembl palnts. The code i used is :

`/home/xiuru/software/STAR-2.7.3a/bin/Linux_x86_64/STAR --runMode genomeGenerate --runThreadN 6 --genomeDir STARindex/ --genomeFastaFiles Zea_mays.B73_RefGen_v4.dna.toplevel.fa --sjdbGTFfile Zea_mays.B73_RefGen_v4.45.gtf`

I tried several times both on my desktop or HPC cluster, but i got the same error when build the index.  

> BUG: next index is smaller than previous, EXITING

Here is the Log.out file.
[Log.out.txt](https://github.com/alexdobin/STAR/files/3986516/Log.out.txt)

Could you please give me some advice to solve this problem?

Xiuru

**Comment by alexdobin** [comment]
Hi Xiuru,

I have run the genome generation on these files and could not reproduce the problem.
Please try it again, and make sure that you start with an empty directory, and no other STAR jobs are running.

Cheers
Alex

**Comment by xiuru** [comment]
Hi Alex,
Thanks for your quick reply. I tried another time using pre-compiled STAR in Linux_x86_64_static, this time the generation of the genome index finished successfully. And i already got some of bam files after alignment.

Have a good holidays！
Xiuru
