### ISSUE TITLE
STAR doesn't take in any reads in my fastq file

### ISSUE THREAD

**Issue by JavonSun** [alexdobin/STAR#800]
Hi Alex,

I am new to STAR and just recently started to use it to map a RNA-seq dataset. Thanks for developing and maintaining this very useful tool. I encountered a very strange problem, having all 0's in the Log.final.out file from running STAR, see attached. I have searched extensively and spent hours for trying to figure out what could be the cause, but without a luck. For everything tried, I always got all 0's in the Log.final.out file, even after I simplified my mapping command down to a very basic one like in below:

STAR --runThreadN 8 \
    --genomeDir /datasets/genomics/ref-genome/pig/susScr11/ensembl/star-index \
    --readFilesIn ./test1.fq ./test2.fq

Genome index was built prior mapping. Files test1.fq and test2.fq are two short fastq files that contain only two paired-end reads (extracted from files containing the full set of RNA-seq reads), see attached.  I checked the log file (Log.out, also attached) and did not notice any reported error. It seems STAR cannot recognize any of the reads in my fastq file, which works fine with Bowtie2 (verified). I ran out of ideas. I wonder could you shed some light on what could be the cause of this problem? I truly appreciate it. Thank you very much! Wish you a great and fruitful new year!

Best,
Javon

Note that I appended .txt to the name of each file for being able to upload them. 

[Log.final.out.txt](https://github.com/alexdobin/STAR/files/4013169/Log.final.out.txt)
[Log.out.txt](https://github.com/alexdobin/STAR/files/4013195/Log.out.txt)
[test1.fq.txt](https://github.com/alexdobin/STAR/files/4013193/test1.fq.txt)
[test2.fq.txt](https://github.com/alexdobin/STAR/files/4013194/test2.fq.txt)

**Comment by alexdobin** [comment]
Hi Javon,

there is nothing suspicious in the Log.out file, and I could map these files fine (to a different genome, so no alignments, but the reads were detected). So the files seem to be correctly formatted.

A few things to try:
1. Specify full path to the FASTQ files.
2 . Use the pre-compiled executables, dynamic or static.
3. Map to a different genome.
4. Map different fastq files.

Cheers,
Alex

**Comment by JavonSun** [comment]
Thanks for the reply, Alex. I have already tried the full paths to fastq files. I am using STAR newly installed on the cluster in my university. I do not believe there is any one else who used it before me. Let me do some local test. It could be because STAR was not installed correctly. Just want to confirm, the "Number of input reads" in the Log.final.out should tell us the total number of reads in the fastq file regardless aligned or unaligned, right? In the testing case that I have above, it should be either 2 (pair end) or 4 (single end), right? If this is the case, I guess we can rule out problematic genome from being the potential cause of this? Plus you have tested the fastq files, they look fine. So, the only thing that is left would be the installation. 

Best
Javon

**Comment by alexdobin** [comment]
Correct - the "Number of input reads" should be equal to the number of reads in fastq file, with two mates of a PE read are counted as one. In your example:
```
                                 Started job on |       Jan 02 11:31:19
                             Started mapping on |       Jan 02 11:31:36
                                    Finished on |       Jan 02 11:31:39
       Mapping speed, Million of reads per hour |       0.00

                          Number of input reads |       2
                      Average input read length |       284
                                    UNIQUE READS:
                   Uniquely mapped reads number |       0
                        Uniquely mapped reads % |       0.00%
                          Average mapped length |       0.00
                       Number of splices: Total |       0
            Number of splices: Annotated (sjdb) |       0
                       Number of splices: GT/AG |       0
                       Number of splices: GC/AG |       0
                       Number of splices: AT/AC |       0
               Number of splices: Non-canonical |       0
                      Mismatch rate per base, % |       -nan%
                         Deletion rate per base |       0.00%
                        Deletion average length |       0.00
                        Insertion rate per base |       0.00%
                       Insertion average length |       0.00
                             MULTI-MAPPING READS:
        Number of reads mapped to multiple loci |       0
             % of reads mapped to multiple loci |       0.00%
        Number of reads mapped to too many loci |       0
             % of reads mapped to too many loci |       0.00%
                                  UNMAPPED READS:
  Number of reads unmapped: too many mismatches |       0
       % of reads unmapped: too many mismatches |       0.00%
            Number of reads unmapped: too short |       2
                 % of reads unmapped: too short |       100.00%
                Number of reads unmapped: other |       0
                     % of reads unmapped: other |       0.00%
                                  CHIMERIC READS:
                       Number of chimeric reads |       0
                            % of chimeric reads |       0.00%
```

**Comment by JavonSun** [comment]
Thank you very much again for the help, Alex. It turned out this was due to a compiling issue during the installation. After my support team rebuilt with ICC, STAR now works as expected. 

Best,
Javon
