### ISSUE TITLE
Is SJ.out.tab based on de-dupped reads

### ISSUE THREAD

**Issue by liuxl18-hku** [alexdobin/STAR#806]
Hi,

Was wondering SJ.out.tab output is based on de-dupped reads or I have to do de-dupplication by myself and re-counting numbers if I want the de-dupped version.

bless~
Xingliang

**Comment by alexdobin** [comment]
Hi Xingliang

SJ.out.tab output does not do any deduplication, i.e. all reads are counted.
You would need to do deduplicate and then count the splices.

Cheers
Alex
