### ISSUE TITLE
BUG: next index is smaller than previous, EXITING

### ISSUE THREAD

**Issue by thondeboer** [alexdobin/STAR#807]
I know this issue has come up a couple of times and has mostly been resolved, so maybe mine will be easy as well...

I am using the GATK Resource bundle FASTA file: https://storage.cloud.google.com/genomics-public-data/resources/broad/hg38/v0/Homo_sapiens_assembly38.fasta
And as the annotations I use GENCODE: ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_32/gencode.v32.chr_patch_hapl_scaff.annotation.gtf.gz

Command line:
```
/home/tdeboer/STAR/bin/Linux_x86_64_static/STAR --runThreadN 8 --runMode genomeGenerate --genomeDir /home/tdeboer/star_index --genomeFastaFiles /home/tdeboer/Dropbox/DOCKER/DATA/GATK_Resource_Bundle_GRCH38/Homo_sapiens_assembly38.fasta --sjdbGTFfile /home/tdeboer/Dropbox/DOCKER/DATA/GENCODE/gencode.v32.annotation.gtf --sjdbOverhang 99
```
Hope this is something that can be resolved...

Thon

**Comment by thondeboer** [comment]
In case you want the last few lines of the log file:

```
Writing 1586604360 bytes into /home/tdeboer/star_index/SA_28 ; empty space on disk = 497134718976 bytes ... done
Jan 08 17:45:07 ... loading chunks from disk, packing SA...
Jan 08 17:48:53 ... finished generating suffix array
Jan 08 17:48:53 ... generating Suffix Array index

BUG: next index is smaller than previous, EXITING

Jan 08 17:51:22 ...... FATAL ERROR, exiting
```

**Comment by alexdobin** [comment]
Hi Thon,

could you try using the GTF for primary assembly: ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_32/gencode.v32.primary_assembly.annotation.gtf.gz

If it does not help, I will try to reproduce the error on my server.

Cheers
Alex

**Comment by bartgrantham** [comment]
We have stumbled across this bug as well, but we've had plenty of success building indices from these inputs so I deleted the output directory and tried again with the _exact same command line_.  It worked the second time, as we've seen it done c half-dozen times before.

Unfortunately I didn't save the Log.out of the failed run, but hopefully this provides some insight on this bug.  Two virtually identical runs, but it failed the first time and succeeded the second time.  The only thing that might be different is that the second time it was overwriting an existing Log.out, and the kernel file cache would have been different the two times.

My educated guess would be a race condition somewhere between "generating Suffix Array index" and "completed Suffix Array index".  Based on the other thread's observation of file creation/deletion happening in rapid succession and the 45 seconds between "generating..." and hitting the bug, my wild speculation would be that the race condition actually started around the time of the "generating..." message even though the failure was 45 seconds later.

**Comment by alexdobin** [comment]
Hi Bart,

thanks for these observations. Pretty much every time this problem appears to be transient and not reproducible.
The only case where the reason is clear is when two genomeGenerate jobs are run simultaneously in the same directory by accident.

This issue appears in the part of the code that's not threaded...

Did it ever happen for a small genome? I can try to run it through valgrind for a small genome, it's impractical to do it for a large genome.

Cheers
Alex
Cheers
Alex

**Comment by bartgrantham** [comment]
> The only case where the reason is clear is when two genomeGenerate jobs are run simultaneously in the same directory by accident.

I'm 100% sure it was the only process, and 99% sure the directory was clean to start with.  I was dumbfounded when it failed because we are running it from a docker image, and with a reference that we've run before.  Even with the same command line!  I was so perplexed I did the irrational and simply up-arrowed in history to re-run it (there were a couple invocations of "ls" in-between).

When it worked I was so sure I was missing something I cut and pasted the two commands from my history through md5, just to verify I wasn't overlooking a typo somewhere.

> This issue appears in the part of the code that's not threaded

Well that blows away my theories.  Is it possible there's an uninitialized variable for the index being compared that is usually larger by luck (overlaying a previously used piece of memory)?

> Did it ever happen for a small genome? 

We only tried it with a "mixed" genome, so human+mouse.  Relatively large, 6GB.  I only saw it happen once. :-/

**Comment by bartgrantham** [comment]
FWIW, we experienced this with 2.7.3a

**Comment by alexdobin** [comment]
Thanks!
I agree that this is most likely some very rare memory corruption. These are hard to catch, unfortunately.

**Comment by millerh1** [comment]
@alexdobin I am having the same bug. Deleting the folder and trying again doesn't work. I have gotten the error several times now even after adjusting parameters and trying different folders/users.

I have a completely fresh install of star 2.7.8a in a conda environment. I am using the primary assembly and main GTF for the hg38 genome from Gencode (downloaded them both today). 

Here is my command:

```
(starenv) millerh1@BioLinx:~$ STAR --runThreadN 40 --runMode genomeGenerate --genomeDir tmp2 --genomeFastaFiles GRCh38.primary_assembly.genome.fa --sjdbGTFfile gencode.v37.annotation.gtf
Feb 24 23:23:16 ..... started STAR run
Feb 24 23:23:16 ... starting to generate Genome files
Feb 24 23:23:54 ..... processing annotations GTF
Feb 24 23:24:18 ... starting to sort Suffix Array. This may take a long time...
Feb 24 23:24:31 ... sorting Suffix Array chunks and saving them to disk...
Feb 24 23:36:37 ... loading chunks from disk, packing SA...
Feb 24 23:37:25 ... finished generating suffix array
Feb 24 23:37:25 ... generating Suffix Array index

BUG: next index is smaller than previous, EXITING

Feb 24 23:37:30 ...... FATAL ERROR, exiting
```

I am providing the log file [here](https://misc-items-to-share.s3-us-west-2.amazonaws.com/Log.out)

My server is running Ubuntu 20.04 LTS, CPU is Ryzen Threadripper 3960x, 256GB DDR4 ram, M.2 NVMe SSD 2TB available. 

Let me know if you want access to it... it sounds like it isn't reproducible on your machine, so (if you want) you can troubleshoot it on mine.

**Comment by alexdobin** [comment]
Hi Henry,

please try a few things:
1. Make sure that no other STAR process is running, e.g. with
```killall STAR```
2. Reduce the number of threads
3. Run the pre-compiled static executable from the STAR release:
```bin/Linux_x86_64_static/STAR```
4. Compile STAR from source - simply issue ```make``` in the ```source/``` directory.

If it does not help, we will need to think how to debug it.

Cheers
Alex

**Comment by millerh1** [comment]
Hi @alexdobin -- thank you for looking into this... what I'm about to say will probably be annoying to you and everyone else who finds this bug, but after noticing the bug I started to find lots of other very unusually issues surrounding C/C++ libraries on the computer... I lost most of a day trying to fix the issues to no avail so I just reset the whole server back to default and re-installed ubuntu fresh. STAR works fine now from the conda install... Sorry I wasn't able to provide more help. Anyways, for me the problem seemed to stem from some deep issues with my C/C++ libraries.

**Comment by alexdobin** [comment]
Hi Henry,

another option - to save time from the beginning - is to use statically compiled executable ```bin/Linux_x86_64_static/STAR```

Cheers
Alex
