### ISSUE TITLE
Segmentation Fault running solo

### ISSUE THREAD

**Issue by wir963** [alexdobin/STAR#809]
Hey @alexdobin, 

I've been using STAR for a while and really enjoy it, so thanks for your hard work. Recently, I've started working with solo and I've managed to get a segmentation fault. I'm using most of the options that I usually use for STAR with bulk RNA-seq so it's very possible that the error is mine.

I've been working with scRNA-seq from 10x genomics 3' chromium v2.0. The raw data is publicly available from [SRA accession PRJNA483959](https://www.ncbi.nlm.nih.gov/Traces/study/?acc=PRJNA483959). I'm working with run SRR7722937. 

## Command
```
STAR --runThreadN 48 --genomeDir 'STAR/genome' --genomeLoad NoSharedMemory --outFileNamePrefix 'output/SRR7722937/star' --readFilesIn 'raw/FASTQ/SRR7722937_cDNAfragmentSequence.fastq.gz' 'raw/FASTQ/SRR7722937_CellBarcodeUMIsequence.fastq.gz' --soloType CB_UMI_Simple --soloCBwhitelist ../STARsolo/barcode_whitelist/737K-august-2016.txt --soloFeatures Transcript3p --outSAMattrRGline ID:SRR7692289 PL:illumina SM:SRR7722937 LB:RNA --outSAMattributes NH HI AS nM NM ch CR UR CB UB --outSAMtype BAM SortedByCoordinate --outSAMunmapped Within --soloOutFileNames SRR7722937 --readFilesCommand zcat --sjdbGTFfile '/gpfs/gsfs9/users/Robinson-SB/SB-RNA-workflows/genome/raw/gencode.v22.annotation.gtf'
```
## Error
From the output file
```
Jan 09 16:08:23 ..... started STAR run
Jan 09 16:08:24 ..... loading genome
Jan 09 16:08:42 ..... processing annotations GTF
Jan 09 16:08:59 ..... inserting junctions into the genome indices
Jan 09 16:12:49 ..... started mapping
Jan 09 16:27:33 ..... finished mapping
Jan 09 16:27:39 ..... started Solo counting
/usr/bin/bash: line 1: 48238 Segmentation fault 
```
The last four lines from the log file
```
Jan 09 16:15:21 ..... started Solo counting
Jan 09 16:15:21 ... Starting Solo post-map for Transcript3p
Jan 09 16:15:21 ... Finished allocating arrays for Solo 0 GB
Jan 09 16:15:21 ... Finished reading reads from Solo files nCB=0, nReadPerCBmax=0, nMatch=0
```

## Environment
I create a conda environment from the below environment file
```
name: star
channels:
  - bioconda
dependencies:
  - star>=2.7.3a
```

## Steps to reproduce
I use snakemake (a workflow tool) so these are snakemake rules for downloading the files from SRA. This assumes that you have the sratoolkit module available. 
```
rule all:
    input:
        expand(cDNA_FASTQ_FILE, sra="SRR7722937"),
        expand(CellBarcode_FASTQ_FILE, sra="SRR7722937"),
rule rename_10x_FASTQ_files:
    input:
        fq1 = FASTQ2_FILE,
        fq2 = FASTQ3_FILE
    output:
        cDNA_fq = cDNA_FASTQ_FILE,
        CellBarcode_fq = CellBarcode_FASTQ_FILE
    shell:
        "mv {input.fq1} {output.CellBarcode_fq} && "
        "mv {input.fq2} {output.cDNA_fq}"

rule extract_FASTQ_from_SRA:
    input:
        SRA_FILE
    params:
        FASTQ_DIR
    output:
        FASTQ1_FILE,
        FASTQ2_FILE,
        FASTQ3_FILE
    shell:
        "module load sratoolkit && fastq-dump --gzip -O {params} -I "
        "--split-files -F {wildcards.sra}"

rule download_SRA_files:
    output:
        SRA_FILE
    shell:
        "module load sratoolkit && prefetch {wildcards.sra}"

rule create_star_index:
    conda:
        join(ENV_DIR, "star.yml")
    input:
        GENOME_FASTA_FILE
    output:
        directory(STAR_GENOME_INDEX)
    threads:
        16
    shell:
        "mkdir '{output}' && STAR "
        "--runThreadN {threads} "
        "--runMode genomeGenerate "
        "--genomeDir '{output}' "
        "--genomeFastaFiles '{input}'"
```

**Comment by wir963** [comment]
I looked and couldn't find a tutorial (or just set of recommended options) for running solo on basic 10x 3' or 5' scRNA-seq. I'm sure there is a reason for this but if we can figure this out, I'd be happy to help contribute to that effort.

**Comment by alexdobin** [comment]
Hi @wir963 

the --soloFeatures Transcript3p option is unsupported in the stable release at the moment. You can use 4 features --soloFeatures Gene GeneFull SJ Velocyto (separately or together).

I have some hints about running STARsolo here:
https://github.com/alexdobin/STAR/blob/master/docs/STARsolo.md
If you are interested in creating a tutorial, it's great - I would be happy to help!

Cheers
Alex

**Comment by wir963** [comment]
Hey Alex, 

Thanks for letting me know. I found the `--soloFeatures Transcript3p` option at [https://github.com/alexdobin/STAR/blob/master/docs/STARsolo.md#for-completenes-all-parameters-that-control-starsolo-output-are-listed-again-below-with-defaults-and-short-descriptions](https://github.com/alexdobin/STAR/blob/master/docs/STARsolo.md#for-completenes-all-parameters-that-control-starsolo-output-are-listed-again-below-with-defaults-and-short-descriptions) so perhaps you could remove that or label it as not supported to help other people in the future?

Best, Welles

**Comment by wir963** [comment]
FYI when I use `--soloFeatures Gene` and remove `-soloOutFileNames SRR7722937` (it didn't play nicely with `--outFileNamePrefix 'output/SRR7722937/star`), STARsolo is running smoothly. I'll work on the tutorial as well and keep you posted. Thanks again for your help

**Comment by kehey** [comment]
I can confirm that indeed `-soloOutFileNames SRR7722937` seems to be causing trouble with `--outFileNamePrefix`

I also had a Segmentation fault when setting both.

**Comment by alexdobin** [comment]
Hi Welles, @kehey 

thanks for pointing this out - I will remove the Transcript3p description for now.
--soloOutFileNames changes names for the Solo.out and inside it:
Solo.out/          features.tsv barcodes.tsv        matrix.mtx
Typically, you do not want to change these, but if you do, you would need to specify all 4 names.

If you need a specific output directory for your STAR run, please use --outFileNamePrefix .

Cheers
Alex
