### ISSUE TITLE
running star within snakemake causes error

### ISSUE THREAD

**Issue by yeroslaviz** [alexdobin/STAR#810]
I having difficulties running `star` within a snakemake workflow. I have 30 paired-end samples in one directory and I'm trying to run in parallel three samples at a time. 

When doing some samples run through with no problems, but than I get the following error:

```
EXITING because of FATAL ERROR: number of bytes expected from the BAM bin does not agree with the actual size on disk: Expected bin size=133759105 ; size on disk=126075572 ; bin number=18
```

the command I'm using in a `snakemake`, which than is being translated to this command

```
STAR --runThreadN 16 --genomeDir /fs/pool/pool-bcfngs/genomes/Dme.BDGP6.22/starIndex/ --outFileNamePrefix P152/Dme.BDGP6.22/star/Ph_C --readFilesIn Ph_C.conc.R1.fastq.gz Ph_C.conc.R2.fastq.gz --readFilesCommand zcat --outSAMtype BAM SortedByCoordinate --limitBAMsortRAM 168632718037 --quantMode GeneCounts --outReadsUnmapped Fastx
```

The `snakemake` command uses the option `-j 50` so that to allow three samples in parallel (16+16+16) and than two more for converting the bam to bigwig. 

I have read that it is problematic to run multiple star runs in one folder. But this was for older `star` versions.  Is this still problematic. Does this apply here to my folder structure?

thanks
Assa

P.S. 
My `star` version is 2.7.2c

**Comment by alexdobin** [comment]
Hi Assa,

when several jobs are run concurrently, do the have different --outFileNamePrefix strings? This is needed so that results and temp files do not overwrite each other.
If this is the case, another cause for this error could insufficient space on disk.

Cheers
Alex
