### ISSUE TITLE
Reducing STAR's RAM usage by removing alternative sequences (CHR_ALT)

### ISSUE THREAD

**Issue by hreinwal** [alexdobin/STAR#811]
Hi @alexdobin,
thank you very much for the advice to the issue #650 . I am using the same ref. genome from the zebrafish (GRCz11) and I am having the same problem that STAR asks for 140 GB of RAM. I have two questions considering your comment and I hope they are not too silly:

1. How do I find out if my references genome has a lot of alternative sequences?
2. How do I remove them as you suggested?

Cheers,
Hannes

**Comment by alexdobin** [comment]
Hi Hannes,

I believe ENSEMBL has the primary assembly for GRCz11 here:
ftp://ftp.ensembl.org/pub/release-98/fasta/danio_rerio/dna/Danio_rerio.GRCz11.dna.primary_assembly.fa.gz
This file should include all the necessary sequences but no alts or patches.

Cheers
Alex

**Comment by hreinwal** [comment]
Thanks for the feedback Alex :) Highly appreciate your work and support. 
Cheers,
Hannes
