### ISSUE TITLE
Aligning reads to very small exons

### ISSUE THREAD

**Issue by sagnikbanerjee15** [alexdobin/STAR#814]
Hello,

I am currently using STAR for alignment and transcriptome assembly. There are few genes in Arabidopsis (and also in other organisms) that have very small exons (<6 nucleotides). In the example below, the small exon has 9 nucleotides. I configured STAR to align to small exons by altering the alignSJDBoverhangMin and seedSplitMin parameter. Unfortunately, STAR was unable to align reads to this exon. I looked up the unmapped reads and I was able to find reads mapping to this exon. Here is a list of parameters I am using for mapping.

            cmd="/work/LAS/rpwise-lab/sagnik/finder/lib/STAR "
            cmd+=" --runThreadN "+options.cpu
            cmd+=" --genomeDir "+options.genome_dir_star
            cmd+=" --outSAMtype BAM SortedByCoordinate "
            cmd+=" --outFilterMultimapNmax 500 " 
            cmd+=" --outFilterMismatchNmax 3  " # For round 3 THREE mismatches are allowed 
            cmd+=" --alignIntronMin 20  "
            cmd+=" --alignIntronMax 10000 "
            cmd+=" --limitBAMsortRAM 50000000000"
            cmd+=" --alignEndsType Local " # ALLOWS soft clipping
            #cmd+=" --alignEndsType EndToEnd " # Disallow soft clipping  
            cmd+=" --outSAMprimaryFlag AllBestScore "
            cmd+=" --outFilterScoreMinOverLread 0.98 "
            cmd+=" --outFilterMatchNminOverLread 0.98 "
            cmd+=" --outSJfilterOverhangMin 4 4 4 4 "
            cmd+=" --outSAMattributes NH HI AS nM NM MD jM jI XS "
            cmd+=" --outReadsUnmapped Fastx "
            cmd+=" --seedPerReadNmax 10000 "
            cmd+=" --seedPerWindowNmax 500 "
            cmd+=" --seedSplitMin 4 "
            cmd+=" --sjdbFileChrStartEnd "+options.output_star+"/"+bioproject+"_round1_and_round2_SJ.out.tab "
cmd+=" --outFileNamePrefix "+options.output_star+"/"+Run+"_round3_"
            cmd+=" --outSJfilterCountUniqueMin 1 1 1 1 " # Stricter bounds than round1
            cmd+=" --outSJfilterCountTotalMin 1 1 1 1 " # Stricter bounds than round1
            cmd+=" --alignSJoverhangMin 4 " # For round 3 same high overhang is used as in round 1
            cmd+=" --alignSJDBoverhangMin 4 " # 
            cmd+=" --readFilesIn "+options.output_star+"/"+Run+"_round2_Unmapped.out.mate1"

Also, please note that STAR is aligning some reads to small exons but this genomic locus is missed.
Could you please help?

Thank you.

![image](https://user-images.githubusercontent.com/23457977/72665221-0db73700-39bb-11ea-84b2-4761370813a3.png)

**Comment by alexdobin** [comment]
Hi Sagnik,

finding microexons (even the annotated ones) is a tricky business. Two parameters that increase sensitivity and may help to align to a small exon are:
--seedSearchStartLmax =50 default, try reducing to 20 or even 10
--winAnchorMultimapNmax =50 by default, try increasing to 200 or more.

I would recommend starting with simulated perfect read that contains a microexon to see if it can be aligned.

Cheers
Alex

**Comment by sagnikbanerjee15** [comment]
Hi Alex,

Thank you for your reply. I implemented the changes you mentioned but I was unable to get more reads to map to the particular loci shown above. Is there any other approach I can take?

Thank you.

**Comment by alexdobin** [comment]
Hi Sagnik,

have you tried to "simulate" a few reads that overlap the short exon and map it?
If this does not work, the other path would be to add the entire transcripts that contain this short exon as separate "chromosomes" to the whole genome. This should allow mapping of these reads, but you would have to transform coordinates back to the genome. Also, some of the reads mapping to these transcripts will become multimappers because of it.

Cheers
Alex

**Comment by sagnikbanerjee15** [comment]
Hi Alex,

Thank you for your reply. Yes, I am currently looking at a particular locus that has a micro exon and STAR fails to map reads to it even with the parameter settings you suggested. I am using alignment as a first step for future assembly. Currently, I am testing my pipeline on a model organism which is why I know what the gene structures are. The pipeline will be implemented on organisms for which RNA-Seq data is available but gene structures are not. I guess I have to come up with some algorithmic approach to deal with this case.

Thank you.

**Comment by alexdobin** [comment]
Hi Sagnik,

detecting microexons de novo, i.e. without annotations, will be a much harder task - probably requires transcript assembly rather than mapping.

Cheers
Alex

**Comment by sagnikbanerjee15** [comment]
Hello Alex,

I completely agree. I tried a bunch of other aligners with different parameter settings but was unable to map reads to all micro-exons. De novo assembly seems to be the only way to capture such cases.

Thanks.
