### ISSUE TITLE
STARlong 2.5.0a stopping after aligning the first read, without crashing

### ISSUE THREAD

**Issue by lucventurini** [alexdobin/STAR#82]
Observed in the latest release, but not with the commit f82c5a002841b3a6e6a503035572e491a153a7cf. Due to the issue, STARlong stops after aligning the first 3 reads (apparently after finding the first successful match).

Tested on the 3B pseudomolecule of wheat (~750 Mbps in a single chromosome; see http://www.ebi.ac.uk/ena/data/view/HG670306), using PacBio data as input.

**Comment by alexdobin** [comment]
Hi Luca,

I cannot reproduce this problem. Could you please send me the Log.out file, as well as a few reads that caused the error.

Cheers
Alex

**Comment by lucventurini** [comment]
Hi Alex,
             sure, I attach everything to this comment. Please note that the file is not a TXT but rather a ZIP ... GitHub did not accept the ZIP file with the right extension.

Cheers

Luca

[Debug.txt](https://github.com/alexdobin/STAR/files/32978/Debug.txt)

**Comment by alexdobin** [comment]
Hi Luca,

I could not reproduce the problem with your reads, parameters and genome.
Are you sure that you compiled STAR with 'make STARlong'?
The Log.final.out indicates that STAR only read 499 bases from the first read, which exactly the limit for normal STAR (not STARlong). I thought that this was supposed to generate a error (or at least a crash :) ) - I will check why it did not.
Could you try to run the pre-compiled STARlong from bin/Linux_x86_64 or Linux_x86_64_static?

Cheers
Alex

**Comment by lucventurini** [comment]
Hi Alex,
            yes, I did compile it with "make STARlong". Bizarrely, though, the two binaries in the foder (STAR and STARlong) are identical according to diff.

One important thing that might explain the problem: I had to modify the Makefile in the source directory to provide the location of the zlib headers (ours is a non-standard linux system). 
In practice I modified:

LDFLAGS_shared := -pthread -Lhtslib -Bstatic -lhts -Bdynamic -L/tgac/software/testing/libraries/zlib/1.2.8/x86_64/lib/ -lz -lrt
CXXFLAGS_common := -pipe -std=c++11 -Wall -Wextra -fopenmp $(COMPTIMEPLACE) -I /tgac/software/testing/libraries/zlib/1.2.8/x86_64/include/

During compilation, "make STARlong" included apparently the switch for long read compilation:

{code}
$ make STARlong
g++ -o STARlong  -O3 -pipe -std=c++11[..] -I /tgac/software/testing/libraries/zlib/1.2.8/x86_64/include/ -D'COMPILE_FOR_LONG_READS'  SharedMemory.o [..]
Parameters_openReadsFiles.cpp: In member function ‘void Parameters::openReadsFiles()’:
Parameters_openReadsFiles.cpp:30:20: warning: variable ‘imate’ might be clobbered by ‘longjmp’ or ‘vfork’ [-Wclobbered]
          for (uint imate=0;imate<readNmates;imate++) {//open readIn files

However, even if the switch is present on the command line, the binary is identical to the STAR one.

**Comment by lucventurini** [comment]
OK, I tested with the released static binaries, and the bug is *not* present. So this genuinely seems to be a compilation issue on our machine, although I am baffled at why this would happen!

**Comment by alexdobin** [comment]
Hi Luca,

one possible explanation is as follows. If you compiled STAR for short reads (i.e. with simple 'make'), and then simply run 'make STARlong', it will not recompile any of the .o files except STAR.cpp, and so the -D'COMPILE_FOR_LONG_READS' switch will not be incorporated. You would need to run 'make clean' before 'make STARlong'. Could you try it out?

Cheers
Alex

**Comment by lucventurini** [comment]
Hi Alex,
             this was indeed the case - after I cleaned and compiled specifically STARlong the issue disappeared. Maybe you could add some lines in the README to highlight this? I would have never figured it out on my own.

Closing this issue anyway.

Cheers

Luca

**Comment by ControlCcolon** [comment]
> Hi Alex,
> this was indeed the case - after I cleaned and compiled specifically STARlong the issue disappeared. Maybe you could add some lines in the README to highlight this? I would have never figured it out on my own.
> 
> Closing this issue anyway.
> 
> Cheers
> 
> Luca

Ciao Luca, volevo chiederti dove si puo' scaricare STARlong 
grazie

**Comment by lucventurini** [comment]
Dear @ControlCcolon ,
                                        you can find STARlong inside the conda package (https://anaconda.org/bioconda/star).
Kind regards
