### ISSUE TITLE
Tagging all alignments

### ISSUE THREAD

**Issue by sagnikbanerjee15** [alexdobin/STAR#822]
Hello Alex,

I am doing several rounds of STAR mapping with different parameter settings. It will be beneficial for me to extract alignments that were generated in a particular run. I was wondering if there is a way ta have STAR append a particular tag, with a certain value, to all alignments.

Thank you.

**Comment by alexdobin** [comment]
Hi Sagnik,

you can use RG (read group) tag to that providing  --outSAMattrRGline ID:<tag> option. It will add RG:Z:<tag> to each line in the SAM file.

Cheers
Alex

**Comment by sagnikbanerjee15** [comment]
Thank you.
