### ISSUE TITLE
STAR error: Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by taltalina** [alexdobin/STAR#828]
Hi Alex,

I've been using STAR for the past few years, but recently, I tried to perform mapping to one specific chromosome.
To do that, I used STAR version 2.5.3a and generated the index based on this one specific chromosome, and it looks like it created all the files.
However, mapping was aborted quickly and I received the error "Segmentation fault (core dumped)", and the standard output looked like this:
Jan 29 11:36:27 ..... started STAR run
Jan 29 11:36:27 ..... loading genome
Jan 29 11:36:28 ..... started mapping

I would greatly appreciate if you could help me with this problem.

Thanks,
Tal

**Comment by siebrenf** [comment]
Hey taltalina, 

have a look at the --genomeSAindexNbases flag. Section 2.2.5 Very small genome, in the manual.

**Comment by taltalina** [comment]
Thank you @siebrenf !
That was exactly it :)
