### ISSUE TITLE
Same number of barcodes across samples

### ISSUE THREAD

**Issue by mej54** [alexdobin/STAR#829]
Hi there,

I'm using STARsolo to process 10x single cell v3 3' samples. I've noticed that there seems to be the same number of barcodes in the barcodes.tsv file across samples that have been processed separately and across experiments. I'm just curious where this number is coming from, if there is a sort of max barcode that is output during the algorithm? 

The number of barcodes I'm getting across samples is 6794880. 

Thanks!

**Comment by alexdobin** [comment]
Hi Molly,

if you are looking in the Solo.out/Gene/raw/ directory, the barcodes there are unfiltered and contain the whole 10X whitelist. This will be the same for all samples as long as you use the same whitelist. The filtered barcodes, in the Solo.out/Gene/filtered/ directory shall vary between samples.

Cheers
Alex

**Comment by mej54** [comment]
Got it, thank you for explaining!
