### ISSUE TITLE
Core dumped by STAR 2.5.0a

### ISSUE THREAD

**Issue by ndaniel** [alexdobin/STAR#83]
When running STAR 2.5.0a, it dumps the core and no input reads are aligned.

This is the error message:
```
Nov 09 15:06:30 ..... Started STAR run
Nov 09 15:06:30 ..... Loading genome
Nov 09 15:06:30 ..... Started 1st pass mapping
Segmentation fault (core dumped)
```

STAR is run like this (and genome generating works fine):

```
STAR \
--genomeChrBinNbits 17 \
--genomeSAindexNbases 14 \
--runMode genomeGenerate \
--runThreadN 16 \
--genomeDir /u/meme-star/ \
--genomeFastaFiles /u/meme.fa \
--outFileNamePrefix /u/meme-star-results/

   STAR \
   --twopass1readsN -1 \
   --twopassMode Basic \
   --genomeSAindexNbases 14 \
   --sjdbOverhang 100 \
   --alignIntronMax 687154 \
   --outFilterMatchNmin 24 \
   --outFilterMatchNminOverLread 0.4 \
   --outFilterScoreMinOverLread 0.4 \
   --alignSplicedMateMapLminOverLmate 0.4 \
   --genomeDir /u/meme-star/ \
   --runThreadN 16 \
   --seedSearchStartLmax 17 \
   --alignSJoverhangMin 16 \
   --alignSJstitchMismatchNmax 5 -1 5 5 \
   --outSJfilterOverhangMin 10 10 10 10 \
   --outSJfilterCountUniqueMin 1 1 1 1 \
   --outSJfilterCountTotalMin 1 1 1 1 \
   --outSJfilterDistToOtherSJmin 0 0 0 0 \
   --outSJfilterIntronMaxVsReadN 687154 687154 687154 \
   --limitOutSAMoneReadBytes 100000000 \
   --scoreGapNoncan -4 \
   --scoreGapATAC -4 \
   --readFilesIn /u/reads_meme_no-str_fixed.fq \
   --outFileNamePrefix /u/meme-star-results/
```
Running STAR 2.4.2a on same input dataset and same command line arguments works fine (without alignSJstitchMismatchNmax of course).

[Here](https://dl.dropboxusercontent.com/u/3870630/logs.zip) are the run logs. The input FASTQ file is [here](https://dl.dropboxusercontent.com/u/3870630/reads_gene-gene_no-str_fixed.fq) and the reference genome FASTA file is [here](https://dl.dropboxusercontent.com/u/3870630/gene-gene.fa).

**Comment by alexdobin** [comment]
Hi Daniel,

thanks for reporting this bug. Please try the patch I just pushed on GitHub master, it should fix the problem.

Cheers
Alex

**Comment by ndaniel** [comment]
Hi Alex!

Thanks for the great work! It was really fast!

I confirm that the bug is fixed (in the last commit)!

Cheers,
Daniel
