### ISSUE TITLE
AlignReads - Bus error 

### ISSUE THREAD

**Issue by Kimvanuitert** [alexdobin/STAR#833]
I want to align the reads of a bacterial genome (MG1363). I have set --genomesSAindexNbases to 10 and I have 16 GB RAM. 

This is the command I use:

STAR --genomeDir MG1363/ --readFilesIn testR1.fastq testR2.fastq 
Feb 03 11:34:28 ..... started STAR run
Feb 03 11:34:28 ..... loading genome
Feb 03 11:34:29 ..... started mapping
Bus error (core dumped)

Is it because of the memory and is there a way to fix it?

**Comment by Kimvanuitert** [comment]
These two paired end reads are triggering the error for example:

R1.fastq
@A00597:65:HHCHNDRXX:2:1101:8413:1094 1:N:0:CCGCGGTT+AGCGCTAG
ATCCCAAACATCAAGTCCCAAAACTGGTGTCAATCCTTCAGAAATTGGATTATCTTGATTTGCAGTTGATACAACTTTCAATTTGCCAGCTTCAACAACAACAAACCAAGCCCAGCCTGAACCAAAACGGCCTGTGGCAGCAGCTATGGAT
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFF,FFFF:FFFFFFFFF:FFFFF:FFF,F,FFFFF:FFFFFFF,FFFFFFFFFFFF,FF,FFFFFFFFFFFFFFFFF,,F,FFF

R2.fastq
@A00597:65:HHCHNDRXX:2:1101:8413:1094 2:N:0:CCGCGGTT+AGCGCTAG
AAAAAAAAAACCACAACCCCAAATTTTTAAAGAAGGGCATTTTTATTTATTTAATAAAAAATAAAAAAAAAAAAATTATAAAAAAAAAAAAAAAAAAAAAAAAAATAAAAAATAAAAAAAACACAAATTTTAAATTAATATTTTTATAAAA
+
F,:,,F,,FF:,F,,:,,:F,,,FF:FF:F,,,:,,,,,:,,FF:,,,,,:,,,,FFF,F,,F,:,:,:,FFF:,,::,FFFFF::F,::FFFFF,:F::,F::F,FFFF,F,F,,,FFF,,,,FF,:F,FF::,,F:F,,:FF,F,::F,

**Comment by alexdobin** [comment]
Hi @Kimvanuitert 

16GB should be enough for a bacterial genome. Please try to further reduce ```--genomesSAindexNbases```, to 8 or 6 or 4.

Cheers
Alex

**Comment by kopeckyl** [comment]
I'm having a similar issue, I am getting a bus error too. I am trying to map 16 single read FASTQ files into a plant genome of 573,000,000 bases using `genomesSAindexNbases` as 13 according to the manual to generate the genome index. I am using `runThreadN ` as 14.

Any idea why I am getting this bus error? I am running out of memory? I am using a 64gb RAM machine with 8 cores with 2 threads per core

**Comment by alexdobin** [comment]
Hi @kopeckyl 

it does not seem like RAM problem, 64GB should be more than enough for the 573MBase genome.
Please send me the Log.out file.

Cheers
Alex

**Comment by SAKAI-Hiroshi** [comment]
Hello,

I have Bus error 10. I am trying to map PE 150bp library into mouse genome to align reads from repeated sequence (Transposable elements). This is the command I use, and I found this code in this paper (https://doi.org/10.1186/s13100-019-0192-1). I am using a 64GB memory. 

STAR --runThreadN 10 --outSAMtype BAM Unsorted --runMode alignReads --outFilterMultimapNmax 5000 --outSAMmultNmax 1 -- outFilterMismatchNmax 3 --outMultimapperOrder Random --winAnchorMultimapNmax 5000 --alignEndsType EndToEnd --alignIntronMax 1 --alignMatesGapMax 350 -- seedSearchStartLmax 30 --alignTranscriptsPerReadNmax 30000 -- alignWindowsPerReadNmax 30000 --alignTranscriptsPerWindowNmax 300 -- seedPerReadNmax 3000 --seedPerWindowNmax 300 --seedNoneLociPerWindow 1000

Nov 09 09:19:26 ..... started STAR run
Nov 09 09:19:26 ..... loading genome
Nov 09 09:21:07 ..... started mapping
Bus error: 10

Thank you for your help.

**Comment by alexdobin** [comment]
Hi @SAKAI-Hiroshi 

I think this is the RAM problem: these parameters 
```--alignTranscriptsPerReadNmax 30000 -- alignWindowsPerReadNmax 30000 --alignTranscriptsPerWindowNmax 300``` significantly increase the memory consumption. I guess they were used because of these values: ```--winAnchorMultimapNmax 5000``` which are very aggressive.

I would recommend gradually increasing --winAnchorMultimapNmax from the default 50 to check how many more reads you are mapping.

Cheers
Alex

**Comment by SAKAI-Hiroshi** [comment]
Hello @alexdobin 

Thank you for your comments. I will try these options.

Best,
Hiroshi
