### ISSUE TITLE
mapping to the virus genome

### ISSUE THREAD

**Issue by priyatamapandey** [alexdobin/STAR#835]
Hi Alex,
I am trying to map my RNA-seq sequence to the virus genome. Since my genome size is around ~250K base long. So, I used `--genomeSAindexNbases 7` for building indices. Now, most of my samples has been running from 3 days but nothing is aligning which I can see in the progress log file. It is working fine with the human genome reference. Since my genome is very small compared to the human genome. Do I need to take care of any other parameter?
I added `--outFilterMismatchNmax 20`  but it did not help.
So,In addition to mismatch, I added `--seedSearchStartLmax 30 --outFilterScoreMinOverLread 0 --outFilterMatchNminOverLread 0 ` in my mapping command and I found at least some alignment. 

Please let me know if I am missing any obvious command to map against viral genome.

Thank you,
Priya

**Comment by alexdobin** [comment]
Hi Priya,

are you running a sample that contains both viral and host reads? In that case, mapping to the viral genome only may indeed be very slow, as most of the reads will not map. I recommend mapping to a combined host/viral genome. Or you can try to reduce the --seedPerWindowNmax from the default 50 to 30 or 20 or 10 - please see the discussion here:  https://groups.google.com/d/msg/rna-star/7ZUTnk8_bEI/BKFobC46CgAJ

Cheers
Alex

**Comment by priyatamapandey** [comment]
Hi Alex,
Thank you for the suggestion and link. I like the idea of combining the host and viral genome. I am hoping that it would be feasible to separate the alignment later. For combining the host and viral genome, I have to make a single the genome fasta file then built the genome. Also, I only have host(human) genome annotation file. Should I provide that in the command?

Thank you for the help.
Priya

**Comment by alexdobin** [comment]
Hi Priya,

you can list multiple fasta files in the --genomeFastaFiles command, no need to concatenate them. You just need to make sure that the chromosome names are distinct in two species. It's OK to have only human annotations.

Cheers
Alex

**Comment by priyatamapandey** [comment]
Hi Alex, 
Thanks for introducing me this option. How do I separate the viral genome mapped from the bam file? Actually, I am only interested in the reads who mapped with viral genome. How can I separate with some reads mapped on the viral genome strand/chromosomes only when I provide multiple genome fasta files?

Thank you so much for your help.

**Comment by alexdobin** [comment]
Hi Priya,

after you get sorted BAM (either with samtools sorting or STAR sorting), you would need to index it, and then use samtools to extract the entire viral chromosome:
```samtools view -b Aligned.sorted.bam _ViralChr_   >   Aligned.viral.bam```

Cheers
Alex

**Comment by priyatamapandey** [comment]
Hi Alex,
thank you for your reply. This is very helpful. I tried to sort with STAR sorting but having memory issue. Although I have added `--limitBAMsortRAM 60G` in my pipeline. But still faced issue for some samples. So, I did it with samtools separately. Although I wanted to get it done by one tool STAR only.

Thanks
Priya

**Comment by priyatamapandey** [comment]
Hi Alex,
I am trying to BLAST with my unmapped reads but not sure how to use Unmapped.out.mate1 and Unmapped.out.mate2 file in blast command? it looks to be BLAST command takes Fasta files as a query.

Thanks so much,
Priya

**Comment by alexdobin** [comment]
Hi Priya,

you would have to BLAST mate1 and mate2 separately, and then check whether the alignments are close to each other (on opposite strand).

Cheers
Alex

**Comment by priyatamapandey** [comment]
Hi Alex,
I thought either I had to cat both the files together and then convert it in fasta or I have  to assemble the unmapped files using  assembly tools like trinity and get the contigs.  

Thanks,
Priya

**Comment by alexdobin** [comment]
Hi Priya,

if you are trying to quickly check for contamination, you could just map both reads independently.
If you want a more serious assessment of the sources of unmapped reads, assembly is a good approach, but it's more complicated.

Cheers
Alex

**Comment by tbrunetti** [comment]
Hi Alex,

First, thank you so much for maintaining such good documentation on open source software and for being very active on the github -- it is much appreciated and impressive!  I am following up with this thread, primarily because my question relates to this issue.

I am using star to align to a mouse genome and a viral genome (with varying concentrations of virus exposure).  I am interested in using reads from both the mouse and viral genome for differential expression analysis.

I have 151bp paired end reads and it seems that you suggest aligning them at the same time rather than first mapping to the mouse and then using the unmapped mouse reads to map to the viral genome.  With that being said, since the viral genome is small and my read lengths are long what is the ideal balance or calculation to set parameters in STAR so that both the mouse and viral reads are aligned optimally?

For example, `--genomeSAindexNbases`, `--outFilterMismatchNmax`, `--outFilterScoreMinOverLread`, `--outFilterMatchNminOverLread`, or any other parameters I need to take into consideration?

**Comment by alexdobin** [comment]
Hi @tbrunetti 

sorry for the belayed reply. It's better to start a new issue - they are visible while the replies to the old issues get pushed out by the new issues. I guess I should probably close more of the old issues.

To answer your questions, I do not think you need to change any of the parameters in your case. The parameters that work for mouse will work well for the combined mouse/human genome.

Cheers
Alex

**Comment by tbrunetti** [comment]
Great, thank you so much!  I will be sure to open a new issue next time.  I have done a few interations of alignments with updating those parameters and have gotten a lot of success.  Thank you!
