### ISSUE TITLE
Why are reads being called too short?

### ISSUE THREAD

**Issue by bbimber** [alexdobin/STAR#836]
Hello,

I am trying to run STAR on some older SRA data which are PE50bp reads.  I trim the reads and some pairs become shorter; however, according to STAR my average input read length is 97 (below).  Nonetheless, 98% are labeled as 'unmapped: too short'.  From what I see in the docs, the default of parameters that might be removing short reads, like --outFilterMatchNmin, are 0.  I dont see any other parameters that dictate the minimum mapped read length.  do you have any suggestions on where I might try to debug why these reads are being discarded?  Thanks in advance.

The log file is below:

                                 Started job on |	Dec 21 11:28:04
                             Started mapping on |	Dec 21 11:42:42
                                    Finished on |	Dec 21 11:54:01
       Mapping speed, Million of reads per hour |	306.24

                          Number of input reads |	57760195
                      Average input read length |	97
                                    UNIQUE READS:
                   Uniquely mapped reads number |	1408
                        Uniquely mapped reads % |	0.00%
                          Average mapped length |	89.30
                       Number of splices: Total |	19
            Number of splices: Annotated (sjdb) |	19
                       Number of splices: GT/AG |	8
                       Number of splices: GC/AG |	11
                       Number of splices: AT/AC |	0
               Number of splices: Non-canonical |	0
                      Mismatch rate per base, % |	9.91%
                         Deletion rate per base |	0.00%
                        Deletion average length |	0.00
                        Insertion rate per base |	0.00%
                       Insertion average length |	1.00
                             MULTI-MAPPING READS:
        Number of reads mapped to multiple loci |	707318
             % of reads mapped to multiple loci |	1.22%
        Number of reads mapped to too many loci |	17576
             % of reads mapped to too many loci |	0.03%
                                  UNMAPPED READS:
       % of reads unmapped: too many mismatches |	0.00%
                 % of reads unmapped: too short |	98.14%
                     % of reads unmapped: other |	0.60%
                                  CHIMERIC READS:
                       Number of chimeric reads |	0
                            % of chimeric reads |	0.00%

**Comment by bbimber** [comment]
Hello - based on some other threads, I'm concluding the most likely problem is one of the "*OverLread" filters.  These default to 0.66.  I'm going to try stronger trimming (through I did trim ends before) and relax those.  Any other ideas or validation you can suggest would be appreciated.

My input is downloaded SRA data and so it uses less standard FASTQ readnames.  They appear to be ordered properly, though it's not clear how/if STAR is parsing the header and if this could cause issues.

**Comment by bbimber** [comment]
Stronger 3' end trimming seems to have fixed this issue.  I did not try changing any filters from defaults, but I assume this indicates lower qual bases at the 3' end were reducing the alignment length relative to input read length.

**Comment by alexdobin** [comment]
Hi @bbimber 

could you please post the first few lines of the read1/read2 fastqs?
Also, have you tried mappig read1/read2 separately?
Such a catastrophically low mapping rate is likely due to some fromatting issues with read1 read2.

Cheers
Alex

**Comment by bbimber** [comment]
hi @alexdobin

below are the first 12 lines of an example pair of FASTQs.  These are what the sra download tool gives us for read names.  Note: see post above about trimming, which made a substantial difference on these data, so i am assuming there is not a readname issue, but am curious if you see a problem:

Fastq-forward:

@SRR5920872.sra.1 1 length=49
TCAAGTTCCAGAAAAACAACATATTGCCGACCTCACGGATTTTTACCAA
+SRR5920872.sra.1 1 length=49
AAAAFJJJFJJJJJJJJJJJJJJJJJJJFJJJJJJJF<JJAFJFJJJJ-
@SRR5920872.sra.2 2 length=49
ATTATGGTGAGTTTAAATGGATAAAATTCATACCTTTAAAAACTGCACT
+SRR5920872.sra.2 2 length=49
AAFFFJJJJJJFFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ
@SRR5920872.sra.3 3 length=49
ATTATGGTGAGTTTAAATGGATAAAATTCATACCTTTAAAAACTGCACT
+SRR5920872.sra.3 3 length=49
AAAFFJJJJJJJJJJJJJJJJJJJJJJJJJJJFFFJJJJJJJJJJJJJJ


Fastq-reverse:
@SRR5920872.sra.1 1 length=49
TGGCAACCACACGGAGGAGGCGAGCGGGCGTTGTGCGTAGATAGAGGAT
+SRR5920872.sra.1 1 length=49
<<-AFJAFJJA7JJJFFJJFJJJFJJJJJFJ<FFJJJJJFF7FJJJFF7
@SRR5920872.sra.2 2 length=49
CCCCTTTCCTTCCCTATGTTGCACATCTCCTTGCAATGTGGTATATGAC
+SRR5920872.sra.2 2 length=49
AAAFFJFJJJJJFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFAJJFJ
@SRR5920872.sra.3 3 length=49
CCCCTTTCCTTCCCTATGTTGCACATCTCCTTGCAATGTGGTATATGAC
+SRR5920872.sra.3 3 length=49
AAAF7JAFJJJJJJFJJJJJJJAJ-FJFJFF77J--<<--<FF<F--7A

**Comment by alexdobin** [comment]
Hi @bbimber 

these look fine indeed. Moreover, I BLATted them against the Rhesus genome and they all mapped perfectly, no trimming required... So my next suspicion is that something is happening in the middle of the file, since only ~1400 reads mapped. You can try to figure out where this happens by changing ```--readMapNumber```, e.g. you can increase it exponentially from 3 (10, 100, 10000, 10000) until you start seeing a reduction in mapping rate, and then find the boundary with a binary search.

Cheers
Alex

**Comment by bbimber** [comment]
sure, not a bad idea

**Comment by bbimber** [comment]
For whatever reason I have not been able to repro this on the latest version.
