### ISSUE TITLE
0 mapped reads

### ISSUE THREAD

**Issue by sgomez0328** [alexdobin/STAR#837]
Hi Alex,

I hope I'm not posting this is the wrong section- I poked around a bit and found some similar problems but didn't find a solution. The problem I am running into may be due to my ignorance, and I apologize if so.

I ran the following STAR parameters:
STAR \
    --runThreadN 16 \
    --genomeDir /groups/chiappinellilab/genomes/hg38/STAR.hg38.index/ \
    --sjdbGTFfile /groups/chiappinellilab/genomes/hg38/gencode.annotation/gencode.v21.primary.assembly.only.annotation.gtf \
    --sjdbOverhang 100 \
    --readFilesIn /lustre/groups/chiappinellilab/processed_data/Steph/SRA.FASTQ/293T_ADAR1KO_IFNb_Rep2_SRR5564260/293T_ADAR1KO_IFNb_Rep2_SRR5564260_R1.cutadapt.fastq /lustre/groups/chiappinellilab/processed_data/Steph/SRA.FASTQ/293T_ADAR1KO_IFNb_Rep2_SRR5564260/293T_ADAR1KO_IFNb_Rep2_SRR5564260_R2.cutadapt.fastq \
--readFilesCommand zcat \
    --outSAMtype BAM Unsorted \
    --outFileNamePrefix /lustre/groups/chiappinellilab/processed_data/Steph/SRA.FASTQ/293T_ADAR1KO_IFNb_Rep2_SRR5564260/293T_ADAR1KO_IFNb_Rep2_SRR5564260.RNAedit.STAR \
    --outFilterMatchNminOverLread 0.95

And this was my output:
[sgomez@login3 293T_ADAR1KO_IFNb_Rep2_SRR5564260]$ cat 293T_ADAR1KO_IFNb_Rep2_SRR5564260.RNAedit.STARLog.final.out
                                 Started job on |	Feb 11 20:40:51
                             Started mapping on |	Feb 11 20:43:29
                                    Finished on |	Feb 11 20:43:31
       Mapping speed, Million of reads per hour |	0.00

                          Number of input reads |	0
                      Average input read length |	0
                                    UNIQUE READS:
                   Uniquely mapped reads number |	0
                        Uniquely mapped reads % |	0.00%
                          Average mapped length |	0.00
                       Number of splices: Total |	0
            Number of splices: Annotated (sjdb) |	0
                       Number of splices: GT/AG |	0
                       Number of splices: GC/AG |	0
                       Number of splices: AT/AC |	0
               Number of splices: Non-canonical |	0
                      Mismatch rate per base, % |	-nan%
                         Deletion rate per base |	0.00%
                        Deletion average length |	0.00
                        Insertion rate per base |	0.00%
                       Insertion average length |	0.00
                             MULTI-MAPPING READS:
        Number of reads mapped to multiple loci |	0
             % of reads mapped to multiple loci |	0.00%
        Number of reads mapped to too many loci |	0
             % of reads mapped to too many loci |	0.00%
                                  UNMAPPED READS:
       % of reads unmapped: too many mismatches |	0.00%
                 % of reads unmapped: too short |	0.00%
                     % of reads unmapped: other |	0.00%
                                  CHIMERIC READS:
                       Number of chimeric reads |	0
                            % of chimeric reads |	0.00%

Based on the log files, STAR is running but I'm not sure why it's not mapping. I've run these parameters successfully before on other fastq files of treated human cell lines. The fastq files that I aligned successfully were 75bp long and had better adapter/quality trimming. The fastq files here that are not aligning (HEK293T cells) are 150 bp long and I used the Illumina universal adapter sequence to trim.

I've attached all of my output log-type files as well as a screenshots of the FastQC output. Please let me know if you need anything else or need any additional information.

![RNAseq A2780 treat1 mock TruSeq5_ACAGTGATCT_S12_R1_cutadapt q20 minlen1_fastqc](https://user-images.githubusercontent.com/59708551/74301105-f81a0080-4d1f-11ea-8379-406b64b33c56.png)
![RNAseq A2780 treat1 mock TruSeq5_ACAGTGATCT_S12_R2_cutadapt q20 minlen1_fastqc](https://user-images.githubusercontent.com/59708551/74301109-f94b2d80-4d1f-11ea-8be6-ad7f58205c18.png)
[293T_ADAR1KO_IFNb_Rep2_SRR5564260.cutadapt.logfile.txt](https://github.com/alexdobin/STAR/files/4189724/293T_ADAR1KO_IFNb_Rep2_SRR5564260.cutadapt.logfile.txt)

Thank you!
Stephanie

**Comment by alexdobin** [comment]
Hi Stephanie

if your files are unzipped, you do not need --readFilesCommand zcat .
This will hopefully fix the problem. 
Please let me know if you encounter any other issues, will be happy to help.

Cheers
Alex

**Comment by sgomez0328** [comment]
Thank you very much Alex, it worked! :)
