### ISSUE TITLE
set the values of  sjdbOverhang 

### ISSUE THREAD

**Issue by QuanLG** [alexdobin/STAR#839]
Hello,
    my data is 2x150b paired-end reads,so I generate the human genome index set the  --sjdbOverhang 150, but there is an **WARNING:** while processing pGe.sjdbGTFfile=/path/to/STAR/gencode.v27lift37.annotation_formal.gtf: overlapping or touching exons:
1       145382056       145382201
1       145382202       145382378
...........................................
so should I use the default value 100 or set other values?
And I want to use the Stringtie for downstream analysis,how can I get the XS tag in the bam.

**Comment by alexdobin** [comment]
Hi @QuanLG 

if there are only a few warnings like this, it's fine. It just a property of the annotation, where some "junction" gaps are 0 for some reason. 

Cheers
Alex

**Comment by QuanLG** [comment]
Thanks Alex,I have  a **stranded library** (fr-firststrand) data, I use tha STAR to mapping genome,and I want the bam have the **XS tag**,so shoule I set --outSAMstrandField intronMotif option? or the stranded library can use the  outSAMstrandField intronMotif option?

**Comment by alexdobin** [comment]
Hi @QuanLG 

--outSAMstrandField intronMotif is independent of the library strandedness, and will only add this flag to spliced alignments. If you want to add this flag to the reads according to the library strandedness, you would need to add it post-mapping. There is a script to do it in the STAR distribution, please see the discussion here:
https://groups.google.com/d/msg/rna-star/t-oT4wUFFow/x8_BdDd0BAAJ

I believe in your case strType=2 (i.e. the 2nd mate has the same strand as RNA).

Cheers
Alex

**Comment by QuanLG** [comment]
Thanks Alex,but I can't download the script **http://labshare.cshl.edu/shares/gingeraslab/www-data/dobin/STAR/STAR.sandbox/extras/scripts/tagXSstrandedData.awk**

**Comment by gjones3339** [comment]
if we do assign --sjdbOverhang in the script does it default to 100? or 0?
