### ISSUE TITLE
std::out_of_range / vector::_M_range_check during genomeGenerate

### ISSUE THREAD

**Issue by chandni177** [alexdobin/STAR#84]
Hi there,

I've been using STAR for a while now, but I have some new GTF files from a collaborator which give this out of range error during the indexing step. 
Upon reading previous posts about similar errors, I made sure the chromosome names were the same, the gtf file sorted. I still get the same error. Not sure what could be going wrong. 

I can send the error message or a part of the gtf file or my command - whichever helps to debug the issue.

Thanks!
Chandni

`
STAR --runThreadN 32 --runMode genomeGenerate --sjdbOverhang 49 --genomeDir GenomeIndex_Try/ --genomeFastaFiles 'GRCm38.p4.genome.fa' --sjdbGTFfile 'testGTF.sorted.gtf'
`

**Comment by alexdobin** [comment]
Hi Chandi,

one of the likely reasons for this problem is the lack of "transcript_id" attribute in some of the exonic lines. If this is not the case, please send me a small part of the GTF that still causes the problem.

Cheers
Alex

**Comment by chandni177** [comment]
Yes, that's true.
But I was assuming that just leads to a warning, not an error.

Here is what the gtf looks like -

``
chr1	RepeatMasker	exon	100000467	100001474	.	-	.	gene_id "LTR/ERVK|RLTR13D5|1|100000467|100001474"; 
chr1	RepeatMasker	exon	100001476	100001763	.	-	.	gene_id "LINE/L1|Lx9|1|100001476|100001763"; 
chr1	RepeatMasker	exon	100001800	100001980	.	+	.	gene_id "SINE/B2|B2_Mm2|1|100001800|100001980"; 
chr1	RepeatMasker	exon	100002005	100002183	.	+	.	gene_id "SINE/B4|ID_B1|1|100002005|100002183"; 
chr1	RepeatMasker	exon	100002229	100002346	.	+	.	gene_id "SINE/B4|B4A|1|100002229|100002346"; 
chr1	RepeatMasker	exon	100002377	100003677	.	-	.	gene_id "LINE/L1|Lx3_Mus|1|100002377|100003677"; 
chr1	RepeatMasker	exon	100003678	100003907	.	-	.	gene_id "LTR/ERVL-MaLR|ORR1B2|1|100003678|100003907"; 
chr1	RepeatMasker	exon	100004201	100004342	.	-	.	gene_id "SINE/Alu|B1_Mus1|1|100004201|100004342";
``

**Comment by alexdobin** [comment]
Hi Chandni,

STAR requires "transcript_id" in each "exon" line of the GTF file. Otherwise it would not know which transcript the exon belongs to, and won't be able to make junctions. I will replace this hard requirement with a warning in the next release. For now, please filter out these lines from the GTF file. Or, add the "transcript_id" to each of these lines, with the value equal to the gene_id - make sure that the exons that belong to the same transcript=gene do not overlap.

Cheers
Alex

**Comment by chandni177** [comment]
I see,
I misunderstood then. Alright, I added the transcript ids to be the same as the gene ids, and it works fine now.

Thanks for helping out!
Chandni

**Comment by chandni177** [comment]
Hi Alex,

I fixed the gtf and it worked fine, but I now have 2 GTF files that need to be a part of the Indexing step.
 Here is the command I use, and I get the same std::out_of_range error once again.

``
STAR --runThreadN 48 --runMode genomeGenerate --genomeDir GenomeIndex/ --genomeFastaFiles 'GRCm38.p4.genome.fa' --sjdbGTFfile <(cat GRCm38.81.chrAdded.gtf GRCm38.78_senseOnlyFiltered_transcriptID_added.gtf)> --sjdbOverhang 49
``

Also - this is how the 2 files look -

GRCm38.81.chrAdded.gtf 
``
chr1	havana	gene	3073253	3074322	.	+	.	gene_id "ENSMUSG00000102693"; gene_version "1"; gene_name "4933401J01Rik"; gene_source "havana"; gene_biotype "TEC"; havana_gene "OTTMUSG00000049935"; havana_gene_version "1";
chr1	havana	transcript	3073253	3074322	.	+	.	gene_id "ENSMUSG00000102693"; gene_version "1"; transcript_id "ENSMUST00000193812"; transcript_version "1"; gene_name "4933401J01Rik"; gene_source "havana"; gene_biotype "TEC"; havana_gene "OTTMUSG00000049935"; havana_gene_version "1"; transcript_name "4933401J01Rik-001"; transcript_source "havana"; transcript_biotype "TEC"; havana_transcript "OTTMUST00000127109"; havana_transcript_version "1"; tag "basic"; transcript_support_level "NA";
``

GRCm38.78_senseOnlyFiltered_transcriptID_added.gtf
``
chr1	RepeatMasker	exon	3000001	3002128	.	-	.	gene_id "LINE/L1|L1MdFanc_I|1|3000001|3002128"; transcript_id "LINE/L1|L1MdFanc_I|1|3000001|3002128";
chr1	RepeatMasker	exon	3003148	3004054	.	-	.	gene_id "LINE/L1|L1MdFanc_I|1|3003148|3004054"; transcript_id "LINE/L1|L1MdFanc_I|1|3003148|3004054";
``

Thanks for the help once again!
Chandni

**Comment by alexdobin** [comment]
Hi Chandni,

not sure if this is still open, since I cannot find this message on GitHub?

Cheers
Alex

**Comment by chandni177** [comment]
Hi Alex,

I just concatenated the 2 files and it worked fine, so I deleted it from
Github.

Thanks for reaching out though!

Chandni

**Comment by alexdobin** [comment]
Hi @Roghaiyeh 

you need to gunzip both the FASTA and GTF file - this is what causes the problem.
e.g. 
ftp://ftp.ensembl.org/pub/release-93/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz

**Comment by Roghaiyeh** [comment]
Thank you Alex.

Cheers
rugi

**Comment by joshuagi** [comment]
Hi,

I managed to figure it out after giving it some more thought. 

The index successfully completed after I assigned entries to a newly created "transcript_id" variable. 
I did it by parsing out the gene name from the "ID" column:

in R:
synth$'transcript_id' <- str_split(synth$ID, pattern = '[.]', simplify = TRUE)[,1]

Josh

**Comment by alexdobin** [comment]
Hi Josh

you figured it out - by default STAR requires transcript_id and gene_id attributes, which are standard for GTF.  In principle, you could change that by specifying 
--sjdbGTFtagExonParentTranscript ID
but it's probably better to have a fully conforming GTF as other tools may rely on it as well.

Cheers
Alex

**Comment by cmandreani** [comment]
Hi Alex, 

I'm willing to use STAR for bacterial genomes. I wanted to ask if this strongly unadvised or if there is a way to manage the main challenges of mapping reads to prokaryotic genomes. (I know there are specific tools for this purpose, but I'm a beginner in bioinformatics and it would significantly simplify the execution of the methodology as STAR is the only tool I've used and it has a very complete manual.) 

I obtained the input data from antismash (GBK) and converted it to GFF3 and FASTA formats. In the third column of the GFF, naturally, there is no Exon feature. However, CDSs correspond to the genes annotated for each sm-BGC (biosynthetic gene cluster that code for specialized metabolites) which is the only feature of interest in my research. I tried to specify this when generating the index with:

STAR --runThreadN 30 --runMode genomeGenerate --genomeDir path_to_genome_directory --genomeFastaFiles path_to_fasta.fa --sjdbGTFfile path_to_GFF.gff --sjdbOverhang 149 --sjdbGTFtagExonParentTranscript Parent --sjdbGTFfeatureExon CDS

But it still appeared the following error message: Fatal INPUT FILE error, no exon lines in the GTF file (...)

Reading the messages above, I also realised that the ninth column of the GFF does not contain "transcript_id" or "gene_id". How can I overcome this? Is it enough to replace "ID" for "transcript_id"?

ISL001_ctg1	GenBank	CDS	8645	8890	.	-	1	ID=ctg1_124; nRPS_PKS=Domain: PP-binding (3-72). E-value: 5.9e-16. Score: 50.6. Matches aSDomain: nrpspksdomains_ctg1_124_PP-binding.1, type: other; Name=ctg1_124; gene_functions=biosynthetic-additional (rule-based-clusters) PP-binding; gene_kind=biosynthetic-additional; sec_met_domain=PP-binding (E-value: 3.3e-15%2C bitscore: 50.6%2C seeds: 164%2C tool: rule-based-clusters); transl_table=11; translation=length.81

More troubling, the ID refers to the name of the gene but not to the genome where it came from: there might be i.e. ISL001_ctg1_124 and ISL002_ctg1_124 and both ID's will be the same. Does the first column account for this, without needing any more details in the ninth to properly map?

Cheers,
Constanza

**Comment by alexdobin** [comment]
Hi Constanza,

the GTF file is only needed for 
1). Annotated splice junctions
2). Quantifying gene expression with ```--quantMode GeneCounts```

If you are not using either, you can safely omit the GTF file.

Cheers
Alex

**Comment by cmandreani** [comment]
Hi Alex, 

I am indeed using --quantMode GeneCounts. I will open another issue with my current problem. Thanks

**Comment by khf0008** [comment]
Hello all,
   Let me begin by saying that I'm brand new to bioinformatics, and this is my first time ever doing an alignment, so please be gentle! Apologies if this is a simple issue or discussed elsewhere. I'm getting the following error when I attempt to index the Drosophila genome:
   
   terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)

Here's the command (I ran it as a script with 48gb of memory):
STAR --runMode genomeGenerate --genomeDir /home/aubkhf/diet_mating/test_align --genomeFastaFiles /home/aubkhf/diet_mating/test_align/dmel-all-chromosome-r6.44.fasta --sjdbGTFfile /home/aubkhf/diet_mating/test_align/dmel-all-r6.44.gtf --sjdbGTFtagExonParentTranscript Parent --sjdbOverhang 100 --runThreadN 8

I *think* I've attached the Log.out file. I've also attached screenshots of my reference genome and .gtf file. Please let me know if I can do anything further, and thanks for your help!

[log.out.txt](https://github.com/alexdobin/STAR/files/8454931/log.out.txt)
<img width="412" alt="dmel ref gen fasta - Copy" src="https://user-images.githubusercontent.com/55117406/162518746-0a6fd606-2224-4a52-bd67-3eb1fec8c17e.PNG">
<img width="950" alt="dmel gtf - Copy" src="https://user-images.githubusercontent.com/55117406/162518748-94f88706-c8b7-4122-bc82-4077708d3dce.PNG">
