### ISSUE TITLE
-- soloFeatures Velocyto

### ISSUE THREAD

**Issue by jmzvillarreal** [alexdobin/STAR#840]
Hi,
I am running the --soloFeatures Gene Velocyto to estimate the spliced, unslipced ans ambiguous counts in order to perform RNA velocity on my dataset. Does the Gene count   should correspond to the sum of spliced, unspliced and ambiguous ? I am getting very few counts for each class... I have the impression tha I am loosing counts somewhere..
Thanks !
Best,
Jaime.

**Comment by alexdobin** [comment]
Hi Jaime,

the Gene counts should be somewhat close to the "Spliced" Velocyto count, while the Unspliced and Ambiguous counts should be generally smaller. Could you plot a scatter plot for Gene vs Spliced on log-log scale?

Cheers
Alex
