### ISSUE TITLE
STARsolo deduplicated reads report

### ISSUE THREAD

**Issue by pati-ni** [alexdobin/STAR#845]
Is there a way to increase verbosity of STARsolo deduplication report?

I think there is a bug which gives me reads not mapping to the transcriptome.

That is the report for my dataset:
```
Number of Reads,463155216
Reads With Valid Barcodes,0.56931
Sequencing Saturation,0.512232
Q30 Bases in CB+UMI,0.933843
Q30 Bases in RNA read,0.895367
Reads Mapped to Genome: Unique+Multiple,0.950876
Reads Mapped to Genome: Unique,0.84252
Reads Mapped to Transcriptome: Unique+Multipe Genes,0.486169
Reads Mapped to Transcriptome: Unique Genes,0.446255
Estimated Number of Cells,46
Reads in Cells Mapped to Unique Genes,206685115
Fraction of Reads in Cells,1
Mean Reads per Cell,4493154
Median Reads per Cell,2084263
UMIs in Cells,100814384
Mean UMI per Cell,2191617
Median UMI per Cell,941447
Mean Genes per Cell,18150
Median Genes per Cell,17064
Total Genes Detected,31168
```

I tried the same bam file using`featureCounts` the same gtf and it read 615 million reads, I guess these are including the multimapped reads, and the following summary:

```
Assigned        334001732
Unassigned_Unmapped     0
Unassigned_MappingQuality       0
Unassigned_Chimera      0
Unassigned_FragmentLength       0
Unassigned_Duplicate    0
Unassigned_MultiMapping 224853614
Unassigned_Secondary    0
Unassigned_Nonjunction  0
Unassigned_NoFeatures   20567206
Unassigned_Overlapping_Length   0
Unassigned_Ambiguity    35648714
```

How does STARsolo annotates reads to the transcriptome or the genome? 

Can this `Reads Mapped to Transcriptome: Unique Genes,0.446255`
be true while `Assigned        334001732` from featureCounts be also true?

**Comment by alexdobin** [comment]
Hi @pati-ni 

STARsolo follows CellRanger's rules to assign reads to genes: the alignment needs to be contained entirely in the gene exons (or follow it's splice junctions). featureCounts, on the other hand, counts all reads that overlap exons - including those that cross an exon-intron boundary. In 10X data the proportion of intronic reads is usually quite high, so I think this will explain the differences that you are observing. CellRanger and STARsolo take a conservative approach by taking into account only 
mRNA reads and discarding the pre-mRNA reads.

Cheers
Alex

**Comment by pati-ni** [comment]
Hi Alex,

thanks for your reply. Does this mean that the equivalent option for getting similar results is the `GeneFull` option?

That is what I got for this. I believe that this is way below than the 350+ Million I got with `featureCounts`
```
cat scrbseq_Solo.out/GeneFull/Summary.csv
Number of Reads,463155216
Reads With Valid Barcodes,0.56929
Sequencing Saturation,0.895821
Q30 Bases in CB+UMI,0.933843
Q30 Bases in RNA read,0.895367
Reads Mapped to Genome: Unique+Multiple,0.950876
Reads Mapped to Genome: Unique,0.84252
Reads Mapped to Transcriptome: Unique+Multipe GeneFulls,0.532083
Reads Mapped to Transcriptome: Unique GeneFulls,0.447325
Estimated Number of Cells,46
Reads in Cells Mapped to Unique GeneFulls,207181099
Fraction of Reads in Cells,1
Mean Reads per Cell,4503936
Median Reads per Cell,2079931
UMIs in Cells,21583966
Mean UMI per Cell,469216
Median UMI per Cell,390991
Mean GeneFulls per Cell,15091
Median GeneFulls per Cell,14877
Total GeneFulls Detected,26598
```

For the record I am not using 10x data but a custom RNAseq protocol for sequencing mRNA.

**Comment by alexdobin** [comment]
Hi @pati-ni 

it seems my explanation was wrong, since - you are right - the GeneFull counts the reads that cross an exon-intron boundary, and it also counts purely intronic reads, which should have given total numbers higher than featureCounts.

What about strandedness of the protocol? What option are you using in featureCounts?
Also, could you run STAR with --quantMode GeneCounts option - this should produce counts (per gene) equal to featureCounts.

Cheers
Alex

**Comment by pati-ni** [comment]
Hi @alexdobin ,

thanks for your support so far! I think I am getting somewhere that is the `head` of the Reads.PerGene.out.tab:

```
N_unmapped      22751879        22751879        22751879
N_multimapping  50185685        50185685        50185685
N_noFeature     20567206        94570449        297976043
N_ambiguous     35648714        14160680        4930971
ENSG00000223972 0       0       0
ENSG00000227232 1       1       0
ENSG00000278267 0       0       0
ENSG00000243485 10      10      0
ENSG00000284332 0       0       0
ENSG00000237613 0       0       0
```

Summing the lines of the file I am getting the following results:
```
tail -n +5 scrbseq_ReadsPerGene.out.tab | cut -d $'\t' -f 2 | awk '{s+=$1} END {print s}'
334001732

np504@login-e-10 ~/rds/rds-np504-ngs-ukdri_metz/scriptseqpilot3/RNAseq_200207/solo2
[15:07] $ tail -n +5 scrbseq_ReadsPerGene.out.tab | cut -d $'\t' -f 3 | awk '{s+=$1} END {print s}'
281486523

np504@login-e-10 ~/rds/rds-np504-ngs-ukdri_metz/scriptseqpilot3/RNAseq_200207/solo2
[15:07] $ tail -n +5 scrbseq_ReadsPerGene.out.tab | cut -d $'\t' -f 4 | awk '{s+=$1} END {print s}'
87310638
```

So 334 million is the the same number with featureCounts! I've tried counting the STARsolo using the Unstranded method and here is the summary file:
```
 $ cat scrbseq_Solo.out/Gene/Summary.csv
Number of Reads,463155216
Reads With Valid Barcodes,0.56932
Sequencing Saturation,0.512518
Q30 Bases in CB+UMI,0.933843
Q30 Bases in RNA read,0.895367
Reads Mapped to Genome: Unique+Multiple,0.950876
Reads Mapped to Genome: Unique,0.84252
Reads Mapped to Transcriptome: Unique+Multipe Genes,0.493114
Reads Mapped to Transcriptome: Unique Genes,0.434915
Estimated Number of Cells,46
Reads in Cells Mapped to Unique Genes,201432975
Fraction of Reads in Cells,1
Mean Reads per Cell,4378977
Median Reads per Cell,2030122
UMIs in Cells,98194886
Mean UMI per Cell,2134671
Median UMI per Cell,918408
Mean Genes per Cell,18531
Median Genes per Cell,17331
Total Genes Detected,33246
```

The only thing that is changing is the sequencing saturation 0.89 to 0.51, which I am not sure what it describes.

**Comment by pati-ni** [comment]
@alexdobin I found the source of the antisense mapped reads. There was a source of contamination in the pool. Thanks a lot for your support. I still think the report in the STARsolo can be improved since it can be a bit misleading in some cases but I think this issue is not relevant now.


Regards
