### ISSUE TITLE
STAR fails with empty output when run on remote mounted drive

### ISSUE THREAD

**Issue by demis001** [alexdobin/STAR#849]
I found STAR fail all the time without any error when I run the mapping  on mounted drive. I have a large space on computer from remote storage that mounted with sshfs with 1G connection.  It creats all the output directories, BUT exit with zero result after loading the genome. 

I attempt to read and write the input and  output on the mounted drive, not on  a local drive. 

The same command run without any problem when I use the local drive. Any idea why?

**Comment by alexdobin** [comment]
Hi Dereje,

this could be a problem with mounted drive not supporting the fifo files that STAR uses for unzipping the gzip files. Are you using the --readFilesCommand zcat?
If so, you could use process substitution: --readFilesIn <(zcat R1.gz) <(zcat R2.gz) 
OR
you can point --outTmpDir to a temp dir on the local drive - though if you plan to run several STAR jobs simultaneously, the temp dirs will have to be distinct.

Cheers
Alex

**Comment by demis001** [comment]
Hi Alex,

Yes,  I  tried both zcat and unpgiz -c. I will look into the fifo file system you suggested on the drive setting. 

Thanks!
@demis001
