### ISSUE TITLE
Mapping improvement

### ISSUE THREAD

**Issue by Tdanis** [alexdobin/STAR#851]
Number of input reads |	150419283
                      Average input read length |	295
                                    UNIQUE READS:
                   Uniquely mapped reads number |	114708996
                        Uniquely mapped reads % |	76.26%
                          Average mapped length |	293.74
                       Number of splices: Total |	131223973
            Number of splices: Annotated (sjdb) |	0
                       Number of splices: GT/AG |	129675664
                       Number of splices: GC/AG |	1170062
                       Number of splices: AT/AC |	39787
               Number of splices: Non-canonical |	338460
                      Mismatch rate per base, % |	0.24%
                         Deletion rate per base |	0.02%
                        Deletion average length |	2.07
                        Insertion rate per base |	0.01%
                       Insertion average length |	2.05
                             MULTI-MAPPING READS:
        Number of reads mapped to multiple loci |	28519403
             % of reads mapped to multiple loci |	18.96%
        Number of reads mapped to too many loci |	320519
             % of reads mapped to too many loci |	0.21%
                                  UNMAPPED READS:
  Number of reads unmapped: too many mismatches |	0
       % of reads unmapped: too many mismatches |	0.00%
            Number of reads unmapped: too short |	6720499
                 % of reads unmapped: too short |	4.47%
                Number of reads unmapped: other |	149866
                     % of reads unmapped: other |	0.10%
                                  CHIMERIC READS:
                       Number of chimeric reads |	0
                            % of chimeric reads |	0.00%

Hello, I have got one naive question, about the above results. Could you suggest me please, any ideas how to improve (Uniquely mapped reads % |	76.26%) and reducethe  (Number of reads unmapped: too shor).

Thank you

**Comment by alexdobin** [comment]
Hi @Tdanis 

your uniquely mapping rate is quite good at ~76% and unmapped rate is low at ~4.5%
The best libraries I have seen have an unmapped rate of >3%.
Your mapped length is very close to the read length and the mismatch rate is low, so I am not sure if you can reduce the unmapped rate significantly...
You can try to reduce --outFilterScoreMinOverLread and  --outFilterMatchNminOverLread from the default 0.66, and you may get a few more mapped reads, but it will be at the cost of letting in poor quality alignments.
If you have annotations, you may get a bit more mappability by using them - this is always recommended. If you do not have annotations, you can try --twopassMode Basic, but this can actually reduce the uniquely mapped reads to increase the multimapping rate.

Cheers
Alex

**Comment by Tdanis** [comment]
Thank you very much for you advice. Have a nice day
