### ISSUE TITLE
STARsolo very different mapping rate from CellRanger, otherwise similar

### ISSUE THREAD

**Issue by johnchamberlin** [alexdobin/STAR#853]
Hello,

I reprocessed the following dataset with STARsolo 2.7.3: 
http://cf.10xgenomics.com/samples/cell-exp/2.1.0/nuclei_2k/nuclei_2k_web_summary.html

From STARsolo, the mapping rate is not good:
Reads Mapped to Genome: Unique+Multiple,0.546346

Cellranger reports 81% mapping to genome.
However, the output is otherwise quite similar (STAR "Gene" vs CellRanger)
Fraction reads in cells, .706 vs .700
Median Genes per cell, 715 vs 775
Median UMI counts per cell, 1028 vs 1127
Est number of cells, 2443 vs 2352
Total UMIs in filtered count matrix: 2860K vs 3015K

```
$STAR --genomeDir $STARREF \
--sjdbGTFfile $GTFFIL \
--soloType CB_UMI_Simple --soloCBwhitelist $WHITELIST --soloUMIlen 10 \
--readFilesIn $CDNA $BCS \
--soloFeatures Gene GeneFull \
--outSAMattributes NH HI nM AS CR UR CB UB GX GN sS sQ sM \
--soloUMIfiltering MultiGeneUMI --soloCBmatchWLtype 1MM_multi_pseudocounts \
--outFileNamePrefix nuc2k. \
--outSAMtype BAM SortedByCoordinate \
--runThreadN 16 --readFilesCommand zcat

```

Log.final.out
```
Started job on |	Mar 09 10:19:41
                             Started mapping on |	Mar 09 10:23:36
                                    Finished on |	Mar 09 10:44:24
       Mapping speed, Million of reads per hour |	342.53

                          Number of input reads |	118742315
                      Average input read length |	98
                                    UNIQUE READS:
                   Uniquely mapped reads number |	58880634
                        Uniquely mapped reads % |	49.59%
                          Average mapped length |	91.70
                       Number of splices: Total |	2083820
            Number of splices: Annotated (sjdb) |	1988870
                       Number of splices: GT/AG |	2012504
                       Number of splices: GC/AG |	12727
                       Number of splices: AT/AC |	1333
               Number of splices: Non-canonical |	57256
                      Mismatch rate per base, % |	1.08%
                         Deletion rate per base |	0.01%
                        Deletion average length |	1.34
                        Insertion rate per base |	0.01%
                       Insertion average length |	1.10
                             MULTI-MAPPING READS:
        Number of reads mapped to multiple loci |	5993811
             % of reads mapped to multiple loci |	5.05%
        Number of reads mapped to too many loci |	90209
             % of reads mapped to too many loci |	0.08%
                                  UNMAPPED READS:
  Number of reads unmapped: too many mismatches |	0
       % of reads unmapped: too many mismatches |	0.00%
            Number of reads unmapped: too short |	53777084
                 % of reads unmapped: too short |	45.29%
                Number of reads unmapped: other |	577
                     % of reads unmapped: other |	0.00%
                                  CHIMERIC READS:
                       Number of chimeric reads |	0
                            % of chimeric reads |	0.00%
```
thanks!
John

**Comment by alexdobin** [comment]
Hi John,

this is strange... did you use the genome FASTA and GTF as CR uses? 
Could you count the number of uniquely mapped reads in the Cell Ranger BAM file to check that they reported the right number?

Since these are nuclei, I think you will see better compatibility for gene-related metrics between GeneFull and CR number.

I will also try to run this dataset to see what's going on.

Cheers
Alex

**Comment by johnchamberlin** [comment]
I did mistakenly use the repeat masked fasta file. Perhaps this had a contribution? I will follow up on this and see if this was the issue.

Mus_musculus.GRCm38.dna_rm.primary_assembly.fa

Cheers,
John

**Comment by johnchamberlin** [comment]
FYI: as far as I can tell, the single nucleus data on 10X website were pre-processed with the standard mRNA annotation, NOT the pre-mRNA annotation. If you run Cellranger with pre-mRNA annotation, it would report intron content as 0%

**Comment by alexdobin** [comment]
Thanks - it seems strange they are using mRNA annotation for nuclei data.

Most definitely, RepeatMasker masks a lot of "repeats" in the introns which are sequenced in nuclei data. Also, CR uses its own "abridged" annotations that exclude some gene categories (most notably pseudogenes) which may affect the results as well. For the best agreement with CR you can use their FASTA and GTF with STARsolo (e.g. inside this distribution http://cf.10xgenomics.com/supp/cell-exp/refdata-cellranger-hg19-3.0.0.tar.gz)
