### ISSUE TITLE
--soloFeatures Velocyto Zero reads mapped

### ISSUE THREAD

**Issue by jenzopr** [alexdobin/STAR#854]
Hi Alex,

I'm currently playing with the `--soloFeatures Gene Velocyto`. According to the `Gene/Summary.csv` and `Velocyto/Summary.csv`, I obtain 97% reads with a valid barcode, and 75% mapped to the genome. However, zero were mapped to `Velocyto` across 8 libraries (samples). I have the feeling that this is very unlikely to happen by chance, so I suspect an error in my processing. How can I track this down? 

Star version is `2.7.3a`, but my `versionGenome` is `2.7.1a`. 

Any help is appreciated :-)
Jens

**Comment by jenzopr** [comment]
Ping @alexdobin

**Comment by alexdobin** [comment]
Hi Jens,

sorry for the belayed reply.
Are you looking at these lines in the Summary.csv for Velocyto?
```
Reads Mapped to Velocyto: Unique+Multipe Velocytos,0
Reads Mapped to Velocyto: Unique Velocytos,0
```
This is a bug, the reported values are wrong. If you look at the columns 3,4,5 of the matrix.mtx, you should be able to see non-zero values there. This post discusses how to load them into python:
https://github.com/alexdobin/STAR/issues/774#issuecomment-549432123

Cheers
Alex

**Comment by jenzopr** [comment]
Hi Alex,

thanks a lot for your reply! 

Yes, I was looking at exactly those lines. The `matrix.mtx` files indeed show non-zero values. Its great that you identified that as a bug - we can continue analysis now :-)

Best,
Jens
