### ISSUE TITLE
--sjdbGTFfile and transcriptome created

### ISSUE THREAD

**Issue by jiaren-zhang** [alexdobin/STAR#855]
Hi I have one question here.  i used --quantMode and --sjdbGTFfile in my STAR run in order to quantify TPM later using RSEM. If the genes in my GTF file are only subsets of full gene list (i removed several for my analysis), does that mean the output Aligned.toTranscriptome.out.bam will only include genes in my gtf file?
Thank you.

**Comment by alexdobin** [comment]
Hi @jiaren-zhang 

that's correct - Aligned.toTranscriptome.out.bam will only contain gene/transcripts that were listed in the GTF file that you used in the --sjdbGTfile option.

Cheers
Alex

**Comment by uros-sipetic** [comment]
Hi @alexdobin I have a follow up question related to this, so I figured not to open a new thread and try and ask here.

When the genome aligned BAM gets mapped to the transcriptome BAM, do all aligned reads from the genome BAM end up in the transcriptome BAM, or only reads that are mapped to annotated regions (from the GTF file)?

I suppose that only reads that map to annotated regions end up in the transcriptome BAM?
If so, what could be the best way to look at reads that do not end up in the transcriptome BAM file (but are mapped to some genomic regions in the genome BAM file)? 
I can keep unaligned reads with `--outSAMunmapped Within ` in the genome BAM file. Can I do anything similar with the transcriptome BAM file? Or use any external tool?

Thank you @alexdobin as always for any answers!!

**Comment by alexdobin** [comment]
Hi @uros-sipetic 

*Aligned.toTranscriptome.out.bam* contains reads that are not mapped at all, but it does not contain reads that are mapped to the genome but not the transcriptiome.
This may look somewhat counterintuitive, but it's what's required by RSEM, whom the *Aligned.toTranscriptome.out.bam*  is mainly designed for.

To get the set of reads that map to genome but not transcrtiptome, is to subtract the set of mapped reads *Aligned.toTranscriptome.out.bam* from the set of mapped reads in *Aligned.out.sam*.

Cheers
Alex

**Comment by uros-sb** [comment]
Thank you @alexdobin again for the help!

**Comment by uros-sipetic** [comment]
Thank you @alexdobin again for the help!
