### ISSUE TITLE
Major runtime slowdown of STAR_2.5.0 vs STAR_2.4.2a when using genomeGenerate

### ISSUE THREAD

**Issue by ndaniel** [alexdobin/STAR#86]
It looks like STAR_2.5.0a is almost two orders of magnitude slower when using `--runMode genomeGenerate` compared to STAR_2.4.2a. I have noticed this effect for small genomes but also for large genomes.

I am not sure if this is a bug or it is by design. Anyway, here it is.

Here is an example for reproducing this slowdown:
```
STAR \
--genomeChrBinNbits 18 \
--genomeSAindexNbases 14 \
--runMode genomeGenerate \
--runThreadN 4 \
--genomeDir /star-test/ \
--genomeFastaFiles /genome.fa \
--outFileNamePrefix /star-results/
```
where:

STAR 2.5.0a [patch](https://github.com/alexdobin/STAR/commit/ebd9473b558f2225e655347d2fa11d6240c0459a)   => runtime: 4 minutes and 40 seconds
STAR 2.4.2a   => runtime: 10 seconds

This test was run on Ubuntu Linux 14.04LTS 64-bit with 24 GB RAM and STAR 2.5.0a was built manually using `make`.

The genome.fa for this test is available [here](https://www.dropbox.com/s/qb60g48xld8hqmx/gene-gene.fa?dl=0).

**Comment by alexdobin** [comment]
Hi Daniel,

the index generation algorithms were changed. For a large real genome it actually is ~30% faster. I think your genome contains a lot of long identical sequences (same gene in many pairs), that what makes it slower. Does it create a serious problem in your pipeline? I can think how to mitigate it.

Cheers
Alex

**Comment by ndaniel** [comment]
Hi Alex,

> the index generation algorithms were changed. For a large real genome 
> it actually is ~30% faster.

I understand.

> I think your genome contains a lot of long identical sequences 
> (same gene in many pairs), that what makes it slower. 

Indeed most of the time it does. Splitting the genome in pieces such that it would not contain identical genes/sequences would not help too much here because it would increase the running time for STAR when aligning the reads (i.e. STAR would be slow because it would have hard times to map the reads on the smaller genomes).

> Does it create a serious problem in your pipeline?

Sadly, it does. I have seen cases where switching from STAR 2.4.2a to STAR 2.5.0a in FusionCatcher, it would increase the running time of STAR  (with genomeGenerate) from 20 minutes to over 4 hours.

> I can think how to mitigate it.

That would be really great and greatly appreciated!

**Comment by alexdobin** [comment]
Hi Daniel,

I will code an option to speed-up genome generation in this case in the next few days.

Cheers
Alex

**Comment by roryk** [comment]
Hi Alex,

Just +1ing this issue and including another example that has an issue for me. It has happened in 2.5.0a and 2.5.0b. The step of index generation can run for over a day without finishing on relatively small genomes such as just chr1 of GRCh37.

Passing it more threads doesn't help, there is only one thread running at 100% CPU and after a day of running it still hasn't finished. 

```
STAR --genomeDir star --genomeFastaFiles chr1.fa --runThreadN 32 --runMode genomeGenerate --genomeSAindexNbases 12
```

[chr1 FASTA](https://dl.dropboxusercontent.com/u/2822886/chr1.fa.gz) and [Log.out](https://dl.dropboxusercontent.com/u/2822886/Log.out) from run taking > 24 hours and not finishing.

**Comment by alexdobin** [comment]
Hi Rory,

this is a different problem from Dan's, and actually I have just (hopefully) fixed it  - please try the latest patch on the master.

I am still working on increasing speed for small genomes, will have it ready probably tomorrow.

Cheers
Alex

**Comment by roryk** [comment]
Hi Alex,

Thanks for the fast fix, that patch fixed it.

**Comment by alexdobin** [comment]
Hi Daniel,

I have reverted the decrease genome generation speed introduced in 2.5.0a.
Please try the latest patch on GitHub master with ---genomeSuffixLengthMax 10000
It should be as fast as 2.4.x versions. You can also decrease this parameter down to your read length to make it even faster.

Cheers
Alex

**Comment by ndaniel** [comment]
I did a quick test and it looks good.

STAR_2.5.0b_modified (using  --genomeSuffixLengthMax 10000 ) gives:
real	0m14.242s
user	0m28.513s
sys	0m1.243s

and STAR_2.4.2a gives:
real	0m15.398s
user	0m17.035s
sys	0m1.647s

Thanks Alex!
