### ISSUE TITLE
Question regarding column 6 in the SJ.out.tab and two-pass mapping

### ISSUE THREAD

**Issue by aleighbrown** [alexdobin/STAR#863]
With STAR when you're doing 2 pass mapping and then reading from the splice junction tabs

For column 6 - when you're doing ```2-pass basic``` this "unannotated" or "annotated" does it refer to the GTF you use, or the GTF + the splice junctions found in the first pass?

**Comment by DarioS** [comment]
Is there a benefit to two-pass mapping, though? I have read if you're already building your genome index supplemented with a transcript database (e.g. GENCODE Genes, RefSeq) then there's no benefit and your analysis takes twice as long as it needs to.

**Comment by aleighbrown** [comment]
Well if you're interested in exploring novel junctions then 2-pass mapping allows additional reads to be mapping to these splice sites...so then yes it's useful. 

I guess if one was only interested in gene expressin maybe not...

On investigation it appears that column 6 includes annotation of both the GTF + the splice junctions found in the first pass for it's 'annotated' or 'unannotated' status. (e.g. you may have a novel junction to your GTF, but it's considered annotated in 2 pass mapping because it was found in the first pass). 

If that's wrong please correct me, I'm only basing this off the annotation of a junction in my data I'm fairly certain is not in the standard human gencode v31 GTF having an annotation status of 1.

**Comment by aleighbrown** [comment]
Closer inspection of the manual also confirms that he junctions found in mapping + GTF are used as the 'annotated' junctions in 2-pass

**Comment by bw2** [comment]
I was also confused by this. The manual describes SJ.out.tab column 6 as  

"column 6: 0: unannotated, 1: annotated (only if splice junctions database is used)"

so I thought 1 = "known junction" in the GTF. 
It would be great if the column description mentioned the 2-pass behavior.
