### ISSUE TITLE
But in unannotated/annotated splice junctions output

### ISSUE THREAD

**Issue by gevro** [alexdobin/STAR#865]
Hi,
I found a bug in the SJ.out.tab splice junctions output. It is annotating the two introns that flank a novel pseudoexon as annotated junctions instead of unannotated. These two novel junctions are definitively not in the original splice junctions reference database. There must be a bug. Let me know if you need more details, but the code should be examined closely.

**Comment by gevro** [comment]
Note that I am running in two pass mode. So alternatively, perhaps STAR is mistakenly saying that junctions it detects during two-pass mode are annotated. However, they should be labeled as unannotated because they are not in the original GENCODE based index.

STAR should distinguish between junctions it finds during two-pass mode from junctions in the original index. The former should still be labeled as unannotated.

**Comment by alexdobin** [comment]
Hi @gevro,

STAR indeed considers the junctions detected in the 1st pass as annotated in the 2nd pass. To find which junctions are annotated from the original GTF, you can compare the junction coordinates in the SJ.out.tab file with the annotated junctions in the sjdbList.out.tab file in the genome index directory.

Cheer
Alex

**Comment by gevro** [comment]
Thank you. Is there a script for this that is part of the STAR package?

**Comment by alexdobin** [comment]
Hi @gevro 

here is an awk one-liner that will add 1 for annotated and 0 for unannotated junctions:
```
awk '{if (ARGIND==1) {sj[$1 "\t" $2 "\t" $3]=0} else {sj1=$1 "\t" $2 "\t" $3; print $0 "\t" (sj1 in sj ? 1 : 0)} }' SJ.out.tab > SJ.out.tab.ann
```

Cheers
Alex

**Comment by gevro** [comment]
Thanks very much.
