### ISSUE TITLE
STAR index succesful but mapping killed, why? 

### ISSUE THREAD

**Issue by shuaizh117** [alexdobin/STAR#866]
Hi, 

I have a problem when mapping using STAR. The reference genome is human and the index was successful. Then I started mapping, the command line I used is as below:

 STAR --runMode alignReads 
--genomeDir /home/zhaos/isilon/SZ/SYBB/STAR_index 
--runThreadN 8
--readFilesIn SRR5657779_trimmed.fq 
--outSAMtype BAM Unsorted 
--outFileNamePrefix SRR5657779.STAR.bam

However, after a few minutes, it says "killed", the tail of the Log.out file is: 

"Genome: size given as a parameter = 3137687906
SA: size given as a parameter = 24613072006
/SAindex: size given as a parameter = 1
Read from SAindex: genomeSAindexNbases=12  nSAi=22369620
nGenome=3137687906;  nSAbyte=24613072006
GstrandBit=32   SA number of indices=5966805334
Shared memory is not used for genomes. Allocated a private copy of the genome.
Genome file size: 3137687906 bytes; state: good=1 eof=0 fail=0 bad=0
Loading Genome ... done! state: good=1 eof=0 fail=0 bad=0; loaded 3137687906 byt
SA file size: 24613072006 bytes; state: good=1 eof=0 fail=0 bad=0
Loading SA ... done! state: good=1 eof=0 fail=0 bad=0; loaded 24613072006 bytes
Loading SAindex ... done: 97867203 bytes
Finished loading the genome: Wed Mar 25 12:02:57 2020

Processing splice junctions database sjdbN=383200,   sjdbOverhang=49
alignIntronMax=alignMatesGapMax=0, the max intron size will be approximately det
winBinNbits=16 > genomeChrBinNbits=0   redefining:
winBinNbits=0
(END)
"

I wonder what could be the problem? I ran STAR on our insitution's hpc server.

**Comment by alexdobin** [comment]
Hi @shuaizh117 

did you generate the genome on the same server? It takes more slightly more RAM to generate the genome than to map, so if the former worked, that latter should have worked as well. How much RAM are you requesting from the server? You would need to request 32GB.

Cheers
Alex

**Comment by shuaizh117** [comment]
Hi @alexdobin 

Thank you for your reply. I figured it out. I didn't really set genomeChrBinNbits when I was doing genome index (I guess that was why it says genomeChrBinNbits=0 when I did mapping?) I went back and re-did the genome index with genomeChrBinNbits=14 according to your formula, and then I did map again (no other settings changed) and the mapping worked.

**Comment by alexdobin** [comment]
Hi @shuaizh117 

great, thanks for letting me know.

Cheers
Alex
