### ISSUE TITLE
Question --help

### ISSUE THREAD

**Issue by portah** [alexdobin/STAR#87]
Hi,
I'm working on CWL(http://commonwl.org/) wrapper for STAR. I have a question can I somehow to get whole list of possible args for it?

Thanks

**Comment by alexdobin** [comment]
Hi Andrey

2.5.0a has the --help option implemented, it actually lists all the possible arguments, their default and possible values. You can also a get it as a file, parametersDefault, in the source/ directory.

Cheers
Alex
