### ISSUE TITLE
STAR genome index Error

### ISSUE THREAD

**Issue by sallyey** [alexdobin/STAR#872]
Hi Alex,

I am running my genome indexing STAR code in a company's cluster:
STAR --runThreadN 12 --runMode genomeGenerate --genomeDir /home/id/ 
--genomeFastaFiles /home/id/GRCm38.primary_assembly.genome.fa --sjdbGTFfile /home/id/gencode.vM24.primary_assembly.annotation.gtf --sjdbOverhang 100

(I increased the number of thread from 1 to 12, since I kept having same issues below)

Since I need to submit the job in SGE cluster system, I used the command to submit the job:
qsub -V -cwd -l h_vmem=36G prepare_STAR.sh 

And I got the consistent error message:

Apr 01 08:44:03 ..... started STAR run 
Apr 01 08:44:03 ... starting to generate Genome files 
Apr 01 08:45:09 ... starting to sort Suffix Array. This may take a long time... 
Apr 01 08:45:25 ... sorting Suffix Array chunks and saving them to disk... 
Apr 01 09:10:06 ... loading chunks from disk, packing SA...

EXITING because of FATAL problem while generating the suffix array The number of indices read from chunks = 2269570266 is not equal to expected nSA=5305567000 SOLUTION: try to re-run suffix array generation, if it still does not work, report this problem to the author

Apr 01 09:10:49 ...... FATAL ERROR, exiting

From your advice in previous similar issues posted here, I noticed that I might need ~100GB to resolve the issue. 
How can I assign ~100GB to the SGE cluster? I used the command "h_vmem=36G" to assign the maximum amount of memory a slot can take as 36G. When I tried to set it as "h_vmem=100G", I was unable to make the job run in the cluster.

Could you please help me resolve this problem? Your time and effort will be greatly appreciated!
Thank you very much.

**Comment by alexdobin** [comment]
Hi @sallyey 

you need to have ~100GB available on the /home/id/, where the temp files are written. This partition is not local to the cluster nodes, right? So you can simply check how much space is available, e.g. with
```$ df /home/id```

Cheers
Alex

**Comment by sallyey** [comment]
Thanks so much, Alex.

I requested IT team to give me more space to run the code and I successfully ran it.
Thanks for your time and effort!
