### ISSUE TITLE
error when running STAR

### ISSUE THREAD

**Issue by ChongJenniferZhang** [alexdobin/STAR#877]
Hi,

I was using STAR v2.7.3a with commands:
"/software/STAR-2.7.3a/source/STAR   --quantMode TranscriptomeSAM GeneCounts  --outFilterType BySJout    --twopassMode Basic --genomeDir /path2/genomeDIr  --genomeFastaFiles hg19Addvirus.fa  --readFilesCommand zcat --outSAMtype BAM SortedByCoordinate --sjdbGTFfile gencode.v28lift37.annotation.gtf    --outReadsUnmapped None  --readFilesIn  $R1.fq $R2.fq --outFileNamePrefix  $output --chimOutType SeparateSAMold"

But errors are reported
"EXITING because of FATAL ERROR: cannot insert sequence on the fly because of strand GstrandBit problem
SOLUTION: please contact STAR author at https://groups.google.com/forum/#!forum/rna-star"

Could you please tell me how to proceed?
Many thanks.

Best,
Jennifer

**Comment by alexdobin** [comment]
Hi Jennifer,

have you used the gencode.v28lift37.annotation.gtf GTF file at the genome generation step? If so, you do not need to use it again at the mapping stage - this may have caused the problem.

Cheers
Alex

**Comment by neeeeeeko** [comment]
Hi,

I see the same erro report  with commands:
"/data6_213/sunmw2/biosoft/STAR-2.7.5b/bin/Linux_x86_64/STAR --runThreadN 5 --genomeDir /data6_213/sunmw2/biosoft/STAR-2.7.5b/STAR_index --genomeFastaFiles /data6_213/sunmw2/biosoft/STAR-2.7.5b/STAR_index/hg38.fasta --readFilesCommand zcat --readFilesIn /data6_213/sunmw2/be/off/Cleandata/1-Blank/1-Blank_R1.fq.gz /data6_213/sunmw2/be/off/Cleandata/1-Blank/1-Blank_R2.fq.gz --sjdbFileChrStartEnd /data6_213/sunmw2/be/off/aligned/tab/sample2.tab --outFileNamePrefix /data6_213/sunmw2/be/off/aligned/a2 --outSAMtype BAM SortedByCoordinate --sjdbOverhang 149 --twopassMode Basic" 
I am sure after generate the genome index I never set gtf file.Is that a version problem or something? Also it stuck in "loading genome".
Thank you so much!

Warm Regards
Neko

**Comment by neeeeeeko** [comment]
@alexdobin 
I see the same erro report  with commands:
"/data6_213/sunmw2/biosoft/STAR-2.7.5b/bin/Linux_x86_64/STAR --runThreadN 5 --genomeDir /data6_213/sunmw2/biosoft/STAR-2.7.5b/STAR_index --genomeFastaFiles /data6_213/sunmw2/biosoft/STAR-2.7.5b/STAR_index/hg38.fasta --readFilesCommand zcat --readFilesIn /data6_213/sunmw2/be/off/Cleandata/1-Blank/1-Blank_R1.fq.gz /data6_213/sunmw2/be/off/Cleandata/1-Blank/1-Blank_R2.fq.gz --sjdbFileChrStartEnd /data6_213/sunmw2/be/off/aligned/tab/sample2.tab --outFileNamePrefix /data6_213/sunmw2/be/off/aligned/a2 --outSAMtype BAM SortedByCoordinate --sjdbOverhang 149 --twopassMode Basic" 
I am sure after generate the genome index I never set gtf file.Is that a version problem or something? Also it stuck in "loading genome".
Thank you so much!
