### ISSUE TITLE
Add feature type as 3rd column to features.tsv

### ISSUE THREAD

**Issue by kehey** [alexdobin/STAR#882]
Hi @alexdobin,

would you be okay with adding the feature type (like 'Gene Expression') as a third column to the features.tsv output ([code](https://github.com/alexdobin/STAR/blob/49dc707ce9cdeba5659a5d58cc446a86bbd38c96/source/SoloFeature_outputResults.cpp#L35))

It would improve the status of CellRanger drop-in replacement as a number of tools (e.g scanpy, dropletUtils) are expecting this column to be filled out for reading using their 10X native reading methods.

It seems that would also make sense to specify since count values could in fact also be e.g. the CRISPR counts. Even if STARSolo does not calculate the others, it seems okay to annotate the Gene Expression ones as being thus.

Or are there reasons to specifically not do this?

**Comment by alexdobin** [comment]
Hi @kehey 

good suggestion, I will add it in the next release. The formatting changed in CellRanger v3 compared to v2, which did not have that column.

Cheers
Alex

**Comment by alexdobin** [comment]
Hi @kehey 

added the 3rd column "Gene Expression" to match CellRanger output. Please check it out on master, will make an official release shortly.

Cheers
Alex

**Comment by kehey** [comment]
Great! I do notice that it is hard coded. 

Will this potentially cause issues when people would try to run a CRISPR experiment through STAR? Cfr. https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/algorithms/crispr

**Comment by alexdobin** [comment]
Hi @kehey,

I am not sure how is the "CRISPR" assay different from the 10X RNA-seq.
I guess I could make this 3rd field optional.

Cheers
Alex

**Comment by alexdobin** [comment]
Hi @kehey 

the 3rd field in the feature.tsv is optional in the 2.7.5a release.

Thanks!
Alex
