### ISSUE TITLE
Problem running STAR alignment for a collection of genomes

### ISSUE THREAD

**Issue by fataltes** [alexdobin/STAR#888]
Dear Alex,

Thanks for all of your work on STAR.

We were running a bunch of experiments over variable types of data; transcriptome, genome, and metagenome data.
STAR works beautifully on transcriptome and genome data, but we can't seem to make it work on the metagenomic sample that we have.

We have tried a series of different options suggested in the manual or in the discussion forums for running over a large number of genomes or genomes with various sizes. However, each time we get into trouble either constructing the index or later aligning to it. This could either be the result of not using the proper combination of options or maybe some issue that you might want to look into it.

The dataset is a combination of `4,000` complete bacteria genomes randomly selected from NCBI bacteria database. The fasta file is `14G` with the smallest sequence being of length `1,326` and the longest one being of length `12,012,215` bases.

The command we ended up constructing the STAR index with is the following:

```
> /usr/bin/time STAR --runThreadN 16 --runMode genomeGenerate --genomeFastaFiles <fasta_file(.fna)> --genomeDir <index_dir> --genomeSAindexNbases 1 --limitGenomeGenerateRAM 300000000000
```

And this is the log produced by STAR:
```
Apr 16 16:39:05 ..... started STAR run
Apr 16 16:39:05 ... starting to generate Genome files
Apr 16 16:43:07 ... starting to sort Suffix Array. This may take a long time...
Apr 16 16:44:29 ... sorting Suffix Array chunks and saving them to disk...
Apr 17 06:48:44 ... loading chunks from disk, packing SA...
Apr 17 06:55:57 ... finished generating suffix array
Apr 17 06:55:57 ... generating Suffix Array index
Apr 17 06:55:57 ... completed Suffix Array index
Apr 17 06:55:57 ... writing Genome to disk ...
Apr 17 06:56:13 ... writing Suffix Array to disk ...
Apr 17 07:10:34 ... writing SAindex to disk
Apr 17 07:10:44 ..... finished successfully
578847.06user 20984.32system 14:31:42elapsed 1146%CPU (0avgtext+0avgdata 263385468maxresident)k                                          
6869488inputs+729003984outputs (0major+11647212205minor)pagefaults 0swaps                                                       
```
The final index size is ~`133G`. 

The command we used to align our sample is the following:
```
> /usr/bin/time STAR  --runThreadN 16 --alignEndsType EndToEnd --alignIntronMax 1 --outFilterMultimapNmax 1000 --outFilterMismatchNmax 1000 --outFilterMismatchNoverReadLmax 0.20 --alignMatesGapMax 1000 --outMultimapperOrder Random --outSAMmultNmax 1 --genomeDir <index_dir> --readFilesIn <r1.fastq> <r2.fastq> --outFileNamePrefix <outputDir>
```
It is over a paired-end read set with `1,012,176` reads of length `100` where the total size of the two fastq files is `842M`.

At alignment time, it takes ~`20` minutes to load the index and the alignment fails after `1h 13m` segfaulting while it has produced about `251,694` alignments (lines of valid alignment in the SAM output per each end separately) in the output sam file. The reported memory for the alignment using `/usr/bin/time` is about the same as the index size (a few gigs over). We have also tried running the alignment with a different value for option `--outSAMmultNmax`, `20`. Getting a segfault there too.

For constructing the index, originally we tried with `--genomeSAindexNbases 9` where 9 is calculated using the equation provided in section 2.2.5 of the [STAR manual]( https://github.com/alexdobin/STAR/blob/master/doc/STARmanual.pdf) setting the minimum sequence length to `1326`. The size of the index, in this case, is `252G` and we get segfault again at the alignment time. The system we are running these commands on has `500G` of memory.

We would be thankful if you would let us know if there is some way we should be setting the indexing / alignment options differently for this data, or if something else is going on.

Thank you,
Fatemeh

**Comment by alexdobin** [comment]
Hi Fatemeh,

not sure if --genomeSAindexNbases 1 works, but --genomeSAindexNbases 9 should have worked for such a large genome, even the default 14 should have worked. The size that enters into the --genomeSAindexNbases is the total genome size. 
Can you send me the Log.out file of the mapping run?
Can you try to run it on a small subset of fastas, say 400 out of 4,000?

I am afraid I will need to reproduce the problem locally - could you share the FASTA file... or maybe a script to load these files from NCBI.

Cheers
Alex

**Comment by fataltes** [comment]
Thank you, Alex, for the quick reply.

I'm attaching the log for the mapping (both the one generated by STAR and the stderr log) as well as the list of the reference IDs for the 4k.
[star_stderr.log](https://github.com/alexdobin/STAR/files/4542685/star_stderr.log)
[starLog.out](https://github.com/alexdobin/STAR/files/4542687/starLog.out.txt)
[names_selected_complete_genome.txt](https://github.com/alexdobin/STAR/files/4542690/names_selected_complete_genome.txt)

I also built the index for the first 400 references and ran the alignment. Same thing happened: segfault.

Originally, to set the value for --genomeSAindexNbases, I used the sum of the length of all the 4k sequences as the input, but the index construction failed there. So in my next attempt, with the reasoning that the data is

 different from list of chromosomes or genes for one genome and each sequence is a separate genome, instead, I chose the length of the shortest sequence (As the smallest genome in the list).

We also ran STAR under GDB, and obtained the following backtrace:

```
Thread 4 "STAR" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffc1f5f0700 (LWP 13222)]
0x00000000004456e2 in compareSeqToGenome(Genome&, char**, unsigned long long, unsigned long long, unsigned long long, unsigned long long, bool, bool&) ()
(gdb) bt
#0  0x00000000004456e2 in compareSeqToGenome(Genome&, char**, unsigned long long, unsigned long long, unsigned long long, unsigned long long, bool, bool&) ()
#1  0x0000000000445d1d in maxMappableLength(Genome&, char**, unsigned long long, unsigned long long, unsigned long long, unsigned long long, bool, unsigned long long&, unsigned long long*) ()
#2  0x000000000048845a in ReadAlign::maxMappableLength2strands(unsigned long long, unsigned long long, unsigned long long, unsigned long long, unsigned long long, unsigned long long&, unsigned long long)
    ()
#3  0x000000000047a9cb in ReadAlign::mapOneRead() ()
#4  0x000000000048d98d in ReadAlign::oneRead() ()
#5  0x0000000000483854 in ReadAlignChunk::mapChunk() ()
#6  0x00000000004802b1 in ReadAlignChunk::processChunks() ()
#7  0x00000000004c9629 in ThreadControl::threadRAprocessChunks(void*) ()
#8  0x00007ffff6ed06ca in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#9  0x00007ffff6c0acaf in clone () from /lib/x86_64-linux-gnu/libc.so.6
(gdb)
```

Please let us know if you need any more information.

Thank you for your time,
Fatemeh

**Comment by alexdobin** [comment]
Hi Fatemeh,

sorry for the delay. I have generated the genome for the first 400 genomes in your list with --genomeSAindexNbases 9 , and mapped some random reads to it. The seg-fault did not happen for these reads. Could you send me a small subset of your reads which still causes the seg-fault?

Thanks
Alex

**Comment by fataltes** [comment]
Hi Alex,
Thank you so much for your effort. That's strange that the segfault didn't happen.
Here are the simulated reads I'm trying to align: https://drive.google.com/open?id=1M2maIUj2xbeaGAiY3BooG-Y_3if-cfam
It's only ~1M reads! 

Can you please let me know the required memory and intermediate disk-space (if any) for the alignment? Also, did you notice anything specific in the log files?

Thank you,
Fatemeh

**Comment by alexdobin** [comment]
Hi Fatemeh,

mapped the reads to the 400 genomes, still no seg-fault.
Could you please send me the Log.out file for mapping these reads to the 400 genomes?
I will try to match the 400 genomes to yours.

Thanks!
Alex

**Comment by fataltes** [comment]
Hi Alex,

This is strange!
I've uploaded the fasta file on my [google drive](https://drive.google.com/open?id=1tITNZIHc_9VDp1THdNrcFCbFQcDKpTrK) along with the two log files generated by STAR.

You already have the reads. So if you can't replicate the segfault .. then I really don't know what else we can do to track it down. :(

Thank you,
Fatemeh

**Comment by alexdobin** [comment]
Hi Fatemeh,

Thanks for the files - I could reproduce the problem, and finally fixed it. This was the long-standing problem with seg-faults in small genomes. Please try the patch on github master. You would need to re-generate the genome index. The official release to follow in a few days.

Cheers
Alex

**Comment by fataltes** [comment]
Hi Alex,

Apologies for the late reply. 
We pulled the new release and were able to run STAR for all of our samples. It was amazing.

Thank you so so much for your careful effort and time put on each issue.
I think it's now time to close the issue.

**Comment by alexdobin** [comment]
Hi Fatemeh,

thanks a lot for your help with debugging this problem. It was an important bug to fix!

Cheers
Alex
