### ISSUE TITLE
Segmentation fault with some input files

### ISSUE THREAD

**Issue by nataschamay** [alexdobin/STAR#89]
Hi Alex,

We have been using STAR successfully for mapping Illumina reads.
Thank you for a really useful software! :)

Recently, we started working with Isoseq data, so I followed the recommendations by PacBio (1), using the latest version of STAR (v2.5).
*Ref(1): https://github.com/PacificBiosciences/cDNA_primer/wiki/Bioinfx-study:-Optimizing-STAR-aligner-for-Iso-Seq-data*

Initially, I kept getting "Segmentation fault" errors, but after several rounds of trials and decreasing both the genomeSAindexNbases and genomeChrBinNbits to 10 during genomeGenereate, I managed to get STARlong to work for a small file (test.fasta). 

However, when I try the same STARlong mapping command on a larger file (test2.fasta), the "Segmentation fault" error happens again.

Is there anything else I could do to try to get it working? 

Thank you!

~ Natascha

----------------------------------------------
Below are more details about my job:

1. Our reference genome assembly size is 1.2Gb, and has 37,502 sequences.

2. The difference between the two test files are listed below:
**test.fasta**
Number of sequences:      30
Max length:     3726 bp
Average length: 1923 bp
**test2.fasta**
Number of sequences:      8729
Max length:     6255 bp
Average length: 2881 bp

3. **STARlong command**
/data/software/STAR-STAR_2.5.0a/bin/Linux_x86_64/STARlong \
--runMode alignReads \
--readNameSeparator space \
--outSAMattributes NH HI NM MD \
--outFilterMultimapScoreRange 1 \
--outFilterMismatchNmax 2000 \
--scoreGapNoncan -20 \
--scoreGapGCAG -4 \
--scoreGapATAC -8 \
--scoreDelOpen -1 \
--scoreDelBase -1 \
--scoreInsOpen -1 \
--scoreInsBase -1 \
--alignEndsType Local \
--seedSearchStartLmax 50 \
--seedPerReadNmax 100000 \
--seedPerWindowNmax 1000 \
--alignTranscriptsPerReadNmax 100000 \
--alignTranscriptsPerWindowNmax 10000 \
--genomeDir STAR_Genome_Index_bin10_SAindex10 \
--readFilesIn test.fasta

**Comment by alexdobin** [comment]
Hi Natascha,

please try the latest patch from GitHub master, I have fixed a bug in STARlong that was seg-faulting in some cases. If this does not help, please send me the Log.out files from both genome generation and mapping steps.

Cheers
Alex

**Comment by nataschamay** [comment]
Hi Alex,

It works now! Thank you very much for your help :)

~ Natascha
