### ISSUE TITLE
How can I assign reads to both genes, when they overlap in STARsolo 

### ISSUE THREAD

**Issue by piyushjo15** [alexdobin/STAR#890]
Hi Alex,

I am using Cellranger for snRNA-seq with premRNA annotation. I realized that in case of overlapping genes, only the longest gene is being counted, as the overlapped reads are discarded. I wanted to ask how  --soloFeatures GeneFull tag it will assign the reads in case of  overlapping genes or discard them? For example, zUMIs first assign the reads to exonic features and then looks at the reads to align to introns. I was wondering what is the default behavior of STARsolo read assignment is? 
Thanks for helping!

**Comment by alexdobin** [comment]
Hi @piyushjo15 

STARsolo will also discard reads that map to overlapping genes. There is no simple way to count them, unfortunately.

Cheers
Alex

**Comment by piyushjo15** [comment]
Yes, I saw that after running the comparison.

**Comment by piyushjo15** [comment]
Just wanted to add my work around the problem.

The problem for snRNA-seq is:
If we use exonic annotation, we get low counts.
If we use pre-mRNA annotation, we get higher counts; but the genes whose exons lies in introns of other (see SOX2-OT and SOX1; HOXA3/4/5/6); don't get counted as reads that could be assigned to exon of one is gene can now also be assigned to intron of other and hence discared.

Work around:
The exonic read of the overlapped inferior (smaller) genes (for example; SOX2) are being captured in the "Gene" folder; lets say `count.ex` marix. The exonic plus intronic read overlapping superior (longer) gene (SOX2-OT for SOX2) is being counted in intronic, `counts.in` matrix. SOX2-OT exonic reads are also being counted in `counts.ex`; so simple addition of `counts.ex` and `counts.in` will inflate SOX2-OT readings.
SOX2 is not being counted at all in `counts.in` and only being counted in `counts.ex`; so simply replacing SOX2 reads in `counts.in` from `counts.ex` will give us reads for both SOX2 and SOX2-OT in one file.
```

library(Matrix)
#load GeneFull raw reads (pre-mRNA alignments)
counts.in <- read_10x("GeneFull/raw/")
dim(counts.in)
# load Gene raw reads (exonic alignments)
counts.ex <- read_10x("Gene/raw/")
dim(counts.ex)

#check colnames
table(colnames(counts.in) ==colnames(counts.ex))
#check rownames
table(row.names(counts.in) == row.names(counts.ex))

#finding genes that were not counted in intronic marix
mean.in <- Matrix::rowMeans(counts.in)
d <- (mean.in==0)
table(d)
#replacing zero mean count gene data in intronic matrix from
#exonic matrix
counts.in <- counts.in[!d,]
dim(counts.in)
counts.ex <- counts.ex[d,]
dim(counts.ex)

counts.in <- rbind(counts.in,counts.ex)
dim(counts.in)

```
This is what we really wanted from intronic + exonic alignments. The reads that are aligning with SOX2 and SOX2-OT introns would not be able to assign unambiguously, hence they are still being discarded.

**Comment by alexdobin** [comment]
Hi @piyushjo15 

good idea, thanks for sharing! I think I should probably implement such a policy as another "feature" option for STARsolo: if a read overlaps exons of one gene and introns of another, it is counted towards the former gene.

Cheers
Alex

**Comment by raivivek** [comment]
Hi @alexdobin Wondering if this feature was ever implemented? If not, what would be the recommended approach to handle such scenario?

**Comment by alexdobin** [comment]
Hi Vivek,

I have implemented it but still testing, hoping to release it next week.

Cheers
Alex
