### ISSUE TITLE
BUG: next index is smaller than previous, EXITING

### ISSUE THREAD

**Issue by KatyBrown** [alexdobin/STAR#893]
Hi,
I am trying to build an index for GRCh38.p13 based on the latest version of Gencode (v33).  I am using the PRI fasta file and PRI gtf.  I am running STAR 2.7.3a on Fedora 23 with 64GB of RAM across 8 cores. 

I keep seeing the following error after about an hour:
```
BUG: next index is smaller than previous, EXITING

Apr 24 00:51:30 ...... FATAL ERROR, exiting
```

My STAR command is 
`STAR --runThreadN 8 --runMode genomeGenerate --genomeDir STAR --genomeFastaFiles GRCh38.primary_assembly.genome.fa  --sjdbGTFfile gencode.v33.primary_assembly.annotation.gtf --sjdbOverhang 100 --limitGenomeGenerateRAM 40000000000`

My Log.out is attached.

Thanks very much,
Katy

[Log.out.txt](https://github.com/alexdobin/STAR/files/4528541/Log.out.txt)

**Comment by alexdobin** [comment]
Hi Katy,

not sure what's going here, I had generated the genome for these exact FASTA and GTF, and there was no problem... A few things to try:
1. Rerun in an empty output directory (one you specify in --genomeDir) without --limitGenomeGenerateRAM 40000000000. Make sure that no other STAR jobs are running.
2. Compile STAR executable locally, using make in the source/ directory - it will generate executable source/STAR

Cheers
Alex

**Comment by KatyBrown** [comment]
Hi Alex,
Thanks very much for your reply.

It eventually worked by downloading Gencode release 34 instead of 33 and using a new clean install of STAR from source.  

Katy
