### ISSUE TITLE
Print STAR Version?

### ISSUE THREAD

**Issue by bbimber** [alexdobin/STAR#896]
Hello,

Is there an option to either make STAR print the current version (i.e. STAR --version), or does it log the version in normal STDERR in some form I'm just not seeing?  I ask b/c we'd like to track this in our job logs, so we have a record of what was actually used.

Thanks,
Ben

**Comment by ColeWunderlich** [comment]
`STAR --version` prints the version for me.  I'm using `2.7.3a`.

**Comment by bbimber** [comment]
Sorry, somehow i completely missed that.
