### ISSUE TITLE
STAR does not terminate when running under parrot_run

### ISSUE THREAD

**Issue by natefoo** [alexdobin/STAR#897]
This is a bit obscure, but seems to be similar to the issue reported on #627, except that no version (dynamic, static, or locally compiled) solves the issue. Essentially, running STAR under the [cctools Parrot](https://cctools.readthedocs.io/en/latest/parrot/) tool causes a similar issue where STAR apparently runs to completion but doesn't terminate.

We have STAR (in this case 2.6.0b, because we haven't yet built indexes for 2.7) installed from Bioconda into CVMFS, and indexes stored in CVMFS as well. cctools' `parrot_run` is used to "fake" mount CVMFS on HPC systems where we run STAR but don't have root privileges to properly mount CVMFS.

A run with some test data and hg19 indexes looks like:

```console
$ export PARROT_CVMFS_REPO="data.galaxyproject.org:url=http://cvmfs1-psu0.galaxyproject.org/cvmfs/@fqrn@/,pubkey=$HOME/data.galaxyproject.org.pub main.galaxyproject.org:url=http://cvmfs1-psu0.galaxyproject.org/cvmfs/@fqrn@/,pubkey=$HOME/main.galaxyproject.org.pub"
$ export PARROT_ALLOW_SWITCHING_CVMFS_REPOSITORIES=yes
$ export PARROT_CVMFS_ALIEN_CACHE=/tmp/cvmfs
$ $HOME/cctools-7.1.2-x86_64-centos7/bin/parrot_run bash
$ . /cvmfs/main.galaxyproject.org/deps/_conda/bin/activate /cvmfs/main.galaxyproject.org/deps/_conda/envs/mulled-v1-b0db0252c036e828bd636008a91dcc510a9fc0e3f41eab2161dc707e5ec49628
$ STAR --runThreadN 4 --genomeLoad NoSharedMemory --genomeDir /cvmfs/data.galaxyproject.org/managed/rnastar_index2/hg19/dataset_950899_files --readFilesIn $HOME/forward.fastq $HOME/reverse.fastq --outSAMtype BAM SortedByCoordinate --sjdbOverhang 100 --sjdbGTFfile $HOME/model.gtf
```

STAR appears to run normally until:

```
May 01 16:45:57   Finished inserting junction indices
May 01 16:46:01   Finished SAi
May 01 16:46:01 ..... finished inserting junctions into genome
Created thread # 1
Created thread # 2
Created thread # 3
Thread #1 end of input stream, nextChar=-1
Completed: thread #2
Completed: thread #3
Completed: thread #0
```

Parrot works through the use of `ptrace` and so I suspect something it's doing is interfering with STAR's use of threads, but was wondering if there's something I could try to debug further.

**Comment by alexdobin** [comment]
Hi Nate,

I have not encountered this issue again.
This job did not complete successfully, it got stuck before or during BAM sorting.
So I would try it without --outSAMtype BAM SortedByCoordinate to see if the problem is with sorting.
Also, if you could try 2.7.3a, it would be great, maybe the problem just disappeared. :)

Cheers
Alex

**Comment by natefoo** [comment]
Hi Alex,

I've just given it a try with 2.7.3a and unfortunately the result is similar:

```
May 27 13:52:01   Finished preparing junctions
May 27 13:52:01 ..... inserting junctions into the genome indices
May 27 13:52:02   Finished SA search: number of new junctions=11745, old junctions=0
May 27 13:52:09   Finished sorting SA indicesL nInd=4698000
Genome size with junctions=3282306473  3279945728   2360745
GstrandBit1=32   GstrandBit=32
May 27 13:53:10   Finished inserting junction indices
May 27 13:53:17   Finished SAi
May 27 13:53:17 ..... finished inserting junctions into genome
Created thread # 1
Created thread # 2
Created thread # 3
Thread #1 end of input stream, nextChar=-1
Completed: thread #2
Completed: thread #0
Completed: thread #3
```

Any thoughts on what to try from here?

**Comment by alexdobin** [comment]
Hi Nate,

I think the next thing to try is to use just one thread, with --runThreadN 1
Also, have you tried it without --outSAMtype BAM SortedByCoordinate ?

Cheers
Alex

**Comment by natefoo** [comment]
Hi Alex,

I get the same result using 1 thread and without `--outSAMtype`:

```console
$ STAR --runThreadN 1 --genomeLoad NoSharedMemory --genomeDir /cvmfs/sandbox.galaxyproject.org/index/hg38/star-2.7 --readFilesIn $SCRATCH/star-test/forward.fastq $SCRATCH/star-test/reverse.fastq --sjdbOverhang 100 --sjdbGTFfile $SCRATCH/star-test/model.gtf

...

May 28 09:29:05   Finished preparing junctions
May 28 09:29:05 ..... inserting junctions into the genome indices
May 28 09:29:07   Finished SA search: number of new junctions=11745, old junctions=0
May 28 09:29:13   Finished sorting SA indicesL nInd=4698000
Genome size with junctions=3282306473  3279945728   2360745
GstrandBit1=32   GstrandBit=32
May 28 09:30:07   Finished inserting junction indices
May 28 09:30:13   Finished SAi
May 28 09:30:13 ..... finished inserting junctions into genome
Thread #0 end of input stream, nextChar=-1
```

**Comment by alexdobin** [comment]
Hi Nate,

and this same example runs OK on a local machine, without the Parrot?

I think the next step would be to try to compile it for gdb with
```
$ make clean
$ make gdb
```
inside the source directory.

Then run with
```
gdb --args /path/to/source/STAR --genomeDir /cvmfs/data.galaxyproject.org/managed/rnastar_index2/hg19/dataset_950899_files --readFilesIn $HOME/forward.fastq $HOME/reverse.fastq
```
Hopefully gdb will show where it gets stuck.

Cheers
Alex

**Comment by natefoo** [comment]
I ultimately stopped running under the Parrot connector due to other issues, so this one will remain in the mystery book. Thanks for your help!
