### ISSUE TITLE
Depend.list: No such file or directory

### ISSUE THREAD

**Issue by michael-s-rooney** [alexdobin/STAR#90]
Hi,

I tried installing STAR on ubuntu (git clone https://github.com/alexdobin/STAR.git; cd STAR; make STAR), but I get the message "Makefile:88: Depend.list: No such file or directory". This is followed by what look like successful installation messages, but then it reports: "cc1plus: error: unrecognized command line option ‘-std=c++11’" many times, and then finally, "make[1]: *** [Depend.list] Error 1".

I saw a similar problem on another thread online (https://groups.google.com/forum/m/#!topic/rna-star/PV70rEYlhTU), but it did not seem like the solution applied to my case. Do you have any ideas?

Thanks,
Mike

**Comment by alexdobin** [comment]
Hi Mike,

I think your gcc is outdated - you need to upgrade to 4.7.0 or later version.

Cheers
Alex

**Comment by michael-s-rooney** [comment]
Thanks a bunch!! I'll try it out!

**Comment by HIM72** [comment]
Hi I just upgraded my gcc to 4.8.2 and tried but got the following error.
make[1]: Entering directory `/home/tools/STAR/STAR-master/source'
Makefile:88: Depend.list: No such file or directory
make -C htslib lib-static
make[2]: Entering directory `/home/tools/STAR/STAR-master/source/htslib'
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o kfunc.o kfunc.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o knetfile.o knetfile.c
cc -g -Wall -O2  -I. -DSAMTOOLS=1 -c -o kstring.o kstring.c
/tmp/cc3AQhIH.s: Assembler messages:
/tmp/cc3AQhIH.s:349: Error: expecting string instruction after `rep'
/tmp/cc3AQhIH.s:363: Error: expecting string instruction after `rep'
make[2]: *** [kstring.o] Error 1
make[2]: Leaving directory `/home/tools/STAR/STAR-master/source/htslib'
make[1]: *** [htslib/libhts.a] Error 2
make[1]: Leaving directory `/home/tools/STAR/STAR-master/source'
make: *** [STAR] Error 2

Is this still the gcc version error?

**Comment by alexdobin** [comment]
Hi @HIM72

I have been compiling with both very old 4.7.0 and latest 5.3.0, and do not have this problem.
Are you using the htslib directory that comes with STAR, or have you replaced it with a newer version?

Cheers
Alex

**Comment by alexdobin** [comment]
This looks similar:
http://stackoverflow.com/questions/23561136/casablanca-assembly-error-gcc-4-8-1-on-linux-centos
It seems that the solution is to update binutils in addition to gcc.
