### ISSUE TITLE
Issues with GFF/GTF

### ISSUE THREAD

**Issue by AmaliT** [alexdobin/STAR#901]
Hi @alexdobin 

I been trying to build a genome index based on a gff file downloaded from JGI. However, I havent had much luck - with all variations of trys leading to `Fatal INPUT FILE error, no valid exon lines in the GTF file: Genome/Gmax/Wm82.a4.v1/annotation/Gmax_508_Wm82.a4.v1.gene_exons.gtf
Solution: check the formatting of the GTF file. Most likely cause is the difference in chromosome naming between GTF and FASTA file` at the processing of GTF file stage.

Initially I tried with just as a gff file with `--sjdbGTFtagExonParentGene` and  `--sjdbGTFtagExonParentTranscript` set to 'Parent' and `--sjdbGTFchrPrefix` set to 'Gm' as chromosome prefix is 'Gm'

Few lines of gff file

> Gm01	phytozomev13	gene	27344	28430	.	-	.	ID=Glyma.01G000100.Wm82.a4.v1;Name=Glyma.01G000100;ancestorIdentifier=Glyma.01G000100.Wm82.a2.v1
> Gm01	phytozomev13	mRNA	27344	28430	.	-	.	ID=Glyma.01G000100.1.Wm82.a4.v1;Name=Glyma.01G000100.1;pacid=41118016;longest=1;ancestorIdentifier=Glyma.01G000100.1.Wm82.a2.v1;Parent=Glyma.01G000100.Wm82.a4.v1
> Gm01	phytozomev13	exon	28139	28430	.	-	.	ID=Glyma.01G000100.1.Wm82.a4.v1.exon.1;Parent=Glyma.01G000100.1.Wm82.a4.v1;pacid=41118016
> Gm01	phytozomev13	CDS	28139	28218	.	-	0	ID=Glyma.01G000100.1.Wm82.a4.v1.CDS.1;Parent=Glyma.01G000100.1.Wm82.a4.v1;pacid=41118016
> Gm01	phytozomev13	five_prime_UTR	28219	28430	.	-	.	ID=Glyma.01G000100.1.Wm82.a4.v1.five_prime_UTR.1;Parent=Glyma.01G000100.1.Wm82.a4.v1;pacid=41118016
> Gm01	phytozomev13	exon	27926	27991	.	-	.	ID=Glyma.01G000100.1.Wm82.a4.v1.exon.2;Parent=Glyma.01G000100.1.Wm82.a4.v1;pacid=41118016
> Gm01	phytozomev13	CDS	27926	27991	.	-	1	ID=Glyma.01G000100.1.Wm82.a4.v1.CDS.2;Parent=Glyma.01G000100.1.Wm82.a4.v1;pacid=41118016

I also tried with the gff converted to gtf with gffread; few lines of gtf

> Gm01	phytozomev13	exon	27344	27824	.	-	.	transcript_id "Glyma.01G000100.1.Wm82.a4.v1"; gene_id "Glyma.01G000100.Wm82.a4.v1"; gene_name "Glyma.01G000100";
> Gm01	phytozomev13	exon	27926	27991	.	-	.	transcript_id "Glyma.01G000100.1.Wm82.a4.v1"; gene_id "Glyma.01G000100.Wm82.a4.v1"; gene_name "Glyma.01G000100";
> Gm01	phytozomev13	exon	28139	28430	.	-	.	transcript_id "Glyma.01G000100.1.Wm82.a4.v1"; gene_id "Glyma.01G000100.Wm82.a4.v1"; gene_name "Glyma.01G000100";
> Gm01	phytozomev13	CDS	27656	27824	.	-	1	transcript_id "Glyma.01G000100.1.Wm82.a4.v1"; gene_id "Glyma.01G000100.Wm82.a4.v1"; gene_name "Glyma.01G000100";
> Gm01	phytozomev13	CDS	27926	27991	.	-	1	transcript_id "Glyma.01G000100.1.Wm82.a4.v1"; gene_id "Glyma.01G000100.Wm82.a4.v1"; gene_name "Glyma.01G000100";
> Gm01	phytozomev13	CDS	28139	28218	.	-	0	transcript_id "Glyma.01G000100.1.Wm82.a4.v1"; gene_id "Glyma.01G000100.Wm82.a4.v1"; gene_name "Glyma.01G000100";
> Gm01	phytozomev13	exon	52485	52601	.	-	.	transcript_id "Glyma.01G000137.1.Wm82.a4.v1"; gene_id "Glyma.01G000137.Wm82.a4.v1"; gene_name "Glyma.01G000137";

Both lead to the same error. Looking at the genome fasta - I cant see any differences in chromosome naming. Few headers from fasta:

> Gm01
> Gm02
> Gm03
> Gm04
> Gm05
> Gm06
> Gm07
> Gm08

So I am not sure what I missed. Are you able to advise me on this? The star version I am using is 2.6.1d

Thanks heaps in advance

Amali

**Comment by alexdobin** [comment]
Hi Amali,

the GTF file should have worked, I see no problems in it. Please send me the Log.out file, and also links to the FASTA and GTF files.

Cheers
Alex

**Comment by AmaliT** [comment]
Hi @alexdobin 

Thanks for the reply. Removal of the `--sjdbGTFchrPrefix` tag seems to solved the issue. I will email you the log.out as I am also having the issue of low map rate as mentioned in few of the issues like #484 #731

**Comment by siuguy** [comment]
Hi @AmaliT and @alexdobin,

I'm having the same issue, where my gff3 files are not working in STAR. Was that issue fixed or it is only working with the gtf version?

@AmaliT, would you able to share your gtf file with me (I do not know how to edit it)?

Thank you!

**Comment by alexdobin** [comment]
Hi @siuguy 

the best option for GFF3 is to convert them to GTF - you can use, for instance, gffread tool.

Cheers
Alex

**Comment by siuguy** [comment]
Thank you @alexdobin, I end up finding a gft version from Ensembl plants.

Link: [Glycine_max.Glycine_max_v2.1.49.gtf.gz](ftp://ftp.ensemblgenomes.org/pub/plants/release-49/gtf/glycine_max/Glycine_max.Glycine_max_v2.1.49.gtf.gz)
