### ISSUE TITLE
The meaning of column in JS.out.tab file 

### ISSUE THREAD

**Issue by fuhao1216** [alexdobin/STAR#903]
With solofeature --SJ ,i get a "JS.out.tab" file .
1	16766	16857	2	2	1	0	1	31
1	18062	18267	2	2	1	0	1	37
1	18367	24737	2	2	1	0	1	22
1	24892	29533	2	2	1	0	1	31
1	147251	164476	2	4	0	0	1	25
1	172689	173752	2	2	1	0	1	14
1	188585	188790	2	2	1	0	1	37
1	505846	523072	2	4	0	0	1	25
1	517267	522858	2	2	1	0	2	44
1	630465	630607	2	2	0	0	1	21

but, i dont understand 4-9 columns' meaning

**Comment by alexdobin** [comment]
Hi @fuhao1216 

from section 4.2 of the manual:
column 1: chromosome
12
column 2: first base of the intron (1-based)
column 3: last base of the intron (1-based)
column 4: strand (0: undefined, 1: +, 2: -)
column 5: intron motif: 0: non-canonical; 1: GT/AG, 2: CT/AC, 3: GC/AG, 4: CT/GC, 5:
AT/AC, 6: GT/AT
column 6: 0: unannotated, 1: annotated (only if splice junctions database is used)
column 7: number of uniquely mapping reads crossing the junction
column 8: number of multi-mapping reads crossing the junction
column 9: maximum spliced alignment overhang

Cheers
Alex

**Comment by fuhao1216** [comment]
> Hi @fuhao1216
> 
> from section 4.2 of the manual:
> column 1: chromosome
> 12
> column 2: first base of the intron (1-based)
> column 3: last base of the intron (1-based)
> column 4: strand (0: undefined, 1: +, 2: -)
> column 5: intron motif: 0: non-canonical; 1: GT/AG, 2: CT/AC, 3: GC/AG, 4: CT/GC, 5:
> AT/AC, 6: GT/AT
> column 6: 0: unannotated, 1: annotated (only if splice junctions database is used)
> column 7: number of uniquely mapping reads crossing the junction
> column 8: number of multi-mapping reads crossing the junction
> column 9: maximum spliced alignment overhang
> 
> Cheers
> Alex

Thanks Alex
With "Gene" , I can get "barcode,tsv","features.tsv"and"matrix.mtx" ,those can be analysed by "seurat".But with "SJ",I get "sj.out.tab",”barcode.tsv"and"matrix.max"."sj.out.tab" seems to be cells mixed.Can you give me an advise how to analyse "SJ" OUTPUT.
Another question, is "Transcript3p" can be used?
Thanks again

**Comment by alexdobin** [comment]
Hi @fuhao1216 

You can create "features.tsv" file for the STARsolo SJ from SJ.out.tab, by merging the first 3 columns of SJ.out.tab with, say, "_" as a delimiter, i.e.
``` awk '{print $1 "_" $2 "_" $3}' SJ.out.tab > features.tsv```
This should allow you to load the junctions into Seurat.
However, I do not think standard Seurat methods can be used with SJs - mostly because the SJ counts are much more sparse than gene counts.

We do the analysis of differential splicing between the cell clusters derived (in a standard way) from the gene counts, and we normalize SJ counts with gene counts.

Cheers
Alex
