### ISSUE TITLE
pre-built index for hg19

### ISSUE THREAD

**Issue by KunFang93** [alexdobin/STAR#905]
Hi, 

I was wondering if there is any link for downloading the pre-built index since this one _http://labshare.cshl.edu/shares/gingeraslab/www-data/dobin/STAR/STARgenomes/_ seems not work currently. Thanks!

Best,
Kun

**Comment by alexdobin** [comment]
Hi Kun,

at the moment I do not have genomes generated with the latest version of STAR. It's easy to generate the genome index - and then you have full control over the genome FASTA and annotations GTF.

Cheers
Alex

**Comment by KunFang93** [comment]
Hi, Alex

Thanks for your reply~Understand, I will generate the genome index then.

Best,
Kun
