### ISSUE TITLE
STARSolo GX/GN not output when TranscriptomeSAM called

### ISSUE THREAD

**Issue by mvanins** [alexdobin/STAR#907]
Hi,

In mapping with STARSolo, the GX and GN tags are not emitted to the `Aligned.sortedByCoord.out.bam` if `--quantMode TranscriptomeSAM` is specified.

Is there a way to output this information?

Thanks in advance,
Mike

**Comment by alexdobin** [comment]
Hi Mike,

this is a bug, thanks for reporting it. Will fix it in the next patch.

Cheers
Alex

**Comment by alexdobin** [comment]
Hi Mike,

I pushed the patch to master, please check it out.
A great test would be to run your command with and without --quantMode TranscriptomeSAM and check that Aligned.out.bam are exactly the same (after converting to SAM and sorting).

Cheers
Alex

**Comment by mvanins** [comment]
Hi Alex,

I ran an experiment through the static linux binary in the c651f3b commit with and without TranscriptomeSAM. The GX/GN tags were present in both and there were no differences in a diff between the output files.

Thanks for the quick response and turnaround!
Mike
