### ISSUE TITLE
Reads counts for Fusion Gene

### ISSUE THREAD

**Issue by zcsheng95** [alexdobin/STAR#908]
Hi,
I want to perform gene-level differential expression analysis for a specific fusion gene in the ceil line.
I followed this post: https://groups.google.com/forum/#!msg/rna-star/FGQRotrCB1Q/oQ2annphCQAJ and ran STAR with:

STAR
 --runThreadN {threads} 
--genomeDir /STARINDEX/ 
--readFilesIn R1-trim.fastq.gz R2-trim.fastq.gz 
--readFilesCommand zcat 
--quantMode TranscriptomeSAM GeneCounts 
--twopassMode Basic
--seedSearchStartLmax 30 
--outSAMtype BAM Unsorted SortedByCoordinate
--outSAMstrandField intronMotif 
--chimOutType Junctions 
--outReadsUnmapped Fastx 
--outSAMunmapped Within 
--outFileName /output/

My question is though I can pull out 28 junction reads from Aligned.sortedByCoord.bam (consistent with STAR-FUSION output), why the ReadsPerGene.out.tab only gives 2 for that fusion gene?

Thanks for your time,
Jeff

**Comment by alexdobin** [comment]
Hi Jeff,

fusion reads are not counted towards the genes in the ReadsPerGene.out.tab file.

Cheers
Alex

**Comment by zcsheng95** [comment]
Thanks Alex, 
Are those fusion reads categorized as multi-mappers in ReadsPerGene.out.tab?
Would you recommend counting fusion reads directly from bam file if I would like to do DE analysis across different samples?

Best,
Jeff

**Comment by alexdobin** [comment]
Hi Jeff,

I have to correct my previous post - let me explain a bit more.
STAR first maps the reads normally (non-chimerically), and if they can map, they will be counted towards genes (if they are unique and overlap genic exons).

Then, STAR tries to make chimeric alignments. These chimeric alignments are not counted in ReadsPerGene. 

However, some reads can have both normal and chimeric alignments
The reads with normal alignments that are unique mappers, and overlap gene exons, will be counted towards the genes. The fact that they also have a chimeric alignment does not affect the counting - i.e. only the gene from the normal alignment will get the count.

Cheers
Alex

**Comment by zcsheng95** [comment]
So I guess those junction reads are not counted because they are not unique mappers in normal alignment not because of their chimeric alignment?

**Comment by alexdobin** [comment]
Hi Jeff 

The chimerically aligned reads will not be counted in ReadsPerGene if either they do not have normal alignments, or if their normal alignments are multimappers. You can check that by gripping these reads from the Aligned.out.bam file.

Cheers
Alex

**Comment by zcsheng95** [comment]
Hi Alex,

Thanks for your time in advance!
I gripped some junction reads out of Aligend.SortedByCoord.out.bam via samtools view command.

Here are parts of the output:
A00257:167:HFKFMDRXX:1:1169:31946:5744	163	FUSE.001	77652	255	51M	=	78820	123890	ATGGCTTTCAACCATCTCATTCCCGGGGGGTTCCCTCCCACTGCCATGCCG	FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	NH:i:1	HI:i:1	AS:i:100	nM:i:0	XS:A:+
A00257:167:HFKFMDRXX:2:2268:12626:26021	163	FUSE.001	77656	255	51M	=	78813	123879	CTTTCAACCATCTCATTCCCGGGGGGTTCCCTCCCACTGCCATGCCGACCT	FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	NH:i:1	HI:i:1	AS:i:100	nM:i:0	XS:A:+
A00257:167:HFKFMDRXX:2:2167:18638:14387	163	FUSE.001	77685	255	51M	=	78817	123854	CCTCCCACTGCCATGCCGACCTTGCCAACGTACCAGCTGTCGGAGACCTCT	FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	NH:i:1	HI:i:1	AS:i:100	nM:i:0	XS:A:+
A00257:167:HFKFMDRXX:2:2275:2736:30655	163	FUSE.001	77686	255	51M	=	78808	123844	CTCCCACTGCCATGCCGACCTTGCCAACGTACCAGCTGTCGGAGACCTCTT	FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	NH:i:1	HI:i:1	AS:i:100	nM:i:0	XS:A:+
...

FUSE.001 is the name of the sequence I added to the reference, looks like those are all unique mapped reads (255). However the ReadsPerGene does not report all those reads(it has 2 counted towards FUSE.001). 

I still can't figure out the reason why those reads are missed.


Sincerely,
Jeff

**Comment by alexdobin** [comment]
Hi Jeff,

did you also add an annotation for FUSE.001 "chromosome" into the GTF file? What does it look like?
Can you grep A00257:167:HFKFMDRXX:1:1169:31946:5744 line in Chimeric.out.junction?

Cheers
Alex

**Comment by zcsheng95** [comment]
Hi Alex,
Yes I added one line for FUSE.001 at the very end of my gtf file:
FUSE.001        AddedGenes      exon    1       6259    .       +       0       gene_id "FUSE.001"; transcript_id "FUSE.001"

And STAR alone didn't give a Chimeric.out.junction output so I grep the record from STAR-FUSION Chimeric.out.junction (for the same sample).

chr13   40560861        +       chr2    222220139       +       2       0       3  A00257:167:HFKFMDRXX:1:1169:31946:5744  40560833        28M23S  222220140       28S23M1117p51M  1     102      71      98      98      0       GRPundef

**Comment by alexdobin** [comment]
Hi Jeff,

these reads map at base >77652 on the FUSE.001 "chromosome", but you annotation only goes from 1 to 6259 - this is why they are not counted.

Cheers
Alex

**Comment by zcsheng95** [comment]
Hi Alex,
Thanks for pointing out the problem in the annotation and it works out perfectly!

Thanks for your time,
Jeff
