### ISSUE TITLE
WASP usage; Not all alignments contain WASP 'vW' tag

### ISSUE THREAD

**Issue by roosheelpatel** [alexdobin/STAR#909]
Hi Alex,
I've been playing around with the STAR+WASP implementation. One observation I noticed looking through the BAM output is that not all of the alignments are tagged with the 'vW' tag. 

Spot checking a few of the alignments missing the tag, it seems that these alignments do not span any SNP detailed in the input VCF. Is this correct? 

Thanks for developing/maintain a great tool.

Roosheel

**Comment by alexdobin** [comment]
Hi Roosheel

that's correct - the alignments that do not overlap variants are not going through the WASP procedure and hence are not assigned the vW tag.

Cheers
Alex
