### ISSUE TITLE
Create output folders when they don't exist

### ISSUE THREAD

**Issue by gringer** [alexdobin/STAR#910]
Suggestion from Monika Cechova Mich on Twitter:

> I find it hilarious that one of the most advanced #RNASeq aligners -- STAR -- is not willing to create an output folder for you. Hey, you want me to output your files there, my dear? Mkdir a folder first!!

See tweet [here](https://mobile.twitter.com/biomonika/status/1263731563105222656)

**Comment by alexdobin** [comment]
Hi David,

good suggestion, implemented. Please check it out on master, will make an official release shortly.

Cheers
Alex
