### ISSUE TITLE
reads with UMI for illumina runs 

### ISSUE THREAD

**Issue by snenish03** [alexdobin/STAR#913]
Hello,

I have paired end 250 bps reads with UMIs. (These are not single cell sequencing reads).  I have 4 files (R1,R2, I1 and I2 -- I1 and I2 have the barcodes for R1 and R2) Is there a way I can use this information to identify splice junctions?

**Comment by alexdobin** [comment]
Hi Sneha,

you can map the R1 and R2 with STAR, and it will output detected splice junctions into SJ.out.tab.

Cheers
Alex

**Comment by snenish03** [comment]
Thanks Alex for your response. So is there no use for UMIs here for identifying splices? Does STAR use them in any way to keep unique reads?

I tried running STAR with and with UMIs in the read names of R1 and R2. I found no difference in results.

**Comment by alexdobin** [comment]
Hi Sneha,

STAR does not use UMIs from read names. If they are the same as I1 and I2 reads from Illumina, there are more likely to be sample barcodes than UMIs.

Cheers
Alex

**Comment by snenish03** [comment]
Got it. Thanks!

I was just exploring ways where I can use UMIs to improve the confidently predict splice junctions. (since I have them). I use them to remove duplicates, etc for other applications. 
Here is a read with a UMI attached to its read name which I generated using UMI tools and my R1,R2, I1 and I2 files - M02550:281:000000000-CYK3C:1:1101:17408:8914_TCCGTTTTC. Hence was curious if I could utilize this additional information to my advantage in STAR.
