### ISSUE TITLE
 Number of input reads lower than the actual number of reads inputed

### ISSUE THREAD

**Issue by kopeckyl** [alexdobin/STAR#914]
Hello,

I identified some differentially expressed genes and subset the sequences of those from the transcriptome fasta that was generated by Trinity. 

Now I am trying to map those reads back to the reference genome. However, I am only getting a " Number of input reads" of 3 while my fasta file has 500 reads. Any idea what may be causing this?

Here is the first three transcripts of my fasta file (I only included the first three lines of each transcript):

>TRINITY_GG_10_c153_g1_i1 len=437 path=[0:0-436]
AATTTGAAAATCCAAAAAAATATCATAATTAAGAAATGGCGATAAGGAAGAGATCATCAAGTTCAGTGAATGTGTTAGAGCCGTGGATCGAGGCGCCACCAGCTAGGGTTGTTTTCCCGGTGAAGTACTACAAGTTGC
>TRINITY_GG_12_c20_g1_i3 len=354 path=[2:0-1 3:2-5 4:6-74 5:75-92 7:93-174 8:175-353]
GTAAGGTAGGGGTCAGAGTGAAGGTTGATGAGAATGGATTTTTATGTGCTGATGAATTATGTGCTTGCATTCAGGAGGTTATGGAAGGAGAAGAAGCAAATAAGATCAAAAATAATGCAAAAATGTGGAAGAAATTAAGTATACAAGCAATGGAAAAAGGTGGGAGTTCTGATAGGAACATTGATGAATTTGTTGCTAAATTGTTGTAAACATCTCCATTTAATTTGATATGTCATGACATTTTCTATTTGATAGTTTCATGCCAACTTATGGATTAGACTTGGTGGATTTTTATCCTAATGAAACAATTCGTTTAAAATTAAAACCATTTCCATGAGTAGAAAAAAAAAAAAA
>TRINITY_GG_12_c20_g1_i1 len=1651 path=[0:0-783 1:784-1298 3:1299-1302 4:1303-1371 5:1372-1389 6:1390-1471 8:1472-1650]
TGGAATGTTATTTAAAATGCCCTCTCTTGACTTGTAGTTTTATATTTTGACAATTCTATGTTGTGGGCCATACTAAATTATGTCTTTAAACAACTATTCTCACACAACACACAACATAGGCACACAACAATGGAAACCAAACCAAAAACAAGTGAAGTAGAAGTTATAGTATTCCCTTATCCAATCCAAGGCCATATTAATCCCATGCTCCAATTTTCAAAGCAACTTGCATCAAGAGGCCTAAAAATTACACTAGTCACCACCTCTACCTTCTCTAATAC

Also, the STAR command used:

`STAR --runThreadN 8 --genomeDir ~/path_to/genome_index --outFileNamePrefix ./mapped_DEGS --readFilesIn ./DEGs.fasta`

**Comment by alexdobin** [comment]
Hi Lucas,

your "reads" are long - you would need to use STARlong to map read longer than ~300b.
Also, you may find that other tools are more suitable for this task - e.g. BLAT, GMAP, minimap2

Cheers
Alex

**Comment by kopeckyl** [comment]
Thanks!
