### ISSUE TITLE
Problem with building Ratus genome

### ISSUE THREAD

**Issue by keremw** [alexdobin/STAR#916]
Hi Alex,
I've downloaded the file you have recommended but when I try to run 
genomeGenerate
I am getting a kill message. The log doesn't say anything interesting. 
This is my command:
STAR --runThreadN 4 --runMode genomeGenerate --genomeDir /home/ubuntu/Documents/References/Rattus_norvegicus/genome --genomeFastaFiles /home/ubuntu/Documents/References/Rattus_norvegicus/genome/Rattus_norvegicus.Rnor_6.0.dna.toplevel.fa --sjdbGTFfile /home/ubuntu/Documents/References/Rattus_norvegicus/annotation/Rattus_norvegicus.Rnor_6.0.100.gtf --genomeSAsparseD 3 --genomeSAindexNbases 12 --limitGenomeGenerateRAM 100000000000

As you see, because I have limited RAM I tied raising the genomeSAsparseD and lowering genomeSAindexNbases as you recommended in another post but it still didn't help.
I am using Linux Ubuntu x86_64 on a VMware Workstation.
Thank you in advance,
Kerem

Hi @keremw 

I am not aware of any problems with the rat genome. Please make sure that you are using the genome without masking - i.e. Rattus_norvegicus.Rnor_6.0.dna.toplevel.fa.gz

Cheers
Alex

_Originally posted by @alexdobin in https://github.com/alexdobin/STAR/issues/479#issuecomment-634332593_

**Comment by alexdobin** [comment]
Hi @keremw 

how much RAM do you have available on the VM. You can check it with "free" Linux command.
Also, you are allowing ~100GB with --limitGenomeGenerateRAM 100000000000 - you need to remove one 0, I think.

Cheers
Alex

**Comment by keremw** [comment]
Hi Alex,
Thank you for your answer.
Indeed I had a mistake in the current run but when I tried with 10GB or even 8.8GB the process still gets killed. Overall using `free -mt` I see I have a total of 11670 MB and free 8970MB (with additional space in SWAP). Is there a minimal amount of RAM to use STAR?
Thanks,
Kerem

**Comment by keremw** [comment]
@alexdobin ?

**Comment by alexdobin** [comment]
Hi Kerem,

sorry for the belayed reply. For ~9GB or even 12GB you would need to further increase `--genomeSAsparseD` - basically until you can fit the the genome into the RAM. However, I would recommend looking for a server with more RAM available. Is the 12GB the VM limitation? What is the physical RAM limit on this machine?

Cheers
Alex

**Comment by alexdobin** [comment]
Hi Kerem,

roughly, these are the RAM requirements:
STAR major memory requirements are:
1. Genome + SA: ~(1+8/genomeSAsparseD)*GenomeLength bytes.
2. SAindex: ~6*4^(genomeSAindexNbases). By default --genomeSAindexNbases 14 and it takes 1.5GB of RAM. If you reduce --genomeSAindexNbases to 12 you can make it <100MB.
3. --limitIObufferSize *NumberOfThreads for I/O buffers. By default it's 150MB per thread, but you can probably go as low as 50MB per thread.

Cheers
Alex

**Comment by keremw** [comment]
Thank you Alex for all your help and clarifications. I've managed to run it with increased RAM. Your rules will help me define my computational needs for the future.
Thanks again for all your help,
Kerem
