### ISSUE TITLE
low fraction of Reads With Valid Barcodes

### ISSUE THREAD

**Issue by MichaelBroux** [alexdobin/STAR#918]
Dear Alex,

I’m using STARsolo for plate-based single-cell 5’ RNA seq, using 96 different cell/well barcodes in a whitelist textfile “MPS20018_257_TSO_barcode_LI00482.txt”. Barcode length = 8 bp, UMI length is 8 bp. We did paired-end sequencing where Read1 = cell barcode (8 bp) + UMI (8 bp) = 16 bp and Read2 = 98 bp containing cDNA insert sequence needed for mapping to the reference genome.

STAR \
--soloType CB_UMI_Simple \
--quantMode GeneCounts \
--runThreadN 4 \
--outFilterMultimapNmax 1 \
--outSAMtype BAM SortedByCoordinate \
--soloCBstart 1 \
--soloCBlen 8 \
--soloUMIstart 9 \
--soloUMIlen 8 \
--soloBarcodeReadLength 0 \
--soloStrand Unstranded \
--soloFeatures Gene \
--genomeDir /path/to/reference/human/genome/refdata-STARsolo--GRCh38/STAR \
--limitBAMsortRAM 10000000000 \
--outReadsUnmapped Fastx \
--outSAMunmapped Within \
--outSAMattributes NH HI nM AS CR UR CB UB GX GN \
--readFilesCommand zcat \
--readFilesIn /path/to/fastqR2/containing/cDNA/information/200320_IR_RC_P7_SI_2_S2_L001_R2_001.fastq.gz /path/to/fastqR1/containing/CBandUMI/information/200320_IR_RC_P7_SI_2_S2_L001_R1_001.fastq.gz \
--soloCBwhitelist /path/to/whitelist/MPS20018_257_TSO_barcode_LI00482.txt

This resulted in following summary with low fraction of Reads With Valid Barcodes:
Number of Reads | 6659731
Reads With Valid Barcodes | 0.671378
Sequencing Saturation | 0.909358
Q30 Bases in CB+UMI | 0.940818
Q30 Bases in RNA read | 0.903433
Reads Mapped to Genome: Unique+Multiple | 0.860277
Reads Mapped to Genome: Unique | 0.860277
Reads Mapped to Transcriptome: Unique+Multipe Genes | 0.565611
Reads Mapped to Transcriptome: Unique Genes | 0.540504
Estimated Number of Cells | 95
Reads in Cells Mapped to Unique Genes | 3599614
Fraction of Reads in Cells | 1
Mean Reads per Cell | 37890
Median Reads per Cell | 34473
UMIs in Cells | 326276
Mean UMI per Cell | 3434
Median UMI per Cell | 3230
Mean Genes per Cell | 1309
Median Genes per Cell | 1249
Total Genes Detected | 12050

Consistently, with all our samples analyzed with STARsolo we find back values between 60-67%. We found it a bit worrying that 33-40% of our reads is already filtered out by STARsolo mapping early on. When we check manually for the sample (summary) shown above we find back indeed 95 barcodes and also 6006688 out of 6659731 reads have a barcode present in the whitelist, being 90.2% instead of 67.1%.

For simplicity, from this same, we also generated a Read1.fastq and Read2.fastq file that only contains 1 cell barcode ATCACGTT. So in theory now we selected for reads that only contain 1 cell barcode resulting in 100% Reads With Valid Barcodes. We ran the same code and parameters on these 2 fastq files and found 79.8% Reads With Valid Barcodes. See summary below:

Number of Reads | 77448
-- | --
Reads With Valid Barcodes | 0.797916
Sequencing Saturation | 0.918726
Q30 Bases in CB+UMI | 0.948963
Q30 Bases in RNA read | 0.903784
Reads Mapped to Genome: Unique+Multiple | 0.584353
Reads Mapped to Genome: Unique | 0.584353
Reads Mapped to Transcriptome: Unique+Multipe Genes | 0.432264
Reads Mapped to Transcriptome: Unique Genes | 0.417506
Estimated Number of Cells | 1
Reads in Cells Mapped to Unique Genes | 32335
Fraction of Reads in Cells | 1
Mean Reads per Cell | 32335
Median Reads per Cell | 32335
UMIs in Cells | 2628
Mean UMI per Cell | 2628
Median UMI per Cell | 2628
Mean Genes per Cell | 1137
Median Genes per Cell | 1137
Total Genes Detected | 1137

I also uploaded the Read1+2 fastq files selected for only 1 cell barcode (extractedrecords_R1_BC1.fastq.gz, extractedrecords_R2_BC1.fastq.gz) and the whitelist with 1 barcode (MPS20018_257_TSO_barcode1_ATCACGTT.txt). The reference genome is human GRCh38.

Could you help us find out why STARsolo seems to filter out 20% of reads that carry a valid barcode? Is it the case that the quality of Read2.fastq file is taken into account to filter out reads that still have a valid cell barcode in Read1.fastq? And most important question: how can we increase the Reads With Valid Barcodes? 

Many thanks in advance.
Best regards,
Michaël

[MPS20018_257_TSO_barcode1_ATCACGTT.txt](https://github.com/alexdobin/STAR/files/4695872/MPS20018_257_TSO_barcode1_ATCACGTT.txt)
[extractedrecords_R1_BC1.fastq.gz](https://github.com/alexdobin/STAR/files/4695873/extractedrecords_R1_BC1.fastq.gz)
[extractedrecords_R2_BC1.fastq.gz](https://github.com/alexdobin/STAR/files/4695874/extractedrecords_R2_BC1.fastq.gz)

**Comment by Qotov** [comment]
I also have a suspicion that STARsolo could filter valid barcodes (I run STARsolo on InDrops v3 how it described here https://github.com/alexdobin/STAR/issues/825#issuecomment-610652720)

**Comment by alexdobin** [comment]
Hi Michael,

sorry for the belayed reply. In your example,  61797 (out of 77448) reads have N(s) in the UMI, which are not allowed, which agrees with only ~80% of the reads having "valid barcodes" in the Summary.csv file.
You can check more detailed barcode statistics in Solo.out/Barcodes.stats file, the nNinUMI value will give you the number of reads with N(s) in UMIs - @Qotov, please check the numbers for the inDrop run there.

Cheers
Alex

**Comment by MichaelBroux** [comment]
Hi Alex,

Thanks for taking your time and clarifying. After your advice we indeed see a significant fraction of reads with N at the end of the UMI in Read1. Seems we would need to sequence more than 16 cycles in Read1. @Qotov thanks for refering to #825 

Cheers,
Michaël
