### ISSUE TITLE
never stop ( always run)

### ISSUE THREAD

**Issue by CTLife** [alexdobin/STAR#92]
Hi,
Map filtered reads (by Trimmomatic) to mm9 reference genome by using STAR version 2.5.0b, but it is  always running (>24 hours for one alignment) after created the last thread. 
Command: 
STAR   --runThreadN 16     --outFileNamePrefix XXX      --genomeDir XXX      --readFilesIn XX_1.fastq    XX_2.fastq        >>runLog.txt   2>&1

XX_1.fastq   and XX_2.fastq are only 1.5 GB. HISAT2 and Subjunc, both of them work well for these files (<2 hours). Why STAR version 2.5.0b never stop (>24 hours), although it works well for small fastq files with 100 reads?  
Linux_x86_64_static, Linux_x86_64 and build from source, all of them have this bug.

My computer:
Ubuntu 15.10, 64 bit
96 GB memory
Free hard disk space > 1TB
24 CPUs

Thank you.

**Comment by alexdobin** [comment]
Hi CTLife,

this is likely owing to some problem with trimming. 
For instance, some trimming software trim the 2 reads independently and remove over-trimmed reads from one file but not the other. STAR requires that reads in both files are exactly in the same order, no skipping allowed - so reads have to be remove from two files simultaneously.

Could you try to map untrimmed files? 
If it still does not work, please send me the Log.out file.

Cheers
Alex

**Comment by CTLife** [comment]
Hi, Alex, 

STAR version 2.5.0b works well for trimmed and untrimmed files when I use "./STAR ....." in the directory of STAR. But "STAR ......" dose not work in other directories although I have add its path into ".bashrc".  I don't know why. 

STAR version 2.5.0b, it can now be used and work well. 

Thank you.
