### ISSUE TITLE
Number of reads on either end of junction

### ISSUE THREAD

**Issue by snenish03** [alexdobin/STAR#920]
Thank you for this great tool!

I am trying to identify novel splice junctions and the SJ.out.tab file is very useful to me. Is there any easy way to identify the reads on either end of the junction? I am interested in knowing how many reads there are and their lengths?

I tried extracting the reads from the bam file but they are not the same as reported in the SJ.out.tab file. 

P.S: I am using 2 pass method.

**Comment by alexdobin** [comment]
Hi Sneha,

you would need to extract the read from the BAM file. You can add jI jM to the --outSAMattributes list, which will give you intron start/end and motif.
However, the SJ.out.tab file is filtered (--outSJfilter* parameters), so not all junctions from the BAM file end up in the SJ.out.tab file.

Cheers
Alex
