### ISSUE TITLE
STAR cannot open genome file in S3 bucket

### ISSUE THREAD

**Issue by jgoldst7** [alexdobin/STAR#924]
Hello. I have an issue running STAR through the snakemake/tibanna framework. My prebuilt index worked for for alignment using snakemake locally. However, when I transitioned to AWS with tibanna, it is no longer working with the index I build. I tried using the index both locally, and in an S3 bucket, with the same error. Attached is the specific STAR rule I am using. The error output is 

"EXITING because of FATAL ERROR: could not open genome file rnaseq.raw/References/STAR_index/genomeParameters.txt
SOLUTION: check that the path to genome files, specified in --genomeDir is correct and the files are present, and have user read permission"

However, the files are there in the S3 bucket, and it is a direct copy of the index that worked locally. Has anybody used STAR in the snakemake/tibanna framework and has similar issues?
[STAR.txt](https://github.com/alexdobin/STAR/files/4704406/STAR.txt)

**Comment by jgoldst7** [comment]
Update: Simply trying to run STAR using an index in an S3 bucket results in the same error. Can STAR definitely be run on genome index in a remote s3 bucket?

**Comment by windybasket** [comment]
Are you sure this is what you want? Your index isn't S3 and Homo_Sapien is without an s
#index = S3.remote("rnaseq.raw/References/STAR_index"),
index = "/Users/jeremygoldstein/data/refseq/Homo_Sapien/STAR_index",

**Comment by jgoldst7** [comment]
Thanks for the response. Attached is my updated STAR file. The error is that the EC2 instances being created by tibanna only attach the input files, not the genome index specified in the params. I figured this out because when I put genomeParameters.txt as in input file (commented out in the attached file) the error becomes 

"EXITING because of FATAL ERROR: could not open genome file rnaseq.raw/References/STAR_index/chrName.txt"

Short of attaching every single file inside the STAR index as an input file. I cannot think of another solution
[STAR.txt](https://github.com/alexdobin/STAR/files/4705216/STAR.txt)

**Comment by alexdobin** [comment]
Hi Jeremy

--genomeDir requires the path to the genomeDir specified. I would recommend using absolute path if possible. Now it is relative to current dir : `--genomeDir rnaseq.raw/References/STAR_index/`
I think you can check if this path is correct with something like `ls {params.index}` before  the STAR command.

Cheers
Alex

**Comment by jgoldst7** [comment]
Hello Alex,
Thanks for the response. It was not an issue with the path specified in --genomeDir, it was an issue with those files not actually being there because anything in the "params" section of a snakemake rule is not copied into the EC2 instance, only things in the "input" section.

Without knowing how to get a params section to be copied, and with snakemake not allowing a folder to be in the input section, only a file,  My inelegant solution is to name every single file present in the STAR_index as an input file, which works.

Attached below is the updated STAR rule that works. This is an ugly solution so if anybody has any better solutions or workarounds, please let me know
[STAR.txt](https://github.com/alexdobin/STAR/files/4708257/STAR.txt)

**Comment by alexdobin** [comment]
Hi Jeremy,

thanks for the explanation. I guess it could be a feature request for snakemake to copy entire directories. Another possible workaround is to tar the directory into one file, and then untar it before the run?

Cheers
Alex

**Comment by jgoldst7** [comment]
Good idea about tarring the directory. Thanks for the help!
