### ISSUE TITLE
RNA-seq data with barcode and ploy(T).

### ISSUE THREAD

**Issue by Junjun-Xu** [alexdobin/STAR#926]
Hi alexdobin,
I'm using STAR for RNA-seq data analysis. But I have some questions about the handling of the input data. We used 150bp pair-end sequencing, and in R1 segment, there are 8 barcode and some ploy (T). I want to know is this sequence can influence the result of alignment(pair end alignment)? I remember that STAR has ability to identify for these sequences. What do you suggest? I need to get rid of these sequences?
Thanks
Jun

**Comment by alexdobin** [comment]
Hi Jun,

STAR can "auto-trim" the unmappable sequences, however, it's always better to pre-trim the adapter and homo-polymer sequences. Are the barcode/polyT sequences of constant length? Then you could use --clip3pNbases or --clip5pNbases to trim them off before mapping.

Cheers
Alex

**Comment by Junjun-Xu** [comment]
Hi,

Thanks a lot. The barcode length in our data is fixed, but T is not. I tried to do alignment using data with barcode and Ploy(T) and without. I find the result is similar.Thank you very much for your reply.

Jun
