### ISSUE TITLE
STAR hangs on first genome generation step when not specifying correct command line arguments

### ISSUE THREAD

**Issue by gringer** [alexdobin/STAR#930]
STAR could do with a bit more feedback on command line options for genome index generation. If a step is taking more than a couple of minutes, it'd be great if more information could be provided about that step. If error checking isn't possible, even a '.' placed on the screen can be helpful to distinguish between "program hangs" and "program is doing what it's meant to be doing".

With regards to my specific situation, STAR decided to hang for four hours while appearing to be carrying out the "starting to generate Genome files step". I thought it looked odd, so double-checked the options and noticed there were a few that I got wrong (in particular, using the toplevel rather than the primary assembly, and not including a GTF file). Restarting the command with the correct options led to a process that produced fast, useful feedback.

Here were my commands:

    1. STAR --runThreadN 10 --runMode genomeGenerate --genomeDir /mnt/ufds/STAR/mm10_v100_2.7.3a --genomeFastaFiles /home/gringer/db/fasta/mmus/ensembl/Mus_musculus.GRCm38.dna_rm.toplevel.fa

    2. STAR --runThreadN 10 --runMode genomeGenerate --genomeDir /mnt/ufds/STAR/mm10_v100_2.7.3a --genomeFastaFiles /home/gringer/db/fasta/mmus/ensembl/v100/Mus_musculus.GRCm38.dna_rm.primary_assembly.fa --sjdbGTFfile /home/gringer/db/fasta/mmus/ensembl/v100/Mus_musculus.GRCm38.100.gtf --sjdbOverhang 100

Output for command 1:
```
Jun 04 14:13:07 ..... started STAR run
WARNING: Could not move Log.out file from ./Log.out into /mnt/ufds/STAR/mm10_v100_2.7.3a/Log.out. Will keep ./Log.out
 : Jun 04 14:13:07
Jun 04 14:13:07 ... starting to generate Genome files
^C
[killed after 4 hours] 
```

Output for command 2:
```
Jun 04 18:41:47 ..... started STAR run
WARNING: Could not move Log.out file from ./Log.out into /mnt/ufds/STAR/mm10_v100_2.7.3a/Log.out. Will keep ./Log.out
 : Jun 04 18:41:47
Jun 04 18:41:47 ... starting to generate Genome files
Jun 04 18:43:57 ... starting to sort Suffix Array. This may take a long time...
Jun 04 18:44:29 ... sorting Suffix Array chunks and saving them to disk...
Jun 04 18:59:35 ... loading chunks from disk, packing SA...
Jun 04 19:00:45 ... finished generating suffix array
Jun 04 19:00:45 ... generating Suffix Array index
Jun 04 19:05:29 ... completed Suffix Array index
Jun 04 19:05:29 ..... processing annotations GTF
Jun 04 19:05:55 ..... inserting junctions into the genome indices
Jun 04 19:11:12 ... writing Genome to disk ...
Jun 04 19:11:15 ... writing Suffix Array to disk ...
Jun 04 19:11:24 ... writing SAindex to disk
Jun 04 19:11:25 ..... finished successfully
```

**Comment by alexdobin** [comment]
Hi David,

the Log.out file is supposed to produce more detailed continuous output, e.g. listing the chromosomes as they are input from the files.

Cheers
Alex
