### ISSUE TITLE
Segmentation fault related to chimeric read detection

### ISSUE THREAD

**Issue by stephan-hutter** [alexdobin/STAR#934]
I have been running STAR as part of the arriba pipeline for fusion gene detection and have been getting a catastrophic Segmentation fault error that is couriously triggered by a single "toxic" read.

Here is how to replicate:
STAR \
--genomeDir /reference/STAR_index_hs37d5_GENCODE19/ \
--readFilesIn CRASH.fastq \
--outSAMtype BAM Unsorted \
--chimOutType WithinBAM SoftClip \
--outFilterMultimapNmax 1 \
--outFilterMismatchNmax 3 \
--chimSegmentMin 10 \
--chimJunctionOverhangMin 10 \
--chimScoreMin 1 \
--chimScoreDropMax 30 \
--chimScoreJunctionNonGTAG 0 \
--chimScoreSeparation 1 \
--alignSJstitchMismatchNmax 5 -1 5 5 \
--chimSegmentReadGapMax 3

The CRASH.fastq input file contains a single read:
@A00122:30:H2C2HDMXX:2:2337:30237:35540 2:N:0:TCCGGAGA+GGCTCTGA
GGCAAGACCTTTAGTCGGAAGTCATATTTTATATGCCATCATAGACTTCATACTGGAGAGAAACCGTATAAGTGTAATGAGTGTTGCAAGACCTTTAGTC
+
FFFFFFFFFFFFFFFFFFF-FFFFFF-F8FFF-FFFFFFFFFFFFFFFF-F-F-FFFFFFFF88--FF-8-8FF-F8FFF-FFF-8F88-8--F-8888F

The genomic reference is based on the hs37d5 human genome with GENCODE19 annotation (as produced by a script in the arriba package). However, I have also tried it with the standard GRCh37 genome and it also crashes.

I have furthermore tried different versions of STAR (2.5.3a, 2.7.1a, 2.7.3a, 2.7.4a) and all of them crash.

Interestingly, if I remove the "--chimOutType WithinBAM SoftClip" parameter the program finishes successfully. Alternatively, I can keep "--chimOutType WithinBAM SoftClip, but remove all the customized parameters that come after it, and STAR also finishes.

So I assume there has to be some interaction with the output type and one or more of the other parameters.

I hope this can be sorted out.

Kind regards,
Stephan

**Comment by alexdobin** [comment]
Hi Stephan:

thanks for the bug report! I could reproduce and fix it, please check the latest patch on GitHub master.

Cheers
Alex

**Comment by stephan-hutter** [comment]
Hi Alex,

can confirm, STAR executes properly with the current master version (2.7.5a_testing4).

Thanks for fixing!
