### ISSUE TITLE
Mapping to transcriptome

### ISSUE THREAD

**Issue by qianxu05172019** [alexdobin/STAR#938]
Hi,

I am using an SGE and trying to map my paired-end reads to this mouse transcriptome (ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M25/gencode.vM25.transcripts.fa.gz).

I can build an index on this reference fasta file using 
mkdir /data/qianxu0517/DMS_MaPseq/genomeDir
STAR --runThreadN 20 \
     --runMode genomeGenerate \
     --genomeDir /data/qianxu0517/DMS_MaPseq/genomeDir \
     --limitGenomeGenerateRAM 199687447936 \
     --genomeFastaFiles /data/qianxu0517/DMS_MaPseq/Hisat2Index_namechanged/gencode.vM25.transcripts_namechanged.fa

I have totally 4 paired-end datasets, 2 of them are relatively small (21G+21G and 6G+6G),But when I try to map the other bigger dataset(43G+43G and 32G+32G ) to the transcriptome using:
STAR --runThreadN 10 \
--runMode alignReads \
--genomeDir /data/qianxu0517/DMS_MaPseq/genomeDir  \
--readFilesIn /data/qianxu0517/DMS_MaPseq/SS5/SS5_1_val_1.fq /data/qianxu0517/DMS_MaPseq/SS5/SS5_2_val_2.fq \
--outSAMtype BAM SortedByCoordinate \
--limitBAMsortRAM 34786300050 \
--outFileNamePrefix /data/qianxu0517/DMS_MaPseq/SS5/SS5_star_t10/SS5_t10_

 it keeps giving me this error:
EXITING because of fatal ERROR: not enough memory for BAM sorting: 
SOLUTION: re-run STAR with at least --limitBAMsortRAM 3478630005
Jun 09 20:04:23 ...... FATAL ERROR, exiting

I have tried using just 2 threads, and increase the number at --limitBAMsortRAM to 347863000500, it does not solve the problem.

Can you please give me a hind about what is going on there and what should I do? Thanks!

**Comment by qianxu05172019** [comment]
I solved this problem by not sorting the bam file. after mapping, I used samtools to sort the bam file. Thanks for developing this awesome tool!

**Comment by alexdobin** [comment]
Hi Qxu,

using samtools for sorting is the safest solution.
I think the problem could have been that you are running out of space on your storage, you may need ~100-200GB depending on your FASTQ file size.

Cheer
Alex
