### ISSUE TITLE
STAR genomeGenerate killed

### ISSUE THREAD

**Issue by diwasri** [alexdobin/STAR#940]
I am new to RNA-seq (and even coding). When trying to generate the genome using STAR-1.7.4a, the process gets killed without any error during the "sorting suffix array chunks and saving them to the disk.

My command line was 
STAR --runThreadN 8 --runMode genomeGenerate --genomeDir /scratch/star-2.7.4a/ --genomeFastaFiles /data/processed/genomes/homo-sapiens-96/ensembl-mirror/fasta/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz --sjdbGTFfile /scratch/Homo_sapiens.GRCh38.dna.primary_assembly.fa --sjdbOverhang 100 --genomeSAsparseD 2

**Comment by alexdobin** [comment]
Hi @diwasri 

You would need to gunzip the Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz file before running the genome generation.
Also, how much RAM do you have on your server, and how much is free?
You can check this with the Linux command `free`

Cheers
Alex

**Comment by diwasri** [comment]
Thank you Alex,

I was running this originally on a 16GB RAM. I guess this wasnt enough. I switched to a 64GB RAM and this worked. I also decompressed the Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz file.

Thanks once again.
