### ISSUE TITLE
Read Group missing in ALL STAR BAM output files

### ISSUE THREAD

**Issue by anandksrao** [alexdobin/STAR#944]
Hi Alex!

Greetings,

I am using STAR Version 2.7.2a, with the goal of 2-pass mapping of RNA-Seq SE reads, with max. length = 100bp, They've been fully pre-processed for adapter, quality, poly-X, N content etc.

**Other Input files:**
Genome File = At this [link](https://medicago.toulouse.inra.fr/MtrunA17r5.0-ANR/downloads/1.7/MtrunA17r5.0-ANR-EGN-r1.7.fastaFiles.zip) 
Genome Filename = `MtrunA17r5.0-20161119-ANR.fasta`

Annotation GTF File = At this [link](https://medicago.toulouse.inra.fr/MtrunA17r5.0-ANR/downloads/1.7/MtrunA17r5.0-ANR-EGN-r1.7.gtf.zip) 
Annotation Filename = `MtrunA17r5.0-ANR-EGN-r1.7.gtf`

**STEP 1 - GENOME INDEX BUILD**
```
STAR --runThreadN 6 --runMode genomeGenerate --genomeDir . --runDirPerm All_RWX \
--genomeFastaFiles MtrunA17r5.0-20161119-ANR.fasta --genomeChrBinNbits 18 \
--sjdbGTFfile MtrunA17r5.0-ANR-EGN-r1.7.gtf --sjdbOverhang 99 --genomeSAindexNbases 13
```

**STEP 2 - GENOME MAPPING PASS 1**
```
STAR --outFilterMismatchNmax 2 --outFilterMismatchNoverLmax 0.065 --alignEndsType EndToEnd \
--alignIntronMin 40 --alignIntronMax 15000 \
--alignSJDBoverhangMin 3 --alignSJoverhangMin 5  --sjdbOverhang 99 --outFilterType BySJout \
--outReadsUnmapped Fastx --runThreadN 2 \
--outBAMsortingThreadN 2 --outSAMtype BAM SortedByCoordinate --outBAMcompression 10 \
--outFileNamePrefix $PREFIX --readFilesCommand zcat \
--readFilesIn $IN --sjdbGTFfile $GTF_ANNOTATION_FILE --genomeDir $GENOME_INDEX_DIR
```

**STEP 3 - COLLECT AND CONCATENATE NEW SPLICE JUNCTIONS**
_pending_

**STEP 4 - GENOME INDEX RE-BUILD**
_pending_

**STEP 5 - GENOME MAPPING PASS 2**
_pending_

**FASTQ INPUT VALIDATION**
```
fastqvalidator/2017-07
Finished processing IN.fq.gz with _xx_ lines containing _yy_ sequences.
There were a total of 0 errors.
Returning: 0 : FASTQ_SUCCESS
```

**PROBLEM**
For **each** output BAM file generated by 1st pass STAR mapping, for validation, 
I employed `PicardTools`' `ValidateSamFile`, as follows:
```
java -jar picard.jar ValidateSamFile I=$IN MODE=VERBOSE > $OUT
```
Error messages start with the line:
```
ERROR: Read groups is empty
```
followed by 100 lines of 
```
WARNING: Read name HTKZQN1:298:C03CTACXX:6:2302:9397:15424, A record is missing a read group
WARNING: Record 1, Read name HTKZQN1:298:C03CTACXX:6:2302:9397:15424, NM tag (nucleotide differences) is missing
.
.
.
WARNING: Read name HWI-ST797:117:D091UACXX:4:2302:2932:91003, A record is missing a read group
Maximum output of [100] errors reached.
```

**SOLUTION**
Should I manually specify the read group for EACH of my input FASTQ files using instructions at:
https://broadinstitute.github.io/picard/command-line-overview.html#AddOrReplaceReadGroups ?

**QUESTIONS**
**1.** As a newbie to FASTQ, STAR, mapping, etc., my naive question is WHY are read groups missing?
**2.** I thought the FASTQ headers DO contain information about machine, flow cell, lane etc. But, is there a problem with my FASTQ files, despite no errors returned by FastQValidator? 
**3.** Can header replacement of FASTQ input files be a simpler fix than replacing read group info in the BAM output files?
**4.** Is there a problem in my syntax (optional flag values) for genome indexing or mapping steps or both?

Please, could you help me figure out where the problem is arising, and how to fix this? Thank you!

**Comment by alexdobin** [comment]
Hi @anandksrao 

1. Read groups do not have to be present in the SAM/BAM file, and STAR does not add them by default.
Picard requires them by default, which causes the error you see. I believe you can suppress Picard errors with `IGNORE={MISSING_READ_GROUP,RECORD_MISSING_READ_GROUP}` - please check the Picard manual for more options.  
If you want to include read groups in STAR BAMs, you can use `--outSAMattrRGline ID:my-read-group` option.  
You can also add RG tags to existing BAM with `samtools addreplacerg`.

2. FASTQ files do not have headers, unfortunately. :)
3.

4. Your parameters look good. Since you used GTF file at the genome generation step, you do not need  to use at mapping - remove the `--sjdbOverhang 99 --sjdbGTFfile ...` from STEP 2

Cheers
Alex

**Comment by anandksrao** [comment]
Thank you for your quick response. And for suggestions to eliminate redundant option flags in my STAR mapping runs, already included in the STAR indexing step. 

The bug I was seeing ended up being a GTF file format incompatibility (just a few lines) with featureCounts, and nothing to do with my STAR use. 

Your reply helped me get to the solution faster, so I appreciate your help. Once again, thank you!
