### ISSUE TITLE
STAR index doesn't finish

### ISSUE THREAD

**Issue by Smriti1990** [alexdobin/STAR#946]
Hi, I am trying to do 2 pass star alignment. When I am regenerating the genome I am getting following:
Writing 8 bytes into  path/indexes/SAindex ; empty space on disk = 30886970327040 bytes ... done
Writing 120 bytes into path/indexes/SAindex ; empty space on disk = 30886970327040 bytes ... done
Writing 1565873491 bytes into path/indexes/SAindex ; empty space on disk = 30886970327040 bytes ... done
Jun 16 20:42:40 ..... finished successfully
DONE: Genome generation, EXITING

Is it complete or not because I am getting sjdbList.out.tab and sjdbInfo.txt files. And there are no errors in log file. Thanks for your help

**Comment by alexdobin** [comment]
Hi @Smriti1990 

The "DONE: Genome generation, EXITING" at the end of the Log.out file means that the run was completed successfully. Are you saying that you are not getting sjdb* files? What is your STAR command?

Cheers
Alex

**Comment by Smriti1990** [comment]
Hi Alex , Thank you so much for you help. Those files are getting generated.
Command was
STAR --runMode genomeGenerate --genomeDir  path/indexes --genomeFastaFiles  hg19.fasta --sjdbFileChrStartEnd  path/OutTabs/*.out.tab --sjdbOverhang 75 --limitSjdbInsertNsj 1210875 --runThreadN 24.

Thanks again. It is working
