### ISSUE TITLE
Compiling problem with 2.7.5a

### ISSUE THREAD

**Issue by yanningzuo** [alexdobin/STAR#948]
Dear Dr. Dobin,

I was compiling version 2.7.5a under Linux and failed. Here are the error messages:

Genome_genomeLoad.cpp: In member function 'void Genome::genomeLoad()':
Genome_genomeLoad.cpp:152:35: error: 'log' was not declared in this scope
         GstrandBit = (uint) floor(log(nGenome)/log(2))+1;
                                   ^~~
Genome_genomeLoad.cpp:152:35: note: suggested alternative: 'long'
         GstrandBit = (uint) floor(log(nGenome)/log(2))+1;
                                   ^~~
                                   long
Genome_genomeLoad.cpp:152:29: error: 'floor' was not declared in this scope
         GstrandBit = (uint) floor(log(nGenome)/log(2))+1;
                             ^~~~~
Genome_genomeLoad.cpp:152:29: note: suggested alternative: 'flock'
         GstrandBit = (uint) floor(log(nGenome)/log(2))+1;
                             ^~~~~
                             flock
Genome_genomeLoad.cpp:434:39: error: 'log2' was not declared in this scope
         P.winBinNbits = (uint) floor( log2( max( max(4LLU,P.alignIntronMax), (P.alignMatesGapMax==0 ? 1000LLU : P.alignMatesGapMax) ) /4 ) + 0.5);
                                       ^~~~
Genome_genomeLoad.cpp:434:39: note: suggested alternative: 'long'
         P.winBinNbits = (uint) floor( log2( max( max(4LLU,P.alignIntronMax), (P.alignMatesGapMax==0 ? 1000LLU : P.alignMatesGapMax) ) /4 ) + 0.5);
                                       ^~~~
                                       long
Genome_genomeLoad.cpp:434:32: error: 'floor' was not declared in this scope
         P.winBinNbits = (uint) floor( log2( max( max(4LLU,P.alignIntronMax), (P.alignMatesGapMax==0 ? 1000LLU : P.alignMatesGapMax) ) /4 ) + 0.5);
                                ^~~~~
Genome_genomeLoad.cpp:434:32: note: suggested alternative: 'flock'
         P.winBinNbits = (uint) floor( log2( max( max(4LLU,P.alignIntronMax), (P.alignMatesGapMax==0 ? 1000LLU : P.alignMatesGapMax) ) /4 ) + 0.5);
                                ^~~~~
                                flock
make: *** [Makefile:78: Genome_genomeLoad.o] Error 1

I guess something is missing in the source code of Genome_genomeLoad.cpp. Could you help me with this? Thank you in advance!

Best,

Yanning

**Comment by alexdobin** [comment]
Hi Yanning,

please try a patch I just pushed to GitHub master, hopefully it will solve the problem.

Cheers
Alex

**Comment by yanningzuo** [comment]
Hi Alex,

Thank you for your prompt response! I just compiled again and here's one more minor issue for SuperTranscriptome.cpp:

SuperTranscriptome.cpp: In member function 'void SuperTranscriptome::load(char*, std::vector<long long unsigned int>&, std::vector<long long unsigned int>&)':
SuperTranscriptome.cpp:51:41: error: cannot convert 'std::basic_istream<char>::__istream_type {aka std::basic_istream<char>}' to 'bool' in initialization
         bool inGood = (superTrSJ >> sutr);
                                         ^
make: *** [Makefile:78: SuperTranscriptome.o] Error 1

Thanks again!

Best,

Yanning

**Comment by alexdobin** [comment]
Hi Yanning.

please try the next patch.
Which gcc version are you using? I do not see these errors with my standard 4.8.5, nor with 7.3.1 , nor with 8.3.1 .

Thanks!
Alex

**Comment by yanningzuo** [comment]
Hi Alex,

This time the compiling succeeded. Thank you! I am using gcc version 4.4.7.

Best,

Yanning

**Comment by yanningzuo** [comment]
And when I was loading STAR, gcc 4.9.3 got loaded

**Comment by alexdobin** [comment]
Hi Yanning,

gcc 4.4.7 is too old, I would recommend switching to 4.8.x or later.
At some point, I will need to jump to even later gcc, probably 8.x.x, to allow for c++14,17,... extensions.

Cheers
Alex
