### ISSUE TITLE
STAR indexing error

### ISSUE THREAD

**Issue by dahun73** [alexdobin/STAR#951]
Hello, Alex!

I have a problem with indexing reference genome. Actually, I tried first to index repeat element sequence from UCSC genome browser to remove repeat elements. 
the fasta files looks like:
![image](https://user-images.githubusercontent.com/52641420/85370001-09460a00-b569-11ea-9e2c-35eedc5c8257.png)

Also, my command is :
STAR --runMode genomeGenerate --runThreadN 8 --genomeDir ~/BioResource/Reference/mm10.repeat.seq --genomeFastaFiles ~/BioResource/Reference/mm10.repeat.seq.fa

Finally, error message is : 
Jun 23 15:44:22 ..... started STAR run
Jun 23 15:44:22 ... starting to generate Genome files
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped).

What is the problem you think..?

Thanks in advance!

Dahun.

**Comment by alexdobin** [comment]
Hi Dahun,

how many "scaffolds" do you have in the FASTA file? If the number is too large, you may need to scale genome parameters, as explained in the STAR manual section 2.2.6.

Cheers
Alex

**Comment by dahun73** [comment]
Hi Alex,

Thank you for help in advance.
Actually, what is the exact meaning of "scaffolds" in FASTA?
Does it mean total header? If so, the result is here.

$ grep '>' mm10.gencode.rmRep.fa | wc -l
1851152

Frankly, I made custom FASTA using "bedtools getfasta". Because I need to map on the repeat element sequence to remove repeat sequence and any other rRNA, tRNAs, I have to make custom FASTA. But It is too large size comparing basic mm10 FASTA.

I'll check the manual! Thanks!

Dahun.

**Comment by alexdobin** [comment]
Hi Dahun,

you calculation is right, by scaffolds  meant the number of different sequences in the file. 2M is a very large number.
I would not recommend mapping to just the repeat sequences
Why not map to the whole genome, and the filter out alignments that map to repeat regions?

Cheers
Alex
Alex

**Comment by dahun73** [comment]
Thanks Alex!!

Really? Is it possible to map like that? I haven't know until now....
Actually, I tried to map on reference fasta that I made using UCSC table browser. Indexing was well done. But... when running mapping, it was running all day not to come out any error messages...haha...
Is it difficult to filter out repeat region aligned read? Would you let me know how to do that?
I'm sorry for bothering.


Dahun.

**Comment by alexdobin** [comment]
Hi Dahun,

mapping to full genome is typically the best option. The repeats in the genome only matter for reads that could map to them, which are typically few. To filter the reads that map to repeat  (or other unwelcome) regions, you can use the `bedtools intersect` command.

Cheers
Alex

**Comment by dahun73** [comment]
Hello Alex,

Thank you for reply. I will try use 'bedtools intersect'. :)
It's really helpful!

Have a good weekend!


Dahun.
