### ISSUE TITLE
could not open genome file

### ISSUE THREAD

**Issue by ayusyarif** [alexdobin/STAR#958]
Hi Alex,

I'm a super newbie to STAR. I've got an issue when running the alignment process even though I already double check my script. 
I have generated the genome index and put it into --genomeDir. However, the alignment gave me an error. 

the steps that I've taken are as follows:
#!/bin/bash -l

# Batch script to run a serial job under SGE.

# Request ten minutes of wallclock time (format hours:minutes:seconds).
#$ -l h_rt=02:00:0

# Request 1 gigabyte of RAM (must be an integer followed by M, G, or T)
#$ -l mem=40G

# Request 15 gigabyte of TMPDIR space (default is 10 GB)
#$ -l tmpfs=50G

# Set the name of the job.
#$ -N Genome_align

# Set the working directory to somewhere in your scratch space.  
#  This is a necessary step as compute nodes cannot write to $HOME.
# Replace "<your_UCL_id>" with your UCL user ID.
#$ -wd /home/rmhaahs/Scratch/alignment

# Your work should be done in $TMPDIR 
cd $TMPDIR

module load gcc-libs
module load star/2.5.2a

STAR --runThreadN 4 --genomeDir /home/rmhaahs/Scratch --readFilesIn /home/rmhaahs/Scratch/A_R1.fastq --outSAMtype BAM SortedByCoordinate

here's the output says:
[rmhaahs@login13 alignment]$ more ~/Scratch/alignment/Genome_align.e4003524 

EXITING because of FATAL ERROR: could not open genome file /home/rmhaahs/Scratch
/Genome

SOLUTION: check that the path to genome files, specified in --genomeDir is corre
ct and the files are present, and have user read permsissions

Jun 29 08:03:29 ...... FATAL ERROR, exiting

p.s in the /rmhaahs/Scratch there are already files :
alignment          exonGeTrInfo.tab  genomealign.rtf       output
A_R1.fastq         exonInfo.tab      genomealign.txt       Script
Ayuscript          geneInfo.tab      genome.fa             Script101
chrLength.txt      genelist.rtf      genomelist.rtf        _STARtmp
chrNameLength.txt  genescript        genomeParameters.txt  transcriptInfo.tab
chrName.txt        genes.gtf         Log.out
chrStart.txt       GENES.rtf         myscriptgene
[rmhaahs@login13 Scratch]$ 

kindly find the log.out as attached.

many thanks!

[Log.out.txt.zip](https://github.com/alexdobin/STAR/files/4844281/Log.out.txt.zip)

**Comment by ayusyarif** [comment]
hi alex, 
I've tried to run again my jobscript using another genome fasta file. Unfortunately, it generated an error result again.

[rmhaahs@login13 reference]$ more ~/reference/genome_index.e4009456

EXITING because of INPUT ERROR: could not open genomeFastaFile: /home/rmhaahs/re
ference/hg38.genome.fa

Jun 30 08:02:37 ...... FATAL ERROR, exiting

is this due to the genome file? do you think the genome fasta file is corrupt?

**Comment by alexdobin** [comment]
Hi @ayusyarif 

the run which produced the Log.out that you attached did not complete. It generated a lot of warnings that the chromosomes in GTF file cannot be found in the FASTA file. Your genome.fa contains only 7 chromosomes, it's probably truncated.

In the second case, it could not find the `/home/rmhaahs/reference/hg38.genome.fa` file, so you need to make sure it's available on the node you are running it on.

Cheers
Alex

**Comment by ayusyarif** [comment]
Hi @alexdobin 

thank you very much for the information. 
I successfully run that by re-download the genome file. 
and also for the 2nd scenario, I put the wrong name in the path file. 

Best
Ayu
