### ISSUE TITLE
diploid genome and transcriptome annotation,mapping speed slow

### ISSUE THREAD

**Issue by john321123** [alexdobin/STAR#96]
Dear alex
 I created a C57Bl/6J, PWK diploid genome and transcriptome annotation,
mapping speed is so slow , Unmapped short or other is  high.

Can you give me some suggestions on improving the speed ?

if set: --seedPerWindowNmax 10 ,25 as fellow
=============
 --seedPerWindowNmax 10
--sjdbOverhang                  default
##### Final user re-defined parameters-----------------:
runThreadN                        4
genomeDir                         /lustre/user/kehao/fx/data/index/
readFilesIn                       /lustre/user/kehao/fx/clean_data/MR962_1.clean.fq.gz   /lustre/user/kehao/fx/clean_data/MR962_2.clean.fq.gz   
readFilesCommand                  zcat   
outFileNamePrefix                 /lustre/user/kehao/fx/result/MR962
outSAMtype                        BAM   SortedByCoordinate   
outSAMstrandField                 intronMotif
outFilterMismatchNmax             1
seedPerWindowNmax                 10
sjdbGTFfile                       /lustre/user/kehao/fx/data/gencode.vM7.C57BL6NJ_PWKPhJ.annotation.gtf
quantMode                         TranscriptomeSAM   GeneCounts   
twopassMode                       Basic

-------------------------------
##### Final effective command line:
STAR   --runThreadN 4   --genomeDir /lustre/user/kehao/fx/data/index/   --readFilesIn /lustre/user/kehao/fx/clean_data/MR962_1.clean.fq.gz   /lustre/user/kehao/fx/clean_data/MR962_2.clean.fq.gz      --readFilesCommand zcat      --outFileNamePrefix /lustre/user/kehao/fx/result/MR962   --outSAMtype BAM   SortedByCoordinate      --outSAMstrandField intronMotif   --outFilterMismatchNmax 1   --seedPerWindowNmax 10   --sjdbGTFfile /lustre/user/kehao/fx/data/gencode.vM7.C57BL6NJ_PWKPhJ.annotation.gtf   --quantMode TranscriptomeSAM   GeneCounts      --twopassMode Basic
######
           Time    Speed        Read     Read   Mapped   Mapped   Mapped   Mapped Unmapped Unmapped Unmapped Unmapped
                    M/hr      number   length   unique   length   MMrate    multi   multi+       MM    short    other
Jan 07 18:10:54 Started 1st pass mapping
Jan 07 18:11:14     15.4       85474      300    22.8%    294.2     0.1%    44.0%     0.0%     0.0%     4.6%    28.5%
Jan 07 18:12:32     53.3     1451955      300    22.9%    294.6     0.1%    44.5%     0.0%     0.0%     4.3%    28.4%
==============================================================================
--seedPerWindowNmax 25
--sjdbOverhang                  149
###### All USER parameters from Command Line:
runThreadN                    4     ~RE-DEFINED
genomeDir                     /lustre/user/kehao/fx/data/index/     ~RE-DEFINED
readFilesIn                   /lustre/user/kehao/fx/clean_data/MR1000_1.clean.fq.gz   /lustre/user/kehao/fx/clean_data/MR1000_2.clean.fq.gz        ~RE-DEFINED
readFilesCommand              zcat        ~RE-DEFINED
sjdbGTFfile                   /lustre/user/kehao/fx/data/gencode.vM7.C57BL6NJ_PWKPhJ.annotation.gtf     ~RE-DEFINED
sjdbOverhang                  149     ~RE-DEFINED
outSAMstrandField             intronMotif     ~RE-DEFINED
outSAMtype                    BAM   SortedByCoordinate        ~RE-DEFINED
quantMode                     TranscriptomeSAM   GeneCounts        ~RE-DEFINED
twopassMode                   Basic     ~RE-DEFINED
seedPerWindowNmax             25     ~RE-DEFINED
outFilterMismatchNmax         1     ~RE-DEFINED
outFileNamePrefix             /lustre/user/kehao/fx/result/MR1000     ~RE-DEFINED
##### Final user re-defined parameters-----------------:
runThreadN                        4
genomeDir                         /lustre/user/kehao/fx/data/index/
readFilesIn                       /lustre/user/kehao/fx/clean_data/MR1000_1.clean.fq.gz   /lustre/user/kehao/fx/clean_data/MR1000_2.clean.fq.gz   
readFilesCommand                  zcat   
outFileNamePrefix                 /lustre/user/kehao/fx/result/MR1000
outSAMtype                        BAM   SortedByCoordinate   
outSAMstrandField                 intronMotif
outFilterMismatchNmax             1
seedPerWindowNmax                 25
sjdbGTFfile                       /lustre/user/kehao/fx/data/gencode.vM7.C57BL6NJ_PWKPhJ.annotation.gtf
sjdbOverhang                      149
quantMode                         TranscriptomeSAM   GeneCounts   
twopassMode                       Basic
######
           Time    Speed        Read     Read   Mapped   Mapped   Mapped   Mapped Unmapped Unmapped Unmapped Unmapped
                    M/hr      number   length   unique   length   MMrate    multi   multi+       MM    short    other
Jan 11 00:54:22 Started 1st pass mapping
Jan 11 01:24:05      0.2       85434      300    28.9%    294.8     0.1%    50.0%     0.0%     0.0%    17.5%     3.6%
Jan 11 01:25:06      0.5      256342      300    28.8%    294.3     0.1%    49.9%     0.0%     0.0%    17.8%     3.6%
Jan 11 01:57:32      0.4      427586      300    28.7%    294.4     0.1%    50.0%     0.0%     0.0%    17.7%     3.6%
Jan 11 01:59:22      0.6      684010      300    28.7%    294.6     0.1%    50.1%     0.0%     0.0%    17.6%     3.6%
==============================================================================

**Comment by alexdobin** [comment]
Hi john321123,

if you have poor mappability, it may also slow mapping speed significantly, as STAR will be trying hard to map unmappable reads. Here are a few suggestions on how to deal with low mappability:
https://groups.google.com/d/msg/rna-star/cvaIAgpCuXQ/Yf6JsPOvCAAJ

Cheers
Alex
