### ISSUE TITLE
STAR does not produce ReadsPerGene with GTF

### ISSUE THREAD

**Issue by sidorov-si** [alexdobin/STAR#969]
Dear Alex,

I ran STAR `2.7.5a` on a whole human chr20 with `--quantMode GeneCounts` using a GTF file for the whole chr20. It mapped reads but did not produce `ReadsPerGene.out.tab` file. Please see the log: [Sample1.Log.out.gz](https://github.com/alexdobin/STAR/files/4927214/Sample1.Log.out.gz).

Here is an excerpt of the GTF file: [Homo_sapiens.GRCh38.100.chr20.excerpt.gtf.gz](https://github.com/alexdobin/STAR/files/4927247/Homo_sapiens.GRCh38.100.chr20.excerpt.gtf.gz).

Could you please advise me what is wrong with this run?

**Comment by alexdobin** [comment]
Hi Slava,

the file ReadsPerGene.out.tab should have been produced, independent of whether GTF file is correct.
If you cannot find it in the output directory, please try to 
1. Use precompiled STAR executables: bin/Linux_x86_64_static/STAR  and bin/Linux_x86_64/STAR
2. If neither of them solves the problem, please compile with make in the source/ directory.

Cheers
Alex

**Comment by sidorov-si** [comment]
Hi Alex,

I'm sorry, it was my bad, -- it actually generates the `ReadsPerGene.out.tab` file! I just failed to copy it properly in a publish dir using Nextflow.

Sorry for bothering you,
     Slava
