### ISSUE TITLE
Value of --genomeSAindexNbases for small genomes

### ISSUE THREAD

**Issue by sidorov-si** [alexdobin/STAR#972]
Hi Alex,

This is most probably not very important, but I decided to ask, as I'm a bit confused.

The [STAR v2.7.5a manual](https://github.com/alexdobin/STAR/blob/master/doc/STARmanual.pdf), section 2.2.5, says that one needs to downscale the `--genomeSAindexNbases` parameter for small genomes (for example, for a 1 Mb-genome it should be 9, and for 100 Kb-genome it should be 7). These example values indeed follow from the general formula in the same section if I take the closest whole number.

Now I'm trying to build an index for a sequence of size 64,487,424 (chr20 in Ensembl). I calculated the `genomeSAindexNbases` according to the general formula, took the closest whole number and got 12: [https://www.wolframalpha.com/input/?i=min%2814%2C+log2%2864487424%29+%2F+2+-+1%29](https://www.wolframalpha.com/input/?i=min%2814%2C+log2%2864487424%29+%2F+2+-+1%29) .

However, when I ran STAR with `--genomeSAindexNbases 12` on this sequence, I got a warning:

`Jul 19 17:06:15 WARNING: --genomeSAindexNbases 12 is too large for the genome size=64487424, which may cause seg-fault at the mapping step. Re-run genome generation with recommended --genomeSAindexNbases 11`

which means, that I needed to take the floor (11) from the value I've got out of the formula (~11.97), not the closest whole number (12).

Am I missing anything in the docs?

Thank you!
     Slava

**Comment by alexdobin** [comment]
Hi Slava,

thanks for pointing it out, I will fix the examples in the manual, rounding down is a bit safer.
This scaling is approximate, and onward from 2.7.5a too large values should not cause the seg-fault, though the scaling is still recommended.

Cheers
Alex

**Comment by sidorov-si** [comment]
Thank you very much for the clarification, Alex!

**Comment by yezi0721** [comment]
I also get the same problem. The number I calculate is 13 https://www.wolframalpha.com/input/?i=min%2814%2C+log2%28277411381%29+%2F+2+-+1%29 , but it recommend 12.
 /lustre/haven/proj/UTK0138/software/STAR-2.7.6a/bin/Linux_x86_64/STAR --runMode genomeGenerate --genomeDir STAR_idx --genomeFastaFiles Ppersica_298_v2.0.fa --runThreadN 1 --genomeSAindexNbases 13 --sjdbGTFfile Ppersica_298_v2.1.gene_exons.gff3 --sjdbGTFtagExonParentTranscript Parent --sjdbOverhang 50
Nov 16 16:19:17 ..... started STAR run
Nov 16 16:19:17 ... starting to generate Genome files
Nov 16 16:19:24 ..... processing annotations GTF
!!!!! WARNING: --genomeSAindexNbases 13 is too large for the genome size=227411381, which may cause seg-fault at the mapping step. Re-run genome generation with recommended --genomeSAindexNbases 12

**Comment by alexdobin** [comment]
Hi @yezi0721 

12 or 13 will make little difference, you can use either.

Cheers
Alex
