### ISSUE TITLE
Unable to generate new genome index using STAR 2.7.5a

### ISSUE THREAD

**Issue by Mrromeros** [alexdobin/STAR#977]
Hello, I am a new user of STAR and have been trying to generate a genome index for the mammalian genome using an HPC cluster, however, I keep having my jobs killed for exceeding the walltime allocated - no matter how much time I give it. Based on resources I have read, it seems this process should be done relatively quickly. I cannot locate the Log.out file but it appears that my program keeps getting stuck at the “starting to generate Genome files step”. I have tried on different versions of the human reference genome and edited my script multiple times, currently I tried copying that from one of the provided examples in generating a binary index, just to see if I could replicate it, but still I get the same error. 
Here is my script, and with one hotel node I get 128GB of memory, and what standard output files I could find.
![image](https://user-images.githubusercontent.com/68712667/88338762-b1c4c680-cced-11ea-9c7c-ea108e6b1175.png)
![image](https://user-images.githubusercontent.com/68712667/88338428-2ea37080-cced-11ea-9d55-8a6b12b5d0f0.png)
![image](https://user-images.githubusercontent.com/68712667/88338474-424ed700-cced-11ea-8aa0-8aa9fd5e2ebb.png)

What can I do to fix this issue? I have been stuck on this for sometime so any help would be greatly appreciated!

**Comment by Mrromeros** [comment]
Update, I have found the Log.out file but it does not contain much more information, simply stating it is stuck at the "starting to generate Genome files" part.

**Comment by alexdobin** [comment]
Hi @Mrromeros 

I think you need to request RAM from PBS with something like
#PBS -l mem=35000MB
You probably need to consult with the cluster sysadmin on how to properly set the RAM requirements.

If this does not help, please send me the Log.out file.

Cheers
Alex

**Comment by Mrromeros** [comment]
Hello Alex,
I asked the sysadmin and they informed me that with each core one gets 5GB, so with my request of 1 node and 24ppn I should have access to 120GB of memory. I ran it again with this specified but still was stuck at the same place.
I have attached my Log.out file below which has the same specifications as before except now it has specified for more memory.
[Log.out.txt](https://github.com/alexdobin/STAR/files/4976166/Log.out.txt)

**Comment by alexdobin** [comment]
Hi @Mrromeros 

it seems to be stuck at the point where it reads the fast files. What's the output of 
`ls -l /home/mrr014/rnaSeq/genome/GRCh38.dna.primary_assembly.fa`
To check that the nodes can see this files, please add this command to the PBS script before the STAR command.

Also, please check permissions for the output directory:  `/oasis/tscc/scratch/mrr014/output/STAR`
For some reason, it could not move the Log.out file into that directory.

Cheers
Alex

**Comment by Mrromeros** [comment]
Ah, I see I incorrectly named the FASTA file, it should have been "Homo_sapiens.GRCh38.dna.primary_assembly.fa" - after renaming it it seemed to work!
Thanks for your help!
