### ISSUE TITLE
STAR becomes very slow with fragmented assemblies

### ISSUE THREAD

**Issue by jesgomez** [alexdobin/STAR#98]
Dear Alex, 
I am trying to run STAR on a large and quite fragmented genome (with ~50,000 scaffolds). Unfortunately, I can't even generate the index, so far it has been running for 2 days and it has not finished... Could you give me some tips on which parameters or options should I use when trying to map genomes with lots of scaffolds? The command I have been running is: 

STAR --runMode genomeGenerate --genomeDir genome/ --genomeFastaFiles assembly.fa --limitGenomeGenerateRAM 60000000000 --genomeChrBinNbits 16 --outTmpDir $TMPDIR/_STAR

Before adding the limitGenomeGenerateRAM and the genomeChrBinNbits it gave memory problems, but now it is extremely slow. 

Thank you.

**Comment by alexdobin** [comment]
Hi @jesgomez

please send me the Log.out file of the failed run.

Cheers
Alex
