### ISSUE TITLE
Reproduce Chimeric.out.sam without --chimOutType SeparateSAMold?

### ISSUE THREAD

**Issue by aubreybailey** [alexdobin/STAR#981]
The STAR manual says that the --chimOutType SeparateSAMold flag will be deprecated in the future. 

I'm glad you're decoupling this, in favor of the proper SAM specification, but for compatibility purposes I'd like to still produce this file for the foreseeable future.

Without reading the code for this section, I'm unclear on what set of flags and tags are used to generate the current Chimeric.out.sam. I think it's a bit more complicated than  ```samtools view -f 2048``` or ```samtools view -h my.bam | grep SA```, but I assume there is some near equivalent?

Thanks!

**Comment by alexdobin** [comment]
Hi Aubrey,

you can add 'ch' to the --outSAMattributes list, and it will add 'ch' tag to all parts of all chimeric reads from the BAM file - this would make it easier to extract all chimeric alignments. The formatting, however, will be different, as BAM output follows standard SAM specifications for chimeric alignments, while old output simply outputs all pieces as if they were multimappers.

Cheers
Alex

**Comment by aubreybailey** [comment]
That's perfect, and exactly what I needed. 
THANK YOU!
