### ISSUE TITLE
"Check if you have enough RAM" even with sufficient RAM

### ISSUE THREAD

**Issue by pchiang5** [alexdobin/STAR#984]
Hi,

When I tried starsolo with the following code with WSL2:
```


STAR --runThreadN 1 \
--genomeSAsparseD 2 \
--genomeDir '/mnt/m/My Drive/tools/star/index' \
--sjdbGTFfile 'GRChm38.99.chr.gtf' \
--readFilesIn R1_50.gz BCUMI.gz \
--soloFeatures Gene SJ GeneFull Velocyto \
--soloStrand Forward \
--soloCBstart 1 --soloCBlen 12 --soloUMIstart 13 --soloUMIlen 12 \
--soloType CB_UMI_Simple  \
--soloCBwhitelist whitelis.csv 


	
```

it showed the following error message:

> 
> Jul 31 16:29:10 ..... started STAR run
> Jul 31 16:29:10 ..... loading genome
> 
> EXITING: fatal error trying to allocate genome arrays, exception thrown: std::bad_alloc
> Possible cause 1: not enough RAM. Check if you have enough RAM 57701241034 bytes
> Possible cause 2: not enough virtual memory allowed with ulimit. SOLUTION: run ulimit -v 57701241034

However, I have 256Gb RAM installed and the genome generation worked fine without the sparse option.

the ulimit -a message:

> 
> core file size          (blocks, -c) 0
> data seg size           (kbytes, -d) unlimited
> scheduling priority             (-e) 0
> file size               (blocks, -f) unlimited
> pending signals                 (-i) 31806
> max locked memory       (kbytes, -l) 64
> max memory size         (kbytes, -m) unlimited
> open files                      (-n) 99999
> pipe size            (512 bytes, -p) 8
> POSIX message queues     (bytes, -q) 819200
> real-time priority              (-r) 0
> stack size              (kbytes, -s) 8192
> cpu time               (seconds, -t) unlimited
> max user processes              (-u) 31806
> virtual memory          (kbytes, -v) 57701241034
> file locks                      (-x) unlimited

What might be the problem?  Thank you.

**Comment by alexdobin** [comment]
Hi @pchiang5 

please send me the Log.out file, and also output of 
`free -m` command.

Cheers
Alex

**Comment by pchiang5** [comment]
Hi Alex,

The `free -m` showed ~8GB instead of expected 256GB. I found that was because WSL2 (win10 20180) limits the RAM to either 50% or 8GB in the VM. Everything is fine after I configured the .wslconfig with `memory=256GB` now. Thank you.
