### ISSUE TITLE
make: *** [Makefile:78: Genome_genomeLoad.o] Error 1   

### ISSUE THREAD

**Issue by ctlshcxy** [alexdobin/STAR#985]
I met this problem after running 'make STAR', the specific information was as follow: 

g++ -c   -O3 -std=c++11 -fopenmp -D'COMPILATION_TIME_PLACE="Sat Aug 1 17:40:18 CST 2020 :/mnt/d/STAR/source"' -pipe -Wall -Wextra Genome_genomeLoad.cpp                                                                                         
Genome_genomeLoad.cpp: In member function ‘void Genome::genomeLoad()’:                                                  Genome_genomeLoad.cpp:152:35: error: ‘log’ was not declared in this scope; did you mean ‘long’?                           
152 |         GstrandBit = (uint) floor(log(nGenome)/log(2))+1;                                                            
|                                   ^~~                                                                                 
|                                   long                                                                          
Genome_genomeLoad.cpp:152:29: error: ‘floor’ was not declared in this scope                                               
152 |         GstrandBit = (uint) floor(log(nGenome)/log(2))+1;                                                             
|                             ^~~~~                                                                               
Genome_genomeLoad.cpp:434:39: error: ‘log2’ was not declared in this scope                                                
434 |         P.winBinNbits = (uint) floor( log2( max( max(4LLU,P.alignIntronMax), (P.alignMatesGapMax==0 ? 1000LLU : P.alignMatesGapMax) ) /4 ) + 0.5);                                                                                            
|                                       ^~~~                                                                      
Genome_genomeLoad.cpp:434:32: error: ‘floor’ was not declared in this scope                                               
434 |         P.winBinNbits = (uint) floor( log2( max( max(4LLU,P.alignIntronMax), (P.alignMatesGapMax==0 ? 1000LLU : P.alignMatesGapMax) ) /4 ) + 0.5);                                                                                            
|                                ^~~~~                                                                            
make: *** [Makefile:78: Genome_genomeLoad.o] Error 1

**Comment by alexdobin** [comment]
Hi @ctlshcxy 

this issue was fixed in the [2.7.5b](https://github.com/alexdobin/STAR/releases/tag/2.7.5b) that I just released, please try it out.

Cheers
Alex

**Comment by ctlshcxy** [comment]
> Hi @ctlshcxy
> 
> this issue was fixed in the [2.7.5b](https://github.com/alexdobin/STAR/releases/tag/2.7.5b) that I just released, please try it out.
> 
> Cheers
> Alex

Great, that helped a lot.
