### ISSUE TITLE
`inserting junctions into the genome indices` causes run to terminate

### ISSUE THREAD

**Issue by etaagen** [alexdobin/STAR#991]
Hi all,
I am having a problem indexing the wheat genome with low confidence gene annotation .gtf (I've successfully annotated with the high confidence gene annotation .gtf). The error occurs after `inserting junctions into the genome indices`, which makes me think there is an issue with the gtf file. The run stops and states:

 terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

This is the code I've used - after this failing with standard input I reduced the genomeChrBinNbits and increased the genomeSAsparseD. I am working on a server with 40 cores and 256 GB RAM.

STAR --runMode genomeGenerate --runThreadN 35 --genomeDir /workdir/et395/STAR_genome_LC --genomeFastaFiles /workdir/et395/161010_Chinese_Spring_v1.0_pseudomolecules.fasta --sjdbGTFfile /workdir/et395/IWGSC_v1.1_LC_20170706.gtf --sjdbOverhang 149 --limitGenomeGenerateRAM=38800833920 --genomeSAsparseD 3 --genomeChrBinNbits 10

The Log.out file is attached.

Here are the first 10 rows of the low confidence gene .gtf file:

chr1A   IWGSC_v1.1_201706       exon    11085   11501   .       +       .       transcript_id "TraesCS1A02G000100LC.1"; gene_id "TraesCS1A02G000100LC"; gene_name "TraesCS1A02G000100LC";
chr1A   IWGSC_v1.1_201706       exon    23483   23914   .       +       .       transcript_id "TraesCS1A02G000100LC.1"; gene_id "TraesCS1A02G000100LC"; gene_name "TraesCS1A02G000100LC";
chr1A   IWGSC_v1.1_201706       exon    40929   42819   .       +       .       transcript_id "TraesCS1A02G000100LC.1"; gene_id "TraesCS1A02G000100LC"; gene_name "TraesCS1A02G000100LC";
chr1A   IWGSC_v1.1_201706       CDS     41202   41522   .       +       0       transcript_id "TraesCS1A02G000100LC.1"; gene_id "TraesCS1A02G000100LC"; gene_name "TraesCS1A02G000100LC";
chr1A   IWGSC_v1.1_201706       exon    42451   42645   .       -       .       transcript_id "TraesCS1A02G000200LC.1"; gene_id "TraesCS1A02G000200LC"; gene_name "TraesCS1A02G000200LC";
chr1A   IWGSC_v1.1_201706       CDS     42451   42645   .       -       0       transcript_id "TraesCS1A02G000200LC.1"; gene_id "TraesCS1A02G000200LC"; gene_name "TraesCS1A02G000200LC";
chr1A   IWGSC_v1.1_201706       exon    94185   94270   .       +       .       transcript_id "TraesCS1A02G000300LC.1"; gene_id "TraesCS1A02G000300LC"; gene_name "TraesCS1A02G000300LC";
chr1A   IWGSC_v1.1_201706       exon    102552  102735  .       +       .       transcript_id "TraesCS1A02G000300LC.1"; gene_id "TraesCS1A02G000300LC"; gene_name "TraesCS1A02G000300LC";
chr1A   IWGSC_v1.1_201706       exon    110792  110830  .       +       .       transcript_id "TraesCS1A02G000300LC.1"; gene_id "TraesCS1A02G000300LC"; gene_name "TraesCS1A02G000300LC";
chr1A   IWGSC_v1.1_201706       CDS     94185   94270   .       +       0       transcript_id "TraesCS1A02G000300LC.1"; gene_id "TraesCS1A02G000300LC"; gene_name "TraesCS1A02G000300LC";

Here are the first 10 rows of the high confidence gene .gtf file:
chr1A   IWGSC_v1.1_201706       exon    40098   40731   .       -       .       transcript_id "TraesCS1A02G000100.1"; gene_id "TraesCS1A02G000100"; gene_name "TraesCS1A02G000100";
chr1A   IWGSC_v1.1_201706       exon    58474   58897   .       -       .       transcript_id "TraesCS1A02G000100.1"; gene_id "TraesCS1A02G000100"; gene_name "TraesCS1A02G000100";
chr1A   IWGSC_v1.1_201706       exon    70089   70338   .       -       .       transcript_id "TraesCS1A02G000100.1"; gene_id "TraesCS1A02G000100"; gene_name "TraesCS1A02G000100";
chr1A   IWGSC_v1.1_201706       CDS     58508   58768   .       -       0       transcript_id "TraesCS1A02G000100.1"; gene_id "TraesCS1A02G000100"; gene_name "TraesCS1A02G000100";
chr1A   IWGSC_v1.1_201706       exon    70239   70650   .       +       .       transcript_id "TraesCS1A02G000200.1"; gene_id "TraesCS1A02G000200"; gene_name "TraesCS1A02G000200";
chr1A   IWGSC_v1.1_201706       exon    88242   89245   .       +       .       transcript_id "TraesCS1A02G000200.1"; gene_id "TraesCS1A02G000200"; gene_name "TraesCS1A02G000200";
chr1A   IWGSC_v1.1_201706       CDS     70239   70556   .       +       0       transcript_id "TraesCS1A02G000200.1"; gene_id "TraesCS1A02G000200"; gene_name "TraesCS1A02G000200";
chr1A   IWGSC_v1.1_201706       exon    95906   96020   .       +       .       transcript_id "TraesCS1A02G000300.1"; gene_id "TraesCS1A02G000300"; gene_name "TraesCS1A02G000300";
chr1A   IWGSC_v1.1_201706       exon    104224  104903  .       +       .       transcript_id "TraesCS1A02G000300.1"; gene_id "TraesCS1A02G000300"; gene_name "TraesCS1A02G000300";
chr1A   IWGSC_v1.1_201706       CDS     104607  104903  .       +       0       transcript_id "TraesCS1A02G000300.1"; gene_id "TraesCS1A02G000300"; gene_name "TraesCS1A02G000300";

Thanks for your assistance! 
Cheers,
Ellie 
[Log.out.txt](https://github.com/alexdobin/STAR/files/5036972/Log.out.txt)

**Comment by etaagen** [comment]
I re-ran today using the code:
STAR --runMode genomeGenerate --runThreadN 30 --genomeDir /workdir/et395/STAR_genome_LC --genomeFastaFiles /workdir/et395/161010_Chinese_Spring_v1.0_pseudomolecules.fasta --sjdbGTFfile /workdir/et395/IWGSC_v1.1_LC_20170706.gtf --sjdbOverhang 149 --limitGenomeGenerateRAM=38800833920 --genomeSAsparseD 2 

And had success! Not  exactly sure what the issue was, but perhaps I was using too many cores.

**Comment by alexdobin** [comment]
Hi Ella,

the GTF file looks fine, and nothing suspicious in the Log.out.
2.7.0f is quite old, I would recommend switching to the latest 2.7.5b release, it should be more stable.
Though you would need or re-generate the genome again.

Cheers
Alex

**Comment by etaagen** [comment]
Thanks Alex!
