### ISSUE TITLE
Segmentation fault (core dumped) 

### ISSUE THREAD

**Issue by ctlshcxy** [alexdobin/STAR#997]
Aug 13 12:41:34 ..... started STAR run                                                                                  
Aug 13 12:41:34 ..... loading genome                                                                                    
Aug 13 12:44:29 ..... processing annotations GTF                                                                        
Aug 13 12:45:02 ..... inserting junctions into the genome indices                                                       
Aug 13 12:45:36 ..... started 1st pass mapping                                                                          
Aug 13 12:50:06 ..... finished 1st pass mapping                                                                         
Aug 13 12:50:07 ..... inserting junctions into the genome indices                                                       
Aug 13 12:50:51 ..... started mapping                                                                                  
Aug 13 13:10:18 ..... finished mapping                                                                                  
Aug 13 13:10:27 ..... started sorting BAM                                                                               
[W::sam_hdr_read] bgzf_check_EOF: Invalid argument                                                                      
[E::bam_hdr_read] invalid BAM binary header                                                                             
Segmentation fault (core dumped)  

Hi, do you have any idea about above problem? how to deal with it?

**Comment by alexdobin** [comment]
Hi @ctlshcxy 

please check that you have enough space on your drive, and rerun the job. If it still fails, please send me the Log.out file.

Cheers
Alex

**Comment by gilbertlsk** [comment]
Hi Alex, I have the same error. I am able to run the same command on a workstation with AMD Ryzen 9 3950, 64GB ram, 1TB NVME SSD. But the same command will not run on a server with Intel Xeon E7 4870 with 128GB ram, 4TB storage (RAID configuration).  At first both systems using the same system - 2.7.4a. Later I compiled from source on the server using the latest version 2.7.9a. Still same error - Segmentation fault (core dumped). Attached is the log.out file. What could be the problem? Thanks.
[J_0_2Log.txt](https://github.com/alexdobin/STAR/files/6499911/J_0_2Log.txt)

**Comment by alexdobin** [comment]
Hi @gilbertlsk 

if the same file maps fine on one machine but not the other, it must the the system configuration. Are both systems running under one of the standard Linux flavors?
Please try to reduce the number of threads, say to 10.
Next, try to map just a small subset of reads with --readMapNumber 100000

Cheers
Alex

**Comment by gilbertlsk** [comment]
Both running Ubuntu 20.04. I tried with 2, 30, 32, 40 threads, and got the
same error. Tried the --readMapNumber 10000, still getting the same error.

**Comment by alexdobin** [comment]
Hi Gilbert,

please try to run it with the most basic parameters, i.e. --genomeDir, --readFilesIn, --readFilesCommand.
Have you compiled STAR on the same machine you are running it on?
You can also try the pre-compiled STAR executables.

Cheers
Alex

**Comment by gilbertlsk** [comment]
I have tried using the most basic parameters. Pull the latest git and compiled from the source. Still the same error "Segmentation fault (core dumped). Have also tried the pre-compiled STAR executables, also the same error. I thought could be my files, re-uploaed, tried other reads, same error too.

**Comment by alexdobin** [comment]
Hi Gilbert,

If it's running fine with 1 thread but not with multiple threads, the problem could be multithreading library incompatibility. 
Could you try to run the static executable from the latest patch on GitHub master? It was compiled on Linux Mint, so it should be more compatible with Ubuntu.
Another option is to get STAR executable via bioconda or Docker and see if it works on your machine.

The SIMD option is only important if you are using 
```--clipAdapterType CellRanger4```
It should not affect runs without this option.

Cheers
Alex

**Comment by gilbertlsk** [comment]
I pulled the latest from github and have tried both the static and
non-static executable. Compiled from source. Tried all three options. Still
getting the same error.

**Comment by alexdobin** [comment]
Hi Gilbert,

can you try to run it on a different machine?

Cheers
Alex

**Comment by gilbertlsk** [comment]
Hi Alex, to update, I reformatted the server and installed with the Ubuntu 20.04 server edition. The mapping is working now without error. Probably not a good idea to install a Ubuntu 20.04 desktop edition on a server. Perhaps something to do with the software version used for desktop and server achitecture.  Problem solved. Thanks for the help.

**Comment by alexdobin** [comment]
Hi Gilbert,

thanks for letting me know. This issue was weird and sometimes full reinstall is the only option.

Cheers
Alex

**Comment by nayanvs** [comment]
> Hi Alex, to update, I reformatted the server and installed with the Ubuntu 20.04 server edition. The mapping is working now without error. Probably not a good idea to install a Ubuntu 20.04 desktop edition on a server. Perhaps something to do with the software version used for desktop and server achitecture. Problem solved. Thanks for the help.

@alexdobin This is very big issue. **STAR package should highlight recommended system configuration.**
