### ISSUE TITLE
Extremely low mapping speed on zebrafish genome

### ISSUE THREAD

**Issue by hreinwal** [alexdobin/STAR#998]
Dear Alex,
I am trying to align mRNAseq reads (~ 30M reads, 50bp, sr) on the [zebrafish genome](ftp://ftp.ensembl.org/pub/release-99/fasta/danio_rerio/dna/Danio_rerio.GRCz11.dna.primary_assembly.fa.gz) (~14 GB).  But the mapping speed is incredibly slow with **0.28 M/h**. I am running STAR on a Linux Mint 19 (64bit) Server with 16 CPUs and 145 GB of RAM.

I used [this GTF](ftp://ftp.ensembl.org/pub/release-99/gtf/danio_rerio/Danio_rerio.GRCz11.99.gtf.gz) and the genome mentioned above to generate the genome index files via STAR running this:
```
/usr/bin/STAR --runThreadN 14 \
    --runMode genomeGenerate \
    --genomeDir ./genome_index_files \
    --genomeFastaFiles ./*.toplevel.fa \
    --sjdbGTFfile ./*.gtf \
    --sjdbOverhang 49 \
    --genomeChrBinNbits 4 \ 
    --limitGenomeGenerateRAM=145000000000
```

After creating the index file I run this loop for my files with 14 CPUs allocated for the process limiting the mapping to the first 10M reads and changing the Window parameter as I read in #878 that this might help speed up things.
```
for SID in *.gz
do
    echo " 
    Processing sample file $SID"
	$StarPATH --runThreadN $CPUs \
    --readMapNumber 10000000 \
    --seedPerWindowNmax 25 \
    --runMode alignReads \
    --genomeDir $refgenome \
    --genomeLoad NoSharedMemory \
    --readFilesCommand gunzip -c \
    --readFilesIn $SID \
    --outFileNamePrefix ../STAR/${SID/fastq.gz/} \
    --outFilterMultimapNmax $MAXmultimap \
    --outSAMtype $OUT $TYPE \
    --limitBAMsortRAM $BAMsortRAM \
    --quantMode GeneCounts
done
```
However the mapping for the first file alone took > 24 hours. What I found interesting is that, although STAR was that slow, it never used more than 25 GB of RAM for the process, which surprised me as I thought STAR is memory intensive. Why didn't it use some of the additional available 120 RAM? 

I have attached the log files from the first completed run. I really hope someone can help me with this as I am running out of ideas right now. 
[R835.Log.progress.txt](https://github.com/alexdobin/STAR/files/5069533/R835.Log.progress.txt)
[R835.Log.final.txt](https://github.com/alexdobin/STAR/files/5069534/R835.Log.final.txt)
[R835.Log.txt](https://github.com/alexdobin/STAR/files/5069535/R835.Log.txt)

To give some insights on the sequence quality I provide some of the FastQC stats summarized via MultiQC.

![grafik](https://user-images.githubusercontent.com/23311618/90146735-b24afd00-dd81-11ea-8bd1-2479efecf24a.png)
![grafik](https://user-images.githubusercontent.com/23311618/90146306-2e911080-dd81-11ea-8258-3d0c7e42c30e.png)
![grafik](https://user-images.githubusercontent.com/23311618/90146369-41a3e080-dd81-11ea-85fe-d15e2f0938cf.png)

**Comment by alexdobin** [comment]
Hi @hreinwal 

several things at the genome generation step that may have caused slow speed:
1. --genomeChrBinNbits 4 is too small. If I read it correctly, your genome sequence is 1.5Gb and you have ~60k contigs, so you need to scale as ~ log2(1.5e9/60000)~15: --genomeChrBinNbits 15
2. You are combining cdna and dna FASTAs in --genomeFastaFiles, which mean you are mapping simultaneously to genome and transcriptome - this results in ~70% of the reads multimapping. You only need to include the dna FASTA.
3. You use wildcard for --sjdbGTFfile - however, it accepts only one file, multiple files have to be concatenated. You only have one GTF file in that directory, so it's OK. Generally I recommend against using wildcards in the parameters, as the results can be unexpected.

STAR was called be memory intensive by 2013 standards. :) 
It takes ~32GB for a human genome, less for smaller genomes.

Cheers
Alex

**Comment by hreinwal** [comment]
Dear Alex,
thank you so much! You are absolutely right. I messed up with the wildcard and the BinNbits size. I made the mistake to store the cdna in the same folder which I was planing to use for salmon for comparative purpose. Totally forgot that I will call this with the wildcard as well. I will follow your advise in the future an type out the file names to avoid that. 

I will give it a try and will let you know if it worked. 
Again thank you so much for your help and this amazing tool!

**Comment by hreinwal** [comment]
>     1. you have ~60k contigs,

May I ask you how you got this number? Cause when I check the reference genome for number of sequences with:
`grep -c "^>" Danio_rerio.GRCz11.dna.primary_assembly.fa`
I get 993.

**Comment by alexdobin** [comment]
Hi @hreinwal 

it's great you resolved it, thanks for letting me know.
The 60k contigs is from the original Log.out file, that included the cDNA transcripts - so most of the 60k are from the transcripts. If you used only the primary_assembly, the Log.out will list 993 "chromosomes".

Cheers
Alex

**Comment by hreinwal** [comment]
Ok got it :) thx!
