### ISSUE TITLE
A lot of warnigns when building a STAR Index for A.Thaliana

### ISSUE THREAD

**Issue by cyntsc** [alexdobin/STAR#999]
Dear Alex

I'm curious to know what the **Log.out file generates a lot of 'Warnigns'**, and also if this can cause alignment issues. I receive 448 notices. Digging a bit, I can see that the warnings are split across all the chromosomes. e.g:
116 Chr1 
76  Chr2
68  Chr3
70  Chr4
103 Chr5
0  Chr6
1 ChrM

**My command was:**
STAR --runThreadN 12 --runMode genomeGenerate --genomeSAsparseD 3 --genomeSAindexNbases 6 --genomeChrBinNbits 14 
--genomeDir ~/athal_STAR_idx_genome 
--genomeFastaFiles ~/Athaliana_447_TAIR10.fa 
--sjdbGTFfile ~/Araport11_GFF3_genes_transposons.201606.gtf 
--sjdbOverhang 92

**My log reports warnings like this:**
WARNING: while processing pGe.sjdbGTFfile=/data/run/cyntsc/athal_STAR_idx_genome/Araport11_GFF3_genes_transposons.201606.gtf: no gene_id for line:
Chr1    Araport11       exon    28635   28655   .       +       .       transcript_id "ath-miR838";

**And, my GTF looks like this:** 
Chr1    Araport11       transcript      3631    5899    .       +       .       transcript_id "AT1G01010.1"; gene_id "AT1G01010";
Chr1    Araport11       exon    3631    3913    .       +       .       transcript_id "AT1G01010.1"; gene_id "AT1G01010";
Chr1    Araport11       exon    3996    4276    .       +       .       transcript_id "AT1G01010.1"; gene_id "AT1G01010";

**A last questions:** 
It is planned to use this index directory to align multiple RNASeq samples, and the length varies slightly between samples. You can leave the --sjdbOverhang parameter empty or you must specify a value.

Regards, 
Cynthia

**Comment by alexdobin** [comment]
Hi Cynthia,

it looks like your GTF is missing gene_id tags for some exons. 
This does not affect mapping - it only affects counting reads per gene, if you use  ```--quantMode GeneCounts``` option.

If you leave ```--sjdbOverhang``` empty it will default to 100, which will work fine if your average read length is close to 100.

Cheers
Alex

**Comment by cyntsc** [comment]
Hi Alex

Thanks for your quick reply. Following your comment, do you know if it is common for some tags to be missing due to incomplete annotations? or is it a technical error?
Another question. Now that I have my genome index with Salmon, I plan to quantify my transcriptome with Salmon's alignment mode, is this approach fully compatible between tools? Or you could share your opinion about a recommendation for this task in order to improve the counts.

Thanks
Cynt

**Comment by alexdobin** [comment]
Hi Cynthia,

I would call it a technical error since GTF format requires gene_transcript and gene_id on each line.
However, it may have been intentional, e.g. if the people who created it did not know what gene to assign the transcript to.
You can probably fix it by adding gene_id tag equal to transcript_id tag with a prefix like "G_".

STAR --quantMode GeneCounts should produce exactly the same counts as htseq-count with default options - if you pick the corresponding strandedness column from ReadPerGene file. I have not checked this for the latest releases of the htseq-count, so if you observe some differences, let us investigate it.

Cheers
Alex

**Comment by cyntsc** [comment]
Hi Alex

Thanks for all. I will let you know if I observe something in my output files.
Cheers
CSC
